/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 * Original work Copyright (c) 2012 - 2021 Adobe Systems Incorporated. All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "GENERIC_ERROR": "(غلطی {0})",
  "NOT_FOUND_ERR": "فائل/ڈائرکٹری نہیں مل سکا.",
  "NOT_READABLE_ERR": "فائل/ڈائرکٹری پڑھا نہیں جا سکا.",
  "EXCEEDS_MAX_FILE_SIZE": "{0} MB سے بڑی فائلیں {APP_NAME} میں نہیں کھولی جا سکتیں۔",
  "NO_MODIFICATION_ALLOWED_ERR": "ہدف ڈائرکٹری میں ترمیم نہیں کی جا سکتی۔",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "اجازت آپ کو ترمیم کرنے کی اجازت نہیں دیتا.",
  "CONTENTS_MODIFIED_ERR": "فائل کو {APP_NAME} کے باہر ترمیم کیا گیا ہے۔",
  "UNSUPPORTED_ENCODING_ERR": "نامعلوم انکوڈنگ فارمیٹ",
  "ENCODE_FILE_FAILED_ERR": "{APP_NAME} فائل کے مندرجات کو خفیہ کرنے کے قابل نہیں تھا.",
  "DECODE_FILE_FAILED_ERR": "{APP_NAME} فائل کے مواد کو ڈی کوڈ کرنے کے قابل نہیں تھا.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "{APP_NAME} فی الحال UTF-16 انکوڈڈ ٹیکسٹ فائلوں کی حمایت نہیں کرتا.",
  "FILE_EXISTS_ERR": "فائل یا ڈائرکٹری پہلے سے موجود ہے.",
  "FILE": "فائل",
  "FILE_TITLE": "فائل",
  "DIRECTORY": "ڈائریکٹری",
  "DIRECTORY_TITLE": "ڈائریکٹری",
  "DIRECTORY_NAMES_LEDE": "ڈائریکٹری کے نام",
  "FILENAMES_LEDE": "فائلوں کے نام",
  "FILENAME": "فائل کا نام",
  "DIRECTORY_NAME": "ڈائریکٹری کا نام",
  "ERROR_LOADING_PROJECT": "پراجیکٹ لوڈ کرنے میں خرابی",
  "OPEN_DIALOG_ERROR": "کھلی فائل ڈائیلاگ دکھاتے وقت ایک غلطی ہوئی. (غلطی {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "ڈائرکٹری <span class='dialog-filename'>{0}</span>لوڈ کرنے کی کوشش کرتے وقت ایک غلطی ہوئی. (غلطی {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "ڈائرکٹری <span class='dialog-filename'>{0} کے مواد کو پڑھنے کے دوران ایک</span>غلطی ہوئی. (غلطی {1})",
  "ERROR_OPENING_FILE_TITLE": "فائل کھولنے میں خرابی",
  "ERROR_OPENING_FILE": "فائل کو کھولنے کی کوشش کرتے وقت ایک غلطی ہوئی <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_OPENING_FILES": "مندرجہ ذیل فائلوں کو کھولنے کی کوشش کرتے وقت ایک غلطی ہوئی:",
  "ERROR_RELOADING_FILE_TITLE": "ڈسک سے تبدیلیوں کو دوبارہ لوڈ کرنے میں خرابی",
  "ERROR_RELOADING_FILE": "فائل کو دوبارہ لوڈ کرنے کی کوشش کرتے وقت ایک غلطی ہوئی <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_SAVING_FILE_TITLE": "فائل محفوظ کرنے میں خرابی",
  "ERROR_SAVING_FILE": "فائل کو محفوظ کرنے کی کوشش کرتے وقت ایک غلطی ہوئی <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_FILE_TITLE": "نام تبدیل کرنے میں غلطی {0}",
  "ERROR_RENAMING_FILE": "{2} { <span class='dialog-filename'>0} کا نام تبدیل کرنے کی کوشش کرتے وقت ایک</span>غلطی ہوئی. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "فائل یا ڈائرکٹری فی الحال کھولی ہوئی پراجیکٹ کا حصہ نہیں ہے۔ بدقسمتی سے، اس وقت صرف پروجیکٹ فائلوں کا نام تبدیل کیا جا سکتا ہے.",
  "ERROR_MOVING_FILE_TITLE": "نقل و حرکت میں غلطی {0}",
  "ERROR_MOVING_FILE": "{2} { <span class='dialog-filename'>0} کو منتقل کرنے کی کوشش کرتے وقت ایک</span>غلطی ہوئی. {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "فائل/فولڈر کو منتقل نہیں کر سکتے ہیں، کیونکہ وہ موجودہ منصوبے کا حصہ نہیں ہیں.",
  "ERROR_DELETING_FILE_TITLE": "{0} حذف کرنے میں نقص",
  "ERROR_DELETING_FILE": "{2} { <span class='dialog-filename'>0} کو حذف کرنے کی کوشش کرتے وقت ایک</span>غلطی ہوئی. {1}",
  "INVALID_FILENAME_TITLE": "غلط {0}",
  "INVALID_FILENAME_MESSAGE": "{0} کسی بھی نظام محفوظ الفاظ کا استعمال نہیں کر سکتے ہیں، نقطوں کے ساتھ ختم کریں (.) یا مندرجہ ذیل حروف میں سے کسی کا استعمال کریں: <code class='emphasized'>{1}</code>",
  "ENTRY_WITH_SAME_NAME_EXISTS": "نام <span class='dialog-filename'>{0} کے ساتھ ایک فائل یا ڈائرکٹری پہلے سے</span> موجود ہے.",
  "ERROR_CREATING_FILE_TITLE": "{0} بنانے میں خرابی",
  "ERROR_CREATING_FILE": "{0} { <span class='dialog-filename'>1} تخلیق کرنے کی کوشش کرتے وقت ایک</span>غلطی ہوئی. {2}",
  "ERROR_MIXED_DRAGDROP": "دیگر فائلوں کو کھولنے کے دوران فولڈر کو ایک ہی وقت میں نہیں کھول سکتا.",
  "ERROR_KEYMAP_TITLE": "صارف کا کلیدی نقشہ پڑھنے میں خرابی",
  "ERROR_KEYMAP_CORRUPT": "آپ کی کلیدی نقشہ فائل درست JSON نہیں ہے. فائل کھول دی جائے گی تاکہ آپ فارمیٹ کو درست کر سکیں.",
  "ERROR_LOADING_KEYMAP": "آپ کی کلیدی نقشہ فائل درست UTF-8 انکوڈ کردہ ٹیکسٹ فائل نہیں ہے اور اسے لوڈ نہیں کیا جا سکتا",
  "ERROR_RESTRICTED_COMMANDS": "آپ ان کمانڈز پر شارٹ کٹس دوبارہ تفویض نہیں کر سکتے: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "آپ ان شارٹ کٹس کو دوبارہ تفویض نہیں کر سکتے: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "آپ ان کمانڈز پر متعدد شارٹ کٹس دوبارہ تفویض کر رہے ہیں: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "آپ کے پاس ان شارٹ کٹس کے متعدد پابند ہیں: {0}",
  "ERROR_INVALID_SHORTCUTS": "یہ شارٹ کٹس غلط ہیں: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "آپ شارٹ کٹس کو غیر موجود کمانڈز کو تفویض کر رہے ہیں: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "پڑھنے کی ترجیحات میں خرابی",
  "ERROR_PREFS_CORRUPT": "آپ کی ترجیحات فائل درست JSON نہیں ہے. فائل کھول دی جائے گی تاکہ آپ فارمیٹ کو درست کر سکیں. آپ کو تبدیل کرنے کے لئے {APP_NAME} کو دوبارہ شروع کرنے کی ضرورت ہوگی.",
  "ERROR_PROJ_PREFS_CORRUPT": "آپ کے منصوبے کی ترجیحات فائل درست JSON نہیں ہے. فائل کھول دی جائے گی تاکہ آپ فارمیٹ کو درست کر سکیں. تبدیلیوں کو اثر انداز کرنے کے لئے آپ کو اس منصوبے کو دوبارہ لوڈ کرنے کی ضرورت ہوگی.",
  "ERROR_IN_BROWSER_TITLE": "افسوس! {APP_NAME} براؤزرز میں ابھی تک نہیں چل رہا ہے.",
  "ERROR_IN_BROWSER": "{APP_NAME} HTML میں بنایا گیا ہے، لیکن ابھی یہ ڈیسک ٹاپ اپلی کیشن کے طور پر چلتا ہے لہذا آپ اسے مقامی فائلوں میں ترمیم کرنے کے لئے استعمال کرسکتے ہیں. براہ مہربانی {APP_NAME} چلانے کے لئے <b>hrejub.com/adobe/بریکٹس-شیل</b> ریپو میں درخواست شیل کا استعمال کریں.",
  "ERROR_MAX_FILES_TITLE": "فائلوں کی اشاریہ کاری میں خرابی",
  "ERROR_MAX_FILES": "اس منصوبے میں 30,000 سے زائد فائلوں پر مشتمل ہے. ایک سے زیادہ فائلوں میں کام کرنے والی خصوصیات غیر فعال ہوسکتی ہیں یا اس طرح برتاؤ کر سکتی ہیں جیسے پروجیکٹ خالی ہے۔ <a href='https://github.com/adobe/brackets/wiki/Large-Projects'>بڑے منصوبوں کے ساتھ کام کرنے کے بارے میں مزید پڑھیں</a>.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "براؤزر شروع کرنے میں خرابی",
  "ERROR_CANT_FIND_CHROME": "گوگل کروم براؤزر نہیں مل سکا. براہ کرم اس بات کو یقینی بنائیں کہ یہ نصب ہے.",
  "ERROR_LAUNCHING_BROWSER": "براؤزر شروع کرتے وقت ایک غلطی ہوئی. (غلطی {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "لائیو پیش نظارہ کی خرابی",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "براؤزر سے متصل",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "مربوط ہونے کے لئے لائیو پیش منظر کے لئے، Chrome کو ریموٹ ڈیبگنگ فعال کے ساتھ دوبارہ لانچ کرنے کی ضرورت ہے. <br /><br />کیا آپ کروم کو دوبارہ شروع کرنا چاہتے ہیں اور ریموٹ ڈیبگنگ کو فعال کرنا چاہتے ہیں؟ <br /><br />",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "لائیو پیش منظر کا صفحہ لوڈ کرنے میں ناقابل۔",
  "LIVE_DEV_NEED_HTML_MESSAGE": "ایک HTML فائل کھولیں یا اس بات کو یقینی بنائیں کہ آپ کے منصوبے میں ایک index.html فائل ہے لائیو پیش نظارہ شروع کرنے کے لئے.",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "سرور سائڈ فائل کے ساتھ لائیو پیش نظارہ شروع کرنے کے لئے، آپ کو اس منصوبے کے لئے بیس URL کی وضاحت کرنے کی ضرورت ہے.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "لائیو پیش نظارہ فائلوں کے لئے HTTP سرور شروع کرنے میں خرابی. براہ مہربانی دوبارہ کوشش کریں۔",
  "LIVE_DEVELOPMENT_INFO_TITLE": "لائیو پیش نظارہ میں خوش آمدید!",
  "LIVE_DEVELOPMENT_INFO_MESSAGE": "لائیو پیش نظارہ {APP_NAME} کو آپ کے براؤزر سے جوڑتا ہے۔ یہ براؤزر میں آپ کی HTML فائل کا پیش منظر شروع کرتا ہے، پھر آپ اپنے کوڈ میں ترمیم کے طور پر پیش نظارہ کو فوری طور پر اپ ڈیٹ کرتا ہے. <br /><br />{ APP_NAME} کے اس ابتدائی ورژن میں، لائیو پیش نظارہ صرف <strong>Google Chrome</strong> کے ساتھ کام کرتا ہے اور اپ ڈیٹس رہتے ہیں جیسے ہی آپ <strong>سی ایس ایس یا HTML فائلوں</strong> میں ترمیم کرتے ہیں. جب آپ محفوظ کرتے ہیں تو جاوا سکرپٹ فائلوں میں تبدیلیاں خودکار طور پر دوبارہ لوڈ ہوجاتی ہیں۔ <br /><br />( آپ کو یہ پیغام صرف ایک بار نظر آئے گا.)",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "مزید معلومات کے لئے، <a href='{0}' title='{0}'>لائیو پیش نظارہ کنکشن کی غلطیوں کا ازالہ کرنا</a>دیکھیں۔",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "لائیو پیش نظارہ",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "لائیو پیش نظارہ: جڑ رہا ہے...",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "لائیو پیش نظارہ: ابتدا...",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "لائیو پیش منظر منقطع کریں",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "لائیو پیش نظارہ (ریفریش کرنے کیلئے فائل محفوظ کریں)",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "لائیو پیش نظارہ کیلئے فائل منتخب کریں",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "صفحہ دوبارہ لوڈ کریں",
  "LIVE_DEV_CLICK_POPOUT": "نئی ونڈو میں پوپ آؤٹ لائیو پیش نظارہ",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "غیر PIN پیش نظارہ صفحہ پر پن کریں",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "لائیو پیش نظارہ (نحو کی غلطی کی وجہ سے اپ ڈیٹ نہیں)",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "لائیو پیش منظر منسوخ کر دیا گیا کیونکہ براؤزر کے ڈویلپر کے ٹولز کھولے گئے تھے",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "لائیو پیش منظر منسوخ کر دیا گیا کیونکہ براؤزر میں صفحہ بند کر دیا گیا تھا",
  "LIVE_DEV_NAVIGATED_AWAY": "لائیو پیش منظر منسوخ کر دیا گیا کیونکہ براؤزر ایک ایسے صفحے پر نیویگیشن کیا گیا ہے جو موجودہ پروجیکٹ کا حصہ نہیں ہے",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "لائیو پیش منظر نامعلوم وجہ کے لئے منسوخ کر دیا گیا تھا ({0})",
  "SAVE_CLOSE_TITLE": "تبدیلیاں محفوظ کریں",
  "SAVE_CLOSE_MESSAGE": "کیا آپ دستاویز <span class='dialog-filename'>{0}</span>میں کی گئی تبدیلیوں کو محفوظ کرنا چاہتے ہیں؟",
  "SAVE_CLOSE_MULTI_MESSAGE": "کیا آپ اپنی تبدیلیوں کو مندرجہ ذیل فائلوں میں محفوظ کرنا چاہتے ہیں؟",
  "EXT_MODIFIED_TITLE": "بیرونی تبدیلیاں",
  "CONFIRM_DELETE_TITLE": "حذف کرنے کی تصدیق کریں",
  "CONFIRM_FILE_DELETE": "کیا آپ کو یقین ہے کہ آپ فائل <span class='dialog-filename'>{0}</span>کو حذف کرنا چاہتے ہیں؟",
  "CONFIRM_FOLDER_DELETE": "کیا آپ واقعی فولڈر <span class='dialog-filename'>{0}</span>کو حذف کرنا چاہتے ہیں؟",
  "FILE_DELETED_TITLE": "فائل حذف کردی گئی",
  "EXT_MODIFIED_WARNING": "<span class='dialog-filename'>{ 0}</span> {APP_NAME} کے باہر ڈسک پر ترمیم کی گئی ہے۔ <br /><br />کیا آپ فائل کو محفوظ کرنا چاہتے ہیں اور ان تبدیلیوں کو اوور لکھنا چاہتے ہیں؟",
  "EXT_MODIFIED_MESSAGE": "<span class='dialog-filename'>{ 0}</span> {APP_NAME} کے باہر ڈسک پر ترمیم کی گئی ہے، لیکن {APP_NAME} میں غیر محفوظ شدہ تبدیلیاں بھی ہیں. <br /><br />آپ کونسی ورژن رکھنا چاہتے ہیں؟",
  "EXT_DELETED_MESSAGE": "<span class='dialog-filename'>{ 0}</span> {APP_NAME} کے باہر ڈسک پر حذف کر دیا گیا ہے، لیکن {APP_NAME} میں غیر محفوظ شدہ تبدیلیاں ہیں. <br /><br />کیا آپ اپنی تبدیلیوں کو برقرار رکھنا چاہتے ہیں؟",
  "WINDOW_UNLOAD_WARNING": "کیا آپ کو یقین ہے کہ آپ ایک مختلف URL پر تشریف لے جانا چاہتے ہیں اور بریکٹ چھوڑنا چاہتے ہیں؟",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "آپ کے پاس غیرنجات یافتہ تبدیلیاں ہوتی ہیں! کیا آپ کو یقین ہے کہ آپ ایک مختلف URL پر تشریف لے جانا چاہتے ہیں اور بریکٹ چھوڑنا چاہتے ہیں؟",
  "DONE": "ہو گیا",
  "OK": "ٹھیک ہے",
  "CANCEL": "منسوخ کریں",
  "DONT_SAVE": "محفوظ نہ کریں",
  "SAVE": "محفوظ کریں",
  "SAVE_AS": "کے طور پر محفوظ کریں...",
  "SAVE_AND_OVERWRITE": "اوور لکھنا",
  "DELETE": "حذف کریں",
  "BUTTON_YES": "جی ہاں",
  "BUTTON_NO": "نہیں",
  "FIND_MATCH_INDEX": "{0} کی {1}",
  "FIND_NO_RESULTS": "کوئی نتیجہ نہیں",
  "FIND_QUERY_PLACEHOLDER": "تلاش کریں...",
  "FIND_HISTORY_MAX_COUNT": "تلاش کی سرگزشت میں تلاش کے آئٹمز کی زیادہ سے زیادہ تعداد",
  "REPLACE_PLACEHOLDER": "کے ساتھ تبدیل کریں...",
  "BUTTON_REPLACE_ALL": "سب کو تبدیل کریں",
  "BUTTON_REPLACE_BATCH": "بیچ...",
  "BUTTON_REPLACE_ALL_IN_FILES": "تبدیل کریں...",
  "BUTTON_REPLACE": "تبدیل کریں",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "اگلا میچ",
  "BUTTON_PREV_HINT": "پچھلا میچ",
  "BUTTON_CASESENSITIVE_HINT": "میچ کیس",
  "BUTTON_REGEXP_HINT": "باقاعدہ اظہار",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "کالعدم کے بغیر تبدیل کریں",
  "REPLACE_WITHOUT_UNDO_WARNING": "کیونکہ {0} سے زیادہ فائلوں کو تبدیل کرنے کی ضرورت ہے، {APP_NAME} ڈسک پر غیر کھولی ہوئی فائلوں میں ترمیم کرے گی. <br />آپ ان فائلوں میں تبدیل کرنے کے قابل نہیں ہوں گے.",
  "BUTTON_REPLACE_WITHOUT_UNDO": "کالعدم کے بغیر تبدیل کریں",
  "OPEN_FILE": "فائل کھولیں",
  "SAVE_FILE_AS": "فائل محفوظ کریں",
  "CHOOSE_FOLDER": "ایک فولڈر منتخب کریں",
  "RELEASE_NOTES": "ریلیز نوٹ",
  "NO_UPDATE_TITLE": "آپ کی تاریخ تک ہیں!",
  "NO_UPDATE_MESSAGE": "آپ {APP_NAME} کا تازہ ترین ورژن چلا رہے ہیں۔",
  "FIND_REPLACE_TITLE_LABEL": "تبدیل کریں",
  "FIND_REPLACE_TITLE_WITH": "کے ساتھ",
  "FIND_TITLE_LABEL": "مل گیا",
  "FIND_TITLE_SUMMARY": "— {0} {1} {2} میں {3}",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "میں <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_NO_SCOPE": "منصوبے میں",
  "FIND_IN_FILES_ZERO_FILES": "فلٹر تمام فائلوں کو خارج کر دیتا ہے {0}",
  "FIND_IN_FILES_FILE": "فائل",
  "FIND_IN_FILES_FILES": "فائلوں",
  "FIND_IN_FILES_MATCH": "میچ۔",
  "FIND_IN_FILES_MATCHES": "میچ",
  "FIND_IN_FILES_MORE_THAN": "اوور ",
  "FIND_IN_FILES_PAGING": "{0} — {1}",
  "FIND_IN_FILES_FILE_PATH": "<span class='dialog-filename'>{ 0}</span> {2} <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "Ctrl /Cmd تمام توسیع/خاتمے کے لئے کلک کریں",
  "FIND_IN_FILES_INDEXING": "فوری تلاش کے لئے اشاریہ کاری...",
  "REPLACE_IN_FILES_ERRORS_TITLE": "غلطیوں کو تبدیل کریں",
  "REPLACE_IN_FILES_ERRORS": "درج ذیل فائلیں ترمیم نہیں کی گئیں کیونکہ وہ تلاش کے بعد تبدیل ہوگئیں یا لکھی نہیں جا سکتیں۔",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "اپ ڈیٹ معلومات حاصل کرنے میں خرابی",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "سرور سے تازہ ترین اپ ڈیٹ کی معلومات حاصل کرنے میں ایک مسئلہ تھا. براہ کرم یقینی بنائیں کہ آپ انٹرنیٹ سے منسلک ہیں اور دوبارہ کوشش کریں.",
  "NEW_FILE_FILTER": "نیا اخراج سیٹ...",
  "CLEAR_FILE_FILTER": "فائلوں کو خارج نہ کریں",
  "NO_FILE_FILTER": "کوئی فائلیں خارج نہیں",
  "EXCLUDE_FILE_FILTER": "خارج کریں {0}",
  "EDIT_FILE_FILTER": "ترمیم کریں...",
  "FILE_FILTER_DIALOG": "اخراج سیٹ میں ترمیم کریں",
  "FILE_FILTER_INSTRUCTIONS": "مندرجہ ذیل سٹرنگ/ذیلی سٹرنگز یا <a href='{0}' title='{0}'>وائلڈ کارڈ</a>سے ملنے والی فائلوں اور فولڈروں کو خارج کریں. ایک نئی لائن پر ہر سٹرنگ درج کریں.",
  "FILTER_NAME_PLACEHOLDER": "اس اخراج سیٹ کا نام (اختیاری)",
  "FILTER_NAME_REMAINING": "{0} حروف باقی",
  "FILE_FILTER_CLIPPED_SUFFIX": "اور {0} مزید",
  "FILTER_COUNTING_FILES": "فائلوں کی گنتی...",
  "FILTER_FILE_COUNT": "{1} فائلوں کی {0} کی اجازت دیتا ہے {2}",
  "FILTER_FILE_COUNT_ALL": "تمام {0} فائلوں کو {1} کی اجازت دیتا ہے",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "موجودہ کرسر کی پوزیشن کے لئے کوئی فوری ترمیم دستیاب نہیں ہے",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "سی ایس ایس فوری ترمیم کریں: ایک کلاس کے نام پر کرسر کی جگہ",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "سی ایس ایس فوری ترمیم: نامکمل کلاس وصف",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "سی ایس ایس فوری ترمیم: نامکمل ID وصف",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "سی ایس ایس فوری ترمیم کریں: ٹیگ، کلاس، یا ID میں جگہ کرسر",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "سی ایس ایس ٹائمنگ فنکشن فوری ترمیم کریں: غلط نحو",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "جے ایس فوری ترمیم کریں: فنکشن نام میں جگہ کرسر",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "موجودہ کرسر پوزیشن کے لئے کوئی فوری دستاویزات دستیاب نہیں",
  "PROJECT_LOADING": "لوڈ ہو رہا ہے...",
  "UNTITLED": "بلا عنوان",
  "WORKING_FILES": "کام کرنے والی فائلیں",
  "TOP": "اوپر",
  "BOTTOM": "نیچے",
  "LEFT": "بائیں",
  "RIGHT": "دائیں",
  "CMD_SPLITVIEW_NONE": "کوئی تقسیم نہیں",
  "CMD_SPLITVIEW_VERTICAL": "عمودی تقسیم",
  "CMD_SPLITVIEW_HORIZONTAL": "افقی تقسیم",
  "SPLITVIEW_MENU_TOOLTIP": "ایڈیٹر عمودی یا افقی طور پر تقسیم کریں",
  "GEAR_MENU_TOOLTIP": "ورکنگ سیٹ ترتیب دیں",
  "SPLITVIEW_INFO_TITLE": "پہلے سے ہی کھولیں",
  "SPLITVIEW_MULTIPANE_WARNING": "فائل پہلے سے ہی کسی دوسرے پین میں کھلا ہوا ہے۔ {APP_NAME} جلد ہی ایک سے زیادہ پین میں ایک ہی فائل کھولنے کی حمایت کرے گا. اس وقت تک، فائل اس پین میں دکھائی جائے گی جس میں یہ پہلے سے ہی کھلا ہوا ہے. <br /><br />( آپ کو یہ پیغام صرف ایک بار نظر آئے گا.)",
  "STATUSBAR_CURSOR_POSITION": "لائن {0}، کالم {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": " — منتخب {0} کالم",
  "STATUSBAR_SELECTION_CH_PLURAL": " — منتخب {0} کالم",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " — منتخب {0} لائن",
  "STATUSBAR_SELECTION_LINE_PLURAL": " — منتخب {0} لائنیں",
  "STATUSBAR_SELECTION_MULTIPLE": " {0} انتخاب",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "خالی جگہوں پر اندراج سوئچ کرنے کے لئے کلک کریں",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "ٹیب پر اندراج سوئچ کرنے کے لئے کلک کریں",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "اندراج کرتے وقت استعمال کردہ خالی جگہوں کی تعداد کو تبدیل کرنے کے لئے کلک کریں",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "ٹیب کردار کی چوڑائی کو تبدیل کرنے کے لئے کلک کریں",
  "STATUSBAR_SPACES": "خالی جگہیں:",
  "STATUSBAR_TAB_SIZE": "ٹیب سائز:",
  "STATUSBAR_LINE_COUNT_SINGULAR": "— {0} لائن",
  "STATUSBAR_LINE_COUNT_PLURAL": "— {0} لائنیں",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "غیر فعال ایکسٹنشن",
  "STATUSBAR_INSERT": "INS",
  "STATUSBAR_OVERWRITE": "سے زیادہ",
  "STATUSBAR_INSOVR_TOOLTIP": "داخل (INS) اور اوور رائٹ (OVR) طریقوں کے درمیان کرسر کو ٹوگل کرنے کے لئے کلک کریں",
  "STATUSBAR_LANG_TOOLTIP": "فائل کی قسم تبدیل کرنے کے لئے کلک کریں",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. رپورٹ پینل کو ٹوگل کرنے کے لئے کلک کریں۔",
  "STATUSBAR_DEFAULT_LANG": "(ڈیفالٹ)",
  "STATUSBAR_SET_DEFAULT_LANG": "{0} فائلوں کے لئے ڈیفالٹ کے طور پر مقرر کریں",
  "STATUSBAR_ENCODING_TOOLTIP": "انکوڈنگ منتخب کریں",
  "ERRORS_PANEL_TITLE_MULTIPLE": "{0} مسائل",
  "SINGLE_ERROR": "1 {0} مسئلہ",
  "MULTIPLE_ERRORS": "{1} {0} مسائل",
  "NO_ERRORS": "نہیں {0} مسائل مل گئے - اچھا کام!",
  "NO_ERRORS_MULTIPLE_PROVIDER": "کوئی مسئلہ نہیں ملا - اچھا کام!",
  "LINT_DISABLED": "لنٹنگ غیر فعال ہے",
  "NO_LINT_AVAILABLE": "{0} کے لئے کوئی لینٹر دستیاب نہیں ہے",
  "NOTHING_TO_LINT": "لنٹ کرنے کے لئے کچھ بھی نہیں",
  "LINTER_TIMED_OUT": "{0} {1} ایم ایس کے لئے انتظار کرنے کے بعد وقت ختم ہو گیا ہے",
  "LINTER_FAILED": "{0} غلطی کے ساتھ ختم: {1}",
  "FILE_MENU": "فائل",
  "CMD_FILE_NEW_UNTITLED": "نیا",
  "CMD_FILE_NEW": "نئی فائل",
  "CMD_FILE_DUPLICATE": "ڈپلیکیٹ",
  "CMD_PROJECT_NEW": "نیا پروجیکٹ",
  "CMD_FILE_NEW_FOLDER": "نیا فولڈر",
  "CMD_FILE_OPEN": "کھولیں...",
  "CMD_RECENT_FILES_OPEN": "حالیہ کھولیں...",
  "CMD_ADD_TO_WORKING_SET": "کام کرنے والے سیٹ پر کھولیں",
  "CMD_OPEN_DROPPED_FILES": "ڈراپ فائلیں کھولیں",
  "CMD_OPEN_FOLDER": "فولڈر کھولیں...",
  "CMD_FILE_CLOSE": "بند کریں",
  "CMD_FILE_CLOSE_ALL": "تمام بند کریں",
  "CMD_FILE_CLOSE_LIST": "فہرست بند کریں",
  "CMD_FILE_CLOSE_OTHERS": "دوسروں کو بند کریں",
  "CMD_FILE_CLOSE_ABOVE": "اوپر دوسروں کو بند کریں",
  "CMD_FILE_CLOSE_BELOW": "ذیل میں دوسروں کو بند کریں",
  "CMD_FILE_SAVE": "محفوظ کریں",
  "CMD_FILE_SAVE_ALL": "تمام محفوظ کریں",
  "CMD_FILE_SAVE_AS": "کے طور پر محفوظ کریں...",
  "CMD_LIVE_FILE_PREVIEW": "لائیو پیش نظارہ",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "تجرباتی لائیو پیش نظارہ فعال کریں",
  "CMD_RELOAD_LIVE_PREVIEW": "فورس دوبارہ لوڈ کریں لائیو پیش نظارہ",
  "CMD_PROJECT_SETTINGS": "پروجیکٹ کی ترتیبات...",
  "CMD_FILE_RENAME": "نام تبدیل کریں",
  "CMD_FILE_DELETE": "حذف کریں",
  "CMD_INSTALL_EXTENSION": "توسیع انسٹال کریں...",
  "CMD_EXTENSION_MANAGER": "ایکسٹنشن مینیجر...",
  "CMD_FILE_REFRESH": "فائل ٹری کو تازہ کریں",
  "CMD_QUIT": "چھوڑیں",
  "CMD_EXIT": "باہر نکلیں",
  "EDIT_MENU": "ترمیم کریں",
  "CMD_UNDO": "کالعدم کریں",
  "CMD_REDO": "دوبارہ کریں",
  "CMD_CUT": "کٹاؤ",
  "CMD_COPY": "کاپی",
  "CMD_PASTE": "پیسٹ کریں",
  "CMD_SELECT_ALL": "تمام منتخب کریں",
  "CMD_SELECT_LINE": "لائن منتخب کریں",
  "CMD_SPLIT_SEL_INTO_LINES": "لائنوں میں تقسیم انتخاب",
  "CMD_ADD_CUR_TO_NEXT_LINE": "اگلی لائن میں کرسر شامل کریں",
  "CMD_ADD_CUR_TO_PREV_LINE": "پچھلی سطر میں کرسر شامل کریں",
  "CMD_INDENT": "انڈینٹ",
  "CMD_UNINDENT": "غیر اشاریہ",
  "CMD_DUPLICATE": "ڈپلیکیٹ",
  "CMD_DELETE_LINES": "لائن حذف کریں",
  "CMD_COMMENT": "ٹوگل لائن تبصرہ",
  "CMD_BLOCK_COMMENT": "بلاک تبصرہ ٹوگل",
  "CMD_LINE_UP": "لائن اپ منتقل کریں",
  "CMD_LINE_DOWN": "لائن نیچے منتقل کریں",
  "CMD_OPEN_LINE_ABOVE": "اوپن لائن اوپر",
  "CMD_OPEN_LINE_BELOW": "نیچے لائن کھولیں",
  "CMD_TOGGLE_CLOSE_BRACKETS": "آٹو بند بریسیز",
  "CMD_SHOW_CODE_HINTS": "کوڈ اشارے دکھائیں",
  "FIND_MENU": "ڈھونڈیں",
  "CMD_FIND": "ڈھونڈیں",
  "CMD_FIND_NEXT": "اگلا تلاش کریں",
  "CMD_FIND_PREVIOUS": "پچھلا تلاش کریں",
  "CMD_FIND_ALL_AND_SELECT": "سب تلاش کریں اور منتخب کریں",
  "CMD_ADD_NEXT_MATCH": "انتخاب میں اگلا میچ شامل کریں",
  "CMD_SKIP_CURRENT_MATCH": "اگلا میچ کو چھوڑ دیں اور شامل کریں",
  "CMD_FIND_IN_FILES": "فائلوں میں تلاش کریں",
  "CMD_FIND_IN_SUBTREE": "میں تلاش کریں...",
  "CMD_REPLACE": "تبدیل کریں",
  "CMD_REPLACE_IN_FILES": "فائلوں میں تبدیل کریں",
  "CMD_REPLACE_IN_SUBTREE": "میں تبدیل کریں...",
  "VIEW_MENU": "دیکھیں",
  "CMD_HIDE_SIDEBAR": "سائڈبار چھپائیں",
  "CMD_SHOW_SIDEBAR": "سائڈبار دکھائیں",
  "CMD_TOGGLE_SIDEBAR": "ٹوگل سائڈبار",
  "CMD_TOGGLE_PANELS": "پینل ٹوگل کریں",
  "CMD_TOGGLE_PURE_CODE": "کوئی پریشانی نہیں",
  "CMD_INCREASE_FONT_SIZE": "فونٹ کا سائز بڑھائیں",
  "CMD_DECREASE_FONT_SIZE": "فونٹ کا سائز کم کریں",
  "CMD_RESTORE_FONT_SIZE": "فونٹ کا سائز بحال کریں",
  "CMD_SCROLL_LINE_UP": "سکرال لائن اپ",
  "CMD_SCROLL_LINE_DOWN": "سکرال لائن نیچے",
  "CMD_TOGGLE_LINE_NUMBERS": "لائن نمبرز",
  "CMD_TOGGLE_ACTIVE_LINE": "فعال لائن کو نمایاں کریں",
  "CMD_TOGGLE_WORD_WRAP": "لفظ لپیٹ",
  "CMD_LIVE_HIGHLIGHT": "لائیو پیش نظارہ نمایاں کریں",
  "CMD_VIEW_TOGGLE_INSPECTION": "محفوظ کرنے پر لنٹ فائلیں",
  "CMD_WORKINGSET_SORT_BY_ADDED": "شامل کی طرف سے ترتیب دیں",
  "CMD_WORKINGSET_SORT_BY_NAME": "نام کے حساب سے ترتیب دیں",
  "CMD_WORKINGSET_SORT_BY_TYPE": "قسم کے لحاظ سے ترتیب دیں",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "خودکار ترتیب دیں",
  "CMD_THEMES": "موضوعات...",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "خودکار طور پر تلاش بند کریں",
  "NAVIGATE_MENU": "تشریف لے جائیں۔",
  "CMD_QUICK_OPEN": "فوری اوپن",
  "CMD_GOTO_LINE": "لائن پر جائیں",
  "CMD_GOTO_DEFINITION": "فوری تلاش کی تعریف",
  "CMD_GOTO_DEFINITION_PROJECT": "پراجیکٹ میں فوری تلاش کی تعریف",
  "CMD_GOTO_FIRST_PROBLEM": "پہلا مسئلہ پر جائیں",
  "CMD_TOGGLE_QUICK_EDIT": "فوری ترمیم",
  "CMD_TOGGLE_QUICK_DOCS": "فوری دستاویزات",
  "CMD_QUICK_EDIT_PREV_MATCH": "پچھلا میچ",
  "CMD_QUICK_EDIT_NEXT_MATCH": "اگلا میچ",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "نیا قاعدہ",
  "CMD_NEXT_DOC": "اگلا دستاویز",
  "CMD_PREV_DOC": "پچھلا دستاویز",
  "CMD_NAVIGATE_BACKWARD": "پسماندہ نیویگیشن",
  "CMD_NAVIGATE_FORWARD": "آگے تشریف لے جائیں",
  "CMD_NEXT_DOC_LIST_ORDER": "فہرست میں اگلا دستاویز",
  "CMD_PREV_DOC_LIST_ORDER": "فہرست میں پچھلا دستاویز",
  "CMD_SHOW_IN_TREE": "فائل ٹری میں دکھائیں",
  "CMD_SHOW_IN_EXPLORER": "ایکسپلورر میں دکھائیں",
  "CMD_SHOW_IN_FINDER": "فائنڈر میں دکھائیں",
  "CMD_SHOW_IN_OS": "OS میں دکھائیں",
  "CMD_SWITCH_PANE_FOCUS": "پین فوکس سوئچ",
  "CMD_OPEN_VFS": "کھولیں مجازی فائل سسٹم",
  "CMD_OPEN_VIRTUAL_SERVER": "کھولیں ورچوئل سرور",
  "HELP_MENU": "مدد",
  "CMD_CHECK_FOR_UPDATE": "اپ ڈیٹس کے لئے چیک کریں",
  "CMD_HOW_TO_USE_BRACKETS": "{APP_NAME} کا استعمال کیسے کریں",
  "CMD_SUPPORT": "{اپ_نام} سپورٹ",
  "CMD_SUGGEST": "ایک خصوصیت تجویز کریں",
  "CMD_RELEASE_NOTES": "ریلیز نوٹ",
  "CMD_GET_INVOLVED": "ملوث ہو جاؤ",
  "CMD_SHOW_EXTENSIONS_FOLDER": "ایکسٹنشن فولڈر دکھائیں",
  "CMD_HEALTH_DATA_STATISTICS": "صحت کی رپورٹ",
  "CMD_HOMEPAGE": "{APP_NAME} ہوم پیج",
  "CMD_TWITTER": "ٹویٹر پر {ٹوئٹر_نام}",
  "CMD_ABOUT": "{APP_عنوان} کے بارے میں",
  "CMD_OPEN_PREFERENCES": "ترجیحات فائل کھولیں",
  "CMD_OPEN_KEYMAP": "صارف کا کلیدی نقشہ کھولیں",
  "EXPERIMENTAL_BUILD": "تجرباتی تعمیر",
  "RELEASE_BUILD": "ساخت",
  "DEVELOPMENT_BUILD": "ترقی کی تعمیر",
  "PRERELEASE_BUILD": "قبل از ریلیز تعمیر",
  "RELOAD_FROM_DISK": "ڈسک سے دوبارہ لوڈ کریں",
  "KEEP_CHANGES_IN_EDITOR": "ایڈیٹر میں تبدیلیاں رکھیں",
  "CLOSE_DONT_SAVE": "بند کریں (محفوظ نہ کریں)",
  "RELAUNCH_CHROME": "Chrome دوبارہ لانچ کریں",
  "ABOUT": "کے بارے میں",
  "CLOSE": "بند کریں",
  "ABOUT_TEXT_LINE1": "{ورژن_میجر} ریلیز کریں۔ {ورژن_معمولی} {تعمیر_ٹائپ} {ورژن}",
  "ABOUT_TEXT_BUILD_TIMESTAMP": "ٹائمسٹیمپ کی تعمیر: ",
  "ABOUT_TEXT_LINE3": "ہم استعمال کرتے ہیں کہ تیسری پارٹی لائبریریوں - <a href='https://github.com/phcode-dev/phoenix/tree/main/src/thirdparty/licences'> لائسنس اور انتساب</a> . ",
  "ABOUT_TEXT_LINE4": "<a href='https://github.com/phcode-dev/phoenix/'>https://github.com/phcode-dev/phoenix/ پر دستاویزات اور ذریعہ</a>",
  "ABOUT_TEXT_LINE5": "❤ اور جاوا سکرپٹ کے ساتھ بنایا گیا:",
  "ABOUT_TEXT_LINE6": "بہت سے لوگ (لیکن ہمیں اس ڈیٹا کو ابھی لوڈ کرنے میں دشواری ہو رہی ہے).",
  "ABOUT_TEXT_MDN_DOCS": "MDN Docs اور MDN گرافیکل علامت (لوگو) تخلیقی العام انتساب لائسنس کے تحت لائسنس یافتہ ہیں، <a href='{MDN_DOCS_LICENSE}'>CC-BY-SA 2.5 Unped</a>.",
  "UPDATE_NOTIFICATION_TOOLTIP": "{APP_NAME} کی ایک نئی تعمیر دستیاب ہے! تفصیلات کے لئے یہاں کلک کریں.",
  "UPDATE_AVAILABLE_TITLE": "دستیاب اپ ڈیٹ کریں",
  "UPDATE_MESSAGE": "ارے، دستیاب {APP_NAME} کی ایک نئی تعمیر ہے. یہاں نئی خصوصیات میں سے کچھ ہیں:",
  "GET_IT_NOW": "اب اسے حاصل کریں!",
  "PROJECT_SETTINGS_TITLE": "پروجیکٹ ترتیبات کے لئے: {0}",
  "PROJECT_SETTING_BASE_URL": "لائیو پیش نظارہ بیس URL",
  "PROJECT_SETTING_BASE_URL_HINT": "مقامی سرور استعمال کرنے کے لئے، http://localhost:8000/ جیسے URL درج کریں",
  "BASEURL_ERROR_INVALID_PROTOCOL": "{0} پروٹوکول لائیو پیش نظارہ کی طرف سے معاونت نہیں ہے - براہ کرم http: یا https: استعمال کریں.",
  "BASEURL_ERROR_SEARCH_DISALLOWED": "بنیادی URL تلاش کے پیرامیٹرز پر مشتمل نہیں ہو سکتا جیسے “{0}”.",
  "BASEURL_ERROR_HASH_DISALLOWED": "بنیادی URL میں “{0}” جیسے ہیش شامل نہیں ہوسکتے۔",
  "BASEURL_ERROR_INVALID_CHAR": "خاص حروف جیسے '{0}' %-انکوڈڈ ہونا ضروری ہے۔",
  "BASEURL_ERROR_UNKNOWN_ERROR": "بیس URL کی تجزیہ کرنے میں نامعلوم غلطی",
  "EMPTY_VIEW_HEADER": "<em>فائلکھولیں جبکہ یہ پین فوکس ہو</em>",
  "FLIPVIEW_BTN_TOOLTIP": "اس منظر کو {0} پین میں پلٹائیں",
  "CURRENT_THEME": "موجودہ تھیم",
  "USE_THEME_SCROLLBARS": "تھیم اسکرول بار استعمال کریں",
  "FONT_SIZE": "فونٹ سائز",
  "FONT_FAMILY": "فونٹ خاندان",
  "THEMES_SETTINGS": "موضوعات کی ترتیبات",
  "BUTTON_NEW_RULE": "نیا قاعدہ",
  "INSTALL": "انسٹال کریں",
  "UPDATE": "اپ ڈیٹ کریں",
  "REMOVE": "ہٹائیں",
  "DISABLE": "غیر فعال کریں",
  "ENABLE": "فعال کریں",
  "OVERWRITE": "اوور لکھنا",
  "CANT_REMOVE_DEV": "“دیو” فولڈر میں توسیع دستی طور پر حذف ہونا ضروری ہے.",
  "CANT_UPDATE": "تجدید {APP_NAME} کے اس ورژن کے ساتھ ہم آہنگ نہیں ہے۔",
  "CANT_UPDATE_DEV": "“dev” فولڈر میں ایکسٹنشنز کو خودکار طور پر اپ ڈیٹ نہیں کیا جا سکتا۔",
  "INSTALL_EXTENSION_TITLE": "توسیع انسٹال کریں",
  "UPDATE_EXTENSION_TITLE": "توسیع اپ ڈیٹ کریں",
  "INSTALL_EXTENSION_LABEL": "ایکسٹنشن یو آر ایل",
  "INSTALL_EXTENSION_HINT": "توسیع کی زپ فائل یا GitHub ریپو کا URL",
  "INSTALLING_FROM": "{0} سے توسیع انسٹال کر رہا ہے...",
  "INSTALL_SUCCEEDED": "تنصیب کامیاب!",
  "INSTALL_FAILED": "تنصیب ناکام ہو گئی۔",
  "CANCELING_INSTALL": "منسوخ کر رہا ہے...",
  "CANCELING_HUNG": "انسٹال کو منسوخ کرنے میں ایک طویل وقت لگ رہا ہے. ایک اندرونی غلطی واقع ہو سکتی ہے.",
  "INSTALL_CANCELED": "تنصیب منسوخ.",
  "VIEW_COMPLETE_DESCRIPTION": "مکمل تفصیل دیکھیے",
  "VIEW_TRUNCATED_DESCRIPTION": "مختصر تفصیل دیکھیں",
  "SORT_EXTENSION_METHOD": "DownladCount یا شائع شدہ تاریخ کا استعمال کرتے ہوئے توسیع کو ترتیب دیں",
  "INVALID_ZIP_FILE": "ڈاؤن لوڈ کردہ مواد ایک درست زپ فائل نہیں ہے.",
  "MISSING_PACKAGE_JSON": "پیکیج میں کوئی پیکج نہیں ہے. jsنہ فائل.",
  "INVALID_PACKAGE_JSON": "پیکج. json فائل درست نہیں ہے (غلطی تھی: {0}).",
  "MISSING_PACKAGE_NAME": "package.jon فائل ایک پیکج نام کی وضاحت نہیں کرتا.",
  "BAD_PACKAGE_NAME": "{0} ایک غلط پیکیج کا نام ہے۔",
  "MISSING_PACKAGE_VERSION": "package.json فائل ایک پیکج ورژن کی وضاحت نہیں کرتا.",
  "INVALID_VERSION_NUMBER": "پیکج ورژن نمبر ({0}) غلط ہے.",
  "INVALID_BRACKETS_VERSION": "{APP_NAME} مطابقت سٹرنگ ({0}) غلط ہے.",
  "DISALLOWED_WORDS": "{0} فیلڈ میں الفاظ ({1}) کی اجازت نہیں ہے۔",
  "NPM_INSTALL_FAILED": "npm انسٹال کمانڈ ناکام ہوگیا: {0}",
  "API_NOT_COMPATIBLE": "توسیع {APP_NAME} کے اس ورژن کے ساتھ ہم آہنگ نہیں ہے۔ یہ آپ کے معذور توسیع فولڈر میں انسٹال ہے.",
  "MISSING_MAIN": "پیکیج میں کوئی main.js فائل نہیں ہے.",
  "EXTENSION_ALREADY_INSTALLED": "اس پیکج کو انسٹال کرنے سے پہلے نصب کردہ توسیع کو اوور کر دیا جائے گا. پرانے توسیع کو اوور لکھ دیں؟",
  "EXTENSION_SAME_VERSION": "یہ پیکج ایک ہی ورژن ہے جو فی الحال انسٹال ہے. موجودہ تنصیب کو اوور رائٹ کریں؟",
  "EXTENSION_OLDER_VERSION": "یہ پیکج ورژن {0} ہے جو فی الحال نصب ({1}) سے پرانی ہے. موجودہ تنصیب کو اوور رائٹ کریں؟",
  "DOWNLOAD_ID_IN_USE": "داخلی غلطی: پہلے سے ہی استعمال میں آئی ڈی ڈاؤن لوڈ کریں.",
  "NO_SERVER_RESPONSE": "سرور سے متصل نہیں ہو سکتا۔",
  "BAD_HTTP_STATUS": "فائل سرور پر نہیں ملی (HTTP {0}).",
  "CANNOT_WRITE_TEMP": "ٹیمپ فائل میں ڈاؤن لوڈ کو محفوظ کرنے میں قاصر ہے.",
  "ERROR_LOADING": "شروع کرنے کے دوران توسیع کو ایک غلطی کا سامنا کرنا پڑا.",
  "MALFORMED_URL": "URL باطل ہے۔ براہ کرم چیک کریں کہ آپ نے اسے صحیح طریقے سے درج کیا ہے.",
  "UNSUPPORTED_PROTOCOL": "URL ایک http یا https URL ہونا ضروری ہے.",
  "UNKNOWN_ERROR": "نامعلوم داخلی نقص.",
  "EXTENSION_MANAGER_TITLE": "ایکسٹنشن مینیجر",
  "EXTENSION_MANAGER_ERROR_LOAD": "توسیع رجسٹری تک رسائی حاصل کرنے میں ناکام. براہ مہربانی بعد میں دوبارہ کوشش کریں۔",
  "INSTALL_EXTENSION_DRAG": ".zip یہاں ڈریگ کریں یا",
  "INSTALL_EXTENSION_DROP": "انسٹال کرنے کے لے.zip چھوڑ دیں",
  "INSTALL_EXTENSION_DROP_ERROR": "مندرجہ ذیل غلطیوں کی وجہ سے تنصیب کریں/اپ ڈیٹ:",
  "INSTALL_FROM_URL": "URL سے انسٹال کریں...",
  "INSTALL_EXTENSION_VALIDATING": "توثیق...",
  "EXTENSION_AUTHOR": "مصنف",
  "EXTENSION_DATE": "تاریخ",
  "EXTENSION_INCOMPATIBLE_NEWER": "اس توسیع کے لیے {APP_NAME} کا نیا ورژن درکار ہے۔",
  "EXTENSION_INCOMPATIBLE_OLDER": "یہ توسیع فی الحال صرف {APP_NAME} کے پرانے ورژن کے ساتھ کام کرتی ہے۔",
  "EXTENSION_LATEST_INCOMPATIBLE_NEWER": "ورژن {0} اس توسیع کے ایک نئے ورژن کی ضرورت ہے {APP_NAME}. لیکن آپ پہلے ورژن {1} انسٹال کر سکتے ہیں.",
  "EXTENSION_LATEST_INCOMPATIBLE_OLDER": "اس توسیع کا ورژن {0} صرف {APP_NAME} کے پرانے ورژن کے ساتھ کام کرتا ہے. لیکن آپ پہلے ورژن {1} انسٹال کر سکتے ہیں.",
  "EXTENSION_NO_DESCRIPTION": "کوئی وضاحت نہیں",
  "EXTENSION_MORE_INFO": "مزید معلومات...",
  "EXTENSION_ERROR": "توسیع کی خرابی",
  "EXTENSION_KEYWORDS": "اہم الفاظ",
  "EXTENSION_TRANSLATED_USER_LANG": "{0} زبانوں میں ترجمہ کیا گیا ہے، بشمول آپ",
  "EXTENSION_TRANSLATED_GENERAL": "{0} زبانوں میں ترجمہ",
  "EXTENSION_TRANSLATED_LANGS": "یہ توسیع ان زبانوں میں ترجمہ کیا گیا ہے: {0}",
  "EXTENSION_INSTALLED": "نصب",
  "EXTENSION_UPDATE_INSTALLED": "یہ توسیع اپ ڈیٹ ڈاؤن لوڈ کیا گیا ہے اور {APP_NAME} دوبارہ لوڈ ہونے کے بعد انسٹال کیا جائے گا.",
  "EXTENSION_SEARCH_PLACEHOLDER": "تلاش",
  "EXTENSION_MORE_INFO_LINK": "مزید",
  "BROWSE_EXTENSIONS": "ایکسٹنشن براؤز کریں",
  "EXTENSION_MANAGER_REMOVE": "توسیع کو ہٹا دیں",
  "EXTENSION_MANAGER_REMOVE_ERROR": "ایک یا زیادہ توسیع کو ہٹانے میں ناکام: {0}. {APP_NAME} اب بھی دوبارہ لوڈ کریں گے.",
  "EXTENSION_MANAGER_UPDATE": "توسیع اپ ڈیٹ کریں",
  "EXTENSION_MANAGER_UPDATE_ERROR": "ایک یا زیادہ توسیع کو اپ ڈیٹ کرنے میں ناکام: {0}. {APP_NAME} اب بھی دوبارہ لوڈ کریں گے.",
  "EXTENSION_MANAGER_DISABLE": "توسیع کو غیر فعال کریں",
  "EXTENSION_MANAGER_DISABLE_ERROR": "ایک یا زیادہ توسیع کو غیر فعال کرنے میں ناکام: {0}. {APP_NAME} اب بھی دوبارہ لوڈ کریں گے.",
  "MARKED_FOR_REMOVAL": "ہٹانے کے لئے نشان لگا",
  "UNDO_REMOVE": "کالعدم کریں",
  "MARKED_FOR_UPDATE": "اپ ڈیٹ کیلئے نشان لگا دیا گیا",
  "UNDO_UPDATE": "کالعدم کریں",
  "MARKED_FOR_DISABLING": "غیر فعال کے لئے نشان لگا دیا گیا",
  "UNDO_DISABLE": "کالعدم کریں",
  "CHANGE_AND_RELOAD_TITLE": "توسیع تبدیل کریں",
  "CHANGE_AND_RELOAD_MESSAGE": "نشان لگا دیا گیا توسیع کو اپ ڈیٹ کرنے، ہٹانے یا غیر فعال کرنے کے لئے، {APP_NAME} کو دوبارہ لوڈ کرنے کی ضرورت ہوگی. آپ کو غیرمحفوظ شدہ تبدیلیوں کو محفوظ کرنے کے لئے کہا جائے گا۔",
  "REMOVE_AND_RELOAD": "توسیع ہٹا دیں اور دوبارہ لوڈ کریں",
  "CHANGE_AND_RELOAD": "ایکسٹنشن تبدیل کریں اور دوبارہ لوڈ کریں",
  "UPDATE_AND_RELOAD": "اپ ڈیٹ توسیع اور دوبارہ لوڈ کریں",
  "DISABLE_AND_RELOAD": "توسیع غیر فعال کریں اور دوبارہ لوڈ کریں",
  "PROCESSING_EXTENSIONS": "پروسیسنگ توسیع تبدیلیاں...",
  "EXTENSION_NOT_INSTALLED": "توسیع کو ہٹا نہیں سکا {0} کیونکہ یہ انسٹال نہیں کیا گیا تھا.",
  "NO_EXTENSIONS": "ابھی تک کوئی توسیع نصب نہیں ہے. <br>شروعکرنے کے لئے اوپر دستیاب ٹیب پر کلک کریں.",
  "NO_EXTENSION_MATCHES": "کوئی ایکسٹنشن آپ کی تلاش سے میل نہیں کھاتا.",
  "REGISTRY_SANITY_CHECK_WARNING": "نوٹ: یہ توسیع {APP_NAME} خود سے مختلف مصنفین سے آ سکتی ہیں. توسیع کا جائزہ نہیں لیا جاتا ہے اور مکمل مقامی مراعات ہیں. نامعلوم ذریعہ سے توسیع کو انسٹال کرتے وقت محتاط رہیں.",
  "EXTENSIONS_INSTALLED_TITLE": "نصب",
  "EXTENSIONS_DEFAULT_TITLE": "ڈیفالٹ",
  "EXTENSIONS_AVAILABLE_TITLE": "دستیاب",
  "EXTENSIONS_THEMES_TITLE": "موضوعات",
  "EXTENSIONS_UPDATES_TITLE": "اپ ڈیٹس",
  "EXTENSIONS_LAST_UPDATED": "آخری اپ ڈیٹ",
  "EXTENSIONS_DOWNLOADS": "ڈاؤنلوڈ",
  "INLINE_EDITOR_NO_MATCHES": "کوئی میچ دستیاب نہیں ہے۔",
  "INLINE_EDITOR_HIDDEN_MATCHES": "تمام میچ منہدم ہو گئے۔ میچوں کو دیکھنے کے حق میں درج کردہ فائلوں کو بڑھائیں.",
  "CSS_QUICK_EDIT_NO_MATCHES": "آپ کے انتخاب سے ملنے والے موجودہ سی ایس ایس کے قوانین موجود نہیں ہیں. <br> ایکتخلیق کرنے کے لئے “نیا قاعدہ” پر کلک کریں۔",
  "CSS_QUICK_EDIT_NO_STYLESHEETS": "آپ کے منصوبے میں کوئی سٹائل شیٹ نہیں ہیں. <br>سیایس ایس کے قواعد کو شامل کرنے کے لئے ایک بنائیں.",
  "IMAGE_VIEWER_LARGEST_ICON": "سب سے بڑا",
  "UNIT_PIXELS": "پکسلز۔",
  "DEBUG_MENU": "ڈیبگ",
  "ERRORS": "غلطیاں",
  "CMD_SHOW_DEV_TOOLS": "ڈویلپر ٹولز دکھائیں",
  "CMD_REFRESH_WINDOW": "توسیع کے ساتھ دوبارہ لوڈ کریں",
  "CMD_RELOAD_WITHOUT_USER_EXTS": "توسیع کے بغیر دوبارہ لوڈ کریں",
  "CMD_NEW_BRACKETS_WINDOW": "نیا {اپ_NAME} ونڈو",
  "CMD_LAUNCH_SCRIPT_MAC": "کمانڈ لائن شارٹ کٹ انسٹال کریں",
  "CMD_SWITCH_LANGUAGE": "زبان تبدیل کریں",
  "CMD_RUN_UNIT_TESTS": "ٹیسٹ چلائیں",
  "CMD_SHOW_PERF_DATA": "کارکردگی کا ڈیٹا دکھائیں",
  "CMD_ENABLE_LOGGING": "تفصیلی نوشتہ جات کو فعال کریں",
  "CMD_OPEN_BRACKETS_SOURCE": "{APP_NAME} ماخذ کھولیں",
  "CREATING_LAUNCH_SCRIPT_TITLE": "{APP_NAME} کمانڈ لائن شارٹ کٹ",
  "ERROR_CREATING_LAUNCH_SCRIPT": "کمانڈ لائن شارٹ کٹ انسٹال کرتے وقت ایک غلطی ہوئی. <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting'>ازراہِ کرم ان تجاویز کو آزمائیں</a> <br/><br/>وجہ: {0}",
  "ERROR_CLTOOLS_RMFAILED": "موجودہ <code>/usr/local/bin/بریکٹ</code> سملنک کو ہٹانے میں قاصر.",
  "ERROR_CLTOOLS_MKDIRFAILED": "<code>/usr/local/bin</code> ڈائرکٹری بنانے میں نااہل",
  "ERROR_CLTOOLS_LNFAILED": "<code>/usr/مقامی/bin/بریکٹ</code> سملنک بنانے میں نااہل.",
  "ERROR_CLTOOLS_SERVFAILED": "داخلی غلطی.",
  "ERROR_CLTOOLS_NOTSUPPORTED": "اس OS پر کمانڈ لائن شارٹ کٹ کی حمایت نہیں کی جاتی ہے.",
  "LAUNCH_SCRIPT_CREATE_SUCCESS": "کامیابی! اب آپ آسانی سے کمانڈ لائن سے {APP_NAME} شروع کر سکتے ہیں: <code>بریکٹ myFile.txt</code> منصوبوں کو سوئچ کرنے کے لئے ایک فائل یا <code>بریکٹ MyFolder</code> کھولنے کے لئے. <br/><br/>کمانڈلائن سے {APP_NAME} استعمال کرنے کے بارے میں<a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments'>مزید جانیں۔</a>",
  "LANGUAGE_TITLE": "زبان تبدیل کریں",
  "LANGUAGE_MESSAGE": "زبان:",
  "LANGUAGE_SUBMIT": "دوبارہ لوڈ کریں {اپ_نام}",
  "LANGUAGE_CANCEL": "منسوخ کریں",
  "LANGUAGE_SYSTEM_DEFAULT": "سسٹم ڈیفالٹ",
  "HEALTH_DATA_NOTIFICATION": "صحت کی رپورٹ کی ترجیحات",
  "HEALTH_FIRST_POPUP_TITLE": "{APP_NAME} صحت کی رپورٹ",
  "HEALTH_DATA_DO_TRACK": "میں {APP_NAME} کا استعمال کیسے کرتا ہوں اس پر تخلص معلومات کا اشتراک کریں",
  "HEALTH_DATA_NOTIFICATION_MESSAGE": "{APP_NAME} کو بہتر بنانے کے لئے, ہم وقفے وقفے سے محدود بھیجتے ہیں, آپ کس طرح استعمال کے بارے میں core.ai پر <strong>تخلص</strong> اعداد و شمار {APP_NAME}. یہ معلومات آپ کی رازداری کی حفاظت کرتے ہوئے خصوصیات کو ترجیح دینے، کیڑے تلاش کرنے اور استعمال کے مسائل کو حل کرنے میں مدد کرتی ہے۔ <br><br>آپ <strong>مدد > صحت کی رپورٹ کو منتخب کرکے اپنا ڈیٹا دیکھ سکتے ہیں یا ڈیٹا کا اشتراک نہ کرنے کا انتخاب کرسکتے</strong>ہیں۔ <br><br>",
  "HEALTH_DATA_PREVIEW": "{APP_NAME} صحت کی رپورٹ",
  "HEALTH_DATA_PREVIEW_INTRO": "<p>{APP_NAME} کو بہتر بنانے کے لئے, ہم وقفے وقفے سے محدود بھیجتے ہیں, آپ کس طرح استعمال کے بارے میں core.ai پر <strong>تخلص</strong> اعداد و شمار {APP_NAME}. یہ معلومات خصوصیات کو ترجیح دینے، کیڑے ڈھونڈنے اور استعمال کے مسائل کو روکنے میں مدد کرتی ہے۔ </p><p>مندرجہذیل اعداد و شمار کی پیش نظارہ ہے جو آپ کی اگلی صحت رپورٹ میں بھیجے جائیں گے <em>اگر</em> یہ فعال ہے. </p>",
  "INLINE_TIMING_EDITOR_TIME": "ٹائم",
  "INLINE_TIMING_EDITOR_PROGRESSION": "ترقی",
  "BEZIER_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd><kbd>←</kbd><kbd>→</kbd>منتخب مقام منتقل کریں<br><kbd class='text'>شفٹ</kbd>دس یونٹس<br><kbd class='text'>ٹیب</kbd>سوئچ پوائنٹس کی طرف سے منتقل",
  "STEPS_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd>اقدامات میں اضافہ یا کم کریں<br><kbd>←</kbd><kbd>→</kbd>'شروع' یا 'اختتام'",
  "INLINE_TIMING_EDITOR_INVALID": "پرانی قدر <code>{0}</code> درست نہیں ہے، لہذا ڈسپلے کردہ فنکشن کو <code>{1}</code> میں تبدیل کر دیا گیا تھا. دستاویز پہلی ترمیم کے ساتھ اپ ڈیٹ کیا جائے گا.",
  "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP": "موجودہ رنگ",
  "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP": "اصل رنگ",
  "COLOR_EDITOR_RGBA_BUTTON_TIP": "RGBA فارمیٹ",
  "COLOR_EDITOR_HEX_BUTTON_TIP": "ہیکس فارمیٹ",
  "COLOR_EDITOR_HSLA_BUTTON_TIP": "ایچ ایس ایل فارمیٹ",
  "COLOR_EDITOR_0X_BUTTON_TIP": "ہیکس (0X) کی شکل",
  "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR": "{0} (استعمال کیا جاتا ہے {1} وقت)",
  "COLOR_EDITOR_USED_COLOR_TIP_PLURAL": "{0} (استعمال کیا جاتا ہے {1} بار)",
  "CMD_JUMPTO_DEFINITION": "تعریف پر چھلانگ لگائیں",
  "CMD_SHOW_PARAMETER_HINT": "پیرامیٹر اشارہ دکھائیں",
  "NO_ARGUMENTS": "<no parameters>",
  "DETECTED_EXCLUSION_TITLE": "جاوا سکرپٹ فائل تخمینہ مسئلہ",
  "DETECTED_EXCLUSION_INFO": "{APP_NAME} مصیبت پروسیسنگ میں بھاگ گیا <span class='dialog-filename'>{0}</span>. <br><br>یہفائل اب کوڈ اشارے، تعریف پر جائیں یا فوری ترمیم کے لئے عملدرآمد نہیں کیا جائے گا. اس فائل کو دوبارہ فعال کرنے کے لئے، آپ کے منصوبے <code><code>میں.baclets.jscodeHints.detectedexcusions</code> </code> میں ترمیم کریں. <br><br>یہممکنہ طور پر {APP_NAME} بگ ہے. اگر آپ اس فائل کی نقل فراہم کر سکتے ہیں، تو براہ کرم یہاں نام کی <a href='https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue'>فائل کے لنک کے ساتھ ایک بگ</a> فائل کریں۔",
  "CMD_REFACTOR": "ری فیکٹر",
  "CMD_EXTRACTTO_VARIABLE": "متغیر کو نکالیں",
  "CMD_EXTRACTTO_FUNCTION": "فنکشن کو نکالیں",
  "ERROR_TERN_FAILED": "ٹرن سے ڈیٹا حاصل کرنے میں ناکام",
  "ERROR_EXTRACTTO_VARIABLE_NOT_VALID": "انتخاب ایک اظہار کی تشکیل نہیں کرتا",
  "ERROR_EXTRACTTO_FUNCTION_NOT_VALID": "منتخب بلاک بیانات یا ایک اظہار کے سیٹ کی نمائندگی کرنا چاہئے",
  "ERROR_EXTRACTTO_VARIABLE_MULTICURSORS": "متغیر کو نکالیں ملٹی کورسرز میں کام نہیں کرتا",
  "ERROR_EXTRACTTO_FUNCTION_MULTICURSORS": "فنکشن کو نکالنے کے لئے ملٹی کورسرز میں کام نہیں کرتا",
  "EXTRACTTO_FUNCTION_SELECT_SCOPE": "منزل کا دائرہ منتخب کریں",
  "EXTRACTTO_VARIABLE_SELECT_EXPRESSION": "اظہار منتخب کریں",
  "CMD_REFACTORING_RENAME": "نام تبدیل کریں",
  "CMD_REFACTORING_TRY_CATCH": "کوشش کیچ میں لپیٹ",
  "CMD_REFACTORING_CONDITION": "حالت میں لپیٹ",
  "CMD_REFACTORING_GETTERS_SETTERS": "گیٹرز/سیٹرز بنائیں",
  "CMD_REFACTORING_ARROW_FUNCTION": "تیر فنکشن میں تبدیل کریں",
  "DESCRIPTION_CODE_REFACTORING": "جاوا سکرپٹ کوڈ ریفیکٹرنگ کو فعال /غیر فعال کریں",
  "ERROR_TRY_CATCH": "کوشش کیچ بلاک میں لپیٹ کرنے کیلئے درست کوڈ منتخب کریں",
  "ERROR_WRAP_IN_CONDITION": "شرط کے بلاک میں لپیٹ کرنے کیلئے درست کوڈ منتخب کریں",
  "ERROR_ARROW_FUNCTION": "ایک فنکشن اظہار کے اندر کرسر رکھیں",
  "ERROR_GETTERS_SETTERS": "کسی چیز کے اظہار کے رکن پر کرسر رکھیں",
  "ERROR_RENAME_MULTICURSOR": "کثیر cursors کا استعمال کرتے وقت نام تبدیل نہیں کر سکتا",
  "ERROR_RENAME_QUICKEDIT": "اس شناخت کنندہ کا نام تبدیل نہیں کر سکتا، کیونکہ اس فنکشن کے باہر کہیں اور حوالہ دیا گیا ہے",
  "ERROR_RENAME_GENERAL": "منتخب ٹیکسٹ کا نام تبدیل نہیں کیا جا سکتا",
  "JSLINT_NAME": "جے ایس لینٹ",
  "CMD_ENABLE_QUICK_VIEW": "ہوور پر فوری نقطہ نظر",
  "CMD_TOGGLE_RECENT_PROJECTS": "حالیہ پروجیکٹس",
  "DOCS_MORE_LINK": "مزید پڑھیں",
  "COLLAPSE_ALL": "تمام کو ختم کریں",
  "EXPAND_ALL": "تمام توسیع کریں",
  "COLLAPSE_CURRENT": "موجودہ خاتمے",
  "EXPAND_CURRENT": "موجودہ توسیع",
  "RECENT_FILES_DLG_HEADER": "حالیہ فائلیں",
  "RECENT_FILES_DLG_CLEAR_BUTTON_LABEL": "صاف",
  "RECENT_FILES_DLG_CLEAR_BUTTON_TITLE": "کام کرنے والے سیٹ میں نہیں فائلوں کو صاف کریں",
  "DESCRIPTION_CLOSE_BRACKETS": "خود کار طریقے سے بند منحنی خطوط وحدانی، بریکٹ اور قوسین",
  "DESCRIPTION_CLOSE_OTHERS_ABOVE": "کام کرنے والے فائلوں کے سیاق و سباق مینو سے “اوپر دوسروں کو بند کریں” کو ہٹانے کے لئے غلط",
  "DESCRIPTION_CLOSE_OTHERS_BELOW": "کام کرنے والے فائلوں کے سیاق و سباق مینو سے “نیچے دوسروں کو بند کریں” کو ہٹانے کے لئے غلط",
  "DESCRIPTION_CLOSE_OTHERS": "کام کرنے والے فائلوں کے سیاق و سباق مینو سے “دوسروں کو بند کریں” کو ہٹانے کے لئے غلط",
  "DESCRIPTION_CLOSE_TAGS": "ٹیگ بند کرنے کے اختیارات کو سیٹ کرتا ہے",
  "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS": "ٹیگز کی ایک صف جو خود کار طریقے سے بند نہیں ہونا چاہئے",
  "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING": "جب کھولنے والے ٹیگ کا ٹائپ کیا جاتا ہے تو بند کریں",
  "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING": "بند کب کب ٹیگ ٹائپ کیا جاتا ہے",
  "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS": "ٹیگز کی ایک صف جب کھولی گئی تو ایک خالی سطر ہے",
  "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD": "جب اشارے کی سطح میں تبدیلی ہوتی ہے تو ہمیشہ گرنے والے سیکشن مارکر پیدا کرنے کے لئے سچ ہے",
  "DESCRIPTION_CODE_FOLDING_ENABLED": "کوڈ فولڈنگ کو فعال کرنے کے لئے سچ",
  "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER": "آپ گٹر پر ماؤس منتقل صرف اس وقت جب سیکشن کے خاتمے مارکر دکھائی دینے کے لئے سچ",
  "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL": "حد کتنی سطحوں گہری خاتمے تمام لاگو ہوتا ہے",
  "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE": "ایک گرنے والے سیکشن آئکن ظاہر ہونے سے پہلے کم از کم لائنز",
  "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES": "اگر آپ کسی فائل یا پروجیکٹ کو بند کرتے ہیں اور دوبارہ کھولتے ہیں تو منہدم حصوں کو یاد رکھنا درست ہے",
  "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE": "ایڈیٹر میں منتخب کردہ متن پر کوڈ فولڈنگ کو فعال کرنے کے لئے سچ ہے",
  "DESCRIPTION_DISABLED_DEFAULT_EXTENSIONS": "ڈیفالٹ ایکسٹنشن جو غیر فعال ہیں",
  "DESCRIPTION_ATTR_HINTS": "ایچ ٹی ایم ایل وصف اشارے کو فعال کر/غیر فعال",
  "DESCRIPTION_CSS_PROP_HINTS": "سی ایس سیس/کم/SCSS جائیداد اشارے کو فعال کریں/غیر فعال کریں",
  "DESCRIPTION_JS_HINTS": "جاوا سکرپٹ کوڈ اشارے کو فعال کریں/",
  "DESCRIPTION_JS_HINTS_TYPE_DETAILS": "جاوا سکرپٹ کوڈ اشارے میں ڈیٹا ٹائپ کی تفصیلات کو فعال کر/غیر فعال کریں",
  "DESCRIPTION_PREF_HINTS": "ترجیحات کوڈ اشارے کو فعال/غیر فعال کریں",
  "DESCRIPTION_SPECIAL_CHAR_HINTS": "ایچ ٹی ایم ایل ادارے اشارے کو فعال /غیر فعال کریں",
  "DESCRIPTION_SVG_HINTS": "SVG کوڈ اشارے کو فعال کریں/غیر فعال کریں",
  "DESCRIPTION_HTML_TAG_HINTS": "ایچ ٹی ایم ایل ٹیگ اشارے کو فعال/غیر فعال کریں",
  "DESCRIPTION_URL_CODE_HINTS": "ایچ ٹی ایم ایل اور سی ایس ایس/کم/ایس ایس ایس میں یو آر ایل کے اشارے کو فعال /غیر فعال کریں",
  "DESCRIPTION_DRAG_DROP_TEXT": "ڈریگ اور ڈراپ فعالیت کو فعال /غیر فعال کریں",
  "DESCRIPTION_HEALTH_DATA_TRACKING": "صحت ڈیٹا ٹریکنگ کو فعال کریں",
  "DESCRIPTION_HIGHLIGHT_MATCHES": "پورے دستاویز میں ملاپ کی تار کی خودکار روشنی کو فعال کرتا ہے",
  "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN": "تمام ڈور کو نمایاں کریں جو ٹوکن سے ملتے ہیں کرسر فی الحال ہے (کوئی انتخاب کی ضرورت نہیں ہے)",
  "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY": "صرف اس وقت نمایاں کریں جب انتخاب مکمل ٹوکن ہو",
  "DESCRIPTION_INSERT_HINT_ON_TAB": "ٹیب پر فی الحال منتخب کردہ کوڈ اشارہ داخل کرنے کے لئے سچ ہے",
  "DESCRIPTION_NO_HINTS_ON_DOT": "خود کار طریقے سے جے ایس کوڈ اشارے کو ظاہر نہیں کرنے کے لئے سچ ہے. ٹائپ کیا جاتا ہے",
  "DESCRIPTION_JSLINT_OPTIONS": "jایس لینٹ کے لئے ڈیفالٹ اختیارات کے ساتھ ایک اعتراض",
  "DESCRIPTION_JSLINT_OPTIONS_ASS": "تفویض اظہار کی اجازت دینے کے لئے سچ",
  "DESCRIPTION_JSLINT_OPTIONS_BITWISE": "bitWise آپریٹرز کی اجازت دینے کے لئے سچ",
  "DESCRIPTION_JSLINT_OPTIONS_BROWSER": "صحیح اگر معیاری براؤزر گلوبلوں کو پیش وضاحتی ہونا چاہئے",
  "DESCRIPTION_JSLINT_OPTIONS_CLOSURE": "گوگل بندش کی اجازت دینے کے لئے سچ ہے",
  "DESCRIPTION_JSLINT_OPTIONS_CONTINUE": "“جاری رکھیں” بیان کی اجازت دینے کے لئے سچ",
  "DESCRIPTION_JSLINT_OPTIONS_COUCH": "سچ ہے اگر CouchDB گلوبلوں کو پیش وضاحتی ہونا چاہئے",
  "DESCRIPTION_JSLINT_OPTIONS_DEBUG": "ڈیبگر کے بیانات کی اجازت دینے کے لئے سچ",
  "DESCRIPTION_JSLINT_OPTIONS_DEVEL": "درست اگر براؤزر globals ترقی میں مفید پیش وضاحتی ہونا چاہئے",
  "DESCRIPTION_JSLINT_OPTIONS_EQEQ": "اجازت دینے کے لئے سچ == اور! =",
  "DESCRIPTION_JSLINT_OPTIONS_ES6": "سچ ہے اگر ES6 گلوبلوں کو پیش وضاحتی ہونا چاہئے",
  "DESCRIPTION_JSLINT_OPTIONS_EVIL": "eval اجازت دینے کے لئے سچ",
  "DESCRIPTION_JSLINT_OPTIONS_FORIN": "غیر فلٹرڈ کی اجازت دینے کے لئے سچ “کے لئے... میں”",
  "DESCRIPTION_JSLINT_OPTIONS_INDENT": "مخصوص ٹیب کی چوڑائی مقرر کریں",
  "DESCRIPTION_JSLINT_OPTIONS_MAXERR": "اطلاع دی گئی تنبیہات کی زیادہ سے زیادہ تعداد",
  "DESCRIPTION_JSLINT_OPTIONS_MAXLEN": "ایک لائن میں حروف کی زیادہ سے زیادہ تعداد",
  "DESCRIPTION_JSLINT_OPTIONS_NEWCAP": "غیر سرمایہ دار تعمیرات کی اجازت دینے کے لئے سچ ہے",
  "DESCRIPTION_JSLINT_OPTIONS_NODE": "سچ ہے اگر Node.js گلوبلز پیش وضاحتی ہونا چاہئے",
  "DESCRIPTION_JSLINT_OPTIONS_NOMEN": "شناخت کنندگان میں لٹکانے والے انڈرسکور کی اجازت دینے کے لئے سچ",
  "DESCRIPTION_JSLINT_OPTIONS_PASSFAIL": "پہلی غلطی پر روکنے کے لئے سچ",
  "DESCRIPTION_JSLINT_OPTIONS_PLUSPLUS": "کی اجازت دینے کے لئے سچ ++ اور —",
  "DESCRIPTION_JSLINT_OPTIONS_REGEXP": "اجازت دینے کے لئے سچ ہے. اور [^...]. Regexp میں",
  "DESCRIPTION_JSLINT_OPTIONS_RHINO": "سچ ہے اگر رائنو گلوبلوں کو پیش وضاحتی ہونا چاہئے",
  "DESCRIPTION_JSLINT_OPTIONS_SLOPPY": "لاپتہ `سخت استعمال کریں' پراگما کی اجازت دینے کے لئے سچ",
  "DESCRIPTION_JSLINT_OPTIONS_STUPID": "اگر بلاک کرنا درست ہے ('... سنکی') طریقوں کو استعمال کیا جا سکتا ہے.",
  "DESCRIPTION_JSLINT_OPTIONS_SUB": "نااہل سبسکرائب کرنے کی اجازت دینے کے لئے سچ",
  "DESCRIPTION_JSLINT_OPTIONS_TODO": "TODO تبصرے اجازت دینے کے لئے سچ",
  "DESCRIPTION_JSLINT_OPTIONS_UNPARAM": "غیر استعمال شدہ پیرامیٹرز اجازت دینے کے لئے سچ",
  "DESCRIPTION_JSLINT_OPTIONS_VARS": "ایک تقریب میں 1 سے زیادہ تار کی اجازت دینے کے لئے سچ",
  "DESCRIPTION_JSLINT_OPTIONS_WHITE": "سفید خلائی قوانین کو نظر انداز کرنے کے لئے سچ",
  "DESCRIPTION_LANGUAGE": "زبان کی مخصوص ترتیبات",
  "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS": "فائل کی توسیع سے زبان کے نام پر اضافی میپنگ",
  "DESCRIPTION_LANGUAGE_FILE_NAMES": "فائل کے نام سے زبان کے نام پر اضافی میپنگ",
  "DESCRIPTION_LINEWISE_COPY_CUT": "کوئی انتخاب نہیں ہے جب کاپی اور کاٹ کر کاپی یا ان میں curcors ہے کہ پوری لائنوں کاٹ جائے گا.",
  "DESCRIPTION_INPUT_STYLE": "CodeIrrr ان پٹ اور فوکس کو سنبھالنے کا طریقہ منتخب کرتا ہے۔ یہ textarea ہوسکتا ہے، جو ڈیفالٹ، یا قابل اطمینان ہے جو اسکرین قارئین کے لئے بہتر ہے (غیر مستحکم)",
  "DESCRIPTION_LINTING_ENABLED": "کوڈ معائنہ کو فعال کرنے کے لئے سچ",
  "DESCRIPTION_ASYNC_TIMEOUT": "ملی سیکنڈ میں وقت جس کے بعد asynchronous linters وقت باہر",
  "DESCRIPTION_LINTING_PREFER": "سب سے پہلے چلانے کے لئے linters کی صف",
  "DESCRIPTION_LIVE_DEV_MULTIBROWSER": "تجرباتی لائیو پیش نظارہ کو فعال کرنے کے لئے سچ",
  "DESCRIPTION_USE_PREFERED_ONLY": "linting.ترجیح صرف میں مخصوص فراہم کرنے والے کو چلانے کے لئے سچ",
  "DESCRIPTION_MAX_CODE_HINTS": "زیادہ سے زیادہ کوڈ اشارے ایک بار میں دکھائے گئے",
  "DESCRIPTION_PATH": "راہ مخصوص ترتیبات",
  "DESCRIPTION_PROXY": "پراکسی سرور کا URL توسیع کی تنصیب کے لئے استعمال کیا جاتا ہے",
  "DESCRIPTION_SCROLL_PAST_END": "دستاویز کے اختتام سے باہر طومار کرنے کو فعال کرنے کے لئے سچ",
  "DESCRIPTION_SHOW_CODE_HINTS": "تمام کوڈ اشارے کو غیر فعال کرنے کے لئے غلط",
  "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING": "جب آپ کے پاس ٹیکسٹ انتخاب ہوتا ہے تو جھپٹکا کرسر نظر آتا ہے",
  "DESCRIPTION_SHOW_LINE_NUMBERS": "کوڈ کے بائیں جانب “گٹر” میں لائن نمبر دکھانے کے لئے سچ ہے",
  "DESCRIPTION_SMART_INDENT": "ایک نیا بلاک بناتے وقت خود کار طریقے سے اشارے",
  "DESCRIPTION_SOFT_TABS": "نرم ٹیب کے رویے کو بند کرنے کے لئے غلط",
  "DESCRIPTION_SORT_DIRECTORIES_FIRST": "اس منصوبے کے درخت میں سب سے پہلے ڈائریکٹریز کو ترتیب دینے کے لئے سچ ہے",
  "DESCRIPTION_SPACE_UNITS": "خلائی بنیاد پر اندراج کے لئے استعمال کرنے کے لئے خالی جگہوں کی تعداد",
  "DESCRIPTION_STATIC_SERVER_PORT": "پورٹ نمبر جسے بلٹ ان سرور کو براہ راست پیش نظارہ کے لئے استعمال کرنا چاہئے",
  "DESCRIPTION_STYLE_ACTIVE_LINE": "کرسر پر لائن کے پس منظر کا رنگ نمایاں کرنے کے لئے سچ ہے",
  "DESCRIPTION_TAB_SIZE": "ٹیبز کے لئے ظاہر کرنے کے لئے خالی جگہوں کی تعداد",
  "DESCRIPTION_USE_TAB_CHAR": "خالی جگہوں کے بجائے ٹیبز استعمال کرنے کے لئے سچ",
  "DESCRIPTION_UPPERCASE_COLORS": "ان لائن رنگین ایڈیٹر میں بڑے ہیکس رنگ پیدا کرنے کے لئے سچ ہے",
  "DESCRIPTION_WORD_WRAP": "ویو پورٹ کی چوڑائی سے بڑھ جانے والی لائنیں لپیٹ دیں",
  "DESCRIPTION_SEARCH_AUTOHIDE": "جیسے ہی ایڈیٹر کی توجہ مرکوز ہوتی ہے تلاش کو بند کردیں",
  "DESCRIPTION_DETECTED_EXCLUSIONS": "فائلوں کی ایک فہرست جو ٹرن کو کنٹرول سے باہر چلانے کے لئے پتہ چلا ہے",
  "DESCRIPTION_INFERENCE_TIMEOUT": "فائلوں کو سمجھنے کی کوشش کرتے وقت وقت وقت کی رقم جس کے بعد ٹرن کا وقت ہوگا",
  "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR": "اسٹیٹس بار میں غلطیوں کو ظاہر کرنے کے لئے سچ",
  "DESCRIPTION_QUICK_VIEW_ENABLED": "فوری نقطہ نظر کو فعال کرنے کے لئے سچ",
  "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW": "یو آر ایل لاپتہ ملانے کے لئے تصویر پیش نظارہ ظاہر کرنے کے لئے سچ",
  "DESCRIPTION_THEME": "ایک {APP_NAME} مرکزی خیال، موضوع منتخب کریں",
  "DESCRIPTION_USE_THEME_SCROLLBARS": "اپنی مرضی کے مطابق سکرال سلاخوں اجازت دینے کے لئے سچ",
  "DESCRIPTION_LINTING_COLLAPSED": "linting کے پینل کو ختم کرنے کے لئے سچ",
  "DESCRIPTION_FONT_FAMILY": "فونٹ خاندان تبدیل کریں",
  "DESCRIPTION_FONT_SIZE": "فونٹ کا سائز تبدیل کریں؛ مثال کے طور پر 13px",
  "DESCRIPTION_FIND_IN_FILES_NODE": "نوڈ کی بنیاد پر تلاش کو فعال کرنے کے لئے سچ",
  "DESCRIPTION_FIND_IN_FILES_INSTANT": "فوری تلاش کو فعال کرنے کے لئے سچ",
  "DESCRIPTION_FONT_SMOOTHING": "میک صرف: “subpixel-antialiased” ذیلی پکسل antialiasing فعال کرنے کے لئے یا “antialiased” سرمئی پیمانے antialiasing کے لئے",
  "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW": "تقسیم کے نقطہ نظر میں افتتاحی ترجیحات فائل کو غیر فعال کرنے کے لئے غلط",
  "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE": "بائیں میں/اوپر پین میں صارف کی ترجیحات فائل کھولنے کے لئے غلط",
  "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED": "پین ہیڈر بند بٹن کے ذریعے پین سے آخری فائل بند ہونے کے بعد پین کو ختم کرنے کے لئے سچ ہے",
  "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS": "ہیڈر پر بند اور فلپ ویو بٹن دکھانے کے لئے ٹوگل کریں۔",
  "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT": "/*\n * یہ ترجیحات کی حمایت کے ساتھ صرف پڑھنے کے لئے فائل ہے\n * {APP_NAME} کی طرف سے.\n * اپنی ترجیحات میں ترمیم کرنے کے لئے اس فائل کو ایک حوالہ کے طور پر استعمال کریں\n * فائل “بریکٹ. jsin” دوسرے پین میں کھولی گئی.\n * اندر ترجیحات استعمال کرنے کے بارے میں مزید معلومات کے لئے\n * {APP_NAME}، https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences پر ویب صفحہ کا حوالہ دیتے ہیں\n */",
  "DEFAULT_PREFERENCES_JSON_DEFAULT": "ڈیفالٹ",
  "DESCRIPTION_PURE_CODING_SURFACE": "کوڈ صرف موڈ کو فعال کرنے اور {APP_NAME} میں دیگر تمام UI عناصر کو چھپانے کے لئے سچ",
  "DESCRIPTION_INDENT_LINE_COMMENT": "لائن تبصرے کے indinting کو فعال کرنے کے لئے سچ ہے",
  "DESCRIPTION_RECENT_FILES_NAV": "حالیہ فائلوں میں نیویگیشن کو فعال /غیر فعال کریں",
  "DESCRIPTION_LIVEDEV_WEBSOCKET_PORT": "پورٹ جس پر ویب ساکٹ سرور لائیو پیش نظارہ کے لئے چلتا ہے",
  "DESCRIPTION_LIVE_DEV_HIGHLIGHT_SETTINGS": "لائیو پیش نظارہ کی ترتیبات نمایاں کریں",
  "DESCRIPTION_LIVEDEV_ENABLE_REVERSE_INSPECT": "لائیو پیش منظر ریورس معائنہ غیر فعال کرنے کے لئے غلط",
  "DOWNLOAD_FAILED": "ڈاؤن لوڈ ناکام ہوا۔",
  "DOWNLOAD_COMPLETE": "مکمل ڈاؤن لوڈ کریں!",
  "UPDATE_SUCCESSFUL": "کامیاب اپ ڈیٹ کریں!",
  "UPDATE_FAILED": "اپ ڈیٹ ناکام ہو گیا!",
  "VALIDATION_FAILED": "توثیق ناکام ہو گئی!",
  "INITIALISATION_FAILED": "ابتداء ناکام ہو گئی!",
  "CLEANUP_FAILED": "صاف اپ ناکام ہو گیا!",
  "WARNING_TYPE": "انتباہ!",
  "CLICK_RESTART_TO_UPDATE": "بریکٹ کو اپ ڈیٹ کرنے کیلئے دوبارہ شروع کریں پر کلک کریں۔",
  "UPDATE_ON_NEXT_LAUNCH": "اپ ڈیٹ کو دوبارہ لانچ پر لاگو کیا جائے گا.",
  "GO_TO_SITE": "<a href = \"http://brackets.io/ “> بریکٹس.io </a> پر دوبارہ کوشش کرنے کے لیے جائیں۔",
  "INTERNET_UNAVAILABLE": "کوئی انٹرنیٹ کنکشن دستیاب نہیں ہے۔",
  "UPDATEDIR_READ_FAILED": "اپ ڈیٹ ڈائرکٹری پڑھا نہیں جا سکا.",
  "UPDATEDIR_CLEAN_FAILED": "اپ ڈیٹ ڈائرکٹری صاف نہیں کیا جا سکا.",
  "INITIAL_DOWNLOAD": "اپ ڈیٹ ڈاؤن لوڈ کر رہا ہے",
  "RETRY_DOWNLOAD": "ڈاؤن لوڈ ناکام ہوا۔ دوبارہ کوشش کر رہا ہے... کوشش ",
  "VALIDATING_INSTALLER": "مکمل ڈاؤن لوڈ کریں! انسٹالر کی توثیق...",
  "CHECKSUM_DID_NOT_MATCH": "چیکسم مماثل نہیں ہوا۔",
  "INSTALLER_NOT_FOUND": "انسٹالر نہیں ملا.",
  "DOWNLOAD_ERROR": "ڈاؤن لوڈ کرتے وقت خرابی ہوئی.",
  "NETWORK_SLOW_OR_DISCONNECTED": "نیٹ ورک منقطع یا بہت سست ہے.",
  "RESTART_BUTTON": "دوبارہ شروع کریں",
  "LATER_BUTTON": "بعد میں",
  "DESCRIPTION_AUTO_UPDATE": "بریکٹ آٹو اپ ڈیٹ کو فعال/غیر فعال کریں",
  "AUTOUPDATE_ERROR": "غلطی!",
  "AUTOUPDATE_IN_PROGRESS": "ایک اپ ڈیٹ پہلے ہی جاری ہے.",
  "NUMBER_WITH_PERCENTAGE": "{0}%",
  "CMD_FIND_RELATED_FILES": "متعلقہ فائلیں تلاش کریں",
  "PHP_VERSION_INVALID": "پی ایچ پی کے ورژن کی تجزیہ کرنے میں خرابی. براہ کرم “پی ایچ پی —ورژن” کمانڈ کی آؤٹ پٹ چیک کریں.",
  "PHP_UNSUPPORTED_VERSION": "پی ایچ پی سے متعلقہ آلات جیسے کوڈ اشارے، پیرامیٹر اشارے، تعریف پر چھلانگ اور زیادہ کو چالو کرنے کے لئے پی ایچ پی 7 رن ٹائم انسٹال کریں. ورژن ملا: {0}",
  "PHP_EXECUTABLE_NOT_FOUND": "پی ایچ پی رن ٹائم نہیں ملا. PHP7 رن ٹائم انسٹال کریں اور پی ایچ پی کی ترجیحات میں مناسب طریقے سے “ایگزیکٹیبل پیتھ” کو اپ ڈیٹ کریں اس سے پی ایچ پی سے متعلق ٹول جیسے کوڈ اشارے، پیرامیٹر اشارے، تعریف پر چھلانگ وغیرہ قابل بناتا ہے۔",
  "PHP_PROCESS_SPAWN_ERROR": "پی ایچ پی کے عمل کو شروع کرنے کے دوران غلطی کوڈ {0} کا سامنا کرنا پڑا.",
  "PHP_SERVER_ERROR_TITLE": "خرابی",
  "PHP_SERVER_MEMORY_LIMIT_INVALID": "آپ کی فراہم کردہ میموری کی حد غلط ہے. درست قدر مقرر کرنے کے لئے پی ایچ پی کی ترجیحات کا جائزہ لیں.",
  "DESCRIPTION_PHP_TOOLING_CONFIGURATION": "پی ایچ پی ٹولنگ ڈیفالٹ ترتیب ترتیبات",
  "OPEN_PREFERENNCES": "اوپن ترجیحات",
  "LANGUAGE_TOOLS_PREFERENCES": "زبان کے ٹولز کے لئے ترجیحات",
  "FIND_ALL_REFERENCES": "تمام حوالہ جات تلاش کریں",
  "REFERENCES_IN_FILES": "حوالہ جات",
  "REFERENCE_IN_FILES": "حوالہ دینا",
  "REFERENCES_NO_RESULTS": "موجودہ کرسر کی پوزیشن کے لئے دستیاب کوئی حوالہ نہیں",
  "CMD_FIND_DOCUMENT_SYMBOLS": "دستاویز علامات تلاش کریں",
  "CMD_FIND_PROJECT_SYMBOLS": "پراجیکٹ علامات تلاش کریں",
  "REMOTE_DEBUGGING_ENABLED": "مقامی ہاسٹ پر ریموٹ ڈیبگنگ فعال ہے:",
  "REMOTE_DEBUGGING_PORT_INVALID": "پورٹ {0} پر ریموٹ ڈیبگنگ فعال نہیں کر سکتا۔ پورٹ نمبر {1} اور {2} کے درمیان ہونا چاہئے.",
  "DESCRIPTION_EXTERNAL_APPLICATION_ASSOCIATE": "بیرونی ایپلی کیشنز کو فائل کی توسیع کے لئے میپنگ. نحو: \"<file_type>“: “<Default|Application Name|Application Path>”، فائل کی قسم کے لیے سسٹم ڈیفالٹ ایپلیکیشن میں فائلیں کھولنے کے لیے “ڈیفالٹ” استعمال کریں۔",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_TITLE": "بیرونی ایڈیٹرز میں گرافک فائلیں کھولیں.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_MSG": "آپ کے موجودہ فولڈر میں گرافک فائل کی اقسام ہیں جو {APP_NAME} کے ذریعہ معاونت نہیں کی جاتی ہیں۔ <br/>ابآپ مخصوص فائل کی اقسام کو بیرونی ایڈیٹرز کے ساتھ منسلک کرسکتے ہیں. ایک بار منسلک ہونے کے بعد، آپ فائل ٹری میں فائلوں پر ڈبل کلک کرکے اپنے ڈیفالٹ ایپلی کیشنز میں.xd، .mpd، .jpg، .ai، .svg جیسے گرافک فائلیں کھول سکتے ہیں. <br/><br/>گرافکفائل کی اقسام کو ان کے متعلقہ ڈیفالٹ ایپلی کیشنز کے ساتھ منسلک کرنے کے لئے براہ کرم 'اوک' بٹن پر کلک کریں.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_CNF_MSG": "مندرجہ ذیل فائل کی اقسام کو ڈیفالٹ ایپلی کیشنز کے ساتھ کامیابی سے منسلک کیا گیا ہے. <br/>{0} آپ کے پاس اپنی ترجیح کو تبدیل کرنے کا اختیار ہے کہ آیا آپ “ڈیبگ->اوپن ترجیحات فائل” مینو پر جانے سے بریکٹ میں نئی فائل کی قسم کے ایسوسی ایشنز کو حذف کریں/شامل کریں.",
  "UNSUPPORTED_BROWSER": "براؤزر کی سہولت نہیں ہے",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER": "براؤزر اوپن فولڈر کی حمایت نہیں کرتا",
  "UNSUPPORTED_BROWSER_MESSAGE_LINE1": "براہ کرم ذیل میں سے کسی ایک کی حمایت کردہ براؤزر کا استعمال کریں.",
  "UNSUPPORTED_BROWSER_MESSAGE_LINE2": " ہم زیادہ براؤزرز میں فینکس دستیاب بنانے کے لئے سخت محنت کر رہے ہیں. آپ اس مکالمہ کو بند کر سکتے ہیں، لیکن فینکس میں کچھ خصوصیات اس براؤزر میں کام نہیں کریں گے.",
  "CANNOT_PUBLISH_LARGE_PROJECT": "بڑے پروجیکٹ شائع نہیں کر سکتے",
  "CANNOT_PUBLISH_LARGE_PROJECT_MESSAGE": "فینکس تجرباتی الفا میں اب بھی ہے. ہم نے ابھی تک 500 فائلوں سے زائد منصوبوں کے مطابقت پذیری کو فعال نہیں کیا ہے.",
  "SHARE_WEBSITE": "ویب سائٹ شائع کریں اور اشتراک کریں؟",
  "PUBLISH": "شائع کریں",
  "PUBLISH_CONSENT_MESSAGE": "تبدیلیوں کو فوری طور پر پیش نظارہ کریں اور دوسروں کے ساتھ اپنی ویب سائٹ کا اشتراک کریں. فینکس {0} میں آپ کے لئے اس ویب سائٹ کو شائع کر سکتا ہے. شائع شدہ لنکس 7 دنوں کی مدت کے لئے درست ہوں گے. </br>کیاآپ اپنی ویب سائٹ شائع اور اشتراک کرنا چاہتے ہیں؟",
  "PUBLISH_SYNC_IN_PROGRESS": "پیش نظارہ کے لئے پیش رفت میں مطابقت پذیری...",
  "PUBLISH_PAGE": "اس سائٹ کو شائع کرنے اور اشتراک کرنے کے لئے کلک کریں",
  "PUBLISH_VIEW_PAGE": "شائع صفحہ دیکھنے کے لئے کلک کریں",
  "MISSING_FIELDS": "لاپتہ فیلڈز",
  "PLEASE_FILL_ALL_REQUIRED": "براہ کرم سرخ رنگ میں نمایاں تمام ضروری شعبوں کو بھریں",
  "CODE_EDITOR": "کوڈ ایڈیٹر",
  "BUILD_THE_WEB": "ویب کی تعمیر",
  "IMPORT_PROJECT": "پراجیکٹ درآمد کریں",
  "GITHUB_PROJECT": "گتب پروجیکٹ",
  "NEW_PROJECT_FROM_GITHUB": "گہب سے نیا پروجیکٹ",
  "GITHUB_REPO_URL": "گٹ ہب ریپو یو آر ایل:",
  "CREATE_PROJECT": "پراجیکٹ بنائیں",
  "SETTING_UP_PROJECT": "پروجیکٹ کی ترتیب",
  "LOCATION": "مقام:",
  "DOWNLOADING": "ڈاؤن لوڈ کر رہا ہے...",
  "DOWNLOAD_FAILED_MESSAGE": "یقینی بنائیں کہ ڈاؤن لوڈ کردہ URL درست ہے۔ </br>اینبی: جیسا کہ فینکس الفا میں ہے، 25 MB سے زیادہ نجی ریپوز اور Github یو آر ایل کی اجازت نہیں ہے.",
  "PLEASE_SELECT_A_FOLDER": "براہ کرم ایک فولڈر منتخب کریں...",
  "UNZIP_IN_PROGRESS": "فائلوں کو غیر زپ کرنا...",
  "UNZIP_FAILED": "خرابی: غیر زپنگ ناکام ہوگئی۔",
  "CONFIRM_REPLACE_TITLE": "تبدیل کرنے کی تصدیق کریں",
  "KEEP_BOTH": "دونوں رکھیں",
  "EXPLORE": "ایچ ٹی ایم ایل گیمز",
  "BLOG": "بلاگ",
  "PHOENIX_DEFAULT_PROJECT": "ڈیفالٹ پروجیکٹ",
  "PROJECT_NAME": "پروجیکٹ کا نام:",
  "NEW_HTML": "نیا ایچ ٹی ایم ایل پروجیکٹ",
  "LICENSE": "لائسنس:",
  "CREDITS": "کریڈٹ:",
  "PREVIEW": "پیش نظارہ",
  "BUILD_WEBSITE": "ویب سائٹ کی تعمیر",
  "VIEW_MORE": "مزید دیکھیے...",
  "NEW_PROJECT_NOTIFICATION": "نیا پروجیکٹ<br/>بنانے کے لئے اس آئکن پر کلک کریں. </br> <a href='#' style='float:right;'>ٹھیک ہے</a>",
  "DEFAULT_PROJECT_NOTIFICATION": "فینکس میں <br/><b>پہلے سے طے شدہ منصوبے</b> کو کھولنے کے لئے یہاں کلک کریں. </br> <a href='#' style='float:right;'>ٹھیک ہے</a>",
  "DIRECTORY_REPLACE_MESSAGE": "منتخب شدہ فولڈر <span class='dialog-filename'>{0}</span> خالی نہیں ہے۔ کیا آپ کو یقین ہے کہ آپ فولڈر کے مواد کو منصوبے کے ساتھ تبدیل کرنا چاہتے ہیں؟",
  "BUILD_WEBSITE_SECTION": "ویب سائٹ کی تعمیر",
  "LEARN_SECTION": "مثالوں کے ساتھ سیکھیں",
  "WEBPAGE_HOME_PAGE": "ہوم پیج کی ترتیب",
  "WEBPAGE_BLOG": "بلاگ پیج",
  "WEBPAGE_DASHBOARD": "ایچ ٹی ایم ایل ڈیش بورڈ",
  "WEBPAGE_BOOTSTRAP_EXAMPLES": "بوٹسٹریپ مثالیں",
  "GUIDED_FILES_SIDEBAR": "ایک HTML فائل <a href='#' style='float:right;'>ٹھیک ہے</a>منتخب </br> کریں",
  "GUIDED_LIVE_PREVIEW": "کچھ کوڈ میں تبدیلی کریں اور پیش نظارہ دیکھنے کے لئے فائل محفوظ کریں. </br> <a href='#' style='float:right;'>ٹھیک ہے</a>",
  "TEST_TRANSLATE": "امتحان"
});