/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "系统默认",
  "PROJECT_BUSY": "项目操作进行中",
  "DUPLICATING": "复制 {0} 中",
  "MOVING": "移动 {0} 中",
  "COPYING": "复制 {0} 中",
  "DELETING": "删除 {0} 中",
  "DELETE_TO_TRASH": "将 {0} 移至回收站",
  "DELETE_TO_RECYCLE_BIN": "将 {0} 移至回收站",
  "RENAMING": "重命名中",
  "STORED_IN_YOUR_BROWSER": "存储在您的浏览器中",
  "SUPPORT_US_OPEN_COLLECTIVE": "在 GitHub 赞助商上支持我们",
  "GENERIC_ERROR": "(错误 {0})",
  "NOT_FOUND_ERR": "未能发现该文件",
  "NOT_READABLE_ERR": "无法读取该文件。",
  "EXCEEDS_MAX_FILE_SIZE": "{APP_NAME} 不能打开大于 {0} MB 的文件。",
  "NO_MODIFICATION_ALLOWED_ERR": "无法修改此目录。",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "你没有权限做此次修改。",
  "CONTENTS_MODIFIED_ERR": "该文件已经在 {APP_NAME} 之外被修改。",
  "UNSUPPORTED_ENCODING_ERR": "{APP_NAME} 暂时仅支持UTF-8编码的文本文档。",
  "ENCODE_FILE_FAILED_ERR": "{APP_NAME} 无法编码文件内容。",
  "DECODE_FILE_FAILED_ERR": "{APP_NAME} 无法解码文件内容。",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "{APP_NAME} 当前不支持 UTF-16 编码的文本文件。",
  "FILE_EXISTS_ERR": "该文件已存在。",
  "FILE": "个文件",
  "FILE_TITLE": "文件",
  "DIRECTORY": "目录",
  "DIRECTORY_TITLE": "目录",
  "DIRECTORY_NAMES_LEDE": "目录名",
  "FILENAMES_LEDE": "文件名",
  "FILENAME": "文件名",
  "DIRECTORY_NAME": "目录名",
  "ERROR_LOADING_PROJECT": "无法加载此项目。",
  "OPEN_DIALOG_ERROR": "显示[打开文件]对话框发生错误。 (错误 {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "打开目录 <span class='dialog-filename'>{0}</span> 发生错误。 (错误 {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "读取目录 <span class='dialog-filename'>{0}</span> 发生错误。 (错误 {1})",
  "ZOOM_WITH_SHORTCUTS": "使用键盘快捷键缩放",
  "ZOOM_WITH_SHORTCUTS_DETAILS": "请使用键盘快捷键 <code><i>{0}</i></code> 放大和 <code><i>{1}</i></code> 缩小。",
  "ERROR_OPENING_FILE_TITLE": "打开文件时发生错误",
  "ERROR_OPENING_FILE": "尝试打开文件 <span class='dialog-filename'>{0}</span> 时发生错误。 {1}",
  "ERROR_OPENING_FILES": "尝试打开以下文件发生现错误:",
  "ERROR_RELOADING_FILE_TITLE": "重新加载文件时发生错误",
  "ERROR_RELOADING_FILE": "尝试重新加载文件 <span class='dialog-filename'>{0}</span> 时发生错误。 {1}",
  "ERROR_SAVING_FILE_TITLE": "保存文件时发生错误",
  "ERROR_SAVING_FILE": "尝试保存文件 <span class='dialog-filename'>{0}</span> 时发生错误。 {1}",
  "ERROR_RENAMING_FILE_TITLE": "重命名文件 {0} 失败",
  "ERROR_RENAMING_FILE": "尝试重命名文件 {2} <span class='dialog-filename'>{0}</span> 时发生错误。 {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "文件或目录不是已打开项目的一部分。当前只允许重命名项目中的文件。",
  "ERROR_MOVING_FILE_TITLE": "移动 {0} 时出错",
  "ERROR_MOVING_FILE": "尝试移动{2} <span class='dialog-filename'>{0}</span> 时出错。{1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "无法移动该文件/文件夹，因为它们不是当前项目的一部分。",
  "ERROR_DELETING_FILE_TITLE": "删除文件 {0} 失败",
  "ERROR_DELETING_FILE": "尝试删除文件 {2} <span class='dialog-filename'>{0}</span> 时发生错误。 {1}",
  "INVALID_FILENAME_TITLE": "无效文件名: {0}",
  "CANNOT_PASTE_TITLE": "无法粘贴 {0}",
  "CANNOT_DOWNLOAD_TITLE": "无法下载 {0}",
  "ERR_TYPE_DOWNLOAD_FAILED": "下载 <span class='dialog-filename'>{0}</span> 时出错",
  "ERR_TYPE_PASTE_FAILED": "将 <span class='dialog-filename'>{0}</span> 粘贴到 <span class='dialog-filename'>{1}</span> 时出错",
  "CANNOT_DUPLICATE_TITLE": "无法复制",
  "ERR_TYPE_DUPLICATE_FAILED": "复制 <span class='dialog-filename'>{0}</span> 时出错",
  "ERR_TYPE_DUPLICATE_FAILED_NO_FILE": "请选择要复制的文件。",
  "INVALID_FILENAME_MESSAGE": "{0} 不能以(.)结尾或者包含系统保留字及以下字符：<code class='emphasized'>{1}</code>",
  "ENTRY_WITH_SAME_NAME_EXISTS": "名为 <span class='dialog-filename'>{0}</span> 的文件/文件夹已经存在。",
  "ERROR_CREATING_FILE_TITLE": "创建文件 {0} 出现错误",
  "ERROR_CREATING_FILE": "尝试创建 {0} <span class='dialog-filename'>{1}</span> 时发生错误。 {2}",
  "ERROR_MIXED_DRAGDROP": "无法在打开文件夹的同时打开其他文件",
  "DROP_TO_OPEN_FILES": "拖放打开文件",
  "DROP_TO_OPEN_FILE": "拖放打开文件",
  "DROP_TO_OPEN_PROJECT": "拖放打开文件夹 `{0}` 作为项目",
  "ERROR_KEYMAP_TITLE": "读取用户键映射错误",
  "ERROR_KEYMAP_CORRUPT": "键映射文件不是有效的 JSON 格式。即将打开配置文件以便您修正。",
  "ERROR_LOADING_KEYMAP": "不能打开你的键映射文件，因为它不是 UTF-8 编码的文本文件。",
  "ERROR_RESTRICTED_COMMANDS": "不能将快捷键重新分配给这些命令： {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "不能重新分配这些快捷键： {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "这些命令定义了多个快捷键： {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "这些快捷键上指定了多个命令： {0}",
  "ERROR_INVALID_SHORTCUTS": "这些快捷键是无效的： {0}",
  "ERROR_NONEXISTENT_COMMANDS": "快捷键指向了并不存在的命令： {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "读取配置错误",
  "ERROR_PREFS_RESET_TITLE": "设置已重置 - 需要重启",
  "ERROR_PREFS_PROJECT_LINT": "项目首选项",
  "ERROR_PREFS_PROJECT_LINT_MESSAGE": "错误：项目同时包含 `.brackets.json` 和 `.phcode.json` 文件，导致冲突。请删除 `.brackets.json` 或 `.phcode.json` 然后重新加载项目。",
  "ERROR_PREFS_CORRUPT": "您的配置文件不是有效的 JSON 格式. 即将打开配置文件以便您修正. 为使更改生效, 您需要重启 {APP_NAME}.",
  "ERROR_PREFS_CORRUPT_RESET": "您的 {APP_NAME} 设置已损坏并已重置。请重新启动 {APP_NAME} 使更改生效。",
  "ERROR_PROJ_PREFS_CORRUPT": "您的项目配置文件不是有效的 JSON 格式. 即将打开配置文件以便您修正. 为使更改生效, 您需要重新载入项目.",
  "ERROR_IN_BROWSER_TITLE": "囧! {APP_NAME} 暂无法在浏览器中运行。",
  "ERROR_IN_BROWSER": "{APP_NAME} 是建立在 HTML 上的一个桌面程序, 你可以用它修改本地文件. 可以前往此处下载系统对应的版本<b>github.com/adobe/brackets-shell</b>, 然后重新运行 {APP_NAME}.",
  "ERROR_MAX_FILES_TITLE": "索引文件错误",
  "ERROR_MAX_FILES": "索引文件过多, 可能无法通过索引查找文件。",
  "UNSUPPORTED_DOM_APIS_CONFIRM": "`window.confirm` 和 `window.prompt` API 在 {APP_NAME} 的嵌入式实时预览中不可用。请弹出实时预览以在浏览器中使用这些 API。",
  "ERROR_LAUNCHING_BROWSER_TITLE": "启动浏览器失败",
  "ERROR_CANT_FIND_CHROME": "没有找到 Google Chrome 浏览器, 请确定您已安装了 Chrome 浏览器。",
  "ERROR_LAUNCHING_BROWSER": "启动浏览器时发生错误。 (错误 {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "实时预览错误",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "正在连接浏览器",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "要使用实时预览, 需要重启 Chrome 并打开远程调试功能。<br /><br />你确定重新启动 Chrome 浏览器, 并且打开远程调试功能吗？",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "无法加载实时预览页面",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "实时预览需要一个服务端, 您需要为这个项目指定一个基本 URL 地址。 (如http://127.0.0.1/)",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "试图启动实时预览 HTTP 服务器时出现错误, 请再试一次。",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "更多信息, 请参考<a href='{0}' title='{0}'>实时预览连接错误信息</a>。",
  "LIVE_PREVIEW_HIDE_OVERLAY": "隐藏此消息",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "实时预览",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "实时预览: 连接中…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "实时预览: 初始化…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "实时预览服务器已激活",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "实时预览",
  "LIVE_DEV_TOOLTIP_SHOW_IN_EDITOR": "{0} - 在编辑器中显示…",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "选择要实时预览的文件",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "重新加载页面",
  "LIVE_DEV_TOGGLE_LIVE_HIGHLIGHT": "切换实时预览高亮",
  "LIVE_DEV_CLICK_POPOUT": "将实时预览弹出到新窗口",
  "LIVE_DEV_OPEN_CHROME": "在 Chrome 中打开…",
  "LIVE_DEV_OPEN_SAFARI": "在 Safari 中打开…",
  "LIVE_DEV_OPEN_EDGE": "在 Edge 中打开…",
  "LIVE_DEV_OPEN_FIREFOX": "在 Firefox 中打开…",
  "LIVE_DEV_OPEN_ERROR_TITLE": "在 {0} 中打开实时预览出错",
  "LIVE_DEV_OPEN_ERROR_MESSAGE": "请确保已安装 {0} 浏览器，然后重试。",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "固定或取消固定预览页面",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "实时预览 (由于语法错误没有更新)",
  "LIVE_DEV_SETTINGS": "实时预览设置…",
  "LIVE_DEV_SETTINGS_BANNER": "设置自定义服务器以实时预览 `<b>{0}</b>` 和其他服务器渲染文件（PHP、JSP 等）",
  "LIVE_DEV_SETTINGS_TITLE": "实时预览设置",
  "LIVE_DEV_SETTINGS_STARTUP": "启动时显示实时预览面板",
  "LIVE_DEV_SETTINGS_SERVER_PREFERENCE": "启用自定义开发服务器（true 为启用）",
  "LIVE_DEV_SETTINGS_STARTUP_PREFERENCE": "启动时显示实时预览面板（true 为启用）",
  "LIVE_DEV_SETTINGS_HOT_RELOAD_PREFERENCE": "如果服务器支持热重载并禁用实时预览保存时重载，则为 true",
  "LIVE_DEV_SETTINGS_USE_SERVER": "为此项目使用自定义开发服务器",
  "LIVE_DEV_SETTINGS_SERVE_PREFERENCE": "项目的开发服务器 URL，例如 http://localhost:8000/php",
  "LIVE_DEV_SETTINGS_SERVER_INBUILT": "例如 http://localhost:8000/php - 当前使用内置服务器。",
  "LIVE_DEV_SETTINGS_SERVER_ROOT": "项目中的服务文件夹",
  "LIVE_DEV_SETTINGS_SERVER_ROOT_HELP": "例如 www/（默认为 /）",
  "LIVE_DEV_SETTINGS_SERVER_ROOT_PREF": "开发服务器服务的项目中的路径，例如 www/（默认为 /）",
  "LIVE_DEV_SETTINGS_RELOAD": "服务器支持热重载",
  "LIVE_DEV_SETTINGS_RELOAD_HELP": "一些服务器支持热重载，代码更改会推送到页面而无需完整地重新加载页面。如果您不希望 {APP_NAME} 在每次保存时都重新加载页面，请启用此功能。",
  "LIVE_DEV_SETTINGS_FRAMEWORK": "服务器框架",
  "LIVE_DEV_SETTINGS_FRAMEWORK_CUSTOM": "自定义",
  "LIVE_DEV_SETTINGS_FRAMEWORK_PREFERENCES": "服务器框架，目前仅支持 Docusaurus",
  "LIVE_DEV_SETTINGS_ELEMENT_HIGHLIGHT_PREFERENCE": "在实时预览中，通过“悬停”或“单击”检查元素。默认为“悬停”",
  "LIVE_DEV_SETTINGS_SHOW_RULER_LINES_PREFERENCE": "在实时预览中选择元素时显示测量值。默认为“false”",
  "LIVE_DEV_TOOLBOX_SELECT_PARENT": "选择父级",
  "LIVE_DEV_TOOLBOX_EDIT_TEXT": "编辑文本",
  "LIVE_DEV_TOOLBOX_EDIT_HYPERLINK": "编辑超链接",
  "LIVE_DEV_HYPERLINK_NO_HREF": "未设置 href",
  "LIVE_DEV_HYPERLINK_OPEN_LINK": "打开此链接",
  "LIVE_DEV_HYPERLINK_OPENS_NEW_TAB": "在新标签页中打开",
  "LIVE_DEV_TOOLBOX_DUPLICATE": "创建副本",
  "LIVE_DEV_TOOLBOX_DELETE": "删除",
  "LIVE_DEV_TOOLBOX_AI": "使用 AI 编辑",
  "LIVE_DEV_TOOLBOX_IMAGE_GALLERY": "图片库",
  "LIVE_DEV_TOOLBOX_MORE_OPTIONS": "更多选项",
  "LIVE_DEV_MORE_OPTIONS_CUT": "剪切",
  "LIVE_DEV_MORE_OPTIONS_COPY": "复制",
  "LIVE_DEV_MORE_OPTIONS_PASTE": "粘贴",
  "LIVE_DEV_IMAGE_GALLERY_USE_IMAGE": "下载图片",
  "LIVE_DEV_IMAGE_GALLERY_SELECT_DOWNLOAD_FOLDER": "选择图片下载文件夹",
  "LIVE_DEV_IMAGE_GALLERY_SEARCH_PLACEHOLDER": "搜索图片…",
  "LIVE_DEV_IMAGE_GALLERY_SEARCH_BUTTON": "搜索",
  "LIVE_DEV_IMAGE_GALLERY_LOADING_INITIAL": "正在加载图片…",
  "LIVE_DEV_IMAGE_GALLERY_LOADING_MORE": "载入中…",
  "LIVE_DEV_IMAGE_GALLERY_NO_IMAGES": "未找到图片",
  "LIVE_DEV_IMAGE_GALLERY_LOAD_ERROR": "图片加载失败",
  "LIVE_DEV_IMAGE_GALLERY_CLOSE": "关闭",
  "LIVE_DEV_IMAGE_GALLERY_SELECT_FROM_COMPUTER_TOOLTIP": "从您的设备选择一张图片",
  "LIVE_DEV_IMAGE_GALLERY_SELECT_FROM_COMPUTER": "从设备选择",
  "LIVE_DEV_IMAGE_GALLERY_DIALOG_OVERLAY_MESSAGE": "请在编辑器中选择图片下载位置以继续",
  "LIVE_DEV_IMAGE_GALLERY_OFFLINE_BANNER": "无连接 - 正在以离线模式工作",
  "LIVE_DEV_IMAGE_GALLERY_OFFLINE_RETRY": "重试",
  "LIVE_DEV_IMAGE_GALLERY_CHECKING_CONNECTION": "正在检查连接",
  "LIVE_DEV_IMAGE_GALLERY_STILL_OFFLINE": "仍处于离线状态。请检查您的网络连接。",
  "LIVE_DEV_IMAGE_GALLERY_SELECT_SIZE": "选择图片尺寸",
  "LIVE_DEV_IMAGE_GALLERY_SIZE_THUMBNAIL": "缩略图",
  "LIVE_DEV_IMAGE_GALLERY_SIZE_XS": "头像",
  "LIVE_DEV_IMAGE_GALLERY_SIZE_SM": "卡片",
  "LIVE_DEV_IMAGE_GALLERY_SIZE_MD": "内容",
  "LIVE_DEV_IMAGE_GALLERY_SIZE_REGULAR": "标准",
  "LIVE_DEV_IMAGE_GALLERY_SIZE_LG": "主图",
  "LIVE_DEV_IMAGE_GALLERY_SIZE_XL": "横幅",
  "LIVE_DEV_IMAGE_GALLERY_SIZE_RETINA": "视网膜",
  "LIVE_DEV_IMAGE_GALLERY_ATTRIBUTION_ON": "于 {0}",
  "LIVE_DEV_IMAGE_GALLERY_GET_PRO": "获取 Pro 版",
  "LIVE_DEV_IMAGE_GALLERY_USAGE_THRESHOLD": "您已使用 {0}% 的免费图片搜索次数 ({1}/{2})",
  "LIVE_DEV_TOAST_NOT_EDITABLE": "元素不可编辑 - 由脚本生成",
  "LIVE_DEV_COPY_TOAST_MESSAGE": "元素已复制。使用“粘贴”可将其添加到所选元素之后。",
  "LIVE_DEV_TOAST_FIXED_ELEMENT_DISMISSED": "元素不随页面滚动 - 编辑框已隐藏",
  "LIVE_DEV_IMAGE_FOLDER_DIALOG_TITLE": "选择图片保存文件夹",
  "LIVE_DEV_IMAGE_FOLDER_DIALOG_DESCRIPTION": "选择图片的下载位置：",
  "LIVE_DEV_IMAGE_FOLDER_DIALOG_PLACEHOLDER": "输入文件夹路径（例如：assets/images/）",
  "LIVE_DEV_IMAGE_FOLDER_DIALOG_HELP": "💡 输入文件夹路径，或留空则下载到 'images' 文件夹。",
  "LIVE_DEV_IMAGE_FOLDER_DIALOG_REMEMBER": "针对此项目不再询问",
  "IMAGE_SEARCH_LIMIT_TITLE": "图片搜索次数已达上限",
  "IMAGE_SEARCH_LIMIT_MESSAGE": "您本月的 {0} 次图片搜索已用尽。<br>升级到 Phoenix Pro 付费版，即可解除试用限制并继续搜索。",
  "IMAGE_SEARCH_LIMIT_MESSAGE_THROTTLE": "因需求过高，图片搜索暂时无法使用。<br>升级到 Phoenix Pro 付费版，即可解除试用限制并继续搜索。",
  "IMAGE_SEARCH_PRO_THROTTLE_TITLE": "已达到图片搜索上限",
  "IMAGE_SEARCH_PRO_THROTTLE_MESSAGE": "因需求过高，图片搜索暂时无法使用。此问题通常会在一小时内解决——请稍后重试。",
  "LIVE_DEV_AI_PROMPT_PLACEHOLDER": "让 Phoenix AI 修改此元素……",
  "LIVE_PREVIEW_CUSTOM_SERVER_BANNER": "正在从您的自定义服务器 {0} 获取预览",
  "LIVE_PREVIEW_MODE_TOGGLE_PREVIEW": "切换预览模式 (F8)",
  "LIVE_PREVIEW_MODE_PREVIEW": "预览模式",
  "LIVE_PREVIEW_MODE_HIGHLIGHT": "高亮模式",
  "LIVE_PREVIEW_MODE_EDIT": "编辑模式",
  "LIVE_PREVIEW_EDIT_HIGHLIGHT_ON": "悬停时检查元素",
  "LIVE_PREVIEW_SHOW_RULER_LINES": "显示测量",
  "LIVE_PREVIEW_MODE_PREFERENCE": "'{0}' 仅显示网页，'{1}' 将网页与您的代码连接 - 点击元素可跳转到其代码，反之亦然，'{2}' 提供高亮显示和高级元素操作功能",
  "LIVE_PREVIEW_CONFIGURE_MODES": "配置实时预览模式",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "由于浏览器开发人员工具已打开, 实时预览已关闭。",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "由于浏览器中页面已关闭, 实时预览已关闭",
  "LIVE_DEV_NAVIGATED_AWAY": "由于浏览器打开一个不属于本项目的页面, 实时预览已关闭",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "未知原因 ({0}) 导致实时预览关闭",
  "SAVE_CLOSE_TITLE": "保存更新",
  "SAVE_CLOSE_MESSAGE": "保存 <span class='dialog-filename'>{0}</span> 文件中所做的修改？",
  "SAVE_CLOSE_MULTI_MESSAGE": "是否保存以下文件的修改？",
  "EXT_MODIFIED_TITLE": "外部文件发生变化",
  "CONFIRM_DELETE_TITLE": "删除确认",
  "CONFIRM_FILE_DELETE": "您确定要删除文件 <span class='dialog-filename'>{0}</span> 吗？",
  "CONFIRM_FOLDER_DELETE": "确认要删除目录 <span class='dialog-filename'>{0}</span>？",
  "CONFIRM_FILE_DELETE_TRASH": "您确定要删除文件 <span class='dialog-filename'>{0}</span> 吗？<br>您可以从回收站恢复此文件。",
  "CONFIRM_FOLDER_DELETE_TRASH": "您确定要删除文件夹 <span class='dialog-filename'>{0}</span> 吗？<br>您可以从回收站恢复此文件夹。",
  "CONFIRM_FILE_DELETE_RECYCLE_BIN": "您确定要删除文件 <span class='dialog-filename'>{0}</span> 吗？<br>您可以从回收站恢复此文件。",
  "CONFIRM_FOLDER_DELETE_RECYCLE_BIN": "确定要删除文件夹 <span class='dialog-filename'>{0}</span> 吗？<br>您可以从回收站恢复此文件夹。",
  "MOVE_TO_TRASH": "移至回收站",
  "MOVE_TO_RECYCLE_BIN": "移至回收站",
  "FILE_DELETED_TITLE": "文件已删除",
  "EXT_MODIFIED_WARNING": "<span class='dialog-filename'>{0}</span> 已产生了外部修改，<br /><br />是否保存并覆盖外部修改？",
  "EXT_MODIFIED_MESSAGE": "<span class='dialog-filename'>{0}</span> 已产生了外部修改, 但是 {APP_NAME} 中有你未保存的内容，<br /><br />需要保留哪个版本？",
  "EXT_DELETED_MESSAGE": "<span class='dialog-filename'>{0}</span> 已被删除, 但是 {APP_NAME} 有你未保存的内容，<br /><br />是否保存你的修改？",
  "EXT_ALWAYS_MODIFIED_BUTTON_TOOLTIP": "始终覆盖文件，直到切换项目或重新启动",
  "WINDOW_UNLOAD_WARNING": "确定要导航到其他 URL 并离开 {APP_NAME} 吗？",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "您有未保存的更改！确定要导航到其他 URL 并离开 {APP_NAME} 吗？",
  "DONE": "完成",
  "OK": "确认",
  "CANCEL": "取消",
  "DONT_SAVE": "不要保存",
  "SAVE": "保存",
  "SAVE_AS": "另存为…",
  "SAVE_AND_OVERWRITE": "覆盖",
  "ALWAYS_OVERWRITE": "始终覆盖",
  "DELETE": "删除",
  "BUTTON_YES": "是",
  "BUTTON_NO": "否",
  "FIND_MATCH_INDEX": "{1} 条中的 {0} 条",
  "FIND_NO_RESULTS": "未找到匹配项",
  "FIND_QUERY_PLACEHOLDER": "查找…",
  "FIND_HISTORY_MAX_COUNT": "搜索历史中最多搜索项数",
  "REPLACE_PLACEHOLDER": "替换为…",
  "BUTTON_REPLACE_ALL": "全部…",
  "BUTTON_REPLACE_BATCH": "批量…",
  "BUTTON_REPLACE_ALL_IN_FILES": "替换…",
  "BUTTON_REPLACE": "替换",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "下一个匹配项",
  "BUTTON_PREV_HINT": "上一个匹配项",
  "BUTTON_CASESENSITIVE_HINT": "区分大小写",
  "BUTTON_REGEXP_HINT": "正则表达式",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "替换(无法撤销)",
  "REPLACE_WITHOUT_UNDO_WARNING": "由于有 {0} 个文件需要修改, {APP_NAME} 将修改磁盘中未打开的文件，<br />这些修改无法撤销。",
  "BUTTON_REPLACE_WITHOUT_UNDO": "替换(无法撤销)",
  "OPEN_FILE": "打开文件",
  "SAVE_FILE_AS": "保存文件",
  "CHOOSE_FOLDER": "请选择一个目录",
  "RELEASE_NOTES": "发行说明",
  "NO_UPDATE_TITLE": "已更新!",
  "NO_UPDATE_MESSAGE": "正在使用最新版本的 {APP_NAME}。",
  "FIND_REPLACE_TITLE_LABEL": "替换",
  "FIND_REPLACE_TITLE_WITH": "为",
  "FIND_TITLE_LABEL": "已找到",
  "FIND_TITLE_SUMMARY": "&mdash; {0} {1} {2} 于 {3}",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "在 <span class='dialog-filename'>{0}</span> 中",
  "FIND_IN_FILES_NO_SCOPE": "在项目中",
  "FIND_IN_FILES_PROJECT_SCOPE": "在项目中查找",
  "FIND_IN_FILES_PROJECT_SCOPE_FILTER": "在 {0} 中查找",
  "FIND_IN_FILES_PROJECT_SCOPE_REPLACE": "在项目中替换",
  "FIND_IN_FILES_PROJECT_SCOPE_REPLACE_FILTER": "在 {0} 中替换",
  "FIND_IN_FILES_ZERO_FILES": "筛选条件排除了所有文件 {0}",
  "FIND_IN_FILES_FILE": "个文件",
  "FIND_IN_FILES_FILES": "个文件",
  "FIND_IN_FILES_MATCH": "个匹配",
  "FIND_IN_FILES_MATCHES": "个匹配",
  "FIND_IN_FILES_MORE_THAN": "超过 ",
  "FIND_IN_FILES_PAGING": "{0}&mdash;{1}",
  "FIND_IN_FILES_FILE_PATH": "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "按住 Ctrl/Cmd 键以便展开/折叠全部结果",
  "FIND_IN_FILES_INDEXING": "Indexing for Instant Search…",
  "FIND_IN_FILES_SEARCHING": "正在搜索文件…",
  "FIND_IN_FILES_SEARCHING_IN": "在 {0} 中",
  "FIND_IN_FILES_INDEXING_PROGRESS": "正在为 {1} 个文件中的 {0} 个文件建立即时搜索索引…",
  "REPLACE_IN_FILES_ERRORS_TITLE": "替换出现错误",
  "REPLACE_IN_FILES_ERRORS": "以下文件未被修改，可能是搜索后发生变更或无法写入。",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "获取更新信息失败",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "无法从服务器获取最新的更新信息. 请确认你的电脑已经连接互联网, 然后再次尝试重新获取！",
  "NEW_FILE_FILTER": "新建排除规则…",
  "CLEAR_FILE_FILTER": "不排除文件",
  "NO_FILE_FILTER": "没有文件被排除",
  "EXCLUDE_FILE_FILTER": "排除文件",
  "INCLUDE_FILE_FILTER": "在文件中搜索",
  "FILTER_PLACEHOLDER": "例如：index,.css,*.js,src/**/*.css",
  "FILTER_HISTORY_TOOLTIP": "按`Ctrl-Space`查看历史记录。",
  "FILTER_HISTORY_TOOLTIP_MAC": "按`Cmd-Space`查看历史记录。",
  "FIND_HISTORY_TOOLTIP": "按`Ctrl-Space`查看历史记录。",
  "FIND_HISTORY_TOOLTIP_MAC": "按`Cmd-Space`查看历史记录。",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "当前光标位置没有可用的快速编辑",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "CSS 快速编辑: 将光标放在单一class名称上",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "CSS 快速编辑: class属性不完整",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "CSS 快速编辑: id属性不完整",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "CSS 快速编辑: 将光标放在标签,、class 或 id上",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "CSS 计时函数快速编辑: 语法无效",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "JS 快速编辑: 将光标放在函数名称上",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "当前光标位置没有可用的快速文件",
  "PROJECT_LOADING": "载入中…",
  "UNTITLED": "无标题",
  "WORKING_FILES": "工作区",
  "TOP": "上",
  "BOTTOM": "下",
  "LEFT": "左",
  "RIGHT": "右",
  "CMD_SPLITVIEW_NONE": "单窗口",
  "CMD_SPLITVIEW_VERTICAL": "垂直分割",
  "CMD_SPLITVIEW_HORIZONTAL": "水平分割",
  "SPLITVIEW_MENU_TOOLTIP": "垂直/水平分割编辑器窗口",
  "GEAR_MENU_TOOLTIP": "配置工作区",
  "CMD_TOGGLE_SHOW_WORKING_SET": "显示工作文件",
  "CMD_TOGGLE_SHOW_FILE_TABS": "显示文件标签栏",
  "SPLITVIEW_INFO_TITLE": "已经打开",
  "SPLITVIEW_MULTIPANE_WARNING": "该文件已经在编辑器的另一个窗格中打开。{APP_NAME} 后续会加上同文件多窗格打开的支持。在此之前，文件只会显示在已打开的窗格中。<br /><br />（本信息只显示一次。）",
  "KEYBOARD_OVERLAY_TEXT": "使用箭头键导航，或输入内容以选择 UI 元素。",
  "KEYBOARD_SHORTCUT_CHANGE_TITLE": "更改键盘快捷键…",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_TITLE": "更改键盘快捷键",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_TEXT": "按新的组合键以设置 <b>'{0}'</b>（当前：<b>{1}</b>）",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_DUPLICATE": "警告：组合键 <b>{0}</b> 已分配给 <b>'{1}'</b>。是否重新分配给 <b>'{2}'</b>？",
  "KEYBOARD_SHORTCUT_ASSIGN": "分配",
  "KEYBOARD_SHORTCUT_NONE": "无",
  "KEYBOARD_SHORTCUT_MENU_SHOW_SHORTCUTS": "键盘快捷键…",
  "KEYBOARD_SHORTCUT_MENU_SHOW_SHORTCUTS_BUTTON": "显示所有快捷键…",
  "KEYBOARD_SHORTCUT_TABLE_BASE_KEY": "基础按键",
  "KEYBOARD_SHORTCUT_TABLE_KEY_BINDING": "快捷键",
  "KEYBOARD_SHORTCUT_TABLE_COMMAND_ID": "命令 ID",
  "KEYBOARD_SHORTCUT_TABLE_COMMAND_NAME": "命令",
  "KEYBOARD_SHORTCUT_TABLE_DOUBLE_CLICK": "双击以更改快捷键",
  "KEYBOARD_SHORTCUT_TABLE_ORIGIN": "来源",
  "KEYBOARD_SHORTCUT_ORIG_EXTENSION": "扩展",
  "KEYBOARD_SHORTCUT_PANEL_TITLE": "键盘快捷键",
  "KEYBOARD_SHORTCUT_PRESET_TOOLTIP": "使用类似 VSCode、WebStorm 或 Sublime Text 等编辑器的键盘快捷键",
  "KEYBOARD_SHORTCUT_PRESET_SELECT": "选择快捷键预设",
  "KEYBOARD_SHORTCUT_PRESET_USING": "使用 {0}",
  "DEFAULT": "默认",
  "KEYBOARD_SHORTCUT_PANEL_FILTER": "筛选…",
  "KEYBOARD_SHORTCUT_PANEL_RESET": "重置…",
  "KEYBOARD_SHORTCUT_PANEL_RESET_DEFAULT": "恢复默认快捷键…",
  "KEYBOARD_SHORTCUT_RESET_DIALOG_TITLE": "重置键盘快捷键",
  "KEYBOARD_SHORTCUT_RESET_DIALOG_MESSAGE": "是否将所有自定义快捷键重置为默认值？此操作不可撤销。",
  "KEYBOARD_SHORTCUT_SRC_USER": "用户自定义",
  "KEYBOARD_SHORTCUT_SRC_PRESET": "{0} 预设",
  "STATUSBAR_CURSOR_POSITION": "行 {0}, 列 {1}",
  "STATUSBAR_CURSOR_POSITION_SHORT": "{0}:{1}",
  "STATUSBAR_CURSOR_GOTO": "点击跳转至:行",
  "STATUSBAR_SELECTION_CH_SINGULAR": " — 已选中 {0} 列",
  "STATUSBAR_SELECTION_CH_PLURAL": " — 已选中 {0} 列",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " — 已选中 {0} 行",
  "STATUSBAR_SELECTION_LINE_PLURAL": " — 已选中 {0} 行",
  "STATUSBAR_SELECTION_MULTIPLE": "— {0} 个多光标选择",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "点击切换缩进为空格",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "点击切换缩进为Tab",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "点击修改缩进的空格长度",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "点击修改缩进的Tab长度",
  "STATUSBAR_SPACES": "空格长度:",
  "STATUSBAR_TAB_SIZE": "Tab 长度:",
  "STATUSBAR_AUTO_INDENT": "<span title='点击切换到固定缩进。当前设置为根据当前文件自动检测并应用缩进。'>自动</span>",
  "STATUSBAR_FIXED_INDENT": "<span title='点击切换到自动缩进检测。当前设置为固定缩进。'>固定</span>",
  "STATUSBAR_LINE_COUNT_SINGULAR": "— {0} 行",
  "STATUSBAR_LINE_COUNT_PLURAL": "— {0} 行",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "扩展已禁用",
  "STATUSBAR_INSERT": "插入",
  "STATUSBAR_OVERWRITE": "改写",
  "STATUSBAR_INSOVR_TOOLTIP": "点击切换光标的插入 (INS) 和改写 (OVR) 模式",
  "STATUSBAR_LANG_TOOLTIP": "点击更改文件类型",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}。点击打开关闭报告面板",
  "STATUSBAR_DEFAULT_LANG": "(默认)",
  "STATUSBAR_SET_DEFAULT_LANG": "设置为 .{0} 的缺省",
  "STATUSBAR_ENCODING_TOOLTIP": "选择编码",
  "STATUSBAR_TASKS": "任务",
  "STATUSBAR_TASKS_TOOLTIP": "管理活动任务",
  "STATUSBAR_TASKS_HIDE_SPINNER": "隐藏旋转图标",
  "STATUSBAR_TASKS_UNKNOWN_EXTENSION_TASK": "未知扩展任务…",
  "STATUSBAR_TASKS_PLAY": "开始或恢复",
  "STATUSBAR_TASKS_PAUSE": "暂停",
  "STATUSBAR_TASKS_STOP": "停止",
  "STATUSBAR_TASKS_RESTART": "重启",
  "CLOSE_TABS_TO_THE_RIGHT": "关闭右侧标签页",
  "CLOSE_TABS_TO_THE_LEFT": "关闭左侧标签页",
  "CLOSE_ALL_TABS": "关闭所有标签页",
  "CLOSE_SAVED_TABS": "关闭已保存的标签页",
  "ERRORS_NO_FILE": "未打开文件",
  "ERRORS_PANEL_TITLE_MULTIPLE": "{0} 个问题 - {1}",
  "ERRORS_PANEL_TITLE_MULTIPLE_FIXABLE": "{0} 个问题，其中 {1} 个可修复 - {2}",
  "SINGLE_ERROR": "1 个{0}问题 - {1}",
  "SINGLE_ERROR_FIXABLE": "1 个{0}问题，可修复 - {2}",
  "MULTIPLE_ERRORS": "{0} {1}个问题 - {2}",
  "MULTIPLE_ERRORS_FIXABLE": "{0} {1}个问题，其中 {2} 个可修复 - {3}",
  "NO_ERRORS": "未发现 {0} 问题 - 加油！",
  "NO_ERRORS_MULTIPLE_PROVIDER": "未发现问题 - 加油！",
  "LINT_DISABLED": "JSLint 已被禁用或者无法在此文件工作。",
  "NO_LINT_AVAILABLE": "{0} 没有可用检查器",
  "NOTHING_TO_LINT": "没有可检查文件",
  "COPY_ERROR": "复制问题",
  "FIX": "修复",
  "CANNOT_FIX_TITLE": "应用修复失败",
  "CANNOT_FIX_SOME_TITLE": "部分修复应用失败",
  "CANNOT_FIX_MESSAGE": "自准备修复以来，文档已被修改。请重试。",
  "LINTER_TIMED_OUT": "{0} 等待 {1} ms 后超时",
  "LINTER_FAILED": "{0} 已终止，错误：{1}",
  "CLICK_VIEW_PROBLEM": "点击在面板中查看问题",
  "FILE_MENU": "文件",
  "CMD_FILE_NEW_UNTITLED": "新建",
  "CMD_FILE_NEW": "新建文件",
  "CMD_FILE_DUPLICATE": "创建副本",
  "CMD_FILE_DUPLICATE_FILE": "复制文件",
  "CMD_FILE_DOWNLOAD_PROJECT": "下载项目",
  "CMD_FILE_DOWNLOAD": "下载",
  "CMD_FILE_CUT": "剪切",
  "CMD_FILE_COPY": "复制",
  "CMD_FILE_COPY_PATH": "复制路径",
  "CMD_FILE_PASTE": "粘贴",
  "CMD_PROJECT_NEW": "新建项目…",
  "CMD_FILE_NEW_FOLDER": "新建目录",
  "CMD_FILE_OPEN": "打开文件…",
  "CMD_RECENT_FILES_OPEN": "最近文件…",
  "CMD_ADD_TO_WORKING_SET": "添加至工作集合",
  "CMD_OPEN_DROPPED_FILES": "打开拖放的文件",
  "CMD_OPEN_FOLDER": "打开目录…",
  "CMD_FILE_CLOSE": "关闭",
  "CMD_FILE_CLOSE_ALL": "全部关闭",
  "CMD_REOPEN_CLOSED": "重新打开已关闭文件",
  "CMD_FILE_CLOSE_LIST": "关闭列表中的文件",
  "CMD_FILE_CLOSE_OTHERS": "关闭其他文件",
  "CMD_FILE_CLOSE_ABOVE": "关闭上面的其他文件",
  "CMD_FILE_CLOSE_BELOW": "关闭下面的其他文件",
  "CMD_FILE_SAVE": "保存文件",
  "CMD_FILE_SAVE_ALL": "全部保存",
  "CMD_FILE_SAVE_AS": "另存为…",
  "CMD_LIVE_FILE_PREVIEW": "实时预览",
  "CMD_LIVE_FILE_PREVIEW_SETTINGS": "实时预览设置",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "开启实验性实时预览",
  "CMD_RELOAD_LIVE_PREVIEW": "重新加载实时预览",
  "CMD_PROJECT_SETTINGS": "项目设置…",
  "CMD_FILE_RENAME": "重命名",
  "CMD_FILE_DELETE": "删除",
  "CMD_INSTALL_EXTENSION": "安装扩展…",
  "CMD_EXTENSION_MANAGER": "扩展管理器…",
  "CMD_FILE_REFRESH": "刷新文件列表",
  "CMD_FILE_SHOW_FOLDERS_FIRST": "文件夹优先排序",
  "CMD_QUIT": "退出",
  "CMD_OPEN_IN": "打开方式",
  "CMD_EXIT": "退出",
  "EDIT_MENU": "编辑",
  "CMD_UNDO": "撤销",
  "CMD_REDO": "重做",
  "CMD_CUT": "剪切",
  "CMD_COPY": "复制",
  "CMD_PASTE": "粘贴",
  "CMD_SELECT_ALL": "全选",
  "CMD_SELECT_LINE": "选中当前行",
  "CMD_SPLIT_SEL_INTO_LINES": "将选中内容拆分至多行",
  "CMD_ADD_CUR_TO_NEXT_LINE": "将下一行添加至选中内容",
  "CMD_ADD_CUR_TO_PREV_LINE": "将上一行添加至选中内容",
  "CMD_INDENT": "增加行缩进",
  "CMD_UNINDENT": "减少行缩进",
  "CMD_DUPLICATE": "创建副本",
  "CMD_DELETE_LINES": "删除当前行",
  "CMD_COMMENT": "注释当前行",
  "CMD_BLOCK_COMMENT": "注释选中内容",
  "CMD_LINE_UP": "移到下一行",
  "CMD_LINE_DOWN": "移到上一行",
  "CMD_OPEN_LINE_ABOVE": "在上方插入新行",
  "CMD_OPEN_LINE_BELOW": "在下方插入新行",
  "CMD_TOGGLE_CLOSE_BRACKETS": "括号自动补全",
  "CMD_SHOW_CODE_HINTS": "显示代码提示",
  "CMD_BEAUTIFY_CODE": "美化代码",
  "CMD_BEAUTIFY_CODE_ON_SAVE": "保存时美化代码",
  "CMD_AUTO_RENAME_TAGS": "自动重命名 HTML 标签",
  "CMD_TOGGLE_EMMET": "Emmet（代码补全）",
  "FIND_MENU": "查找",
  "CMD_FIND": "查找",
  "CMD_FIND_NEXT": "查找下一个",
  "CMD_FIND_PREVIOUS": "查找上一个",
  "CMD_FIND_ALL_AND_SELECT": "全选匹配项",
  "CMD_ADD_NEXT_MATCH": "添加下一个匹配项",
  "CMD_SKIP_CURRENT_MATCH": "跳过并添加下一个匹配项",
  "CMD_FIND_IN_FILES": "在文件中查找",
  "CMD_FIND_IN_SUBTREE": "在该位置查找…",
  "CMD_REPLACE": "替换",
  "CMD_REPLACE_IN_FILES": "在文件中替换",
  "CMD_REPLACE_IN_SUBTREE": "在该位置替换…",
  "VIEW_MENU": "视图",
  "CMD_HIDE_SIDEBAR": "隐藏边栏",
  "CMD_SHOW_SIDEBAR": "显示边栏",
  "CMD_TOGGLE_SIDEBAR": "显示/隐藏边栏",
  "CMD_TOGGLE_TABBAR": "文件标签栏",
  "CMD_TOGGLE_PANELS": "显示/隐藏面板",
  "CMD_TOGGLE_PURE_CODE": "无干扰模式",
  "CMD_TOGGLE_FULLSCREEN": "全屏",
  "CMD_ZOOM_UI": "缩放界面和字体",
  "CMD_ZOOM_IN": "放大",
  "CMD_ZOOM_IN_SCALE": "放大 (当前: {0}%)",
  "CMD_ZOOM_OUT": "缩小",
  "CMD_INCREASE_FONT_SIZE": "放大编辑器字体",
  "CMD_DECREASE_FONT_SIZE": "缩小编辑器字体",
  "CMD_RESTORE_FONT_SIZE": "恢复编辑器默认字体",
  "CMD_SCROLL_LINE_UP": "向上滚动",
  "CMD_SCROLL_LINE_DOWN": "向下滚动",
  "CMD_TOGGLE_LINE_NUMBERS": "显示行号",
  "CMD_TOGGLE_ACTIVE_LINE": "高亮当前行",
  "CMD_TOGGLE_WORD_WRAP": "自动换行",
  "CMD_VIEW_TOGGLE_INSPECTION": "保存时检查文件",
  "CMD_VIEW_TOGGLE_PROBLEMS": "问题",
  "CMD_WORKINGSET_SORT_BY_ADDED": "根据添加时间排序",
  "CMD_WORKINGSET_SORT_BY_NAME": "根据名称排序",
  "CMD_WORKINGSET_SORT_BY_TYPE": "根据类型排序",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "自动排序",
  "CMD_THEMES": "主题…",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "自动关闭搜索",
  "CMD_TOGGLE_RULERS": "标尺",
  "CMD_TOGGLE_INDENT_GUIDES": "缩进参考线",
  "CMD_KEYBOARD_NAV_OVERLAY": "可视化命令面板",
  "NAVIGATE_MENU": "导航",
  "CMD_QUICK_OPEN": "打开快速导航",
  "CMD_GOTO_LINE": "转到某行",
  "CMD_GOTO_DEFINITION": "转到定义",
  "CMD_GOTO_DEFINITION_PROJECT": "在项目中查找定义",
  "CMD_GOTO_FIRST_PROBLEM": "转到第一个错误/警告",
  "CMD_GOTO_NEXT_PROBLEM": "转到下一个问题",
  "CMD_GOTO_PREV_PROBLEM": "转到上一个问题",
  "CMD_TOGGLE_QUICK_EDIT": "快速编辑",
  "CMD_TOGGLE_QUICK_DOCS": "快速文档",
  "CMD_QUICK_EDIT_PREV_MATCH": "上一个快速编辑项",
  "CMD_QUICK_EDIT_NEXT_MATCH": "下一个快速编辑项",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "新 CSS 规则",
  "CMD_NEXT_DOC": "下一个文件",
  "CMD_PREV_DOC": "上一个文件",
  "CMD_NAVIGATE_BACKWARD": "后退",
  "CMD_NAVIGATE_FORWARD": "前进",
  "CMD_NEXT_DOC_LIST_ORDER": "列表中下一个文件",
  "CMD_PREV_DOC_LIST_ORDER": "列表中上一个文件",
  "CMD_SHOW_IN_TREE": "在侧边栏显示",
  "CMD_SHOW_IN_EXPLORER": "Windows 资源管理器",
  "CMD_SHOW_IN_FINDER": "macOS Finder",
  "CMD_SHOW_IN_FILE_MANAGER": "文件管理器",
  "CMD_OPEN_IN_CMD": "命令提示符",
  "CMD_OPEN_IN_POWER_SHELL": "PowerShell",
  "CMD_OPEN_IN_DEFAULT_APP": "系统默认应用",
  "CMD_SWITCH_PANE_FOCUS": "切换面板焦点",
  "CMD_OPEN_VFS": "打开虚拟文件系统",
  "CMD_DIAGNOSTIC_TOOLS": "{APP_NAME} 诊断工具",
  "CMD_EXPERIMENTAL_FEATURES": "实验性功能",
  "CMD_ENABLE_DRAG_AND_DROP": "拖放文件",
  "CMD_OPEN_EXTENSIONS_FOLDER": "打开扩展文件夹…",
  "CMD_OPEN_VIRTUAL_SERVER": "打开虚拟服务器",
  "HELP_MENU": "帮助",
  "CMD_CHECK_FOR_UPDATE": "检查更新…",
  "CMD_AUTO_UPDATE": "自动更新",
  "CMD_HOW_TO_USE_BRACKETS": "如何使用 {APP_NAME}",
  "CMD_SUPPORT": "{APP_NAME} 支持",
  "CMD_GET_PRO": "获取 Phoenix Pro",
  "CMD_VIEW_LICENSE": "查看许可证",
  "CMD_MANAGE_LICENSES": "管理许可证",
  "CMD_USER_PROFILE": "{APP_NAME} 帐户",
  "CMD_DOCS": "帮助，入门指南",
  "CMD_SUGGEST": "推荐功能",
  "CMD_REPORT_ISSUE": "报告问题",
  "CMD_RELEASE_NOTES": "发行说明",
  "CMD_GET_INVOLVED": "参与",
  "CMD_SHOW_EXTENSIONS_FOLDER": "显示扩展目录",
  "CMD_HEALTH_DATA_STATISTICS": "健康报告…",
  "CMD_HOMEPAGE": "下载应用 - 主页",
  "CMD_TWITTER": "在 Twitter 上 {TWITTER_NAME}",
  "CMD_YOUTUBE": "YouTube 频道",
  "CMD_ABOUT": "关于 {APP_TITLE}",
  "CMD_OPEN_PREFERENCES": "打开配置文件",
  "CMD_OPEN_KEYMAP": "打开用户快捷键映射文件",
  "EXPERIMENTAL_BUILD": "体验版",
  "RELEASE_BUILD": "发布版",
  "DEVELOPMENT_BUILD": "开发版",
  "PRERELEASE_BUILD": "预发布版本",
  "RELOAD_FROM_DISK": "重新从硬盘中加载",
  "KEEP_CHANGES_IN_EDITOR": "保留编辑器中的修改",
  "CLOSE_DONT_SAVE": "放弃保存并关闭",
  "RELAUNCH_CHROME": "重新运行 Chrome",
  "ABOUT": "关于",
  "CLOSE": "关闭",
  "ABOUT_TEXT_LINE1": "版本 {VERSION_MAJOR}.{VERSION_MINOR} {BUILD_TYPE} {VERSION}",
  "ABOUT_TEXT_BUILD_TIMESTAMP": "构建时间戳：",
  "ABOUT_TEXT_PRO_BUILD": "Phoenix Pro 构建版本：",
  "ABOUT_RELEASE_CREDITS": "发布鸣谢：",
  "ABOUT_TEXT_LINE3": "我们使用的第三方库 - <a href='https://github.com/phcode-dev/phoenix/tree/main/src/thirdparty/licences'> 许可证和署名</a>。",
  "ABOUT_TEXT_LINE4": "文档和源代码位于 <a href='https://github.com/phcode-dev/phoenix/'>https://github.com/phcode-dev/phoenix/</a>",
  "ABOUT_TEXT_LINE5": "用 ❤ 和 JavaScript 制作：",
  "ABOUT_TEXT_LINE6": "很多人（但我们现在无法加载该数据）。",
  "ABOUT_TEXT_MDN_DOCS": "MDN 文档和图形 logo 遵循<a href='{MDN_DOCS_LICENSE}'>署名-相同方式共享 3.0 未本地化</a>协议。",
  "UPDATE_NOTIFICATION_TOOLTIP": "有一个新版本的 {APP_NAME}! 点此查看详情。",
  "UPDATE_NOT_AVAILABLE_TITLE": "{APP_NAME} 已是最新版本",
  "UPDATE_UP_TO_DATE": "你的 {APP_NAME} 版本已是最新！",
  "UPDATE_AVAILABLE_TITLE": "可用的更新",
  "UPDATE_WHATS_NEW": "{APP_NAME} 更新内容",
  "UPDATE_READY_RESTART_TITLE": "重启应用以完成更新",
  "UPDATE_READY_RESTART_INSTALL_MESSAGE": "关闭所有打开的窗口后，{APP_NAME} 将自动更新。",
  "UPDATE_FAILED_TITLE": "更新失败",
  "UPDATE_INSTALLING": "正在安装更新…",
  "UPDATE_INSTALLING_MESSAGE": "正在安装更新：{APP_NAME} 正在安装最新的更新。安装完成后，应用程序将自动关闭。",
  "UPDATE_FAILED_MESSAGE": "请关闭所有 {APP_NAME} 应用窗口并重新打开应用程序以再次尝试更新。<br/>您也可以从 <a href='https://phcode.io'>phcode.io</a> 下载安装程序进行更新。",
  "UPDATE_FAILED_VISIT_SITE_MESSAGE": "要重试，请退出所有 {APP_NAME} 实例并重新启动应用程序。<br>您很快将被定向到我们的下载页面，您可以在其中手动下载最新版本。",
  "UPDATE_MESSAGE": "有一个新版本的 {APP_NAME}，增加了一些功能：",
  "GET_IT_NOW": "马上获取！",
  "UPDATE_ON_EXIT": "退出时更新",
  "UPDATE_LATER": "稍后提醒我",
  "UPDATE_DONE": "重启以更新 {APP_NAME}",
  "UPDATE_RESTART_INSTALL": "重启以安装更新",
  "UPDATE_DOWNLOADING": "正在下载安装程序",
  "INSTALL_WEBAPP": "在您的设备上安装 {APP_NAME}",
  "UPDATE_DOWNLOAD_PROGRESS": "正在下载 - {0} / {1} MB",
  "UPDATING_APP": "正在更新 {APP_NAME}",
  "UPDATING_APP_MESSAGE": "这可能需要一些时间",
  "UPDATING_APP_DIALOG_MESSAGE": "更新正在进行中。您可以在我们升级的同时继续使用 {APP_NAME}。",
  "PROJECT_SETTINGS_TITLE": "项目设置: {0}",
  "PROJECT_SETTING_BASE_URL": "实时预览的根目录地址",
  "PROJECT_SETTING_BASE_URL_HINT": "使用本地服务器, 并指定一个URL。 例如: http://localhost:8000/",
  "BASEURL_ERROR_INVALID_PROTOCOL": "实时预览不支持此协议 {0} &mdash;请使用 http: 或 https: .",
  "BASEURL_ERROR_SEARCH_DISALLOWED": "地址不能包含搜索参数如 \"{0}\".",
  "BASEURL_ERROR_HASH_DISALLOWED": "地址不能包含哈希如 \"{0}\".",
  "BASEURL_ERROR_INVALID_CHAR": "特殊字符 '{0}' 必须 %-encoded.",
  "BASEURL_ERROR_UNKNOWN_ERROR": "地址解析错误, 请确认地址格式",
  "EMPTY_VIEW_HEADER": "<em>保持此窗格的焦点，打开文件</em>",
  "FLIPVIEW_BTN_TOOLTIP": "将此视图翻转到 {0} 面板",
  "CURRENT_THEME": "当前主题",
  "GET_MORE_THEMES": "获取更多...",
  "USE_THEME_SCROLLBARS": "使用主题自带滚动条",
  "FONT_SIZE": "字号",
  "FONT_FAMILY": "字体",
  "FONT_LINE_HEIGHT": "行高",
  "THEMES_SETTINGS": "主题设置",
  "THEMES_ERROR": "主题错误",
  "THEMES_ERROR_CANNOT_APPLY": "由于发生错误，无法应用主题。",
  "BUTTON_NEW_RULE": "新 CSS 规则",
  "INSTALL": "安装",
  "APPLY": "应用",
  "UPDATE": "升级",
  "REMOVE": "移除",
  "DISABLE": "禁用",
  "ENABLE": "启用",
  "OVERWRITE": "覆盖",
  "CANT_DROP_ZIP": "即将支持拖放 zip 文件……",
  "CANT_REMOVE_DEV": "\"dev\" 文件夹中扩展必须手动删除。",
  "CANT_UPDATE": "升级与当前版本的 {APP_NAME} 不兼容。",
  "CANT_UPDATE_DEV": "\"dev\" 文件夹中的扩展无法自动升级。",
  "INSTALL_EXTENSION_TITLE": "安装扩展",
  "UPDATE_EXTENSION_TITLE": "升级扩展",
  "INSTALL_EXTENSION_LABEL": "扩展包地址",
  "INSTALL_EXTENSION_HINT": "填写扩展包的 zip 文件或 GitHub repo 的链接地址",
  "INSTALLING_FROM": "正在从 {0} 安装扩展…",
  "INSTALL_SUCCEEDED": "安装成功！",
  "INSTALL_FAILED": "安装失败.",
  "CANCELING_INSTALL": "正在取消…",
  "CANCELING_HUNG": "取消安装需要很长时间. 可能出现了内部错误。",
  "INSTALL_CANCELED": "安装已取消。",
  "VIEW_COMPLETE_DESCRIPTION": "查看完整说明",
  "VIEW_TRUNCATED_DESCRIPTION": "查看简短说明",
  "SORT_EXTENSION_METHOD": "使用 downloadCount 或 publishedDate 对扩展进行排序",
  "INVALID_ZIP_FILE": "下载的内容不是一个有效的 ZIP 文件。",
  "MISSING_PACKAGE_JSON": "包中缺少 package.json 文件。",
  "INVALID_PACKAGE_JSON": "扩展包中的 Package.json 不存在。(错误: {0})",
  "MISSING_PACKAGE_NAME": "扩展包中的 Package.json 未指定扩展包名称。",
  "BAD_PACKAGE_NAME": "{0} 是一个无效扩展包名。",
  "MISSING_PACKAGE_VERSION": "扩展包中的 Package.json 未指定扩展包版本。",
  "INVALID_VERSION_NUMBER": "扩展包版本号 ({0}) 无效。",
  "INVALID_BRACKETS_VERSION": "{APP_NAME} 兼容性字串 ({0}) 无效。",
  "DISALLOWED_WORDS": "({1}) 不允许在 {0} 中出现。",
  "NPM_INSTALL_FAILED": "npm install 命令失败：{0}",
  "API_NOT_COMPATIBLE": "这个扩展包不兼容当前版本的 {APP_NAME}. 将安装至 Disabled 扩展文件夹中。",
  "MISSING_MAIN": "扩展包遗失 main.js 文件.",
  "EXTENSION_ALREADY_INSTALLED": "安装这个扩展将会覆盖先前的版本, 覆盖旧版本吗？",
  "EXTENSION_SAME_VERSION": "已安装相同版本的扩展. 覆盖已存在的安装吗？",
  "EXTENSION_OLDER_VERSION": "扩展包版本 {0} 低于已安装版本 ({1})， 覆盖已存在的安装吗？",
  "DOWNLOAD_ID_IN_USE": "内部错误: 该下载ID已被使用。",
  "NO_SERVER_RESPONSE": "无法连接到服务器。",
  "BAD_HTTP_STATUS": "未在服务器上发现该文件 (HTTP {0})。",
  "CANNOT_WRITE_TEMP": "无法保存下载文件到临时文件。",
  "ERROR_LOADING": "扩展程序启动时遇到一个错误。",
  "MALFORMED_URL": "无效的链接地址，请检查输入是否有误。",
  "UNSUPPORTED_PROTOCOL": "需要一个 http 或 https 协议的地址。",
  "UNKNOWN_ERROR": "未知内部错误。",
  "EXTENSION_VERIFIED_PUBLISHER": "此发布者已验证 {0} 的所有权。",
  "EXTENSION_VERIFIED_SORT": "已验证",
  "EXTENSION_STAR": "星标",
  "EXTENSION_STAR_SORT": "星级",
  "ERROR_UNINSTALLING_EXTENSION_TITLE": "卸载扩展时出错",
  "ERROR_UNINSTALLING_EXTENSION_MESSAGE": "卸载扩展 {0} 失败",
  "EXTENSION_MANAGER_TITLE": "扩展管理器",
  "EXTENSION_MANAGER_ERROR_LOAD": "无法连接到扩展仓库。请稍后重试。",
  "EXTENSION_UPDATE_RESTART_TITLE": "重启以更新",
  "EXTENSION_UPDATE_RESTART_MESSAGE": "要加载已更新的扩展，请关闭所有正在运行的 {APP_NAME} 实例并重新启动应用程序。",
  "INSTALL_EXTENSION_DRAG": "拖拽 .zip 到此处或者",
  "INSTALL_EXTENSION_DROP": "Drop .zip to install",
  "INSTALL_EXTENSION_DROP_ERROR": "安装/更新由于以下错误终止:",
  "INSTALL_FROM_URL": "从 URL 安装…",
  "INSTALL_EXTENSION_VALIDATING": "验证中...…",
  "EXTENSION_AUTHOR": "作者",
  "EXTENSION_DATE": "日期",
  "EXTENSION_INCOMPATIBLE_NEWER": "这个扩展需要更新版本的 {APP_NAME}。",
  "EXTENSION_INCOMPATIBLE_OLDER": "这个扩展目前只能在旧版本的 {APP_NAME} 上运行。",
  "EXTENSION_DEFAULT_FEATURE_PRESENT": "您可能不需要此扩展。{APP_NAME} 已具备此功能。",
  "EXTENSION_DEPRECATED_NOT_LOADED": "扩展未加载。它已弃用或不安全。",
  "EXTENSION_LATEST_INCOMPATIBLE_NEWER": "扩展版本为 {0} 需要一个更新版本的 {APP_NAME}，但你可以安装旧版本的扩展 {1}。",
  "EXTENSION_LATEST_INCOMPATIBLE_OLDER": "扩展版本为 {0} 需要一个更旧版本的 {APP_NAME}，但你可以安装旧版本的扩展 {1}。",
  "EXTENSION_NO_DESCRIPTION": "没有描述",
  "EXTENSION_MORE_INFO": "更多信息...",
  "EXTENSION_ERROR": "扩展错误",
  "EXTENSION_KEYWORDS": "关键词",
  "EXTENSION_TRANSLATED_USER_LANG": "翻译为{0} , 包括你所使用的语言",
  "EXTENSION_TRANSLATED_GENERAL": "翻译为 {0} ",
  "EXTENSION_TRANSLATED_LANGS": "该扩展已被翻译为以下语言: {0}",
  "EXTENSION_INSTALLED": "已安装",
  "EXTENSION_UPDATE_INSTALLED": "此扩展的更新已下载, 将在重启 {APP_NAME} 后安装。",
  "EXTENSION_SEARCH_PLACEHOLDER": "搜索",
  "EXTENSION_MORE_INFO_LINK": "更多",
  "EXTENSION_MANAGER_CREATE_EXTENSION": "创建扩展程序",
  "EXTENSION_MANAGER_CREATE_THEME": "创建主题",
  "BROWSE_EXTENSIONS": "浏览扩展",
  "EXTENSION_MANAGER_REMOVE": "移除扩展",
  "EXTENSION_MANAGER_REMOVE_ERROR": "无法移除一个或多个扩展: {0}. {APP_NAME} 仍会重新加载。",
  "EXTENSION_MANAGER_UPDATE": "升级扩展",
  "EXTENSION_MANAGER_UPDATE_ERROR": "无法升级一个或多个扩展: {0}. {APP_NAME} 仍会重新加载。",
  "EXTENSION_MANAGER_DISABLE": "禁用扩展",
  "EXTENSION_MANAGER_DISABLE_ERROR": "无法禁用一个或多个扩展: {0}. {APP_NAME} 仍会重新加载。",
  "EXTENSION_MANAGER_THEMES_INFO": "要<a class=\"theme_settings\">选择默认主题</a>或修改其他主题设置，请<a class=\"theme_settings\">点击此处</a>。",
  "EXTENSION_MANAGER_THEMES_UNDO": "恢复到之前的主题",
  "MARKED_FOR_REMOVAL": "标记为删除",
  "UNDO_REMOVE": "撤销",
  "MARKED_FOR_UPDATE": "标记为升级",
  "UNDO_UPDATE": "撤销",
  "MARKED_FOR_DISABLING": "标记为禁用",
  "UNDO_DISABLE": "撤销",
  "CHANGE_AND_RELOAD_TITLE": "扩展更改",
  "CHANGE_AND_RELOAD_MESSAGE": "安装或移除已标记的扩展, 需要退出并重启 {APP_NAME}， 请保存未保存的更改。",
  "REMOVE_AND_RELOAD": "移除扩展并退出重启",
  "CHANGE_AND_RELOAD": "更改扩展并退出重启",
  "UPDATE_AND_RELOAD": "升级扩展并退出重启",
  "DISABLE_AND_RELOAD": "禁用扩展并退出重启",
  "PROCESSING_EXTENSIONS": "正在处理扩展的变更…",
  "EXTENSION_NOT_INSTALLED": "无法移除扩展 {0} 其并未被安装.",
  "NO_EXTENSIONS": "还没有安装扩展。<br>点击上方可用的标签开始安装。",
  "NO_EXTENSION_MATCHES": "没有找到相符的扩展。",
  "REGISTRY_SANITY_CHECK_WARNING": "小心来自未知源的扩展。",
  "EXTENSIONS_INSTALLED_TITLE": "已安装",
  "EXTENSIONS_DEFAULT_TITLE": "默认",
  "EXTENSIONS_AVAILABLE_TITLE": "可获取",
  "EXTENSIONS_THEMES_TITLE": "主题",
  "EXTENSIONS_UPDATES_TITLE": "升级",
  "EXTENSIONS_LAST_UPDATED": "上次更新时间",
  "EXTENSIONS_DOWNLOADS": "下载量",
  "EXTENSIONS_REGISTRY_TASK_TITLE": "正在更新扩展列表",
  "EXTENSIONS_REGISTRY_TASK_MESSAGE": "正在下载…",
  "INLINE_EDITOR_NO_MATCHES": "未找到匹配项。",
  "INLINE_EDITOR_HIDDEN_MATCHES": "所有匹配项已折叠。展开右侧列出的文件以查看匹配项。",
  "CSS_QUICK_EDIT_NO_MATCHES": "符合选择的 CSS 规则不存在。<br> 点击 \"新 CSS 规则\" 来创建。",
  "CSS_QUICK_EDIT_NO_STYLESHEETS": "您的项目中没有样式表。<br>建立一个来添加 CSS 规则。",
  "IMAGE_VIEWER_LARGEST_ICON": "最大化",
  "UNIT_PIXELS": "像素",
  "DEBUG_MENU": "调试",
  "ERRORS": "错误",
  "CMD_SHOW_DEV_TOOLS": "{APP_NAME} 开发者工具",
  "CMD_REFRESH_WINDOW": "以带扩展模式重启",
  "CMD_LOAD_CURRENT_EXTENSION": "将项目作为扩展程序加载",
  "CMD_RELOAD_CURRENT_EXTENSION": "将项目作为扩展程序重新加载",
  "CMD_UNLOAD_CURRENT_EXTENSION": "卸载项目作为扩展程序",
  "CMD_RELOAD_WITHOUT_USER_EXTS": "以无扩展模式重启",
  "CMD_NEW_BRACKETS_WINDOW": "新建窗口",
  "CMD_LAUNCH_SCRIPT_MAC": "安装命令行快捷方式",
  "CMD_SWITCH_LANGUAGE": "切换语言…",
  "CMD_RUN_UNIT_TESTS": "运行 {APP_NAME} 测试",
  "CMD_BUILD_TESTS": "构建编辑器测试",
  "CMD_SHOW_PERF_DATA": "显示性能数据",
  "CMD_ENABLE_LOGGING": "启用详细日志",
  "CMD_ENABLE_PHNODE_INSPECTOR": "启用 PhNode 检查器",
  "CMD_GET_PHNODE_INSPECTOR_URL": "如何检查 PhNode",
  "CMD_ENABLE_LIVE_PREVIEW_LOGS": "实时预览日志",
  "CMD_ENABLE_GIT_LOGS": "Git 详细日志",
  "CMD_OPEN_BRACKETS_SOURCE": "打开 Brackets 源码",
  "CREATING_LAUNCH_SCRIPT_TITLE": "{APP_NAME} 命令行快捷方式",
  "ERROR_CREATING_LAUNCH_SCRIPT": "安装命令行快捷方式时发生错误。 请尝试<a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting'>这些故障排除建议</a>.<br/><br/>原因: {0}",
  "ERROR_CLTOOLS_RMFAILED": "无法移除已存在的 <code>/usr/local/bin/brackets</code> 符号链接.",
  "ERROR_CLTOOLS_MKDIRFAILED": "无法创建 <code>/usr/local/bin</code> 目录.",
  "ERROR_CLTOOLS_LNFAILED": "无法创建 <code>/usr/local/bin/brackets</code> 符号链接.",
  "ERROR_CLTOOLS_SERVFAILED": "内部错误.",
  "ERROR_CLTOOLS_NOTSUPPORTED": "该系统不支持命令行快捷方式.",
  "LAUNCH_SCRIPT_CREATE_SUCCESS": "成功! 现在你可以通过这样的命令简单地启动 {APP_NAME} 了: <code>brackets myFile.txt</code> 打开文件, <code>brackets myFolder</code> 切换项目, <br/><br/><a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments'>点击此处</a>了解更多 {APP_NAME} 命令行的使用方法.",
  "ERROR_LOADING_EXTENSION": "加载扩展程序出错",
  "ERROR_NO_EXTENSION_PACKAGE": "在当前项目中未检测到 <code>package.json</code> 文件。当前项目是有效的 {APP_NAME} 扩展程序吗？</br>请参阅<a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>此链接</a>了解更多详细信息。",
  "ERROR_INVALID_EXTENSION_PACKAGE": "<code>package.json</code> 文件是无效的 JSON。</br>请参阅<a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>此链接</a>了解更多详细信息。",
  "ERROR_INVALID_EXTENSION_PACKAGE_FIELDS": "<code>package.json</code> 中缺少必填字段：[{0}] </br>请参阅<a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>此链接</a>了解更多详细信息。",
  "ERROR_NODE_JS_CRASH_TITLE": "哎呀！出了点问题。",
  "ERROR_NODE_JS_CRASH_MESSAGE": "我们遇到了问题，需要重新启动 {APP_NAME}。别担心，我们正在尝试在重新启动之前保存您的所有工作。</br>（错误：ERROR_NODE_JS_CRASH）",
  "LANGUAGE_TITLE": "切换语言",
  "LANGUAGE_MESSAGE": "请从列表中选择所需的语言:",
  "LANGUAGE_SUBMIT": "重新加载 {APP_NAME}",
  "LANGUAGE_CANCEL": "取消",
  "LANGUAGE_SYSTEM_DEFAULT": "系统默认",
  "HEALTH_DATA_NOTIFICATION": "健康报告首选项",
  "HEALTH_FIRST_POPUP_TITLE": "隐私声明",
  "HEALTH_DATA_DO_TRACK": "分享我使用 {APP_NAME} 的匿名信息",
  "HEALTH_DATA_NOTIFICATION_MESSAGE": "{APP_NAME} <strong>不会收集或处理任何个人身份信息</strong>，但<strong>会收集匿名的使用统计数据</strong>以保护您的隐私。匿名数据不受 GDPR/CCPA 通知要求的约束，但我们认为您也需要有选择退出匿名数据收集的权利。<br><br>您可以通过选择<strong>帮助 > 健康报告</strong>来查看您的数据或<strong>选择不共享任何匿名数据</strong>。这些<strong>匿名的</strong>应用使用统计数据和错误报告有助于确定功能优先级、查找错误和发现可用性问题，从而改善您使用 {APP_NAME} 的体验。如果没有这些数据，我们将无法了解哪些功能值得为您构建！<br>",
  "HEALTH_DATA_PREVIEW": "{APP_NAME} 健康报告",
  "HEALTH_DATA_PREVIEW_INTRO": "<p>{APP_NAME} <strong>不会收集或处理任何个人身份信息</strong>，但会<strong>收集匿名使用统计数据</strong>来保护您的隐私。这些<strong>匿名</strong>应用使用统计数据和错误报告有助于确定功能优先级、查找错误和发现可用性问题，从而改善您使用 {APP_NAME} 的体验。</p> <p>以下是您的下一个健康报告<em>如果</em>启用将发送的数据预览。（另请参阅开发者控制台中标记为“Caught Critical error”的错误日志。）</p>",
  "HEALTH_DATA_PREVIEW_NECESSARY": "安全/应用更新、分析库初始化、用户数量和使用时间等应用健康指标将以匿名方式收集。这些是聚合统计数据，不会发送/记录任何个人数据。",
  "INLINE_TIMING_EDITOR_TIME": "时间",
  "INLINE_TIMING_EDITOR_PROGRESSION": "进程",
  "BEZIER_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd><kbd>←</kbd><kbd>→</kbd> 移动选中点<br><kbd class='text'>Shift</kbd> 10倍移动<br><kbd class='text'>Tab</kbd> 切换点",
  "STEPS_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd> 增减步进<br><kbd>←</kbd><kbd>→</kbd> 切换 'Start' 或 'End'",
  "INLINE_TIMING_EDITOR_INVALID": "原值 <code>{0}</code> 无效, 函数值已变为 <code>{1}</code>. 文档将在首次编辑时更新.",
  "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP": "当前的颜色",
  "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP": "原来的颜色",
  "COLOR_EDITOR_RGBA_BUTTON_TIP": "RGBa 格式",
  "COLOR_EDITOR_HEX_BUTTON_TIP": "十六进制格式",
  "COLOR_EDITOR_HSLA_BUTTON_TIP": "HSLa 格式",
  "COLOR_EDITOR_0X_BUTTON_TIP": "十六进制 (0x) 格式",
  "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR": "{0} (使用 {1} 次)",
  "COLOR_EDITOR_USED_COLOR_TIP_PLURAL": "{0} (使用 {1} 次)",
  "EDIT": "编辑",
  "CMD_JUMPTO_DEFINITION": "跳转到源代码定义处",
  "CMD_SHOW_PARAMETER_HINT": "显示参数提示",
  "NO_ARGUMENTS": "<无相应参数>",
  "DETECTED_EXCLUSION_TITLE": "JavaScript 文件引用问题",
  "DETECTED_EXCLUSION_INFO": "{APP_NAME} 在处理 <span class='dialog-filename'>{0}</span> 时遇到问题。<br><br>此文件将不再进行代码提示、跳转到定义或快速编辑的处理。要重新启用此文件，请在项目中打开 <code>.phcode.json</code> 并编辑 <code>jscodehints.detectedExclusions</code>。<br><br>这可能是 {APP_NAME} 的一个错误。如果您能提供此文件的副本，请<a href='https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue'>提交错误报告</a>，并在报告中提供此文件的链接。",
  "CMD_REFACTOR": "重构",
  "CMD_EXTRACTTO_VARIABLE": "提取到变量",
  "CMD_EXTRACTTO_FUNCTION": "提取到函数",
  "ERROR_TERN_FAILED": "无法从 Tern 获取数据",
  "ERROR_EXTRACTTO_VARIABLE_NOT_VALID": "所选内容无法构成表达式",
  "ERROR_EXTRACTTO_FUNCTION_NOT_VALID": "所选代码块应表示一组语句或一个表达式",
  "ERROR_EXTRACTTO_VARIABLE_MULTICURSORS": "“提取到变量”功能不支持多光标",
  "ERROR_EXTRACTTO_FUNCTION_MULTICURSORS": "“提取到函数”功能不支持多光标",
  "EXTRACTTO_FUNCTION_SELECT_SCOPE": "选择目标作用域",
  "EXTRACTTO_VARIABLE_SELECT_EXPRESSION": "选择一个表达式",
  "CMD_REFACTORING_RENAME": "重命名",
  "CMD_REFACTORING_TRY_CATCH": "用 Try Catch 包装",
  "CMD_REFACTORING_CONDITION": "用条件语句包装",
  "CMD_REFACTORING_GETTERS_SETTERS": "创建 Getter/Setter",
  "CMD_REFACTORING_ARROW_FUNCTION": "转换为箭头函数",
  "DESCRIPTION_CODE_REFACTORING": "启用/禁用 JavaScript 代码重构",
  "ERROR_TRY_CATCH": "选择有效代码以包裹在 Try-catch 块中",
  "ERROR_WRAP_IN_CONDITION": "选择有效代码以包裹在条件块中",
  "ERROR_ARROW_FUNCTION": "将光标置于函数表达式内",
  "ERROR_GETTERS_SETTERS": "将光标置于对象表达式的成员上",
  "ERROR_RENAME_MULTICURSOR": "使用多光标时无法重命名",
  "ERROR_RENAME_QUICKEDIT": "无法重命名此标识符，因为它在此函数外部被引用",
  "ERROR_RENAME_GENERAL": "无法重命名选定的文本",
  "JSHINT_NAME": "JSHint",
  "JSHINT_CONFIG_ERROR": "读取 JSHint 配置文件出错：{0}",
  "JSHINT_CONFIG_JSON_ERROR": "错误：JSHint 配置文件“{0}”不是有效的 JSON",
  "ESLINT_NAME": "ESLint",
  "CSS_LINT_NAME": "{0}",
  "HTML_LINT_NAME": "HTML",
  "HTML_LINT_CONFIG_JSON_ERROR": "错误：HTML 验证器配置文件“{0}”不是有效的 JSON",
  "HTML_LINT_CONFIG_UNSUPPORTED": "错误：不支持的配置文件格式“{0}”。请使用 JSON 配置文件“.htmlvalidate.json”",
  "CMD_ENABLE_QUICK_VIEW": "鼠标悬停时启用快速查看",
  "CMD_ENABLE_SELECTION_VIEW": "选定内容查看",
  "TOOLTIP_CLICK_TO_EDIT_COLOR": "点击编辑颜色",
  "CMD_RECENT_PROJECTS": "最近的项目",
  "REMOVE_FROM_RECENT_PROJECTS": "从最近项目中移除",
  "DOCS_MORE_LINK": "更多信息",
  "DOCS_MORE_LINK_MDN_TITLE": "点击阅读文档",
  "COLLAPSE_ALL": "收起所有",
  "EXPAND_ALL": "展开所有",
  "COLLAPSE_CURRENT": "收起当前",
  "EXPAND_CURRENT": "展开当前",
  "RECENT_FILES_DLG_HEADER": "最近打开的文件",
  "RECENT_FILES_DLG_CLEAR_BUTTON_LABEL": "清除",
  "RECENT_FILES_DLG_CLEAR_BUTTON_TITLE": "清除不在工作区的文件",
  "RECOVER_UNSAVED_FILES_TITLE": "恢复未保存的文件？",
  "RECOVER_UNSAVED_FILES_MESSAGE": "是否恢复上个会话中未保存的文件？",
  "RECOVER_UNSAVED_FILES_RESTORE": "恢复",
  "DISCARD_UNSAVED_FILES_RESTORE": "丢弃",
  "DESCRIPTION_CLOSE_BRACKETS": "值为真时，自动闭合括号",
  "DESCRIPTION_CLOSE_OTHERS_ABOVE": "值为假时，从工作区右键菜单中移除 \"关闭上面的其他文件\" 项",
  "DESCRIPTION_CLOSE_OTHERS_BELOW": "值为假时，从工作区右键菜单中移除 \"关闭下面的其他文件\" 项",
  "DESCRIPTION_CLOSE_OTHERS": "值为假时，从工作区右键菜单中移除 \"关闭其他文件\" 项",
  "DESCRIPTION_CLOSE_TAGS": "设置标签自动闭合选项",
  "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS": "不应自动闭合的一组标签",
  "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING": "键入起始标签的 > 字符时闭合",
  "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING": "键入结束标签的 / 字符时闭合",
  "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS": "标签内容另起一行的一组标签",
  "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD": "值为真时，总是在缩进级别改变后可折叠区域标记",
  "DESCRIPTION_CODE_FOLDING_ENABLED": "值为真时，开启代码折叠",
  "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER": "值为真时，区域折叠标记只会在鼠标移动到折叠处显示",
  "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL": "限制展开全部所限制的最大层级数",
  "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE": "显示可折叠区域图标的最小行数",
  "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES": "值为真时，关闭或打开文件/项目也会记住所折叠的区域",
  "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE": "值为真时，在编辑器中开启选定文本的代码折叠功能",
  "DESCRIPTION_DISABLED_DEFAULT_EXTENSIONS": "默认禁用的扩展",
  "DESCRIPTION_ATTR_HINTS": "开启/关闭 HTML 属性提示",
  "DESCRIPTION_CSS_PROP_HINTS": "开启/关闭 CSS/LESS/SCSS 属性名提示",
  "DESCRIPTION_JS_HINTS": "开启/关闭 JavaScript 代码提示",
  "DESCRIPTION_JS_HINTS_TYPE_DETAILS": "开启/关闭 JavaScript 代码的数据类型提示",
  "DESCRIPTION_PREF_HINTS": "开启/关闭配置文件选项提示",
  "DESCRIPTION_SPECIAL_CHAR_HINTS": "开启/关闭 HTML 实体提示",
  "DESCRIPTION_SVG_HINTS": "开启/关闭 SVG 代码提示",
  "DESCRIPTION_HTML_TAG_HINTS": "开启/关闭 HTML 标签提示",
  "DESCRIPTION_URL_CODE_HINTS": "开启/关闭 HTML & CSS/LESS/SCSS 中的 URL 提示",
  "DESCRIPTION_DRAG_DROP_TEXT": "开启/关闭拖曳功能",
  "DESCRIPTION_HEALTH_DATA_TRACKING": "开启健康数据跟踪",
  "DESCRIPTION_HIGHLIGHT_MATCHES": "开启文档中匹配字符串的自动高亮",
  "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN": "高亮匹配光标处符号的所有字符串(无需选区)",
  "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY": "仅在选区为完整符号时高亮",
  "DESCRIPTION_INSERT_HINT_ON_TAB": "值为真时，插入在标签页上选择的代码",
  "DESCRIPTION_NO_HINTS_ON_DOT": "值为真时，不再在输入 . 符号后自动显示 JS 代码提示",
  "DESCRIPTION_JSHINT_DISABLE": "true 表示在问题面板中禁用 JSHints 代码检查器",
  "DESCRIPTION_ESLINT_DISABLE": "在问题面板中禁用 ESLint 检查器，设为 true",
  "DESCRIPTION_HTML_LINT_DISABLE": "在问题面板中禁用 HTML 检查器，设为 true",
  "DESCRIPTION_ESLINT_FAILED": "ESLint 失败 ({0})。请确保项目包含有效的 <a href='https://eslint.org/docs/latest/use/configure/configuration-files'>配置文件</a>",
  "DESCRIPTION_ESLINT_USE_NATIVE_APP": "ESLint 仅在桌面应用程序中可用。请从 <a href='https://phcode.io'>phcode.io</a> 下载",
  "DESCRIPTION_ESLINT_LOAD_FAILED": "无法为此项目加载 ESLint。{APP_NAME} 仅支持 7 以上版本的 ESLint。",
  "DESCRIPTION_ESLINT_DO_NPM_INSTALL": "请在您的项目上运行 `npm install` 以启用 ESLint",
  "DESCRIPTION_LANGUAGE": "语言特定设置",
  "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS": "扩展名到语言名的附加映射",
  "DESCRIPTION_LANGUAGE_FILE_NAMES": "文件名到语言名的附加映射",
  "DESCRIPTION_LINEWISE_COPY_CUT": "在没有选择内容的情况下执行复制和剪切操作将复制或剪切光标所在的行",
  "DESCRIPTION_INPUT_STYLE": "选择 CodeMirror 处理输入和焦点的方式。可以是 textarea，这是默认设置，也可以是 contenteditable，这更适合屏幕阅读器（不稳定）。",
  "DESCRIPTION_LINTING_ENABLED": "值为真时，开启代码检查器",
  "DESCRIPTION_ASYNC_TIMEOUT": "异步检查器的超时时间",
  "DESCRIPTION_LINTING_PREFER": "首先运行的代码检查器列表",
  "DESCRIPTION_LIVE_DEV_MULTIBROWSER": "值为真时，开启实验性的实时预览",
  "DESCRIPTION_USE_PREFERED_ONLY": "值为真时，只使用 linting.prefer 指定的提供商",
  "DESCRIPTION_MAX_CODE_HINTS": "一次显示最多的提示数",
  "DESCRIPTION_PATH": "路径特定设置",
  "DESCRIPTION_PROXY": "扩展安装所用的代理服务器 URL",
  "DESCRIPTION_SCROLL_PAST_END": "值为真时，允许滚动超出文档末尾",
  "DESCRIPTION_SHOW_CODE_HINTS": "值为假时，关闭所有代码提示",
  "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING": "有文字选区时保持光标闪烁",
  "DESCRIPTION_SHOW_LINE_NUMBERS": "值为真时，在代码左侧显示行号",
  "DESCRIPTION_RULERS_COLUMNS": "用于在编辑器中绘制垂直标尺的列号数组。例如：[80, 100]",
  "DESCRIPTION_RULERS_COLORS": "与编辑器中 rulers 选项对应的标尺颜色数组。例如：[\"#3d3d3d\", \"red\"]",
  "DESCRIPTION_RULERS_ENABLED": "将此设置为 true 可启用编辑器标尺，否则为 false",
  "DESCRIPTION_AUTO_RENAME_TAGS": "将此设置为 true 可自动重命名配对的 HTML/XML 标签，否则为 false",
  "DESCRIPTION_DRAG_AND_DROP_ENABLED": "将此设置为 true 可启用从文件资源管理器或 Finder 中拖放文件和文件夹的功能",
  "DESCRIPTION_TRIPLE_CTRL_PALETTE": "将此设置为 true 可在连续三次按下 Ctrl/Cmd 键时显示可视化命令面板",
  "DESCRIPTION_SMART_INDENT": "生成新区域时自动缩进",
  "DESCRIPTION_SOFT_TABS": "值为假时，关闭软 tab 功能",
  "DESCRIPTION_SORT_DIRECTORIES_FIRST": "值为真时，给项目数中的文件夹排序",
  "DESCRIPTION_SPACE_UNITS": "空格缩进所使用的空格数",
  "DESCRIPTION_STATIC_SERVER_PORT": "内置服务器开启实时预览所使用的端口号",
  "DESCRIPTION_STYLE_ACTIVE_LINE": "值为真时，高亮显示光标所在行的背景颜色",
  "DESCRIPTION_TAB_SIZE": "一个 Tab 键所代表的空格数",
  "DESCRIPTION_USE_TAB_CHAR": "值为真时，使用 tab 字符而不用空格",
  "DESCRIPTION_AUTO_TAB_SPACE": "将此设置为 true 可自动检测当前文件中使用的制表符和空格",
  "DESCRIPTION_UPPERCASE_COLORS": "值为真时，在内联的色彩编辑器中生成大写的16进制色彩值",
  "DESCRIPTION_WORD_WRAP": "超过可视区域时换行",
  "DESCRIPTION_SEARCH_AUTOHIDE": "编辑器获得焦点后立即关闭搜索",
  "DESCRIPTION_DETECTED_EXCLUSIONS": "检测会导致 Tern 失效的文件列表",
  "DESCRIPTION_INFERENCE_TIMEOUT": "Tern 尝试解析文件所需要的超时时长",
  "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR": "值为真时，在状态栏显示错误",
  "DESCRIPTION_QUICK_VIEW_ENABLED": "值为真时，开启快速查看",
  "DESCRIPTION_SELECTION_VIEW_ENABLED": "true 表示启用选定内容查看",
  "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW": "值为真时，为缺少 URL 的扩展程序显示图像预览",
  "DESCRIPTION_NUMBER_QUICK_VIEW": "true 表示在编辑器中将鼠标悬停在数字上时显示快速查看",
  "DESCRIPTION_THEME": "选择一个 {APP_NAME} 主题",
  "DESCRIPTION_USE_THEME_SCROLLBARS": "值为真时，允许自定义滚动条",
  "DESCRIPTION_EDITOR_LINE_HEIGHT": "调整编辑器中代码行之间的垂直间距。选择 1 到 3 之间的值，默认为 1.5",
  "DESCRIPTION_LINTING_COLLAPSED": "值为真时，折叠提示面板",
  "DESCRIPTION_FONT_FAMILY": "改变字体",
  "DESCRIPTION_DESKTOP_ZOOM_SCALE": "选择缩放比例因子，范围从 0.1（更紧凑的视图）到 2（更大、更放大的视图）。仅在桌面应用程序中可用",
  "DESCRIPTION_FONT_SIZE": "改变字号，例如 13px",
  "DESCRIPTION_FIND_IN_FILES_NODE": "值为真时，开启基于 node 的搜索",
  "DESCRIPTION_FIND_IN_FILES_INSTANT": "值为真时，开启实时搜索",
  "DESCRIPTION_FONT_SMOOTHING": "仅Mac: \"subpixel-antialiased\" 开启次像素防锯齿或者 \"antialiased\" 开启灰阶防锯齿",
  "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW": "值为假时，不再划分一个窗口打开用户配置",
  "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE": "值为假时，在左边/顶部窗格中打开用户设置",
  "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED": "值为真时，折叠面板头部关闭后最后一个文件之后的面板",
  "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS": "切换头部显示关闭或者翻转视图的按钮。",
  "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT": "/*",
  "DEFAULT_PREFERENCES_JSON_DEFAULT": "默认",
  "DESCRIPTION_PURE_CODING_SURFACE": "值为真时，开启纯代码模式，隐藏 {APP_NAME} 的其他 UI 元素",
  "DESCRIPTION_INDENT_LINE_COMMENT": "值为真时，开启行注释缩进",
  "DESCRIPTION_RECENT_FILES_NAV": "开启/关闭最近文件导航",
  "DESCRIPTION_LIVEDEV_WEBSOCKET_PORT": "实时预览的 WebSocket 服务器运行端口。",
  "DESCRIPTION_LIVEDEV_ENABLE_REVERSE_INSPECT": "设为 false 可禁用实时预览反向检查。",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW": "无可预览内容！",
  "DESCRIPTION_LIVEDEV_EXCLUDED": "自定义服务器无法提供此文件",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW_EXCLUDED": "实时预览设置已配置为仅提供来自“{0}”文件夹的文件",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW_DETAILS": "请选择一个 HTML 文件进行预览",
  "DESCRIPTION_LIVEDEV_PREVIEW_RESTRICTED": "预览不可用！",
  "DESCRIPTION_LIVEDEV_PREVIEW_RESTRICTED_DETAILS": "此 HTML 文件并非当前项目的一部分。出于安全考虑，只能实时预览项目文件。要预览此文件，请将其所在文件夹作为单独的项目打开。",
  "DESCRIPTION_LIVEDEV_MAIN_HEADING": "哎呀！<br>您当前的浏览器不支持实时预览。",
  "DESCRIPTION_LIVEDEV_MAIN_SPAN": "从 <a href=\"https://phcode.io\" style=\"color: white\">phcode.io</a> 下载适用于 Windows、Mac 和 Linux 的原生应用，以获得最佳实时预览体验。<br>",
  "DESCRIPTION_LIVEDEV_SECURITY_POPOUT_MESSAGE": "您即将打开一个文件进行实时预览。仅当您信任此项目的来源时，才继续操作。单击“信任项目”继续，或者如果您不信任来源，请关闭此窗口。",
  "DESCRIPTION_LIVEDEV_SECURITY_TRUST_MESSAGE": "您即将打开一个文件进行实时预览。仅当您信任此项目的来源时，才单击“信任项目”继续！",
  "CONFIRM_EXTERNAL_BROWSER_TITLE": "弹出窗口已被阻止",
  "CONFIRM_EXTERNAL_BROWSER_MESSAGE": "是否允许实时预览页面打开此 URL：{0}？",
  "TRUST_PROJECT": "信任并执行预览 - {0}",
  "TRUST_AUTHORS": "您信任此项目的作者吗？",
  "DOWNLOAD_FAILED": "下载失败。",
  "DOWNLOAD_COMPLETE": "下载完成！",
  "UPDATE_SUCCESSFUL": "更新成功！",
  "UPDATE_FAILED": "更新失败！",
  "VALIDATION_FAILED": "验证失败！",
  "INITIALISATION_FAILED": "初始化失败！",
  "CLEANUP_FAILED": "清理失败！",
  "WARNING_TYPE": "警告！",
  "CLICK_RESTART_TO_UPDATE": "点击“重新启动”以更新 Brackets。",
  "UPDATE_ON_NEXT_LAUNCH": "更新将在下次启动时应用。",
  "GO_TO_SITE": "前往 <a href = \"http://brackets.io/\"> brackets.io </a> 重试。",
  "INTERNET_UNAVAILABLE": "当前无网络连接。",
  "UPDATEDIR_READ_FAILED": "无法读取更新目录。",
  "UPDATEDIR_CLEAN_FAILED": "无法清理更新目录。",
  "INITIAL_DOWNLOAD": "正在下载更新…",
  "RETRY_DOWNLOAD": "下载失败，正在重试…尝试",
  "VALIDATING_INSTALLER": "下载完成！正在验证安装程序…",
  "CHECKSUM_DID_NOT_MATCH": "校验和不匹配。",
  "INSTALLER_NOT_FOUND": "找不到安装程序。",
  "DOWNLOAD_ERROR": "下载过程中发生错误。",
  "NETWORK_SLOW_OR_DISCONNECTED": "网络连接断开或速度太慢。",
  "RESTART_BUTTON": "重启",
  "RESTART_APP_BUTTON": "重启 {APP_NAME}",
  "LATER_BUTTON": "稍后",
  "DESCRIPTION_AUTO_UPDATE": "启用/禁用 {APP_NAME} 自动更新",
  "AUTOUPDATE_ERROR": "错误！",
  "AUTOUPDATE_IN_PROGRESS": "更新已在进行中。",
  "REMOVING": "正在删除…",
  "NUMBER_WITH_PERCENTAGE": "{0}%",
  "CMD_FIND_RELATED_FILES": "查找相关文件",
  "PHP_VERSION_INVALID": "解析 PHP 版本时出错。请检查“php –version”命令的输出。",
  "PHP_UNSUPPORTED_VERSION": "安装 PHP7 运行时以启用 PHP 相关工具，例如代码提示、参数提示、跳转到定义等。找到的版本：{0}",
  "PHP_EXECUTABLE_NOT_FOUND": "未找到 PHP 运行时。请安装 PHP7 运行时并在 PHP 首选项中更新“executablePath”。这将启用 PHP 相关工具，例如代码提示、参数提示、跳转到定义等。",
  "PHP_PROCESS_SPAWN_ERROR": "启动 PHP 进程时遇到错误代码 {0}。",
  "PHP_SERVER_ERROR_TITLE": "错误",
  "PHP_SERVER_MEMORY_LIMIT_INVALID": "您提供的内存限制无效。请查看 PHP 首选项以设置正确的值。",
  "DESCRIPTION_PHP_TOOLING_CONFIGURATION": "PHP 工具默认配置设置",
  "OPEN_PREFERENNCES": "打开首选项",
  "LANGUAGE_TOOLS_PREFERENCES": "语言工具首选项",
  "FIND_ALL_REFERENCES": "查找所有引用",
  "REFERENCES_IN_FILES": "引用",
  "REFERENCE_IN_FILES": "引用",
  "REFERENCES_NO_RESULTS": "光标当前位置没有可用引用",
  "CMD_FIND_DOCUMENT_SYMBOLS": "查找文档符号",
  "CMD_FIND_PROJECT_SYMBOLS": "查找项目符号",
  "REMOTE_DEBUGGING_ENABLED": "已在 localhost:{0} 上启用远程调试",
  "REMOTE_DEBUGGING_PORT_INVALID": "无法在端口 {0} 上启用远程调试。端口号应介于 {1} 和 {2} 之间。",
  "DESCRIPTION_EXTERNAL_APPLICATION_ASSOCIATE": "文件扩展名到外部应用程序的映射。语法：\"<file_type>\": \"<default|applicationName|ApplicationPath>\"，使用 \"default\" 在文件类型的系统默认应用程序中打开文件。",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_TITLE": "在外部编辑器中打开图形文件",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_MSG": "你当前的文件夹包含{APP_NAME}不支持的图形文件类型。<br/>现在你可以将特定文件类型与外部编辑器关联。关联后，你可以通过双击文件树中的文件，在默认应用程序中打开 .xd、.psd、.jpg、.png、.ai、.svg 等图形文件。<br/><br/>请点击“确定”按钮将图形文件类型与其各自的默认应用程序关联。",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_CNF_MSG": "以下文件类型已成功与默认应用程序关联。<br/>{0} 你可以通过“调试->打开首选项文件”菜单，在 phcode.json 中更改是否删除/添加新的文件类型关联的首选项。",
  "UNSUPPORTED_BROWSER_TITLE": "浏览器不支持",
  "UNSUPPORTED_BROWSER_MESSAGE": "请使用现代浏览器（最近三年内发布的）。",
  "UNSUPPORTED_BROWSER_MOBILE_TITLE": "不支持移动浏览器",
  "UNSUPPORTED_BROWSER_MOBILE": "目前尚不完全支持移动和平板电脑浏览器。您可以关闭此对话框，但 Phoenix 的某些功能在此浏览器中将无法使用。<br/><br/>我们正在开发适用于 iOS 和 Android 的原生应用。<a href=\"https://github.com/phcode-dev/phoenix/discussions/1046\" target=\"_blank\">点击此处加入讨论！</a>",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER_TITLE": "浏览器不支持访问本地文件夹",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER": "抱歉，您当前的浏览器似乎不支持打开本地文件夹。对于此功能，我们建议使用 Chrome、Edge 或 Opera。<br/><br/>或者，我们正在开发适用于 Windows、Mac、Linux、iOS 和 Android 的原生应用以提供全面支持。<a href=\"https://github.com/phcode-dev/phoenix/discussions/1047\" target=\"_blank\">敬请期待更新！</a>",
  "ATTENTION_SAFARI_USERS": "致 Safari 用户",
  "ATTENTION_SAFARI_USERS_MESSAGE": "<span>如果 7 天内未再次访问某个网站，Safari 会自动删除该网站的数据。{APP_NAME} 依靠浏览器存储来保存您的项目，这些项目可能会因这项策略而被删除。<br/> <br/>建议您从 <a href='https://phcode.io' target='_blank' style='color: white'>https://phcode.io</a><strong> 下载 macOS 桌面应用程序</strong></span>",
  "CANNOT_PUBLISH_LARGE_PROJECT": "无法发布大型项目",
  "CANNOT_PUBLISH_LARGE_PROJECT_MESSAGE": "Phoenix 仍处于实验性 alpha 阶段。我们尚未启用超过 500 个文件的项目同步功能。",
  "SHARE_WEBSITE": "发布并分享网站？",
  "PUBLISH": "发布",
  "PUBLISH_CONSENT_MESSAGE": "快速预览更改并与他人分享您的网站。{APP_NAME} 可以在 {0} 为您发布此网站。发布的链接将在 3 天内有效。</br>您是否要发布并分享您的网站？",
  "PUBLISH_SYNC_IN_PROGRESS": "预览同步中…",
  "PUBLISH_PAGE": "点击发布并分享此网站",
  "PUBLISH_VIEW_PAGE": "点击查看已发布页面",
  "MISSING_FIELDS": "字段缺失",
  "PLEASE_FILL_ALL_REQUIRED": "请填写所有标红必填项",
  "CODE_EDITOR": "代码编辑器",
  "BUILD_THE_WEB": "Web 开发",
  "IMPORT_PROJECT": "导入项目",
  "GIT_PROJECT": "从 Git 获取",
  "NEW_PROJECT_FROM_GIT": "基于 Git 的新项目",
  "GIT_REPO_URL": "Git 仓库 URL：",
  "GIT_CLONE_URL": "Git 克隆 URL：",
  "START_PROJECT": "开始项目…",
  "DOWNLOAD_DESKTOP_APP": "下载桌面应用",
  "GET_DESKTOP_APP": "获取桌面应用",
  "CREATE_PROJECT": "创建项目",
  "SETTING_UP_PROJECT": "正在设置项目",
  "LOCATION": "位置：",
  "ERROR_ONLY_GITHUB": "浏览器版本的 {APP_NAME} 仅支持 GitHub URL。如需使用其他 Git URL，请使用桌面应用程序。",
  "ERROR_GIT_URL_INVALID": "请输入有效的 Git 克隆 URL。",
  "ERROR_GIT_FOLDER_NOT_EMPTY": "所选文件夹非空或不可读，无法用于 Git 克隆。",
  "ERROR_GIT_FOLDER_NOT_EXIST": "所选文件夹不存在，无法用于 Git 克隆。",
  "ERROR_CLONING_TITLE": "Git 克隆失败",
  "DOWNLOADING": "正在下载…",
  "DOWNLOADING_FILE": "正在下载 {0}…",
  "EXTRACTING_FILES_PROGRESS": "正在解压，已完成 {0} 个文件，共 {1} 个。",
  "COMPRESS_FILES_PROGRESS": "正在压缩，已完成 {0} 个文件，共 {1} 个。",
  "DOWNLOAD_FAILED_MESSAGE": "请确保下载 URL 有效。</br>注意：由于 Phoenix 处于 alpha 阶段，不支持私有仓库和大于 25 MB 的 GitHub URL。",
  "PLEASE_SELECT_A_FOLDER": "请选择一个文件夹…",
  "UNZIP_IN_PROGRESS": "正在解压缩文件…",
  "UNZIP_FAILED": "错误：解压失败。",
  "CONFIRM_REPLACE_TITLE": "确认替换",
  "KEEP_BOTH": "保留两者",
  "EXPLORE": "HTML 游戏",
  "BLOG": "博客",
  "PHOENIX_DEFAULT_PROJECT": "默认项目",
  "PROJECT_NAME": "项目名称：",
  "NEW_HTML": "新建 HTML 项目",
  "LICENSE": "许可证和致谢：",
  "PREVIEW": "预览",
  "BUILD_WEBSITE": "构建网站",
  "VIEW_MORE": "查看更多...",
  "NEW_PROJECT_NOTIFICATION": "点击此图标可再次打开“新建项目”窗口。</br>查看最近项目、打开文件夹或从模板启动项目。</br> <img src=\"styles/images/new_project.png\">",
  "BEAUTIFY_CODE_NOTIFICATION": "点击此处或按 <b>`{0}`</b> 美化代码。</br> <img src=\"styles/images/beautify.gif\">",
  "DEFAULT_PROJECT_NOTIFICATION": "在 {APP_NAME} 中打开<b>默认项目</b>即可快速开始（非常适合用作暂存板）。</br></br>或者，使用下面的<strong>打开文件夹</strong>图标从您的计算机打开一个文件夹。<br><a href='#' style='float:right;'>确定</a>",
  "DIRECTORY_REPLACE_MESSAGE": "所选文件夹 <span class='dialog-filename'>{0}</span> 不为空。您确定要用项目替换文件夹内容吗？",
  "DEFAULT_PROJECT_HTML_CLICK_HERE": "点击此处可在 HTML 文件中找到此 &lt;span&gt;",
  "BUILD_WEBSITE_SECTION": "构建网站",
  "LEARN_SECTION": "通过示例学习",
  "CREATE_EXTENSION_SECTION": "创建 {APP_NAME} 扩展和主题",
  "CREATE_EXTENSION": "创建扩展",
  "CREATE_THEME": "创建主题",
  "WEBPAGE_HOME_PAGE": "首页",
  "WEBPAGE_BLOG": "博客",
  "WEBPAGE_DASHBOARD": "HTML 仪表板",
  "WEBPAGE_BOOTSTRAP_EXAMPLES": "Bootstrap 示例",
  "PROJECTS_AT_A_GLANCE": "项目概览",
  "PROJECT_AT_GLANCE_DESCRIPTION": "观看视频快速入门。",
  "PROJECT_FROM_BROWSER": "存储在您的浏览器中",
  "PROJECT_FROM_BROWSER_TERSE": "浏览器存储",
  "PROJECT_SHOW_ON_STARTUP": "启动时显示此对话框",
  "GUIDED_LIVE_PREVIEW": "在 HTML 文件中进行一些代码更改以查看实时预览。</br> <a href='#' style='float:right;'>确定</a>",
  "GUIDED_LIVE_PREVIEW_POPOUT": "点击此按钮可将实时预览弹出到新标签页。</br> <a href='#' style='float:right;'>确定</a>",
  "TEST_TRANSLATE": "使用此测试翻译",
  "BEAUTIFY_ERROR": "无法美化代码。请检查语法。",
  "BEAUTIFY_ERROR_ORIGINAL_CHANGED": "无法美化。美化后编辑器文本已更改。",
  "BEAUTIFY_PROJECT_BUSY_MESSAGE": "正在美化文件 {0}",
  "BEAUTIFY_ERROR_SELECTION": "无法美化。</br>选择的代码块不完整或语法无效。",
  "BEAUTIFY_OPTIONS": "控制代码美化方式的选项",
  "BEAUTIFY_OPTION_PRINT_WIDTH": "指定美化器换行的行长度",
  "BEAUTIFY_OPTION_SEMICOLON": "在每个语句的末尾添加分号",
  "BEAUTIFY_OPTION_SINGLE_QUOTE": "使用单引号代替双引号",
  "BEAUTIFY_OPTION_QUOTE_PROPS": "更改对象中属性何时加引号",
  "BEAUTIFY_OPTION_BRACKET_SAME_LINE": "将多行 HTML（HTML、JSX、Vue、Angular）元素的 > 放在最后一行的末尾，而不是单独放在下一行（不适用于自闭合元素）",
  "BEAUTIFY_OPTION_SINGLE_ATTRIBUTE_PER_LINE": "在 HTML、Vue 和 JSX 中强制每行只有一个属性",
  "BEAUTIFY_OPTION_PROSE_WRAP": "如果 Markdown 文件中的文本超过打印宽度，则进行换行",
  "BEAUTIFY_OPTION_PRINT_TRAILING_COMMAS": "尽可能在多行逗号分隔的语法结构中打印尾随逗号",
  "DESCRIPTION_INDENT_GUIDES_ENABLED": "显示缩进参考线：`true` 显示，`false` 不显示。",
  "DESCRIPTION_HIDE_FIRST": "显示第一条缩进参考线：`true` 显示，`false` 不显示。",
  "DESCRIPTION_CSS_COLOR_PREVIEW": "在边栏中显示颜色预览：`true` 显示，`false` 不显示。",
  "DESCRIPTION_EMMET": "启用 Emmet 输入 true，否则输入 false。",
  "DESCRIPTION_SHOW_WORKING_SET": "true 显示工作集，false 隐藏。",
  "DESCRIPTION_TABBAR": "设置标签栏设置。",
  "DESCRIPTION_SHOW_TABBAR": "显示标签栏则为 true，否则为 false。",
  "DESCRIPTION_NUMBER_OF_TABS": "标签栏中显示的标签页数量。设置为 -1 以显示所有标签页",
  "TABBAR_SHOW_HIDDEN_TABS": "显示隐藏的标签页",
  "ENABLE_GIT": "启用 Git",
  "ACTION": "操作",
  "STATUSBAR_SHOW_GIT": "Git 面板",
  "ADD_ENDLINE_TO_THE_END_OF_FILE": "在文件末尾添加换行符",
  "ADD_TO_GITIGNORE": "添加到 .gitignore",
  "AMEND_COMMIT": "修改上次提交",
  "SKIP_COMMIT_CHECKS": "跳过预提交检查 (--no-verify)",
  "AMEND_COMMIT_FORBIDDEN": "没有未推送的提交时无法修改提交",
  "_ANOTHER_BRANCH": "其他分支",
  "AUTHOR": "作者",
  "AUTHORS_OF": "作者",
  "SYSTEM_CONFIGURATION": "系统配置",
  "BRACKETS_GIT_ERROR": "Git 遇到错误…",
  "BRANCH_NAME": "分支名称",
  "BUTTON_CANCEL": "取消",
  "CHECKOUT_COMMIT": "检出",
  "CHECKOUT_COMMIT_DETAIL": "<b>提交信息：</b> {0} <br><b>提交哈希：</b> {1}",
  "GIT_CLONE": "克隆",
  "BUTTON_CLOSE": "关闭",
  "BUTTON_COMMIT": "提交",
  "BUTTON_DEFAULTS": "恢复默认值",
  "BUTTON_FIND_CONFLICTS": "查找冲突…",
  "GIT_INIT": "初始化",
  "BUTTON_MERGE_ABORT": "中止合并",
  "BUTTON_OK": "确认",
  "BUTTON_REBASE_ABORT": "中止",
  "BUTTON_REBASE_CONTINUE": "继续变基",
  "BUTTON_REBASE_SKIP": "跳过",
  "MENU_RESET_HARD": "丢弃此提交之后的所有更改和提交（硬重置）",
  "MENU_RESET_MIXED": "丢弃此提交之后的所有提交，但保留未暂存的更改（混合重置）",
  "MENU_RESET_SOFT": "丢弃此提交之后的所有提交，但保留已暂存的更改（软重置）",
  "MENU_TAG_COMMIT": "标记提交",
  "RESET_HARD_TITLE": "确认硬重置",
  "RESET_MIXED_TITLE": "确认混合重置",
  "RESET_SOFT_TITLE": "确认软重置",
  "RESET_DETAIL": "<b>以下提交将被丢弃：</b><br><b>提交信息：</b> {0}<br><b>Git 命令：</b> {1}",
  "RESET_HARD_MESSAGE": "此操作将丢弃所选提交之后的所有更改和提交。<b>此操作不易撤消。</b> 确定要继续吗？<br><br>⚠️ 警告：此操作会重写历史记录，不应在已推送到共享分支的提交上使用。",
  "RESET_MIXED_MESSAGE": "此操作将丢弃所选提交之后的所有提交，但会将所有更改保留为未暂存状态。<b>此操作不易撤消。</b> 确定要继续吗？<br><br>⚠️ 警告：此操作会重写历史记录，不应在已推送到共享分支的提交上使用。",
  "RESET_SOFT_MESSAGE": "此操作将丢弃所选提交之后的所有提交，但会将所有更改暂存以进行新的提交。<b>此操作不易撤消。</b> 确定要继续吗？<br><br>⚠️ 警告：此操作会重写历史记录，不应在已推送到共享分支的提交上使用。",
  "BUTTON_SAVE": "保存",
  "RESET": "重置",
  "CHANGE_USER_EMAIL_TITLE": "更改 Git 邮箱",
  "CHANGE_USER_EMAIL": "更改 Git 邮箱…",
  "CHANGE_USER_EMAIL_MENU": "更改 Git 邮箱 ({0})…",
  "CHANGE_USER_NAME_TITLE": "更改 Git 用户名",
  "CHANGE_USER_NAME": "更改 Git 用户名…",
  "CHANGE_USER_NAME_MENU": "更改 Git 用户名（{0}）…",
  "REQUIRES_APP_RESTART_SETTING": "此设置的更改需要重新启动应用程序才能生效",
  "CLEAN_FILE_END": "文件已清理",
  "CLEAN_FILE_START": "正在清理文件",
  "CLEANING_WHITESPACE_PROGRESS": "正在清理文件中的空格…",
  "CLEAR_WHITESPACE_ON_FILE_SAVE": "保存文件时清除空格",
  "CLONE_REPOSITORY": "克隆仓库",
  "CODE_INSPECTION_PROBLEMS": "代码检查问题",
  "CODE_INSPECTION_IN_PROGRESS": "代码检查进行中…",
  "CODE_INSPECTION_PROBLEMS_NONE": "未检测到问题",
  "CODE_INSPECTION_DONE_FILES": "已完成 {0}/{1} 个文件…",
  "PLEASE_WAIT": "请稍候…",
  "COMMIT": "提交",
  "COMMIT_ALL_SHORTCUT": "提交所有文件…",
  "COMMIT_CURRENT_SHORTCUT": "提交当前文件…",
  "COMMIT_MESSAGE_PLACEHOLDER": "在此处输入提交消息…",
  "CREATE_NEW_BRANCH": "创建新分支…",
  "CREATE_NEW_BRANCH_TITLE": "创建新分支",
  "CREATE_NEW_GITFTP_SCOPE": "创建新的 Git-FTP 远程仓库…",
  "CREATE_NEW_REMOTE": "创建新的远程仓库…",
  "CURRENT_TRACKING_BRANCH": "当前跟踪分支",
  "_CURRENT_TRACKING_BRANCH": "当前跟踪分支",
  "DEFAULT_GIT_TIMEOUT": "默认 Git 操作超时时间（秒）",
  "DELETE_FILE_BTN": "删除文件…",
  "DELETE_LOCAL_BRANCH": "删除本地分支",
  "DELETE_LOCAL_BRANCH_NAME": "确定要删除本地分支“{0}”吗？",
  "DELETE_REMOTE": "删除远程仓库",
  "DELETE_REMOTE_NAME": "确定要删除远程仓库“{0}”吗？",
  "DELETE_SCOPE": "删除 Git-FTP 作用域",
  "DELETE_SCOPE_NAME": "确定要删除 Git-FTP 作用域“{0}”吗？",
  "DIALOG_CHECKOUT": "检出提交时，仓库将进入分离 HEAD 状态。除非您基于此创建一个分支，否则无法进行任何提交。",
  "DIALOG_PULL_TITLE": "从远程仓库拉取",
  "DIALOG_PUSH_TITLE": "推送到远程仓库",
  "SKIP_PRE_PUSH_CHECKS": "跳过推送前检查 (--no-verify)",
  "DIFF": "差异",
  "DIFFTOOL": "使用 difftool 查看差异",
  "DIFF_FAILED_SEE_FILES": "Git diff 无法提供差异结果。以下是待提交的暂存文件列表：",
  "DIFF_TOO_LONG": "差异过长，无法显示",
  "ENABLE_GERRIT_PUSH_REF": "使用 Gerrit 兼容的推送引用",
  "ENTER_NEW_USER_EMAIL": "输入邮箱",
  "ENTER_NEW_USER_NAME": "输入用户名",
  "ENTER_PASSWORD": "输入密码：",
  "ENTER_REMOTE_GIT_URL": "输入要克隆的仓库的 Git URL：",
  "ENTER_REMOTE_NAME": "输入新的远程名称：",
  "ENTER_REMOTE_URL": "输入新的远程 URL：",
  "ENTER_USERNAME": "输入用户名：",
  "ERROR_NOTHING_SELECTED": "未选择任何内容！",
  "ERROR_SAVE_FIRST": "请先保存文档！",
  "ERROR_TERMINAL_NOT_FOUND": "找不到适用于您操作系统的终端，您可以在设置中自定义终端命令",
  "EXTENDED_COMMIT_MESSAGE": "扩展",
  "GETTING_STAGED_DIFF_PROGRESS": "获取已暂存文件的差异…",
  "GIT_COMMIT": "Git 提交…",
  "GIT_COMMIT_IN_PROGRESS": "Git 提交中",
  "GIT_DIFF": "Git 差异 &mdash;",
  "GIT_PULL_RESPONSE": "Git 拉取响应",
  "GIT_PUSH_RESPONSE": "Git 推送响应",
  "GIT_REMOTES": "Git 远程仓库",
  "GIT_SETTINGS": "Git 设置…",
  "GIT_SETTINGS_TITLE": "Git 设置",
  "GOTO_NEXT_GIT_CHANGE": "转到下一个 Git 变更",
  "GOTO_PREVIOUS_GIT_CHANGE": "跳转到上一个 Git 变更",
  "GUTTER_CLICK_DETAILS": "点击查看详情",
  "HIDE_UNTRACKED": "在面板中隐藏未跟踪的文件",
  "HISTORY": "历史记录",
  "HISTORY_COMMIT_BY": "作者：",
  "LINES": "行数",
  "_LINES": "行",
  "MARK_MODIFIED_FILES_IN_TREE": "在文件树中标记已修改的文件",
  "MERGE_BRANCH": "合并分支",
  "MERGE_MESSAGE": "合并消息",
  "MERGE_RESULT": "合并结果",
  "NORMALIZE_LINE_ENDINGS": "标准化行尾（转换为 \\n）",
  "NOTHING_TO_COMMIT": "无需提交，工作目录干净。",
  "OPERATION_IN_PROGRESS_TITLE": "Git 操作进行中…",
  "ORIGIN_BRANCH": "远程分支",
  "ON_BRANCH": "'{0}' - 当前 Git 分支",
  "PANEL_COMMAND": "显示 Git 面板",
  "PASSWORD": "密码",
  "PASSWORDS": "密码",
  "PATH_TO_GIT_EXECUTABLE": "Git 可执行文件路径",
  "PULL_AVOID_MERGING": "避免手动合并",
  "PULL_DEFAULT": "默认合并",
  "PULL_FROM": "拉取自",
  "PULL_MERGE_NOCOMMIT": "合并但不提交",
  "PULL_REBASE": "使用变基",
  "PULL_RESET": "使用软重置",
  "PULL_SHORTCUT": "从远程拉取…",
  "PULL_SHORTCUT_BEHIND": "从远程拉取（落后 {0} 个提交）…",
  "PULL_BEHAVIOR": "拉取行为",
  "FETCH_SHORTCUT": "从远程获取",
  "PUSH_DEFAULT": "默认推送",
  "PUSH_DELETE_BRANCH": "删除远程分支",
  "PUSH_SEND_TAGS": "推送标签",
  "PUSH_FORCED": "强制推送",
  "PUSH_SHORTCUT": "推送到远程…",
  "PUSH_SHORTCUT_AHEAD": "推送到远程（超前 {0} 个提交）…",
  "PUSH_TO": "推送到",
  "PUSH_BEHAVIOR": "推送行为",
  "Q_UNDO_CHANGES": "是否重置文件 <span class='dialog-filename'>{0}</span> 的更改？",
  "REBASE_RESULT": "变基结果",
  "REFRESH_GIT": "刷新 Git",
  "REMOVE_BOM": "从文件中删除 BOM",
  "REMOVE_FROM_GITIGNORE": "从 .gitignore 中移除",
  "RESET_LOCAL_REPO": "放弃自上次提交以来的所有更改…",
  "DISCARD_CHANGES": "放弃更改",
  "RESET_LOCAL_REPO_CONFIRM": "您确定要放弃自上次提交以来所做的所有更改吗？此操作无法撤消。",
  "UNDO_LOCAL_COMMIT_CONFIRM": "您确定要撤销上次未推送的提交吗？",
  "MORE_OPTIONS": "更多选项",
  "CREDENTIALS": "凭据",
  "SAVE_CREDENTIALS_HELP": "如果您的凭据在其他地方管理，则无需填写用户名/密码。仅当您的操作持续超时时才使用此选项。",
  "SAVE_CREDENTIALS_IN_URL": "将凭据保存到远程 URL（明文）",
  "SET_THIS_BRANCH_AS_TRACKING": "将此分支设置为新的跟踪分支",
  "STRIP_WHITESPACE_FROM_COMMITS": "从提交中去除尾随空格",
  "TARGET_BRANCH": "目标分支",
  "TITLE_CHECKOUT": "检出提交？",
  "TOOLTIP_CLONE": "克隆现有仓库",
  "TOOLTIP_COMMIT": "提交选中的文件",
  "TOOLTIP_FETCH": "获取所有远程分支并刷新计数器",
  "TOOLTIP_FIND_CONFLICTS": "在项目中开始搜索 Git 合并/变基冲突",
  "TOOLTIP_HIDE_FILE_HISTORY": "隐藏文件历史记录",
  "TOOLTIP_HIDE_HISTORY": "隐藏历史记录",
  "TOOLTIP_INIT": "初始化仓库",
  "TOOLTIP_MERGE_ABORT": "放弃合并操作并将 HEAD 重置为上次本地提交",
  "TOOLTIP_PICK_REMOTE": "选择首选远程仓库",
  "TOOLTIP_PULL": "Git 拉取",
  "TOOLTIP_PUSH": "Git 推送",
  "TOOLTIP_REBASE_ABORT": "放弃变基操作并将 HEAD 重置为原始分支",
  "TOOLTIP_REBASE_CONTINUE": "解决合并冲突后重新启动变基过程",
  "TOOLTIP_REBASE_SKIP": "跳过当前补丁并重新启动变基过程",
  "TOOLTIP_REFRESH_PANEL": "刷新面板",
  "TOOLTIP_SHOW_FILE_HISTORY": "显示文件历史记录",
  "TOOLTIP_SHOW_HISTORY": "显示历史记录",
  "GIT_SHOW_FILE_HISTORY": "文件提交历史",
  "GIT_SHOW_HISTORY": "提交历史",
  "UNDO_CHANGES": "丢弃更改",
  "UNDO_CHANGES_BTN": "丢弃更改…",
  "UNDO_LAST_LOCAL_COMMIT": "撤销上次本地（未推送）提交…",
  "UNDO_COMMIT": "撤销提交",
  "URL": "网址",
  "USERNAME": "用户名",
  "USER_ABORTED": "用户已取消！",
  "USE_GIT_GUTTER": "使用 Git 侧边标记",
  "USE_NOFF": "即使合并可以快进，也创建合并提交（--no-ff）",
  "USE_REBASE": "使用变基",
  "USE_VERBOSE_DIFF": "在差异比较中显示详细输出",
  "USE_DIFFTOOL": "使用差异比较工具",
  "VIEW_AUTHORS_FILE": "查看文件作者…",
  "VIEW_AUTHORS_SELECTION": "查看选中部分的作者…",
  "VIEW_THIS_FILE": "查看此文件",
  "TAG_NAME_PLACEHOLDER": "在此处输入标签名称…",
  "TAG_NAME": "标签",
  "CMD_CLOSE_UNMODIFIED": "关闭未修改的文件",
  "FILE_ADDED": "新建文件",
  "FILE_COPIED": "已复制",
  "FILE_DELETED": "已删除",
  "FILE_IGNORED": "已忽略",
  "FILE_MODIFIED": "已修改",
  "FILE_RENAMED": "已重命名",
  "FILE_STAGED": "已暂存",
  "FILE_UNMERGED": "未合并",
  "FILE_UNMODIFIED": "未修改",
  "FILE_UNTRACKED": "未跟踪",
  "GIT_PUSH_SUCCESS_MSG": "快速推送成功",
  "GIT_PUSH_FORCE_UPDATED_MSG": "强制更新成功",
  "GIT_PUSH_DELETED_MSG": "成功删除引用",
  "GIT_PUSH_NEW_REF_MSG": "成功推送新引用",
  "GIT_PUSH_REJECTED_MSG": "引用被拒绝或推送失败",
  "GIT_PUSH_UP_TO_DATE_MSG": "引用已更新，无需推送",
  "GIT_PULL_SUCCESS": "Git 拉取完成",
  "GIT_MERGE_SUCCESS": "Git 合并完成",
  "GIT_REBASE_SUCCESS": "Git 变基完成",
  "GIT_BRANCH_DELETE_SUCCESS": "Git 分支删除成功",
  "INIT_NEW_REPO_FAILED": "新建仓库失败",
  "GIT_CLONE_REMOTE_FAILED": "克隆远程仓库失败！",
  "GIT_CLONE_ERROR_EXPLAIN": "所选目录“{0}”",
  "FOLDER_NOT_WRITABLE": "所选目录“{0}”",
  "GIT_NOT_FOUND_MESSAGE": "未安装 Git 或在系统上找不到 Git。请安装 Git 或在下面的文本字段中提供 Git 可执行文件的正确路径。",
  "ERROR_GETTING_BRANCH_LIST": "获取分支列表失败",
  "ERROR_READING_GIT_HEAD": "读取 .git/HEAD 文件失败",
  "ERROR_PARSING_BRANCH_NAME": "从 {0} 解析分支名称失败",
  "ERROR_READING_GIT_STATE": "读取 .git 状态失败",
  "ERROR_GETTING_DELETED_FILES": "获取已删除文件列表失败",
  "ERROR_SWITCHING_BRANCHES": "切换分支失败",
  "ERROR_GETTING_CURRENT_BRANCH": "获取当前分支名称失败",
  "ERROR_REBASE_FAILED": "变基失败",
  "ERROR_MERGE_FAILED": "合并失败",
  "ERROR_BRANCH_DELETE_FORCED": "强制删除分支失败",
  "ERROR_FETCH_REMOTE_INFO": "获取远程信息失败",
  "ERROR_CREATE_BRANCH": "创建新分支失败",
  "ERROR_REFRESH_GUTTER": "刷新行号槽失败！",
  "ERROR_GET_HISTORY": "获取历史记录失败",
  "ERROR_GET_MORE_HISTORY": "加载更多历史记录行失败",
  "ERROR_GET_CURRENT_BRANCH": "获取当前分支名称失败",
  "ERROR_GET_DIFF_FILE_COMMIT": "获取差异失败",
  "ERROR_GET_DIFF_FILES": "获取差异文件列表失败",
  "ERROR_MODIFY_GITIGNORE": "修改 .gitignore 失败",
  "ERROR_UNDO_LAST_COMMIT_FAILED": "无法撤销上次提交",
  "ERROR_MODIFY_FILE_STATUS_FAILED": "无法修改文件状态",
  "ERROR_CHANGE_USERNAME_FAILED": "无法更改用户名",
  "ERROR_CHANGE_EMAIL_FAILED": "无法更改用户邮箱",
  "ERROR_TOGGLE_GERRIT_PUSH_REF_FAILED": "无法切换 Gerrit 推送引用",
  "ERROR_RESET_LOCAL_REPO_FAILED": "重置本地仓库失败",
  "ERROR_CREATE_TAG": "创建标签失败",
  "ERROR_CODE_INSPECTION_FAILED": "CodeInspection.inspectFile 执行失败，文件：",
  "ERROR_CANT_GET_STAGED_DIFF": "无法获取已暂存文件的差异",
  "ERROR_STAGE_FAILED": "Git 文件暂存失败",
  "ERROR_GIT_COMMIT_FAILED": "Git 提交失败",
  "ERROR_GIT_BLAME_FAILED": "Git 追溯失败",
  "ERROR_GIT_DIFF_FAILED": "Git 比较失败",
  "ERROR_DISCARD_CHANGES_FAILED": "丢弃文件更改失败",
  "ERROR_COULD_NOT_RESOLVE_FILE": "无法解析文件",
  "ERROR_MERGE_ABORT_FAILED": "合并中止失败",
  "ERROR_MODIFIED_DIALOG_FILES": "您要提交的文件在提交对话框显示期间已被修改。由于结果与对话框中显示的内容不同，因此中止提交。",
  "ERROR_GETTING_REMOTES": "获取远程仓库失败！",
  "ERROR_REMOTE_CREATION": "创建远程仓库失败",
  "ERROR_PUSHING_REMOTE": "推送到远程仓库失败",
  "ERROR_PULLING_REMOTE": "从远程仓库拉取失败",
  "ERROR_PULLING_OPERATION": "拉取操作失败",
  "ERROR_PUSHING_OPERATION": "推送操作失败",
  "ERROR_NO_REMOTE_SELECTED": "未为 {0} 选择远程仓库！",
  "ERROR_BRANCH_LIST": "获取分支列表失败",
  "ERROR_FETCH_REMOTE": "获取远程仓库信息失败",
  "ERROR_PREPARING_COMMIT_DIALOG": "准备提交对话框失败",
  "GIT_TOAST_TITLE": "探索 Phoenix Code 中的 Git 功能",
  "GIT_TOAST_MESSAGE": "点击 Git 面板图标来管理您的仓库。一站式轻松完成提交、推送、拉取和查看项目历史。<br><a href='https://docs.phcode.dev/app-links/git'>进一步了解 Git 面板 →</a>",
  "SURVEY_TITLE_VOTE_FOR_FEATURES_YOU_WANT": "为您希望看到的下一个功能投票！",
  "SIGNED_OUT": "您已退出登录。",
  "SIGNED_OUT_MESSAGE": "您已退出 {APP_NAME} 帐户。请重新登录以继续。",
  "SIGNED_OUT_MESSAGE_FRIENDLY": "感谢您使用 {APP_NAME}。下次再见！",
  "SIGNED_IN_OFFLINE_TITLE": "离线 - 无法登录",
  "SIGNED_IN_OFFLINE_MESSAGE": "请连接到互联网以登录 {APP_NAME}。",
  "SIGNED_IN_FAILED_TITLE": "无法登录",
  "SIGNED_IN_FAILED_MESSAGE": "登录时出现问题。请重试。",
  "SIGNED_OUT_FAILED_TITLE": "退出登录失败",
  "SIGNED_OUT_FAILED_MESSAGE": "登出时出错。请按“确定”打开<a href='https://account.phcode.dev/#advanced'>account.phcode.dev</a>手动登出。",
  "VALIDATION_CODE_TITLE": "登录验证码",
  "VALIDATION_CODE_MESSAGE": "请使用此验证码登录您的{APP_NAME}帐户：",
  "COPY_VALIDATION_CODE": "复制验证码",
  "VALIDATION_CODE_COPIED": "已复制",
  "OPEN_SIGN_IN_URL": "打开登录页面",
  "PROFILE_POP_TITLE": "{APP_NAME} 帐户",
  "PROFILE_SIGN_IN": "登录您的帐户",
  "CONTACT_SUPPORT": "联系支持",
  "SIGN_OUT": "退出登录",
  "SIGN_IN": "登录",
  "ACCOUNT_DETAILS": "帐户详情",
  "LOGIN_REFRESH": "检查登录状态",
  "SIGN_IN_WAITING_TITLE": "等待登录",
  "SIGN_IN_WAITING_MESSAGE": "请在新标签页中完成登录，然后返回此处。",
  "WAITING_FOR_LOGIN": "正在登录…",
  "CHECK_NOW": "立即检查",
  "CHECKING": "正在检查…",
  "CHECKING_STATUS": "正在检查登录状态…",
  "NOT_SIGNED_IN_YET": "尚未登录。请在另一个标签页中完成登录。",
  "WELCOME_BACK": "欢迎回来",
  "WELCOME_BACK_USER": "欢迎回来，{0}！",
  "POPUP_BLOCKED": "弹窗被阻止。请允许弹窗并重试，或手动导航至 {0}",
  "COLLAPSE_ALL_FOLDERS": "折叠所有文件夹",
  "CUSTOM_SNIPPETS_MENU_ITEM_NAME": "自定义代码片段…",
  "CUSTOM_SNIPPETS_PANEL_TITLE": "自定义代码片段",
  "CUSTOM_SNIPPETS_ADD_PANEL_TITLE": "添加代码片段",
  "CUSTOM_SNIPPETS_EDIT_PANEL_TITLE": "编辑代码片段",
  "CUSTOM_SNIPPETS_ADD_NEW_TITLE": "添加新代码片段",
  "CUSTOM_SNIPPETS_BACK_TO_LIST_TITLE": "返回代码片段列表",
  "CUSTOM_SNIPPETS_BACK": "返回",
  "CUSTOM_SNIPPETS_FILTER_PLACEHOLDER": "筛选…",
  "CUSTOM_SNIPPETS_NO_SNIPPETS_MESSAGE": "尚未添加自定义代码片段！",
  "CUSTOM_SNIPPETS_ADD_SNIPPET_BTN": "添加代码片段",
  "CUSTOM_SNIPPETS_ABBREVIATION_LABEL": "缩写：",
  "CUSTOM_SNIPPETS_TEMPLATE_TEXT_LABEL": "模板文本：",
  "CUSTOM_SNIPPETS_DESCRIPTION_LABEL": "描述：",
  "CUSTOM_SNIPPETS_FILE_EXTENSION_LABEL": "文件扩展名：",
  "CUSTOM_SNIPPETS_CANCEL": "取消",
  "CUSTOM_SNIPPETS_SAVE": "保存",
  "CUSTOM_SNIPPETS_NO_DESCRIPTION": "没有描述",
  "CUSTOM_SNIPPETS_NO_MATCHES": "没有与“{0}”匹配的代码片段",
  "CUSTOM_SNIPPETS_LEARN_MORE": "添加您自己的代码提示以加快编码速度 - <a href=\"https://docs.phcode.dev/app-links/custom-snippets\" target=\"_blank\">了解更多</a>",
  "CUSTOM_SNIPPETS_DUPLICATE_ERROR": "缩写为“{0}”的代码片段已存在。",
  "CUSTOM_SNIPPETS_SPACE_ERROR": "空格不是有效的缩写字符。",
  "CUSTOM_SNIPPETS_ABBR_LENGTH_ERROR": "缩写不能超过 30 个字符。",
  "CUSTOM_SNIPPETS_DESC_LENGTH_ERROR": "描述不能超过 80 个字符。",
  "CUSTOM_SNIPPETS_HINT_LABEL": "代码片段",
  "CUSTOM_SNIPPETS_EDIT_ABBR_TOOLTIP": "点击编辑缩写 - {0}",
  "CUSTOM_SNIPPETS_EDIT_TEMPLATE_TOOLTIP": "点击编辑模板文本 - {0}",
  "CUSTOM_SNIPPETS_EDIT_DESC_TOOLTIP": "点击编辑描述 - {0}",
  "CUSTOM_SNIPPETS_ADD_DESC_TOOLTIP": "点击添加描述",
  "CUSTOM_SNIPPETS_EDIT_FILE_EXT_TOOLTIP": "点击编辑文件扩展名 - {0}",
  "CUSTOM_SNIPPETS_ABBR_INPUT_TOOLTIP": "输入简短缩写（例如“clg”、“fn”、“div”）。这将是您触发代码片段时键入的内容。",
  "CUSTOM_SNIPPETS_DESC_INPUT_TOOLTIP": "此代码片段功能的简要描述。如果不需要描述，请留空。",
  "CUSTOM_SNIPPETS_FILE_EXT_INPUT_TOOLTIP": "指定此代码片段适用的文件类型（例如“.js”、“.html”、“.css”）。留空则适用于所有文件。",
  "CUSTOM_SNIPPETS_TEMPLATE_INPUT_TOOLTIP": "将要插入的实际代码。使用 ${1}、${2}、${3} 等表示光标位置。${1} 是初始位置，Tab 键将光标移动到 ${2}、${3} 等。${0} 是最终位置。",
  "CUSTOM_SNIPPETS_DESC_PLACEHOLDER": "控制台日志快捷方式（可选）",
  "CUSTOM_SNIPPETS_FILE_EXT_PLACEHOLDER": "留空表示所有文件，或指定例如 .js、.html",
  "CUSTOM_SNIPPETS_TEMPLATE_PLACEHOLDER": "`console.log(${1});`",
  "CUSTOM_SNIPPETS_HEADER_ABBREVIATION": "缩写",
  "CUSTOM_SNIPPETS_HEADER_TEMPLATE": "模板文本",
  "CUSTOM_SNIPPETS_HEADER_DESCRIPTION": "描述",
  "CUSTOM_SNIPPETS_HEADER_FILE_EXTENSION": "文件扩展名",
  "PROMO_UPGRADE_TITLE": "您已升级到 {0}",
  "PROMO_UPGRADE_MESSAGE": "在接下来的 {0} 天内畅享这些高级功能：",
  "PROMO_CARD_1": "实时预览编辑",
  "PROMO_CARD_1_MESSAGE": "直接在实时预览中编辑内容和元素 - 剪切、复制、粘贴、创建副本、删除 - 不会打断您的工作流程。",
  "PROMO_CARD_2": "拖放元素",
  "PROMO_CARD_2_MESSAGE": "直观地重排版块 - 只需几秒即可尝试更多布局创意，告别耗时数分钟的编码。",
  "PROMO_CARD_3": "素材图片库",
  "PROMO_CARD_3_MESSAGE": "浏览免版权图片 - 悬停即时预览，点击即可应用。更快地尝试更多选项。",
  "PROMO_CARD_4": "检查元素布局",
  "PROMO_CARD_4_MESSAGE": "在同一视图中进行设计和检查 - 悬停可查看间距、尺寸和类。标尺参考线可实现像素级完美对齐。",
  "PROMO_LEARN_MORE": "了解更多…",
  "PROMO_UPGRADE_APP_UPSELL_BUTTON": "升级到 {0}",
  "PROMO_PRO_ENDED_TITLE": "{0} 试用已结束",
  "PROMO_PHOENIX_PRO_ENDED_MESSAGE": "感谢您试用 Pro！<b>您现在使用的是免费社区版。</b><br>随时升级即可解锁以下功能：",
  "PROMO_PRO_UNLOCK_PRO_TITLE": "释放 {0} 的强大功能",
  "PROMO_PRO_CONTINUE_ON_FREE": "继续使用免费版",
  "PROMO_PRO_UNLOCK_LIVE_EDIT_TITLE": "使用 {0} 解锁实时编辑功能",
  "PROMO_PRO_UNLOCK_MESSAGE": "立即订阅以解锁以下高级功能：",
  "PROMO_PRO_TRIAL_DAYS_LEFT": "Phoenix Pro 试用版（剩余 {0} 天）",
  "PRO_TRIAL_ENDING_TITLE": "您的 {0} 升级将在 {1} 天后结束",
  "PRO_TRIAL_ENDING_TITLE_TOMORROW": "您的 {0} 升级将于明天结束",
  "PRO_TRIAL_ENDING_MESSAGE": "我们将在 {0} 天后自动<b>将您切换到免费社区版</b>。<br>立即升级以继续使用以下 Pro 功能：",
  "PRO_TRIAL_ENDING_MESSAGE_TOMORROW": "我们将在明天自动<b>将您切换到免费社区版</b>。<br>立即升级以继续使用以下 Pro 功能：",
  "GET_PRO_NOT_NOW": "暂不",
  "GET_PHOENIX_PRO": "获取 Phoenix Pro",
  "MANAGE_LICENSE_DIALOG_TITLE": "管理设备许可证",
  "LICENSE_KEY": "许可证密钥",
  "LICENSE_KEY_PLACEHOLDER": "输入您的许可证密钥…",
  "LICENSE_KEY_ACTIVATE": "激活许可证",
  "LICENSE_KEY_ACTIVATING": "正在激活…",
  "LICENSE_KEY_CURRENT": "当前设备许可证",
  "LICENSE_KEY_CHECKING": "正在检查许可证状态…",
  "LICENSE_KEY_NONE": "未找到有效的设备许可证",
  "LICENSE_STATUS_ACTIVE": "已激活",
  "LICENSE_INFO_STATUS_LABEL": "状态：",
  "LICENSE_INFO_LICENSED_TO_LABEL": "授权给：",
  "LICENSE_INFO_TYPE_LABEL": "许可证类型：",
  "LICENSE_INFO_VALID_UNTIL_LABEL": "有效期至：",
  "LICENSE_CHECK_ERROR": "检查许可证状态时出错",
  "LICENSE_STATUS_UNKNOWN": "未知",
  "LICENSE_VALID_NEVER": "永不过期",
  "LICENSE_STATUS_ERROR_CHECK": "检查许可证状态时出错",
  "LICENSE_ACTIVATE_SUCCESS": "许可证已在系统范围内激活。请重启 {APP_NAME} 以使更改生效。",
  "LICENSE_ACTIVATE_SUCCESS_PARTIAL": "许可证仅为您的账户激活（非系统范围）。请重启 {APP_NAME} 以使更改生效。",
  "LICENSE_ACTIVATE_FAIL": "激活许可证失败",
  "LICENSE_ACTIVATE_FAIL_APPLY": "未能将许可证应用于设备",
  "LICENSE_ENTER_KEY": "请输入许可证密钥",
  "LICENSE_REAPPLY_TO_DEVICE": "已激活？重新应用至全系统",
  "DEPRECATED_EXTENSIONS_TITLE": "检测到已弃用的扩展",
  "DEPRECATED_EXTENSIONS_MESSAGE": "以下已安装的扩展现已由 {APP_NAME} 原生支持，可以从扩展管理器中安全卸载：",
  "DEPRECATED_EXTENSIONS_LEARN_MORE": "现已内置 — 了解更多",
  "AI_LOGIN_DIALOG_TITLE": "登录以使用 AI 编辑",
  "AI_LOGIN_DIALOG_MESSAGE": "请登录以使用 AI 编辑功能",
  "AI_LOGIN_DIALOG_BUTTON": "获取 AI 访问权限",
  "AI_DISABLED_DIALOG_TITLE": "AI 已禁用",
  "AI_CONTROL_ALL_ALLOWED_NO_CONFIG": "系统中未找到 AI 配置文件。AI 已为所有用户启用。",
  "AI_CONTROL_ALL_ALLOWED": "AI 已为所有用户启用。",
  "AI_CONTROL_USER_ALLOWED": "AI 已为用户 ({0}) 启用，但为其他用户禁用。",
  "AI_CONTROL_ADMIN_DISABLED": "AI 访问权限已被您的系统管理员禁用。",
  "AI_CONTROL_ADMIN_DISABLED_CONTACT": "AI 访问权限已被您的系统管理员禁用。请联系 {0} 以获取帮助。",
  "AI_UPSELL_DIALOG_TITLE": "继续使用 {0}？",
  "AI_UPSELL_DIALOG_MESSAGE": "您发现了 {0}。要继续，您需要 AI 订阅或点数。",
  "DEMO_DELETE_KEY": "删除",
  "DEMO_ALT_DUPLICATE_ICON": "创建副本",
  "DEMO_ALT_DELETE_ICON": "删除",
  "DEMO_SECTION1_TITLE": "在实时预览中编辑",
  "DEMO_SECTION1_SUBTITLE": "可视化编辑页面 -&nbsp; <b>HTML 代码即时更新</b>",
  "DEMO_GET_STARTED_BUTTON": "开始使用",
  "DEMO_SECTION2_TITLE": "编辑文本",
  "DEMO_SECTION2_SUBTITLE": "双击编辑下方文本并添加您的姓名",
  "DEMO_EDITABLE_PLACEHOLDER_HELLO": "你好 ___",
  "DEMO_SECTION2_SUCCESS_MESSAGE": "您的编辑已更新代码 — 使用 <span id=\"undo-shortcut\"></span> 撤销，使用 <span id=\"redo-shortcut\"></span> 重做。",
  "DEMO_HINT_COMPLETE_TASK_LABEL": "要完成此任务：",
  "DEMO_SECTION2_HINT_STEP1": "双击“你好 ___”文本",
  "DEMO_SECTION2_HINT_STEP2": "用您的姓名替换下划线",
  "DEMO_SECTION2_HINT_STEP3": "按 Enter 键或在外部单击以应用您的更改",
  "DEMO_SECTION3_TITLE": "实时更换图片",
  "DEMO_SECTION3_SUBTITLE": "单击下面的图片，从图片库中选择您喜欢的图片进行替换。",
  "DEMO_SECTION3_SUCCESS_URL": "您知道吗？您可以使用图片库中的 <img src=\"images/download.svg\" alt=\"Download\" class=\"inline-icon\"> 下载按钮来下载图片。",
  "DEMO_SECTION3_SUCCESS_LOCAL": "您知道吗？您可以单击图片直接使用，无需下载。",
  "DEMO_SECTION3_HINT_STEP1": "单击上方的图片以打开图片库（双击可切换）",
  "DEMO_SECTION3_HINT_STEP2": "在图片库中：将鼠标悬停在缩略图上可进行预览",
  "DEMO_SECTION3_HINT_STEP3": "单击缩略图可将其放置在您的页面上，或单击 <img src=\"images/download.svg\" alt=\"Download\" class=\"inline-icon\"> 图标先将其下载",
  "DEMO_SECTION4_TITLE": "可视化编辑元素",
  "DEMO_SECTION4_SUBTITLE": "复制<img src=\"images/duplicate.svg\" alt=\"Duplicate\" class=\"inline-icon\">下方的卡片，使其总数达到<strong>3 张卡片</strong>，然后<strong>删除<img src=\"images/trash.svg\" alt=\"Delete\" class=\"inline-icon\"> 1 张卡片</strong>。",
  "DEMO_SECTION4_UNDO_WARNING": "哎呀！所有卡片均已删除。按 <strong><span id=\"undo-shortcut-section4\"></span></strong> 撤销。",
  "DEMO_CARD_TITLE": "卡片",
  "DEMO_CARD_SELECT_PARENT_TIP": "点击上方工具栏中的 <img src=\"images/arrowUp.svg\" alt=\"Up\" class=\"inline-icon\">&nbsp;图标以选择父卡片。",
  "DEMO_SECTION4_SUCCESS_MESSAGE": "完美！您已掌握复制和删除元素。",
  "DEMO_SECTION4_HINT_STEP1": "点击卡片以选中。",
  "DEMO_SECTION4_HINT_STEP2_DUPLICATE": "使用 <img src=\"images/duplicate.svg\" alt=\"Duplicate\" class=\"inline-icon\"> 按钮或按 <strong><span id=\"duplicate-shortcut\"></span></strong> 复制卡片，直到总共有 3 个。",
  "DEMO_SECTION4_HINT_STEP3_DELETE": "选中任意卡片，然后使用 <img src=\"images/trash.svg\" alt=\"Delete\" class=\"inline-icon\"> 按钮或按 <strong>Delete</strong> 键将其删除。",
  "DEMO_SECTION4_HINT_TIP_UNDO_REDO": "提示：您可以按 <strong><span id=\"undo-shortcut-hint\"></span></strong> 撤销，按 <strong><span id=\"redo-shortcut-hint\"></span></strong> 重做。",
  "DEMO_SECTION5_TITLE": "通过拖动重新排序元素",
  "DEMO_SECTION5_SUBTITLE": "拖动任意笔记以更改顺序。",
  "DEMO_STICKY_NOTE_FIRST_PLACE": "第一名",
  "DEMO_STICKY_NOTE_SECOND_PLACE": "第二名",
  "DEMO_STICKY_NOTE_THIRD_PLACE": "第三名",
  "DEMO_SECTION5_SUCCESS_MESSAGE": "您可以将元素拖动到页面上的任意位置来重新排列它们。",
  "DEMO_SECTION5_HINT_STEP1": "点击并按住任意便笺以开始拖动",
  "DEMO_SECTION5_HINT_STEP2": "将其向上或向下移动以更改顺序",
  "DEMO_SECTION5_HINT_STEP3": "松开即可将其放置在新位置",
  "DEMO_SECTION6_TITLE": "编辑链接并预览您的页面",
  "DEMO_SECTION6_SUBTITLE": "选择工具栏中的 <img src=\"images/link.svg\" alt=\"Link\" class=\"inline-icon\"> 图标，以更改此链接指向的位置。",
  "DEMO_LINK_EDIT_LINK": "编辑链接",
  "DEMO_SECTION6_SUCCESS_MESSAGE": "您编辑了一个链接。",
  "DEMO_MODE_EXPLANATION_TITLE": "编辑模式与预览模式",
  "DEMO_EDIT_MODE_LABEL": "编辑模式",
  "DEMO_EDIT_MODE_DESCRIPTION": "在页面上选择并更改内容",
  "DEMO_PREVIEW_MODE_LABEL": "预览模式",
  "DEMO_PREVIEW_MODE_DESCRIPTION": "以访客视角查看您的页面",
  "DEMO_MODE_SWITCH_HINT": "按 <strong>F8</strong> 键或单击 <span class=\"play-button-hint\"><img src=\"images/playButton.svg\" alt=\"Play\" class=\"play-hint-svg svg-gold\"></span> 按钮来切换模式。",
  "DEMO_TIPS_LABEL": "提示：",
  "DEMO_SECTION6_TIP1": "单击任何链接以选中并进行编辑",
  "DEMO_SECTION6_TIP2_NEWTAB": "启用 <strong>在新标签页中打开</strong>，以便在单独的页面中打开链接",
  "DEMO_SECTION6_TIP3_PREVIEW": "切换到预览模式 (<strong>F8</strong>) 以测试链接和交互",
  "DEMO_COMPLETION_TITLE": "您已准备好开始构建！",
  "DEMO_COMPLETION_BODY": "您已学会如何使用实时预览进行编辑。<br>打开包含 HTML 文件的文件夹以开始编辑。",
  "DEMO_COMPLETION_HELP_PROMPT": "需要更多帮助？",
  "DEMO_RESOURCE_YOUTUBE": "YouTube",
  "DEMO_RESOURCE_DOCUMENTATION": "文档",
  "DEMO_BONUS_BADGE": "还有一件事",
  "DEMO_SECTION8_TITLE": "使用测量功能检查布局",
  "DEMO_SECTION8_SUBTITLE": "点击工具栏中的 <img src=\"images/verticalEllipsis.svg\" alt=\"menu\" class=\"inline-icon\"> 并选择 <strong>显示测量</strong>，以查看哪个框未对齐。",
  "DEMO_BOX_CLICK_MENU": "点击 <img src=\"images/verticalEllipsis.svg\" alt=\"menu\" class=\"inline-icon\">",
  "DEMO_BOX_LABEL": "盒子",
  "DEMO_SECTION8_TIP1": "点击工具栏中的 <img src=\"images/verticalEllipsis.svg\" alt=\"更多选项\" class=\"inline-icon\"> 图标，或右键单击打开菜单",
  "DEMO_SECTION8_TIP2_MEASUREMENTS": "启用<strong>显示度量</strong>以查看间距和对齐参考线",
  "DEMO_SECTION8_TIP3": "度量可帮助您快速发现对齐问题",
  "DEMO_ALT_EDIT_TEXT": "编辑文本",
  "DEMO_ALT_IMAGE_LIBRARY": "图片库",
  "DEMO_ALT_DRAG_AND_DROP": "拖放",
  "DEMO_ALT_LAYOUT_RULERS": "布局标尺",
  "DEMO_ALT_REPLACEABLE_IMAGE": "可替换的图片",
  "DEMO_ALT_DOWNLOAD_ICON": "下载",
  "DEMO_ALT_UP_ICON": "向上",
  "DEMO_ALT_LINK_ICON": "链接",
  "DEMO_ALT_PLAY_ICON": "播放",
  "DEMO_ALT_MENU_ICON": "菜单",
  "DEMO_ALT_MORE_OPTIONS_ICON": "更多选项",
  "DEMO_ALT_CARD_IMAGE": "卡片图片",
  "DEMO_ALT_ROCKET": "火箭",
  "DEMO_ALT_ARROW": "箭头"
});