/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "Sistēmas noklusējums",
  "PROJECT_BUSY": "Notiek projekta darbības",
  "DUPLICATING": "Dublējas {0}",
  "MOVING": "Notiek {0} pārvietošana",
  "COPYING": "Notiek {0} kopēšana",
  "DELETING": "Notiek {0} dzēšana",
  "RENAMING": "Pārdēvēšana",
  "STORED_IN_YOUR_BROWSER": "Saglabāts jūsu pārlūkprogrammā",
  "SUPPORT_US_OPEN_COLLECTIVE": "Atbalstiet mūs Open Collective",
  "GENERIC_ERROR": "(kļūda {0})",
  "NOT_FOUND_ERR": "Datne/katalogs netika atrasts.",
  "NOT_READABLE_ERR": "Nevar nolasīt datni/katalogu.",
  "EXCEEDS_MAX_FILE_SIZE": "{APP_NAME} nevar atvērt datnes, lielākas par {0} MB.",
  "NO_MODIFICATION_ALLOWED_ERR": "Izvēlētais katalogs nevar tikt pārveidots.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "Jums nav atļaujas veikt izmaiņas.",
  "CONTENTS_MODIFIED_ERR": "Šī datne ir pārveidota ārpus {APP_NAME}.",
  "UNSUPPORTED_ENCODING_ERR": "{APP_NAME} šobrīd atbalsta tikai UTF-8 kodējuma teksta datnes.",
  "ENCODE_FILE_FAILED_ERR": "{APP_NAME} nevarēja kodēt faila saturu.",
  "DECODE_FILE_FAILED_ERR": "{APP_NAME} nevarēja atšifrēt faila saturu.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "Lietotne {APP_NAME} pašlaik neatbalsta UTF-16 kodētus teksta failus.",
  "FILE_EXISTS_ERR": "Datne vai katalogs jau eksistē.",
  "FILE": "datne",
  "FILE_TITLE": "Datne",
  "DIRECTORY": "katalogs",
  "DIRECTORY_TITLE": "Katalogs",
  "DIRECTORY_NAMES_LEDE": "Katalogu nosaukumi",
  "FILENAMES_LEDE": "Datņu nosaukumi",
  "FILENAME": "Datnes nosaukums",
  "DIRECTORY_NAME": "Kataloga nosaukums",
  "ERROR_LOADING_PROJECT": "Kļūda, ielādējot projektu",
  "OPEN_DIALOG_ERROR": "Radās kļūda, rādot datņu atvēršanas dialogu. (kļūda {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "Radās kļūda, ielādējot katalogu <span class='dialog-filename'>{0}</span>. (error {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "Radās kļūda, nolasot kataloga saturu <span class='dialog-filename'>{0}</span>. (error {1})",
  "ZOOM_WITH_SHORTCUTS": "Izmantojiet īsinājumtaustiņus, lai tuvinātu",
  "ZOOM_WITH_SHORTCUTS_DETAILS": "Lūdzu, izmantojiet īsinājumtaustiņus <code><i>{0}</i></code> , lai tuvinātu, un <code><i>{1}</i></code> , lai tālinātu.",
  "ERROR_OPENING_FILE_TITLE": "Kļūda, verot datni",
  "ERROR_OPENING_FILE": "Radās kļūda, verot datni <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_OPENING_FILES": "Radās kļūda, verot šīs datnes:",
  "ERROR_RELOADING_FILE_TITLE": "Kļūda, pārlādējot izmaiņas no diska",
  "ERROR_RELOADING_FILE": "Radās kļūda, pārlādējot datni <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_SAVING_FILE_TITLE": "Kļūda, saglabājot datni",
  "ERROR_SAVING_FILE": "Radās kļūda, saglabājot datni <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_FILE_TITLE": "Kļūda, pārdēvējot {0}",
  "ERROR_RENAMING_FILE": "Radās kļūda, pārdēvējot {2} <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "Datne vai katalogs nav daļa no pašlaik atvērtā projekta. Diemžēl šobrīd var pārdēvēt tikai projekta datnes.",
  "ERROR_MOVING_FILE_TITLE": "Pārvietojot {0}, radās kļūda",
  "ERROR_MOVING_FILE": "Mēģinot pārvietot {2} <span class='dialog-filename'>{0}</span> , radās kļūda. {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "Failu/mapi nevar pārvietot, jo tie nav pašreizējā projekta daļa.",
  "ERROR_DELETING_FILE_TITLE": "Kļūda, dzēšot {0}",
  "ERROR_DELETING_FILE": "Radās kļūda, dzēšot {2} <span class='dialog-filename'>{0}</span>. {1}",
  "INVALID_FILENAME_TITLE": "Nederīgs {0}",
  "CANNOT_PASTE_TITLE": "Nevar ielīmēt {0}",
  "CANNOT_DOWNLOAD_TITLE": "Nevar lejupielādēt {0}",
  "ERR_TYPE_DOWNLOAD_FAILED": "Lejupielādējot <span class='dialog-filename'>{0}</span> , radās kļūda",
  "ERR_TYPE_PASTE_FAILED": "Ielīmējot <span class='dialog-filename'>{0}</span> uz <span class='dialog-filename'>{1}</span> , radās kļūda",
  "CANNOT_DUPLICATE_TITLE": "Nevar dublēt",
  "ERR_TYPE_DUPLICATE_FAILED": "Dublējot <span class='dialog-filename'>{0}</span> , radās kļūda",
  "ERR_TYPE_DUPLICATE_FAILED_NO_FILE": "Lūdzu, atlasiet failu, ko dublēt.",
  "INVALID_FILENAME_MESSAGE": "{0} nevar izmantot sistēmas rezervētos vārdus, kas beidzas ar punktu (.) vai izmantot šādus simbolus: <code class='emphasized'>{1}</code>",
  "ENTRY_WITH_SAME_NAME_EXISTS": "Jau eksistē datne vai katalogs ar nosaukumu <span class='dialog-filename'>{0}</span> .",
  "ERROR_CREATING_FILE_TITLE": "Kļūda, veidojot {0}",
  "ERROR_CREATING_FILE": "Radās kļūda, veidojot {0} <span class='dialog-filename'>{1}</span>. {2}",
  "ERROR_MIXED_DRAGDROP": "Nevar atvērt mapi, kamēr tiek atvērtas citas datnes.",
  "ERROR_KEYMAP_TITLE": "Kļūda, lasot lietotāja atslēgu karti",
  "ERROR_KEYMAP_CORRUPT": "Atslēgu kartes datne nav derīga JSON datne. Datne tiks atvērta, lai Jūs varētu izlabot formātu.",
  "ERROR_LOADING_KEYMAP": "Atslēgu karte nav derīga UTF-8 kodējuma teksta datne un nevar tikt ielādēta",
  "ERROR_RESTRICTED_COMMANDS": "Nevar piešķirt saīsnes šīm komandām: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "Nevar piešķirt šīs saīsnes: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "Tiek piešķirtas vairākas saīsnes šīm komandām: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "Šīm saīsnēm ir vairākas piesaistes: {0}",
  "ERROR_INVALID_SHORTCUTS": "Šīs saīsnes nav derīgas: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "Tiek piešķirtas saīsnes neeksistējošām komandām: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "Kļūda, lasot iestatījumus",
  "ERROR_PREFS_PROJECT_LINT": "Projekta preferences",
  "ERROR_PREFS_PROJECT_LINT_MESSAGE": "Kļūda: projekts satur gan .brackets.json, gan .phcode.json failus, radot konfliktu. Lūdzu, izdzēsiet `.brackets.json` vai `.phcode.json` un pēc tam atkārtoti ielādējiet projektu.",
  "ERROR_PREFS_CORRUPT": "Iestatījumu datne nav derīga JSON datne. Datne tiks atvērta, lai Jūs varētu izlabot formātu. Nepieciešams restartēt {APP_NAME}, lai izmaiņas stāstos spēkā.",
  "ERROR_PROJ_PREFS_CORRUPT": "Iestatījumu datne nav derīga JSON datne. Datne tiks atvērta, lai Jūs varētu izlabot formātu. Nepieciešams pārlādēt projektu, lai izmaiņas stāstos spēkā.",
  "ERROR_IN_BROWSER_TITLE": "Ups! {APP_NAME} vēl nedarbojas pārlūkā.",
  "ERROR_IN_BROWSER": "{APP_NAME} ir būvēta HTML, bet šobrīd strādā kā darbvirsmas lietotne, tāpēc to var izmantot, lai rediģētu lokālās datnes. Lūdzu, izmantojiet lietotnes čaulu <b>github.com/adobe/brackets-shell</b> repozitorijā, lai palaistu {APP_NAME}.",
  "ERROR_MAX_FILES_TITLE": "Kļūda, indeksējot datnes",
  "ERROR_MAX_FILES": "Šis projekts ietver vairāk nekā 30000 datņu. Funkcijas, kas darbojas vairākās datnēs, var tikt atspējotas vai darboties tā, it kā projekts būtu tukšs. <a href='https://github.com/adobe/brackets/wiki/Large-Projects'> Lasīt vairāk par strādāšanu ar lieliem projektiem</a>.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "Kļūda, palaižot pārlūku",
  "ERROR_CANT_FIND_CHROME": "Pārlūks Google Chrome netika atrasts. Pārliecinieties, ka tas ir instalēts.",
  "ERROR_LAUNCHING_BROWSER": "Radās kļūda, palaižot pārlūku. (kļūda {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "Tiešā priekšskatījuma kļūda",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "Savienojas ar pārlūku",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "Lai savienotos ar tiešo priekšskatījumu, nepieciešams pārlādēt Chrome ar iespējotu attālo atkļūdošanu.<br /><br />Vai vēlaties pārlādēt Chrome un iespējot attālo atkļūdošanu?<br /><br />",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "Neizdevās ielādēt tiešā priekšskatījuma lapu.",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "Lai palaistu tiešo priekšskatījumu ar serverī importētu datni, nepieciešams norādīt šī projekta bāzes URL.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "Kļūda, startējot HTTP serveri tiešā priekšskatījuma datnēm. Lūdzu, mēģiniet vēlreiz. ",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "Sīkākai informācijai skatiet <a href='{0}' title='{0}'>Tiešā priekšskatījuma savienojuma kļūdu novēršana</a>.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "Tiešais priekšskatījums",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "Tiešais priekšskatījums: savienojas…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "Tiešais priekšskatījums: inicializē…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "Tiešraides priekšskatījuma serveris ir aktīvs",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "Tiešais priekšskatījums",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "Atlasiet File To Live Preview",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "Pārlādēt lapu",
  "LIVE_DEV_TOGGLE_LIVE_HIGHLIGHT": "Pārslēgt tiešraides priekšskatījuma izcēlumus",
  "LIVE_DEV_CLICK_POPOUT": "Iznirst tiešraides priekšskatījums jaunā logā",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "Piespraudiet priekšskatījuma lapā Atspraust",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "Tiešais priekšskatījums (netiek atjaunināts sintakses kļūdas dēļ)",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "Tiešais priekšskatījums tika atcelts, jo bija atvērti pārlūka izstrādātāja rīki",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "Tiešais priekšskatījums tika atcelts, jo lapa tika aizvērta pārlūkā",
  "LIVE_DEV_NAVIGATED_AWAY": "Tiešais priekšskatījums tika atcelts, jo pārlūks pārvietojās uz lapu, kas nav daļa no šī projekta",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "Tiešais priekšskatījums tika atcelts nezināma iemesla dēļ ({0})",
  "SAVE_CLOSE_TITLE": "Saglabāt izmaiņas",
  "SAVE_CLOSE_MESSAGE": "Vai vēlaties saglabāt veiktās izmaiņas dokumentā <span class='dialog-filename'>{0}</span>?",
  "SAVE_CLOSE_MULTI_MESSAGE": "Vai vēlaties saglabāt izmaiņas šajās datnēs?",
  "EXT_MODIFIED_TITLE": "Ārējas izmaiņas",
  "CONFIRM_DELETE_TITLE": "Apstiprināt dzēšanu",
  "CONFIRM_FILE_DELETE": "Vai tiešām vēlaties dzēst failu <span class='dialog-filename'>{0}</span> ?",
  "CONFIRM_FOLDER_DELETE": "Vai tiešām vēlaties izdzēst mapi <span class='dialog-filename'>{0}</span>?",
  "FILE_DELETED_TITLE": "Datne izdzēsta",
  "EXT_MODIFIED_WARNING": "<span class='dialog-filename'>{0}</span> ir pārveidots diskā ārpus {APP_NAME}.<br /><br />Vai vēlaties saglabāt datni un pārrakstīt šīs izmaiņas?",
  "EXT_MODIFIED_MESSAGE": "<span class='dialog-filename'>{0}</span> ir pārveidots diskā ārpus {APP_NAME}, bet tam ir arī nesaglabātas izmaiņas {APP_NAME}.<br /><br />Kuru versiju vēlaties paturēt?",
  "EXT_DELETED_MESSAGE": "<span class='dialog-filename'>{0}</span> ir pārveidots diskā ārpus {APP_NAME}, bet tam ir nesaglabātas izmaiņas {APP_NAME}.<br /><br />Vai vēlaties paturēt izmaiņas?",
  "EXT_ALWAYS_MODIFIED_BUTTON_TOOLTIP": "Vienmēr pārrakstiet failus līdz projekta pārslēgšanai vai restartēšanai",
  "WINDOW_UNLOAD_WARNING": "Vai tiešām vēlaties pāriet uz citu URL un atstāt lietotni {APP_NAME}?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "Jums ir nesaglabātas izmaiņas! Vai tiešām vēlaties pāriet uz citu URL un atstāt lietotni {APP_NAME}?",
  "DONE": "Darīts",
  "OK": "Labi",
  "CANCEL": "Atcelt",
  "DONT_SAVE": "Nesaglabāt",
  "SAVE": "Saglabāt",
  "SAVE_AS": "Saglabāt kā…",
  "SAVE_AND_OVERWRITE": "Pārrakstīt",
  "ALWAYS_OVERWRITE": "Vienmēr pārrakstīt",
  "DELETE": "Dzēst",
  "BUTTON_YES": "Jā",
  "BUTTON_NO": "Nē",
  "FIND_MATCH_INDEX": "{0} no {1}",
  "FIND_NO_RESULTS": "Nav rezultātu",
  "FIND_QUERY_PLACEHOLDER": "Meklēt…",
  "FIND_HISTORY_MAX_COUNT": "Maksimālais meklēšanas vienumu skaits meklēšanas vēsturē",
  "REPLACE_PLACEHOLDER": "Aizstāt ar…",
  "BUTTON_REPLACE_ALL": "Grupēt…",
  "BUTTON_REPLACE_BATCH": "Partija…",
  "BUTTON_REPLACE_ALL_IN_FILES": "Aizstāt…",
  "BUTTON_REPLACE": "Aizstāt",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "Nākamā sakritība",
  "BUTTON_PREV_HINT": "Iepriekšējā sakritība",
  "BUTTON_CASESENSITIVE_HINT": "Jāsakrīt reģistriem",
  "BUTTON_REGEXP_HINT": "Regulārā izteiksme",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "Aizstāt bez atcelšanas",
  "REPLACE_WITHOUT_UNDO_WARNING": "Tā kā jāizmaina vairāk nekā {0} datnes, {APP_NAME} pārveidos neatvērtas datnes uz diska.<br />Jūs nevarēsiet atcelt šajās datnēs veiktos aizvietojumus.",
  "BUTTON_REPLACE_WITHOUT_UNDO": "Aizstāt bez atcelšanas",
  "OPEN_FILE": "Atvērt datni",
  "SAVE_FILE_AS": "Saglabāt datni",
  "CHOOSE_FOLDER": "Izvēlēties mapi",
  "RELEASE_NOTES": "Informācija par laidienu",
  "NO_UPDATE_TITLE": "Jums ir jaunākā versija!",
  "NO_UPDATE_MESSAGE": "Jums ir jaunākā {APP_NAME} versija.",
  "FIND_REPLACE_TITLE_LABEL": "Aizstāt",
  "FIND_REPLACE_TITLE_WITH": "ar",
  "FIND_TITLE_LABEL": "Atrasts",
  "FIND_TITLE_SUMMARY": "&mdash; {0} {1} {2} iekš {3}",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "iekš <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_NO_SCOPE": "projektā",
  "FIND_IN_FILES_ZERO_FILES": "Filtrs izslēdz visas datnes {0}",
  "FIND_IN_FILES_FILE": "datne",
  "FIND_IN_FILES_FILES": "datnes",
  "FIND_IN_FILES_MATCH": "sakritība",
  "FIND_IN_FILES_MATCHES": "sakritības",
  "FIND_IN_FILES_MORE_THAN": "Pāri ",
  "FIND_IN_FILES_PAGING": "{0}&mdash;{1}",
  "FIND_IN_FILES_FILE_PATH": "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "Spiediet Ctrl/Cmd, lai izvērstu/sakļautu visu",
  "FIND_IN_FILES_INDEXING": "Indeksēšana tūlītējai meklēšanai…",
  "FIND_IN_FILES_SEARCHING": "Notiek failu meklēšana…",
  "FIND_IN_FILES_SEARCHING_IN": "{0}",
  "FIND_IN_FILES_INDEXING_PROGRESS": "Indeksē {0} no {1} failiem tūlītējai meklēšanai…",
  "REPLACE_IN_FILES_ERRORS_TITLE": "Aizstāt kļūdas",
  "REPLACE_IN_FILES_ERRORS": "Šīs datnes netika pārveidotas, jo tās mainījās pēc meklēšanas vai nevar tikt rakstītas.",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "Kļūda, saņemot informāciju par atjauninājumiem",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "Neizdevās iegūt informāciju no servera par jaunākajiem atjauninājumiem. Pārliecinieties, vai esat pieslēdzies internetam, un mēģiniet vēlreiz.",
  "NEW_FILE_FILTER": "Jauna izslēgšanas kopa…",
  "CLEAR_FILE_FILTER": "Neizslēgt datnes",
  "NO_FILE_FILTER": "Netika izslēgtas datnes",
  "EXCLUDE_FILE_FILTER": "Izslēgt {0}",
  "INCLUDE_FILE_FILTER": "Iekļaut {0}",
  "EXCLUDE_FILE_FILTER_DROPDOWN": "Izslēgt",
  "INCLUDE_FILE_FILTER_DROPDOWN": "Iekļauts",
  "EDIT_FILE_FILTER": "Rediģēt…",
  "FILE_FILTER_DIALOG": "Rediģēt izslēgšanas filtru",
  "FILE_FILTER_INSTRUCTIONS": "Izslēdziet failus un mapes, kas atbilst jebkurai no šīm <a href='{0}' title=\"{0}\">ignorēšanas aizstājējzīmēm</a> . Ievadiet katru virkni jaunā rindā. Piem<ul><li> <code>*.js</code> atbilst <code>a/b/x.js</code> , <code>xyx.js</code> utt.</li><li> <code>./*.css</code> atbildīs tikai <code>x.css</code> projekta saknē, bet ne <code>y/x.css</code> apakšmapē.</li></ul>",
  "FILE_FILTER_INSTRUCTIONS_INCLUDE": "Iekļaujiet tikai tos failus un mapes, kas atbilst jebkurai no šīm <a href='{0}' title=\"{0}\">ignorēšanas aizstājējzīmēm</a> . Ievadiet katru virkni jaunā rindā. Piem<ul><li> <code>*.js</code> atbilst <code>a/b/x.js</code> , <code>xyx.js</code> utt.</li><li> <code>./*.css</code> atbildīs tikai <code>x.css</code> projekta saknē, bet ne <code>y/x.css</code> apakšmapē.</li></ul>",
  "FILTER_NAME_PLACEHOLDER": "Nosaukt šo izslēgšanas kopu (nav obligāti)",
  "FILTER_NAME_REMAINING": "Atlikušas {0} rakstzīmes",
  "FILE_FILTER_CLIPPED_SUFFIX": "un {0} vairāk",
  "FILTER_COUNTING_FILES": "Skaita datnes…",
  "FILTER_FILE_COUNT": "Pieļauj {0} no {1} datnēm {2} ",
  "FILTER_FILE_COUNT_ALL": "Pieļauj visas {0} datnes {1}",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "Pašreizējai kursora pozīcijai nav pieejama ātrā rediģēšana",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "CSS ātrā rediģēšana: novietojiet kursoru uz vienas klases nosaukuma",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "CSS ātrā rediģēšana: nepilnīgs klases atribūts",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "CSS ātrā rediģēšana: nepilnīgs id atribūts",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "CSS ātrā rediģēšana: novietojiet kursuru tagā, klasē vai id",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "CSS laika funkcijas ātrā rediģēšana: nederīga sintakse",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "JS ātrā rediģēšana: novietojiet kursoru funkcijas nosaukumā",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "Pašreizējai kursora pozīcijai nav pieejams neviens ātrais dokuments",
  "PROJECT_LOADING": "Ielādē…",
  "UNTITLED": "Nenosaukts",
  "WORKING_FILES": "Darba datnes",
  "TOP": "Augša",
  "BOTTOM": "Apakša",
  "LEFT": "Pa kreisi",
  "RIGHT": "Pa labi",
  "CMD_SPLITVIEW_NONE": "Netiek sadalīts",
  "CMD_SPLITVIEW_VERTICAL": "Vertikālā sadalīšana",
  "CMD_SPLITVIEW_HORIZONTAL": "Horizontālā sadalīšana",
  "SPLITVIEW_MENU_TOOLTIP": "Sadalīt redaktoru vertikāli vai horizontāli",
  "GEAR_MENU_TOOLTIP": "Konfigurēt darba kopu",
  "SPLITVIEW_INFO_TITLE": "Jau atvērts",
  "SPLITVIEW_MULTIPANE_WARNING": "Datne jau ir atvērta citā rūtī. {APP_NAME} drīz atbalstīs datnes atvēršanu vairāk nekā vienā rūtī. Līdz tam datne tiks rādīta rūtī, kurā tā jau ir atvērta.<br /<br />(Šis paziņojums paradīsies tikai vienreiz.)",
  "KEYBOARD_OVERLAY_TEXT": "Izmantojiet bultiņas, lai pārvietotos, vai rakstiet, lai atlasītu lietotāja saskarnes elementus.",
  "KEYBOARD_SHORTCUT_CHANGE_TITLE": "Mainīt īsinājumtaustiņu…",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_TITLE": "Mainiet īsinājumtaustiņus",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_TEXT": "Nospiediet jauno taustiņu kombināciju <b>&#39;{0}&#39;</b> (pašreizējais: <b>{1}</b> )",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_DUPLICATE": "Brīdinājums: taustiņu kombinācija <b>{0}</b> jau ir piešķirta <b>&#39;{1}&#39;</b> . Vai atkārtoti piešķirt <b>&#39;{2}&#39;</b> ?",
  "KEYBOARD_SHORTCUT_ASSIGN": "Piešķirt",
  "KEYBOARD_SHORTCUT_NONE": "Nav",
  "KEYBOARD_SHORTCUT_MENU_SHOW_SHORTCUTS": "Tastatūras īsinājumtaustiņi…",
  "KEYBOARD_SHORTCUT_MENU_SHOW_SHORTCUTS_BUTTON": "Rādīt visus saīsnes…",
  "KEYBOARD_SHORTCUT_TABLE_BASE_KEY": "Pamata atslēga",
  "KEYBOARD_SHORTCUT_TABLE_KEY_BINDING": "Īsceļš",
  "KEYBOARD_SHORTCUT_TABLE_COMMAND_ID": "Komandas ID",
  "KEYBOARD_SHORTCUT_TABLE_COMMAND_NAME": "Pavēli",
  "KEYBOARD_SHORTCUT_TABLE_DOUBLE_CLICK": "Veiciet dubultklikšķi, lai mainītu saīsni",
  "KEYBOARD_SHORTCUT_TABLE_ORIGIN": "Izcelsme",
  "KEYBOARD_SHORTCUT_ORIG_EXTENSION": "Pagarinājums",
  "KEYBOARD_SHORTCUT_PANEL_TITLE": "Tastatūras īsinājumtaustiņi",
  "KEYBOARD_SHORTCUT_PANEL_FILTER": "Filtrs&hellip;",
  "KEYBOARD_SHORTCUT_PANEL_RESET": "Atiestatīt…",
  "KEYBOARD_SHORTCUT_PANEL_RESET_DEFAULT": "Atiestatīt uz noklusējuma saīsnes…",
  "KEYBOARD_SHORTCUT_RESET_DIALOG_TITLE": "Atiestatīt īsinājumtaustiņus",
  "KEYBOARD_SHORTCUT_RESET_DIALOG_MESSAGE": "Vai atiestatīt visus pielāgotos saīsnes uz noklusējuma iestatījumiem? To nevar atsaukt.",
  "STATUSBAR_CURSOR_POSITION": "Rinda {0} kolonna {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": " — izvēlēta {0} kolonna",
  "STATUSBAR_SELECTION_CH_PLURAL": " — izvēlētas {0} kolonnas",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " — izvēlēta {0} rinda",
  "STATUSBAR_SELECTION_LINE_PLURAL": " — izvēlētas {0} rindas",
  "STATUSBAR_SELECTION_MULTIPLE": " — {0} izvēles",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "Nospiediet, lai pārslēgtu atkāpes uz atstarpēm",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "Nospiediet, lai pārslēgtu atkāpes uz tabulāciju",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "Nospiediet, lai mainītu atstarpju skaitu, izmantojot atkāpes",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "Nospiediet, lai mainītu tabulācijas simbolu platumu",
  "STATUSBAR_SPACES": "Atstarpes:",
  "STATUSBAR_TAB_SIZE": "Tabulācijas izmērs:",
  "STATUSBAR_LINE_COUNT_SINGULAR": "— {0} rinda",
  "STATUSBAR_LINE_COUNT_PLURAL": "— {0} rindas",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "Paplašinājumi atspējoti",
  "STATUSBAR_INSERT": "Iespraušana (INS)",
  "STATUSBAR_OVERWRITE": "Pārraksts (OVR)",
  "STATUSBAR_INSOVR_TOOLTIP": "Nospiediet, lai pārslēgtu kursoru starp iespraušanas (INS) un pārraksta (OVR) režīmu",
  "STATUSBAR_LANG_TOOLTIP": "Nospiediet, lai mainītu datnes tipu",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. Nospiediet, lai rādītu/slēptu atskaites paneli.",
  "STATUSBAR_DEFAULT_LANG": "(noklusējums)",
  "STATUSBAR_SET_DEFAULT_LANG": "Iestatīt kā noklusējumu .{0} datnēm",
  "STATUSBAR_ENCODING_TOOLTIP": "Izvēlieties kodējumu",
  "STATUSBAR_TASKS": "Uzdevumi",
  "STATUSBAR_TASKS_TOOLTIP": "Pārvaldiet aktīvos uzdevumus",
  "STATUSBAR_TASKS_HIDE_SPINNER": "Paslēpt vērpēja ikonu",
  "STATUSBAR_TASKS_UNKNOWN_EXTENSION_TASK": "Nezināms paplašinājuma uzdevums…",
  "STATUSBAR_TASKS_PLAY": "Sākt vai atsākt",
  "STATUSBAR_TASKS_PAUSE": "Pauze",
  "STATUSBAR_TASKS_STOP": "Stop",
  "STATUSBAR_TASKS_RESTART": "Restartēt",
  "ERRORS_PANEL_TITLE_MULTIPLE": "{0} problēmas",
  "SINGLE_ERROR": "1 {0} problēma",
  "MULTIPLE_ERRORS": "{1} {0} problēmas",
  "NO_ERRORS": "Netika atrasta neviena {0} problēma - labi pastrādāts!",
  "NO_ERRORS_MULTIPLE_PROVIDER": "Netika atrasta neviena problēma - labi pastrādāts!",
  "LINT_DISABLED": "Sintakses pārbaudīšana ir atspējota",
  "NO_LINT_AVAILABLE": "Nav pieejama sintakses pārbaudīšana priekš {0}",
  "NOTHING_TO_LINT": "Nav ko pārbaudīt",
  "LINTER_TIMED_OUT": "{0} iestājās taimauts pēc {1} ms ilgas gaidīšanas",
  "LINTER_FAILED": "{0} beidzās ar kļūdu: {1}",
  "FILE_MENU": "Datne",
  "CMD_FILE_NEW_UNTITLED": "Jauna",
  "CMD_FILE_NEW": "Jauna datne",
  "CMD_FILE_DUPLICATE": "Dublēt",
  "CMD_FILE_DUPLICATE_FILE": "Dublēt failu",
  "CMD_FILE_DOWNLOAD_PROJECT": "Lejupielādēt projektu",
  "CMD_FILE_DOWNLOAD": "Lejupielādēt",
  "CMD_FILE_CUT": "Izgriezt",
  "CMD_FILE_COPY": "Kopēt",
  "CMD_FILE_COPY_PATH": "Kopēt ceļu",
  "CMD_FILE_PASTE": "Ielīmēt",
  "CMD_PROJECT_NEW": "Jauns projekts…",
  "CMD_FILE_NEW_FOLDER": "Jauna mape",
  "CMD_FILE_OPEN": "Atvērt failus…",
  "CMD_RECENT_FILES_OPEN": "Jaunākie faili…",
  "CMD_ADD_TO_WORKING_SET": "Atvērt darba kopā",
  "CMD_OPEN_DROPPED_FILES": "Atvērt nomestās datnes",
  "CMD_OPEN_FOLDER": "Atvērt mapi…",
  "CMD_FILE_CLOSE": "Aizvērt",
  "CMD_FILE_CLOSE_ALL": "Aizvērt visas",
  "CMD_FILE_CLOSE_LIST": "Aizvērt sarakstu",
  "CMD_FILE_CLOSE_OTHERS": "Aizvērt citas",
  "CMD_FILE_CLOSE_ABOVE": "Aizvērt visas augstāk",
  "CMD_FILE_CLOSE_BELOW": "Aizvērt visas zemāk",
  "CMD_FILE_SAVE": "Saglabāt datni",
  "CMD_FILE_SAVE_ALL": "Saglabāt visas",
  "CMD_FILE_SAVE_AS": "Saglabāt kā…",
  "CMD_LIVE_FILE_PREVIEW": "Tiešais priekšskatījums",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "Iespējot eksperimentālo tiešo priekšskatījumu",
  "CMD_RELOAD_LIVE_PREVIEW": "Piespiedu tiešā priekšskatījuma pārlādēšana",
  "CMD_PROJECT_SETTINGS": "Projekta iestatījumi…",
  "CMD_FILE_RENAME": "Pārdēvēt",
  "CMD_FILE_DELETE": "Dzēst",
  "CMD_INSTALL_EXTENSION": "Instalēt paplašinājumu…",
  "CMD_EXTENSION_MANAGER": "Paplašinājumu pārvaldnieks…",
  "CMD_FILE_REFRESH": "Atsvaidzināt datņu koku",
  "CMD_FILE_SHOW_FOLDERS_FIRST": "Vispirms kārtojiet mapes",
  "CMD_QUIT": "Beigt",
  "CMD_EXIT": "Iziet",
  "EDIT_MENU": "Rediģēt",
  "CMD_UNDO": "Atsaukt",
  "CMD_REDO": "Atcelt atsaukšanu",
  "CMD_CUT": "Izgriezt",
  "CMD_COPY": "Kopēt",
  "CMD_PASTE": "Ielīmēt",
  "CMD_SELECT_ALL": "Izvēlēties visu",
  "CMD_SELECT_LINE": "Izvēlēties rindu",
  "CMD_SPLIT_SEL_INTO_LINES": "Sadalīt izvēlēto rindās",
  "CMD_ADD_CUR_TO_NEXT_LINE": "Pievienot kursoru nākamajai rindai",
  "CMD_ADD_CUR_TO_PREV_LINE": "Pievienot kursoru iepriekšējai rindai",
  "CMD_INDENT": "Atkāpe",
  "CMD_UNINDENT": "Nav atkāpes",
  "CMD_DUPLICATE": "Dublēt",
  "CMD_DELETE_LINES": "Dzēst rindu",
  "CMD_COMMENT": "Rādīt/slēpt rindas komentāru",
  "CMD_BLOCK_COMMENT": "Rādīt/slēpt bloka komentāru",
  "CMD_LINE_UP": "Pārvietot rindu uz augšu",
  "CMD_LINE_DOWN": "Pārvietot rindu uz leju",
  "CMD_OPEN_LINE_ABOVE": "Atvērt augšējo rindu",
  "CMD_OPEN_LINE_BELOW": "Atvērt apakšējo rindu",
  "CMD_TOGGLE_CLOSE_BRACKETS": "Automātiski aizvērt figūriekavas",
  "CMD_SHOW_CODE_HINTS": "Rādīt koda ieteikumus",
  "CMD_BEAUTIFY_CODE": "Izdaiļot kodu",
  "CMD_BEAUTIFY_CODE_ON_SAVE": "Izdaiļojiet kodu pēc saglabāšanas",
  "FIND_MENU": "Meklēt",
  "CMD_FIND": "Meklēt",
  "CMD_FIND_NEXT": "Meklēt nākamo",
  "CMD_FIND_PREVIOUS": "Meklēt iepriekšējo",
  "CMD_FIND_ALL_AND_SELECT": "Atlasiet Visi gadījumi",
  "CMD_ADD_NEXT_MATCH": "Pievienot nākamo notikumu",
  "CMD_SKIP_CURRENT_MATCH": "Izlaist un pievienot nākamo notikumu",
  "CMD_FIND_IN_FILES": "Meklēt datnēs",
  "CMD_FIND_IN_SUBTREE": "Meklēt… ",
  "CMD_REPLACE": "Aizstāt",
  "CMD_REPLACE_IN_FILES": "Aizstāt datnēs",
  "CMD_REPLACE_IN_SUBTREE": "Aizstāt…",
  "VIEW_MENU": "Skats",
  "CMD_HIDE_SIDEBAR": "Slēpt sānjoslu",
  "CMD_SHOW_SIDEBAR": "Rādīt sānjoslu",
  "CMD_TOGGLE_SIDEBAR": "Rādīt/slēpt sānjoslu",
  "CMD_TOGGLE_PANELS": "Rādīt/slēpt paneļus",
  "CMD_TOGGLE_PURE_CODE": "Rādīt/slēpt palīgjoslas",
  "CMD_TOGGLE_FULLSCREEN": "Pilnekrāna režīms",
  "CMD_ZOOM_UI": "Tālummaiņas lietotāja saskarne un fonti",
  "CMD_ZOOM_IN": "Pietuvināt",
  "CMD_ZOOM_IN_SCALE": "Tuvināt (pašreizējais: {0}%)",
  "CMD_ZOOM_OUT": "Attālināt",
  "CMD_INCREASE_FONT_SIZE": "Palielināt fonta lielumu",
  "CMD_DECREASE_FONT_SIZE": "Samazināt fonta lielumu",
  "CMD_RESTORE_FONT_SIZE": "Atjaunot fonta lielumu",
  "CMD_SCROLL_LINE_UP": "Ritināt rindu augstāk",
  "CMD_SCROLL_LINE_DOWN": "Ritināt rindu zemāk",
  "CMD_TOGGLE_LINE_NUMBERS": "Rindu numuri",
  "CMD_TOGGLE_ACTIVE_LINE": "Izcelt aktīvo rindu",
  "CMD_TOGGLE_WORD_WRAP": "Aplaušana",
  "CMD_LIVE_HIGHLIGHT": "Tiešā priekšskatījuma izcelšana",
  "CMD_VIEW_TOGGLE_INSPECTION": "Pārbaudīt sintaksi datnēs, tās saglabājot",
  "CMD_WORKINGSET_SORT_BY_ADDED": "Kārtot pēc pievienošanas datuma",
  "CMD_WORKINGSET_SORT_BY_NAME": "Kārtot pēc nosaukuma",
  "CMD_WORKINGSET_SORT_BY_TYPE": "Kārtot pēc tipa",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "Automātiskā kārtošana",
  "CMD_THEMES": "Dizains…",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "Automātiski aizvērt meklēšanu",
  "CMD_KEYBOARD_NAV_OVERLAY": "UI navigācijas režīms",
  "NAVIGATE_MENU": "Pārvietoties",
  "CMD_QUICK_OPEN": "Ātrā atvēršana",
  "CMD_GOTO_LINE": "Iet uz rindu",
  "CMD_GOTO_DEFINITION": "Ātrā definīcijas meklēšana",
  "CMD_GOTO_DEFINITION_PROJECT": "Ātrās meklēšanas definīcija projektā",
  "CMD_GOTO_FIRST_PROBLEM": "Iet uz pirmo problēmu",
  "CMD_TOGGLE_QUICK_EDIT": "Ātrā rediģēšana",
  "CMD_TOGGLE_QUICK_DOCS": "Ātrie dokumenti",
  "CMD_QUICK_EDIT_PREV_MATCH": "Iepriekšējā sakritība",
  "CMD_QUICK_EDIT_NEXT_MATCH": "Nākamā sakritība",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "Jauna kārtula",
  "CMD_NEXT_DOC": "Nākamais dokuments",
  "CMD_PREV_DOC": "Iepriekšējais dokuments",
  "CMD_NAVIGATE_BACKWARD": "Pārvietojieties atpakaļ",
  "CMD_NAVIGATE_FORWARD": "Pārvietojieties uz priekšu",
  "CMD_NEXT_DOC_LIST_ORDER": "Nākamais dokuments sarakstā",
  "CMD_PREV_DOC_LIST_ORDER": "Iepriekšējais dokuments sarakstā",
  "CMD_SHOW_IN_TREE": "Parādīt datņu kokā",
  "CMD_SHOW_IN_EXPLORER": "Parādīt pārlūkā",
  "CMD_SHOW_IN_FINDER": "Parādīt meklētājā",
  "CMD_SHOW_IN_OS": "Rādīt OS failos",
  "CMD_SWITCH_PANE_FOCUS": "Pārslēgt rūts fokusu",
  "CMD_OPEN_VFS": "Atveriet virtuālo failu sistēmu",
  "CMD_DIAGNOSTIC_TOOLS": "{APP_NAME} diagnostikas rīki",
  "CMD_OPEN_EXTENSIONS_FOLDER": "Atvērt paplašinājumu mapi…",
  "CMD_OPEN_VIRTUAL_SERVER": "Atveriet virtuālo serveri",
  "HELP_MENU": "Palīdzība",
  "CMD_CHECK_FOR_UPDATE": "Pārbaudīt atjauninājumus",
  "CMD_HOW_TO_USE_BRACKETS": "Kā lietot {APP_NAME}",
  "CMD_SUPPORT": "{APP_NAME} palīdzība",
  "CMD_SUGGEST": "Ieteikt funkciju",
  "CMD_RELEASE_NOTES": "Informācija par laidienu",
  "CMD_GET_INVOLVED": "Iesaistīties",
  "CMD_SHOW_EXTENSIONS_FOLDER": "Parādīt paplašinājumu mapi",
  "CMD_HEALTH_DATA_STATISTICS": "Pārskats par veselību…",
  "CMD_HOMEPAGE": "Mājas lapa — Lejupielādēt lietotnes",
  "CMD_TWITTER": "{TWITTER_NAME} tīmekļa vietnē \"Twitter\"",
  "CMD_ABOUT": "Par {APP_TITLE}",
  "CMD_OPEN_PREFERENCES": "Atvērt iestatījumu datni",
  "CMD_OPEN_KEYMAP": "Atveriet lietotāja atslēgas kartes failu",
  "EXPERIMENTAL_BUILD": "eksperimentāls būvējums",
  "RELEASE_BUILD": "būvējums",
  "DEVELOPMENT_BUILD": "izstrādes būvējums",
  "PRERELEASE_BUILD": "pirmsizlaides būvējums",
  "RELOAD_FROM_DISK": "Pārlādēt no diska",
  "KEEP_CHANGES_IN_EDITOR": "Saglabāt izmaiņas redaktorā",
  "CLOSE_DONT_SAVE": "Aizvērt (nesaglabāt)",
  "RELAUNCH_CHROME": "Restartēt Chrome",
  "ABOUT": "Par",
  "CLOSE": "Aizvērt",
  "ABOUT_TEXT_LINE1": "Izlaidums {VERSION_MAJOR}.{VERSION_MINOR} {BUILD_TYPE} {VERSION}",
  "ABOUT_TEXT_BUILD_TIMESTAMP": "izveides laika zīmogs:",
  "ABOUT_TEXT_LINE3": "Mūsu izmantotās trešo pušu bibliotēkas — <a href='https://github.com/phcode-dev/phoenix/tree/main/src/thirdparty/licences'>licences un attiecinājumi</a> .",
  "ABOUT_TEXT_LINE4": "Dokumentācija un avots: <a href='https://github.com/phcode-dev/phoenix/'>https://github.com/phcode-dev/phoenix/</a>",
  "ABOUT_TEXT_LINE5": "Izgatavoja, izmantojot ❤ un JavaScript, autors:",
  "ABOUT_TEXT_LINE6": "Daudz cilvēku (taču mums pašlaik ir problēmas ar šo datu ielādi).",
  "ABOUT_TEXT_MDN_DOCS": "MDN dokumenti un MDN grafiskais logo ir licencēti saskaņā ar \"Creative Commons\" licenci <a href='{MDN_DOCS_LICENSE}'>CC-BY-SA 2.5 Unported</a>.",
  "UPDATE_NOTIFICATION_TOOLTIP": "{APP_NAME} ir pieejams jauns būvējums! Spiediet šeit, lai saņemtu sīkāku informāciju.",
  "UPDATE_NOT_AVAILABLE_TITLE": "Lietotne {APP_NAME} ir atjaunināta",
  "UPDATE_UP_TO_DATE": "Jūsu lietotnes {APP_NAME} versija ir jaunākā un labākā!",
  "UPDATE_AVAILABLE_TITLE": "Pieejams atjauninājums",
  "UPDATE_READY_RESTART_TITLE": "Atjauninājums gatavs: nepieciešama restartēšana",
  "UPDATE_READY_RESTART_MESSAGE": "Aizveriet visus lietotnes {APP_NAME} logus un restartējiet lietotni, lai palaistu atjaunināto versiju.",
  "UPDATE_READY_RESTART_INSTALL_MESSAGE": "Atjauninājums ir veiksmīgi lejupielādēts: lūdzu, aizveriet visus lietotnes {APP_NAME} logus, lai lietotu jaunākos atjauninājumus.",
  "UPDATE_FAILED_TITLE": "Atjaunināšana neizdevās",
  "UPDATE_INSTALLING": "Notiek atjauninājuma instalēšana…",
  "UPDATE_INSTALLING_MESSAGE": "Notiek atjaunināšanas instalēšana: {APP_NAME} pašlaik instalē jaunākos atjauninājumus. Lietojumprogramma tiks automātiski aizvērta, kad instalēšana būs pabeigta.",
  "UPDATE_FAILED_MESSAGE": "Lūdzu, aizveriet visus {APP_NAME} lietotņu logus un atkārtoti atveriet lietojumprogrammu, lai mēģinātu atjaunināt vēlreiz.",
  "UPDATE_FAILED_VISIT_SITE_MESSAGE": "Lai mēģinātu vēlreiz, lūdzu, izejiet no visām lietotnes {APP_NAME} gadījumiem un restartējiet lietojumprogrammu.<br> Drīzumā tiksiet novirzīts uz mūsu lejupielādes lapu, kur varēsit manuāli lejupielādēt jaunāko versiju.",
  "UPDATE_MESSAGE": "{APP_NAME} ir pieejams jauns būvējums. Dažas no jaunajām funkcijām:",
  "GET_IT_NOW": "Iegūt to tagad!",
  "UPDATE_LATER": "Atgādini man vēlāk",
  "UPDATE_DONE": "Restartējiet, lai atjauninātu lietotni {APP_NAME}",
  "UPDATE_RESTART": "Restartējiet, lai lietotu atjauninājumus",
  "UPDATE_RESTART_INSTALL": "Restartējiet, lai instalētu atjauninājumus",
  "UPDATE_DOWNLOADING": "Notiek instalēšanas programmas lejupielāde",
  "INSTALL_WEBAPP": "Instalējiet {APP_NAME} savā ierīcē",
  "UPDATE_DOWNLOAD_PROGRESS": "Notiek lejupielāde — {0} no {1} MB",
  "UPDATING_APP": "Notiek lietotnes {APP_NAME} atjaunināšana",
  "UPDATING_APP_MESSAGE": "Tas var aizņemt kādu laiku",
  "UPDATING_APP_DIALOG_MESSAGE": "Notiek atjaunināšana. Kamēr mēs jauninām, varat turpināt lietot lietotni {APP_NAME}.",
  "PROJECT_SETTINGS_TITLE": "Projekta iestatījumi priekš: {0}",
  "PROJECT_SETTING_BASE_URL": "Tiešā priekšskatījuma bāzes URL",
  "PROJECT_SETTING_BASE_URL_HINT": "Lai izmantotu lokālo serveri, ievadiet URL, kā, piemēram, http://localhost:8000/",
  "BASEURL_ERROR_INVALID_PROTOCOL": "Tiešais priekšskatījums neatbalsta protokolu {0} &mdash;lūdzu, izmantojiet http: vai https: .",
  "BASEURL_ERROR_SEARCH_DISALLOWED": "Bāzes URL nevar ietvert tādus meklēšanas parametrus kā \"{0}\".",
  "BASEURL_ERROR_HASH_DISALLOWED": "Bāzes URL nevar ietver jaucējkodu kā \"{0}\".",
  "BASEURL_ERROR_INVALID_CHAR": "Speciālajiem simboliem kā '{0}' jābūt %-kodētiem.",
  "BASEURL_ERROR_UNKNOWN_ERROR": "Nezināma kļūda, parsējot bāzes URL",
  "EMPTY_VIEW_HEADER": "<em>Atvērt datni, kamēr fokuss ir uz šo rūti</em>",
  "FLIPVIEW_BTN_TOOLTIP": "Pārnest šo skatu uz rūti {0}",
  "CURRENT_THEME": "Pašreizējais dizains",
  "USE_THEME_SCROLLBARS": "Lietot dizaina ritjoslas",
  "FONT_SIZE": "Fonta lielums",
  "FONT_FAMILY": "Fontu saime",
  "THEMES_SETTINGS": "Dizaina iestatījumi",
  "THEMES_ERROR": "Motīvu kļūda",
  "THEMES_ERROR_CANNOT_APPLY": "Motīvu nevarēja lietot kļūdas dēļ.",
  "BUTTON_NEW_RULE": "Jauna kārtula",
  "INSTALL": "Instalēt",
  "APPLY": "Pieteikties",
  "UPDATE": "Atjaunināt",
  "REMOVE": "Noņemt",
  "DISABLE": "Atspējot",
  "ENABLE": "Iespējot",
  "OVERWRITE": "Pārrakstīt",
  "CANT_DROP_ZIP": "Drīzumā tiks atbalstīta ZIP failu nomešana...",
  "CANT_REMOVE_DEV": "Paplašinājumi mapē \"dev\" ir jādzēš manuāli.",
  "CANT_UPDATE": "Atjauninājums nesader ar šo {APP_NAME} versiju.",
  "CANT_UPDATE_DEV": "Paplašinājumi mapē \"dev\" nevar tikt atjaunoti automātiski.",
  "INSTALL_EXTENSION_TITLE": "Instalēt paplašinājumu",
  "UPDATE_EXTENSION_TITLE": "Atjaunināt paplašinājumu",
  "INSTALL_EXTENSION_LABEL": "Paplašinājuma URL",
  "INSTALL_EXTENSION_HINT": "Paplašinājuma zip datnes URL vai GitHub repozitorijs",
  "INSTALLING_FROM": "Instalē paplašinājumu no {0}…",
  "INSTALL_SUCCEEDED": "Instalēšana veiksmīga!",
  "INSTALL_FAILED": "Instalēšana neveiksmīga.",
  "CANCELING_INSTALL": "Atceļ …",
  "CANCELING_HUNG": "Instalēšanas atcelšana aizņem daudz laika. Var būt radusies iekšēja kļūda.",
  "INSTALL_CANCELED": "Instalēšana atcelta.",
  "VIEW_COMPLETE_DESCRIPTION": "Skatīt pilnīgu aprakstu",
  "VIEW_TRUNCATED_DESCRIPTION": "Skatīt saīsinātu aprakstu",
  "SORT_EXTENSION_METHOD": "Kārtojiet paplašinājumus, izmantojot vienumu downloadCount vai PublicētsDate",
  "INVALID_ZIP_FILE": "Lejupielādētais saturs nav derīga zip datne.",
  "MISSING_PACKAGE_JSON": "Pakotnei nav faila package.json.",
  "INVALID_PACKAGE_JSON": "Datne package.json nav derīga (kļūda: {0}).",
  "MISSING_PACKAGE_NAME": "Datnē package.json nav norādīts pakotnes nosaukums.",
  "BAD_PACKAGE_NAME": "{0} ir nederīgs pakotnes nosaukums.",
  "MISSING_PACKAGE_VERSION": "Datnē package.json nav norādīta pakotnes versija.",
  "INVALID_VERSION_NUMBER": "Pakotnes versijas numurs ({0}) ir nederīgs.",
  "INVALID_BRACKETS_VERSION": "{APP_NAME} saderības virkne ({0}) ir nederīga.",
  "DISALLOWED_WORDS": "Laukā {0} nav atļauti vārdi ({1}).",
  "NPM_INSTALL_FAILED": "npm instalēšanas komanda neizdevās: {0}",
  "API_NOT_COMPATIBLE": "Paplašinājums nav saderīgs ar šo {APP_NAME} versiju. Tas ir instalēts atspējoto paplašinājumu mapē.",
  "MISSING_MAIN": "Pakotnē nav datnes main.js.",
  "EXTENSION_ALREADY_INSTALLED": "Šīs pakotnes instalēšana pārrakstīs iepriekš instalētu paplašinājumu. Pārrakstīt veco paplašinājumu?",
  "EXTENSION_SAME_VERSION": "Šai pakotnei ir tāda pati versija kā jau pašreiz instalētajai. Pārrakstīt esošo instalāciju?",
  "EXTENSION_OLDER_VERSION": "Pakotnes versija ir {0}, kas ir vecāka par pašreiz instalēto ({1}). Pārrakstīt esošo instalāciju?",
  "DOWNLOAD_ID_IN_USE": "Iekšēja kļūda: lejupielādes ID jau tiek lietots.",
  "NO_SERVER_RESPONSE": "Nevar savienoties ar serveri.",
  "BAD_HTTP_STATUS": "Datne netika atrasta serverī (HTTP {0}).",
  "CANNOT_WRITE_TEMP": "Neizdevās saglabāt lejupielādi pagaidu datnē.",
  "ERROR_LOADING": "Uzsākot darbību, paplašinājums sadūrās ar kļūdu.",
  "MALFORMED_URL": "URL nav derīgs. Pārliecinieties, vai ievadījāt to pareizi.",
  "UNSUPPORTED_PROTOCOL": "URL jābūt http vai https formātā.",
  "UNKNOWN_ERROR": "Nezināma iekšējā kļūda.",
  "EXTENSION_VERIFIED_PUBLISHER": "Šis izdevējs ir apstiprinājis {0} īpašumtiesības",
  "EXTENSION_VERIFIED_SORT": "Pārbaudīts",
  "EXTENSION_STAR": "Zvaigzne",
  "EXTENSION_STAR_SORT": "Zvaigžņu vērtējums",
  "EXTENSION_MANAGER_TITLE": "Paplašinājumu pārvaldnieks",
  "EXTENSION_MANAGER_ERROR_LOAD": "Neizdevās piekļūt paplašinājumu reģistram. Lūdzu, mēģiniet vēlreiz.",
  "EXTENSION_UPDATE_RESTART_TITLE": "Restartēt, lai atjauninātu",
  "EXTENSION_UPDATE_RESTART_MESSAGE": "Lai ielādētu atjauninātus paplašinājumus, lūdzu, aizveriet visas lietojumprogrammas {APP_NAME} darbības un restartējiet lietojumprogrammu.",
  "INSTALL_EXTENSION_DRAG": "Ievelciet šeit .zip vai",
  "INSTALL_EXTENSION_DROP": "Nometiet .zip, lai instalētu",
  "INSTALL_EXTENSION_DROP_ERROR": "Instalēšana/atjaunināšana pārtraukta šādu kļūdu dēļ:",
  "INSTALL_FROM_URL": "Instalēt no URL…",
  "INSTALL_EXTENSION_VALIDATING": "Validē…",
  "EXTENSION_AUTHOR": "Autors",
  "EXTENSION_DATE": "Datums",
  "EXTENSION_INCOMPATIBLE_NEWER": "Šim paplašinājumam nepieciešama jaunāka {APP_NAME} versija.",
  "EXTENSION_INCOMPATIBLE_OLDER": "Pašlaik šis paplašinājums darbojas tikai ar vecākām {APP_NAME} versijām.",
  "EXTENSION_DEFAULT_FEATURE_PRESENT": "Jums var nebūt nepieciešams šis paplašinājums. Lietotnei APP_NAME} jau ir šī funkcija.",
  "EXTENSION_LATEST_INCOMPATIBLE_NEWER": "Šai paplašinājuma versijai {0} nepieciešama jaunāka {APP_NAME} versija. Bet jūs varat instalēt agrāko versiju {1}. ",
  "EXTENSION_LATEST_INCOMPATIBLE_OLDER": "Šī paplašinājuma versija {0} darbojas tikai ar vecākām {APP_NAME} versijām. Bet jūs varat instalēt agrāko versiju {1}.",
  "EXTENSION_NO_DESCRIPTION": "Nav apraksta",
  "EXTENSION_MORE_INFO": "Vairāk informācijas…",
  "EXTENSION_ERROR": "Paplašinājuma kļūda",
  "EXTENSION_KEYWORDS": "Atslēgas vārdi",
  "EXTENSION_TRANSLATED_USER_LANG": "Tulkots {0} valodās, ieskaitot Jūsu",
  "EXTENSION_TRANSLATED_GENERAL": "Tulkots {0} valodās",
  "EXTENSION_TRANSLATED_LANGS": "Paplašinājums tulkots šādās valodās: {0}",
  "EXTENSION_INSTALLED": "Instalētie",
  "EXTENSION_UPDATE_INSTALLED": "Paplašinājuma atjauninājums tika lejupielādēts, un tas tiks instalēts pēc {APP_NAME} pārlādēšanas.",
  "EXTENSION_SEARCH_PLACEHOLDER": "Meklēt",
  "EXTENSION_MORE_INFO_LINK": "Vairāk",
  "EXTENSION_MANAGER_CREATE_EXTENSION": "+ Izveidot paplašinājumu",
  "EXTENSION_MANAGER_CREATE_THEME": "+ Izveidojiet motīvu",
  "BROWSE_EXTENSIONS": "Pārlūkot paplašinājumus",
  "EXTENSION_MANAGER_REMOVE": "Noņemt paplašinājumu",
  "EXTENSION_MANAGER_REMOVE_ERROR": "Neizdevās noņemt vienu vai vairākus paplašinājumus: {0}. {APP_NAME} tik un tā pārlādēsies.",
  "EXTENSION_MANAGER_UPDATE": "Atjaunināt paplašinājumu",
  "EXTENSION_MANAGER_UPDATE_ERROR": "Neizdevās atjaunināt vienu vai vairākus paplašinājumus: {0}. {APP_NAME} tik un tā pārlādēsies.",
  "EXTENSION_MANAGER_DISABLE": "Atspējot paplašinājumu",
  "EXTENSION_MANAGER_DISABLE_ERROR": "Neizdevās atspējot vienu vai vairākus paplašinājumus: {0}. {APP_NAME} tik un tā pārlādēsies.",
  "EXTENSION_MANAGER_THEMES_INFO": "Lai <a class=\"theme_settings\">atlasītu noklusējuma motīvus</a> vai mainītu citus motīvu iestatījumus, <a class=\"theme_settings\">noklikšķiniet šeit</a> .",
  "EXTENSION_MANAGER_THEMES_UNDO": "Atgriezties uz iepriekšējo tēmu",
  "MARKED_FOR_REMOVAL": "Atzīmēts noņemšanai",
  "UNDO_REMOVE": "Atsaukt",
  "MARKED_FOR_UPDATE": "Atzīmēts atjaunināšanai",
  "UNDO_UPDATE": "Atsaukt",
  "MARKED_FOR_DISABLING": "Atzīmēts atspējošanai",
  "UNDO_DISABLE": "Atsaukt",
  "CHANGE_AND_RELOAD_TITLE": "Mainīt paplašinājumus",
  "CHANGE_AND_RELOAD_MESSAGE": "Lai atjauninātu, noņemtu vai atspējotu atzīmētos paplašinājumus, ir jāpārlādē {APP_NAME}. Jums būs jāsaglabā nesaglabātās izmaiņas.",
  "REMOVE_AND_RELOAD": "Noņemt paplašinājumus un pārlādēt",
  "CHANGE_AND_RELOAD": "Mainīt paplašinājumus un pārlādēt",
  "UPDATE_AND_RELOAD": "Atjaunināt paplašinājumus un pārlādēt",
  "DISABLE_AND_RELOAD": "Atspējot paplašinājumus un pārlādēt",
  "PROCESSING_EXTENSIONS": "Apstrādā paplašinājumu izmaiņas…",
  "EXTENSION_NOT_INSTALLED": "Nevarēja noņemt paplašinājumu {0}, jo tas nebija instalēts.",
  "NO_EXTENSIONS": "Vēl nav instalēti paplašinājumi.<br>Spiediet uz cilnes \"Pieejamie\", lai sāktu darbu.",
  "NO_EXTENSION_MATCHES": "Neviens paplašinājums neatbilst meklētajam.",
  "REGISTRY_SANITY_CHECK_WARNING": "PIEZĪME: Šo paplašinājumu autori var nebūt {APP_NAME} autori. Paplašinājumi nav pārskatīti, un tiem ir pilnas lokālās privilēģijas. Uzmanieties, instalējot paplašinājumus no nezināma avota.",
  "EXTENSIONS_INSTALLED_TITLE": "Instalētie",
  "EXTENSIONS_DEFAULT_TITLE": "Noklusējums",
  "EXTENSIONS_AVAILABLE_TITLE": "Pieejamie",
  "EXTENSIONS_THEMES_TITLE": "Dizaini",
  "EXTENSIONS_UPDATES_TITLE": "Atjauninājumi",
  "EXTENSIONS_LAST_UPDATED": "Pēdējoreiz atjaunots",
  "EXTENSIONS_DOWNLOADS": "Lejupielādes",
  "INLINE_EDITOR_NO_MATCHES": "Nav sakritību.",
  "INLINE_EDITOR_HIDDEN_MATCHES": "Visas sakritības ir sakļautas. Izvērsiet labajā pusē uzskaitītās datnes, lai apskatītu sakritības.",
  "CSS_QUICK_EDIT_NO_MATCHES": "Neeksistē tādas CSS kārtulas, kas atbilstu izvēlētajam.<br> Nospiediet \"Jauna kārtula\", lai to izveidotu.",
  "CSS_QUICK_EDIT_NO_STYLESHEETS": "Jūsu projektā nav stila lapu.<br>Izveidojiet to, lai pievienotu CSS kārtulas.",
  "IMAGE_VIEWER_LARGEST_ICON": "lielākais",
  "UNIT_PIXELS": "pikseļi",
  "DEBUG_MENU": "Atkļūdot",
  "ERRORS": "Kļūdas",
  "CMD_SHOW_DEV_TOOLS": "{APP_NAME} izstrādātāja rīki",
  "CMD_REFRESH_WINDOW": "Pārlādēt ar paplašinājumiem",
  "CMD_LOAD_CURRENT_EXTENSION": "Ielādēt projektu kā paplašinājumu",
  "CMD_RELOAD_CURRENT_EXTENSION": "Pārlādēt projektu kā paplašinājumu",
  "CMD_UNLOAD_CURRENT_EXTENSION": "Izlādēt projektu kā paplašinājumu",
  "CMD_RELOAD_WITHOUT_USER_EXTS": "Pārlādēt bez paplašinājumiem",
  "CMD_NEW_BRACKETS_WINDOW": "Jauns logs",
  "CMD_LAUNCH_SCRIPT_MAC": "Instalēt komandrindas saīsni",
  "CMD_SWITCH_LANGUAGE": "Mainīt valodu…",
  "CMD_RUN_UNIT_TESTS": "Palaidiet {APP_NAME} testus",
  "CMD_SHOW_PERF_DATA": "Rādīt veiktspējas informāciju",
  "CMD_ENABLE_LOGGING": "Iespējot detalizētus žurnālus",
  "CMD_ENABLE_PHNODE_INSPECTOR": "Iespējot PhNode inspektoru",
  "CMD_GET_PHNODE_INSPECTOR_URL": "Kā pārbaudīt PhNode",
  "CMD_ENABLE_LIVE_PREVIEW_LOGS": "Tiešraides priekšskatījuma žurnāli",
  "CMD_OPEN_BRACKETS_SOURCE": "Atvērt {APP_NAME} avotu",
  "CREATING_LAUNCH_SCRIPT_TITLE": "{APP_NAME} komandrindas saīsne",
  "ERROR_CREATING_LAUNCH_SCRIPT": "Radās kļūda, instalējot komandrindas saīsni. Lūdzu, mēģiniet <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting'>šīs problēmu noteikšanas ieteikumi</a>.<br/><br/>Iemesls: {0}",
  "ERROR_CLTOOLS_RMFAILED": "Neizdevās noņemt esošo <code>/usr/local/bin/brackets</code> simbolisko saiti.",
  "ERROR_CLTOOLS_MKDIRFAILED": "Neizdevās izveidot <code>/usr/local/bin</code> katalogu.",
  "ERROR_CLTOOLS_LNFAILED": "Neizdevās izveidot <code>/usr/local/bin/brackets</code> simbolisko saiti.",
  "ERROR_CLTOOLS_SERVFAILED": "Iekšēja kļūda.",
  "ERROR_CLTOOLS_NOTSUPPORTED": "Šī operētājsistēma neatbalsta komandrindas saīsni.",
  "LAUNCH_SCRIPT_CREATE_SUCCESS": "Veiksmīgi! Nu varat vienkārši palaist {APP_NAME} no komandrindas: <code>brackets myFile.txt</code>, lai atvērtu datni vai <code>brackets myFolder</code>, lai pārslēgtu projektus. <br/><br/><a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments'>Uzzināt vairāk</a>  par {APP_NAME} komandrindas izmantošanu.",
  "ERROR_LOADING_EXTENSION": "Ielādējot paplašinājumu, radās kļūda",
  "ERROR_NO_EXTENSION_PACKAGE": "<code>package.json</code> fails pašreizējā projektā nav atrasts. Vai pašreizējais projekts ir derīgs {APP_NAME} paplašinājums?</br> Plašāku informāciju skatiet <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>šajā saitē</a> .",
  "ERROR_INVALID_EXTENSION_PACKAGE": "<code>package.json</code> fails nav derīgs JSON.</br> Plašāku informāciju skatiet <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>šajā saitē</a> .",
  "ERROR_INVALID_EXTENSION_PACKAGE_FIELDS": "<code>package.json</code> failā trūkst obligāto lauku: [{0}]</br> Plašāku informāciju skatiet <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>šajā saitē</a> .",
  "ERROR_NODE_JS_CRASH_TITLE": "Hmm! Kaut kas nogāja greizi.",
  "ERROR_NODE_JS_CRASH_MESSAGE": "Radās problēma, un ir jārestartē lietotne {APP_NAME}. Neuztraucieties, mēs cenšamies saglabāt visu jūsu darbu pirms restartēšanas. </br>(Kļūda: ERROR_NODE_JS_CRASH)",
  "LANGUAGE_TITLE": "Pārslēgt valodu",
  "LANGUAGE_MESSAGE": "Valoda:",
  "LANGUAGE_SUBMIT": "Pārlādēt {APP_NAME}",
  "LANGUAGE_CANCEL": "Atcelt",
  "LANGUAGE_SYSTEM_DEFAULT": "Sistēmas noklusējums",
  "HEALTH_DATA_NOTIFICATION": "Veselības atskaites iestatījumi",
  "HEALTH_FIRST_POPUP_TITLE": "{APP_NAME} veselības atskaite",
  "HEALTH_DATA_DO_TRACK": "Dalīties ar anonīmu informāciju, kā es izmantoju {APP_NAME}",
  "HEALTH_DATA_NOTIFICATION_MESSAGE": "Lai uzlabotu lietotni {APP_NAME}, mēs periodiski nosūtām ierobežotu, <strong>pseidonīmu</strong> statistiku un kļūdu ziņojumus vietnei phcode.dev par to, kā izmantojat lietotni {APP_NAME}. Šī informācija palīdz noteikt funkcijām prioritāti, atrast kļūdas un pamanīt lietojamības problēmas, vienlaikus aizsargājot jūsu privātumu.<br><br> Varat skatīt savus datus vai izvēlēties nekoplietot datus, atlasot <strong>Palīdzība &gt; Veselības pārskats</strong> .<br><br>",
  "HEALTH_DATA_PREVIEW": "{APP_NAME} veselības atskaite",
  "HEALTH_DATA_PREVIEW_INTRO": "<p>Lai uzlabotu lietotni {APP_NAME}, mēs periodiski nosūtām ierobežotu, <strong>pseidonīmu</strong> statistiku un kļūdu ziņojumus vietnei phcode.dev par to, kā izmantojat lietotni {APP_NAME}. Šī informācija palīdz noteikt funkcijām prioritāti, atrast kļūdas un pamanīt lietojamības problēmas.</p><p> Tālāk ir sniegts to datu priekšskatījums, kas tiks nosūtīti nākamajā veselības pārskatā, <em>ja</em> tas ir iespējots. (Skatiet arī izstrādātāja konsoli, lai uzzinātu kļūdu žurnālus ar atzīmi “Pieķerta kritiska kļūda”.)</p>",
  "INLINE_TIMING_EDITOR_TIME": "Laiks",
  "INLINE_TIMING_EDITOR_PROGRESSION": "Progress",
  "BEZIER_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd><kbd>←</kbd><kbd>→</kbd>Pārvietot izvēlēto punktu<br><kbd class='text'>Shift</kbd> Pārvietot par desmit vienībām<br><kbd class='text'>Tabulācija</kbd> Pārslēgšanās punkti",
  "STEPS_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd> Palielināt vai samazināt soļus<br><kbd>←</kbd><kbd>→</kbd> 'Sākt' vai 'Beigt'",
  "INLINE_TIMING_EDITOR_INVALID": "Vecā vērtība <code>{0}</code> nav derīga, tāpēc parādītā funkcija tika mainīta uz <code>{1}</code>. Dokuments tiks atjaunināts līdz ar pirmo rediģēšanu.",
  "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP": "Pašreizējā krāsa",
  "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP": "Oriģinālā krāsa",
  "COLOR_EDITOR_RGBA_BUTTON_TIP": "RGBa formāts",
  "COLOR_EDITOR_HEX_BUTTON_TIP": "Hex formāts",
  "COLOR_EDITOR_HSLA_BUTTON_TIP": "HSLa formāts",
  "COLOR_EDITOR_0X_BUTTON_TIP": "Hex (0x) formāts",
  "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR": "{0} (lietots {1} reizi)",
  "COLOR_EDITOR_USED_COLOR_TIP_PLURAL": "{0} (lietots {1} reizes)",
  "CMD_JUMPTO_DEFINITION": "Pārlēkt uz definīciju",
  "CMD_SHOW_PARAMETER_HINT": "Rādīt parametru ieteikumus",
  "NO_ARGUMENTS": "<nav argumentu>",
  "DETECTED_EXCLUSION_TITLE": "JavaScript datnes izveduma problēma",
  "DETECTED_EXCLUSION_INFO": "Lietotnei {APP_NAME} radās problēmas, apstrādājot lietotni <span class='dialog-filename'>{0}</span> .<br><br> Šis fails vairs netiks apstrādāts, lai sniegtu koda ieteikumus, pārietu uz definīciju vai ātro rediģēšanu. Lai atkārtoti iespējotu šo failu, savā projektā atveriet <code>.phcode.json</code> un rediģējiet <code>jscodehints.detectedExclusions</code> .<br><br> Iespējams, šī ir {APP_NAME} kļūda. Ja varat iesniegt šī faila kopiju, lūdzu <a href='https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue'>, iesniedziet kļūdu</a> ar saiti uz šeit nosaukto failu.",
  "CMD_REFACTOR": "Refaktors",
  "CMD_EXTRACTTO_VARIABLE": "Ekstrakts uz mainīgo",
  "CMD_EXTRACTTO_FUNCTION": "Ekstrakts uz funkciju",
  "ERROR_TERN_FAILED": "Nevar iegūt datus no Tern",
  "ERROR_EXTRACTTO_VARIABLE_NOT_VALID": "Atlase neveido izteiksmi",
  "ERROR_EXTRACTTO_FUNCTION_NOT_VALID": "Atlasītajam blokam jāatspoguļo priekšrakstu kopa vai izteiksme",
  "ERROR_EXTRACTTO_VARIABLE_MULTICURSORS": "Izvilkums uz mainīgo nedarbojas vairākos kursoros",
  "ERROR_EXTRACTTO_FUNCTION_MULTICURSORS": "Ekstrakts uz funkciju nedarbojas vairākos kursoros",
  "EXTRACTTO_FUNCTION_SELECT_SCOPE": "Izvēlieties galamērķa tvērumu",
  "EXTRACTTO_VARIABLE_SELECT_EXPRESSION": "Izvēlieties izteiksmi",
  "CMD_REFACTORING_RENAME": "Pārdēvēt",
  "CMD_REFACTORING_TRY_CATCH": "Ietiniet Try Catch",
  "CMD_REFACTORING_CONDITION": "Iesaiņojums stāvoklī",
  "CMD_REFACTORING_GETTERS_SETTERS": "Izveidot Getters/Setters",
  "CMD_REFACTORING_ARROW_FUNCTION": "Konvertēt uz bultiņu funkciju",
  "DESCRIPTION_CODE_REFACTORING": "Iespējot/atspējot JavaScript koda pārstrukturēšanu",
  "ERROR_TRY_CATCH": "Atlasiet derīgu kodu, ko ietīt Try-catch blokā",
  "ERROR_WRAP_IN_CONDITION": "Atlasiet derīgu kodu, lai iekļautu nosacījumu blokā",
  "ERROR_ARROW_FUNCTION": "Novietojiet kursoru funkcijas izteiksmē",
  "ERROR_GETTERS_SETTERS": "Novietojiet kursoru uz objekta izteiksmes dalībnieka",
  "ERROR_RENAME_MULTICURSOR": "Nevar pārdēvēt, izmantojot vairākus kursorus",
  "ERROR_RENAME_QUICKEDIT": "Šo identifikatoru nevar pārdēvēt, jo tas ir norādīts citur ārpus šīs funkcijas",
  "ERROR_RENAME_GENERAL": "Nevar pārdēvēt atlasīto tekstu",
  "JSHINT_NAME": "JSHint",
  "CMD_ENABLE_QUICK_VIEW": "Ātrais skats uz norādēm",
  "CMD_ENABLE_SELECTION_VIEW": "Atlases skats",
  "TOOLTIP_CLICK_TO_EDIT_COLOR": "Noklikšķiniet šeit, lai rediģētu krāsu",
  "CMD_TOGGLE_RECENT_PROJECTS": "Nesenie projekti",
  "REMOVE_FROM_RECENT_PROJECTS": "Noņemt no jaunākajiem projektiem",
  "DOCS_MORE_LINK": "Lasīt vairāk",
  "COLLAPSE_ALL": "Sakļaut visu",
  "EXPAND_ALL": "Izvērst visu",
  "COLLAPSE_CURRENT": "Sakļaut pašreizējo",
  "EXPAND_CURRENT": "Izvērst pašreizējo",
  "RECENT_FILES_DLG_HEADER": "Jaunākie faili",
  "RECENT_FILES_DLG_CLEAR_BUTTON_LABEL": "Skaidrs",
  "RECENT_FILES_DLG_CLEAR_BUTTON_TITLE": "Notīrīt failus, kas nav darba komplektā",
  "RECOVER_UNSAVED_FILES_TITLE": "Vai atgūt nesaglabātos failus?",
  "RECOVER_UNSAVED_FILES_MESSAGE": "Vai atjaunot nesaglabātos failus no iepriekšējās sesijas?",
  "RECOVER_UNSAVED_FILES_RESTORE": "Atjaunot",
  "DISCARD_UNSAVED_FILES_RESTORE": "Izmest",
  "DESCRIPTION_CLOSE_BRACKETS": "vērtība true, lai automātiski aizvērtu figūriekavas, iekavas un apaļās iekavas",
  "DESCRIPTION_CLOSE_OTHERS_ABOVE": "vērtība false, lai noņemtu \"Aizvērt visus augstāk\" no darba datņu kontekstizvēlnes",
  "DESCRIPTION_CLOSE_OTHERS_BELOW": "vērtība false, lai noņemtu \"Aizvērt visus zemāk\" no darba datņu kontekstizvēlnes",
  "DESCRIPTION_CLOSE_OTHERS": "vērtība false, lai noņemtu \"Aizvērt citus\" no darba datņu kontekstizvēlnes",
  "DESCRIPTION_CLOSE_TAGS": "Nosaka tagu aizvēršanas iespējas",
  "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS": "Tagu masīvs, kas nav automātiski jāaizver",
  "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING": "Aizvērt, kad tiek ierakstīts atverošā taga > ",
  "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING": "Aizvērt, kad tiek ierakstīts aizverošā taga / ",
  "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS": "Tagu masīvs, kuru atverot ir tukša rinda",
  "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD": "vērtība true, lai vienmēr ģenerētu sakļaušanas atzīmes, kad mainās atkāpes līmenis",
  "DESCRIPTION_CODE_FOLDING_ENABLED": "vērtība true, lai iespējotu koda locīšanu",
  "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER": "vērtība true, lai sadaļu sakļaušanas atzīmes būtu redzamas, kustinot peli pāri koda kreisajai malai",
  "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL": "Limitēt, uz cik līmeņiem attiecas Sakļaut visu",
  "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE": "Minimālais rindu skaits, pirms parādās sakļaušanas sadaļas ikona",
  "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES": "vērtība true, lai atcerētos sakļautās sadaļas, aizverot un no jauna atverot datni vai projektu",
  "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE": "vērtība true, lai iespējotu koda locīšanu izvēlētajam tekstam redaktorā",
  "DESCRIPTION_DISABLED_DEFAULT_EXTENSIONS": "Noklusējuma paplašinājumi, kas ir atspējoti",
  "DESCRIPTION_ATTR_HINTS": "Iespējot/atspējot HTML atribūtu ieteikumus",
  "DESCRIPTION_CSS_PROP_HINTS": "Iespējot/atspējot CSS/LESS/SCSS rekvizītu ieteikumus",
  "DESCRIPTION_JS_HINTS": "Iespējot/atspējot JavaScript koda ieteikumus",
  "DESCRIPTION_JS_HINTS_TYPE_DETAILS": "Iespējot/atspējot datu tipa informāciju JavaScript koda ieteikumos",
  "DESCRIPTION_PREF_HINTS": "Iespējot/atspējot iestatījumu koda ieteikumus",
  "DESCRIPTION_SPECIAL_CHAR_HINTS": "Iespējot/atspējot HTML elementu ieteikumus",
  "DESCRIPTION_SVG_HINTS": "Iespējot/atspējot SVG koda ieteikumus",
  "DESCRIPTION_HTML_TAG_HINTS": "Iespējot/atspējot HTML tagu ieteikumus",
  "DESCRIPTION_URL_CODE_HINTS": "Iespējot/atspējot URL ieteikumus HTML & CSS/LESS/SCSS",
  "DESCRIPTION_DRAG_DROP_TEXT": "Iespējot/atspējot ievilkšanas & nomešanas funkcionalitāti",
  "DESCRIPTION_HEALTH_DATA_TRACKING": "Iespējot sekošanu veselības datiem",
  "DESCRIPTION_HIGHLIGHT_MATCHES": "Iespējot automātisko saskanīgo virkņu izcelšanu visā dokumentā",
  "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN": "Izcelt visas virknes, kuras sakrīt ar tekstvienībām, kurās šobrīd ir kursors (nav nepieciešams izvēlēties)",
  "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY": "Izcelt tikai tad, kad izvēlētais ir pilna tekstvienība",
  "DESCRIPTION_INSERT_HINT_ON_TAB": "vērtība true, lai ievietotu pašlaik izvēlēto koda ieteikumu cilnē",
  "DESCRIPTION_NO_HINTS_ON_DOT": "vērtība true, lai automātiski nerādītu JS koda ieteikumus, ierakstot .",
  "DESCRIPTION_JSHINT_OPTIONS": "Objekts ar noklusējuma opcijām JSHint. Lūdzu, skatiet šo URL, lai uzzinātu visas pieejamās JSHint opcijas: https://jshint.com/docs/options/",
  "DESCRIPTION_LANGUAGE": "Specifiski valodas iestatījumi",
  "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS": "Papildu kartēšana no datnes paplašinājuma uz valodas nosaukumu",
  "DESCRIPTION_LANGUAGE_FILE_NAMES": "Papildu kartēšana no datnes nosaukuma uz valodas nosaukumu",
  "DESCRIPTION_LINEWISE_COPY_CUT": "Kopējot un izgriežot, kad nav atlases, tiks kopētas vai izgrieztas visas rindas, kurās ir kursori",
  "DESCRIPTION_INPUT_STYLE": "Atlasa veidu, kā CodeMirror apstrādā ievadi un fokusu. Tas var būt teksta apgabals, kas ir noklusējuma iestatījums, vai saturiski rediģējams, kas ir labāks ekrāna lasītājiem (nestabils).",
  "DESCRIPTION_LINTING_ENABLED": "vērtība true, lai iespējotu koda pārbaudi",
  "DESCRIPTION_ASYNC_TIMEOUT": "Laiks milisekundēs pēc asinhronās sintakses pārbaudes taimauta",
  "DESCRIPTION_LINTING_PREFER": "Sintakses pārbaužu kārtība",
  "DESCRIPTION_LIVE_DEV_MULTIBROWSER": "vērtība true, lai iespējotu eksperimentālo tiešo priekšskatījumu",
  "DESCRIPTION_USE_PREFERED_ONLY": "vērtība true, lai palaistu sniedzējus, kas norādīti tikai linting.prefer",
  "DESCRIPTION_MAX_CODE_HINTS": "Sasniegts maksimālais vienlaicīgi parādīto kodu ieteikumu skaits",
  "DESCRIPTION_PATH": "Specifiski ceļu iestatījumi",
  "DESCRIPTION_PROXY": "Paplašinājuma instalēšanai izmantotais starpniekservera URL",
  "DESCRIPTION_SCROLL_PAST_END": "vērtība true, lai iespējotu ritināšanu pēc dokumenta beigām",
  "DESCRIPTION_SHOW_CODE_HINTS": "vērtība false, lai atspējotu koda ieteikumus",
  "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING": "Atstāj mirgojošo kursoru redzamu, kad izvēlēts teksts",
  "DESCRIPTION_SHOW_LINE_NUMBERS": "vērtība true, lai rādītu rindu numuru koda kreisajā malā",
  "DESCRIPTION_SMART_INDENT": "Automātiskā atkāpe, veidojot jaunu bloku",
  "DESCRIPTION_SOFT_TABS": "vērtība false, lai izslēgtu mīkstās tabulācijas uzvedību",
  "DESCRIPTION_SORT_DIRECTORIES_FIRST": "vērtība true, lai projektu kokā pirmos sakārtotu katalogus",
  "DESCRIPTION_SPACE_UNITS": "Atstarpju skaits, lai izmantotu uz atstarpēm balstītas atkāpes",
  "DESCRIPTION_STATIC_SERVER_PORT": "Porta numurs, kas iebūvētajam serverim jāizmanto tiešajam priekšskatījumam",
  "DESCRIPTION_STYLE_ACTIVE_LINE": "vērtība true, lai izceltu fona krāsu rindai, kurā atrodas kursors",
  "DESCRIPTION_TAB_SIZE": "Atstarpju skaits, lai parādītu tabulāciju",
  "DESCRIPTION_USE_TAB_CHAR": "vērtība true, lai atstarpju vietā izmantotu tabulāciju",
  "DESCRIPTION_UPPERCASE_COLORS": "vērtība true, lai iekšrindas krāsu redaktorā ģenerētu  heksadecimālos krāsu kodus ar lielajiem burtiem",
  "DESCRIPTION_WORD_WRAP": "Rindu aplaušana, lai pārsniegtu skatlauka platumu",
  "DESCRIPTION_SEARCH_AUTOHIDE": "Aizveriet meklēšanu, tiklīdz redaktors ir fokusēts",
  "DESCRIPTION_DETECTED_EXCLUSIONS": "Noteikto datņu saraksts, kas izraisīja Tern nekontrolējamību",
  "DESCRIPTION_INFERENCE_TIMEOUT": "Laiks, pēc kura Tern iestāsies taimauts, cenšoties saprast datnes",
  "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR": "vērtība true, lai rādītu kļūdas statusa joslā",
  "DESCRIPTION_QUICK_VIEW_ENABLED": "vērtība true, lai iespējotu ātro skatu",
  "DESCRIPTION_SELECTION_VIEW_ENABLED": "True, lai iespējotu atlases skatu",
  "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW": "vērtība true, lai rādītu attēlu priekšskatījumus URL bez paplašinājumiem",
  "DESCRIPTION_NUMBER_QUICK_VIEW": "True, lai rādītu ātro skatu, novietojot kursoru virs cipariem redaktorā",
  "DESCRIPTION_THEME": "Izvēlēties {APP_NAME} dizainu",
  "DESCRIPTION_USE_THEME_SCROLLBARS": "vērtība true, lai atļautu pielāgotas ritjoslas",
  "DESCRIPTION_LINTING_COLLAPSED": "vērtība true, lai sakļautu sintakses pārbaudes paneli",
  "DESCRIPTION_FONT_FAMILY": "Mainīt fontu saimi",
  "DESCRIPTION_DESKTOP_ZOOM_SCALE": "Izvēlieties tālummaiņas mēroga koeficientu no 0,1 (kompaktākam skatam) līdz 2 (lielākam, palielinātam skatam). Pieejams tikai darbvirsmas lietotnēs",
  "DESCRIPTION_FONT_SIZE": "Mainīt fonta lielumu; piemēram, 13px",
  "DESCRIPTION_FIND_IN_FILES_NODE": "vērtība true, lai iespējotu uz mezgliem balstītu meklēšanu",
  "DESCRIPTION_FIND_IN_FILES_INSTANT": "vērtība true, lai iespējotu tūlītēju meklēšanu",
  "DESCRIPTION_FONT_SMOOTHING": "Tikai Mac: \"subpikseļi-gludināšana\", lai iespējotu subpikseļu gludināšanu vai \"gludināšana\", lai iespējotu pelēko toņu gludināšanu",
  "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW": "vērtība false, lai atspējotu iestatījumu datni sadalītajā skatā",
  "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE": "vērtība false, lai atvērtu iestatījumu datni kreisajā/augšējā rūtī",
  "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED": "vērtība true, lai sakļautu rūtis, kad tiek aizvērta pēdējā rūts ar aizvēršanas pogu rūts galvenē",
  "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS": "Rādīt/nerādīt aizvēršanas un pārnešanas pogas galvenē.",
  "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT": "/*\n * Šis ir tikai lasāms fails ar atbalstītajām preferencēm\n * autors {APP_NAME}.\n * Izmantojiet šo failu kā atsauci, lai mainītu savas preferences\n * fails \"phcode.json\" atvērts citā rūtī.\n * Lai iegūtu plašāku informāciju par preferenču izmantošanu iekšpusē\n * {APP_NAME}, skatiet tīmekļa lapu https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences\n */",
  "DEFAULT_PREFERENCES_JSON_DEFAULT": "Noklusējums",
  "DESCRIPTION_PURE_CODING_SURFACE": "vērtība true, lai iespējotu tikai koda režīmu un paslēptu visus citus UI elementus {APP_NAME}",
  "DESCRIPTION_INDENT_LINE_COMMENT": "vērtība true, lai iespējotu rindas komentāru atkāpi",
  "DESCRIPTION_RECENT_FILES_NAV": "Iespējot/atspējot navigāciju jaunākajos failos",
  "DESCRIPTION_LIVEDEV_WEBSOCKET_PORT": "Ports, kurā WebSocket Server darbojas tiešraides priekšskatījumam",
  "DESCRIPTION_LIVE_DEV_HIGHLIGHT_SETTINGS": "Tiešraides priekšskatījuma izcelšanas iestatījumi",
  "DESCRIPTION_LIVEDEV_ENABLE_REVERSE_INSPECT": "false, lai atspējotu tiešā priekšskatījuma apgriezto pārbaudi",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW": "Nav ko priekšskatīt!",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW_DETAILS": "Lūdzu, atlasiet priekšskatīšanai HTML failu",
  "DESCRIPTION_LIVEDEV_PREVIEW_RESTRICTED": "Priekšskatījums nav pieejams!",
  "DESCRIPTION_LIVEDEV_PREVIEW_RESTRICTED_DETAILS": "Šis HTML fails nav pašreizējā projekta daļa. Drošības apsvērumu dēļ tiešraidē var priekšskatīt tikai projekta failus. Lai priekšskatītu šo failu, atveriet tajā esošo mapi kā atsevišķu projektu.",
  "DESCRIPTION_LIVEDEV_MAIN_HEADING": "Ak, vai!<br> Jūsu pašreizējā pārlūkprogramma neatbalsta tiešo priekšskatījumu.",
  "DESCRIPTION_LIVEDEV_MAIN_SPAN": "Iegūstiet vislabāko tiešraides priekšskatījuma pieredzi, lejupielādējot mūsu vietējās lietotnes operētājsistēmai Windows, Mac un Linux no <a href=\"https://phcode.io\" style=\"color: white\">vietnes phcode.io</a> .<br>",
  "DESCRIPTION_LIVEDEV_SECURITY_POPOUT_MESSAGE": "Jūs gatavojaties atvērt failu tiešraides priekšskatīšanai. Lūdzu, turpiniet tikai tad, ja uzticaties šī projekta avotam. Noklikšķiniet uz Trust Project, lai turpinātu, vai aizveriet šo logu, ja neuzticaties avotam.",
  "DESCRIPTION_LIVEDEV_SECURITY_TRUST_MESSAGE": "Jūs gatavojaties atvērt failu tiešraides priekšskatīšanai. Lūdzu, turpiniet, noklikšķinot uz “Uzticēties projektam” tikai tad, ja uzticaties šī projekta avotam!",
  "CONFIRM_EXTERNAL_BROWSER_TITLE": "Uznirstošie logi ir bloķēti",
  "CONFIRM_EXTERNAL_BROWSER_MESSAGE": "Vai vēlaties ļaut tiešraides priekšskatījuma lapai atvērt šo URL: {0}?",
  "TRUST_PROJECT": "Uzticības un izpildes priekšskatījums — {0}",
  "TRUST_AUTHORS": "Vai uzticaties šī projekta autoriem?",
  "DOWNLOAD_FAILED": "Lejupielāde neizdevās.",
  "DOWNLOAD_COMPLETE": "Lejupielāde ir pabeigta!",
  "UPDATE_SUCCESSFUL": "Atjaunināšana ir veiksmīga!",
  "UPDATE_FAILED": "Atjaunināšana neizdevās!",
  "VALIDATION_FAILED": "Validācija neizdevās!",
  "INITIALISATION_FAILED": "Inicializācija neizdevās!",
  "CLEANUP_FAILED": "Tīrīšana neizdevās!",
  "WARNING_TYPE": "Brīdinājums!",
  "CLICK_RESTART_TO_UPDATE": "Noklikšķiniet uz Restartēt, lai atjauninātu iekavas.",
  "UPDATE_ON_NEXT_LAUNCH": "Atjauninājums tiks lietots atkārtotas palaišanas laikā.",
  "GO_TO_SITE": "Dodieties uz <a href = \"http://brackets.io/\">brackets.io</a> , lai mēģinātu vēlreiz.",
  "INTERNET_UNAVAILABLE": "Nav pieejams interneta pieslēgums.",
  "UPDATEDIR_READ_FAILED": "Atjaunināšanas direktoriju nevarēja nolasīt.",
  "UPDATEDIR_CLEAN_FAILED": "Atjaunināšanas direktoriju nevarēja notīrīt.",
  "INITIAL_DOWNLOAD": "Notiek atjauninājuma lejupielāde...",
  "RETRY_DOWNLOAD": "Lejupielāde neizdevās. Notiek atkārtots mēģinājums... Mēģinājums",
  "VALIDATING_INSTALLER": "Lejupielāde ir pabeigta! Notiek instalētāja apstiprināšana...",
  "CHECKSUM_DID_NOT_MATCH": "Kontrolsumma nesakrita.",
  "INSTALLER_NOT_FOUND": "Instalētājs nav atrasts.",
  "DOWNLOAD_ERROR": "Lejupielādes laikā radās kļūda.",
  "NETWORK_SLOW_OR_DISCONNECTED": "Tīkls ir atvienots vai pārāk lēns.",
  "RESTART_BUTTON": "Restartēt",
  "LATER_BUTTON": "Vēlāk",
  "DESCRIPTION_AUTO_UPDATE": "Iespējot/atspējot iekavu automātisko atjaunināšanu",
  "AUTOUPDATE_ERROR": "Kļūda!",
  "AUTOUPDATE_IN_PROGRESS": "Atjaunināšana jau notiek.",
  "NUMBER_WITH_PERCENTAGE": "{0}%",
  "CMD_FIND_RELATED_FILES": "Atrodiet saistītos failus",
  "PHP_VERSION_INVALID": "Kļūda parsējot PHP versiju. Lūdzu, pārbaudiet komandas “php –version” izvadi.",
  "PHP_UNSUPPORTED_VERSION": "Instalējiet PHP7 izpildlaiku, lai iespējotu ar PHP saistītus rīkus, piemēram, koda ieteikumus, parametru ieteikumus, pāriet uz definīciju un citus. Atrasta versija: {0}",
  "PHP_EXECUTABLE_NOT_FOUND": "PHP izpildlaiks nav atrasts. Instalējiet PHP7 izpildlaiku un atbilstoši atjauniniet “executablePath” PHP preferencēs. Tas nodrošina ar PHP saistītus rīkus, piemēram, koda ieteikumus, parametru ieteikumus, pāreju uz definīciju un citus.",
  "PHP_PROCESS_SPAWN_ERROR": "Sākot PHP procesu, tika konstatēts kļūdas kods {0}.",
  "PHP_SERVER_ERROR_TITLE": "Kļūda",
  "PHP_SERVER_MEMORY_LIMIT_INVALID": "Jūsu norādītais atmiņas ierobežojums nav derīgs. Pārskatiet PHP preferences, lai iestatītu pareizo vērtību.",
  "DESCRIPTION_PHP_TOOLING_CONFIGURATION": "PHP Tooling noklusējuma konfigurācijas iestatījumi",
  "OPEN_PREFERENNCES": "Atveriet iestatījumus",
  "LANGUAGE_TOOLS_PREFERENCES": "Valodu rīku preferences",
  "FIND_ALL_REFERENCES": "Atrodiet visas atsauces",
  "REFERENCES_IN_FILES": "atsauces",
  "REFERENCE_IN_FILES": "atsauce",
  "REFERENCES_NO_RESULTS": "Atsauces uz pašreizējo kursora pozīciju nav pieejamas",
  "CMD_FIND_DOCUMENT_SYMBOLS": "Atrodiet dokumentu simbolus",
  "CMD_FIND_PROJECT_SYMBOLS": "Atrodiet projekta simbolus",
  "REMOTE_DEBUGGING_ENABLED": "Vietējā resursdatorā ir iespējota attālā atkļūdošana:",
  "REMOTE_DEBUGGING_PORT_INVALID": "Nevar iespējot attālo atkļūdošanu portā {0}. Portu numuriem ir jābūt no {1} līdz {2}.",
  "DESCRIPTION_EXTERNAL_APPLICATION_ASSOCIATE": "Kartējumi failu paplašinājumiem ārējām lietojumprogrammām. Sintakse: \"<faila_tips>\": \"<default|applicationName|ApplicationPath>\", Izmantojiet \"noklusējums\", lai atvērtu failus sistēmas noklusējuma lietojumprogrammā atbilstoši faila tipam.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_TITLE": "Atveriet grafiskos failus ārējos redaktoros.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_MSG": "Jūsu pašreizējā mapē ir grafisko failu tipi, kurus neatbalsta lietotne {APP_NAME}.<br/> Tagad konkrētus failu tipus varat saistīt ar ārējiem redaktoriem. Pēc pievienošanas varat atvērt grafiskos failus, piemēram, .xd, .psd, .jpg, .png, .ai, .svg to noklusējuma lietojumprogrammās, veicot dubultklikšķi uz failiem failu kokā.<br/><br/> Lūdzu, noklikšķiniet uz pogas &quot;Labi&quot;, lai saistītu grafisko failu tipus ar to attiecīgajām noklusējuma lietojumprogrammām.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_CNF_MSG": "Šie failu tipi ir veiksmīgi saistīti ar noklusējuma lietojumprogrammām.<br/> {0} Jums ir iespēja mainīt preferences attiecībā uz to, vai failā phcode.json dzēst/pievienot jaunas failu tipu asociācijas, atverot izvēlni “Atkļūdošana-&gt; Atvērt preferenču failu”.",
  "UNSUPPORTED_BROWSER_TITLE": "Pārlūkprogramma netiek atbalstīta",
  "UNSUPPORTED_BROWSER_MESSAGE": "Lūdzu, izmantojiet modernu pārlūkprogrammu (izlaista pēdējo 3 gadu laikā).",
  "UNSUPPORTED_BROWSER_MOBILE_TITLE": "Mobilās pārlūkprogrammas netiek atbalstītas",
  "UNSUPPORTED_BROWSER_MOBILE": "Mobilās un planšetdatoru pārlūkprogrammas pašlaik netiek pilnībā atbalstītas. Varat aizvērt šo dialogu, taču dažas Phoenix funkcijas nedarbosies šajā pārlūkprogrammā.<br/><br/> Mēs strādājam pie vietējo lietotņu izstrādes operētājsistēmai iOS un Android. <a href=\"https://github.com/phcode-dev/phoenix/discussions/1046\" target=\"_blank\">Pievienojieties diskusijai šeit!</a>",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER_TITLE": "Pārlūkprogramma neatbalsta piekļuvi vietējai mapei",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER": "Atvainojiet, šķiet, ka jūsu pašreizējā pārlūkprogramma neatbalsta vietējo mapju atvēršanu. Šai funkcijai iesakām izmantot Chrome, Edge vai Opera.<br/><br/> Alternatīvi, mēs strādājam pie vietējo lietotņu izstrādes operētājsistēmai Windows, Mac, Linux, iOS un Android, lai nodrošinātu pilnīgu atbalstu. <a href=\"https://github.com/phcode-dev/phoenix/discussions/1047\" target=\"_blank\">Sekojiet līdzi jaunumiem!</a>",
  "ATTENTION_SAFARI_USERS": "Uzmanību Safari lietotājiem",
  "ATTENTION_SAFARI_USERS_MESSAGE": "<span>Safari automātiski izdzēš vietnes datus, ja vietne netiek atkārtoti apmeklēta 7 dienu laikā. Lai saglabātu jūsu projektus, {APP_NAME} izmanto pārlūkprogrammas krātuvi, kas var tikt noņemta šīs politikas dēļ.<br/><br/> Ieteicams <strong>lejupielādēt macOS darbvirsmas lietotni</strong> no <a href='https://phcode.io' target='_blank' style='color: white'>vietnes https://phcode.io</a></span>",
  "CANNOT_PUBLISH_LARGE_PROJECT": "Nevar publicēt lielu projektu",
  "CANNOT_PUBLISH_LARGE_PROJECT_MESSAGE": "Phoenix joprojām ir eksperimentālā alfa. Mēs vēl neesam iespējojuši sinhronizāciju projektiem, kuros ir vairāk nekā 500 failu.",
  "SHARE_WEBSITE": "Vai publicēt un kopīgot vietni?",
  "PUBLISH": "Publicēt",
  "PUBLISH_CONSENT_MESSAGE": "Ātri priekšskatiet izmaiņas un kopīgojiet savu vietni ar citiem. Phoenix var publicēt šo vietni jūsu vietā vietnē {0}. Publicētās saites būs derīgas 30 dienas. </br>Vai vēlaties publicēt un koplietot savu vietni?",
  "PUBLISH_SYNC_IN_PROGRESS": "Notiek sinhronizācija priekšskatījumam...",
  "PUBLISH_PAGE": "Noklikšķiniet, lai publicētu un kopīgotu šo vietni",
  "PUBLISH_VIEW_PAGE": "Noklikšķiniet, lai skatītu publicēto lapu",
  "MISSING_FIELDS": "Trūkstošie lauki",
  "PLEASE_FILL_ALL_REQUIRED": "Lūdzu, aizpildiet visus obligātos laukus, kas iezīmēti sarkanā krāsā",
  "CODE_EDITOR": "Koda redaktors",
  "BUILD_THE_WEB": "Veidojiet tīmekli",
  "IMPORT_PROJECT": "Importēt projektu",
  "GITHUB_PROJECT": "GitHub projekts",
  "NEW_PROJECT_FROM_GITHUB": "Jauns projekts no GitHub",
  "GITHUB_REPO_URL": "GitHub repo URL:",
  "CREATE_PROJECT": "Izveidot projektu",
  "SETTING_UP_PROJECT": "Projekta iestatīšana",
  "LOCATION": "Atrašanās vieta:",
  "DOWNLOADING": "Notiek lejupielāde...",
  "DOWNLOADING_FILE": "Notiek {0} lejupielāde...",
  "EXTRACTING_FILES_PROGRESS": "Notiek {0} no {1} failu izvilkšana.",
  "COMPRESS_FILES_PROGRESS": "Notiek {0} no {1} failu saspiešana.",
  "DOWNLOAD_FAILED_MESSAGE": "Pārliecinieties, vai lejupielādes URL ir derīgs. </br>Ņemiet vērā: tā kā Phoenix ir alfa, nav atļauti privātie repo un GitHub vietrāži URL, kas lielāki par 25 MB.",
  "PLEASE_SELECT_A_FOLDER": "Lūdzu, atlasiet mapi...",
  "UNZIP_IN_PROGRESS": "Notiek failu izsaiņošana...",
  "UNZIP_FAILED": "Kļūda: izsaiņošana neizdevās.",
  "CONFIRM_REPLACE_TITLE": "Apstipriniet Aizstāt",
  "KEEP_BOTH": "Saglabājiet abus",
  "EXPLORE": "HTML spēles",
  "BLOG": "Emuārs",
  "PHOENIX_DEFAULT_PROJECT": "Noklusējuma projekts",
  "PROJECT_NAME": "Projekta nosaukums:",
  "NEW_HTML": "Jauns HTML projekts",
  "LICENSE": "Licence:",
  "CREDITS": "Kredīti:",
  "PREVIEW": "Priekšskatījums",
  "BUILD_WEBSITE": "Izveidojiet vietni",
  "VIEW_MORE": "Skatīt vairāk...",
  "NEW_PROJECT_NOTIFICATION": "Noklikšķiniet uz šīs ikonas, lai izveidotu jaunu projektu.</br><img src=\"styles/images/new_project.png\"><br/> <a href='#' style='float:right;'>labi</a>",
  "BEAUTIFY_CODE_NOTIFICATION": "Noklikšķiniet šeit vai nospiediet <b>`{0}`</b> , lai izdaiļotu kodu.</br><img src=\"styles/images/beautify.gif\"><br/> <a href='#' style='float:right;'>labi</a>",
  "DEFAULT_PROJECT_NOTIFICATION": "Noklikšķiniet šeit, lai atvērtu<br/> <b>noklusējuma projekts</b> Fīniksā.</br> <a href='#' style='float:right;'>labi</a>",
  "DIRECTORY_REPLACE_MESSAGE": "Atlasītā mape <span class='dialog-filename'>{0}</span> nav tukša. Vai tiešām vēlaties aizstāt mapes saturu ar projektu?",
  "BUILD_WEBSITE_SECTION": "Izveidojiet vietni",
  "LEARN_SECTION": "Mācieties ar piemēriem",
  "CREATE_EXTENSION_SECTION": "Izveidojiet {APP_NAME} paplašinājumus un motīvus",
  "CREATE_EXTENSION": "Izveidot paplašinājumu",
  "CREATE_THEME": "Izveidojiet motīvu",
  "WEBPAGE_HOME_PAGE": "Mājas lapa",
  "WEBPAGE_BLOG": "Emuāra lapa",
  "WEBPAGE_DASHBOARD": "HTML informācijas panelis",
  "WEBPAGE_BOOTSTRAP_EXAMPLES": "Bootstrap piemēri",
  "PROJECTS_AT_A_GLANCE": "Jūsu projekti īsumā",
  "PROJECT_AT_GLANCE_DESCRIPTION": "Lai sāktu, skatieties video.",
  "PROJECT_FROM_BROWSER": "Saglabāts jūsu pārlūkprogrammā",
  "PROJECT_FROM_BROWSER_TERSE": "Pārlūka krātuve",
  "PROJECT_SHOW_ON_STARTUP": "Rādīt šo dialogu startēšanas laikā",
  "GUIDED_LIVE_PREVIEW": "Veiciet dažas koda izmaiņas HTML failā, lai redzētu tiešo priekšskatījumu.</br> <a href='#' style='float:right;'>labi</a>",
  "GUIDED_LIVE_PREVIEW_POPOUT": "Noklikšķiniet uz šīs pogas, lai tiešraides priekšskatījumu atvērtu jaunā cilnē.</br> <a href='#' style='float:right;'>labi</a>",
  "ENJOYING_APP": "Vai jums patīk lietotne {APP_NAME}?",
  "GITHUB_STARS_POPUP": "<div>Jūsu atsauksmes motivē mūsu mazo komandu, lai padarītu <b>vietni phcode.dev</b> vēl labāku.<br/> Lūdzu, atzīmējiet mūs ar zvaigznīti GitHub:",
  "GITHUB_STARS_POPUP_TWITTER": "Sniedziet atsauksmes vai izplatiet informāciju pakalpojumā Twitter:",
  "TEST_TRANSLATE": "izmantojiet to, lai pārbaudītu tulkojumus",
  "POWER_USER_POPUP_TITLE": "Kā mēs varam uzlabot lietotni {APP_NAME}?",
  "POWER_USER_POPUP_TEXT": "<div>Mēs labprāt saņemtu jūsu atsauksmes. Jūsu atsauksmes palīdz mums izlemt, kuras funkcijas izveidot un kādi uzlabojumi būtu jāveic mūsu platformā.<br/> <a>Lūdzu, aizpildiet šo īso aptauju.</a></div>",
  "BEAUTIFY_ERROR": "Nevarēja izdaiļot kodu. Pārbaudiet sintakse.",
  "BEAUTIFY_ERROR_ORIGINAL_CHANGED": "Nevarēja izdaiļot. Redaktora teksts mainīts pēc izdaiļošanas.",
  "BEAUTIFY_PROJECT_BUSY_MESSAGE": "Skaistuma fails {0}",
  "BEAUTIFY_ERROR_SELECTION": "Nevarēja izdaiļot.</br>Atlasīts nepilnīgs koda bloks vai nederīga sintakse.",
  "BEAUTIFY_OPTIONS": "Opcijas, kas kontrolē, kā Beautify Code darbojas",
  "BEAUTIFY_OPTION_PRINT_WIDTH": "Norādiet līnijas garumu, uz kuru ietīs skaistumkopšanas līdzeklis",
  "BEAUTIFY_OPTION_SEMICOLON": "Katra paziņojuma beigās pievienojiet semikolu",
  "BEAUTIFY_OPTION_SINGLE_QUOTE": "Izmantojiet vienas pēdiņas, nevis dubultpēdiņas",
  "BEAUTIFY_OPTION_QUOTE_PROPS": "Mainiet, kad objektos tiek norādītas īpašības",
  "BEAUTIFY_OPTION_BRACKET_SAME_LINE": "Ievietojiet vairāku rindiņu HTML (HTML, JSX, Vue, Angular) elementu > pēdējās rindiņas beigās, nevis ievietojiet vienu pašu nākamajā rindā (neattiecas uz pašaizverošiem elementiem).",
  "BEAUTIFY_OPTION_SINGLE_ATTRIBUTE_PER_LINE": "Ieviesiet vienu atribūtu katrā rindā HTML, Vue un JSX",
  "BEAUTIFY_OPTION_PROSE_WRAP": "Aptiniet prozu, ja tas pārsniedz drukas platumu atzīmes failos",
  "BEAUTIFY_OPTION_PRINT_TRAILING_COMMAS": "Drukājiet beigu komatus, kur vien iespējams, vairāku rindiņu komatu atdalītās sintaktiskās struktūrās"
});