/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "系統預設",
  "PROJECT_BUSY": "專案作業進行中",
  "DUPLICATING": "複製 {0} 中",
  "MOVING": "移動 {0} 中",
  "COPYING": "複製 {0} 中",
  "DELETING": "刪除 {0} 中",
  "DELETE_TO_TRASH": "將 {0} 移至垃圾桶",
  "DELETE_TO_RECYCLE_BIN": "將 {0} 移至資源回收筒",
  "RENAMING": "重新命名中",
  "STORED_IN_YOUR_BROWSER": "儲存於您的瀏覽器中",
  "SUPPORT_US_OPEN_COLLECTIVE": "在 GitHub 贊助我們",
  "GENERIC_ERROR": "(錯誤 {0})",
  "NOT_FOUND_ERR": "找不到檔案或目錄。",
  "NOT_READABLE_ERR": "無法讀取檔案或目錄。",
  "EXCEEDS_MAX_FILE_SIZE": "{APP_NAME} 無法開啟大於 {0} MB 的檔案。",
  "NO_MODIFICATION_ALLOWED_ERR": "無法異動目標目錄。",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "您的權限不足，無法修改。",
  "CONTENTS_MODIFIED_ERR": "檔案已被 {APP_NAME} 以外的程式修改。",
  "UNSUPPORTED_ENCODING_ERR": "{APP_NAME} 目前只支援 UTF-8 編碼的文字檔。",
  "ENCODE_FILE_FAILED_ERR": "{APP_NAME} 無法編碼檔案內容。",
  "DECODE_FILE_FAILED_ERR": "{APP_NAME} 無法解碼檔案內容。",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "{APP_NAME} 目前不支援 UTF-16 編碼的文字檔。",
  "FILE_EXISTS_ERR": "檔案或目錄已經存在。",
  "FILE": "檔案",
  "FILE_TITLE": "檔案",
  "DIRECTORY": "目錄",
  "DIRECTORY_TITLE": "目錄",
  "DIRECTORY_NAMES_LEDE": "目錄名稱",
  "FILENAMES_LEDE": "檔案名稱",
  "FILENAME": "檔案名稱",
  "DIRECTORY_NAME": "目錄名稱",
  "ERROR_LOADING_PROJECT": "無法載入專案",
  "OPEN_DIALOG_ERROR": "顯示開啟檔案對話框時發生錯誤。 (錯誤 {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "載入 <span class='dialog-filename'>{0}</span> 目錄時發生錯誤。 (錯誤 {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "讀取 <span class='dialog-filename'>{0}</span> 目錄中的內容時發生錯誤。 (錯誤 {1})",
  "ZOOM_WITH_SHORTCUTS": "使用鍵盤快速鍵縮放",
  "ZOOM_WITH_SHORTCUTS_DETAILS": "請使用鍵盤快速鍵 <code><i>{0}</i></code> 放大，以及 <code><i>{1}</i></code> 縮小。",
  "ERROR_OPENING_FILE_TITLE": "無法開啟檔案",
  "ERROR_OPENING_FILE": "開啟 <span class='dialog-filename'>{0}</span> 檔案時發生錯誤。 {1}",
  "ERROR_OPENING_FILES": "開啟下列檔案時發生錯誤:",
  "ERROR_RELOADING_FILE_TITLE": "無法從磁碟重新載入變更",
  "ERROR_RELOADING_FILE": "重新載入 <span class='dialog-filename'>{0}</span> 檔案時發生錯誤。 {1}",
  "ERROR_SAVING_FILE_TITLE": "無法儲存檔案",
  "ERROR_SAVING_FILE": "儲存 <span class='dialog-filename'>{0}</span> 檔案時發生錯誤。 {1}",
  "ERROR_RENAMING_FILE_TITLE": "無法將{0}重新命名",
  "ERROR_RENAMING_FILE": "重新命名{2} <span class='dialog-filename'>{0}</span> 時發生錯誤。 {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "該檔案或目錄不是目前開啟專案的一部分。很抱歉，目前只能重新命名專案檔案。",
  "ERROR_MOVING_FILE_TITLE": "移動 {0} 時發生錯誤",
  "ERROR_MOVING_FILE": "嘗試移動 {2} <span class='dialog-filename'>{0}</span> 時發生錯誤。{1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "無法移動檔案／資料夾，因為它們不是目前專案的一部分。",
  "ERROR_DELETING_FILE_TITLE": "無法刪除{0}",
  "ERROR_DELETING_FILE": "刪除{2} <span class='dialog-filename'>{0}</span> 時發生錯誤。 {1}",
  "INVALID_FILENAME_TITLE": "{0}無效",
  "CANNOT_PASTE_TITLE": "無法貼上 {0}",
  "CANNOT_DOWNLOAD_TITLE": "無法下載 {0}",
  "ERR_TYPE_DOWNLOAD_FAILED": "下載 <span class='dialog-filename'>{0}</span> 時發生錯誤",
  "ERR_TYPE_PASTE_FAILED": "將 <span class='dialog-filename'>{0}</span> 貼到 <span class='dialog-filename'>{1}</span> 時發生錯誤",
  "CANNOT_DUPLICATE_TITLE": "無法複製",
  "ERR_TYPE_DUPLICATE_FAILED": "複製 <span class='dialog-filename'>{0}</span> 時發生錯誤",
  "ERR_TYPE_DUPLICATE_FAILED_NO_FILE": "請選擇要複製的檔案。",
  "INVALID_FILENAME_MESSAGE": "{0}當中不能包含任何的系統保留字、結尾不能是半型句點 (.)，也不能使用下列字元: <code class='emphasized'>{1}</code>",
  "ENTRY_WITH_SAME_NAME_EXISTS": "已經有叫做 <span class='dialog-filename'>{0}</span> 的檔案或目錄了。",
  "ERROR_CREATING_FILE_TITLE": "無法建立{0}",
  "ERROR_CREATING_FILE": "建立{0} <span class='dialog-filename'>{1}</span> 時發生錯誤。 {2}",
  "ERROR_MIXED_DRAGDROP": "開啟其他檔案的同時不能開啟資料夾。",
  "DROP_TO_OPEN_FILES": "拖曳至此以開啟檔案",
  "DROP_TO_OPEN_FILE": "拖曳至此以開啟檔案",
  "DROP_TO_OPEN_PROJECT": "拖曳至此以將資料夾 `{0}` 作為專案開啟",
  "ERROR_KEYMAP_TITLE": "無法讀取使用者按鍵對應資料",
  "ERROR_KEYMAP_CORRUPT": "您的按鍵對應檔內容不是正確的 JSON 格式。將開啟該檔以便您修正格式問題。",
  "ERROR_LOADING_KEYMAP": "您的按鍵對應檔不是正確的 UTF-8 編碼文字檔，無法載入",
  "ERROR_RESTRICTED_COMMANDS": "您無法重新定義下列指令的快捷鍵: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "您無法重新定義快捷鍵: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "您定義了超過一組快捷鍵給下列指令: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "您定義了超過一種按鍵組合給下列快捷鍵: {0}",
  "ERROR_INVALID_SHORTCUTS": "下列快捷鍵無效: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "您定義了快捷鍵給不存在的指令: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "讀取喜好設定時發生錯誤",
  "ERROR_PREFS_RESET_TITLE": "設定已重設 - 需要重新啟動",
  "ERROR_PREFS_PROJECT_LINT": "專案偏好設定",
  "ERROR_PREFS_PROJECT_LINT_MESSAGE": "錯誤：專案同時包含 `.brackets.json` 和 `.phcode.json` 檔案，造成衝突。請刪除 `.brackets.json` 或 `.phcode.json` 檔案，然後重新載入專案。",
  "ERROR_PREFS_CORRUPT": "您的喜好設定檔內容不是正確的 JSON 格式。將開啟該檔以便您修正格式問題。 重新啟動 {APP_NAME} 後異動才會生效。",
  "ERROR_PREFS_CORRUPT_RESET": "您的 {APP_NAME} 設定已損毀，並且已經被重設。請重新啟動 {APP_NAME} 才能使變更生效。",
  "ERROR_PROJ_PREFS_CORRUPT": "您的專案喜好設定檔內容不是正確的 JSON 格式。將開啟該檔以便您修正格式問題。 重新啟動 {APP_NAME} 後異動才會生效。",
  "ERROR_IN_BROWSER_TITLE": "不妙! {APP_NAME} 還不能在瀏覽器裡跑。",
  "ERROR_IN_BROWSER": "{APP_NAME} 是以 HTML 打造，不過要以應用程式的方式執行才能編輯電腦上的檔案。請透過 <b>github.com/adobe/brackets-shell</b> 儲存庫中的應用程式介面來執行 {APP_NAME}。",
  "ERROR_MAX_FILES_TITLE": "無法建立檔案索引",
  "ERROR_MAX_FILES": "專案超過 30,000 個檔案。需要跨檔案執行的功能可能會被關閉或是變成跟專案內沒有任何檔案一樣。<a href='https://github.com/adobe/brackets/wiki/Large-Projects'>了解怎麼處理大型專案</a>。",
  "UNSUPPORTED_DOM_APIS_CONFIRM": "在 {APP_NAME} 的嵌入式即時預覽中無法使用 `window.confirm` 和 `window.prompt` API。請彈出即時預覽，以便在瀏覽器中使用這些 API。",
  "ERROR_LAUNCHING_BROWSER_TITLE": "無法啟動瀏覽器",
  "ERROR_CANT_FIND_CHROME": "找不到 Google Chrome 瀏覽器。請確定您有安裝。",
  "ERROR_LAUNCHING_BROWSER": "啟動瀏覽器時發生錯誤。 (錯誤 {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "即時預覽錯誤",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "正在連到瀏覽器",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "為了讓即時預覽功能順利連線，需要重新啟動 Chrome 並開啟遠端除錯功能。<br /><br />您是否要重新啟動 Chrome 並啟用遠端除錯功能?<br /><br />",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "無法載入即時預覽頁。",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "您需要指定專案的 URL 根位址，才能啟動包含伺服器端資源的即時預覽功能。",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "無法啟動即時預覽用的 HTTP 伺服器。請再試一次。",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "想了解更多，請參考<a href='{0}' title='{0}'>即時預覽連結錯誤排解</a>。",
  "LIVE_PREVIEW_HIDE_OVERLAY": "隱藏此訊息",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "即時預覽",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "即時預覽: 連線中…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "即時預覽: 初始化中…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "即時預覽伺服器已啟動",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "即時預覽",
  "LIVE_DEV_TOOLTIP_SHOW_IN_EDITOR": "{0} - 在編輯器中顯示…",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "選取要即時預覽的檔案",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "重新載入頁面",
  "LIVE_DEV_TOGGLE_LIVE_HIGHLIGHT": "切換即時預覽醒目提示",
  "LIVE_DEV_CLICK_POPOUT": "將即時預覽彈出至新視窗",
  "LIVE_DEV_OPEN_CHROME": "在 Chrome 中開啟…",
  "LIVE_DEV_OPEN_SAFARI": "在 Safari 中開啟…",
  "LIVE_DEV_OPEN_EDGE": "在 Edge 中開啟…",
  "LIVE_DEV_OPEN_FIREFOX": "在 Firefox 中開啟…",
  "LIVE_DEV_OPEN_ERROR_TITLE": "在 {0} 中開啟即時預覽時發生錯誤",
  "LIVE_DEV_OPEN_ERROR_MESSAGE": "請確認已安裝 {0} 瀏覽器，然後再試一次。",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "釘選或取消釘選預覽頁面",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "即時預覽 (語法錯誤，不更新)",
  "LIVE_DEV_SETTINGS": "即時預覽設定…",
  "LIVE_DEV_SETTINGS_BANNER": "設定自訂伺服器以即時預覽 `<b>{0}</b>` 和其他伺服器呈現的檔案（PHP、JSP 等）",
  "LIVE_DEV_SETTINGS_TITLE": "即時預覽設定",
  "LIVE_DEV_SETTINGS_STARTUP": "啟動時顯示即時預覽面板",
  "LIVE_DEV_SETTINGS_SERVER_PREFERENCE": "設為 true 以啟用自訂開發伺服器",
  "LIVE_DEV_SETTINGS_STARTUP_PREFERENCE": "設為 true 以在啟動時顯示即時預覽面板",
  "LIVE_DEV_SETTINGS_HOT_RELOAD_PREFERENCE": "如果伺服器支援熱重載並停用儲存時即時預覽的重新載入，則設為 true",
  "LIVE_DEV_SETTINGS_USE_SERVER": "對此專案使用自訂開發伺服器",
  "LIVE_DEV_SETTINGS_SERVE_PREFERENCE": "您專案的開發伺服器網址，例如：http://localhost:8000/php",
  "LIVE_DEV_SETTINGS_SERVER_INBUILT": "例如：http://localhost:8000/php - 目前使用內建伺服器。",
  "LIVE_DEV_SETTINGS_SERVER_ROOT": "專案中的服務資料夾",
  "LIVE_DEV_SETTINGS_SERVER_ROOT_HELP": "例如：www/ （預設為 /）",
  "LIVE_DEV_SETTINGS_SERVER_ROOT_PREF": "專案中由開發伺服器服務的路徑，例如：www/ （預設為 /）",
  "LIVE_DEV_SETTINGS_RELOAD": "伺服器支援熱重載",
  "LIVE_DEV_SETTINGS_RELOAD_HELP": "部分伺服器支援熱重載，程式碼變更會推送至頁面而無需重新載入整個頁面。如果您不希望 {APP_NAME} 在每次儲存時都重新載入頁面，請啟用此功能。",
  "LIVE_DEV_SETTINGS_FRAMEWORK": "伺服器框架",
  "LIVE_DEV_SETTINGS_FRAMEWORK_CUSTOM": "自訂",
  "LIVE_DEV_SETTINGS_FRAMEWORK_PREFERENCES": "伺服器框架，目前僅支援 Docusaurus",
  "LIVE_DEV_SETTINGS_ELEMENT_HIGHLIGHT_PREFERENCE": "在「即時預覽」中，透過「懸停」或「點擊」檢查元素。預設為「懸停」",
  "LIVE_DEV_SETTINGS_SHOW_RULER_LINES_PREFERENCE": "在即時預覽中選取元素時顯示尺寸。預設為「false」",
  "LIVE_DEV_TOOLBOX_SELECT_PARENT": "選取父層",
  "LIVE_DEV_TOOLBOX_EDIT_TEXT": "編輯文字",
  "LIVE_DEV_TOOLBOX_EDIT_HYPERLINK": "編輯超連結",
  "LIVE_DEV_HYPERLINK_NO_HREF": "未設定 href",
  "LIVE_DEV_HYPERLINK_OPEN_LINK": "開啟此連結",
  "LIVE_DEV_HYPERLINK_OPENS_NEW_TAB": "於新分頁中開啟",
  "LIVE_DEV_TOOLBOX_DUPLICATE": "整行複製",
  "LIVE_DEV_TOOLBOX_DELETE": "刪除",
  "LIVE_DEV_TOOLBOX_AI": "使用 AI 編輯",
  "LIVE_DEV_TOOLBOX_IMAGE_GALLERY": "圖片庫",
  "LIVE_DEV_TOOLBOX_MORE_OPTIONS": "更多選項",
  "LIVE_DEV_MORE_OPTIONS_CUT": "剪下",
  "LIVE_DEV_MORE_OPTIONS_COPY": "複製",
  "LIVE_DEV_MORE_OPTIONS_PASTE": "貼上",
  "LIVE_DEV_IMAGE_GALLERY_USE_IMAGE": "下載圖片",
  "LIVE_DEV_IMAGE_GALLERY_SELECT_DOWNLOAD_FOLDER": "選擇圖片下載資料夾",
  "LIVE_DEV_IMAGE_GALLERY_SEARCH_PLACEHOLDER": "搜尋圖片…",
  "LIVE_DEV_IMAGE_GALLERY_SEARCH_BUTTON": "搜尋",
  "LIVE_DEV_IMAGE_GALLERY_LOADING_INITIAL": "正在載入圖片…",
  "LIVE_DEV_IMAGE_GALLERY_LOADING_MORE": "載入中…",
  "LIVE_DEV_IMAGE_GALLERY_NO_IMAGES": "找不到任何圖片",
  "LIVE_DEV_IMAGE_GALLERY_LOAD_ERROR": "載入圖片失敗",
  "LIVE_DEV_IMAGE_GALLERY_SELECT_FROM_COMPUTER_TOOLTIP": "從您的裝置選取圖片",
  "LIVE_DEV_IMAGE_GALLERY_SELECT_FROM_COMPUTER": "從裝置選取",
  "LIVE_DEV_IMAGE_GALLERY_DIALOG_OVERLAY_MESSAGE": "請在編輯器中選取圖片下載位置以繼續",
  "LIVE_DEV_IMAGE_GALLERY_OFFLINE_BANNER": "沒有連線 - 正在離線模式下運作",
  "LIVE_DEV_IMAGE_GALLERY_OFFLINE_RETRY": "重試",
  "LIVE_DEV_IMAGE_GALLERY_CHECKING_CONNECTION": "正在檢查連線",
  "LIVE_DEV_IMAGE_GALLERY_STILL_OFFLINE": "仍處於離線狀態。請檢查您的網路連線。",
  "LIVE_DEV_IMAGE_GALLERY_SELECT_SIZE": "選取圖片尺寸",
  "LIVE_DEV_IMAGE_GALLERY_SIZE_THUMBNAIL": "縮圖",
  "LIVE_DEV_IMAGE_GALLERY_SIZE_XS": "頭像",
  "LIVE_DEV_IMAGE_GALLERY_SIZE_SM": "卡片",
  "LIVE_DEV_IMAGE_GALLERY_SIZE_MD": "內容",
  "LIVE_DEV_IMAGE_GALLERY_SIZE_REGULAR": "標準",
  "LIVE_DEV_IMAGE_GALLERY_SIZE_LG": "主視覺",
  "LIVE_DEV_IMAGE_GALLERY_SIZE_XL": "橫幅",
  "LIVE_DEV_IMAGE_GALLERY_SIZE_RETINA": "視網膜",
  "LIVE_DEV_IMAGE_GALLERY_ATTRIBUTION_ON": "於 {0}",
  "LIVE_DEV_IMAGE_GALLERY_GET_PRO": "取得專業版",
  "LIVE_DEV_IMAGE_GALLERY_USAGE_THRESHOLD": "您已使用 {0}% 的免費圖片搜尋次數 ({1}/{2})",
  "LIVE_DEV_STYLES_PANEL_HEADER": "樣式編輯器",
  "LIVE_DEV_STYLES_EDIT_TOOLTIP": "編輯樣式",
  "LIVE_DEV_STYLES_PANEL_ADD": "+ 新增",
  "LIVE_DEV_STYLES_PANEL_NO_RULES": "找不到 CSS 規則",
  "LIVE_DEV_STYLES_PANEL_MATCHING_RULES": "相符規則 ({0})",
  "LIVE_DEV_STYLES_PANEL_LOADING": "正在載入樣式…",
  "LIVE_DEV_STYLES_PANEL_NO_STYLES": "找不到任何樣式",
  "LIVE_DEV_STYLES_PANEL_PROPERTY_PLACEHOLDER": "屬性",
  "LIVE_DEV_STYLES_PANEL_VALUE_PLACEHOLDER": "值",
  "LIVE_DEV_TOAST_NOT_EDITABLE": "元素不可編輯 - 由指令碼產生",
  "LIVE_DEV_COPY_TOAST_MESSAGE": "元素已複製。使用「貼上」即可將其新增至所選元素之後。",
  "LIVE_DEV_TOAST_FIXED_ELEMENT_DISMISSED": "元素不會隨頁面捲動 - 編輯方塊已隱藏",
  "LIVE_DEV_IMAGE_FOLDER_DIALOG_TITLE": "選取儲存圖片的資料夾",
  "LIVE_DEV_IMAGE_FOLDER_DIALOG_DESCRIPTION": "選擇要下載圖片的位置：",
  "LIVE_DEV_IMAGE_FOLDER_DIALOG_PLACEHOLDER": "輸入資料夾路徑 (例如：assets/images/)",
  "LIVE_DEV_IMAGE_FOLDER_DIALOG_HELP": "💡 輸入資料夾路徑，或留空以將檔案下載至 'images' 資料夾。",
  "LIVE_DEV_IMAGE_FOLDER_DIALOG_REMEMBER": "針對此專案不再詢問",
  "DEVICE_SIZE_LIMIT_TITLE": "響應式預覽次數已達上限",
  "DEVICE_SIZE_LIMIT_MESSAGE": "免費帳號每日的響應式預覽次數有限。升級至 Phoenix Pro，即可在所有裝置尺寸上無限次使用響應式預覽。",
  "IMAGE_SEARCH_LIMIT_TITLE": "圖片搜尋已達上限",
  "IMAGE_SEARCH_LIMIT_MESSAGE": "您已用完本月的 {0} 次圖片搜尋。<br>升級至付費 Phoenix Pro 方案，即可移除試用限制並繼續搜尋。",
  "IMAGE_SEARCH_LIMIT_MESSAGE_THROTTLE": "因需求量過高，圖片搜尋功能暫時無法使用。<br>升級至付費 Phoenix Pro 方案，即可移除試用限制並繼續搜尋。",
  "IMAGE_SEARCH_PRO_THROTTLE_TITLE": "圖片搜尋上限已達",
  "IMAGE_SEARCH_PRO_THROTTLE_MESSAGE": "因需求量過高，圖片搜尋功能暫時無法使用。此狀況通常會在一小時內排除 — 請稍後再試。",
  "LIVE_DEV_AI_PROMPT_PLACEHOLDER": "讓 Phoenix AI 修改此元素…",
  "LIVE_PREVIEW_CUSTOM_SERVER_BANNER": "從您的自訂伺服器 {0} 取得預覽",
  "LIVE_PREVIEW_MODE_TOGGLE_PREVIEW": "切換預覽模式 (F8)",
  "LIVE_PREVIEW_MODE_PREVIEW": "預覽模式",
  "LIVE_PREVIEW_MODE_HIGHLIGHT": "醒目提示模式",
  "LIVE_PREVIEW_MODE_EDIT": "編輯模式",
  "LIVE_PREVIEW_EDIT_HIGHLIGHT_ON": "懸停時檢查元素",
  "LIVE_PREVIEW_SHOW_RULER_LINES": "顯示度量",
  "LIVE_PREVIEW_MODE_PREFERENCE": "「{0}」僅顯示網頁，「{1}」會將網頁與您的程式碼連結——點擊元素即可跳至其程式碼，反之亦然，「{2}」提供反白顯示以及進階的元素操作功能。",
  "LIVE_PREVIEW_CONFIGURE_MODES": "設定即時預覽模式",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "已取消即時預覽，因為開發者工具被打開了",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "已取消即時預覽，因為頁面被關掉了",
  "LIVE_DEV_NAVIGATED_AWAY": "已取消即時預覽，因為您連到專案外的頁面了",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "即時預覽因為不明的錯誤而取消 ({0})",
  "SAVE_CLOSE_TITLE": "儲存變更",
  "SAVE_CLOSE_MESSAGE": "您想要儲存 <span class='dialog-filename'>{0}</span> 檔案的變更嗎?",
  "SAVE_CLOSE_MULTI_MESSAGE": "您想要儲存下列檔案的變更嗎?",
  "EXT_MODIFIED_TITLE": "外部變更",
  "CONFIRM_DELETE_TITLE": "確定刪除",
  "CONFIRM_FILE_DELETE": "您確定要刪除檔案 <span class='dialog-filename'>{0}</span> 嗎？",
  "CONFIRM_FOLDER_DELETE": "您確定要刪除 <span class='dialog-filename'>{0}</span> 資料夾嗎?",
  "CONFIRM_FILE_DELETE_TRASH": "您確定要刪除檔案 <span class='dialog-filename'>{0}</span> 嗎？<br>您可以從垃圾桶還原此檔案。",
  "CONFIRM_FOLDER_DELETE_TRASH": "您確定要刪除資料夾 <span class='dialog-filename'>{0}</span> 嗎？<br>您可以從垃圾桶還原此資料夾。",
  "CONFIRM_FILE_DELETE_RECYCLE_BIN": "您確定要刪除檔案 <span class='dialog-filename'>{0}</span> 嗎？<br>您可以從資源回收筒還原此檔案。",
  "CONFIRM_FOLDER_DELETE_RECYCLE_BIN": "您確定要刪除資料夾 <span class='dialog-filename'>{0}</span> 嗎？<br>您可以從資源回收筒還原此資料夾。",
  "MOVE_TO_TRASH": "移至垃圾桶",
  "MOVE_TO_RECYCLE_BIN": "移至資源回收筒",
  "FILE_DELETED_TITLE": "檔案已刪除",
  "EXT_MODIFIED_WARNING": "<span class='dialog-filename'>{0}</span> 在 {APP_NAME} 外被修改過了。<br /><br />您想要儲存檔案並覆寫蓋掉外部的變更嗎?",
  "EXT_MODIFIED_MESSAGE": "<span class='dialog-filename'>{0}</span> 在 {APP_NAME} 外被修改過了，但在 {APP_NAME} 中也有還沒儲存的變更。<br /><br />您想保留哪個版本呢?",
  "EXT_DELETED_MESSAGE": "<span class='dialog-filename'>{0}</span> 在 {APP_NAME} 外被刪除了，但在 {APP_NAME} 中還有沒儲存的變更。<br /><br />想要保留您變更的內容嗎?",
  "EXT_ALWAYS_MODIFIED_BUTTON_TOOLTIP": "在專案切換或重新啟動前，一律覆寫檔案",
  "WINDOW_UNLOAD_WARNING": "您確定要瀏覽至不同的網址並離開 {APP_NAME} 嗎？",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "您有未儲存的變更！您確定要瀏覽至不同的網址並離開 {APP_NAME} 嗎？",
  "DONE": "完成",
  "OK": "確定",
  "CANCEL": "取消",
  "DONT_SAVE": "不要儲存",
  "SAVE": "儲存",
  "SAVE_AS": "另存新檔…",
  "SAVE_AND_OVERWRITE": "覆寫",
  "ALWAYS_OVERWRITE": "一律覆寫",
  "DELETE": "刪除",
  "BUTTON_YES": "是",
  "BUTTON_NO": "否",
  "FIND_MATCH_INDEX": "{0} / {1}",
  "FIND_NO_RESULTS": "沒有結果",
  "FIND_QUERY_PLACEHOLDER": "尋找…",
  "FIND_HISTORY_MAX_COUNT": "搜尋歷程記錄中搜尋項目的最大數量",
  "REPLACE_PLACEHOLDER": "取代成…",
  "BUTTON_REPLACE_ALL": "批次…",
  "BUTTON_REPLACE_BATCH": "批次…",
  "BUTTON_REPLACE_ALL_IN_FILES": "取代…",
  "BUTTON_REPLACE": "取代",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "下一筆符合",
  "BUTTON_PREV_HINT": "上一筆符合",
  "BUTTON_CASESENSITIVE_HINT": "大小寫須相符",
  "BUTTON_REGEXP_HINT": "正規表示式",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "直接取代，不用復原",
  "REPLACE_WITHOUT_UNDO_WARNING": "有超過 {0} 個檔案會被變更，{APP_NAME} 會修改到磁碟上沒被開啟的檔案。<br />這些檔案內容取代後無法再復原。",
  "BUTTON_REPLACE_WITHOUT_UNDO": "直接取代，不用復原",
  "OPEN_FILE": "開啟檔案",
  "SAVE_FILE_AS": "儲存檔案",
  "CHOOSE_FOLDER": "選取資料夾",
  "RELEASE_NOTES": "版本資訊",
  "NO_UPDATE_TITLE": "已經是最新版!",
  "NO_UPDATE_MESSAGE": "您的 {APP_NAME} 已經是最新版。",
  "FIND_REPLACE_TITLE_LABEL": "取代",
  "FIND_REPLACE_TITLE_WITH": "取代成",
  "FIND_TITLE_LABEL": "找到",
  "FIND_TITLE_SUMMARY": "&mdash; {3}中共有{0} {1} 筆{2}",
  "FIND_NUM_FILES": "{0} 個{1}",
  "FIND_IN_FILES_SCOPED": "在 <span class='dialog-filename'>{0}</span> 中",
  "FIND_IN_FILES_NO_SCOPE": "在專案中",
  "FIND_IN_FILES_PROJECT_SCOPE": "在專案中尋找",
  "FIND_IN_FILES_PROJECT_SCOPE_FILTER": "在 {0} 中尋找",
  "FIND_IN_FILES_PROJECT_SCOPE_REPLACE": "在專案中取代",
  "FIND_IN_FILES_PROJECT_SCOPE_REPLACE_FILTER": "在 {0} 中取代",
  "FIND_IN_FILES_ZERO_FILES": "篩選條件排除了{0}的所有檔案",
  "FIND_IN_FILES_FILE": "檔案",
  "FIND_IN_FILES_FILES": "檔案",
  "FIND_IN_FILES_MATCH": "符合",
  "FIND_IN_FILES_MATCHES": "符合",
  "FIND_IN_FILES_MORE_THAN": "超過",
  "FIND_IN_FILES_PAGING": "{0}&mdash;{1}",
  "FIND_IN_FILES_FILE_PATH": "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "按住 Ctrl/Cmd 再用滑鼠點一下可以全部展開/收合",
  "FIND_IN_FILES_INDEXING": "正在建立即時搜尋索引…",
  "FIND_IN_FILES_SEARCHING": "正在搜尋檔案…",
  "FIND_IN_FILES_SEARCHING_IN": "在 {0} 中",
  "FIND_IN_FILES_INDEXING_PROGRESS": "正在為 {1} 個檔案中的 {0} 個檔案建立即時搜尋索引…",
  "REPLACE_IN_FILES_ERRORS_TITLE": "取代錯誤",
  "REPLACE_IN_FILES_ERRORS": "下列檔案沒有被修改，可能是搜尋後又被變更或是無法寫入。",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "無法取得更新資訊",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "由伺服器取得更新資訊時發生錯誤。請確定您已連線到 Internet 後再重試一次。",
  "NEW_FILE_FILTER": "新增排除集…",
  "CLEAR_FILE_FILTER": "不要排除檔案",
  "NO_FILE_FILTER": "沒有檔案被排除",
  "EXCLUDE_FILE_FILTER": "排除檔案",
  "INCLUDE_FILE_FILTER": "在檔案中搜尋",
  "FILTER_PLACEHOLDER": "例如：index,.css,*.js,src/**/*.css",
  "FILTER_HISTORY_TOOLTIP": "按 `Ctrl-Space` 檢視歷程記錄。",
  "FILTER_HISTORY_TOOLTIP_MAC": "按下 `Cmd-Space` 檢視歷史記錄。",
  "FIND_HISTORY_TOOLTIP": "按下 `Ctrl-Space` 檢視歷史記錄。",
  "FIND_HISTORY_TOOLTIP_MAC": "按下 `Cmd-Space` 檢視歷史記錄。",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "游標所在位置沒有相關的快速編輯功能",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "CSS 快速編輯: 將游標放在單一 class 名稱上",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "CSS 快速編輯: class 屬性不完整",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "CSS 快速編輯: id 屬性不完整",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "CSS 快速編輯: 將游標放在標籤名稱、class 或 id 上",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "CSS 計時函式快速編輯: 語法無效",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "JS 快速編輯: 將游標放在函式名稱上",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "游標所在位置沒有相關的快速文件",
  "PROJECT_LOADING": "載入中…",
  "UNTITLED": "未命名",
  "WORKING_FILES": "工作檔案",
  "TOP": "上方",
  "BOTTOM": "下方",
  "LEFT": "左側",
  "RIGHT": "右側",
  "CMD_SPLITVIEW_NONE": "不分割",
  "CMD_SPLITVIEW_VERTICAL": "左右分割",
  "CMD_SPLITVIEW_HORIZONTAL": "上下分割",
  "SPLITVIEW_MENU_TOOLTIP": "將編輯器分割成上下或左右兩塊",
  "GEAR_MENU_TOOLTIP": "設定工作檔案",
  "CMD_TOGGLE_SHOW_WORKING_SET": "顯示工作檔案",
  "CMD_TOGGLE_SHOW_FILE_TABS": "顯示檔案標籤列",
  "SPLITVIEW_INFO_TITLE": "已經開啟",
  "SPLITVIEW_MULTIPANE_WARNING": "檔案已經在另一個窗格中開啟。{APP_NAME} 很快就會支援在多個窗格中開啟相同的檔案。在那之前，檔案還是會在原本已開啟的窗格中顯示。<br /><br />(您只會看到一次這個訊息。)",
  "KEYBOARD_OVERLAY_TEXT": "使用方向鍵導覽，或輸入文字以選取 UI 元素。",
  "KEYBOARD_SHORTCUT_CHANGE_TITLE": "變更鍵盤快速鍵…",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_TITLE": "變更鍵盤快速鍵",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_TEXT": "請按下<b>「{0}」</b>的新鍵盤組合鍵 (目前：<b>{1}</b>)",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_DUPLICATE": "警告：鍵盤組合鍵<b>{0}</b> 已指派給<b>「{1}」</b>。要重新指派給<b>「{2}」</b>嗎？",
  "KEYBOARD_SHORTCUT_ASSIGN": "指派",
  "KEYBOARD_SHORTCUT_NONE": "無",
  "KEYBOARD_SHORTCUT_MENU_SHOW_SHORTCUTS": "鍵盤快速鍵…",
  "KEYBOARD_SHORTCUT_MENU_SHOW_SHORTCUTS_BUTTON": "顯示所有快速鍵…",
  "KEYBOARD_SHORTCUT_TABLE_BASE_KEY": "主要按鍵",
  "KEYBOARD_SHORTCUT_TABLE_KEY_BINDING": "快速鍵",
  "KEYBOARD_SHORTCUT_TABLE_COMMAND_ID": "指令 ID",
  "KEYBOARD_SHORTCUT_TABLE_COMMAND_NAME": "指令",
  "KEYBOARD_SHORTCUT_TABLE_DOUBLE_CLICK": "雙擊以更改快速鍵",
  "KEYBOARD_SHORTCUT_TABLE_ORIGIN": "來源",
  "KEYBOARD_SHORTCUT_ORIG_EXTENSION": "擴充功能",
  "KEYBOARD_SHORTCUT_PANEL_TITLE": "鍵盤快速鍵",
  "KEYBOARD_SHORTCUT_PRESET_TOOLTIP": "使用 VSCode、WebStorm 或 Sublime Text 等編輯器的鍵盤快捷鍵",
  "KEYBOARD_SHORTCUT_PRESET_SELECT": "選擇快捷鍵預設集",
  "KEYBOARD_SHORTCUT_PRESET_USING": "使用 {0}",
  "DEFAULT": "預設",
  "KEYBOARD_SHORTCUT_PANEL_FILTER": "篩選(&hellip;)",
  "KEYBOARD_SHORTCUT_PANEL_RESET": "重設(&hellip;)",
  "KEYBOARD_SHORTCUT_PANEL_RESET_DEFAULT": "重設為預設快捷鍵(&hellip;)",
  "KEYBOARD_SHORTCUT_RESET_DIALOG_TITLE": "重設鍵盤快捷鍵",
  "KEYBOARD_SHORTCUT_RESET_DIALOG_MESSAGE": "要將所有自訂快捷鍵重設為預設值嗎？此動作無法復原。",
  "KEYBOARD_SHORTCUT_SRC_USER": "使用者自訂",
  "KEYBOARD_SHORTCUT_SRC_PRESET": "{0} 預設集",
  "STATUSBAR_CURSOR_POSITION": "第 {0} 行，第 {1} 個字元",
  "STATUSBAR_CURSOR_POSITION_SHORT": "{0}：{1}",
  "STATUSBAR_CURSOR_GOTO": "點擊以跳至另一行",
  "STATUSBAR_SELECTION_CH_SINGULAR": " — 選了 {0} 個字元",
  "STATUSBAR_SELECTION_CH_PLURAL": " — 選了 {0} 個字元",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " — 選了 {0} 行",
  "STATUSBAR_SELECTION_LINE_PLURAL": " — 選了 {0} 行",
  "STATUSBAR_SELECTION_MULTIPLE": "— {0} 個多重游標選取範圍",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "點一下切換成使用空白字元縮排",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "點一下切換成使用 Tab 縮排",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "點一下變更縮排用的空白字元數",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "點一下變更 Tab 字元所代表的長度",
  "STATUSBAR_SPACES": "空白字元:",
  "STATUSBAR_TAB_SIZE": "Tab 長度:",
  "STATUSBAR_AUTO_INDENT": "<span title='點擊以切換為固定縮排。目前設定為根據目前檔案自動偵測並套用縮排。'>自動</span>",
  "STATUSBAR_FIXED_INDENT": "<span title='點擊以切換為自動縮排偵測。目前設定為固定縮排。'>固定</span>",
  "STATUSBAR_LINE_COUNT_SINGULAR": "— {0} 行",
  "STATUSBAR_LINE_COUNT_PLURAL": "— {0} 行",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "已停用擴充功能",
  "STATUSBAR_INSERT": "INS",
  "STATUSBAR_OVERWRITE": "OVR",
  "STATUSBAR_INSOVR_TOOLTIP": "按一下可以在插入 (INS) 與覆寫 (OVR) 模式中切換",
  "STATUSBAR_LANG_TOOLTIP": "按一下可以變更檔案類型",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}。按一下可以開啟或關閉報告面板。",
  "STATUSBAR_DEFAULT_LANG": "(預設)",
  "STATUSBAR_SET_DEFAULT_LANG": "設定成 .{0} 檔的預設值",
  "STATUSBAR_ENCODING_TOOLTIP": "選取編碼",
  "STATUSBAR_TASKS": "工作",
  "STATUSBAR_TASKS_TOOLTIP": "管理執行中的工作",
  "STATUSBAR_TASKS_HIDE_SPINNER": "隱藏旋轉圖示",
  "STATUSBAR_TASKS_UNKNOWN_EXTENSION_TASK": "未知的擴充功能工作…",
  "STATUSBAR_TASKS_PLAY": "開始或繼續",
  "STATUSBAR_TASKS_PAUSE": "暫停",
  "STATUSBAR_TASKS_STOP": "停止",
  "STATUSBAR_TASKS_RESTART": "重新啟動",
  "CLOSE_TABS_TO_THE_RIGHT": "關閉右側分頁",
  "CLOSE_TABS_TO_THE_LEFT": "關閉左側分頁",
  "CLOSE_ALL_TABS": "關閉所有分頁",
  "CLOSE_SAVED_TABS": "關閉已儲存的索引標籤",
  "CLOSE_TAB_TOOLTIP": "關閉頁籤",
  "ERRORS_NO_FILE": "尚未開啟檔案",
  "ERRORS_PANEL_TITLE_MULTIPLE": "{0} 個問題 - {1}",
  "ERRORS_PANEL_TITLE_MULTIPLE_FIXABLE": "{0} 個問題，其中 {1} 個可修復 - {2}",
  "SINGLE_ERROR": "1 個{0}問題 - {1}",
  "SINGLE_ERROR_FIXABLE": "1 個{0}問題，可修復 - {2}",
  "MULTIPLE_ERRORS": "{0} {1} 個問題 - {2}",
  "MULTIPLE_ERRORS_FIXABLE": "{0} {1} 個問題，其中 {2} 個可修復 - {3}",
  "NO_ERRORS": "沒發現任何 {0} 問題，幹得好!",
  "NO_ERRORS_MULTIPLE_PROVIDER": "沒發現任何問題，幹得好!",
  "LINT_DISABLED": "已停用 Lint 功能",
  "NO_LINT_AVAILABLE": "沒有 {0} 適用的 Linter",
  "NOTHING_TO_LINT": "沒有東西好 Lint",
  "COPY_ERROR": "複製問題",
  "FIX": "修正",
  "CANNOT_FIX_TITLE": "無法套用修正",
  "CANNOT_FIX_SOME_TITLE": "無法套用部分修正",
  "CANNOT_FIX_MESSAGE": "文件自準備修正後已被修改。請再試一次。",
  "LINTER_TIMED_OUT": "{0} 等了 {1} 毫秒後逾時",
  "LINTER_FAILED": "{0} 已終止，錯誤: {1}",
  "CLICK_VIEW_PROBLEM": "點擊以在面板中檢視問題",
  "FILE_MENU": "檔案",
  "CMD_FILE_NEW_UNTITLED": "新增",
  "CMD_FILE_NEW": "新增檔案",
  "CMD_FILE_DUPLICATE": "整行複製",
  "CMD_FILE_DUPLICATE_FILE": "複製檔案",
  "CMD_FILE_DOWNLOAD_PROJECT": "下載專案",
  "CMD_FILE_DOWNLOAD": "下載",
  "CMD_FILE_CUT": "剪下",
  "CMD_FILE_COPY": "複製",
  "CMD_FILE_COPY_PATH": "複製路徑",
  "CMD_FILE_PASTE": "貼上",
  "CMD_PROJECT_NEW": "建立專案…",
  "CMD_FILE_NEW_FOLDER": "新增資料夾",
  "CMD_FILE_OPEN": "開啟檔案(&hellip;)",
  "CMD_RECENT_FILES_OPEN": "最近檔案(&hellip;)",
  "CMD_ADD_TO_WORKING_SET": "開啟進工作集",
  "CMD_OPEN_DROPPED_FILES": "開啟拖放的檔案",
  "CMD_OPEN_FOLDER": "開啟資料夾…",
  "CMD_FILE_CLOSE": "關閉",
  "CMD_FILE_CLOSE_ALL": "全部關閉",
  "CMD_REOPEN_CLOSED": "重新開啟已關閉的檔案",
  "CMD_FILE_CLOSE_LIST": "關閉清單",
  "CMD_FILE_CLOSE_OTHERS": "關閉其他檔案",
  "CMD_FILE_CLOSE_ABOVE": "關閉上列檔案",
  "CMD_FILE_CLOSE_BELOW": "關閉下列檔案",
  "CMD_FILE_SAVE": "儲存檔案",
  "CMD_FILE_SAVE_ALL": "全部儲存",
  "CMD_FILE_SAVE_AS": "另存新檔…",
  "CMD_LIVE_FILE_PREVIEW": "即時預覽",
  "CMD_LIVE_FILE_PREVIEW_SETTINGS": "即時預覽設定",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "啟用實驗版即時預覽",
  "CMD_RELOAD_LIVE_PREVIEW": "重新載入即時預覽",
  "CMD_PROJECT_SETTINGS": "專案設定…",
  "CMD_FILE_RENAME": "重新命名",
  "CMD_FILE_DELETE": "刪除",
  "CMD_INSTALL_EXTENSION": "安裝擴充功能…",
  "CMD_EXTENSION_MANAGER": "擴充功能管理員…",
  "CMD_FILE_REFRESH": "重新整理檔案樹",
  "CMD_FILE_SHOW_FOLDERS_FIRST": "資料夾優先排序",
  "CMD_QUIT": "結束",
  "CMD_OPEN_IN": "在(&I)…開啟",
  "CMD_EXIT": "結束",
  "EDIT_MENU": "編輯",
  "CMD_UNDO": "復原",
  "CMD_REDO": "取消復原",
  "CMD_CUT": "剪下",
  "CMD_COPY": "複製",
  "CMD_PASTE": "貼上",
  "CMD_SELECT_ALL": "全部選取",
  "CMD_SELECT_LINE": "整行選取",
  "CMD_SPLIT_SEL_INTO_LINES": "逐行切成多段選取區塊",
  "CMD_ADD_CUR_TO_NEXT_LINE": "在下一行加入游標",
  "CMD_ADD_CUR_TO_PREV_LINE": "在上一行加入游標",
  "CMD_INDENT": "縮排",
  "CMD_UNINDENT": "取消縮排",
  "CMD_DUPLICATE": "整行複製",
  "CMD_DELETE_LINES": "整行刪除",
  "CMD_COMMENT": "加入或取消行註解",
  "CMD_BLOCK_COMMENT": "加入或取消區塊註解",
  "CMD_LINE_UP": "整行上移",
  "CMD_LINE_DOWN": "整行下移",
  "CMD_OPEN_LINE_ABOVE": "往上新增一行",
  "CMD_OPEN_LINE_BELOW": "往下新增一行",
  "CMD_TOGGLE_CLOSE_BRACKETS": "自動插入右括號",
  "CMD_SHOW_CODE_HINTS": "顯示程式提示",
  "CMD_BEAUTIFY_CODE": "格式化程式碼",
  "CMD_BEAUTIFY_CODE_ON_SAVE": "儲存後格式化程式碼",
  "CMD_AUTO_RENAME_TAGS": "自動重新命名 HTML 標籤",
  "CMD_TOGGLE_EMMET": "Emmet (保留原文，因 Emmet 為專有名詞)",
  "FIND_MENU": "尋找",
  "CMD_FIND": "尋找",
  "CMD_FIND_NEXT": "找下一個",
  "CMD_FIND_PREVIOUS": "找上一個",
  "CMD_FIND_ALL_AND_SELECT": "選取所有出現項目",
  "CMD_ADD_NEXT_MATCH": "加入下一個符合項目",
  "CMD_SKIP_CURRENT_MATCH": "跳過並加入下一個符合項目",
  "CMD_FIND_IN_FILES": "在檔案中尋找",
  "CMD_FIND_IN_SUBTREE": "尋找…",
  "CMD_REPLACE": "取代",
  "CMD_REPLACE_IN_FILES": "在檔案中取代",
  "CMD_REPLACE_IN_SUBTREE": "取代…",
  "VIEW_MENU": "檢視",
  "CMD_HIDE_SIDEBAR": "隱藏側欄",
  "CMD_SHOW_SIDEBAR": "顯示側欄",
  "CMD_TOGGLE_SIDEBAR": "切換側邊欄",
  "CMD_TOGGLE_TABBAR": "檔案標籤列",
  "CMD_TOGGLE_PANELS": "切換面板",
  "CMD_TOGGLE_PURE_CODE": "專注模式",
  "CMD_TOGGLE_FULLSCREEN": "全螢幕",
  "CMD_ZOOM_UI": "調整介面與字體大小",
  "CMD_ZOOM_IN": "放大",
  "CMD_ZOOM_IN_SCALE": "放大 (目前：{0}%)",
  "CMD_ZOOM_OUT": "縮小",
  "CMD_INCREASE_FONT_SIZE": "放大字體",
  "CMD_DECREASE_FONT_SIZE": "縮小字體",
  "CMD_RESTORE_FONT_SIZE": "還原字體大小",
  "CMD_SCROLL_LINE_UP": "向上捲動一行",
  "CMD_SCROLL_LINE_DOWN": "向下捲動一行",
  "CMD_TOGGLE_LINE_NUMBERS": "行號",
  "CMD_TOGGLE_ACTIVE_LINE": "強調游標所在行",
  "CMD_TOGGLE_WORD_WRAP": "自動換行",
  "CMD_VIEW_TOGGLE_INSPECTION": "存檔時執行 Lint",
  "CMD_VIEW_TOGGLE_PROBLEMS": "問題",
  "CMD_WORKINGSET_SORT_BY_ADDED": "依加入先後排序",
  "CMD_WORKINGSET_SORT_BY_NAME": "依檔名排序",
  "CMD_WORKINGSET_SORT_BY_TYPE": "依類型排序",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "自動排序",
  "CMD_THEMES": "佈景主題…",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "自動關閉搜尋",
  "CMD_TOGGLE_RULERS": "尺規",
  "CMD_TOGGLE_INDENT_GUIDES": "縮排引導線",
  "CMD_KEYBOARD_NAV_OVERLAY": "視覺化指令面板",
  "NAVIGATE_MENU": "瀏覽",
  "CMD_QUICK_OPEN": "快速開啟",
  "CMD_GOTO_LINE": "到指定行",
  "CMD_GOTO_DEFINITION": "快速尋找定義",
  "CMD_GOTO_DEFINITION_PROJECT": "在專案中快速尋找定義",
  "CMD_GOTO_FIRST_PROBLEM": "到第一筆問題",
  "CMD_GOTO_NEXT_PROBLEM": "前往下一個問題",
  "CMD_GOTO_PREV_PROBLEM": "前往上一個問題",
  "CMD_TOGGLE_QUICK_EDIT": "快速編輯",
  "CMD_TOGGLE_QUICK_DOCS": "快速文件",
  "CMD_QUICK_EDIT_PREV_MATCH": "上一個快速編輯項目",
  "CMD_QUICK_EDIT_NEXT_MATCH": "下一個快速編輯項目",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "新增規則",
  "CMD_NEXT_DOC": "下一個檔案",
  "CMD_PREV_DOC": "上一個檔案",
  "CMD_NAVIGATE_BACKWARD": "向後導覽",
  "CMD_NAVIGATE_FORWARD": "向前導覽",
  "CMD_NEXT_DOC_LIST_ORDER": "清單中的下一個檔案",
  "CMD_PREV_DOC_LIST_ORDER": "清單中的上一個檔案",
  "CMD_SHOW_IN_TREE": "在檔案樹中顯示",
  "CMD_SHOW_IN_EXPLORER": "Windows 檔案總管",
  "CMD_SHOW_IN_FINDER": "在 Finder 中顯示",
  "CMD_SHOW_IN_FILE_MANAGER": "檔案總管",
  "CMD_OPEN_IN_CMD": "命令提示字元",
  "CMD_OPEN_IN_POWER_SHELL": "PowerShell",
  "CMD_OPEN_IN_DEFAULT_APP": "系統預設應用程式",
  "CMD_SWITCH_PANE_FOCUS": "切換窗格焦點",
  "CMD_OPEN_VFS": "開啟虛擬檔案系統",
  "CMD_DIAGNOSTIC_TOOLS": "{APP_NAME} 診斷工具",
  "CMD_EXPERIMENTAL_FEATURES": "實驗性功能",
  "CMD_ENABLE_DRAG_AND_DROP": "拖放檔案",
  "CMD_OPEN_EXTENSIONS_FOLDER": "開啟擴充功能資料夾…",
  "CMD_OPEN_VIRTUAL_SERVER": "開啟虛擬伺服器",
  "HELP_MENU": "說明",
  "CMD_CHECK_FOR_UPDATE": "檢查更新…",
  "CMD_AUTO_UPDATE": "自動更新",
  "CMD_HOW_TO_USE_BRACKETS": "如何使用 {APP_NAME}",
  "CMD_SUPPORT": "{APP_NAME} 支援",
  "CMD_GET_PRO": "取得 Phoenix Pro",
  "CMD_CANCEL_TRIAL": "取消 Phoenix Pro 試用",
  "CANCEL_TRIAL_TITLE": "要取消 {0} 試用嗎？",
  "CANCEL_TRIAL_MESSAGE": "您的 Phoenix Pro 試用期還剩下 {0} 天。取消後將無法復原。您確定要中止試用嗎？",
  "CANCEL_TRIAL_STOP_BTN": "中止試用",
  "CMD_VIEW_LICENSE": "檢視授權",
  "CMD_MANAGE_LICENSES": "管理授權",
  "CMD_USER_PROFILE": "{APP_NAME} 帳號",
  "CMD_DOCS": "說明、入門指南",
  "CMD_SUGGEST": "功能建議",
  "CMD_REPORT_ISSUE": "回報問題",
  "CMD_RELEASE_NOTES": "版本資訊",
  "CMD_GET_INVOLVED": "參與",
  "CMD_SHOW_EXTENSIONS_FOLDER": "顯示擴充功能資料夾",
  "CMD_HEALTH_DATA_STATISTICS": "健康報告…",
  "CMD_HOMEPAGE": "下載應用程式 - 首頁",
  "CMD_TWITTER": "Twitter {TWITTER_NAME} 專頁",
  "CMD_YOUTUBE": "YouTube 頻道",
  "CMD_ABOUT": "關於 {APP_TITLE}",
  "CMD_OPEN_PREFERENCES": "開啟喜好設定檔",
  "CMD_OPEN_KEYMAP": "開啟使用者快捷鍵映射檔",
  "EXPERIMENTAL_BUILD": "實驗建置",
  "RELEASE_BUILD": "建置",
  "DEVELOPMENT_BUILD": "開發建置",
  "PRERELEASE_BUILD": "預覽版本",
  "RELOAD_FROM_DISK": "從磁碟重新載入",
  "KEEP_CHANGES_IN_EDITOR": "在編輯器中保留變更",
  "CLOSE_DONT_SAVE": "關閉 (不要儲存)",
  "RELAUNCH_CHROME": "重新啟動 Chrome",
  "ABOUT": "關於",
  "CLOSE": "關閉",
  "ABOUT_TEXT_LINE1": "版本 {VERSION_MAJOR}.{VERSION_MINOR} {BUILD_TYPE} {VERSION}",
  "ABOUT_TEXT_BUILD_TIMESTAMP": "建置時間戳記：",
  "ABOUT_TEXT_PRO_BUILD": "Phoenix Pro 組建：",
  "ABOUT_RELEASE_CREDITS": "發行貢獻者：",
  "ABOUT_TEXT_LINE3": "我們使用的第三方函式庫 - <a href='https://github.com/phcode-dev/phoenix/tree/main/src/thirdparty/licences'> 授權與歸屬</a>。",
  "ABOUT_TEXT_LINE4": "文件和原始碼位於 <a href='https://github.com/phcode-dev/phoenix/'>https://github.com/phcode-dev/phoenix/</a>",
  "ABOUT_TEXT_LINE5": "以 ❤ 和 JavaScript 製作，作者：",
  "ABOUT_TEXT_LINE6": "許多人（但我們目前無法載入該資料）。",
  "ABOUT_TEXT_MDN_DOCS": "MDN 文件及 MDN 圖示皆以 Creative Commons Attribution 授權條款 <a href='{MDN_DOCS_LICENSE}'>CC-BY-SA 2.5 Unported</a> 授權。",
  "UPDATE_NOTIFICATION_TOOLTIP": "有新版的 {APP_NAME}! 點這裡了解詳情。",
  "UPDATE_NOT_AVAILABLE_TITLE": "{APP_NAME} 已為最新版本",
  "UPDATE_UP_TO_DATE": "您的 {APP_NAME} 已是最新版本！",
  "UPDATE_AVAILABLE_TITLE": "有新版",
  "UPDATE_WHATS_NEW": "{APP_NAME} 的新功能",
  "UPDATE_READY_RESTART_TITLE": "重新啟動應用程式以更新",
  "UPDATE_READY_RESTART_INSTALL_MESSAGE": "關閉所有已開啟的視窗後，{APP_NAME} 將會自動更新。",
  "UPDATE_FAILED_TITLE": "更新失敗",
  "UPDATE_INSTALLING": "安裝更新中…",
  "UPDATE_INSTALLING_MESSAGE": "更新安裝進行中：{APP_NAME} 目前正在安裝最新的更新。安裝完成後，應用程式將會自動關閉。",
  "UPDATE_FAILED_MESSAGE": "請關閉所有 {APP_NAME} 應用程式視窗，然後重新開啟應用程式以再次嘗試更新。<br/>您也可以從 <a href='https://phcode.io'>phcode.io</a> 下載安裝程式來安裝更新。",
  "UPDATE_FAILED_VISIT_SITE_MESSAGE": "若要重試，請結束所有 {APP_NAME} 執行個體，然後重新啟動應用程式。<br>您將很快被導向至我們的下載頁面，您可以在那裡手動下載最新版本。",
  "UPDATE_MESSAGE": "嗨! 新版的 {APP_NAME} 已經可以下載。新功能有:",
  "GET_IT_NOW": "馬上取得!",
  "UPDATE_ON_EXIT": "退出時更新",
  "UPDATE_LATER": "稍後提醒我",
  "UPDATE_DONE": "重新啟動以更新 {APP_NAME}",
  "UPDATE_RESTART_INSTALL": "重新啟動以安裝更新",
  "UPDATE_DOWNLOADING": "下載安裝程式",
  "INSTALL_WEBAPP": "在您的裝置上安裝 {APP_NAME}",
  "UPDATE_DOWNLOAD_PROGRESS": "下載中 - {0} / {1} MB",
  "UPDATING_APP": "更新 {APP_NAME} 中",
  "UPDATING_APP_MESSAGE": "這可能需要一些時間",
  "UPDATING_APP_DIALOG_MESSAGE": "更新進行中。您可以在我們升級的同時繼續使用 {APP_NAME}。",
  "PROJECT_SETTINGS_TITLE": "專案設定: {0}",
  "PROJECT_SETTING_BASE_URL": "即時預覽 URL 根位址",
  "PROJECT_SETTING_BASE_URL_HINT": "如果要用本機伺服器，可以輸入 http://localhost:8000/ 這類 URL",
  "BASEURL_ERROR_INVALID_PROTOCOL": "即時預覽功能不支援 {0} 協定&mdash;請使用 http: 或 https: 。",
  "BASEURL_ERROR_SEARCH_DISALLOWED": "URL 根位址不能有 \"{0}\" 這類搜尋參數。",
  "BASEURL_ERROR_HASH_DISALLOWED": "URL 根位址不能有半型井號 (#)，例如 \"{0}\"。",
  "BASEURL_ERROR_INVALID_CHAR": "'{0}' 這類特殊字元一定要用 % 格式編碼過。",
  "BASEURL_ERROR_UNKNOWN_ERROR": "解析 URL 根位址時發生不明錯誤",
  "EMPTY_VIEW_HEADER": "<em>選到本窗格後再開啟檔案</em>",
  "FLIPVIEW_BTN_TOOLTIP": "將此檢視翻轉至 {0} 窗格",
  "CURRENT_THEME": "目前的佈景主題",
  "GET_MORE_THEMES": "取得更多…",
  "USE_THEME_SCROLLBARS": "使用佈景主題的捲軸",
  "FONT_SIZE": "字體大小",
  "FONT_FAMILY": "字體",
  "FONT_LINE_HEIGHT": "行高",
  "SCROLL_SENSITIVITY": "捲動靈敏度",
  "THEMES_SETTINGS": "佈景主題設定",
  "THEMES_ERROR": "佈景主題錯誤",
  "THEMES_ERROR_CANNOT_APPLY": "因發生錯誤，無法套用佈景主題。",
  "BUTTON_NEW_RULE": "新增規則",
  "INSTALL": "安裝",
  "APPLY": "套用",
  "UPDATE": "更新",
  "REMOVE": "移除",
  "DISABLE": "停用",
  "ENABLE": "啟用",
  "OVERWRITE": "覆寫",
  "CANT_DROP_ZIP": "即將支援拖放 zip 檔案...",
  "CANT_REMOVE_DEV": "在 \"dev\" 資料夾中的擴充功能必需手動刪除。",
  "CANT_UPDATE": "這項更新不相容於這一版的 {APP_NAME}。",
  "CANT_UPDATE_DEV": "在 \"dev\" 資料夾中的擴充功能無法自動更新。",
  "INSTALL_EXTENSION_TITLE": "安裝擴充功能",
  "UPDATE_EXTENSION_TITLE": "更新擴充功能",
  "INSTALL_EXTENSION_LABEL": "擴充功能 URL",
  "INSTALL_EXTENSION_HINT": "擴充功能 zip 壓縮檔或是 GitHub 儲存庫的 URL",
  "INSTALLING_FROM": "由 {0} 安裝擴充功能中…",
  "INSTALL_SUCCEEDED": "安裝成功!",
  "INSTALL_FAILED": "安裝失敗。",
  "CANCELING_INSTALL": "取消中…",
  "CANCELING_HUNG": "取消安裝花太多時間。可能發生了內部錯誤。",
  "INSTALL_CANCELED": "安裝已取消。",
  "VIEW_COMPLETE_DESCRIPTION": "顯示完整描述資訊",
  "VIEW_TRUNCATED_DESCRIPTION": "只顯示部分描述資訊",
  "SORT_EXTENSION_METHOD": "使用下載次數或發佈日期排序擴充功能",
  "INVALID_ZIP_FILE": "下載的內容不是正確的 zip 壓縮檔。",
  "MISSING_PACKAGE_JSON": "套件缺少 package.json 檔案。",
  "INVALID_PACKAGE_JSON": "package.json 檔案無效 (錯誤: {0}).",
  "MISSING_PACKAGE_NAME": "package.json 檔案中沒有指定套件名稱。",
  "BAD_PACKAGE_NAME": "{0} 不是正確的套件名稱。",
  "MISSING_PACKAGE_VERSION": "package.json 檔案中沒有指定套件版本。",
  "INVALID_VERSION_NUMBER": "套件版號 ({0}) 無效。",
  "INVALID_BRACKETS_VERSION": "{APP_NAME} 相容性字串 ({0}) 無效。",
  "DISALLOWED_WORDS": "{0} 欄位中不能有 ({1}) 這些字。",
  "NPM_INSTALL_FAILED": "npm install 指令失敗：{0}",
  "API_NOT_COMPATIBLE": "這個擴充功能不相容於本版 {APP_NAME}。已將其安裝在 \"disabled\" 已停用擴充功能資料夾中。",
  "MISSING_MAIN": "套件中沒有 main.js 檔案。",
  "EXTENSION_ALREADY_INSTALLED": "安裝這個套件將會蓋掉先前安裝的擴充功能。 是否要覆寫?",
  "EXTENSION_SAME_VERSION": "已經安裝過這個版本的套件了。 是否要覆寫已安裝的版本?",
  "EXTENSION_OLDER_VERSION": "{0} 版的套件比已安裝的版本 ({1}) 還要舊。 是否要覆寫已經安裝的版本?",
  "DOWNLOAD_ID_IN_USE": "內部錯誤: 下載識別碼正在使用中。",
  "NO_SERVER_RESPONSE": "無法連到伺服器。",
  "BAD_HTTP_STATUS": "伺服器 (HTTP {0}) 回應找不到檔案。",
  "CANNOT_WRITE_TEMP": "無法下載存成暫存檔。",
  "ERROR_LOADING": "擴充功能啟動時發生錯誤。",
  "MALFORMED_URL": "URL 無效。請檢查您是否輸入正確。",
  "UNSUPPORTED_PROTOCOL": "只支援 http 或 https 協定的 URL。",
  "UNKNOWN_ERROR": "不明的內部錯誤。",
  "EXTENSION_VERIFIED_PUBLISHER": "此發行者已驗證 {0} 的所有權。",
  "EXTENSION_VERIFIED_SORT": "已驗證",
  "EXTENSION_STAR": "星級",
  "EXTENSION_STAR_SORT": "星級評分",
  "ERROR_UNINSTALLING_EXTENSION_TITLE": "解除安裝擴充功能錯誤",
  "ERROR_UNINSTALLING_EXTENSION_MESSAGE": "解除安裝擴充功能 {0} 失敗",
  "EXTENSION_MANAGER_TITLE": "擴充功能管理員",
  "EXTENSION_MANAGER_ERROR_LOAD": "無法存取擴充功能登錄庫。請稍後再試。",
  "EXTENSION_UPDATE_RESTART_TITLE": "重新啟動以更新",
  "EXTENSION_UPDATE_RESTART_MESSAGE": "若要載入已更新的擴充功能，請關閉所有正在執行的 {APP_NAME} 執行個體，然後重新啟動應用程式。",
  "INSTALL_EXTENSION_DRAG": "將 .zip 拖過來，或",
  "INSTALL_EXTENSION_DROP": "放開 .zip 開始安裝",
  "INSTALL_EXTENSION_DROP_ERROR": "下列原因造成安裝或是更新失敗:",
  "INSTALL_FROM_URL": "由 URL 安裝…",
  "INSTALL_EXTENSION_VALIDATING": "Validating…",
  "EXTENSION_AUTHOR": "作者",
  "EXTENSION_DATE": "日期",
  "EXTENSION_INCOMPATIBLE_NEWER": "這個擴充功能需要較新版的 {APP_NAME} 才能使用。",
  "EXTENSION_INCOMPATIBLE_OLDER": "這個擴充功能目前只能在舊版 {APP_NAME} 中使用。",
  "EXTENSION_DEFAULT_FEATURE_PRESENT": "您可能不需要此擴充功能。{APP_NAME} 已具備此功能。",
  "EXTENSION_DEPRECATED_NOT_LOADED": "擴充功能未載入。其已棄用或不安全。",
  "EXTENSION_LATEST_INCOMPATIBLE_NEWER": "這個擴充功能 {0} 版只能在新版 {APP_NAME} 中使用。不過您可以選擇安裝較舊的 {1} 版。",
  "EXTENSION_LATEST_INCOMPATIBLE_OLDER": "這個擴充功能 {0} 版只能在舊版 {APP_NAME} 中使用。不過您可以選擇安裝較舊的 {1} 版。",
  "EXTENSION_NO_DESCRIPTION": "沒有描述資訊",
  "EXTENSION_MORE_INFO": "更多資訊…",
  "EXTENSION_ERROR": "擴充功能錯誤",
  "EXTENSION_KEYWORDS": "關鍵字",
  "EXTENSION_TRANSLATED_USER_LANG": "包含您使用的語言在內，總共支援 {0} 種語言",
  "EXTENSION_TRANSLATED_GENERAL": "支援 {0} 種語言",
  "EXTENSION_TRANSLATED_LANGS": "這個擴充功能已經被翻譯成下列語言: {0}",
  "EXTENSION_INSTALLED": "已安裝",
  "EXTENSION_UPDATE_INSTALLED": "這個擴充功能的更新已經下載完成，會在重新載入 {APP_NAME} 時安裝。",
  "EXTENSION_SEARCH_PLACEHOLDER": "搜尋",
  "EXTENSION_MORE_INFO_LINK": "更多",
  "EXTENSION_MANAGER_CREATE_EXTENSION": "新增擴充功能",
  "EXTENSION_MANAGER_CREATE_THEME": "新增佈景主題",
  "BROWSE_EXTENSIONS": "瀏覽擴充功能",
  "EXTENSION_MANAGER_REMOVE": "移除擴充功能",
  "EXTENSION_MANAGER_REMOVE_ERROR": "無法移除擴充功能: {0}。 {APP_NAME} 還是會重新載入。",
  "EXTENSION_MANAGER_UPDATE": "更新擴充功能",
  "EXTENSION_MANAGER_UPDATE_ERROR": "無法更新擴充功能: {0}。 {APP_NAME} 還是會重新載入。",
  "EXTENSION_MANAGER_DISABLE": "停用擴充功能",
  "EXTENSION_MANAGER_DISABLE_ERROR": "無法停用擴充功能: {0}。 {APP_NAME} 還是會重新載入。",
  "EXTENSION_MANAGER_THEMES_INFO": "若要<a class=\"theme_settings\">選取預設佈景主題</a>或修改其他佈景主題設定，請<a class=\"theme_settings\">按一下這裡</a>。",
  "EXTENSION_MANAGER_THEMES_UNDO": "回復至先前的佈景主題",
  "MARKED_FOR_REMOVAL": "標為待移除",
  "UNDO_REMOVE": "復原",
  "MARKED_FOR_UPDATE": "標為待更新",
  "UNDO_UPDATE": "復原",
  "MARKED_FOR_DISABLING": "標為待停用",
  "UNDO_DISABLE": "復原",
  "CHANGE_AND_RELOAD_TITLE": "變更擴充功能",
  "CHANGE_AND_RELOAD_MESSAGE": "要更新、移除或停用標記的擴充功能，需要重新載入 {APP_NAME}。 會再提示您儲存所做的變更。",
  "REMOVE_AND_RELOAD": "移除擴充功能並重新載入",
  "CHANGE_AND_RELOAD": "變更擴充功能並重新載入",
  "UPDATE_AND_RELOAD": "更新擴充功能並重新載入",
  "DISABLE_AND_RELOAD": "停用擴充功能並重新載入",
  "PROCESSING_EXTENSIONS": "正在變更擴充功能…",
  "EXTENSION_NOT_INSTALLED": "無法移除還沒安裝的擴充功能 {0}。",
  "NO_EXTENSIONS": "還沒安裝任何擴充功能。<br>請點一下上方的「可使用」頁籤開始。",
  "NO_EXTENSION_MATCHES": "找不到符合您搜尋條件的擴充功能。",
  "REGISTRY_SANITY_CHECK_WARNING": "注意: 擴充功能可能是 {APP_NAME} 以外的作者提供，內容沒有經過檢閱，並且有完整的本地權限。由不明來源安裝時請小心警覺!",
  "EXTENSIONS_INSTALLED_TITLE": "已安裝",
  "EXTENSIONS_DEFAULT_TITLE": "預設",
  "EXTENSIONS_AVAILABLE_TITLE": "可使用",
  "EXTENSIONS_THEMES_TITLE": "佈景主題",
  "EXTENSIONS_UPDATES_TITLE": "更新",
  "EXTENSIONS_LAST_UPDATED": "上次更新時間",
  "EXTENSIONS_DOWNLOADS": "下載次數",
  "EXTENSIONS_REGISTRY_TASK_TITLE": "更新擴充功能清單",
  "EXTENSIONS_REGISTRY_TASK_MESSAGE": "下載中…",
  "INLINE_EDITOR_NO_MATCHES": "找不到符合的。",
  "INLINE_EDITOR_HIDDEN_MATCHES": "所有符合項目都被收合起來了。展開右側清單中的檔案檢視符合項目。",
  "CSS_QUICK_EDIT_NO_MATCHES": "既有 CSS 中沒有符合您選取內容的規則。<br> 按一下「新增規則」 建立一組。",
  "CSS_QUICK_EDIT_NO_STYLESHEETS": "您的專案中沒有 Stylesheet 樣式表檔案。<br>建立一個來新增 CSS 規則。",
  "IMAGE_VIEWER_LARGEST_ICON": "最大",
  "UNIT_PIXELS": "像素",
  "DEBUG_MENU": "除錯",
  "ERRORS": "錯誤",
  "CMD_SHOW_DEV_TOOLS": "{APP_NAME} 開發人員工具",
  "CMD_REFRESH_WINDOW": "重新載入並啟用擴充功能",
  "CMD_LOAD_CURRENT_EXTENSION": "將專案作為擴充功能載入",
  "CMD_RELOAD_CURRENT_EXTENSION": "將專案作為擴充功能重新載入",
  "CMD_UNLOAD_CURRENT_EXTENSION": "卸載專案作為擴充功能",
  "CMD_RELOAD_WITHOUT_USER_EXTS": "重新載入並停用擴充功能",
  "CMD_NEW_BRACKETS_WINDOW": "開啟新視窗",
  "CMD_LAUNCH_SCRIPT_MAC": "安裝命令列捷徑",
  "CMD_SWITCH_LANGUAGE": "切換語言…",
  "CMD_RUN_UNIT_TESTS": "執行 {APP_NAME} 測試",
  "CMD_BUILD_TESTS": "建置編輯器測試",
  "CMD_SHOW_PERF_DATA": "顯示效能資料",
  "CMD_ENABLE_LOGGING": "啟用詳細記錄",
  "CMD_ENABLE_PHNODE_INSPECTOR": "啟用 PhNode 檢查器",
  "CMD_GET_PHNODE_INSPECTOR_URL": "如何檢查 PhNode",
  "CMD_ENABLE_LIVE_PREVIEW_LOGS": "即時預覽記錄",
  "CMD_ENABLE_GIT_LOGS": "Git 詳細記錄",
  "CMD_OPEN_BRACKETS_SOURCE": "開啟 {APP_NAME} 原始碼",
  "CREATING_LAUNCH_SCRIPT_TITLE": "{APP_NAME} 命令列捷徑",
  "ERROR_CREATING_LAUNCH_SCRIPT": "安裝命令列捷徑時發生錯誤。請嘗試<a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting'>這些疑難排解建議</a>。<br/><br/>原因: {0}",
  "ERROR_CLTOOLS_RMFAILED": "無法移除現有的 <code>/usr/local/bin/brackets</code> 符號連結。",
  "ERROR_CLTOOLS_MKDIRFAILED": "無法建立 <code>/usr/local/bin</code> 目錄。",
  "ERROR_CLTOOLS_LNFAILED": "無法建立 <code>/usr/local/bin/brackets</code> 符號連結。",
  "ERROR_CLTOOLS_SERVFAILED": "內部錯誤。",
  "ERROR_CLTOOLS_NOTSUPPORTED": "在這個作業系統中無法使用命令列捷徑功能。",
  "LAUNCH_SCRIPT_CREATE_SUCCESS": "成功! 現在開始您可以經由下列指令啟動 {APP_NAME}: <code>brackets myFile.txt</code> 開啟檔案，或 <code>brackets myFolder</code> 切換專案。<br/><br/><a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments'>了解更多</a> {APP_NAME} 命令列的使用方法。",
  "ERROR_LOADING_EXTENSION": "載入擴充功能時發生錯誤",
  "ERROR_NO_EXTENSION_PACKAGE": "在目前的專案中找不到 <code>package.json</code> 檔案。目前的專案是有效的 {APP_NAME} 擴充功能嗎？</br>請參閱<a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>此連結</a>以取得更多詳細資訊。",
  "ERROR_INVALID_EXTENSION_PACKAGE": "<code>package.json</code> 檔案的 JSON 格式無效。</br>請參閱<a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>此連結</a>以取得更多詳細資訊。",
  "ERROR_INVALID_EXTENSION_PACKAGE_FIELDS": "<code>package.json</code> 中缺少必要的欄位：[{0}] </br>請參閱<a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>此連結</a>以取得更多詳細資訊。",
  "ERROR_NODE_JS_CRASH_TITLE": "糟糕！發生了一些錯誤。",
  "ERROR_NODE_JS_CRASH_MESSAGE": "我們遇到問題，需要重新啟動 {APP_NAME}。別擔心，我們會嘗試在重新啟動前儲存您的所有工作。</br>（錯誤：ERROR_NODE_JS_CRASH）",
  "LANGUAGE_TITLE": "切換語言",
  "LANGUAGE_MESSAGE": "語言:",
  "LANGUAGE_SUBMIT": "重新載入 {APP_NAME}",
  "LANGUAGE_CANCEL": "取消",
  "LANGUAGE_SYSTEM_DEFAULT": "系統預設",
  "HEALTH_DATA_NOTIFICATION": "狀況報告喜好設定",
  "HEALTH_FIRST_POPUP_TITLE": "隱私權聲明",
  "HEALTH_DATA_DO_TRACK": "分享我使用 {APP_NAME} 的匿名資訊",
  "HEALTH_DATA_NOTIFICATION_MESSAGE": "{APP_NAME} <strong>不會收集或處理任何個人識別資訊</strong>，但<strong>會收集匿名使用統計數據</strong>以保護您的隱私。匿名數據不受 GDPR/CCPA 通知要求的約束，但我們認為您也需要有選擇退出匿名數據收集的權利。<br><br>您可以透過選擇<strong>說明 > 健康報告</strong>來查看您的數據或<strong>選擇不分享任何匿名數據</strong>。這些<strong>匿名</strong>應用程式使用統計數據和錯誤報告有助於我們排定功能優先順序、找出錯誤並發現可用性問題，以改善您使用 {APP_NAME} 的體驗。沒有這些數據，我們就不知道哪些功能值得為您打造！<br>",
  "HEALTH_DATA_PREVIEW": "{APP_NAME} 狀況報告",
  "HEALTH_DATA_PREVIEW_INTRO": "<p>{APP_NAME} <strong>不會收集或處理任何個人識別資訊</strong>，但<strong>會收集匿名使用統計資料</strong>以保障您的隱私。這些<strong>匿名</strong>應用程式使用統計資料和錯誤報告有助於我們排定功能優先順序、找出錯誤並發現可用性問題，以改善您使用 {APP_NAME} 的體驗。</p> <p>以下是<em>如果</em>已啟用健康報告，將在您的下次健康報告中傳送的資料預覽。（另請參閱開發人員主控台，查看標記為「攔截到嚴重錯誤」的錯誤日誌。）</p>",
  "HEALTH_DATA_PREVIEW_NECESSARY": "安全性/應用程式更新、分析程式庫初始化、使用者人數和使用時間等應用程式健康指標，皆以匿名方式收集。這些皆為彙總統計數據，不會傳送/記錄任何個人資料。",
  "INLINE_TIMING_EDITOR_TIME": "時間",
  "INLINE_TIMING_EDITOR_PROGRESSION": "進度",
  "BEZIER_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd><kbd>←</kbd><kbd>→</kbd> 移動選取的控制點<br><kbd class='text'>Shift</kbd> 移動 10 個單位<br><kbd class='text'>Tab</kbd> 切換控制點",
  "STEPS_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd> 增加或減少 Step 數<br><kbd>←</kbd><kbd>→</kbd> 'Start' 或 'End'",
  "INLINE_TIMING_EDITOR_INVALID": "原始值 <code>{0}</code> 無效，因此改以 <code>{1}</code> 函式顯示。 檔案在第一次編輯後將被更新。",
  "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP": "目前的色彩",
  "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP": "原來的色彩",
  "COLOR_EDITOR_RGBA_BUTTON_TIP": "RGBa 格式",
  "COLOR_EDITOR_HEX_BUTTON_TIP": "16 進位格式",
  "COLOR_EDITOR_HSLA_BUTTON_TIP": "HSLa 格式",
  "COLOR_EDITOR_0X_BUTTON_TIP": "Hex (0x) 格式",
  "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR": "{0} (用了 {1} 次)",
  "COLOR_EDITOR_USED_COLOR_TIP_PLURAL": "{0} (用了 {1} 次)",
  "EDIT": "編輯",
  "CMD_JUMPTO_DEFINITION": "跳到定義位置",
  "CMD_SHOW_PARAMETER_HINT": "顯示參數提示",
  "NO_ARGUMENTS": "<沒有參數>",
  "DETECTED_EXCLUSION_TITLE": "JavaScript 檔案推斷問題",
  "DETECTED_EXCLUSION_INFO": "{APP_NAME} 在處理 <span class='dialog-filename'>{0}</span> 時遇到問題。<br><br>程式碼提示、跳至定義或快速編輯將不再處理此檔案。要重新啟用此檔案，請在您的專案中開啟 <code>.phcode.json</code> 並編輯 <code>jscodehints.detectedExclusions</code>。<br><br>這可能是 {APP_NAME} 的錯誤。如果您能提供此檔案的副本，請<a href='https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue'>回報錯誤</a>並附上此檔案的連結。",
  "CMD_REFACTOR": "重構",
  "CMD_EXTRACTTO_VARIABLE": "擷取至變數",
  "CMD_EXTRACTTO_FUNCTION": "擷取至函式",
  "ERROR_TERN_FAILED": "無法從 Tern 取得資料",
  "ERROR_EXTRACTTO_VARIABLE_NOT_VALID": "選取的內容並非有效的表達式",
  "ERROR_EXTRACTTO_FUNCTION_NOT_VALID": "選取的區塊應該代表一組陳述式或一個表達式",
  "ERROR_EXTRACTTO_VARIABLE_MULTICURSORS": "「擷取至變數」在多游標模式下無法運作",
  "ERROR_EXTRACTTO_FUNCTION_MULTICURSORS": "「擷取至函式」在多游標模式下無法運作",
  "EXTRACTTO_FUNCTION_SELECT_SCOPE": "選擇目標範圍",
  "EXTRACTTO_VARIABLE_SELECT_EXPRESSION": "選取一個表達式",
  "CMD_REFACTORING_RENAME": "重新命名",
  "CMD_REFACTORING_TRY_CATCH": "包裹在 Try Catch 中",
  "CMD_REFACTORING_CONDITION": "包裹在條件式中",
  "CMD_REFACTORING_GETTERS_SETTERS": "建立 Getter/Setter",
  "CMD_REFACTORING_ARROW_FUNCTION": "轉換為箭頭函式",
  "DESCRIPTION_CODE_REFACTORING": "啟用/停用 JavaScript 程式碼重構",
  "ERROR_TRY_CATCH": "選取有效的程式碼以包覆在 Try-catch 區塊中",
  "ERROR_WRAP_IN_CONDITION": "選取有效的程式碼以包覆在條件區塊中",
  "ERROR_ARROW_FUNCTION": "將游標放置在函式表達式內",
  "ERROR_GETTERS_SETTERS": "將游標放置在物件表達式的成員上",
  "ERROR_RENAME_MULTICURSOR": "使用多個游標時無法重新命名",
  "ERROR_RENAME_QUICKEDIT": "由於此識別項在函式外部被參考，因此無法重新命名",
  "ERROR_RENAME_GENERAL": "無法重新命名選取的文字",
  "JSHINT_NAME": "JSHint",
  "JSHINT_CONFIG_ERROR": "讀取 JSHint 設定檔時發生錯誤：{0}",
  "JSHINT_CONFIG_JSON_ERROR": "錯誤：JSHint 設定檔 `{0}` 不是有效的 JSON 格式",
  "ESLINT_NAME": "ESLint",
  "CSS_LINT_NAME": "{0}",
  "HTML_LINT_NAME": "HTML",
  "HTML_LINT_CONFIG_JSON_ERROR": "錯誤：HTML 驗證器設定檔 `{0}` 不是有效的 JSON 格式",
  "HTML_LINT_CONFIG_UNSUPPORTED": "錯誤：不支援的設定格式 `{0}`。請使用 JSON 設定檔 `.htmlvalidate.json`",
  "CMD_ENABLE_QUICK_VIEW": "游標停留時快速檢視",
  "CMD_ENABLE_SELECTION_VIEW": "選取範圍檢視",
  "TOOLTIP_CLICK_TO_EDIT_COLOR": "點擊此處以編輯顏色",
  "CMD_RECENT_PROJECTS": "最近開啟的專案",
  "REMOVE_FROM_RECENT_PROJECTS": "從最近專案移除",
  "DOCS_MORE_LINK": "更多資訊",
  "DOCS_MORE_LINK_MDN_TITLE": "點擊以閱讀文件",
  "COLLAPSE_ALL": "全部收合",
  "EXPAND_ALL": "全部展開",
  "COLLAPSE_CURRENT": "收合目前區塊",
  "EXPAND_CURRENT": "展開目前區塊",
  "RECENT_FILES_DLG_HEADER": "最近檔案",
  "RECENT_FILES_DLG_CLEAR_BUTTON_LABEL": "清除",
  "RECENT_FILES_DLG_CLEAR_BUTTON_TITLE": "清除不在工作集中的檔案",
  "RECOVER_UNSAVED_FILES_TITLE": "復原未儲存的檔案？",
  "RECOVER_UNSAVED_FILES_MESSAGE": "是否要從您之前的階段作業復原未儲存的檔案？",
  "RECOVER_UNSAVED_FILES_RESTORE": "復原",
  "DISCARD_UNSAVED_FILES_RESTORE": "捨棄",
  "DESCRIPTION_CLOSE_BRACKETS": "true 代表自動插入右括號",
  "DESCRIPTION_CLOSE_OTHERS_ABOVE": "false 代表由「工作檔案」內容功能表中移除「關閉上列檔案」",
  "DESCRIPTION_CLOSE_OTHERS_BELOW": "false 代表由「工作檔案」內容功能表中移除「關閉下列檔案」",
  "DESCRIPTION_CLOSE_OTHERS": "false 代表由「工作檔案」內容功能表中移除「關閉其他檔案」",
  "DESCRIPTION_CLOSE_TAGS": "設定結尾標籤自動插入選項",
  "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS": "不需要自動結尾的標籤陣列",
  "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING": "輸入啟始標籤的 > 時自動結尾",
  "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING": "輸入結尾標籤的 / 時自動完成結尾",
  "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS": "啟始時需要空一行的標籤陣列",
  "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD": "true 代表縮排階層變更時立即產生區塊收合標記",
  "DESCRIPTION_CODE_FOLDING_ENABLED": "true 代表啟用程式區塊收合功能",
  "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER": "true 代表只在滑鼠游標移動到邊欄時才顯示區塊收合標記",
  "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL": "「全部收合」時實際收合的階層上限",
  "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE": "顯示區塊收合標記的最小行數",
  "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES": "true 代表關閉再重開檔案或專案後還要記住收合狀態",
  "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE": "true 代表在編輯器中啟用選取區塊收合功能",
  "DESCRIPTION_DISABLED_DEFAULT_EXTENSIONS": "預設停用的擴充功能",
  "DESCRIPTION_ATTR_HINTS": "啟用或停用 HTML 屬性提示",
  "DESCRIPTION_CSS_PROP_HINTS": "啟用或停用 CSS/LESS/SCSS 屬性提示",
  "DESCRIPTION_JS_HINTS": "啟用或停用 JavaScript 程式碼提示",
  "DESCRIPTION_JS_HINTS_TYPE_DETAILS": "啟用／停用 JavaScript 程式碼提示中的資料類型詳細資訊",
  "DESCRIPTION_PREF_HINTS": "啟用或停用「喜好設定」程式碼提示",
  "DESCRIPTION_SPECIAL_CHAR_HINTS": "啟用或停用 HTML 實體 (Entity) 提示",
  "DESCRIPTION_SVG_HINTS": "啟用或停用 SVG 程式碼提示",
  "DESCRIPTION_HTML_TAG_HINTS": "啟用或停用 HTML 標籤提示",
  "DESCRIPTION_URL_CODE_HINTS": "啟用或停用 HTML 與 CSS/LESS/SCSS 中的 URL 提示",
  "DESCRIPTION_DRAG_DROP_TEXT": "啟用或停用「拖放功能」",
  "DESCRIPTION_HEALTH_DATA_TRACKING": "啟用「狀況資料追蹤」",
  "DESCRIPTION_HIGHLIGHT_MATCHES": "啟用檔案中的其他符合字串突顯功能",
  "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN": "突顯游標所在字符的所有符合字串 (不用選取)",
  "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY": "只在選到完整字符時才突顯其他符合字串",
  "DESCRIPTION_INSERT_HINT_ON_TAB": "true 代表按 Tab 鍵也能插入選取的程式碼提示",
  "DESCRIPTION_NO_HINTS_ON_DOT": "true 代表輸入 . 時不要自動顯示 JS 程式碼提示",
  "DESCRIPTION_JSHINT_DISABLE": "設定為 true 可在問題面板中停用 JSHints 程式碼檢查器",
  "DESCRIPTION_ESLINT_DISABLE": "在問題面板中停用 ESLint 程式碼檢查器的選項設為 true",
  "DESCRIPTION_HTML_LINT_DISABLE": "在問題面板中停用 HTML 程式碼檢查器的選項設為 true",
  "DESCRIPTION_ESLINT_FAILED": "ESLint 執行失敗 ({0})。請確認專案包含有效的 <a href='https://eslint.org/docs/latest/use/configure/configuration-files'>設定檔</a>",
  "DESCRIPTION_ESLINT_USE_NATIVE_APP": "ESLint 僅在桌面應用程式中可用。請從 <a href='https://phcode.io'>phcode.io</a> 下載",
  "DESCRIPTION_ESLINT_LOAD_FAILED": "無法載入此專案的 ESLint。{APP_NAME} 僅支援 7 以上版本的 ESLint。",
  "DESCRIPTION_ESLINT_DO_NPM_INSTALL": "請在您的專案上執行 `npm install` 以啟用 ESLint",
  "DESCRIPTION_LANGUAGE": "語言相關設定",
  "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS": "副檔與程式語言名稱的額外對應",
  "DESCRIPTION_LANGUAGE_FILE_NAMES": "檔名與程式語言名稱的額外對應",
  "DESCRIPTION_LINEWISE_COPY_CUT": "當沒有選取任何內容時執行複製和剪下，將會複製或剪下游標所在的所有行",
  "DESCRIPTION_INPUT_STYLE": "選擇 CodeMirror 處理輸入和焦點的方式。可以是 textarea（預設值），或是 contenteditable（對螢幕閱讀器較佳，但較不穩定）",
  "DESCRIPTION_LINTING_ENABLED": "true 代表啟用「程式碼檢查」",
  "DESCRIPTION_ASYNC_TIMEOUT": "非同步檢查程式的執行時間上限亳秒數",
  "DESCRIPTION_LINTING_PREFER": "優先執行的檢查程式陣列",
  "DESCRIPTION_LIVE_DEV_MULTIBROWSER": "true 代表啟用實驗版「即時預覽」",
  "DESCRIPTION_USE_PREFERED_ONLY": "true 代表只執行 linting.prefer 中指定的提供者",
  "DESCRIPTION_MAX_CODE_HINTS": "同時顯示的程式碼提示數目上限",
  "DESCRIPTION_PATH": "路徑相關設定",
  "DESCRIPTION_PROXY": "用來安裝擴充功能的 Proxy 伺服器 URL",
  "DESCRIPTION_SCROLL_PAST_END": "true 代表允許捲動到檔案結尾之後",
  "DESCRIPTION_MOUSE_WHEEL_SCROLL_SENSITIVITY": "滑鼠滾輪捲動速度倍率 (0.1 至 10，預設值為 1)。若您覺得捲動速度過慢或過快，可調整此數值。",
  "DESCRIPTION_SHOW_CODE_HINTS": "false 代表停用所有的程式碼提示",
  "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING": "選取文字時還是要顯示閃動的游標",
  "DESCRIPTION_SHOW_LINE_NUMBERS": "true 代表在程式碼左方「邊欄」中顯示行號",
  "DESCRIPTION_RULERS_COLUMNS": "一個用於在編輯器中繪製垂直尺規的欄號陣列。例如：[80, 100]",
  "DESCRIPTION_RULERS_COLORS": "與編輯器中 rulers 選項對應的尺規顏色陣列。例如：[\"#3d3d3d\", \"red\"]",
  "DESCRIPTION_RULERS_ENABLED": "設為 true 以啟用編輯器尺規，否則設為 false",
  "DESCRIPTION_AUTO_RENAME_TAGS": "設為 true 以自動重新命名成對的 HTML/XML 標籤，否則設為 false",
  "DESCRIPTION_DRAG_AND_DROP_ENABLED": "設為 true 以啟用從檔案總管或 Finder 拖放檔案和資料夾的功能",
  "DESCRIPTION_TRIPLE_CTRL_PALETTE": "設為 true 可在連續按三次 Ctrl/Cmd 鍵時顯示視覺指令面板",
  "DESCRIPTION_SMART_INDENT": "建立新區塊時自動縮排",
  "DESCRIPTION_SOFT_TABS": "false 代表停用軟體 Tab 功能",
  "DESCRIPTION_SORT_DIRECTORIES_FIRST": "true 代表在專案樹中將目錄排在上面",
  "DESCRIPTION_SPACE_UNITS": "以空格縮排時一階的空格數",
  "DESCRIPTION_STATIC_SERVER_PORT": "供「即時預覽」內建伺服器使用的通訊埠號",
  "DESCRIPTION_STYLE_ACTIVE_LINE": "true 代表使用背景色突顯出游標所在行",
  "DESCRIPTION_TAB_SIZE": "顯示一個 Tab 所需的空格數",
  "DESCRIPTION_USE_TAB_CHAR": "true 代表使用 Tab 取代空格",
  "DESCRIPTION_AUTO_TAB_SPACE": "設定為 true 以自動偵測目前檔案中使用的定位點和空格",
  "DESCRIPTION_UPPERCASE_COLORS": "true 代表在「就地色彩編輯器」中產出 16 進位色彩值時使用大寫",
  "DESCRIPTION_WORD_WRAP": "超過檢視區寛度時自動換行",
  "DESCRIPTION_SEARCH_AUTOHIDE": "編輯器取得焦點時自動關閉搜尋",
  "DESCRIPTION_DETECTED_EXCLUSIONS": "偵測出會讓 Tern 失控的檔案清單",
  "DESCRIPTION_INFERENCE_TIMEOUT": "Tern 檔案內容分析時間上限毫秒數",
  "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR": "true 代表在狀態列顯示錯誤",
  "DESCRIPTION_QUICK_VIEW_ENABLED": "true 代表啟用「快速檢視」",
  "DESCRIPTION_SELECTION_VIEW_ENABLED": "設為 true 以啟用選取檢視",
  "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW": "true 代表對沒有副檔名的 URL 顯示圖片預覽",
  "DESCRIPTION_NUMBER_QUICK_VIEW": "設為 true 以在編輯器中將滑鼠懸停在數字上時顯示快速檢視",
  "DESCRIPTION_THEME": "選用 {APP_NAME} 佈景主題",
  "DESCRIPTION_USE_THEME_SCROLLBARS": "true 代表允許自訂捲軸",
  "DESCRIPTION_EDITOR_LINE_HEIGHT": "調整編輯器中程式碼行間的垂直間距。選擇一個介於 1 和 3 之間的值，預設值為 1.5",
  "DESCRIPTION_LINTING_COLLAPSED": "true 代表收合檢查面板",
  "DESCRIPTION_FONT_FAMILY": "變更字族 (Font Family)",
  "DESCRIPTION_DESKTOP_ZOOM_SCALE": "選擇縮放比例，範圍從 0.1（更緊湊的視圖）到 2（更大、更放大的視圖）。僅適用於桌面應用程式",
  "DESCRIPTION_FONT_SIZE": "變更字體大小，例如: 13px",
  "DESCRIPTION_FIND_IN_FILES_NODE": "true 代表啟用節點搜尋",
  "DESCRIPTION_FIND_IN_FILES_INSTANT": "true 代表啟用立即搜尋",
  "DESCRIPTION_FONT_SMOOTHING": "只適用 Mac: \"subpixel-antialiased\" 代表啟用子像素鋸齒消除模式，或是設成 \"antialiased\" 使用灰階鋸齒消除模式。",
  "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW": "false 代表不要使用分割窗格開啟喜好設定檔",
  "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE": "false 代表在左窗格或上窗格開啟使用者喜好設定檔",
  "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED": "當窗格中的最後一個檔案透過窗格標題關閉按鈕關閉後，設為 true 可摺疊窗格。",
  "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS": "切換何時在標題上顯示關閉和翻轉檢視按鈕。",
  "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT": "/*",
  "DEFAULT_PREFERENCES_JSON_DEFAULT": "預設",
  "DESCRIPTION_PURE_CODING_SURFACE": "設為 true 可啟用純程式碼模式並隱藏 {APP_NAME} 中的所有其他 UI 元素。",
  "DESCRIPTION_INDENT_LINE_COMMENT": "設為 true 可啟用行註解的縮排。",
  "DESCRIPTION_RECENT_FILES_NAV": "啟用／停用在最近檔案中的導覽。",
  "DESCRIPTION_LIVEDEV_WEBSOCKET_PORT": "即時預覽的 WebSocket 伺服器執行所在的連接埠。",
  "DESCRIPTION_LIVEDEV_ENABLE_REVERSE_INSPECT": "設為 false 可停用即時預覽反向檢查。",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW": "無可預覽的內容！",
  "DESCRIPTION_LIVEDEV_EXCLUDED": "自訂伺服器無法提供此檔案",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW_EXCLUDED": "即時預覽設定僅提供來自「{0}」資料夾的檔案",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW_DETAILS": "請選擇一個 HTML 檔案進行預覽",
  "DESCRIPTION_LIVEDEV_PREVIEW_RESTRICTED": "無法預覽！",
  "DESCRIPTION_LIVEDEV_PREVIEW_RESTRICTED_DETAILS": "此 HTML 檔案不屬於目前的專案。基於安全性考量，僅能即時預覽專案檔案。若要預覽此檔案，請將其所在的資料夾以個別專案開啟。",
  "DESCRIPTION_LIVEDEV_MAIN_HEADING": "哎呀！<br>您目前的瀏覽器不支援即時預覽。",
  "DESCRIPTION_LIVEDEV_MAIN_SPAN": "從 <a href=\"https://phcode.io\" style=\"color: white\">phcode.io</a> 下載適用於 Windows、Mac 和 Linux 的原生應用程式，以獲得最佳的即時預覽體驗。<br>",
  "DESCRIPTION_LIVEDEV_SECURITY_POPOUT_MESSAGE": "您即將開啟一個檔案以進行即時預覽。如果您信任此專案的來源，才請繼續操作。按一下「信任專案」繼續，或如果您不信任來源，請關閉此視窗。",
  "DESCRIPTION_LIVEDEV_SECURITY_TRUST_MESSAGE": "您即將開啟一個檔案以進行即時預覽。如果您信任此專案的來源，才請按一下「信任專案」繼續！",
  "CONFIRM_EXTERNAL_BROWSER_TITLE": "彈出視窗已封鎖",
  "CONFIRM_EXTERNAL_BROWSER_MESSAGE": "您是否允許即時預覽頁面開啟此網址：{0}？",
  "TRUST_PROJECT": "信任並執行預覽 - {0}",
  "TRUST_AUTHORS": "您是否信任此專案的作者？",
  "DOWNLOAD_FAILED": "下載失敗。",
  "DOWNLOAD_COMPLETE": "下載完成！",
  "UPDATE_SUCCESSFUL": "更新成功！",
  "UPDATE_FAILED": "更新失敗！",
  "VALIDATION_FAILED": "驗證失敗！",
  "INITIALISATION_FAILED": "初始化失敗！",
  "CLEANUP_FAILED": "清理失敗！",
  "WARNING_TYPE": "警告！",
  "CLICK_RESTART_TO_UPDATE": "按一下「重新啟動」來更新 Brackets。",
  "UPDATE_ON_NEXT_LAUNCH": "更新將在下一次啟動時套用。",
  "GO_TO_SITE": "前往 <a href = \"http://brackets.io/\"> brackets.io </a> 重試。",
  "INTERNET_UNAVAILABLE": "無法連線到網際網路。",
  "UPDATEDIR_READ_FAILED": "無法讀取更新目錄。",
  "UPDATEDIR_CLEAN_FAILED": "無法清理更新目錄。",
  "INITIAL_DOWNLOAD": "正在下載更新…",
  "RETRY_DOWNLOAD": "下載失敗，正在重試…嘗試",
  "VALIDATING_INSTALLER": "下載完成！正在驗證安裝程式⋯",
  "CHECKSUM_DID_NOT_MATCH": "校驗碼不符。",
  "INSTALLER_NOT_FOUND": "找不到安裝程式。",
  "DOWNLOAD_ERROR": "下載時發生錯誤。",
  "NETWORK_SLOW_OR_DISCONNECTED": "網路已斷線或速度過慢。",
  "RESTART_BUTTON": "重新啟動",
  "RESTART_APP_BUTTON": "重新啟動 {APP_NAME}",
  "LATER_BUTTON": "之後再說",
  "DESCRIPTION_AUTO_UPDATE": "啟用／停用 {APP_NAME} 自動更新",
  "AUTOUPDATE_ERROR": "錯誤！",
  "AUTOUPDATE_IN_PROGRESS": "更新程序已在進行中。",
  "REMOVING": "正在移除…",
  "NUMBER_WITH_PERCENTAGE": "{0}%",
  "CMD_FIND_RELATED_FILES": "尋找相關檔案",
  "PHP_VERSION_INVALID": "解析 PHP 版本時發生錯誤。請檢查「php –version」指令的輸出。",
  "PHP_UNSUPPORTED_VERSION": "安裝 PHP7 執行環境以啟用 PHP 相關工具，例如程式碼提示、參數提示、跳至定義等等。找到的版本：{0}",
  "PHP_EXECUTABLE_NOT_FOUND": "找不到 PHP 執行環境。請安裝 PHP7 執行環境並在 PHP 偏好設定中適當更新「executablePath」。這將啟用 PHP 相關工具，例如程式碼提示、參數提示、跳至定義等等。",
  "PHP_PROCESS_SPAWN_ERROR": "啟動 PHP 程序時遇到錯誤碼 {0}。",
  "PHP_SERVER_ERROR_TITLE": "錯誤",
  "PHP_SERVER_MEMORY_LIMIT_INVALID": "您提供的記憶體限制無效。請檢查 PHP 偏好設定以設定正確的值。",
  "DESCRIPTION_PHP_TOOLING_CONFIGURATION": "PHP 工具預設設定",
  "OPEN_PREFERENNCES": "開啟偏好設定",
  "LANGUAGE_TOOLS_PREFERENCES": "語言工具偏好設定",
  "FIND_ALL_REFERENCES": "尋找所有參考",
  "REFERENCES_IN_FILES": "參考",
  "REFERENCE_IN_FILES": "參考",
  "REFERENCES_NO_RESULTS": "目前游標位置找不到任何參考",
  "CMD_FIND_DOCUMENT_SYMBOLS": "尋找文件符號",
  "CMD_FIND_PROJECT_SYMBOLS": "尋找專案符號",
  "REMOTE_DEBUGGING_ENABLED": "已在 localhost 啟用遠端除錯：",
  "REMOTE_DEBUGGING_PORT_INVALID": "無法在連接埠 {0} 上啟用遠端除錯。連接埠號碼應介於 {1} 和 {2} 之間。",
  "DESCRIPTION_EXTERNAL_APPLICATION_ASSOCIATE": "檔案副檔名與外部應用程式的對應。語法：\"<file_type>\": \"<default|applicationName|ApplicationPath>\"，使用 \"default\" 以系統預設應用程式開啟檔案。",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_TITLE": "在外部編輯器中開啟圖形檔案",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_MSG": "您目前的資料夾包含 {APP_NAME} 不支援的圖形檔案類型。<br/>您現在可以將特定檔案類型與外部編輯器關聯。關聯後，您可以透過在檔案樹狀結構中雙擊檔案，在預設應用程式中開啟圖形檔案，例如 .xd、.psd、.jpg、.png、.ai、.svg。<br/><br/>請點擊「確定」按鈕，將圖形檔案類型與其各自的預設應用程式關聯。",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_CNF_MSG": "以下檔案類型已成功與預設應用程式關聯。<br/>{0} 您可以選擇是否在 phcode.json 中刪除／新增檔案類型關聯，方法是前往「除錯->開啟偏好設定檔案」選單。",
  "UNSUPPORTED_BROWSER_TITLE": "不支援的瀏覽器",
  "UNSUPPORTED_BROWSER_MESSAGE": "請使用新式瀏覽器（三年內發行的版本）。",
  "UNSUPPORTED_BROWSER_MOBILE_TITLE": "不支援行動瀏覽器",
  "UNSUPPORTED_BROWSER_MOBILE": "目前不完全支援行動裝置和平台瀏覽器。您可以關閉此對話方塊，但 Phoenix 的某些功能在此瀏覽器中將無法使用。<br/><br/>我們正在開發適用於 iOS 和 Android 的原生應用程式。<a href=\"https://github.com/phcode-dev/phoenix/discussions/1046\" target=\"_blank\">在此加入討論！</a>",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER_TITLE": "瀏覽器不支援本機資料夾存取",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER": "抱歉，您的目前瀏覽器似乎不支援開啟本機資料夾。對於此功能，我們建議使用 Chrome、Edge 或 Opera。<br/><br/>或者，我們正在開發適用於 Windows、Mac、Linux、iOS 和 Android 的原生應用程式，以提供完整支援。<a href=\"https://github.com/phcode-dev/phoenix/discussions/1047\" target=\"_blank\">敬請期待更新！</a>",
  "ATTENTION_SAFARI_USERS": "Safari 使用者注意事項",
  "ATTENTION_SAFARI_USERS_MESSAGE": "<span>如果 7 天內沒有再次造訪網站，Safari 會自動刪除網站資料。{APP_NAME} 仰賴瀏覽器儲存空間來儲存您的專案，這些專案可能會因為這項政策而被移除。<br/> <br/>建議您從 <a href='https://phcode.io' target='_blank' style='color: white'>https://phcode.io</a><strong>下載 macOS 桌面應用程式</strong></span>",
  "CANNOT_PUBLISH_LARGE_PROJECT": "無法發佈大型專案",
  "CANNOT_PUBLISH_LARGE_PROJECT_MESSAGE": "Phoenix 仍處於實驗性 alpha 階段。我們尚未啟用超過 500 個檔案的專案同步功能。",
  "SHARE_WEBSITE": "發佈並分享網站？",
  "PUBLISH": "發佈",
  "PUBLISH_CONSENT_MESSAGE": "快速預覽變更並與他人分享您的網站。{APP_NAME} 可以在 {0} 為您發佈此網站。已發佈的連結將在 3 天內有效。</br>您是否要發佈並分享您的網站？",
  "PUBLISH_SYNC_IN_PROGRESS": "預覽同步處理中…",
  "PUBLISH_PAGE": "點擊以發佈並分享此網站",
  "PUBLISH_VIEW_PAGE": "點擊以檢視已發佈的頁面",
  "MISSING_FIELDS": "缺少欄位",
  "PLEASE_FILL_ALL_REQUIRED": "請填寫所有標示為紅色的必填欄位",
  "CODE_EDITOR": "程式碼編輯器",
  "BUILD_THE_WEB": "建置網頁",
  "IMPORT_PROJECT": "匯入專案",
  "GIT_PROJECT": "從 Git 取得",
  "NEW_PROJECT_FROM_GIT": "從 Git 建立新專案",
  "GIT_REPO_URL": "Git 儲存庫網址：",
  "GIT_CLONE_URL": "Git 複製網址：",
  "START_PROJECT": "開始專案…",
  "DOWNLOAD_DESKTOP_APP": "下載桌面應用程式",
  "GET_DESKTOP_APP": "取得桌面應用程式",
  "CREATE_PROJECT": "建立專案",
  "SETTING_UP_PROJECT": "設定專案中",
  "LOCATION": "位置：",
  "ERROR_ONLY_GITHUB": "瀏覽器版本的 {APP_NAME} 只支援 GitHub 網址。如需使用其他 Git 網址，請使用桌面應用程式。",
  "ERROR_GIT_URL_INVALID": "請輸入有效的 Git 複製網址。",
  "ERROR_GIT_FOLDER_NOT_EMPTY": "選取的資料夾不能用於 Git 複製，因為它不是空的或無法讀取。",
  "ERROR_GIT_FOLDER_NOT_EXIST": "選取的資料夾不能用於 Git 複製，因為它不存在。",
  "ERROR_CLONING_TITLE": "Git 複製失敗",
  "DOWNLOADING": "下載中…",
  "DOWNLOADING_FILE": "正在下載 {0}…",
  "EXTRACTING_FILES_PROGRESS": "正在解壓縮 {0} / {1} 個檔案。",
  "COMPRESS_FILES_PROGRESS": "正在壓縮 {0} / {1} 個檔案。",
  "DOWNLOAD_FAILED_MESSAGE": "請確認下載網址有效。</br>注意：由於 Phoenix 仍處於 alpha 階段，不允許使用私有儲存庫和超過 25 MB 的 GitHub 網址。",
  "PLEASE_SELECT_A_FOLDER": "請選擇一個資料夾…",
  "UNZIP_IN_PROGRESS": "正在解壓縮檔案…",
  "UNZIP_FAILED": "錯誤：解壓縮失敗。",
  "CONFIRM_REPLACE_TITLE": "確認取代",
  "KEEP_BOTH": "兩者保留",
  "EXPLORE": "HTML 遊戲",
  "BLOG": "部落格",
  "PHOENIX_DEFAULT_PROJECT": "預設專案",
  "PROJECT_NAME": "專案名稱：",
  "NEW_HTML": "新增 HTML 專案",
  "LICENSE": "授權與鳴謝：",
  "PREVIEW": "預覽",
  "BUILD_WEBSITE": "建置網站",
  "VIEW_MORE": "查看更多…",
  "NEW_PROJECT_NOTIFICATION": "按一下此圖示即可再次開啟「開始專案」視窗。</br> 查看最近的專案、開啟資料夾或從範本開始專案。</br> <img src=\"styles/images/new_project.png\">",
  "BEAUTIFY_CODE_NOTIFICATION": "按一下此處或按下 <b>`{0}`</b> 以美化程式碼。</br> <img src=\"styles/images/beautify.gif\">",
  "DEFAULT_PROJECT_NOTIFICATION": "在 {APP_NAME} 中開啟<b>預設專案</b>即可快速上手（適合做為草稿區）。</br></br>或者，使用下方的<strong>開啟資料夾</strong>圖示從您的電腦開啟資料夾。<br><a href='#' style='float:right;'>確定</a>",
  "DIRECTORY_REPLACE_MESSAGE": "所選資料夾 <span class='dialog-filename'>{0}</span> 並非空的。您確定要用專案取代資料夾內容嗎？",
  "DEFAULT_PROJECT_HTML_CLICK_HERE": "點擊此處即可在 HTML 檔案中找到此 &lt;span&gt;",
  "BUILD_WEBSITE_SECTION": "建置網站",
  "LEARN_SECTION": "透過範例學習",
  "CREATE_EXTENSION_SECTION": "建立 {APP_NAME} 擴充功能和佈景主題",
  "CREATE_EXTENSION": "建立擴充功能",
  "CREATE_THEME": "建立佈景主題",
  "WEBPAGE_HOME_PAGE": "首頁",
  "WEBPAGE_BLOG": "部落格頁面",
  "WEBPAGE_DASHBOARD": "HTML 儀表板",
  "WEBPAGE_BOOTSTRAP_EXAMPLES": "Bootstrap 範例",
  "PROJECTS_AT_A_GLANCE": "專案總覽",
  "PROJECT_AT_GLANCE_DESCRIPTION": "觀看影片以開始使用。",
  "PROJECT_FROM_BROWSER": "儲存於您的瀏覽器",
  "PROJECT_FROM_BROWSER_TERSE": "瀏覽器儲存空間",
  "PROJECT_SHOW_ON_STARTUP": "啟動時顯示此對話框",
  "GUIDED_LIVE_PREVIEW": "在 HTML 檔案中進行一些程式碼更改，即可查看即時預覽。<br/> <a href='#' style='float:right;'>確定</a>",
  "GUIDED_LIVE_PREVIEW_POPOUT": "點擊此按鈕可將即時預覽彈出至新分頁。<br/> <a href='#' style='float:right;'>確定</a>",
  "TEST_TRANSLATE": "使用此功能測試翻譯",
  "BEAUTIFY_ERROR": "無法美化程式碼。請檢查語法。",
  "BEAUTIFY_ERROR_ORIGINAL_CHANGED": "無法美化。美化後編輯器文字已更改。",
  "BEAUTIFY_PROJECT_BUSY_MESSAGE": "正在美化檔案 {0}",
  "BEAUTIFY_ERROR_SELECTION": "無法美化程式碼。</br>選取的程式碼區塊不完整或語法無效。",
  "BEAUTIFY_OPTIONS": "控制程式碼美化方式的選項",
  "BEAUTIFY_OPTION_PRINT_WIDTH": "指定美化工具換行的行長度",
  "BEAUTIFY_OPTION_SEMICOLON": "在每個語句的結尾添加分號",
  "BEAUTIFY_OPTION_SINGLE_QUOTE": "使用單引號代替雙引號",
  "BEAUTIFY_OPTION_QUOTE_PROPS": "變更物件中屬性何時使用引號",
  "BEAUTIFY_OPTION_BRACKET_SAME_LINE": "將多行 HTML（HTML、JSX、Vue、Angular）元素的 > 放在最後一行的結尾，而不是單獨放在下一行（不適用於自閉合元素）",
  "BEAUTIFY_OPTION_SINGLE_ATTRIBUTE_PER_LINE": "在 HTML、Vue 和 JSX 中強制每個屬性佔用一行",
  "BEAUTIFY_OPTION_PROSE_WRAP": "如果 Markdown 檔案中的散文超過列印寬度，則進行換行",
  "BEAUTIFY_OPTION_PRINT_TRAILING_COMMAS": "盡可能在多行逗號分隔的語法結構中列印尾隨逗號",
  "DESCRIPTION_INDENT_GUIDES_ENABLED": "顯示縮排引導線：勾選為顯示，取消勾選則不顯示。",
  "DESCRIPTION_HIDE_FIRST": "顯示第一條縮排引導線：勾選為顯示，取消勾選則不顯示。",
  "DESCRIPTION_CSS_COLOR_PREVIEW": "在側邊顯示顏色預覽：勾選為顯示，取消勾選則不顯示。",
  "DESCRIPTION_EMMET": "啟用 Emmet 請設為 true，否則為 false。",
  "DESCRIPTION_SHOW_WORKING_SET": "顯示工作集設為 true，隱藏設為 false。",
  "DESCRIPTION_TABBAR": "設定分頁列設定。",
  "DESCRIPTION_SHOW_TABBAR": "顯示分頁列設為 true，隱藏則設為 false。",
  "DESCRIPTION_NUMBER_OF_TABS": "分頁列中顯示的分頁數量。設為 -1 則顯示所有分頁。",
  "TABBAR_SHOW_HIDDEN_TABS": "顯示隱藏的索引標籤",
  "ENABLE_GIT": "啟用 Git",
  "ACTION": "動作",
  "STATUSBAR_SHOW_GIT": "Git 面板",
  "ADD_ENDLINE_TO_THE_END_OF_FILE": "在檔案結尾新增換行字元",
  "ADD_TO_GITIGNORE": "加入至 .gitignore",
  "AMEND_COMMIT": "修改上次提交",
  "SKIP_COMMIT_CHECKS": "跳過提交前檢查 (--no-verify)",
  "AMEND_COMMIT_FORBIDDEN": "無未推送的提交時無法修改提交",
  "_ANOTHER_BRANCH": "其他分支",
  "AUTHOR": "作者",
  "AUTHORS_OF": "作者：",
  "SYSTEM_CONFIGURATION": "系統設定",
  "BRACKETS_GIT_ERROR": "Git 發生錯誤…",
  "BRANCH_NAME": "分支名稱",
  "BUTTON_CANCEL": "取消",
  "CHECKOUT_COMMIT": "切換版本",
  "CHECKOUT_COMMIT_DETAIL": "<b>提交訊息：</b> {0} <br><b>提交雜湊值：</b> {1}",
  "GIT_CLONE": "複製",
  "BUTTON_CLOSE": "關閉",
  "BUTTON_COMMIT": "提交",
  "BUTTON_DEFAULTS": "還原預設值",
  "BUTTON_FIND_CONFLICTS": "尋找衝突…",
  "GIT_INIT": "初始化",
  "BUTTON_MERGE_ABORT": "放棄合併",
  "BUTTON_OK": "確定",
  "BUTTON_REBASE_ABORT": "中止",
  "BUTTON_REBASE_CONTINUE": "繼續變基",
  "BUTTON_REBASE_SKIP": "跳過",
  "MENU_RESET_HARD": "捨棄此提交之後的變更和提交（硬重置）",
  "MENU_RESET_MIXED": "捨棄此提交之後的提交，但保留未暫存的變更（混合重置）",
  "MENU_RESET_SOFT": "捨棄此提交之後的提交，但保留已暫存的變更（軟重置）",
  "MENU_TAG_COMMIT": "標記提交",
  "RESET_HARD_TITLE": "確認硬重置",
  "RESET_MIXED_TITLE": "確認混合重置",
  "RESET_SOFT_TITLE": "確認軟重置",
  "RESET_DETAIL": "<b>以下提交將被捨棄：</b><br><b>提交訊息：</b> {0}<br><b>Git 指令：</b> {1}",
  "RESET_HARD_MESSAGE": "此動作將捨棄選定提交之後的所有變更和提交。<b>此操作不易復原。</b>確定要繼續嗎？<br><br>⚠️ 警告：此操作會改寫歷史記錄，不應在已推送至共用分支的提交上使用。",
  "RESET_MIXED_MESSAGE": "此動作將捨棄選定提交之後的所有提交，但會保留所有未暫存的變更。<b>此操作不易復原。</b>確定要繼續嗎？<br><br>⚠️ 警告：此操作會改寫歷史記錄，不應在已推送至共用分支的提交上使用。",
  "RESET_SOFT_MESSAGE": "此動作將捨棄選定提交之後的所有提交，但會保留所有已暫存的變更以進行新的提交。<b>此操作不易復原。</b>確定要繼續嗎？<br><br>⚠️ 警告：此操作會改寫歷史記錄，不應在已推送至共用分支的提交上使用。",
  "BUTTON_SAVE": "儲存",
  "RESET": "重設",
  "CHANGE_USER_EMAIL_TITLE": "變更 Git 電子郵件地址",
  "CHANGE_USER_EMAIL": "變更 Git 電子郵件地址…",
  "CHANGE_USER_EMAIL_MENU": "變更 Git 電子郵件地址 ({0})…",
  "CHANGE_USER_NAME_TITLE": "變更 Git 使用者名稱",
  "CHANGE_USER_NAME": "變更 Git 使用者名稱…",
  "CHANGE_USER_NAME_MENU": "變更 Git 使用者名稱 ({0})…",
  "REQUIRES_APP_RESTART_SETTING": "變更此設定需要重新啟動應用程式才會生效",
  "CLEAN_FILE_END": "已清除檔案",
  "CLEAN_FILE_START": "正在清除檔案",
  "CLEANING_WHITESPACE_PROGRESS": "正在清除檔案中的空白…",
  "CLEAR_WHITESPACE_ON_FILE_SAVE": "儲存檔案時清除空白",
  "CLONE_REPOSITORY": "複製儲存庫",
  "CODE_INSPECTION_PROBLEMS": "程式碼檢查問題",
  "CODE_INSPECTION_IN_PROGRESS": "程式碼檢查進行中…",
  "CODE_INSPECTION_PROBLEMS_NONE": "未偵測到問題",
  "CODE_INSPECTION_DONE_FILES": "已完成 {0} / {1} 個檔案…",
  "PLEASE_WAIT": "請稍候…",
  "COMMIT": "提交",
  "COMMIT_ALL_SHORTCUT": "提交所有檔案…",
  "COMMIT_CURRENT_SHORTCUT": "提交目前檔案…",
  "COMMIT_MESSAGE_PLACEHOLDER": "在此輸入提交訊息…",
  "CREATE_NEW_BRANCH": "建立新的分支…",
  "CREATE_NEW_BRANCH_TITLE": "建立新的分支",
  "CREATE_NEW_GITFTP_SCOPE": "建立新的 Git-FTP 遠端…",
  "CREATE_NEW_REMOTE": "建立新的遠端…",
  "CURRENT_TRACKING_BRANCH": "目前追蹤的分支",
  "_CURRENT_TRACKING_BRANCH": "目前追蹤的分支",
  "DEFAULT_GIT_TIMEOUT": "預設 Git 操作逾時時間（秒）",
  "DELETE_FILE_BTN": "刪除檔案…",
  "DELETE_LOCAL_BRANCH": "刪除本地分支",
  "DELETE_LOCAL_BRANCH_NAME": "您確定要刪除本地分支「{0}」嗎？",
  "DELETE_REMOTE": "刪除遠端",
  "DELETE_REMOTE_NAME": "您確定要刪除遠端「{0}」嗎？",
  "DELETE_SCOPE": "刪除 Git-FTP 範圍",
  "DELETE_SCOPE_NAME": "您確定要刪除 Git-FTP 範圍「{0}」嗎？",
  "DIALOG_CHECKOUT": "檢出 commit 時，儲存庫將進入「分離 HEAD」狀態。除非您以此為基礎建立分支，否則無法提交任何 commit。",
  "DIALOG_PULL_TITLE": "從遠端拉取",
  "DIALOG_PUSH_TITLE": "推送到遠端",
  "SKIP_PRE_PUSH_CHECKS": "略過推送前檢查 (--no-verify)",
  "DIFF": "差異",
  "DIFFTOOL": "使用 difftool 進行差異比對",
  "DIFF_FAILED_SEE_FILES": "Git diff 無法提供差異結果。以下是待提交的暫存檔案列表：",
  "DIFF_TOO_LONG": "差異過長，無法顯示",
  "ENABLE_GERRIT_PUSH_REF": "使用 Gerrit 相容的推送參考",
  "ENTER_NEW_USER_EMAIL": "輸入電子郵件",
  "ENTER_NEW_USER_NAME": "輸入使用者名稱",
  "ENTER_PASSWORD": "輸入密碼：",
  "ENTER_REMOTE_GIT_URL": "輸入您要複製的儲存庫之 Git URL：",
  "ENTER_REMOTE_NAME": "輸入新的遠端名稱：",
  "ENTER_REMOTE_URL": "輸入新的遠端 URL：",
  "ENTER_USERNAME": "輸入使用者名稱：",
  "ERROR_NOTHING_SELECTED": "未選取任何項目！",
  "ERROR_SAVE_FIRST": "請先儲存文件！",
  "ERROR_TERMINAL_NOT_FOUND": "您的作業系統找不到終端機，您可以在設定中自訂終端機指令",
  "EXTENDED_COMMIT_MESSAGE": "延伸說明",
  "GETTING_STAGED_DIFF_PROGRESS": "取得已暫存檔案的差異…",
  "GIT_COMMIT": "Git 送出…",
  "GIT_COMMIT_IN_PROGRESS": "Git 送出中…",
  "GIT_DIFF": "Git diff &mdash;",
  "GIT_PULL_RESPONSE": "Git 拉取回應",
  "GIT_PUSH_RESPONSE": "Git 推送回應",
  "GIT_REMOTES": "Git 遠端",
  "GIT_SETTINGS": "Git 設定…",
  "GIT_SETTINGS_TITLE": "Git 設定",
  "GOTO_NEXT_GIT_CHANGE": "前往下一項 Git 變更",
  "GOTO_PREVIOUS_GIT_CHANGE": "跳至上一個 Git 變更",
  "GUTTER_CLICK_DETAILS": "點擊查看更多詳細資訊",
  "HIDE_UNTRACKED": "在面板中隱藏未追蹤的檔案",
  "HISTORY": "歷史記錄",
  "HISTORY_COMMIT_BY": "作者：",
  "LINES": "行數",
  "_LINES": "行",
  "MARK_MODIFIED_FILES_IN_TREE": "在檔案樹中標記已修改的檔案",
  "MERGE_BRANCH": "合併分支",
  "MERGE_MESSAGE": "合併訊息",
  "MERGE_RESULT": "合併結果",
  "NORMALIZE_LINE_ENDINGS": "正規化行尾 (改為 \\n)",
  "NOTHING_TO_COMMIT": "沒有任何要提交的變更，工作目錄是乾淨的。",
  "OPERATION_IN_PROGRESS_TITLE": "Git 操作執行中…",
  "ORIGIN_BRANCH": "遠端分支",
  "ON_BRANCH": "'{0}' - 目前 Git 分支",
  "PANEL_COMMAND": "顯示 Git 面板",
  "PASSWORD": "密碼",
  "PASSWORDS": "密碼",
  "PATH_TO_GIT_EXECUTABLE": "Git 執行檔路徑",
  "PULL_AVOID_MERGING": "避免手動合併",
  "PULL_DEFAULT": "預設合併",
  "PULL_FROM": "從…拉取",
  "PULL_MERGE_NOCOMMIT": "合併但不提交",
  "PULL_REBASE": "使用變基",
  "PULL_RESET": "使用軟重置",
  "PULL_SHORTCUT": "從遠端儲存庫拉取…",
  "PULL_SHORTCUT_BEHIND": "從遠端儲存庫拉取（落後 {0} 個提交）…",
  "PULL_BEHAVIOR": "拉取行為",
  "FETCH_SHORTCUT": "從遠端儲存庫擷取",
  "PUSH_DEFAULT": "預設推送",
  "PUSH_DELETE_BRANCH": "刪除遠端分支",
  "PUSH_SEND_TAGS": "傳送標籤",
  "PUSH_FORCED": "強制推送",
  "PUSH_SHORTCUT": "推送至遠端…",
  "PUSH_SHORTCUT_AHEAD": "推送至遠端（超前 {0} 個提交）…",
  "PUSH_TO": "推送至",
  "PUSH_BEHAVIOR": "推送行為",
  "Q_UNDO_CHANGES": "重設 <span class='dialog-filename'>{0}</span> 檔案的變更？",
  "REBASE_RESULT": "重整基底結果",
  "REFRESH_GIT": "更新 Git 狀態",
  "REMOVE_BOM": "移除檔案的 BOM",
  "REMOVE_FROM_GITIGNORE": "從 .gitignore 移除",
  "RESET_LOCAL_REPO": "放棄上次提交後的變更…",
  "DISCARD_CHANGES": "放棄變更",
  "RESET_LOCAL_REPO_CONFIRM": "您確定要放棄上次提交後的所有變更嗎？此動作無法復原。",
  "UNDO_LOCAL_COMMIT_CONFIRM": "您確定要復原上次未推送的提交嗎？",
  "MORE_OPTIONS": "更多選項",
  "CREDENTIALS": "認證",
  "SAVE_CREDENTIALS_HELP": "如果您的認證已在其他地方管理，您無需填寫使用者名稱／密碼。僅在操作持續逾時時使用。",
  "SAVE_CREDENTIALS_IN_URL": "將憑證儲存至遠端網址（純文字格式）",
  "SET_THIS_BRANCH_AS_TRACKING": "將此分支設定為新的追蹤分支",
  "STRIP_WHITESPACE_FROM_COMMITS": "移除提交訊息尾端的空白字元",
  "TARGET_BRANCH": "目標分支",
  "TITLE_CHECKOUT": "確認要取出提交嗎？",
  "TOOLTIP_CLONE": "複製現有的儲存庫",
  "TOOLTIP_COMMIT": "提交選取的檔案",
  "TOOLTIP_FETCH": "抓取所有遠端分支並更新計數器",
  "TOOLTIP_FIND_CONFLICTS": "在專案中開始搜尋 Git 合併/變基衝突",
  "TOOLTIP_HIDE_FILE_HISTORY": "隱藏檔案歷史記錄",
  "TOOLTIP_HIDE_HISTORY": "隱藏歷史紀錄",
  "TOOLTIP_INIT": "初始化儲存庫",
  "TOOLTIP_MERGE_ABORT": "放棄合併操作並將 HEAD 重設為上次的本地提交",
  "TOOLTIP_PICK_REMOTE": "選擇偏好的遠端",
  "TOOLTIP_PULL": "Git 拉取",
  "TOOLTIP_PUSH": "Git 推送",
  "TOOLTIP_REBASE_ABORT": "放棄變基操作並將 HEAD 重設為原始分支",
  "TOOLTIP_REBASE_CONTINUE": "解決合併衝突後，重新啟動變基程序",
  "TOOLTIP_REBASE_SKIP": "跳過目前的修補程式，重新啟動變基程序",
  "TOOLTIP_REFRESH_PANEL": "重新整理面板",
  "TOOLTIP_SHOW_FILE_HISTORY": "顯示檔案歷史紀錄",
  "TOOLTIP_SHOW_HISTORY": "顯示歷史紀錄",
  "GIT_SHOW_FILE_HISTORY": "檔案提交紀錄",
  "GIT_SHOW_HISTORY": "提交紀錄",
  "UNDO_CHANGES": "捨棄變更",
  "UNDO_CHANGES_BTN": "捨棄變更…",
  "UNDO_LAST_LOCAL_COMMIT": "復原上次的本地（尚未推送的）提交…",
  "UNDO_COMMIT": "復原提交",
  "URL": "網址",
  "USERNAME": "使用者名稱",
  "USER_ABORTED": "使用者已中止！",
  "USE_GIT_GUTTER": "使用 Git 邊欄標記",
  "USE_NOFF": "即使合併可以快速向前推進，仍建立合併提交 (--no-ff)",
  "USE_REBASE": "使用變基",
  "USE_VERBOSE_DIFF": "在差異比較中顯示詳細輸出",
  "USE_DIFFTOOL": "使用差異比較工具",
  "VIEW_AUTHORS_FILE": "查看檔案的作者…",
  "VIEW_AUTHORS_SELECTION": "查看選取範圍的作者…",
  "VIEW_THIS_FILE": "查看此檔案",
  "TAG_NAME_PLACEHOLDER": "在此輸入標籤名稱…",
  "TAG_NAME": "標籤",
  "CMD_CLOSE_UNMODIFIED": "關閉未修改的檔案",
  "FILE_ADDED": "新增檔案",
  "FILE_COPIED": "已複製",
  "FILE_DELETED": "已刪除",
  "FILE_IGNORED": "已忽略",
  "FILE_MODIFIED": "已修改",
  "FILE_RENAMED": "已重新命名",
  "FILE_STAGED": "已加入索引",
  "FILE_UNMERGED": "未合併",
  "FILE_UNMODIFIED": "未修改",
  "FILE_UNTRACKED": "未追蹤",
  "GIT_PUSH_SUCCESS_MSG": "快速前推成功",
  "GIT_PUSH_FORCE_UPDATED_MSG": "強制更新成功",
  "GIT_PUSH_DELETED_MSG": "成功刪除參考",
  "GIT_PUSH_NEW_REF_MSG": "成功推送新的參考",
  "GIT_PUSH_REJECTED_MSG": "參考被拒絕或推送失敗",
  "GIT_PUSH_UP_TO_DATE_MSG": "參考已是最新狀態，無需推送",
  "GIT_PULL_SUCCESS": "Git 拉取完成",
  "GIT_MERGE_SUCCESS": "Git 合併完成",
  "GIT_REBASE_SUCCESS": "Git 重定基底完成",
  "GIT_BRANCH_DELETE_SUCCESS": "Git 分支刪除成功",
  "INIT_NEW_REPO_FAILED": "建立新的儲存庫失敗",
  "GIT_CLONE_REMOTE_FAILED": "複製遠端儲存庫失敗！",
  "GIT_CLONE_ERROR_EXPLAIN": "選取的目錄 `{0}`",
  "FOLDER_NOT_WRITABLE": "選取的目錄 `{0}`",
  "GIT_NOT_FOUND_MESSAGE": "您的系統上未安裝 Git 或找不到 Git。請安裝 Git 或在下面的文字欄位中提供 Git 執行檔的正確路徑。",
  "ERROR_GETTING_BRANCH_LIST": "取得分支列表失敗",
  "ERROR_READING_GIT_HEAD": "讀取 .git/HEAD 檔案失敗",
  "ERROR_PARSING_BRANCH_NAME": "從 {0} 解析分支名稱失敗",
  "ERROR_READING_GIT_STATE": "讀取 .git 狀態失敗",
  "ERROR_GETTING_DELETED_FILES": "取得已刪除檔案列表失敗",
  "ERROR_SWITCHING_BRANCHES": "切換分支失敗",
  "ERROR_GETTING_CURRENT_BRANCH": "取得目前分支名稱失敗",
  "ERROR_REBASE_FAILED": "重整基底失敗",
  "ERROR_MERGE_FAILED": "合併失敗",
  "ERROR_BRANCH_DELETE_FORCED": "強制刪除分支失敗",
  "ERROR_FETCH_REMOTE_INFO": "取得遠端資訊失敗",
  "ERROR_CREATE_BRANCH": "建立新的分支失敗",
  "ERROR_REFRESH_GUTTER": "更新行號區塊失敗！",
  "ERROR_GET_HISTORY": "取得歷史紀錄失敗",
  "ERROR_GET_MORE_HISTORY": "載入更多歷史紀錄列失敗",
  "ERROR_GET_CURRENT_BRANCH": "取得目前分支名稱失敗",
  "ERROR_GET_DIFF_FILE_COMMIT": "取得差異比對失敗",
  "ERROR_GET_DIFF_FILES": "載入差異檔案列表失敗",
  "ERROR_MODIFY_GITIGNORE": "修改 .gitignore 失敗",
  "ERROR_UNDO_LAST_COMMIT_FAILED": "無法復原上次提交",
  "ERROR_MODIFY_FILE_STATUS_FAILED": "無法修改檔案狀態",
  "ERROR_CHANGE_USERNAME_FAILED": "無法變更使用者名稱",
  "ERROR_CHANGE_EMAIL_FAILED": "無法變更使用者電子郵件",
  "ERROR_TOGGLE_GERRIT_PUSH_REF_FAILED": "無法切換 Gerrit 推送參考",
  "ERROR_RESET_LOCAL_REPO_FAILED": "重設本地儲存庫失敗",
  "ERROR_CREATE_TAG": "建立標籤失敗",
  "ERROR_CODE_INSPECTION_FAILED": "CodeInspection.inspectFile 無法執行檔案",
  "ERROR_CANT_GET_STAGED_DIFF": "無法取得已暫存檔案的差異",
  "ERROR_STAGE_FAILED": "Git 檔案暫存失敗",
  "ERROR_GIT_COMMIT_FAILED": "Git 送交失敗",
  "ERROR_GIT_BLAME_FAILED": "Git 追溯失敗",
  "ERROR_GIT_DIFF_FAILED": "Git 比對失敗",
  "ERROR_DISCARD_CHANGES_FAILED": "放棄檔案變更失敗",
  "ERROR_COULD_NOT_RESOLVE_FILE": "無法解析檔案",
  "ERROR_MERGE_ABORT_FAILED": "合併中止失敗",
  "ERROR_MODIFIED_DIALOG_FILES": "您要送交的檔案在送交對話框顯示時已被修改。由於結果與對話框中顯示的內容不同，因此中止送交。",
  "ERROR_GETTING_REMOTES": "取得遠端資訊失敗！",
  "ERROR_REMOTE_CREATION": "建立遠端失敗",
  "ERROR_PUSHING_REMOTE": "推送至遠端失敗",
  "ERROR_PULLING_REMOTE": "從遠端拉取失敗",
  "ERROR_PULLING_OPERATION": "拉取操作失敗",
  "ERROR_PUSHING_OPERATION": "推送操作失敗",
  "ERROR_NO_REMOTE_SELECTED": "{0} 尚未選取任何遠端！",
  "ERROR_BRANCH_LIST": "取得分支列表失敗",
  "ERROR_FETCH_REMOTE": "擷取遠端資訊失敗",
  "ERROR_PREPARING_COMMIT_DIALOG": "準備提交對話框失敗",
  "GIT_TOAST_TITLE": "在 Phoenix Code 中探索 Git 功能",
  "GIT_TOAST_MESSAGE": "點擊 Git 面板圖示來管理您的儲存庫。輕鬆提交、推送、拉取，並檢視您的專案歷史紀錄 — 全都在同一個地方。<br><a href='https://docs.phcode.dev/app-links/git'>深入了解 Git 面板 →</a>",
  "SURVEY_TITLE_VOTE_FOR_FEATURES_YOU_WANT": "投票選出您希望看到的下個功能！",
  "SIGNED_OUT": "您已登出。",
  "SIGNED_OUT_MESSAGE": "您已登出 {APP_NAME} 帳號。請重新登入以繼續。",
  "SIGNED_OUT_MESSAGE_FRIENDLY": "感謝您使用 {APP_NAME}。下次見！",
  "SIGNED_IN_OFFLINE_TITLE": "離線 - 無法登入",
  "SIGNED_IN_OFFLINE_MESSAGE": "請連線到網際網路以登入 {APP_NAME}。",
  "SIGNED_IN_FAILED_TITLE": "無法登入",
  "SIGNED_IN_FAILED_MESSAGE": "登入時發生錯誤。請再試一次。",
  "SIGNED_OUT_FAILED_TITLE": "登出失敗",
  "SIGNED_OUT_FAILED_MESSAGE": "登出時發生錯誤。請按一下「確定」開啟 <a href='https://account.phcode.dev/#advanced'>account.phcode.dev</a> 以手動登出。",
  "VALIDATION_CODE_TITLE": "登入驗證碼",
  "VALIDATION_CODE_MESSAGE": "請使用此驗證碼登入您的 {APP_NAME} 帳號：",
  "COPY_VALIDATION_CODE": "複製驗證碼",
  "VALIDATION_CODE_COPIED": "已複製",
  "OPEN_SIGN_IN_URL": "開啟登入頁面",
  "PROFILE_POP_TITLE": "{APP_NAME} 帳號",
  "PROFILE_SIGN_IN": "登入您的帳號",
  "CONTACT_SUPPORT": "聯絡客服",
  "SIGN_OUT": "登出",
  "SIGN_IN": "登入",
  "ACCOUNT_DETAILS": "帳號詳細資訊",
  "LOGIN_REFRESH": "檢查登入狀態",
  "SIGN_IN_WAITING_TITLE": "等待登入中",
  "SIGN_IN_WAITING_MESSAGE": "請在新分頁中完成登入，然後返回此處。",
  "WAITING_FOR_LOGIN": "正在登入中…",
  "CHECK_NOW": "立即檢查",
  "CHECKING": "檢查中…",
  "CHECKING_STATUS": "正在檢查登入狀態…",
  "NOT_SIGNED_IN_YET": "您尚未登入。請在另一個分頁中完成登入。",
  "WELCOME_BACK": "歡迎回來",
  "WELCOME_BACK_USER": "歡迎回來，{0}！",
  "POPUP_BLOCKED": "彈出視窗遭到封鎖。請允許彈出視窗並重試，或手動前往 {0}",
  "COLLAPSE_ALL_FOLDERS": "收合所有資料夾",
  "CUSTOM_SNIPPETS_MENU_ITEM_NAME": "自訂程式碼片段…",
  "CUSTOM_SNIPPETS_PANEL_TITLE": "自訂程式碼片段",
  "CUSTOM_SNIPPETS_ADD_PANEL_TITLE": "新增程式碼片段",
  "CUSTOM_SNIPPETS_EDIT_PANEL_TITLE": "編輯程式碼片段",
  "CUSTOM_SNIPPETS_ADD_NEW_TITLE": "新增程式碼片段",
  "CUSTOM_SNIPPETS_BACK_TO_LIST_TITLE": "返回程式碼片段清單",
  "CUSTOM_SNIPPETS_BACK": "返回",
  "CUSTOM_SNIPPETS_FILTER_PLACEHOLDER": "篩選…",
  "CUSTOM_SNIPPETS_NO_SNIPPETS_MESSAGE": "尚未新增任何自訂程式碼片段！",
  "CUSTOM_SNIPPETS_ADD_SNIPPET_BTN": "新增程式碼片段",
  "CUSTOM_SNIPPETS_ABBREVIATION_LABEL": "縮寫：",
  "CUSTOM_SNIPPETS_TEMPLATE_TEXT_LABEL": "範本文字：",
  "CUSTOM_SNIPPETS_DESCRIPTION_LABEL": "說明：",
  "CUSTOM_SNIPPETS_FILE_EXTENSION_LABEL": "檔案副檔名：",
  "CUSTOM_SNIPPETS_CANCEL": "取消",
  "CUSTOM_SNIPPETS_SAVE": "儲存",
  "CUSTOM_SNIPPETS_NO_DESCRIPTION": "沒有描述資訊",
  "CUSTOM_SNIPPETS_NO_MATCHES": "沒有符合「{0}」的程式碼片段",
  "CUSTOM_SNIPPETS_LEARN_MORE": "新增您自己的程式碼片段，加快編碼速度 - <a href=\"https://docs.phcode.dev/app-links/custom-snippets\" target=\"_blank\">了解更多</a>",
  "CUSTOM_SNIPPETS_DUPLICATE_ERROR": "縮寫為「{0}」的程式碼片段已存在。",
  "CUSTOM_SNIPPETS_SPACE_ERROR": "空格不能作為有效的縮寫字元。",
  "CUSTOM_SNIPPETS_ABBR_LENGTH_ERROR": "縮寫不能超過 30 個字元。",
  "CUSTOM_SNIPPETS_DESC_LENGTH_ERROR": "說明不能超過 80 個字元。",
  "CUSTOM_SNIPPETS_HINT_LABEL": "程式碼片段",
  "CUSTOM_SNIPPETS_EDIT_ABBR_TOOLTIP": "點擊以編輯縮寫 - {0}",
  "CUSTOM_SNIPPETS_EDIT_TEMPLATE_TOOLTIP": "點擊以編輯範本文字 - {0}",
  "CUSTOM_SNIPPETS_EDIT_DESC_TOOLTIP": "點擊以編輯描述 - {0}",
  "CUSTOM_SNIPPETS_ADD_DESC_TOOLTIP": "點擊以新增描述",
  "CUSTOM_SNIPPETS_EDIT_FILE_EXT_TOOLTIP": "點擊以編輯檔案副檔名 - {0}",
  "CUSTOM_SNIPPETS_ABBR_INPUT_TOOLTIP": "輸入簡短的縮寫（例如「clg」、「fn」、「div」）。這將是用於觸發程式碼片段的輸入內容。",
  "CUSTOM_SNIPPETS_DESC_INPUT_TOOLTIP": "這個程式碼片段功能的簡要描述。如果不需要描述，請留空。",
  "CUSTOM_SNIPPETS_FILE_EXT_INPUT_TOOLTIP": "指定此程式碼片段應可用的檔案類型（例如「.js」、「.html」、「.css」）。留空則適用於所有檔案。",
  "CUSTOM_SNIPPETS_TEMPLATE_INPUT_TOOLTIP": "將插入的實際程式碼。使用 ${1}、${2}、${3} 等表示游標位置。${1} 是初始位置，按下 Tab 鍵會依序移至 ${2}、${3} 等。${0} 是最終位置。",
  "CUSTOM_SNIPPETS_DESC_PLACEHOLDER": "console log 的快捷鍵（選用）",
  "CUSTOM_SNIPPETS_FILE_EXT_PLACEHOLDER": "留空適用於所有檔案，或指定例如 .js、.html",
  "CUSTOM_SNIPPETS_TEMPLATE_PLACEHOLDER": "`console.log(${1});` (維持不變，因其為程式碼)",
  "CUSTOM_SNIPPETS_HEADER_ABBREVIATION": "縮寫",
  "CUSTOM_SNIPPETS_HEADER_TEMPLATE": "範本文字",
  "CUSTOM_SNIPPETS_HEADER_DESCRIPTION": "描述",
  "CUSTOM_SNIPPETS_HEADER_FILE_EXTENSION": "檔案副檔名",
  "CUSTOM_SNIPPETS_DELETE_TOOLTIP": "刪除片段",
  "PROMO_UPGRADE_TITLE": "您已升級至 {0}",
  "PROMO_UPGRADE_MESSAGE": "在接下來的 {0} 天內，您將可享用以下這些進階功能：",
  "PROMO_CARD_1": "在即時預覽中編輯",
  "PROMO_CARD_1_MESSAGE": "直接在即時預覽中編輯內容和元素——剪下、複製、貼上、再製、刪除——完全不中斷您的工作流程。",
  "PROMO_CARD_2": "拖放元素",
  "PROMO_CARD_2_MESSAGE": "以視覺化方式重新排列區塊——在幾秒鐘內嘗試更多版面配置，而無需花費數分鐘編寫程式碼。",
  "PROMO_CARD_3": "素材圖庫",
  "PROMO_CARD_3_MESSAGE": "瀏覽免版稅圖片——懸停可立即預覽，點擊即可套用。更快地嘗試更多選項。",
  "PROMO_CARD_4": "檢查元素版面配置",
  "PROMO_CARD_4_MESSAGE": "在單一視圖中進行設計與檢查——懸停即可查看間距、尺寸和類別。使用尺規參考線，實現像素級的精準對齊。",
  "PROMO_LEARN_MORE": "深入瞭解…",
  "PROMO_UPGRADE_APP_UPSELL_BUTTON": "升級至 {0}",
  "PROMO_PRO_ENDED_TITLE": "{0} 試用已結束",
  "PROMO_PHOENIX_PRO_ENDED_MESSAGE": "感謝您試用 Pro！<b>您現在使用的是免費社群版。</b><br>隨時升級以解鎖以下功能：",
  "PROMO_PRO_UNLOCK_PRO_TITLE": "釋放 {0} 的強大功能",
  "PROMO_PRO_CONTINUE_ON_FREE": "繼續使用免費版",
  "PROMO_PRO_UNLOCK_LIVE_EDIT_TITLE": "使用 {0} 解鎖即時編輯功能",
  "PROMO_PRO_UNLOCK_MESSAGE": "立即訂閱以解鎖以下進階功能：",
  "PROMO_PRO_TRIAL_DAYS_LEFT": "Phoenix Pro 試用版（剩餘 {0} 天）",
  "PRO_TRIAL_ENDING_TITLE": "您的 {0} 升級將於 {1} 天後結束",
  "PRO_TRIAL_ENDING_TITLE_TOMORROW": "您的 {0} 升級將於明天結束",
  "PRO_TRIAL_ENDING_MESSAGE": "我們將在 {0} 天後自動<b>將您切換至免費社群版</b>。<br>立即升級以繼續使用這些 Pro 功能：",
  "PRO_TRIAL_ENDING_MESSAGE_TOMORROW": "我們將於明天自動<b>將您切換至免費社群版</b>。<br>立即升級以繼續使用這些 Pro 功能：",
  "GET_PRO_NOT_NOW": "暫時不要",
  "GET_PHOENIX_PRO": "取得 Phoenix Pro",
  "MANAGE_LICENSE_DIALOG_TITLE": "管理裝置授權",
  "LICENSE_KEY": "授權金鑰",
  "LICENSE_KEY_PLACEHOLDER": "輸入您的授權金鑰…",
  "LICENSE_KEY_ACTIVATE": "啟用授權",
  "LICENSE_KEY_ACTIVATING": "啟用中…",
  "LICENSE_KEY_CURRENT": "目前裝置授權",
  "LICENSE_KEY_CHECKING": "正在檢查授權狀態…",
  "LICENSE_KEY_NONE": "未找到有效的裝置授權",
  "LICENSE_STATUS_ACTIVE": "已啟用",
  "LICENSE_INFO_STATUS_LABEL": "狀態：",
  "LICENSE_INFO_LICENSED_TO_LABEL": "授權給：",
  "LICENSE_INFO_TYPE_LABEL": "授權類型：",
  "LICENSE_INFO_VALID_UNTIL_LABEL": "有效期限：",
  "LICENSE_CHECK_ERROR": "檢查授權狀態時發生錯誤",
  "LICENSE_STATUS_UNKNOWN": "未知",
  "LICENSE_VALID_NEVER": "永久",
  "LICENSE_STATUS_ERROR_CHECK": "檢查授權狀態時發生錯誤",
  "LICENSE_ACTIVATE_SUCCESS": "授權已在全系統啟用。請重新啟動 {APP_NAME} 以讓變更生效。",
  "LICENSE_ACTIVATE_SUCCESS_PARTIAL": "授權僅為您的帳戶啟用 (非全系統)。請重新啟動 {APP_NAME} 以讓變更生效。",
  "LICENSE_ACTIVATE_FAIL": "啟用授權失敗",
  "LICENSE_ACTIVATE_FAIL_APPLY": "無法將授權套用至裝置",
  "LICENSE_ENTER_KEY": "請輸入授權金鑰",
  "LICENSE_REAPPLY_TO_DEVICE": "已啟用？ 全系統重新套用",
  "DEPRECATED_EXTENSIONS_TITLE": "偵測到已棄用的擴充功能",
  "DEPRECATED_EXTENSIONS_MESSAGE": "下列已安裝的擴充功能現已由 {APP_NAME} 原生支援，可從「擴充功能管理員」中安全地解除安裝：",
  "DEPRECATED_EXTENSIONS_LEARN_MORE": "現已內建 — 了解更多",
  "AI_LOGIN_DIALOG_TITLE": "登入以使用 AI 編輯功能",
  "AI_LOGIN_DIALOG_MESSAGE": "請登入以使用 AI 支援的編輯功能",
  "AI_LOGIN_DIALOG_BUTTON": "取得 AI 存取權限",
  "AI_DISABLED_DIALOG_TITLE": "AI 功能已停用",
  "AI_CONTROL_ALL_ALLOWED_NO_CONFIG": "系統中找不到 AI 設定檔。AI 功能已為所有使用者啟用。",
  "AI_CONTROL_ALL_ALLOWED": "AI 功能已為所有使用者啟用。",
  "AI_CONTROL_USER_ALLOWED": "AI 功能已為使用者 ({0}) 啟用，但已為其他使用者停用。",
  "AI_CONTROL_ADMIN_DISABLED": "您的系統管理員已停用 AI 存取權限。",
  "AI_CONTROL_ADMIN_DISABLED_CONTACT": "您的系統管理員已停用 AI 存取權限。如需協助，請聯絡 {0}。",
  "AI_UPSELL_DIALOG_TITLE": "要繼續使用 {0} 嗎？",
  "AI_UPSELL_DIALOG_MESSAGE": "您已發現 {0}。您需要 AI 訂閱或點數才能繼續。",
  "DEMO_SECTION1_TITLE": "即時預覽編輯",
  "DEMO_SECTION1_SUBTITLE": "視覺化編輯頁面 -&nbsp; <b>HTML 即時更新</b>",
  "DEMO_GET_STARTED_BUTTON": "開始使用",
  "DEMO_SECTION2_TITLE": "編輯文字",
  "DEMO_SECTION2_SUBTITLE": "雙擊下方文字以編輯並加入您的姓名",
  "DEMO_EDITABLE_PLACEHOLDER_HELLO": "哈囉 ___",
  "DEMO_SECTION2_SUCCESS_MESSAGE": "您的編輯已更新程式碼 — 使用 <span id=\"undo-shortcut\"></span> 復原，<span id=\"redo-shortcut\"></span> 重做。",
  "DEMO_HINT_COMPLETE_TASK_LABEL": "若要完成此任務：",
  "DEMO_SECTION2_HINT_STEP1": "雙擊「哈囉 ___」文字",
  "DEMO_SECTION2_HINT_STEP2": "將底線取代為您的姓名",
  "DEMO_SECTION2_HINT_STEP3": "按下 Enter 鍵或在外部點擊以套用您的變更",
  "DEMO_SECTION3_TITLE": "即時變更圖片",
  "DEMO_SECTION3_SUBTITLE": "點擊下方的圖片，從圖片庫中選擇您喜歡的圖片來替換它。",
  "DEMO_SECTION3_SUCCESS_URL": "您知道嗎？您可以使用圖片庫中的 <img src=\"images/download.svg\" alt=\"Download\" class=\"inline-icon\"> 下載按鈕來下載圖片。",
  "DEMO_SECTION3_SUCCESS_LOCAL": "您知道嗎？您可以點擊圖片直接使用，無需下載。",
  "DEMO_SECTION3_HINT_STEP1": "點擊圖片以開啟圖片庫（可透過 <img src=\"images/image.svg\" alt=\"Image\" class=\"inline-icon\"> 工具列圖示或雙擊來切換）。",
  "DEMO_SECTION3_HINT_STEP2": "在圖片庫中：將滑鼠懸停在縮圖上即可預覽",
  "DEMO_SECTION3_HINT_STEP3": "點擊縮圖以將其放置在您的頁面上，或點擊 <img src=\"images/download.svg\" alt=\"Download\" class=\"inline-icon\"> 圖示先將其下載",
  "DEMO_SECTION4_TITLE": "視覺化編輯元素",
  "DEMO_SECTION4_SUBTITLE": "複製<img src=\"images/duplicate.svg\" alt=\"Duplicate\" class=\"inline-icon\">下方的卡片，使總數達到 <strong>3 張卡片</strong>，然後<strong>刪除<img src=\"images/trash.svg\" alt=\"Delete\" class=\"inline-icon\"> 1 張卡片</strong>。",
  "DEMO_SECTION4_UNDO_WARNING": "哎呀！所有卡片都已刪除。按下 <strong><span id=\"undo-shortcut-section4\"></span></strong> 來復原。",
  "DEMO_CARD_TITLE": "卡片",
  "DEMO_CARD_SELECT_PARENT_TIP": "點擊上方工具列中的 <img src=\"images/arrowUp.svg\" alt=\"Up\" class=\"inline-icon\">&nbsp;圖示，以選取上層卡片。",
  "DEMO_SECTION4_SUCCESS_MESSAGE": "太棒了！您已學會複製與刪除元素。",
  "DEMO_SECTION4_HINT_STEP1": "點擊卡片以選取",
  "DEMO_SECTION4_HINT_STEP2_DUPLICATE": "使用 <img src=\"images/duplicate.svg\" alt=\"Duplicate\" class=\"inline-icon\"> 按鈕或按下 <strong><span id=\"duplicate-shortcut\"></span></strong> 來複製卡片，直到總共有 3 張為止",
  "DEMO_SECTION4_HINT_STEP3_DELETE": "選取任一張卡片，並使用 <img src=\"images/trash.svg\" alt=\"Delete\" class=\"inline-icon\"> 按鈕或按下 <strong>Delete</strong> 鍵來將其移除",
  "DEMO_SECTION4_HINT_TIP_UNDO_REDO": "提示：您可以用 <strong><span id=\"undo-shortcut-hint\"></span></strong> 來復原，並用 <strong><span id=\"redo-shortcut-hint\"></span></strong> 來重做",
  "DEMO_DELETE_KEY": "刪除",
  "DEMO_SECTION5_TITLE": "拖曳以重新排序元素",
  "DEMO_SECTION5_SUBTITLE": "拖曳任一筆記來變更順序。",
  "DEMO_STICKY_NOTE_FIRST_PLACE": "第一名",
  "DEMO_STICKY_NOTE_SECOND_PLACE": "第二名",
  "DEMO_STICKY_NOTE_THIRD_PLACE": "第三名",
  "DEMO_SECTION5_SUCCESS_MESSAGE": "您可以將元素拖曳至頁面上的任何位置來重新排列。",
  "DEMO_SECTION5_HINT_STEP1": "按住任何便條即可開始拖曳",
  "DEMO_SECTION5_HINT_STEP2": "上下移動以變更順序",
  "DEMO_SECTION5_HINT_STEP3": "放開即可將其放置到新位置",
  "DEMO_SECTION6_TITLE": "編輯連結並預覽您的頁面",
  "DEMO_SECTION6_SUBTITLE": "在工具列中選取 <img src=\"images/link.svg\" alt=\"Link\" class=\"inline-icon\"> 圖示，以變更此連結指向的位置。",
  "DEMO_LINK_EDIT_LINK": "編輯連結",
  "DEMO_SECTION6_SUCCESS_MESSAGE": "您已編輯一個連結。",
  "DEMO_MODE_EXPLANATION_TITLE": "編輯模式與預覽模式",
  "DEMO_EDIT_MODE_LABEL": "編輯模式",
  "DEMO_EDIT_MODE_DESCRIPTION": "在頁面上選取並變更項目",
  "DEMO_PREVIEW_MODE_LABEL": "預覽模式",
  "DEMO_PREVIEW_MODE_DESCRIPTION": "查看訪客將看到的頁面樣式",
  "DEMO_MODE_SWITCH_HINT": "按下 <strong>F8</strong> 或點擊 <span class=\"play-button-hint\"><img src=\"images/playButton.svg\" alt=\"Play\" class=\"play-hint-svg svg-gold\"></span> 按鈕來切換模式。",
  "DEMO_TIPS_LABEL": "提示：",
  "DEMO_SECTION6_TIP1": "點擊任何連結以選取並进行編輯",
  "DEMO_SECTION6_TIP2_NEWTAB": "啟用 <strong>在新分頁中開啟</strong>，即可在獨立分頁中開啟連結。",
  "DEMO_SECTION6_TIP3_PREVIEW": "切換至預覽模式 (<strong>F8</strong>) 以測試連結與互動",
  "DEMO_COMPLETION_TITLE": "您已準備好開始建置！",
  "DEMO_COMPLETION_BODY": "您已學會如何使用即時預覽進行編輯。<br>開啟包含您 HTML 檔案的資料夾以開始編輯。",
  "DEMO_COMPLETION_HELP_PROMPT": "需要更多協助嗎？",
  "DEMO_RESOURCE_YOUTUBE": "YouTube",
  "DEMO_RESOURCE_DOCUMENTATION": "說明文件",
  "DEMO_BONUS_BADGE": "還有一件事",
  "DEMO_SECTION8_TITLE": "使用度量檢查版面配置",
  "DEMO_SECTION8_SUBTITLE": "按一下工具列中的 <img src=\"images/verticalEllipsis.svg\" alt=\"menu\" class=\"inline-icon\"> 並選取<strong>顯示度量</strong>，以查看哪個方塊未對齊。",
  "DEMO_BOX_CLICK_MENU": "按一下 <img src=\"images/verticalEllipsis.svg\" alt=\"menu\" class=\"inline-icon\">",
  "DEMO_BOX_LABEL": "方塊",
  "DEMO_SECTION8_TIP1": "按一下工具列中的 <img src=\"images/verticalEllipsis.svg\" alt=\"更多選項\" class=\"inline-icon\"> 圖示，或按一下右鍵開啟選單",
  "DEMO_SECTION8_TIP2_MEASUREMENTS": "啟用 <strong>顯示測量</strong> 以查看間距與對齊輔助線",
  "DEMO_SECTION8_TIP3": "測量可協助您快速發現對齊問題",
  "DEMO_ALT_EDIT_TEXT": "編輯文字",
  "DEMO_ALT_IMAGE_LIBRARY": "圖片庫",
  "DEMO_ALT_DRAG_AND_DROP": "拖放",
  "DEMO_ALT_LAYOUT_RULERS": "版面配置尺規",
  "DEMO_ALT_REPLACEABLE_IMAGE": "可替換的圖片",
  "DEMO_ALT_DOWNLOAD_ICON": "下載",
  "DEMO_ALT_DUPLICATE_ICON": "整行複製",
  "DEMO_ALT_DELETE_ICON": "刪除",
  "DEMO_ALT_UP_ICON": "上",
  "DEMO_ALT_LINK_ICON": "連結",
  "DEMO_ALT_PLAY_ICON": "播放",
  "DEMO_ALT_MENU_ICON": "選單",
  "DEMO_ALT_MORE_OPTIONS_ICON": "更多選項",
  "DEMO_ALT_CARD_IMAGE": "卡片圖片",
  "DEMO_ALT_ROCKET": "火箭",
  "DEMO_ALT_ARROW": "箭頭",
  "DEMO_CLICK_TO_REPLACE_IMAGE": "點擊以更換",
  "DEMO_JS_BUTTON_BACK": "返回",
  "DEMO_JS_BUTTON_PREVIOUS": "上一步",
  "DEMO_JS_BUTTON_NEXT": "下一步",
  "DEMO_JS_BUTTON_TIP": "提示",
  "DEMO_JS_BUTTON_FINISH": "完成",
  "DEMO_JS_BUTTON_ONE_MORE": "還有一件事",
  "DEMO_JS_BUTTON_START_AGAIN": "重新開始",
  "DEMO_JS_CARD_COUNT_TEMPLATE": "{NUM_DONE}/3 張卡片",
  "DEMO_JS_DELETE_COUNT_TEMPLATE": "{NUM_DONE}/1 已刪除",
  "CMD_PHOENIX_BUILDER_CONNECT": "Phoenix Builder MCP…"
});