/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "Langue par défaut du système",
  "PROJECT_BUSY": "Opérations du projet en cours",
  "DUPLICATING": "Dupliquer {0}",
  "MOVING": "Déménagement {0}",
  "COPYING": "Copie de {0}",
  "DELETING": "Suppression de {0}",
  "RENAMING": "Renommer",
  "STORED_IN_YOUR_BROWSER": "Stocké dans votre navigateur",
  "SUPPORT_US_OPEN_COLLECTIVE": "Soutenez-nous sur Open Collective",
  "GENERIC_ERROR": "(Erreur {0})",
  "NOT_FOUND_ERR": "Fichier/répertoire introuvable.",
  "NOT_READABLE_ERR": "Impossible de lire le fichier/répertoire.",
  "EXCEEDS_MAX_FILE_SIZE": "Les fichiers dont la taille excède {0} Mo ne peuvent pas être ouverts dans {APP_NAME}.",
  "NO_MODIFICATION_ALLOWED_ERR": "Le répertoire cible ne peut pas être modifié.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "Vous n’êtes pas autorisé à effectuer des modifications.",
  "CONTENTS_MODIFIED_ERR": "Le fichier a été modifié dans une application autre que {APP_NAME}.",
  "UNSUPPORTED_ENCODING_ERR": "Format de codage inconnu",
  "ENCODE_FILE_FAILED_ERR": "{APP_NAME} n’a pas pu coder le contenu du fichier.",
  "DECODE_FILE_FAILED_ERR": "{APP_NAME} n’a pas pu décoder le contenu du fichier.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "Actuellement, {APP_NAME} ne prend pas en charge les fichiers texte codés UTF-16.",
  "FILE_EXISTS_ERR": "Le fichier ou le répertoire existe déjà.",
  "FILE": "fichier",
  "FILE_TITLE": "Fichier",
  "DIRECTORY": "répertoire",
  "DIRECTORY_TITLE": "Répertoire",
  "DIRECTORY_NAMES_LEDE": "noms de répertoires",
  "FILENAMES_LEDE": "noms de fichiers",
  "FILENAME": "Nom de fichier",
  "DIRECTORY_NAME": "Nom du répertoire",
  "ERROR_LOADING_PROJECT": "Erreur lors du chargement du projet",
  "OPEN_DIALOG_ERROR": "Une erreur s’est produite lors de l’affichage de la boîte de dialogue Ouvrir. (Erreur {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "Une erreur s’est produite lors de la tentative de chargement du répertoire <span class='dialog-filename'>{0}</span>. (Erreur {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "Une erreur s’est produite lors de la lecture du contenu du répertoire <span class='dialog-filename'>{0}</span>. (Erreur {1})",
  "ZOOM_WITH_SHORTCUTS": "Utiliser les raccourcis clavier pour zoomer",
  "ZOOM_WITH_SHORTCUTS_DETAILS": "Veuillez utiliser les raccourcis clavier <code><i>{0}</i></code> pour effectuer un zoom avant et <code><i>{1}</i></code> pour effectuer un zoom arrière.",
  "ERROR_OPENING_FILE_TITLE": "Erreur lors de l’ouverture du fichier",
  "ERROR_OPENING_FILE": "Une erreur s’est produite lors de la tentative d’ouverture du fichier <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_OPENING_FILES": "Une erreur s’est produite en tentant d’ouvrir les fichiers suivants :",
  "ERROR_RELOADING_FILE_TITLE": "Erreur lors du rechargement des modifications à partir du disque",
  "ERROR_RELOADING_FILE": "Une erreur s’est produite lors de la tentative de rechargement du fichier <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_SAVING_FILE_TITLE": "Erreur lors de l’enregistrement du fichier",
  "ERROR_SAVING_FILE": "Une erreur s’est produite lors de la tentative d’enregistrement du fichier <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_FILE_TITLE": "Erreur lors du changement de nom du {0}",
  "ERROR_RENAMING_FILE": "Une erreur s’est produite lors de la tentative de changement de nom du {2} <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "Le fichier ou le répertoire ne fait pas partie du projet actuellement ouvert. Or, seuls les fichiers appartenant au projet peuvent être renommés à ce stade.",
  "ERROR_MOVING_FILE_TITLE": "Erreur lors du déplacement de l’élément {0}",
  "ERROR_MOVING_FILE": "Une erreur s’est produite lors du déplacement de l’élément {2} <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "Impossible de déplacer le fichier/dossier, car ils ne font pas partie du projet en cours.",
  "ERROR_DELETING_FILE_TITLE": "Erreur lors de la suppression du {0}",
  "ERROR_DELETING_FILE": "Une erreur s’est produite lors de la tentative de suppression du {2} <span class='dialog-filename'>{0}</span>. {1}",
  "INVALID_FILENAME_TITLE": "{0} non valide",
  "CANNOT_PASTE_TITLE": "Impossible de coller {0}",
  "CANNOT_DOWNLOAD_TITLE": "Impossible de télécharger {0}",
  "ERR_TYPE_DOWNLOAD_FAILED": "Une erreur s&#39;est produite lors du téléchargement de <span class='dialog-filename'>{0}</span>",
  "ERR_TYPE_PASTE_FAILED": "Une erreur s&#39;est produite lors du collage de <span class='dialog-filename'>{0}</span> dans <span class='dialog-filename'>{1}</span>",
  "CANNOT_DUPLICATE_TITLE": "Impossible de dupliquer",
  "ERR_TYPE_DUPLICATE_FAILED": "Une erreur s&#39;est produite lors de la duplication de <span class='dialog-filename'>{0}</span>",
  "ERR_TYPE_DUPLICATE_FAILED_NO_FILE": "Veuillez sélectionner un fichier à dupliquer.",
  "INVALID_FILENAME_MESSAGE": "Les {0} ne peuvent pas utiliser de termes réservés au système, finir par un point (.) ou contenir l’un des caractères suivants : <code class='emphasized'>{1}</code>",
  "ENTRY_WITH_SAME_NAME_EXISTS": "Il existe déjà un fichier ou un répertoire portant le nom <span class='dialog-filename'>{0}</span>.",
  "ERROR_CREATING_FILE_TITLE": "Erreur lors de la création de l’élément {0}",
  "ERROR_CREATING_FILE": "Une erreur s’est produite lors de la tentative de création du {0} <span class='dialog-filename'>{1}</span>. {2}",
  "ERROR_MIXED_DRAGDROP": "Impossible d’ouvrir un dossier en même temps que d’autres fichiers.",
  "ERROR_KEYMAP_TITLE": "Erreur lors de la lecture du mappage de touches utilisateur",
  "ERROR_KEYMAP_CORRUPT": "Votre fichier de mappage de touches n’est pas un fichier JSON valide. Il va s’ouvrir afin que vous puissiez corriger le format.",
  "ERROR_LOADING_KEYMAP": "Votre fichier de mappage de touches n’étant pas un fichier texte codé en UTF-8 valide, il ne peut pas être chargé.",
  "ERROR_RESTRICTED_COMMANDS": "Vous ne pouvez pas réaffecter de raccourcis à ces commandes : {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "Vous ne pouvez pas réaffecter ces raccourcis : {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "Vous réaffectez plusieurs raccourcis à ces commandes : {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "Plusieurs liaisons ont été définies pour les raccourcis suivants : {0}",
  "ERROR_INVALID_SHORTCUTS": "Ces raccourcis ne sont pas valides : {0}",
  "ERROR_NONEXISTENT_COMMANDS": "Vous affectez des raccourcis à des commandes qui n'existent pas : {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "Erreur lors de la lecture des préférences",
  "ERROR_PREFS_PROJECT_LINT": "Préférences du projet",
  "ERROR_PREFS_PROJECT_LINT_MESSAGE": "Erreur : le projet contient à la fois les fichiers `.brackets.json` et `.phcode.json`, provoquant un conflit. Veuillez supprimer « .brackets.json » ou « .phcode.json », puis recharger le projet.",
  "ERROR_PREFS_CORRUPT": "Votre fichier de préférences n’est pas un fichier JSON valide, il va donc être ouvert afin que vous puissiez corriger le format. Vous devrez ensuite redémarrer {APP_NAME} pour que les modifications prennent effet.",
  "ERROR_PROJ_PREFS_CORRUPT": "Votre fichier de préférences de projet n’est pas un fichier JSON valide, il va donc être ouvert afin que vous puissiez corriger le format. Vous devrez ensuite recharger le projet pour que les modifications prennent effet.",
  "ERROR_IN_BROWSER_TITLE": "Malheureusement, {APP_NAME} n’est pas encore compatible avec les navigateurs.",
  "ERROR_IN_BROWSER": "{APP_NAME} est défini en HTML, mais il s’exécute actuellement en tant qu’application de bureau, vous pouvez donc l’utiliser afin de modifier des fichiers locaux. Utilisez l’interpréteur de commandes d’application situé dans le référentiel <b>github.com/adobe/brackets-shell</b> afin d’exécuter {APP_NAME}.",
  "ERROR_MAX_FILES_TITLE": "Erreur lors de l’indexation des fichiers",
  "ERROR_MAX_FILES": "Ce projet contient plus de 30 000 fichiers. Les fonctionnalités qui s’appliquent de manière globale à plusieurs fichiers peuvent être désactivées ou se comporter comme si le projet était vide. <a href='https://github.com/adobe/brackets/wiki/Large-Projects'>En savoir plus sur l’utilisation de projets volumineux</a>.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "Erreur lors du lancement du navigateur",
  "ERROR_CANT_FIND_CHROME": "Le navigateur Google Chrome est introuvable. Assurez-vous qu’il est installé.",
  "ERROR_LAUNCHING_BROWSER": "Une erreur s’est produite lors du lancement du navigateur. (Erreur {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "Erreur du module Aperçu en direct",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "Connexion au navigateur",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "Pour que le module Aperçu en direct puisse se connecter, vous devez relancer Chrome en activant la fonction de débogage à distance.<br /><br />Voulez-vous relancer Chrome et activer le débogage à distance ?<br /><br />",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "Impossible de charger la page Aperçu en direct.",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "Pour lancer l’Aperçu en direct avec un fichier de serveur, vous devez indiquer une URL de base pour ce projet.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "Une erreur s’est produite au démarrage du serveur HTTP pour les fichiers d’aperçu en direct. Veuillez réessayer.",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "Pour plus d’informations, consultez la page <a href='{0}' title='{0}'>Résolution des erreurs de connexion à l’Aperçu en direct</a>.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "Aperçu en direct",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "Aperçu en direct : Connexion…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "Aperçu en direct : Initialisation…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "Serveur de prévisualisation en direct actif",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "Aperçu en direct",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "Sélectionnez le fichier pour l'aperçu en direct",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "Rafraîchir la page",
  "LIVE_DEV_TOGGLE_LIVE_HIGHLIGHT": "Basculer les faits saillants de l'aperçu en direct",
  "LIVE_DEV_CLICK_POPOUT": "Aperçu instantané en direct dans une nouvelle fenêtre",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "Épingler sur la page d'aperçu de détachement",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "Aperçu en direct (échec de la mise à jour en raison d’une erreur de syntaxe)",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "Aperçu en direct annulé car les outils de développement du navigateur étaient ouverts",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "Aperçu en direct annulé car la page a été fermée dans le navigateur",
  "LIVE_DEV_NAVIGATED_AWAY": "Aperçu en direct annulé car le navigateur a accédé à une page qui ne fait pas partie du projet actuel",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "Aperçu en direct annulé pour une raison inconnue ({0})",
  "SAVE_CLOSE_TITLE": "Enregistrer les modifications",
  "SAVE_CLOSE_MESSAGE": "Souhaitez-vous enregistrer les modifications apportées au document <span class='dialog-filename'>{0}</span> ?",
  "SAVE_CLOSE_MULTI_MESSAGE": "Souhaitez-vous enregistrer les modifications apportées aux fichiers suivants ?",
  "EXT_MODIFIED_TITLE": "Modifications externes",
  "CONFIRM_DELETE_TITLE": "Confirmer la suppression",
  "CONFIRM_FILE_DELETE": "Souhaitez-vous vraiment supprimer le fichier <span class='dialog-filename'>{0}</span> ?",
  "CONFIRM_FOLDER_DELETE": "Voulez-vous vraiment supprimer le dossier <span class='dialog-filename'>{0}</span> ?",
  "FILE_DELETED_TITLE": "Fichier supprimé",
  "EXT_MODIFIED_WARNING": "<span class='dialog-filename'>{0}</span> a été modifié sur le disque, dans une application autre que {APP_NAME}.<br /><br />Voulez-vous enregistrer le fichier et remplacer ces modifications ?",
  "EXT_MODIFIED_MESSAGE": "Le fichier <span class='dialog-filename'>{0}</span> a été modifié sur le disque dans une autre application que {APP_NAME} mais présente également des modifications non enregistrées dans {APP_NAME}.<br /><br />Quelle version souhaitez-vous conserver ?",
  "EXT_DELETED_MESSAGE": "Le fichier <span class='dialog-filename'>{0}</span> a été supprimé du disque dans une autre application que {APP_NAME} mais présente également des modifications non enregistrées dans {APP_NAME}.<br /><br />Souhaitez-vous conserver vos modifications ?",
  "EXT_ALWAYS_MODIFIED_BUTTON_TOOLTIP": "Toujours écraser les fichiers jusqu'au changement de projet ou au redémarrage",
  "WINDOW_UNLOAD_WARNING": "Voulez-vous vraiment accéder à une autre URL et quitter {APP_NAME} ?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "Vous avez des changements non enregistrés! Voulez-vous vraiment accéder à une autre URL et quitter {APP_NAME} ?",
  "DONE": "Terminé",
  "OK": "OK",
  "CANCEL": "Annuler",
  "DONT_SAVE": "Ne pas enregistrer",
  "SAVE": "Enregistrer",
  "SAVE_AS": "Enregistrer sous…",
  "SAVE_AND_OVERWRITE": "Remplacer",
  "ALWAYS_OVERWRITE": "Toujours écraser",
  "DELETE": "Supprimer",
  "BUTTON_YES": "Oui",
  "BUTTON_NO": "Non",
  "FIND_MATCH_INDEX": "{0} sur {1}",
  "FIND_NO_RESULTS": "Aucun résultat",
  "FIND_QUERY_PLACEHOLDER": "Rechercher…",
  "FIND_HISTORY_MAX_COUNT": "Nombre maximal d'éléments de recherche dans l'historique des recherches",
  "REPLACE_PLACEHOLDER": "Remplacer par…",
  "BUTTON_REPLACE_ALL": "Tout remplacer",
  "BUTTON_REPLACE_BATCH": "Traiter par lots…",
  "BUTTON_REPLACE_ALL_IN_FILES": "Remplacer…",
  "BUTTON_REPLACE": "Remplacer",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "Correspondance suivante",
  "BUTTON_PREV_HINT": "Correspondance précédente",
  "BUTTON_CASESENSITIVE_HINT": "Respecter la casse",
  "BUTTON_REGEXP_HINT": "Expression régulière",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "Remplacer sans possibilité d’annuler",
  "REPLACE_WITHOUT_UNDO_WARNING": "Dans la mesure où le nombre de fichiers à modifier excède {0}, {APP_NAME} va modifier des fichiers non ouverts sur le disque.<br />Vous ne pourrez pas annuler les remplacements effectués dans ces fichiers.",
  "BUTTON_REPLACE_WITHOUT_UNDO": "Remplacer sans possibilité d’annuler",
  "OPEN_FILE": "Ouvrir le fichier",
  "SAVE_FILE_AS": "Enregistrer le fichier",
  "CHOOSE_FOLDER": "Choisir un dossier",
  "RELEASE_NOTES": "Notes de mise à jour",
  "NO_UPDATE_TITLE": "Vos logiciels sont à jour !",
  "NO_UPDATE_MESSAGE": "Vous utilisez la dernière version de {APP_NAME}.",
  "FIND_REPLACE_TITLE_LABEL": "Remplacer",
  "FIND_REPLACE_TITLE_WITH": "par",
  "FIND_TITLE_LABEL": "Occurrences trouvées pour",
  "FIND_TITLE_SUMMARY": "&mdash; {0} {1} {2} dans {3}",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "dans <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_NO_SCOPE": "dans le projet",
  "FIND_IN_FILES_ZERO_FILES": "Le filtre exclut tous les fichiers {0}",
  "FIND_IN_FILES_FILE": "fichier",
  "FIND_IN_FILES_FILES": "fichiers",
  "FIND_IN_FILES_MATCH": "résultat",
  "FIND_IN_FILES_MATCHES": "résultats",
  "FIND_IN_FILES_MORE_THAN": "Plus de ",
  "FIND_IN_FILES_PAGING": "{0}&mdash;{1}",
  "FIND_IN_FILES_FILE_PATH": "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "Cliquer tout en appuyant sur Ctrl/Cmd pour tout développer/tout réduire",
  "FIND_IN_FILES_INDEXING": "Indexation pour la recherche instantanée…",
  "FIND_IN_FILES_SEARCHING": "Recherche de fichiers…",
  "FIND_IN_FILES_SEARCHING_IN": "Dans {0}",
  "FIND_IN_FILES_INDEXING_PROGRESS": "Indexation de {0} fichiers sur {1} pour la recherche instantanée…",
  "REPLACE_IN_FILES_ERRORS_TITLE": "Erreurs de remplacement",
  "REPLACE_IN_FILES_ERRORS": "Les fichiers suivants n’ont pas été traités car ils ont été modifiés après l’opération de recherche ou ne sont pas accessibles en écriture.",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "Erreur de récupération des informations de mise à jour",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "Un problème est survenu lors de la récupération des dernières informations de mise à jour sur le serveur. Vérifiez que vous êtes connecté à Internet et réessayez.",
  "NEW_FILE_FILTER": "Nouveau jeu d’exclusion…",
  "CLEAR_FILE_FILTER": "Ne pas exclure les fichiers",
  "NO_FILE_FILTER": "Aucun fichier exclu",
  "EXCLUDE_FILE_FILTER": "Exclure des fichiers",
  "INCLUDE_FILE_FILTER": "Rechercher dans les fichiers",
  "FILTER_PLACEHOLDER": "par exemple. index,.css,*.js,src/**/*.css",
  "FILTER_HISTORY_TOOLTIP": "Appuyez sur « Ctrl-Espace » pour afficher l'historique.",
  "FILTER_HISTORY_TOOLTIP_MAC": "Appuyez sur « Cmd-Espace » pour afficher l'historique.",
  "FIND_HISTORY_TOOLTIP": "Appuyez sur « Ctrl-Espace » pour afficher l'historique.",
  "FIND_HISTORY_TOOLTIP_MAC": "Appuyez sur « Cmd-Espace » pour afficher l'historique.",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "Fonction Édition rapide non disponible pour la position actuelle du curseur",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "Édition rapide CSS : placez le curseur sur un seul nom de classe",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "Édition rapide CSS : attribut de classe incomplet",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "Édition rapide CSS : attribut d’ID incomplet",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "Édition rapide CSS : placez le curseur dans la balise, la classe ou l’ID",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "Édition rapide des fonctions de temporisation CSS : syntaxe incorrecte",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "Édition rapide JS : placez le curseur dans le nom de fonction",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "Fonction Documentation rapide non disponible pour la position actuelle du curseur",
  "PROJECT_LOADING": "Chargement…",
  "UNTITLED": "Sans titre",
  "WORKING_FILES": "Fichiers de travail",
  "TOP": "Haut",
  "BOTTOM": "Bas",
  "LEFT": "Gauche",
  "RIGHT": "Droite",
  "CMD_SPLITVIEW_NONE": "Pas de fractionnement",
  "CMD_SPLITVIEW_VERTICAL": "Fractionnement vertical",
  "CMD_SPLITVIEW_HORIZONTAL": "Fractionnement horizontal",
  "SPLITVIEW_MENU_TOOLTIP": "Fractionner l’éditeur horizontalement ou verticalement",
  "GEAR_MENU_TOOLTIP": "Configurer l’ensemble de travail",
  "SPLITVIEW_INFO_TITLE": "Déjà ouvert",
  "SPLITVIEW_MULTIPANE_WARNING": "Ce fichier est déjà ouvert dans un autre volet. Il sera bientôt possible d’ouvrir un même fichier dans plusieurs volets de l’application {APP_NAME}, mais en attendant, vous ne pouvez consulter le fichier que dans le volet dans lequel il est déjà ouvert.<br /><br />(Ce message ne s’affichera qu’une fois.)",
  "KEYBOARD_OVERLAY_TEXT": "Utilisez les flèches pour naviguer ou tapez pour sélectionner les éléments de l'interface utilisateur.",
  "KEYBOARD_SHORTCUT_CHANGE_TITLE": "Modifier le raccourci clavier…",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_TITLE": "Modifier le raccourci clavier",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_TEXT": "Appuyez sur la nouvelle combinaison de touches pour <b>« {0} »</b> (Actuel :<b> {1}</b> )",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_DUPLICATE": "Attention : La combinaison de touches <b>{0}</b> est déjà attribuée à <b>&#39;{1}&#39;</b> . Réaffecter à <b>&#39;{2}&#39;</b> ?",
  "KEYBOARD_SHORTCUT_ASSIGN": "Attribuer",
  "KEYBOARD_SHORTCUT_NONE": "Aucun",
  "KEYBOARD_SHORTCUT_MENU_SHOW_SHORTCUTS": "Raccourcis clavier…",
  "KEYBOARD_SHORTCUT_MENU_SHOW_SHORTCUTS_BUTTON": "Afficher tous les raccourcis…",
  "KEYBOARD_SHORTCUT_TABLE_BASE_KEY": "Clé de base",
  "KEYBOARD_SHORTCUT_TABLE_KEY_BINDING": "Raccourci",
  "KEYBOARD_SHORTCUT_TABLE_COMMAND_ID": "ID de commande",
  "KEYBOARD_SHORTCUT_TABLE_COMMAND_NAME": "Commande",
  "KEYBOARD_SHORTCUT_TABLE_DOUBLE_CLICK": "Double-cliquez pour changer de raccourci",
  "KEYBOARD_SHORTCUT_TABLE_ORIGIN": "Origine",
  "KEYBOARD_SHORTCUT_ORIG_EXTENSION": "Extension",
  "KEYBOARD_SHORTCUT_PANEL_TITLE": "Raccourcis clavier",
  "KEYBOARD_SHORTCUT_PANEL_FILTER": "Filtrer…",
  "KEYBOARD_SHORTCUT_PANEL_RESET": "Réinitialiser…",
  "KEYBOARD_SHORTCUT_PANEL_RESET_DEFAULT": "Réinitialiser les raccourcis par défaut…",
  "KEYBOARD_SHORTCUT_RESET_DIALOG_TITLE": "Réinitialiser les raccourcis clavier",
  "KEYBOARD_SHORTCUT_RESET_DIALOG_MESSAGE": "Réinitialiser tous les raccourcis personnalisés par défaut ? Ça ne peut pas être annulé.",
  "STATUSBAR_CURSOR_POSITION": "Ligne {0}, colonne {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": " — {0} colonne sélectionnée",
  "STATUSBAR_SELECTION_CH_PLURAL": " — {0} colonnes sélectionnées",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " — {0} ligne sélectionnée",
  "STATUSBAR_SELECTION_LINE_PLURAL": " — {0} lignes sélectionnées",
  "STATUSBAR_SELECTION_MULTIPLE": " — {0} sélections",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "Cliquez ici pour remplacer la mise en retrait par des espaces.",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "Cliquez ici pour remplacer la mise en retrait par des tabulations.",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "Cliquez ici pour changer le nombre d’espaces utilisés lors de la mise en retrait.",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "Cliquez ici pour modifier la largeur du caractère de tabulation.",
  "STATUSBAR_SPACES": "Espaces :",
  "STATUSBAR_TAB_SIZE": "Taille de tabulation :",
  "STATUSBAR_LINE_COUNT_SINGULAR": "— {0} ligne",
  "STATUSBAR_LINE_COUNT_PLURAL": "— {0} lignes",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "Extensions désactivées",
  "STATUSBAR_INSERT": "INS",
  "STATUSBAR_OVERWRITE": "RFP",
  "STATUSBAR_INSOVR_TOOLTIP": "Cliquez pour faire passer le curseur du mode Insertion (INS) au mode Remplacement (RFP) ou inversement",
  "STATUSBAR_LANG_TOOLTIP": "Cliquez pour modifier le type de fichier",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. Cliquez pour afficher/masquer le panneau des rapports.",
  "STATUSBAR_DEFAULT_LANG": "(par défaut)",
  "STATUSBAR_SET_DEFAULT_LANG": "Utiliser par défaut pour les fichiers .{0}",
  "STATUSBAR_ENCODING_TOOLTIP": "Sélectionner le codage",
  "STATUSBAR_TASKS": "Tâches",
  "STATUSBAR_TASKS_TOOLTIP": "Gérer les tâches actives",
  "STATUSBAR_TASKS_HIDE_SPINNER": "Masquer l'icône de la roulette",
  "STATUSBAR_TASKS_UNKNOWN_EXTENSION_TASK": "Tâche d'extension inconnue…",
  "STATUSBAR_TASKS_PLAY": "Démarrer ou reprendre",
  "STATUSBAR_TASKS_PAUSE": "Pause",
  "STATUSBAR_TASKS_STOP": "Arrêt",
  "STATUSBAR_TASKS_RESTART": "Recommencer",
  "ERRORS_PANEL_TITLE_MULTIPLE": "{0} problèmes",
  "SINGLE_ERROR": "1 problème {0}",
  "MULTIPLE_ERRORS": "{1} problèmes {0}",
  "NO_ERRORS": "Aucun problème {0} détecté, félicitations !",
  "NO_ERRORS_MULTIPLE_PROVIDER": "Aucun problème détecté, félicitations !",
  "LINT_DISABLED": "L’analyse lint est désactivée",
  "NO_LINT_AVAILABLE": "Aucun programme lint disponible pour {0}",
  "NOTHING_TO_LINT": "Rien à analyser",
  "LINTER_TIMED_OUT": "Délai dépassé pour {0} après une attente de {1} ms",
  "LINTER_FAILED": "{0} arrêté avec l’erreur suivante : {1}",
  "FILE_MENU": "Fichier",
  "CMD_FILE_NEW_UNTITLED": "Nouveau",
  "CMD_FILE_NEW": "Nouveau fichier",
  "CMD_FILE_DUPLICATE": "Dupliquer",
  "CMD_FILE_DUPLICATE_FILE": "Fichier en double",
  "CMD_FILE_DOWNLOAD_PROJECT": "Télécharger le projet",
  "CMD_FILE_DOWNLOAD": "Télécharger",
  "CMD_FILE_CUT": "Couper",
  "CMD_FILE_COPY": "Copier",
  "CMD_FILE_COPY_PATH": "Copier le chemin",
  "CMD_FILE_PASTE": "Coller",
  "CMD_PROJECT_NEW": "Nouveau projet…",
  "CMD_FILE_NEW_FOLDER": "Nouveau dossier",
  "CMD_FILE_OPEN": "Ouvrir des fichiers…",
  "CMD_RECENT_FILES_OPEN": "Fichiers récents…",
  "CMD_ADD_TO_WORKING_SET": "Ouvrir dans l’ensemble de travail",
  "CMD_OPEN_DROPPED_FILES": "Ouvrir les fichiers déposés",
  "CMD_OPEN_FOLDER": "Ouvrir un dossier…",
  "CMD_FILE_CLOSE": "Fermer",
  "CMD_FILE_CLOSE_ALL": "Tout fermer",
  "CMD_FILE_CLOSE_LIST": "Fermer la liste",
  "CMD_FILE_CLOSE_OTHERS": "Fermer tous les autres",
  "CMD_FILE_CLOSE_ABOVE": "Fermer les autres au-dessus",
  "CMD_FILE_CLOSE_BELOW": "Fermer les autres en dessous",
  "CMD_FILE_SAVE": "Enregistrer le fichier",
  "CMD_FILE_SAVE_ALL": "Enregistrer tout",
  "CMD_FILE_SAVE_AS": "Enregistrer sous…",
  "CMD_LIVE_FILE_PREVIEW": "Aperçu en direct",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "Activer la version expérimentale de l’Aperçu en direct",
  "CMD_RELOAD_LIVE_PREVIEW": "Forcer le rechargement de l’aperçu en direct",
  "CMD_PROJECT_SETTINGS": "Paramètres du projet…",
  "CMD_FILE_RENAME": "Renommer",
  "CMD_FILE_DELETE": "Supprimer",
  "CMD_INSTALL_EXTENSION": "Installer une extension…",
  "CMD_EXTENSION_MANAGER": "Gestionnaire d'extensions…",
  "CMD_FILE_REFRESH": "Actualiser l’arborescence de fichiers",
  "CMD_FILE_SHOW_FOLDERS_FIRST": "Trier les dossiers en premier",
  "CMD_QUIT": "Quitter",
  "CMD_EXIT": "Quitter",
  "EDIT_MENU": "Modifier",
  "CMD_UNDO": "Annuler",
  "CMD_REDO": "Répéter",
  "CMD_CUT": "Couper",
  "CMD_COPY": "Copier",
  "CMD_PASTE": "Coller",
  "CMD_SELECT_ALL": "Sélectionner tout",
  "CMD_SELECT_LINE": "Sélectionner la ligne",
  "CMD_SPLIT_SEL_INTO_LINES": "Scinder la sélection en lignes",
  "CMD_ADD_CUR_TO_NEXT_LINE": "Ajouter un curseur à la ligne suivante",
  "CMD_ADD_CUR_TO_PREV_LINE": "Ajouter un curseur à la ligne précédente",
  "CMD_INDENT": "Retrait",
  "CMD_UNINDENT": "Annuler le retrait",
  "CMD_DUPLICATE": "Dupliquer",
  "CMD_DELETE_LINES": "Supprimer la ligne",
  "CMD_COMMENT": "Activer/Désactiver le commentaire de ligne",
  "CMD_BLOCK_COMMENT": "Commenter les blocs/Annuler les commentaires",
  "CMD_LINE_UP": "Déplacer la ligne vers le haut",
  "CMD_LINE_DOWN": "Déplacer la ligne vers le bas",
  "CMD_OPEN_LINE_ABOVE": "Ouvrir une ligne au-dessus",
  "CMD_OPEN_LINE_BELOW": "Ouvrir une ligne en dessous",
  "CMD_TOGGLE_CLOSE_BRACKETS": "Fermeture automatique des accolades",
  "CMD_SHOW_CODE_HINTS": "Afficher les indicateurs de code",
  "CMD_BEAUTIFY_CODE": "Embellir le code",
  "CMD_BEAUTIFY_CODE_ON_SAVE": "Embellir le code après l'enregistrement",
  "FIND_MENU": "Rechercher",
  "CMD_FIND": "Rechercher",
  "CMD_FIND_NEXT": "Rechercher suivant",
  "CMD_FIND_PREVIOUS": "Rechercher précédent",
  "CMD_FIND_ALL_AND_SELECT": "Sélectionner toutes les occurrences",
  "CMD_ADD_NEXT_MATCH": "Ajouter l'occurrence suivante",
  "CMD_SKIP_CURRENT_MATCH": "Ignorer et ajouter l'occurrence suivante",
  "CMD_FIND_IN_FILES": "Rechercher dans les fichiers",
  "CMD_FIND_IN_SUBTREE": "Rechercher dans…",
  "CMD_REPLACE": "Remplacer",
  "CMD_REPLACE_IN_FILES": "Remplacer dans les fichiers",
  "CMD_REPLACE_IN_SUBTREE": "Remplacer dans…",
  "VIEW_MENU": "Affichage",
  "CMD_HIDE_SIDEBAR": "Masquer la barre latérale",
  "CMD_SHOW_SIDEBAR": "Afficher la barre latérale",
  "CMD_TOGGLE_SIDEBAR": "Afficher/Masquer la barre latérale",
  "CMD_TOGGLE_PANELS": "Afficher/Masquer les panneaux",
  "CMD_TOGGLE_PURE_CODE": "Pas de distraction",
  "CMD_TOGGLE_FULLSCREEN": "Plein écran",
  "CMD_ZOOM_UI": "Interface utilisateur et polices de zoom",
  "CMD_ZOOM_IN": "Agrandir",
  "CMD_ZOOM_IN_SCALE": "Zoom avant (actuel : {0} %)",
  "CMD_ZOOM_OUT": "Dézoomer",
  "CMD_INCREASE_FONT_SIZE": "Augmenter la taille de la police",
  "CMD_DECREASE_FONT_SIZE": "Diminuer la taille de la police",
  "CMD_RESTORE_FONT_SIZE": "Restaurer la taille de la police",
  "CMD_SCROLL_LINE_UP": "Faire défiler d’une ligne vers le haut",
  "CMD_SCROLL_LINE_DOWN": "Faire défiler d’une ligne vers le bas",
  "CMD_TOGGLE_LINE_NUMBERS": "Numéros de ligne",
  "CMD_TOGGLE_ACTIVE_LINE": "Surligner la ligne active",
  "CMD_TOGGLE_WORD_WRAP": "Renvoi à la ligne",
  "CMD_LIVE_HIGHLIGHT": "Surlignement dans l’Aperçu en direct",
  "CMD_VIEW_TOGGLE_INSPECTION": "Effectuer une analyse lint des fichiers à l’enregistrement",
  "CMD_WORKINGSET_SORT_BY_ADDED": "Trier par date d’ajout",
  "CMD_WORKINGSET_SORT_BY_NAME": "Trier par nom",
  "CMD_WORKINGSET_SORT_BY_TYPE": "Trier par type",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "Tri automatique",
  "CMD_THEMES": "Thèmes…",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "Fermer automatiquement la recherche",
  "CMD_KEYBOARD_NAV_OVERLAY": "Palette de commandes visuelles",
  "NAVIGATE_MENU": "Naviguer",
  "CMD_QUICK_OPEN": "Ouverture rapide",
  "CMD_GOTO_LINE": "Atteindre la ligne",
  "CMD_GOTO_DEFINITION": "Accès rapide à la définition",
  "CMD_GOTO_DEFINITION_PROJECT": "Accès rapide à la définition dans le projet",
  "CMD_GOTO_FIRST_PROBLEM": "Accéder au premier problème",
  "CMD_TOGGLE_QUICK_EDIT": "Édition rapide",
  "CMD_TOGGLE_QUICK_DOCS": "Documentation rapide",
  "CMD_QUICK_EDIT_PREV_MATCH": "Élément de modification rapide précédent",
  "CMD_QUICK_EDIT_NEXT_MATCH": "Élément de modification rapide suivant",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "Nouvelle règle",
  "CMD_NEXT_DOC": "Document suivant",
  "CMD_PREV_DOC": "Document précédent",
  "CMD_NAVIGATE_BACKWARD": "Naviguer vers l’arrière",
  "CMD_NAVIGATE_FORWARD": "Naviguer vers l’avant",
  "CMD_NEXT_DOC_LIST_ORDER": "Document suivant de la liste",
  "CMD_PREV_DOC_LIST_ORDER": "Document précédent de la liste",
  "CMD_SHOW_IN_TREE": "Afficher dans l’arborescence de fichiers",
  "CMD_SHOW_IN_EXPLORER": "Afficher dans l’Explorateur",
  "CMD_SHOW_IN_FINDER": "Afficher dans le Finder",
  "CMD_SHOW_IN_OS": "Afficher dans les fichiers du système d'exploitation",
  "CMD_SWITCH_PANE_FOCUS": "Changer de volet actif",
  "CMD_OPEN_VFS": "Ouvrir le système de fichiers virtuel",
  "CMD_DIAGNOSTIC_TOOLS": "{APP_NAME} Outils de diagnostic",
  "CMD_OPEN_EXTENSIONS_FOLDER": "Ouvrir le dossier des extensions…",
  "CMD_OPEN_VIRTUAL_SERVER": "Ouvrir le serveur virtuel",
  "HELP_MENU": "Aide",
  "CMD_CHECK_FOR_UPDATE": "Vérifiez les mises à jour…",
  "CMD_AUTO_UPDATE": "Mise à jour automatique",
  "CMD_HOW_TO_USE_BRACKETS": "Comment utiliser {APP_NAME}",
  "CMD_SUPPORT": "Assistance {APP_NAME}",
  "CMD_SUGGEST": "Suggérer une fonctionnalité",
  "CMD_RELEASE_NOTES": "Notes de mise à jour",
  "CMD_GET_INVOLVED": "Participer",
  "CMD_SHOW_EXTENSIONS_FOLDER": "Afficher le dossier d’extensions",
  "CMD_HEALTH_DATA_STATISTICS": "Bilan de santé…",
  "CMD_HOMEPAGE": "Page d'accueil - Télécharger des applications",
  "CMD_TWITTER": "{TWITTER_NAME} sur Twitter",
  "CMD_ABOUT": "À propos de {APP_TITLE}",
  "CMD_OPEN_PREFERENCES": "Ouvrir le fichier de préférences",
  "CMD_OPEN_KEYMAP": "Ouvrir le fichier de mappage de clés utilisateur",
  "EXPERIMENTAL_BUILD": "version expérimentale",
  "RELEASE_BUILD": "édition",
  "DEVELOPMENT_BUILD": "version de développement",
  "PRERELEASE_BUILD": "version préliminaire",
  "RELOAD_FROM_DISK": "Recharger à partir du disque",
  "KEEP_CHANGES_IN_EDITOR": "Conserver les modifications dans l’éditeur",
  "CLOSE_DONT_SAVE": "Fermer (sans enregistrer)",
  "RELAUNCH_CHROME": "Relancer Chrome",
  "ABOUT": "À propos",
  "CLOSE": "Fermer",
  "ABOUT_TEXT_LINE1": "Version {VERSION_MAJOR}.{VERSION_MINOR} {BUILD_TYPE} {VERSION}",
  "ABOUT_TEXT_BUILD_TIMESTAMP": "horodatage de construction :",
  "ABOUT_TEXT_LINE3": "Bibliothèques tierces que nous utilisons - <a href='https://github.com/phcode-dev/phoenix/tree/main/src/thirdparty/licences'>Licences et attributions</a> .",
  "ABOUT_TEXT_LINE4": "Documentation et source sur <a href='https://github.com/phcode-dev/phoenix/'>https://github.com/phcode-dev/phoenix/</a>",
  "ABOUT_TEXT_LINE5": "Réalisé avec ❤ et JavaScript par :",
  "ABOUT_TEXT_LINE6": "Beaucoup de monde (mais nous avons du mal à charger ces données en ce moment).",
  "ABOUT_TEXT_MDN_DOCS": "MDN Docs et le logo graphique MDN sont sous licence Creative Commons Attribution, <a href='{MDN_DOCS_LICENSE}'>CC-BY-SA 2.5 Unported</a>.",
  "UPDATE_NOTIFICATION_TOOLTIP": "Une nouvelle version de {APP_NAME} est disponible. Cliquez ici pour plus de détails.",
  "UPDATE_NOT_AVAILABLE_TITLE": "{APP_NAME} est à jour",
  "UPDATE_UP_TO_DATE": "Votre version de {APP_NAME} est la dernière !",
  "UPDATE_AVAILABLE_TITLE": "Mise à jour disponible",
  "UPDATE_READY_RESTART_TITLE": "Mise à jour prête : redémarrage requis",
  "UPDATE_READY_RESTART_MESSAGE": "Fermez toutes les fenêtres de l'application {APP_NAME} et redémarrez l'application pour lancer la version mise à jour.",
  "UPDATE_READY_RESTART_INSTALL_MESSAGE": "Mise à jour téléchargée avec succès : veuillez fermer toutes les fenêtres de l'application {APP_NAME} pour appliquer les dernières mises à jour.",
  "UPDATE_FAILED_TITLE": "Mise à jour a échoué",
  "UPDATE_INSTALLING": "Installation de mise à jour…",
  "UPDATE_INSTALLING_MESSAGE": "Installation de la mise à jour en cours : {APP_NAME} installe actuellement les dernières mises à jour. L'application se fermera automatiquement une fois l'installation terminée.",
  "UPDATE_FAILED_MESSAGE": "Veuillez fermer toutes les fenêtres de l'application {APP_NAME} et rouvrir l'application pour tenter à nouveau la mise à jour.",
  "UPDATE_FAILED_VISIT_SITE_MESSAGE": "Pour réessayer, veuillez quitter toutes les instances de {APP_NAME} et redémarrer l&#39;application.<br> Vous serez bientôt dirigé vers notre page de téléchargement, où vous pourrez télécharger manuellement la dernière version.",
  "UPDATE_MESSAGE": "Une nouvelle version de {APP_NAME} est disponible. Voici quelques-unes des nouvelles fonctionnalités proposées :",
  "GET_IT_NOW": "Télécharger",
  "UPDATE_ON_EXIT": "Mise à jour à la sortie",
  "UPDATE_LATER": "Rappelez-moi plus tard",
  "UPDATE_DONE": "Redémarrez pour mettre à jour {APP_NAME}",
  "UPDATE_RESTART": "Redémarrer pour appliquer les mises à jour",
  "UPDATE_RESTART_INSTALL": "Redémarrez pour installer les mises à jour",
  "UPDATE_DOWNLOADING": "Téléchargement du programme d'installation",
  "INSTALL_WEBAPP": "Installez {APP_NAME} sur votre appareil",
  "UPDATE_DOWNLOAD_PROGRESS": "Téléchargement – {0} sur {1} Mo",
  "UPDATING_APP": "Mise à jour de {APP_NAME}",
  "UPDATING_APP_MESSAGE": "Cela peut prendre un peu de temps",
  "UPDATING_APP_DIALOG_MESSAGE": "Mise à jour en cours. Vous pouvez continuer à utiliser {APP_NAME} pendant la mise à niveau.",
  "PROJECT_SETTINGS_TITLE": "Paramètres de projet pour : {0}",
  "PROJECT_SETTING_BASE_URL": "URL de base de l’Aperçu en direct ",
  "PROJECT_SETTING_BASE_URL_HINT": "Pour utiliser un serveur local, entrez une URL telle que http://localhost:8000/",
  "BASEURL_ERROR_INVALID_PROTOCOL": "Le protocole {0} n’est pas pris en charge par l’Aperçu en direct. Veuillez utiliser une adresse de type http: ou https: .",
  "BASEURL_ERROR_SEARCH_DISALLOWED": "L’URL de base ne peut pas contenir de paramètres de recherche tels que \"{0}\".",
  "BASEURL_ERROR_HASH_DISALLOWED": "L’URL de base ne peut pas contenir de signe dièse (\"{0}\").",
  "BASEURL_ERROR_INVALID_CHAR": "Les caractères spéciaux tels que '{0}' doivent être codés en %.",
  "BASEURL_ERROR_UNKNOWN_ERROR": "Erreur inconnue lors de l’analyse de l’URL de base",
  "EMPTY_VIEW_HEADER": "<em>Ouvrir un fichier quand ce panneau est actif</em>",
  "FLIPVIEW_BTN_TOOLTIP": "Transférer cette vue dans le volet de {0}",
  "CURRENT_THEME": "Thème actuel ",
  "USE_THEME_SCROLLBARS": "Utiliser les barres de défilement du thème ",
  "FONT_SIZE": "Taille de la police ",
  "FONT_FAMILY": "Famille de polices ",
  "THEMES_SETTINGS": "Paramètres des thèmes",
  "THEMES_ERROR": "Erreur de thèmes",
  "THEMES_ERROR_CANNOT_APPLY": "Impossible d'appliquer le thème en raison d'une erreur.",
  "BUTTON_NEW_RULE": "Nouvelle règle",
  "INSTALL": "Installer",
  "APPLY": "Appliquer",
  "UPDATE": "Mettre à jour",
  "REMOVE": "Supprimer",
  "DISABLE": "Désactiver",
  "ENABLE": "Activer",
  "OVERWRITE": "Remplacer",
  "CANT_DROP_ZIP": "La suppression de fichiers zip sera bientôt prise en charge...",
  "CANT_REMOVE_DEV": "Les extensions du dossier \"dev\" doivent être supprimées manuellement.",
  "CANT_UPDATE": "La mise à jour n’est pas disponible avec cette version de l’application {APP_NAME}.",
  "CANT_UPDATE_DEV": "Les extensions du dossier « dev » ne peuvent pas être mises à jour automatiquement.",
  "INSTALL_EXTENSION_TITLE": "Installer l’extension",
  "UPDATE_EXTENSION_TITLE": "Mettre à jour l’extension",
  "INSTALL_EXTENSION_LABEL": "URL de l’extension ",
  "INSTALL_EXTENSION_HINT": "URL du fichier zip de l’extension ou du référentiel GitHub",
  "INSTALLING_FROM": "Installation de l’extension depuis·{0}…",
  "INSTALL_SUCCEEDED": "Installation réussie !",
  "INSTALL_FAILED": "Échec de l’installation.",
  "CANCELING_INSTALL": "Annulation en cours…",
  "CANCELING_HUNG": "L’annulation de l’installation prend beaucoup de temps. Il est possible qu’une erreur interne se soit produite.",
  "INSTALL_CANCELED": "Installation annulée.",
  "VIEW_COMPLETE_DESCRIPTION": "Voir la description complète",
  "VIEW_TRUNCATED_DESCRIPTION": "Voir la description tronquée",
  "SORT_EXTENSION_METHOD": "Trier les extensions suivant downloadCount ou publishedDate",
  "INVALID_ZIP_FILE": "Le contenu téléchargé n’est pas un fichier zip valide.",
  "MISSING_PACKAGE_JSON": "Le pack ne contient pas de fichier package.json.",
  "INVALID_PACKAGE_JSON": "Le fichier package.json n’est pas valide (erreur : {0}).",
  "MISSING_PACKAGE_NAME": "Le fichier package.json n’indique pas le nom du pack.",
  "BAD_PACKAGE_NAME": "{0} n’est pas un nom de pack valide.",
  "MISSING_PACKAGE_VERSION": "Le fichier package.json n’indique pas la version du pack.",
  "INVALID_VERSION_NUMBER": "Le numéro de version du pack ({0}) n’est pas valide.",
  "INVALID_BRACKETS_VERSION": "La chaîne de compatibilité {APP_NAME} ({0}) n’est pas valide.",
  "DISALLOWED_WORDS": "Le champ {0} ne peut pas contenir les mots ({1}).",
  "NPM_INSTALL_FAILED": "Échec de la commande npm install : {0}",
  "API_NOT_COMPATIBLE": "L’extension n’est pas compatible avec cette version de l’application {APP_NAME}. Elle a été installée dans le dossier contenant les extensions désactivées.",
  "MISSING_MAIN": "Le pack ne contient pas de fichier main.js.",
  "EXTENSION_ALREADY_INSTALLED": "L’installation de ce pack remplacera une extension installée précédemment. Voulez-vous remplacer l’extension installée ?",
  "EXTENSION_SAME_VERSION": "Ce pack correspond à la même version que celle installée actuellement. Voulez-vous remplacer l’installation actuelle ?",
  "EXTENSION_OLDER_VERSION": "Ce pack correspond à la version {0}, qui est antérieure à la version actuellement installée ({1}). Voulez-vous remplacer l’installation actuelle ?",
  "DOWNLOAD_ID_IN_USE": "Erreur interne : l’ID de téléchargement est déjà utilisé.",
  "NO_SERVER_RESPONSE": "Impossible de se connecter au serveur.",
  "BAD_HTTP_STATUS": "Fichier introuvable sur le serveur (HTTP {0}).",
  "CANNOT_WRITE_TEMP": "Impossible d’enregistrer le téléchargement vers le fichier temporaire.",
  "ERROR_LOADING": "Une erreur s’est produite au démarrage de l’extension.",
  "MALFORMED_URL": "URL non valide. Veuillez vérifier l’URL saisie.",
  "UNSUPPORTED_PROTOCOL": "L’URL doit commencer par http ou https.",
  "UNKNOWN_ERROR": "Erreur interne inconnue.",
  "EXTENSION_VERIFIED_PUBLISHER": "Cet éditeur a validé la propriété de {0}",
  "EXTENSION_VERIFIED_SORT": "Vérifié",
  "EXTENSION_STAR": "Star",
  "EXTENSION_STAR_SORT": "Évaluation étoilée",
  "EXTENSION_MANAGER_TITLE": "Gestionnaire d’extensions",
  "EXTENSION_MANAGER_ERROR_LOAD": "Impossible d’accéder au registre de l’extension. Réessayez ultérieurement.",
  "EXTENSION_UPDATE_RESTART_TITLE": "Redémarrer pour mettre à jour",
  "EXTENSION_UPDATE_RESTART_MESSAGE": "Pour charger les extensions mises à jour, veuillez fermer toutes les instances en cours d'exécution de {APP_NAME} et redémarrer l'application.",
  "INSTALL_EXTENSION_DRAG": "Faire glisser le fichier .zip ici ou",
  "INSTALL_EXTENSION_DROP": "Déposer le fichier .zip pour lancer l’installation",
  "INSTALL_EXTENSION_DROP_ERROR": "Installation/Mise à jour interrompue en raison des erreurs suivantes :",
  "INSTALL_FROM_URL": "Installer à partir de l’URL…",
  "INSTALL_EXTENSION_VALIDATING": "Validation en cours…",
  "EXTENSION_AUTHOR": "Auteur",
  "EXTENSION_DATE": "Date",
  "EXTENSION_INCOMPATIBLE_NEWER": "Cette extension nécessite une version plus récente de l’application {APP_NAME}.",
  "EXTENSION_INCOMPATIBLE_OLDER": "Cette extension n’est actuellement compatible qu’avec les versions antérieures de l’application {APP_NAME}.",
  "EXTENSION_DEFAULT_FEATURE_PRESENT": "Vous n'aurez peut-être pas besoin de cette extension. {APP_NAME} dispose déjà de cette fonctionnalité.",
  "EXTENSION_LATEST_INCOMPATIBLE_NEWER": "La version {0} de cette extension nécessite une version plus récente de {APP_NAME}. Mais vous pouvez installer la version antérieure {1}.",
  "EXTENSION_LATEST_INCOMPATIBLE_OLDER": "La version {0} de cette extension n’est compatible qu’avec les anciennes versions de {APP_NAME}. Mais vous pouvez installer la version antérieure {1}.",
  "EXTENSION_NO_DESCRIPTION": "Aucune description",
  "EXTENSION_MORE_INFO": "Plus d’infos…",
  "EXTENSION_ERROR": "Erreur d’extension",
  "EXTENSION_KEYWORDS": "Mots-clés",
  "EXTENSION_TRANSLATED_USER_LANG": "Traduit en {0} langues, y compris la vôtre",
  "EXTENSION_TRANSLATED_GENERAL": "Traduit en {0} langues",
  "EXTENSION_TRANSLATED_LANGS": "Cette extension a été traduite dans les langues suivantes : {0}",
  "EXTENSION_INSTALLED": "Installées",
  "EXTENSION_UPDATE_INSTALLED": "Cette mise à jour d’extension a été téléchargée et va être installée une fois le rechargement de {APP_NAME} effectué.",
  "EXTENSION_SEARCH_PLACEHOLDER": "Rechercher",
  "EXTENSION_MORE_INFO_LINK": "Plus",
  "EXTENSION_MANAGER_CREATE_EXTENSION": "+ Créer une extension",
  "EXTENSION_MANAGER_CREATE_THEME": "+ Créer un thème",
  "BROWSE_EXTENSIONS": "Parcourir les extensions",
  "EXTENSION_MANAGER_REMOVE": "Supprimer l’extension",
  "EXTENSION_MANAGER_REMOVE_ERROR": "Impossible de supprimer une ou plusieurs extensions : {0}. {APP_NAME} va être rechargé malgré tout.",
  "EXTENSION_MANAGER_UPDATE": "Mettre à jour l’extension",
  "EXTENSION_MANAGER_UPDATE_ERROR": "Impossible de mettre à jour une ou plusieurs extensions : {0}. {APP_NAME} va être rechargé malgré tout.",
  "EXTENSION_MANAGER_DISABLE": "Désactiver l’extension",
  "EXTENSION_MANAGER_DISABLE_ERROR": "Impossible de désactiver une ou plusieurs extensions : {0}. {APP_NAME} va être rechargé malgré tout.",
  "EXTENSION_MANAGER_THEMES_INFO": "Pour <a class=\"theme_settings\">sélectionner des thèmes par défaut</a> ou modifier d&#39;autres paramètres de thème, <a class=\"theme_settings\">cliquez ici</a> .",
  "EXTENSION_MANAGER_THEMES_UNDO": "Revenir au thème précédent",
  "MARKED_FOR_REMOVAL": "Marquée pour suppression",
  "UNDO_REMOVE": "Annuler",
  "MARKED_FOR_UPDATE": "Marquée pour mise à jour",
  "UNDO_UPDATE": "Annuler",
  "MARKED_FOR_DISABLING": "Marqué pour désactivation",
  "UNDO_DISABLE": "Annuler",
  "CHANGE_AND_RELOAD_TITLE": "Modifier les extensions",
  "CHANGE_AND_RELOAD_MESSAGE": "Pour mettre à jour, supprimer ou désactiver les extensions marquées, {APP_NAME} va devoir être rechargé. Vous serez invité à enregistrer vos modifications.",
  "REMOVE_AND_RELOAD": "Supprimer les extensions et recharger",
  "CHANGE_AND_RELOAD": "Modifier les extensions et recharger",
  "UPDATE_AND_RELOAD": "Mettre à jour les extensions et recharger",
  "DISABLE_AND_RELOAD": "Désactiver les extensions et recharger",
  "PROCESSING_EXTENSIONS": "Traitement des changements d’extension…",
  "EXTENSION_NOT_INSTALLED": "Impossible de supprimer l’extension {0} car elle n’est pas installée.",
  "NO_EXTENSIONS": "Aucune extension installée pour le moment.<br>Cliquez sur l’onglet Disponibles ci-dessus pour vous lancer.",
  "NO_EXTENSION_MATCHES": "Aucune extension ne correspond à votre recherche.",
  "REGISTRY_SANITY_CHECK_WARNING": "REMARQUE : ces extensions peuvent provenir d’autres sources que l’application {APP_NAME} elle-même. Les extensions ne sont pas contrôlées et disposent de privilèges locaux complets. Soyez prudents lorsque vous installez des extensions provenant d’une source inconnue.",
  "EXTENSIONS_INSTALLED_TITLE": "Installées",
  "EXTENSIONS_DEFAULT_TITLE": "Par défaut",
  "EXTENSIONS_AVAILABLE_TITLE": "Disponibles",
  "EXTENSIONS_THEMES_TITLE": "Thèmes",
  "EXTENSIONS_UPDATES_TITLE": "Mises à jour",
  "EXTENSIONS_LAST_UPDATED": "Dernière mise à jour",
  "EXTENSIONS_DOWNLOADS": "Téléchargements",
  "INLINE_EDITOR_NO_MATCHES": "Aucun résultat.",
  "INLINE_EDITOR_HIDDEN_MATCHES": "Tous les résultats sont réduits. Développez les fichiers dans la liste de droite pour voir le détail.",
  "CSS_QUICK_EDIT_NO_MATCHES": "Aucune règle CSS existante ne correspond à votre sélection.<br> Cliquez sur « Nouvelle règle » pour en créer une.",
  "CSS_QUICK_EDIT_NO_STYLESHEETS": "Votre projet ne contient aucune feuille de style.<br>Créez-en une pour pouvoir ajouter des règles CSS.",
  "IMAGE_VIEWER_LARGEST_ICON": "maximum",
  "UNIT_PIXELS": "pixels",
  "DEBUG_MENU": "Déboguer",
  "ERRORS": "Erreurs ",
  "CMD_SHOW_DEV_TOOLS": "Outils de développement {APP_NAME}",
  "CMD_REFRESH_WINDOW": "Recharger avec les extensions",
  "CMD_LOAD_CURRENT_EXTENSION": "Charger le projet en tant qu'extension",
  "CMD_RELOAD_CURRENT_EXTENSION": "Recharger le projet en tant qu'extension",
  "CMD_UNLOAD_CURRENT_EXTENSION": "Décharger le projet en tant qu'extension",
  "CMD_RELOAD_WITHOUT_USER_EXTS": "Recharger sans les extensions",
  "CMD_NEW_BRACKETS_WINDOW": "Nouvelle fenetre",
  "CMD_LAUNCH_SCRIPT_MAC": "Installer le raccourci de ligne de commande",
  "CMD_SWITCH_LANGUAGE": "Changer de langue…",
  "CMD_RUN_UNIT_TESTS": "Exécuter les tests {APP_NAME}",
  "CMD_SHOW_PERF_DATA": "Afficher les données de performances",
  "CMD_ENABLE_LOGGING": "Activer les journaux détaillés",
  "CMD_ENABLE_PHNODE_INSPECTOR": "Activer l'inspecteur PhNode",
  "CMD_GET_PHNODE_INSPECTOR_URL": "Comment inspecter PhNode",
  "CMD_ENABLE_LIVE_PREVIEW_LOGS": "Journaux d'aperçu en direct",
  "CMD_OPEN_BRACKETS_SOURCE": "Ouvrir la source de {APP_NAME}",
  "CREATING_LAUNCH_SCRIPT_TITLE": "Raccourci de ligne de commande {APP_NAME}",
  "ERROR_CREATING_LAUNCH_SCRIPT": "Une erreur est survenue lors de l’installation du raccourci de ligne de commande. Essayez d’appliquer <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting'>ces suggestions pour résoudre le problème</a>.<br/><br/>Motif : {0}",
  "ERROR_CLTOOLS_RMFAILED": "Impossible de supprimer le lien symbolique existant <code>/usr/local/bin/brackets</code>.",
  "ERROR_CLTOOLS_MKDIRFAILED": "Impossible de créer le répertoire <code>/usr/local/bin</code>.",
  "ERROR_CLTOOLS_LNFAILED": "Impossible de créer le lien symbolique <code>/usr/local/bin/brackets</code>.",
  "ERROR_CLTOOLS_SERVFAILED": "Erreur interne.",
  "ERROR_CLTOOLS_NOTSUPPORTED": "Le raccourci de ligne de commande n’est pas pris en charge par ce système d’exploitation.",
  "LAUNCH_SCRIPT_CREATE_SUCCESS": "Opération réussie ! À présent, vous pouvez facilement lancer {APP_NAME} depuis la ligne de commande : utilisez <code>brackets myFile.txt</code> pour ouvrir un fichier ou <code>brackets myFolder</code> pour changer de projet. <br/><br/><a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments'>En savoir plus</a> sur l’utilisation de {APP_NAME} depuis la ligne de commande.",
  "ERROR_LOADING_EXTENSION": "Erreur lors du chargement de l'extension",
  "ERROR_NO_EXTENSION_PACKAGE": "Fichier <code>package.json</code> non détecté dans le projet en cours. Le projet actuel est-il une extension {APP_NAME} valide ?</br> Voir <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>ce lien</a> pour plus de détails.",
  "ERROR_INVALID_EXTENSION_PACKAGE": "Le fichier <code>package.json</code> est un JSON non valide.</br> Voir <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>ce lien</a> pour plus de détails.",
  "ERROR_INVALID_EXTENSION_PACKAGE_FIELDS": "Champs obligatoires manquants dans <code>package.json</code> : [{0}]</br> Voir <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>ce lien</a> pour plus de détails.",
  "ERROR_NODE_JS_CRASH_TITLE": "Oops! Quelque chose s'est mal passé.",
  "ERROR_NODE_JS_CRASH_MESSAGE": "Nous avons rencontré un problème et devons redémarrer {APP_NAME}. Ne vous inquiétez pas, nous essayons de sauvegarder tout votre travail avant de redémarrer. </br>(Erreur : ERROR_NODE_JS_CRASH)",
  "LANGUAGE_TITLE": "Changer de langue",
  "LANGUAGE_MESSAGE": "Langue :",
  "LANGUAGE_SUBMIT": "Recharger {APP_NAME}",
  "LANGUAGE_CANCEL": "Annuler",
  "LANGUAGE_SYSTEM_DEFAULT": "Langue par défaut du système",
  "HEALTH_DATA_NOTIFICATION": "Health Report Preferences",
  "HEALTH_FIRST_POPUP_TITLE": "Rapport d’intégrité de {APP_NAME}",
  "HEALTH_DATA_DO_TRACK": "Partager des informations anonymes sur la façon dont j'utilise {APP_NAME}",
  "HEALTH_DATA_NOTIFICATION_MESSAGE": "{APP_NAME} <strong>ne collecte ni ne traite aucune information personnelle identifiable</strong> , mais <strong>collecte des statistiques d&#39;utilisation anonymes</strong> pour protéger votre vie privée. Les données anonymes sont exemptées des exigences de notification RGPD/CCPA, mais nous pensons que vous devez également avoir le choix de vous désinscrire de la collecte de données anonymes.<br><br> Vous pouvez voir vos données ou <strong>choisir de ne partager aucune donnée anonyme</strong> en sélectionnant <strong>Aide &gt; Rapport de santé</strong> . Ces statistiques <strong>anonymes</strong> d&#39;utilisation des applications et ces rapports d&#39;erreurs permettent de hiérarchiser les fonctionnalités, de détecter les bugs et de détecter les problèmes d&#39;utilisation afin d&#39;améliorer votre expérience avec {APP_NAME}. Sans ces données, nous ne saurions pas quelles fonctionnalités cela vaut la peine de créer pour vous !<br><br>",
  "HEALTH_DATA_PREVIEW": "Rapport d’intégrité de {APP_NAME}",
  "HEALTH_DATA_PREVIEW_INTRO": "<p>{APP_NAME} <strong>ne collecte ni ne traite aucune information personnelle identifiable</strong> , mais <strong>collecte des statistiques d&#39;utilisation anonymes</strong> pour protéger votre vie privée. Les données anonymes sont exemptées des exigences de notification RGPD/CCPA, mais nous pensons que vous devez avoir le choix de bien vous désinscrire de la collecte de données anonymes.<br> Ces statistiques <strong>anonymes</strong> d&#39;utilisation des applications et ces rapports d&#39;erreurs permettent de hiérarchiser les fonctionnalités, de détecter les bugs et de détecter les problèmes d&#39;utilisation de votre expérience avec {APP_NAME}.</p><p> Vous trouverez ci-dessous un aperçu des données qui seront envoyées dans votre prochain rapport de santé <em>si</em> elles sont activées. (Voir également la console du développeur pour les journaux d&#39;erreurs marqués « Erreur critique détectée ».)</p>",
  "INLINE_TIMING_EDITOR_TIME": "Temps",
  "INLINE_TIMING_EDITOR_PROGRESSION": "Progression",
  "BEZIER_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd><kbd>←</kbd><kbd>→</kbd> Déplacer le point sélectionné<br><kbd class='text'>Maj</kbd> Déplacer de dix unités<br><kbd class='text'>Tabulation</kbd> Permuter les points",
  "STEPS_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd> Augmenter ou réduire les pas<br><kbd>←</kbd><kbd>→</kbd> 'Démarrer' ou 'Arrêter'",
  "INLINE_TIMING_EDITOR_INVALID": "L’ancienne valeur <code>{0}</code> n’est pas valide et a donc été remplacée par <code>{1}</code> pour la fonction affichée. Le document sera mis à jour à la première modification.",
  "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP": "Couleur actuelle",
  "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP": "Couleur d’origine",
  "COLOR_EDITOR_RGBA_BUTTON_TIP": "Format RGBa",
  "COLOR_EDITOR_HEX_BUTTON_TIP": "Format Hex",
  "COLOR_EDITOR_HSLA_BUTTON_TIP": "Format HSLa",
  "COLOR_EDITOR_0X_BUTTON_TIP": "Format hexadécimal (0x)",
  "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR": "{0} (utilisé {1} fois)",
  "COLOR_EDITOR_USED_COLOR_TIP_PLURAL": "{0} (utilisé {1} fois)",
  "CMD_JUMPTO_DEFINITION": "Accéder à la définition",
  "CMD_SHOW_PARAMETER_HINT": "Afficher l’indicateur de paramètre",
  "NO_ARGUMENTS": "<aucun paramètre>",
  "DETECTED_EXCLUSION_TITLE": "Problème d’inférence de fichier Javascript",
  "DETECTED_EXCLUSION_INFO": "{APP_NAME} a rencontré des problèmes lors du traitement <span class='dialog-filename'>de {0}</span> .<br><br> Ce fichier ne sera plus traité pour les astuces de code, le saut à la définition ou l&#39;édition rapide. Pour réactiver ce fichier, ouvrez <code>.phcode.json</code> dans votre projet et modifiez <code>jscodehints.detectedExclusions</code> .<br><br> Il s&#39;agit probablement d&#39;un bug de {APP_NAME}. Si vous pouvez fournir une copie de ce fichier, veuillez <a href='https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue'>déposer un bug</a> avec un lien vers le fichier nommé ici.",
  "CMD_REFACTOR": "Remanier",
  "CMD_EXTRACTTO_VARIABLE": "Extraire vers variable",
  "CMD_EXTRACTTO_FUNCTION": "Extraire vers fonction",
  "ERROR_TERN_FAILED": "Impossible d’obtenir des données depuis Tern",
  "ERROR_EXTRACTTO_VARIABLE_NOT_VALID": "La sélection ne forme pas une expression",
  "ERROR_EXTRACTTO_FUNCTION_NOT_VALID": "Le bloc sélectionné doit représenter un ensemble d’instructions ou une expression",
  "ERROR_EXTRACTTO_VARIABLE_MULTICURSORS": "L’option Extraire vers variable ne fonctionne pas en cas de curseurs multiples",
  "ERROR_EXTRACTTO_FUNCTION_MULTICURSORS": "L’option Extraire vers fonction ne fonctionne pas en cas de curseurs multiples",
  "EXTRACTTO_FUNCTION_SELECT_SCOPE": "Choisir la portée cible",
  "EXTRACTTO_VARIABLE_SELECT_EXPRESSION": "Sélectionner une expression",
  "CMD_REFACTORING_RENAME": "Renommer",
  "CMD_REFACTORING_TRY_CATCH": "Encapsuler dans Try/Catch",
  "CMD_REFACTORING_CONDITION": "Encapsuler dans Condition",
  "CMD_REFACTORING_GETTERS_SETTERS": "Créer des getters/setters",
  "CMD_REFACTORING_ARROW_FUNCTION": "Convertir en fonction de flèche",
  "DESCRIPTION_CODE_REFACTORING": "Activer/désactiver le remaniement de code JavaScript",
  "ERROR_TRY_CATCH": "Sélectionner un code valide à encapsuler dans un bloc Try/Catch",
  "ERROR_WRAP_IN_CONDITION": "Sélectionner un code valide à encapsuler dans un bloc Condition",
  "ERROR_ARROW_FUNCTION": "Placer le curseur à l’intérieur d’une expression de fonction",
  "ERROR_GETTERS_SETTERS": "Placer le curseur au niveau d’un membre d’une expression d’objet",
  "ERROR_RENAME_MULTICURSOR": "Impossible de renommer en cas d’utilisation de plusieurs curseurs",
  "ERROR_RENAME_QUICKEDIT": "Impossible de renommer cet identifiant, car il est référencé ailleurs en dehors de cette fonction.",
  "ERROR_RENAME_GENERAL": "Impossible de renommer le texte sélectionné",
  "JSHINT_NAME": "JSHint",
  "CMD_ENABLE_QUICK_VIEW": "Affichage rapide au survol",
  "CMD_ENABLE_SELECTION_VIEW": "Vue de sélection",
  "TOOLTIP_CLICK_TO_EDIT_COLOR": "Cliquez ici pour modifier la couleur",
  "CMD_TOGGLE_RECENT_PROJECTS": "Projets récents",
  "REMOVE_FROM_RECENT_PROJECTS": "Supprimer des projets récents",
  "DOCS_MORE_LINK": "En savoir plus",
  "COLLAPSE_ALL": "Réduire tout",
  "EXPAND_ALL": "Développer tout",
  "COLLAPSE_CURRENT": "Réduire l’élément actif",
  "EXPAND_CURRENT": "Développer l’élément actif",
  "RECENT_FILES_DLG_HEADER": "Fichiers récents",
  "RECENT_FILES_DLG_CLEAR_BUTTON_LABEL": "Effacer",
  "RECENT_FILES_DLG_CLEAR_BUTTON_TITLE": "Effacer les fichiers non présents dans l’ensemble de travail",
  "RECOVER_UNSAVED_FILES_TITLE": "Récupérer des fichiers non enregistrés ?",
  "RECOVER_UNSAVED_FILES_MESSAGE": "Restaurer les fichiers non enregistrés de votre session précédente ?",
  "RECOVER_UNSAVED_FILES_RESTORE": "Restaurer",
  "DISCARD_UNSAVED_FILES_RESTORE": "Jeter",
  "DESCRIPTION_CLOSE_BRACKETS": "vrai pour fermer automatiquement les accolades, les crochets et les parenthèses",
  "DESCRIPTION_CLOSE_OTHERS_ABOVE": "faux pour supprimer l’option « Fermer les autres au-dessus » du menu contextuel Fichiers de travail",
  "DESCRIPTION_CLOSE_OTHERS_BELOW": "faux pour supprimer l’option « Fermer les autres en dessous » du menu contextuel Fichiers de travail",
  "DESCRIPTION_CLOSE_OTHERS": "faux pour supprimer l’option « Fermer tous les autres » du menu contextuel Fichiers de travail",
  "DESCRIPTION_CLOSE_TAGS": "Définit les options de fermeture des balises",
  "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS": "Ensemble de balises qui ne doivent pas se fermer automatiquement",
  "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING": "Fermer quand l’utilisateur tape le caractère > de la balise d’ouverture",
  "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING": "Fermer quand l’utilisateur tape le caractère / de la balise de fermeture",
  "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS": "Ensemble de balises qui, quand elles sont ouvertes, disposent d’une ligne vierge",
  "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD": "vrai pour toujours générer des marqueurs de sections réductibles quand le niveau de retrait change",
  "DESCRIPTION_CODE_FOLDING_ENABLED": "vrai pour activer le pliage de code",
  "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER": "vrai pour rendre les marqueurs de réduction de section visibles uniquement quand l’utilisateur passe la souris sur la gouttière",
  "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL": "Limite le nombre de niveaux auquel s’applique l’option Réduire tout",
  "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE": "Nombre minimum de lignes pour qu’une icône de section réductible apparaisse",
  "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES": "vrai pour mémoriser les sections réduites si vous fermez et rouvrez un fichier ou un projet",
  "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE": "vrai pour activer le pliage de code sur le texte sélectionné dans l’éditeur",
  "DESCRIPTION_DISABLED_DEFAULT_EXTENSIONS": "Extensions par défaut qui sont désactivées",
  "DESCRIPTION_ATTR_HINTS": "Activer/désactiver les indicateurs d’attribut HTML",
  "DESCRIPTION_CSS_PROP_HINTS": "Activer/désactiver les indicateurs de propriété CSS/LESS/SCSS",
  "DESCRIPTION_JS_HINTS": "Activer/désactiver les indicateurs de code JavaScript",
  "DESCRIPTION_JS_HINTS_TYPE_DETAILS": "Activer/désactiver les détails de type de données dans les indicateurs de code JavaScript",
  "DESCRIPTION_PREF_HINTS": "Activer/désactiver les indicateurs de code Préférences",
  "DESCRIPTION_SPECIAL_CHAR_HINTS": "Activer/désactiver les indicateurs d’entité HTML",
  "DESCRIPTION_SVG_HINTS": "Activer/désactiver les indicateurs de code SVG",
  "DESCRIPTION_HTML_TAG_HINTS": "Activer/désactiver les indicateurs de balise HTML",
  "DESCRIPTION_URL_CODE_HINTS": "Activer/désactiver les indicateurs d’URL dans le code HTML et CSS/LESS/SCSS",
  "DESCRIPTION_DRAG_DROP_TEXT": "Activer/désactiver la fonctionnalité de glisser-déposer",
  "DESCRIPTION_HEALTH_DATA_TRACKING": "Activer le suivi des données d’intégrité",
  "DESCRIPTION_HIGHLIGHT_MATCHES": "Active le surlignage automatique des chaînes correspondantes dans tout le document",
  "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN": "Surligner toutes les chaînes qui correspondent au paramètre dans lequel se trouve le curseur actuellement (sélection non nécessaire)",
  "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY": "Surligner uniquement quand la sélection est un paramètre complet",
  "DESCRIPTION_INSERT_HINT_ON_TAB": "vrai pour insérer l’indicateur de code sélectionné avec la touche Tabulation",
  "DESCRIPTION_NO_HINTS_ON_DOT": "vrai pour que les indicateurs de code JS ne s’affichent pas automatiquement quand l’utilisateur tape un point (.)",
  "DESCRIPTION_JSHINT_OPTIONS": "Un objet avec les options par défaut pour JSHint. Veuillez consulter l'URL suivante pour toutes les options JSHint disponibles : https://jshint.com/docs/options/",
  "DESCRIPTION_LANGUAGE": "Paramètres spécifiques à la langue",
  "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS": "Mappages supplémentaires entre extension de fichier et nom de langue",
  "DESCRIPTION_LANGUAGE_FILE_NAMES": "Mappages supplémentaires entre nom de fichier et nom de langue",
  "DESCRIPTION_LINEWISE_COPY_CUT": "En cas d’absence de sélection, un couper-copier coupe ou copie les lignes entières comportant des curseurs.",
  "DESCRIPTION_INPUT_STYLE": "Sélectionne la manière dont CodeMirror gère l'entrée et la mise au point. Il peut s'agir de zone de texte, qui est la sélection par défaut, ou de contenu modifiable, qui est la meilleure méthode pour les lecteurs d'écran (instable)",
  "DESCRIPTION_LINTING_ENABLED": "vrai pour activer l’inspection de code",
  "DESCRIPTION_ASYNC_TIMEOUT": "Durée, en millisecondes, après laquelle les utilitaires lint asynchrones échouent",
  "DESCRIPTION_LINTING_PREFER": "Ensemble d’utilitaires lint à exécuter en premier",
  "DESCRIPTION_LIVE_DEV_MULTIBROWSER": "vrai pour activer la version expérimentale de l’Aperçu en direct",
  "DESCRIPTION_USE_PREFERED_ONLY": "vrai pour exécuter uniquement les fournisseurs spécifiés dans linting.prefer",
  "DESCRIPTION_MAX_CODE_HINTS": "Nombre maximum d’indicateurs de code affichés à la fois",
  "DESCRIPTION_PATH": "Paramètres spécifiques au chemin d’accès",
  "DESCRIPTION_PROXY": "URL du serveur proxy utilisé pour l’installation des extensions",
  "DESCRIPTION_SCROLL_PAST_END": "vrai pour autoriser le défilement au-delà de la fin du document",
  "DESCRIPTION_SHOW_CODE_HINTS": "faux pour désactiver tous les indicateurs de code",
  "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING": "Laisse le curseur clignotant visible en cas de sélection de texte",
  "DESCRIPTION_SHOW_LINE_NUMBERS": "vrai pour afficher les numéros de ligne dans une « gouttière » à gauche du code",
  "DESCRIPTION_SMART_INDENT": "Mettre en retrait automatiquement lors de la création d’un nouveau bloc",
  "DESCRIPTION_SOFT_TABS": "faux pour désactiver le comportement des tabulations flexibles",
  "DESCRIPTION_SORT_DIRECTORIES_FIRST": "vrai pour trier les répertoires en premier dans l’arborescence de projets",
  "DESCRIPTION_SPACE_UNITS": "Nombre d’espaces à utiliser pour la mise en retrait",
  "DESCRIPTION_STATIC_SERVER_PORT": "Numéro de port que le serveur intégré doit utiliser pour l’Aperçu en direct",
  "DESCRIPTION_STYLE_ACTIVE_LINE": "vrai pour surligner la couleur d’arrière-plan de la ligne sur laquelle se trouve le curseur",
  "DESCRIPTION_TAB_SIZE": "Nombre d’espaces à afficher pour les tabulations",
  "DESCRIPTION_USE_TAB_CHAR": "vrai pour utiliser des tabulations au lieu d’espaces",
  "DESCRIPTION_UPPERCASE_COLORS": "vrai pour générer des couleurs hexadécimales en majuscules dans l’éditeur de couleur intégré",
  "DESCRIPTION_WORD_WRAP": "Renvoyer à la ligne automatiquement en cas de dépassement de la largeur de la fenêtre",
  "DESCRIPTION_SEARCH_AUTOHIDE": "Fermer la recherche dès que l’éditeur redevient actif",
  "DESCRIPTION_DETECTED_EXCLUSIONS": "Liste de fichiers qui ont été identifiés comme provoquant une perte de contrôle de Tern",
  "DESCRIPTION_INFERENCE_TIMEOUT": "Laps de temps au bout duquel le processus Tern expire quand il tente d’interpréter des fichiers",
  "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR": "vrai pour afficher les erreurs dans la barre d’état",
  "DESCRIPTION_QUICK_VIEW_ENABLED": "vrai pour activer l’affichage rapide",
  "DESCRIPTION_SELECTION_VIEW_ENABLED": "true pour activer la vue de sélection",
  "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW": "vrai pour afficher les aperçus d’images pour les extensions sans URL",
  "DESCRIPTION_NUMBER_QUICK_VIEW": "true pour afficher Quick View lors du survol des nombres dans l'éditeur",
  "DESCRIPTION_THEME": "Sélectionner un thème {APP_NAME}",
  "DESCRIPTION_USE_THEME_SCROLLBARS": "vrai pour autoriser les barres de défilement personnalisées",
  "DESCRIPTION_LINTING_COLLAPSED": "vrai pour réduire le panneau d’analyse lint",
  "DESCRIPTION_FONT_FAMILY": "Changer de famille de polices",
  "DESCRIPTION_DESKTOP_ZOOM_SCALE": "Choisissez un facteur d'échelle de zoom allant de 0,1 (pour une vue plus compacte) à 2 (pour une vue plus grande et plus agrandie). Disponible uniquement dans les applications de bureau",
  "DESCRIPTION_FONT_SIZE": "Modifier la taille de police, par ex. 13px",
  "DESCRIPTION_FIND_IN_FILES_NODE": "vrai pour activer la recherche basée sur des nœuds",
  "DESCRIPTION_FIND_IN_FILES_INSTANT": "vrai pour activer la recherche instantanée",
  "DESCRIPTION_FONT_SMOOTHING": "Mac uniquement : « subpixel-antialiased » pour activer l’anticrénelage (lissage) des sous-pixels ou « antialiased » pour l’anticrénelage des niveaux de gris",
  "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW": "faux pour désactiver l’ouverture du fichier de préférences en mode fractionné",
  "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE": "faux pour ouvrir le fichier de préférences de l’utilisateur dans le volet gauche/supérieur",
  "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED": "vrai pour réduire les volets une fois que le dernier fichier du volet est fermé à l’aide du bouton situé dans l’en-tête",
  "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS": "Permet de choisir quand afficher les boutons Fermer et Transférer la vue dans l’en-tête.",
  "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT": "/*\n * Ceci est un fichier en lecture seule avec les préférences prises en charge\n * par {APP_NAME}.\n * Utilisez ce fichier comme référence pour modifier vos préférences\n * fichier \"phcode.json\" ouvert dans l'autre volet.\n * Pour plus d'informations sur la façon d'utiliser les préférences à l'intérieur\n * {APP_NAME}, reportez-vous à la page Web à l'adresse https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences\n */",
  "DEFAULT_PREFERENCES_JSON_DEFAULT": "Par défaut",
  "DESCRIPTION_PURE_CODING_SURFACE": "vrai pour activer le mode code seul et masquer tous les autres éléments de l’interface utilisateur dans {APP_NAME}",
  "DESCRIPTION_INDENT_LINE_COMMENT": "vrai pour activer la mise en retrait des commentaires sur une ligne",
  "DESCRIPTION_RECENT_FILES_NAV": "Activer/désactiver la navigation dans les fichiers récents",
  "DESCRIPTION_LIVEDEV_WEBSOCKET_PORT": "Port sur lequel s’exécute le serveur WebSocket pour le mode Aperçu en direct",
  "DESCRIPTION_LIVE_DEV_HIGHLIGHT_SETTINGS": "Paramètres de surbrillance de l'Aperçu en direct",
  "DESCRIPTION_LIVEDEV_ENABLE_REVERSE_INSPECT": "faux pour désactiver l’inspection inverse de l’Aperçu en direct",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW": "Rien à prévoir !",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW_DETAILS": "Veuillez sélectionner un fichier HTML pour prévisualiser",
  "DESCRIPTION_LIVEDEV_PREVIEW_RESTRICTED": "Aperçu indisponible !",
  "DESCRIPTION_LIVEDEV_PREVIEW_RESTRICTED_DETAILS": "Ce fichier HTML ne fait pas partie du projet en cours. Pour des raisons de sécurité, seuls les fichiers de projet peuvent être prévisualisés en direct. Pour prévisualiser ce fichier, ouvrez son dossier contenant en tant que projet distinct.",
  "DESCRIPTION_LIVEDEV_MAIN_HEADING": "Euh Oh !<br> Votre navigateur actuel ne prend pas en charge l&#39;aperçu en direct.",
  "DESCRIPTION_LIVEDEV_MAIN_SPAN": "Obtenez la meilleure expérience de prévisualisation en direct en téléchargeant nos applications natives pour Windows, Mac et Linux à partir de <a href=\"https://phcode.io\" style=\"color: white\">phcode.io</a> .<br>",
  "DESCRIPTION_LIVEDEV_SECURITY_POPOUT_MESSAGE": "Vous êtes sur le point d'ouvrir un fichier pour un aperçu en direct. Veuillez continuer uniquement si vous faites confiance à la source de ce projet. Cliquez sur « Faire confiance au projet » pour continuer ou fermez cette fenêtre si vous ne faites pas confiance à la source.",
  "DESCRIPTION_LIVEDEV_SECURITY_TRUST_MESSAGE": "Vous êtes sur le point d'ouvrir un fichier pour un aperçu en direct. Veuillez continuer en cliquant sur « Faire confiance au projet » uniquement si vous faites confiance à la source de ce projet !",
  "CONFIRM_EXTERNAL_BROWSER_TITLE": "Pop-ups bloqués",
  "CONFIRM_EXTERNAL_BROWSER_MESSAGE": "Souhaitez-vous autoriser la page d'aperçu en direct à ouvrir cette URL : {0} ?",
  "TRUST_PROJECT": "Aperçu de Faire confiance et d'exécution – {0}",
  "TRUST_AUTHORS": "Faites-vous confiance aux auteurs de ce projet ?",
  "DOWNLOAD_FAILED": "Échec du téléchargement.",
  "DOWNLOAD_COMPLETE": "Téléchargement terminé.",
  "UPDATE_SUCCESSFUL": "Mise à jour effectuée.",
  "UPDATE_FAILED": "Échec de la mise à jour.",
  "VALIDATION_FAILED": "Échec de la validation.",
  "INITIALISATION_FAILED": "Échec de l’initialisation.",
  "CLEANUP_FAILED": "Échec du nettoyage.",
  "WARNING_TYPE": "Avertissement !",
  "CLICK_RESTART_TO_UPDATE": "Cliquez sur Redémarrer pour mettre à jour Brackets.",
  "UPDATE_ON_NEXT_LAUNCH": "La mise à jour sera appliquée au prochain lancement de l’application.",
  "GO_TO_SITE": "Rendez-vous sur <a href=\"http://brackets.io/\"> brackets.io </a> pour réessayer.",
  "INTERNET_UNAVAILABLE": "Aucune connexion Internet disponible.",
  "UPDATEDIR_READ_FAILED": "Impossible de lire le répertoire de mise à jour.",
  "UPDATEDIR_CLEAN_FAILED": "Impossible de nettoyer le répertoire de mise à jour.",
  "INITIAL_DOWNLOAD": "Téléchargement de la mise à jour...",
  "RETRY_DOWNLOAD": "Échec du téléchargement. Nouvelle tentative... ",
  "VALIDATING_INSTALLER": "Téléchargement terminé. Validation du programme d’installation...",
  "CHECKSUM_DID_NOT_MATCH": "La somme de contrôle ne correspond pas.",
  "INSTALLER_NOT_FOUND": "Programme d’installation non trouvé.",
  "DOWNLOAD_ERROR": "Erreur lors du téléchargement.",
  "NETWORK_SLOW_OR_DISCONNECTED": "Le réseau est déconnecté ou trop lent.",
  "RESTART_BUTTON": "Recommencer",
  "LATER_BUTTON": "Plus tard",
  "DESCRIPTION_AUTO_UPDATE": "Activer/désactiver la mise à jour automatique de {APP_NAME}",
  "AUTOUPDATE_ERROR": "Erreur !",
  "AUTOUPDATE_IN_PROGRESS": "Une mise à jour est déjà en cours.",
  "NUMBER_WITH_PERCENTAGE": "{0} %",
  "CMD_FIND_RELATED_FILES": "Trouver les fichiers associés",
  "PHP_VERSION_INVALID": "Erreur lors de l’analyse de la version de PHP. Veuillez vérifier la sortie de la commande « php –version ».",
  "PHP_UNSUPPORTED_VERSION": "Installez le moteur d’exécution de PHP 7 pour activer les outils correspondants comme Conseils de code, Conseils de paramètres, Accéder à la définition, etc. Version trouvée : {0}",
  "PHP_EXECUTABLE_NOT_FOUND": "Moteur d’exécution PHP introuvable. Installez le moteur d’exécution de PHP 7 et mettez à jour « executablePath » dans les préférences PHP. Cela permettra l’activation des outils liés à PHP comme Conseils de code, Conseils de paramètres ou encore Accéder à la définition.",
  "PHP_PROCESS_SPAWN_ERROR": "Code d’erreur {0} rencontré lors du démarrage du processus PHP.",
  "PHP_SERVER_ERROR_TITLE": "Erreur",
  "PHP_SERVER_MEMORY_LIMIT_INVALID": "La limite de mémoire que vous avez fournie n’est pas valide. Veuillez corriger la valeur indiquée dans les préférences PHP.",
  "DESCRIPTION_PHP_TOOLING_CONFIGURATION": "Paramètres de configuration par défaut des outils PHP",
  "OPEN_PREFERENNCES": "Ouvrir les préférences",
  "LANGUAGE_TOOLS_PREFERENCES": "Préférences pour les outils linguistiques",
  "FIND_ALL_REFERENCES": "Rechercher toutes les références",
  "REFERENCES_IN_FILES": "références",
  "REFERENCE_IN_FILES": "référence",
  "REFERENCES_NO_RESULTS": "Références non disponibles pour la position actuelle du curseur",
  "CMD_FIND_DOCUMENT_SYMBOLS": "Rechercher des symboles de document",
  "CMD_FIND_PROJECT_SYMBOLS": "Rechercher des symboles de projet",
  "REMOTE_DEBUGGING_ENABLED": "Débogage à distance activé sur localhost:",
  "REMOTE_DEBUGGING_PORT_INVALID": "Impossible d’activer le débogage à distance sur le port {0}. Les numéros de port doivent être compris entre {1} et {2}.",
  "DESCRIPTION_EXTERNAL_APPLICATION_ASSOCIATE": "Mappages d’extension de fichier avec des applications externes. Syntaxe : \"<type_fichier>\": \"<default|NomApplication|CheminApplication>\", Utiliser « default » pour ouvrir les fichiers dans l’application par défaut du système pour le type de fichier.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_TITLE": "Ouvrez les fichiers graphiques dans des éditeurs externes.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_MSG": "Votre dossier actuel comporte des types de fichier graphique non pris en charge par {APP_NAME}.<br/>Vous pouvez à présent associer des types de fichiers spécifiques avec des éditeurs externes. Une fois l’association établie, vous pouvez ouvrir des fichiers graphiques tels que .xd, .psd, .jpg, .png, .ai et .svg, dans leur application par défaut en double-cliquant sur ces fichiers dans l’arborescence de fichiers.<br/><br/>Cliquez sur le bouton OK pour associer les types de fichier graphique avec leur application par défaut respective.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_CNF_MSG": "Les types de fichiers suivants ont été associés avec succès aux applications par défaut.<br/> {0} Vous avez la possibilité de modifier vos préférences quant à la suppression/ajout de nouvelles associations de types de fichiers dans phcode.json en accédant au menu &quot;Débogage-&gt; Ouvrir le fichier de préférences&quot;.",
  "UNSUPPORTED_BROWSER_TITLE": "Le navigateur n'est pas pris en charge",
  "UNSUPPORTED_BROWSER_MESSAGE": "Veuillez utiliser un navigateur moderne (sorti au cours des 3 dernières années).",
  "UNSUPPORTED_BROWSER_MOBILE_TITLE": "Navigateurs mobiles non pris en charge",
  "UNSUPPORTED_BROWSER_MOBILE": "Les navigateurs mobiles et tablettes ne sont actuellement pas entièrement pris en charge. Vous pouvez fermer cette boîte de dialogue, mais certaines fonctionnalités de Phoenix ne fonctionneront pas dans ce navigateur.<br/><br/> Nous travaillons sur le développement d&#39;applications natives pour iOS et Android. <a href=\"https://github.com/phcode-dev/phoenix/discussions/1046\" target=\"_blank\">Rejoignez la discussion ici !</a>",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER_TITLE": "Accès au dossier local non pris en charge par le navigateur",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER": "Désolé, il semble que votre navigateur actuel ne prend pas en charge l&#39;ouverture des dossiers locaux. Pour cette fonctionnalité, nous vous recommandons d&#39;utiliser Chrome, Edge ou Opera.<br/><br/> Alternativement, nous travaillons sur le développement d&#39;applications natives pour Windows, Mac, Linux, iOS et Android afin de fournir une prise en charge complète. <a href=\"https://github.com/phcode-dev/phoenix/discussions/1047\" target=\"_blank\">Restez à l&#39;écoute pour les mises à jour !</a>",
  "ATTENTION_SAFARI_USERS": "Avis aux utilisateurs de Safari",
  "ATTENTION_SAFARI_USERS_MESSAGE": "<span>Safari supprime automatiquement les données du site Web si un site n&#39;est pas revisité dans les 7 jours. {APP_NAME} s&#39;appuie sur le stockage du navigateur pour enregistrer vos projets, qui peuvent être supprimés en raison de cette politique.<br/><br/> Il est recommandé de <strong>télécharger l&#39;application de bureau macOS</strong> depuis <a href='https://phcode.io' target='_blank' style='color: white'>https://phcode.io</a></span>",
  "CANNOT_PUBLISH_LARGE_PROJECT": "Impossible de publier un grand projet",
  "CANNOT_PUBLISH_LARGE_PROJECT_MESSAGE": "Phoenix est toujours en version alpha expérimentale. Nous n'avons pas encore activé la synchronisation des projets avec plus de 500 fichiers.",
  "SHARE_WEBSITE": "Publier et partager le site Web ?",
  "PUBLISH": "Publier",
  "PUBLISH_CONSENT_MESSAGE": "Prévisualisez rapidement les modifications et partagez votre site Web avec d'autres. Phoenix peut publier ce site Web pour vous à {0}. Les liens publiés seront valables pendant une période de 30 jours. </br>Vous souhaitez publier et partager votre site ?",
  "PUBLISH_SYNC_IN_PROGRESS": "Synchronisation en cours pour l'aperçu...",
  "PUBLISH_PAGE": "Cliquez pour publier et partager ce site",
  "PUBLISH_VIEW_PAGE": "Cliquez pour voir la page publiée",
  "MISSING_FIELDS": "Champs manquants",
  "PLEASE_FILL_ALL_REQUIRED": "Veuillez remplir tous les champs obligatoires surlignés en rouge",
  "CODE_EDITOR": "Éditeur de code",
  "BUILD_THE_WEB": "Construire le Web",
  "IMPORT_PROJECT": "Importer un projet",
  "GITHUB_PROJECT": "Projet GitHub",
  "NEW_PROJECT_FROM_GITHUB": "Nouveau projet de GitHub",
  "GITHUB_REPO_URL": "URL du référentiel GitHub :",
  "CREATE_PROJECT": "Créer un projet",
  "SETTING_UP_PROJECT": "Configuration du projet",
  "LOCATION": "Emplacement :",
  "DOWNLOADING": "Téléchargement...",
  "DOWNLOADING_FILE": "Téléchargement de {0}...",
  "EXTRACTING_FILES_PROGRESS": "Extraction de {0} fichiers sur {1}.",
  "COMPRESS_FILES_PROGRESS": "Compression de {0} fichiers sur {1}.",
  "DOWNLOAD_FAILED_MESSAGE": "Assurez-vous que l'URL de téléchargement est valide. </br>NB : Phoenix étant en version alpha, les URL de dépôt privé et GitHub supérieures à 25 Mo ne sont pas autorisées.",
  "PLEASE_SELECT_A_FOLDER": "Veuillez sélectionner un dossier...",
  "UNZIP_IN_PROGRESS": "Décompression des fichiers...",
  "UNZIP_FAILED": "Erreur : Échec de la décompression.",
  "CONFIRM_REPLACE_TITLE": "Confirmer le remplacement",
  "KEEP_BOTH": "Garde les deux",
  "EXPLORE": "Jeux HTML",
  "BLOG": "Blog",
  "PHOENIX_DEFAULT_PROJECT": "Projet par défaut",
  "PROJECT_NAME": "Nom du projet:",
  "NEW_HTML": "Nouveau projet HTML",
  "LICENSE": "Licence et crédits :",
  "PREVIEW": "Aperçu",
  "BUILD_WEBSITE": "Créer un site Web",
  "VIEW_MORE": "Voir plus...",
  "NEW_PROJECT_NOTIFICATION": "Cliquez sur cette icône pour créer un nouveau projet.</br><img src=\"styles/images/new_project.png\"><br/> <a href='#' style='float:right;'>d&#39;accord</a>",
  "BEAUTIFY_CODE_NOTIFICATION": "Cliquez ici ou appuyez sur <b>`{0}`</b> pour embellir le code.</br><img src=\"styles/images/beautify.gif\"><br/> <a href='#' style='float:right;'>d&#39;accord</a>",
  "DEFAULT_PROJECT_NOTIFICATION": "Cliquez ici pour ouvrir le<br/> <b>projet par défaut</b> dans Phoenix.</br> <a href='#' style='float:right;'>d&#39;accord</a>",
  "DIRECTORY_REPLACE_MESSAGE": "Le dossier sélectionné <span class='dialog-filename'>{0}</span> n&#39;est pas vide. Voulez-vous vraiment remplacer le contenu du dossier par le projet ?",
  "BUILD_WEBSITE_SECTION": "Créer un site Web",
  "LEARN_SECTION": "Apprendre avec des exemples",
  "CREATE_EXTENSION_SECTION": "Créer des extensions et des thèmes {APP_NAME}",
  "CREATE_EXTENSION": "Créer une extension",
  "CREATE_THEME": "Créer un thème",
  "WEBPAGE_HOME_PAGE": "Page d'accueil",
  "WEBPAGE_BLOG": "Blog",
  "WEBPAGE_DASHBOARD": "Tableau de bord HTML",
  "WEBPAGE_BOOTSTRAP_EXAMPLES": "Exemples d'amorçage",
  "PROJECTS_AT_A_GLANCE": "Vos projets en un coup d'œil",
  "PROJECT_AT_GLANCE_DESCRIPTION": "Regardez la vidéo pour commencer.",
  "PROJECT_FROM_BROWSER": "Stocké dans votre navigateur",
  "PROJECT_FROM_BROWSER_TERSE": "Stockage du navigateur",
  "PROJECT_SHOW_ON_STARTUP": "Afficher cette boîte de dialogue au démarrage",
  "GUIDED_LIVE_PREVIEW": "Apportez quelques modifications au code dans le fichier HTML pour voir l&#39;aperçu en direct.</br> <a href='#' style='float:right;'>d&#39;accord</a>",
  "GUIDED_LIVE_PREVIEW_POPOUT": "Cliquez sur ce bouton pour afficher l&#39;aperçu en direct dans un nouvel onglet.</br> <a href='#' style='float:right;'>d&#39;accord</a>",
  "ENJOYING_APP": "Vous aimez {APP_NAME} ?",
  "GITHUB_STARS_POPUP": "<div>Vos avis motivent notre petite équipe à rendre <b>phcode.dev</b> encore meilleur.<br/> Veuillez nous suivre sur GitHub :",
  "GITHUB_STARS_POPUP_TWITTER": "Donnez votre avis ou faites passer le mot sur Twitter :",
  "TEST_TRANSLATE": "utilisez ceci pour tester les traductions",
  "POWER_USER_POPUP_TITLE": "Comment pouvons-nous améliorer {APP_NAME} pour vous ?",
  "POWER_USER_POPUP_TEXT": "<div>Nous adorerions recevoir votre avis. Vos commentaires nous aident à décider des fonctionnalités à créer et des améliorations à apporter à notre plateforme.<br/> <a>Veuillez remplir ce court sondage.</a></div>",
  "BEAUTIFY_ERROR": "Impossible d'embellir le code. Vérifiez la syntaxe.",
  "BEAUTIFY_ERROR_ORIGINAL_CHANGED": "Impossible d'embellir. Le texte de l'éditeur a été modifié après l'embellissement.",
  "BEAUTIFY_PROJECT_BUSY_MESSAGE": "Fichier d'embellissement {0}",
  "BEAUTIFY_ERROR_SELECTION": "Impossible d'embellir.</br>Bloc de code incomplet sélectionné ou syntaxe invalide.",
  "BEAUTIFY_OPTIONS": "Options qui contrôlent le fonctionnement de Beautify Code",
  "BEAUTIFY_OPTION_PRINT_WIDTH": "Spécifiez la longueur de ligne sur laquelle l'embellisseur s'enroulera",
  "BEAUTIFY_OPTION_SEMICOLON": "Ajouter un point-virgule à la fin de chaque instruction",
  "BEAUTIFY_OPTION_SINGLE_QUOTE": "Utilisez des guillemets simples au lieu de guillemets doubles",
  "BEAUTIFY_OPTION_QUOTE_PROPS": "Changer quand les propriétés des objets sont entre guillemets",
  "BEAUTIFY_OPTION_BRACKET_SAME_LINE": "Mettre le > d'un élément HTML multi-ligne (HTML, JSX, Vue, Angular) à la fin de la dernière ligne au lieu d'être seul sur la ligne suivante (ne s'applique pas aux éléments à fermeture automatique)",
  "BEAUTIFY_OPTION_SINGLE_ATTRIBUTE_PER_LINE": "Appliquer un seul attribut par ligne dans HTML, Vue et JSX",
  "BEAUTIFY_OPTION_PROSE_WRAP": "Enveloppez la prose si elle dépasse la largeur d'impression dans les fichiers Markdown",
  "BEAUTIFY_OPTION_PRINT_TRAILING_COMMAS": "Imprimer des virgules de fin dans la mesure du possible dans des structures syntaxiques multilignes séparées par des virgules"
});