/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "Systemstandard",
  "PROJECT_BUSY": "Projektoperationen laufen",
  "DUPLICATING": "Duplizieren von {0}",
  "MOVING": "Verschieben von {0}",
  "COPYING": "Kopieren von {0}",
  "DELETING": "Löschen von {0}",
  "RENAMING": "Umbenennung",
  "STORED_IN_YOUR_BROWSER": "In Ihrem Browser gespeichert",
  "SUPPORT_US_OPEN_COLLECTIVE": "Unterstützen Sie uns auf GitHub Sponsors",
  "GENERIC_ERROR": "(Fehler {0})",
  "NOT_FOUND_ERR": "Die Datei/der Ordner konnte nicht gefunden werden.",
  "NOT_READABLE_ERR": "Die Datei/der Ordner konnte nicht gelesen werden.",
  "EXCEEDS_MAX_FILE_SIZE": "{APP_NAME} kann keine Dateien öffnen, die größer als {0} MB sind.",
  "NO_MODIFICATION_ALLOWED_ERR": "Der Ziel-Ordner kann nicht verändert werden.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "Die Berechtigungen erlauben Ihnen nicht, Veränderungen vorzunehmen.",
  "CONTENTS_MODIFIED_ERR": "Die Datei wurde außerhalb von {APP_NAME} verändert.",
  "UNSUPPORTED_ENCODING_ERR": "{APP_NAME} unterstützt derzeit nur UTF-8-kodierte Textdateien.",
  "ENCODE_FILE_FAILED_ERR": "{APP_NAME} konnte den Inhalt der Datei nicht codieren.",
  "DECODE_FILE_FAILED_ERR": "{APP_NAME} konnte den Inhalt der Datei nicht entschlüsseln.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "{APP_NAME} unterstützt derzeit keine UTF-16-codierten Textdateien.",
  "FILE_EXISTS_ERR": "Die Datei existiert bereits.",
  "FILE": "Datei",
  "FILE_TITLE": "Datei",
  "DIRECTORY": "Ordner",
  "DIRECTORY_TITLE": "Ordner",
  "DIRECTORY_NAMES_LEDE": "Ordnernamen",
  "FILENAMES_LEDE": "Dateinamen",
  "FILENAME": "Dateiname",
  "DIRECTORY_NAME": "Ordnername",
  "ERROR_LOADING_PROJECT": "Fehler beim Laden des Projekts",
  "OPEN_DIALOG_ERROR": "Fehler beim Erstellen des Datei-Öffnen-Dialogs. (Fehler {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "Fehler beim Lesen des Ordners <span class='dialog-filename'>{0}</span>. (Fehler {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "Fehler beim Lesen der Ordnerinhalte von <span class='dialog-filename'>{0}</span>. (Fehler {1})",
  "ZOOM_WITH_SHORTCUTS": "Verwenden Sie Tastenkombinationen zum Zoomen",
  "ZOOM_WITH_SHORTCUTS_DETAILS": "Bitte verwenden Sie die Tastenkombinationen <code><i>{0}</i></code> zum Vergrößern und <code><i>{1}</i></code> zum Verkleinern.",
  "ERROR_OPENING_FILE_TITLE": "Fehler beim Öffnen der Datei",
  "ERROR_OPENING_FILE": "Beim Öffnen der Datei <span class='dialog-filename'>{0}</span> ist ein Fehler aufgetreten: {1}",
  "ERROR_OPENING_FILES": "Beim Öffnen folgender Dateien ist ein Fehler aufgetreten:",
  "ERROR_RELOADING_FILE_TITLE": "Fehler beim Laden der Änderungen",
  "ERROR_RELOADING_FILE": "Beim Laden der Änderungen der Datei <span class='dialog-filename'>{0}</span> ist ein Fehler aufgetreten: {1}",
  "ERROR_SAVING_FILE_TITLE": "Fehler beim Speichern der Datei",
  "ERROR_SAVING_FILE": "Beim Speichern der Datei <span class='dialog-filename'>{0}</span> ist ein Fehler aufgetreten: {1}",
  "ERROR_RENAMING_FILE_TITLE": "Fehler beim Umbenennen von {0}",
  "ERROR_RENAMING_FILE": "Beim Umbenennen von {2} <span class='dialog-filename'>{0}</span> ist ein Fehler aufgetreten: {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "Die Datei oder der Ordner ist nicht Teil des geöffneten Projekts. Leider können derzeit nur Dateien im Projekt umbenannt werden.",
  "ERROR_MOVING_FILE_TITLE": "Fehler beim Verschieben von {0}",
  "ERROR_MOVING_FILE": "Beim Versuch, {2} <span class='dialog-filename'>{0}</span> zu verschieben, ist ein Fehler aufgetreten. {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "Datei/Ordner kann nicht verschoben werden, da sie nicht Teil des aktuellen Projekts sind.",
  "ERROR_DELETING_FILE_TITLE": "Fehler beim Löschen von {0}",
  "ERROR_DELETING_FILE": "Beim Löschen von {2} <span class='dialog-filename'>{0}</span> ist ein Fehler aufgetreten. {1}",
  "INVALID_FILENAME_TITLE": "Ungültiger {0}",
  "CANNOT_PASTE_TITLE": "{0} kann nicht eingefügt werden",
  "CANNOT_DOWNLOAD_TITLE": "Download von {0} nicht möglich",
  "ERR_TYPE_DOWNLOAD_FAILED": "Beim Herunterladen von <span class='dialog-filename'>{0}</span> ist ein Fehler aufgetreten",
  "ERR_TYPE_PASTE_FAILED": "Beim Einfügen von <span class='dialog-filename'>{0}</span> in <span class='dialog-filename'>{1}</span> ist ein Fehler aufgetreten",
  "CANNOT_DUPLICATE_TITLE": "Kann nicht duplizieren",
  "ERR_TYPE_DUPLICATE_FAILED": "Beim Duplizieren von <span class='dialog-filename'>{0}</span> ist ein Fehler aufgetreten",
  "ERR_TYPE_DUPLICATE_FAILED_NO_FILE": "Bitte wählen Sie eine Datei zum Duplizieren aus.",
  "INVALID_FILENAME_MESSAGE": "{0} dürfen keine dem System vorbehaltenen Namen gebrauchen und nicht mit Punkten (.) enden oder die folgenden Zeichen enthalten: <span class='emphasized'>{1}</span>",
  "ENTRY_WITH_SAME_NAME_EXISTS": "Eine Datei oder ein Ordner mit dem Namen <span class='dialog-filename'>{0}</span> existiert bereits.",
  "ERROR_CREATING_FILE_TITLE": "Fehler beim Erstellen von {0}",
  "ERROR_CREATING_FILE": "Beim Erstellen von {0} <span class='dialog-filename'>{1}</span> ist ein Fehler aufgetreten: {2}",
  "ERROR_MIXED_DRAGDROP": "Ein Ordner kann nicht zeitgleich mit anderen Dateien geöffnet werden.",
  "ERROR_KEYMAP_TITLE": "Fehler beim Einlesen der benutzerdefinierten Tastenbelegung",
  "ERROR_KEYMAP_CORRUPT": "Ihre Tastenbelegungs-Datei enthält kein gültiges JSON. Die Datei wird geöffnet, damit sie das Format korrigieren können.",
  "ERROR_LOADING_KEYMAP": "Ihre Tastenbelegungs-Datei ist keine gültige UTF-8-kodierte Textdatei und kann daher nicht geladen werden.",
  "ERROR_RESTRICTED_COMMANDS": "Sie können die Tastenkürzel der folgenden Befehle nicht ändern: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "Sie können die folgenden Tastenkürzel nicht ändern: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "Sie ordnen diesen Befehlen mehrere Tastenkürzel zu: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "Sie belegen diese Tastenkürzel mehrfach: {0}",
  "ERROR_INVALID_SHORTCUTS": "Diese Tastenkürzel sind ungültig: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "Sie ordnen nicht existierenden Befehlen Tastenkürzel zu: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "Fehler beim Lesen der Einstellungen",
  "ERROR_PREFS_PROJECT_LINT": "Projekteinstellungen",
  "ERROR_PREFS_PROJECT_LINT_MESSAGE": "Fehler: Das Projekt enthält sowohl die Dateien „.brackets.json“ als auch „.phcode.json“, was zu einem Konflikt führt. Bitte löschen Sie entweder „.brackets.json“ oder „.phcode.json“ und laden Sie dann das Projekt neu.",
  "ERROR_PREFS_CORRUPT": "Ihre Einstellungsdatei enthält kein gültiges JSON. Die Datei wird geöffnet, damit Sie das Format korrigieren können. Sie müssen {APP_NAME} neu starten, damit die Änderungen wirksam werden.",
  "ERROR_PROJ_PREFS_CORRUPT": "Ihre projektspezifische Einstellungsdatei enthält kein gültiges JSON. Die Datei wird geöffnet, damit Sie das Format korrigieren können. Sie müssen das Projekt neu öffnen, damit die Änderungen wirksam werden.",
  "ERROR_IN_BROWSER_TITLE": "Ups! {APP_NAME} kann derzeit leider noch nicht im Browser ausgeführt werden.",
  "ERROR_IN_BROWSER": "{APP_NAME} wurde in HTML programmiert, ist derzeit jedoch lediglich als Desktop-Anwendung verfügbar, um damit lokale Dateien zu bearbeiten. Bitte verwenden Sie die Anwendungs-Shell im Repo <b>github.com/adobe/brackets-shell</b>, um {APP_NAME} auszuführen.",
  "ERROR_MAX_FILES_TITLE": "Fehler beim Indizieren der Dateien",
  "ERROR_MAX_FILES": "Dieses Projekt besteht aus über 30.000 Dateien. Funktionen, die mit mehreren Dateien interagieren, wurden eventuell deaktiviert oder verhalten sich so, als ob das Projekt keine Dateien hätte. <a href='https://github.com/adobe/brackets/wiki/Large-Projects'>Lies mehr über das Arbeiten mit großen Projekten</a>.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "Fehler beim Starten des Browsers",
  "ERROR_CANT_FIND_CHROME": "Der Browser Google Chrome konnte nicht gefunden werden. Bitte stellen Sie sicher, dass er installiert ist.",
  "ERROR_LAUNCHING_BROWSER": "Beim Starten des Browsers ist ein Fehler aufgetreten. (Fehler {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "Fehler bei der Live-Vorschau",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "Verbinden zum Browser",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "Um die Live-Vorschau zu verwenden, muss Chrome mit aktiviertem Remote-Debugging neu gestartet werden.<br /><br />Soll Chrome neu gestartet werden, um das Remote Debugger Protokoll zu aktivieren?<br /><br />",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "Laden der Live-Vorschau nicht möglich.",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "Zum Starten der Live-Vorschau mit einer serverseitigen Datei müssen Sie eine Basis-URL für dieses Projekt angeben.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "Ein Fehler ist beim Starten des HTTP-Servers oder der Live-Vorschau-Dateien aufgetreten. Bitte versuchen Sie es später erneut.",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "Weitere Informationen finden Sie unter dem Thema <a href='{0}' title='{0}'>Fehlerbehebung bei Verbindungs-Fehlern der Live-Entwicklung</a>.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "Live-Vorschau",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "Live-Vorschau: Verbinden…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "Live-Vorschau: Initialisieren…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "Live-Vorschau-Server aktiv",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "Live-Vorschau",
  "LIVE_DEV_TOOLTIP_SHOW_IN_EDITOR": "{0} – Im Editor anzeigen…",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "Wählen Sie Datei für Live-Vorschau",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "Seite neuladen",
  "LIVE_DEV_TOGGLE_LIVE_HIGHLIGHT": "Live-Vorschau-Highlights umschalten",
  "LIVE_DEV_CLICK_POPOUT": "Popout-Live-Vorschau in neues Fenster",
  "LIVE_DEV_OPEN_CHROME": "In Chrome öffnen…",
  "LIVE_DEV_OPEN_SAFARI": "In Safari öffnen…",
  "LIVE_DEV_OPEN_EDGE": "In Edge öffnen…",
  "LIVE_DEV_OPEN_FIREFOX": "In Firefox öffnen…",
  "LIVE_DEV_OPEN_ERROR_TITLE": "Fehler beim Öffnen der Live-Vorschau in {0}",
  "LIVE_DEV_OPEN_ERROR_MESSAGE": "Stellen Sie sicher, dass der Browser {0} installiert ist, und versuchen Sie es erneut.",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "Vorschauseite anheften oder lösen",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "Live-Vorschau (Es wird aufgrund eines Syntax-Fehlers nicht aktualisiert)",
  "LIVE_DEV_SETTINGS": "Einstellungen für die Live-Vorschau …",
  "LIVE_DEV_SETTINGS_BANNER": "Richten Sie einen benutzerdefinierten Server ein, um PHP, JSP und andere serverseitig gerenderte Dateien in der Live-Vorschau anzuzeigen.",
  "LIVE_DEV_SETTINGS_TITLE": "Live-Vorschau-Einstellungen",
  "LIVE_DEV_SETTINGS_STARTUP": "Live-Vorschau-Fenster beim Start anzeigen",
  "LIVE_DEV_SETTINGS_SERVER_PREFERENCE": "true, um benutzerdefinierten Entwicklungsserver zu aktivieren",
  "LIVE_DEV_SETTINGS_STARTUP_PREFERENCE": "„true“, um das Livevorschaufenster beim Start anzuzeigen",
  "LIVE_DEV_SETTINGS_HOT_RELOAD_PREFERENCE": "„true“, wenn der Server Hot Reload unterstützt und das Neuladen der Live-Vorschau beim Speichern deaktiviert.",
  "LIVE_DEV_SETTINGS_USE_SERVER": "Für dieses Projekt benutzerdefinierten Entwicklungsserver verwenden",
  "LIVE_DEV_SETTINGS_SERVE_PREFERENCE": "Die URL Ihres Entwicklungsservers für das Projekt, z. B. http://localhost:8000/php",
  "LIVE_DEV_SETTINGS_SERVER_INBUILT": "Z. B. http://localhost:8000/php – Derzeit wird der integrierte Server verwendet.",
  "LIVE_DEV_SETTINGS_SERVER_ROOT": "Serverordner im Projekt",
  "LIVE_DEV_SETTINGS_SERVER_ROOT_HELP": "Z. B. www/ (Standard ist /)",
  "LIVE_DEV_SETTINGS_SERVER_ROOT_PREF": "Pfad innerhalb des Projekts, der vom Entwicklungsserver bereitgestellt wird, z. B. www/ (Standard ist /)",
  "LIVE_DEV_SETTINGS_RELOAD": "Server unterstützt Hot-Reload",
  "LIVE_DEV_SETTINGS_RELOAD_HELP": "Einige Server unterstützen Hot Reload, bei dem Codeänderungen auf die Seite übertragen werden, ohne dass die Seite vollständig neu geladen wird.\nAktivieren Sie diese Funktion, wenn {APP_NAME} die Seite nicht bei jedem Speichern neu laden soll.",
  "LIVE_DEV_SETTINGS_FRAMEWORK": "Server Framework",
  "LIVE_DEV_SETTINGS_FRAMEWORK_CUSTOM": "Brauch",
  "LIVE_DEV_SETTINGS_FRAMEWORK_PREFERENCES": "Server Framework, unterstützt derzeit nur Docusaurus",
  "LIVE_PREVIEW_CUSTOM_SERVER_BANNER": "Vorschau von Ihrem benutzerdefinierten Server abrufen {0}",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "Die Live-Vorschau wurde abgebrochen, weil die Entwickler-Tools des Browsers geöffnet wurden",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "Die Live-Vorschau wurde abgebrochen, weil die Seite im Browser geschlossen wurde",
  "LIVE_DEV_NAVIGATED_AWAY": "Die Live-Vorschau wurde abgebrochen, weil der Browser eine Seite geladen hat, die nicht Teil des aktuellen Projekts ist",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "Die Live-Vorschau wurde aus einem unbekannten Grund abgebrochen ({0})",
  "SAVE_CLOSE_TITLE": "Änderungen speichern",
  "SAVE_CLOSE_MESSAGE": "Wollen Sie die Änderungen in dem Dokument <span class='dialog-filename'>{0}</span> speichern?",
  "SAVE_CLOSE_MULTI_MESSAGE": "Wollen Sie Ihre Änderungen in den folgenden Dateien speichern?",
  "EXT_MODIFIED_TITLE": "Externe Änderungen",
  "CONFIRM_DELETE_TITLE": "Löschen bestätigen",
  "CONFIRM_FILE_DELETE": "Sind Sie sich sicher, dass Sie die Datei <span class='dialog-filename'>{0}</span> löschen wollen?",
  "CONFIRM_FOLDER_DELETE": "Sind Sie sich sicher, dass Sie den Ordner <span class='dialog-filename'>{0}</span> löschen wollen?",
  "FILE_DELETED_TITLE": "Datei gelöscht",
  "EXT_MODIFIED_WARNING": "<span class='dialog-filename'>{0}</span> wurde außerhalb von {APP_NAME} geändert.<br /><br />Wollen Sie die Datei speichern und die externen Änderungen ersetzen?",
  "EXT_MODIFIED_MESSAGE": "<span class='dialog-filename'>{0}</span> wurde außerhalb von {APP_NAME} geändert und hat ungespeicherte Änderungen in {APP_NAME}.<br /><br />Welche Version wollen Sie weiterverwenden?",
  "EXT_DELETED_MESSAGE": "<span class='dialog-filename'>{0}</span> wurde außerhalb von {APP_NAME} gelöscht und hat ungespeicherte Änderungen in {APP_NAME}.<br /><br />Wollen Sie die Änderungen beibehalten?",
  "EXT_ALWAYS_MODIFIED_BUTTON_TOOLTIP": "Überschreiben Sie Dateien immer, bis das Projekt gewechselt oder neu gestartet wird",
  "WINDOW_UNLOAD_WARNING": "Möchten Sie wirklich zu einer anderen URL navigieren und {APP_NAME} verlassen?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "Du hast nicht gespeicherte Änderungen! Möchten Sie wirklich zu einer anderen URL navigieren und {APP_NAME} verlassen?",
  "DONE": "Fertig",
  "OK": "OK",
  "CANCEL": "Abbrechen",
  "DONT_SAVE": "Nicht speichern",
  "SAVE": "Speichern",
  "SAVE_AS": "Speichern unter…",
  "SAVE_AND_OVERWRITE": "Überschreiben",
  "ALWAYS_OVERWRITE": "Immer überschreiben",
  "DELETE": "Löschen",
  "BUTTON_YES": "Ja",
  "BUTTON_NO": "Nein",
  "FIND_MATCH_INDEX": "{0} von {1}",
  "FIND_NO_RESULTS": "Keine Ergebnisse",
  "FIND_QUERY_PLACEHOLDER": "Suchen…",
  "FIND_HISTORY_MAX_COUNT": "Höchstzahl an Ergebnissen im Suchverlauf",
  "REPLACE_PLACEHOLDER": "Ersetzen mit…",
  "BUTTON_REPLACE_ALL": "Alle ersetzen",
  "BUTTON_REPLACE_BATCH": "Mehrere…",
  "BUTTON_REPLACE_ALL_IN_FILES": "Ersetzen…",
  "BUTTON_REPLACE": "Ersetzen",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "Nächster Treffer",
  "BUTTON_PREV_HINT": "Voriger Treffer",
  "BUTTON_CASESENSITIVE_HINT": "Groß-/Kleinschreibung beachten",
  "BUTTON_REGEXP_HINT": "Regulärer Ausdruck",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "Endgültig ersetzen",
  "REPLACE_WITHOUT_UNDO_WARNING": "Da mehr als {0} Dateien geändert werden, wird {APP_NAME} ungeöffnete Dateien auf der Festplatte verändern.<br />Das Ersetzen kann in diesen Dateien nicht mehr rückgängig gemacht werden.",
  "BUTTON_REPLACE_WITHOUT_UNDO": "Endgültig ersetzen",
  "OPEN_FILE": "Datei öffnen",
  "SAVE_FILE_AS": "Datei speichern",
  "CHOOSE_FOLDER": "Ordner wählen",
  "RELEASE_NOTES": "Versionshinweise",
  "NO_UPDATE_TITLE": "Sie sind auf dem Laufenden!",
  "NO_UPDATE_MESSAGE": "Sie führen die neuste Version von {APP_NAME} aus.",
  "FIND_REPLACE_TITLE_LABEL": "Ersetzen",
  "FIND_REPLACE_TITLE_WITH": "mit",
  "FIND_TITLE_LABEL": "Gefunden:",
  "FIND_TITLE_SUMMARY": "&ndash; {0} {1} {2} in {3}",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "in <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_NO_SCOPE": "im Projekt",
  "FIND_IN_FILES_PROJECT_SCOPE": "Im Projekt suchen",
  "FIND_IN_FILES_PROJECT_SCOPE_FILTER": "Suchen in {0}",
  "FIND_IN_FILES_PROJECT_SCOPE_REPLACE": "Im Projekt ersetzen",
  "FIND_IN_FILES_PROJECT_SCOPE_REPLACE_FILTER": "Ersetzen in {0}",
  "FIND_IN_FILES_ZERO_FILES": "Der Filter schließt alle Dateien {0} aus",
  "FIND_IN_FILES_FILE": "Datei",
  "FIND_IN_FILES_FILES": "Dateien",
  "FIND_IN_FILES_MATCH": "Treffer",
  "FIND_IN_FILES_MATCHES": "Treffer",
  "FIND_IN_FILES_MORE_THAN": "Über ",
  "FIND_IN_FILES_PAGING": "{0}&ndash;{1}",
  "FIND_IN_FILES_FILE_PATH": "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "Strg/Cmd + Klick, um alle aus-/einzuklappen",
  "FIND_IN_FILES_INDEXING": "Index für Sofortsuche wird erstellt…",
  "FIND_IN_FILES_SEARCHING": "Dateien durchsuchen…",
  "FIND_IN_FILES_SEARCHING_IN": "In {0}",
  "FIND_IN_FILES_INDEXING_PROGRESS": "Indizierung von {0} von {1} Dateien für die Sofortsuche…",
  "REPLACE_IN_FILES_ERRORS_TITLE": "Fehler beim Ersetzen",
  "REPLACE_IN_FILES_ERRORS": "Die folgenden Dateien wurden nicht verändert, weil sie nach der Suche geändert wurden oder nicht geschrieben werden konnten.",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "Fehler beim Abrufen der Update-Info",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "Beim Abrufen der neusten Update-Informationen vom Server ist ein Problem aufgetreten. Bitte stellen Sie sicher, dass Sie mit dem Internet verbunden sind, und probieren Sie es erneut.",
  "NEW_FILE_FILTER": "Neuer Filter…",
  "CLEAR_FILE_FILTER": "Keine Dateien ausschließen",
  "NO_FILE_FILTER": "Keine Dateien werden ausgeschlossen",
  "EXCLUDE_FILE_FILTER": "Dateien ausschließen",
  "INCLUDE_FILE_FILTER": "In Dateien suchen",
  "FILTER_PLACEHOLDER": "z.B. index,.css,*.js,src/**/*.css",
  "FILTER_HISTORY_TOOLTIP": "Drücken Sie „Strg-Leertaste“, um den Verlauf anzuzeigen.",
  "FILTER_HISTORY_TOOLTIP_MAC": "Drücken Sie „Befehl-Leertaste“, um den Verlauf anzuzeigen.",
  "FIND_HISTORY_TOOLTIP": "Drücken Sie „Strg-Leertaste“, um den Verlauf anzuzeigen.",
  "FIND_HISTORY_TOOLTIP_MAC": "Drücken Sie „Befehl-Leertaste“, um den Verlauf anzuzeigen.",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "Es wurde kein Editor für Schnelles Bearbeiten für die aktuelle Cursorposition gefunden",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "CSS Quick Edit: Setzen Sie den Cursor auf einen einzigen Klassennamen",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "CSS Quick Edit: Unvollständiges Klassenattribut",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "CSS Quick Edit: Unvollständiges ID-Attribut",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "CSS Quick Edit: Setzen Sie den Cursor auf einen Tag, eine Klasse oder eine ID",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "CSS Timing Function Quick Edit: Syntax nicht korrekt",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "JS Quick Edit: Setzen Sie den Cursor auf einen Funktionsnamen",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "Die Schnell-Dokumentation ist für die aktuelle Cursorposition nicht verfügbar",
  "PROJECT_LOADING": "Lädt…",
  "UNTITLED": "Unbenannt",
  "WORKING_FILES": "Offene Dateien",
  "TOP": "Oben",
  "BOTTOM": "Unten",
  "LEFT": "Links",
  "RIGHT": "Rechts",
  "CMD_SPLITVIEW_NONE": "Nicht geteilt",
  "CMD_SPLITVIEW_VERTICAL": "Vertikal geteilt",
  "CMD_SPLITVIEW_HORIZONTAL": "Horizontal geteilt",
  "SPLITVIEW_MENU_TOOLTIP": "Teilen Sie den Editor vertikal oder horizontal",
  "GEAR_MENU_TOOLTIP": "Projektdateien konfigurieren",
  "SPLITVIEW_INFO_TITLE": "Bereits geöffnet",
  "SPLITVIEW_MULTIPANE_WARNING": "Diese Datei ist bereits in einer anderen Ansicht geöffnet. Das Öffnen einer Datei in mehreren Ansichten wird {APP_NAME} bald unterstützen. Bis dahin wird die Datei in der Ansicht angezeigt, in der sie bereits geöffnet ist.<br /><br />(Sie sehen diese Nachricht nur einmal.)",
  "KEYBOARD_OVERLAY_TEXT": "Verwenden Sie Pfeile zum Navigieren oder tippen Sie, um UI-Elemente auszuwählen.",
  "KEYBOARD_SHORTCUT_CHANGE_TITLE": "Tastaturkürzel ändern…",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_TITLE": "Tastaturkürzel ändern",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_TEXT": "Drücken Sie die neue Tastenkombination für <b>„{0}“</b> (Aktuell: <b>{1}</b> )",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_DUPLICATE": "Warnung: Die Tastenkombination <b>{0}</b> ist bereits <b>„{1}“</b> zugewiesen. Neu zuweisen zu <b>„{2}“</b> ?",
  "KEYBOARD_SHORTCUT_ASSIGN": "Zuordnen",
  "KEYBOARD_SHORTCUT_NONE": "Keiner",
  "KEYBOARD_SHORTCUT_MENU_SHOW_SHORTCUTS": "Tastatürkürzel…",
  "KEYBOARD_SHORTCUT_MENU_SHOW_SHORTCUTS_BUTTON": "Alle Verknüpfungen anzeigen…",
  "KEYBOARD_SHORTCUT_TABLE_BASE_KEY": "Basisschlüssel",
  "KEYBOARD_SHORTCUT_TABLE_KEY_BINDING": "Abkürzung",
  "KEYBOARD_SHORTCUT_TABLE_COMMAND_ID": "Befehls-ID",
  "KEYBOARD_SHORTCUT_TABLE_COMMAND_NAME": "Befehl",
  "KEYBOARD_SHORTCUT_TABLE_DOUBLE_CLICK": "Doppelklicken Sie, um die Verknüpfung zu ändern",
  "KEYBOARD_SHORTCUT_TABLE_ORIGIN": "Herkunft",
  "KEYBOARD_SHORTCUT_ORIG_EXTENSION": "Verlängerung",
  "KEYBOARD_SHORTCUT_PANEL_TITLE": "Tastatürkürzel",
  "KEYBOARD_SHORTCUT_PANEL_FILTER": "Filter&hellip;",
  "KEYBOARD_SHORTCUT_PANEL_RESET": "Zurücksetzen…",
  "KEYBOARD_SHORTCUT_PANEL_RESET_DEFAULT": "Auf Standardverknüpfungen zurücksetzen…",
  "KEYBOARD_SHORTCUT_RESET_DIALOG_TITLE": "Tastaturkürzel zurücksetzen",
  "KEYBOARD_SHORTCUT_RESET_DIALOG_MESSAGE": "Alle benutzerdefinierten Verknüpfungen auf Standard zurücksetzen? Das kann nicht rückgängig gemacht werden.",
  "STATUSBAR_CURSOR_POSITION": "Zeile {0}, Spalte {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": " — {0} Spalte ausgewählt",
  "STATUSBAR_SELECTION_CH_PLURAL": " — {0} Spalten ausgewählt",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " — {0} Zeile ausgewählt",
  "STATUSBAR_SELECTION_LINE_PLURAL": " — {0} Zeilen ausgewählt",
  "STATUSBAR_SELECTION_MULTIPLE": " — {0} Auswahlen",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "Klicken, um Einrückung auf Leerzeichen umzuschalten",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "Klicken, um Einrückung auf Tabs umzuschalten",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "Klicken, um die Anzahl Leerzeichen beim Einrücken zu ändern",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "Klicken, um die Schrittweite von Tabs zu ändern",
  "STATUSBAR_SPACES": "Leerzeichen:",
  "STATUSBAR_TAB_SIZE": "Tab-Schrittweite:",
  "STATUSBAR_LINE_COUNT_SINGULAR": "— {0} Zeile",
  "STATUSBAR_LINE_COUNT_PLURAL": "— {0} Zeilen",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "Erweiterungen deaktiviert",
  "STATUSBAR_INSERT": "INS",
  "STATUSBAR_OVERWRITE": "OVR",
  "STATUSBAR_INSOVR_TOOLTIP": "Klicken, um zwischen den Cursor-Modi Einfügen (INS) und Überschreiben (OVR) umzuschalten",
  "STATUSBAR_LANG_TOOLTIP": "Klicken, um den Dateityp zu ändern",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. Klicken, um Übersicht anzuzeigen/auszublenden.",
  "STATUSBAR_DEFAULT_LANG": "(Standard)",
  "STATUSBAR_SET_DEFAULT_LANG": "Als Standard für .{0}-Dateien festlegen",
  "STATUSBAR_ENCODING_TOOLTIP": "Wählen Sie die Codierung aus",
  "STATUSBAR_TASKS": "Aufgaben",
  "STATUSBAR_TASKS_TOOLTIP": "Aktive Aufgaben verwalten",
  "STATUSBAR_TASKS_HIDE_SPINNER": "Spinner-Symbol ausblenden",
  "STATUSBAR_TASKS_UNKNOWN_EXTENSION_TASK": "Unbekannte Erweiterungsaufgabe…",
  "STATUSBAR_TASKS_PLAY": "Starten oder fortsetzen",
  "STATUSBAR_TASKS_PAUSE": "Pause",
  "STATUSBAR_TASKS_STOP": "Stoppen",
  "STATUSBAR_TASKS_RESTART": "Neu starten",
  "ERRORS_PANEL_TITLE_MULTIPLE": "{0} Probleme",
  "SINGLE_ERROR": "1 {0} Fehler",
  "MULTIPLE_ERRORS": "{1} {0} Fehler",
  "NO_ERRORS": "Keine {0} Fehler - gute Arbeit!",
  "NO_ERRORS_MULTIPLE_PROVIDER": "Keine Fehler - gute Arbeit!",
  "LINT_DISABLED": "Das Linten ist nicht aktiviert",
  "NO_LINT_AVAILABLE": "Es ist kein Linter für {0} verfügbar",
  "NOTHING_TO_LINT": "Es gibt nichts zum Linten",
  "COPY_ERROR": "Fehlermeldung kopieren",
  "LINTER_TIMED_OUT": "{0} hat die Zeitbegrenzung von {1} ms überschritten",
  "LINTER_FAILED": "{0} hat mit einer Fehlermeldung abgebrochen: {1}",
  "FILE_MENU": "Datei",
  "CMD_FILE_NEW_UNTITLED": "Neu",
  "CMD_FILE_NEW": "Neue Datei",
  "CMD_FILE_DUPLICATE": "Duplizieren",
  "CMD_FILE_DUPLICATE_FILE": "Datei duplizieren",
  "CMD_FILE_DOWNLOAD_PROJECT": "Projekt herunterladen",
  "CMD_FILE_DOWNLOAD": "Herunterladen",
  "CMD_FILE_CUT": "Ausschneiden",
  "CMD_FILE_COPY": "Kopieren",
  "CMD_FILE_COPY_PATH": "Pfad kopieren",
  "CMD_FILE_PASTE": "Einfügen",
  "CMD_PROJECT_NEW": "Neues Projekt…",
  "CMD_FILE_NEW_FOLDER": "Neuer Ordner",
  "CMD_FILE_OPEN": "Dateien öffnen…",
  "CMD_RECENT_FILES_OPEN": "Letzte Dateien…",
  "CMD_ADD_TO_WORKING_SET": "Im Projekt öffnen",
  "CMD_OPEN_DROPPED_FILES": "Abgelegte Dateien öffnen",
  "CMD_OPEN_FOLDER": "Ordner öffnen…",
  "CMD_FILE_CLOSE": "Schließen",
  "CMD_FILE_CLOSE_ALL": "Alles schließen",
  "CMD_FILE_CLOSE_LIST": "Liste schließen",
  "CMD_FILE_CLOSE_OTHERS": "Alle anderen schließen",
  "CMD_FILE_CLOSE_ABOVE": "Alle darüber schließen",
  "CMD_FILE_CLOSE_BELOW": "Alle darunter schließen",
  "CMD_FILE_SAVE": "Datei speichern",
  "CMD_FILE_SAVE_ALL": "Alles speichern",
  "CMD_FILE_SAVE_AS": "Speichern unter…",
  "CMD_LIVE_FILE_PREVIEW": "Live-Vorschau",
  "CMD_LIVE_FILE_PREVIEW_SETTINGS": "Live-Vorschau-Einstellungen",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "Experimentelle Live-Vorschau aktivieren",
  "CMD_RELOAD_LIVE_PREVIEW": "Live-Vorschau neu laden",
  "CMD_PROJECT_SETTINGS": "Projekt-Einstellungen…",
  "CMD_FILE_RENAME": "Umbenennen…",
  "CMD_FILE_DELETE": "Löschen",
  "CMD_INSTALL_EXTENSION": "Erweiterung installieren…",
  "CMD_EXTENSION_MANAGER": "Erweiterungs-Verwaltung…",
  "CMD_FILE_REFRESH": "Dateibaum neu laden",
  "CMD_FILE_SHOW_FOLDERS_FIRST": "Ordner zuerst sortieren",
  "CMD_QUIT": "Beenden",
  "CMD_EXIT": "Beenden",
  "EDIT_MENU": "Bearbeiten",
  "CMD_UNDO": "Rückgängig",
  "CMD_REDO": "Wiederholen",
  "CMD_CUT": "Ausschneiden",
  "CMD_COPY": "Kopieren",
  "CMD_PASTE": "Einfügen",
  "CMD_SELECT_ALL": "Alles auswählen",
  "CMD_SELECT_LINE": "Zeile auswählen",
  "CMD_SPLIT_SEL_INTO_LINES": "Auswahl in Zeilen aufteilen",
  "CMD_ADD_CUR_TO_NEXT_LINE": "Cursor zur nächsten Zeile hinzufügen",
  "CMD_ADD_CUR_TO_PREV_LINE": "Cursor zur vorherigen Zeile hinzufügen",
  "CMD_INDENT": "Einrücken",
  "CMD_UNINDENT": "Ausrücken",
  "CMD_DUPLICATE": "Duplizieren",
  "CMD_DELETE_LINES": "Zeile löschen",
  "CMD_COMMENT": "Zeile (aus-)kommentieren",
  "CMD_BLOCK_COMMENT": "Block (aus-)kommentieren",
  "CMD_LINE_UP": "Zeile nach oben verschieben",
  "CMD_LINE_DOWN": "Zeile nach unten verschieben",
  "CMD_OPEN_LINE_ABOVE": "Zeile darüber öffnen",
  "CMD_OPEN_LINE_BELOW": "Zeile darunter öffnen",
  "CMD_TOGGLE_CLOSE_BRACKETS": "Klammern automatisch schließen",
  "CMD_SHOW_CODE_HINTS": "Code Hints anzeigen",
  "CMD_BEAUTIFY_CODE": "Code verschönern",
  "CMD_BEAUTIFY_CODE_ON_SAVE": "Code nach dem Speichern verschönern",
  "FIND_MENU": "Suchen",
  "CMD_FIND": "Suchen",
  "CMD_FIND_NEXT": "Weitersuchen (vorwärts)",
  "CMD_FIND_PREVIOUS": "Weitersuchen (rückwärts)",
  "CMD_FIND_ALL_AND_SELECT": "Wählen Sie „Alle Vorkommen“ aus",
  "CMD_ADD_NEXT_MATCH": "Nächstes Vorkommen hinzufügen",
  "CMD_SKIP_CURRENT_MATCH": "Überspringen und nächstes Vorkommen hinzufügen",
  "CMD_FIND_IN_FILES": "Im Projekt suchen",
  "CMD_FIND_IN_SUBTREE": "Suchen in…",
  "CMD_REPLACE": "Ersetzen",
  "CMD_REPLACE_IN_FILES": "Im Projekt ersetzen",
  "CMD_REPLACE_IN_SUBTREE": "Ersetzen in…",
  "VIEW_MENU": "Ansicht",
  "CMD_HIDE_SIDEBAR": "Seitenleiste verbergen",
  "CMD_SHOW_SIDEBAR": "Seitenleiste zeigen",
  "CMD_TOGGLE_SIDEBAR": "Seitenleiste anzeigen/verbergen",
  "CMD_TOGGLE_PANELS": "Panels anzeigen/verbergen",
  "CMD_TOGGLE_PURE_CODE": "Ablenkungsfreier Modus",
  "CMD_TOGGLE_FULLSCREEN": "Ganzer Bildschirm",
  "CMD_ZOOM_UI": "Zoom-Benutzeroberfläche und Schriftarten",
  "CMD_ZOOM_IN": "Hineinzoomen",
  "CMD_ZOOM_IN_SCALE": "Vergrößern (Aktuell: {0}%)",
  "CMD_ZOOM_OUT": "Rauszoomen",
  "CMD_INCREASE_FONT_SIZE": "Schrift vergrößern",
  "CMD_DECREASE_FONT_SIZE": "Schrift verkleinern",
  "CMD_RESTORE_FONT_SIZE": "Schriftgröße zurücksetzen",
  "CMD_SCROLL_LINE_UP": "Zeile hoch scrollen",
  "CMD_SCROLL_LINE_DOWN": "Zeile runter scrollen",
  "CMD_TOGGLE_LINE_NUMBERS": "Zeilennummern anzeigen",
  "CMD_TOGGLE_ACTIVE_LINE": "Aktive Zeile hervorheben",
  "CMD_TOGGLE_WORD_WRAP": "Zeilenumbruch aktivieren",
  "CMD_LIVE_HIGHLIGHT": "Live-Vorschau Highlight",
  "CMD_VIEW_TOGGLE_INSPECTION": "Beim Speichern linten",
  "CMD_WORKINGSET_SORT_BY_ADDED": "Nach Hinzufügen-Datum sortieren",
  "CMD_WORKINGSET_SORT_BY_NAME": "Nach Name sortieren",
  "CMD_WORKINGSET_SORT_BY_TYPE": "Nach Typ sortieren",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "Automatisch sortieren",
  "CMD_THEMES": "Designs…",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "Suche automatisch schließen",
  "CMD_TOGGLE_RULERS": "Lineale",
  "CMD_KEYBOARD_NAV_OVERLAY": "Visuelle Befehlspalette",
  "NAVIGATE_MENU": "Navigation",
  "CMD_QUICK_OPEN": "Schnell öffnen",
  "CMD_GOTO_LINE": "Gehe zur Zeile",
  "CMD_GOTO_DEFINITION": "Definition schnell finden",
  "CMD_GOTO_DEFINITION_PROJECT": "Schnellsuche-Definition im Projekt",
  "CMD_GOTO_FIRST_PROBLEM": "Zum ersten Problem gehen",
  "CMD_TOGGLE_QUICK_EDIT": "Schnell bearbeiten",
  "CMD_TOGGLE_QUICK_DOCS": "Schnell-Dokumentation",
  "CMD_QUICK_EDIT_PREV_MATCH": "Vorheriges Schnellbearbeitungselement",
  "CMD_QUICK_EDIT_NEXT_MATCH": "Nächstes Schnellbearbeitungselement",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "Neue Regel",
  "CMD_NEXT_DOC": "Nächstes Dokument",
  "CMD_PREV_DOC": "Voriges Dokument",
  "CMD_NAVIGATE_BACKWARD": "Rückwärts navigieren",
  "CMD_NAVIGATE_FORWARD": "Vorwärts navigieren",
  "CMD_NEXT_DOC_LIST_ORDER": "Nächstes Dokument in der Liste",
  "CMD_PREV_DOC_LIST_ORDER": "Vorheriges Dokument in der Liste",
  "CMD_SHOW_IN_TREE": "Im Dateibaum anzeigen",
  "CMD_SHOW_IN_EXPLORER": "Im Explorer anzeigen",
  "CMD_SHOW_IN_FINDER": "Im Finder anzeigen",
  "CMD_SHOW_IN_OS": "In Betriebssystemdateien anzeigen",
  "CMD_SWITCH_PANE_FOCUS": "In andere Ansicht wechseln",
  "CMD_OPEN_VFS": "Öffnen Sie das virtuelle Dateisystem",
  "CMD_DIAGNOSTIC_TOOLS": "{APP_NAME} Diagnosetools",
  "CMD_OPEN_EXTENSIONS_FOLDER": "Erweiterungsordner öffnen…",
  "CMD_OPEN_VIRTUAL_SERVER": "Öffnen Sie den virtuellen Server",
  "HELP_MENU": "Hilfe",
  "CMD_CHECK_FOR_UPDATE": "Auf Updates prüfen…",
  "CMD_AUTO_UPDATE": "Auto-Update",
  "CMD_HOW_TO_USE_BRACKETS": "So verwendet man {APP_NAME}",
  "CMD_SUPPORT": "{APP_NAME}-Support",
  "CMD_SUGGEST": "Ein Feature vorschlagen",
  "CMD_RELEASE_NOTES": "Versionshinweise",
  "CMD_GET_INVOLVED": "Mach mit",
  "CMD_SHOW_EXTENSIONS_FOLDER": "Erweiterungen-Ordner anzeigen",
  "CMD_HEALTH_DATA_STATISTICS": "Gesundheitsbericht…",
  "CMD_HOMEPAGE": "Apps herunterladen – Startseite",
  "CMD_TWITTER": "{TWITTER_NAME} auf Twitter",
  "CMD_ABOUT": "Über {APP_TITLE}",
  "CMD_OPEN_PREFERENCES": "Einstellungsdatei öffnen",
  "CMD_OPEN_KEYMAP": "Öffnen Sie die Benutzerschlüsselzuordnungsdatei",
  "EXPERIMENTAL_BUILD": "Experimenteller Build",
  "RELEASE_BUILD": "Build",
  "DEVELOPMENT_BUILD": "Entwicklungs-Build",
  "PRERELEASE_BUILD": "Prerelease-Build",
  "RELOAD_FROM_DISK": "Von der Festplatte neu laden",
  "KEEP_CHANGES_IN_EDITOR": "Änderungen im Editor behalten",
  "CLOSE_DONT_SAVE": "Schließen (nicht speichern)",
  "RELAUNCH_CHROME": "Chrome neu starten",
  "ABOUT": "Über",
  "CLOSE": "Schließen",
  "ABOUT_TEXT_LINE1": "Geben Sie {VERSION_MAJOR} frei.{VERSION_MINOR} {BUILD_TYPE} {VERSION}",
  "ABOUT_TEXT_BUILD_TIMESTAMP": "Erstellungszeitstempel:",
  "ABOUT_RELEASE_CREDITS": "Veröffentlichungsnachweis:",
  "ABOUT_TEXT_LINE3": "Bibliotheken von Drittanbietern, die wir verwenden – <a href='https://github.com/phcode-dev/phoenix/tree/main/src/thirdparty/licences'>Lizenzen und Zuschreibungen</a> .",
  "ABOUT_TEXT_LINE4": "Dokumentation und Quelle unter <a href='https://github.com/phcode-dev/phoenix/'>https://github.com/phcode-dev/phoenix/</a>",
  "ABOUT_TEXT_LINE5": "Erstellt mit ❤ und JavaScript von:",
  "ABOUT_TEXT_LINE6": "Viele Leute (aber wir haben gerade Probleme beim Laden dieser Daten).",
  "ABOUT_TEXT_MDN_DOCS": "MDN-Dokumente und das grafische Logo von MDN sind unter einer Creative-Commons-Namensnennungs-Lizenz lizenziert, <a href='{MDN_DOCS_LICENSE}'>CC-BY-SA 2.5 Unported</a>.",
  "UPDATE_NOTIFICATION_TOOLTIP": "Eine neue Version von {APP_NAME} ist verfügbar! Für Details hier klicken.",
  "UPDATE_NOT_AVAILABLE_TITLE": "{APP_NAME} ist auf dem neuesten Stand",
  "UPDATE_UP_TO_DATE": "Ihre Version von {APP_NAME} ist die neueste!",
  "UPDATE_AVAILABLE_TITLE": "Update verfügbar",
  "UPDATE_READY_RESTART_TITLE": "Update bereit: Neustart erforderlich",
  "UPDATE_READY_RESTART_MESSAGE": "Schließen Sie alle Fenster der {APP_NAME}-App und starten Sie die App neu, um die aktualisierte Version zu starten.",
  "UPDATE_READY_RESTART_INSTALL_MESSAGE": "Update erfolgreich heruntergeladen: Bitte schließen Sie alle Fenster der {APP_NAME}-App, um die neuesten Updates anzuwenden.",
  "UPDATE_FAILED_TITLE": "Update fehlgeschlagen",
  "UPDATE_INSTALLING": "Update installieren…",
  "UPDATE_INSTALLING_MESSAGE": "Update-Installation läuft: {APP_NAME} installiert derzeit die neuesten Updates. Die Anwendung wird automatisch geschlossen, sobald die Installation abgeschlossen ist.",
  "UPDATE_FAILED_MESSAGE": "Bitte schließen Sie alle Fenster der {APP_NAME}-App und öffnen Sie die Anwendung erneut, um die Aktualisierung erneut zu versuchen.",
  "UPDATE_FAILED_VISIT_SITE_MESSAGE": "Um es erneut zu versuchen, beenden Sie bitte alle Instanzen von {APP_NAME} und starten Sie die Anwendung neu.<br> Sie werden in Kürze auf unsere Download-Seite weitergeleitet, wo Sie die neueste Version manuell herunterladen können.",
  "UPDATE_MESSAGE": "Hallo! Eine neue Version von {APP_NAME} ist verfügbar. Hier sind einige der neuen Funktionen:",
  "GET_IT_NOW": "Jetzt aktualisieren!",
  "UPDATE_ON_EXIT": "Beim Beenden aktualisieren",
  "UPDATE_LATER": "Erinnere mich später",
  "UPDATE_DONE": "Neu starten, um {APP_NAME} zu aktualisieren",
  "UPDATE_RESTART": "Starten Sie neu, um Updates anzuwenden",
  "UPDATE_RESTART_INSTALL": "Starten Sie neu, um Updates zu installieren",
  "UPDATE_DOWNLOADING": "Installationsprogramm herunterladen",
  "INSTALL_WEBAPP": "Installieren Sie {APP_NAME} auf Ihrem Gerät",
  "UPDATE_DOWNLOAD_PROGRESS": "Herunterladen: {0} von {1} MB",
  "UPDATING_APP": "{APP_NAME} wird aktualisiert",
  "UPDATING_APP_MESSAGE": "Das kann eine Weile dauern",
  "UPDATING_APP_DIALOG_MESSAGE": "Aktualisierung läuft. Sie können {APP_NAME} während des Upgrades weiterhin verwenden.",
  "PROJECT_SETTINGS_TITLE": "Projekt-Einstellungen",
  "PROJECT_SETTING_BASE_URL": "Basis-URL für Live-Vorschau",
  "PROJECT_SETTING_BASE_URL_HINT": "(URL angeben, um einen lokalen Server zu verwenden)",
  "BASEURL_ERROR_INVALID_PROTOCOL": "Das Protokoll {0} wird von der Live-Vorschau nicht unterstützt &ndash; bitte http: oder https: verwenden.",
  "BASEURL_ERROR_SEARCH_DISALLOWED": "Die Basis-URL kann keine Such-Parameter wie \"{0}\" enthalten.",
  "BASEURL_ERROR_HASH_DISALLOWED": "Die Basis-URL kann keine Hashes wie \"{0}\" enthalten.",
  "BASEURL_ERROR_INVALID_CHAR": "Sonderzeichen wie \"{0}\" müssen %-kodiert werden.",
  "BASEURL_ERROR_UNKNOWN_ERROR": "Unbekannter Fehler beim Verarbeiten der Basis-URL",
  "EMPTY_VIEW_HEADER": "<em>Öffnen Sie eine Datei, während diese Ansicht fokussiert ist</em>",
  "FLIPVIEW_BTN_TOOLTIP": "Diese Ansicht nach {0} verschieben",
  "CURRENT_THEME": "Aktuelles Design",
  "USE_THEME_SCROLLBARS": "Scrollbars vom Design verwenden",
  "FONT_SIZE": "Schriftgröße",
  "FONT_FAMILY": "Schriftart",
  "THEMES_SETTINGS": "Design-Einstellungen",
  "THEMES_ERROR": "Themenfehler",
  "THEMES_ERROR_CANNOT_APPLY": "Design konnte aufgrund eines Fehlers nicht angewendet werden.",
  "BUTTON_NEW_RULE": "Neue Regel",
  "INSTALL": "Installieren",
  "APPLY": "Anwenden",
  "UPDATE": "Aktualisieren",
  "REMOVE": "Entfernen",
  "DISABLE": "Deaktivieren",
  "ENABLE": "Aktivieren",
  "OVERWRITE": "Überschreiben",
  "CANT_DROP_ZIP": "Das Ablegen von ZIP-Dateien wird bald unterstützt...",
  "CANT_REMOVE_DEV": "Erweiterungen im \"dev\"-Ordner müssen manuell gelöscht werden.",
  "CANT_UPDATE": "Das Update ist nicht kompatibel mit dieser Version von {APP_NAME}.",
  "CANT_UPDATE_DEV": "Erweiterungen im \"dev\"-Ordner können nicht automatisch aktualisiert werden.",
  "INSTALL_EXTENSION_TITLE": "Erweiterung installieren",
  "UPDATE_EXTENSION_TITLE": "Erweiterung aktualisieren",
  "INSTALL_EXTENSION_LABEL": "Erweiterungs-URL",
  "INSTALL_EXTENSION_HINT": "URL der Erweiterungs-ZIP-Datei oder GitHub-Repo",
  "INSTALLING_FROM": "Erweiterung installieren von {0}…",
  "INSTALL_SUCCEEDED": "Installation abgeschlossen!",
  "INSTALL_FAILED": "Installation fehlgeschlagen.",
  "CANCELING_INSTALL": "Abgebrochen…",
  "CANCELING_HUNG": "Das Abbrechen der Installation nimmt bereits einige Minuten in Anspruch. Ein interner Fehler könnte aufgetreten sein.",
  "INSTALL_CANCELED": "Installation abgebrochen.",
  "VIEW_COMPLETE_DESCRIPTION": "Komplette Beschreibung anzeigen",
  "VIEW_TRUNCATED_DESCRIPTION": "Gekürzte Beschreibung anzeigen",
  "SORT_EXTENSION_METHOD": "Erweiterungen nach Downloadzahl oder Veröffentlichungsdatum sortieren",
  "INVALID_ZIP_FILE": "Der heruntergeladene Inhalt ist keine gültige ZIP-Datei.",
  "MISSING_PACKAGE_JSON": "Die package.json-Datei ist nicht vorhanden.",
  "INVALID_PACKAGE_JSON": "Die package.json-Datei ist ungültig (Fehler: {0}).",
  "MISSING_PACKAGE_NAME": "Die package.json-Datei hat keinen definierten Paketnamen.",
  "BAD_PACKAGE_NAME": "{0} ist ein ungültiger Paketname.",
  "MISSING_PACKAGE_VERSION": "Die package.json-Datein hat keine definierte Paketversion.",
  "INVALID_VERSION_NUMBER": "Die Paket-Versionsnummer ({0}) ist ungültig.",
  "INVALID_BRACKETS_VERSION": "Die {APP_NAME}-Kompatibilitäts-Zeichenkette ({0}) ist ungültig.",
  "DISALLOWED_WORDS": "Die Wörter ({1}) sind im Feld {0} nicht erlaubt.",
  "NPM_INSTALL_FAILED": "Der Befehl 'npm install' ist fehlgeschlagen: {0}",
  "API_NOT_COMPATIBLE": "Die Erweiterung ist nicht mit der aktuellen Version von {APP_NAME} kompatibel. Die Erweiterung wurde in den Ordner für die deaktivierten Erweiterungen installiert.",
  "MISSING_MAIN": "Das Paket hat keine main.js-Datei.",
  "EXTENSION_ALREADY_INSTALLED": "Durch die Installation dieses Pakets wird eine zuvor installierte Erweiterung überschrieben. Alte Erweiterung überschreiben?",
  "EXTENSION_SAME_VERSION": "Dieses Paket ist die gleiche Version wie die bereits installierte. Bestehende Installation überschreiben?",
  "EXTENSION_OLDER_VERSION": "Dieses Paket ist die Version {0}, die älter ist als die aktuell installierte ({1}). Bestehende Installation überschreiben?",
  "DOWNLOAD_ID_IN_USE": "Interner Fehler: Download-ID wird schon verwendet.",
  "NO_SERVER_RESPONSE": "Verbindung konnte nicht hergestellt werden.",
  "BAD_HTTP_STATUS": "Die Datei wurde auf dem Server nicht gefunden (HTTP {0}).",
  "CANNOT_WRITE_TEMP": "Konnte den Download nicht in einer temporären Datei speichern.",
  "ERROR_LOADING": "Beim Starten der Erweiterung ist ein Fehler aufgetreten.",
  "MALFORMED_URL": "Die URL ist ungültig. Bitte prüfen Sie, ob es sich um eine gültige URL handelt.",
  "UNSUPPORTED_PROTOCOL": "Bitte geben Sie eine http- oder https-URL an.",
  "UNKNOWN_ERROR": "Unbekannter (interner) Fehler.",
  "EXTENSION_VERIFIED_PUBLISHER": "Dieser Publisher hat die Inhaberschaft von {0} verifiziert",
  "EXTENSION_VERIFIED_SORT": "Verifiziert",
  "EXTENSION_STAR": "Stern",
  "EXTENSION_STAR_SORT": "Bewertung in Sternen",
  "EXTENSION_MANAGER_TITLE": "Erweiterungs-Verwaltung",
  "EXTENSION_MANAGER_ERROR_LOAD": "Fehler beim Zugriff auf das Verzeichnis der Erweiterungen. Bitte später erneut versuchen.",
  "EXTENSION_UPDATE_RESTART_TITLE": "Zum Aktualisieren neu starten",
  "EXTENSION_UPDATE_RESTART_MESSAGE": "Um aktualisierte Erweiterungen zu laden, schließen Sie bitte alle laufenden Instanzen von {APP_NAME} und starten Sie die Anwendung neu.",
  "INSTALL_EXTENSION_DRAG": ".zip hierhin ziehen oder",
  "INSTALL_EXTENSION_DROP": ".zip zum Installieren ablegen",
  "INSTALL_EXTENSION_DROP_ERROR": "Das Installieren/Aktualisieren schlug fehl, da die folgenden Fehler aufgetreten sind:",
  "INSTALL_FROM_URL": "von URL installieren…",
  "INSTALL_EXTENSION_VALIDATING": "Überprüfen…",
  "EXTENSION_AUTHOR": "Autor",
  "EXTENSION_DATE": "Datum",
  "EXTENSION_INCOMPATIBLE_NEWER": "Diese Erweiterung benötigt eine neuere Version von {APP_NAME}.",
  "EXTENSION_INCOMPATIBLE_OLDER": "Diese Erweiterung funktioniert momentan nur mit älteren Versionen von {APP_NAME}.",
  "EXTENSION_DEFAULT_FEATURE_PRESENT": "Möglicherweise benötigen Sie diese Erweiterung nicht. {APP_NAME} verfügt bereits über diese Funktion.",
  "EXTENSION_LATEST_INCOMPATIBLE_NEWER": "Die Version {0} dieser Erweiterung benötigt eine neuere Version von {APP_NAME}. Sie können jedoch die ältere Version {1} installieren.",
  "EXTENSION_LATEST_INCOMPATIBLE_OLDER": "Die Version {0} dieser Erweiterung funktioniert nur mit älteren Versionen von {APP_NAME}. Sie können jedoch die ältere Version {1} installieren.",
  "EXTENSION_NO_DESCRIPTION": "Keine Beschreibung",
  "EXTENSION_MORE_INFO": "Mehr Informationen…",
  "EXTENSION_ERROR": "Erweiterungs-Fehler",
  "EXTENSION_KEYWORDS": "Schlüsselwörter",
  "EXTENSION_TRANSLATED_USER_LANG": "In {0} Sprachen, inklusive Ihrer, übersetzt",
  "EXTENSION_TRANSLATED_GENERAL": "In {0} Sprachen übersetzt",
  "EXTENSION_TRANSLATED_LANGS": "Die Erweiterung wurde in diese Sprachen übersetzt: {0}",
  "EXTENSION_INSTALLED": "Installiert",
  "EXTENSION_UPDATE_INSTALLED": "Dieses Erweiterungs-Update wurde heruntergeladen und wird installiert, wenn {APP_NAME} neu geladen wird.",
  "EXTENSION_SEARCH_PLACEHOLDER": "Suchen",
  "EXTENSION_MORE_INFO_LINK": "Mehr",
  "EXTENSION_MANAGER_CREATE_EXTENSION": "+ Erweiterung erstellen",
  "EXTENSION_MANAGER_CREATE_THEME": "+ Thema erstellen",
  "BROWSE_EXTENSIONS": "Erweiterungen durchsuchen",
  "EXTENSION_MANAGER_REMOVE": "Erweiterung entfernen",
  "EXTENSION_MANAGER_REMOVE_ERROR": "Fehler beim Entfernen der Erweiterung: {0}. {APP_NAME} wird trotzdem neu geladen.",
  "EXTENSION_MANAGER_UPDATE": "Erweiterung aktualisieren",
  "EXTENSION_MANAGER_UPDATE_ERROR": "Fehler beim Update einer oder mehrerer Erweiterung(en): {0}. {APP_NAME} wird trotzdem neu geladen.",
  "EXTENSION_MANAGER_DISABLE": "Erweiterung deaktivieren",
  "EXTENSION_MANAGER_DISABLE_ERROR": "Fehler beim Deaktivieren einer oder mehrerer Erweiterung(en): {0}. {APP_NAME} wird trotzdem neu geladen.",
  "EXTENSION_MANAGER_THEMES_INFO": "<a class=\"theme_settings\">Klicken Sie hier</a> , <a class=\"theme_settings\">um Standarddesigns auszuwählen</a> oder andere Designeinstellungen zu ändern.",
  "EXTENSION_MANAGER_THEMES_UNDO": "Zum vorherigen Thema zurückkehren",
  "MARKED_FOR_REMOVAL": "Zur Entfernung markiert",
  "UNDO_REMOVE": "Rückgängig",
  "MARKED_FOR_UPDATE": "Zum Update markiert",
  "UNDO_UPDATE": "Rückgängig",
  "MARKED_FOR_DISABLING": "Zum Deaktivieren markiert",
  "UNDO_DISABLE": "Rückgängig",
  "CHANGE_AND_RELOAD_TITLE": "Erweiterungen ändern",
  "CHANGE_AND_RELOAD_MESSAGE": "Um die markierten Erweiterungen zu aktualisieren, entfernen oder deaktivieren, muss {APP_NAME} neu geladen werden. Sie werden gefragt, ob ungespeicherte Änderungen gespeichert werden sollen.",
  "REMOVE_AND_RELOAD": "Erweiterungen entfernen und neu laden",
  "CHANGE_AND_RELOAD": "Erweiterungen ändern und neu laden",
  "UPDATE_AND_RELOAD": "Erweiterungen aktualisieren und neu laden",
  "DISABLE_AND_RELOAD": "Erweiterungen deaktivieren und neu laden",
  "PROCESSING_EXTENSIONS": "Erweiterungs-Änderungen werden verarbeitet…",
  "EXTENSION_NOT_INSTALLED": "Die Erweiterung {0} konnte nicht entfernt werden, weil sie nicht installiert ist.",
  "NO_EXTENSIONS": "Momentan sind keine Erweiterungen installiert.<br>Klicken Sie oben auf den Tab \"Verfügbar\", um zu beginnen.",
  "NO_EXTENSION_MATCHES": "Keine Erweiterungen passen auf Ihre Suchanfrage.",
  "REGISTRY_SANITY_CHECK_WARNING": "ACHTUNG: Diese Erweiterungen stammen nicht unbedingt von den Machern von {APP_NAME}. Erweiterungen werden nicht überprüft und haben uneingeschränkte lokale Rechte. Seien Sie vorsichtig, wenn Sie Erweiterungen aus unbekannter Quelle installieren.",
  "EXTENSIONS_INSTALLED_TITLE": "Installiert",
  "EXTENSIONS_DEFAULT_TITLE": "Standard",
  "EXTENSIONS_AVAILABLE_TITLE": "Verfügbar",
  "EXTENSIONS_THEMES_TITLE": "Designs",
  "EXTENSIONS_UPDATES_TITLE": "Updates",
  "EXTENSIONS_LAST_UPDATED": "Zuletzt aktualisiert",
  "EXTENSIONS_DOWNLOADS": "Downloads",
  "INLINE_EDITOR_NO_MATCHES": "Keine Ergebnisse verfügbar.",
  "INLINE_EDITOR_HIDDEN_MATCHES": "Alle Ergebnisse sind ausglendet. Klicken Sie auf die rechts gelisteten Dateien, um die dazugehörigen Ergebnisse anzuzeigen.",
  "CSS_QUICK_EDIT_NO_MATCHES": "Es gibt keine CSS-Regeln, die zu Ihrer Auswahl passen.<br> Klicken Sie auf \"Neue Regel\", um eine neue Regel zu erstellen.",
  "CSS_QUICK_EDIT_NO_STYLESHEETS": "Es gibt keine Stylesheets in Ihrem Projekt.<br>Erstellen Sie eines, um CSS-Regeln hinzuzufügen.",
  "IMAGE_VIEWER_LARGEST_ICON": "größtes",
  "UNIT_PIXELS": "Pixel",
  "DEBUG_MENU": "Debug",
  "ERRORS": "Fehler",
  "CMD_SHOW_DEV_TOOLS": "{APP_NAME} Entwicklertools",
  "CMD_REFRESH_WINDOW": "Mit Erweiterungen neu laden",
  "CMD_LOAD_CURRENT_EXTENSION": "Projekt als Erweiterung laden",
  "CMD_RELOAD_CURRENT_EXTENSION": "Projekt als Erweiterung neu laden",
  "CMD_UNLOAD_CURRENT_EXTENSION": "Projekt als Erweiterung entladen",
  "CMD_RELOAD_WITHOUT_USER_EXTS": "Ohne Erweiterungen neu laden",
  "CMD_NEW_BRACKETS_WINDOW": "Neues Fenster",
  "CMD_LAUNCH_SCRIPT_MAC": "Kommandozeilenverknüpfung einrichten",
  "CMD_SWITCH_LANGUAGE": "Sprache wechseln…",
  "CMD_RUN_UNIT_TESTS": "Führen Sie {APP_NAME}-Tests aus",
  "CMD_SHOW_PERF_DATA": "Performance-Analyse",
  "CMD_ENABLE_LOGGING": "Aktivieren Sie detaillierte Protokolle",
  "CMD_ENABLE_PHNODE_INSPECTOR": "Aktivieren Sie PhNode Inspector",
  "CMD_GET_PHNODE_INSPECTOR_URL": "So überprüfen Sie PhNode",
  "CMD_ENABLE_LIVE_PREVIEW_LOGS": "Live-Vorschauprotokolle",
  "CMD_OPEN_BRACKETS_SOURCE": "{APP_NAME}-Quellcode anzeigen",
  "CREATING_LAUNCH_SCRIPT_TITLE": "{APP_NAME}-Befehlszeilenverknüpfung",
  "ERROR_CREATING_LAUNCH_SCRIPT": "Beim Einrichten der Befehlszeilenverknüpfung ist ein Fehler aufgetreten. Bitte probieren Sie <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting'>diese Schritte zur Fehlerbehebung</a>.<br/><br/>Fehler: {0}",
  "ERROR_CLTOOLS_RMFAILED": "Die aktuelle symbolische Verknüpfung <code>/usr/local/bin/brackets</code> konnte nicht entfernt werden.",
  "ERROR_CLTOOLS_MKDIRFAILED": "Das Verzeichnis <code>/usr/local/bin</code> konnte nicht erstellt werden.",
  "ERROR_CLTOOLS_LNFAILED": "Die symbolische Verknüpfung <code>/usr/local/bin/brackets</code> konnte nicht erstellt werden.",
  "ERROR_CLTOOLS_SERVFAILED": "Interner Fehler.",
  "ERROR_CLTOOLS_NOTSUPPORTED": "Eine Befehlszeilenverknüpfung wird unter diesem Betriebssystem nicht unterstützt.",
  "LAUNCH_SCRIPT_CREATE_SUCCESS": "Einrichtung erfolgreich! Sie können {APP_NAME} nun ganz einfach von der Befehlszeile aus starten: <code<brackets myFile.txt</code>, um eine Datei zu öffnen oder <code>brackets myFolder</code>, um das geöffnete Projekt zu ändern.<br/><br/><a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments'>Erfahre mehr</a> über das Nutzen von {APP_NAME} über die Befehlszeile.",
  "ERROR_LOADING_EXTENSION": "Fehler beim Laden der Erweiterung",
  "ERROR_NO_EXTENSION_PACKAGE": "<code>package.json</code> Datei im aktuellen Projekt nicht erkannt. Ist das aktuelle Projekt eine gültige {APP_NAME}-Erweiterung?</br> Weitere Informationen finden Sie unter <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>diesem Link</a> .",
  "ERROR_INVALID_EXTENSION_PACKAGE": "Die Datei <code>package.json</code> ist ungültiges JSON.</br> Weitere Informationen finden Sie unter <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>diesem Link</a> .",
  "ERROR_INVALID_EXTENSION_PACKAGE_FIELDS": "Erforderliche Felder fehlen in <code>package.json</code> : [{0}]</br> Weitere Informationen finden Sie unter <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>diesem Link</a> .",
  "ERROR_NODE_JS_CRASH_TITLE": "Hoppla! Etwas ist schief gelaufen.",
  "ERROR_NODE_JS_CRASH_MESSAGE": "Wir sind auf ein Problem gestoßen und müssen {APP_NAME} neu starten. Keine Sorge, wir versuchen, Ihre gesamte Arbeit vor dem Neustart zu speichern. </br>(Fehler: ERROR_NODE_JS_CRASH)",
  "LANGUAGE_TITLE": "Sprache wechseln",
  "LANGUAGE_MESSAGE": "Sprache:",
  "LANGUAGE_SUBMIT": "{APP_NAME} neu starten",
  "LANGUAGE_CANCEL": "Abbrechen",
  "LANGUAGE_SYSTEM_DEFAULT": "Systemstandard",
  "HEALTH_DATA_NOTIFICATION": "Statusbericht-Einstellungen",
  "HEALTH_FIRST_POPUP_TITLE": "Datenschutzerklärung",
  "HEALTH_DATA_DO_TRACK": "Geben Sie anonyme Informationen darüber weiter, wie ich {APP_NAME} verwende.",
  "HEALTH_DATA_NOTIFICATION_MESSAGE": "{APP_NAME} <strong>erhebt oder verarbeitet keine personenbezogenen Daten</strong> , <strong>sammelt jedoch anonyme Nutzungsstatistiken</strong> , um Ihre Privatsphäre zu schützen. Anonyme Daten sind von der DSGVO/CCPA-Meldepflicht ausgenommen, wir glauben jedoch, dass Sie auch die Möglichkeit haben müssen, die anonyme Datenerfassung abzulehnen.<br><br> Sie können Ihre Daten anzeigen oder <strong>entscheiden, keine anonymen Daten weiterzugeben,</strong> indem Sie <strong>Hilfe &gt; Gesundheitsbericht</strong> auswählen. Diese <strong>anonymen</strong> App-Nutzungsstatistiken und Fehlerberichte helfen dabei, Funktionen zu priorisieren, Fehler zu finden und Benutzerfreundlichkeitsprobleme zu erkennen, um Ihr Erlebnis mit {APP_NAME} zu verbessern. Ohne diese Daten wüssten wir nicht, welche Features sich für Sie lohnen!<br><br>",
  "HEALTH_DATA_PREVIEW": "{APP_NAME}-Statusbericht",
  "HEALTH_DATA_PREVIEW_INTRO": "<p>{APP_NAME} <strong>sammelt oder verarbeitet keine personenbezogenen Daten</strong> , <strong>sammelt jedoch anonyme Nutzungsstatistiken,</strong> um Ihre Privatsphäre zu schützen. Diese <strong>anonymen</strong> App-Nutzungsstatistiken und Fehlerberichte helfen dabei, Funktionen zu priorisieren, Fehler zu finden und Probleme bei der Benutzerfreundlichkeit zu erkennen, um Ihre Erfahrung mit {APP_NAME} zu verbessern.</p><p> Unten sehen Sie eine Vorschau der Daten, die in Ihrem nächsten Integritätsbericht gesendet werden, <em>sofern</em> dieser aktiviert ist. (In der Entwicklerkonsole finden Sie auch Fehlerprotokolle mit der Markierung „Kritischer Fehler abgefangen“.)</p>",
  "INLINE_TIMING_EDITOR_TIME": "Zeit",
  "INLINE_TIMING_EDITOR_PROGRESSION": "Verlauf",
  "BEZIER_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd><kbd>←</kbd><kbd>→</kbd> Ausgewählten Punkt bewegen<br><kbd class='text'>Umschalt</kbd> Um 10 Einheiten bewegen<br><kbd class='text'>Tab</kbd> Zwischen Punkten wechseln",
  "STEPS_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd> Stufenzahl vergrößern oder verkleinern<br><kbd>←</kbd><kbd>→</kbd> 'Start' oder 'Ende'",
  "INLINE_TIMING_EDITOR_INVALID": "Der Code im Dokument <code>{0}</code> ist nicht korrekt, daher wird die Funktion <code>{1}</code> angezeigt. Die Änderungen werden bei der ersten Bearbeitung ins Dokument übernommen.",
  "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP": "Aktuelle Farbe",
  "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP": "Original-Farbe",
  "COLOR_EDITOR_RGBA_BUTTON_TIP": "RGBa-Format",
  "COLOR_EDITOR_HEX_BUTTON_TIP": "Hex-Format",
  "COLOR_EDITOR_HSLA_BUTTON_TIP": "HSLa-Format",
  "COLOR_EDITOR_0X_BUTTON_TIP": "Hex-Format (0x)",
  "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR": "{0} ({1} Mal verwendet)",
  "COLOR_EDITOR_USED_COLOR_TIP_PLURAL": "{0} ({1} Mal verwendet)",
  "CMD_JUMPTO_DEFINITION": "Springe zur Definition",
  "CMD_SHOW_PARAMETER_HINT": "Parameter-Hinweis anzeigen",
  "NO_ARGUMENTS": "<keine Parameter>",
  "DETECTED_EXCLUSION_TITLE": "Problem mit einer JavaScript-Datei",
  "DETECTED_EXCLUSION_INFO": "Bei {APP_NAME} sind Probleme bei der Verarbeitung von <span class='dialog-filename'>{0}</span> aufgetreten.<br><br> Diese Datei wird nicht mehr für Codehinweise, Zur Definition springen oder Schnellbearbeitung verarbeitet. Um diese Datei wieder zu aktivieren, öffnen Sie <code>.phcode.json</code> in Ihrem Projekt und bearbeiten Sie <code>jscodehints.detectedExclusions</code> .<br><br> Dies ist wahrscheinlich ein {APP_NAME}-Fehler. Wenn Sie eine Kopie dieser Datei bereitstellen können, <a href='https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue'>melden Sie bitte einen Fehler</a> mit einem Link zu der hier genannten Datei.",
  "CMD_REFACTOR": "Umgestalten",
  "CMD_EXTRACTTO_VARIABLE": "In Variable extrahieren",
  "CMD_EXTRACTTO_FUNCTION": "In Funktion extrahieren",
  "ERROR_TERN_FAILED": "Es können keine Daten von Tern abgerufen werden",
  "ERROR_EXTRACTTO_VARIABLE_NOT_VALID": "Auswahl bildet keinen Ausdruck",
  "ERROR_EXTRACTTO_FUNCTION_NOT_VALID": "Der ausgewählte Block sollte eine Reihe von Anweisungen oder einen Ausdruck darstellen",
  "ERROR_EXTRACTTO_VARIABLE_MULTICURSORS": "In Variable extrahieren funktioniert nicht in Multicursoren",
  "ERROR_EXTRACTTO_FUNCTION_MULTICURSORS": "Extract to Function funktioniert nicht in Multicursoren",
  "EXTRACTTO_FUNCTION_SELECT_SCOPE": "Wählen Sie den Zielbereich aus",
  "EXTRACTTO_VARIABLE_SELECT_EXPRESSION": "Wählen Sie einen Ausdruck aus",
  "CMD_REFACTORING_RENAME": "Umbenennen…",
  "CMD_REFACTORING_TRY_CATCH": "Wrap in Try Catch",
  "CMD_REFACTORING_CONDITION": "Zustand einwickeln",
  "CMD_REFACTORING_GETTERS_SETTERS": "Erstellen Sie Getter/Setter",
  "CMD_REFACTORING_ARROW_FUNCTION": "In Pfeilfunktion umwandeln",
  "DESCRIPTION_CODE_REFACTORING": "JavaScript-Code-Refactoring aktivieren/deaktivieren",
  "ERROR_TRY_CATCH": "Wählen Sie gültigen Code aus, der in einen Try-Catch-Block eingeschlossen werden soll",
  "ERROR_WRAP_IN_CONDITION": "Wählen Sie gültigen Code aus, der in einen Bedingungsblock eingeschlossen werden soll",
  "ERROR_ARROW_FUNCTION": "Platzieren Sie den Cursor in einem Funktionsausdruck",
  "ERROR_GETTERS_SETTERS": "Platzieren Sie den Cursor auf einem Element eines Objektausdrucks",
  "ERROR_RENAME_MULTICURSOR": "Kann nicht umbenannt werden, wenn Multi-Cursor verwendet wird",
  "ERROR_RENAME_QUICKEDIT": "Dieser Bezeichner kann nicht umbenannt werden, da er an anderer Stelle außerhalb dieser Funktion referenziert wird",
  "ERROR_RENAME_GENERAL": "Ausgewählter Text kann nicht umbenannt werden",
  "JSHINT_NAME": "JSHint",
  "CSS_LINT_NAME": "{0} Flusen",
  "CMD_ENABLE_QUICK_VIEW": "Schnelle Farbansicht",
  "CMD_ENABLE_SELECTION_VIEW": "Auswahlansicht",
  "TOOLTIP_CLICK_TO_EDIT_COLOR": "Klicken Sie hier, um die Farbe zu bearbeiten",
  "CMD_TOGGLE_RECENT_PROJECTS": "Zuletzt verwendete Projekte",
  "REMOVE_FROM_RECENT_PROJECTS": "Aus aktuellen Projekten entfernen",
  "DOCS_MORE_LINK": "Weiterlesen",
  "DOCS_MORE_LINK_MDN_TITLE": "Klicken Sie hier, um die Dokumentation zu lesen",
  "COLLAPSE_ALL": "Alle einklappen",
  "EXPAND_ALL": "Alle ausklappen",
  "COLLAPSE_CURRENT": "Aktuelle einklappen",
  "EXPAND_CURRENT": "Aktuelle ausklappen",
  "RECENT_FILES_DLG_HEADER": "Kürzlich verwendete Dateien",
  "RECENT_FILES_DLG_CLEAR_BUTTON_LABEL": "Leeren",
  "RECENT_FILES_DLG_CLEAR_BUTTON_TITLE": "Entferne alle Dateien aus der Liste, die nicht im Projekt geöffnet sind",
  "RECOVER_UNSAVED_FILES_TITLE": "Nicht gespeicherte Dateien wiederherstellen?",
  "RECOVER_UNSAVED_FILES_MESSAGE": "Nicht gespeicherte Dateien aus Ihrer vorherigen Sitzung wiederherstellen?",
  "RECOVER_UNSAVED_FILES_RESTORE": "Wiederherstellen",
  "DISCARD_UNSAVED_FILES_RESTORE": "Verwerfen",
  "DESCRIPTION_CLOSE_BRACKETS": "Aktiviert das automatische Schließen von runden, eckigen und geschweiften Klammern",
  "DESCRIPTION_CLOSE_OTHERS_ABOVE": "Aktiviert den Eintrag \"Alle darüber schließen\" im Kontextmenü der Offenen Dateien",
  "DESCRIPTION_CLOSE_OTHERS_BELOW": "Aktiviert den Eintrag \"Alle darunter schließen\" im Kontextmenü der Offenen Dateien",
  "DESCRIPTION_CLOSE_OTHERS": "Aktiviert den Eintrag \"Alle anderen schließen\" im Kontextmenü der Offenen Dateien",
  "DESCRIPTION_CLOSE_TAGS": "Optionen für die \"Tags automatisch schließen\"-Funktion",
  "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS": "Ein Array von Tags, die nicht automatisch geschlossen werden sollen",
  "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING": "Tag beim Eingeben von > vom öffnenden Tag schließen",
  "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING": "Tag beim Eingeben von / vom schließenden Tag schließen",
  "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS": "Ein Array von Tags, die einen Zeilenumbruch auslösen",
  "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD": "Immer einklappbare Folding-Markierungen anzeigen, wenn sich der Zeileneinzug ändert",
  "DESCRIPTION_CODE_FOLDING_ENABLED": "Aktiviert Code Folding",
  "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER": "Einklappbare Folding-Markierungen nur anzeigen, wenn sich die Maus über dem linken Zeilenrand befindet",
  "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL": "Limitiert die maximale Anzahl von \"Alle Einklappen\"-Markierungen",
  "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE": "Mindestzahl an Zeilen, bevor eine einklappbare Folding-Markierung erscheint",
  "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES": "Aktiviert das Speichern der eingeklappten Abschnitte",
  "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE": "Aktiviert das Einklappen von ausgewähltem Text",
  "DESCRIPTION_DISABLED_DEFAULT_EXTENSIONS": "Standardmäßig installierte Erweiterungen, die deaktiviert sind",
  "DESCRIPTION_ATTR_HINTS": "Aktiviert Code Hints für HTML-Attribute",
  "DESCRIPTION_CSS_PROP_HINTS": "Aktiviert Code Hints für CSS/LESS/SCSS",
  "DESCRIPTION_JS_HINTS": "Aktiviert Code Hints für JavaScript",
  "DESCRIPTION_JS_HINTS_TYPE_DETAILS": "Zeigt Details zum Datentyp in den Code Hints für JavaScript",
  "DESCRIPTION_PREF_HINTS": "Aktiviert Code Hints für Einstellungen",
  "DESCRIPTION_SPECIAL_CHAR_HINTS": "Aktiviert Code Hints für HTML Entities",
  "DESCRIPTION_SVG_HINTS": "Aktiviert Code Hints für SVG",
  "DESCRIPTION_HTML_TAG_HINTS": "Aktiviert Code Hints für HTML-Tags",
  "DESCRIPTION_URL_CODE_HINTS": "Aktiviert Code Hints für URLs in HTML & CSS/LESS/SCSS",
  "DESCRIPTION_DRAG_DROP_TEXT": "Aktiviert Drag & Drop",
  "DESCRIPTION_HEALTH_DATA_TRACKING": "Aktiviert das Übermitteln des {APP_NAME}-Statusberichts",
  "DESCRIPTION_HIGHLIGHT_MATCHES": "Aktiviert die Hervorhebung von Vorkommnissen des markierten Worts im Dokument",
  "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN": "Hervorheben aller Vorkommnisse des Wortes, auf dem sich der Cursor befindet (keine Auswahl benötigt)",
  "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY": "Nur hervorheben, wenn die Auswahl ein komplettes Wort umfasst",
  "DESCRIPTION_INSERT_HINT_ON_TAB": "Aktiviert das Akzeptieren eines Code Hints mithilfe der Tab-Taste",
  "DESCRIPTION_NO_HINTS_ON_DOT": "Deaktiviert das automatische Anzeigen der JavaScript Code Hints, sobald . eingegeben wird",
  "DESCRIPTION_JSHINT_OPTIONS": "Ein Objekt mit den Standardoptionen für JSHint. Unter der folgenden URL finden Sie alle verfügbaren JSHint-Optionen: https://jshint.com/docs/options/",
  "DESCRIPTION_LANGUAGE": "Sprachspezifische Einstellungen",
  "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS": "Zusätzliche Zuordnungen von Dateierweiterung zu Programmiersprache",
  "DESCRIPTION_LANGUAGE_FILE_NAMES": "Zusätzliche Zuordnungen von Dateiname zu Programmiersprache",
  "DESCRIPTION_LINEWISE_COPY_CUT": "Kopieren und Ausschneiden ohne Auswahl kopiert alle Zeilen mit Cursor bzw. schneidet diese aus",
  "DESCRIPTION_INPUT_STYLE": "Die Art, wie CodeMirror mit Eingaben und Auswahlen umgeht. Kann 'textarea' (Standard) oder 'contenteditable' sein, wobei letzteres besser für Screenreader geeignet ist",
  "DESCRIPTION_LINTING_ENABLED": "Aktiviert Linten beim Speichern",
  "DESCRIPTION_ASYNC_TIMEOUT": "Die Zeitbegrenzung in Millisekunden, nach der asynchrone Linter gestoppt werden",
  "DESCRIPTION_LINTING_PREFER": "Array der Linter, die als erstes ausgeführt werden",
  "DESCRIPTION_LIVE_DEV_MULTIBROWSER": "Aktiviert die experimentelle Live-Vorschau",
  "DESCRIPTION_USE_PREFERED_ONLY": "Nur die in linting.prefer angegebenen Linter ausführen",
  "DESCRIPTION_MAX_CODE_HINTS": "Maximale Anzahl an Code Hints, die gleichzeitig angezeigt werden",
  "DESCRIPTION_PATH": "Pfadspezifische Einstellungen",
  "DESCRIPTION_PROXY": "URL des Proxyservers, der bei der Installation von Erweiterungen verwendet wird",
  "DESCRIPTION_SCROLL_PAST_END": "Aktiviert Scrollen über das Ende des Dokuments hinaus",
  "DESCRIPTION_SHOW_CODE_HINTS": "Aktiviert Code Hints",
  "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING": "Der Cursor wird auch angezeigt, wenn eine Auswahl besteht",
  "DESCRIPTION_SHOW_LINE_NUMBERS": "Zeigt Zeilennummern am linken Zeilenrand an",
  "DESCRIPTION_RULERS_COLUMNS": "Ein Array von Spaltennummern zum Zeichnen vertikaler Lineale im Editor. Beispiel: [80, 100]",
  "DESCRIPTION_RULERS_COLORS": "Eine Reihe von Linealfarben, die den Linealoptionen im Editor entsprechen. Beispiel: [\"#3d3d3d\", \"red\"]",
  "DESCRIPTION_RULERS_ENABLED": "true, um Editorlineale zu aktivieren, andernfalls false",
  "DESCRIPTION_SMART_INDENT": "Aktiviert das automatische Einrücken von neuen Blocks",
  "DESCRIPTION_SOFT_TABS": "Aktiviert die \"Soft Tabs\"-Navigation",
  "DESCRIPTION_SORT_DIRECTORIES_FIRST": "Aktiviert, dass Ordner im Dateibaum vor Dateien aufgelistet werden",
  "DESCRIPTION_SPACE_UNITS": "Anzahl der Leerzeichen beim Einrücken, wenn Leerzeichen verwendet werden",
  "DESCRIPTION_STATIC_SERVER_PORT": "Port, der vom internen Server für die Live-Vorschau verwendet wird",
  "DESCRIPTION_STYLE_ACTIVE_LINE": "Aktiviert das Hervorheben der aktiven Zeile",
  "DESCRIPTION_TAB_SIZE": "Anzahl der Leerzeichen, die für Tabs angezeigt werden",
  "DESCRIPTION_USE_TAB_CHAR": "Tabs anstelle von Leerzeichen verwenden",
  "DESCRIPTION_UPPERCASE_COLORS": "Erzeugt großgeschriebene Hex-Werte im Farbeditor",
  "DESCRIPTION_WORD_WRAP": "Aktiviert Zeilenumbruch für lange Zeilen",
  "DESCRIPTION_SEARCH_AUTOHIDE": "Schließen Sie die Suche, sobald der Editor fokussiert ist",
  "DESCRIPTION_DETECTED_EXCLUSIONS": "Ein Array von Dateien, für die erkannt wurde, dass Tern durch sie außer Kontrolle gerät",
  "DESCRIPTION_INFERENCE_TIMEOUT": "Das Zeitlimit, nach dem Tern stoppt zu versuchen, Dateien zu verstehen",
  "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR": "Aktiviert die Anzeige von Fehlern in der Statusleiste",
  "DESCRIPTION_QUICK_VIEW_ENABLED": "Aktiviert die Schnelle Farbansicht",
  "DESCRIPTION_SELECTION_VIEW_ENABLED": "true, um die Auswahlansicht zu aktivieren",
  "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW": "Aktiviert die Bildvorschau auch bei URLs, die keine Dateierweiterung haben",
  "DESCRIPTION_NUMBER_QUICK_VIEW": "true , um die Schnellansicht anzuzeigen, wenn der Mauszeiger über Zahlen im Editor bewegt wird",
  "DESCRIPTION_THEME": "Wählen eines {APP_NAME}-Designs",
  "DESCRIPTION_USE_THEME_SCROLLBARS": "Erlaubt die Verwendung der Scrollbars vom Design",
  "DESCRIPTION_LINTING_COLLAPSED": "Das Linter-Panel einklappen",
  "DESCRIPTION_FONT_FAMILY": "Schriftart ändern",
  "DESCRIPTION_DESKTOP_ZOOM_SCALE": "Wählen Sie einen Zoomfaktor zwischen 0,1 (für eine kompaktere Ansicht) und 2 (für eine größere, stärker vergrößerte Ansicht). Nur in Desktop-Apps verfügbar",
  "DESCRIPTION_FONT_SIZE": "Schriftgröße ändern; z. B. 13px",
  "DESCRIPTION_FIND_IN_FILES_NODE": "Aktiviert die Node-basierte Suche",
  "DESCRIPTION_FIND_IN_FILES_INSTANT": "Aktiviert die Sofortsuche",
  "DESCRIPTION_FONT_SMOOTHING": "Nur Mac: \"subpixel-antialiased\", um Subpixel-Antialiasing zu aktivieren, oder \"antialiased\" für Graustufen-Antialiasing",
  "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW": "Aktiviert das Öffnen der Einstellungsdatei in einer geteilten Ansicht",
  "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE": "Öffnet die Einstellungsdatei in der rechten bzw. unteren Ansicht",
  "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED": "Eine Ansicht einer geteilten Ansicht wird automatisch geschlossen, wenn ihre letzte Datei mit dem Schließen-Button oben rechts geschlossen wird",
  "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS": "Zeigt bei der geteilten Ansicht die Schließen- und Umschalten-Buttons in der Kopfzeile",
  "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT": "/*\n * Dies ist eine schreibgeschützte Datei mit den unterstützten Einstellungen\n * von {APP_NAME}.\n * Verwenden Sie diese Datei als Referenz, um Ihre Einstellungen zu ändern\n * Datei „phcode.json“ im anderen Bereich geöffnet.\n * Weitere Informationen zur Verwendung der darin enthaltenen Einstellungen\n * {APP_NAME}, siehe Webseite unter https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences\n */",
  "DEFAULT_PREFERENCES_JSON_DEFAULT": "Standard",
  "DESCRIPTION_PURE_CODING_SURFACE": "Aktiviert den Ablenkungsfreien Modus, bei dem alle UI-Elemente außer dem Code ausgeblendet werden",
  "DESCRIPTION_INDENT_LINE_COMMENT": "Aktiviert das Einrücken von Zeilenkommentaren",
  "DESCRIPTION_RECENT_FILES_NAV": "Aktiviert das Navigieren durch kürzlich verwendete Dateien",
  "DESCRIPTION_LIVEDEV_WEBSOCKET_PORT": "Der Port, der für den WebSocket-Server der Live-Vorschau genutzt wird",
  "DESCRIPTION_LIVE_DEV_HIGHLIGHT_SETTINGS": "Live-Vorschau Highlight-Einstellungen",
  "DESCRIPTION_LIVEDEV_ENABLE_REVERSE_INSPECT": "false, um die Reverse-Inspection in der Live-Vorschau zu deaktivieren",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW": "Nichts zur Vorschau!",
  "DESCRIPTION_LIVEDEV_EXCLUDED": "Der benutzerdefinierte Server kann diese Datei nicht bereitstellen",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW_EXCLUDED": "Die Livevorschau-Einstellungen sind so konfiguriert, dass nur Dateien aus dem Ordner „{0}“ bereitgestellt werden.",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW_DETAILS": "Bitte wählen Sie eine HTML-Datei für die Vorschau aus",
  "DESCRIPTION_LIVEDEV_PREVIEW_RESTRICTED": "Vorschau nicht verfügbar!",
  "DESCRIPTION_LIVEDEV_PREVIEW_RESTRICTED_DETAILS": "Diese HTML-Datei ist nicht Teil des aktuellen Projekts. Aus Sicherheitsgründen können nur Projektdateien in der Live-Vorschau angezeigt werden. Um eine Vorschau dieser Datei anzuzeigen, öffnen Sie den enthaltenen Ordner als separates Projekt.",
  "DESCRIPTION_LIVEDEV_MAIN_HEADING": "Äh oh!<br> Ihr aktueller Browser unterstützt keine Live-Vorschau.",
  "DESCRIPTION_LIVEDEV_MAIN_SPAN": "Holen Sie sich das beste Live-Vorschau-Erlebnis, indem Sie unsere nativen Apps für Windows, Mac und Linux von <a href=\"https://phcode.io\" style=\"color: white\">phcode.io</a> herunterladen.<br>",
  "DESCRIPTION_LIVEDEV_SECURITY_POPOUT_MESSAGE": "Sie sind dabei, eine Datei für die Live-Vorschau zu öffnen. Bitte fahren Sie nur fort, wenn Sie der Quelle dieses Projekts vertrauen. Klicken Sie auf „Projekt vertrauen“, um fortzufahren, oder schließen Sie dieses Fenster, wenn Sie der Quelle nicht vertrauen.",
  "DESCRIPTION_LIVEDEV_SECURITY_TRUST_MESSAGE": "Sie sind dabei, eine Datei für die Live-Vorschau zu öffnen. Klicken Sie bitte nur dann auf „Projekt vertrauen“, wenn Sie der Quelle dieses Projekts vertrauen!",
  "CONFIRM_EXTERNAL_BROWSER_TITLE": "Pop-ups blockiert",
  "CONFIRM_EXTERNAL_BROWSER_MESSAGE": "Möchten Sie zulassen, dass die Live-Vorschauseite diese URL öffnet: {0}?",
  "TRUST_PROJECT": "Trust & Execute-Vorschau – {0}",
  "TRUST_AUTHORS": "Vertrauen Sie den Autoren dieses Projekts?",
  "DOWNLOAD_FAILED": "Herunterladen fehlgeschlagen.",
  "DOWNLOAD_COMPLETE": "Download abgeschlossen!",
  "UPDATE_SUCCESSFUL": "Aktualisierung erfolgreich!",
  "UPDATE_FAILED": "Update fehlgeschlagen!",
  "VALIDATION_FAILED": "Überprüfung fehlgeschlagen!",
  "INITIALISATION_FAILED": "Initialisierung fehlgeschlagen!",
  "CLEANUP_FAILED": "Bereinigung fehlgeschlagen!",
  "WARNING_TYPE": "Warnung!",
  "CLICK_RESTART_TO_UPDATE": "Klicken Sie auf Neustart, um Brackets zu aktualisieren.",
  "UPDATE_ON_NEXT_LAUNCH": "Das Update wird beim Neustart angewendet.",
  "GO_TO_SITE": "Gehen Sie zu <a href = \"http://brackets.io/\">brackets.io</a> , um es erneut zu versuchen.",
  "INTERNET_UNAVAILABLE": "Keine Internetverbindung verfügbar.",
  "UPDATEDIR_READ_FAILED": "Update-Verzeichnis konnte nicht gelesen werden.",
  "UPDATEDIR_CLEAN_FAILED": "Update-Verzeichnis konnte nicht bereinigt werden.",
  "INITIAL_DOWNLOAD": "Update wird heruntergeladen...",
  "RETRY_DOWNLOAD": "Herunterladen fehlgeschlagen. Neuer Versuch ... Versuch",
  "VALIDATING_INSTALLER": "Download abgeschlossen! Validierung des Installationsprogramms...",
  "CHECKSUM_DID_NOT_MATCH": "Prüfsumme stimmte nicht überein.",
  "INSTALLER_NOT_FOUND": "Installer nicht gefunden.",
  "DOWNLOAD_ERROR": "Beim Herunterladen ist ein Fehler aufgetreten.",
  "NETWORK_SLOW_OR_DISCONNECTED": "Netzwerk ist getrennt oder zu langsam.",
  "RESTART_BUTTON": "Neu starten",
  "LATER_BUTTON": "Später",
  "DESCRIPTION_AUTO_UPDATE": "Aktivieren/deaktivieren Sie die automatische Aktualisierung von {APP_NAME}",
  "AUTOUPDATE_ERROR": "Fehler!",
  "AUTOUPDATE_IN_PROGRESS": "Ein Update ist bereits in Arbeit.",
  "NUMBER_WITH_PERCENTAGE": "{0} %",
  "CMD_FIND_RELATED_FILES": "Verwandte Dateien finden",
  "PHP_VERSION_INVALID": "Fehler beim Parsen der PHP-Version. Bitte überprüfen Sie die Ausgabe des Befehls „php –version“.",
  "PHP_UNSUPPORTED_VERSION": "Installieren Sie die PHP7-Laufzeitumgebung, um PHP-bezogene Tools wie Codehinweise, Parameterhinweise, Sprung zu Definition und mehr zu aktivieren. Version gefunden: {0}",
  "PHP_EXECUTABLE_NOT_FOUND": "PHP-Laufzeit nicht gefunden. Installieren Sie die PHP7-Laufzeitumgebung und aktualisieren Sie „executablePath“ in den PHP-Einstellungen entsprechend. Dies ermöglicht PHP-bezogene Tools wie Codehinweise, Parameterhinweise, Sprung zu Definition und mehr.",
  "PHP_PROCESS_SPAWN_ERROR": "Fehlercode {0} beim Starten des PHP-Prozesses aufgetreten.",
  "PHP_SERVER_ERROR_TITLE": "Fehler",
  "PHP_SERVER_MEMORY_LIMIT_INVALID": "Das von Ihnen angegebene Speicherlimit ist ungültig. Überprüfen Sie die PHP-Einstellungen, um den richtigen Wert festzulegen.",
  "DESCRIPTION_PHP_TOOLING_CONFIGURATION": "PHP-Tooling-Standardkonfigurationseinstellungen",
  "OPEN_PREFERENNCES": "Öffnen Sie die Einstellungen",
  "LANGUAGE_TOOLS_PREFERENCES": "Einstellungen für Sprachwerkzeuge",
  "FIND_ALL_REFERENCES": "Alle Referenzen finden",
  "REFERENCES_IN_FILES": "Verweise",
  "REFERENCE_IN_FILES": "Hinweis",
  "REFERENCES_NO_RESULTS": "Für die aktuelle Cursorposition sind keine Referenzen verfügbar",
  "CMD_FIND_DOCUMENT_SYMBOLS": "Dokumentsymbole finden",
  "CMD_FIND_PROJECT_SYMBOLS": "Finden Sie Projektsymbole",
  "REMOTE_DEBUGGING_ENABLED": "Remote-Debugging auf localhost aktiviert:",
  "REMOTE_DEBUGGING_PORT_INVALID": "Remote-Debugging auf Port {0} kann nicht aktiviert werden. Portnummern sollten zwischen {1} und {2} liegen.",
  "DESCRIPTION_EXTERNAL_APPLICATION_ASSOCIATE": "Zuordnungen für die Dateierweiterung zu externen Anwendungen. Syntax: „<Dateityp>“: „<Standard|Anwendungsname|Anwendungspfad>“, Verwenden Sie „Standard“, um Dateien in der Standardanwendung des Systems für den Dateityp zu öffnen.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_TITLE": "Grafikdateien in externen Editoren öffnen.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_MSG": "Ihr aktueller Ordner enthält Grafikdateitypen, die von {APP_NAME} nicht unterstützt werden.<br/> Sie können jetzt bestimmte Dateitypen mit externen Editoren verknüpfen. Nach der Zuordnung können Sie Grafikdateien wie .xd, .psd, .jpg, .png, .ai, .svg in ihren Standardanwendungen öffnen, indem Sie auf die Dateien im Dateibaum doppelklicken.<br/><br/> Bitte klicken Sie auf die Schaltfläche „Ok“, um die Grafikdateitypen mit ihren jeweiligen Standardanwendungen zu verknüpfen.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_CNF_MSG": "Die folgenden Dateitypen wurden erfolgreich Standardanwendungen zugeordnet.<br/> {0} Sie haben die Möglichkeit, Ihre Einstellungen zum Löschen/Hinzufügen neuer Dateitypzuordnungen in phcode.json zu ändern, indem Sie zum Menü „Debug-&gt;Einstellungsdatei öffnen“ gehen.",
  "UNSUPPORTED_BROWSER_TITLE": "Browser wird nicht unterstützt",
  "UNSUPPORTED_BROWSER_MESSAGE": "Bitte verwenden Sie einen modernen Browser (nicht älter als 3 Jahre).",
  "UNSUPPORTED_BROWSER_MOBILE_TITLE": "Mobile Browser werden nicht unterstützt",
  "UNSUPPORTED_BROWSER_MOBILE": "Mobile und Tablet-Browser werden derzeit nicht vollständig unterstützt. Sie können diesen Dialog schließen, aber einige Funktionen in Phoenix werden in diesem Browser nicht funktionieren.<br/><br/> Wir arbeiten an der Entwicklung nativer Apps für iOS und Android. <a href=\"https://github.com/phcode-dev/phoenix/discussions/1046\" target=\"_blank\">Beteiligen Sie sich hier an der Diskussion!</a>",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER_TITLE": "Zugriff auf lokale Ordner wird vom Browser nicht unterstützt",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER": "Tut mir leid, anscheinend unterstützt Ihr aktueller Browser das Öffnen lokaler Ordner nicht. Für diese Funktion empfehlen wir die Verwendung von Chrome, Edge oder Opera.<br/><br/> Alternativ arbeiten wir an der Entwicklung nativer Apps für Windows, Mac, Linux, iOS und Android, um volle Unterstützung zu bieten. <a href=\"https://github.com/phcode-dev/phoenix/discussions/1047\" target=\"_blank\">Bleiben Sie dran für Updates!</a>",
  "ATTENTION_SAFARI_USERS": "Safari-Benutzer aufgepasst",
  "ATTENTION_SAFARI_USERS_MESSAGE": "<span>Safari löscht Website-Daten automatisch, wenn eine Website nicht innerhalb von 7 Tagen erneut besucht wird. {APP_NAME} ist zum Speichern Ihrer Projekte auf Browserspeicher angewiesen, der aufgrund dieser Richtlinie möglicherweise entfernt wird.<br/><br/> Es wird empfohlen <strong>, die macOS-Desktop-App</strong> von <a href='https://phcode.io' target='_blank' style='color: white'>https://phcode.io</a> herunterzuladen</span>",
  "CANNOT_PUBLISH_LARGE_PROJECT": "Großes Projekt kann nicht veröffentlicht werden",
  "CANNOT_PUBLISH_LARGE_PROJECT_MESSAGE": "Phoenix befindet sich noch in der experimentellen Alpha. Wir haben die Synchronisierung von Projekten mit mehr als 500 Dateien noch nicht aktiviert.",
  "SHARE_WEBSITE": "Website veröffentlichen und teilen?",
  "PUBLISH": "Veröffentlichen",
  "PUBLISH_CONSENT_MESSAGE": "Zeigen Sie Änderungen schnell in der Vorschau an und teilen Sie Ihre Website mit anderen. Phoenix kann diese Website unter {0} für Sie veröffentlichen. Die veröffentlichten Links sind für einen Zeitraum von 30 Tagen gültig. </br>Möchten Sie Ihre Website veröffentlichen und teilen?",
  "PUBLISH_SYNC_IN_PROGRESS": "Synchronisierung für Vorschau läuft...",
  "PUBLISH_PAGE": "Klicken Sie hier, um diese Website zu veröffentlichen und zu teilen",
  "PUBLISH_VIEW_PAGE": "Klicken Sie hier, um die veröffentlichte Seite anzuzeigen",
  "MISSING_FIELDS": "Fehlende Felder",
  "PLEASE_FILL_ALL_REQUIRED": "Bitte füllen Sie alle rot markierten Pflichtfelder aus",
  "CODE_EDITOR": "Code-Editor",
  "BUILD_THE_WEB": "Bauen Sie das Web auf",
  "IMPORT_PROJECT": "Projekt importieren",
  "GITHUB_PROJECT": "GitHub-Projekt",
  "NEW_PROJECT_FROM_GITHUB": "Neues Projekt von GitHub",
  "GITHUB_REPO_URL": "GitHub Repo-URL:",
  "CREATE_PROJECT": "Projekt erstellen",
  "SETTING_UP_PROJECT": "Projekt einrichten",
  "LOCATION": "Ort :",
  "DOWNLOADING": "Wird heruntergeladen...",
  "DOWNLOADING_FILE": "{0} wird heruntergeladen...",
  "EXTRACTING_FILES_PROGRESS": "Extrahieren von {0} von {1} Dateien.",
  "COMPRESS_FILES_PROGRESS": "Komprimierung von {0} von {1} Dateien.",
  "DOWNLOAD_FAILED_MESSAGE": "Stellen Sie sicher, dass die Download-URL gültig ist. </br>Hinweis: Da sich Phoenix in der Alpha-Phase befindet, sind Private Repos und GitHub-URLs mit mehr als 25 MB nicht zulässig.",
  "PLEASE_SELECT_A_FOLDER": "Bitte wählen Sie einen Ordner aus...",
  "UNZIP_IN_PROGRESS": "Entpacken von Dateien...",
  "UNZIP_FAILED": "Fehler: Entpacken fehlgeschlagen.",
  "CONFIRM_REPLACE_TITLE": "Ersetzen bestätigen",
  "KEEP_BOTH": "Behalte beides",
  "EXPLORE": "HTML-Spiele",
  "BLOG": "Bloggen",
  "PHOENIX_DEFAULT_PROJECT": "Standardprojekt",
  "PROJECT_NAME": "Projektname:",
  "NEW_HTML": "Neues HTML-Projekt",
  "LICENSE": "Lizenz & Credits:",
  "PREVIEW": "Vorschau",
  "BUILD_WEBSITE": "Website erstellen",
  "VIEW_MORE": "Mehr sehen...",
  "NEW_PROJECT_NOTIFICATION": "Klicken Sie auf dieses Symbol, um das Fenster „Neues Projekt“ erneut zu öffnen.</br> Sehen Sie sich die letzten Projekte an, öffnen Sie Ordner oder starten Sie Projekte anhand von Vorlagen.</br><img src=\"styles/images/new_project.png\"><br/> <a href='#' style='float:right;'>OK</a>",
  "BEAUTIFY_CODE_NOTIFICATION": "Klicken Sie hier oder drücken Sie <b>„{0}“</b> , um den Code zu verschönern.</br><img src=\"styles/images/beautify.gif\"><br/> <a href='#' style='float:right;'>OK</a>",
  "DEFAULT_PROJECT_NOTIFICATION": "Klicken Sie hier, um die zu öffnen<br/> <b>Standardprojekt</b> in Phoenix.</br> <a href='#' style='float:right;'>OK</a>",
  "DIRECTORY_REPLACE_MESSAGE": "Der ausgewählte Ordner <span class='dialog-filename'>{0}</span> ist nicht leer. Möchten Sie den Ordnerinhalt wirklich durch das Projekt ersetzen?",
  "DEFAULT_PROJECT_HTML_CLICK_HERE": "Klicken Sie hier, um dieses &ltspan&gt in der HTML-Datei zu finden",
  "BUILD_WEBSITE_SECTION": "Website erstellen",
  "LEARN_SECTION": "Lernen Sie mit Beispielen",
  "CREATE_EXTENSION_SECTION": "{APP_NAME}-Erweiterungen und -Designs erstellen",
  "CREATE_EXTENSION": "Erweiterung erstellen",
  "CREATE_THEME": "Thema erstellen",
  "WEBPAGE_HOME_PAGE": "Startseite",
  "WEBPAGE_BLOG": "Blog-Seite",
  "WEBPAGE_DASHBOARD": "HTML-Dashboard",
  "WEBPAGE_BOOTSTRAP_EXAMPLES": "Bootstrap-Beispiele",
  "PROJECTS_AT_A_GLANCE": "Ihre Projekte auf einen Blick",
  "PROJECT_AT_GLANCE_DESCRIPTION": "Sehen Sie sich das Video an, um loszulegen.",
  "PROJECT_FROM_BROWSER": "In Ihrem Browser gespeichert",
  "PROJECT_FROM_BROWSER_TERSE": "Browserspeicher",
  "PROJECT_SHOW_ON_STARTUP": "Diesen Dialog beim Start anzeigen",
  "GUIDED_LIVE_PREVIEW": "Nehmen Sie einige Codeänderungen in der HTML-Datei vor, um eine Live-Vorschau anzuzeigen.</br> <a href='#' style='float:right;'>Ok</a>",
  "GUIDED_LIVE_PREVIEW_POPOUT": "Klicken Sie auf diese Schaltfläche, um die Live-Vorschau auf einer neuen Registerkarte anzuzeigen.</br> <a href='#' style='float:right;'>OK</a>",
  "ENJOYING_APP": "Gefällt dir {APP_NAME}?",
  "GITHUB_STARS_POPUP": "<div>Ihre Unterstützung motiviert unser kleines Team <b style='color: darkblue'>, phcode.dev</b> noch besser zu machen.<br/> Bitte markieren Sie uns mit einem Stern oder ziehen Sie in Erwägung, uns auf GitHub zu sponsern:",
  "GITHUB_STARS_POPUP_TWITTER": "Geben Sie Feedback oder teilen Sie es auf Twitter mit:",
  "TEST_TRANSLATE": "Verwenden Sie dies, um Übersetzungen zu testen",
  "BEAUTIFY_ERROR": "Code konnte nicht verschönert werden. Überprüfen Sie die Syntax.",
  "BEAUTIFY_ERROR_ORIGINAL_CHANGED": "Konnte nicht verschönern. Editortext nach Verschönerung geändert.",
  "BEAUTIFY_PROJECT_BUSY_MESSAGE": "Verschönerungsdatei {0}",
  "BEAUTIFY_ERROR_SELECTION": "Verschönern nicht möglich.</br>Unvollständiger Codeblock ausgewählt oder ungültige Syntax.",
  "BEAUTIFY_OPTIONS": "Optionen, die steuern, wie Beautify Code funktioniert",
  "BEAUTIFY_OPTION_PRINT_WIDTH": "Geben Sie die Linienlänge an, die der Verschönerer umbrechen soll",
  "BEAUTIFY_OPTION_SEMICOLON": "Fügen Sie am Ende jeder Anweisung ein Semikolon hinzu",
  "BEAUTIFY_OPTION_SINGLE_QUOTE": "Verwenden Sie einfache Anführungszeichen anstelle von doppelten Anführungszeichen",
  "BEAUTIFY_OPTION_QUOTE_PROPS": "Ändern, wenn Eigenschaften in Objekten in Anführungszeichen gesetzt werden",
  "BEAUTIFY_OPTION_BRACKET_SAME_LINE": "Platzieren Sie das > eines mehrzeiligen HTML-Elements (HTML, JSX, Vue, Angular) am Ende der letzten Zeile, anstatt allein in der nächsten Zeile (gilt nicht für selbstschließende Elemente).",
  "BEAUTIFY_OPTION_SINGLE_ATTRIBUTE_PER_LINE": "Erzwingen Sie ein einzelnes Attribut pro Zeile in HTML, Vue und JSX",
  "BEAUTIFY_OPTION_PROSE_WRAP": "Prosa umbrechen, wenn sie die Druckbreite in Markdown-Dateien überschreitet",
  "BEAUTIFY_OPTION_PRINT_TRAILING_COMMAS": "Geben Sie, wo immer möglich, nachgestellte Kommas in mehrzeiligen, durch Kommas getrennten syntaktischen Strukturen aus"
});