/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "језик система",
  "PROJECT_BUSY": "Пројектне операције су у току",
  "DUPLICATING": "Дуплицирање {0}",
  "MOVING": "Премештање {0}",
  "COPYING": "Копирање {0}",
  "DELETING": "Брисање {0}",
  "RENAMING": "Преименовање",
  "STORED_IN_YOUR_BROWSER": "Чува се у вашем претраживачу",
  "SUPPORT_US_OPEN_COLLECTIVE": "Подржите нас на Опен Цоллецтиве",
  "GENERIC_ERROR": "(грешка {0})",
  "NOT_FOUND_ERR": "Непостојећа датотека.",
  "NOT_READABLE_ERR": "Датотека не може бити учитана.",
  "EXCEEDS_MAX_FILE_SIZE": "Датотеке веће од {0} MB се не могу отворити у {APP_NAME}-у.",
  "NO_MODIFICATION_ALLOWED_ERR": "Циљани директоријум не може бити измењен.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "Тренутна овлашћења Вам не дозвољавају да правите измене.",
  "CONTENTS_MODIFIED_ERR": "Ова датотека је била измењена ван {APP_NAME}-а.",
  "UNSUPPORTED_ENCODING_ERR": "{APP_NAME} тренутно подржава искључиво текстуалне датотеке које су енкодиране у UTF-8 формату.",
  "ENCODE_FILE_FAILED_ERR": "{АПП_НАМЕ} није могао да кодира садржај датотеке.",
  "DECODE_FILE_FAILED_ERR": "{АПП_НАМЕ} није могао да декодира садржај датотеке.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "{АПП_НАМЕ} тренутно не подржава текстуалне датотеке кодиране УТФ-16.",
  "FILE_EXISTS_ERR": "Датотека или директоријум већ постоји.",
  "FILE": "датотеци",
  "FILE_TITLE": "Датотека",
  "DIRECTORY": "директоријум",
  "DIRECTORY_TITLE": "Директоријум",
  "DIRECTORY_NAMES_LEDE": "Имена директоријума",
  "FILENAMES_LEDE": "Имена датотека",
  "FILENAME": "Име датотеке",
  "DIRECTORY_NAME": "Име директоријума",
  "ERROR_LOADING_PROJECT": "Грешка приликом учитавања пројекта",
  "OPEN_DIALOG_ERROR": "Дошло је до грешке приликом приказивања дијалога за отварање датотеке. (грешка {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "Дошло је до грешке приликом покушаја да се учита директоријум <span class='dialog-filename'>{0}</span>. (грешка {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "Дошло је до грешке приликом ишчитавања садржаја директоријума <span class='dialog-filename'>{0}</span>. (грешка {1})",
  "ZOOM_WITH_SHORTCUTS": "Користите пречице на тастатури за зумирање",
  "ZOOM_WITH_SHORTCUTS_DETAILS": "Користите пречице на тастатури <code><i>{0}</i></code> за увећање и <code><i>{1}</i></code> за умањивање.",
  "ERROR_OPENING_FILE_TITLE": "Грешка при отварању датотеке",
  "ERROR_OPENING_FILE": "Дошло је до грешке приликом покушаја да се отвори датотека <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_OPENING_FILES": "Дошло је до грешке приликом покушаја да се отворе следеће датотеке:",
  "ERROR_RELOADING_FILE_TITLE": "Грешка при поновном учитавању измена са диска",
  "ERROR_RELOADING_FILE": "Дошло је до грешке приликом покушаја да се поново учита датотека <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_SAVING_FILE_TITLE": "Грешка при чувању датотеке",
  "ERROR_SAVING_FILE": "Дошло је до грешке приликом покушаја да се сачува датотека <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_FILE_TITLE": "Грешка приликом преименовања датотеке {0}",
  "ERROR_RENAMING_FILE": "Дошло је до грешке приликом покушаја да се преименује датотека {2} <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "Датотека или директоријум није део тренутно отвореног пројекта. Нажалост, у овом тренутку могу се преименовати само пројектне датотеке.",
  "ERROR_MOVING_FILE_TITLE": "Грешка при премештању {0}",
  "ERROR_MOVING_FILE": "Дошло је до грешке при покушају да преместите {2} <span class='dialog-filename'>{0}</span> . {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "Није могуће преместити датотеку/директоријум, јер они нису део тренутног пројекта.",
  "ERROR_DELETING_FILE_TITLE": "Грешка при брисању датотеке {0}",
  "ERROR_DELETING_FILE": "Дошло је до грешке приликом покушаја да се обрише датотека {2} <span class='dialog-filename'>{0}</span>. {1}",
  "INVALID_FILENAME_TITLE": "Име {0} није валидно",
  "CANNOT_PASTE_TITLE": "Није могуће налепити {0}",
  "CANNOT_DOWNLOAD_TITLE": "Није могуће преузети {0}",
  "ERR_TYPE_DOWNLOAD_FAILED": "Дошло је до грешке при преузимању <span class='dialog-filename'>{0}</span>",
  "ERR_TYPE_PASTE_FAILED": "Дошло је до грешке при лепљењу <span class='dialog-filename'>{0}</span> у <span class='dialog-filename'>{1}</span>",
  "CANNOT_DUPLICATE_TITLE": "Није могуће дуплирати",
  "ERR_TYPE_DUPLICATE_FAILED": "Дошло је до грешке при дуплирању <span class='dialog-filename'>{0}</span>",
  "ERR_TYPE_DUPLICATE_FAILED_NO_FILE": "Изаберите датотеку за дуплирање.",
  "INVALID_FILENAME_MESSAGE": "Име {0} не сме садржати системски резервисане речи, не сме се завршити тачком (.) или користити неки од следећих карактера: <code class='emphasized'>{1}</code>",
  "ENTRY_WITH_SAME_NAME_EXISTS": "Датотека или директоријум са именом <span class='dialog-filename'>{0}</span> већ постоји.",
  "ERROR_CREATING_FILE_TITLE": "Грешка при креирању {0}",
  "ERROR_CREATING_FILE": "Дошло је до грешке приликом покушаја да се креира {0} <span class='dialog-filename'>{1}</span>. {2}",
  "ERROR_MIXED_DRAGDROP": "Директоријум се не може учитавати у исто време када и остале датотеке.",
  "ERROR_KEYMAP_TITLE": "Грешка приликом ишчитавања корисничке мапе пречица на тастатури",
  "ERROR_KEYMAP_CORRUPT": "Ваша мапа пречица на тастатури није валидан JSON. Датотека ће бити отворена како бисте исправили формат.",
  "ERROR_LOADING_KEYMAP": "Ваша мапа пречица на тастатури није валидна UTF-8 енкодирана текстуална датотека и не може се учитати",
  "ERROR_RESTRICTED_COMMANDS": "Не можете поново доделити пречице овим командама: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "Не можете доделити ове пречице: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "Додајете више пречица на тастатури за ове команде: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "Имате више комбинација за ове пречице: {0}",
  "ERROR_INVALID_SHORTCUTS": "Ове пречице нису валидне: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "Додајете пречице на тастатури непостојећим командама: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "Грешка приликом ишчитавања подешавања",
  "ERROR_PREFS_PROJECT_LINT": "Подешавања пројекта",
  "ERROR_PREFS_PROJECT_LINT_MESSAGE": "Грешка: Пројекат садржи датотеке `.брацкетс.јсон` и `.пхцоде.јсон`, што узрокује конфликт. Избришите `.брацкетс.јсон` или `.пхцоде.јсон`, а затим поново учитајте пројекат.",
  "ERROR_PREFS_CORRUPT": "Ваша датотека са подешавањима није валидан JSON. Датотека ће бити отворена како бисте исправили формат. Биће неопходно да поново покренете {APP_NAME} како би измене биле примењене.",
  "ERROR_PROJ_PREFS_CORRUPT": "Датотека са подешавањима вашег пројекта није важећа ЈСОН. Датотека ће се отворити да бисте могли да исправите формат. Мораћете поново да учитате пројекат да би промене ступиле на снагу.",
  "ERROR_IN_BROWSER_TITLE": "Упс! {APP_NAME} још увек не ради у веб претраживачу.",
  "ERROR_IN_BROWSER": "Апликација {APP_NAME} је направљена помоћу HTML-а, али тренутно ради као \"desktop\" апликација па је можете користити за измену локалних датотека. Молимо Вас користите \"application shell\" на <b>github.com/adobe/brackets-shell</b> репозиторијуму за покретање {APP_NAME}-а.",
  "ERROR_MAX_FILES_TITLE": "Грешка приликом индексирања датотека",
  "ERROR_MAX_FILES": "Пројекат садржи више од 30.000 датотека. Делови апликације који врше обраду над више датотека могу постати неактивни или се понашати као да је пројекат празан. <a href='https://github.com/adobe/brackets/wiki/Large-Projects'>Прочитајте више о раду са великим пројектима</a>.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "Грешка при покретању претраживача",
  "ERROR_CANT_FIND_CHROME": "Google Chrome претраживач није пронађен. Молимо потврдите да је инсталиран.",
  "ERROR_LAUNCHING_BROWSER": "Грешка приликом покретања претраживача. (error {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "Грешка у живом приказу",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "Повезивање са веб претраживачем",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "Да би се живи приказ повезао, потребно је да поново покренете Chrome са укљученим подешавањима за \"remote debugging\".<br /><br />Да ли желите поново да покренете Chrome са укљученим подешавањима за \"remote debugging\"?<br /><br />",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "Није могуће учитати страницу са живим приказом.",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "За покретање живог приказа са датотеком која је \"server-side\", морате навести основну URL адресу за овај пројекат.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "Грешка приликом покретања HTTP сервера за \"живе\" развојне датотеке. Молимо покушајте поново.",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "За више информација, погледајте <a href='{0}' title='{0}'>Отклањање грешака у конекцији приликом развоја уживо</a>.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "Живи приказ",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "Живи приказ: Успостављање конекције…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "Живи приказ: Иницијализација…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "Сервер за преглед уживо активан",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "Живи приказ",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "Изаберите Филе То Ливе Превиев",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "Поново учитај страницу",
  "LIVE_DEV_TOGGLE_LIVE_HIGHLIGHT": "Укључи Истакнуто у прегледу уживо",
  "LIVE_DEV_CLICK_POPOUT": "Искачући преглед уживо у новом прозору",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "Закачи на страницу за преглед откачи",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "Живи приказ (не освежава се због грешке у синтакси)",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "Живи приказ је отказан јер су развојни алати били отворени у претраживачу",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "Живи приказ је отказан јер је страница затворена у претраживачу",
  "LIVE_DEV_NAVIGATED_AWAY": "Живи приказ је отказан јер је претраживач отишао на страницу која није део тренутног пројекта",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "Живи приказ је отказан из непознатог разлога ({0})",
  "SAVE_CLOSE_TITLE": "Сачувај измене",
  "SAVE_CLOSE_MESSAGE": "Да ли желите да сачувате измене које сте направили у документу <span class='dialog-filename'>{0}</span>?",
  "SAVE_CLOSE_MULTI_MESSAGE": "Да ли желите да сачувате Ваше измене над следећим датотекама?",
  "EXT_MODIFIED_TITLE": "Екстерне измене",
  "CONFIRM_DELETE_TITLE": "Потврди брисање",
  "CONFIRM_FILE_DELETE": "Да ли сте сигурни да желите да избришете датотеку <span class='dialog-filename'>{0}</span> ?",
  "CONFIRM_FOLDER_DELETE": "Да ли сте сигурни да желите обрисати директоријум <span class='dialog-filename'>{0}</span>?",
  "FILE_DELETED_TITLE": "Датотека обрисана",
  "EXT_MODIFIED_WARNING": "Датотека <span class='dialog-filename'>{0}</span> је измењена на диску.<br /><br />Да ли желите да сачувате датотеку и преснимите те измене?",
  "EXT_MODIFIED_MESSAGE": "Датотека <span class='dialog-filename'>{0}</span> је измењена на диску, али садржи и измене начињене у {APP_NAME}-у.<br /><br />Коју верзију желите да сачувате?",
  "EXT_DELETED_MESSAGE": "Датотека <span class='dialog-filename'>{0}</span> је обрисана са диска, али садржи несачуване измене начињене у {APP_NAME}-у.<br /><br />Да ли желите да сачувате Ваше измене?",
  "EXT_ALWAYS_MODIFIED_BUTTON_TOOLTIP": "Увек замените датотеке док се пројекат не промени или поново покрене",
  "WINDOW_UNLOAD_WARNING": "Да ли сте сигурни да желите да одете до друге УРЛ адресе и напустите {АПП_НАМЕ}?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "Имате несачуване промене! Да ли сте сигурни да желите да одете до друге УРЛ адресе и напустите {АПП_НАМЕ}?",
  "DONE": "Завршено",
  "OK": "OK",
  "CANCEL": "Откажи",
  "DONT_SAVE": "Немој сачувати",
  "SAVE": "Сачувај",
  "SAVE_AS": "Сачувај као…",
  "SAVE_AND_OVERWRITE": "Пресними",
  "ALWAYS_OVERWRITE": "Увек препиши",
  "DELETE": "Обриши",
  "BUTTON_YES": "Да",
  "BUTTON_NO": "Не",
  "FIND_MATCH_INDEX": "{0} од {1}",
  "FIND_NO_RESULTS": "Нема резултата",
  "FIND_QUERY_PLACEHOLDER": "Пронађи…",
  "FIND_HISTORY_MAX_COUNT": "Максималан број ставки претраге у историји претраге",
  "REPLACE_PLACEHOLDER": "Замени са…",
  "BUTTON_REPLACE_ALL": "Комплет…",
  "BUTTON_REPLACE_BATCH": "Група…",
  "BUTTON_REPLACE_ALL_IN_FILES": "Замени…",
  "BUTTON_REPLACE": "Замени",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "Следеће поклапање",
  "BUTTON_PREV_HINT": "Претходно поклапање",
  "BUTTON_CASESENSITIVE_HINT": "Иста величина",
  "BUTTON_REGEXP_HINT": "Регуларни израз",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "Замени без опозива",
  "REPLACE_WITHOUT_UNDO_WARNING": "Зато што је потребно променити више од {0} датотека, {APP_NAME} ће изменити неотворене датотеке на диску.<br />Нећете бити у могућности да опозовете измене у овим датотекама.",
  "BUTTON_REPLACE_WITHOUT_UNDO": "Замени без опозива",
  "OPEN_FILE": "Отвори датотеку",
  "SAVE_FILE_AS": "Сачувај датотеку",
  "CHOOSE_FOLDER": "Изабери директоријум",
  "RELEASE_NOTES": "Белешке о тренутној верзији",
  "NO_UPDATE_TITLE": "Имате актуелну верзију!",
  "NO_UPDATE_MESSAGE": "Тренутно поседујете актуелну верзију апликације {APP_NAME}.",
  "FIND_REPLACE_TITLE_LABEL": "Замени",
  "FIND_REPLACE_TITLE_WITH": "са",
  "FIND_TITLE_LABEL": "Пронађено",
  "FIND_TITLE_SUMMARY": "&mdash; {0} {1} {2} у {3}",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "у <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_NO_SCOPE": "у пројекту",
  "FIND_IN_FILES_ZERO_FILES": "Филтер искључује све датотеке {0}",
  "FIND_IN_FILES_FILE": "датотеци",
  "FIND_IN_FILES_FILES": "датотека",
  "FIND_IN_FILES_MATCH": "поклапање",
  "FIND_IN_FILES_MATCHES": "поклапања",
  "FIND_IN_FILES_MORE_THAN": "Преко ",
  "FIND_IN_FILES_PAGING": "{0}&mdash;{1}",
  "FIND_IN_FILES_FILE_PATH": "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "Притисните Ctrl/Cmd и кликните како бисте раширили/скупили све",
  "FIND_IN_FILES_INDEXING": "Индексирање за тренутну претрагу…",
  "FIND_IN_FILES_SEARCHING": "Претраживање датотека…",
  "FIND_IN_FILES_SEARCHING_IN": "у {0}",
  "FIND_IN_FILES_INDEXING_PROGRESS": "Индексирање {0} од {1} фајлова за тренутну претрагу…",
  "REPLACE_IN_FILES_ERRORS_TITLE": "Замени грешке",
  "REPLACE_IN_FILES_ERRORS": "Следеће датотеке нису модификоване зато што су измењене након претраге или у њих није било могуће уписивати.",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "Грешка приликом учитавања информација о новој верзији",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "Дошло је до проблема приликом преузимања последњих информација о новој верзији са сервера. Молимо проверите да ли сте повезани на интернет и покушајте поново.",
  "NEW_FILE_FILTER": "Нови сет искључења…",
  "CLEAR_FILE_FILTER": "Немој исључити датотеке",
  "NO_FILE_FILTER": "Ниједна датотека није искључена",
  "EXCLUDE_FILE_FILTER": "Искључи {0}",
  "INCLUDE_FILE_FILTER": "Укључи {0}",
  "EXCLUDE_FILE_FILTER_DROPDOWN": "Искључи",
  "INCLUDE_FILE_FILTER_DROPDOWN": "Укључи",
  "EDIT_FILE_FILTER": "Измени…",
  "FILE_FILTER_DIALOG": "Уреди филтер за изузимање",
  "FILE_FILTER_INSTRUCTIONS": "Изузми датотеке и фасцикле које одговарају било ком од следећих <a href='{0}' title=\"{0}\">џокер знакова</a> . Унесите сваки низ у нови ред. На пример<ul><li> <code>*.js</code> ће одговарати <code>a/b/x.js</code> , <code>xyx.js</code> итд.</li><li> <code>./*.css</code> ће одговарати само <code>x.css</code> у корену пројекта, али не <code>y/x.css</code> у поддиректоријуму.</li></ul>",
  "FILE_FILTER_INSTRUCTIONS_INCLUDE": "Укључи само датотеке и фасцикле који одговарају било ком од следећих <a href='{0}' title=\"{0}\">џокер знакова</a> . Унесите сваки низ у нови ред. На пример<ul><li> <code>*.js</code> ће одговарати <code>a/b/x.js</code> , <code>xyx.js</code> итд.</li><li> <code>./*.css</code> ће одговарати само <code>x.css</code> у корену пројекта, али не <code>y/x.css</code> у поддиректоријуму.</li></ul>",
  "FILTER_NAME_PLACEHOLDER": "Дај име овом сету искључења (опционо)",
  "FILTER_NAME_REMAINING": "Преостало знакова: {0}",
  "FILE_FILTER_CLIPPED_SUFFIX": "и још {0}",
  "FILTER_COUNTING_FILES": "Пребројавам датотеке…",
  "FILTER_FILE_COUNT": "Дозвољава {0} од {1} датотека {2}",
  "FILTER_FILE_COUNT_ALL": "Дозвољава свих {0} датотека {1}",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "Брза измена није доступна на тренутној позицији курсора",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "CSS Брза измена: позиционирајте курсор на једно име класе",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "CSS Брза измена: непотпун атрибут класе",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "CSS Брза измена: непотпун атрибут идентификатора",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "CSS Брза измена: позиционирајте курсор на таг, класу, или идентификатор",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "CSS Времендска функција Брза измена: синтакса није валидна",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "JS Брза измена: позиционирајте курсор на име функције",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "Брзи документи нису доступни за тренутну позицију курсора",
  "PROJECT_LOADING": "Учитавам…",
  "UNTITLED": "Неименовано",
  "WORKING_FILES": "Радне датотеке",
  "TOP": "Горе",
  "BOTTOM": "Доле",
  "LEFT": "Лево",
  "RIGHT": "Десно",
  "CMD_SPLITVIEW_NONE": "Без поделе",
  "CMD_SPLITVIEW_VERTICAL": "Вертикална подела",
  "CMD_SPLITVIEW_HORIZONTAL": "Хоризонтална подела",
  "SPLITVIEW_MENU_TOOLTIP": "Подели едитор вертикално или хоризонтално",
  "GEAR_MENU_TOOLTIP": "Конфигуриши радни сет",
  "SPLITVIEW_INFO_TITLE": "Већ отворена",
  "SPLITVIEW_MULTIPANE_WARNING": "Датотека је већ отворена у другом панелу. {APP_NAME} ће ускоро подржавати отварање исте датотеке у више панела. До тада, датотека ће бити приказана у панелу у коме је већ отворена.<br /><br />(Ова порука ће се приказати само једном.)",
  "KEYBOARD_OVERLAY_TEXT": "Користите стрелице за навигацију или куцајте да бисте изабрали елементе корисничког интерфејса.",
  "KEYBOARD_SHORTCUT_CHANGE_TITLE": "Промените пречицу на тастатури…",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_TITLE": "Промените пречицу на тастатури",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_TEXT": "Притисните нову комбинацију тастера за <b>„{0}“</b> (Тренутно: <b>{1}</b> )",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_DUPLICATE": "Упозорење: Комбинација тастера <b>{0}</b> је већ додељена <b>&#39;{1}&#39;</b> . Поново доделити <b>&#39;{2}&#39;</b> ?",
  "KEYBOARD_SHORTCUT_ASSIGN": "Додели",
  "KEYBOARD_SHORTCUT_NONE": "Ниједан",
  "KEYBOARD_SHORTCUT_MENU_SHOW_SHORTCUTS": "Пречице на тастатури…",
  "KEYBOARD_SHORTCUT_MENU_SHOW_SHORTCUTS_BUTTON": "Прикажи све пречице…",
  "KEYBOARD_SHORTCUT_TABLE_BASE_KEY": "Основни кључ",
  "KEYBOARD_SHORTCUT_TABLE_KEY_BINDING": "Пречица",
  "KEYBOARD_SHORTCUT_TABLE_COMMAND_ID": "ИД команде",
  "KEYBOARD_SHORTCUT_TABLE_COMMAND_NAME": "Цомманд",
  "KEYBOARD_SHORTCUT_TABLE_DOUBLE_CLICK": "Двапут кликните да бисте променили пречицу",
  "KEYBOARD_SHORTCUT_TABLE_ORIGIN": "Порекло",
  "KEYBOARD_SHORTCUT_ORIG_EXTENSION": "Продужетак",
  "KEYBOARD_SHORTCUT_PANEL_TITLE": "Пречице на тастатури",
  "KEYBOARD_SHORTCUT_PANEL_FILTER": "Филтер&хеллип;",
  "KEYBOARD_SHORTCUT_PANEL_RESET": "Ресетовати…",
  "KEYBOARD_SHORTCUT_PANEL_RESET_DEFAULT": "Ресетуј на подразумеване пречице…",
  "KEYBOARD_SHORTCUT_RESET_DIALOG_TITLE": "Ресетујте пречице на тастатури",
  "KEYBOARD_SHORTCUT_RESET_DIALOG_MESSAGE": "Ресетовати све прилагођене пречице на подразумеване? Ово се не може поништити.",
  "STATUSBAR_CURSOR_POSITION": "Линија {0}, колона {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": " — Изабрана {0} колона",
  "STATUSBAR_SELECTION_CH_PLURAL": " — Изабрано {0} колона",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " — Изабрана {0} линија",
  "STATUSBAR_SELECTION_LINE_PLURAL": " — Изабрано {0} линија",
  "STATUSBAR_SELECTION_MULTIPLE": " — {0} селекција",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "Кликни за коришћење размака приликом увлачења кôда",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "Кликни за коришћење таб-ова приликом увлачења кôда",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "Кликни за промену броја размака приликом увлачења кôда",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "Кликни за промену величине таб-а приликом увлачења кôда",
  "STATUSBAR_SPACES": "Размаци:",
  "STATUSBAR_TAB_SIZE": "Величина таб-а:",
  "STATUSBAR_LINE_COUNT_SINGULAR": "— {0} линија",
  "STATUSBAR_LINE_COUNT_PLURAL": "— {0} линија",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "Екстензије деактивиране",
  "STATUSBAR_INSERT": "УБ",
  "STATUSBAR_OVERWRITE": "ПРЕ",
  "STATUSBAR_INSOVR_TOOLTIP": "Кликни да промениш мôд курсора из Убаци (УБ) у Препиши (ПРЕ) и обрнуто",
  "STATUSBAR_LANG_TOOLTIP": "Кликни за измену типа датотеке",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. Кликни за приказ/скривање панела са извештајима.",
  "STATUSBAR_DEFAULT_LANG": "(подразумевано)",
  "STATUSBAR_SET_DEFAULT_LANG": "Подеси као \"подразумевано\" за .{0} датотеке",
  "STATUSBAR_ENCODING_TOOLTIP": "Изаберите кодирање",
  "STATUSBAR_TASKS": "Задаци",
  "STATUSBAR_TASKS_TOOLTIP": "Управљајте активним задацима",
  "STATUSBAR_TASKS_HIDE_SPINNER": "Сакриј икону спинера",
  "STATUSBAR_TASKS_UNKNOWN_EXTENSION_TASK": "Непознати задатак проширења…",
  "STATUSBAR_TASKS_PLAY": "Старт или Ресуме",
  "STATUSBAR_TASKS_PAUSE": "Пауза",
  "STATUSBAR_TASKS_STOP": "Зауставити",
  "STATUSBAR_TASKS_RESTART": "Поново покренути",
  "ERRORS_PANEL_TITLE_MULTIPLE": "{0} грешака",
  "SINGLE_ERROR": "1 {0} грешка",
  "MULTIPLE_ERRORS": "{1} {0} грешака",
  "NO_ERRORS": "Нема {0} грешака - свака част!",
  "NO_ERRORS_MULTIPLE_PROVIDER": "Нема пронађених грешака - свака част!",
  "LINT_DISABLED": "Детектовање сумњивог кôда искључено",
  "NO_LINT_AVAILABLE": "Ниједан детектор сумњивог кôда није доступан за {0}",
  "NOTHING_TO_LINT": "Није пронађен сумњив кôд",
  "LINTER_TIMED_OUT": "Прекинуто је извршавање {0} након чекања од {1} ms",
  "LINTER_FAILED": "Прекинуто је извршавање {0} уз грешку: {1}",
  "FILE_MENU": "Датотека",
  "CMD_FILE_NEW_UNTITLED": "Нова",
  "CMD_FILE_NEW": "Нова датотека",
  "CMD_FILE_DUPLICATE": "Удвостручи",
  "CMD_FILE_DUPLICATE_FILE": "Дуплицате Филе",
  "CMD_FILE_DOWNLOAD_PROJECT": "Преузмите пројекат",
  "CMD_FILE_DOWNLOAD": "Преузимање",
  "CMD_FILE_CUT": "Исеци",
  "CMD_FILE_COPY": "Копирај",
  "CMD_FILE_COPY_PATH": "Копирај путању",
  "CMD_FILE_PASTE": "Налепи",
  "CMD_PROJECT_NEW": "Нови пројекат…",
  "CMD_FILE_NEW_FOLDER": "Нови директоријум",
  "CMD_FILE_OPEN": "Отвори датотеке…",
  "CMD_RECENT_FILES_OPEN": "Недавни фајлови…",
  "CMD_ADD_TO_WORKING_SET": "Додај у радни сет",
  "CMD_OPEN_DROPPED_FILES": "Open Dropped Files",
  "CMD_OPEN_FOLDER": "Отвори директоријум…",
  "CMD_FILE_CLOSE": "Затвори",
  "CMD_FILE_CLOSE_ALL": "Затвори све",
  "CMD_FILE_CLOSE_LIST": "Затвори листу",
  "CMD_FILE_CLOSE_OTHERS": "Затвори остале",
  "CMD_FILE_CLOSE_ABOVE": "Затвори остале изнад",
  "CMD_FILE_CLOSE_BELOW": "Затвори остале испод",
  "CMD_FILE_SAVE": "Сачувај датотеку",
  "CMD_FILE_SAVE_ALL": "Сачувај све",
  "CMD_FILE_SAVE_AS": "Сачувај као…",
  "CMD_LIVE_FILE_PREVIEW": "Живи приказ",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "Омогућите експериментални преглед уживо",
  "CMD_RELOAD_LIVE_PREVIEW": "На силу обнови Живи приказ",
  "CMD_PROJECT_SETTINGS": "Подешавање пројекта…",
  "CMD_FILE_RENAME": "Преименуј",
  "CMD_FILE_DELETE": "Обриши",
  "CMD_INSTALL_EXTENSION": "Инсталирај екстензију…",
  "CMD_EXTENSION_MANAGER": "Менаџер екстензија…",
  "CMD_FILE_REFRESH": "Освежи стабло датотека",
  "CMD_FILE_SHOW_FOLDERS_FIRST": "Прво сортирајте фасцикле",
  "CMD_QUIT": "Прекини",
  "CMD_EXIT": "Излаз",
  "EDIT_MENU": "Уреди",
  "CMD_UNDO": "Опозови",
  "CMD_REDO": "Понови",
  "CMD_CUT": "Исеци",
  "CMD_COPY": "Копирај",
  "CMD_PASTE": "Налепи",
  "CMD_SELECT_ALL": "Изабери све",
  "CMD_SELECT_LINE": "Изабери линију",
  "CMD_SPLIT_SEL_INTO_LINES": "Подели селекцију на линије",
  "CMD_ADD_CUR_TO_NEXT_LINE": "Додај курсор следећој линији",
  "CMD_ADD_CUR_TO_PREV_LINE": "Додај курсор претходној линији",
  "CMD_INDENT": "Помери удесно",
  "CMD_UNINDENT": "Помери улево",
  "CMD_DUPLICATE": "Удвостручи",
  "CMD_DELETE_LINES": "Обриши линију",
  "CMD_COMMENT": "Додај/уклони линијски коментар",
  "CMD_BLOCK_COMMENT": "Додај/уклони блок коментар",
  "CMD_LINE_UP": "Помери линију горе",
  "CMD_LINE_DOWN": "Помери линију доле",
  "CMD_OPEN_LINE_ABOVE": "Отвори линију изнад",
  "CMD_OPEN_LINE_BELOW": "Отвори линију испод",
  "CMD_TOGGLE_CLOSE_BRACKETS": "Аутоматски затвори заграде",
  "CMD_SHOW_CODE_HINTS": "Пружи малу помоћ око кôда",
  "CMD_BEAUTIFY_CODE": "Беаутифи Цоде",
  "CMD_BEAUTIFY_CODE_ON_SAVE": "Улепшавање кода након чувања",
  "FIND_MENU": "Пронађи",
  "CMD_FIND": "Пронађи",
  "CMD_FIND_NEXT": "Пронађи следеће",
  "CMD_FIND_PREVIOUS": "Пронађи претходно",
  "CMD_FIND_ALL_AND_SELECT": "Изаберите Све појаве",
  "CMD_ADD_NEXT_MATCH": "Додај следећу појаву",
  "CMD_SKIP_CURRENT_MATCH": "Прескочи и додај следећу појаву",
  "CMD_FIND_IN_FILES": "Пронађи међу датотекама",
  "CMD_FIND_IN_SUBTREE": "Пронађи у…",
  "CMD_REPLACE": "Замени",
  "CMD_REPLACE_IN_FILES": "Замени у датотекама",
  "CMD_REPLACE_IN_SUBTREE": "Замени у…",
  "VIEW_MENU": "Приказ",
  "CMD_HIDE_SIDEBAR": "Сакриј споредну траку",
  "CMD_SHOW_SIDEBAR": "Прикажи споредну траку",
  "CMD_TOGGLE_SIDEBAR": "Укључите бочну траку",
  "CMD_TOGGLE_PANELS": "Пребаци панеле",
  "CMD_TOGGLE_PURE_CODE": "Без ометања",
  "CMD_TOGGLE_FULLSCREEN": "Цео екран",
  "CMD_ZOOM_UI": "Зум корисничко сучеље и фонтови",
  "CMD_ZOOM_IN": "Увеличати",
  "CMD_ZOOM_IN_SCALE": "Увећај (тренутно: {0}%)",
  "CMD_ZOOM_OUT": "Зоом Оут",
  "CMD_INCREASE_FONT_SIZE": "Повећај величину фонта",
  "CMD_DECREASE_FONT_SIZE": "Смањи величину фонта",
  "CMD_RESTORE_FONT_SIZE": "Поврати величину фонта",
  "CMD_SCROLL_LINE_UP": "Помакни једну линију горе",
  "CMD_SCROLL_LINE_DOWN": "Помакни једну линију доле",
  "CMD_TOGGLE_LINE_NUMBERS": "Бројеви редова",
  "CMD_TOGGLE_ACTIVE_LINE": "Означи активну линију",
  "CMD_TOGGLE_WORD_WRAP": "Прелом текста",
  "CMD_LIVE_HIGHLIGHT": "Обележи живи приказ",
  "CMD_VIEW_TOGGLE_INSPECTION": "Преконтролиши датотеке приликом чувања",
  "CMD_WORKINGSET_SORT_BY_ADDED": "Сортирај по датуму додавања",
  "CMD_WORKINGSET_SORT_BY_NAME": "Сортирај по имену",
  "CMD_WORKINGSET_SORT_BY_TYPE": "Сортирај по типу",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "Аутоматско сортирање",
  "CMD_THEMES": "Теме…",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "Аутоматски затвори претрагу",
  "CMD_KEYBOARD_NAV_OVERLAY": "Режим навигације корисничког интерфејса",
  "NAVIGATE_MENU": "Навигација",
  "CMD_QUICK_OPEN": "Отвори на брзину",
  "CMD_GOTO_LINE": "Иди на линију",
  "CMD_GOTO_DEFINITION": "Брзо пронађи дефиницију",
  "CMD_GOTO_DEFINITION_PROJECT": "Брзо проналажење дефиниције у пројекту",
  "CMD_GOTO_FIRST_PROBLEM": "Иди на први проблем",
  "CMD_TOGGLE_QUICK_EDIT": "Измени на брзину",
  "CMD_TOGGLE_QUICK_DOCS": "Брзи документи",
  "CMD_QUICK_EDIT_PREV_MATCH": "Претходно поклапање",
  "CMD_QUICK_EDIT_NEXT_MATCH": "Следеће поклапање",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "Ново правило",
  "CMD_NEXT_DOC": "Следећи документ",
  "CMD_PREV_DOC": "Претходни документ",
  "CMD_NAVIGATE_BACKWARD": "Навигација уназад",
  "CMD_NAVIGATE_FORWARD": "Навигирај напред",
  "CMD_NEXT_DOC_LIST_ORDER": "Следећи документ на листи",
  "CMD_PREV_DOC_LIST_ORDER": "Претходни документ на листи",
  "CMD_SHOW_IN_TREE": "Прикажи у стаблу датотека",
  "CMD_SHOW_IN_EXPLORER": "Прикажи у Explorer-у",
  "CMD_SHOW_IN_FINDER": "Прикажи у Проналазачу",
  "CMD_SHOW_IN_OS": "Прикажи у ОС датотекама",
  "CMD_SWITCH_PANE_FOCUS": "Пребаците фокус на окно",
  "CMD_OPEN_VFS": "Отворите виртуелни систем датотека",
  "CMD_DIAGNOSTIC_TOOLS": "{АПП_НАМЕ} дијагностичке алатке",
  "CMD_OPEN_EXTENSIONS_FOLDER": "Отвори фасциклу екстензија…",
  "CMD_OPEN_VIRTUAL_SERVER": "Отворите виртуелни сервер",
  "HELP_MENU": "Помоћ",
  "CMD_CHECK_FOR_UPDATE": "Провери да ли постоји новијa верзија",
  "CMD_HOW_TO_USE_BRACKETS": "Корисничко упутство за {APP_NAME}",
  "CMD_SUPPORT": "{APP_NAME} подршка",
  "CMD_SUGGEST": "Предложи нову функционалност",
  "CMD_RELEASE_NOTES": "Белешке о тренутној верзији",
  "CMD_GET_INVOLVED": "Прикључи се развоју апликације",
  "CMD_SHOW_EXTENSIONS_FOLDER": "Прикажи директоријум са екстензијама",
  "CMD_HEALTH_DATA_STATISTICS": "Здравствени извештај…",
  "CMD_HOMEPAGE": "{АПП_НАМЕ} почетна страница",
  "CMD_TWITTER": "{TWITTER_NAME} на Твитеру",
  "CMD_ABOUT": "О апликацији {APP_TITLE}",
  "CMD_OPEN_PREFERENCES": "Отвори датотеку са подешавањима",
  "CMD_OPEN_KEYMAP": "Отворите датотеку мапе корисничких кључева",
  "EXPERIMENTAL_BUILD": "експериментална верзија",
  "RELEASE_BUILD": "билд",
  "DEVELOPMENT_BUILD": "развојна верзија",
  "PRERELEASE_BUILD": "прелеасе буилд",
  "RELOAD_FROM_DISK": "Поново учитај са диска",
  "KEEP_CHANGES_IN_EDITOR": "Сачувај измене у едитору",
  "CLOSE_DONT_SAVE": "Затвори (без чувања измена)",
  "RELAUNCH_CHROME": "Поново покрени Chrome",
  "ABOUT": "О апликацији",
  "CLOSE": "Затвори",
  "ABOUT_TEXT_LINE1": "Издајте {ВЕРСИОН_МАЈОР}.{ВЕРСИОН_МИНОР} {БУИЛД_ТИПЕ} {ВЕРСИОН}",
  "ABOUT_TEXT_BUILD_TIMESTAMP": "временска ознака израде:",
  "ABOUT_TEXT_LINE3": "Библиотеке трећих страна које користимо - <a href='https://github.com/phcode-dev/phoenix/tree/main/src/thirdparty/licences'>Лиценце и атрибуције</a> .",
  "ABOUT_TEXT_LINE4": "Документација и извор на <a href='https://github.com/phcode-dev/phoenix/'>хттпс://гитхуб.цом/пхцоде-дев/пхоеник/</a>",
  "ABOUT_TEXT_LINE5": "Са ❤ и ЈаваСцрипт-ом направио:",
  "ABOUT_TEXT_LINE6": "Много људи (али тренутно имамо проблема са учитавањем тих података).",
  "ABOUT_TEXT_MDN_DOCS": "\"MDN Docs\" и \"MDN\" логотип су заштићени \"Creative Commons Attribution\" лиценцом, <a href='{MDN_DOCS_LICENSE}'>CC-BY-SA 2.5 Unported</a>.",
  "UPDATE_NOTIFICATION_TOOLTIP": "Објављена је нова верзија {APP_NAME}-а! Кликните овде за више информација.",
  "UPDATE_NOT_AVAILABLE_TITLE": "{АПП_НАМЕ} је ажурирана",
  "UPDATE_UP_TO_DATE": "Ваша верзија {АПП_НАМЕ} је најновија и најбоља!",
  "UPDATE_AVAILABLE_TITLE": "Нова верзија доступна",
  "UPDATE_READY_RESTART_TITLE": "Спремно за ажурирање: потребно је поновно покретање",
  "UPDATE_READY_RESTART_MESSAGE": "Затворите све прозоре апликације {АПП_НАМЕ} и поново покрените апликацију да бисте покренули ажурирану верзију.",
  "UPDATE_READY_RESTART_INSTALL_MESSAGE": "Ажурирање је успешно преузето: Затворите све прозоре апликације {АПП_НАМЕ} да бисте применили најновија ажурирања.",
  "UPDATE_FAILED_TITLE": "Ажурирање није успело",
  "UPDATE_INSTALLING": "Инсталирање ажурирања…",
  "UPDATE_INSTALLING_MESSAGE": "Инсталација ажурирања је у току: {АПП_НАМЕ} тренутно инсталира најновија ажурирања. Апликација ће се аутоматски затворити када се инсталација заврши.",
  "UPDATE_FAILED_MESSAGE": "Затворите све прозоре апликације {АПП_НАМЕ} и поново отворите апликацију да бисте поново покушали да ажурирате.",
  "UPDATE_FAILED_VISIT_SITE_MESSAGE": "Да бисте покушали поново, изађите из свих инстанци апликације {АПП_НАМЕ} и поново покрените апликацију.<br> Ускоро ћете бити преусмерени на нашу страницу за преузимање, где можете ручно да преузмете најновију верзију.",
  "UPDATE_MESSAGE": "Хеј, нова верзија {APP_NAME}-а је доступна. Ово су нека од најновијих унапређења:",
  "GET_IT_NOW": "Преузми сада!",
  "UPDATE_LATER": "Касније подсети ме",
  "UPDATE_DONE": "Поново покрените да бисте ажурирали {АПП_НАМЕ}",
  "UPDATE_RESTART": "Поново покрените да бисте применили ажурирања",
  "UPDATE_RESTART_INSTALL": "Поново покрените да бисте инсталирали ажурирања",
  "UPDATE_DOWNLOADING": "Довнлоадинг Инсталлер",
  "UPDATE_DOWNLOAD_PROGRESS": "Преузимање – {0} од {1} МБ",
  "UPDATING_APP": "Ажурирање апликације {АПП_НАМЕ}",
  "UPDATING_APP_MESSAGE": "Ово може потрајати",
  "UPDATING_APP_DIALOG_MESSAGE": "У току је ажурирање. Можете да наставите да користите {АПП_НАМЕ} док вршимо надоградњу.",
  "PROJECT_SETTINGS_TITLE": "Подешавања пројекта за: {0}",
  "PROJECT_SETTING_BASE_URL": "Основна URL адреса за живи приказ",
  "PROJECT_SETTING_BASE_URL_HINT": "Да бисте користили локални сервер, унесите адресу (url) попут http://localhost:8000/",
  "BASEURL_ERROR_INVALID_PROTOCOL": "Живи приказ не подржава протокол {0}&mdash;Молимо Вас користите http: или https: .",
  "BASEURL_ERROR_SEARCH_DISALLOWED": "Основна URL адреса не сме садржати параметре попут \"{0}\".",
  "BASEURL_ERROR_HASH_DISALLOWED": "Основна URL адреса не сме садржати хешеве (hashes) попут \"{0}\".",
  "BASEURL_ERROR_INVALID_CHAR": "Специјални карактери попут '{0}' морају бити %-енкодирани.",
  "BASEURL_ERROR_UNKNOWN_ERROR": "Непозната грешка приликом парсирања основне URL адресе",
  "EMPTY_VIEW_HEADER": "<em>Отвори датотеку док је овај панел у фокусу</em>",
  "FLIPVIEW_BTN_TOOLTIP": "Окрените овај приказ у окно {0}",
  "CURRENT_THEME": "Тренутна тема",
  "USE_THEME_SCROLLBARS": "Користи клизаче из теме",
  "FONT_SIZE": "Величина фонта",
  "FONT_FAMILY": "Породица фонта",
  "THEMES_SETTINGS": "Подешавања теме",
  "THEMES_ERROR": "Теме Грешка",
  "THEMES_ERROR_CANNOT_APPLY": "Није могуће применити тему због грешке.",
  "BUTTON_NEW_RULE": "Ново правило",
  "INSTALL": "Инсталирај",
  "APPLY": "Применити",
  "UPDATE": "Ажурирај",
  "REMOVE": "Уклони",
  "DISABLE": "Онемогући",
  "ENABLE": "Омогући",
  "OVERWRITE": "Пресними",
  "CANT_DROP_ZIP": "Испуштање зип датотека ће ускоро бити подржано...",
  "CANT_REMOVE_DEV": "Екстензије у \"dev\" директоријуму морају бити ручно обрисане.",
  "CANT_UPDATE": "Нова верзија није компатибилна са тренутном верзијом {APP_NAME}-а.",
  "CANT_UPDATE_DEV": "Extensions in the \"dev\" folder can't be updated automatically.",
  "INSTALL_EXTENSION_TITLE": "Инсталирај екстензију",
  "UPDATE_EXTENSION_TITLE": "Ажурирај екстензију",
  "INSTALL_EXTENSION_LABEL": "URL екстензије",
  "INSTALL_EXTENSION_HINT": "Интернет адреса (URL) zip архиве екстензије или GitHub репозиторијума",
  "INSTALLING_FROM": "Инсталирам екстензију са {0}…",
  "INSTALL_SUCCEEDED": "Инсталација успешна!",
  "INSTALL_FAILED": "Инсталација неуспешна.",
  "CANCELING_INSTALL": "Отказујем…",
  "CANCELING_HUNG": "Отказивање инсталације траје предуго. Могуће да је дошло до интерне грешке.",
  "INSTALL_CANCELED": "Инсталација отказана.",
  "VIEW_COMPLETE_DESCRIPTION": "Прикажи комплетан опис",
  "VIEW_TRUNCATED_DESCRIPTION": "Прикажи сажет опис",
  "SORT_EXTENSION_METHOD": "Сортирајте екстензије користећи довнлоадЦоунт или публисхедДате",
  "INVALID_ZIP_FILE": "Преузети садржај није валидна zip архива.",
  "MISSING_PACKAGE_JSON": "Пакет нема датотеку пацкаге.јсон.",
  "INVALID_PACKAGE_JSON": "Датотека \"package.json\" није валидна (грешка: {0}).",
  "MISSING_PACKAGE_NAME": "У датотеци \"package.json\" није наведено име пакета.",
  "BAD_PACKAGE_NAME": "{0} није валидно име за пакет.",
  "MISSING_PACKAGE_VERSION": "У датотеци \"package.json\" није наведена верзија пакета.",
  "INVALID_VERSION_NUMBER": "Верзија пакета број ({0}) није валидна.",
  "INVALID_BRACKETS_VERSION": "{APP_NAME}-ов низ о компатибилности ({0}) није валидан.",
  "DISALLOWED_WORDS": "Речи ({1}) нису дозвољене у пољу {0}.",
  "NPM_INSTALL_FAILED": "нпм инсталл команда није успела: {0}",
  "API_NOT_COMPATIBLE": "Ова екстензија није компатибилна са тренутном верзијом апликације \"{APP_NAME}\". Инсталирана је у Ваш директоријум са неактивним екстензијама.",
  "MISSING_MAIN": "Овај пакет нема \"main.js\" датотеку.",
  "EXTENSION_ALREADY_INSTALLED": "Инсталирањем овог пакета ћете преснимити претходно инсталирану екстензију. Да ли желите да преснимите стару инсталацију?",
  "EXTENSION_SAME_VERSION": "Верзија овог пакета је иста као верзија која је тренутно инсталирана. Да ли желите да преснимите постојећу инсталацију?",
  "EXTENSION_OLDER_VERSION": "Овај пакет је у верзији {0} што је старије од тренутно инсталиране верзије ({1}). Да ли желите да преснимите постојећу инсталацију?",
  "DOWNLOAD_ID_IN_USE": "Интерна грешка: ID преузимања је већ у употреби.",
  "NO_SERVER_RESPONSE": "Повезивање са сервером није могуће.",
  "BAD_HTTP_STATUS": "Датотека није пронађена на серверу (HTTP {0}).",
  "CANNOT_WRITE_TEMP": "Није могуће сачувати преузете податке у привремену датотеку.",
  "ERROR_LOADING": "Дошло је до грешке у екстензији приликом њеног покретања.",
  "MALFORMED_URL": "URL није валидан. Молимо проверите да ли је Ваш унос тачан.",
  "UNSUPPORTED_PROTOCOL": "URL мора бити http или https.",
  "UNKNOWN_ERROR": "Непозната интерна грешка.",
  "EXTENSION_VERIFIED_PUBLISHER": "Овај издавач је верификовао власништво над {0}",
  "EXTENSION_VERIFIED_SORT": "Проверено",
  "EXTENSION_STAR": "Звезда",
  "EXTENSION_STAR_SORT": "Звјездице",
  "EXTENSION_MANAGER_TITLE": "Менаџер екстензија",
  "EXTENSION_MANAGER_ERROR_LOAD": "Приступање регистру екстензије није могуће. Молимо покушајте касније.",
  "EXTENSION_UPDATE_RESTART_TITLE": "Поново покрените за ажурирање",
  "EXTENSION_UPDATE_RESTART_MESSAGE": "Да бисте учитали ажуриране екстензије, затворите све покренуте инстанце апликације {АПП_НАМЕ} и поново покрените апликацију.",
  "INSTALL_EXTENSION_DRAG": "Превуци .zip овде или",
  "INSTALL_EXTENSION_DROP": "Пусти .zip за инсталирање",
  "INSTALL_EXTENSION_DROP_ERROR": "Инсталирање/Ажурирање прекинуто услед следећих грешака:",
  "INSTALL_FROM_URL": "Инсталирај са URL адресе…",
  "INSTALL_EXTENSION_VALIDATING": "Валидирам…",
  "EXTENSION_AUTHOR": "Аутор",
  "EXTENSION_DATE": "Датум",
  "EXTENSION_INCOMPATIBLE_NEWER": "Ова екстензија захтева новиу верзију {APP_NAME}-а.",
  "EXTENSION_INCOMPATIBLE_OLDER": "Ова екстензија тренутно ради само у старијим верзијама {APP_NAME}-а.",
  "EXTENSION_DEFAULT_FEATURE_PRESENT": "Можда вам неће требати ово проширење. {АПП_НАМЕ} већ има ову функцију.",
  "EXTENSION_LATEST_INCOMPATIBLE_NEWER": "Верзија {0} ове екстензије захтева новију верзију апликације {APP_NAME}. Али можете инсталирати ранију верзију {1}.",
  "EXTENSION_LATEST_INCOMPATIBLE_OLDER": "Верзија {0} ове екстензије ради искључиво са старијим верзијама апликације {APP_NAME}. Али можете инсталирати ранију верзију {1}.",
  "EXTENSION_NO_DESCRIPTION": "Не постоји опис",
  "EXTENSION_MORE_INFO": "Више информација...",
  "EXTENSION_ERROR": "Грешка у екстензији",
  "EXTENSION_KEYWORDS": "Кључне речи",
  "EXTENSION_TRANSLATED_USER_LANG": "Преведено на {0} језика, укључујући Ваш",
  "EXTENSION_TRANSLATED_GENERAL": "Преведено на {0} језика",
  "EXTENSION_TRANSLATED_LANGS": "Ова екстензија је преведена на ове језике: {0}",
  "EXTENSION_INSTALLED": "Инсталирано",
  "EXTENSION_UPDATE_INSTALLED": "Ова верзија екстензије је већ преузета и биће инсталирана приликом поновног покретања {APP_NAME}-а.",
  "EXTENSION_SEARCH_PLACEHOLDER": "Пронађи",
  "EXTENSION_MORE_INFO_LINK": "Још",
  "EXTENSION_MANAGER_CREATE_EXTENSION": "+ Креирајте проширење",
  "EXTENSION_MANAGER_CREATE_THEME": "+ Креирајте тему",
  "BROWSE_EXTENSIONS": "Претражи екстензије",
  "EXTENSION_MANAGER_REMOVE": "Уклони екстензију",
  "EXTENSION_MANAGER_REMOVE_ERROR": "Није могуће уклонити једну или више екстензија: {0}. {APP_NAME} ће се ипак поново покренути.",
  "EXTENSION_MANAGER_UPDATE": "Ажурирај екстензију",
  "EXTENSION_MANAGER_UPDATE_ERROR": "Није могуће ажурирати једну или више екстензија: {0}. {APP_NAME} ће се ипак поново покренути.",
  "EXTENSION_MANAGER_DISABLE": "Онемогући проширење",
  "EXTENSION_MANAGER_DISABLE_ERROR": "Није могуће онемогућити један или више екстензија: {0}. {АПП_НАМЕ} ће се и даље поново учитавати.",
  "EXTENSION_MANAGER_THEMES_INFO": "Да бисте <a class=\"theme_settings\">изабрали подразумеване теме</a> или изменили друга подешавања теме, <a class=\"theme_settings\">кликните овде</a> .",
  "EXTENSION_MANAGER_THEMES_UNDO": "Вратите се на претходну тему",
  "MARKED_FOR_REMOVAL": "Означено за уклањање",
  "UNDO_REMOVE": "Опозови",
  "MARKED_FOR_UPDATE": "Означено за ажурирање",
  "UNDO_UPDATE": "Опозови",
  "MARKED_FOR_DISABLING": "Означено за онемогућавање",
  "UNDO_DISABLE": "Опозови",
  "CHANGE_AND_RELOAD_TITLE": "Промени екстензије",
  "CHANGE_AND_RELOAD_MESSAGE": "Да би се означене екстензије ажурирале или уклониле \"{APP_NAME}\" ће морати поново да се покрене. Од Вас ће бити затражено да сачувате измене.",
  "REMOVE_AND_RELOAD": "Уклони екстензије и изађи",
  "CHANGE_AND_RELOAD": "Промени екстензије и изађи",
  "UPDATE_AND_RELOAD": "Ажурирај екстензије и изађи",
  "DISABLE_AND_RELOAD": "Онемогућите проширења и поново учитајте",
  "PROCESSING_EXTENSIONS": "Процесуирам измене у екстензијама…",
  "EXTENSION_NOT_INSTALLED": "Екстензија {0} није могла бити уклоњена јер није била инсталирана.",
  "NO_EXTENSIONS": "Тренутно нема инсталираних екстензија.<br>Кликните изнад на картицу Доступно да додате екстензију.",
  "NO_EXTENSION_MATCHES": "Ниједна екстензија се не поклапа са унетим параметрима претраге.",
  "REGISTRY_SANITY_CHECK_WARNING": "ОПРЕЗ: Ове екстензије можда потичу од непознатих извора. Екстензије нису проверене и поседују пуне локалне привилегије. Будите обазриви приликом инсталације екстензија које потичу од непознатих извора.",
  "EXTENSIONS_INSTALLED_TITLE": "Инсталирано",
  "EXTENSIONS_DEFAULT_TITLE": "Уобичајено",
  "EXTENSIONS_AVAILABLE_TITLE": "Доступно",
  "EXTENSIONS_THEMES_TITLE": "Теме",
  "EXTENSIONS_UPDATES_TITLE": "Ажурирања",
  "EXTENSIONS_LAST_UPDATED": "Последње измене",
  "EXTENSIONS_DOWNLOADS": "Преузимања",
  "INLINE_EDITOR_NO_MATCHES": "Нема поклапања.",
  "INLINE_EDITOR_HIDDEN_MATCHES": "Сва поклапања су скривена. Раширите датотеке излистане на десној страни како бисте видели поклапања.",
  "CSS_QUICK_EDIT_NO_MATCHES": "Не постоје CSS правила која се поклапају са Вашом селекцијом.<br> Кликните \"Ново правило\" како бисте креирали ново.",
  "CSS_QUICK_EDIT_NO_STYLESHEETS": "Не постоје стилови у вашем пројекту.<br>Креирајте један или додајте CSS правила.",
  "IMAGE_VIEWER_LARGEST_ICON": "највећа",
  "UNIT_PIXELS": "пиксели",
  "DEBUG_MENU": "Отклањање грешака",
  "ERRORS": "Грешке",
  "CMD_SHOW_DEV_TOOLS": "Алатке за програмере {АПП_НАМЕ}",
  "CMD_REFRESH_WINDOW": "Поново учитај са екстензијама",
  "CMD_LOAD_CURRENT_EXTENSION": "Учитај пројекат као проширење",
  "CMD_RELOAD_CURRENT_EXTENSION": "Поново учитај пројекат као проширење",
  "CMD_UNLOAD_CURRENT_EXTENSION": "Скини пројекат као проширење",
  "CMD_RELOAD_WITHOUT_USER_EXTS": "Поново учитај без екстензија",
  "CMD_NEW_BRACKETS_WINDOW": "Нови прозор",
  "CMD_LAUNCH_SCRIPT_MAC": "Инсталирајте пречицу командне линије",
  "CMD_SWITCH_LANGUAGE": "Промени језик…",
  "CMD_RUN_UNIT_TESTS": "Покрените {АПП_НАМЕ} тестове",
  "CMD_SHOW_PERF_DATA": "Прикажи податке о перформансама",
  "CMD_ENABLE_LOGGING": "Омогући детаљне евиденције",
  "CMD_ENABLE_PHNODE_INSPECTOR": "Омогућите ПхНоде Инспецтор",
  "CMD_GET_PHNODE_INSPECTOR_URL": "Како прегледати ПхНоде",
  "CMD_ENABLE_LIVE_PREVIEW_LOGS": "Дневници прегледа уживо",
  "CMD_OPEN_BRACKETS_SOURCE": "Отвори изворни кôд Brackets-а",
  "CREATING_LAUNCH_SCRIPT_TITLE": "{АПП_НАМЕ} пречица командне линије",
  "ERROR_CREATING_LAUNCH_SCRIPT": "Дошло је до грешке приликом инсталирања пречице командне линије. Испробајте <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting'>ове предлоге за решавање проблема</a> .<br/><br/> Разлог: {0}",
  "ERROR_CLTOOLS_RMFAILED": "Није могуће уклонити постојећу <code>/usr/local/bin/brackets</code> симболичку везу.",
  "ERROR_CLTOOLS_MKDIRFAILED": "Није могуће креирати <code>/usr/local/bin</code> директоријум.",
  "ERROR_CLTOOLS_LNFAILED": "Није могуће креирати <code>/usr/local/bin/brackets</code> симболичку везу.",
  "ERROR_CLTOOLS_SERVFAILED": "Унутрашња грешка.",
  "ERROR_CLTOOLS_NOTSUPPORTED": "Пречица командне линије није подржана на овом ОС.",
  "LAUNCH_SCRIPT_CREATE_SUCCESS": "Успех! Сада можете лако да покренете {АПП_НАМЕ} из командне линије: у <code>brackets myFile.txt</code> да отворите датотеку или у <code>brackets myFolder</code> да промените пројекте.<br/><br/> <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments'>Сазнајте више</a> о коришћењу апликације {АПП_НАМЕ} из командне линије.",
  "ERROR_LOADING_EXTENSION": "Грешка при учитавању екстензије",
  "ERROR_NO_EXTENSION_PACKAGE": "<code>package.json</code> датотека није откривена у тренутном пројекту. Да ли је тренутни пројекат важећи додатак за {АПП_НАМЕ}?</br> Погледајте <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>овај линк</a> за више детаља.",
  "ERROR_INVALID_EXTENSION_PACKAGE": "<code>package.json</code> датотека је неважећи ЈСОН.</br> Погледајте <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>овај линк</a> за више детаља.",
  "ERROR_INVALID_EXTENSION_PACKAGE_FIELDS": "Недостају обавезна поља у <code>package.json</code> : [{0}]</br> Погледајте <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>овај линк</a> за више детаља.",
  "ERROR_NODE_JS_CRASH_TITLE": "Упс! Нешто није у реду.",
  "ERROR_NODE_JS_CRASH_MESSAGE": "Наишли смо на проблем и морамо поново да покренемо {АПП_НАМЕ}. Не брините, покушавамо да сачувамо сав ваш рад пре поновног покретања. </бр>(Грешка: ЕРРОР_НОДЕ_ЈС_ЦРАСХ)",
  "LANGUAGE_TITLE": "Промени језик",
  "LANGUAGE_MESSAGE": "Језик:",
  "LANGUAGE_SUBMIT": "Поново учитај {APP_NAME}",
  "LANGUAGE_CANCEL": "Откажи",
  "LANGUAGE_SYSTEM_DEFAULT": "језик система",
  "HEALTH_DATA_NOTIFICATION": "Подешавања здравственог извештаја",
  "HEALTH_FIRST_POPUP_TITLE": "Извештај о здравственом стању апликације {АПП_НАМЕ}",
  "HEALTH_DATA_DO_TRACK": "Делите псеудонимне информације о томе како користим {АПП_НАМЕ}",
  "HEALTH_DATA_NOTIFICATION_MESSAGE": "Да бисмо побољшали {АПП_НАМЕ}, периодично шаљемо ограничену, <strong>псеудонимну</strong> статистику и извештаје о грешкама на пхцоде.дев о томе како користите {АПП_НАМЕ}. Ове информације помажу у одређивању приоритета функција, проналажењу грешака и уочавању проблема са употребљивошћу, истовремено чувајући вашу приватност.<br><br> Можете да видите своје податке или да изаберете да их не делите тако што ћете изабрати <strong>Помоћ &gt; Извештај о здрављу</strong> .<br><br>",
  "HEALTH_DATA_PREVIEW": "Извештај о здравственом стању апликације {АПП_НАМЕ}",
  "HEALTH_DATA_PREVIEW_INTRO": "<p>Да бисмо побољшали {АПП_НАМЕ}, периодично шаљемо ограничену, <strong>псеудонимну</strong> статистику и извештаје о грешкама на пхцоде.дев о томе како користите {АПП_НАМЕ}. Ове информације помажу у одређивању приоритета функција, проналажењу грешака и уочавању проблема употребљивости.</p><p> Испод је преглед података који ће бити послати у вашем следећем здравственом извештају <em>ако</em> је омогућен. (Погледајте и конзолу за програмере за евиденцију грешака са ознаком „Ухваћена критична грешка“.)</p>",
  "INLINE_TIMING_EDITOR_TIME": "Време",
  "INLINE_TIMING_EDITOR_PROGRESSION": "Напредак",
  "BEZIER_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd><kbd>←</kbd><kbd>→</kbd> Помери изабрану тачку<br><kbd class='text'>Shift</kbd> Помери за десет јединица<br><kbd class='text'>Tab</kbd> Замени тачке",
  "STEPS_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd> Повећај или смањи кораке<br><kbd>←</kbd><kbd>→</kbd> 'Почни' или 'Заврши'",
  "INLINE_TIMING_EDITOR_INVALID": "Стара вредност <code>{0}</code> није валидна, па је приказана функција промењена у <code>{1}</code>. Овај документ ће се ажурирати приликом прве измене.",
  "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP": "Тренутна боја",
  "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP": "Оригинална боја",
  "COLOR_EDITOR_RGBA_BUTTON_TIP": "RGBa формат",
  "COLOR_EDITOR_HEX_BUTTON_TIP": "Hex формат",
  "COLOR_EDITOR_HSLA_BUTTON_TIP": "HSLa формат",
  "COLOR_EDITOR_0X_BUTTON_TIP": "Хек (0к) формат",
  "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR": "{0} (Коришћена {1} пут)",
  "COLOR_EDITOR_USED_COLOR_TIP_PLURAL": "{0} (Коришћена {1} пута)",
  "CMD_JUMPTO_DEFINITION": "Скочи на дефиницију",
  "CMD_SHOW_PARAMETER_HINT": "Пружи малу помоћ око параметра",
  "NO_ARGUMENTS": "<без параметара>",
  "DETECTED_EXCLUSION_TITLE": "Проблем у обради JavaScript датотеке",
  "DETECTED_EXCLUSION_INFO": "{АПП_НАМЕ} је наишла на проблеме са обрадом <span class='dialog-filename'>{0}</span> .<br><br> Ова датотека се више неће обрађивати за наговештаје кода, прелазак на дефиницију или брзо уређивање. Да бисте поново омогућили ову датотеку, отворите <code>.phcode.json</code> у свом пројекту и уредите <code>jscodehints.detectedExclusions</code> .<br><br> Ово је вероватно грешка у апликацији {АПП_НАМЕ}. Ако можете да дате копију ове датотеке, <a href='https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue'>пријавите грешку</a> са везом до датотеке која је овде названа.",
  "CMD_REFACTOR": "Рефактор",
  "CMD_EXTRACTTO_VARIABLE": "Издвој у променљиву",
  "CMD_EXTRACTTO_FUNCTION": "Екстракт у функцију",
  "ERROR_TERN_FAILED": "Није могуће добити податке од Терн-а",
  "ERROR_EXTRACTTO_VARIABLE_NOT_VALID": "Селекција не формира израз",
  "ERROR_EXTRACTTO_FUNCTION_NOT_VALID": "Изабрани блок треба да представља скуп исказа или израза",
  "ERROR_EXTRACTTO_VARIABLE_MULTICURSORS": "Екстракт у променљиву не ради у мултикурзорима",
  "ERROR_EXTRACTTO_FUNCTION_MULTICURSORS": "Екстракт у функцију не ради у мултикурзорима",
  "EXTRACTTO_FUNCTION_SELECT_SCOPE": "Изаберите одредишни опсег",
  "EXTRACTTO_VARIABLE_SELECT_EXPRESSION": "Изаберите израз",
  "CMD_REFACTORING_RENAME": "Преименуј",
  "CMD_REFACTORING_TRY_CATCH": "Замотајте у Три Цатцх",
  "CMD_REFACTORING_CONDITION": "Умотајте у стање",
  "CMD_REFACTORING_GETTERS_SETTERS": "Креирајте Геттерс/Сеттерс",
  "CMD_REFACTORING_ARROW_FUNCTION": "Претвори у функцију стрелице",
  "DESCRIPTION_CODE_REFACTORING": "Омогућите/онемогућите рефакторисање ЈаваСцрипт кода",
  "ERROR_TRY_CATCH": "Изаберите важећи код који ћете умотати у блок Три-цатцх",
  "ERROR_WRAP_IN_CONDITION": "Изаберите важећи код за умотавање у блок услова",
  "ERROR_ARROW_FUNCTION": "Поставите курсор унутар израза функције",
  "ERROR_GETTERS_SETTERS": "Поставите курсор на члан израза објекта",
  "ERROR_RENAME_MULTICURSOR": "Не може се преименовати када се користи више курсора",
  "ERROR_RENAME_QUICKEDIT": "Не може се преименовати овај идентификатор, јер се на њега упућује на другом месту ван ове функције",
  "ERROR_RENAME_GENERAL": "Није могуће преименовати изабрани текст",
  "JSHINT_NAME": "ЈСХинт",
  "CMD_ENABLE_QUICK_VIEW": "Брзи приказ приликом задржавања миша",
  "CMD_ENABLE_SELECTION_VIEW": "Селецтион Виев",
  "TOOLTIP_CLICK_TO_EDIT_COLOR": "Кликните овде да бисте уредили боју",
  "CMD_TOGGLE_RECENT_PROJECTS": "Недавни пројекти",
  "REMOVE_FROM_RECENT_PROJECTS": "Уклони из недавних пројеката",
  "DOCS_MORE_LINK": "Прочитај више",
  "COLLAPSE_ALL": "Скупи све",
  "EXPAND_ALL": "Прошири све",
  "COLLAPSE_CURRENT": "Цоллапс Цуррент",
  "EXPAND_CURRENT": "Прошири Цуррент",
  "RECENT_FILES_DLG_HEADER": "Недавне датотеке",
  "RECENT_FILES_DLG_CLEAR_BUTTON_LABEL": "Јасно",
  "RECENT_FILES_DLG_CLEAR_BUTTON_TITLE": "Обришите датотеке које нису у радном скупу",
  "RECOVER_UNSAVED_FILES_TITLE": "Опоравити несачуване датотеке?",
  "RECOVER_UNSAVED_FILES_MESSAGE": "Желите ли да вратите несачуване датотеке из претходне сесије?",
  "RECOVER_UNSAVED_FILES_RESTORE": "Ресторе",
  "DISCARD_UNSAVED_FILES_RESTORE": "Одбаци",
  "DESCRIPTION_CLOSE_BRACKETS": "труе за аутоматско затварање заграда, заграда и заграда",
  "DESCRIPTION_CLOSE_OTHERS_ABOVE": "фалсе да бисте уклонили „Затвори друге изнад“ из контекстног менија Радне датотеке",
  "DESCRIPTION_CLOSE_OTHERS_BELOW": "фалсе да бисте уклонили „Затвори друге испод“ из контекстног менија Радне датотеке",
  "DESCRIPTION_CLOSE_OTHERS": "фалсе да бисте уклонили „Затвори друге“ из контекстног менија Радне датотеке",
  "DESCRIPTION_CLOSE_TAGS": "Поставља опције затварања ознаке",
  "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS": "Низ ознака које не би требало аутоматски да се затварају",
  "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING": "Затвори када се откуца > од почетне ознаке",
  "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING": "Затвори када се откуца ознака / од завршне ознаке",
  "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS": "Низ ознака које када се отворе имају празан ред",
  "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD": "труе да увек генерише склопиве маркере секција када се промени ниво увлаке",
  "DESCRIPTION_CODE_FOLDING_ENABLED": "труе да би се омогућило савијање кода",
  "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER": "труе да би маркери за сажимање секција били видљиви само када померите миш преко олука",
  "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL": "Ограничава колико нивоа се примењује дубоко Цоллапс Алл",
  "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE": "Минимум редова пре него што се појави икона склопивог одељка",
  "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES": "тачно да запамтите скупљене одељке ако затворите и поново отворите датотеку или пројекат",
  "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE": "труе да омогући савијање кода на изабраном тексту у уређивачу",
  "DESCRIPTION_DISABLED_DEFAULT_EXTENSIONS": "Подразумеване екстензије које су онемогућене",
  "DESCRIPTION_ATTR_HINTS": "Омогућите/онемогућите савете за ХТМЛ атрибуте",
  "DESCRIPTION_CSS_PROP_HINTS": "Омогућите/онемогућите ЦСС/ЛЕСС/СЦСС савете за својства",
  "DESCRIPTION_JS_HINTS": "Омогућите/онемогућите наговештаје ЈаваСцрипт кода",
  "DESCRIPTION_JS_HINTS_TYPE_DETAILS": "Омогућите/онемогућите детаље типа података у наговештајима ЈаваСцрипт кода",
  "DESCRIPTION_PREF_HINTS": "Омогућите/онемогућите наговештаје кода за подешавања",
  "DESCRIPTION_SPECIAL_CHAR_HINTS": "Омогућите/онемогућите ХТМЛ наговештаје ентитета",
  "DESCRIPTION_SVG_HINTS": "Омогућите/онемогућите савете за СВГ код",
  "DESCRIPTION_HTML_TAG_HINTS": "Омогућите/онемогућите савете за ХТМЛ ознаке",
  "DESCRIPTION_URL_CODE_HINTS": "Омогућите/онемогућите УРЛ наговештаје у ХТМЛ & ЦСС/ЛЕСС/СЦСС",
  "DESCRIPTION_DRAG_DROP_TEXT": "Омогућите/онемогућите функцију Драг & Дроп",
  "DESCRIPTION_HEALTH_DATA_TRACKING": "Омогућите праћење здравствених података",
  "DESCRIPTION_HIGHLIGHT_MATCHES": "Омогућава аутоматско истицање одговарајућих низова у целом документу",
  "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN": "Означите све низове који одговарају токену у којем се курсор тренутно налази (није потребан избор)",
  "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY": "Означите само када је избор комплетан токен",
  "DESCRIPTION_INSERT_HINT_ON_TAB": "тачно да бисте уметнули тренутно изабрани наговештај кода на картици",
  "DESCRIPTION_NO_HINTS_ON_DOT": "тачно да се аутоматски не приказују наговештаји ЈС кода када . је откуцано",
  "DESCRIPTION_JSHINT_OPTIONS": "Објекат са подразумеваним опцијама за ЈСХинт. Погледајте следећу УРЛ адресу за све доступне ЈСХинт опције: хттпс://јсхинт.цом/доцс/оптионс/",
  "DESCRIPTION_LANGUAGE": "Подешавања специфична за језик",
  "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS": "Додатна мапирања од екстензије датотеке до назива језика",
  "DESCRIPTION_LANGUAGE_FILE_NAMES": "Додатна пресликавања од имена датотеке до назива језика",
  "DESCRIPTION_LINEWISE_COPY_CUT": "Копирање и сечење када нема избора ће копирати или исећи целе линије које имају курсоре у себи",
  "DESCRIPTION_INPUT_STYLE": "Бира начин на који ЦодеМиррор рукује уносом и фокусом. То може бити тектареа, која је подразумевана, или садржај који се може уређивати што је боље за читаче екрана (нестабилно)",
  "DESCRIPTION_LINTING_ENABLED": "труе да бисте омогућили инспекцију кода",
  "DESCRIPTION_ASYNC_TIMEOUT": "Време у милисекундама након којег асинхрони линтерс истекне",
  "DESCRIPTION_LINTING_PREFER": "Низ линтера за покретање први",
  "DESCRIPTION_LIVE_DEV_MULTIBROWSER": "труе да бисте омогућили експериментални преглед уживо",
  "DESCRIPTION_USE_PREFERED_ONLY": "истина само за покретање добављача наведених у линтинг.префер",
  "DESCRIPTION_MAX_CODE_HINTS": "Максималан број наговештаја кода који се приказује одједном",
  "DESCRIPTION_PATH": "Специфична подешавања путање",
  "DESCRIPTION_PROXY": "УРЛ прокси сервера који се користи за инсталацију екстензије",
  "DESCRIPTION_SCROLL_PAST_END": "труе да бисте омогућили померање даље од краја документа",
  "DESCRIPTION_SHOW_CODE_HINTS": "фалсе да бисте онемогућили све наговештаје кода",
  "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING": "Одржава трепћући курсор видљивим када имате избор текста",
  "DESCRIPTION_SHOW_LINE_NUMBERS": "труе да прикаже бројеве редова у „олуку“ лево од кода",
  "DESCRIPTION_SMART_INDENT": "Аутоматско увлачење приликом креирања новог блока",
  "DESCRIPTION_SOFT_TABS": "фалсе да бисте искључили понашање меких картица",
  "DESCRIPTION_SORT_DIRECTORIES_FIRST": "труе да прво сортирате директоријуме у стаблу пројекта",
  "DESCRIPTION_SPACE_UNITS": "Број размака који се користе за увлачење засновано на простору",
  "DESCRIPTION_STATIC_SERVER_PORT": "Број порта који би уграђени сервер требало да користи за Ливе Превиев",
  "DESCRIPTION_STYLE_ACTIVE_LINE": "труе да би се истакла боја позадине линије на којој је курсор",
  "DESCRIPTION_TAB_SIZE": "Број размака за приказ за картице",
  "DESCRIPTION_USE_TAB_CHAR": "тачно да користите табулаторе уместо размака",
  "DESCRIPTION_UPPERCASE_COLORS": "труе да генерише хексадецималне боје у великим словима у Инлине Цолор Едитору",
  "DESCRIPTION_WORD_WRAP": "Премотајте линије које прелазе ширину прозора за приказ",
  "DESCRIPTION_SEARCH_AUTOHIDE": "Затворите претрагу чим се уредник фокусира",
  "DESCRIPTION_DETECTED_EXCLUSIONS": "Листа датотека за које је откривено да Терн измакне контроли",
  "DESCRIPTION_INFERENCE_TIMEOUT": "Време након којег ће Терн истећи када покуша да разуме датотеке",
  "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR": "труе да прикаже грешке у статусној траци",
  "DESCRIPTION_QUICK_VIEW_ENABLED": "труе да бисте омогућили брзи преглед",
  "DESCRIPTION_SELECTION_VIEW_ENABLED": "труе да бисте омогућили приказ избора",
  "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW": "труе да би се приказали прегледи слика за УРЛ адресе којима недостају екстензије",
  "DESCRIPTION_NUMBER_QUICK_VIEW": "труе да бисте приказали брзи приказ када пређете курсором преко бројева у уређивачу",
  "DESCRIPTION_THEME": "Изаберите тему за {АПП_НАМЕ}",
  "DESCRIPTION_USE_THEME_SCROLLBARS": "труе да дозволи прилагођене траке за померање",
  "DESCRIPTION_LINTING_COLLAPSED": "истинито до колапса лајсни панел",
  "DESCRIPTION_FONT_FAMILY": "Промените породицу фонтова",
  "DESCRIPTION_DESKTOP_ZOOM_SCALE": "Изаберите фактор зумирања у распону од 0,1 (за компактнији приказ) до 2 (за већи, увећани приказ). Доступно само у апликацијама за рачунаре",
  "DESCRIPTION_FONT_SIZE": "Промените величину фонта; на пример. 13пк",
  "DESCRIPTION_FIND_IN_FILES_NODE": "труе да омогући претрагу засновану на чвору",
  "DESCRIPTION_FIND_IN_FILES_INSTANT": "труе да бисте омогућили тренутну претрагу",
  "DESCRIPTION_FONT_SMOOTHING": "Само за Мац: „субпикел-антиалиасед“ да би се омогућило антиалиасинг подпиксела или „антиалиасед“ за антиалиасинг у сивој скали",
  "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW": "фалсе да бисте онемогућили отварање датотеке са подешавањима у подељеном приказу",
  "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE": "фалсе да бисте отворили датотеку корисничких подешавања у левом/горњем окну",
  "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED": "труе за сажимање окна након што је последња датотека из окна затворена преко дугмета за затварање заглавља окна",
  "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS": "Укључите када желите да прикажете дугмад за затварање и преокренути приказ у заглављу.",
  "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT": "/*\n * Ово је датотека само за читање са подржаним подешавањима\n * од {АПП_НАМЕ}.\n * Користите ову датотеку као референцу да бисте изменили своја подешавања\n * датотека \"пхцоде.јсон\" отворена у другом окну.\n * За више информација о томе како да користите преференце унутар\n * {АПП_НАМЕ}, погледајте веб страницу на хттпс://гитхуб.цом/адобе/брацкетс/вики/Хов-то-Усе-Брацкетс#преференцес\n */",
  "DEFAULT_PREFERENCES_JSON_DEFAULT": "Уобичајено",
  "DESCRIPTION_PURE_CODING_SURFACE": "тачно да бисте омогућили режим само код и сакрили све остале елементе корисничког интерфејса у {АПП_НАМЕ}",
  "DESCRIPTION_INDENT_LINE_COMMENT": "труе да би се омогућило увлачење коментара реда",
  "DESCRIPTION_RECENT_FILES_NAV": "Омогућите/онемогућите навигацију у недавним датотекама",
  "DESCRIPTION_LIVEDEV_WEBSOCKET_PORT": "Порт на коме ради ВебСоцкет Сервер за Ливе Превиев",
  "DESCRIPTION_LIVE_DEV_HIGHLIGHT_SETTINGS": "Ливе Превиев Хигхлигхт подешавања",
  "DESCRIPTION_LIVEDEV_ENABLE_REVERSE_INSPECT": "нетачно да бисте онемогућили обрнути преглед прегледа уживо",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW": "Нема шта за преглед!",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW_DETAILS": "Изаберите ХТМЛ датотеку за преглед",
  "DESCRIPTION_LIVEDEV_PREVIEW_RESTRICTED": "Преглед недоступан!",
  "DESCRIPTION_LIVEDEV_PREVIEW_RESTRICTED_DETAILS": "Ова ХТМЛ датотека није део тренутног пројекта. Из безбедносних разлога, само датотеке пројекта могу да се прегледају уживо. Да бисте прегледали ову датотеку, отворите њену фасциклу као посебан пројекат.",
  "DESCRIPTION_LIVEDEV_MAIN_HEADING": "Ух Ох!<br> Ваш тренутни прегледач не подржава преглед уживо.",
  "DESCRIPTION_LIVEDEV_MAIN_SPAN": "Добијте најбоље искуство прегледа уживо преузимањем наших изворних апликација за Виндовс, Мац и Линук са <a href=\"https://phcode.io\" style=\"color: white\">пхцоде.ио</a> .<br>",
  "DESCRIPTION_LIVEDEV_SECURITY_POPOUT_MESSAGE": "Управо ћете отворити датотеку за преглед уживо. Наставите само ако верујете извору овог пројекта. Кликните на „Поверите пројекту“ да бисте наставили или затворите овај прозор ако немате поверења у извор.",
  "DESCRIPTION_LIVEDEV_SECURITY_TRUST_MESSAGE": "Управо ћете отворити датотеку за преглед уживо. Наставите тако што ћете кликнути на „Поверите пројекту“ само ако верујете извору овог пројекта!",
  "CONFIRM_EXTERNAL_BROWSER_TITLE": "Искачући прозори су блокирани",
  "CONFIRM_EXTERNAL_BROWSER_MESSAGE": "Да ли желите да дозволите да страница за преглед уживо отвори ову УРЛ адресу: {0}?",
  "TRUST_PROJECT": "Верујте и извршите преглед – {0}",
  "TRUST_AUTHORS": "Да ли верујете ауторима овог пројекта?",
  "DOWNLOAD_FAILED": "Преузимање није успело.",
  "DOWNLOAD_COMPLETE": "Скидање завршено!",
  "UPDATE_SUCCESSFUL": "Ажурирање је успешно!",
  "UPDATE_FAILED": "Ажурирање није успело!",
  "VALIDATION_FAILED": "Валидација није успела!",
  "INITIALISATION_FAILED": "Иницијализација није успела!",
  "CLEANUP_FAILED": "Чишћење није успело!",
  "WARNING_TYPE": "Упозорење!",
  "CLICK_RESTART_TO_UPDATE": "Кликните на Поново покрени да бисте ажурирали заграде.",
  "UPDATE_ON_NEXT_LAUNCH": "Ажурирање ће се применити при поновном покретању.",
  "GO_TO_SITE": "Идите на <a href = \"http://brackets.io/\">брацкетс.ио</a> да бисте покушали поново.",
  "INTERNET_UNAVAILABLE": "Интернет веза није доступна.",
  "UPDATEDIR_READ_FAILED": "Није могуће прочитати директоријум ажурирања.",
  "UPDATEDIR_CLEAN_FAILED": "Није могуће очистити директоријум ажурирања.",
  "INITIAL_DOWNLOAD": "Преузимање ажурирања...",
  "RETRY_DOWNLOAD": "Преузимање није успело. Поновни покушај...Покушај",
  "VALIDATING_INSTALLER": "Скидање завршено! Потврда инсталатера...",
  "CHECKSUM_DID_NOT_MATCH": "Контролни збир се није подударао.",
  "INSTALLER_NOT_FOUND": "Инсталатер није пронађен.",
  "DOWNLOAD_ERROR": "Дошло је до грешке при преузимању.",
  "NETWORK_SLOW_OR_DISCONNECTED": "Мрежа је прекинута или преспора.",
  "RESTART_BUTTON": "Поново покренути",
  "LATER_BUTTON": "Касније",
  "DESCRIPTION_AUTO_UPDATE": "Омогућите/онемогућите аутоматско ажурирање заграда",
  "AUTOUPDATE_ERROR": "Грешка!",
  "AUTOUPDATE_IN_PROGRESS": "Ажурирање је већ у току.",
  "NUMBER_WITH_PERCENTAGE": "{0}%",
  "CMD_FIND_RELATED_FILES": "Пронађите повезане датотеке",
  "PHP_VERSION_INVALID": "Грешка при рашчлањивању ПХП верзије. Проверите излаз команде „пхп –версион“.",
  "PHP_UNSUPPORTED_VERSION": "Инсталирајте ПХП7 рунтиме да бисте омогућили алатке повезане са ПХП-ом, као што су савети кода, савети за параметре, скок на дефиницију и још много тога. Пронађена верзија: {0}",
  "PHP_EXECUTABLE_NOT_FOUND": "ПХП време извођења није пронађено. Инсталирајте ПХП7 рунтиме и ажурирајте „екецутаблеПатх“ у ПХП Преференцес на одговарајући начин. Ово омогућава алатке повезане са ПХП-ом, као што су савети кода, савети за параметре, прелазак на дефиницију и још много тога.",
  "PHP_PROCESS_SPAWN_ERROR": "Дошло је до кода грешке {0} приликом покретања ПХП процеса.",
  "PHP_SERVER_ERROR_TITLE": "Грешка",
  "PHP_SERVER_MEMORY_LIMIT_INVALID": "Ограничење меморије које сте навели је неважеће. Прегледајте ПХП подешавања да бисте поставили тачну вредност.",
  "DESCRIPTION_PHP_TOOLING_CONFIGURATION": "Подразумевана подешавања конфигурације ПХП алата",
  "OPEN_PREFERENNCES": "Отворите Преференцес",
  "LANGUAGE_TOOLS_PREFERENCES": "Преференцес фор Лангуаге Тоолс",
  "FIND_ALL_REFERENCES": "Пронађите све референце",
  "REFERENCES_IN_FILES": "референце",
  "REFERENCE_IN_FILES": "референца",
  "REFERENCES_NO_RESULTS": "Нема доступних референци за тренутну позицију курсора",
  "CMD_FIND_DOCUMENT_SYMBOLS": "Пронађите симболе докумената",
  "CMD_FIND_PROJECT_SYMBOLS": "Пронађите симболе пројекта",
  "REMOTE_DEBUGGING_ENABLED": "Даљинско отклањање грешака је омогућено на локалном хосту:",
  "REMOTE_DEBUGGING_PORT_INVALID": "Није могуће омогућити даљинско отклањање грешака на порту {0}. Бројеви портова треба да буду између {1} и {2}.",
  "DESCRIPTION_EXTERNAL_APPLICATION_ASSOCIATE": "Пресликавања екстензија датотеке на спољне апликације. Синтакса: \"<тип_датотеке>\": \"<подразумевано|име апликације|Путања апликације>\", Користите \"подразумевано\" да отворите датотеке у системској подразумеваној апликацији за тип датотеке.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_TITLE": "Отворите графичке датотеке у спољним уређивачима.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_MSG": "Ваш тренутни директоријум има типове графичких датотека које {АПП_НАМЕ} не подржава.<br/> Сада можете да повежете одређене типове датотека са спољним уређивачима. Када се повежете, можете отворити графичке датотеке као што су .кд, .псд, .јпг, .пнг, .аи, .свг у њиховим подразумеваним апликацијама тако што ћете двапут кликнути на датотеке у стаблу датотека.<br/><br/> Кликните на дугме &#39;Ок&#39; да бисте повезали типове графичких датотека са њиховим одговарајућим подразумеваним апликацијама.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_CNF_MSG": "Следећи типови датотека су успешно повезани са подразумеваним апликацијама.<br/> {0} Имате опцију да промените подешавања да ли бришете/додајете нове асоцијације типова датотека у пхцоде.јсон тако што ћете отићи у мени „Дебуг-&gt;Опен Преференцес Филе“.",
  "UNSUPPORTED_BROWSER_TITLE": "Прегледач није подржан",
  "UNSUPPORTED_BROWSER_MESSAGE": "Користите модеран претраживач (објављен у последње 3 године).",
  "UNSUPPORTED_BROWSER_MOBILE_TITLE": "Мобилни претраживачи нису подржани",
  "UNSUPPORTED_BROWSER_MOBILE": "Прегледачи за мобилне уређаје и таблете тренутно нису у потпуности подржани. Можете затворити овај дијалог, али неке функције у Пхоеник-у неће радити у овом претраживачу.<br/><br/> Радимо на развоју изворних апликација за иОС и Андроид. <a href=\"https://github.com/phcode-dev/phoenix/discussions/1046\" target=\"_blank\">Придружите се дискусији овде!</a>",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER_TITLE": "Приступ локалној фасцикли није подржан од стране претраживача",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER": "Жао нам је, изгледа да ваш тренутни прегледач не подржава отварање локалних фасцикли. За ову функцију препоручујемо да користите Цхроме, Едге или Опера.<br/><br/> Алтернативно, радимо на развоју изворних апликација за Виндовс, Мац, Линук, иОС и Андроид како бисмо пружили пуну подршку. <a href=\"https://github.com/phcode-dev/phoenix/discussions/1047\" target=\"_blank\">Пратите новости!</a>",
  "ATTENTION_SAFARI_USERS": "Пажња корисницима Сафарија",
  "ATTENTION_SAFARI_USERS_MESSAGE": "<span>Сафари аутоматски брише податке веб локације ако се сајт не посети у року од 7 дана. {АПП_НАМЕ} се ослања на складиште прегледача да би сачувао ваше пројекте, који могу бити уклоњени због ових смерница.<br/><br/> Препоручује се да <strong>преузмете мацОС десктоп апликацију</strong> са <a href='https://phcode.io' target='_blank' style='color: white'>хттпс://пхцоде.ио</a></span>",
  "CANNOT_PUBLISH_LARGE_PROJECT": "Није могуће објавити велики пројекат",
  "CANNOT_PUBLISH_LARGE_PROJECT_MESSAGE": "Феникс је још увек у експерименталној алфа верзији. Још увек нисмо омогућили синхронизацију пројеката са више од 500 датотека.",
  "SHARE_WEBSITE": "Објавите и делите веб локацију?",
  "PUBLISH": "Објавите",
  "PUBLISH_CONSENT_MESSAGE": "Брзо прегледајте промене и поделите своју веб локацију са другима. Пхоеник може да објави ову веб локацију за вас на {0}. Објављени линкови ће важити 30 дана. </бр>Да ли желите да објавите и делите своју веб локацију?",
  "PUBLISH_SYNC_IN_PROGRESS": "Синхронизација је у току за преглед...",
  "PUBLISH_PAGE": "Кликните да бисте објавили и поделили овај сајт",
  "PUBLISH_VIEW_PAGE": "Кликните да видите објављену страницу",
  "MISSING_FIELDS": "Недостајућа поља",
  "PLEASE_FILL_ALL_REQUIRED": "Попуните сва обавезна поља означена црвеном бојом",
  "CODE_EDITOR": "Цоде Едитор",
  "BUILD_THE_WEB": "Изградите веб",
  "IMPORT_PROJECT": "Импорт Пројецт",
  "GITHUB_PROJECT": "ГитХуб пројекат",
  "NEW_PROJECT_FROM_GITHUB": "Нови пројекат са ГитХуб-а",
  "GITHUB_REPO_URL": "ГитХуб репо УРЛ:",
  "CREATE_PROJECT": "Креирајте пројекат",
  "SETTING_UP_PROJECT": "Постављање пројекта",
  "LOCATION": "Локација:",
  "DOWNLOADING": "Преузимање...",
  "DOWNLOADING_FILE": "Преузимање {0}...",
  "EXTRACTING_FILES_PROGRESS": "Распакивање {0} од {1} датотека.",
  "COMPRESS_FILES_PROGRESS": "Компресовање {0} од {1} датотека.",
  "DOWNLOAD_FAILED_MESSAGE": "Уверите се да је УРЛ за преузимање исправан. </бр>Напомена: Пошто је Пхоеник у алфа верзији, Приватне Репос и ГитХуб УРЛ адресе веће од 25 МБ нису дозвољене.",
  "PLEASE_SELECT_A_FOLDER": "Молимо изаберите фасциклу...",
  "UNZIP_IN_PROGRESS": "Распакивање датотека...",
  "UNZIP_FAILED": "Грешка: Распакивање није успело.",
  "CONFIRM_REPLACE_TITLE": "Потврдите замену",
  "KEEP_BOTH": "Задржи оба",
  "EXPLORE": "ХТМЛ игре",
  "BLOG": "Блог",
  "PHOENIX_DEFAULT_PROJECT": "Подразумевани пројекат",
  "PROJECT_NAME": "Назив пројекта:",
  "NEW_HTML": "Нови ХТМЛ пројекат",
  "LICENSE": "Лиценца:",
  "CREDITS": "Заслуге:",
  "PREVIEW": "Преглед",
  "BUILD_WEBSITE": "Буилд Вебсите",
  "VIEW_MORE": "Погледај још...",
  "NEW_PROJECT_NOTIFICATION": "Кликните на ову икону да бисте креирали нови пројекат.</br><img src=\"styles/images/new_project.png\"><br/> <a href='#' style='float:right;'>У реду</a>",
  "BEAUTIFY_CODE_NOTIFICATION": "Кликните овде или притисните <b>`{0}`</b> да бисте улепшали код.</br><img src=\"styles/images/beautify.gif\"><br/> <a href='#' style='float:right;'>У реду</a>",
  "DEFAULT_PROJECT_NOTIFICATION": "Кликните овде да отворите<br/> <b>подразумевани пројекат</b> у Фениксу.</br> <a href='#' style='float:right;'>У реду</a>",
  "DIRECTORY_REPLACE_MESSAGE": "Изабрани директоријум <span class='dialog-filename'>{0}</span> није празан. Да ли сте сигурни да желите да замените садржај фасцикле са пројектом?",
  "BUILD_WEBSITE_SECTION": "Буилд Вебсите",
  "LEARN_SECTION": "Учите на примерима",
  "CREATE_EXTENSION_SECTION": "Направите {АПП_НАМЕ} екстензије и теме",
  "CREATE_EXTENSION": "Цреате Ектенсион",
  "CREATE_THEME": "Цреате Тхеме",
  "WEBPAGE_HOME_PAGE": "Почетна страница",
  "WEBPAGE_BLOG": "Блог страница",
  "WEBPAGE_DASHBOARD": "ХТМЛ контролна табла",
  "WEBPAGE_BOOTSTRAP_EXAMPLES": "Боотстрап Примери",
  "PROJECTS_AT_A_GLANCE": "Ваши пројекти на први поглед",
  "PROJECT_AT_GLANCE_DESCRIPTION": "Погледајте видео да бисте започели.",
  "PROJECT_FROM_BROWSER": "Чува се у вашем претраживачу",
  "PROJECT_FROM_BROWSER_TERSE": "Складиштење претраживача",
  "PROJECT_SHOW_ON_STARTUP": "Прикажи овај дијалог при покретању",
  "GUIDED_LIVE_PREVIEW": "Направите неке измене кода у ХТМЛ датотеци да бисте видели преглед уживо.</br> <a href='#' style='float:right;'>ок</a>",
  "GUIDED_LIVE_PREVIEW_POPOUT": "Кликните на ово дугме да бисте искочили преглед уживо на нову картицу.</br> <a href='#' style='float:right;'>У реду</a>",
  "ENJOYING_APP": "Свиђа вам се {АПП_НАМЕ}?",
  "GITHUB_STARS_POPUP": "<div>Ваше рецензије мотивишу наш мали тим да учини <b>пхцоде.дев</b> још бољим.<br/> Молимо вас да нас означите звездицом на ГитХуб-у:",
  "GITHUB_STARS_POPUP_TWITTER": "Дајте повратне информације или проширите вест на Твиттер-у:",
  "TEST_TRANSLATE": "користите ово за тестирање превода",
  "POWER_USER_POPUP_TITLE": "Како можемо да побољшамо {АПП_НАМЕ} за вас?",
  "POWER_USER_POPUP_TEXT": "<div>Волели бисмо да добијемо ваше повратне информације. Ваше повратне информације нам помажу да одлучимо које функције да направимо и која побољшања треба да урадимо на нашој платформи.<br/> <a>Молимо попуните ову кратку анкету.</a></div>",
  "BEAUTIFY_ERROR": "Улепшавање кода није успело. Проверите синтаксу.",
  "BEAUTIFY_ERROR_ORIGINAL_CHANGED": "Није могло да се улепша. Текст уредника је промењен након улепшавања.",
  "BEAUTIFY_PROJECT_BUSY_MESSAGE": "Улепшавање датотеке {0}",
  "BEAUTIFY_ERROR_SELECTION": "Није могуће улепшати.</бр>Изабран је непотпун блок кода или неважећа синтакса.",
  "BEAUTIFY_OPTIONS": "Опције које контролишу како функционише Беаутифи Цоде",
  "BEAUTIFY_OPTION_PRINT_WIDTH": "Одредите дужину линије на којој ће се улепшавање обавити",
  "BEAUTIFY_OPTION_SEMICOLON": "Додајте тачку и зарез на крају сваке изјаве",
  "BEAUTIFY_OPTION_SINGLE_QUOTE": "Користите једноструке наводнике уместо двоструких наводника",
  "BEAUTIFY_OPTION_QUOTE_PROPS": "Промените када се својства у објектима наводе",
  "BEAUTIFY_OPTION_BRACKET_SAME_LINE": "Ставите > вишередног ХТМЛ (ХТМЛ, ЈСКС, Вуе, Ангулар) елемента на крај последњег реда уместо да будете сами у следећем реду (не примењује се на елементе који се самозатварају)",
  "BEAUTIFY_OPTION_SINGLE_ATTRIBUTE_PER_LINE": "Примените један атрибут по реду у ХТМЛ, Вуе и ЈСКС",
  "BEAUTIFY_OPTION_PROSE_WRAP": "Замотајте прозу ако премашује ширину штампе у датотекама за означавање",
  "BEAUTIFY_OPTION_PRINT_TRAILING_COMMAS": "Штампајте задње зарезе где год је то могуће у синтаксичким структурама раздвојеним зарезима у више редова"
});