/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 * Original work Copyright (c) 2012 - 2021 Adobe Systems Incorporated. All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "GENERIC_ERROR": "(त्रुटि {0})",
  "NOT_FOUND_ERR": "फ़ाइल/निर्देशिका नहीं मिल सका।",
  "NOT_READABLE_ERR": "फ़ाइल/निर्देशिका पढ़ा नहीं जा सका।",
  "EXCEEDS_MAX_FILE_SIZE": "{0} MB से बड़ी फ़ाइलें {APP_NAME} में नहीं खोली जा सकती हैं।",
  "NO_MODIFICATION_ALLOWED_ERR": "लक्ष्य निर्देशिका को संशोधित नहीं किया जा सकता है।",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "अनुमतियाँ आपको संशोधन करने की अनुमति नहीं देती हैं।",
  "CONTENTS_MODIFIED_ERR": "फ़ाइल को {APP_NAME} के बाहर संशोधित किया गया है।",
  "UNSUPPORTED_ENCODING_ERR": "अज्ञात एन्कोडिंग फ़ॉर्मेट",
  "ENCODE_FILE_FAILED_ERR": "{APP_NAME} फ़ाइल की सामग्री को एन्कोड करने में सक्षम नहीं था।",
  "DECODE_FILE_FAILED_ERR": "{APP_NAME} फ़ाइल की सामग्री को डीकोड करने में सक्षम नहीं था।",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "{APP_NAME} वर्तमान में UTF-16 एन्कोडेड टेक्स्ट फ़ाइलों का समर्थन नहीं करता है।",
  "FILE_EXISTS_ERR": "फ़ाइल या निर्देशिका पहले से मौजूद है।",
  "FILE": "फ़ाइल",
  "FILE_TITLE": "फ़ाइल",
  "DIRECTORY": "निर्देशिका",
  "DIRECTORY_TITLE": "निर्देशिका",
  "DIRECTORY_NAMES_LEDE": "डिरेक्ट्री नाम",
  "FILENAMES_LEDE": "फ़ाइलनाम",
  "FILENAME": "फ़ाइलनाम",
  "DIRECTORY_NAME": "डिरेक्ट्री नाम",
  "ERROR_LOADING_PROJECT": "प्रोजेक्ट लोड करने में त्रुटि",
  "OPEN_DIALOG_ERROR": "खुला फ़ाइल संवाद दिखाते समय एक त्रुटि हुई। (त्रुटि {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "निर्देशिका को लोड करने का प्रयास करते समय एक त्रुटि हुई <span class='dialog-filename'>{0}</span>। (त्रुटि {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "निर्देशिका की सामग्री को पढ़ने के दौरान एक त्रुटि हुई <span class='dialog-filename'>{0}</span>। (त्रुटि {1})",
  "ERROR_OPENING_FILE_TITLE": "फ़ाइल खोलने में त्रुटि",
  "ERROR_OPENING_FILE": "फ़ाइल को खोलने का प्रयास करते समय एक त्रुटि हुई <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_OPENING_FILES": "निम्न फ़ाइलों को खोलने का प्रयास करते समय एक त्रुटि हुई:",
  "ERROR_RELOADING_FILE_TITLE": "डिस्क से परिवर्तन पुनः लोड करने में त्रुटि",
  "ERROR_RELOADING_FILE": "फ़ाइल को पुनः लोड करने का प्रयास करते समय एक त्रुटि हुई <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_SAVING_FILE_TITLE": "फ़ाइल सहेजने में त्रुटि",
  "ERROR_SAVING_FILE": "फ़ाइल को सहेजने का प्रयास करते समय एक त्रुटि हुई <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_FILE_TITLE": "{0} नाम बदलने में त्रुटि",
  "ERROR_RENAMING_FILE": "{2} {<span class='dialog-filename'>0</span>} का नाम बदलने का प्रयास करते समय एक त्रुटि हुई. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "फ़ाइल या निर्देशिका वर्तमान में खोले गए प्रोजेक्ट का हिस्सा नहीं है। दुर्भाग्य से, इस बिंदु पर केवल प्रोजेक्ट फ़ाइलों का नाम बदला जा सकता है।",
  "ERROR_MOVING_FILE_TITLE": "{0} खिसकाने में त्रुटि",
  "ERROR_MOVING_FILE": "{2} {<span class='dialog-filename'>0}. {1} खिसकाने</span> का प्रयास करते समय एक त्रुटि हुई",
  "ERROR_MOVING_NOT_IN_PROJECT": "फ़ाइल/फ़ोल्डर को स्थानांतरित नहीं किया जा सकता, क्योंकि वे वर्तमान प्रोजेक्ट का हिस्सा नहीं हैं।",
  "ERROR_DELETING_FILE_TITLE": "{0} मिटाने में त्रुटि",
  "ERROR_DELETING_FILE": "{2} {<span class='dialog-filename'>0</span>} को मिटाने का प्रयास करते समय एक त्रुटि हुई. {1}",
  "INVALID_FILENAME_TITLE": "अमान्य {0}",
  "CANNOT_PASTE_TITLE": "{0} पेस्ट नहीं किया जा सकता",
  "ERR_TYPE_PASTE_FAILED": "<span class='dialog-filename'>{0} को <span class='dialog-filename'>{1}</span></span> चिपकाने के दौरान एक त्रुटि हुई",
  "CANNOT_DUPLICATE_TITLE": "डुप्लिकेट नहीं कर सकता",
  "ERR_TYPE_DUPLICATE_FAILED": "<span class='dialog-filename'>{0}</span> डुप्लीकेट करते समय एक त्रुटि हुई",
  "INVALID_FILENAME_MESSAGE": "{0} किसी भी सिस्टम आरक्षित शब्दों का उपयोग नहीं कर सकते हैं, डॉट्स (.) के साथ समाप्त हो सकते हैं या निम्न वर्णों में से किसी एक का उपयोग नहीं कर सकते हैं: <code class='emphasized'>{</code>",
  "ENTRY_WITH_SAME_NAME_EXISTS": "<span class='dialog-filename'>{0}</span> नाम वाली फ़ाइल या निर्देशिका पहले से मौजूद है।",
  "ERROR_CREATING_FILE_TITLE": "{0} बनाने में त्रुटि",
  "ERROR_CREATING_FILE": "{0} {<span class='dialog-filename'>1</span>} बनाने का प्रयास करते समय एक त्रुटि हुई. {2}",
  "ERROR_MIXED_DRAGDROP": "अन्य फ़ाइलों को खोलने के साथ ही फ़ोल्डर नहीं खोल सकता।",
  "ERROR_KEYMAP_TITLE": "उपयोक्ता कुंजी मानचित्र पढ़ने में त्रुटि",
  "ERROR_KEYMAP_CORRUPT": "आपकी कुंजी मैप फ़ाइल JSON मान्य नहीं है। फ़ाइल खोली जाएगी ताकि आप प्रारूप को सही कर सकें।",
  "ERROR_LOADING_KEYMAP": "आपकी कुंजी मैप फ़ाइल वैध UTF-8 एन्कोडेड टेक्स्ट फ़ाइल नहीं है और इसे लोड नहीं किया जा सकता है",
  "ERROR_RESTRICTED_COMMANDS": "आप इन आदेशों के लिए शॉर्टकट पुन: असाइन नहीं कर सकते: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "आप इन शॉर्टकट को पुन: असाइन नहीं कर सकते: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "आप इन आदेशों के लिए कई शॉर्टकट पुन: असाइन कर रहे हैं: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "आपके पास इन शॉर्टकट के कई बाइंडिंग हैं: {0}",
  "ERROR_INVALID_SHORTCUTS": "ये शॉर्टकट अमान्य हैं: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "आप गैर-मौजूद आदेशों के लिए शॉर्टकट असाइन कर रहे हैं: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "वरीयताएँ पढ़ने में त्रुटि",
  "ERROR_PREFS_CORRUPT": "आपकी वरीयता फ़ाइल JSON मान्य नहीं है। फ़ाइल खोली जाएगी ताकि आप प्रारूप को सही कर सकें। परिवर्तनों को प्रभावी करने के लिए आपको {APP_NAME} को पुनरारंभ करना होगा।",
  "ERROR_PROJ_PREFS_CORRUPT": "आपकी प्रोजेक्ट प्राथमिकता फ़ाइल JSON मान्य नहीं है। फ़ाइल खोली जाएगी ताकि आप प्रारूप को सही कर सकें। परिवर्तनों को प्रभावी करने के लिए आपको प्रोजेक्ट को फिर से लोड करना होगा।",
  "ERROR_IN_BROWSER_TITLE": "उफ़! {APP_NAME} ब्राउज़र में अभी तक नहीं चलता है।",
  "ERROR_IN_BROWSER": "{APP_NAME} HTML में बनाया गया है, लेकिन अभी यह डेस्कटॉप ऐप के रूप में चलता है ताकि आप इसे स्थानीय फ़ाइलों को संपादित करने के लिए उपयोग कर सकें। {APP_NAME} चलाने के लिए कृपया <b>github.com/adobe/brackets-shell</b> रेपो में एप्लिकेशन शेल का उपयोग करें।",
  "ERROR_MAX_FILES_TITLE": "फ़ाइलों का अनुक्रमण करने में त्रुटि",
  "ERROR_MAX_FILES": "इस प्रोजेक्ट में 30,000 से अधिक फाइलें हैं। कई फ़ाइलों में संचालित होने वाली सुविधाएँ अक्षम हो सकती हैं या ऐसा व्यवहार कर सकती हैं जैसे कि प्रोजेक्ट खाली है। <a href='https://github.com/adobe/brackets/wiki/Large-Projects'>बड़ी परियोजनाओं के साथ काम करने के बारे में और पढ़ें</a>।",
  "ERROR_LAUNCHING_BROWSER_TITLE": "ब्राउज़र लॉन्च करने में त्रुटि",
  "ERROR_CANT_FIND_CHROME": "Google Chrome ब्राउज़र नहीं मिला। कृपया सुनिश्चित करें कि यह स्थापित है।",
  "ERROR_LAUNCHING_BROWSER": "ब्राउज़र को लॉन्च करते समय एक त्रुटि हुई। (त्रुटि {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "लाइव पूर्वावलोकन त्रुटि",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "ब्राउज़र से कनेक्ट करना",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "लाइव प्रीव्यू कनेक्ट करने के लिए, Chrome को रिमोट डीबगिंग सक्षम के साथ फिर से लॉन्च करने की आवश्यकता है। <br /><br />क्या आप क्रोम को फिर से लॉन्च करना चाहते हैं और रिमोट डीबगिंग को सक्षम करना चाहते हैं? <br /><br />",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "लाइव प्रीव्यू पेज लोड करने में अक्षम।",
  "LIVE_DEV_NEED_HTML_MESSAGE": "एक HTML फ़ाइल खोलें या सुनिश्चित करें कि लाइव पूर्वावलोकन लॉन्च करने के लिए आपके प्रोजेक्ट में index.html फ़ाइल है।",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "सर्वर-साइड फ़ाइल के साथ लाइव पूर्वावलोकन लॉन्च करने के लिए, आपको इस प्रोजेक्ट के लिए एक बेस URL निर्दिष्ट करना होगा।",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "लाइव पूर्वावलोकन फ़ाइलों के लिए HTTP सर्वर को प्रारंभ करने में त्रुटि। कृपया पुन: प्रयास करें।",
  "LIVE_DEVELOPMENT_INFO_TITLE": "लाइव पूर्वावलोकन में आपका स्वागत है!",
  "LIVE_DEVELOPMENT_INFO_MESSAGE": "लाइव पूर्वावलोकन {APP_NAME} को आपके ब्राउज़र से जोड़ता है। यह ब्राउज़र में आपकी HTML फ़ाइल का पूर्वावलोकन लॉन्च करता है, फिर जैसे ही आप अपना कोड संपादित करते हैं, पूर्वावलोकन को तुरंत अपडेट करता है। <br /><br />{APP_NAME} के इस शुरुआती संस्करण में, लाइव पूर्वावलोकन केवल <strong>Google Chrome</strong> के साथ काम करता है और <strong>CSS या HTML फ़ाइलों</strong> को संपादित करते समय अपडेट लाइव होते हैं। जब आप सहेजते हैं तो जावास्क्रिप्ट फ़ाइलों में परिवर्तन स्वचालित रूप से पुनः लोड हो जाते हैं। <br /><br />(आपको यह संदेश केवल एक बार दिखाई देगा.)",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "अधिक जानकारी के लिए, <a href='{0}' title='{0}'>लाइव पूर्वावलोकन कनेक्शन त्रुटियों का समस्या निवारण</a> देखें।",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "सजीव पूर्वावलोकन",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "लाइव पूर्वावलोकन: कनेक्ट हो रहा है...",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "लाइव पूर्वावलोकन: आरंभ किया जा रहा है...",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "लाइव प्रीव्यू को डिस्कनेक्ट करें",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "लाइव पूर्वावलोकन (ताज़ा करने के लिए फ़ाइल सहेजें)",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "लाइव प्रीव्यू के लिए फ़ाइल चुनें",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "पृष्ठ पुनः लोड करें",
  "LIVE_DEV_CLICK_POPOUT": "पॉपआउट लाइव प्रीव्यू टू न्यू विंडो",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "अनपिन प्रीव्यू पेज पर पिन करें",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "लाइव पूर्वावलोकन (सिंटैक्स त्रुटि के कारण अपडेट नहीं हो रहा है)",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "लाइव पूर्वावलोकन रद्द कर दिया गया क्योंकि ब्राउज़र के डेवलपर टूल खोले गए थे",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "ब्राउज़र में पृष्ठ बंद होने के कारण लाइव पूर्वावलोकन रद्द कर दिया गया था",
  "LIVE_DEV_NAVIGATED_AWAY": "लाइव पूर्वावलोकन रद्द कर दिया गया था क्योंकि ब्राउज़र उस पृष्ठ पर नेविगेट किया गया था जो वर्तमान प्रोजेक्ट का हिस्सा नहीं है",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "किसी अज्ञात कारण से लाइव पूर्वावलोकन रद्द कर दिया गया ({0})",
  "SAVE_CLOSE_TITLE": "परिवर्तनों को सहेजें",
  "SAVE_CLOSE_MESSAGE": "क्या आप दस्तावेज़ <span class='dialog-filename'>{0}</span> में किए गए परिवर्तनों को सहेजना चाहते हैं?",
  "SAVE_CLOSE_MULTI_MESSAGE": "क्या आप अपने परिवर्तनों को निम्न फ़ाइलों में सहेजना चाहते हैं?",
  "EXT_MODIFIED_TITLE": "बाह्य परिवर्तन",
  "CONFIRM_DELETE_TITLE": "मिटाना पुष्टि करें",
  "CONFIRM_FILE_DELETE": "क्या आप वाकई फ़ाइल <span class='dialog-filename'>{0}</span> को मिटाना चाहते हैं?",
  "CONFIRM_FOLDER_DELETE": "क्या आप वाकई फ़ोल्डर <span class='dialog-filename'>{0}</span> को मिटाना चाहते हैं?",
  "FILE_DELETED_TITLE": "फ़ाइल मिटाई गई",
  "EXT_MODIFIED_WARNING": "<span class='dialog-filename'>{0}</span> को डिस्क पर {APP_NAME} के बाहर परिवर्धित किया गया है। <br /><br />क्या आप फ़ाइल को सहेजना चाहते हैं और उन परिवर्तनों को ओवरराइट करना चाहते हैं?",
  "EXT_MODIFIED_MESSAGE": "<span class='dialog-filename'>{0}</span> को {APP_NAME} के बाहर डिस्क पर संशोधित किया गया है, लेकिन इसमें {APP_NAME} में बिना सहेजे गए परिवर्तन भी हैं। <br /><br />आप किस संस्करण को रखना चाहते हैं?",
  "EXT_DELETED_MESSAGE": "<span class='dialog-filename'>{0}</span> को डिस्क पर {APP_NAME} के बाहर हटा दिया गया है, लेकिन इसमें बिना सहेजे गए परिवर्तन {APP_NAME} में हैं। <br /><br />क्या आप अपने बदलाव रखना चाहते हैं?",
  "WINDOW_UNLOAD_WARNING": "क्या आप वाकई एक अलग URL पर नेविगेट करना चाहते हैं और Brackets को छोड़ना चाहते हैं?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "आपके पास बिना सहेजे गए परिवर्तन हैं! क्या आप वाकई एक अलग URL पर नेविगेट करना चाहते हैं और Brackets को छोड़ना चाहते हैं?",
  "DONE": "डन",
  "OK": "ठीक है",
  "CANCEL": "रद्द करें",
  "DONT_SAVE": "सेव न करें",
  "SAVE": "सेव",
  "SAVE_AS": "इस रूप में सहेजें...",
  "SAVE_AND_OVERWRITE": "मिटाकर लिखें",
  "DELETE": "मिटाएँ",
  "BUTTON_YES": "हाँ",
  "BUTTON_NO": "नहीं",
  "FIND_MATCH_INDEX": "{1} का {0}",
  "FIND_NO_RESULTS": "कोई परिणाम नहीं",
  "FIND_QUERY_PLACEHOLDER": "ढूंढें...",
  "FIND_HISTORY_MAX_COUNT": "खोज इतिहास में खोज आइटम की अधिकतम संख्या",
  "REPLACE_PLACEHOLDER": "इसके साथ बदलें...",
  "BUTTON_REPLACE_ALL": "सभी को बदलें",
  "BUTTON_REPLACE_BATCH": "बैच...",
  "BUTTON_REPLACE_ALL_IN_FILES": "बदलें...",
  "BUTTON_REPLACE": "बदलें",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "अगला मैच",
  "BUTTON_PREV_HINT": "पिछला मैच",
  "BUTTON_CASESENSITIVE_HINT": "मैच केस",
  "BUTTON_REGEXP_HINT": "नियमित अभिव्यक्ति",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "बिना पूर्ववत करें बदलें",
  "REPLACE_WITHOUT_UNDO_WARNING": "चूंकि {0} से अधिक फ़ाइलों को परिवर्तित करने की आवश्यकता है, {APP_NAME} डिस्क पर अनपेक्षित फ़ाइलों को संशोधित करेगा। <br />आप उन फ़ाइलों में प्रतिस्थापन को पूर्ववत नहीं कर पाएंगे।",
  "BUTTON_REPLACE_WITHOUT_UNDO": "बिना पूर्ववत करें बदलें",
  "OPEN_FILE": "फ़ाइल खोलें",
  "SAVE_FILE_AS": "फ़ाइल सहेजें",
  "CHOOSE_FOLDER": "एक फोल्डर चुनें",
  "RELEASE_NOTES": "नोट्स जारी करें",
  "NO_UPDATE_TITLE": "आप अद्यतित हैं!",
  "NO_UPDATE_MESSAGE": "आप {APP_NAME} का नवीनतम संस्करण चला रहे हैं।",
  "FIND_REPLACE_TITLE_LABEL": "बदलें",
  "FIND_REPLACE_TITLE_WITH": "साथ",
  "FIND_TITLE_LABEL": "मिल गया",
  "FIND_TITLE_SUMMARY": "— {0} {1} {2} {3} में",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "<span class='dialog-filename'>{0}</span> में",
  "FIND_IN_FILES_NO_SCOPE": "प्रोजेक्ट में",
  "FIND_IN_FILES_ZERO_FILES": "फ़िल्टर में सभी फाइलें शामिल नहीं हैं {0}",
  "FIND_IN_FILES_FILE": "फ़ाइल",
  "FIND_IN_FILES_FILES": "फ़ाइलें",
  "FIND_IN_FILES_MATCH": "मेल खाना",
  "FIND_IN_FILES_MATCHES": "माचिस",
  "FIND_IN_FILES_MORE_THAN": "ओवर ",
  "FIND_IN_FILES_PAGING": "{0} — {1}",
  "FIND_IN_FILES_FILE_PATH": "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "Ctrl/Cmd सभी का विस्तार/संक्षिप्त करने के लिए क्लिक करें",
  "FIND_IN_FILES_INDEXING": "त्वरित खोज के लिए इंडेक्सिंग...",
  "FIND_IN_FILES_INDEXING_PROGRESS": "तत्काल खोज के लिए {1} फ़ाइलों में से {0} को अनुक्रमणित करना...",
  "REPLACE_IN_FILES_ERRORS_TITLE": "त्रुटियाँ बदलें",
  "REPLACE_IN_FILES_ERRORS": "निम्न फ़ाइलों को संशोधित नहीं किया गया क्योंकि वे खोज के बाद बदल गईं या लिखी नहीं जा सकी।",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "अद्यतन जानकारी प्राप्त करने में त्रुटि",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "सर्वर से नवीनतम अद्यतन जानकारी प्राप्त करने में समस्या थी। कृपया सुनिश्चित करें कि आप इंटरनेट से कनेक्ट हैं और फिर से प्रयास करें।",
  "NEW_FILE_FILTER": "नया बहिष्करण सेट",
  "CLEAR_FILE_FILTER": "फ़ाइलों को बाहर न करें",
  "NO_FILE_FILTER": "कोई फ़ाइल बहिष्कृत नहीं",
  "EXCLUDE_FILE_FILTER": "{0} को बाहर करें",
  "EDIT_FILE_FILTER": "संपादित करें...",
  "FILE_FILTER_DIALOG": "बहिष्करण सेट संपादित करें",
  "FILE_FILTER_INSTRUCTIONS": "निम्न स्ट्रिंग/सबस्ट्रिंग्स या <a href='{0}' title='{0}'>वाइल्डकार्ड</a> में से किसी एक से मेल खाने वाली फ़ाइलों और फ़ोल्डरों को बाहर निकालें। प्रत्येक स्ट्रिंग को एक नई लाइन पर दर्ज करें।",
  "FILTER_NAME_PLACEHOLDER": "इस बहिष्करण सेट को नाम दें (वैकल्पिक)",
  "FILTER_NAME_REMAINING": "{0} वर्ण शेष हैं",
  "FILE_FILTER_CLIPPED_SUFFIX": "और {0} और",
  "FILTER_COUNTING_FILES": "फाइलों की गिनती...",
  "FILTER_FILE_COUNT": "{1} फ़ाइलों की {0} अनुमति देता है {2}",
  "FILTER_FILE_COUNT_ALL": "सभी {0} फ़ाइलों को अनुमति देता है {1}",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "वर्तमान कर्सर स्थिति के लिए कोई त्वरित संपादन उपलब्ध नहीं है",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "[Css] सीएसएस त्वरित संपादन: कर्सर को एकल वर्ग के नाम पर रखें",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "[Css] सीएसएस त्वरित संपादन: अपूर्ण वर्ग विशेषता",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "[Css] सीएसएस त्वरित संपादन: अपूर्ण आईडी विशेषता",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "सीएसएस क्विक एडिट: कर्सर को टैग, क्लास या आईडी में रखें",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "सीएसएस टाइमिंग फंक्शन क्विक एडिट: अमान्य सिंटैक्स",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "जेएस क्विक एडिट: फ़ंक्शन नाम में कर्सर रखें",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "वर्तमान कर्सर स्थिति के लिए कोई क्विक डॉक्स उपलब्ध नहीं है",
  "PROJECT_LOADING": "लोड हो रहा है",
  "UNTITLED": "शीर्षकहीन",
  "WORKING_FILES": "वर्किंग फाइल्स",
  "TOP": "टॉप",
  "BOTTOM": "बॉटम",
  "LEFT": "बायाँ",
  "RIGHT": "दाएँ",
  "CMD_SPLITVIEW_NONE": "नो स्प्लिट",
  "CMD_SPLITVIEW_VERTICAL": "वर्टिकल स्प्लिट",
  "CMD_SPLITVIEW_HORIZONTAL": "क्षैतिज विभाजन",
  "SPLITVIEW_MENU_TOOLTIP": "संपादक को लंबवत या क्षैतिज रूप से विभाजित करें",
  "GEAR_MENU_TOOLTIP": "वर्किंग सेट कॉन्फ़िगर करें",
  "SPLITVIEW_INFO_TITLE": "पहले से खुला हुआ",
  "SPLITVIEW_MULTIPANE_WARNING": "फ़ाइल पहले से ही किसी अन्य फलक में खुली है {APP_NAME} जल्द ही एक ही फाइल को एक से अधिक फलक में खोलने का समर्थन करेगा। तब तक, फ़ाइल उस फलक में दिखाई जाएगी जिसमें यह पहले से खुला है। <br /><br />(आपको यह संदेश केवल एक बार दिखाई देगा.)",
  "STATUSBAR_CURSOR_POSITION": "पंक्ति {0}, स्तम्भ {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": " — चयनित {0} स्तम्भ",
  "STATUSBAR_SELECTION_CH_PLURAL": " — चयनित {0} स्तम्भ",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " — चयनित {0} पंक्ति",
  "STATUSBAR_SELECTION_LINE_PLURAL": " — चयनित {0} पंक्तियाँ",
  "STATUSBAR_SELECTION_MULTIPLE": " — {0} चयन",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "इंडेंटेशन को रिक्त स्थान पर बदलने के लिए क्लिक",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "इंडेंटेशन को टैब में बदलने के लिए क्लिक करें",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "इंडेंट करते समय उपयोग किए जाने वाले रिक्त स्थान की संख्या बदलने के लिए क्लिक करें",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "टैब वर्ण चौड़ाई बदलने के लिए क्लिक करें",
  "STATUSBAR_SPACES": "रिक्त स्थान:",
  "STATUSBAR_TAB_SIZE": "टैब का आकार:",
  "STATUSBAR_LINE_COUNT_SINGULAR": "— {0} लाइन",
  "STATUSBAR_LINE_COUNT_PLURAL": "— {0} लाइन्स",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "एक्सटेंशन अक्षम",
  "STATUSBAR_INSERT": "इन्स",
  "STATUSBAR_OVERWRITE": "ओवर",
  "STATUSBAR_INSOVR_TOOLTIP": "इन्सर्ट (INS) और ओवरराइट (OVR) मोड के बीच कर्सर टॉगल करने के लिए क्लिक करें",
  "STATUSBAR_LANG_TOOLTIP": "फ़ाइल क़िस्म बदलने के लिए क्लिक",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}। रिपोर्ट पैनल टॉगल करने के लिए क्लिक करें।",
  "STATUSBAR_DEFAULT_LANG": "(डिफ़ॉल्ट)",
  "STATUSBAR_SET_DEFAULT_LANG": ". {0} फ़ाइलों के लिए डिफ़ॉल्ट के रूप में सेट करें",
  "STATUSBAR_ENCODING_TOOLTIP": "एन्कोडिंग का चयन करें",
  "ERRORS_PANEL_TITLE_MULTIPLE": "{0} समस्याएँ",
  "SINGLE_ERROR": "1 {0} समस्या",
  "MULTIPLE_ERRORS": "{1} {0} समस्याएँ",
  "NO_ERRORS": "कोई {0} समस्याएं नहीं मिलीं - अच्छा काम!",
  "NO_ERRORS_MULTIPLE_PROVIDER": "कोई समस्या नहीं मिली - अच्छी नौकरी!",
  "LINT_DISABLED": "लिन्टिंग अक्षम है",
  "NO_LINT_AVAILABLE": "{0} के लिए कोई लिंटर उपलब्ध नहीं है",
  "NOTHING_TO_LINT": "लिंट के लिए कुछ भी नहीं",
  "LINTER_TIMED_OUT": "{0} ने {1} एमएस के इंतजार के बाद समय समाप्त कर दिया है",
  "LINTER_FAILED": "{0} त्रुटि के साथ समाप्त: {1}",
  "FILE_MENU": "फ़ाइल",
  "CMD_FILE_NEW_UNTITLED": "नया",
  "CMD_FILE_NEW": "नया फ़ाइल",
  "CMD_FILE_DUPLICATE": "डुप्लीकेट",
  "CMD_FILE_CUT": "कट",
  "CMD_FILE_COPY": "नक़ल",
  "CMD_FILE_COPY_PATH": "पथ कॉपी करें",
  "CMD_FILE_PASTE": "चिपकाएँ",
  "CMD_PROJECT_NEW": "नया प्रोजेक्ट",
  "CMD_FILE_NEW_FOLDER": "नया फोल्डर",
  "CMD_FILE_OPEN": "खोलें...",
  "CMD_RECENT_FILES_OPEN": "हाल ही में खोलें...",
  "CMD_ADD_TO_WORKING_SET": "वर्किंग सेट के लिए खोलें",
  "CMD_OPEN_DROPPED_FILES": "गिराई गई फ़ाइलें खोलें",
  "CMD_OPEN_FOLDER": "फोल्डर खोलें...",
  "CMD_FILE_CLOSE": "बन्द करें",
  "CMD_FILE_CLOSE_ALL": "सभी बन्द करें",
  "CMD_FILE_CLOSE_LIST": "सूची बन्द करें",
  "CMD_FILE_CLOSE_OTHERS": "दूसरों को बंद करें",
  "CMD_FILE_CLOSE_ABOVE": "दूसरों को ऊपर बंद करें",
  "CMD_FILE_CLOSE_BELOW": "दूसरों को नीचे बंद करें",
  "CMD_FILE_SAVE": "सेव",
  "CMD_FILE_SAVE_ALL": "सभी को बचाओ",
  "CMD_FILE_SAVE_AS": "इस रूप में सहेजें...",
  "CMD_LIVE_FILE_PREVIEW": "सजीव पूर्वावलोकन",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "प्रायोगिक लाइव पूर्वावलोकन सक्षम करें",
  "CMD_RELOAD_LIVE_PREVIEW": "फोर्स रीलोड लाइव प्रीव्यू",
  "CMD_PROJECT_SETTINGS": "प्रोजेक्ट सेटिंग...",
  "CMD_FILE_RENAME": "नाम बदलें",
  "CMD_FILE_DELETE": "मिटाएँ",
  "CMD_INSTALL_EXTENSION": "एक्सटेंशन इंस्टॉल करें...",
  "CMD_EXTENSION_MANAGER": "एक्सटेंशन मैनेजर...",
  "CMD_FILE_REFRESH": "फ़ाइल ट्री रीफ्रेश करें",
  "CMD_QUIT": "क्विट",
  "CMD_EXIT": "बाहर जाएं",
  "EDIT_MENU": "संपादित करें",
  "CMD_UNDO": "पूर्ववत करें",
  "CMD_REDO": "फिर से करें",
  "CMD_CUT": "कट",
  "CMD_COPY": "नक़ल",
  "CMD_PASTE": "चिपकाएँ",
  "CMD_SELECT_ALL": "सभी का चयन करें",
  "CMD_SELECT_LINE": "पंक्ति चुनें",
  "CMD_SPLIT_SEL_INTO_LINES": "चयन को लाइनों में विभाजित करें",
  "CMD_ADD_CUR_TO_NEXT_LINE": "कर्सर को अगली पंक्ति में जोड़ें",
  "CMD_ADD_CUR_TO_PREV_LINE": "कर्सर को पिछली पंक्ति में जोड़ें",
  "CMD_INDENT": "इंडेंट",
  "CMD_UNINDENT": "अनइंडेंट",
  "CMD_DUPLICATE": "डुप्लीकेट",
  "CMD_DELETE_LINES": "पंक्ति मिटाएँ",
  "CMD_COMMENT": "पंक्ति टिप्पणी टॉगल करें",
  "CMD_BLOCK_COMMENT": "ब्लॉक टिप्पणी टॉगल करें",
  "CMD_LINE_UP": "पंक्ति को ऊपर ले जाएँ",
  "CMD_LINE_DOWN": "पंक्ति को नीचे ले जाएँ",
  "CMD_OPEN_LINE_ABOVE": "ओपन लाइन अबव",
  "CMD_OPEN_LINE_BELOW": "नीचे लाइन खोलें",
  "CMD_TOGGLE_CLOSE_BRACKETS": "ऑटो क्लोज ब्रेसेस",
  "CMD_SHOW_CODE_HINTS": "कोड संकेत दिखाएँ",
  "FIND_MENU": "ढूँढें",
  "CMD_FIND": "ढूँढें",
  "CMD_FIND_NEXT": "अगला ढूँढें",
  "CMD_FIND_PREVIOUS": "पिछला ढूंढें",
  "CMD_FIND_ALL_AND_SELECT": "सब ढूँढें और चुनें",
  "CMD_ADD_NEXT_MATCH": "चयन में अगला मिलान जोड़ें",
  "CMD_SKIP_CURRENT_MATCH": "स्किप करें और अगला मैच जोड़ें",
  "CMD_FIND_IN_FILES": "फाइल्स में खोजें",
  "CMD_FIND_IN_SUBTREE": "में ढूँढें...",
  "CMD_REPLACE": "बदलें",
  "CMD_REPLACE_IN_FILES": "फ़ाइलों में बदलें",
  "CMD_REPLACE_IN_SUBTREE": "में बदलें...",
  "VIEW_MENU": "व्यू",
  "CMD_HIDE_SIDEBAR": "साइडबार छुपाएँ",
  "CMD_SHOW_SIDEBAR": "साइडबार दिखाएँ",
  "CMD_TOGGLE_SIDEBAR": "साइडबार टॉगल करें",
  "CMD_TOGGLE_PANELS": "पैनल टॉगल करें",
  "CMD_TOGGLE_PURE_CODE": "कोई विकर्षण नहीं",
  "CMD_INCREASE_FONT_SIZE": "फ़ॉन्ट का आकार बढ़ाएँ",
  "CMD_DECREASE_FONT_SIZE": "फ़ॉन्ट का आकार घटाएं",
  "CMD_RESTORE_FONT_SIZE": "फ़ॉन्ट आकार को पुनर्स्थापित करें",
  "CMD_SCROLL_LINE_UP": "स्क्रॉल लाइन अप",
  "CMD_SCROLL_LINE_DOWN": "स्क्रॉल लाइन डाउन",
  "CMD_TOGGLE_LINE_NUMBERS": "पंक्ति क्रमांक",
  "CMD_TOGGLE_ACTIVE_LINE": "सक्रिय पंक्ति को हाईलाइट करें",
  "CMD_TOGGLE_WORD_WRAP": "वर्ड रैप",
  "CMD_LIVE_HIGHLIGHT": "लाइव पूर्वावलोकन हाइलाइट",
  "CMD_VIEW_TOGGLE_INSPECTION": "सेव पर लिंट फाइल्स",
  "CMD_WORKINGSET_SORT_BY_ADDED": "इसके अनुसार क्रमबद्ध करें",
  "CMD_WORKINGSET_SORT_BY_NAME": "नाम के अनुसार छाँटें",
  "CMD_WORKINGSET_SORT_BY_TYPE": "प्रकार के अनुसार क्रमबद्ध करें",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "स्वचालित सॉर्ट करें",
  "CMD_THEMES": "थीम्स...",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "खोज स्वचालित रूप से बंद करें",
  "NAVIGATE_MENU": "नेविगेट करें",
  "CMD_QUICK_OPEN": "क्विक ओपन",
  "CMD_GOTO_LINE": "लाइन पर जाएं",
  "CMD_GOTO_DEFINITION": "क्विक फाइंड परिभाषा",
  "CMD_GOTO_DEFINITION_PROJECT": "प्रोजेक्ट में क्विक फाइंड डेफिनिशन",
  "CMD_GOTO_FIRST_PROBLEM": "पहली समस्या पर जाएँ",
  "CMD_TOGGLE_QUICK_EDIT": "क्विक एडिट",
  "CMD_TOGGLE_QUICK_DOCS": "क्विक डॉक्स",
  "CMD_QUICK_EDIT_PREV_MATCH": "पिछला मैच",
  "CMD_QUICK_EDIT_NEXT_MATCH": "अगला मैच",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "नया नियम",
  "CMD_NEXT_DOC": "अगला डॉक्यूमेंट",
  "CMD_PREV_DOC": "पिछला डॉक्यूमेंट",
  "CMD_NAVIGATE_BACKWARD": "पीछे की ओर नेविगेट करें",
  "CMD_NAVIGATE_FORWARD": "फॉरवर्ड नेविगेट करें",
  "CMD_NEXT_DOC_LIST_ORDER": "सूची में अगला दस्तावेज़",
  "CMD_PREV_DOC_LIST_ORDER": "सूची में पिछला दस्तावेज़",
  "CMD_SHOW_IN_TREE": "फ़ाइल ट्री में दिखाएँ",
  "CMD_SHOW_IN_EXPLORER": "एक्सप्लोरर में दिखाएँ",
  "CMD_SHOW_IN_FINDER": "खोजक में दिखाएँ",
  "CMD_SHOW_IN_OS": "OS में दिखाएँ",
  "CMD_SWITCH_PANE_FOCUS": "फलक फोकस स्विच करें",
  "CMD_OPEN_VFS": "वर्चुअल फाइल सिस्टम खोलें",
  "CMD_OPEN_VIRTUAL_SERVER": "वर्चुअल सर्वर खोलें",
  "HELP_MENU": "हेल्प",
  "CMD_CHECK_FOR_UPDATE": "अपडेट के लिए जाँच करें",
  "CMD_HOW_TO_USE_BRACKETS": "{APP_NAME} का उपयोग कैसे करें",
  "CMD_SUPPORT": "{APP_NAME} सहायता",
  "CMD_SUGGEST": "एक विशेषता सुझाएं",
  "CMD_RELEASE_NOTES": "नोट्स जारी करें",
  "CMD_GET_INVOLVED": "शामिल हो जाओ",
  "CMD_SHOW_EXTENSIONS_FOLDER": "एक्सटेंशन फ़ोल्डर दिखाएँ",
  "CMD_HEALTH_DATA_STATISTICS": "हेल्थ रिपोर्ट",
  "CMD_HOMEPAGE": "{APP_NAME} होमपेज",
  "CMD_TWITTER": "{TWITTER_NAME} ट्विटर पे",
  "CMD_ABOUT": "{app_TITLE} के बारे में",
  "CMD_OPEN_PREFERENCES": "प्राथमिकता फ़ाइल खोलें",
  "CMD_OPEN_KEYMAP": "उपयोक्ता कुंजी मानचित्र खोलें",
  "EXPERIMENTAL_BUILD": "प्रायोगिक बिल्ड",
  "RELEASE_BUILD": "निर्माण",
  "DEVELOPMENT_BUILD": "विकास का निर्माण",
  "PRERELEASE_BUILD": "प्री-रिलीज़ बिल्ड",
  "RELOAD_FROM_DISK": "डिस्क से पुनः लोड करें",
  "KEEP_CHANGES_IN_EDITOR": "संपादक में परिवर्तन रखें",
  "CLOSE_DONT_SAVE": "बंद करें (सहेजें नहीं)",
  "RELAUNCH_CHROME": "Chrome को पुनः लॉन्च करें",
  "ABOUT": "के बारे में",
  "CLOSE": "बन्द करें",
  "ABOUT_TEXT_LINE1": "{VERSION_MAJOR} जारी करें। {संस्करण_माइनर} {बिल्ड_टाइप} {संस्करण}",
  "ABOUT_TEXT_BUILD_TIMESTAMP": "टाइमस्टैम्प बनाएं: ",
  "ABOUT_TEXT_LINE3": "हमारे द्वारा उपयोग की जाने वाली तृतीय पक्ष लाइब्रेरी - <a href='https://github.com/phcode-dev/phoenix/tree/main/src/thirdparty/licences'>लाइसेंस और एट्रिब्यूशन</a> ",
  "ABOUT_TEXT_LINE4": "<a href='https://github.com/phcode-dev/phoenix/'>https://github.com/phcode-dev/phoenix/ पर दस्तावेज़ीकरण और स्रोत</a>",
  "ABOUT_TEXT_LINE5": "❤ और जावास्क्रिप्ट के साथ बनाया गया:",
  "ABOUT_TEXT_LINE6": "बहुत सारे लोग (लेकिन हमें अभी उस डेटा को लोड करने में मुश्किल हो रही है)।",
  "ABOUT_TEXT_MDN_DOCS": "MDN डॉक्स और MDN ग्राफिकल लोगो को क्रिएटिव कॉमन्स एट्रिब्यूशन लाइसेंस, <a href='{MDN_DOCS_LICENSE}'>CC-BY-SA 2.5 अनपोर्टेड</a> के तहत लाइसेंस प्राप्त है।",
  "UPDATE_NOTIFICATION_TOOLTIP": "{APP_NAME} का एक नया निर्माण उपलब्ध है! विवरण के लिए यहां क्लिक करें।",
  "UPDATE_AVAILABLE_TITLE": "अपडेट उपलब्ध",
  "UPDATE_MESSAGE": "अरे, {APP_NAME} का एक नया निर्माण उपलब्ध है। यहां कुछ नई विशेषताएं दी गई हैं:",
  "GET_IT_NOW": "इसे अभी प्राप्त करें!",
  "PROJECT_SETTINGS_TITLE": "के लिए प्रोजेक्ट सेटिंग: {0}",
  "PROJECT_SETTING_BASE_URL": "लाइव पूर्वावलोकन बेस URL",
  "PROJECT_SETTING_BASE_URL_HINT": "स्थानीय सर्वर का उपयोग करने के लिए, http://localhost:8000/ जैसे URL दर्ज करें",
  "BASEURL_ERROR_INVALID_PROTOCOL": "{0} प्रोटोकॉल लाइव पूर्वावलोकन द्वारा समर्थित नहीं है—कृपया http: या https: का उपयोग करें।",
  "BASEURL_ERROR_SEARCH_DISALLOWED": "बेस यूआरएल में “{0}” जैसे खोज पैरामीटर नहीं हो सकते हैं।",
  "BASEURL_ERROR_HASH_DISALLOWED": "बेस यूआरएल में “{0}” जैसे हैश नहीं हो सकते।",
  "BASEURL_ERROR_INVALID_CHAR": "'{ 0} 'जैसे विशेष वर्ण %-encoded होने चाहिए।",
  "BASEURL_ERROR_UNKNOWN_ERROR": "बेस यूआरएल पार्स करने में अज्ञात त्रुटि",
  "EMPTY_VIEW_HEADER": "<em>इस फलक में फोकस होने पर फ़ाइल खोलें</em>",
  "FLIPVIEW_BTN_TOOLTIP": "इस दृश्य को {0} फलक पर फ़्लिप करें",
  "CURRENT_THEME": "मौज़ूदा थीम",
  "USE_THEME_SCROLLBARS": "प्रसंग स्क्रॉलबार का उपयोग करें",
  "FONT_SIZE": "फॉन्ट साइज़",
  "FONT_FAMILY": "फ़ॉन्ट फ़ैमिली",
  "THEMES_SETTINGS": "थीम्स सेटिंग",
  "BUTTON_NEW_RULE": "नया नियम",
  "INSTALL": "संस्थापित करें",
  "UPDATE": "अपडेट",
  "REMOVE": "हटाएँ",
  "DISABLE": "अक्षम करें",
  "ENABLE": "सक्षम करें",
  "OVERWRITE": "मिटाकर लिखें",
  "CANT_REMOVE_DEV": "“देव” फ़ोल्डर में एक्सटेंशन मैन्युअल रूप से हटाए जाने चाहिए।",
  "CANT_UPDATE": "अद्यतन {APP_NAME} के इस संस्करण के साथ संगत नहीं है।",
  "CANT_UPDATE_DEV": "“देव” फ़ोल्डर में एक्सटेंशन स्वचालित रूप से अपडेट नहीं किए जा सकते।",
  "INSTALL_EXTENSION_TITLE": "एक्सटेंशन इंस्टॉल करें",
  "UPDATE_EXTENSION_TITLE": "एक्सटेंशन अपडेट करें",
  "INSTALL_EXTENSION_LABEL": "एक्सटेंशन URL",
  "INSTALL_EXTENSION_HINT": "एक्सटेंशन की ज़िप फ़ाइल या GitHub रेपो का URL",
  "INSTALLING_FROM": "{0} से एक्सटेंशन इंस्टॉल किया जा रहा है...",
  "INSTALL_SUCCEEDED": "स्थापना सफल!",
  "INSTALL_FAILED": "स्थापना विफल।",
  "CANCELING_INSTALL": "रद्द किया जा रहा है...",
  "CANCELING_HUNG": "इंस्टॉल को रद्द करने में लंबा समय लग रहा है। एक आंतरिक त्रुटि हो सकती है।",
  "INSTALL_CANCELED": "स्थापना रद्द कर दी गई।",
  "VIEW_COMPLETE_DESCRIPTION": "पूरा विवरण देखें",
  "VIEW_TRUNCATED_DESCRIPTION": "छोटा किया गया विवरण देखें",
  "SORT_EXTENSION_METHOD": "डाउनलोडकाउंट या पब्लिशडेट का उपयोग करके एक्सटेंशन को सॉर्ट करें",
  "INVALID_ZIP_FILE": "डाउनलोड की गई सामग्री वैध ज़िप फ़ाइल नहीं है।",
  "MISSING_PACKAGE_JSON": "पैकेज में कोई package.json फ़ाइल नहीं है।",
  "INVALID_PACKAGE_JSON": "package.json फ़ाइल मान्य नहीं है (त्रुटि थी: {0})।",
  "MISSING_PACKAGE_NAME": "package.json फ़ाइल पैकेज नाम निर्दिष्ट नहीं करती है।",
  "BAD_PACKAGE_NAME": "{0} एक अवैध पैकेज नाम है।",
  "MISSING_PACKAGE_VERSION": "package.json फ़ाइल पैकेज संस्करण निर्दिष्ट नहीं करती है।",
  "INVALID_VERSION_NUMBER": "संकुल संस्करण क्रमांक ({0}) अमान्य है।",
  "INVALID_BRACKETS_VERSION": "{APP_NAME} संगतता स्ट्रिंग ({0}) अमान्य है।",
  "DISALLOWED_WORDS": "{0} फ़ील्ड में शब्द ({1}) की अनुमति नहीं है।",
  "NPM_INSTALL_FAILED": "npm इंस्टॉल कमांड विफल: {0}",
  "API_NOT_COMPATIBLE": "एक्सटेंशन {APP_NAME} के इस संस्करण के साथ संगत नहीं है। यह आपके अक्षम किए गए एक्सटेंशन फ़ोल्डर में इंस्टॉल किया गया है।",
  "MISSING_MAIN": "पैकेज में कोई main.js फ़ाइल नहीं है।",
  "EXTENSION_ALREADY_INSTALLED": "इस पैकेज को इंस्टॉल करने से पहले इंस्टॉल किए गए एक्सटेंशन को ओवरराइट कर दिया जाएगा। पुराने एक्सटेंशन को ओवरराइट करें?",
  "EXTENSION_SAME_VERSION": "यह पैकेज वही संस्करण है जो वर्तमान में स्थापित है। मौजूदा स्थापना को मिटाकर लिखें?",
  "EXTENSION_OLDER_VERSION": "यह पैकेज version {0} है जो वर्तमान में स्थापित ({1}) से पुराना है। मौजूदा स्थापना को मिटाकर लिखें?",
  "DOWNLOAD_ID_IN_USE": "आंतरिक त्रुटि: पहले से उपयोग में आईडी डाउनलोड करें।",
  "NO_SERVER_RESPONSE": "सर्वर से कनेक्ट नहीं हो सका।",
  "BAD_HTTP_STATUS": "फ़ाइल सर्वर पर नहीं मिली (HTTP {0})।",
  "CANNOT_WRITE_TEMP": "डाउनलोड को अस्थायी फ़ाइल में सहेजने में अक्षम।",
  "ERROR_LOADING": "प्रारंभ करते समय एक्सटेंशन में त्रुटि आई।",
  "MALFORMED_URL": "यूआरएल अमान्य है। कृपया जांचें कि आपने इसे सही तरीके से दर्ज किया है।",
  "UNSUPPORTED_PROTOCOL": "यूआरएल http या https यूआरएल होना चाहिए।",
  "UNKNOWN_ERROR": "अज्ञात आंतरिक त्रुटि।",
  "EXTENSION_MANAGER_TITLE": "एक्सटेंशन मैनेजर",
  "EXTENSION_MANAGER_ERROR_LOAD": "एक्सटेंशन रजिस्ट्री पर पहुँचने में अक्षम। कृपया बाद में पुन: प्रयास करें।",
  "INSTALL_EXTENSION_DRAG": ".zip को यहाँ खींचें या",
  "INSTALL_EXTENSION_DROP": "इंस्टॉल करने के लिए.zip ड्रॉप करें",
  "INSTALL_EXTENSION_DROP_ERROR": "निम्न त्रुटियों के कारण स्थापित/अद्यतन निरस्त किया गया:",
  "INSTALL_FROM_URL": "URL से इंस्टॉल करें...",
  "INSTALL_EXTENSION_VALIDATING": "मान्य किया जा रहा है...",
  "EXTENSION_AUTHOR": "लेखक",
  "EXTENSION_DATE": "तारीख़",
  "EXTENSION_INCOMPATIBLE_NEWER": "इस एक्सटेंशन के लिए {APP_NAME} के नए संस्करण की आवश्यकता है।",
  "EXTENSION_INCOMPATIBLE_OLDER": "यह एक्सटेंशन वर्तमान में केवल {APP_NAME} के पुराने संस्करणों के साथ काम करता है।",
  "EXTENSION_LATEST_INCOMPATIBLE_NEWER": "इस एक्सटेंशन के संस्करण {0} के लिए {APP_NAME} के नए संस्करण की आवश्यकता है। लेकिन आप पहले संस्करण {1} को इंस्टॉल कर सकते हैं।",
  "EXTENSION_LATEST_INCOMPATIBLE_OLDER": "इस एक्सटेंशन का Version {0} केवल {APP_NAME} के पुराने संस्करणों के साथ काम करता है। लेकिन आप पहले संस्करण {1} को इंस्टॉल कर सकते हैं।",
  "EXTENSION_NO_DESCRIPTION": "कोई विवरण नहीं",
  "EXTENSION_MORE_INFO": "और जानकारी...",
  "EXTENSION_ERROR": "एक्सटेंशन त्रुटि",
  "EXTENSION_KEYWORDS": "मुख्य शब्दों",
  "EXTENSION_TRANSLATED_USER_LANG": "आपकी सहित {0} भाषाओं में अनुवादित",
  "EXTENSION_TRANSLATED_GENERAL": "{0} भाषाओं में अनुवादित",
  "EXTENSION_TRANSLATED_LANGS": "इस एक्सटेंशन का इन भाषाओं में अनुवाद किया गया है: {0}",
  "EXTENSION_INSTALLED": "इंस्टॉल किया गया",
  "EXTENSION_UPDATE_INSTALLED": "यह एक्सटेंशन अपडेट डाउनलोड किया गया है और {APP_NAME} पुनः लोड होने के बाद इंस्टॉल किया जाएगा।",
  "EXTENSION_SEARCH_PLACEHOLDER": "खोजें",
  "EXTENSION_MORE_INFO_LINK": "मोरे",
  "BROWSE_EXTENSIONS": "एक्सटेंशन ब्राउज़ करें",
  "EXTENSION_MANAGER_REMOVE": "एक्सटेंशन हटाएँ",
  "EXTENSION_MANAGER_REMOVE_ERROR": "एक या अधिक एक्सटेंशन हटाने में अक्षम: {0}। {APP_NAME} अभी भी पुनः लोड होगा।",
  "EXTENSION_MANAGER_UPDATE": "एक्सटेंशन अपडेट करें",
  "EXTENSION_MANAGER_UPDATE_ERROR": "एक या अधिक एक्सटेंशन अपडेट करने में अक्षम: {0}। {APP_NAME} अभी भी पुनः लोड होगा।",
  "EXTENSION_MANAGER_DISABLE": "एक्सटेंशन को अक्षम करें",
  "EXTENSION_MANAGER_DISABLE_ERROR": "एक या अधिक एक्सटेंशन अक्षम करने में अक्षम: {0}। {APP_NAME} अभी भी पुनः लोड होगा।",
  "MARKED_FOR_REMOVAL": "हटाने के लिए चिह्नित",
  "UNDO_REMOVE": "पूर्ववत करें",
  "MARKED_FOR_UPDATE": "अपडेट के लिए चिह्नित",
  "UNDO_UPDATE": "पूर्ववत करें",
  "MARKED_FOR_DISABLING": "अक्षम करने के लिए चिह्नित",
  "UNDO_DISABLE": "पूर्ववत करें",
  "CHANGE_AND_RELOAD_TITLE": "एक्सटेंशन बदलें",
  "CHANGE_AND_RELOAD_MESSAGE": "चिह्नित एक्सटेंशन को अपडेट करने, हटाने या अक्षम करने के लिए, {APP_NAME} को फिर से लोड करना होगा। आपको बिना सहेजे गए परिवर्तनों को सहेजने के लिए कहा जाएगा।",
  "REMOVE_AND_RELOAD": "एक्सटेंशन निकालें और पुनः लोड करें",
  "CHANGE_AND_RELOAD": "एक्सटेंशन बदलें और पुनः लोड करें",
  "UPDATE_AND_RELOAD": "एक्सटेंशन अपडेट करें और पुनः लोड करें",
  "DISABLE_AND_RELOAD": "एक्सटेंशन अक्षम करें और पुनः लोड करें",
  "PROCESSING_EXTENSIONS": "एक्सटेंशन परिवर्तन संसाधित कर रहा है...",
  "EXTENSION_NOT_INSTALLED": "एक्सटेंशन {0} को हटा नहीं सका क्योंकि यह संस्थापित नहीं था।",
  "NO_EXTENSIONS": "अभी तक कोई एक्सटेंशन इंस्टॉल नहीं है। <br>आरंभ करने के लिए ऊपर दिए गए उपलब्ध टैब पर क्लिक करें।",
  "NO_EXTENSION_MATCHES": "कोई भी एक्सटेंशन आपकी खोज से मेल नहीं खाता।",
  "REGISTRY_SANITY_CHECK_WARNING": "नोट: ये एक्सटेंशन {APP_NAME} की तुलना में अलग-अलग लेखकों से आ सकते हैं। एक्सटेंशन की समीक्षा नहीं की जाती है और पूर्ण स्थानीय विशेषाधिकार होते हैं। किसी अज्ञात स्रोत से एक्सटेंशन इंस्टॉल करते समय सावधान रहें।",
  "EXTENSIONS_INSTALLED_TITLE": "इंस्टॉल किया गया",
  "EXTENSIONS_DEFAULT_TITLE": "डिफॉल्ट",
  "EXTENSIONS_AVAILABLE_TITLE": "उपलब्ध",
  "EXTENSIONS_THEMES_TITLE": "थीम्स",
  "EXTENSIONS_UPDATES_TITLE": "अपडेट्स",
  "EXTENSIONS_LAST_UPDATED": "आखरी अपडेट",
  "EXTENSIONS_DOWNLOADS": "डाउनलोड्स",
  "INLINE_EDITOR_NO_MATCHES": "कोई मेल उपलब्ध नहीं है।",
  "INLINE_EDITOR_HIDDEN_MATCHES": "सभी मैच ध्वस्त हो गए हैं। मिलान देखने के लिए दाईं ओर सूचीबद्ध फ़ाइलों का विस्तार करें।",
  "CSS_QUICK_EDIT_NO_MATCHES": "आपके चयन से मेल खाने वाले कोई मौजूदा CSS नियम नहीं हैं। <br>एक बनाने के लिए “नया नियम” पर क्लिक करें।",
  "CSS_QUICK_EDIT_NO_STYLESHEETS": "आपके प्रोजेक्ट में कोई स्टाइलशीट नहीं हैं। <br>CSS नियम जोड़ने के लिए एक बनाएँ।",
  "IMAGE_VIEWER_LARGEST_ICON": "विशालतम",
  "UNIT_PIXELS": "पिक्सल",
  "DEBUG_MENU": "डिबग",
  "ERRORS": "त्रुटियाँ",
  "CMD_SHOW_DEV_TOOLS": "डेवलपर टूल दिखाएं",
  "CMD_REFRESH_WINDOW": "एक्सटेंशन के साथ पुनः लोड करें",
  "CMD_RELOAD_WITHOUT_USER_EXTS": "एक्सटेंशन के बिना पुनः लोड करें",
  "CMD_NEW_BRACKETS_WINDOW": "नया {APP_NAME} विंडो",
  "CMD_LAUNCH_SCRIPT_MAC": "कमांड लाइन शॉर्टकट इंस्टॉल करें",
  "CMD_SWITCH_LANGUAGE": "भाषा स्विच करें",
  "CMD_RUN_UNIT_TESTS": "रन टेस्ट",
  "CMD_SHOW_PERF_DATA": "परफ़ॉर्मेंस डेटा दिखाएँ",
  "CMD_ENABLE_LOGGING": "विस्तृत लॉग सक्षम करें",
  "CMD_OPEN_BRACKETS_SOURCE": "{APP_NAME} स्रोत खोलें",
  "CREATING_LAUNCH_SCRIPT_TITLE": "{APP_NAME} कमांड लाइन शॉर्टकट",
  "ERROR_CREATING_LAUNCH_SCRIPT": "कमांड लाइन शॉर्टकट स्थापित करते समय एक त्रुटि हुई। कृपया <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting'>इन समस्या निवारण सुझावों को आज़माएँ</a>। <br/><br/>कारण: {0}",
  "ERROR_CLTOOLS_RMFAILED": "मौजूदा <code>/usr/local/bin/ब्रैकेट्स सिमलिंक</code> को मिटाने में असमर्थ।",
  "ERROR_CLTOOLS_MKDIRFAILED": "<code>/usr/local/bin</code> निर्देशिका बनाने में अक्षम।",
  "ERROR_CLTOOLS_LNFAILED": "<code>/usr/local/bin/ब्रैकेट्स सिमलिंक</code> बनाने में अक्षम।",
  "ERROR_CLTOOLS_SERVFAILED": "आंतरिक त्रुटि।",
  "ERROR_CLTOOLS_NOTSUPPORTED": "इस OS पर कमांड लाइन शॉर्टकट समर्थित नहीं है।",
  "LAUNCH_SCRIPT_CREATE_SUCCESS": "सफलता! अब आप कमांड लाइन से आसानी से {APP_NAME} लॉन्च कर सकते हैं: परियोजनाओं को स्विच करने के लिए फ़ाइल या <code>ब्रैकेट MyFolder खोलने के लिए <code>myFile.txt</code> कोष्ठक</code>। <br/><br/>कमांड लाइन से {APP_NAME} का उपयोग करने के बारे में और <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments'>जानें</a>।",
  "LANGUAGE_TITLE": "भाषा स्विच करें",
  "LANGUAGE_MESSAGE": "भाषा:",
  "LANGUAGE_SUBMIT": "{APP_NAME} पुनः लोड करें",
  "LANGUAGE_CANCEL": "रद्द करें",
  "LANGUAGE_SYSTEM_DEFAULT": "सिस्टम डिफॉल्ट",
  "HEALTH_DATA_NOTIFICATION": "स्वास्थ्य रिपोर्ट की प्राथमिकताएं",
  "HEALTH_FIRST_POPUP_TITLE": "{APP_NAME} स्वास्थ्य रिपोर्ट",
  "HEALTH_DATA_DO_TRACK": "मैं {APP_NAME} का उपयोग कैसे करता हूं, इस बारे में छद्म नाम जानकारी साझा करें",
  "HEALTH_DATA_NOTIFICATION_MESSAGE": "{APP_NAME} को बेहतर बनाने के लिए, हम समय-समय पर सीमित, <strong>छद्म</strong> नाम के आंकड़े core.ai को भेजते हैं कि आप {APP_NAME} का उपयोग कैसे करते हैं। यह जानकारी आपकी गोपनीयता की रक्षा करते हुए सुविधाओं को प्राथमिकता देने, बग ढूंढने और उपयोगिता संबंधी समस्याओं को पहचानने में मदद करती है। <br><br>आप <strong>मदद > स्वास्थ्य रिपोर्ट</strong> का चयन करके अपना डेटा देख सकते हैं या डेटा साझा नहीं करना चुन सकते हैं। <br><br>",
  "HEALTH_DATA_PREVIEW": "{APP_NAME} स्वास्थ्य रिपोर्ट",
  "HEALTH_DATA_PREVIEW_INTRO": "<p>{APP_NAME} को बेहतर बनाने के लिए, हम समय-समय पर सीमित, <strong>छद्म</strong> नाम के आंकड़े core.ai को भेजते हैं कि आप {APP_NAME} का उपयोग कैसे करते हैं। यह जानकारी सुविधाओं को प्राथमिकता देने, बग ढूंढने और उपयोगिता संबंधी समस्याओं को खोजने में मदद करती है। </p><p>नीचे उस डेटा का पूर्वावलोकन दिया गया है जिसे आपकी अगली स्वास्थ्य रिपोर्ट में भेजा जाएगा <em>यदि</em> वह सक्षम है। </p>",
  "INLINE_TIMING_EDITOR_TIME": "टाइम",
  "INLINE_TIMING_EDITOR_PROGRESSION": "प्रोग्रेशन",
  "BEZIER_EDITOR_INFO": "<kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd> चयनित बिंदु को स्थानांतरित करें <br><kbd class='text'>खिसक</kbd> जाना दस इकाइयों से आगे बढ़ें <br><kbd class='text'>टैब</kbd> स्विच पॉइंट्स",
  "STEPS_EDITOR_INFO": "<kbd>↑</kbd> <kbd>↓</kbd> चरणों को बढ़ाएं या घटाएं <br><kbd>←</kbd> <kbd>→</kbd> 'स्टार्ट' या 'एंड'",
  "INLINE_TIMING_EDITOR_INVALID": "पुराना मान <code>{0}</code> मान्य नहीं है, इसलिए प्रदर्शित फ़ंक्शन को <code>{1}</code> में बदल दिया गया था। दस्तावेज़ को पहले संपादन के साथ अपडेट किया जाएगा।",
  "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP": "मौज़ूदा रंग",
  "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP": "ओरिजिनल रंग",
  "COLOR_EDITOR_RGBA_BUTTON_TIP": "आरजीबीए फॉर्मेट",
  "COLOR_EDITOR_HEX_BUTTON_TIP": "हेक्स फॉर्मेट",
  "COLOR_EDITOR_HSLA_BUTTON_TIP": "एचएसएलए फॉर्मेट",
  "COLOR_EDITOR_0X_BUTTON_TIP": "हेक्स (0x) स्वरूप",
  "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR": "{0} (प्रयुक्त {1} समय)",
  "COLOR_EDITOR_USED_COLOR_TIP_PLURAL": "{0} ({1} बार इस्तेमाल किया गया)",
  "CMD_JUMPTO_DEFINITION": "जम्प टू डेफिनिशन",
  "CMD_SHOW_PARAMETER_HINT": "पैरामीटर संकेत दिखाएँ",
  "NO_ARGUMENTS": "<no parameters>",
  "DETECTED_EXCLUSION_TITLE": "[Javascript] जावास्क्रिप्ट फ़ाइल अनुमान समस्या",
  "DETECTED_EXCLUSION_INFO": "{APP_NAME} <span class='dialog-filename'>{0}</span> प्रसंस्करण में परेशानी में भाग गया। <br><br>इस फ़ाइल को अब कोड संकेत, जम्प टू डेफिनिशन या क्विक एडिट के लिए प्रोसेस नहीं किया जाएगा। इस फ़ाइल को पुनः सक्षम करने के लिए, अपनी प्रोजेक्ट <code>में.brackets.json</code> खोलें और <code>JScodeHints.detectedExclusions</code> संपादित करें। <br><br>यह संभवतः {APP_NAME} बग है। यदि आप इस फ़ाइल की एक प्रति प्रदान कर सकते हैं, तो कृपया यहां नामित <a href='https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue'>फ़ाइल के लिंक के साथ एक बग</a> दर्ज करें।",
  "CMD_REFACTOR": "रिफैक्टर",
  "CMD_EXTRACTTO_VARIABLE": "वेरिएबल में निकालें",
  "CMD_EXTRACTTO_FUNCTION": "कार्य करने के लिए निकालें",
  "ERROR_TERN_FAILED": "Tern से डेटा प्राप्त करने में असमर्थ",
  "ERROR_EXTRACTTO_VARIABLE_NOT_VALID": "चयन अभिव्यक्ति नहीं बनाता है",
  "ERROR_EXTRACTTO_FUNCTION_NOT_VALID": "चयनित ब्लॉक को कथन या अभिव्यक्ति के सेट का प्रतिनिधित्व करना चाहिए",
  "ERROR_EXTRACTTO_VARIABLE_MULTICURSORS": "वेरिएबल में निकालें मल्टीकर्सर्स में काम नहीं करता है",
  "ERROR_EXTRACTTO_FUNCTION_MULTICURSORS": "फंक्शन में निकालें मल्टीकर्सर्स में काम नहीं करता है",
  "EXTRACTTO_FUNCTION_SELECT_SCOPE": "डेस्टिनेशन स्कोप चुनें",
  "EXTRACTTO_VARIABLE_SELECT_EXPRESSION": "एक एक्सप्रेशन चुनें",
  "CMD_REFACTORING_RENAME": "नाम बदलें",
  "CMD_REFACTORING_TRY_CATCH": "रैप इन ट्राई कैच",
  "CMD_REFACTORING_CONDITION": "रैप इन कंडीशन",
  "CMD_REFACTORING_GETTERS_SETTERS": "गेटर्स/सेटर्स बनाएं",
  "CMD_REFACTORING_ARROW_FUNCTION": "एरो फंक्शन में कनवर्ट करें",
  "DESCRIPTION_CODE_REFACTORING": "जावास्क्रिप्ट कोड रिफैक्टरिंग सक्षम/अक्षम करें",
  "ERROR_TRY_CATCH": "Try-catch ब्लॉक में लपेटने के लिए वैध कोड चुनें",
  "ERROR_WRAP_IN_CONDITION": "कंडीशन ब्लॉक में रैप करने के लिए वैध कोड चुनें",
  "ERROR_ARROW_FUNCTION": "कर्सर को फ़ंक्शन एक्सप्रेशन के अंदर रखें",
  "ERROR_GETTERS_SETTERS": "कर्सर को ऑब्जेक्ट एक्सप्रेशन के सदस्य पर रखें",
  "ERROR_RENAME_MULTICURSOR": "बहु-कर्सर का उपयोग करते समय नाम बदल नहीं सकता",
  "ERROR_RENAME_QUICKEDIT": "इस पहचानकर्ता का नाम बदल नहीं सकते हैं, क्योंकि इसे इस फ़ंक्शन के बाहर कहीं और संदर्भित किया गया है",
  "ERROR_RENAME_GENERAL": "चुने गए पाठ का नाम बदल नहीं सकता",
  "JSLINT_NAME": "जेएसलिंट",
  "CMD_ENABLE_QUICK_VIEW": "होवर पर त्वरित दृश्य",
  "CMD_TOGGLE_RECENT_PROJECTS": "हालिया परियोजनाएँ",
  "DOCS_MORE_LINK": "और पढ़ें",
  "COLLAPSE_ALL": "सभी को संकुचित करें",
  "EXPAND_ALL": "सभी को विस्तृत करें",
  "COLLAPSE_CURRENT": "वर्तमान को संकुचित करें",
  "EXPAND_CURRENT": "वर्तमान का विस्तार करें",
  "RECENT_FILES_DLG_HEADER": "हाल की फाइलें",
  "RECENT_FILES_DLG_CLEAR_BUTTON_LABEL": "क्लियर",
  "RECENT_FILES_DLG_CLEAR_BUTTON_TITLE": "कार्यशील सेट में नहीं फ़ाइलें साफ़ करें",
  "DESCRIPTION_CLOSE_BRACKETS": "ब्रेसिज़, ब्रैकेट और कोष्ठक को स्वचालित रूप से बंद करने के लिए सही है",
  "DESCRIPTION_CLOSE_OTHERS_ABOVE": "वर्किंग फाइल संदर्भ मेनू से “ऊपर दूसरों को बंद करें” को हटाने के लिए गलत",
  "DESCRIPTION_CLOSE_OTHERS_BELOW": "वर्किंग फाइल संदर्भ मेनू से “नीचे दूसरों को बंद करें” को हटाने के लिए गलत",
  "DESCRIPTION_CLOSE_OTHERS": "वर्किंग फाइल संदर्भ मेनू से “दूसरों को बंद करें” को हटाने के लिए गलत",
  "DESCRIPTION_CLOSE_TAGS": "टैग बंद करने के विकल्प सेट करता है",
  "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS": "टैग की एक सरणी जिसे स्वतः बंद नहीं किया जाना चाहिए",
  "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING": "बंद करें जब> टैग खोलने का टाइप किया गया है",
  "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING": "बन्द करें जब/बन्द करने वाला टैग टाइप किया गया हो",
  "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS": "टैग की एक सरणी जो खोले जाने पर रिक्त रेखा होती है",
  "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD": "इंडेंट स्तर में परिवर्तन होने पर हमेशा ढहने योग्य अनुभाग मार्कर उत्पन्न करने के लिए सच है",
  "DESCRIPTION_CODE_FOLDING_ENABLED": "कोड फोल्डिंग को सक्षम करने के लिए सच है",
  "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER": "जब आप माउस को गटर पर ले जाते हैं तो सेक्शन-कॉलिंग मार्कर केवल तभी दिखाई देते हैं",
  "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL": "सीमित करता है कि कितने स्तर गहरे संकुचित करें सभी लागू होते हैं",
  "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE": "खुलने योग्य अनुभाग आइकन प्रकट होने से पहले न्यूनतम पंक्तियाँ",
  "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES": "यदि आप किसी फ़ाइल या प्रोजेक्ट को बंद और फिर से खोलते हैं तो ढह गए वर्गों को याद रखने के लिए सही है",
  "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE": "संपादक में चयनित पाठ पर कोड फोल्डिंग को सक्षम करने के लिए true",
  "DESCRIPTION_DISABLED_DEFAULT_EXTENSIONS": "डिफ़ॉल्ट एक्सटेंशन जो अक्षम हैं",
  "DESCRIPTION_ATTR_HINTS": "HTML विशेषता संकेत सक्षम/अक्षम करें",
  "DESCRIPTION_CSS_PROP_HINTS": "सीएसएस/कम/एससीएसएस संपत्ति संकेतों को सक्षम/अक्षम करें",
  "DESCRIPTION_JS_HINTS": "जावास्क्रिप्ट कोड संकेतों को सक्षम/अक्षम करें",
  "DESCRIPTION_JS_HINTS_TYPE_DETAILS": "जावास्क्रिप्ट कोड संकेतों में डेटाटाइप विवरण सक्षम/अक्षम करें",
  "DESCRIPTION_PREF_HINTS": "प्राथमिकता कोड संकेत सक्षम/अक्षम करें",
  "DESCRIPTION_SPECIAL_CHAR_HINTS": "HTML इकाई संकेतों को सक्षम/अक्षम करें",
  "DESCRIPTION_SVG_HINTS": "एसवीजी कोड संकेतों को सक्षम/अक्षम करें",
  "DESCRIPTION_HTML_TAG_HINTS": "HTML टैग संकेत सक्षम/अक्षम करें",
  "DESCRIPTION_URL_CODE_HINTS": "एचटीएमएल और सीएसएस/कम/एससीएसएस में यूआरएल संकेतों को सक्षम/अक्षम करें",
  "DESCRIPTION_DRAG_DROP_TEXT": "ड्रैग एंड ड्रॉप कार्यक्षमता सक्षम/अक्षम करें",
  "DESCRIPTION_HEALTH_DATA_TRACKING": "हेल्थ डेटा ट्रैकिंग सक्षम करें",
  "DESCRIPTION_HIGHLIGHT_MATCHES": "पूरे दस्तावेज़ में मिलान स्ट्रिंग के स्वचालित हाइलाइटिंग को सक्षम करता है",
  "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN": "कर्सर वर्तमान में टोकन से मेल खाने वाले सभी तारों को हाइलाइट करें (कोई चयन आवश्यक नहीं है)",
  "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY": "केवल तभी हाइलाइट करें जब चयन पूर्ण टोकन हो",
  "DESCRIPTION_INSERT_HINT_ON_TAB": "टैब पर वर्तमान में चयनित कोड संकेत डालने के लिए सही है",
  "DESCRIPTION_NO_HINTS_ON_DOT": "टाइप किए जाने पर जेएस कोड संकेत स्वचालित रूप से दिखाने के लिए सही नहीं है",
  "DESCRIPTION_JSLINT_OPTIONS": "JSLint के लिए डिफ़ॉल्ट विकल्प वाला एक ऑब्जेक्ट",
  "DESCRIPTION_JSLINT_OPTIONS_ASS": "असाइनमेंट अभिव्यक्तियों को अनुमति देने के लिए सही",
  "DESCRIPTION_JSLINT_OPTIONS_BITWISE": "बिटवाई ऑपरेटरों को अनुमति देने के लिए सच है",
  "DESCRIPTION_JSLINT_OPTIONS_BROWSER": "सच है अगर मानक ब्राउज़र ग्लोबल्स को पूर्वनिर्धारित किया जाना चाहिए",
  "DESCRIPTION_JSLINT_OPTIONS_CLOSURE": "Google क्लोजर मुहावरों को अनुमति देने के लिए सही है",
  "DESCRIPTION_JSLINT_OPTIONS_CONTINUE": "“जारी रखें” कथन की अनुमति देने के लिए सही है",
  "DESCRIPTION_JSLINT_OPTIONS_COUCH": "सच है अगर कॉच डीबी ग्लोबल्स को पूर्वनिर्धारित किया जाना चाहिए",
  "DESCRIPTION_JSLINT_OPTIONS_DEBUG": "डीबगर स्टेटमेंट की अनुमति देने के लिए सही है",
  "DESCRIPTION_JSLINT_OPTIONS_DEVEL": "सच है अगर विकास में उपयोगी ब्राउज़र ग्लोबल्स पूर्वनिर्धारित होना चाहिए",
  "DESCRIPTION_JSLINT_OPTIONS_EQEQ": "== और! =",
  "DESCRIPTION_JSLINT_OPTIONS_ES6": "सच है अगर ES6 ग्लोबल्स को पूर्वनिर्धारित किया जाना चाहिए",
  "DESCRIPTION_JSLINT_OPTIONS_EVIL": "eval अनुमति देने के लिए सच है",
  "DESCRIPTION_JSLINT_OPTIONS_FORIN": "अनफ़िल्टर्ड “के लिए... इन” की अनुमति देने के लिए सही",
  "DESCRIPTION_JSLINT_OPTIONS_INDENT": "एक विशिष्ट टैब चौड़ाई सेट करें",
  "DESCRIPTION_JSLINT_OPTIONS_MAXERR": "चेतावनियों की अधिकतम संख्या बताई गई",
  "DESCRIPTION_JSLINT_OPTIONS_MAXLEN": "एक पंक्ति में वर्णों की अधिकतम संख्या",
  "DESCRIPTION_JSLINT_OPTIONS_NEWCAP": "गैर-पूंजीकृत कन्स्ट्रक्टर को अनुमति देने के लिए सच है",
  "DESCRIPTION_JSLINT_OPTIONS_NODE": "सच है अगर Node.js ग्लोबल्स को पूर्वनिर्धारित किया जाना चाहिए",
  "DESCRIPTION_JSLINT_OPTIONS_NOMEN": "पहचानकर्ताओं में अंडरस्कोर लटकने की अनुमति देने के लिए सच है",
  "DESCRIPTION_JSLINT_OPTIONS_PASSFAIL": "पहली त्रुटि पर रुकने के लिए सच है",
  "DESCRIPTION_JSLINT_OPTIONS_PLUSPLUS": "++ और — की अनुमति देने के लिए सही है",
  "DESCRIPTION_JSLINT_OPTIONS_REGEXP": "और [^...]। RegExp में",
  "DESCRIPTION_JSLINT_OPTIONS_RHINO": "सच है अगर राइनो ग्लोबल्स को पूर्वनिर्धारित किया जाना चाहिए",
  "DESCRIPTION_JSLINT_OPTIONS_SLOPPY": "लापता `strict` pragma का उपयोग करने की अनुमति देने के लिए सच है",
  "DESCRIPTION_JSLINT_OPTIONS_STUPID": "true अगर अवरुद्ध ('... Sync') विधियों का उपयोग किया जा सकता है।",
  "DESCRIPTION_JSLINT_OPTIONS_SUB": "अक्षम सबस्क्रिप्टिंग की अनुमति देने के लिए सच है",
  "DESCRIPTION_JSLINT_OPTIONS_TODO": "TODO टिप्पणियों की अनुमति देने के लिए true",
  "DESCRIPTION_JSLINT_OPTIONS_UNPARAM": "अप्रयुक्त पैरामीटर की अनुमति देने के लिए सही है",
  "DESCRIPTION_JSLINT_OPTIONS_VARS": "फ़ंक्शन में 1 से अधिक वर्णों की अनुमति देने के लिए सही है",
  "DESCRIPTION_JSLINT_OPTIONS_WHITE": "व्हाइट-स्पेस नियमों को अनदेखा करने के लिए सच है",
  "DESCRIPTION_LANGUAGE": "भाषा विशिष्ट सेटिंग",
  "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS": "फ़ाइल एक्सटेंशन से भाषा के नाम पर अतिरिक्त मैपिंग",
  "DESCRIPTION_LANGUAGE_FILE_NAMES": "फ़ाइल नाम से भाषा के नाम पर अतिरिक्त मैपिंग",
  "DESCRIPTION_LINEWISE_COPY_CUT": "जब कोई चयन नहीं होता है तो copy और cut करना उन पूरी लाइनों को कॉपी या कट करेगा जिनमें कर्सर हैं",
  "DESCRIPTION_INPUT_STYLE": "CodeMirror इनपुट और फ़ोकस को संभालने के तरीके का चयन करता है। यह textarea हो सकता है, जो डिफ़ॉल्ट है, या contenteditable जो स्क्रीन रीडर (अस्थिर) के लिए बेहतर है",
  "DESCRIPTION_LINTING_ENABLED": "कोड निरीक्षण को सक्षम करने के लिए सही",
  "DESCRIPTION_ASYNC_TIMEOUT": "मिलीसेकंड में समय जिसके बाद एसिंक्रोनस लिंटर्स का समय समाप्त हो जाता है",
  "DESCRIPTION_LINTING_PREFER": "पहले चलाने के लिए लिंटर्स की सरणी",
  "DESCRIPTION_LIVE_DEV_MULTIBROWSER": "प्रयोगात्मक लाइव पूर्वावलोकन को सक्षम करने के लिए सही है",
  "DESCRIPTION_USE_PREFERED_ONLY": "linting.prefer में निर्दिष्ट प्रदाताओं को चलाने के लिए सही है",
  "DESCRIPTION_MAX_CODE_HINTS": "अधिकतम कोड संकेत एक बार में प्रदर्शित होते हैं",
  "DESCRIPTION_PATH": "पथ विशिष्ट सेटिंग",
  "DESCRIPTION_PROXY": "एक्सटेंशन इंस्टॉलेशन के लिए उपयोग किए जाने वाले प्रॉक्सी सर्वर का URL",
  "DESCRIPTION_SCROLL_PAST_END": "दस्तावेज़ के अंत से परे स्क्रॉलिंग को सक्षम करने के लिए true",
  "DESCRIPTION_SHOW_CODE_HINTS": "सभी कोड संकेतों को अक्षम करने के लिए गलत",
  "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING": "पाठ चयन होने पर ब्लिंकिंग कर्सर को दृश्यमान रखता है",
  "DESCRIPTION_SHOW_LINE_NUMBERS": "कोड के बाईं ओर “गटर” में लाइन नंबर दिखाने के लिए सही है",
  "DESCRIPTION_SMART_INDENT": "नया ब्लॉक बनाते समय स्वचालित रूप से इंडेंट करें",
  "DESCRIPTION_SOFT_TABS": "मुलायम टैब व्यवहार को बंद करने के लिए गलत",
  "DESCRIPTION_SORT_DIRECTORIES_FIRST": "प्रोजेक्ट ट्री में पहले निर्देशिकाओं को सॉर्ट करने के लिए सही है",
  "DESCRIPTION_SPACE_UNITS": "स्थान-आधारित इंडेंटेशन के लिए उपयोग करने के लिए रिक्त स्थान की संख्या",
  "DESCRIPTION_STATIC_SERVER_PORT": "पोर्ट संख्या जिसे अंतर्निहित सर्वर को लाइव पूर्वावलोकन के लिए उपयोग करना चाहिए",
  "DESCRIPTION_STYLE_ACTIVE_LINE": "कर्सर चालू होने वाली रेखा के पृष्ठभूमि रंग को हाइलाइट करने के लिए सही है",
  "DESCRIPTION_TAB_SIZE": "टैब के लिए प्रदर्शित करने के लिए रिक्त स्थान की संख्या",
  "DESCRIPTION_USE_TAB_CHAR": "रिक्त स्थान के बजाय टैब का उपयोग करने के लिए सही है",
  "DESCRIPTION_UPPERCASE_COLORS": "इनलाइन रंग संपादक में अपरकेस हेक्स रंग उत्पन्न करने के लिए सच है",
  "DESCRIPTION_WORD_WRAP": "व्यूपोर्ट चौड़ाई से अधिक पंक्तियां लपेटें",
  "DESCRIPTION_SEARCH_AUTOHIDE": "जैसे ही संपादक केंद्रित होता है, खोज बंद कर दें",
  "DESCRIPTION_DETECTED_EXCLUSIONS": "टर्न के नियंत्रण से बाहर होने के कारण पाई गई फ़ाइलों की एक सूची",
  "DESCRIPTION_INFERENCE_TIMEOUT": "फ़ाइलों को समझने की कोशिश करते समय टर्न का समय समाप्त हो जाएगा",
  "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR": "स्टेटस बार में त्रुटियों को दिखाने के लिए सही है",
  "DESCRIPTION_QUICK_VIEW_ENABLED": "त्वरित दृश्य को सक्षम करने के लिए सही है",
  "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW": "अनुपलब्ध एक्सटेंशन यूआरएल के लिए छवि पूर्वावलोकन दिखाने के लिए सही है",
  "DESCRIPTION_THEME": "{APP_NAME} प्रसंग चुनें",
  "DESCRIPTION_USE_THEME_SCROLLBARS": "कस्टम स्क्रॉल बार की अनुमति देने के लिए सही है",
  "DESCRIPTION_LINTING_COLLAPSED": "लाइनिंग पैनल को पतन करने के लिए सच है",
  "DESCRIPTION_FONT_FAMILY": "फ़ॉन्ट परिवार बदलें",
  "DESCRIPTION_FONT_SIZE": "फ़ॉन्ट आकार बदलें; उदाहरण के लिए 13px",
  "DESCRIPTION_FIND_IN_FILES_NODE": "नोड आधारित खोज को सक्षम करने के लिए सही",
  "DESCRIPTION_FIND_IN_FILES_INSTANT": "तत्काल खोज को सक्षम करने के लिए सही",
  "DESCRIPTION_FONT_SMOOTHING": "मैक-ओनली: ग्रे स्केल एंटीअलाइजिंग के लिए उप-पिक्सेल एंटीएलियासिंग या “एंटीअलाइज्ड” को सक्षम करने के लिए “सबपिक्सेल-एंटीअलाइज्ड”",
  "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW": "विभाजन दृश्य में खोलने की प्राथमिकता फ़ाइल को अक्षम करने के लिए गलत",
  "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE": "बाएं/शीर्ष फलक में उपयोगकर्ता वरीयता फ़ाइल खोलने के लिए गलत",
  "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED": "फलक हेडर क्लोज बटन के माध्यम से फलक से अंतिम फ़ाइल बंद होने के बाद पैन को पतन करने के लिए सही है",
  "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS": "हेडर पर क्लोज और फ्लिप-व्यू बटन दिखाने के लिए टॉगल करें।",
  "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT": "/*\n * यह केवल पढ़ने योग्य फ़ाइल है जिसमें वरीयताएँ समर्थित हैं\n * {APP_NAME} द्वारा।\n * अपनी प्राथमिकताओं को संशोधित करने के लिए इस फ़ाइल को संदर्भ के रूप में उपयोग करें\n * फ़ाइल “brackets.json” दूसरे फलक में खोला गया।\n * अंदर वरीयताओं का उपयोग करने के तरीके के बारे में अधिक जानकारी के लिए\n * {APP_NAME}, https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences पर वेब पेज देखें\n */",
  "DEFAULT_PREFERENCES_JSON_DEFAULT": "डिफॉल्ट",
  "DESCRIPTION_PURE_CODING_SURFACE": "कोड केवल मोड को सक्षम करने और {APP_NAME} में अन्य सभी UI तत्वों को छिपाने के लिए true",
  "DESCRIPTION_INDENT_LINE_COMMENT": "लाइन टिप्पणियों के इंडेंटिंग को सक्षम करने के लिए true",
  "DESCRIPTION_RECENT_FILES_NAV": "हाल की फाइलों में नेविगेशन सक्षम/अक्षम करें",
  "DESCRIPTION_LIVEDEV_WEBSOCKET_PORT": "पोर्ट जिस पर WebSocket सर्वर लाइव पूर्वावलोकन के लिए चलता है",
  "DESCRIPTION_LIVE_DEV_HIGHLIGHT_SETTINGS": "लाइव पूर्वावलोकन हाइलाइट सेटिंग्स",
  "DESCRIPTION_LIVEDEV_ENABLE_REVERSE_INSPECT": "लाइव पूर्वावलोकन रिवर्स निरीक्षण को अक्षम करने के लिए गलत",
  "DOWNLOAD_FAILED": "डाउनलोड असफल।",
  "DOWNLOAD_COMPLETE": "पूरा डाउनलोड करें!",
  "UPDATE_SUCCESSFUL": "अपडेट सफल!",
  "UPDATE_FAILED": "अपडेट विफल हुआ!",
  "VALIDATION_FAILED": "वेलिडेशन असफल!",
  "INITIALISATION_FAILED": "आरंभीकरण विफल रहा!",
  "CLEANUP_FAILED": "क्लीन-अप विफल!",
  "WARNING_TYPE": "चेतावनी!",
  "CLICK_RESTART_TO_UPDATE": "ब्रैकेट्स को अपडेट करने के लिए पुनरारंभ करें क्लिक करें",
  "UPDATE_ON_NEXT_LAUNCH": "अपडेट को फिर से लॉन्च करने पर लागू किया जाएगा।",
  "GO_TO_SITE": "पुनः प्रयास करने के लिए <a href = \"http://brackets.io/ “> ब्रैकेट्स. आईओ</a> पर जाएं।",
  "INTERNET_UNAVAILABLE": "कोई इंटरनेट कनेक्शन उपलब्ध नहीं है।",
  "UPDATEDIR_READ_FAILED": "अद्यतन निर्देशिका पढ़ा नहीं जा सका।",
  "UPDATEDIR_CLEAN_FAILED": "अद्यतन निर्देशिका को साफ नहीं किया जा सका।",
  "INITIAL_DOWNLOAD": "अपडेट डाउनलोड हो रहा है...",
  "RETRY_DOWNLOAD": "डाउनलोड असफल। पुनः प्रयास कर रहे हैं... प्रयास ",
  "VALIDATING_INSTALLER": "पूरा डाउनलोड करें! इंस्टॉलर सत्यापित कर रहा है...",
  "CHECKSUM_DID_NOT_MATCH": "चेकसम मेल नहीं खाता था।",
  "INSTALLER_NOT_FOUND": "इंस्टॉलर नहीं मिला।",
  "DOWNLOAD_ERROR": "डाउनलोड करते समय त्रुटि हुई।",
  "NETWORK_SLOW_OR_DISCONNECTED": "नेटवर्क डिस्कनेक्ट हो गया है या बहुत धीमा है।",
  "RESTART_BUTTON": "पुनः आरंभ करें",
  "LATER_BUTTON": "बाद में",
  "DESCRIPTION_AUTO_UPDATE": "ब्रैकेट्स ऑटो-अपडेट को सक्षम/अक्षम करें",
  "AUTOUPDATE_ERROR": "ग़लती!",
  "AUTOUPDATE_IN_PROGRESS": "एक अपडेट पहले से ही प्रगति पर है।",
  "NUMBER_WITH_PERCENTAGE": "{0}%",
  "CMD_FIND_RELATED_FILES": "सम्बंधित फ़ाइलें ढूँढें",
  "PHP_VERSION_INVALID": "PHP संस्करण पार्स करने में त्रुटि। कृपया “php —version” कमांड के आउटपुट की जांच करें।",
  "PHP_UNSUPPORTED_VERSION": "PHP से संबंधित टूलिंग जैसे कोड संकेत, पैरामीटर संकेत, परिभाषा पर जाएं और अधिक सक्षम करने के लिए PHP7 रनटाइम स्थापित करें। संस्करण मिला: {0}",
  "PHP_EXECUTABLE_NOT_FOUND": "PHP रनटाइम नहीं मिला। PHP7 रनटाइम स्थापित करें और PHP प्राथमिकताओं में “ExecutablePath” को उचित रूप से अपडेट करें। यह PHP से संबंधित टूलिंग जैसे कोड संकेत, पैरामीटर संकेत, जंप टू डेफिनिशन और बहुत कुछ सक्षम करता है।",
  "PHP_PROCESS_SPAWN_ERROR": "PHP प्रक्रिया शुरू करते समय त्रुटि कोड {0} का सामना करना पड़ा।",
  "PHP_SERVER_ERROR_TITLE": "एरर",
  "PHP_SERVER_MEMORY_LIMIT_INVALID": "आपके द्वारा प्रदत्त स्मृति सीमा अमान्य है। सही मान सेट करने के लिए PHP प्राथमिकताओं की समीक्षा करें।",
  "DESCRIPTION_PHP_TOOLING_CONFIGURATION": "PHP टूलिंग डिफ़ॉल्ट कॉन्फ़िगरेशन सेटिंग्स",
  "OPEN_PREFERENNCES": "प्राथमिकताएं खोलें",
  "LANGUAGE_TOOLS_PREFERENCES": "भाषा टूल के लिए प्राथमिकताएं",
  "FIND_ALL_REFERENCES": "सभी सन्दर्भ ढूँढें",
  "REFERENCES_IN_FILES": "संदर्भों",
  "REFERENCE_IN_FILES": "संदर्भ",
  "REFERENCES_NO_RESULTS": "वर्तमान कर्सर स्थिति के लिए कोई संदर्भ उपलब्ध नहीं है",
  "CMD_FIND_DOCUMENT_SYMBOLS": "दस्तावेज़ चिह्न ढूँढें",
  "CMD_FIND_PROJECT_SYMBOLS": "प्रोजेक्ट सिंबल खोजें",
  "REMOTE_DEBUGGING_ENABLED": "लोकलहोस्ट पर रिमोट डीबगिंग सक्षम है:",
  "REMOTE_DEBUGGING_PORT_INVALID": "port {0} पर दूरस्थ डिबगिंग सक्षम नहीं कर सका। पोर्ट संख्या {1} और {2} के बीच होनी चाहिए।",
  "DESCRIPTION_EXTERNAL_APPLICATION_ASSOCIATE": "बाहरी अनुप्रयोगों के लिए फ़ाइल एक्सटेंशन के लिए मैपिंग। सिंटेक्स: \"<file_type>“: “<default|ApplicationName|ApplicationPath>”, फ़ाइल प्रकार के लिए सिस्टम डिफ़ॉल्ट अनुप्रयोग में फ़ाइलों को खोलने के लिए “डिफ़ॉल्ट” का उपयोग करें।",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_TITLE": "बाहरी संपादकों में ग्राफिक फ़ाइलें खोलें।",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_MSG": "आपके मौजूदा फ़ोल्डर में ग्राफ़िक फ़ाइल प्रकार हैं जो {APP_NAME} के द्वारा समर्थित नहीं हैं। <br/>अब आप विशिष्ट फ़ाइल प्रकारों को बाहरी संपादकों के साथ जोड़ सकते हैं। एक बार जुड़े होने के बाद, आप फ़ाइल ट्री में फ़ाइलों पर डबल क्लिक करके अपने डिफ़ॉल्ट अनुप्रयोगों में.xd, .psd, .jpg, .png, .ai, .svg जैसी ग्राफिक फाइलें खोल सकते हैं। <br/><br/>ग्राफिक फ़ाइल प्रकारों को उनके संबंधित डिफ़ॉल्ट अनुप्रयोगों के साथ जोड़ने के लिए कृपया 'ओके' बटन पर क्लिक करें।",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_CNF_MSG": "निम्न फ़ाइल प्रकारों को डिफ़ॉल्ट अनुप्रयोगों के साथ सफलतापूर्वक संबद्ध किया गया है। <br/>{0} आपके पास “डीबग-> ओपन वरीयता फ़ाइल” मेनू पर जाकर कोष्ठक. जेसन में नई फ़ाइल प्रकार संघों को हटाने/जोड़ने पर अपनी वरीयता बदलने का विकल्प है।",
  "UNSUPPORTED_BROWSER": "ब्राउज़र समर्थित नहीं है",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER": "ब्राउज़र खुले फ़ोल्डर का समर्थन नहीं करता है",
  "UNSUPPORTED_BROWSER_MESSAGE_LINE1": "कृपया नीचे दिए गए समर्थित ब्राउज़रों में से एक का उपयोग करें।",
  "UNSUPPORTED_BROWSER_MESSAGE_LINE2": " हम फीनिक्स को और अधिक ब्राउज़रों में उपलब्ध कराने के लिए कड़ी मेहनत कर रहे हैं। आप इस संवाद को बंद कर सकते हैं, लेकिन Phoenix में कुछ सुविधाएँ इस ब्राउज़र में काम नहीं करेंगी।",
  "CANNOT_PUBLISH_LARGE_PROJECT": "बड़ी परियोजना प्रकाशित नहीं कर सकता",
  "CANNOT_PUBLISH_LARGE_PROJECT_MESSAGE": "फीनिक्स अभी भी प्रायोगिक अल्फा में है। हमने अभी तक 500 से अधिक फाइलों के साथ परियोजनाओं के सिंक को सक्षम नहीं किया है।",
  "SHARE_WEBSITE": "वेबसाइट प्रकाशित करें और साझा करें?",
  "PUBLISH": "प्रकाशित करें",
  "PUBLISH_CONSENT_MESSAGE": "परिवर्तनों का तुरंत पूर्वावलोकन करें और अपनी वेबसाइट को दूसरों के साथ साझा करें। फीनिक्स आपके लिए इस वेबसाइट को {0} पर प्रकाशित कर सकता है। प्रकाशित लिंक 7 दिनों की अवधि के लिए मान्य होंगे। </br>क्या आप अपनी वेबसाइट प्रकाशित और साझा करना चाहते हैं?",
  "PUBLISH_SYNC_IN_PROGRESS": "पूर्वावलोकन के लिए सिंक प्रगति पर है...",
  "PUBLISH_PAGE": "इस साइट को प्रकाशित करने और साझा करने के लिए क्लिक करें",
  "PUBLISH_VIEW_PAGE": "प्रकाशित पृष्ठ देखने के लिए क्लिक करें",
  "MISSING_FIELDS": "मिसिंग फील्ड्स",
  "PLEASE_FILL_ALL_REQUIRED": "कृपया लाल रंग में हाइलाइट किए गए सभी आवश्यक फ़ील्ड भरें",
  "CODE_EDITOR": "कोड एडिटर",
  "BUILD_THE_WEB": "वेब का निर्माण करें",
  "IMPORT_PROJECT": "परियोजना आयात करें",
  "GITHUB_PROJECT": "गीथूब प्रोजेक्ट",
  "NEW_PROJECT_FROM_GITHUB": "गीथूब की ओर से नई परियोजनाएं",
  "GITHUB_REPO_URL": "गीथूब रेपो यूआरएल:",
  "CREATE_PROJECT": "प्रोजेक्ट बनाएं",
  "SETTING_UP_PROJECT": "प्रोजेक्ट सेट अप करना",
  "LOCATION": "लोकेशन:",
  "DOWNLOADING": "डाउनलोडिंग...",
  "DOWNLOAD_FAILED_MESSAGE": "सुनिश्चित करें कि डाउनलोड URL वैध है। </br>एनबी: जैसा कि फीनिक्स अल्फा में है, 25 एमबी से बड़े निजी रिपोस और गिथब यूआरएल की अनुमति नहीं है।",
  "PLEASE_SELECT_A_FOLDER": "कृपया एक फोल्डर चुनें...",
  "UNZIP_IN_PROGRESS": "फ़ाइलों को अनजिप कर रहा है...",
  "UNZIP_FAILED": "त्रुटि: अनजिप करने में असफल।",
  "CONFIRM_REPLACE_TITLE": "बदलने की पुष्टि करें",
  "KEEP_BOTH": "दोनों को रखें",
  "EXPLORE": "एचटीएमएल गेम्स",
  "BLOG": "ब्लॉग",
  "PHOENIX_DEFAULT_PROJECT": "डिफ़ॉल्ट प्रोजेक्ट",
  "PROJECT_NAME": "प्रोजेक्ट का नाम:",
  "NEW_HTML": "नया HTML प्रोजेक्ट",
  "LICENSE": "लाइसेंस:",
  "CREDITS": "क्रेडिट्स:",
  "PREVIEW": "पूर्वावलोकन",
  "BUILD_WEBSITE": "वेबसाइट बनाएं",
  "VIEW_MORE": "और देखें...",
  "NEW_PROJECT_NOTIFICATION": "नया प्रोजेक्ट<br/> बनाने के लिए इस आइकन पर क्लिक करें। </br><a href='#' style='float:right;'>ठीक</a>",
  "DEFAULT_PROJECT_NOTIFICATION": "फीनिक्स में<br/> <b>डिफ़ॉल्ट प्रोजेक्ट</b> खोलने के लिए यहां क्लिक करें </br><a href='#' style='float:right;'>ठीक</a>",
  "DIRECTORY_REPLACE_MESSAGE": "चयनित फ़ोल्डर <span class='dialog-filename'>{0}</span> खाली नहीं है। क्या आप वाकई प्रोजेक्ट के साथ फ़ोल्डर सामग्री को बदलना चाहते हैं?",
  "BUILD_WEBSITE_SECTION": "वेबसाइट बनाएं",
  "LEARN_SECTION": "उदाहरणों के साथ सीखें",
  "WEBPAGE_HOME_PAGE": "होम पेज लेआउट",
  "WEBPAGE_BLOG": "ब्लॉग पेज",
  "WEBPAGE_DASHBOARD": "HTML डैशबोर्ड",
  "WEBPAGE_BOOTSTRAP_EXAMPLES": "बूटस्ट्रैप उदाहरण",
  "GUIDED_FILES_SIDEBAR": "एक HTML फ़ाइल <a href='#' style='float:right;'>ठीक</a> चुनें</br>",
  "GUIDED_LIVE_PREVIEW": "पूर्वावलोकन देखने के लिए कुछ कोड परिवर्तन करें और फ़ाइल सहेजें। </br><a href='#' style='float:right;'>ठीक</a>",
  "TEST_TRANSLATE": "अनुवाद का परीक्षण करने के लिए इसका उपयोग करें"
});