name: ðŸž Bug Report
title: 'Give a title here'
description: Report a bug
labels: ['bug']

body:
  - type: markdown
    attributes:
      value: |
        ## First of all
        1. Please search for [existing issues](https://github.com/phcode-dev/phoenix/issues) about this problem first.
        2. Make sure `rustc` and all relevant Tauri packages are up to date.
        3. Make sure it's an issue with Tauri and not something else you are using.
        4. Remember to follow our community guidelines and be friendly.
        5. Gif screen recordings help more if present. You can use one of the below free screen recorders:
          1. windows gif recorder- https://www.screentogif.com/
          2. mac gif recorder- https://apps.apple.com/au/app/giphy-capture-the-gif-maker/id668208984?mt=12
          3. linux gif recorder-  https://github.com/phw/peek

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is. Include screenshots if applicable.
      placeholder: Bug description
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear description of what you expected to happen.

  - type: textarea
    id: info
    attributes:
      label: OS, Browser and Phoenix versions
      description: "goto Help menu > About Phoenix and copy the line that looks like `Release 3.0 development build 3.0.2-0`"
      placeholder: |
        1. OS: [e.g. macos]
        1. device: [mobile, tablet, desktop or other]
        2. Browser [e.g. chrome, safari]
        3. Version [e.g. Release 3.0 development build 3.0.2-0]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: logs or debug stack trace if any
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
