/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "По умолчанию",
  "PROJECT_BUSY": "Операции проекта в процессе",
  "DUPLICATING": "Дублирование {0}",
  "MOVING": "Перемещение {0}",
  "COPYING": "Копирование {0}",
  "DELETING": "Удаление {0}",
  "RENAMING": "Переименование",
  "GENERIC_ERROR": "(ошибка {0})",
  "NOT_FOUND_ERR": "Файл не найден",
  "NOT_READABLE_ERR": "Файл не может быть прочитан",
  "EXCEEDS_MAX_FILE_SIZE": "Файлы размером более {0} МБ нельзя открыть в {APP_NAME}.",
  "NO_MODIFICATION_ALLOWED_ERR": "Целевая директория не может быть изменена.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "Ограничение прав не позволяет сделать изменения.",
  "CONTENTS_MODIFIED_ERR": "Файл был изменен вне {APP_NAME}.",
  "UNSUPPORTED_ENCODING_ERR": "{APP_NAME} пока поддерживает только текстовые файлы в кодировке UTF-8.",
  "ENCODE_FILE_FAILED_ERR": "{APP_NAME} не удалось закодировать содержимое файла.",
  "DECODE_FILE_FAILED_ERR": "{APP_NAME} не удалось расшифровать содержимое файла.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "{APP_NAME} в настоящее время не поддерживает текстовые файлы в кодировке UTF-16.",
  "FILE_EXISTS_ERR": "Файл уже существует.",
  "FILE": "файле",
  "FILE_TITLE": "Файл",
  "DIRECTORY": "директория",
  "DIRECTORY_TITLE": "Каталог",
  "DIRECTORY_NAMES_LEDE": "Имена директорий",
  "FILENAMES_LEDE": "Имена файлов",
  "FILENAME": "имя файла",
  "DIRECTORY_NAME": "имя директории",
  "ERROR_LOADING_PROJECT": "Ошибка при загрузке проекта",
  "OPEN_DIALOG_ERROR": "Произошла ошибка при показе диалога открытия файлов. (ошибка {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "Произошла ошибка при попытке загрузить директорию <span class='dialog-filename'>{0}</span>. (ошибка {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "Произошла ошибка при чтении содержимого директории <span class='dialog-filename'>{0}</span>. (ошибка {1})",
  "ERROR_OPENING_FILE_TITLE": "Ошибка открытия файла",
  "ERROR_OPENING_FILE": "Произошла ошибка при попытке открыть файл <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_OPENING_FILES": "Произошла ошибка при попытке открыть файлы: ",
  "ERROR_RELOADING_FILE_TITLE": "Ошибка перезагрузки изменений с диска",
  "ERROR_RELOADING_FILE": "Произошла ошибка при попытке перезагрузить файл <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_SAVING_FILE_TITLE": "Ошибка сохранения файла",
  "ERROR_SAVING_FILE": "Произошла ошибка при попытке сохранить файл <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_FILE_TITLE": "Ошибка переименования файла",
  "ERROR_RENAMING_FILE": "Произошла ошибка при попытке переименовать файл <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "Файл или каталог не является частью текущего открытого проекта. К сожалению, на этом этапе можно переименовывать только файлы проекта.",
  "ERROR_MOVING_FILE_TITLE": "Ошибка перемещения {0}",
  "ERROR_MOVING_FILE": "Произошла ошибка при попытке переместить {2} <span class='dialog-filename'>{0}</span> . {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "Невозможно переместить файл/папку, так как они не являются частью текущего проекта.",
  "ERROR_DELETING_FILE_TITLE": "Ошибка удаления файла",
  "ERROR_DELETING_FILE": "Произошла ошибка при попытке удалить файл <span class='dialog-filename'>{0}</span>. {1}",
  "INVALID_FILENAME_TITLE": "Неверное имя файла {0}",
  "CANNOT_PASTE_TITLE": "Невозможно вставить {0}",
  "ERR_TYPE_PASTE_FAILED": "Произошла ошибка при вставке <span class='dialog-filename'>{0}</span> в <span class='dialog-filename'>{1}</span>",
  "CANNOT_DUPLICATE_TITLE": "Невозможно дублировать",
  "ERR_TYPE_DUPLICATE_FAILED": "Произошла ошибка при дублировании <span class='dialog-filename'>{0}</span>",
  "INVALID_FILENAME_MESSAGE": "{0} не может содержать зарезервированные слова, заканчиваться точкой (.) или содержать следующие символы: <code class='emphasized'>{1}</code>",
  "ENTRY_WITH_SAME_NAME_EXISTS": "Файл или директория с именем <span class='dialog-filename'>{0}</span> уже существует.",
  "ERROR_CREATING_FILE_TITLE": "Ошибка создания файла",
  "ERROR_CREATING_FILE": "Произошла ошибка при попытке создать файл <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_MIXED_DRAGDROP": "Невозможно открыть папку одновременно с открытием других файлов.",
  "ERROR_KEYMAP_TITLE": "Ошибка чтения карты ключей пользователя",
  "ERROR_KEYMAP_CORRUPT": "Ваш файл карты ключей не является допустимым JSON. Файл будет открыт, чтобы вы могли исправить формат.",
  "ERROR_LOADING_KEYMAP": "Ваш файл карты ключей не является допустимым текстовым файлом в кодировке UTF-8 и не может быть загружен",
  "ERROR_RESTRICTED_COMMANDS": "Вы не можете переназначить ярлыки для этих команд: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "Вы не можете переназначить эти ярлыки: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "Вы переназначаете несколько ярлыков для этих команд: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "У вас есть несколько привязок этих сочетаний клавиш: {0}",
  "ERROR_INVALID_SHORTCUTS": "Эти ярлыки недействительны: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "Вы назначаете ярлыки несуществующим командам: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "Ошибка чтения настроек",
  "ERROR_PREFS_CORRUPT": "Обнаружена ошибка формата JSON в файле настроек. Он будет открыт для того, чтобы исправить ошибку вручную. Вам будет необходимо перезагрузить {APP_NAME}, чтобы исправления вступили в силу.",
  "ERROR_PROJ_PREFS_CORRUPT": "Ваш файл настроек проекта не является допустимым JSON. Файл будет открыт, чтобы вы могли исправить формат. Вам нужно будет перезагрузить проект, чтобы изменения вступили в силу.",
  "ERROR_IN_BROWSER_TITLE": "К сожалению, запуск {APP_NAME} в браузере пока что не поддерживается.",
  "ERROR_IN_BROWSER": "{APP_NAME} разработан на HTML, но пока что может работать только как настольное приложение, чтобы вы могли редактировать локальные файлы. Пожалуйста, используйте специальную оболочку (проект <b>github.com/adobe/brackets-shell</b>) для запуска {APP_NAME}.",
  "ERROR_MAX_FILES_TITLE": "Ошибка индексирования файлов",
  "ERROR_MAX_FILES": "Количество файлов превышает предельно допустимое. Команды использующие индекс файлов могут работать некорректно.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "Ошибка запуска браузера.",
  "ERROR_CANT_FIND_CHROME": "Браузер Google Chrome не найден. Пожалуйста, убедитесь, что он установлен.",
  "ERROR_LAUNCHING_BROWSER": "Произошла ошибка при запуске браузера. (ошибка {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "Ошибка функции Live Preview",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "Соединение с браузером",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "Функция Live Preview требует перезапуска Chrome с включенной функцией удаленной отладки. <br /><br />Перезапустить Chrome с удаленной отладкой?",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "Невозможно загрузить страницу Live Preview",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "Для запуска Live Preview с серверным файлом, вы должны указать базовый URL проекта.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "Ошибка запуска HTTP сервера для Live Preview. Попытайтесь снова.",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "Для дополнительной информации, смотрите <a href='{0}' title='{0}'>Поиск и устранение неисправностей ошибок подключения Live Preview</a>.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "Live Preview",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "Live Preview: Подключение…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "Live Preview: Инициализация…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "Отсоединить Live Preview",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "Live Preview",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "Выберите файл для просмотра в реальном времени",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "Перезагрузить страницу",
  "LIVE_DEV_TOGGLE_LIVE_HIGHLIGHT": "Toggle Live Preview Highlights",
  "LIVE_DEV_CLICK_POPOUT": "Всплывающий предварительный просмотр в новом окне",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "Закрепить на открепленной странице предварительного просмотра",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "Live Preview (Не обновляется из-за синтаксической ошибки)",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "Функция Live Preview была отключена при открытии инструментов разработки в браузере",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "Функция Live Preview была отключена при закрытии страницы в браузере",
  "LIVE_DEV_NAVIGATED_AWAY": "Функция Live Preview была отключена при переходе на страницу не принадлежащую проекту",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "Функция Live Preview была отменена по неизвестной причине ({0})",
  "SAVE_CLOSE_TITLE": "Сохранить изменения",
  "SAVE_CLOSE_MESSAGE": "Вы хотите сохранить изменения, которые вы сделали в документе <span class='dialog-filename'>{0}</span>?",
  "SAVE_CLOSE_MULTI_MESSAGE": "Вы хотите сохранить изменения для следующих файлов?",
  "EXT_MODIFIED_TITLE": "Внешние изменения",
  "CONFIRM_DELETE_TITLE": "Подтвердить удаление",
  "CONFIRM_FILE_DELETE": "Вы уверены, что хотите удалить файл <span class='dialog-filename'>{0}</span> ?",
  "CONFIRM_FOLDER_DELETE": "Вы уверены, что хотите удалить директорию <span class='dialog-filename'>{0}</span>?",
  "FILE_DELETED_TITLE": "Файл удален",
  "EXT_MODIFIED_WARNING": "<span class='dialog-filename'>{0}</span> был изменен на диске.<br /><br />Вы хотите сохранить ваши изменения и перезаписать внешние?",
  "EXT_MODIFIED_MESSAGE": "<span class='dialog-filename'>{0}</span> был изменен на диске, но также имеются несохраненные изменения в {APP_NAME}.<br /><br />Какую версию вы хотите оставить?",
  "EXT_DELETED_MESSAGE": "<span class='dialog-filename'>{0}</span> был удален на диске, но имеются несохраненные изменения в {APP_NAME}.<br /><br />Вы хотите оставить ваши изменения?",
  "WINDOW_UNLOAD_WARNING": "Вы уверены, что хотите перейти по другому URL-адресу и выйти из скобок?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "У вас есть несохраненные изменения! Вы уверены, что хотите перейти по другому URL-адресу и выйти из скобок?",
  "DONE": "Готово",
  "OK": "ОК",
  "CANCEL": "Отмена",
  "DONT_SAVE": "Не сохранять",
  "SAVE": "Сохранить",
  "SAVE_AS": "Сохранить как…",
  "SAVE_AND_OVERWRITE": "Переустановить",
  "DELETE": "Удалить",
  "BUTTON_YES": "Да",
  "BUTTON_NO": "Нет",
  "FIND_MATCH_INDEX": "{0} из {1}",
  "FIND_NO_RESULTS": "Не найдено",
  "FIND_QUERY_PLACEHOLDER": "Найти…",
  "FIND_HISTORY_MAX_COUNT": "Максимальное количество элементов поиска в истории поиска",
  "REPLACE_PLACEHOLDER": "Заменить на…",
  "BUTTON_REPLACE_ALL": "Все…",
  "BUTTON_REPLACE_BATCH": "Партия…",
  "BUTTON_REPLACE_ALL_IN_FILES": "Заменять…",
  "BUTTON_REPLACE": "Заменить",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "Следующее совпадение",
  "BUTTON_PREV_HINT": "Предыдущее совпадение",
  "BUTTON_CASESENSITIVE_HINT": "С учетом регистра",
  "BUTTON_REGEXP_HINT": "Регулярное выражение",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "Заменить без отмены",
  "REPLACE_WITHOUT_UNDO_WARNING": "Т.к. необходимо изменить более чем {0} файла(ов), {APP_NAME} выполнит замену непосредственно на диске.<br />Вы не сможете отменить изменения в этих файлах.",
  "BUTTON_REPLACE_WITHOUT_UNDO": "Заменить без отмены",
  "OPEN_FILE": "Открыть файл",
  "SAVE_FILE_AS": "Сохранить файл",
  "CHOOSE_FOLDER": "Выбрать директорию",
  "RELEASE_NOTES": "Примечания к выпуску",
  "NO_UPDATE_TITLE": "Обновления отсутствуют",
  "NO_UPDATE_MESSAGE": "Вы используете последнюю версию {APP_NAME}.",
  "FIND_REPLACE_TITLE_LABEL": "Заменить",
  "FIND_REPLACE_TITLE_WITH": "на",
  "FIND_TITLE_LABEL": "Найдено",
  "FIND_TITLE_SUMMARY": "&mdash; {0} {1} {2} в {3}",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "в <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_NO_SCOPE": "в проекте",
  "FIND_IN_FILES_ZERO_FILES": "Фильтр исключает все файлы {0}",
  "FIND_IN_FILES_FILE": "файле",
  "FIND_IN_FILES_FILES": "файлах",
  "FIND_IN_FILES_MATCH": "совпадение",
  "FIND_IN_FILES_MATCHES": "совпадений",
  "FIND_IN_FILES_MORE_THAN": "Более ",
  "FIND_IN_FILES_PAGING": "{0}&mdash;{1}",
  "FIND_IN_FILES_FILE_PATH": "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "Ctrl/Cmd-клик чтобы развернуть/свернуть все",
  "FIND_IN_FILES_INDEXING": "Индексация для мгновенного поиска…",
  "FIND_IN_FILES_INDEXING_PROGRESS": "Индексация {0} из {1} файлов для мгновенного поиска…",
  "REPLACE_IN_FILES_ERRORS_TITLE": "Ошибка замены",
  "REPLACE_IN_FILES_ERRORS": "Данные файлы не были изменены, т.к. они изменились после поиска или не могут быть записаны.",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "Ошибка при получении информации об обновлениях",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "Ошибка при получении информации о последних обновлениях с сервера. Пожалуйста, убедитесь, что вы подключены к интернету и попробуйте снова. ",
  "NEW_FILE_FILTER": "Новый фильтр…",
  "CLEAR_FILE_FILTER": "Не исключать файлы",
  "NO_FILE_FILTER": "Нет исключенных файлов",
  "EXCLUDE_FILE_FILTER": "Исключить {0}",
  "EDIT_FILE_FILTER": "Редактировать…",
  "FILE_FILTER_DIALOG": "Редактировать фильтр",
  "FILE_FILTER_INSTRUCTIONS": "Исключить файлы и директории содержащие любую из перечисленных строк, возможно использование <a href='{0}' title='{0}'>групповых символов</a>. Указывайте по одной строке на линию.",
  "FILTER_NAME_PLACEHOLDER": "Назвать этот фильтр (опционально)",
  "FILTER_NAME_REMAINING": "Осталось {0} символов",
  "FILE_FILTER_CLIPPED_SUFFIX": "и еще {0}",
  "FILTER_COUNTING_FILES": "Подсчет количества файлов…",
  "FILTER_FILE_COUNT": "Фильтр оставляет {0} из {1} файлов/а {2}",
  "FILTER_FILE_COUNT_ALL": "Фильтр оставляет все {0} файлов/а {1}",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "Быстрое редактирование недоступно для данной позиции курсора",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "Быстрое редактирование CSS: установите курсор на одном из имен класса",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "Быстрое редактирование CSS: отсутствует имя класса",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "Быстрое редактирование CSS: отсутствует имя идентификатора",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "Быстрое редактирование CSS: установите курсор на теге, классе или идентификаторе",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "Быстрое редактирование временной функции CSS: некорректный синтаксис",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "Быстрое редактирование JS: установите курсор на имени функции",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "Быстрая документация для текущей позиции курсора отсутствет",
  "PROJECT_LOADING": "Загрузка…",
  "UNTITLED": "Без названия",
  "WORKING_FILES": "Рабочие файлы",
  "TOP": "верхний",
  "BOTTOM": "Нижний",
  "LEFT": "Оставил",
  "RIGHT": "Верно",
  "CMD_SPLITVIEW_NONE": "Не разделен",
  "CMD_SPLITVIEW_VERTICAL": "Вертикальное разделение",
  "CMD_SPLITVIEW_HORIZONTAL": "Горизонтальное разделение",
  "SPLITVIEW_MENU_TOOLTIP": "Разделите редактор по вертикали или по горизонтали",
  "GEAR_MENU_TOOLTIP": "Настроить рабочий набор",
  "SPLITVIEW_INFO_TITLE": "Уже открыто",
  "SPLITVIEW_MULTIPANE_WARNING": "Файл уже открыт в другой панели. {APP_NAME} скоро будет поддерживать открытие одного и того же файла более чем в одной панели. До этого файл будет отображаться на панели, в которой он уже открыт.<br /><br /> (Вы увидите это сообщение только один раз.)",
  "STATUSBAR_CURSOR_POSITION": "Строка {0}, Столбец {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": " — Выделен {0} столбец",
  "STATUSBAR_SELECTION_CH_PLURAL": " — Выделено {0} столбцов",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " — Выделена {0} строка",
  "STATUSBAR_SELECTION_LINE_PLURAL": " — Выделено {0} строк",
  "STATUSBAR_SELECTION_MULTIPLE": " — {0} выбранных элементов",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "Нажмите чтобы использовать пробелы для отступа",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "Нажмите чтобы использовать табуляцию для отступа",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "Нажмите чтобы изменить количества пробелов для отступа",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "Нажмите чтобы изменить ширину табуляции в столбцах",
  "STATUSBAR_SPACES": "Пробелы:",
  "STATUSBAR_TAB_SIZE": "Табуляция:",
  "STATUSBAR_LINE_COUNT_SINGULAR": "— {0} строка",
  "STATUSBAR_LINE_COUNT_PLURAL": "— {0} строк",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "Расширения отключены",
  "STATUSBAR_INSERT": "ВСТ",
  "STATUSBAR_OVERWRITE": "ЗАМ",
  "STATUSBAR_INSOVR_TOOLTIP": "Нажмите, чтобы переключить курсор между режимами вставки (INS) и перезаписи (OVR).",
  "STATUSBAR_LANG_TOOLTIP": "Нажмите, чтобы изменить тип файла",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. Нажмите, чтобы переключить панель отчетов.",
  "STATUSBAR_DEFAULT_LANG": "(дефолт)",
  "STATUSBAR_SET_DEFAULT_LANG": "Установить по умолчанию для файлов .{0}",
  "STATUSBAR_ENCODING_TOOLTIP": "Выберите кодировку",
  "ERRORS_PANEL_TITLE_MULTIPLE": "{0} ошибок",
  "SINGLE_ERROR": "1 ошибка {0}",
  "MULTIPLE_ERRORS": "{1} ошибок {0}",
  "NO_ERRORS": "{0} не нашел ошибок &mdash; отлично!",
  "NO_ERRORS_MULTIPLE_PROVIDER": "Ошибок не найдено &mdash; отлично!",
  "LINT_DISABLED": "Статический анализ отключен",
  "NO_LINT_AVAILABLE": "Нет статического анализатора для {0}",
  "NOTHING_TO_LINT": "Не подлежит статическому анализу",
  "LINTER_TIMED_OUT": "{0} превысил время ожидания {1} мс",
  "LINTER_FAILED": "{0} завершил исполнение с ошибкой: {1}",
  "FILE_MENU": "Файл",
  "CMD_FILE_NEW_UNTITLED": "Новый",
  "CMD_FILE_NEW": "Новый файл",
  "CMD_FILE_DUPLICATE": "Дублировать",
  "CMD_FILE_CUT": "Вырезать",
  "CMD_FILE_COPY": "Копировать",
  "CMD_FILE_COPY_PATH": "Копировать путь",
  "CMD_FILE_PASTE": "Вставить",
  "CMD_PROJECT_NEW": "Новый проект",
  "CMD_FILE_NEW_FOLDER": "Новая директория",
  "CMD_FILE_OPEN": "Открыть…",
  "CMD_RECENT_FILES_OPEN": "Недавние файлы…",
  "CMD_ADD_TO_WORKING_SET": "Добавить в рабочий набор",
  "CMD_OPEN_DROPPED_FILES": "Открыть перетащенные файлы",
  "CMD_OPEN_FOLDER": "Открыть директорию…",
  "CMD_FILE_CLOSE": "Закрыть",
  "CMD_FILE_CLOSE_ALL": "Закрыть все",
  "CMD_FILE_CLOSE_LIST": "Закрыть список",
  "CMD_FILE_CLOSE_OTHERS": "Закрыть остальные",
  "CMD_FILE_CLOSE_ABOVE": "Закрыть остальные сверху",
  "CMD_FILE_CLOSE_BELOW": "Закрыть остальные снизу",
  "CMD_FILE_SAVE": "Сохранить файл",
  "CMD_FILE_SAVE_ALL": "Сохранить все",
  "CMD_FILE_SAVE_AS": "Сохранить как…",
  "CMD_LIVE_FILE_PREVIEW": "Live Preview",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "Включить экспериментальный предварительный просмотр в реальном времени",
  "CMD_RELOAD_LIVE_PREVIEW": "Принудительная перезагрузка в режиме реального времени",
  "CMD_PROJECT_SETTINGS": "Настройки проекта…",
  "CMD_FILE_RENAME": "Переименовать",
  "CMD_FILE_DELETE": "Удалить",
  "CMD_INSTALL_EXTENSION": "Установить расширение…",
  "CMD_EXTENSION_MANAGER": "Менеджер расширений…",
  "CMD_FILE_REFRESH": "Обновить дерево проекта",
  "CMD_FILE_SHOW_FOLDERS_FIRST": "Сортировать папки в первую очередь",
  "CMD_QUIT": "Выход",
  "CMD_EXIT": "Выход",
  "EDIT_MENU": "Правка",
  "CMD_UNDO": "Не обновлять",
  "CMD_REDO": "Повторить",
  "CMD_CUT": "Вырезать",
  "CMD_COPY": "Копировать",
  "CMD_PASTE": "Вставить",
  "CMD_SELECT_ALL": "Выделить все",
  "CMD_SELECT_LINE": "Выделить строку",
  "CMD_SPLIT_SEL_INTO_LINES": "Разбить выделенное на линии",
  "CMD_ADD_CUR_TO_NEXT_LINE": "Добавить курсор к следующей линии",
  "CMD_ADD_CUR_TO_PREV_LINE": "Добавить курсор к предыдущей линии",
  "CMD_INDENT": "Сделать отступ",
  "CMD_UNINDENT": "Убрать отступ",
  "CMD_DUPLICATE": "Дублировать",
  "CMD_DELETE_LINES": "Удалить строку",
  "CMD_COMMENT": "Вкл./выкл. строчный комментарий",
  "CMD_BLOCK_COMMENT": "Вкл./выкл. блочный комментарий",
  "CMD_LINE_UP": "Переместить строку вверх",
  "CMD_LINE_DOWN": "Переместить строку вниз",
  "CMD_OPEN_LINE_ABOVE": "Открыть строку сверху",
  "CMD_OPEN_LINE_BELOW": "Открыть строку снизу",
  "CMD_TOGGLE_CLOSE_BRACKETS": "Автоматически закрывать скобки",
  "CMD_SHOW_CODE_HINTS": "Показывать подсказки в коде",
  "CMD_BEAUTIFY_CODE": "Украсить код",
  "CMD_BEAUTIFY_CODE_ON_SAVE": "Украсить код после сохранения",
  "FIND_MENU": "Найти",
  "CMD_FIND": "Найти",
  "CMD_FIND_NEXT": "Найти след.",
  "CMD_FIND_PREVIOUS": "Найти пред.",
  "CMD_FIND_ALL_AND_SELECT": "Найти все и выделить",
  "CMD_ADD_NEXT_MATCH": "Добавить следущее найденное к выделению",
  "CMD_SKIP_CURRENT_MATCH": "Пропустить и добавить следующее найденное",
  "CMD_FIND_IN_FILES": "Найти в файлах",
  "CMD_FIND_IN_SUBTREE": "Найти в…",
  "CMD_REPLACE": "Заменить",
  "CMD_REPLACE_IN_FILES": "Заменить в файлах",
  "CMD_REPLACE_IN_SUBTREE": "Заменить в…",
  "VIEW_MENU": "Вид",
  "CMD_HIDE_SIDEBAR": "Скрыть боковую панель",
  "CMD_SHOW_SIDEBAR": "Показать боковую панель",
  "CMD_TOGGLE_SIDEBAR": "Переключить боковую панель",
  "CMD_TOGGLE_PANELS": "Переключить панели",
  "CMD_TOGGLE_PURE_CODE": "Никаких отвлекающих факторов",
  "CMD_INCREASE_FONT_SIZE": "Увеличить размер шрифта",
  "CMD_DECREASE_FONT_SIZE": "Уменьшить размер шрифта",
  "CMD_RESTORE_FONT_SIZE": "Восстановить размер шрифта",
  "CMD_SCROLL_LINE_UP": "Прокрутить на строку вверх",
  "CMD_SCROLL_LINE_DOWN": "Прокрутить на строку вниз",
  "CMD_TOGGLE_LINE_NUMBERS": "Номера строк",
  "CMD_TOGGLE_ACTIVE_LINE": "Подсвечивать активную строку",
  "CMD_TOGGLE_WORD_WRAP": "Заворачивать строки",
  "CMD_LIVE_HIGHLIGHT": "Подсвечивать в Live Preview",
  "CMD_VIEW_TOGGLE_INSPECTION": "Анализировать при сохранении",
  "CMD_WORKINGSET_SORT_BY_ADDED": "Сортировать по порядку добавления",
  "CMD_WORKINGSET_SORT_BY_NAME": "Сортировать по имени",
  "CMD_WORKINGSET_SORT_BY_TYPE": "Сортировать по типу",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "Автоматическая сортировка",
  "CMD_THEMES": "Темы…",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "Автоматически закрыть поиск",
  "NAVIGATE_MENU": "Навигация",
  "CMD_QUICK_OPEN": "Быстрое открытие",
  "CMD_GOTO_LINE": "Перейти к строке",
  "CMD_GOTO_DEFINITION": "Быстрый поиск определения",
  "CMD_GOTO_DEFINITION_PROJECT": "Определение быстрого поиска в проекте",
  "CMD_GOTO_FIRST_PROBLEM": "Перейти к первой ошибке/предупреждению",
  "CMD_TOGGLE_QUICK_EDIT": "Быстрое редактирование",
  "CMD_TOGGLE_QUICK_DOCS": "Быстрая документация",
  "CMD_QUICK_EDIT_PREV_MATCH": "Предыдущее совпадение",
  "CMD_QUICK_EDIT_NEXT_MATCH": "Следующее совпадение",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "Новое правило",
  "CMD_NEXT_DOC": "Следующий документ",
  "CMD_PREV_DOC": "Предыдущий документ",
  "CMD_NAVIGATE_BACKWARD": "Перейти назад",
  "CMD_NAVIGATE_FORWARD": "Навигация вперед",
  "CMD_NEXT_DOC_LIST_ORDER": "Следующий документ в списке",
  "CMD_PREV_DOC_LIST_ORDER": "Предыдущий документ в списке",
  "CMD_SHOW_IN_TREE": "Показать в дереве проекта",
  "CMD_SHOW_IN_EXPLORER": "Показать в Проводнике",
  "CMD_SHOW_IN_FINDER": "Показать в Finder",
  "CMD_SHOW_IN_OS": "Показать в операционной системе",
  "CMD_SWITCH_PANE_FOCUS": "Переключить фокус панели",
  "CMD_OPEN_VFS": "Открытая виртуальная файловая система",
  "CMD_OPEN_VIRTUAL_SERVER": "Открытый виртуальный сервер",
  "HELP_MENU": "Помощь",
  "CMD_CHECK_FOR_UPDATE": "Проверить наличие обновлений",
  "CMD_HOW_TO_USE_BRACKETS": "Как использовать {APP_NAME}",
  "CMD_SUPPORT": "Поддержка {APP_NAME}",
  "CMD_SUGGEST": "Предложить улучшение",
  "CMD_RELEASE_NOTES": "Примечания к выпуску",
  "CMD_GET_INVOLVED": "Принять участие в проекте",
  "CMD_SHOW_EXTENSIONS_FOLDER": "Показать директорию расширений",
  "CMD_HEALTH_DATA_STATISTICS": "Отчет о состоянии здоровья",
  "CMD_HOMEPAGE": "Домашняя страница {APP_NAME}",
  "CMD_TWITTER": "{TWITTER_NAME} в Twitter",
  "CMD_ABOUT": "О {APP_TITLE}",
  "CMD_OPEN_PREFERENCES": "Открыть файл настроек",
  "CMD_OPEN_KEYMAP": "Открыть карту ключей пользователя",
  "EXPERIMENTAL_BUILD": "Экспериментальная сборка",
  "RELEASE_BUILD": "строить",
  "DEVELOPMENT_BUILD": "Сборка для разработчиков",
  "PRERELEASE_BUILD": "предварительная сборка",
  "RELOAD_FROM_DISK": "Перезагрузить с диска",
  "KEEP_CHANGES_IN_EDITOR": "Оставить изменения в редакторе",
  "CLOSE_DONT_SAVE": "Закрыть (Не сохранять)",
  "RELAUNCH_CHROME": "Перезапустить Chrome",
  "ABOUT": "О программе",
  "CLOSE": "Закрыть",
  "ABOUT_TEXT_LINE1": "Выпуск {VERSION_MAJOR}.{VERSION_MINOR} {BUILD_TYPE} {VERSION}",
  "ABOUT_TEXT_BUILD_TIMESTAMP": "метка времени сборки:",
  "ABOUT_TEXT_LINE3": "Используемые нами сторонние библиотеки — <a href='https://github.com/phcode-dev/phoenix/tree/main/src/thirdparty/licences'>лицензии и атрибуты</a> .",
  "ABOUT_TEXT_LINE4": "Документация и источник на <a href='https://github.com/phcode-dev/phoenix/'>https://github.com/phcode-dev/phoenix/</a>",
  "ABOUT_TEXT_LINE5": "Сделано с помощью ❤ и JavaScript:",
  "ABOUT_TEXT_LINE6": "Много людей (но у нас сейчас проблемы с загрузкой этих данных).",
  "ABOUT_TEXT_MDN_DOCS": "MDN Docs and the MDN graphical logo are licensed under a Creative Commons Attribution license, <a href='{MDN_DOCS_LICENSE}'>CC-BY-SA 2.5 Unported</a>.",
  "UPDATE_NOTIFICATION_TOOLTIP": "Новая сборка {APP_NAME} доступна! Нажмите здесь для подробностей.",
  "UPDATE_AVAILABLE_TITLE": "Доступно обновление",
  "UPDATE_RELOAD_APP": "Закройте все окна/вкладки {APP_NAME} и снова откройте {APP_NAME}, чтобы получить последнюю версию.",
  "UPDATE_MESSAGE": "Эй, новая версия {APP_NAME} доступна. Вот некоторые из новых функций:",
  "GET_IT_NOW": "Установить немедленно!",
  "PROJECT_SETTINGS_TITLE": "Настройки проекта для: {0}",
  "PROJECT_SETTING_BASE_URL": "Базовый URL для Live Preview",
  "PROJECT_SETTING_BASE_URL_HINT": "(оставьте пустым для просмотра локальных файлов)",
  "BASEURL_ERROR_INVALID_PROTOCOL": "Протокол {0} не поддерживается Live Preview &mdash; пожалуйста, используйте http: или https: .",
  "BASEURL_ERROR_SEARCH_DISALLOWED": "Базовый URL не может содержать такие параметры поиска как \"{0}\".",
  "BASEURL_ERROR_HASH_DISALLOWED": "Базовый URL не может содержать такие хеши как \"{0}\".",
  "BASEURL_ERROR_INVALID_CHAR": "Специальные символы как '{0}' должны быть %-экранированы.",
  "BASEURL_ERROR_UNKNOWN_ERROR": "Неизвестная ошибка при синтаксическом разборе основного URL",
  "EMPTY_VIEW_HEADER": "<em>Открыть файл, когда эта панель находится в фокусе</em>",
  "FLIPVIEW_BTN_TOOLTIP": "Перевернуть это представление на панель {0}",
  "CURRENT_THEME": "Текущая тема",
  "USE_THEME_SCROLLBARS": "Используйте полосы прокрутки темы",
  "FONT_SIZE": "Размер шрифта",
  "FONT_FAMILY": "Семейство шрифтов",
  "THEMES_SETTINGS": "Настройки тем",
  "BUTTON_NEW_RULE": "Новое правило",
  "INSTALL": "Установить",
  "UPDATE": "Обновить",
  "REMOVE": "Удалить",
  "DISABLE": "Запрещать",
  "ENABLE": "включить",
  "OVERWRITE": "Переустановить",
  "CANT_DROP_ZIP": "Удаление zip-файлов скоро будет поддерживаться...",
  "CANT_REMOVE_DEV": "Расширения, установленные в директории \"dev\", должны удаляться вручную.",
  "CANT_UPDATE": "Это обновление не совместимо с данной версией {APP_NAME}.",
  "CANT_UPDATE_DEV": "Расширения, установленные в директории \"dev\", не могут быть автоматически обновлены.",
  "INSTALL_EXTENSION_TITLE": "Установка расширения",
  "UPDATE_EXTENSION_TITLE": "Обновить расширение",
  "INSTALL_EXTENSION_LABEL": "URL расширения",
  "INSTALL_EXTENSION_HINT": "URL zip-файла расширения или репозитория GitHub",
  "INSTALLING_FROM": "Установка расширения с {0}…",
  "INSTALL_SUCCEEDED": "Установка завершена успешно!",
  "INSTALL_FAILED": "Не удалось установить.",
  "CANCELING_INSTALL": "Отмена…",
  "CANCELING_HUNG": "Отмена установки занимает продолжительное время. Возможно по причине внутренней ошибки.",
  "INSTALL_CANCELED": "Установка отменена.",
  "VIEW_COMPLETE_DESCRIPTION": "Посмотреть полное описание",
  "VIEW_TRUNCATED_DESCRIPTION": "Посмотреть усеченное описание",
  "SORT_EXTENSION_METHOD": "Сортировка расширений с помощью downloadCount или publishDate",
  "INVALID_ZIP_FILE": "Скачанный файл не является zip-файлом.",
  "MISSING_PACKAGE_JSON": "В пакете нет файла package.json.",
  "INVALID_PACKAGE_JSON": "Файл package.json некорректен (ошибка: {0}).",
  "MISSING_PACKAGE_NAME": "Файл package.json не содержит имени пакета.",
  "BAD_PACKAGE_NAME": "{0} не является корректным именем пакета.",
  "MISSING_PACKAGE_VERSION": "Файл package.json не содержит версии пакета.",
  "INVALID_VERSION_NUMBER": "Версия пакета ({0}) некорректна.",
  "INVALID_BRACKETS_VERSION": "Строка совместимости с {APP_NAME} ({0}) некорректна.",
  "DISALLOWED_WORDS": "Слова ({1}) недопустимы в поле {0}.",
  "NPM_INSTALL_FAILED": "Ошибка команды установки npm: {0}",
  "API_NOT_COMPATIBLE": "Расширение несовместимо с данной версией {APP_NAME}. Расширение установлено в директории disabled.",
  "MISSING_MAIN": "Пакет не содержит файл main.js.",
  "EXTENSION_ALREADY_INSTALLED": "Установка данного пакета перезапишет установленное расширение. Перезаписать существующее расширение?",
  "EXTENSION_SAME_VERSION": "Версия данного пакета совпадает с версией установленного расширения. Перезаписать существующее расширение?",
  "EXTENSION_OLDER_VERSION": "Версия данного пакета ({0}) старее версии уставновленного расширения ({1}). Перезаписать существующее расширение?",
  "DOWNLOAD_ID_IN_USE": "Внутренняя ошибка: идентификатор закачки уже используется.",
  "NO_SERVER_RESPONSE": "Невозможно присоединиться к серверу.",
  "BAD_HTTP_STATUS": "Файл не найден на сервере (HTTP {0}).",
  "CANNOT_WRITE_TEMP": "Невозможно сохранить закачку во временный файл.",
  "ERROR_LOADING": "Ошибка при запуске расширения.",
  "MALFORMED_URL": "Некорректный URL. Пожалуйста, убедитесь в его правильности.",
  "UNSUPPORTED_PROTOCOL": "URL должен использовать протокол http or https.",
  "UNKNOWN_ERROR": "Неизвестная внутренняя ошибка.",
  "EXTENSION_MANAGER_TITLE": "Менеджер расширений",
  "EXTENSION_MANAGER_ERROR_LOAD": "Невозможно подсоединиться к каталогу расширений. Пожалуйста, попытайтесь еще раз.",
  "INSTALL_EXTENSION_DRAG": "Перетащите .zip сюда или",
  "INSTALL_EXTENSION_DROP": "Перетащите .zip для установки",
  "INSTALL_EXTENSION_DROP_ERROR": "Установка/обновление прервано из-за следующих ошибок:",
  "INSTALL_FROM_URL": "Установить с URL…",
  "INSTALL_EXTENSION_VALIDATING": "Проверка…",
  "EXTENSION_AUTHOR": "Автор",
  "EXTENSION_DATE": "Дата",
  "EXTENSION_INCOMPATIBLE_NEWER": "Это расширение требует новой версии {APP_NAME}.",
  "EXTENSION_INCOMPATIBLE_OLDER": "Это расширение работает только с предыдущими версиями {APP_NAME}.",
  "EXTENSION_LATEST_INCOMPATIBLE_NEWER": "Версия {0} данного расширения требует новой версии {APP_NAME}. Вы можете установить предыдущую версию расширения{1}.",
  "EXTENSION_LATEST_INCOMPATIBLE_OLDER": "Версия {0} данного расширения требует предыдущей версии {APP_NAME}. Вы можете установить предыдущую версию {1}.",
  "EXTENSION_NO_DESCRIPTION": "Описание отсутвует",
  "EXTENSION_MORE_INFO": "Подробнее…",
  "EXTENSION_ERROR": "Ошибка расширения",
  "EXTENSION_KEYWORDS": "Ключевые слова",
  "EXTENSION_TRANSLATED_USER_LANG": "Переведено на {0} языков, включая ваш",
  "EXTENSION_TRANSLATED_GENERAL": "Переведено на {0} языков",
  "EXTENSION_TRANSLATED_LANGS": "Это расширение переведено на следующие языки: {0}",
  "EXTENSION_INSTALLED": "Установленные",
  "EXTENSION_UPDATE_INSTALLED": "Данное расширение было скачано и будет установлено после перегрузки {APP_NAME}.",
  "EXTENSION_SEARCH_PLACEHOLDER": "Поиск",
  "EXTENSION_MORE_INFO_LINK": "Подробнее",
  "BROWSE_EXTENSIONS": "Просмотреть расширения",
  "EXTENSION_MANAGER_REMOVE": "Удалить расширение",
  "EXTENSION_MANAGER_REMOVE_ERROR": "Невозможно удалить одно или более расширений: {0}. {APP_NAME} продолжит перезагрузку.",
  "EXTENSION_MANAGER_UPDATE": "Обновить расширение",
  "EXTENSION_MANAGER_UPDATE_ERROR": "Невозможно обновить одно или более расширений: {0}. {APP_NAME} продолжит перезагрузку.",
  "EXTENSION_MANAGER_DISABLE": "Отключить расширение",
  "EXTENSION_MANAGER_DISABLE_ERROR": "Не удалось отключить одно или несколько расширений: {0}. {APP_NAME} все равно перезагрузится.",
  "MARKED_FOR_REMOVAL": "Отмечено для удаления",
  "UNDO_REMOVE": "Не обновлять",
  "MARKED_FOR_UPDATE": "Отмечено для обновления",
  "UNDO_UPDATE": "Не обновлять",
  "MARKED_FOR_DISABLING": "Помечено для отключения",
  "UNDO_DISABLE": "Не обновлять",
  "CHANGE_AND_RELOAD_TITLE": "Изменить расширения",
  "CHANGE_AND_RELOAD_MESSAGE": "Для обновления или удаления расширений, {APP_NAME} будет перезагружен. Вам будет предложено сохранить несохраненные изменения.",
  "REMOVE_AND_RELOAD": "Удалить расширения и перегрузиться",
  "CHANGE_AND_RELOAD": "Изменить расширения и перегрузиться",
  "UPDATE_AND_RELOAD": "Обновить расширения и перегрузиться",
  "DISABLE_AND_RELOAD": "Отключить расширения и перезагрузить",
  "PROCESSING_EXTENSIONS": "Обработка изменений в расширениях…",
  "EXTENSION_NOT_INSTALLED": "Невозможно удалить расширение {0}, оно не было установлено.",
  "NO_EXTENSIONS": "Нет установленных расширений.<br>Перейдите на закладку Доступные чтобы начать работу с расширениями.",
  "NO_EXTENSION_MATCHES": "Не найдено расширений по критерию поиска.",
  "REGISTRY_SANITY_CHECK_WARNING": "Будьте осторожны при установке расширений из неизвестных источников.",
  "EXTENSIONS_INSTALLED_TITLE": "Установленные",
  "EXTENSIONS_DEFAULT_TITLE": "По умолчанию",
  "EXTENSIONS_AVAILABLE_TITLE": "Доступные",
  "EXTENSIONS_THEMES_TITLE": "Темы",
  "EXTENSIONS_UPDATES_TITLE": "Обновления",
  "EXTENSIONS_LAST_UPDATED": "Последнее обновление",
  "EXTENSIONS_DOWNLOADS": "Загрузки",
  "INLINE_EDITOR_NO_MATCHES": "Совпадений не найдено.",
  "INLINE_EDITOR_HIDDEN_MATCHES": "Все матчи свернуты. Разверните файлы, перечисленные справа, чтобы просмотреть совпадения.",
  "CSS_QUICK_EDIT_NO_MATCHES": "Существующих правил CSS соответвующих выделенному тексту не определено. <br> Выберите \"Новое правило\" чтобы создать новое.",
  "CSS_QUICK_EDIT_NO_STYLESHEETS": "Ваш проект не содержит таблиц стилей (stylesheets).<br>Создайте его чтобы добавить правила CSS.",
  "IMAGE_VIEWER_LARGEST_ICON": "наибольший размер",
  "UNIT_PIXELS": "пикселей",
  "DEBUG_MENU": "Отладка",
  "ERRORS": "Ошибки",
  "CMD_SHOW_DEV_TOOLS": "Показать инструменты разработчика",
  "CMD_REFRESH_WINDOW": "Перезагрузить с расширениями",
  "CMD_RELOAD_WITHOUT_USER_EXTS": "Перезагрузить без расширений",
  "CMD_NEW_BRACKETS_WINDOW": "Новое окно {APP_NAME}",
  "CMD_LAUNCH_SCRIPT_MAC": "Установить ярлык командной строки",
  "CMD_SWITCH_LANGUAGE": "Изменить язык",
  "CMD_RUN_UNIT_TESTS": "Запустить тесты",
  "CMD_SHOW_PERF_DATA": "Показать данные о производительности",
  "CMD_ENABLE_LOGGING": "Включить подробные журналы",
  "CMD_ENABLE_LIVE_PREVIEW_LOGS": "Журналы просмотра в реальном времени",
  "CMD_OPEN_BRACKETS_SOURCE": "Откройте источник {APP_NAME}",
  "CREATING_LAUNCH_SCRIPT_TITLE": "Ярлык командной строки {APP_NAME}",
  "ERROR_CREATING_LAUNCH_SCRIPT": "Произошла ошибка при установке ярлыка командной строки. Пожалуйста, попробуйте <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting'>эти рекомендации по устранению неполадок</a> .<br/><br/> Причина: {0}",
  "ERROR_CLTOOLS_RMFAILED": "Не удалось удалить существующую символическую ссылку <code>/usr/local/bin/brackets</code> .",
  "ERROR_CLTOOLS_MKDIRFAILED": "Не удалось создать каталог <code>/usr/local/bin</code> .",
  "ERROR_CLTOOLS_LNFAILED": "Не удалось создать символическую ссылку <code>/usr/local/bin/brackets</code> .",
  "ERROR_CLTOOLS_SERVFAILED": "Внутренняя ошибка.",
  "ERROR_CLTOOLS_NOTSUPPORTED": "Ярлык командной строки не поддерживается в этой ОС.",
  "LAUNCH_SCRIPT_CREATE_SUCCESS": "Успех! Теперь вы можете легко запустить {APP_NAME} из командной строки: <code>brackets myFile.txt</code> для открытия файла или <code>brackets myFolder</code> для переключения проектов.<br/><br/> <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments'>Узнайте больше</a> об использовании {APP_NAME} из командной строки.",
  "LANGUAGE_TITLE": "Изменить язык",
  "LANGUAGE_MESSAGE": "Пожалуйста, выберите желаемый язык из списка ниже:",
  "LANGUAGE_SUBMIT": "Перезагрузить {APP_NAME}",
  "LANGUAGE_CANCEL": "Отмена",
  "LANGUAGE_SYSTEM_DEFAULT": "По умолчанию",
  "HEALTH_DATA_NOTIFICATION": "Настройки отчета о работоспособности",
  "HEALTH_FIRST_POPUP_TITLE": "Отчет о работоспособности {APP_NAME}",
  "HEALTH_DATA_DO_TRACK": "Делиться псевдонимной информацией о том, как я использую {APP_NAME}",
  "HEALTH_DATA_NOTIFICATION_MESSAGE": "Чтобы улучшить {APP_NAME}, мы периодически отправляем на <strong>phcode.dev</strong> ограниченную анонимную статистику и отчеты об ошибках о том, как вы используете {APP_NAME}. Эта информация помогает определять приоритеты функций, находить ошибки и выявлять проблемы с удобством использования, защищая при этом вашу конфиденциальность.<br><br> Вы можете просмотреть свои данные или отказаться от обмена данными, выбрав « <strong>Справка» &gt; «Отчет о работоспособности»</strong> .<br><br>",
  "HEALTH_DATA_PREVIEW": "Отчет о работоспособности {APP_NAME}",
  "HEALTH_DATA_PREVIEW_INTRO": "<p>Чтобы улучшить {APP_NAME}, мы периодически отправляем на <strong>phcode.dev</strong> ограниченную анонимную статистику и отчеты об ошибках о том, как вы используете {APP_NAME}. Эта информация помогает определять приоритеты функций, находить ошибки и выявлять проблемы с удобством использования.</p><p> Ниже приведен предварительный просмотр данных, которые будут отправлены в вашем следующем отчете о работоспособности <em>, если</em> он включен. (Также см. консоль разработчика для журналов ошибок с пометкой «Caught Critical error».)</p>",
  "INLINE_TIMING_EDITOR_TIME": "Время",
  "INLINE_TIMING_EDITOR_PROGRESSION": "Прогресс",
  "BEZIER_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd><kbd>←</kbd><kbd>→</kbd> Передвинуть выделенную точку<br><kbd class='text'>Shift</kbd> Передвинуться на десять единиц<br><kbd class='text'>Tab</kbd> Переключиться между точками",
  "STEPS_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd> Увеличить или уменьшить шаги<br><kbd>←</kbd><kbd>→</kbd> 'Начало' или 'Конец'",
  "INLINE_TIMING_EDITOR_INVALID": "Старое значение <code>{0}</code> некорректно, отображаемая функция была заменена на <code>{1}</code>. Документ будет обновлен с первой правкой.",
  "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP": "Текущий цвет",
  "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP": "Оригинальный цвет",
  "COLOR_EDITOR_RGBA_BUTTON_TIP": "RGBa формат",
  "COLOR_EDITOR_HEX_BUTTON_TIP": "Hex формат",
  "COLOR_EDITOR_HSLA_BUTTON_TIP": "HSLa формат",
  "COLOR_EDITOR_0X_BUTTON_TIP": "Шестнадцатеричный (0x) формат",
  "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR": "{0} (Использовано {1} раз)",
  "COLOR_EDITOR_USED_COLOR_TIP_PLURAL": "{0} (Использовано {1} раза)",
  "CMD_JUMPTO_DEFINITION": "Перейти к определению",
  "CMD_SHOW_PARAMETER_HINT": "Показывать подсказки по аргументам функции",
  "NO_ARGUMENTS": "<нет аргументов>",
  "DETECTED_EXCLUSION_TITLE": "Проблема вывода файла JavaScript",
  "DETECTED_EXCLUSION_INFO": "{APP_NAME} столкнулся с проблемой при обработке <span class='dialog-filename'>{0}</span> .<br><br> Этот файл больше не будет обрабатываться для подсказок по коду, перехода к определению или быстрого редактирования. Чтобы снова включить этот файл, откройте <code>.brackets.json</code> в своем проекте и отредактируйте <code>jscodehints.detectedExclusions</code> .<br><br> Вероятно, это ошибка {APP_NAME}. Если вы можете предоставить копию этого файла, отправьте <a href='https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue'>сообщение об ошибке</a> со ссылкой на файл, указанный здесь.",
  "CMD_REFACTOR": "Рефакторинг",
  "CMD_EXTRACTTO_VARIABLE": "Извлечь в переменную",
  "CMD_EXTRACTTO_FUNCTION": "Извлечь в функцию",
  "ERROR_TERN_FAILED": "Не удалось получить данные от Tern",
  "ERROR_EXTRACTTO_VARIABLE_NOT_VALID": "Выбор не формирует выражение",
  "ERROR_EXTRACTTO_FUNCTION_NOT_VALID": "Выбранный блок должен представлять набор операторов или выражение",
  "ERROR_EXTRACTTO_VARIABLE_MULTICURSORS": "Извлечь в переменную не работает в мультикурсорах",
  "ERROR_EXTRACTTO_FUNCTION_MULTICURSORS": "Извлечь в функцию не работает в мультикурсорах",
  "EXTRACTTO_FUNCTION_SELECT_SCOPE": "Выберите область назначения",
  "EXTRACTTO_VARIABLE_SELECT_EXPRESSION": "Выберите выражение",
  "CMD_REFACTORING_RENAME": "Переименовать",
  "CMD_REFACTORING_TRY_CATCH": "Завернуть в Try Catch",
  "CMD_REFACTORING_CONDITION": "Обернуть в состоянии",
  "CMD_REFACTORING_GETTERS_SETTERS": "Создание геттеров/сеттеров",
  "CMD_REFACTORING_ARROW_FUNCTION": "Преобразовать в стрелочную функцию",
  "DESCRIPTION_CODE_REFACTORING": "Включить/отключить рефакторинг кода JavaScript",
  "ERROR_TRY_CATCH": "Выберите действительный код для включения в блок Try-catch.",
  "ERROR_WRAP_IN_CONDITION": "Выберите допустимый код для переноса в блок Condition",
  "ERROR_ARROW_FUNCTION": "Поместите курсор внутрь функционального выражения",
  "ERROR_GETTERS_SETTERS": "Поместите курсор на член выражения объекта",
  "ERROR_RENAME_MULTICURSOR": "Невозможно переименовать при использовании нескольких курсоров",
  "ERROR_RENAME_QUICKEDIT": "Невозможно переименовать этот идентификатор, так как он упоминается в другом месте за пределами этой функции.",
  "ERROR_RENAME_GENERAL": "Невозможно переименовать выделенный текст",
  "JSHINT_NAME": "JSHint",
  "CMD_ENABLE_QUICK_VIEW": "Быстрый просмотр при наведении",
  "CMD_ENABLE_SELECTION_VIEW": "Представление выбора",
  "TOOLTIP_CLICK_TO_EDIT_COLOR": "Нажмите здесь, чтобы изменить цвет",
  "CMD_TOGGLE_RECENT_PROJECTS": "Предыдущие проекты",
  "DOCS_MORE_LINK": "Подробнее…",
  "COLLAPSE_ALL": "Свернуть все",
  "EXPAND_ALL": "Развернуть все",
  "COLLAPSE_CURRENT": "Свернуть текущий",
  "EXPAND_CURRENT": "Развернуть текущий",
  "RECENT_FILES_DLG_HEADER": "Недавние файлы",
  "RECENT_FILES_DLG_CLEAR_BUTTON_LABEL": "чистый",
  "RECENT_FILES_DLG_CLEAR_BUTTON_TITLE": "Удалить файлы, не входящие в рабочий набор",
  "DESCRIPTION_CLOSE_BRACKETS": "true, чтобы автоматически закрывать скобки, квадратные и круглые скобки",
  "DESCRIPTION_CLOSE_OTHERS_ABOVE": "false, чтобы удалить «Закрыть другие выше» из контекстного меню «Рабочие файлы».",
  "DESCRIPTION_CLOSE_OTHERS_BELOW": "false, чтобы удалить «Закрыть другие ниже» из контекстного меню «Рабочие файлы».",
  "DESCRIPTION_CLOSE_OTHERS": "false, чтобы удалить «Закрыть другие» из контекстного меню «Рабочие файлы».",
  "DESCRIPTION_CLOSE_TAGS": "Устанавливает параметры закрытия тега",
  "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS": "Массив тегов, которые не должны автоматически закрываться",
  "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING": "Закрыть, когда набирается > открывающего тега",
  "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING": "Закрыть, когда / из закрывающего тега введено",
  "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS": "Массив тегов, который при открытии имеет пустую строку",
  "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD": "Значение true, чтобы всегда создавать складные маркеры разделов при изменении уровня отступа.",
  "DESCRIPTION_CODE_FOLDING_ENABLED": "true, чтобы включить свертывание кода",
  "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER": "Значение true, чтобы сделать маркеры свертывания секций видимыми только при наведении указателя мыши на желоб.",
  "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL": "Ограничивает количество уровней в глубину Применяется свернуть все",
  "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE": "Минимум строк до появления значка сворачиваемого раздела",
  "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES": "Значение true, чтобы помнить свернутые разделы при закрытии и повторном открытии файла или проекта.",
  "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE": "Значение true, чтобы включить свертывание кода для выделенного текста в редакторе.",
  "DESCRIPTION_DISABLED_DEFAULT_EXTENSIONS": "Расширения по умолчанию, которые отключены",
  "DESCRIPTION_ATTR_HINTS": "Включить/отключить подсказки атрибутов HTML",
  "DESCRIPTION_CSS_PROP_HINTS": "Включить/отключить подсказки свойств CSS/LESS/SCSS",
  "DESCRIPTION_JS_HINTS": "Включить/отключить подсказки кода JavaScript",
  "DESCRIPTION_JS_HINTS_TYPE_DETAILS": "Включить/отключить сведения о типе данных в подсказках по коду JavaScript",
  "DESCRIPTION_PREF_HINTS": "Включить/отключить подсказки кода настроек",
  "DESCRIPTION_SPECIAL_CHAR_HINTS": "Включить/отключить подсказки объектов HTML",
  "DESCRIPTION_SVG_HINTS": "Включить/отключить подсказки кода SVG",
  "DESCRIPTION_HTML_TAG_HINTS": "Включить/отключить подсказки тегов HTML",
  "DESCRIPTION_URL_CODE_HINTS": "Включить/отключить подсказки URL в HTML и CSS/LESS/SCSS",
  "DESCRIPTION_DRAG_DROP_TEXT": "Включить/отключить функцию перетаскивания",
  "DESCRIPTION_HEALTH_DATA_TRACKING": "Включить отслеживание данных о здоровье",
  "DESCRIPTION_HIGHLIGHT_MATCHES": "Включает автоматическое выделение совпадающих строк по всему документу.",
  "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN": "Выделите все строки, соответствующие токену, в котором в данный момент находится курсор (выбор не требуется)",
  "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY": "Выделять только в том случае, если выбор является полным токеном",
  "DESCRIPTION_INSERT_HINT_ON_TAB": "Значение true, чтобы вставить текущую выбранную подсказку кода на вкладке",
  "DESCRIPTION_NO_HINTS_ON_DOT": "Значение true , чтобы автоматически не отображать подсказки кода JS, когда . набирается",
  "DESCRIPTION_JSHINT_OPTIONS": "Объект с параметрами по умолчанию для JSHint. См. следующий URL-адрес для всех доступных параметров JSHint: https://jshint.com/docs/options/",
  "DESCRIPTION_LANGUAGE": "Языковые настройки",
  "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS": "Дополнительные сопоставления расширения файла с названием языка",
  "DESCRIPTION_LANGUAGE_FILE_NAMES": "Дополнительные сопоставления имени файла с названием языка",
  "DESCRIPTION_LINEWISE_COPY_CUT": "Выполнение копирования и вырезания при отсутствии выбора приведет к копированию или вырезанию целых строк, в которых есть курсоры.",
  "DESCRIPTION_INPUT_STYLE": "Выбирает, как CodeMirror обрабатывает ввод и фокус. Это может быть textarea, что используется по умолчанию, или contenteditable, что лучше для программ чтения с экрана (нестабильно).",
  "DESCRIPTION_LINTING_ENABLED": "true, чтобы включить проверку кода",
  "DESCRIPTION_ASYNC_TIMEOUT": "Время в миллисекундах, по истечении которого тайм-аут асинхронных линтеров",
  "DESCRIPTION_LINTING_PREFER": "Массив линтеров для запуска в первую очередь",
  "DESCRIPTION_LIVE_DEV_MULTIBROWSER": "Значение true, чтобы включить экспериментальный предварительный просмотр в реальном времени.",
  "DESCRIPTION_USE_PREFERED_ONLY": "true для запуска только провайдеров, указанных в linting.prefer",
  "DESCRIPTION_MAX_CODE_HINTS": "Одновременно отображается максимальное количество подсказок по коду",
  "DESCRIPTION_PATH": "Конкретные настройки пути",
  "DESCRIPTION_PROXY": "URL-адрес прокси-сервера, используемого для установки расширения.",
  "DESCRIPTION_SCROLL_PAST_END": "true, чтобы разрешить прокрутку за пределы документа",
  "DESCRIPTION_SHOW_CODE_HINTS": "false, чтобы отключить все подсказки кода",
  "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING": "Сохраняет видимость мигающего курсора при выделении текста",
  "DESCRIPTION_SHOW_LINE_NUMBERS": "Значение true, чтобы отображать номера строк в «желобе» слева от кода.",
  "DESCRIPTION_SMART_INDENT": "Автоматический отступ при создании нового блока",
  "DESCRIPTION_SOFT_TABS": "false, чтобы отключить поведение мягких вкладок",
  "DESCRIPTION_SORT_DIRECTORIES_FIRST": "Значение true, чтобы сначала отсортировать каталоги в дереве проекта.",
  "DESCRIPTION_SPACE_UNITS": "Количество пробелов, используемых для отступа на основе пробелов",
  "DESCRIPTION_STATIC_SERVER_PORT": "Номер порта, который встроенный сервер должен использовать для Live Preview",
  "DESCRIPTION_STYLE_ACTIVE_LINE": "Значение true, чтобы выделить фоновый цвет строки, на которой находится курсор",
  "DESCRIPTION_TAB_SIZE": "Количество пробелов для отображения вкладок",
  "DESCRIPTION_USE_TAB_CHAR": "true для использования табуляции вместо пробела",
  "DESCRIPTION_UPPERCASE_COLORS": "Значение true для создания шестнадцатеричных цветов в верхнем регистре во встроенном редакторе цветов.",
  "DESCRIPTION_WORD_WRAP": "Обтекание строк, которые превышают ширину области просмотра",
  "DESCRIPTION_SEARCH_AUTOHIDE": "Закройте поиск, как только редактор сфокусируется",
  "DESCRIPTION_DETECTED_EXCLUSIONS": "Список файлов, которые, как было обнаружено, приводят к выходу Tern из-под контроля.",
  "DESCRIPTION_INFERENCE_TIMEOUT": "Количество времени, по истечении которого Терн истечет при попытке понять файлы.",
  "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR": "true для отображения ошибок в строке состояния",
  "DESCRIPTION_QUICK_VIEW_ENABLED": "true, чтобы включить быстрый просмотр",
  "DESCRIPTION_SELECTION_VIEW_ENABLED": "true, чтобы включить представление выбора",
  "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW": "Значение true, чтобы показывать превью изображений для URL-адресов без расширений.",
  "DESCRIPTION_NUMBER_QUICK_VIEW": "true, чтобы отображать Quick View при наведении курсора на числа в редакторе",
  "DESCRIPTION_THEME": "Выберите тему {APP_NAME}",
  "DESCRIPTION_USE_THEME_SCROLLBARS": "true, чтобы разрешить настраиваемые полосы прокрутки",
  "DESCRIPTION_LINTING_COLLAPSED": "true, чтобы свернуть панель ворса",
  "DESCRIPTION_FONT_FAMILY": "Изменить семейство шрифтов",
  "DESCRIPTION_FONT_SIZE": "Изменить размер шрифта; например 13 пикселей",
  "DESCRIPTION_FIND_IN_FILES_NODE": "true, чтобы включить поиск по узлу",
  "DESCRIPTION_FIND_IN_FILES_INSTANT": "true, чтобы включить мгновенный поиск",
  "DESCRIPTION_FONT_SMOOTHING": "Только для Mac: «субпиксельное сглаживание» для включения субпиксельного сглаживания или «сглаживание» для сглаживания оттенков серого.",
  "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW": "false, чтобы отключить открытие файла настроек в режиме разделенного просмотра",
  "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE": "false, чтобы открыть файл настроек пользователя в левой/верхней панели",
  "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED": "Значение true, чтобы свернуть панели после закрытия последнего файла из панели с помощью кнопки закрытия заголовка панели",
  "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS": "Переключите, когда отображать кнопки закрытия и перелистывания в заголовке.",
  "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT": "/*\n * Это файл только для чтения с поддерживаемыми настройками\n * через {APP_NAME}.\n * Используйте этот файл в качестве ссылки для изменения ваших настроек\n * файл \"brackets.json\" открыт в другой панели.\n * Для получения дополнительной информации о том, как использовать настройки внутри\n * {APP_NAME}, см. веб-страницу по адресу https://github.com/adobe/brackets/wiki/How-to-Use-Bracckets#preferences.\n */",
  "DEFAULT_PREFERENCES_JSON_DEFAULT": "По умолчанию",
  "DESCRIPTION_PURE_CODING_SURFACE": "Значение true, чтобы включить режим только кода и скрыть все остальные элементы пользовательского интерфейса в {APP_NAME}.",
  "DESCRIPTION_INDENT_LINE_COMMENT": "Значение true, чтобы включить отступ строковых комментариев.",
  "DESCRIPTION_RECENT_FILES_NAV": "Включить/отключить навигацию в последних файлах",
  "DESCRIPTION_LIVEDEV_WEBSOCKET_PORT": "Порт, на котором работает WebSocket Server для Live Preview",
  "DESCRIPTION_LIVE_DEV_HIGHLIGHT_SETTINGS": "Настройки подсветки предварительного просмотра в реальном времени",
  "DESCRIPTION_LIVEDEV_ENABLE_REVERSE_INSPECT": "false, чтобы отключить предварительный просмотр в реальном времени",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW": "Нечего превью!",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW_DETAILS": "Пожалуйста, выберите файл HTML для предварительного просмотра",
  "DOWNLOAD_FAILED": "Загрузка не удалась.",
  "DOWNLOAD_COMPLETE": "Загрузка завершена!",
  "UPDATE_SUCCESSFUL": "Обновление успешно!",
  "UPDATE_FAILED": "Не удалось обновить!",
  "VALIDATION_FAILED": "Проверка не удалась!",
  "INITIALISATION_FAILED": "Ошибка инициализации!",
  "CLEANUP_FAILED": "Очистка не удалась!",
  "WARNING_TYPE": "Предупреждение!",
  "CLICK_RESTART_TO_UPDATE": "Нажмите «Перезагрузить», чтобы обновить Brackets.",
  "UPDATE_ON_NEXT_LAUNCH": "Обновление будет применено при перезапуске.",
  "GO_TO_SITE": "Перейдите на <a href = \"http://brackets.io/\">страницу скобок.io</a> , чтобы повторить попытку.",
  "INTERNET_UNAVAILABLE": "Нет подключения к Интернету.",
  "UPDATEDIR_READ_FAILED": "Каталог обновления не может быть прочитан.",
  "UPDATEDIR_CLEAN_FAILED": "Каталог обновлений не может быть очищен.",
  "INITIAL_DOWNLOAD": "Загрузка обновления...",
  "RETRY_DOWNLOAD": "Загрузка не удалась. Повторная попытка... Попытка",
  "VALIDATING_INSTALLER": "Загрузка завершена! Проверка установщика...",
  "CHECKSUM_DID_NOT_MATCH": "Контрольная сумма не совпала.",
  "INSTALLER_NOT_FOUND": "Установщик не найден.",
  "DOWNLOAD_ERROR": "Произошла ошибка при загрузке.",
  "NETWORK_SLOW_OR_DISCONNECTED": "Сеть отключена или работает слишком медленно.",
  "RESTART_BUTTON": "Запустить снова",
  "LATER_BUTTON": "Потом",
  "DESCRIPTION_AUTO_UPDATE": "Включить/отключить автоматическое обновление скобок",
  "AUTOUPDATE_ERROR": "Ошибка!",
  "AUTOUPDATE_IN_PROGRESS": "Обновление уже выполняется.",
  "NUMBER_WITH_PERCENTAGE": "{0}%",
  "CMD_FIND_RELATED_FILES": "Найти связанные файлы",
  "PHP_VERSION_INVALID": "Ошибка анализа версии PHP. Пожалуйста, проверьте вывод команды «php –version».",
  "PHP_UNSUPPORTED_VERSION": "Установите среду выполнения PHP7, чтобы включить инструменты, связанные с PHP, такие как подсказки по коду, подсказки по параметрам, переход к определению и многое другое. Найдена версия: {0}",
  "PHP_EXECUTABLE_NOT_FOUND": "Среда выполнения PHP не найдена. Установите среду выполнения PHP7 и соответствующим образом обновите «executablePath» в настройках PHP. Это включает инструменты, связанные с PHP, такие как подсказки кода, подсказки параметров, переход к определению и многое другое.",
  "PHP_PROCESS_SPAWN_ERROR": "Код ошибки {0} обнаружен при запуске процесса PHP.",
  "PHP_SERVER_ERROR_TITLE": "Ошибка",
  "PHP_SERVER_MEMORY_LIMIT_INVALID": "Предоставленный вами лимит памяти недействителен. Просмотрите настройки PHP, чтобы установить правильное значение.",
  "DESCRIPTION_PHP_TOOLING_CONFIGURATION": "Параметры конфигурации PHP Tooling по умолчанию",
  "OPEN_PREFERENNCES": "Открыть настройки",
  "LANGUAGE_TOOLS_PREFERENCES": "Настройки для языковых инструментов",
  "FIND_ALL_REFERENCES": "Найти все ссылки",
  "REFERENCES_IN_FILES": "использованная литература",
  "REFERENCE_IN_FILES": "ссылка",
  "REFERENCES_NO_RESULTS": "Нет доступных ссылок для текущей позиции курсора",
  "CMD_FIND_DOCUMENT_SYMBOLS": "Найти символы документа",
  "CMD_FIND_PROJECT_SYMBOLS": "Найдите символы проекта",
  "REMOTE_DEBUGGING_ENABLED": "Удаленная отладка включена на локальном хосте:",
  "REMOTE_DEBUGGING_PORT_INVALID": "Невозможно включить удаленную отладку для порта {0}. Номера портов должны быть между {1} и {2}.",
  "DESCRIPTION_EXTERNAL_APPLICATION_ASSOCIATE": "Сопоставление расширения файла с внешними приложениями. Синтаксис: \"<file_type>\": \"<default|applicationName|ApplicationPath>\", используйте \"default\" для открытия файлов в системном приложении по умолчанию для данного типа файлов.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_TITLE": "Открывайте графические файлы во внешних редакторах.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_MSG": "В вашей текущей папке есть типы графических файлов, которые не поддерживаются {APP_NAME}.<br/> Теперь вы можете связать определенные типы файлов с внешними редакторами. После связывания вы можете открывать графические файлы, такие как .xd, .psd, .jpg, .png, .ai, .svg, в их приложениях по умолчанию, дважды щелкнув файлы в дереве файлов.<br/><br/> Нажмите кнопку «ОК», чтобы связать типы графических файлов с соответствующими приложениями по умолчанию.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_CNF_MSG": "Следующие типы файлов были успешно связаны с приложениями по умолчанию.<br/> {0} У вас есть возможность изменить свои предпочтения относительно удаления или добавления новых ассоциаций типов файлов в скобках.json, перейдя в меню «Отладка-&gt;Открыть файл настроек».",
  "UNSUPPORTED_BROWSER": "Браузер не поддерживается",
  "UNSUPPORTED_BROWSER_MOBILE": "Мобильные устройства и планшеты в настоящее время не полностью поддерживаются. Вы можете закрыть этот диалог, но некоторые функции Phoenix не будут работать в этом браузере.",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER": "Браузер не поддерживает Открыть папку. Пожалуйста, используйте Chrome, Edge или Opera, чтобы открывать локальные папки.",
  "UNSUPPORTED_BROWSER_MESSAGE_LINE1": "Пожалуйста, используйте один из поддерживаемых браузеров ниже.",
  "UNSUPPORTED_BROWSER_MESSAGE_LINE2": " Мы прилагаем все усилия, чтобы сделать Phoenix доступным в большем количестве браузеров. Вы можете закрыть этот диалог, но некоторые функции Phoenix не будут работать в этом браузере.",
  "CANNOT_PUBLISH_LARGE_PROJECT": "Невозможно опубликовать большой проект",
  "CANNOT_PUBLISH_LARGE_PROJECT_MESSAGE": "Phoenix все еще находится в экспериментальной альфе. Мы еще не включили синхронизацию проектов с более чем 500 файлами.",
  "SHARE_WEBSITE": "Опубликовать и поделиться веб-сайтом?",
  "PUBLISH": "Публиковать",
  "PUBLISH_CONSENT_MESSAGE": "Быстро просматривайте изменения и делитесь своим веб-сайтом с другими. Phoenix может опубликовать для вас этот веб-сайт по адресу {0}. Опубликованные ссылки будут действительны в течение 7 дней. </br>Вы хотите опубликовать и поделиться своим веб-сайтом?",
  "PUBLISH_SYNC_IN_PROGRESS": "Выполняется синхронизация для предварительного просмотра...",
  "PUBLISH_PAGE": "Нажмите, чтобы опубликовать и поделиться этим сайтом",
  "PUBLISH_VIEW_PAGE": "Нажмите, чтобы просмотреть опубликованную страницу",
  "MISSING_FIELDS": "Отсутствующие поля",
  "PLEASE_FILL_ALL_REQUIRED": "Пожалуйста, заполните все обязательные поля, выделенные красным",
  "CODE_EDITOR": "Редактор кода",
  "BUILD_THE_WEB": "Создайте сеть",
  "IMPORT_PROJECT": "Импорт проекта",
  "GITHUB_PROJECT": "Проект GitHub",
  "NEW_PROJECT_FROM_GITHUB": "Новый проект с GitHub",
  "GITHUB_REPO_URL": "URL-адрес репозитория GitHub:",
  "CREATE_PROJECT": "Создать проект",
  "SETTING_UP_PROJECT": "Настройка проекта",
  "LOCATION": "Расположение :",
  "DOWNLOADING": "Загрузка...",
  "EXTRACTING_FILES_PROGRESS": "Извлечение файлов {0} из {1}.",
  "DOWNLOAD_FAILED_MESSAGE": "Убедитесь, что URL-адрес загрузки является допустимым. </br>Примечание. Поскольку Phoenix находится в стадии альфа-тестирования, URL-адреса частных репозиториев и GitHub размером более 25 МБ не допускаются.",
  "PLEASE_SELECT_A_FOLDER": "Пожалуйста, выберите папку...",
  "UNZIP_IN_PROGRESS": "Распаковка файлов...",
  "UNZIP_FAILED": "Ошибка: Не удалось разархивировать.",
  "CONFIRM_REPLACE_TITLE": "Подтвердить замену",
  "KEEP_BOTH": "Оставь оба",
  "EXPLORE": "HTML-игры",
  "BLOG": "Блог",
  "PHOENIX_DEFAULT_PROJECT": "Проект по умолчанию",
  "PROJECT_NAME": "Название проекта:",
  "NEW_HTML": "Новый HTML-проект",
  "LICENSE": "Лицензия:",
  "CREDITS": "Кредиты:",
  "PREVIEW": "Предварительный просмотр",
  "BUILD_WEBSITE": "Создать сайт",
  "VIEW_MORE": "Посмотреть больше...",
  "NEW_PROJECT_NOTIFICATION": "Щелкните этот значок, чтобы<br/> создать новый проект.</br> <a href='#' style='float:right;'>Ok</a>",
  "DEFAULT_PROJECT_NOTIFICATION": "Щелкните здесь, чтобы открыть<br/> <b>проект по умолчанию</b> в phoenix.</br> <a href='#' style='float:right;'>Ok</a>",
  "DIRECTORY_REPLACE_MESSAGE": "Выбранная папка <span class='dialog-filename'>{0}</span> не пуста. Вы уверены, что хотите заменить содержимое папки проектом?",
  "BUILD_WEBSITE_SECTION": "Создать сайт",
  "LEARN_SECTION": "Учитесь на примерах",
  "WEBPAGE_HOME_PAGE": "Домашняя страница",
  "WEBPAGE_BLOG": "Страница блога",
  "WEBPAGE_DASHBOARD": "HTML-панель",
  "WEBPAGE_BOOTSTRAP_EXAMPLES": "Примеры начальной загрузки",
  "PROJECTS_AT_A_GLANCE": "Ваши проекты с первого взгляда",
  "PROJECT_AT_GLANCE_DESCRIPTION": "Создавайте новые проекты или открывайте существующие папки проектов со своего устройства здесь.",
  "GUIDED_LIVE_PREVIEW": "Внесите некоторые изменения в код HTML-файла, чтобы увидеть предварительный просмотр в реальном времени.</br> <a href='#' style='float:right;'>Хорошо</a>",
  "GUIDED_LIVE_PREVIEW_POPOUT": "Нажмите эту кнопку, чтобы открыть предварительный просмотр в новой вкладке.</br> <a href='#' style='float:right;'>Ok</a>",
  "TEST_TRANSLATE": "используйте это для проверки переводов",
  "BEAUTIFY_ERROR": "Не удалось украсить код. Проверьте синтаксис.",
  "BEAUTIFY_ERROR_ORIGINAL_CHANGED": "Не смог украсить. Текст редактора изменен после благоустройства.",
  "BEAUTIFY_PROJECT_BUSY_MESSAGE": "Украшение файла {0}",
  "BEAUTIFY_ERROR_SELECTION": "Не удалось украсить.</br>Выбран неполный блок кода или недопустимый синтаксис.",
  "BEAUTIFY_OPTIONS": "Параметры, управляющие работой Beautify Code",
  "BEAUTIFY_OPTION_PRINT_WIDTH": "Укажите длину строки, на которую будет накладываться beautifier",
  "BEAUTIFY_OPTION_SEMICOLON": "Добавляйте точку с запятой в конце каждого оператора",
  "BEAUTIFY_OPTION_SINGLE_QUOTE": "Используйте одинарные кавычки вместо двойных кавычек",
  "BEAUTIFY_OPTION_QUOTE_PROPS": "Изменение, когда свойства объектов указаны в кавычках",
  "BEAUTIFY_OPTION_BRACKET_SAME_LINE": "Поместите > многострочного элемента HTML (HTML, JSX, Vue, Angular) в конец последней строки, а не в одиночку на следующей строке (не относится к самозакрывающимся элементам)",
  "BEAUTIFY_OPTION_SINGLE_ATTRIBUTE_PER_LINE": "Применять один атрибут на строку в HTML, Vue и JSX",
  "BEAUTIFY_OPTION_PROSE_WRAP": "Оберните прозу, если она превышает ширину печати в файлах уценки",
  "BEAUTIFY_OPTION_PRINT_TRAILING_COMMAS": "Печатайте конечные запятые везде, где это возможно, в многострочных синтаксических структурах, разделенных запятыми."
});