/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "시스템 언어",
  "PROJECT_BUSY": "진행 중인 프로젝트 작업",
  "DUPLICATING": "{0} 복제 중",
  "MOVING": "이사 {0}",
  "COPYING": "{0} 복사 중",
  "DELETING": "{0} 삭제 중",
  "RENAMING": "이름 바꾸기",
  "STORED_IN_YOUR_BROWSER": "브라우저에 저장됨",
  "SUPPORT_US_OPEN_COLLECTIVE": "GitHub 후원자에서 우리를 지원하세요",
  "GENERIC_ERROR": "(에러 {0})",
  "NOT_FOUND_ERR": "파일을 찾을 수 없습니다.",
  "NOT_READABLE_ERR": "파일을 읽을 수 없습니다.",
  "EXCEEDS_MAX_FILE_SIZE": "{0} MB보다 큰 파일은 {APP_NAME}에서 열 수 없습니다.",
  "NO_MODIFICATION_ALLOWED_ERR": "대상 디렉토리를 변경할 수 없습니다.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "파일을 수정할 수 있는 권한이 없습니다.",
  "CONTENTS_MODIFIED_ERR": "{APP_NAME} 외부에서 파일이 변경되었습니다.",
  "UNSUPPORTED_ENCODING_ERR": "{APP_NAME}는 현재 UTF-8 인코딩된 파일만 지원합니다.",
  "ENCODE_FILE_FAILED_ERR": "{APP_NAME}에서 파일 콘텐츠를 인코딩할 수 없습니다.",
  "DECODE_FILE_FAILED_ERR": "{APP_NAME}에서 파일 내용을 디코딩할 수 없습니다.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "{APP_NAME}은(는) 현재 UTF-16으로 인코딩된 텍스트 파일을 지원하지 않습니다.",
  "FILE_EXISTS_ERR": "파일 또는 디렉토리가 이미 있습니다.",
  "FILE": "파일",
  "FILE_TITLE": "파일",
  "DIRECTORY": "디렉토리",
  "DIRECTORY_TITLE": "디렉토리",
  "DIRECTORY_NAMES_LEDE": "디렉토리 이름",
  "FILENAMES_LEDE": "파일 이름",
  "FILENAME": "파일 이름",
  "DIRECTORY_NAME": "디렉토리 이름",
  "ERROR_LOADING_PROJECT": "프로젝트 로드에 실패했습니다",
  "OPEN_DIALOG_ERROR": "'파일 열기' 대화 상자를 표시 하는 중 에러가 발생했습니다. (에러 {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "디렉토리 <span class='dialog-filename'>{0}</span>을 읽는 중 에러가 발생했습니다. (에러 {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "디렉토리 <span class='dialog-filename'>{0}</span>의 내용을 읽는 중에 에러가 발생했습니다. (에러 {1})",
  "ZOOM_WITH_SHORTCUTS": "키보드 단축키를 사용하여 확대/축소",
  "ZOOM_WITH_SHORTCUTS_DETAILS": "확대하려면 키보드 단축키 <code><i>{0}</i></code> 를 사용하고 축소하려면 <code><i>{1}</i></code> 사용하십시오.",
  "ERROR_OPENING_FILE_TITLE": "파일을 열던 중에 에러가 발생했습니다.",
  "ERROR_OPENING_FILE": "파일 <span class='dialog-filename'>{0}</span>을 열던 중에 에러가 발생했습니다. {1}",
  "ERROR_OPENING_FILES": "다음의 파일을 열던 중에 에러가 발생했습니다 :",
  "ERROR_RELOADING_FILE_TITLE": "디스크에서 변경 내용을 다시 로드 하던 중에 에러가 발생했습니다.",
  "ERROR_RELOADING_FILE": "파일 <span class='dialog-filename'>{0}</span>을 다시 읽어 오던 중에 에러가 발생했습니다. {1}",
  "ERROR_SAVING_FILE_TITLE": "파일을 저장하는 동안 에러가 발생했습니다.",
  "ERROR_SAVING_FILE": "파일 <span class='dialog-filename'>{0}</span>을 저장하던 중에 에러가 발생했습니다. {1}",
  "ERROR_RENAMING_FILE_TITLE": "파일의 이름을 변경하던 중에 에러가 발생했습니다.",
  "ERROR_RENAMING_FILE": "파일 <span class='dialog-filename'>{0}</span>의 이름을 변경하던 중에 에러가 발생했습니다. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "파일 또는 디렉토리가 현재 열려 있는 프로젝트의 일부가 아닙니다. 안타깝게도 현재로서는 프로젝트 파일만 이름을 바꿀 수 있습니다.",
  "ERROR_MOVING_FILE_TITLE": "{0} 이동 오류",
  "ERROR_MOVING_FILE": "{2} <span class='dialog-filename'>{0}</span> 을(를) 이동하는 동안 오류가 발생했습니다. {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "파일/폴더는 현재 프로젝트의 일부가 아니므로 이동할 수 없습니다.",
  "ERROR_DELETING_FILE_TITLE": "파일 삭제 에러",
  "ERROR_DELETING_FILE": "파일을 삭제할 때 에러가 발생했습니다 <span class='dialog-filename'>{0}</span>. {1}",
  "INVALID_FILENAME_TITLE": "잘못된 {0}이름",
  "CANNOT_PASTE_TITLE": "{0}을(를) 붙여넣을 수 없습니다.",
  "CANNOT_DOWNLOAD_TITLE": "{0}을(를) 다운로드할 수 없습니다",
  "ERR_TYPE_DOWNLOAD_FAILED": "<span class='dialog-filename'>{0}</span> 을(를) 다운로드하는 동안 오류가 발생했습니다.",
  "ERR_TYPE_PASTE_FAILED": "<span class='dialog-filename'>{0}</span> 을(를) <span class='dialog-filename'>{1}</span> 에 붙여넣는 동안 오류가 발생했습니다.",
  "CANNOT_DUPLICATE_TITLE": "복제할 수 없음",
  "ERR_TYPE_DUPLICATE_FAILED": "<span class='dialog-filename'>{0}</span> 을(를) 복제하는 동안 오류가 발생했습니다.",
  "ERR_TYPE_DUPLICATE_FAILED_NO_FILE": "복제할 파일을 선택하세요.",
  "INVALID_FILENAME_MESSAGE": "파일 이름에는 다음 문자를 포함 할 수 없습니다: {0} 또는 시스템의 모든 예약어",
  "ENTRY_WITH_SAME_NAME_EXISTS": "<span class='dialog-filename'>{0}</span> 이름을 가진 파일 또는 디렉토리가 이미 존재합니다.",
  "ERROR_CREATING_FILE_TITLE": "{0}를 만들던 중에 에러가 발생했습니다",
  "ERROR_CREATING_FILE": "{0} <span class='dialog-filename'>{1}</span>를 만들던 중에 에러가 발생했습니다.{2}",
  "ERROR_MIXED_DRAGDROP": "다른 파일을 여는 도중에는 폴더를 열 수 없습니다.",
  "ERROR_KEYMAP_TITLE": "사용자 키맵 파일을 읽는 중 에러가 발생했습니다",
  "ERROR_KEYMAP_CORRUPT": "키맵 파일의 JSON 형식이 올바르지 않습니다. 형식을 올바르게 수정할 수 있도록 파일이 열릴 것입니다",
  "ERROR_LOADING_KEYMAP": "키맵 파일이 올바르지 않은 UTF-8로 인코딩되어 있어 읽을 수 없습니다",
  "ERROR_RESTRICTED_COMMANDS": "다음 명령에 대한 단축키를 다시 설정할 수 없습니다: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "다음 단축키를 다시 설정할 수 없습니다: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "다음 명령에 대해 단축키를 여러 개 할당하려 했습니다: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "다음 단축키에 대해 여러 개의 명령어가 설정되어 있습니다: {0}",
  "ERROR_INVALID_SHORTCUTS": "다음 단축키는 올바르지 않습니다: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "존재하지 안는 명령어애 단축키를 설정했습니다: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "환경설정을 읽는 중 에러가 발생했습니다",
  "ERROR_PREFS_PROJECT_LINT": "프로젝트 환경설정",
  "ERROR_PREFS_PROJECT_LINT_MESSAGE": "오류: 프로젝트에 '.brackets.json' 및 '.phcode.json' 파일이 모두 포함되어 있어 충돌이 발생합니다. `.brackets.json` 또는 `.phcode.json`을 삭제한 후 프로젝트를 다시 로드하세요.",
  "ERROR_PREFS_CORRUPT": "환경설정 파일의 JSON 형식이 올바르지 않습니다. 형식을 올바르게 수정할 수 있도록 파일이 열릴 것입니다. 수정한 내용을 반영하려면 {APP_NAME}를 재시작해야 합니다.",
  "ERROR_PROJ_PREFS_CORRUPT": "프로젝트 환경설정 파일의 JSON 형식이 올바르지 않습니다. 형식을 올바르게 수정할 수 있도록 파일이 열릴 것입니다. 변경 사항을 적용하려면 프로젝트를 다시 로드해야 합니다.",
  "ERROR_IN_BROWSER_TITLE": "{APP_NAME}는 아직 브라우저에서 실행되지 않습니다.",
  "ERROR_IN_BROWSER": "{APP_NAME}는 HTML로 구축되어 있지만 데스크톱 응용 프로그램으로 실행하여 로컬 파일을 편집 할 수 있습니다. {APP_NAME}를 실행하기 위해 <b>github.com / adobe / brackets-shell</b> 저장소 응용 프로그램 셸을 사용하십시오.",
  "ERROR_MAX_FILES_TITLE": "파일을 인덱스 하던 중에 에러가 발생했습니다.",
  "ERROR_MAX_FILES": "인덱싱 할 수 있는 파일의 최대 수에 도달했습니다. 인덱스에서 파일 검색 기능이 제대로 작동하지 않을 수 있습니다.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "브라우저 시작 에러",
  "ERROR_CANT_FIND_CHROME": "Google Chrome 브라우저를 찾을 수 없습니다. 설치되어 있는지 확인하십시오.",
  "ERROR_LAUNCHING_BROWSER": "브라우저를 시작하던 중에 에러가 발생했습니다. (에러 {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "실시간 미리보기 에러",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "브라우저에 연결합니다",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "실시간 미리보기에 연결하려면 원격 디버깅을 사용하여 Chrome을 다시 시작해야 합니다. <br /> Chrome을 다시 시작하고 원격 디버깅을 사용하시겠습니까?",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "실시간 미리보기 페이지를 읽을 수 없습니다.",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "서버 측 파일 실시간 미리보기를 시작하려면 이 프로젝트의 기본 URL을 지정해야 합니다.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "실시간 미리보기에 사용되는 HTTP 서버를 시작할 때 에러가 발생했습니다. 잠시 후에 다시 시도하세요.",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "자세한 내용은 <a href='{0}' title='{0}'> Live Development 연결 오류 문제 해결 </a>를 참조하세요.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "실시간 미리보기",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "실시간 미리보기: 연결 중 …",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "실시간 미리보기: 초기화 중…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "실시간 미리보기 서버 활성화",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "실시간 미리보기",
  "LIVE_DEV_TOOLTIP_SHOW_IN_EDITOR": "{0} - 편집기에 표시…",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "라이브 미리 보기로 파일 선택",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "페이지 새로고침",
  "LIVE_DEV_TOGGLE_LIVE_HIGHLIGHT": "실시간 미리보기 하이라이트 전환",
  "LIVE_DEV_CLICK_POPOUT": "새 창으로 실시간 미리보기 팝업",
  "LIVE_DEV_OPEN_CHROME": "Chrome에서 열기…",
  "LIVE_DEV_OPEN_SAFARI": "사파리에서 열기…",
  "LIVE_DEV_OPEN_EDGE": "엣지에서 열기…",
  "LIVE_DEV_OPEN_FIREFOX": "파이어폭스에서 열기…",
  "LIVE_DEV_OPEN_ERROR_TITLE": "{0}에서 실시간 미리보기를 여는 중 오류가 발생했습니다.",
  "LIVE_DEV_OPEN_ERROR_MESSAGE": "{0} 브라우저가 설치되어 있는지 확인하고 다시 시도하세요.",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "미리보기 페이지 고정 또는 고정 해제",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "실시간 프리 (구문 오류로 인해 업데이트되지 않습니다)",
  "LIVE_DEV_SETTINGS": "실시간 미리보기 설정…",
  "LIVE_DEV_SETTINGS_BANNER": "PHP, JSP 및 기타 서버 렌더링 파일을 실시간으로 미리 볼 수 있도록 사용자 정의 서버 설정",
  "LIVE_DEV_SETTINGS_TITLE": "실시간 미리보기 설정",
  "LIVE_DEV_SETTINGS_STARTUP": "시작 시 실시간 미리보기 패널 표시",
  "LIVE_DEV_SETTINGS_SERVER_PREFERENCE": "사용자 정의 개발 서버를 활성화하려면 true입니다.",
  "LIVE_DEV_SETTINGS_STARTUP_PREFERENCE": "시작 시 실시간 미리보기 패널을 표시하려면 true입니다.",
  "LIVE_DEV_SETTINGS_HOT_RELOAD_PREFERENCE": "서버가 핫 리로드를 지원하고 저장 시 실시간 미리 보기 리로드를 비활성화하는 경우 true입니다.",
  "LIVE_DEV_SETTINGS_USE_SERVER": "이 프로젝트에 사용자 정의 개발 서버 사용",
  "LIVE_DEV_SETTINGS_SERVE_PREFERENCE": "프로젝트의 개발 서버 URL(예: http://localhost:8000/php",
  "LIVE_DEV_SETTINGS_SERVER_INBUILT": "예. http://localhost:8000/php - 현재 내장 서버를 사용하고 있습니다.",
  "LIVE_DEV_SETTINGS_SERVER_ROOT": "프로젝트의 검색 폴더",
  "LIVE_DEV_SETTINGS_SERVER_ROOT_HELP": "예. www/(기본값은 /)",
  "LIVE_DEV_SETTINGS_SERVER_ROOT_PREF": "Development Server에서 서비스하는 프로젝트 내 경로입니다. www/(기본값은 /)",
  "LIVE_DEV_SETTINGS_RELOAD": "서버는 핫 리로드를 지원합니다",
  "LIVE_DEV_SETTINGS_RELOAD_HELP": "일부 서버는 전체 페이지를 다시 로드하지 않고도 코드 변경 사항이 페이지에 푸시되는 핫 다시 로드를 지원합니다.\n{APP_NAME}이 저장할 때마다 페이지를 새로고침하지 않도록 하려면 이 기능을 활성화하세요.",
  "LIVE_DEV_SETTINGS_FRAMEWORK": "서버 프레임워크",
  "LIVE_DEV_SETTINGS_FRAMEWORK_UNKNOWN": "알려지지 않은",
  "LIVE_DEV_SETTINGS_FRAMEWORK_PREFERENCES": "서버 프레임워크는 현재 docusaurus만 지원합니다.",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "브라우저의 개발 도구가 열려 있기 때문에 실시간 미리보기가 취소되었습니다뷰.",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "브라우저에서 페이지가 닫혀 있으므로 실시간 미리보기가 취소되었습니다.",
  "LIVE_DEV_NAVIGATED_AWAY": "브라우저에서 현재 프로젝트에 포함되지 않은 페이지로 이동했기 때문에 실시간 미리보기가 취소되었습니다.",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "알 수없는 원인 ({0})에 의해 실시간 미리보기가 취소되었습니다.",
  "SAVE_CLOSE_TITLE": "변경 사항 저장",
  "SAVE_CLOSE_MESSAGE": "문서 <span class='dialog-filename'>{0}</span> 변경 내용을 저장 하시겠습니까?",
  "SAVE_CLOSE_MULTI_MESSAGE": "다음 파일에 대한 변경 사항을 저장 하시겠습니까?",
  "EXT_MODIFIED_TITLE": "외부 변경 감지",
  "CONFIRM_DELETE_TITLE": "삭제 확인",
  "CONFIRM_FILE_DELETE": "<span class='dialog-filename'>{0}</span> 파일을 삭제하시겠습니까?",
  "CONFIRM_FOLDER_DELETE": "<span class='dialog-filename'>{0}</span> 폴더를 삭제 하시겠습니까?",
  "FILE_DELETED_TITLE": "파일이 삭제되었습니다",
  "EXT_MODIFIED_WARNING": "<span class='dialog-filename'>{0}</span>파일이 변경되었습니다.<br /><br />파일을 저장하여 이 변경 사항을 덮어씌우겠습니까?",
  "EXT_MODIFIED_MESSAGE": "<span class='dialog-filename'>{0}</span>파일에 저장되지 않은 변경 사항이 있습니다. <br /> 두 버전을 유지 하시겠습니까?",
  "EXT_DELETED_MESSAGE": "<span class='dialog-filename'>{0}</span>파일은 삭제되었지만 저장되지 않은 변경 사항이 있습니다. <br /> 변경을 유지 하시겠습니까?",
  "EXT_ALWAYS_MODIFIED_BUTTON_TOOLTIP": "프로젝트를 전환하거나 다시 시작할 때까지 항상 파일을 덮어씁니다.",
  "WINDOW_UNLOAD_WARNING": "다른 URL로 이동하고 {APP_NAME}을(를) 종료하시겠습니까?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "저장되지 않은 변경사항이 있습니다. 다른 URL로 이동하고 {APP_NAME}을(를) 종료하시겠습니까?",
  "DONE": "완료",
  "OK": "확인",
  "CANCEL": "취소",
  "DONT_SAVE": "저장하지 않음",
  "SAVE": "저장",
  "SAVE_AS": "다른 이름으로 저장…",
  "SAVE_AND_OVERWRITE": "덮어쓰기",
  "ALWAYS_OVERWRITE": "항상 덮어쓰기",
  "DELETE": "삭제",
  "BUTTON_YES": "예",
  "BUTTON_NO": "아니오",
  "FIND_MATCH_INDEX": "{1}개 중 {0}번째",
  "FIND_NO_RESULTS": "결과 없음",
  "FIND_QUERY_PLACEHOLDER": "검색할 내용…",
  "FIND_HISTORY_MAX_COUNT": "검색 기록의 최대 검색 항목 수",
  "REPLACE_PLACEHOLDER": "바꿀 내용…",
  "BUTTON_REPLACE_ALL": "일괄 변경…",
  "BUTTON_REPLACE_BATCH": "일괄…",
  "BUTTON_REPLACE_ALL_IN_FILES": "바꾸기…",
  "BUTTON_REPLACE": "바꾸기",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "다음 결과로 이동",
  "BUTTON_PREV_HINT": "이전 결과로 이동",
  "BUTTON_CASESENSITIVE_HINT": "대소문자 구별",
  "BUTTON_REGEXP_HINT": "정규식",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "바꾸기",
  "REPLACE_WITHOUT_UNDO_WARNING": "{0}개 이상의 파일을 수정해야 하므로, {APP_NAME}는 열지 않은 파일도 수정할 것입니다.<br />열지 않은 파일에서 바꾼 내용은 복원할 수 없습니다.",
  "BUTTON_REPLACE_WITHOUT_UNDO": "바꾸기",
  "OPEN_FILE": "파일 열기",
  "SAVE_FILE_AS": "다른 이름으로 저장",
  "CHOOSE_FOLDER": "폴더 선택",
  "RELEASE_NOTES": "릴리즈 노트",
  "NO_UPDATE_TITLE": "최신 버전입니다.",
  "NO_UPDATE_MESSAGE": "{APP_NAME} 최신 버전을 사용중입니다.",
  "FIND_REPLACE_TITLE_LABEL": "바꾸기",
  "FIND_REPLACE_TITLE_WITH": "→",
  "FIND_TITLE_LABEL": "찾기:",
  "FIND_TITLE_SUMMARY": "&mdash; {3}에서 {1}개를 찾았습니다",
  "FIND_NUM_FILES": "{0}개 {1}",
  "FIND_IN_FILES_SCOPED": "<span class='dialog-filename'>{0}</span>의",
  "FIND_IN_FILES_NO_SCOPE": "프로젝트",
  "FIND_IN_FILES_PROJECT_SCOPE": "프로젝트에서 찾기",
  "FIND_IN_FILES_PROJECT_SCOPE_FILTER": "{0}에서 찾기",
  "FIND_IN_FILES_PROJECT_SCOPE_REPLACE": "프로젝트에서 바꾸기",
  "FIND_IN_FILES_PROJECT_SCOPE_REPLACE_FILTER": "{0}에서 교체",
  "FIND_IN_FILES_ZERO_FILES": "검색 규칙이 {0}의 파일을 모두 대상에서 제외시켰습니다.",
  "FIND_IN_FILES_FILE": "파일",
  "FIND_IN_FILES_FILES": "파일",
  "FIND_IN_FILES_MATCH": "을 찾았습니다",
  "FIND_IN_FILES_MATCHES": "을 찾았습니다",
  "FIND_IN_FILES_MORE_THAN": "이상",
  "FIND_IN_FILES_PAGING": "{0}&mdash;{1}",
  "FIND_IN_FILES_FILE_PATH": "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "Ctrl/Cmd를 클릭하면 전부 펼치거나 접습니다",
  "FIND_IN_FILES_INDEXING": "빠른 검색을 위한 색인 중…",
  "FIND_IN_FILES_SEARCHING": "파일 검색 중...",
  "FIND_IN_FILES_SEARCHING_IN": "{0}에",
  "FIND_IN_FILES_INDEXING_PROGRESS": "빠른 검색을 위해 파일 {1}개 중 {0} 색인 생성 중…",
  "REPLACE_IN_FILES_ERRORS_TITLE": "바꾸기 에러",
  "REPLACE_IN_FILES_ERRORS": "다음 파일은 검색 후에 변경되었거나 저장할 수 없는 파일이므로 수정할 수 없습니다.",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "업데이트 정보를 검색하는 중 오류가 발생했습니다.",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "서버에서 최신 업데이트를 검색하는 중 오류가 발생했습니다. 인터넷 연결을 확인하고 다시 시도하세요.",
  "NEW_FILE_FILTER": "검색 제외 규칙…",
  "CLEAR_FILE_FILTER": "제외할 파일 없음",
  "NO_FILE_FILTER": "제외할 파일 없음",
  "EXCLUDE_FILE_FILTER": "파일 제외",
  "INCLUDE_FILE_FILTER": "파일에서 검색",
  "FILTER_PLACEHOLDER": "예를 들어 인덱스,.css,*.js,src/**/*.css",
  "FILTER_HISTORY_TOOLTIP": "기록을 보려면 'Ctrl-Space'를 누르세요.",
  "FILTER_HISTORY_TOOLTIP_MAC": "기록을 보려면 'Cmd-Space'를 누르세요.",
  "FIND_HISTORY_TOOLTIP": "기록을 보려면 'Ctrl-Space'를 누르세요.",
  "FIND_HISTORY_TOOLTIP_MAC": "기록을 보려면 'Cmd-Space'를 누르세요.",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "현재 커서 위치에서는 빠른 편집을 사용할 수 없습니다",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "CSS 빠른 편집: 커서를 클래스 이름 위에 두세요",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "CSS 빠른 편집: 완료되지 않은 class 속성입니다",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "CSS 빠른 편집: 완료되지 않은 id 속성입니다",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "CSS 빠른 편집: 커서를 태그, 클래스 또는 아이디에 두세요",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "CSS 타이밍 함수 빠른 편집:  문법이 올바르지 않습니다",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "JS 빠른 편집: 커서를 함수 이름에 두세요",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "현재 커서 위치에서는 빠른 문서보기를 사용할 수 없습니다",
  "PROJECT_LOADING": "프로젝트 여는 중…",
  "UNTITLED": "제목 없음",
  "WORKING_FILES": "현재 파일",
  "TOP": "위",
  "BOTTOM": "아래",
  "LEFT": "왼쪽",
  "RIGHT": "오른쪽",
  "CMD_SPLITVIEW_NONE": "나누지 않음",
  "CMD_SPLITVIEW_VERTICAL": "왼쪽/오른쪽으로 분할",
  "CMD_SPLITVIEW_HORIZONTAL": "위/아래로 분할",
  "SPLITVIEW_MENU_TOOLTIP": "에디터를 왼쪽/오른쪽 또는 위/아래로 분할합니다",
  "GEAR_MENU_TOOLTIP": "Configure Working Set",
  "SPLITVIEW_INFO_TITLE": "이미 열려있는 파일",
  "SPLITVIEW_MULTIPANE_WARNING": "이 파일은 이미 다른 패널에서 열려있습니다. 이름이 같은 파일을 여러 패널에서 여는 기능은 곧 지원될 예정입니다. 그 전에는 이미 열려있던 파일은 해당 패널에서 보게될 것입니다.<br /><br />(이 메시지는 한 번만 나타납니다.)",
  "KEYBOARD_OVERLAY_TEXT": "화살표를 사용하여 탐색하거나 입력하여 UI 요소를 선택하세요.",
  "KEYBOARD_SHORTCUT_CHANGE_TITLE": "키보드 단축키 변경…",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_TITLE": "키보드 단축키 변경",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_TEXT": "<b>&#39;{0}&#39;</b> 에 대한 새 키 조합을 누르세요(현재: <b>{1}</b> ).",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_DUPLICATE": "경고: 키 조합 <b>{0}</b> 이(가) 이미 <b>&#39;{1}&#39;</b> 에 할당되었습니다. <b>&#39;{2}&#39;</b> 에 재할당하시겠습니까?",
  "KEYBOARD_SHORTCUT_ASSIGN": "양수인",
  "KEYBOARD_SHORTCUT_NONE": "없음",
  "KEYBOARD_SHORTCUT_MENU_SHOW_SHORTCUTS": "키보드 단축키…",
  "KEYBOARD_SHORTCUT_MENU_SHOW_SHORTCUTS_BUTTON": "모든 바로가기 표시…",
  "KEYBOARD_SHORTCUT_TABLE_BASE_KEY": "기본 키",
  "KEYBOARD_SHORTCUT_TABLE_KEY_BINDING": "지름길",
  "KEYBOARD_SHORTCUT_TABLE_COMMAND_ID": "명령 ID",
  "KEYBOARD_SHORTCUT_TABLE_COMMAND_NAME": "명령",
  "KEYBOARD_SHORTCUT_TABLE_DOUBLE_CLICK": "바로가기를 변경하려면 두 번 클릭하세요.",
  "KEYBOARD_SHORTCUT_TABLE_ORIGIN": "기원",
  "KEYBOARD_SHORTCUT_ORIG_EXTENSION": "확대",
  "KEYBOARD_SHORTCUT_PANEL_TITLE": "키보드 단축키",
  "KEYBOARD_SHORTCUT_PANEL_FILTER": "필터&hellip;",
  "KEYBOARD_SHORTCUT_PANEL_RESET": "초기화…",
  "KEYBOARD_SHORTCUT_PANEL_RESET_DEFAULT": "기본 단축키로 재설정…",
  "KEYBOARD_SHORTCUT_RESET_DIALOG_TITLE": "키보드 단축키 재설정",
  "KEYBOARD_SHORTCUT_RESET_DIALOG_MESSAGE": "모든 맞춤 단축키를 기본값으로 재설정하시겠습니까? 이 취소 할 수 없습니다.",
  "STATUSBAR_CURSOR_POSITION": "행 {0}, 열 {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": " — {0} 열을 선택",
  "STATUSBAR_SELECTION_CH_PLURAL": " — {0} 열을 선택",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " — {0} 행을 선택",
  "STATUSBAR_SELECTION_LINE_PLURAL": " — {0} 행을 선택",
  "STATUSBAR_SELECTION_MULTIPLE": " — {0}개 선택영역",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "들여쓰기를 공백으로 변환",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "들여쓰기를 탭으로 변환",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "들여쓰기에 사용할 공백 갯수 변경",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "탭 너비 변경",
  "STATUSBAR_SPACES": "스페이스:",
  "STATUSBAR_TAB_SIZE": "탭 폭:",
  "STATUSBAR_LINE_COUNT_SINGULAR": "— {0} 행",
  "STATUSBAR_LINE_COUNT_PLURAL": "— {0} 행",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "확장 기능 사용 불가",
  "STATUSBAR_INSERT": "INS",
  "STATUSBAR_OVERWRITE": "OVR",
  "STATUSBAR_INSOVR_TOOLTIP": "클릭하면 커서를 삽입(INS)또는 덮어쓰기(OVR) 모드로 전환합니다",
  "STATUSBAR_LANG_TOOLTIP": "파일 종류를 변경하려면 클릭하세요",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. 클릭하면 기록 패널을 토글합니다.",
  "STATUSBAR_DEFAULT_LANG": "(기본값)",
  "STATUSBAR_SET_DEFAULT_LANG": ".{0} 파일에 대한 기본값으로 설정",
  "STATUSBAR_ENCODING_TOOLTIP": "인코딩 선택",
  "STATUSBAR_TASKS": "작업",
  "STATUSBAR_TASKS_TOOLTIP": "활성 작업 관리",
  "STATUSBAR_TASKS_HIDE_SPINNER": "스피너 아이콘 숨기기",
  "STATUSBAR_TASKS_UNKNOWN_EXTENSION_TASK": "알 수 없는 확장 작업…",
  "STATUSBAR_TASKS_PLAY": "시작 또는 재개",
  "STATUSBAR_TASKS_PAUSE": "정지시키다",
  "STATUSBAR_TASKS_STOP": "멈추다",
  "STATUSBAR_TASKS_RESTART": "재시작",
  "ERRORS_PANEL_TITLE_MULTIPLE": "{0}개의 에러",
  "SINGLE_ERROR": "1개의 {0} 에러",
  "MULTIPLE_ERRORS": "{1}개의 {0} 에러",
  "NO_ERRORS": "{0} 에러가 없습니다 - 훌륭합니다!",
  "NO_ERRORS_MULTIPLE_PROVIDER": "에러가 없습니다 - 훌륭합니다!",
  "LINT_DISABLED": "Lint 검사를 사용할 수 없습니다.",
  "NO_LINT_AVAILABLE": "{0} 사용할 수 있는 Lint 검사기가 없습니다.",
  "NOTHING_TO_LINT": "Lint 검사기로 확인할 파일이 없습니다.",
  "LINTER_TIMED_OUT": "{0} 검사기가 {1}ms 대기 후 타임아웃 되었습니다",
  "LINTER_FAILED": "{0} 검사기가 에러때문에 종료되었습니다: {1}",
  "FILE_MENU": "파일",
  "CMD_FILE_NEW_UNTITLED": "새 파일",
  "CMD_FILE_NEW": "파일 만들기",
  "CMD_FILE_DUPLICATE": "행 복사",
  "CMD_FILE_DUPLICATE_FILE": "중복 파일",
  "CMD_FILE_DOWNLOAD_PROJECT": "프로젝트 다운로드",
  "CMD_FILE_DOWNLOAD": "다운로드",
  "CMD_FILE_CUT": "오려두기",
  "CMD_FILE_COPY": "복사하기",
  "CMD_FILE_COPY_PATH": "경로 복사",
  "CMD_FILE_PASTE": "붙여넣기",
  "CMD_PROJECT_NEW": "새 프로젝트…",
  "CMD_FILE_NEW_FOLDER": "폴더 만들기",
  "CMD_FILE_OPEN": "파일 열기…",
  "CMD_RECENT_FILES_OPEN": "최근 파일…",
  "CMD_ADD_TO_WORKING_SET": "작업세트에 추가",
  "CMD_OPEN_DROPPED_FILES": "드롭한 파일 열기",
  "CMD_OPEN_FOLDER": "폴더 열기…",
  "CMD_FILE_CLOSE": "닫기",
  "CMD_FILE_CLOSE_ALL": "모두 닫기",
  "CMD_FILE_CLOSE_LIST": "목록 닫기",
  "CMD_FILE_CLOSE_OTHERS": "다른 파일 닫기",
  "CMD_FILE_CLOSE_ABOVE": "위의 목록 닫기",
  "CMD_FILE_CLOSE_BELOW": "아래 목록 닫기",
  "CMD_FILE_SAVE": "다른 이름으로 저장",
  "CMD_FILE_SAVE_ALL": "모두 저장",
  "CMD_FILE_SAVE_AS": "다른 이름으로 저장…",
  "CMD_LIVE_FILE_PREVIEW": "실시간 미리보기",
  "CMD_LIVE_FILE_PREVIEW_SETTINGS": "실시간 미리보기 설정",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "실험적 실시간 미리보기 활성화",
  "CMD_RELOAD_LIVE_PREVIEW": "실시간 미리보기 다시 읽기",
  "CMD_PROJECT_SETTINGS": "프로젝트 설정…",
  "CMD_FILE_RENAME": "파일명 변경",
  "CMD_FILE_DELETE": "삭제",
  "CMD_INSTALL_EXTENSION": "확장 기능 설치…",
  "CMD_EXTENSION_MANAGER": "확장 기능 관리자…",
  "CMD_FILE_REFRESH": "파일 트리 업데이트",
  "CMD_FILE_SHOW_FOLDERS_FIRST": "먼저 폴더 정렬",
  "CMD_QUIT": "종료",
  "CMD_EXIT": "종료",
  "EDIT_MENU": "편집",
  "CMD_UNDO": "비활성화 취소",
  "CMD_REDO": "재실행",
  "CMD_CUT": "오려두기",
  "CMD_COPY": "복사하기",
  "CMD_PASTE": "붙여넣기",
  "CMD_SELECT_ALL": "전체 선택",
  "CMD_SELECT_LINE": "행 선택",
  "CMD_SPLIT_SEL_INTO_LINES": "선택영역을 여러 줄로 나누기",
  "CMD_ADD_CUR_TO_NEXT_LINE": "아랫줄에 커서 추가",
  "CMD_ADD_CUR_TO_PREV_LINE": "윗줄에 커서 추가",
  "CMD_INDENT": "들여쓰기",
  "CMD_UNINDENT": "내어쓰기",
  "CMD_DUPLICATE": "행 복사",
  "CMD_DELETE_LINES": "행 삭제",
  "CMD_COMMENT": "행 주석처리",
  "CMD_BLOCK_COMMENT": "블록 주석처리",
  "CMD_LINE_UP": "행을 위로 이동",
  "CMD_LINE_DOWN": "행을 아래로 이동",
  "CMD_OPEN_LINE_ABOVE": "상단에 라인 열기",
  "CMD_OPEN_LINE_BELOW": "하단에 라인 열기",
  "CMD_TOGGLE_CLOSE_BRACKETS": "자동 괄호",
  "CMD_SHOW_CODE_HINTS": "코드 힌트 표시",
  "CMD_BEAUTIFY_CODE": "코드를 아름답게",
  "CMD_BEAUTIFY_CODE_ON_SAVE": "저장 후 코드 꾸미기",
  "FIND_MENU": "찾기",
  "CMD_FIND": "찾기",
  "CMD_FIND_NEXT": "다음 찾기",
  "CMD_FIND_PREVIOUS": "이전 찾기",
  "CMD_FIND_ALL_AND_SELECT": "모든 발생 선택",
  "CMD_ADD_NEXT_MATCH": "다음 발생 추가",
  "CMD_SKIP_CURRENT_MATCH": "건너뛰기 및 다음 항목 추가",
  "CMD_FIND_IN_FILES": "파일에서 찾기",
  "CMD_FIND_IN_SUBTREE": "다음에서 찾기…",
  "CMD_REPLACE": "바꾸기",
  "CMD_REPLACE_IN_FILES": "파일에서 바꾸기",
  "CMD_REPLACE_IN_SUBTREE": "다음에서 바꾸기…",
  "VIEW_MENU": "보기",
  "CMD_HIDE_SIDEBAR": "사이드 바 숨기기",
  "CMD_SHOW_SIDEBAR": "사이드 바 표시",
  "CMD_TOGGLE_SIDEBAR": "사이드바 표시 전환",
  "CMD_TOGGLE_PANELS": "패널 표시 전환",
  "CMD_TOGGLE_PURE_CODE": "코드만 보기",
  "CMD_TOGGLE_FULLSCREEN": "전체 화면",
  "CMD_ZOOM_UI": "줌 UI 및 글꼴",
  "CMD_ZOOM_IN": "확대",
  "CMD_ZOOM_IN_SCALE": "확대(현재: {0}%)",
  "CMD_ZOOM_OUT": "축소",
  "CMD_INCREASE_FONT_SIZE": "폰트 크기 키우기",
  "CMD_DECREASE_FONT_SIZE": "폰트 크기 줄이기",
  "CMD_RESTORE_FONT_SIZE": "폰트 크기 초기화",
  "CMD_SCROLL_LINE_UP": "한줄 위로 스크롤",
  "CMD_SCROLL_LINE_DOWN": "한줄 아래로 스크롤",
  "CMD_TOGGLE_LINE_NUMBERS": "행 번호 보이기",
  "CMD_TOGGLE_ACTIVE_LINE": "활성 행 하이라이트",
  "CMD_TOGGLE_WORD_WRAP": "자동 줄바꿈",
  "CMD_LIVE_HIGHLIGHT": "실시간 미리보기 하이라이트",
  "CMD_VIEW_TOGGLE_INSPECTION": "저장시 파일 Lint표시",
  "CMD_WORKINGSET_SORT_BY_ADDED": "추가순으로 작업세트 정렬",
  "CMD_WORKINGSET_SORT_BY_NAME": "이름순으로 작업세트 정렬",
  "CMD_WORKINGSET_SORT_BY_TYPE": "타입별로 작업세트 정렬",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "자동으로 작업세트 정렬",
  "CMD_THEMES": "테마…",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "자동으로 검색 닫기",
  "CMD_TOGGLE_RULERS": "통치자",
  "CMD_KEYBOARD_NAV_OVERLAY": "시각적 명령 팔레트",
  "NAVIGATE_MENU": "탐색",
  "CMD_QUICK_OPEN": "빠른 열기",
  "CMD_GOTO_LINE": "행으로 이동",
  "CMD_GOTO_DEFINITION": "빠른 정의 검색",
  "CMD_GOTO_DEFINITION_PROJECT": "프로젝트에서 빠른 찾기 정의",
  "CMD_GOTO_FIRST_PROBLEM": "최초의 에러 또는 경고로 이동",
  "CMD_TOGGLE_QUICK_EDIT": "빠른 편집",
  "CMD_TOGGLE_QUICK_DOCS": "빠른 문서보기",
  "CMD_QUICK_EDIT_PREV_MATCH": "이전 빠른 편집 항목",
  "CMD_QUICK_EDIT_NEXT_MATCH": "다음 빠른 편집 항목",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "새 규칙",
  "CMD_NEXT_DOC": "다음 문서",
  "CMD_PREV_DOC": "이전 문서",
  "CMD_NAVIGATE_BACKWARD": "뒤로 탐색",
  "CMD_NAVIGATE_FORWARD": "앞으로 탐색",
  "CMD_NEXT_DOC_LIST_ORDER": "목록의 다음 문서",
  "CMD_PREV_DOC_LIST_ORDER": "목록의 이전 문서",
  "CMD_SHOW_IN_TREE": "파일트리에서 보기",
  "CMD_SHOW_IN_EXPLORER": "탐색기에서 보기",
  "CMD_SHOW_IN_FINDER": "파인더에서 보기",
  "CMD_SHOW_IN_OS": "OS 파일에 표시",
  "CMD_SWITCH_PANE_FOCUS": "창 초점 전환",
  "CMD_OPEN_VFS": "가상 파일 시스템 열기",
  "CMD_DIAGNOSTIC_TOOLS": "{APP_NAME} 진단 도구",
  "CMD_OPEN_EXTENSIONS_FOLDER": "확장 폴더 열기…",
  "CMD_OPEN_VIRTUAL_SERVER": "가상 서버 열기",
  "HELP_MENU": "도움말",
  "CMD_CHECK_FOR_UPDATE": "업데이트 확인…",
  "CMD_AUTO_UPDATE": "자동 업데이트",
  "CMD_HOW_TO_USE_BRACKETS": "{APP_NAME} 사용법",
  "CMD_SUPPORT": "{APP_NAME} 지원",
  "CMD_SUGGEST": "기능 제안",
  "CMD_RELEASE_NOTES": "릴리즈 노트",
  "CMD_GET_INVOLVED": "프로젝트 참여",
  "CMD_SHOW_EXTENSIONS_FOLDER": "확장 기능 폴더 열기",
  "CMD_HEALTH_DATA_STATISTICS": "건강 보고서…",
  "CMD_HOMEPAGE": "앱 다운로드 - 홈 페이지",
  "CMD_TWITTER": "Twitter에서 {TWITTER_NAME} 팔로우하기",
  "CMD_ABOUT": "{APP_TITLE} 정보",
  "CMD_OPEN_PREFERENCES": "환경설정 파일 열기",
  "CMD_OPEN_KEYMAP": "사용자 키 맵 파일 열기",
  "EXPERIMENTAL_BUILD": "시험 빌드",
  "RELEASE_BUILD": "빌드",
  "DEVELOPMENT_BUILD": "개발 빌드",
  "PRERELEASE_BUILD": "시험판 빌드",
  "RELOAD_FROM_DISK": "디스크에서 다시 읽기",
  "KEEP_CHANGES_IN_EDITOR": "편집기에서 변경 내용을 유지",
  "CLOSE_DONT_SAVE": "저장하지 않고 닫기",
  "RELAUNCH_CHROME": "Chrome 재시작",
  "ABOUT": "이 소프트웨어에 대하여",
  "CLOSE": "닫기",
  "ABOUT_TEXT_LINE1": "{VERSION_MAJOR} 출시.{VERSION_MINOR} {BUILD_TYPE} {VERSION}",
  "ABOUT_TEXT_BUILD_TIMESTAMP": "빌드 타임스탬프:",
  "ABOUT_TEXT_LINE3": "우리가 사용하는 타사 라이브러리 - <a href='https://github.com/phcode-dev/phoenix/tree/main/src/thirdparty/licences'>라이선스 및 속성</a> .",
  "ABOUT_TEXT_LINE4": "문서 및 소스: <a href='https://github.com/phcode-dev/phoenix/'>https://github.com/phcode-dev/phoenix/</a>",
  "ABOUT_TEXT_LINE5": "❤ 및 JavaScript로 제작:",
  "ABOUT_TEXT_LINE6": "많은 사람들이 있습니다(하지만 지금은 해당 데이터를 로드하는 데 문제가 있습니다).",
  "ABOUT_TEXT_MDN_DOCS": "MDN 문서와 MDN 로고는 크리에이티브 커먼즈 저작자표시 라이선스, <a href='{MDN_DOCS_LICENSE}'>CC-BY-SA 2.5 Unported</a> 로 배포됩니다.",
  "UPDATE_NOTIFICATION_TOOLTIP": "{APP_NAME}의 새로운 빌드를 사용할 수 있습니다. 자세한 내용은 여기를 클릭하세요.",
  "UPDATE_NOT_AVAILABLE_TITLE": "{APP_NAME}이(가) 최신 상태입니다.",
  "UPDATE_UP_TO_DATE": "{APP_NAME} 버전이 최신 버전입니다.",
  "UPDATE_AVAILABLE_TITLE": "사용 가능한 업데이트가 있습니다",
  "UPDATE_READY_RESTART_TITLE": "업데이트 준비됨: 다시 시작해야 함",
  "UPDATE_READY_RESTART_MESSAGE": "업데이트된 버전을 실행하려면 모든 {APP_NAME} 앱 창을 닫고 앱을 다시 시작하세요.",
  "UPDATE_READY_RESTART_INSTALL_MESSAGE": "업데이트 다운로드 성공: 최신 업데이트를 적용하려면 모든 {APP_NAME} 앱 창을 닫으세요.",
  "UPDATE_FAILED_TITLE": "업데이트가 실패",
  "UPDATE_INSTALLING": "업데이트 설치 중…",
  "UPDATE_INSTALLING_MESSAGE": "업데이트 설치 진행 중: {APP_NAME}이 현재 최신 업데이트를 설치하고 있습니다. 설치가 완료되면 애플리케이션이 자동으로 닫힙니다.",
  "UPDATE_FAILED_MESSAGE": "업데이트를 다시 시도하려면 {APP_NAME} 앱 창을 모두 닫은 후 애플리케이션을 다시 열어보세요.",
  "UPDATE_FAILED_VISIT_SITE_MESSAGE": "다시 시도하려면 {APP_NAME}의 모든 인스턴스를 종료하고 애플리케이션을 다시 시작하세요.<br> 곧 최신 버전을 수동으로 다운로드할 수 있는 다운로드 페이지로 이동하게 됩니다.",
  "UPDATE_MESSAGE": "{APP_NAME}의 새로운 빌드를 사용할 수 있습니다. 새로운 기능의 일부를 다음에 소개합니다 :",
  "GET_IT_NOW": "지금 다운로드",
  "UPDATE_ON_EXIT": "종료 시 업데이트",
  "UPDATE_LATER": "나중에 상기시켜 줘",
  "UPDATE_DONE": "{APP_NAME}을 업데이트하려면 다시 시작하세요.",
  "UPDATE_RESTART": "업데이트를 적용하려면 다시 시작하세요.",
  "UPDATE_RESTART_INSTALL": "업데이트를 설치하려면 다시 시작하세요.",
  "UPDATE_DOWNLOADING": "설치 프로그램 다운로드 중",
  "INSTALL_WEBAPP": "기기에 {APP_NAME}을(를) 설치하세요",
  "UPDATE_DOWNLOAD_PROGRESS": "다운로드 중 - {1}MB 중 {0}MB",
  "UPDATING_APP": "{APP_NAME} 업데이트 중",
  "UPDATING_APP_MESSAGE": "시간이 좀 걸릴 수 있습니다.",
  "UPDATING_APP_DIALOG_MESSAGE": "업데이트가 진행 중입니다. 업그레이드하는 동안 {APP_NAME}을(를) 계속 사용할 수 있습니다.",
  "PROJECT_SETTINGS_TITLE": "프로젝트 설정 : {0}",
  "PROJECT_SETTING_BASE_URL": "실시간 미리보기에 대한 기본 URL",
  "PROJECT_SETTING_BASE_URL_HINT": "http://localhost:8000/ 등의 URL을 입력하여 로컬 서버를 사용",
  "BASEURL_ERROR_INVALID_PROTOCOL": "{0} 프로토콜이 실시간 미리보기가 지원되지 않습니다. http: 또는 https:를 사용하세요.",
  "BASEURL_ERROR_SEARCH_DISALLOWED": "기본 URL에는 「{0}」과(와) 같은 검색어를 사용할 수 없습니다.",
  "BASEURL_ERROR_HASH_DISALLOWED": "기본 URL에는 「{0}」과(와) 같은 해시 기호는 사용할 수 없습니다.",
  "BASEURL_ERROR_INVALID_CHAR": "「{0}」과(와) 같은 특수 문자는 퍼센트로 인코딩해야합니다.",
  "BASEURL_ERROR_UNKNOWN_ERROR": "기본 URL의 구문을 분석하는 동안 알 수 없는 오류가 발생했습니다",
  "EMPTY_VIEW_HEADER": "<em>이 창에 포커스가 있을 때 파일 열기</em>",
  "FLIPVIEW_BTN_TOOLTIP": "{0} 창에 이 보기를 반전",
  "CURRENT_THEME": "현재 테마",
  "USE_THEME_SCROLLBARS": "테마에서 정의한 스크롤바 적용",
  "FONT_SIZE": "글자 크기",
  "FONT_FAMILY": "글꼴",
  "THEMES_SETTINGS": "테마 설정",
  "THEMES_ERROR": "테마 오류",
  "THEMES_ERROR_CANNOT_APPLY": "오류로 인해 테마를 적용할 수 없습니다.",
  "BUTTON_NEW_RULE": "새 규칙",
  "INSTALL": "설치",
  "APPLY": "적용하다",
  "UPDATE": "업데이트",
  "REMOVE": "삭제",
  "DISABLE": "비활성",
  "ENABLE": "활성",
  "OVERWRITE": "덮어쓰기",
  "CANT_DROP_ZIP": "zip 파일 삭제는 곧 지원될 예정입니다...",
  "CANT_REMOVE_DEV": "\"dev\" 폴더의 확장 기능은 수동으로 제거해야 합니다.",
  "CANT_UPDATE": "업데이트가 이 버전의 {APP_NAME}와 호환되지 않습니다.",
  "CANT_UPDATE_DEV": "\"dev\" 폴더의 확장 기능은 자동으로 업데이트 할 수 없습니다.",
  "INSTALL_EXTENSION_TITLE": "확장 기능 설치",
  "UPDATE_EXTENSION_TITLE": "확장 기능 업데이트",
  "INSTALL_EXTENSION_LABEL": "확장 기능 URL",
  "INSTALL_EXTENSION_HINT": "확장 기능 zip 파일 또는 GitHub 저장소의 URL",
  "INSTALLING_FROM": "{0}에서 확장 기능을 설치합니다",
  "INSTALL_SUCCEEDED": "설치에 성공했습니다.",
  "INSTALL_FAILED": "설치에 실패했습니다.",
  "CANCELING_INSTALL": "설치 취소중…",
  "CANCELING_HUNG": "설치 취소에 시간이 지연되고 있습니다. 내부 에러가 발생했을 수 있습니다.",
  "INSTALL_CANCELED": "설치가 취소되었습니다.",
  "VIEW_COMPLETE_DESCRIPTION": "전체 설명 보기",
  "VIEW_TRUNCATED_DESCRIPTION": "설명 일부 숨기기",
  "SORT_EXTENSION_METHOD": "downloadCount 또는publishedDate를 사용하여 확장 프로그램 정렬",
  "INVALID_ZIP_FILE": "다운로드 한 콘텐츠가 유효한 zip 파일이 아닙니다.",
  "MISSING_PACKAGE_JSON": "패키지에 package.json 파일이 없습니다.",
  "INVALID_PACKAGE_JSON": "package.json 파일이 유효하지 않습니다 (에러: {0})",
  "MISSING_PACKAGE_NAME": "package.json 파일에 패키지 이름을 지정하지 않았습니다.",
  "BAD_PACKAGE_NAME": "{0} 잘못된 패키지 이름입니다.",
  "MISSING_PACKAGE_VERSION": "package.json 파일에 패키지 버전을 지정하지 않습니다.",
  "INVALID_VERSION_NUMBER": "패키지 버전 번호 ({0})가 잘못되었습니다.",
  "INVALID_BRACKETS_VERSION": "{APP_NAME} 호환 문자열 {0}이 잘못되었습니다.",
  "DISALLOWED_WORDS": "{1} {0} 필드에서는 사용할 수 없습니다.",
  "NPM_INSTALL_FAILED": "npm 설치 명령 실패: {0}",
  "API_NOT_COMPATIBLE": "확장 기능은 이 버전의 {APP_NAME}와 호환되지 않습니다. 잘못된 확장 기능 폴더에 설치됩니다.",
  "MISSING_MAIN": "패키지에 main.js 파일이 포함되어 있지 않습니다.",
  "EXTENSION_ALREADY_INSTALLED": "이 패키지를 설치하면 이전에 설치한 확장 기능이 무시됩니다. 이전 확장을 덮어 쓰시겠습니까?",
  "EXTENSION_SAME_VERSION": "이 패키지 버전은 현재 설치되어있는 버전과 동일합니다. 기존 설치를 겹쳐 쓰시겠습니까?",
  "EXTENSION_OLDER_VERSION": "이 패키지 버전 ({0})은 현재 설치되어있는 버전 ({1})보다 이전 버전입니다. 기존 설치를 겹쳐 쓰시겠습니까?",
  "DOWNLOAD_ID_IN_USE": "내부 에러: 이미 사용 중인 다운로드 ID 입니다.",
  "NO_SERVER_RESPONSE": "서버에 연결할 수 없습니다.",
  "BAD_HTTP_STATUS": "파일 서버 (HTTP {0})에 찾을 수 없습니다.",
  "CANNOT_WRITE_TEMP": "임시 다운로드 파일을 저장할 수 없습니다.",
  "ERROR_LOADING": "확장 기능 시작 중 오류가 발생했습니다",
  "MALFORMED_URL": "URL이 잘못되었습니다. 제대로 입력되어 있는지 확인하세요.",
  "UNSUPPORTED_PROTOCOL": "URL은 http 또는 https URL이어야합니다.",
  "UNKNOWN_ERROR": "알 수 없는 내부 에러.",
  "EXTENSION_VERIFIED_PUBLISHER": "이 게시자는 {0}의 소유권을 확인했습니다.",
  "EXTENSION_VERIFIED_SORT": "검증됨",
  "EXTENSION_STAR": "별",
  "EXTENSION_STAR_SORT": "별점 매기기",
  "EXTENSION_MANAGER_TITLE": "확장 기능 관리자",
  "EXTENSION_MANAGER_ERROR_LOAD": "확장 기능 레지스트리에 액세스 할 수 없습니다. 나중에 다시 시도하십시오.",
  "EXTENSION_UPDATE_RESTART_TITLE": "업데이트하려면 다시 시작하세요",
  "EXTENSION_UPDATE_RESTART_MESSAGE": "업데이트된 확장 프로그램을 로드하려면 실행 중인 {APP_NAME} 인스턴스를 모두 닫고 애플리케이션을 다시 시작하세요.",
  "INSTALL_EXTENSION_DRAG": "여기에 .zip 파일을 드래그하거나",
  "INSTALL_EXTENSION_DROP": "파일을 드롭하면 설치를 시작합니다.",
  "INSTALL_EXTENSION_DROP_ERROR": "에러가 발생하여 설치/업데이트가 종료되었습니다:",
  "INSTALL_FROM_URL": "URL에서 설치하세요…",
  "INSTALL_EXTENSION_VALIDATING": "유효성 검사중…",
  "EXTENSION_AUTHOR": "제작자",
  "EXTENSION_DATE": "제작일",
  "EXTENSION_INCOMPATIBLE_NEWER": "이 확장 기능은 새 버전의 {APP_NAME}가 필요합니다.",
  "EXTENSION_INCOMPATIBLE_OLDER": "이 확장 기능은 현재 이전 버전의 {APP_NAME}에서 작동하지 않습니다.",
  "EXTENSION_DEFAULT_FEATURE_PRESENT": "이 확장 프로그램이 필요하지 않을 수 있습니다. {APP_NAME}에는 이미 이 기능이 있습니다.",
  "EXTENSION_LATEST_INCOMPATIBLE_NEWER": "이 확장 기능 버전 {0}에는 {APP_NAME}의 새 버전이 필요합니다. 그러나 이전 버전 {1}을 설치할 수 있습니다.",
  "EXTENSION_LATEST_INCOMPATIBLE_OLDER": "이 확장 기능 버전 {0} {APP_NAME}의 이전 버전에서만 작동합니다. 그러나 이전 버전 {1}을 설치할 수 있습니다.",
  "EXTENSION_NO_DESCRIPTION": "설명 없음",
  "EXTENSION_MORE_INFO": "추가 정보...",
  "EXTENSION_ERROR": "확장 기능 에러",
  "EXTENSION_KEYWORDS": "키워드",
  "EXTENSION_TRANSLATED_USER_LANG": "{0}개 언어 지원. 한국어 포함",
  "EXTENSION_TRANSLATED_GENERAL": "{0}개 언어 지원",
  "EXTENSION_TRANSLATED_LANGS": "이 확장 기능은 다음 언어를 지원합니다: {0}",
  "EXTENSION_INSTALLED": "설치됨",
  "EXTENSION_UPDATE_INSTALLED": "이 확장 기능의 업데이트가 다운로드되었습니다. {APP_NAME}를 종료할 때 설치합니다.",
  "EXTENSION_SEARCH_PLACEHOLDER": "검색",
  "EXTENSION_MORE_INFO_LINK": "상세 정보",
  "EXTENSION_MANAGER_CREATE_EXTENSION": "+ 확장 프로그램 만들기",
  "EXTENSION_MANAGER_CREATE_THEME": "+ 테마 만들기",
  "BROWSE_EXTENSIONS": "확장 기능 찾기",
  "EXTENSION_MANAGER_REMOVE": "확장 기능 제거",
  "EXTENSION_MANAGER_REMOVE_ERROR": "하나 이상의 확장 기능을 ({0}) 제거할 수 없습니다. {APP_NAME}가 종료 중입니다.",
  "EXTENSION_MANAGER_UPDATE": "확장 기능 업데이트",
  "EXTENSION_MANAGER_UPDATE_ERROR": "하나 이상의 확장 기능을 ({0}) 업데이트 할 수 없습니다. {APP_NAME}가 종료 중입니다.",
  "EXTENSION_MANAGER_DISABLE": "확장 기능 비활성",
  "EXTENSION_MANAGER_DISABLE_ERROR": "하나 이상의 확장 기능을 ({0}) 비활성화 할 수 없습니다. {APP_NAME}가 종료 중입니다.",
  "EXTENSION_MANAGER_THEMES_INFO": "<a class=\"theme_settings\">기본 테마를 선택</a> 하거나 다른 테마 설정을 수정하려면 여기를 <a class=\"theme_settings\">클릭하십시오</a> .",
  "EXTENSION_MANAGER_THEMES_UNDO": "이전 테마로 되돌리기",
  "MARKED_FOR_REMOVAL": "삭제 예정",
  "UNDO_REMOVE": "비활성화 취소",
  "MARKED_FOR_UPDATE": "업데이트 예정",
  "UNDO_UPDATE": "비활성화 취소",
  "MARKED_FOR_DISABLING": "비활성화 예정",
  "UNDO_DISABLE": "비활성화 취소",
  "CHANGE_AND_RELOAD_TITLE": "확장 기능 변경",
  "CHANGE_AND_RELOAD_MESSAGE": "업데이트 예정 또는 삭제 예정 확장 기능을 업데이트하거나 삭제하려면 {APP_NAME}를 재시작해야 합니다. 저장되지 않은 변경 내용은 저장여부를 확인합니다.",
  "REMOVE_AND_RELOAD": "확장 기능을 제거하고 재시작",
  "CHANGE_AND_RELOAD": "확장 기능을 변경하고 재시작",
  "UPDATE_AND_RELOAD": "확장 기능을 업데이트하고 재시작",
  "DISABLE_AND_RELOAD": "확장 기능을 비활성화하고 재시작",
  "PROCESSING_EXTENSIONS": "확장 기능 변경사항 처리 중…",
  "EXTENSION_NOT_INSTALLED": "설치되지 않았기 때문에 확장 기능 {0}을 삭제할 수 없습니다.",
  "NO_EXTENSIONS": "설치되어있는 확장 기능이 아직 없습니다. <br>에서 「설치 가능」탭을 클릭하여 설치하세요.",
  "NO_EXTENSION_MATCHES": "검색 조건에 일치하는 확장 기능이 없습니다.",
  "REGISTRY_SANITY_CHECK_WARNING": "알 수 없는 소스에서 확장 기능을 설치할 때 주의하세요.",
  "EXTENSIONS_INSTALLED_TITLE": "설치됨",
  "EXTENSIONS_DEFAULT_TITLE": "기본",
  "EXTENSIONS_AVAILABLE_TITLE": "설치 가능",
  "EXTENSIONS_THEMES_TITLE": "테마",
  "EXTENSIONS_UPDATES_TITLE": "업데이트",
  "EXTENSIONS_LAST_UPDATED": "마지막 업데이트",
  "EXTENSIONS_DOWNLOADS": "다운로드",
  "INLINE_EDITOR_NO_MATCHES": "일치하는 항목이 없습니다.",
  "INLINE_EDITOR_HIDDEN_MATCHES": "All matches are collapsed. Expand the files listed at right to view matches.",
  "CSS_QUICK_EDIT_NO_MATCHES": "선택 일치하는 기존 CSS 규칙이 없습니다. <br> 「새 규칙」을 클릭하여 규칙을 작성하세요.",
  "CSS_QUICK_EDIT_NO_STYLESHEETS": "프로젝트에는 스타일 시트가 없습니다. <br> 스타일 시트를 작성하여 CSS 규칙에 추가하세요.",
  "IMAGE_VIEWER_LARGEST_ICON": "최대",
  "UNIT_PIXELS": "픽셀",
  "DEBUG_MENU": "디버그",
  "ERRORS": "에러",
  "CMD_SHOW_DEV_TOOLS": "{APP_NAME} 개발자 도구",
  "CMD_REFRESH_WINDOW": "{APP_NAME} 재시작",
  "CMD_LOAD_CURRENT_EXTENSION": "프로젝트를 확장자로 로드",
  "CMD_RELOAD_CURRENT_EXTENSION": "확장 프로그램으로 프로젝트 다시 로드",
  "CMD_UNLOAD_CURRENT_EXTENSION": "확장 프로그램으로 프로젝트 언로드",
  "CMD_RELOAD_WITHOUT_USER_EXTS": "확장 기능 없이 재시작",
  "CMD_NEW_BRACKETS_WINDOW": "새창",
  "CMD_LAUNCH_SCRIPT_MAC": "명령 줄 바로가기 설치",
  "CMD_SWITCH_LANGUAGE": "언어 전환…",
  "CMD_RUN_UNIT_TESTS": "{APP_NAME} 테스트 실행",
  "CMD_SHOW_PERF_DATA": "성능 데이터를 표시",
  "CMD_ENABLE_LOGGING": "상세 로그 활성화",
  "CMD_ENABLE_PHNODE_INSPECTOR": "PhNode 검사기 활성화",
  "CMD_GET_PHNODE_INSPECTOR_URL": "PhNode를 검사하는 방법",
  "CMD_ENABLE_LIVE_PREVIEW_LOGS": "실시간 미리보기 로그",
  "CMD_OPEN_BRACKETS_SOURCE": "{APP_NAME} 소스 열기",
  "CREATING_LAUNCH_SCRIPT_TITLE": "{APP_NAME} 명령 줄 바로가기",
  "ERROR_CREATING_LAUNCH_SCRIPT": "명령 줄 바로가기를 설치하는 동안 오류가 발생했습니다. <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting'>이런 문제를 해결하기 위한 제안</a>을 시도해 보세요.<br/><br/>원인: {0}",
  "ERROR_CLTOOLS_RMFAILED": "기존의 <code>/usr/local/bin/brackets</code> 심볼릭 링크를 제거할 수 없습니다.",
  "ERROR_CLTOOLS_MKDIRFAILED": "<code>/usr/local/bin</code> 디렉토리를 만들 수 없습니다.",
  "ERROR_CLTOOLS_LNFAILED": "<code>/usr/local/bin/brackets</code> 심볼릭 링크를 만들 수 없습니다.",
  "ERROR_CLTOOLS_SERVFAILED": "내부 오류입니다.",
  "ERROR_CLTOOLS_NOTSUPPORTED": "현재 운영체제(OS)가 명령줄 바로가기를 지원하지 않습니다.",
  "LAUNCH_SCRIPT_CREATE_SUCCESS": "성공! 이제부터 명령 줄에서 쉽게 {APP_NAME}를 시작할 수 있습니다: 파일을 열기 위해 <code>brackets myFile.txt</code> 또는 프로젝트를 전환하기 위해 <code>brackets myFolder</code>. <br/><br/>명령 줄에서 {APP_NAME}를 사용하기 위한 <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments'>더 자세한 정보</a>.",
  "ERROR_LOADING_EXTENSION": "확장 프로그램을 로드하는 중에 오류가 발생했습니다.",
  "ERROR_NO_EXTENSION_PACKAGE": "현재 프로젝트에서 <code>package.json</code> 파일이 감지되지 않습니다. 현재 프로젝트가 유효한 {APP_NAME} 확장 프로그램인가요?</br> 자세한 내용은 <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>이 링크를</a> 참조하십시오.",
  "ERROR_INVALID_EXTENSION_PACKAGE": "<code>package.json</code> 파일이 유효하지 않은 JSON입니다.</br> 자세한 내용은 <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>이 링크를</a> 참조하십시오.",
  "ERROR_INVALID_EXTENSION_PACKAGE_FIELDS": "<code>package.json</code> 에 누락된 필수 필드: [{0}]</br> 자세한 내용은 <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>이 링크를</a> 참조하십시오.",
  "ERROR_NODE_JS_CRASH_TITLE": "이런! 문제가 발생했습니다.",
  "ERROR_NODE_JS_CRASH_MESSAGE": "문제가 발생하여 {APP_NAME}을(를) 다시 시작해야 합니다. 걱정하지 마십시오. 다시 시작하기 전에 모든 작업을 저장하려고 합니다. </br>(오류: ERROR_NODE_JS_CRASH)",
  "LANGUAGE_TITLE": "언어 변경",
  "LANGUAGE_MESSAGE": "언어:",
  "LANGUAGE_SUBMIT": "{APP_NAME} 재시작",
  "LANGUAGE_CANCEL": "취소",
  "LANGUAGE_SYSTEM_DEFAULT": "시스템 언어",
  "HEALTH_DATA_NOTIFICATION": "상태 보고서 환경설정",
  "HEALTH_FIRST_POPUP_TITLE": "개인정보 보호정책",
  "HEALTH_DATA_DO_TRACK": "내가 {APP_NAME}을(를) 어떻게 사용하는지에 대한 익명 정보를 공유하세요",
  "HEALTH_DATA_NOTIFICATION_MESSAGE": "{APP_NAME} <strong>은 개인 식별 정보를 수집하거나 처리하지 않지만</strong> 개인정보 보호를 위해 <strong>익명의 사용 통계를 수집합니다</strong> . 익명 데이터는 GDPR/CCPA 통지 요구 사항에서 제외되지만 익명 데이터 수집을 거부할 수도 있는 선택권이 필요하다고 생각합니다.<br><br> <strong>도움말 &gt; 상태 보고서를</strong> 선택하여 데이터를 보거나 <strong>익명 데이터를 공유하지 않도록 선택할</strong> 수 있습니다. 이러한 <strong>익명의</strong> 앱 사용 통계 및 오류 보고서는 기능의 우선순위를 지정하고, 버그를 찾고, 사용성 문제를 파악하여 {APP_NAME} 사용 환경을 개선하는 데 도움이 됩니다. 이 데이터가 없으면 우리는 어떤 기능을 구축할 가치가 있는지 알 수 없습니다!<br><br>",
  "HEALTH_DATA_PREVIEW": "{APP_NAME} 상태 보고서",
  "HEALTH_DATA_PREVIEW_INTRO": "<p>{APP_NAME}은 <strong>개인 식별 정보를 수집하거나 처리하지 않지만</strong> 개인정보 보호를 위해 <strong>익명의 사용 통계를 수집합니다</strong> . 이러한 <strong>익명의</strong> 앱 사용 통계 및 오류 보고서는 기능의 우선순위를 지정하고, 버그를 찾고, 사용성 문제를 파악하여 {APP_NAME} 사용 환경을 개선하는 데 도움이 됩니다.</p><p> 다음은 활성화된 <em>경우</em> 다음 건강 보고서에서 전송될 데이터의 미리보기입니다. (&#39;Caught Critical error&#39;라고 표시된 오류 로그는 개발자 콘솔을 참조하세요.)</p>",
  "INLINE_TIMING_EDITOR_TIME": "시간",
  "INLINE_TIMING_EDITOR_PROGRESSION": "진행",
  "BEZIER_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd><kbd>←</kbd><kbd>→</kbd> Move selected point<br><kbd class='text'>Shift</kbd> Move by ten units<br><kbd class='text'>Tab</kbd> Switch points",
  "STEPS_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd> 단계를 증가 또는 감소 <br><kbd>←</kbd><kbd>→</kbd> '시작' 또는 '끝내기'",
  "INLINE_TIMING_EDITOR_INVALID": "이전의 값 <code>{0}</code>이 유효하지 않으므로 표시된 기능이 <code>{1}</code>로 변경되었습니다. 문서가 첫 번째 수정으로 업데이트됩니다.",
  "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP": "현재색",
  "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP": "원본색",
  "COLOR_EDITOR_RGBA_BUTTON_TIP": "RGBa 형식",
  "COLOR_EDITOR_HEX_BUTTON_TIP": "16 진수",
  "COLOR_EDITOR_HSLA_BUTTON_TIP": "HSLa 형식",
  "COLOR_EDITOR_0X_BUTTON_TIP": "16진수(0x) 형식",
  "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR": "{0} ({1}시간 사용)",
  "COLOR_EDITOR_USED_COLOR_TIP_PLURAL": "{0} ({1}시간 사용)",
  "CMD_JUMPTO_DEFINITION": "정의로 이동",
  "CMD_SHOW_PARAMETER_HINT": "파라메터 정보를 표시",
  "NO_ARGUMENTS": "<매개변수가 없습니다>",
  "DETECTED_EXCLUSION_TITLE": "자바스크립트 파일 추론 문제",
  "DETECTED_EXCLUSION_INFO": "{APP_NAME}에서 <span class='dialog-filename'>{0}을(를</span> ) 처리하는 중에 문제가 발생했습니다.<br><br> 이 파일은 더 이상 코드 힌트, 정의로 이동 또는 빠른 편집을 위해 처리되지 않습니다. 이 파일을 다시 활성화하려면 프로젝트에서 <code>.phcode.json</code> 열고 <code>jscodehints.detectedExclusions</code> 편집하세요.<br><br> 이는 {APP_NAME} 버그일 가능성이 높습니다. 이 파일의 사본을 제공할 수 있는 경우 여기에 이름이 지정된 파일에 대한 링크와 함께 <a href='https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue'>버그를 신고해</a> 주세요.",
  "CMD_REFACTOR": "리팩터링",
  "CMD_EXTRACTTO_VARIABLE": "변수로 추출",
  "CMD_EXTRACTTO_FUNCTION": "함수로 추출",
  "ERROR_TERN_FAILED": "Tern에서 데이터를 가져올 수 없습니다.",
  "ERROR_EXTRACTTO_VARIABLE_NOT_VALID": "선택은 표현식을 형성하지 않습니다",
  "ERROR_EXTRACTTO_FUNCTION_NOT_VALID": "선택한 블록은 일련의 명령문 또는 표현식을 나타내야 합니다.",
  "ERROR_EXTRACTTO_VARIABLE_MULTICURSORS": "변수로 추출이 다중 커서에서 작동하지 않음",
  "ERROR_EXTRACTTO_FUNCTION_MULTICURSORS": "함수로 추출이 다중 커서에서 작동하지 않음",
  "EXTRACTTO_FUNCTION_SELECT_SCOPE": "대상 범위 선택",
  "EXTRACTTO_VARIABLE_SELECT_EXPRESSION": "표현식 선택",
  "CMD_REFACTORING_RENAME": "파일명 변경",
  "CMD_REFACTORING_TRY_CATCH": "Try Catch로 감싸기",
  "CMD_REFACTORING_CONDITION": "상태로 포장",
  "CMD_REFACTORING_GETTERS_SETTERS": "게터/세터 생성",
  "CMD_REFACTORING_ARROW_FUNCTION": "화살표 함수로 변환",
  "DESCRIPTION_CODE_REFACTORING": "JavaScript 코드 리팩토링 활성화/비활성화",
  "ERROR_TRY_CATCH": "Try-catch 블록으로 래핑할 유효한 코드 선택",
  "ERROR_WRAP_IN_CONDITION": "조건 블록에서 래핑할 유효한 코드 선택",
  "ERROR_ARROW_FUNCTION": "함수 표현식 안에 커서를 놓습니다.",
  "ERROR_GETTERS_SETTERS": "개체 표현식의 멤버에 커서를 놓습니다.",
  "ERROR_RENAME_MULTICURSOR": "다중 커서를 사용할 때 이름을 바꿀 수 없습니다.",
  "ERROR_RENAME_QUICKEDIT": "이 식별자는 이 함수 외부의 다른 곳에서 참조되므로 이름을 바꿀 수 없습니다.",
  "ERROR_RENAME_GENERAL": "선택한 텍스트의 이름을 바꿀 수 없습니다",
  "JSHINT_NAME": "JSHint",
  "CMD_ENABLE_QUICK_VIEW": "QuickView 사용",
  "CMD_ENABLE_SELECTION_VIEW": "선택 보기",
  "TOOLTIP_CLICK_TO_EDIT_COLOR": "색상을 수정하려면 여기를 클릭하세요.",
  "CMD_TOGGLE_RECENT_PROJECTS": "최근에 사용한 프로젝트",
  "REMOVE_FROM_RECENT_PROJECTS": "최근 프로젝트에서 제거",
  "DOCS_MORE_LINK": "상세 정보",
  "DOCS_MORE_LINK_MDN_TITLE": "문서를 읽으려면 클릭하세요.",
  "COLLAPSE_ALL": "모두 접기",
  "EXPAND_ALL": "모두 펼치기",
  "COLLAPSE_CURRENT": "현재 코드 접기",
  "EXPAND_CURRENT": "현재 코드 펼치기",
  "RECENT_FILES_DLG_HEADER": "최근 파일",
  "RECENT_FILES_DLG_CLEAR_BUTTON_LABEL": "분명한",
  "RECENT_FILES_DLG_CLEAR_BUTTON_TITLE": "작업 세트에 없는 파일 지우기",
  "RECOVER_UNSAVED_FILES_TITLE": "저장되지 않은 파일을 복구하시겠습니까?",
  "RECOVER_UNSAVED_FILES_MESSAGE": "이전 세션에서 저장되지 않은 파일을 복원하시겠습니까?",
  "RECOVER_UNSAVED_FILES_RESTORE": "복원하다",
  "DISCARD_UNSAVED_FILES_RESTORE": "버리다",
  "DESCRIPTION_CLOSE_BRACKETS": "괄호(), 중괄호{}, 대괄호[]를 자동으로 닫으려면 true",
  "DESCRIPTION_CLOSE_OTHERS_ABOVE": "작업중인 파일 콘텍스트 메뉴에서 \"위의 목록 닫기\"를 제거하려면 false",
  "DESCRIPTION_CLOSE_OTHERS_BELOW": "작업중인 파일 콘텍스트 메뉴에서 \"아래 목록 닫기\"를 제거하려면 false",
  "DESCRIPTION_CLOSE_OTHERS": "작업중인 파일 콘텍스트 메뉴에서 \"다른 파일 닫기\"를 제거하려면 false",
  "DESCRIPTION_CLOSE_TAGS": "태그 종료 옵션 설정",
  "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS": "자동으로 닫지 말아야 할 태그 목록",
  "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING": "시작 태그 > 입력 시 닫기",
  "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING": "종료 태그 / 입력 시 닫기",
  "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS": "열릴 때 빈 줄 하나를 포함해야 하는 태그 목록",
  "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD": "들여쓰기 수준을 변경할 때 접을 수 있는 섹션 마커를 항상 생성하려면 true",
  "DESCRIPTION_CODE_FOLDING_ENABLED": "코드 접기를 활성화 하려면 true",
  "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER": "빈 공간에 마우스 포인터를 두는 경우에만 섹션 접기 마커를 표시하려면 true",
  "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL": "모두 접기를 얼마나 깊게 적용할 것인지 수준을 제한합니다",
  "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE": "섹션 접기 아이콘을 표시하기 위한 최소 라인 수",
  "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES": "파일 또는 프로젝트를 닫거나 다시 열 때 접은 섹션을 기억해야 한다면 true",
  "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE": "편집기 안에서 선택한 텍스트에 대한 코드 접기 기능을 활성화 하려면 true",
  "DESCRIPTION_DISABLED_DEFAULT_EXTENSIONS": "비활성화된 기본 확장",
  "DESCRIPTION_ATTR_HINTS": "HTML 속성 힌트 활성/비활성",
  "DESCRIPTION_CSS_PROP_HINTS": "CSS/LESS/SCSS 속성 힌트 활성/비활성",
  "DESCRIPTION_JS_HINTS": "JavaScript 코드 힌트 활성/비활성",
  "DESCRIPTION_JS_HINTS_TYPE_DETAILS": "JavaScript 코드 힌트에 데이터 타입 상세 활성/비활성",
  "DESCRIPTION_PREF_HINTS": "환경설정 코드 힌트 활성/비활성",
  "DESCRIPTION_SPECIAL_CHAR_HINTS": "HTML 엔터티 힌트 활성/비활성",
  "DESCRIPTION_SVG_HINTS": "SVG 코드 힌트 활성/비활성",
  "DESCRIPTION_HTML_TAG_HINTS": "HTML 태그 힌트 활성/비활성",
  "DESCRIPTION_URL_CODE_HINTS": "HTML & CSS/LESS/SCSS의 URL 힌트 활성/비활성",
  "DESCRIPTION_DRAG_DROP_TEXT": "드래그 앤 드롭 기능 활성/비활성",
  "DESCRIPTION_HEALTH_DATA_TRACKING": "상태 데이터 추적 활성화",
  "DESCRIPTION_HIGHLIGHT_MATCHES": "문서 내에서 일치하는 문자열 자동 강조 활성화",
  "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN": "현재 커서가 있는 토큰과 일치하는 모든 문자열 강조(선택 불필요)",
  "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY": "선택 항목이 완전한 토큰인 경우에만 강조",
  "DESCRIPTION_INSERT_HINT_ON_TAB": "탭에서 현재 선택한 코드 힌트를 삽입하려면 true",
  "DESCRIPTION_NO_HINTS_ON_DOT": ". 입력 시 JS 코드 힌트를 자동으로 표시하지 않으려면 true",
  "DESCRIPTION_JSHINT_OPTIONS": "JSHint에 대한 기본 옵션이 있는 개체입니다. 사용 가능한 모든 JSHint 옵션에 대해서는 다음 URL을 참조하십시오. https://jshint.com/docs/options/",
  "DESCRIPTION_LANGUAGE": "언어 별 설정",
  "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS": "파일 확장자를 통해 언어 이름 매핑",
  "DESCRIPTION_LANGUAGE_FILE_NAMES": "파일 이름을 통해 언어 이름 매핑",
  "DESCRIPTION_LINEWISE_COPY_CUT": "선택 영역이 없을 때 복사 및 잘라내기를 수행하면 커서가 있는 전체 줄을 복사하거나 잘라냅니다.",
  "DESCRIPTION_INPUT_STYLE": "CodeMirror가 입력 및 포커스를 처리하는 방식을 선택합니다. 기본값인 textarea 또는 스크린 리더에 더 나은 contenteditable일 수 있습니다(불안정).",
  "DESCRIPTION_LINTING_ENABLED": "코드 검사를 활성화 하려면 true",
  "DESCRIPTION_ASYNC_TIMEOUT": "비동기 구문 검사 초과 시간을 밀리세컨드로 표기",
  "DESCRIPTION_LINTING_PREFER": "최초 실행 구문 검사 배열",
  "DESCRIPTION_LIVE_DEV_MULTIBROWSER": "실험적 실시간 미리보기를 활성화 하려면 true",
  "DESCRIPTION_USE_PREFERED_ONLY": "제공자에 의해 기술된 linting.prefer 만으로 실행하려면 true",
  "DESCRIPTION_MAX_CODE_HINTS": "한 번에 표시되는 최대 코드 힌트",
  "DESCRIPTION_PATH": "경로 별 설정",
  "DESCRIPTION_PROXY": "확장기능 설치를 위해 사용된 프록시 서버 URL",
  "DESCRIPTION_SCROLL_PAST_END": "문서 끝을 넘어선 스크롤을 활성화 하려면 true",
  "DESCRIPTION_SHOW_CODE_HINTS": "모든 코드 힌트를 비활성화 하려면 false",
  "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING": "문자를 선택한 경우 깜빡이는 커서 표시",
  "DESCRIPTION_SHOW_LINE_NUMBERS": "코드 왼쪽의 “여백”에 행 번호를 표시하려면 true",
  "DESCRIPTION_RULERS_COLUMNS": "편집기에서 세로 눈금자를 그리는 데 사용되는 열 번호 배열입니다. 예: [80, 100]",
  "DESCRIPTION_RULERS_COLORS": "편집기의 눈금자 옵션에 해당하는 눈금자 색상 배열입니다. 예: [\"#3d3d3d\", \"빨간색\"]",
  "DESCRIPTION_RULERS_ENABLED": "편집기 눈금자를 활성화하려면 true이고, 그렇지 않으면 false입니다.",
  "DESCRIPTION_SMART_INDENT": "새 블록을 만들 때 자동 들여쓰기",
  "DESCRIPTION_SOFT_TABS": "소프트 탭 작동을 끄려면 false",
  "DESCRIPTION_SORT_DIRECTORIES_FIRST": "프로젝트 트리에서 디렉토리 우선 정렬하려면 true",
  "DESCRIPTION_SPACE_UNITS": "공백 기반의 들여쓰기를 위한 공백 수",
  "DESCRIPTION_STATIC_SERVER_PORT": "실시간 미리보기를 위한 빌트인 서버 포트 번호",
  "DESCRIPTION_STYLE_ACTIVE_LINE": "커서가 있는 행의 배경 색을 강조하려면 true",
  "DESCRIPTION_TAB_SIZE": "탭 표시를 위한 공백 수",
  "DESCRIPTION_USE_TAB_CHAR": "공백 대신 탭을 사용하려면 true",
  "DESCRIPTION_UPPERCASE_COLORS": "인라인 색상 편집기에서 대문자 16진수 색을 생성하려면 true",
  "DESCRIPTION_WORD_WRAP": "뷰포트 폭을 초과하는 행 감싸기",
  "DESCRIPTION_SEARCH_AUTOHIDE": "편집기에 포커스가 맞춰지는 즉시 검색을 닫습니다.",
  "DESCRIPTION_DETECTED_EXCLUSIONS": "통제 불가능한 실행 Tern을 유발하도록 감지된 파일 목록",
  "DESCRIPTION_INFERENCE_TIMEOUT": "파일 인식 시 Tern이 초과될 때 까지의 시간",
  "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR": "상태 표시 줄에 오류를 표시하려면 true",
  "DESCRIPTION_QUICK_VIEW_ENABLED": "빠른 보기를 활성화 하려면 true",
  "DESCRIPTION_SELECTION_VIEW_ENABLED": "선택 보기를 활성화하려면 true",
  "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW": "URL 없는 확장 기능의 이미지 미리보기를 표시하려면 true",
  "DESCRIPTION_NUMBER_QUICK_VIEW": "편집기에서 숫자 위로 마우스를 가져가면 빠른 보기를 표시하려면 true",
  "DESCRIPTION_THEME": "{APP_NAME} 테마 선택",
  "DESCRIPTION_USE_THEME_SCROLLBARS": "사용자 정의 스크롤 바를 허용하려면 true",
  "DESCRIPTION_LINTING_COLLAPSED": "구문 검사 패널을 접어 두려면 true",
  "DESCRIPTION_FONT_FAMILY": "글꼴 변경",
  "DESCRIPTION_DESKTOP_ZOOM_SCALE": "0.1(더 작게 보기)에서 2(더 크고 더 확대된 보기) 범위의 확대/축소 배율을 선택합니다. 데스크톱 앱에서만 사용 가능",
  "DESCRIPTION_FONT_SIZE": "글꼴 크기 변경(예: 13px)",
  "DESCRIPTION_FIND_IN_FILES_NODE": "노드 기반 검색을 활성화 하려면 true",
  "DESCRIPTION_FIND_IN_FILES_INSTANT": "빠른 검색을 활성화 하려면 true",
  "DESCRIPTION_FONT_SMOOTHING": "맥 전용: 서브픽셀 안티 에일리어싱을 활성화 하려면 \"subpixel-antialiased\" 회색조 안티 에일리어싱을 활성화 하려면 \"antialiased\"",
  "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW": "분할 보기에서 파일 환경 설정 열기를 비 활성화 하려면 false",
  "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE": "사용자 환경 설정 파일을 좌측/상단 창에서 열려면 false",
  "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED": "창 헤더의 닫기 버튼을 통해 마지막으로 닫힌 창을 접으려면 true",
  "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS": "헤더에 닫기 버튼과 반전 보기 버튼 표시 전환.",
  "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT": "/*\n * 기본 설정이 지원되는 읽기 전용 파일입니다.\n * {APP_NAME} 제공.\n * 이 파일을 참조하여 기본 설정을 수정하세요.\n * \"phcode.json\" 파일이 다른 창에 열립니다.\n * 내부 환경 설정 사용 방법에 대한 자세한 내용은\n * {APP_NAME}, https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences의 웹페이지를 참조하세요.\n */",
  "DEFAULT_PREFERENCES_JSON_DEFAULT": "기본",
  "DESCRIPTION_PURE_CODING_SURFACE": "{APP_NAME}에서 코드 전용 모드를 실행하고 다른 모든 UI 요소 숨기기를 활성화 하려면 true",
  "DESCRIPTION_INDENT_LINE_COMMENT": "줄 주석의 들여쓰기를 활성화하려면 true",
  "DESCRIPTION_RECENT_FILES_NAV": "최근 파일에서 탐색 활성화/비활성화",
  "DESCRIPTION_LIVEDEV_WEBSOCKET_PORT": "라이브 미리 보기를 위해 WebSocket 서버가 실행되는 포트",
  "DESCRIPTION_LIVE_DEV_HIGHLIGHT_SETTINGS": "라이브 미리보기 하이라이트 설정",
  "DESCRIPTION_LIVEDEV_ENABLE_REVERSE_INSPECT": "라이브 미리보기 역방향 검사를 비활성화하려면 false",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW": "미리보기가 없습니다!",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW_DETAILS": "미리 볼 HTML 파일을 선택하십시오",
  "DESCRIPTION_LIVEDEV_PREVIEW_RESTRICTED": "미리보기를 사용할 수 없습니다!",
  "DESCRIPTION_LIVEDEV_PREVIEW_RESTRICTED_DETAILS": "이 HTML 파일은 현재 프로젝트의 일부가 아닙니다. 보안상의 이유로 프로젝트 파일만 실시간 미리보기가 가능합니다. 이 파일을 미리 보려면 포함된 폴더를 별도의 프로젝트로 엽니다.",
  "DESCRIPTION_LIVEDEV_MAIN_HEADING": "어 오!<br> 현재 브라우저는 실시간 미리보기를 지원하지 않습니다.",
  "DESCRIPTION_LIVEDEV_MAIN_SPAN": "<a href=\"https://phcode.io\" style=\"color: white\">phcode.io</a> 에서 Windows, Mac 및 Linux용 기본 앱을 다운로드하여 최고의 라이브 미리 보기 경험을 얻으십시오.<br>",
  "DESCRIPTION_LIVEDEV_SECURITY_POPOUT_MESSAGE": "실시간 미리보기용 파일을 열려고 합니다. 이 프로젝트의 소스를 신뢰하는 경우에만 진행하세요. 계속하려면 '프로젝트 신뢰'를 클릭하고, 소스를 신뢰하지 않으면 이 창을 닫으세요.",
  "DESCRIPTION_LIVEDEV_SECURITY_TRUST_MESSAGE": "실시간 미리보기용 파일을 열려고 합니다. 해당 프로젝트의 소스를 신뢰하시는 경우에만 '프로젝트 신뢰'를 클릭하여 진행해주세요!",
  "CONFIRM_EXTERNAL_BROWSER_TITLE": "팝업이 차단됨",
  "CONFIRM_EXTERNAL_BROWSER_MESSAGE": "실시간 미리보기 페이지에서 이 URL({0})을 열도록 허용하시겠습니까?",
  "TRUST_PROJECT": "신뢰 및 실행 미리보기 - {0}",
  "TRUST_AUTHORS": "이 프로젝트의 작성자를 신뢰하시나요?",
  "DOWNLOAD_FAILED": "다운로드 실패.",
  "DOWNLOAD_COMPLETE": "다운로드를 완료하였습니다!",
  "UPDATE_SUCCESSFUL": "업데이트 성공!",
  "UPDATE_FAILED": "업데이트가 실패!",
  "VALIDATION_FAILED": "검증에 실패했습니다!",
  "INITIALISATION_FAILED": "초기화 실패!",
  "CLEANUP_FAILED": "정리 실패!",
  "WARNING_TYPE": "경고!",
  "CLICK_RESTART_TO_UPDATE": "다시 시작을 클릭하여 브래킷을 업데이트하십시오.",
  "UPDATE_ON_NEXT_LAUNCH": "업데이트는 재실행 시 적용됩니다.",
  "GO_TO_SITE": "다시 시도하려면 <a href = \"http://brackets.io/\">brackets.io</a> 로 이동하세요.",
  "INTERNET_UNAVAILABLE": "인터넷에 연결할 수 없습니다.",
  "UPDATEDIR_READ_FAILED": "업데이트 디렉토리를 읽을 수 없습니다.",
  "UPDATEDIR_CLEAN_FAILED": "업데이트 디렉토리를 정리할 수 없습니다.",
  "INITIAL_DOWNLOAD": "업데이트 다운로드 중...",
  "RETRY_DOWNLOAD": "다운로드 실패. 재시도 중...시도",
  "VALIDATING_INSTALLER": "다운로드를 완료하였습니다! 설치 프로그램 확인 중...",
  "CHECKSUM_DID_NOT_MATCH": "체크섬이 일치하지 않습니다.",
  "INSTALLER_NOT_FOUND": "설치 프로그램을 찾을 수 없습니다.",
  "DOWNLOAD_ERROR": "다운로드하는 동안 오류가 발생했습니다.",
  "NETWORK_SLOW_OR_DISCONNECTED": "네트워크 연결이 끊겼거나 너무 느립니다.",
  "RESTART_BUTTON": "재시작",
  "LATER_BUTTON": "나중",
  "DESCRIPTION_AUTO_UPDATE": "{APP_NAME} 자동 업데이트 활성화/비활성화",
  "AUTOUPDATE_ERROR": "오류!",
  "AUTOUPDATE_IN_PROGRESS": "업데이트가 이미 진행 중입니다.",
  "NUMBER_WITH_PERCENTAGE": "{0}%",
  "CMD_FIND_RELATED_FILES": "관련 파일 찾기",
  "PHP_VERSION_INVALID": "PHP 버전을 구문 분석하는 동안 오류가 발생했습니다. \"php –version\" 명령의 출력을 확인하십시오.",
  "PHP_UNSUPPORTED_VERSION": "코드 힌트, 매개변수 힌트, 정의로 이동 등과 같은 PHP 관련 도구를 활성화하려면 PHP7 런타임을 설치하세요. 발견된 버전: {0}",
  "PHP_EXECUTABLE_NOT_FOUND": "PHP 런타임을 찾을 수 없습니다. PHP7 런타임을 설치하고 PHP 환경 설정에서 \"executablePath\"를 적절하게 업데이트하십시오. 이를 통해 코드 힌트, 매개변수 힌트, 정의로 점프 등과 같은 PHP 관련 도구를 사용할 수 있습니다.",
  "PHP_PROCESS_SPAWN_ERROR": "PHP 프로세스를 시작하는 동안 오류 코드 {0}이(가) 발생했습니다.",
  "PHP_SERVER_ERROR_TITLE": "오류",
  "PHP_SERVER_MEMORY_LIMIT_INVALID": "제공한 메모리 제한이 잘못되었습니다. PHP 환경 설정을 검토하여 올바른 값을 설정하십시오.",
  "DESCRIPTION_PHP_TOOLING_CONFIGURATION": "PHP 도구 기본 구성 설정",
  "OPEN_PREFERENNCES": "환경 설정 열기",
  "LANGUAGE_TOOLS_PREFERENCES": "언어 도구에 대한 기본 설정",
  "FIND_ALL_REFERENCES": "모든 참조 찾기",
  "REFERENCES_IN_FILES": "참조",
  "REFERENCE_IN_FILES": "참조",
  "REFERENCES_NO_RESULTS": "현재 커서 위치에 사용할 수 있는 참조가 없습니다.",
  "CMD_FIND_DOCUMENT_SYMBOLS": "문서 기호 찾기",
  "CMD_FIND_PROJECT_SYMBOLS": "프로젝트 기호 찾기",
  "REMOTE_DEBUGGING_ENABLED": "로컬 호스트에서 활성화된 원격 디버깅:",
  "REMOTE_DEBUGGING_PORT_INVALID": "포트 {0}에서 원격 디버깅을 활성화할 수 없습니다. 포트 번호는 {1}에서 {2} 사이여야 합니다.",
  "DESCRIPTION_EXTERNAL_APPLICATION_ASSOCIATE": "파일 확장자를 외부 응용 프로그램에 매핑합니다. 구문: \"<file_type>\": \"<default|applicationName|ApplicationPath>\", \"default\"를 사용하여 파일 유형에 대한 시스템 기본 응용 프로그램에서 파일을 엽니다.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_TITLE": "외부 편집기에서 그래픽 파일을 엽니다.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_MSG": "현재 폴더에 {APP_NAME}에서 지원하지 않는 그래픽 파일 형식이 있습니다.<br/> 이제 특정 파일 형식을 외부 편집기와 연결할 수 있습니다. 연결되면 파일 트리에서 파일을 두 번 클릭하여 기본 응용 프로그램에서 .xd, .psd, .jpg, .png, .ai, .svg와 같은 그래픽 파일을 열 수 있습니다.<br/><br/> 그래픽 파일 형식을 해당 기본 응용 프로그램과 연결하려면 &#39;확인&#39; 버튼을 클릭하십시오.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_CNF_MSG": "다음 파일 형식은 기본 응용 프로그램과 성공적으로 연결되었습니다.<br/> {0} &#39;디버그-&gt;기본 설정 파일 열기&#39; 메뉴로 이동하여 phcode.json에서 새 파일 형식 연결을 삭제/추가할지 여부에 대한 기본 설정을 변경할 수 있습니다.",
  "UNSUPPORTED_BROWSER_TITLE": "브라우저가 지원되지 않습니다",
  "UNSUPPORTED_BROWSER_MESSAGE": "최신 브라우저(출시된 지 3년 이내)를 사용하십시오.",
  "UNSUPPORTED_BROWSER_MOBILE_TITLE": "지원되지 않는 모바일 브라우저",
  "UNSUPPORTED_BROWSER_MOBILE": "모바일 및 태블릿 브라우저는 현재 완전히 지원되지 않습니다. 이 대화 상자를 닫을 수 있지만 Phoenix의 일부 기능은 이 브라우저에서 작동하지 않습니다.<br/><br/> 우리는 iOS 및 Android용 기본 앱을 개발하기 위해 노력하고 있습니다. <a href=\"https://github.com/phcode-dev/phoenix/discussions/1046\" target=\"_blank\">여기에서 토론에 참여하십시오!</a>",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER_TITLE": "브라우저에서 지원하지 않는 로컬 폴더 액세스",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER": "죄송합니다. 현재 브라우저가 로컬 폴더 열기를 지원하지 않는 것 같습니다. 이 기능을 사용하려면 Chrome, Edge 또는 Opera를 사용하는 것이 좋습니다.<br/><br/> 또는 완전한 지원을 제공하기 위해 Windows, Mac, Linux, iOS 및 Android용 기본 앱을 개발하고 있습니다. <a href=\"https://github.com/phcode-dev/phoenix/discussions/1047\" target=\"_blank\">업데이트를 계속 지켜봐 주세요!</a>",
  "ATTENTION_SAFARI_USERS": "Safari 사용자 주의",
  "ATTENTION_SAFARI_USERS_MESSAGE": "<span>Safari는 7일 이내에 사이트를 다시 방문하지 않으면 웹사이트 데이터를 자동으로 삭제합니다. {APP_NAME}은 프로젝트를 저장하기 위해 브라우저 저장소를 사용하며, 이 정책으로 인해 프로젝트가 삭제될 수 있습니다.<br/><br/> <a href='https://phcode.io' target='_blank' style='color: white'>https://phcode.io</a> 에서 <strong>macOS 데스크탑 앱을 다운로드하는</strong> 것이 좋습니다.</span>",
  "CANNOT_PUBLISH_LARGE_PROJECT": "대규모 프로젝트를 게시할 수 없음",
  "CANNOT_PUBLISH_LARGE_PROJECT_MESSAGE": "피닉스는 아직 실험적인 알파 단계입니다. 500개 이상의 파일이 있는 프로젝트의 동기화는 아직 활성화하지 않았습니다.",
  "SHARE_WEBSITE": "웹사이트 게시 및 공유?",
  "PUBLISH": "게시",
  "PUBLISH_CONSENT_MESSAGE": "변경 사항을 빠르게 미리 보고 웹 사이트를 다른 사람과 공유하십시오. Phoenix는 {0}에서 귀하를 위해 이 웹사이트를 게시할 수 있습니다. 게시된 링크는 30일 동안 유효합니다. </br>웹사이트를 게시하고 공유하시겠습니까?",
  "PUBLISH_SYNC_IN_PROGRESS": "미리보기를 위해 동기화 진행 중...",
  "PUBLISH_PAGE": "이 사이트를 게시하고 공유하려면 클릭하세요.",
  "PUBLISH_VIEW_PAGE": "게시된 페이지를 보려면 클릭하세요.",
  "MISSING_FIELDS": "누락된 필드",
  "PLEASE_FILL_ALL_REQUIRED": "빨간색으로 강조 표시된 모든 필수 필드를 작성하십시오",
  "CODE_EDITOR": "코드 편집기",
  "BUILD_THE_WEB": "웹 구축",
  "IMPORT_PROJECT": "프로젝트 가져오기",
  "GITHUB_PROJECT": "GitHub 프로젝트",
  "NEW_PROJECT_FROM_GITHUB": "GitHub의 새 프로젝트",
  "GITHUB_REPO_URL": "GitHub 저장소 URL:",
  "CREATE_PROJECT": "프로젝트 생성",
  "SETTING_UP_PROJECT": "프로젝트 설정",
  "LOCATION": "위치 :",
  "DOWNLOADING": "다운로드 중...",
  "DOWNLOADING_FILE": "{0} 다운로드 중...",
  "EXTRACTING_FILES_PROGRESS": "파일 {1}개 중 {0}개를 추출하는 중입니다.",
  "COMPRESS_FILES_PROGRESS": "{1}개 파일 중 {0}개를 압축하는 중입니다.",
  "DOWNLOAD_FAILED_MESSAGE": "다운로드 URL이 유효한지 확인하십시오. </br>주의: Phoenix는 알파 버전이므로 25MB보다 큰 Private Repos 및 GitHub URL은 허용되지 않습니다.",
  "PLEASE_SELECT_A_FOLDER": "폴더를 선택하세요...",
  "UNZIP_IN_PROGRESS": "파일 압축을 푸는 중...",
  "UNZIP_FAILED": "오류: 압축을 풀지 못했습니다.",
  "CONFIRM_REPLACE_TITLE": "교체 확인",
  "KEEP_BOTH": "둘 다 유지",
  "EXPLORE": "HTML 게임",
  "BLOG": "블로그",
  "PHOENIX_DEFAULT_PROJECT": "기본 프로젝트",
  "PROJECT_NAME": "프로젝트 이름:",
  "NEW_HTML": "새 HTML 프로젝트",
  "LICENSE": "라이센스 및 크레딧:",
  "PREVIEW": "시사",
  "BUILD_WEBSITE": "웹사이트 구축",
  "VIEW_MORE": "더보기...",
  "NEW_PROJECT_NOTIFICATION": "이 아이콘을 클릭하면 &#39;새 프로젝트&#39; 창이 다시 열립니다.</br> 최근 프로젝트, 폴더 열기를 확인하거나 템플릿에서 프로젝트를 시작하세요.</br><img src=\"styles/images/new_project.png\"><br/> <a href='#' style='float:right;'>좋아요</a>",
  "BEAUTIFY_CODE_NOTIFICATION": "코드를 아름답게 하려면 여기를 클릭하거나 <b>`{0}`를</b> 누르세요.</br><img src=\"styles/images/beautify.gif\"><br/> <a href='#' style='float:right;'>좋아요</a>",
  "DEFAULT_PROJECT_NOTIFICATION": "열려면 여기를 클릭하십시오<br/> 피닉스의 <b>기본 프로젝트</b> .</br> <a href='#' style='float:right;'>좋아요</a>",
  "DIRECTORY_REPLACE_MESSAGE": "선택한 폴더 <span class='dialog-filename'>{0}</span> 이(가) 비어 있지 않습니다. 폴더 내용을 프로젝트로 바꾸시겠습니까?",
  "DEFAULT_PROJECT_HTML_CLICK_HERE": "편집기에서 이 HTML 파일을 열려면 여기를 클릭하세요. 커서는 이 &ltspan&gt에 해당하는 코드를 가리킵니다.",
  "BUILD_WEBSITE_SECTION": "웹사이트 구축",
  "LEARN_SECTION": "예제로 배우기",
  "CREATE_EXTENSION_SECTION": "{APP_NAME} 확장 프로그램 및 테마 만들기",
  "CREATE_EXTENSION": "확장 프로그램 만들기",
  "CREATE_THEME": "테마 만들기",
  "WEBPAGE_HOME_PAGE": "홈페이지",
  "WEBPAGE_BLOG": "블로그 페이지",
  "WEBPAGE_DASHBOARD": "HTML 대시보드",
  "WEBPAGE_BOOTSTRAP_EXAMPLES": "부트스트랩 예제",
  "PROJECTS_AT_A_GLANCE": "프로젝트 개요",
  "PROJECT_AT_GLANCE_DESCRIPTION": "시작하려면 동영상을 시청하세요.",
  "PROJECT_FROM_BROWSER": "브라우저에 저장됨",
  "PROJECT_FROM_BROWSER_TERSE": "브라우저 저장 공간",
  "PROJECT_SHOW_ON_STARTUP": "시작 시 이 대화 상자 표시",
  "GUIDED_LIVE_PREVIEW": "실시간 미리 보기를 보려면 HTML 파일에서 일부 코드를 변경하십시오.</br> <a href='#' style='float:right;'>좋아요</a>",
  "GUIDED_LIVE_PREVIEW_POPOUT": "이 버튼을 클릭하면 실시간 미리보기가 새 탭으로 표시됩니다.</br> <a href='#' style='float:right;'>좋아요</a>",
  "ENJOYING_APP": "{APP_NAME}을(를) 즐기고 계신가요?",
  "GITHUB_STARS_POPUP": "<div>귀하의 지원은 우리 소규모 팀이 <b style='color: darkblue'>phcode.dev를</b> 더욱 향상시키려는 동기를 부여하는 데 도움이 됩니다.<br/> 별표를 표시하거나 GitHub에서 후원해 주세요.",
  "GITHUB_STARS_POPUP_TWITTER": "피드백을 제공하거나 Twitter에서 소식을 전하세요.",
  "TEST_TRANSLATE": "이것을 사용하여 번역을 테스트하십시오",
  "BEAUTIFY_ERROR": "코드를 아름답게 할 수 없습니다. 구문을 확인하십시오.",
  "BEAUTIFY_ERROR_ORIGINAL_CHANGED": "미화할 수 없습니다. 미화 후 에디터 텍스트가 변경되었습니다.",
  "BEAUTIFY_PROJECT_BUSY_MESSAGE": "파일 미화 {0}",
  "BEAUTIFY_ERROR_SELECTION": "미화할 수 없습니다.</br>불완전한 코드 블록이 선택되었거나 구문이 잘못되었습니다.",
  "BEAUTIFY_OPTIONS": "코드 미화 작동 방식을 제어하는 옵션",
  "BEAUTIFY_OPTION_PRINT_WIDTH": "beautifier가 줄 바꿈할 줄 길이를 지정하십시오.",
  "BEAUTIFY_OPTION_SEMICOLON": "모든 문장 끝에 세미콜론 추가",
  "BEAUTIFY_OPTION_SINGLE_QUOTE": "큰따옴표 대신 작은따옴표 사용",
  "BEAUTIFY_OPTION_QUOTE_PROPS": "개체의 속성이 인용될 때 변경",
  "BEAUTIFY_OPTION_BRACKET_SAME_LINE": "다음 줄에 혼자 있는 대신 여러 줄 HTML(HTML, JSX, Vue, Angular) 요소의 >를 마지막 줄 끝에 배치합니다(자체 닫는 요소에는 적용되지 않음).",
  "BEAUTIFY_OPTION_SINGLE_ATTRIBUTE_PER_LINE": "HTML, Vue 및 JSX에서 행당 단일 속성 적용",
  "BEAUTIFY_OPTION_PROSE_WRAP": "마크다운 파일의 인쇄 너비를 초과하는 경우 산문을 줄입니다.",
  "BEAUTIFY_OPTION_PRINT_TRAILING_COMMAS": "여러 줄 쉼표로 구분된 구문 구조에서 가능한 한 후행 쉼표를 인쇄합니다."
});