/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "Προεπιλογή Συστήματος",
  "PROJECT_BUSY": "Λειτουργίες Έργου σε εξέλιξη",
  "DUPLICATING": "Αντιγραφή {0}",
  "MOVING": "Μετακίνηση {0}",
  "COPYING": "Αντιγραφή {0}",
  "DELETING": "Διαγραφή {0}",
  "RENAMING": "Μετονομασία",
  "GENERIC_ERROR": "(error {0})",
  "NOT_FOUND_ERR": "Το αρχείο δεν βρέθηκε.",
  "NOT_READABLE_ERR": "Το αρχείο δεν μπορεί να διαβαστεί.",
  "EXCEEDS_MAX_FILE_SIZE": "Αρχεία που ξεπερνούν τα {0} MB δεν μπορούν να ανοίξουν στο {APP_NAME}.",
  "NO_MODIFICATION_ALLOWED_ERR": "Ο φάκελος δεν μπορεί να τροποποιηθεί.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "Δεν επιτρέπεται να κάνεις τροποποιήσεις.",
  "CONTENTS_MODIFIED_ERR": "Το αρχείο έχει τροποποιηθεί εκτός του {APP_NAME}.",
  "UNSUPPORTED_ENCODING_ERR": "Άγνωστη μορφή κωδικοποίησης",
  "ENCODE_FILE_FAILED_ERR": "Το {AP_NAME} δεν μπόρεσε να κωδικοποιήσει τα περιεχόμενα του αρχείου.",
  "DECODE_FILE_FAILED_ERR": "Το {AP_NAME} δεν μπόρεσε να αποκωδικοποιήσει τα περιεχόμενα του αρχείου.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "Το {AP_NAME} προς το παρόν δεν υποστηρίζει αρχεία κειμένου με κωδικοποίηση UTF-16.",
  "FILE_EXISTS_ERR": "Αυτό το αρχείο ή ο φάκελος υπάρχουν ήδη.",
  "FILE": "αρχείο",
  "FILE_TITLE": "Αρχείο",
  "DIRECTORY": "φάκελος",
  "DIRECTORY_TITLE": "Φάκελος",
  "DIRECTORY_NAMES_LEDE": "Ονόματα καταλόγου",
  "FILENAMES_LEDE": "Ονόματα αρχείων",
  "FILENAME": "Όνομα αρχείου",
  "DIRECTORY_NAME": "Όνομα φακέλου",
  "ERROR_LOADING_PROJECT": "Σφάλμα φόρτωσης project",
  "OPEN_DIALOG_ERROR": "Σφάλμα προέκυψε κατά τη διαδικασία εμφάνισης του παραθύρου ανοίγματος αρχείου. (error {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "Σφάλμα προέκυψε κατά τη διαδικασία φόρτωσης του φακέλου <span class='dialog-filename'>{0}</span>. (error {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "Σφάλμα προέκυψε κατά τη διαδικασία διαβάσματος των περιεχομένων του φακέλου <span class='dialog-filename'>{0}</span>. (error {1})",
  "ERROR_OPENING_FILE_TITLE": "Σφάλμα ανοίγματος αρχείου",
  "ERROR_OPENING_FILE": "Σφάλμα προέκυψε κατά τη διαδικασία ανοίγματος του αρχείου <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_OPENING_FILES": "Σφάλμα προέκυψε κατά τη διαδικασία ανοίγματος των παρακάτω αρχείων:",
  "ERROR_RELOADING_FILE_TITLE": "Σφάλμα επαναφόρτωσης αλλαγών από το δίσκο",
  "ERROR_RELOADING_FILE": "Σφάλμα προέκυψε κατά τη διαδικασία επαναφόρτωσης του αρχείου <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_SAVING_FILE_TITLE": "Σφάλμα αποθήκευσης αρχείου",
  "ERROR_SAVING_FILE": "Σφάλμα προέκυψε κατά τη διαδικασία αποθήκευσης του αρχείου <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_FILE_TITLE": "Σφάλμα μετονομασίας αρχείου",
  "ERROR_RENAMING_FILE": "Σφάλμα προέκυψε κατά τη διαδικασία μετονομασίας αρχείου <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "Το αρχείο ή ο κατάλογος δεν αποτελεί μέρος του έργου που έχει ανοίξει αυτήν τη στιγμή. Δυστυχώς, μόνο τα αρχεία του έργου μπορούν να μετονομαστούν σε αυτό το σημείο.",
  "ERROR_MOVING_FILE_TITLE": "Σφάλμα μετακίνησης {0}",
  "ERROR_MOVING_FILE": "Παρουσιάστηκε σφάλμα κατά την προσπάθεια μετακίνησης του {2} <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "Αδυναμία μετακίνησης του αρχείου/φακέλου, καθώς δεν αποτελούν μέρος του τρέχοντος έργου.",
  "ERROR_DELETING_FILE_TITLE": "Σφάλμα διαγραφής αρχείου",
  "ERROR_DELETING_FILE": "Σφάλμα προέκυψε κατά τη διαδικασία διαγραφής του αρχείου <span class='dialog-filename'>{0}</span>. {1}",
  "INVALID_FILENAME_TITLE": "Μη έγκυρο {0} όνομα",
  "CANNOT_PASTE_TITLE": "Αδύνατη η επικόλληση {0}",
  "ERR_TYPE_PASTE_FAILED": "Παρουσιάστηκε σφάλμα κατά την επικόλληση <span class='dialog-filename'>{0}</span> στο <span class='dialog-filename'>{1}</span>",
  "CANNOT_DUPLICATE_TITLE": "Δεν είναι δυνατό να",
  "ERR_TYPE_DUPLICATE_FAILED": "Παρουσιάστηκε σφάλμα κατά την αντιγραφή <span class='dialog-filename'>{0}</span>",
  "INVALID_FILENAME_MESSAGE": "Τα όνομα αρχείων δεν μπορούν να περιέχουν τους ακόλουθους χαρακτήρες: {0} ή οποιεσδήποτε system reserved λέξεις.",
  "ENTRY_WITH_SAME_NAME_EXISTS": "Ένα αρχείο ή κατάλογος με όνομα <span class='dialog-filename'>{0}</span> υπάρχει ήδη.",
  "ERROR_CREATING_FILE_TITLE": "Σφάλμα δημιουργίας {0}",
  "ERROR_CREATING_FILE": "Σφάλμα προέκυψε κατά τη διαδικασία δημιουργίας του {0} <span class='dialog-filename'>{1}</span>. {2}",
  "ERROR_MIXED_DRAGDROP": "Δεν είναι δυνατό το άνοιγμα ενός φακέλου ταυτόχρονα με το άνοιγμα άλλων αρχείων.",
  "ERROR_KEYMAP_TITLE": "Σφάλμα κατά την ανάγνωση του χάρτη κλειδιών χρήστη",
  "ERROR_KEYMAP_CORRUPT": "Το αρχείο χάρτη κλειδιού σας δεν είναι έγκυρο JSON. Το αρχείο θα ανοίξει έτσι ώστε να μπορείτε να διορθώσετε τη μορφή.",
  "ERROR_LOADING_KEYMAP": "Το αρχείο αντιστοίχισης κλειδιών δεν είναι ένα έγκυρο αρχείο κειμένου με κωδικοποίηση UTF-8 και δεν μπορεί να φορτωθεί",
  "ERROR_RESTRICTED_COMMANDS": "Δεν μπορείτε να αντιστοιχίσετε εκ νέου συντομεύσεις σε αυτές τις εντολές: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "Δεν μπορείτε να αντιστοιχίσετε εκ νέου αυτές τις συντομεύσεις: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "Αντιστοίχιση πολλών συντομεύσεων σε αυτές τις εντολές: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "Έχετε πολλές συνδέσεις με αυτές τις συντομεύσεις: {0}",
  "ERROR_INVALID_SHORTCUTS": "Αυτές οι συντομεύσεις δεν είναι έγκυρες: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "Αντιστοίχιση συντομεύσεων σε ανύπαρκτες εντολές: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "Σφάλμα ανάγνωσης προτιμήσεων",
  "ERROR_PREFS_CORRUPT": "Το αρχείο προτιμήσεών σας δεν είναι έγκυρο JSON. Το αρχείο θα ανοίξει έτσι ώστε να μπορείτε να διορθώσετε τη μορφή. Θα χρειαστεί να επανεκκινήσετε το {AP_NAME} για να ισχύσουν οι αλλαγές.",
  "ERROR_PROJ_PREFS_CORRUPT": "Το αρχείο προτιμήσεων έργου σας δεν είναι έγκυρο JSON. Το αρχείο θα ανοίξει έτσι ώστε να μπορείτε να διορθώσετε τη μορφή. Θα χρειαστεί να φορτώσετε ξανά το έργο για να εφαρμοστούν οι αλλαγές.",
  "ERROR_IN_BROWSER_TITLE": "Ουπς! Το {APP_NAME} δεν τρέχει ακόμα σε browsers.",
  "ERROR_IN_BROWSER": "To {APP_NAME} είναι γραμμένο σε HTML, αλλά αυτή τη στιγμή τρέχει σαν native εφαρμογή έτσι ώστε να μπορείτε να επεξεργαστείτε τοπικά αρχεία. Παρακαλούμε να χρησιμοποιήσετε το application shell στο <b>github.com/adobe/brackets-shell</b> repo για να τρέξετε το {APP_NAME}.",
  "ERROR_MAX_FILES_TITLE": "Σφάλμα κατά τη διαδικασία indexing των αρχείων",
  "ERROR_MAX_FILES": "Ο μέγιστος αριθμός αρχείων έχει καταχωρηθεί index. Λειτουργίες που ψάχνουν αρχεία στο index μπορεί να μην δουλεύουν σωστά.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "Σφάλμα ανοίγματος browser",
  "ERROR_CANT_FIND_CHROME": "Ο Google Chrome browser δεν βρέθηκε. Παρακαλούμε σιγουρευτείτε ότι είναι εγκατεστημένος.",
  "ERROR_LAUNCHING_BROWSER": "Σφάλμα προέκυψε κατά τη διαδικασία ανοίγματος του browser. (error {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "Σφάλμα Live Preview",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "Σύνδεση στον Browser",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "Για να συνδεθεί το Live Preview, ο Chrome πρέπει να επανεκκινηθεί με το remote debugging (απομακρυσμένη αποσφαλμάτωση) ενεργοποιημένο.<br /><br />Θέλετε να επανεκκινήσετε τον Chrome και να ενεργοποιήσετε το remote debugging;",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "Αδυναμία φόρτωσης της σελίδας Live Development",
  "LIVE_DEV_NEED_HTML_MESSAGE": "Ανοίξτε ένα αρχείο HTML έτσι ώστε να ξεκινήσει η άμεση προεπισκόπηση (Live Preview).",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "Για να ανοίξετε το Live Preview με ένα αρχείο από κάποιον server, πρέπει να προσδιορίσετε μια διεύθυνση (Base URL) για αυτό το project.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "Σφάλμα κατά τη διαδικασία εκκίνησης του HTTP server για την άμεση επεξεργασία αρχείων. Παρακαλούμε προσπαθήστε ξανά.",
  "LIVE_DEVELOPMENT_INFO_TITLE": "Καλώς ήρθατε στο Live Preview!",
  "LIVE_DEVELOPMENT_INFO_MESSAGE": "Το Live Preview συνδέει το {APP_NAME} με τον browser σας. Ανοίγει μια προεπισκόπηση του HTML αρχείου σας στον browser, και την ανανεώνει στιγμιαία ενώ επεξεργάζεστε τον κώδικα.<br /><br />Σε τούτη την πρώιμη έκδοση του {APP_NAME}, το Live Preview δουλεύει μόνο με <strong>Google Chrome</strong> και ανανεώνει άμεσα την σελίδα ενώ επεξεργάζεστε <strong>αρχεία CSS ή HTML</strong>. Αλλαγές σε αρχεία JavaScript ανανεώνονται αυτόματα όταν κάνετε αποθήκευση.<br /><br />(Το μήνυμα αυτό θα αυτοκαταστραφεί μετά την πρώτη εμφάνιση του.)",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "Για περισσότερες πληροφορίες δείτε εδώ: <a href='{0}' title='{0}'>Troubleshooting Live Development connection errors</a>.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "Live Preview",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "Live Preview: Σύνδεση…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "Live Preview: Εκκίνηση…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "Αποσύνδεση Live Preview",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "Live Preview (κάντε αποθήκευση για να ανανεωθεί)",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "Επιλογή αρχείου για προεπισκόπηση",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "Επαναφόρτωση σελίδας",
  "LIVE_DEV_CLICK_POPOUT": "Αναδυόμενη ζωντανή προεπισκόπηση σε νέο παράθυρο",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "Καρφίτσωμα στη σελίδα προεπισκόπησης ξεκαρ",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "Live Preview (αδυναμία ανανέωσης λόγο συντακτικού λάθους)",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "Το Live Preview ακυρώθηκε επειδή τα developer tools του browser ανοίχτηκαν",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "Το Live Preview ακυρώθηκε επειδή η σελίδα στον browser έκλεισε",
  "LIVE_DEV_NAVIGATED_AWAY": "Το Live Preview ακυρώθηκε επειδή ο browser πήγε σε μια σελίδα που δεν είναι μέρος του τρέχων project",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "Το Live Preview ακυρώθηκε. Δεν ξέρουμε γιατί. ({0})",
  "SAVE_CLOSE_TITLE": "Αποθήκευση Αλλαγών",
  "SAVE_CLOSE_MESSAGE": "Θέλετε να αποθηκεύσετε τις αλλαγές που κάνατε στο έγγραφο <span class='dialog-filename'>{0}</span>?",
  "SAVE_CLOSE_MULTI_MESSAGE": "Θέλετε να αποθηκεύσετε τις αλλαγές σας στα παρακάτω αρχεία;",
  "EXT_MODIFIED_TITLE": "Εξωτερικές Αλλαγές",
  "CONFIRM_DELETE_TITLE": "Επιβεβαίωση Διαγραφής",
  "CONFIRM_FILE_DELETE": "Είστε σίγουρος ότι θέλετε να διαγράψε το αρχείο <span class='dialog-filename'>{0}</span>?",
  "CONFIRM_FOLDER_DELETE": "Είστε σίγουρος ότι θέλετε να διαγράψετε τον φάκελο <span class='dialog-filename'>{0}</span>?",
  "FILE_DELETED_TITLE": "Το Αρχείο Διαγράφηκε",
  "EXT_MODIFIED_WARNING": "<span class='dialog-filename'>Το {0}</span> έχει τροποποιηθεί σε δίσκο έξω από το {AP_NAME}. <br /><br />Θέλετε να αποθηκεύσετε το αρχείο και να αντικαταστήσετε αυτές τις αλλαγές;",
  "EXT_MODIFIED_MESSAGE": "Το <span class='dialog-filename'>{0}</span> έχει τροποποιηθεί στο δίσκο, αλλά υπάρχουν και μη αποθηκευμένες αλλαγές στο {APP_NAME}.<br /><br />Ποια έκδοση θέλετε να κρατήσετε;",
  "EXT_DELETED_MESSAGE": "Το <span class='dialog-filename'>{0}</span> έχει διαγραφεί στον δίσκο, αλλά έχει μη αποθηκευμένες αλλαγές στο {APP_NAME}.<br /><br />Θέλετε να κρατήσετε τις αλλαγές σας;",
  "WINDOW_UNLOAD_WARNING": "Είστε βέβαιοι ότι θέλετε να πλοηγηθείτε σε ένα διαφορετικό URL και να αφήσετε Brackets;",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "Έχετε μη αποθηκευμένες αλλαγές! Είστε βέβαιοι ότι θέλετε να πλοηγηθείτε σε ένα διαφορετικό URL και να αφήσετε Brackets;",
  "DONE": "Έγινε",
  "OK": "OK",
  "CANCEL": "Ακύρωση",
  "DONT_SAVE": "Να Μην Αποθηκευτεί",
  "SAVE": "Αποθήκευση",
  "SAVE_AS": "Αποθήκευση Ως…",
  "SAVE_AND_OVERWRITE": "Αντικατάσταση",
  "DELETE": "Διαγραφή",
  "BUTTON_YES": "Ναι",
  "BUTTON_NO": "Όχι",
  "FIND_MATCH_INDEX": "{0} από {1}",
  "FIND_NO_RESULTS": "Δεν βρέθηκαν αποτελέσματα",
  "FIND_QUERY_PLACEHOLDER": "Εύρεση…",
  "FIND_HISTORY_MAX_COUNT": "Μέγιστος αριθμός αντικειμένων αναζήτησης στο ιστορικό αναζήτησης",
  "REPLACE_PLACEHOLDER": "Αντικατάσταση με…",
  "BUTTON_REPLACE_ALL": "Όλα…",
  "BUTTON_REPLACE_BATCH": "Παρτίδα...",
  "BUTTON_REPLACE_ALL_IN_FILES": "Αντικατάσταση...",
  "BUTTON_REPLACE": "Αντικατάσταση",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "Επόμενη Αντιστοιχία",
  "BUTTON_PREV_HINT": "Προηγούμενη Αντιστοιχία",
  "BUTTON_CASESENSITIVE_HINT": "Ταίριασμα υπόθεσης",
  "BUTTON_REGEXP_HINT": "Κανονική έκφραση",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "Αντικατάσταση χωρίς αναίρεση",
  "REPLACE_WITHOUT_UNDO_WARNING": "Επειδή περισσότερα από {0} αρχεία πρέπει να αλλάξουν, {AP_NAME} θα τροποποιήσει τα αρχεία που δεν έχουν ανοιχτεί στο δίσκο. <br />Δεν θα μπορείτε να αναιρέσετε αντικαταστάσεις σε αυτά τα αρχεία.",
  "BUTTON_REPLACE_WITHOUT_UNDO": "Αντικατάσταση χωρίς αναίρεση",
  "OPEN_FILE": "Άνοιγμα Αρχείου",
  "SAVE_FILE_AS": "Αποθήκευση Αρχείου",
  "CHOOSE_FOLDER": "Επίλεξε ένα φάκελο",
  "RELEASE_NOTES": "Release Notes",
  "NO_UPDATE_TITLE": "Έχετε την τελευταία έκδοση!",
  "NO_UPDATE_MESSAGE": "Τρέχετε την τελευταία έκδοση του {APP_NAME}.",
  "FIND_REPLACE_TITLE_LABEL": "Αντικατάσταση",
  "FIND_REPLACE_TITLE_WITH": "με",
  "FIND_TITLE_LABEL": "Βρέθηκε",
  "FIND_TITLE_SUMMARY": "— {0} {1} {2} σε {3}",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "στο <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_NO_SCOPE": "στο project",
  "FIND_IN_FILES_ZERO_FILES": "Το φίλτρο εξαιρεί όλα τα αρχεία {0}",
  "FIND_IN_FILES_FILE": "αρχείο",
  "FIND_IN_FILES_FILES": "αρχεία",
  "FIND_IN_FILES_MATCH": "αντιστοιχία",
  "FIND_IN_FILES_MATCHES": "αντιστοιχίες",
  "FIND_IN_FILES_MORE_THAN": "Πάνω από ",
  "FIND_IN_FILES_PAGING": "{0}&mdash;{1}",
  "FIND_IN_FILES_FILE_PATH": "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "Ctrl/Cmd κλικ για επέκταση/σύμπτυξη όλων",
  "FIND_IN_FILES_INDEXING": "Ευρετήριο για Άμεση Αναζήτηση...",
  "FIND_IN_FILES_INDEXING_PROGRESS": "Ευρετηρίαση {0} αρχείων {1} για άμεση αναζήτηση...",
  "REPLACE_IN_FILES_ERRORS_TITLE": "Αντικατάσταση λαθών",
  "REPLACE_IN_FILES_ERRORS": "Τα ακόλουθα αρχεία δεν τροποποιήθηκαν επειδή άλλαξαν μετά την αναζήτηση ή δεν ήταν δυνατή η εγγραφή τους.",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "Σφάλμα λήψης πληροφοριών αναβάθμισης",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "Προέκυψε σφάλμα κατά τη διαδικασία λήψης πληροφοριών της τελευταίας αναβάθμισης από τον server. Παρακαλούμε βεβαιωθείτε ότι είστε συνδεδεμένος στο internet και προσπαθήστε ξανά.",
  "NEW_FILE_FILTER": "Νέο σύνολο εξαίρεσης...",
  "CLEAR_FILE_FILTER": "Να μην εξαιρεθούν αρχεία",
  "NO_FILE_FILTER": "Δεν εξαιρέθηκαν αρχεία",
  "EXCLUDE_FILE_FILTER": "Εξαίρεση {0}",
  "EDIT_FILE_FILTER": "Επεξεργασία...",
  "FILE_FILTER_DIALOG": "Επεξεργασία συνόλου εξαίρεσης",
  "FILE_FILTER_INSTRUCTIONS": "Εξαίρεση αρχείων και φακέλων που ταιριάζουν με οποιαδήποτε από τις ακόλουθες συμβολοσειρές/δευτερεύουσες συμβολοσειρές ή <a href='{0}' title='{0}'>χαρακτήρες μπαλαντέρ</a>. Εισαγάγετε κάθε συμβολοσειρά σε μια νέα γραμμή.",
  "FILTER_NAME_PLACEHOLDER": "Ονομασία αυτού του συνόλου εξαίρεσης (προαιρετικό)",
  "FILTER_NAME_REMAINING": "{0} χαρακτήρες που απομένουν",
  "FILE_FILTER_CLIPPED_SUFFIX": "και {0} περισσότερα",
  "FILTER_COUNTING_FILES": "Μέτρηση αρχείων...",
  "FILTER_FILE_COUNT": "Επιτρέπει {0} από {1} αρχεία {2}",
  "FILTER_FILE_COUNT_ALL": "Επιτρέπει σε όλα τα αρχεία {0} {1}",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "Δεν υπάρχει διαθέσιμη Γρήγορη επεξεργασία για την τρέχουσα θέση του δρομέα",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "CSS Quick Edit: τοποθέτηση του δρομέα σε ένα όνομα κλάσης",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "CSS Quick Edit: μη ολοκληρωμένο χαρακτηριστικό κλάσης",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "CSS Quick Edit: μη ολοκληρωμένο χαρακτηριστικό id",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "CSS Quick Edit: τοποθέτηση του δρομέα σε tag, κλάση ή id",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "Λειτουργία CSS Timing Γρήγορη επεξεργασία: μη έγκυρη σύνταξη",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "JS Γρήγορη Επεξεργασία: τοποθετήστε τον κέρσορα στο όνομα της συνάρτησης",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "Δεν υπάρχουν διαθέσιμα Γρήγορα έγγραφα για την τρέχουσα θέση του δρομέα",
  "PROJECT_LOADING": "Φόρτωση…",
  "UNTITLED": "Άτιτλο",
  "WORKING_FILES": "Αρχεία Εργασίας",
  "TOP": "Κορυφή",
  "BOTTOM": "Κάτω",
  "LEFT": "Αριστερά",
  "RIGHT": "Δεξιά",
  "CMD_SPLITVIEW_NONE": "Χωρίς Διαίρεση",
  "CMD_SPLITVIEW_VERTICAL": "Κάθετη Διαίρεση",
  "CMD_SPLITVIEW_HORIZONTAL": "Οριζόντια",
  "SPLITVIEW_MENU_TOOLTIP": "Διαχωρισμός του επεξεργαστή κατακόρυφα ή οριζόντια",
  "GEAR_MENU_TOOLTIP": "Ρύθμιση συνόλου εργασίας",
  "SPLITVIEW_INFO_TITLE": "Ήδη Ανοιχτό",
  "SPLITVIEW_MULTIPANE_WARNING": "Το αρχείο είναι ήδη ανοιχτό σε άλλο τμήμα παραθύρου. Το {AP_NAME} σύντομα θα υποστηρίξει το άνοιγμα του ίδιου αρχείου σε περισσότερα από ένα παράθυρο. Μέχρι τότε, το αρχείο θα εμφανίζεται στο παράθυρο στο οποίο είναι ήδη ανοιχτό. <br /><br />( Θα δείτε αυτό το μήνυμα μόνο μία φορά.)",
  "STATUSBAR_CURSOR_POSITION": "Σειρά {0}, Στήλη {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": " — επιλεγμένη {0} στήλη",
  "STATUSBAR_SELECTION_CH_PLURAL": " — επιλεγμένες {0} στήλες",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " — επιλεγμένη {0} γραμμή",
  "STATUSBAR_SELECTION_LINE_PLURAL": " — επιλεγμένες {0} γραμμές",
  "STATUSBAR_SELECTION_MULTIPLE": " — {0} επιλογές",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "Κάντε κλικ για να αλλάξετε τις εσοχές (indentation) σε κενά",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "Κάντε κλικ για να αλλάξετε τις εσοχές (indentation) σε tabs",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "Κάντε κλικ για να αλλάξετε τον αριθμό των κενών στις εσοχές",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "Κάντε κλικ για να αλλάξετε το πλάτος του tab",
  "STATUSBAR_SPACES": "Κενά:",
  "STATUSBAR_TAB_SIZE": "Μέγεθος Tab:",
  "STATUSBAR_LINE_COUNT_SINGULAR": "— {0} Γραμμή",
  "STATUSBAR_LINE_COUNT_PLURAL": "— {0} Γραμμές",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "Οι επεκτάσεις απενεργοποιήθηκαν",
  "STATUSBAR_INSERT": "INS",
  "STATUSBAR_OVERWRITE": "ΟΦ",
  "STATUSBAR_INSOVR_TOOLTIP": "Κάντε κλικ για εναλλαγή του δρομέα μεταξύ των λειτουργιών Insert (INS) και Αντικατάσταση (OVR)",
  "STATUSBAR_LANG_TOOLTIP": "Κάνε κλικ για να αλλάξεις τον τύπο του αρχείου",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. Κάντε κλικ για εναλλαγή του πίνακα αναφορών.",
  "STATUSBAR_DEFAULT_LANG": "(προεπιλογή)",
  "STATUSBAR_SET_DEFAULT_LANG": "Ορισμός ως προεπιλογή για .{0} αρχεία",
  "STATUSBAR_ENCODING_TOOLTIP": "Επιλέξτε την κωδικοποίηση",
  "ERRORS_PANEL_TITLE_MULTIPLE": "{0} Προβλήματα",
  "SINGLE_ERROR": "1 {0} Σφάλμα",
  "MULTIPLE_ERRORS": "{1} {0} Σφάλματα",
  "NO_ERRORS": "Καθόλου {0} σφάλματα - καλή δουλειά!",
  "NO_ERRORS_MULTIPLE_PROVIDER": "Δεν βρέθηκαν προβλήματα - καλή δουλειά!",
  "LINT_DISABLED": "Το Linting είναι απενεργοποιημένο",
  "NO_LINT_AVAILABLE": "Δεν υπάρχει linter διαθέσιμος για {0}",
  "NOTHING_TO_LINT": "Δεν υπάρχει κάτι για να γίνει lint",
  "LINTER_TIMED_OUT": "Το {0} έχει λήξει το χρονικό όριο μετά την αναμονή για {1} ms",
  "LINTER_FAILED": "{0} τερμάτισε με σφάλμα: {1}",
  "FILE_MENU": "Αρχείο",
  "CMD_FILE_NEW_UNTITLED": "Νέο",
  "CMD_FILE_NEW": "Νέο Αρχείο",
  "CMD_FILE_DUPLICATE": "Δημιουργία Αντιγράφου",
  "CMD_FILE_CUT": "Αποκοπή",
  "CMD_FILE_COPY": "Αντιγραφή",
  "CMD_FILE_COPY_PATH": "Αντιγραφή διαδρομής",
  "CMD_FILE_PASTE": "Επικόλληση",
  "CMD_PROJECT_NEW": "Νέο Έργο",
  "CMD_FILE_NEW_FOLDER": "Νέος Φάκελος",
  "CMD_FILE_OPEN": "Άνοιγμα…",
  "CMD_RECENT_FILES_OPEN": "Άνοιγμα πρόσφατου...",
  "CMD_ADD_TO_WORKING_SET": "Προσθήκη στα Αρχεία Εργασίας",
  "CMD_OPEN_DROPPED_FILES": "Άνοιγμα Αρχείων που ρίχτηκαν",
  "CMD_OPEN_FOLDER": "Άνοιγμα Φακέλου…",
  "CMD_FILE_CLOSE": "Κλείσιμο",
  "CMD_FILE_CLOSE_ALL": "Κλείσιμο Όλων",
  "CMD_FILE_CLOSE_LIST": "Κλείσιμο Λίστας",
  "CMD_FILE_CLOSE_OTHERS": "Κλείσιμο Άλλων",
  "CMD_FILE_CLOSE_ABOVE": "Κλείσιμο Άλλων απο πάνω",
  "CMD_FILE_CLOSE_BELOW": "Κλείσιμο Άλλων από κάτων",
  "CMD_FILE_SAVE": "Αποθήκευση",
  "CMD_FILE_SAVE_ALL": "Αποθήκευση Όλων",
  "CMD_FILE_SAVE_AS": "Αποθήκευση Ως…",
  "CMD_LIVE_FILE_PREVIEW": "Live Preview",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "Ενεργοποίηση πειραματικής προεπισκόπησης Live",
  "CMD_RELOAD_LIVE_PREVIEW": "Επαναφόρτωση ζωντανής προεπισκόπησης",
  "CMD_PROJECT_SETTINGS": "Ρυθμίσεις Project…",
  "CMD_FILE_RENAME": "Μετονομασία",
  "CMD_FILE_DELETE": "Διαγραφή",
  "CMD_INSTALL_EXTENSION": "Εγκατάσταση Επέκτασης (Extension)…",
  "CMD_EXTENSION_MANAGER": "Διαχείρηση Επεκτάσεων…",
  "CMD_FILE_REFRESH": "Ανανέωση Δέντρου Αρχείων",
  "CMD_FILE_SHOW_FOLDERS_FIRST": "Ταξινόμηση φακέλων πρώτα",
  "CMD_QUIT": "Κλείσιμο",
  "CMD_EXIT": "΄Εξοδος",
  "EDIT_MENU": "Επεξεργασία",
  "CMD_UNDO": "Αναίρεση",
  "CMD_REDO": "Επανάληψη",
  "CMD_CUT": "Αποκοπή",
  "CMD_COPY": "Αντιγραφή",
  "CMD_PASTE": "Επικόλληση",
  "CMD_SELECT_ALL": "Επιλογή Όλων",
  "CMD_SELECT_LINE": "Επιλογή Γραμμής",
  "CMD_SPLIT_SEL_INTO_LINES": "Διαίρεση επιλογής σε γραμμές",
  "CMD_ADD_CUR_TO_NEXT_LINE": "Προσθήκη κέρσοσα στην επόμενη γραμμή",
  "CMD_ADD_CUR_TO_PREV_LINE": "Προσθήκη κέρσοσα στην προηγούμενη γραμμή",
  "CMD_INDENT": "Εσοχή",
  "CMD_UNINDENT": "Αφαίρεση Εσοχής",
  "CMD_DUPLICATE": "Δημιουργία Αντιγράφου",
  "CMD_DELETE_LINES": "Διαγραφή Γραμμής",
  "CMD_COMMENT": "Εναλλαγή Σχολίου Γραμμής",
  "CMD_BLOCK_COMMENT": "Εναλλαγή Σχολίου Block",
  "CMD_LINE_UP": "Μετακίνηση Γραμμής Πάνω",
  "CMD_LINE_DOWN": "Μετακίνηση Γραμμής Κάτω",
  "CMD_OPEN_LINE_ABOVE": "Δημιουργία Γραμμής από πάνω",
  "CMD_OPEN_LINE_BELOW": "Δημιουργία Γραμμής από κάτω",
  "CMD_TOGGLE_CLOSE_BRACKETS": "Αυτόματο Κλείσιμο Αγκίστρων",
  "CMD_SHOW_CODE_HINTS": "Προβολή Υποδείξεων Κώδικα",
  "CMD_BEAUTIFY_CODE": "Ομορφοποιήστε τον κώδικα",
  "CMD_BEAUTIFY_CODE_ON_SAVE": "Ομορφοποιήστε τον κώδικα κατά την αποθήκευση",
  "FIND_MENU": "Εύρεση",
  "CMD_FIND": "Εύρεση",
  "CMD_FIND_NEXT": "Εύρεση Επόμενου",
  "CMD_FIND_PREVIOUS": "Εύρεση Προηγούμενου",
  "CMD_FIND_ALL_AND_SELECT": "Εύρεση όλων και Επιλογή",
  "CMD_ADD_NEXT_MATCH": "Προσθήκη επόμενης αντιστοίχισης στην επιλογή",
  "CMD_SKIP_CURRENT_MATCH": "Παράλειψη και προσθήκη επόμενης αντιστοίχισης",
  "CMD_FIND_IN_FILES": "Εύρεση σε Αρχεία",
  "CMD_FIND_IN_SUBTREE": "Εύρεση σε…",
  "CMD_REPLACE": "Αντικατάσταση",
  "CMD_REPLACE_IN_FILES": "Αντικατάσταση σε αρχεία",
  "CMD_REPLACE_IN_SUBTREE": "Αντικατάσταση σε...",
  "VIEW_MENU": "Προβολή",
  "CMD_HIDE_SIDEBAR": "Απόκρυψη Πλευρικής Εργαλειοθήκης",
  "CMD_SHOW_SIDEBAR": "Προβολή Πλευρικής Εργαλειοθήκης",
  "CMD_TOGGLE_SIDEBAR": "Εναλλαγή πλευρικής γραμμής",
  "CMD_TOGGLE_PANELS": "Εναλλαγή πινάκων",
  "CMD_TOGGLE_PURE_CODE": "Χωρίς περισπασμούς",
  "CMD_INCREASE_FONT_SIZE": "Αύξηση Μεγέθους Γραμματοσειράς",
  "CMD_DECREASE_FONT_SIZE": "Μείωση Μεγέθους Γραμματοσειράς",
  "CMD_RESTORE_FONT_SIZE": "Επαναφορά Μεγέθους Γραμματοσειράς",
  "CMD_SCROLL_LINE_UP": "Κύλιση Γραμμής Πάνω",
  "CMD_SCROLL_LINE_DOWN": "Κύλιση Γραμμής Κάτω",
  "CMD_TOGGLE_LINE_NUMBERS": "Αριθμοί Γραμμών",
  "CMD_TOGGLE_ACTIVE_LINE": "Επισήμανση Ενεργής Γραμμής",
  "CMD_TOGGLE_WORD_WRAP": "Αναδίπλωση Λέξης",
  "CMD_LIVE_HIGHLIGHT": "Επισήμανση Live Preview",
  "CMD_VIEW_TOGGLE_INSPECTION": "Lint Αρχείων κατά την Αποθήκευση",
  "CMD_WORKINGSET_SORT_BY_ADDED": "Ταξινόμηση κατά Σειρά Προσθήκης",
  "CMD_WORKINGSET_SORT_BY_NAME": "Ταξινόμηση κατά Όνομα",
  "CMD_WORKINGSET_SORT_BY_TYPE": "Ταξινόμηση κατά Τύπο",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "Αυτόματη Ταξινόμηση",
  "CMD_THEMES": "Θέματα...",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "Αυτόματο κλείσιμο αναζήτησης",
  "NAVIGATE_MENU": "Πλοήγηση",
  "CMD_QUICK_OPEN": "Γρήγορο Άνοιγμα",
  "CMD_GOTO_LINE": "Πήγαινε στη γραμμή",
  "CMD_GOTO_DEFINITION": "Γρήγορη Αναζήτηση Ορισμού",
  "CMD_GOTO_DEFINITION_PROJECT": "Ορισμός γρήγορης εύρεσης στο Project",
  "CMD_GOTO_FIRST_PROBLEM": "Πήγαινε στο Πρώτο Σφάλμα/Προειδοποίηση",
  "CMD_TOGGLE_QUICK_EDIT": "Γρήγορη Επεξεργασία",
  "CMD_TOGGLE_QUICK_DOCS": "Γρήγορα Έγγραφα",
  "CMD_QUICK_EDIT_PREV_MATCH": "Προηγούμενη Αντιστοιχία",
  "CMD_QUICK_EDIT_NEXT_MATCH": "Επόμενη Αντιστοιχία",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "Νέος Κανόνας",
  "CMD_NEXT_DOC": "Επόμενο Έγγραφο",
  "CMD_PREV_DOC": "Προηγούμενο Έγγραφο",
  "CMD_NAVIGATE_BACKWARD": "Περιήγηση πίσω",
  "CMD_NAVIGATE_FORWARD": "Περιήγηση εμπρός",
  "CMD_NEXT_DOC_LIST_ORDER": "Επόμενο έγγραφο στην λίστα",
  "CMD_PREV_DOC_LIST_ORDER": "Προηγούμενο έγγραφο στην λίστα",
  "CMD_SHOW_IN_TREE": "Προβολή στο Δέντρο Αρχείων",
  "CMD_SHOW_IN_EXPLORER": "Εμφάνιση στην Εξερεύνηση",
  "CMD_SHOW_IN_FINDER": "Εμφάνιση στο Ευρέτη",
  "CMD_SHOW_IN_OS": "Προβολή στο Λειτουργικό Σύστημα",
  "CMD_SWITCH_PANE_FOCUS": "Εναλλαγή εστίασης παραθύρου",
  "CMD_OPEN_VFS": "Άνοιγμα εικονικού συστήματος αρχείων",
  "CMD_OPEN_VIRTUAL_SERVER": "Άνοιγμα εικονικού διακομιστή",
  "HELP_MENU": "Βοήθεια",
  "CMD_CHECK_FOR_UPDATE": "Έλεγχος για Αναβαθμίσεις",
  "CMD_HOW_TO_USE_BRACKETS": "Πώς να Χρησιμοποιήσετε το {APP_NAME}",
  "CMD_SUPPORT": "Υποστήριξη {APP_NAME}",
  "CMD_SUGGEST": "Πρότεινε Feature",
  "CMD_RELEASE_NOTES": "Release Notes",
  "CMD_GET_INVOLVED": "Συμμετέχετε",
  "CMD_SHOW_EXTENSIONS_FOLDER": "Προβολή Φακέλου Επεκτάσεων",
  "CMD_HEALTH_DATA_STATISTICS": "Έκθεση Υγείας",
  "CMD_HOMEPAGE": "Αρχική σελίδα {App_NAME}",
  "CMD_TWITTER": "{TWITTER_NAME} στο Twitter",
  "CMD_ABOUT": "Σχετικά με το {APP_TITLE}",
  "CMD_OPEN_PREFERENCES": "Άνοιξε το αρχείο προτιμήσεων",
  "CMD_OPEN_KEYMAP": "Άνοιγμα χάρτη κλειδιών χρήστη",
  "EXPERIMENTAL_BUILD": "experimental build",
  "RELEASE_BUILD": "χτίζω",
  "DEVELOPMENT_BUILD": "development build",
  "PRERELEASE_BUILD": "build προέκδοσης",
  "RELOAD_FROM_DISK": "Επαναφόρτωση από τον Δίσκο",
  "KEEP_CHANGES_IN_EDITOR": "Διατήρηση Αλλαγών στον Επεξεργαστή",
  "CLOSE_DONT_SAVE": "Κλείσιμο (Να Μην Αποθηκευτεί)",
  "RELAUNCH_CHROME": "Επανεκκίνηση Chrome",
  "ABOUT": "Σχετικά",
  "CLOSE": "Κλείσιμο",
  "ABOUT_TEXT_LINE1": "Κυκλοφορία {VERSION_MAJOR} {ΈΚΔΟΣΗ_ΕΛΆΣΣΟΝΟΣ} {ΤΎΠΟΣ ΚΑΤΑΣΚΕΥΉΣ} {ΈΚΔΟΣΗ}",
  "ABOUT_TEXT_BUILD_TIMESTAMP": "Χρονική σήμανση κατασκευής: ",
  "ABOUT_TEXT_LINE3": "Βιβλιοθήκες Τρίτων που χρησιμοποιούμε - <a href='https://github.com/phcode-dev/phoenix/tree/main/src/thirdparty/licences'> Άδειες και Απόδοση</a> . ",
  "ABOUT_TEXT_LINE4": "Τεκμηρίωση και πηγή στη <a href='https://github.com/phcode-dev/phoenix/'>διεύθυνση https://github.com/phcode-dev/phoenix/</a>",
  "ABOUT_TEXT_LINE5": "Φτιαγμένο με ❤ και JavaScript από:",
  "ABOUT_TEXT_LINE6": "Πολλοί άνθρωποι (αλλά δυσκολευόμαστε να φορτώσουμε αυτά τα δεδομένα αυτή τη στιγμή).",
  "ABOUT_TEXT_MDN_DOCS": "Τα MDN Docs και το MDN γραφικό logo είναι αδειοδοτημένα κάτω από την άδεια Creative Commons Attribution, <a href='{MDN_DOCS_LICENSE}'>CC-BY-SA 2.5 Unported</a>.",
  "UPDATE_NOTIFICATION_TOOLTIP": "Υπάρχει ένα νέο build του {APP_NAME} διαθέσιμο! Πατήστε εδώ για λεπτομέρειες.",
  "UPDATE_AVAILABLE_TITLE": "Διαθέσιμη Αναβάθμιση",
  "UPDATE_MESSAGE": "Ψιτ, υπάρχει ένα νέο build του {APP_NAME} διαθέσιμο. Μερικές από τις καινούργιες λειτουργίες:",
  "GET_IT_NOW": "Κατέβασε το τώρα!",
  "PROJECT_SETTINGS_TITLE": "Ρυθμίσεις Project για: {0}",
  "PROJECT_SETTING_BASE_URL": "Live Preview Base URL",
  "PROJECT_SETTING_BASE_URL_HINT": "Για να χρησιμοποιήσετε τοπικό server, εισάγετε μια διεύθυνση σαν και αυτή http://localhost:8000/",
  "BASEURL_ERROR_INVALID_PROTOCOL": "Το πρωτόκολλο {0} δεν υποστηρίζεται από το Live Preview&mdash;παρακαλούμε χρησιμοποιήστε http: ή https: .",
  "BASEURL_ERROR_SEARCH_DISALLOWED": "Η διεύθυνση URL δεν μπορεί να περιέχει παραμέτρους αναζήτησης όπως \"{0}\".",
  "BASEURL_ERROR_HASH_DISALLOWED": "Η διεύθυνση URL δεν μπορεί να περιέχει hashes σαν και αυτά \"{0}\".",
  "BASEURL_ERROR_INVALID_CHAR": "Οι ειδικοί χαρακτήρες όπως '{0}' πρέπει να είναι %-encoded.",
  "BASEURL_ERROR_UNKNOWN_ERROR": "Άγνωστο σφάλμα κατά την προσπέλαση της διεύθυνσης URL",
  "EMPTY_VIEW_HEADER": "<em>Άνοιγμααρχείου ενώ αυτό το τμήμα έχει την εστίαση</em>",
  "FLIPVIEW_BTN_TOOLTIP": "Αναστροφή αυτής της προβολής στο παράθυρο {0}",
  "CURRENT_THEME": "Τρέχον Θέμα",
  "USE_THEME_SCROLLBARS": "Χρήση γραμμών κύλισης θέματος",
  "FONT_SIZE": "Μέγεθος Γραμματοσειράς",
  "FONT_FAMILY": "Οικογένεια γραμματοσειρών",
  "THEMES_SETTINGS": "Ρυθμίσεις θεμάτων",
  "BUTTON_NEW_RULE": "Νέος Κανόνας",
  "INSTALL": "Εγκατάσταση",
  "UPDATE": "Αναβάθμιση",
  "REMOVE": "Κατάργηση",
  "DISABLE": "Απενεργοποίηση",
  "ENABLE": "Ενεργοποίηση",
  "OVERWRITE": "Αντικατάσταση",
  "CANT_REMOVE_DEV": "Οι επεκτάσεις στο φάκελο \"dev\" πρέπει να διαγραφούν χειροκίνητα.",
  "CANT_UPDATE": "Η αναβάθμιση δεν είναι συμβατή με αυτήν την έκδοση του {APP_NAME}.",
  "CANT_UPDATE_DEV": "Οι επεκτάσεις στον φάκελο \"dev\" δεν μπορούν να αναβαθμιστούν αυτόματα.",
  "INSTALL_EXTENSION_TITLE": "Εγκατάσταση Επέκτασης",
  "UPDATE_EXTENSION_TITLE": "Αναβάθμιση Επέκτασης",
  "INSTALL_EXTENSION_LABEL": "URL Επέκτασης",
  "INSTALL_EXTENSION_HINT": "URL αρχείου zip ή GitHub repo της επέκτασης",
  "INSTALLING_FROM": "Εγκατάσταση επέκτασης από {0}…",
  "INSTALL_SUCCEEDED": "Επιτυχής Εγκατάσταση!",
  "INSTALL_FAILED": "Ανεπιτυχής Εγκατάσταση .",
  "CANCELING_INSTALL": "Ακύρωση…",
  "CANCELING_HUNG": "Η ακύρωση της εγκατάστασης παίρνει πολύ ώρα. Κάποιο εσωτερικό σφάλμα μπορεί να έχει προκληθεί.",
  "INSTALL_CANCELED": "Η εγκατάσταση ακυρώθηκε.",
  "VIEW_COMPLETE_DESCRIPTION": "Προβολή αναλυτικής περιγραφής",
  "VIEW_TRUNCATED_DESCRIPTION": "Προβολή περικομμένης περιγραφής",
  "SORT_EXTENSION_METHOD": "Ταξινόμηση επεκτάσεων χρησιμοποιώντας DownloadCount ή Published",
  "INVALID_ZIP_FILE": "Το περιεχόμενο που κατέβηκε δεν είναι έγκυρο αρχείο zip.",
  "MISSING_PACKAGE_JSON": "Το πακέτο δεν έχει αρχείο package.json.",
  "INVALID_PACKAGE_JSON": "Το αρχείο package.json δεν είναι έγκυρο (error was: {0}).",
  "MISSING_PACKAGE_NAME": "Το αρχείο package.json δεν καθορίζει όνομα πακέτου.",
  "BAD_PACKAGE_NAME": "Το {0} δεν είναι έγκυρο όνομα αρχείου.",
  "MISSING_PACKAGE_VERSION": "Το αρχείο package.json δεν καθορίζει έκδοση πακέτου.",
  "INVALID_VERSION_NUMBER": "Ο αριθμός έκδοσης του πακέτου ({0}) δεν είναι έγκυρος.",
  "INVALID_BRACKETS_VERSION": "Η συμβολοσειρά συμβατότητας (compatibility string) ({0}) του {APP_NAME} δεν είναι έγκυρη.",
  "DISALLOWED_WORDS": "Οι λέξεις ({1}) δεν επιτρέπονται στο πεδίο {0}.",
  "NPM_INSTALL_FAILED": "Η εντολή εγκατάστασης του npm απέτυχε: {0}",
  "API_NOT_COMPATIBLE": "Η επέκταση δεν είναι συμβατή με αυτήν την έκδοση του {APP_NAME}. Εγκαταστάθηκε στον φάκελο των απενεργοποιημένων επεκτάσεων.",
  "MISSING_MAIN": "Το πακέτο δεν έχει main.js αρχείο.",
  "EXTENSION_ALREADY_INSTALLED": "Η εγκατάσταση αυτού του πακέτου θα αντικαταστήσει μια προηγούμενη εγκατάσταση επέκτασης. Να αντικατασταθεί η παλιά επέκταση;",
  "EXTENSION_SAME_VERSION": "Αυτό το πακέτο είναι η ίδια έκδοση με αυτό που είναι ήδη εγκατεστημένο. Να αντικατασταθεί η υπάρχουσα εγκατάσταση;",
  "EXTENSION_OLDER_VERSION": "Αυτό το πακέτο είναι στην έκδοση {0} η οποία είναι παλιότερη από την τρέχουσα εγκατάσταση ({1}). Να αντικατασταθεί η υπάρχουσα εγκατάσταση;",
  "DOWNLOAD_ID_IN_USE": "Εσωτερικό σφάλμα: το ID που κατέβηκε χρησιμοποιείται ήδη.",
  "NO_SERVER_RESPONSE": "Αδυναμία σύνδεσης στον server.",
  "BAD_HTTP_STATUS": "Το αρχείο δεν βρέθηκε στον server (HTTP {0}).",
  "CANNOT_WRITE_TEMP": "Αδυναμία αποθήκευσης του ληφθέντος αρχείου στο temp.",
  "ERROR_LOADING": "Η επέκταση αντιμετώπισε ένα σφάλμα κατά την εκκίνηση.",
  "MALFORMED_URL": "Η διεύθυνση URL δεν είναι έγκυρη is invalid. Please check that you entered it correctly.",
  "UNSUPPORTED_PROTOCOL": "Η διεύθυνση URL πρέπει να είναι http ή https.",
  "UNKNOWN_ERROR": "Άγνωστο εσωτερικό σφάλμα.",
  "EXTENSION_MANAGER_TITLE": "Διαχειριστής Επεκτάσεων",
  "EXTENSION_MANAGER_ERROR_LOAD": "Αδυναμία πρόσβασης στο μητρώο επεκτάσεων. Παρακαλώ προσπαθήστε αργότερα.",
  "INSTALL_EXTENSION_DRAG": "Σύρετε το.zip εδώ ή",
  "INSTALL_EXTENSION_DROP": "Πετάξτε το.zip για εγκατάσταση",
  "INSTALL_EXTENSION_DROP_ERROR": "Η εγκατάσταση/ενημέρωση ματαιώθηκε λόγω των ακόλουθων σφαλμάτων:",
  "INSTALL_FROM_URL": "Εγκατάσταση από διεύθυνση URL…",
  "INSTALL_EXTENSION_VALIDATING": "Επικύρωση...",
  "EXTENSION_AUTHOR": "Δημιουργός",
  "EXTENSION_DATE": "Ημερομηνία",
  "EXTENSION_INCOMPATIBLE_NEWER": "Αυτή η επέκταση απαιτεί νεότερη έκδοση του {APP_NAME}.",
  "EXTENSION_INCOMPATIBLE_OLDER": "Αυτή η επέκταση προς το παρόν δουλεύει μόνο με παλαιότερες εκδόσεις του {APP_NAME}.",
  "EXTENSION_LATEST_INCOMPATIBLE_NEWER": "Η έκδοση {0} αυτής της επέκτασης απαιτεί μια νεότερη έκδοση του {APP_NAME}. Αλλά μπορείτε να εγκαταστήσετε την προηγούμενη έκδοση {1}.",
  "EXTENSION_LATEST_INCOMPATIBLE_OLDER": "Η έκδοση {0} αυτής της επέκτασης λειτουργεί μόνο με παλαιότερες εκδόσεις του {APP_NAME}. Αλλά μπορείτε να εγκαταστήσετε την προηγούμενη έκδοση {1}.",
  "EXTENSION_NO_DESCRIPTION": "Δεν υπάρχει περιγραφή",
  "EXTENSION_MORE_INFO": "Περισσότερες Πληροφορίες...",
  "EXTENSION_ERROR": "Σφάλμα επέκτασης",
  "EXTENSION_KEYWORDS": "Λέξεις κλειδιά",
  "EXTENSION_TRANSLATED_USER_LANG": "Μεταφρασμένο σε {0} γλώσσες, συμπεριλαμβανομένης και της δικής σας",
  "EXTENSION_TRANSLATED_GENERAL": "Μεταφρασμένο σε {0} γλώσσες",
  "EXTENSION_TRANSLATED_LANGS": "Αυτή η επέκταση έχει μεταφραστεί σε αυτές τις γλώσσες: {0}",
  "EXTENSION_INSTALLED": "Εγκατεστημένες",
  "EXTENSION_UPDATE_INSTALLED": "Αυτή η αναβάθμιση επέκτασης έχει κατέβει και θα εγκατασταθεί όταν κλείσει το {APP_NAME}.",
  "EXTENSION_SEARCH_PLACEHOLDER": "Αναζήτηση",
  "EXTENSION_MORE_INFO_LINK": "Περισσότερα",
  "BROWSE_EXTENSIONS": "Περιήγηση Επεκτάσεων",
  "EXTENSION_MANAGER_REMOVE": "Κατάργηση Επέκτασης",
  "EXTENSION_MANAGER_REMOVE_ERROR": "Αδυναμία κατάργησης μίας ή περισσότερων επεκτάσεων: {0}. Το {APP_NAME} θα κλείσει.",
  "EXTENSION_MANAGER_UPDATE": "Αναβάθμιση Επέκτασης",
  "EXTENSION_MANAGER_UPDATE_ERROR": "Αδυναμία αναβάθμισης μίας η περισσότερων επεκτάσεων: {0}. Το {APP_NAME} θα κλείσει.",
  "EXTENSION_MANAGER_DISABLE": "Απενεργοποίηση επέκτασης",
  "EXTENSION_MANAGER_DISABLE_ERROR": "Δεν είναι δυνατή η απενεργοποίηση μίας ή περισσότερων επεκτάσεων: {0}. {AP_NAME} θα φορτώσει ξανά.",
  "MARKED_FOR_REMOVAL": "Επιλεγμένο για κατάργηση",
  "UNDO_REMOVE": "Αναίρεση",
  "MARKED_FOR_UPDATE": "Επιλεγμένο για αναβάθμιση",
  "UNDO_UPDATE": "Αναίρεση",
  "MARKED_FOR_DISABLING": "Επισημάνθηκε για απενεργοποίηση",
  "UNDO_DISABLE": "Αναίρεση",
  "CHANGE_AND_RELOAD_TITLE": "Αλλαγή επεκτάσεων",
  "CHANGE_AND_RELOAD_MESSAGE": "Για να ενημερώσετε, να καταργήσετε ή να απενεργοποιήσετε τις επισημασμένες επεκτάσεις, {AP_NAME} θα χρειαστεί να φορτώσετε εκ νέου. Θα σας ζητηθεί να αποθηκεύσετε τις μη αποθηκευμένες αλλαγές.",
  "REMOVE_AND_RELOAD": "Αφαίρεση επεκτάσεων και επαναφόρτωση",
  "CHANGE_AND_RELOAD": "Αλλαγή επεκτάσεων και επαναφόρτωση",
  "UPDATE_AND_RELOAD": "Ενημέρωση επεκτάσεων και επαναφόρτωση",
  "DISABLE_AND_RELOAD": "Απενεργοποίηση επεκτάσεων και επαναφόρτωση",
  "PROCESSING_EXTENSIONS": "Επεξεργασία αλλαγών επέκτασης...",
  "EXTENSION_NOT_INSTALLED": "Αδυναμία κατάργησης της επέκτασης {0} αφού δεν ήταν εγκατεστημένη.",
  "NO_EXTENSIONS": "Δεν υπάρχουν επεκτάσεις εγκατεστημένες ακόμα.<br>Κάντε κλικ στην καρτέλα Διαθέσιμα για να ξεκινήσετε.",
  "NO_EXTENSION_MATCHES": "Δεν βρέθηκαν επεκτάσεις που να ικανοποιούν τα κριτήρια αναζήτησης σας.",
  "REGISTRY_SANITY_CHECK_WARNING": "Να είστε προσεκτικοί όταν εγκαθιστάτε επεκτάσεις από άγνωστες πηγές.",
  "EXTENSIONS_INSTALLED_TITLE": "Εγκατεστημένες",
  "EXTENSIONS_DEFAULT_TITLE": "Προκαθορισμένο",
  "EXTENSIONS_AVAILABLE_TITLE": "Διαθέσιμες",
  "EXTENSIONS_THEMES_TITLE": "Θέματα",
  "EXTENSIONS_UPDATES_TITLE": "Αναβαθμίσεις",
  "EXTENSIONS_LAST_UPDATED": "Τελευταία Ενημέρωση",
  "EXTENSIONS_DOWNLOADS": "Λήψεις",
  "INLINE_EDITOR_NO_MATCHES": "Δεν υπάρχουν διαθέσιμες αντιστοιχίες.",
  "INLINE_EDITOR_HIDDEN_MATCHES": "Όλα τα σπίρτα κατέρρευσαν. Αναπτύξτε τα αρχεία που εμφανίζονται στα δεξιά για να δείτε τις αντιστοιχίες.",
  "CSS_QUICK_EDIT_NO_MATCHES": "Δεν υπάρχουν κανόνες CSS που να ταιριάζουν με την επιλογή σας.<br> Κάντε κλικ στο \"Νέος Κανόνας\" για να δημιουργήσετε ένα νέο.",
  "CSS_QUICK_EDIT_NO_STYLESHEETS": "Δεν υπάρχουν stylesheets στο project σας.<br>Δημιουργήστε ένα για να προσθέσετε κανόνες CSS.",
  "IMAGE_VIEWER_LARGEST_ICON": "μεγαλύτερη",
  "UNIT_PIXELS": "pixels",
  "DEBUG_MENU": "Debug",
  "ERRORS": "Σφάλματα",
  "CMD_SHOW_DEV_TOOLS": "Προβολή Developer Tools",
  "CMD_REFRESH_WINDOW": "Επαναφόρτωση {APP_NAME}",
  "CMD_RELOAD_WITHOUT_USER_EXTS": "Επαναφόρτωση χωρίς τις επεκτάσεις",
  "CMD_NEW_BRACKETS_WINDOW": "Νέο Παράθυρο {APP_NAME}",
  "CMD_LAUNCH_SCRIPT_MAC": "Εγκατάσταση συντόμευσης για την γραμμή εντολών",
  "CMD_SWITCH_LANGUAGE": "Αλλαγή Γλώσσας",
  "CMD_RUN_UNIT_TESTS": "Τρέξε Tests",
  "CMD_SHOW_PERF_DATA": "Προβολή Δεδομένων Επίδοσης",
  "CMD_ENABLE_LOGGING": "Ενεργοποίηση λεπτομερών αρχείων καταγραφής",
  "CMD_OPEN_BRACKETS_SOURCE": "Άνοιξε τον κώδικα του {APP_NAME}",
  "CREATING_LAUNCH_SCRIPT_TITLE": "{APP_NAME} Συντόμευση γραμμής εντολών",
  "ERROR_CREATING_LAUNCH_SCRIPT": "Ένα σφάλμα προέκυψε κατά την εγκατάσταση της συντόμευσης για την γραμμή εντολών. Παρακαλώ δοκίμασε <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting'>αυτές τις προτείνομενες λύσεις</a>.<br/><br/>Αιτιολογία: {0}",
  "ERROR_CLTOOLS_RMFAILED": "Δεν είναι δυνατή η αφαίρεση του υπάρχοντος symlink <code>/usr/local/bin/brackets</code> .",
  "ERROR_CLTOOLS_MKDIRFAILED": "Αποτυχία δημιουργίας φακέλου του <code>/usr/local/bin</code>.",
  "ERROR_CLTOOLS_LNFAILED": "Δεν είναι δυνατή η δημιουργία συμβολικού συνδέσμου <code>/usr/local/bin/brackets</code> .",
  "ERROR_CLTOOLS_SERVFAILED": "Εσωτερικό σφάλμα.",
  "ERROR_CLTOOLS_NOTSUPPORTED": "Η συντόμευση για την γραμμή εντολών δεν υποστηρίζεται στο συγκεκριμένο λειτουργικό σύστημα.",
  "LAUNCH_SCRIPT_CREATE_SUCCESS": "Επιτυχία! Τώρα μπορείς εύκολα να τρέξεις το {APP_NAME} από την γραμμή εντολών: <code>brackets myFile.txt</code> για να ανοίξεις ένα αρχείο ή <code>brackets myFolder</code> για να αλλάξεις project. <br/><br/><a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments'>Μάθε περισσότερα</a>για το πώς να χρησιμοποιήσεις το {APP_NAME} από την γραμμή εντολών.",
  "LANGUAGE_TITLE": "Αλλαγή Γλώσσας",
  "LANGUAGE_MESSAGE": "Γλώσσες:",
  "LANGUAGE_SUBMIT": "Επανεκκίνηση του {APP_NAME}",
  "LANGUAGE_CANCEL": "Ακύρωση",
  "LANGUAGE_SYSTEM_DEFAULT": "Προεπιλογή Συστήματος",
  "HEALTH_DATA_NOTIFICATION": "Προτιμήσεις Health Report",
  "HEALTH_FIRST_POPUP_TITLE": "{APP_NAME} Health Report",
  "HEALTH_DATA_DO_TRACK": "Κοινοποίηση ανώνυμων πληροφοριών σχετικά με το πώς χρησιμοποιώ το {APP_NAME}",
  "HEALTH_DATA_NOTIFICATION_MESSAGE": "Προκειμένου να βελτιώσουμε το {APP_NAME}, στέλνουμε περιοδικά περιορισμένα, <strong>ανώνυμα</strong> στατιστικά στοιχεία στην Adobe σχετικά με το πώς χρησιμοποιείς το {APP_NAME}. Αυτές οι πληροφορίες βοηθάνε στην καταχώρηση προτεραιοτήτων στα χαρακτηριστικά,στην εύρεση σφαλμάτων και στον εντοπισμό προβλημάτων χρηστικότητας.<br><br>Μπορείς να δεις τα δεδομένα σου ή να επιλέξεις να μην μοιραστείς κάποια επιλέγοντας <strong>Help > Health Report</strong>.<br><br><a href='https://github.com/adobe/brackets/wiki/Health-Data'>Μάθε περισσότερα για το {APP_NAME} Health Report</a>",
  "HEALTH_DATA_PREVIEW": "{APP_NAME} Health Report",
  "HEALTH_DATA_PREVIEW_INTRO": "<p>Προκειμένου να βελτιώσουμε το {APP_NAME}, στέλνουμε περιοδικά περιορισμένα, <strong>ανώνυμα</strong> στατιστικά στοιχεία στην Adobe σχετικά με το πώς χρησιμοποιείς το {APP_NAME}. Αυτές οι πληροφορίες βοηθάνε στην καταχώρηση προτεραιοτήτων στα χαρακτηριστικά,στην εύρεση σφαλμάτων και στον εντοπισμό προβλημάτων χρηστικότητας. <a href='https://github.com/adobe/brackets/wiki/Health-Data'>Μάθε περισσότερα για το {APP_NAME} Health Report</a> και πόσο ωφελεί την κοινότητα του {APP_NAME} προστατεύοντας παράλληλα την ιδιωτικότητα σου..</p><p>Παρακάτω βλέπεις μια προεπισκόπηση των δεδομένων που θα σταλούν στο επόμενο Health Report <em>εφόσον</em> είναι ενεργοποιημένο.</p>",
  "INLINE_TIMING_EDITOR_TIME": "Χρόνος",
  "INLINE_TIMING_EDITOR_PROGRESSION": "Πρόοδος",
  "BEZIER_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd><kbd>←</kbd><kbd>→</kbd>Μετακίνηση επιλεγμένου σημείου<br><kbd class='text'>Shift</kbd>Μετακίνηση κατά δέκα μονάδες<br><kbd class='text'>Καρτέλα</kbd>Σημεία αλλαγής",
  "STEPS_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd>Αύξηση ή μείωση βημάτων<br><kbd>←</kbd><kbd>→</kbd>'Έναρξη' ή 'Τέλος'",
  "INLINE_TIMING_EDITOR_INVALID": "Η παλιά τιμή <code>{0}</code> δεν είναι έγκυρη, επομένως η εμφανιζόμενη συνάρτηση άλλαξε σε <code>{1}</code> . Το έγγραφο θα ενημερωθεί με την πρώτη επεξεργασία.",
  "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP": "Τρέχων Χρώμα",
  "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP": "Αρχικό Χρώμα",
  "COLOR_EDITOR_RGBA_BUTTON_TIP": "Μορφή RGBa",
  "COLOR_EDITOR_HEX_BUTTON_TIP": "Μορφή Hex",
  "COLOR_EDITOR_HSLA_BUTTON_TIP": "Μορφή HSLa",
  "COLOR_EDITOR_0X_BUTTON_TIP": "Μορφή δεκαεξαδικού (0x)",
  "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR": "{0} (Χρησιμοποιήθηκε {1} φορά)",
  "COLOR_EDITOR_USED_COLOR_TIP_PLURAL": "{0} (Χρησιμοποιήθηκε {1} φορές)",
  "CMD_JUMPTO_DEFINITION": "Πήγαινε στον Ορισμό",
  "CMD_SHOW_PARAMETER_HINT": "Προβολή Υποδείξεων Παραμέτρων",
  "NO_ARGUMENTS": "<χωρίς παραμέτρους>",
  "DETECTED_EXCLUSION_TITLE": "Πρόβλημα συμπερασμού αρχείου JavaScript",
  "DETECTED_EXCLUSION_INFO": "{AP_NAME} έτρεξε σε προβλήματα επεξεργασίας <span class='dialog-filename'>{0}</span>. <br><br>Αυτότο αρχείο δεν θα γίνεται πλέον επεξεργασία για συμβουλές κώδικα, Μετάβαση σε ορισμό ή Γρήγορη επεξεργασία. Για να ενεργοποιήσετε ξανά αυτό το αρχείο, ανοίξτε <code>το.brackets.json</code> στο έργο σας και επεξεργαστείτε <code>JSCODEHINTS.DetectedExclussions</code> . <br><br>Αυτόείναι πιθανώς ένα σφάλμα {APP_NAME}. Εάν μπορείτε να δώσετε ένα αντίγραφο αυτού του αρχείου, παρακαλώ καταχωρήστε <a href='https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue'>ένα σφάλμα</a> με ένα σύνδεσμο προς το αρχείο που ονομάζεται εδώ.",
  "CMD_REFACTOR": "Συντελεστής",
  "CMD_EXTRACTTO_VARIABLE": "Εξαγωγή σε μεταβλητή",
  "CMD_EXTRACTTO_FUNCTION": "Εξαγωγή σε συνάρτηση",
  "ERROR_TERN_FAILED": "Δεν είναι δυνατή η λήψη δεδομένων από το Tern",
  "ERROR_EXTRACTTO_VARIABLE_NOT_VALID": "Η επιλογή δεν σχηματίζει παράσταση",
  "ERROR_EXTRACTTO_FUNCTION_NOT_VALID": "Το επιλεγμένο μπλοκ πρέπει να αντιπροσωπεύει ένα σύνολο προτάσεων ή μια παράσταση",
  "ERROR_EXTRACTTO_VARIABLE_MULTICURSORS": "Το Extract to Variable δεν λειτουργεί σε πολυκριτές",
  "ERROR_EXTRACTTO_FUNCTION_MULTICURSORS": "Το Extract to Function δεν λειτουργεί σε πολυκριτές",
  "EXTRACTTO_FUNCTION_SELECT_SCOPE": "Επιλέξτε πεδίο προορισμού",
  "EXTRACTTO_VARIABLE_SELECT_EXPRESSION": "Επιλέξτε μια παράσταση",
  "CMD_REFACTORING_RENAME": "Μετονομασία",
  "CMD_REFACTORING_TRY_CATCH": "Τυλίξτε στο Δοκιμάστε αλιευμάτων",
  "CMD_REFACTORING_CONDITION": "Τυλίξτε σε Κατάσταση",
  "CMD_REFACTORING_GETTERS_SETTERS": "Δημιουργία Getters/Setters",
  "CMD_REFACTORING_ARROW_FUNCTION": "Μετατροπή σε συνάρτηση βέλους",
  "DESCRIPTION_CODE_REFACTORING": "Ενεργοποίηση/απενεργοποίηση επανασχεδιασμού κώδικα JavaScript",
  "ERROR_TRY_CATCH": "Επιλογή έγκυρου κώδικα για αναδίπλωση σε ένα μπλοκ Try-catch",
  "ERROR_WRAP_IN_CONDITION": "Επιλογή έγκυρου κώδικα για αναδίπλωση σε ένα μπλοκ συνθήκης",
  "ERROR_ARROW_FUNCTION": "Τοποθέτηση του δρομέα μέσα σε μια παράσταση συνάρτησης",
  "ERROR_GETTERS_SETTERS": "Τοποθέτηση του δρομέα σε ένα μέλος μιας έκφρασης αντικειμένου",
  "ERROR_RENAME_MULTICURSOR": "Δεν είναι δυνατή η μετονομασία κατά τη χρήση πολλών δρομ",
  "ERROR_RENAME_QUICKEDIT": "Δεν είναι δυνατή η μετονομασία αυτού του αναγνωριστικού, καθώς αναφέρεται αλλού εκτός αυτής της συνάρτησης",
  "ERROR_RENAME_GENERAL": "Δεν είναι δυνατή η μετονομασία",
  "JSHINT_NAME": "JShint",
  "CMD_ENABLE_QUICK_VIEW": "Γρήγορη Προβολή στο Hover",
  "CMD_ENABLE_SELECTION_VIEW": "Προβολή Επιλογής",
  "CMD_TOGGLE_RECENT_PROJECTS": "Πρόσφατα Project",
  "DOCS_MORE_LINK": "Διαβάστε Περισσότερα",
  "COLLAPSE_ALL": "Συρρίκνωση όλων",
  "EXPAND_ALL": "Ανάπτυξη όλων",
  "COLLAPSE_CURRENT": "Συρρίκνωση ρεύματος",
  "EXPAND_CURRENT": "Ανάπτυξη τρέχοντος",
  "RECENT_FILES_DLG_HEADER": "Πρόσφατα αρχεία",
  "RECENT_FILES_DLG_CLEAR_BUTTON_LABEL": "Διαφανής",
  "RECENT_FILES_DLG_CLEAR_BUTTON_TITLE": "Εκκαθάριση αρχείων που δεν βρίσκονται στο σύνολο εργασίας",
  "DESCRIPTION_CLOSE_BRACKETS": "αληθές για αυτόματο κλείσιμο αγκύλων, παρενθέσεων και παρενθέσεων",
  "DESCRIPTION_CLOSE_OTHERS_ABOVE": "false για να καταργήσετε το «Κλείσιμο άλλων επάνω» από το μενού περιβάλλοντος των αρχείων εργασίας",
  "DESCRIPTION_CLOSE_OTHERS_BELOW": "false για να καταργήσετε το «Κλείσιμο άλλων παρακάτω» από το μενού περιβάλλοντος Αρχεία εργασίας",
  "DESCRIPTION_CLOSE_OTHERS": "false για να καταργήσετε το «Κλείσιμο άλλων» από το μενού περιβάλλοντος των αρχείων εργασίας",
  "DESCRIPTION_CLOSE_TAGS": "Ορίζει τις επιλογές κλεισίματος του tag",
  "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS": "Ένας πίνακας tag που δεν πρέπει να κλείνει αυτόματα",
  "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING": "Κλείσιμο όταν πληκτρολογηθεί > της ετικέτας ανοίγματος",
  "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING": "Κλείσιμο όταν πληκτρολογείται το/της ετικέτας κλεισίματος",
  "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS": "Ένας πίνακας tag που όταν ανοιχτεί έχει μια κενή γραμμή",
  "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD": "ισχύει για τη δημιουργία πάντα πτυσσόμενων δεικτών ενότητας όταν αλλάζει το επίπεδο εσοχής",
  "DESCRIPTION_CODE_FOLDING_ENABLED": "true για να ενεργοποιήσετε το δίπλωμα κώδικα",
  "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER": "αληθές για να κάνετε τους δείκτες κατάρρευσης τμημάτων ορατοί μόνο όταν μετακινείτε το ποντίκι πάνω από την υδρορροή",
  "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL": "Περιορίζει πόσα επίπεδα βαθιά Σύμπτυξη όλων ισχύει",
  "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE": "Ελάχιστες γραμμές πριν εμφανιστεί ένα εικονίδιο πτυσσόμενης ενότητας",
  "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES": "true για την απομνημόνευση συμπτυγμένων ενοτήτων, εάν κλείσετε και ανοίξετε ξανά ένα αρχείο ή ένα έργο",
  "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE": "true για να ενεργοποιήσετε την αναδίπλωση κώδικα σε επιλεγμένο κείμενο στον επεξεργαστή",
  "DESCRIPTION_DISABLED_DEFAULT_EXTENSIONS": "Προεπιλεγμένες επεκτάσεις που είναι απενεργοποιημένες",
  "DESCRIPTION_ATTR_HINTS": "Ενεργοποίηση/απενεργοποίηση υποδείξεων χαρακτηριστικών HTML",
  "DESCRIPTION_CSS_PROP_HINTS": "Ενεργοποίηση/απενεργοποίηση υποδείξεων ιδιοτήτων CSS/LESS/SCSS",
  "DESCRIPTION_JS_HINTS": "Ενεργοποίηση/απενεργοποίηση υποδείξεων κώδικα JavaScript",
  "DESCRIPTION_JS_HINTS_TYPE_DETAILS": "Ενεργοποίηση/απενεργοποίηση λεπτομερειών τύπου δεδομένων στις υποδείξεις κώδικα JavaScript",
  "DESCRIPTION_PREF_HINTS": "Ενεργοποίηση/απενεργοποίηση συμβουλών κώδικα προτιμήσεων",
  "DESCRIPTION_SPECIAL_CHAR_HINTS": "Ενεργοποίηση/απενεργοποίηση υποδείξεων οντοτήτων HTML",
  "DESCRIPTION_SVG_HINTS": "Ενεργοποίηση/απενεργοποίηση υποδείξεων κώδικα SVG",
  "DESCRIPTION_HTML_TAG_HINTS": "Ενεργοποίηση/απενεργοποίηση υποδείξεων ετικετών HTML",
  "DESCRIPTION_URL_CODE_HINTS": "Ενεργοποίηση/απενεργοποίηση υποδείξεων URL σε HTML & CSS/LESS/SCSS",
  "DESCRIPTION_DRAG_DROP_TEXT": "Ενεργοποίηση/απενεργοποίηση της λειτουργίας μεταφοράς & απόθεσης",
  "DESCRIPTION_HEALTH_DATA_TRACKING": "Ενεργοποίηση της παρακολούθησης δεδομένων υγείας",
  "DESCRIPTION_HIGHLIGHT_MATCHES": "Επιτρέπει την αυτόματη επισήμανση συμβολοσειρών που ταιριάζουν σε όλο το έγγραφο",
  "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN": "Επισημάνετε όλες τις συμβολοσειρές που ταιριάζουν με το διακριτικό στο οποίο βρίσκεται ο δρομέας (δεν απαιτείται επιλογή)",
  "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY": "Επισήμανση μόνο όταν η επιλογή είναι ένα πλήρες token",
  "DESCRIPTION_INSERT_HINT_ON_TAB": "true για την εισαγωγή της τρέχουσας επιλεγμένης υπόδειξης κώδικα στην καρτέλα",
  "DESCRIPTION_NO_HINTS_ON_DOT": "αληθές για να μην εμφανίζονται αυτόματα JS συμβουλές κώδικα όταν. πληκτρολογείται",
  "DESCRIPTION_JSHINT_OPTIONS": "Ένα αντικείμενο με τις προεπιλεγμένες επιλογές για το JShint. Ανατρέξτε στην ακόλουθη διεύθυνση URL για όλες τις διαθέσιμες επιλογές JShint: https://jshint.com/docs/options/",
  "DESCRIPTION_LANGUAGE": "Ρυθμίσεις για τη συγκεκριμένη γλώσσα",
  "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS": "Πρόσθετες αντιστοιχίσεις από την επέκταση αρχείου στο όνομα γλώσσας",
  "DESCRIPTION_LANGUAGE_FILE_NAMES": "Πρόσθετες αντιστοιχίσεις από όνομα αρχείου σε όνομα γλώσσας",
  "DESCRIPTION_LINEWISE_COPY_CUT": "Κάνοντας αντιγραφή και αποκοπή όταν δεν υπάρχει επιλογή θα αντιγράψει ή θα αποκόψει ολόκληρες γραμμές που έχουν δρομείς σε αυτές",
  "DESCRIPTION_INPUT_STYLE": "Επιλέγει τον τρόπο χειρισμού της εισόδου και της εστίασης. Μπορεί να είναι textarea, η οποία είναι η προεπιλογή, ή contenteditable το οποίο είναι καλύτερο για προγράμματα ανάγνωσης οθόνης (ασταθής)",
  "DESCRIPTION_LINTING_ENABLED": "αληθές για να ενεργοποιήσετε την Επιθεώρηση Κώδικα",
  "DESCRIPTION_ASYNC_TIMEOUT": "Ο χρόνος σε χιλιοστά του δευτερολέπτου μετά τον οποίο το χρονικό διάστημα ασύγχρονων linters",
  "DESCRIPTION_LINTING_PREFER": "Συστοιχία από χνούδες που θα τρέξουν πρώτα",
  "DESCRIPTION_LIVE_DEV_MULTIBROWSER": "true για να ενεργοποιήσετε την πειραματική ζωντανή προεπισκόπηση",
  "DESCRIPTION_USE_PREFERED_ONLY": "ισχύει για την εκτέλεση υπηρεσιών παροχής που καθορίζονται στο linting.parm; only",
  "DESCRIPTION_MAX_CODE_HINTS": "Μέγιστες συμβουλές κώδικα που εμφανίζονται ταυτόχρονα",
  "DESCRIPTION_PATH": "Ρυθμίσεις για συγκεκριμένες διαδρομές",
  "DESCRIPTION_PROXY": "Η διεύθυνση URL του διακομιστή μεσολάβησης που χρησιμοποιείται για την εγκατάσταση επεκτάσεων",
  "DESCRIPTION_SCROLL_PAST_END": "true για να ενεργοποιήσετε την κύλιση πέρα από το τέλος του εγγράφου",
  "DESCRIPTION_SHOW_CODE_HINTS": "false για να απενεργοποιήσετε όλες τις υποδείξεις κώδικα",
  "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING": "Διατηρεί ορατό το δρομέα που αναβοσβήνει όταν έχετε επιλογή κειμένου",
  "DESCRIPTION_SHOW_LINE_NUMBERS": "αληθές για να εμφανίσετε αριθμούς γραμμών σε μια «υδρορροή» στα αριστερά του κώδικα",
  "DESCRIPTION_SMART_INDENT": "Αυτόματη εσοχή κατά τη δημιουργία νέου μπλοκ",
  "DESCRIPTION_SOFT_TABS": "false για να απενεργοποιήσετε τη συμπεριφορά soft tab",
  "DESCRIPTION_SORT_DIRECTORIES_FIRST": "ισχύει για την ταξινόμηση των καταλόγων πρώτα στο δέντρο του έργου",
  "DESCRIPTION_SPACE_UNITS": "Αριθμός κενών που θα χρησιμοποιηθούν για εσοχές βάσει διαστήματος",
  "DESCRIPTION_STATIC_SERVER_PORT": "Αριθμός θύρας που πρέπει να χρησιμοποιήσει ο ενσωματωμένος διακομιστής για την προεπισκόπηση Live",
  "DESCRIPTION_STYLE_ACTIVE_LINE": "αληθές για να επισημάνετε το χρώμα φόντου της γραμμής στην οποία βρίσκεται ο δρομέας",
  "DESCRIPTION_TAB_SIZE": "Αριθμός κενών που θα εμφανίζονται για τις καρτέλες",
  "DESCRIPTION_USE_TAB_CHAR": "ισχύει για χρήση στηλοθετών αντί για κενά",
  "DESCRIPTION_UPPERCASE_COLORS": "ισχύει για τη δημιουργία δεκαεξαδικών χρωμάτων με κεφαλαία στον επεξεργαστή χρωμάτων Inline",
  "DESCRIPTION_WORD_WRAP": "Αναδίπλωση γραμμών που υπερβαίνουν το πλάτος της οπτικής γωνίας",
  "DESCRIPTION_SEARCH_AUTOHIDE": "Κλείσιμο της αναζήτησης μόλις εστιαστεί ο επεξεργαστής",
  "DESCRIPTION_DETECTED_EXCLUSIONS": "Μια λίστα αρχείων που εντοπίστηκαν ώστε το Tern να εξαντλείται από τον έλεγχο",
  "DESCRIPTION_INFERENCE_TIMEOUT": "Ο χρόνος μετά τον οποίο ο Tern θα τελειώσει το χρονικό όριο όταν προσπαθεί να κατανοήσει τα αρχεία",
  "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR": "αληθές για την εμφάνιση σφαλμάτων στη γραμμή κατάστασης",
  "DESCRIPTION_QUICK_VIEW_ENABLED": "true για να ενεργοποιήσετε τη Γρήγορη προβολή",
  "DESCRIPTION_SELECTION_VIEW_ENABLED": "true για ενεργοποίηση της προβολής επιλογής",
  "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW": "αληθές για την εμφάνιση προεπισκοπήσεων εικόνων για διευθύνσεις URL που λείπουν επεκτάσεις",
  "DESCRIPTION_THEME": "Επιλέξτε ένα θέμα {AP_NAME}",
  "DESCRIPTION_USE_THEME_SCROLLBARS": "true για να επιτρέψετε προσαρμοσμένες γραμμές κύλισης",
  "DESCRIPTION_LINTING_COLLAPSED": "αληθές για τη σύμπτυξη του πίνακα επένδυσης",
  "DESCRIPTION_FONT_FAMILY": "Αλλαγή οικογένειας γραμματοσειρών",
  "DESCRIPTION_FONT_SIZE": "Αλλαγή μεγέθους γραμματοσειράς, π.χ. 13px",
  "DESCRIPTION_FIND_IN_FILES_NODE": "true για να ενεργοποιήσετε την αναζήτηση βάσει κόμβου",
  "DESCRIPTION_FIND_IN_FILES_INSTANT": "true για να ενεργοποιήσετε την άμεση αναζήτηση",
  "DESCRIPTION_FONT_SMOOTHING": "Μόνο Mac: «εξομάλυνση υποpixel» για ενεργοποίηση εξομάλυνσης ή εξομάλυνσης υποεικονοστοιχείων για εξομάλυνση κλίμακας του γκρι",
  "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW": "false για να απενεργοποιήσετε το αρχείο προτιμήσεων ανοίγματος σε διαχωρισμένη προβολή",
  "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE": "false για να ανοίξετε το αρχείο προτιμήσεων χρήστη στο αριστερό/επάνω τμήμα",
  "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED": "ισχύει για σύμπτυξη παραθύρων μετά το κλείσιμο του τελευταίου αρχείου από το παράθυρο μέσω κουμπιού κλεισίματος κεφαλίδας παραθύρου",
  "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS": "Εναλλαγή του πότε θα εμφανίζονται τα κουμπιά κλεισίματος και flip-view στην κεφαλίδα.",
  "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT": "/*\n * Αυτό είναι ένα αρχείο μόνο για ανάγνωση με τις προτιμήσεις που υποστηρίζονται\n * από {ΟΝΟΜΑ APP_}.\n * Χρησιμοποιήστε αυτό το αρχείο ως αναφορά για να τροποποιήσετε τις προτιμήσεις σας\n * αρχείο «brackets.json» άνοιξε στο άλλο παράθυρο.\n * Για περισσότερες πληροφορίες σχετικά με τον τρόπο χρήσης των προτιμήσεων στο\n * {AP_NAME}, ανατρέξτε στην ιστοσελίδα στη διεύθυνση https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences\n */",
  "DEFAULT_PREFERENCES_JSON_DEFAULT": "Προκαθορισμένο",
  "DESCRIPTION_PURE_CODING_SURFACE": "true για να ενεργοποιήσετε τη λειτουργία μόνο κώδικα και να αποκρύψετε όλα τα άλλα στοιχεία περιβάλλοντος εργασίας χρήστη στο {AP_NAME}",
  "DESCRIPTION_INDENT_LINE_COMMENT": "true για να ενεργοποιήσετε την εσοχή σχολίων γραμμής",
  "DESCRIPTION_RECENT_FILES_NAV": "Ενεργοποίηση/απενεργοποίηση πλοήγησης σε πρόσφατα αρχεία",
  "DESCRIPTION_LIVEDEV_WEBSOCKET_PORT": "Θύρα στην οποία εκτελείται WebSocket Server για προεπισκόπηση Live",
  "DESCRIPTION_LIVE_DEV_HIGHLIGHT_SETTINGS": "Ρυθμίσεις επισήμανσης προεπισκόπησης Live",
  "DESCRIPTION_LIVEDEV_ENABLE_REVERSE_INSPECT": "false για να απενεργοποιήσετε ζωντανή προεπισκόπηση αντίστροφη επιθεώρηση",
  "DOWNLOAD_FAILED": "Η λήψη απέτυχε.",
  "DOWNLOAD_COMPLETE": "Η λήψη ολοκληρώθηκε!",
  "UPDATE_SUCCESSFUL": "Επιτυχής ενημέρωση!",
  "UPDATE_FAILED": "Η ενημέρωση απέτυχε!",
  "VALIDATION_FAILED": "Αποτυχία επικύρωσης!",
  "INITIALISATION_FAILED": "Αποτυχία προετοιμασίας!",
  "CLEANUP_FAILED": "Απέτυχε ο καθαρισμός!",
  "WARNING_TYPE": "Προειδοποίηση!",
  "CLICK_RESTART_TO_UPDATE": "Κάντε κλικ στο κουμπί Επανεκκίνηση για να ενημερώσετε τα στηρίγματα",
  "UPDATE_ON_NEXT_LAUNCH": "Η ενημερωμένη έκδοση θα εφαρμοστεί κατά την επανεκκίνηση.",
  "GO_TO_SITE": "Μεταβείτε στο <a href = \"http://brackets.io/ «> brackets.io </a> για να προσπαθήσετε ξανά.",
  "INTERNET_UNAVAILABLE": "Δεν υπάρχει διαθέσιμη σύνδεση στο διαδίκτυο.",
  "UPDATEDIR_READ_FAILED": "Δεν ήταν δυνατή η ανάγνωση του καταλόγου ενημέρωσης.",
  "UPDATEDIR_CLEAN_FAILED": "Δεν ήταν δυνατό να καθαριστεί ο κατάλογος ενημέρωσης.",
  "INITIAL_DOWNLOAD": "Λήψη ενημερωμένης έκδοσης...",
  "RETRY_DOWNLOAD": "Η λήψη απέτυχε. Επανάληψη... Απόπειρα ",
  "VALIDATING_INSTALLER": "Η λήψη ολοκληρώθηκε! Επικύρωση προγράμματος εγκατάστασης...",
  "CHECKSUM_DID_NOT_MATCH": "Το άθροισμα ελέγχου δεν ταίριαζε.",
  "INSTALLER_NOT_FOUND": "Ο εγκαταστάτης δεν βρέθηκε.",
  "DOWNLOAD_ERROR": "Παρουσιάστηκε σφάλμα κατά τη λήψη.",
  "NETWORK_SLOW_OR_DISCONNECTED": "Το δίκτυο έχει αποσυνδεθεί ή είναι πολύ αργό.",
  "RESTART_BUTTON": "Επανεκκίνηση",
  "LATER_BUTTON": "Αργότερα",
  "DESCRIPTION_AUTO_UPDATE": "Ενεργοποίηση/απενεργοποίηση αυτόματης ενημέρωσης βραχιόνων",
  "AUTOUPDATE_ERROR": "Σφάλμα!",
  "AUTOUPDATE_IN_PROGRESS": "Μια ενημέρωση βρίσκεται ήδη σε εξέλιξη.",
  "NUMBER_WITH_PERCENTAGE": "{0}%",
  "CMD_FIND_RELATED_FILES": "Εύρεση σχετικών αρχείων",
  "PHP_VERSION_INVALID": "Σφάλμα κατά την ανάλυση της έκδοσης PHP. Παρακαλώ ελέγξτε την έξοδο της εντολής «php —version».",
  "PHP_UNSUPPORTED_VERSION": "Εγκαταστήστε το χρόνο εκτέλεσης PHP7 για την ενεργοποίηση εργαλείων που σχετίζονται με το PHP, όπως συμβουλές κώδικα, υποδείξεις παραμέτρων, Jump to Definition και πολλά άλλα. Έκδοση που βρέθηκε: {0}",
  "PHP_EXECUTABLE_NOT_FOUND": "Δεν βρέθηκε χρόνος εκτέλεσης PHP. Εγκαταστήστε το χρόνο εκτέλεσης PHP7 και ενημερώστε κατάλληλα το «ExecutablePath» στις προτιμήσεις PHP. Αυτό επιτρέπει εργαλεία που σχετίζονται με το PHP, όπως συμβουλές κώδικα, υποδείξεις παραμέτρων, Jump to Definition και πολλά άλλα.",
  "PHP_PROCESS_SPAWN_ERROR": "Παρουσιάστηκε κωδικός σφάλματος {0} κατά την εκκίνηση της διαδικασίας PHP.",
  "PHP_SERVER_ERROR_TITLE": "Σφάλμα",
  "PHP_SERVER_MEMORY_LIMIT_INVALID": "Το όριο μνήμης που δώσατε δεν είναι έγκυρο. Ελέγξτε τις προτιμήσεις PHP για να ορίσετε τη σωστή τιμή.",
  "DESCRIPTION_PHP_TOOLING_CONFIGURATION": "Προεπιλεγμένες ρυθμίσεις παραμέτρων PHP Tooling",
  "OPEN_PREFERENNCES": "Άνοιγμα Προτιμήσεων",
  "LANGUAGE_TOOLS_PREFERENCES": "Προτιμήσεις για τα εργαλεία γλώσσας",
  "FIND_ALL_REFERENCES": "Εύρεση όλων των αναφορών",
  "REFERENCES_IN_FILES": "αναφορές",
  "REFERENCE_IN_FILES": "αναφορά",
  "REFERENCES_NO_RESULTS": "Δεν υπάρχουν διαθέσιμες αναφορές για την τρέχουσα θέση του δρομέα",
  "CMD_FIND_DOCUMENT_SYMBOLS": "Εύρεση συμβόλων εγγράφου",
  "CMD_FIND_PROJECT_SYMBOLS": "Εύρεση συμβόλων έργου",
  "REMOTE_DEBUGGING_ENABLED": "Ενεργοποίηση απομακρυσμένου εντοπισμού σφαλμάτων στο localhost:",
  "REMOTE_DEBUGGING_PORT_INVALID": "Δεν είναι δυνατή η ενεργοποίηση απομακρυσμένου εντοπισμού σφαλμάτων στη θύρα {0}. Οι αριθμοί θύρας πρέπει να είναι μεταξύ {1} και {2}.",
  "DESCRIPTION_EXTERNAL_APPLICATION_ASSOCIATE": "Αντιστοιχίσεις για επέκταση αρχείου σε εξωτερικές εφαρμογές. Σύνταξη: \"<file_type>«: «<Default|ApplicationName|ApplicationPath>», Χρησιμοποιήστε το «default» για να ανοίξετε αρχεία στην προεπιλεγμένη εφαρμογή συστήματος για τον τύπο αρχείου.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_TITLE": "Ανοίξτε τα αρχεία γραφικών σε εξωτερικούς επεξεργαστές.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_MSG": "Ο τρέχων φάκελός σας έχει τύπους αρχείων γραφικών που δεν υποστηρίζονται από το {AP_NAME}. <br/>Τώραμπορείτε να συσχετίσετε συγκεκριμένους τύπους αρχείων με εξωτερικούς επεξεργαστές. Αφού συσχετιστούν, μπορείτε να ανοίξετε αρχεία γραφικών όπως .xd, .psd, .jpg, .png, .ai, .svg στις προεπιλεγμένες εφαρμογές τους κάνοντας διπλό κλικ στα αρχεία στο δέντρο αρχείων. <br/><br/>Κάντεκλικ στο κουμπί «Ok» για να συσχετίσετε τους τύπους αρχείων γραφικών με τις αντίστοιχες προεπιλεγμένες εφαρμογές τους.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_CNF_MSG": "Οι παρακάτω τύποι αρχείων έχουν συσχετιστεί με επιτυχία με τις προεπιλεγμένες εφαρμογές. <br/>{0} Έχετε την επιλογή να αλλάξετε την προτίμησή σας για το αν διαγράφετε/προσθέτετε νέες συσχετίσεις τύπων αρχείων στο brackets.json πηγαίνοντας στο μενού «Debug->Άνοιγμα Προτιμήσεων αρχείου».",
  "UNSUPPORTED_BROWSER": "Ο περιηγητής δεν υποστηρίζεται",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER": "Το πρόγραμμα περιήγησης δεν υποστηρίζει Άνοιγμα φακέλου",
  "UNSUPPORTED_BROWSER_MESSAGE_LINE1": "Χρησιμοποιήστε ένα από τα υποστηριζόμενα προγράμματα περιήγησης παρακάτω.",
  "UNSUPPORTED_BROWSER_MESSAGE_LINE2": " Εργαζόμαστε σκληρά για να καταστήσουμε το Phoenix διαθέσιμο σε περισσότερα προγράμματα περιήγησης. Μπορείτε να κλείσετε αυτό το παράθυρο διαλόγου, αλλά ορισμένες δυνατότητες στο Phoenix δεν θα λειτουργούν σε αυτό το πρόγραμμα περιήγησης.",
  "CANNOT_PUBLISH_LARGE_PROJECT": "Δεν είναι δυνατή η δημοσίευση μεγάλου έργου",
  "CANNOT_PUBLISH_LARGE_PROJECT_MESSAGE": "Ο Φοίνιξ είναι ακόμα σε πειραματικό άλφα. Δεν έχουμε ενεργοποιήσει ακόμα το συγχρονισμό έργων με περισσότερα από 500 αρχεία.",
  "SHARE_WEBSITE": "Να δημοσιεύσετε και να μοιραστείτε την ιστοσελίδα;",
  "PUBLISH": "Δημοσίευση",
  "PUBLISH_CONSENT_MESSAGE": "Κάντε γρήγορα προεπισκόπηση των αλλαγών και μοιραστείτε τον ιστότοπό σας με άλλους. Η Phoenix μπορεί να δημοσιεύσει αυτή την ιστοσελίδα για εσάς στο {0}. Οι δημοσιευμένοι σύνδεσμοι θα ισχύουν για περίοδο 7 ημερών. </br>Θέλετενα δημοσιεύσετε και να μοιραστείτε την ιστοσελίδα σας;",
  "PUBLISH_SYNC_IN_PROGRESS": "Συγχρονισμός σε εξέλιξη για προεπισκόπηση...",
  "PUBLISH_PAGE": "Κάντε κλικ για να δημοσιεύσετε και να μοιραστείτε αυτό το site",
  "PUBLISH_VIEW_PAGE": "Κάντε κλικ για να δείτε τη δημοσιευμένη σελίδα",
  "MISSING_FIELDS": "Πεδία που λείπουν",
  "PLEASE_FILL_ALL_REQUIRED": "Παρακαλώ συμπληρώστε όλα τα απαιτούμενα πεδία που επισημαίνονται με κόκκινο χρώμα",
  "CODE_EDITOR": "Επεξεργαστής κώδικα",
  "BUILD_THE_WEB": "Χτίστε τον ιστό",
  "IMPORT_PROJECT": "Εισαγωγή Έργου",
  "GITHUB_PROJECT": "Πρόγραμμα Github",
  "NEW_PROJECT_FROM_GITHUB": "Νέο Έργο από το Github",
  "GITHUB_REPO_URL": "Διεύθυνση URL Repo του Github:",
  "CREATE_PROJECT": "Δημιουργία Έργου",
  "SETTING_UP_PROJECT": "Ρύθμιση του έργου",
  "LOCATION": "Τοποθεσία:",
  "DOWNLOADING": "Λήψη...",
  "EXTRACTING_FILES_PROGRESS": "Εξαγωγή {0} αρχείων {1}.",
  "DOWNLOAD_FAILED_MESSAGE": "Βεβαιωθείτε ότι η διεύθυνση URL λήψης είναι έγκυρη. </br>Σημείωση: Καθώς το Phoenix είναι σε alpha, τα ιδιωτικά Repos και Github URL μεγαλύτερα από 25 MB δεν επιτρέπονται.",
  "PLEASE_SELECT_A_FOLDER": "Παρακαλώ επιλέξτε ένα φάκελο...",
  "UNZIP_IN_PROGRESS": "Αποσυμπιέζοντας αρχεία...",
  "UNZIP_FAILED": "Σφάλμα: Αποτυχία αποζιδάλωσης.",
  "CONFIRM_REPLACE_TITLE": "Επιβεβαίωση αντικατάστασης",
  "KEEP_BOTH": "Κρατήστε και τα δύο",
  "EXPLORE": "Παιχνίδια HTML",
  "BLOG": "Blog",
  "PHOENIX_DEFAULT_PROJECT": "Προεπιλεγμένο έργο",
  "PROJECT_NAME": "Όνομα έργου:",
  "NEW_HTML": "Νέο έργο HTML",
  "LICENSE": "Άδεια χρήσης:",
  "CREDITS": "Πιστώσεις:",
  "PREVIEW": "Προεπισκόπηση",
  "BUILD_WEBSITE": "Κατασκευή Ιστοσελίδας",
  "VIEW_MORE": "Δείτε περισσότερα...",
  "NEW_PROJECT_NOTIFICATION": "Κάντε κλικ σε αυτό το εικονίδιο για να<br/>δημιουργήσετε ένα νέο έργο. </br> <a href='#' style='float:right;'>οκ</a>",
  "DEFAULT_PROJECT_NOTIFICATION": "Κάντε κλικ εδώ για να ανοίξετε το <br/><b>προεπιλεγμένο έργο</b> στο Phoenix. </br> <a href='#' style='float:right;'>οκ</a>",
  "DIRECTORY_REPLACE_MESSAGE": "Ο επιλεγμένος φάκελος <span class='dialog-filename'>{0}</span> δεν είναι κενός. Είστε βέβαιοι ότι θέλετε να αντικαταστήσετε τα περιεχόμενα του φακέλου με το έργο;",
  "BUILD_WEBSITE_SECTION": "Κατασκευή Ιστοσελίδας",
  "LEARN_SECTION": "Μάθετε με παραδείγματα",
  "WEBPAGE_HOME_PAGE": "Διατάξεις αρχικής σελίδας",
  "WEBPAGE_BLOG": "Σελίδα ιστολογίου",
  "WEBPAGE_DASHBOARD": "Πίνακας εργαλείων HTML",
  "WEBPAGE_BOOTSTRAP_EXAMPLES": "Παραδείγματα Bootstrap",
  "GUIDED_FILES_SIDEBAR": "Επιλέξτε ένα αρχείο HTML </br> <a href='#' style='float:right;'>ok</a>",
  "GUIDED_LIVE_PREVIEW": "Κάντε μερικές αλλαγές κώδικα και αποθηκεύστε το αρχείο για να δείτε την προεπισκόπηση. </br> <a href='#' style='float:right;'>οκ</a>",
  "GUIDED_LIVE_PREVIEW_POPOUT": "Κάντε κλικ σε αυτό το κουμπί για να αναδυθεί η ζωντανή προεπισκόπηση σε μια νέα καρτέλα. </br> <a href='#' style='float:right;'>οκ</a>",
  "TEST_TRANSLATE": "χρησιμοποιήστε αυτό για να ελέγξετε μεταφράσεις",
  "BEAUTIFY_ERROR": "Αδύνατη η ομορφιά του κώδικα. Ελέγξτε τη σύνταξη.",
  "BEAUTIFY_PROJECT_BUSY_MESSAGE": "Ομορφοποίηση αρχείου {0}",
  "BEAUTIFY_ERROR_SELECTION": "Δεν μπορούσε να ομορφύνει. </br>Τοεπιλεγμένο μπλοκ κώδικα είναι ελλιπής ή μη έγκυρη σύνταξη.",
  "BEAUTIFY_OPTIONS": "Επιλογές που ελέγχουν πώς λειτουργεί ο Beautify Code",
  "BEAUTIFY_OPTION_PRINT_WIDTH": "Καθορίστε το μήκος γραμμής στο οποίο θα αναδιπλωθεί ο εξωραϊστής",
  "BEAUTIFY_OPTION_SEMICOLON": "Προσθήκη ερωτηματικού στο τέλος κάθε πρότασης",
  "BEAUTIFY_OPTION_SINGLE_QUOTE": "Χρήση μονών εισαγωγικών αντί για διπλά εισαγωγικά",
  "BEAUTIFY_OPTION_QUOTE_PROPS": "Αλλαγή όταν παρατίθενται ιδιότητες σε αντικείμενα",
  "BEAUTIFY_OPTION_BRACKET_SAME_LINE": "Τοποθετήστε το > ενός στοιχείου HTML (HTML, JSX, Vue, Angular) στο τέλος της τελευταίας γραμμής αντί να είστε μόνοι στην επόμενη γραμμή (δεν ισχύει για στοιχεία αυτόματου κλεισίματος)",
  "BEAUTIFY_OPTION_SINGLE_ATTRIBUTE_PER_LINE": "Επιβολή μεμονωμένου χαρακτηριστικού ανά γραμμή σε HTML, Vue και JSX",
  "BEAUTIFY_OPTION_PROSE_WRAP": "Αναδίπλωση πεζογραφίας αν υπερβαίνει το πλάτος εκτύπωσης σε αρχεία markdown",
  "BEAUTIFY_OPTION_PRINT_TRAILING_COMMAS": "Εκτύπωση τελικών κομμών όπου είναι δυνατόν σε συντακτικές δομές διαχωρισμένες με κόμματα πολλών γραμμών"
});