/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "Järjestelmän oletus",
  "PROJECT_BUSY": "Projektitoiminta käynnissä",
  "DUPLICATING": "Kopioidaan {0}",
  "MOVING": "Siirretään {0}",
  "COPYING": "Kopioidaan {0}",
  "DELETING": "Poistetaan {0}",
  "DELETE_TO_TRASH": "Siirretään {0} roskakoriin",
  "DELETE_TO_RECYCLE_BIN": "Siirretään {0} roskakoriin",
  "RENAMING": "Nimetään uudelleen",
  "STORED_IN_YOUR_BROWSER": "Tallennettu selaimeesi",
  "SUPPORT_US_OPEN_COLLECTIVE": "Tue meitä GitHub-sponsoreissa",
  "GENERIC_ERROR": "(virhe {0})",
  "NOT_FOUND_ERR": "Tiedostoa tai hakemistoa ei löytynyt.",
  "NOT_READABLE_ERR": "Tiedostoa tai hakemistoa ei voitu lukea.",
  "EXCEEDS_MAX_FILE_SIZE": "Yli {0} Mt:n tiedostoja ei voi avata {APP_NAME}issa.",
  "NO_MODIFICATION_ALLOWED_ERR": "Kohdehakemistoa ei voi muuttaa.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "Sinulla ei ole oikeuksia tehdä muutoksia.",
  "CONTENTS_MODIFIED_ERR": "Tiedostoa on muokattu {APP_NAME}in ulkopuolella.",
  "UNSUPPORTED_ENCODING_ERR": "Tuntematon enkoodausmuoto",
  "ENCODE_FILE_FAILED_ERR": "{APP_NAME} ei voinut enkoodata tämän tiedoston sisältöä.",
  "DECODE_FILE_FAILED_ERR": "{APP_NAME} ei voinut dekoodata tämän tiedoston sisältöä.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "{APP_NAME} ei tällä hetkellä tue UTF-16-koodattuja tiedostoja.",
  "FILE_EXISTS_ERR": "Tiedosto tai hakemisto on jo olemassa.",
  "FILE": "tiedostossa",
  "FILE_TITLE": "Tiedosto",
  "DIRECTORY": "hakemisto",
  "DIRECTORY_TITLE": "hakemisto",
  "DIRECTORY_NAMES_LEDE": "Hakemistojen nimet",
  "FILENAMES_LEDE": "Tiedostonimet",
  "FILENAME": "tiedostonimi",
  "DIRECTORY_NAME": "hakemiston nimi",
  "ERROR_LOADING_PROJECT": "Virhe projektia ladattaessa",
  "OPEN_DIALOG_ERROR": "Tapahtui virhe avattaessa tiedostonvalintaikkunaa. (Virhe {0}.)",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "Tapahtui virhe yritettäessä avata hakemistoa <span class='dialog-filename'>{0}</span>. (Virhe {1}.)",
  "READ_DIRECTORY_ENTRIES_ERROR": "Tapahtui virhe luettaessa hakemiston <span class='dialog-filename'>{0}</span> sisältöä. (Virhe {1}.)",
  "ZOOM_WITH_SHORTCUTS": "Käytä pikanäppäimiä zoomaamiseen",
  "ZOOM_WITH_SHORTCUTS_DETAILS": "Käytä pikanäppäimiä <code><i>{0}</i></code> lähentääksesi ja <code><i>{1}</i></code> loitontaaksesi.",
  "ERROR_OPENING_FILE_TITLE": "Virhe tiedostoa avattaessa",
  "ERROR_OPENING_FILE": "Tapahtui virhe yritettäessä avata tiedostoa <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_OPENING_FILES": "Tapahtui virhe yritettäessä avata seuraavia tiedostoja:",
  "ERROR_RELOADING_FILE_TITLE": "Virhe päivitettäessä muutoksia levyltä",
  "ERROR_RELOADING_FILE": "Tapahtui virhe yritettäessä päivittää tiedostoa <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_SAVING_FILE_TITLE": "Virhe tallennettaessa tiedostoa",
  "ERROR_SAVING_FILE": "Tapahtui virhe yritettäessä tallentaa tiedostoa <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_FILE_TITLE": "Virhe nimettäessä {0}a uudelleen",
  "ERROR_RENAMING_FILE": "Tapahtui virhe yritettäessä nimetä uudelleen {2}a <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "Tiedosto tai hakemisto ei kuulu avoinna olevaan projektiin. Valitettavasti vain projektin tiedostoja voi nimetä uudelleen tällä hetkellä.",
  "ERROR_MOVING_FILE_TITLE": "Virhe siirrettäessä kohdetta {0}",
  "ERROR_MOVING_FILE": "Virhe yritettäessä siirtää kohdetta {2} <span class='dialog-filename'>{0}</span> . {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "Tiedostoa/kansiota ei voi siirtää, koska ne eivät ole osa nykyistä projektia.",
  "ERROR_DELETING_FILE_TITLE": "Virhe poistettaessa {0}a",
  "ERROR_DELETING_FILE": "Tapahtui virhe yritettäessä poistaa {2}a <span class='dialog-filename'>{0}</span>. {1}",
  "INVALID_FILENAME_TITLE": "Virheellinen {0}",
  "CANNOT_PASTE_TITLE": "Ei voi liittää {0}",
  "CANNOT_DOWNLOAD_TITLE": "Ei voi ladata {0}",
  "ERR_TYPE_DOWNLOAD_FAILED": "Virhe ladattaessa tiedostoa <span class='dialog-filename'>{0}</span>",
  "ERR_TYPE_PASTE_FAILED": "Tapahtui virhe liitettäessä kohdetta <span class='dialog-filename'>{0}</span> kohteeseen <span class='dialog-filename'>{1}</span>",
  "CANNOT_DUPLICATE_TITLE": "Ei voi kopioida",
  "ERR_TYPE_DUPLICATE_FAILED": "Tapahtui virhe kopioitaessa tiedostoa <span class='dialog-filename'>{0}</span>",
  "ERR_TYPE_DUPLICATE_FAILED_NO_FILE": "Valitse kopioitava tiedosto.",
  "INVALID_FILENAME_MESSAGE": "{0} ei voi käyttää mitään järjestelmän varaamia sanoja, päättyä pisteeseen (.) tai käyttää mitään seuraavista merkeistä: <code class='emphasized'>{1}</code>",
  "ENTRY_WITH_SAME_NAME_EXISTS": "Tiedosto tai hakemisto nimellä <span class='dialog-filename'>{0}</span> on jo olemassa.",
  "ERROR_CREATING_FILE_TITLE": "Virhe luotaessa {0}a",
  "ERROR_CREATING_FILE": "Virhe yritettäessä luoda {0}a <span class='dialog-filename'>{1}</span>. {2}",
  "ERROR_MIXED_DRAGDROP": "Kansiota ei voi avata samaan aikaan muiden tiedostojen kanssa.",
  "ERROR_KEYMAP_TITLE": "Virhe käyttäjän näppäinkarttaa luettaessa",
  "ERROR_KEYMAP_CORRUPT": "Näppäinkarttatiedostossasi on virheellistä JSON-koodia. Tiedosto aukeaa, niin voit korjata sen muodon.",
  "ERROR_LOADING_KEYMAP": "Näppäinkarttatiedostosi ei ole UTF-8-koodattu tai tekstimuotoinen, joten sitä ei voi ladata.",
  "ERROR_RESTRICTED_COMMANDS": "Seuraavien komentojen näppäinyhdistelmiä ei voi määrittää uudelleen: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "Seuraavia näppäinyhdistelmiä ei voi määrittää uudelleen: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "Olet määrittämässä seuraaville komennoille useita näppäinyhdistelmiä: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "Seuraaviin näppäinyhdistelmiin on useita liitoksia: {0}",
  "ERROR_INVALID_SHORTCUTS": "Seuraavat näppäinyhdistelmät ovat virheellisiä: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "Olet määrittämässä näppäinyhdistelmiä olemattomille komennoille: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "Virhe asetuksia luettaessa",
  "ERROR_PREFS_PROJECT_LINT": "Projektiasetukset",
  "ERROR_PREFS_PROJECT_LINT_MESSAGE": "Virhe: Projekti sisältää sekä .brackets.json- että .phcode.json-tiedostot, mikä aiheuttaa ristiriidan. Poista joko \".brackets.json\" tai \".phcode.json\" ja lataa sitten projekti uudelleen.",
  "ERROR_PREFS_CORRUPT": "Asetustiedostossa on virheellistä JSON-koodia. Tiedosto avataan, niin voit korjata sen muodon. {APP_NAME} tulee käynnistää uudelleen, jotta muutokset tulevat voimaan.",
  "ERROR_PROJ_PREFS_CORRUPT": "Projektin asetustiedostossa on virheellistä JSON-koodia. Tiedosto avataan, niin voit korjata sen muodon. Projekti tulee ladata uudelleen, jotta muutokset tulevat voimaan.",
  "ERROR_IN_BROWSER_TITLE": "Hups! {APP_NAME} ei toimi vielä selaimessa.",
  "ERROR_IN_BROWSER": "{APP_NAME} on tehty HTML:llä, mutta juuri nyt se toimii työpöytäsovelluksena, joten voit muokata sillä paikallisia tiedostoja. Käytä ohjelmistolähteen <b>github.com/adobe/brackets-shell</b> sovellusliittymää, niin voit suorittaa {APP_NAME}in.",
  "ERROR_MAX_FILES_TITLE": "Virhe tiedostojen indeksoinnissa",
  "ERROR_MAX_FILES": "Tässä projektissa on yli 30&nbsp;000 tiedostoa. Useiden tiedostojen väliset ominaisuudet poistetaan käytöstä, tai ne toimivat niin kuin projekti olisi tyhjä. <a href='https://github.com/adobe/brackets/wiki/Large-Projects'>Lue lisää suurten projektien parissa työskentelystä</a>.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "Virhe selaimen avaamisessa",
  "ERROR_CANT_FIND_CHROME": "Google Chrome ‑selainta ei löytynyt. Varmista, että se on asennettu.",
  "ERROR_LAUNCHING_BROWSER": "Selaimen avaaminen epäonnistui. (Virhe {0}.)",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "Esikatselun virhe",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "Yhdistetään selaimeen",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "Jotta esikatselu voi muodostaa yhteyden, pitää Chromen käynnistyä uudelleen etävirheenjäljitys käytössä.<br /><br />Käynnistetäänkö Chrome uudelleen ja aktivoidaan etävirheenjäljitys?<br /><br />",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "Esikatselun sivua ei voitu ladata.",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "Jotta voit käynnistää esikatselun palvelimen tiedostolla, täytyy tämän projektin URL-osoite määrittää.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "Virhe käynnistettäessä HTTP-palvelinta esikatselun tiedostoille. Yritä uudelleen.",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "Saat lisätietoja tutustumalla ohjeeseen <a href='{0}' title='{0}'>Troubleshooting Live Preview connection errors</a>.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "Esikatselu",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "Esikatselu: yhdistetään…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "Esikatselu: alustetaan…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "Live-esikatselupalvelin aktiivinen",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "Esikatselu",
  "LIVE_DEV_TOOLTIP_SHOW_IN_EDITOR": "{0} - Näytä editorissa…",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "Valitse Tiedosto live-esikatseluun",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "Lataa sivu uudelleen",
  "LIVE_DEV_TOGGLE_LIVE_HIGHLIGHT": "Vaihda live-esikatselun kohokohdat päälle/pois",
  "LIVE_DEV_CLICK_POPOUT": "Avaa live-esikatselu uuteen ikkunaan",
  "LIVE_DEV_OPEN_CHROME": "Avaa Chromessa…",
  "LIVE_DEV_OPEN_SAFARI": "Avaa Safarissa…",
  "LIVE_DEV_OPEN_EDGE": "Avaa Edgessä…",
  "LIVE_DEV_OPEN_FIREFOX": "Avaa Firefoxissa…",
  "LIVE_DEV_OPEN_ERROR_TITLE": "Virhe avattaessa live-esikatselua kohteessa {0}",
  "LIVE_DEV_OPEN_ERROR_MESSAGE": "Varmista, että {0} selain on asennettu ja yritä uudelleen.",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "Kiinnitä tai irrota esikatselusivu",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "Esikatselu (ei päivity syntaksivirheen takia)",
  "LIVE_DEV_SETTINGS": "Live-esikatselun asetukset…",
  "LIVE_DEV_SETTINGS_BANNER": "Määritä mukautettu palvelin PHP:n, JSP:n ja muiden palvelimen tuottamien tiedostojen esikatseluun livenä",
  "LIVE_DEV_SETTINGS_TITLE": "Live-esikatselun asetukset",
  "LIVE_DEV_SETTINGS_STARTUP": "Näytä live-esikatselupaneeli käynnistyksen yhteydessä",
  "LIVE_DEV_SETTINGS_SERVER_PREFERENCE": "tosi mahdollistaa mukautetun kehityspalvelimen",
  "LIVE_DEV_SETTINGS_STARTUP_PREFERENCE": "tosi näyttää Live Preview Panel käynnistyksen yhteydessä",
  "LIVE_DEV_SETTINGS_HOT_RELOAD_PREFERENCE": "tosi, jos palvelin tukee hot-reloadia ja poista Live Preview -uudelleenlataus käytöstä tallennuksen yhteydessä",
  "LIVE_DEV_SETTINGS_USE_SERVER": "Käytä mukautettua kehityspalvelinta tähän projektiin",
  "LIVE_DEV_SETTINGS_SERVE_PREFERENCE": "Kehityspalvelimesi URL-osoite projektille, esim. http://localhost:8000/php",
  "LIVE_DEV_SETTINGS_SERVER_INBUILT": "Esim. http://localhost:8000/php - Tällä hetkellä käytössä sisäänrakennettu palvelin.",
  "LIVE_DEV_SETTINGS_SERVER_ROOT": "Palvelukansio projektissa",
  "LIVE_DEV_SETTINGS_SERVER_ROOT_HELP": "Esim. www/ (oletus on /)",
  "LIVE_DEV_SETTINGS_SERVER_ROOT_PREF": "Polku projektin sisällä, jota palvelee kehityspalvelin esim. www/ (oletus on /)",
  "LIVE_DEV_SETTINGS_RELOAD": "Palvelin tukee kuumaa uudelleenlatausta",
  "LIVE_DEV_SETTINGS_RELOAD_HELP": "Jotkut palvelimet tukevat kuumaa uudelleenlatausta, jossa koodimuutokset työnnetään sivulle ilman koko sivun uudelleenlatausta.\nOta tämä ominaisuus käyttöön, jos et halua, että {APP_NAME} lataa sivua uudelleen jokaisen tallennuksen yhteydessä.",
  "LIVE_DEV_SETTINGS_FRAMEWORK": "Palvelinkehys",
  "LIVE_DEV_SETTINGS_FRAMEWORK_CUSTOM": "Mukautettu",
  "LIVE_DEV_SETTINGS_FRAMEWORK_PREFERENCES": "Server Framework tukee tällä hetkellä vain docusaurusia",
  "LIVE_PREVIEW_CUSTOM_SERVER_BANNER": "Haetaan esikatselua mukautetusta palvelimestasi {0}",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "Esikatselu peruutettiin, koska selaimen kehitystyökalut avattiin",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "Esikatselu peruutettiin, koska sivu suljettiin selaimessa",
  "LIVE_DEV_NAVIGATED_AWAY": "Esikatselu peruutettiin, koska selain siirtyi sivulle, joka ei kuulu nykyiseen projektiin",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "Esikatselu peruutettiin tuntemattomasta syystä ({0})",
  "SAVE_CLOSE_TITLE": "Tallenna muutokset",
  "SAVE_CLOSE_MESSAGE": "Haluatko tallentaa dokumenttiin <span class='dialog-filename'>{0}</span> tehdyt muutokset?",
  "SAVE_CLOSE_MULTI_MESSAGE": "Haluatko tallentaa seuraavien tiedostojen muutokset?",
  "EXT_MODIFIED_TITLE": "Ulkoisia muutoksia",
  "CONFIRM_DELETE_TITLE": "Vahvista poisto",
  "CONFIRM_FILE_DELETE": "Haluatko varmasti poistaa tiedoston <span class='dialog-filename'>{0}</span>?",
  "CONFIRM_FOLDER_DELETE": "Haluatko varmasti poistaa kansion <span class='dialog-filename'>{0}</span>?",
  "CONFIRM_FILE_DELETE_TRASH": "Haluatko varmasti poistaa tiedoston <span class='dialog-filename'>{0}</span> ?<br> Voit palauttaa tämän tiedoston roskakorista.",
  "CONFIRM_FOLDER_DELETE_TRASH": "Haluatko varmasti poistaa kansion <span class='dialog-filename'>{0}</span> ?<br> Voit palauttaa tämän kansion roskakorista.",
  "CONFIRM_FILE_DELETE_RECYCLE_BIN": "Haluatko varmasti poistaa tiedoston <span class='dialog-filename'>{0}</span> ?<br> Voit palauttaa tämän tiedoston roskakorista.",
  "CONFIRM_FOLDER_DELETE_RECYCLE_BIN": "Haluatko varmasti poistaa kansion <span class='dialog-filename'>{0}</span> ?<br> Voit palauttaa tämän kansion roskakorista.",
  "MOVE_TO_TRASH": "Siirtää roskakoriin",
  "MOVE_TO_RECYCLE_BIN": "Siirrä roskakoriin",
  "FILE_DELETED_TITLE": "Poistettu tiedosto",
  "EXT_MODIFIED_WARNING": "<span class='dialog-filename'>{0}</span> on muuttunut levyllä {APP_NAME}in ulkopuolella.<br /><br />Haluatko tallentaa tiedoston ja korvata kyseiset muutokset?",
  "EXT_MODIFIED_MESSAGE": "<span class='dialog-filename'>{0}</span> on muuttunut levyllä {APP_NAME}in ulkopuolella, mutta sillä on tallentamattomia muutoksia myös {APP_NAME}issa.<br /><br />Kumman version haluat säilyttää?",
  "EXT_DELETED_MESSAGE": "<span class='dialog-filename'>{0}</span> on poistettu levyltä {APP_NAME}in ulkopuolella, mutta sillä on tallentamattomia muutoksia {APP_NAME}issa.<br /><br />Haluatko säilyttää muutoksesi?",
  "EXT_ALWAYS_MODIFIED_BUTTON_TOOLTIP": "Korvaa tiedostot aina, kunnes projekti vaihtuu tai käynnistyy uudelleen",
  "WINDOW_UNLOAD_WARNING": "Haluatko varmasti siirtyä toiseen URL-osoitteeseen ja poistua sovelluksesta {APP_NAME}?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "Sinulla on tallentamattomia muutoksia! Haluatko varmasti siirtyä toiseen URL-osoitteeseen ja poistua sovelluksesta {APP_NAME}?",
  "DONE": "Valmis",
  "OK": "OK",
  "CANCEL": "Peruuta",
  "DONT_SAVE": "Älä tallenna",
  "SAVE": "Tallenna",
  "SAVE_AS": "Tallenna nimellä…",
  "SAVE_AND_OVERWRITE": "Korvaa",
  "ALWAYS_OVERWRITE": "Korvaa aina",
  "DELETE": "Poista",
  "BUTTON_YES": "Kyllä",
  "BUTTON_NO": "Ei",
  "FIND_MATCH_INDEX": "{0} / {1}",
  "FIND_NO_RESULTS": "Ei tuloksia",
  "FIND_QUERY_PLACEHOLDER": "Etsi…",
  "FIND_HISTORY_MAX_COUNT": "Kohteiden enimmäismäärä hakuhistoriassa",
  "REPLACE_PLACEHOLDER": "Korvaa merkkijonolla…",
  "BUTTON_REPLACE_ALL": "Korvaa kaikki",
  "BUTTON_REPLACE_BATCH": "Korvaa erissä…",
  "BUTTON_REPLACE_ALL_IN_FILES": "Korvaa…",
  "BUTTON_REPLACE": "Korvaa",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "Seuraava vastine",
  "BUTTON_PREV_HINT": "Edellinen vastine",
  "BUTTON_CASESENSITIVE_HINT": "Huomioi kirjainkoko",
  "BUTTON_REGEXP_HINT": "Säännöllinen lauseke",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "Korvaa kumoamatta",
  "REPLACE_WITHOUT_UNDO_WARNING": "Koska yli {0} tiedoston pitää muuttua, {APP_NAME} muokkaa avaamattomia tiedostoja levyllä.<br />Et voi perua korvauksia näissä tiedostoissa.",
  "BUTTON_REPLACE_WITHOUT_UNDO": "Korvaa kumoamatta",
  "OPEN_FILE": "Avaa tiedosto",
  "SAVE_FILE_AS": "Tallenna tiedosto",
  "CHOOSE_FOLDER": "Valitse kansio",
  "RELEASE_NOTES": "Julkaisutiedot",
  "NO_UPDATE_TITLE": "Olet ajan tasalla!",
  "NO_UPDATE_MESSAGE": "Käytät uusinta {APP_NAME}-versiota.",
  "FIND_REPLACE_TITLE_LABEL": "Korvaa",
  "FIND_REPLACE_TITLE_WITH": "merkkijonolla",
  "FIND_TITLE_LABEL": "Löytyi",
  "FIND_TITLE_SUMMARY": "&mdash; {0} {1} {2} {3}",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "kohteesta <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_NO_SCOPE": "projektissa",
  "FIND_IN_FILES_PROJECT_SCOPE": "Etsi projektista",
  "FIND_IN_FILES_PROJECT_SCOPE_FILTER": "Etsi osoitteesta {0}",
  "FIND_IN_FILES_PROJECT_SCOPE_REPLACE": "Vaihda projektiin",
  "FIND_IN_FILES_PROJECT_SCOPE_REPLACE_FILTER": "Korvaa kielellä {0}",
  "FIND_IN_FILES_ZERO_FILES": "Suodatin ohittaa kaikki tiedostot {0}",
  "FIND_IN_FILES_FILE": "tiedostossa",
  "FIND_IN_FILES_FILES": "tiedostossa",
  "FIND_IN_FILES_MATCH": "vastine",
  "FIND_IN_FILES_MATCHES": "vastinetta",
  "FIND_IN_FILES_MORE_THAN": "Yli ",
  "FIND_IN_FILES_PAGING": "{0}&ndash;{1}",
  "FIND_IN_FILES_FILE_PATH": "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "Laajenna tai pienennä kaikki painamalla Ctrl/Cmd",
  "FIND_IN_FILES_INDEXING": "Indeksoidaan pikahakua varten…",
  "FIND_IN_FILES_SEARCHING": "Haetaan tiedostoja…",
  "FIND_IN_FILES_SEARCHING_IN": "{0}",
  "FIND_IN_FILES_INDEXING_PROGRESS": "Indeksoidaan {0}/{1} tiedostoa pikahakuun…",
  "REPLACE_IN_FILES_ERRORS_TITLE": "Korvausvirheitä",
  "REPLACE_IN_FILES_ERRORS": "Seuraavia tiedostoja ei muokattu, koska ne olivat muuttuneet haun jälkeen tai niihin ei voitu kirjoittaa.",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "Virhe päivitystietojen haussa",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "Uusimpien päivitystietojen haussa palvelimelta oli ongelmia. Varmista, että olet yhteydessä verkkoon, ja yritä uudelleen.",
  "NEW_FILE_FILTER": "Uusi ohitusjoukko…",
  "CLEAR_FILE_FILTER": "Älä ohita tiedostoja",
  "NO_FILE_FILTER": "Tiedostoja ei ohitettu",
  "EXCLUDE_FILE_FILTER": "Sulje pois tiedostot",
  "INCLUDE_FILE_FILTER": "Hae tiedostoista",
  "FILTER_PLACEHOLDER": "esim. index,.css,*.js,src/**/*.css",
  "FILTER_HISTORY_TOOLTIP": "Paina Ctrl-välilyönti nähdäksesi historian.",
  "FILTER_HISTORY_TOOLTIP_MAC": "Paina \"Cmd-Space\" nähdäksesi historian.",
  "FIND_HISTORY_TOOLTIP": "Paina Ctrl-välilyönti nähdäksesi historian.",
  "FIND_HISTORY_TOOLTIP_MAC": "Paina \"Cmd-Space\" nähdäksesi historian.",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "Pikamuokkaus ei ole saatavilla kohdistimen nykyiselle sijainnille",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "CSS-pikamuokkaus: sijoita kohdistin yksittäiseen luokan nimeen",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "CSS-pikamuokkaus: puutteellinen class-määrite",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "CSS-pikamuokkaus: puutteellinen id-määrite",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "CSS-pikamuokkaus: sijoita kohdistin tägiin taikka class- tai id-attribuuttiin",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "CSS:n aikafunktion pikamuokkaus: virheellinen syntaksi",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "JS-pikamuokkaus: sijoita kohdistin funktion nimeen",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "Pikadokumentaatio ei ole saatavilla kohdistimen nykyiselle sijainnille",
  "PROJECT_LOADING": "Ladataan…",
  "UNTITLED": "Nimetön",
  "WORKING_FILES": "Työtiedostot",
  "TOP": "ylä",
  "BOTTOM": "ala",
  "LEFT": "vasempaan ",
  "RIGHT": "oikeaan ",
  "CMD_SPLITVIEW_NONE": "Ei jakoa",
  "CMD_SPLITVIEW_VERTICAL": "Pystyjako",
  "CMD_SPLITVIEW_HORIZONTAL": "Vaakajako",
  "SPLITVIEW_MENU_TOOLTIP": "Jaa editori pysty- tai vaakasuunnassa",
  "GEAR_MENU_TOOLTIP": "Määritä työlista",
  "SPLITVIEW_INFO_TITLE": "Jo avoinna",
  "SPLITVIEW_MULTIPANE_WARNING": "Tiedosto on jo auki toisessa ruudussa. {APP_NAME} tukee pian saman tiedoston avaamista useammassa ruudussa. Siihen asti tiedosto näytetään ruudussa, jossa se on jo auki.<br /><br />(Tämä viesti näkyy vain kerran.)",
  "KEYBOARD_OVERLAY_TEXT": "Käytä nuolia navigoidaksesi tai kirjoittamalla valitaksesi käyttöliittymäelementtejä.",
  "KEYBOARD_SHORTCUT_CHANGE_TITLE": "Muuta pikanäppäintä…",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_TITLE": "Muuta pikanäppäintä",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_TEXT": "Paina uutta näppäinyhdistelmää <b>&#39;{0}&#39;</b> (nykyinen: <b>{1}</b> )",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_DUPLICATE": "Varoitus: näppäinyhdistelmä <b>{0}</b> on jo määritetty <b>&#39;{1}&#39;</b> . Määritetäänkö uudelleen kohteelle <b>{2}</b> ?",
  "KEYBOARD_SHORTCUT_ASSIGN": "Määritä",
  "KEYBOARD_SHORTCUT_NONE": "Ei mitään",
  "KEYBOARD_SHORTCUT_MENU_SHOW_SHORTCUTS": "Pikanäppäimet…",
  "KEYBOARD_SHORTCUT_MENU_SHOW_SHORTCUTS_BUTTON": "Näytä kaikki pikakuvakkeet…",
  "KEYBOARD_SHORTCUT_TABLE_BASE_KEY": "Perusavain",
  "KEYBOARD_SHORTCUT_TABLE_KEY_BINDING": "Pikakuvake",
  "KEYBOARD_SHORTCUT_TABLE_COMMAND_ID": "Komentotunnus",
  "KEYBOARD_SHORTCUT_TABLE_COMMAND_NAME": "Komento",
  "KEYBOARD_SHORTCUT_TABLE_DOUBLE_CLICK": "Muuta pikakuvaketta kaksoisnapsauttamalla",
  "KEYBOARD_SHORTCUT_TABLE_ORIGIN": "Alkuperä",
  "KEYBOARD_SHORTCUT_ORIG_EXTENSION": "Laajennus",
  "KEYBOARD_SHORTCUT_PANEL_TITLE": "Pikanäppäimet",
  "KEYBOARD_SHORTCUT_PANEL_FILTER": "Suodata&hellip;",
  "KEYBOARD_SHORTCUT_PANEL_RESET": "Palauta…",
  "KEYBOARD_SHORTCUT_PANEL_RESET_DEFAULT": "Palauta oletuspikakuvakkeet…",
  "KEYBOARD_SHORTCUT_RESET_DIALOG_TITLE": "Nollaa pikanäppäimet",
  "KEYBOARD_SHORTCUT_RESET_DIALOG_MESSAGE": "Palautetaanko kaikki mukautetut pikanäppäimet oletusarvoiksi? Tätä ei voi peruuttaa.",
  "STATUSBAR_CURSOR_POSITION": "Rivi {0}, sarake {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": " — valittu {0} sarake",
  "STATUSBAR_SELECTION_CH_PLURAL": " — valittu {0} saraketta",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " — valittu {0} rivi",
  "STATUSBAR_SELECTION_LINE_PLURAL": " — valittu {0} riviä",
  "STATUSBAR_SELECTION_MULTIPLE": " — {0} valintaa",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "Muuta sisennys välilyönneiksi napsauttamalla",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "Muuta sisennys sarkainmerkeiksi napsauttamalla",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "Muuta sisennyksenä käytettävien välilyöntien määrää napsauttamalla",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "Muuta sarkainmerkin leveyttä napsauttamalla",
  "STATUSBAR_SPACES": "Välilyöntejä:",
  "STATUSBAR_TAB_SIZE": "Sarkaimen koko:",
  "STATUSBAR_LINE_COUNT_SINGULAR": "— {0} rivi",
  "STATUSBAR_LINE_COUNT_PLURAL": "— {0} riviä",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "Laajennukset poistettu käytöstä",
  "STATUSBAR_INSERT": "INS",
  "STATUSBAR_OVERWRITE": "OVR",
  "STATUSBAR_INSOVR_TOOLTIP": "Vaihda kohdistimen sijoitus (INS)- ja korvaus (OVR) ‑tilojen välillä napsauttamalla",
  "STATUSBAR_LANG_TOOLTIP": "Vaihda tiedostotyyppiä napsauttamalla",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. Näytä tai piilota raporttipaneeli napsauttamalla.",
  "STATUSBAR_DEFAULT_LANG": "(oletus)",
  "STATUSBAR_SET_DEFAULT_LANG": "Aseta oletukseksi .{0}-tiedostoille",
  "STATUSBAR_ENCODING_TOOLTIP": "Valitse enkoodaus",
  "STATUSBAR_TASKS": "Tehtävät",
  "STATUSBAR_TASKS_TOOLTIP": "Hallitse aktiivisia tehtäviä",
  "STATUSBAR_TASKS_HIDE_SPINNER": "Piilota Spinner-kuvake",
  "STATUSBAR_TASKS_UNKNOWN_EXTENSION_TASK": "Tuntematon laajennustehtävä…",
  "STATUSBAR_TASKS_PLAY": "Aloita tai Jatka",
  "STATUSBAR_TASKS_PAUSE": "Tauko",
  "STATUSBAR_TASKS_STOP": "Lopettaa",
  "STATUSBAR_TASKS_RESTART": "Uudelleenkäynnistää",
  "ERRORS_NO_FILE": "Ei tiedostoa auki",
  "ERRORS_PANEL_TITLE_MULTIPLE": "{0} ongelmat - {1}",
  "ERRORS_PANEL_TITLE_MULTIPLE_FIXABLE": "{0} Ongelmia, {1} Korjattavissa - {2}",
  "SINGLE_ERROR": "1 {0} Ongelma - {1}",
  "SINGLE_ERROR_FIXABLE": "1 {0} Ongelma, {1} Korjattavissa - {2}",
  "MULTIPLE_ERRORS": "{0} {1} Ongelmia - {2}",
  "MULTIPLE_ERRORS_FIXABLE": "{0} {1} Ongelmia, {2} Korjattavissa - {3}",
  "NO_ERRORS": "{0}-ongelmia ei löytynyt – hyvää työtä!",
  "NO_ERRORS_MULTIPLE_PROVIDER": "Ongelmia ei löytynyt – hyvää työtä!",
  "LINT_DISABLED": "Tarkistus on pois käytöstä",
  "NO_LINT_AVAILABLE": "Tarkistinta ei saatavilla kohteelle {0}",
  "NOTHING_TO_LINT": "Ei tarkistettavaa",
  "COPY_ERROR": "Kopiointiongelma",
  "FIX": "Korjata",
  "CANNOT_FIX_TITLE": "Korjauksen käyttäminen epäonnistui",
  "CANNOT_FIX_SOME_TITLE": "Joidenkin korjausten käyttöönotto epäonnistui",
  "CANNOT_FIX_MESSAGE": "Asiakirjaa on muokattu korjauksen valmistelun jälkeen. Yritä uudelleen.",
  "LINTER_TIMED_OUT": "{0} on aikakatkaistu {1} ms:n odotuksen jälkeen",
  "LINTER_FAILED": "{0} keskeytyi virheeseen: {1}",
  "CLICK_VIEW_PROBLEM": "Napsauta nähdäksesi ongelman paneelissa",
  "FILE_MENU": "Tiedosto",
  "CMD_FILE_NEW_UNTITLED": "Uusi",
  "CMD_FILE_NEW": "Uusi tiedosto",
  "CMD_FILE_DUPLICATE": "Monista",
  "CMD_FILE_DUPLICATE_FILE": "Kopioi tiedosto",
  "CMD_FILE_DOWNLOAD_PROJECT": "Lataa projekti",
  "CMD_FILE_DOWNLOAD": "ladata",
  "CMD_FILE_CUT": "Leikkaa",
  "CMD_FILE_COPY": "Kopioi",
  "CMD_FILE_COPY_PATH": "Kopioi polku",
  "CMD_FILE_PASTE": "Liitä",
  "CMD_PROJECT_NEW": "Uusi projekti…",
  "CMD_FILE_NEW_FOLDER": "Uusi kansio",
  "CMD_FILE_OPEN": "Avaa tiedostot…",
  "CMD_RECENT_FILES_OPEN": "Viimeaikaiset tiedostot…",
  "CMD_ADD_TO_WORKING_SET": "Avaa työlistaan",
  "CMD_OPEN_DROPPED_FILES": "Avaa pudotetut tiedostot",
  "CMD_OPEN_FOLDER": "Avaa kansio…",
  "CMD_FILE_CLOSE": "Sulje",
  "CMD_FILE_CLOSE_ALL": "Sulje kaikki",
  "CMD_FILE_CLOSE_LIST": "Sulje lista",
  "CMD_FILE_CLOSE_OTHERS": "Sulje muut",
  "CMD_FILE_CLOSE_ABOVE": "Sulje muut yläpuolelta",
  "CMD_FILE_CLOSE_BELOW": "Sulje muut alapuolelta",
  "CMD_FILE_SAVE": "Tallenna tiedosto",
  "CMD_FILE_SAVE_ALL": "Tallenna kaikki",
  "CMD_FILE_SAVE_AS": "Tallenna nimellä…",
  "CMD_LIVE_FILE_PREVIEW": "Esikatselu",
  "CMD_LIVE_FILE_PREVIEW_SETTINGS": "Live-esikatselun asetukset",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "Ota kokeellinen esikatselu käyttöön",
  "CMD_RELOAD_LIVE_PREVIEW": "Pakota esikatselu päivittymään",
  "CMD_PROJECT_SETTINGS": "Projektin asetukset…",
  "CMD_FILE_RENAME": "Nimeä uudelleen",
  "CMD_FILE_DELETE": "Poista",
  "CMD_INSTALL_EXTENSION": "Asenna laajennus…",
  "CMD_EXTENSION_MANAGER": "Laajennusten hallinta…",
  "CMD_FILE_REFRESH": "Päivitä tiedostopuu",
  "CMD_FILE_SHOW_FOLDERS_FIRST": "Lajittele kansiot ensin",
  "CMD_QUIT": "Lopeta",
  "CMD_EXIT": "Lopeta",
  "EDIT_MENU": "Muokkaa",
  "CMD_UNDO": "Kumoa",
  "CMD_REDO": "Tee uudelleen",
  "CMD_CUT": "Leikkaa",
  "CMD_COPY": "Kopioi",
  "CMD_PASTE": "Liitä",
  "CMD_SELECT_ALL": "Valitse kaikki",
  "CMD_SELECT_LINE": "Valitse rivi",
  "CMD_SPLIT_SEL_INTO_LINES": "Jaa valinta riveille",
  "CMD_ADD_CUR_TO_NEXT_LINE": "Lisää kohdistin seuraavalle riville",
  "CMD_ADD_CUR_TO_PREV_LINE": "Lisää kohdistin edelliselle riville",
  "CMD_INDENT": "Sisennä",
  "CMD_UNINDENT": "Poista sisennys",
  "CMD_DUPLICATE": "Monista",
  "CMD_DELETE_LINES": "Poista rivi",
  "CMD_COMMENT": "Muuta kommenttiriviksi",
  "CMD_BLOCK_COMMENT": "Muuta kommenttilohkoksi",
  "CMD_LINE_UP": "Siirrä riviä ylös",
  "CMD_LINE_DOWN": "Siirrä riviä alas",
  "CMD_OPEN_LINE_ABOVE": "Avaa rivi yllä",
  "CMD_OPEN_LINE_BELOW": "Avaa rivi alla",
  "CMD_TOGGLE_CLOSE_BRACKETS": "Sulje sulkeet automaattisesti",
  "CMD_SHOW_CODE_HINTS": "Näytä koodivihjeet",
  "CMD_BEAUTIFY_CODE": "Kaunista koodi",
  "CMD_BEAUTIFY_CODE_ON_SAVE": "Kaunista koodi tallennuksen jälkeen",
  "FIND_MENU": "Etsi",
  "CMD_FIND": "Etsi",
  "CMD_FIND_NEXT": "Etsi seuraava",
  "CMD_FIND_PREVIOUS": "Etsi edellinen",
  "CMD_FIND_ALL_AND_SELECT": "Valitse Kaikki tapahtumat",
  "CMD_ADD_NEXT_MATCH": "Lisää seuraava esiintyminen",
  "CMD_SKIP_CURRENT_MATCH": "Ohita ja lisää seuraava tapahtuma",
  "CMD_FIND_IN_FILES": "Etsi tiedostoista",
  "CMD_FIND_IN_SUBTREE": "Etsi kohteesta…",
  "CMD_REPLACE": "Korvaa",
  "CMD_REPLACE_IN_FILES": "Korvaa tiedostoissa",
  "CMD_REPLACE_IN_SUBTREE": "Korvaa kohteessa…",
  "VIEW_MENU": "Näytä",
  "CMD_HIDE_SIDEBAR": "Piilota sivupalkki",
  "CMD_SHOW_SIDEBAR": "Näytä sivupalkki",
  "CMD_TOGGLE_SIDEBAR": "Näytä tai piilota sivupalkki",
  "CMD_TOGGLE_PANELS": "Näytä tai piilota paneelit",
  "CMD_TOGGLE_PURE_CODE": "Ei häiriötekijöitä",
  "CMD_TOGGLE_FULLSCREEN": "Koko näyttö",
  "CMD_ZOOM_UI": "Zoomaa käyttöliittymä ja fontit",
  "CMD_ZOOM_IN": "Lähennä",
  "CMD_ZOOM_IN_SCALE": "Lähennä (nykyinen: {0} %)",
  "CMD_ZOOM_OUT": "Loitontaa",
  "CMD_INCREASE_FONT_SIZE": "Suurenna fonttikokoa",
  "CMD_DECREASE_FONT_SIZE": "Pienennä fonttikokoa",
  "CMD_RESTORE_FONT_SIZE": "Palauta fonttikoko",
  "CMD_SCROLL_LINE_UP": "Vieritä rivi ylös",
  "CMD_SCROLL_LINE_DOWN": "Vieritä rivi alas",
  "CMD_TOGGLE_LINE_NUMBERS": "Rivinumerot",
  "CMD_TOGGLE_ACTIVE_LINE": "Korosta valittu rivi",
  "CMD_TOGGLE_WORD_WRAP": "Automaattinen rivitys",
  "CMD_LIVE_HIGHLIGHT": "Esikatselun korostus",
  "CMD_VIEW_TOGGLE_INSPECTION": "Tarkista tiedostot tallennettaessa",
  "CMD_WORKINGSET_SORT_BY_ADDED": "Järjestä lisäysajan mukaan",
  "CMD_WORKINGSET_SORT_BY_NAME": "Järjestä nimen mukaan",
  "CMD_WORKINGSET_SORT_BY_TYPE": "Järjestä tyypin mukaan",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "Automaattinen järjestys",
  "CMD_THEMES": "Teemat…",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "Sulje haku automaattisesti",
  "CMD_TOGGLE_RULERS": "Hallitsijat",
  "CMD_KEYBOARD_NAV_OVERLAY": "Visuaalinen komentopaletti",
  "NAVIGATE_MENU": "Siirry",
  "CMD_QUICK_OPEN": "Pika-avaus",
  "CMD_GOTO_LINE": "Siirry riville",
  "CMD_GOTO_DEFINITION": "Etsi määrittely nopeasti",
  "CMD_GOTO_DEFINITION_PROJECT": "Quick Find Definition in Project",
  "CMD_GOTO_FIRST_PROBLEM": "Siirry ensimmäiseen ongelmaan",
  "CMD_TOGGLE_QUICK_EDIT": "Pikamuokkaus",
  "CMD_TOGGLE_QUICK_DOCS": "Pikadokumentaatio",
  "CMD_QUICK_EDIT_PREV_MATCH": "Edellinen pikamuokkauskohde",
  "CMD_QUICK_EDIT_NEXT_MATCH": "Seuraava pikamuokkauskohde",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "Uusi sääntö",
  "CMD_NEXT_DOC": "Seuraava dokumentti",
  "CMD_PREV_DOC": "Edellinen dokumentti",
  "CMD_NAVIGATE_BACKWARD": "Siirry taaksepäin",
  "CMD_NAVIGATE_FORWARD": "Siirry eteenpäin",
  "CMD_NEXT_DOC_LIST_ORDER": "Seuraava dokumentti listassa",
  "CMD_PREV_DOC_LIST_ORDER": "Edellinen dokumentti listassa",
  "CMD_SHOW_IN_TREE": "Näytä tiedostopuussa",
  "CMD_SHOW_IN_EXPLORER": "Näytä Resurssienhallinnassa",
  "CMD_SHOW_IN_FINDER": "Näytä Finderissä",
  "CMD_SHOW_IN_OS": "Näytä käyttöjärjestelmätiedostoissa",
  "CMD_SWITCH_PANE_FOCUS": "Vaihda ruudun valinta",
  "CMD_OPEN_VFS": "Avaa Virtual File System",
  "CMD_DIAGNOSTIC_TOOLS": "{APP_NAME} Diagnostiikkatyökalut",
  "CMD_OPEN_EXTENSIONS_FOLDER": "Avaa laajennuskansio…",
  "CMD_OPEN_VIRTUAL_SERVER": "Avaa Virtual Server",
  "HELP_MENU": "Ohje",
  "CMD_CHECK_FOR_UPDATE": "Tarkista päivitykset…",
  "CMD_AUTO_UPDATE": "Automaattinen päivitys",
  "CMD_HOW_TO_USE_BRACKETS": "Kuinka käyttää {APP_NAME}iä",
  "CMD_SUPPORT": "{APP_NAME}-tuki",
  "CMD_DOCS": "Apua, Aloitus",
  "CMD_SUGGEST": "Ehdota ominaisuutta",
  "CMD_RELEASE_NOTES": "Julkaisutiedot",
  "CMD_GET_INVOLVED": "Lähde mukaan",
  "CMD_SHOW_EXTENSIONS_FOLDER": "Näytä laajennuskansio",
  "CMD_HEALTH_DATA_STATISTICS": "Terveysraportti…",
  "CMD_HOMEPAGE": "Lataa sovelluksia - Kotisivu",
  "CMD_TWITTER": "{TWITTER_NAME} Twitterissä",
  "CMD_YOUTUBE": "Youtube kanava",
  "CMD_ABOUT": "Tietoja {APP_TITLE}istä",
  "CMD_OPEN_PREFERENCES": "Avaa asetustiedosto",
  "CMD_OPEN_KEYMAP": "Avaa User Key Map File",
  "EXPERIMENTAL_BUILD": "kokeellinen koontiversio",
  "RELEASE_BUILD": "koontiversio",
  "DEVELOPMENT_BUILD": "kehityskoontiversio",
  "PRERELEASE_BUILD": "esijulkaisuversio",
  "RELOAD_FROM_DISK": "Lataa uudelleen levyltä",
  "KEEP_CHANGES_IN_EDITOR": "Pidä muutokset editorissa",
  "CLOSE_DONT_SAVE": "Sulje (Älä tallenna)",
  "RELAUNCH_CHROME": "Käynnistä Chrome uudelleen",
  "ABOUT": "Tietoja",
  "CLOSE": "Sulje",
  "ABOUT_TEXT_LINE1": "Julkaisu {VERSION_MAJOR}.{VERSION_MINOR} {BUILD_TYPE} {VERSION}",
  "ABOUT_TEXT_BUILD_TIMESTAMP": "rakentamisen aikaleima:",
  "ABOUT_RELEASE_CREDITS": "Julkaisutiedot:",
  "ABOUT_TEXT_LINE3": "Käyttämämme kolmannen osapuolen kirjastot - <a href='https://github.com/phcode-dev/phoenix/tree/main/src/thirdparty/licences'>lisenssit ja merkinnät</a> .",
  "ABOUT_TEXT_LINE4": "Dokumentaatio ja lähde osoitteessa <a href='https://github.com/phcode-dev/phoenix/'>https://github.com/phcode-dev/phoenix/</a>",
  "ABOUT_TEXT_LINE5": "Tekijä: ❤ ja JavaScript:",
  "ABOUT_TEXT_LINE6": "Monet ihmiset (mutta meillä on vaikeuksia näiden tietojen lataamisessa juuri nyt).",
  "ABOUT_TEXT_MDN_DOCS": "MDN-dokumentit ja graafinen MDN-logo on lisensoitu Creative Commons Attribution ‑lisenssillä, <a href='{MDN_DOCS_LICENSE}'>CC-BY-SA 2.5 Unported</a>.",
  "UPDATE_NOTIFICATION_TOOLTIP": "Uusi {APP_NAME}-versio on saatavilla! Saat lisätietoja napsauttamalla tästä.",
  "UPDATE_NOT_AVAILABLE_TITLE": "{APP_NAME} on ajan tasalla",
  "UPDATE_UP_TO_DATE": "Sovelluksesi {APP_NAME} versio on uusin!",
  "UPDATE_AVAILABLE_TITLE": "Päivitys saatavilla",
  "UPDATE_WHATS_NEW": "Mitä uutta sovelluksessa {APP_NAME}",
  "UPDATE_READY_RESTART_TITLE": "Päivitä käynnistämällä sovellus uudelleen",
  "UPDATE_READY_RESTART_INSTALL_MESSAGE": "{APP_NAME} päivitetään automaattisesti, kun suljet kaikki avoimet ikkunat.",
  "UPDATE_FAILED_TITLE": "Päivitys epäonnistui",
  "UPDATE_INSTALLING": "Asentaa päivitystä…",
  "UPDATE_INSTALLING_MESSAGE": "Päivityksen asennus käynnissä: {APP_NAME} asentaa parhaillaan uusimpia päivityksiä. Sovellus sulkeutuu automaattisesti, kun asennus on valmis.",
  "UPDATE_FAILED_MESSAGE": "Sulje kaikki {APP_NAME} -sovellusikkunat ja avaa sovellus uudelleen yrittääksesi päivittää uudelleen.<br/> Voit myös asentaa päivityksen lataamalla asennusohjelman osoitteesta <a href='https://phcode.io'>phcode.io</a>",
  "UPDATE_FAILED_VISIT_SITE_MESSAGE": "Yritä uudelleen sulkemalla kaikki sovelluksen {APP_NAME} esiintymät ja käynnistämällä sovellus uudelleen.<br> Sinut ohjataan pian lataussivullemme, josta voit ladata manuaalisesti uusimman version.",
  "UPDATE_MESSAGE": "Hei, uusi {APP_NAME}-versio on saatavilla. Tässä on joitakin uusista ominaisuuksista:",
  "GET_IT_NOW": "Hae nyt!",
  "UPDATE_ON_EXIT": "Päivitys poistuttaessa",
  "UPDATE_LATER": "Muistuta minua myöhemmin",
  "UPDATE_DONE": "Päivitä {APP_NAME} käynnistämällä uudelleen",
  "UPDATE_RESTART_INSTALL": "Käynnistä uudelleen asentaaksesi päivitykset",
  "UPDATE_DOWNLOADING": "Ladataan asennusohjelmaa",
  "INSTALL_WEBAPP": "Asenna {APP_NAME} laitteellesi",
  "UPDATE_DOWNLOAD_PROGRESS": "Ladataan - {0}/{1} Mt",
  "UPDATING_APP": "Päivitetään {APP_NAME}",
  "UPDATING_APP_MESSAGE": "Tämä voi kestää hetken",
  "UPDATING_APP_DIALOG_MESSAGE": "Päivitys käynnissä. Voit jatkaa sovelluksen {APP_NAME} käyttöä päivityksen aikana.",
  "PROJECT_SETTINGS_TITLE": "Projektin asetukset kohteelle: {0}",
  "PROJECT_SETTING_BASE_URL": "Esikatselun perus-URL",
  "PROJECT_SETTING_BASE_URL_HINT": "Käytä paikall. palvelinta antamalla URL, kuten http://localhost:8000/",
  "BASEURL_ERROR_INVALID_PROTOCOL": "Esikatselu ei tue {0}-protokollaa. Käytä joko http: tai https: ‑muotoa.",
  "BASEURL_ERROR_SEARCH_DISALLOWED": "URL-osoite ei voi sisältää hakuparametreja, kuten ”{0}”.",
  "BASEURL_ERROR_HASH_DISALLOWED": "URL-osoite ei voi sisältää ristikkomerkkejä, kuten ”{0}”.",
  "BASEURL_ERROR_INVALID_CHAR": "Erikoismerkit, kuten ”{0}”, täytyy %-koodata.",
  "BASEURL_ERROR_UNKNOWN_ERROR": "Tuntematon virhe URL-osoitteen jäsentämisessä",
  "EMPTY_VIEW_HEADER": "<em>Avaa tiedosto tämän ruudun ollessa valittuna</em>",
  "FLIPVIEW_BTN_TOOLTIP": "Heitä tämä näkymä {0}paneeliin",
  "CURRENT_THEME": "Nykyinen teema",
  "USE_THEME_SCROLLBARS": "Käytä teeman vierityspalkkeja",
  "FONT_SIZE": "Fonttikoko",
  "FONT_FAMILY": "Fonttiperhe",
  "THEMES_SETTINGS": "Teema-asetukset",
  "THEMES_ERROR": "Teemat Virhe",
  "THEMES_ERROR_CANNOT_APPLY": "Teemaa ei voitu käyttää virheen vuoksi.",
  "BUTTON_NEW_RULE": "Uusi sääntö",
  "INSTALL": "Asenna",
  "APPLY": "Käytä",
  "UPDATE": "Päivitä",
  "REMOVE": "Poista",
  "DISABLE": "Poista käytöstä",
  "ENABLE": "Ota käyttöön",
  "OVERWRITE": "Korvaa",
  "CANT_DROP_ZIP": "Zip-tiedostojen pudottamista tuetaan pian...",
  "CANT_REMOVE_DEV": "Kansion ”dev” laajennukset on poistettava käsin.",
  "CANT_UPDATE": "Laajennus ei ole yhteensopiva tämän {APP_NAME}-version kanssa.",
  "CANT_UPDATE_DEV": "Kansion ”dev” laajennuksia ei voi päivittää automaattisesti.",
  "INSTALL_EXTENSION_TITLE": "Asenna laajennus",
  "UPDATE_EXTENSION_TITLE": "Päivitä laajennus",
  "INSTALL_EXTENSION_LABEL": "Laajennuksen URL-osoite",
  "INSTALL_EXTENSION_HINT": "Laajennuksen zip-tiedoston URL-osoite tai GitHub-varasto",
  "INSTALLING_FROM": "Asennetaan laajennus kohteesta {0}…",
  "INSTALL_SUCCEEDED": "Asennus on valmis!",
  "INSTALL_FAILED": "Asennus epäonnistui.",
  "CANCELING_INSTALL": "Peruutetaan…",
  "CANCELING_HUNG": "Asennuksen peruuttaminen kestää pitkään. On saattanut tapahtua sisäinen virhe.",
  "INSTALL_CANCELED": "Asennus on peruutettu.",
  "VIEW_COMPLETE_DESCRIPTION": "Näytä täysi kuvaus",
  "VIEW_TRUNCATED_DESCRIPTION": "Näytä katkaistu kuvaus",
  "SORT_EXTENSION_METHOD": "Järjestele laajennukset latausmäärän tai päivitysajankohdan mukaan",
  "INVALID_ZIP_FILE": "Ladattu sisältö ei ole kelvollinen zip-tiedosto.",
  "MISSING_PACKAGE_JSON": "Paketissa ei ole tiedostoa package.json.",
  "INVALID_PACKAGE_JSON": "Tiedosto package.json on virheellinen. (Virhe {0}.)",
  "MISSING_PACKAGE_NAME": "Tiedostoon package.json ei ole merkitty paketin nimeä.",
  "BAD_PACKAGE_NAME": "{0} on virheellinen paketin nimi.",
  "MISSING_PACKAGE_VERSION": "Tiedostoon package.json ei ole merkitty paketin versiota.",
  "INVALID_VERSION_NUMBER": "Paketin versionumero ({0}) on virheellinen.",
  "INVALID_BRACKETS_VERSION": "{APP_NAME}in yhteensopivuuden merkkijono ({0}) on virheellinen.",
  "DISALLOWED_WORDS": "Sanat ({1}) eivät ole sallittuja kentässä {0}.",
  "NPM_INSTALL_FAILED": "npm install ‑komento epäonnistui: {0}",
  "API_NOT_COMPATIBLE": "Laajennus ei ole yhteensopiva tämän {APP_NAME}-version kanssa. Se asennettiin käytöstä poistettujen laajennusten kansioon.",
  "MISSING_MAIN": "Paketissa ei ole tiedostoa main.js.",
  "EXTENSION_ALREADY_INSTALLED": "Tämän paketin asennus korvaa aiemmin asennetun laajennuksen. Korvataanko vanha laajennus?",
  "EXTENSION_SAME_VERSION": "Tämän paketin versio on sama kuin jo asennetun. Korvataanko nykyinen asennus?",
  "EXTENSION_OLDER_VERSION": "Tämän paketin versio on {0}, joka on vanhempi kuin jo asennetun ({1}). Korvataanko nykyinen asennus?",
  "DOWNLOAD_ID_IN_USE": "Sisäinen virhe: lataustunnus on jo käytössä.",
  "NO_SERVER_RESPONSE": "Palvelimeen ei voida yhdistää.",
  "BAD_HTTP_STATUS": "Tiedostoa ei löydy palvelimelta (HTTP {0}).",
  "CANNOT_WRITE_TEMP": "Latausta ei kyetty tallentamaan tilapäistiedostoon.",
  "ERROR_LOADING": "Laajennuksen käynnistyksessä tapahtui virhe.",
  "MALFORMED_URL": "URL-osoite on virheellinen. Tarkista, että kirjoitit sen oikein.",
  "UNSUPPORTED_PROTOCOL": "URL-osoitteen on oltava http- tai https-muotoinen.",
  "UNKNOWN_ERROR": "Tuntematon sisäinen virhe.",
  "EXTENSION_VERIFIED_PUBLISHER": "Tämä julkaisija on vahvistanut kohteen {0} omistajuuden",
  "EXTENSION_VERIFIED_SORT": "Vahvistettu",
  "EXTENSION_STAR": "Tähti",
  "EXTENSION_STAR_SORT": "Tähtiluokitus",
  "EXTENSION_MANAGER_TITLE": "Laajennusten hallinta",
  "EXTENSION_MANAGER_ERROR_LOAD": "Virhe käytettäessä laajennusten rekisteriä. Yritä myöhemmin uudelleen.",
  "EXTENSION_UPDATE_RESTART_TITLE": "Käynnistä uudelleen päivittääksesi",
  "EXTENSION_UPDATE_RESTART_MESSAGE": "Lataa päivitetyt laajennukset sulkemalla kaikki käynnissä olevat sovelluksen {APP_NAME} esiintymät ja käynnistämällä sovellus uudelleen.",
  "INSTALL_EXTENSION_DRAG": "Vedä .zip-paketti tähän tai",
  "INSTALL_EXTENSION_DROP": "Asenna pudottamalla .zip-paketti",
  "INSTALL_EXTENSION_DROP_ERROR": "Asennus tai päivitys keskeytyi seuraaviin virheisiin:",
  "INSTALL_FROM_URL": "asenna URL-osoitteesta…",
  "INSTALL_EXTENSION_VALIDATING": "Vahvistetaan…",
  "EXTENSION_AUTHOR": "Tekijä",
  "EXTENSION_DATE": "Päivämäärä",
  "EXTENSION_INCOMPATIBLE_NEWER": "Tämä laajennus vaatii uudemman {APP_NAME}-version.",
  "EXTENSION_INCOMPATIBLE_OLDER": "Tämä laajennus toimii tällä hetkellä vain vanhemmilla {APP_NAME}-versioilla.",
  "EXTENSION_DEFAULT_FEATURE_PRESENT": "Et ehkä tarvitse tätä laajennusta. {APP_NAME} sisältää jo tämän ominaisuuden.",
  "EXTENSION_LATEST_INCOMPATIBLE_NEWER": "Tämän laajennuksen versio {0} vaatii uudemman {APP_NAME}-version, mutta voit asentaa aikaisemman version {1}.",
  "EXTENSION_LATEST_INCOMPATIBLE_OLDER": "Tämän laajennuksen versio {0} toimii vain vanhemmilla {APP_NAME}-versioilla, mutta voit asentaa aikaisemman version {1}.",
  "EXTENSION_NO_DESCRIPTION": "Ei kuvausta",
  "EXTENSION_MORE_INFO": "Lisätietoja…",
  "EXTENSION_ERROR": "Laajennusvirhe",
  "EXTENSION_KEYWORDS": "Avainsanat",
  "EXTENSION_TRANSLATED_USER_LANG": "Käännetty {0} kielelle, myös sinun",
  "EXTENSION_TRANSLATED_GENERAL": "Käännetty {0} kielelle",
  "EXTENSION_TRANSLATED_LANGS": "Tämä laajennus on käännetty näille kielille: {0}",
  "EXTENSION_INSTALLED": "Asennettu",
  "EXTENSION_UPDATE_INSTALLED": "Tämä laajennuspäivitys on ladattu ja asennetaan {APP_NAME}in latauduttua uudelleen.",
  "EXTENSION_SEARCH_PLACEHOLDER": "Hae",
  "EXTENSION_MORE_INFO_LINK": "Lisää",
  "EXTENSION_MANAGER_CREATE_EXTENSION": "+ Luo laajennus",
  "EXTENSION_MANAGER_CREATE_THEME": "+ Luo teema",
  "BROWSE_EXTENSIONS": "Selaa laajennuksia",
  "EXTENSION_MANAGER_REMOVE": "Poista laajennus",
  "EXTENSION_MANAGER_REMOVE_ERROR": "Ainakaan yhtä laajennusta ei voitu poistaa: {0}. {APP_NAME} latautuu silti uudelleen.",
  "EXTENSION_MANAGER_UPDATE": "Päivitä laajennus",
  "EXTENSION_MANAGER_UPDATE_ERROR": "Ainakaan yhtä laajennusta ei voitu päivittää: {0}. {APP_NAME} latautuu silti uudelleen.",
  "EXTENSION_MANAGER_DISABLE": "Poista laajennus käytöstä",
  "EXTENSION_MANAGER_DISABLE_ERROR": "Ainakaan yhtä laajennusta ei voitu poistaa käytöstä: {0}. {APP_NAME} latautuu silti uudelleen.",
  "EXTENSION_MANAGER_THEMES_INFO": "Voit <a class=\"theme_settings\">valita oletusteemoja</a> tai muokata muita teemaasetuksia <a class=\"theme_settings\">napsauttamalla tätä</a> .",
  "EXTENSION_MANAGER_THEMES_UNDO": "Palaa edelliseen teemaan",
  "MARKED_FOR_REMOVAL": "Merkitty poistettavaksi",
  "UNDO_REMOVE": "Kumoa",
  "MARKED_FOR_UPDATE": "Merkitty päivitettäväksi",
  "UNDO_UPDATE": "Kumoa",
  "MARKED_FOR_DISABLING": "Merkitty käytöstä poistettavaksi",
  "UNDO_DISABLE": "Kumoa",
  "CHANGE_AND_RELOAD_TITLE": "Muuta laajennuksia",
  "CHANGE_AND_RELOAD_MESSAGE": "Jotta voit päivittää, poistaa tai poistaa käytöstä merkityt laajennukset, pitää {APP_NAME}in latautua uudelleen. Sinua muistutetaan tallentamattomien muutosten tallentamisesta.",
  "REMOVE_AND_RELOAD": "Poista laajennukset ja lataa uudelleen",
  "CHANGE_AND_RELOAD": "Muuta laajennuksia ja lataa uudelleen",
  "UPDATE_AND_RELOAD": "Päivitä laajennukset ja lataa uudelleen",
  "DISABLE_AND_RELOAD": "Poista laajennukset käytöstä ja lataa uudelleen",
  "PROCESSING_EXTENSIONS": "Käsitellään laajennusten muutoksia…",
  "EXTENSION_NOT_INSTALLED": "Laajennusta {0} ei voida poistaa, koska sitä ei ole asennettu.",
  "NO_EXTENSIONS": "Laajennuksia ei ole vielä asennettu.<br>Aloita napsauttamalla Saatavilla-välilehteä yltä.",
  "NO_EXTENSION_MATCHES": "Ei hakuasi vastaavia laajennuksia.",
  "REGISTRY_SANITY_CHECK_WARNING": "HUOMAA: Nämä laajennukset voivat olla peräisin eri lähteistä kuin {APP_NAME} itse. Laajennuksia ei ole tarkastettu, ja niillä on täydet paikalliset oikeudet. Ole varovainen asentaessasi laajennuksia tuntemattomasta lähteestä.",
  "EXTENSIONS_INSTALLED_TITLE": "Asennettu",
  "EXTENSIONS_DEFAULT_TITLE": "Oletus",
  "EXTENSIONS_AVAILABLE_TITLE": "Saatavilla",
  "EXTENSIONS_THEMES_TITLE": "Teemat",
  "EXTENSIONS_UPDATES_TITLE": "Päivitykset",
  "EXTENSIONS_LAST_UPDATED": "Päivitetty",
  "EXTENSIONS_DOWNLOADS": "Lataukset",
  "INLINE_EDITOR_NO_MATCHES": "Vastineita ei saatavilla.",
  "INLINE_EDITOR_HIDDEN_MATCHES": "Kaikki vastineet on pienennetty. Laajenna oikealla listatut tiedostot, niin näet vastineet.",
  "CSS_QUICK_EDIT_NO_MATCHES": "Valintaasi vastaavia CSS-sääntöjä ei ole.<br> Luo sellainen napsauttamalla ”Uusi sääntö”.",
  "CSS_QUICK_EDIT_NO_STYLESHEETS": "Projektissa ei ole tyylitiedostoja.<br>Lisää CSS-sääntöjä luomalla sellainen.",
  "IMAGE_VIEWER_LARGEST_ICON": "suurin",
  "UNIT_PIXELS": "pikseliä",
  "DEBUG_MENU": "Kehitys",
  "ERRORS": "Virheet",
  "CMD_SHOW_DEV_TOOLS": "{APP_NAME} -kehittäjätyökalut",
  "CMD_REFRESH_WINDOW": "Lataa uudelleen laajennuksineen",
  "CMD_LOAD_CURRENT_EXTENSION": "Lataa projekti laajennuksena",
  "CMD_RELOAD_CURRENT_EXTENSION": "Lataa projekti uudelleen laajennuksena",
  "CMD_UNLOAD_CURRENT_EXTENSION": "Pura projekti laajennuksena",
  "CMD_RELOAD_WITHOUT_USER_EXTS": "Lataa uudelleen laajennuksitta",
  "CMD_NEW_BRACKETS_WINDOW": "Uusi ikkuna",
  "CMD_LAUNCH_SCRIPT_MAC": "Asenna komentorivin oikotie",
  "CMD_SWITCH_LANGUAGE": "Vaihda kieltä…",
  "CMD_RUN_UNIT_TESTS": "Suorita sovelluksen {APP_NAME} testit",
  "CMD_SHOW_PERF_DATA": "Näytä suorituskykytiedot",
  "CMD_ENABLE_LOGGING": "Ota käyttöön yksityiskohtaiset lokit",
  "CMD_ENABLE_PHNODE_INSPECTOR": "Ota PhNode Inspector käyttöön",
  "CMD_GET_PHNODE_INSPECTOR_URL": "Kuinka tarkastaa PhNode",
  "CMD_ENABLE_LIVE_PREVIEW_LOGS": "Live-esikatselulokit",
  "CMD_OPEN_BRACKETS_SOURCE": "Avaa {APP_NAME}in lähdekoodi",
  "CREATING_LAUNCH_SCRIPT_TITLE": "{APP_NAME}in komentorivin oikotie",
  "ERROR_CREATING_LAUNCH_SCRIPT": "Tapahtui virhe asennettaessa komentorivin oikotietä. Kokeile <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting'>näitä vianmääritysohjeita</a>.<br/><br/>Syy: {0}",
  "ERROR_CLTOOLS_RMFAILED": "Olemassa olevaa symbolista linkkiä <code>/usr/local/bin/brackets</code> ei voitu poistaa.",
  "ERROR_CLTOOLS_MKDIRFAILED": "Hakemistoa <code>/usr/local/bin</code> ei voitu luoda.",
  "ERROR_CLTOOLS_LNFAILED": "Symbolista linkkiä <code>/usr/local/bin/brackets</code> ei voitu luoda.",
  "ERROR_CLTOOLS_SERVFAILED": "Sisäinen virhe.",
  "ERROR_CLTOOLS_NOTSUPPORTED": "Komentorivin oikotie ei ole tuettu tässä käyttöjärjestelmässä.",
  "LAUNCH_SCRIPT_CREATE_SUCCESS": "Onnistui! Voit nyt avata {APP_NAME}in helposti komentoriviltä: avaa tiedosto komennolla <code>brackets tiedosto.txt</code> tai vaihda projektia komennolla <code>brackets kansio</code>. <br/><br/><a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments'>Lue lisää</a> {APP_NAME}in käyttämisestä komentoriviltä.",
  "ERROR_LOADING_EXTENSION": "Virhe ladattaessa laajennusta",
  "ERROR_NO_EXTENSION_PACKAGE": "<code>package.json</code> -tiedostoa ei löydy nykyisestä projektista. Onko nykyinen projekti kelvollinen laajennus {APP_NAME}?</br> Katso lisätietoja <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>tästä linkistä</a> .",
  "ERROR_INVALID_EXTENSION_PACKAGE": "<code>package.json</code> tiedosto on virheellinen JSON.</br> Katso lisätietoja <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>tästä linkistä</a> .",
  "ERROR_INVALID_EXTENSION_PACKAGE_FIELDS": "Pakolliset kentät puuttuvat paketista <code>package.json</code> : [{0}]</br> Katso lisätietoja <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>tästä linkistä</a> .",
  "ERROR_NODE_JS_CRASH_TITLE": "Oho! Jotain meni pieleen.",
  "ERROR_NODE_JS_CRASH_MESSAGE": "Olemme törmänneet ongelmaan, ja {APP_NAME} on käynnistettävä uudelleen. Älä huoli, yritämme tallentaa kaikki työsi ennen uudelleenkäynnistystä. </br>(Virhe: ERROR_NODE_JS_CRASH)",
  "LANGUAGE_TITLE": "Vaihda kieltä",
  "LANGUAGE_MESSAGE": "Kieli:",
  "LANGUAGE_SUBMIT": "Päivitä {APP_NAME}",
  "LANGUAGE_CANCEL": "Peruuta",
  "LANGUAGE_SYSTEM_DEFAULT": "Järjestelmän oletus",
  "HEALTH_DATA_NOTIFICATION": "Terveydentilaraportin asetukset",
  "HEALTH_FIRST_POPUP_TITLE": "Tietosuojailmoitus",
  "HEALTH_DATA_DO_TRACK": "Jaa nimettömiä tietoja siitä, kuinka käytän sovellusta {APP_NAME}",
  "HEALTH_DATA_NOTIFICATION_MESSAGE": "{APP_NAME} <strong>ei kerää tai käsittele henkilökohtaisia tunnistetietoja</strong> , mutta <strong>kerää anonyymejä käyttötilastoja</strong> suojatakseen yksityisyyttäsi. Nimettömät tiedot on vapautettu GDPR/CCPA-ilmoitusvaatimuksista, mutta uskomme, että sinun on voitava myös kieltäytyä anonyymista tiedonkeruusta.<br><br> Voit nähdä tietosi tai <strong>päättää olla jakamatta anonyymejä tietoja</strong> valitsemalla <strong>Ohje &gt; Terveysraportti</strong> . Nämä <strong>anonyymit</strong> sovellusten käyttötilastot ja virheraportit auttavat priorisoimaan ominaisuuksia, löytämään virheitä ja havaitsemaan käytettävyysongelmia parantaaksesi käyttökokemustasi sovelluksen {APP_NAME} kanssa. Ilman näitä tietoja emme tietäisi, mitä ominaisuuksia sinun kannattaa rakentaa!<br><br>",
  "HEALTH_DATA_PREVIEW": "{APP_NAME}in terveydentilaraportti",
  "HEALTH_DATA_PREVIEW_INTRO": "<p>{APP_NAME} <strong>ei kerää tai käsittele henkilökohtaisia tunnistetietoja</strong> , mutta <strong>kerää anonyymejä käyttötilastoja</strong> suojatakseen yksityisyyttäsi. Nämä <strong>anonyymit</strong> sovellusten käyttötilastot ja virheraportit auttavat priorisoimaan ominaisuuksia, löytämään virheitä ja havaitsemaan käytettävyysongelmia parantaaksesi käyttökokemustasi sovelluksen {APP_NAME} kanssa.</p><p> Alla on esikatselu tiedoista, jotka lähetetään seuraavassa terveysraportissasi <em>, jos</em> se on käytössä. (Katso myös kehittäjäkonsolista virhelokit, joissa on merkintä &quot;Caught Critical error&quot;.)</p>",
  "INLINE_TIMING_EDITOR_TIME": "Aika",
  "INLINE_TIMING_EDITOR_PROGRESSION": "Edistyminen",
  "BEZIER_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd><kbd>←</kbd><kbd>→</kbd> Siirrä valittua pistettä<br><kbd class='text'>Vaihto</kbd> Siirrä kymmenen yksikköä<br><kbd class='text'>Tab</kbd> Vaihda pisteitä",
  "STEPS_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd> Lisää tai vähennä askelmia<br><kbd>←</kbd><kbd>→</kbd> ”Start” tai ”end”",
  "INLINE_TIMING_EDITOR_INVALID": "Vanha arvo <code>{0}</code> on virheellinen, joten näytetty funktio muutettiin muotoon <code>{1}</code>. Dokumentti päivitetään ensimmäisellä muokkauksella.",
  "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP": "Nykyinen väri",
  "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP": "Alkuperäinen väri",
  "COLOR_EDITOR_RGBA_BUTTON_TIP": "RGBa-muoto",
  "COLOR_EDITOR_HEX_BUTTON_TIP": "Hex-muoto",
  "COLOR_EDITOR_HSLA_BUTTON_TIP": "HSLa-muoto",
  "COLOR_EDITOR_0X_BUTTON_TIP": "Hex (0x) ‑muoto",
  "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR": "{0} (käytetty {1} kerran)",
  "COLOR_EDITOR_USED_COLOR_TIP_PLURAL": "{0} (käytetty {1} kertaa)",
  "EDIT": "Muokkaa",
  "CMD_JUMPTO_DEFINITION": "Siirry määrittelyyn",
  "CMD_SHOW_PARAMETER_HINT": "Näytä parametrivihje",
  "NO_ARGUMENTS": "<ei parametreja>",
  "DETECTED_EXCLUSION_TITLE": "JavaScript-tiedoston päättelyongelma",
  "DETECTED_EXCLUSION_INFO": "{APP_NAME} kohtasi ongelmia sovelluksen <span class='dialog-filename'>{0}</span> käsittelyssä.<br><br> Tätä tiedostoa ei enää käsitellä koodivinkkejä, Jump to Definition tai pikamuokkausta varten. Ota tämä tiedosto uudelleen käyttöön avaamalla projektissasi <code>.phcode.json</code> ja muokkaamalla <code>jscodehints.detectedExclusions</code> .<br><br> Tämä on todennäköisesti {APP_NAME} -virhe. Jos voit toimittaa kopion tästä tiedostosta, <a href='https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue'>ilmoita virheestä</a> ja linkistä tässä nimettyyn tiedostoon.",
  "CMD_REFACTOR": "Refaktori",
  "CMD_EXTRACTTO_VARIABLE": "Pura muuttujaan",
  "CMD_EXTRACTTO_FUNCTION": "Pura toimintoon",
  "ERROR_TERN_FAILED": "Tietoja ei voi saada Ternistä",
  "ERROR_EXTRACTTO_VARIABLE_NOT_VALID": "Valinta ei muodosta ilmaisua",
  "ERROR_EXTRACTTO_FUNCTION_NOT_VALID": "Valitun lohkon tulee edustaa lauseiden joukkoa tai lauseketta",
  "ERROR_EXTRACTTO_VARIABLE_MULTICURSORS": "Purkaminen muuttujaksi ei toimi monikursoreissa",
  "ERROR_EXTRACTTO_FUNCTION_MULTICURSORS": "Pura funktioon ei toimi monikursoreissa",
  "EXTRACTTO_FUNCTION_SELECT_SCOPE": "Valitse kohteen laajuus",
  "EXTRACTTO_VARIABLE_SELECT_EXPRESSION": "Valitse lauseke",
  "CMD_REFACTORING_RENAME": "Nimeä uudelleen",
  "CMD_REFACTORING_TRY_CATCH": "Kääri Try Catchiin",
  "CMD_REFACTORING_CONDITION": "Kääri kuntoon",
  "CMD_REFACTORING_GETTERS_SETTERS": "Luo Getters/Setters",
  "CMD_REFACTORING_ARROW_FUNCTION": "Muunna nuolifunktioksi",
  "DESCRIPTION_CODE_REFACTORING": "Ota JavaScript Code Refaktoring käyttöön tai poista se käytöstä",
  "ERROR_TRY_CATCH": "Valitse kelvollinen koodi kääriäksesi Try-catch-lohkoon",
  "ERROR_WRAP_IN_CONDITION": "Valitse kelvollinen koodi kääriäksesi ehtolohkoon",
  "ERROR_ARROW_FUNCTION": "Aseta kohdistin funktiolausekkeen sisään",
  "ERROR_GETTERS_SETTERS": "Aseta kohdistin objektilausekkeen jäsenen kohdalle",
  "ERROR_RENAME_MULTICURSOR": "Ei voi nimetä uudelleen, kun käytetään useita kohdistin",
  "ERROR_RENAME_QUICKEDIT": "Tätä tunnistetta ei voi nimetä uudelleen, koska siihen viitataan muualla tämän toiminnon ulkopuolella",
  "ERROR_RENAME_GENERAL": "Valittua tekstiä ei voi nimetä uudelleen",
  "JSHINT_NAME": "JSHint",
  "JSHINT_CONFIG_ERROR": "Virhe luettaessa JSHint-määritystiedostoa: {0}",
  "JSHINT_CONFIG_JSON_ERROR": "Virhe: JSHint-määritystiedosto `{0}` ei ole kelvollinen JSON",
  "ESLINT_NAME": "ESLint",
  "CSS_LINT_NAME": "{0}",
  "HTML_LINT_NAME": "HTML",
  "HTML_LINT_CONFIG_JSON_ERROR": "Virhe: HTML Validator -määritystiedosto `{0}` ei ole kelvollinen JSON",
  "HTML_LINT_CONFIG_UNSUPPORTED": "Virhe: Määritysmuotoa `{0}` ei tueta. Käytä JSON-asetusta `.htmlvalidate.json`",
  "CMD_ENABLE_QUICK_VIEW": "Pikanäkymä osoitettaessa",
  "CMD_ENABLE_SELECTION_VIEW": "Valintanäkymä",
  "TOOLTIP_CLICK_TO_EDIT_COLOR": "Napsauta tästä muokataksesi väriä",
  "CMD_TOGGLE_RECENT_PROJECTS": "Viimeaikaiset projektit",
  "REMOVE_FROM_RECENT_PROJECTS": "Poista viimeaikaisista projekteista",
  "DOCS_MORE_LINK": "Lue lisää",
  "DOCS_MORE_LINK_MDN_TITLE": "Napsauta lukeaksesi dokumentaatiota",
  "COLLAPSE_ALL": "Pienennä kaikki",
  "EXPAND_ALL": "Laajenna kaikki",
  "COLLAPSE_CURRENT": "Pienennä nykyinen",
  "EXPAND_CURRENT": "Laajenna nykyinen",
  "RECENT_FILES_DLG_HEADER": "Viimeaikaiset tiedostot",
  "RECENT_FILES_DLG_CLEAR_BUTTON_LABEL": "Tyhjennä",
  "RECENT_FILES_DLG_CLEAR_BUTTON_TITLE": "Tyhjennä työlistassa olemattomat tiedostot",
  "RECOVER_UNSAVED_FILES_TITLE": "Palautetaanko tallentamattomat tiedostot?",
  "RECOVER_UNSAVED_FILES_MESSAGE": "Palautetaanko tallentamattomat tiedostot edellisestä istunnosta?",
  "RECOVER_UNSAVED_FILES_RESTORE": "Palauttaa",
  "DISCARD_UNSAVED_FILES_RESTORE": "Hävitä",
  "DESCRIPTION_CLOSE_BRACKETS": "true: sulje aalto-, haka- ja kaarisulkeet automaattisesti",
  "DESCRIPTION_CLOSE_OTHERS_ABOVE": "false: poista Sulje muut yläpuolelta -valinta työtiedostojen kontekstivalikosta",
  "DESCRIPTION_CLOSE_OTHERS_BELOW": "false: poista Sulje muut alapuolelta -valinta työtiedostojen kontekstivalikosta",
  "DESCRIPTION_CLOSE_OTHERS": "false: poista Sulje muut -valinta työtiedostojen kontekstivalikosta",
  "DESCRIPTION_CLOSE_TAGS": "Asettaa tägien sulkemisvalinnat",
  "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS": "Taulukko tägeistä, joita ei pidä sulkea automaattisesti",
  "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING": "Sulje, kun avaustägin > kirjoitetaan",
  "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING": "Sulje, kun sulkutägin / kirjoitetaan",
  "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS": "Taulukko tägeistä, jotka avattaessa sisältävät tyhjän rivin",
  "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD": "true: luo aina pienennettävän osion merkit, kun sisennyksen taso muuttuu",
  "DESCRIPTION_CODE_FOLDING_ENABLED": "true: ota koodin laskostus käyttöön",
  "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER": "true: näytä osion pienennyksen merkit vain, kun osoitin siirretään vasemman marginaalin päälle",
  "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL": "Rajoittaa sitä, kuinka monta tasoa syvälle Pienennä kaikki -valinta vaikuttaa",
  "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE": "Rivejä vähintään ennen kuin pienennettävän osion kuvake tulee esiin",
  "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES": "true: muista pienennetyt osiot, jos tiedosto tai projekti suljetaan ja avataan sitten uudelleen",
  "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE": "true: ota valitun tekstin koodin laskostus käyttöön editorissa",
  "DESCRIPTION_DISABLED_DEFAULT_EXTENSIONS": "Oletuslaajennukset, jotka on poistettu käytöstä",
  "DESCRIPTION_ATTR_HINTS": "Näytä tai piilota HTML-attribuuttien vihjeet",
  "DESCRIPTION_CSS_PROP_HINTS": "Näytä tai piilota CSS/LESS/SCSS-ominaisuuksien vihjeet",
  "DESCRIPTION_JS_HINTS": "Näytä tai piilota JavaScript-koodin vihjeet",
  "DESCRIPTION_JS_HINTS_TYPE_DETAILS": "Näytä tai piilota datatyyppien yksityiskohdat JavaScript-koodin vihjeissä",
  "DESCRIPTION_PREF_HINTS": "Näytä tai piilota asetusten koodin vihjeet",
  "DESCRIPTION_SPECIAL_CHAR_HINTS": "Näytä tai piilota HTML-entiteettien vihjeet",
  "DESCRIPTION_SVG_HINTS": "Näytä tai piilota SVG-koodin vihjeet",
  "DESCRIPTION_HTML_TAG_HINTS": "Näytä tai piilota HTML-tägien vihjeet",
  "DESCRIPTION_URL_CODE_HINTS": "Näytä tai piilota URL-vihjeet HTML- ja CSS/LESS/SCSS-tiedostoissa",
  "DESCRIPTION_DRAG_DROP_TEXT": "Ota vedä ja pudota -toiminto käyttöön tai poista se käytöstä",
  "DESCRIPTION_HEALTH_DATA_TRACKING": "Ota terveydentilan seuranta käyttöön",
  "DESCRIPTION_HIGHLIGHT_MATCHES": "Ottaa käyttöön vastaavien merkkijonojen automaattisen korostuksen koko dokumentissa",
  "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN": "Korosta kaikki merkkijonot, jotka vastaavat ilmausta, jossa kohdistin parhaillaan on (valintaa ei tarvita)",
  "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY": "Korosta vain, kun valinta on kokonainen ilmaus",
  "DESCRIPTION_INSERT_HINT_ON_TAB": "true: lisää parhaillaan valittu koodivihje, kun painetaan sarkainnäppäintä",
  "DESCRIPTION_NO_HINTS_ON_DOT": "true: älä näytä JS-koodivihjeitä automaattisesti, kun . kirjoitetaan",
  "DESCRIPTION_JSHINT_DISABLE": "true poistaaksesi JSHints-linterin käytöstä ongelmapaneelissa",
  "DESCRIPTION_ESLINT_DISABLE": "true poistaaksesi ESLint-linterin käytöstä ongelmapaneelissa",
  "DESCRIPTION_HTML_LINT_DISABLE": "true poistaaksesi HTML-linterin käytöstä ongelmapaneelissa",
  "DESCRIPTION_ESLINT_FAILED": "ESLint epäonnistui ({0}). Varmista, että projekti sisältää kelvollisia <a href='https://eslint.org/docs/latest/use/configure/configuration-files'>määritystiedostoja</a>",
  "DESCRIPTION_ESLINT_USE_NATIVE_APP": "ESLint on saatavilla vain Desktop-sovelluksessa. Lataa se osoitteesta <a href='https://phcode.io'>phcode.io</a>",
  "DESCRIPTION_ESLINT_LOAD_FAILED": "ESLintin lataaminen tälle projektille epäonnistui. {APP_NAME} tukee vain ESLint 7:ää uudempia versioita.",
  "DESCRIPTION_ESLINT_DO_NPM_INSTALL": "Suorita \"npm install\" projektissasi ottaaksesi ESLint käyttöön",
  "DESCRIPTION_LANGUAGE": "Kielikohtaiset asetukset",
  "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS": "Ylimääräiset liitokset tiedostopäätteestä kielen nimeen",
  "DESCRIPTION_LANGUAGE_FILE_NAMES": "Ylimääräiset liitokset tiedostonimestä kielen nimeen",
  "DESCRIPTION_LINEWISE_COPY_CUT": "Kopiointi ja leikkaaminen ilman valintaa kopioi tai leikkaa kokonaan rivit, joilla on kohdistin",
  "DESCRIPTION_INPUT_STYLE": "Valitsee, miten CodeMirror käsittelee syötteen ja kohdistuksen. Se voi olla textarea, joka on oletus, tai contenteditable, joka on parempi näytönlukijoille (mutta epävakaa)",
  "DESCRIPTION_LINTING_ENABLED": "true: ota koodin tarkistus käyttööön",
  "DESCRIPTION_ASYNC_TIMEOUT": "Aika, jonka jälkeen asynkroniset tarkistimet aikakatkaistaan, millisekunteina",
  "DESCRIPTION_LINTING_PREFER": "Taulukko tarkistimista, jotka suoritetaan ensin",
  "DESCRIPTION_LIVE_DEV_MULTIBROWSER": "true: ota kokeellinen esikatselu käyttöön",
  "DESCRIPTION_USE_PREFERED_ONLY": "true: suorita vain kohdassa linting.prefer eritellyt tarkistimet",
  "DESCRIPTION_MAX_CODE_HINTS": "Kerralla näytettävien koodivihjeiden enimmäismäärä",
  "DESCRIPTION_PATH": "Polkukohtaiset asetukset",
  "DESCRIPTION_PROXY": "URL välityspalvelimelle, jota käytetään laajennusten asentamiseen",
  "DESCRIPTION_SCROLL_PAST_END": "true: ota käyttöön vierittäminen pidemmälle kuin dokumentin loppuun",
  "DESCRIPTION_SHOW_CODE_HINTS": "false: poista kaikki koodivihjeet käytöstä",
  "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING": "Pitää vilkkuvan kohdistimen esillä, kun tekstiä on valittu",
  "DESCRIPTION_SHOW_LINE_NUMBERS": "true: näytä rivinumerot vasemman reunan marginaalissa",
  "DESCRIPTION_RULERS_COLUMNS": "Joukko sarakenumeroita pystysuuntaisten viivojen piirtämiseksi editorissa. Esim: [80, 100]",
  "DESCRIPTION_RULERS_COLORS": "Joukko viivainvärejä, jotka vastaavat editorin viivaimet-vaihtoehtoa. Esim: [\"#3d3d3d\", \"punainen\"]",
  "DESCRIPTION_RULERS_ENABLED": "tosi mahdollistaa editorin hallitsijat, muuten false",
  "DESCRIPTION_SMART_INDENT": "Sisennä automaattisesti, kun luodaan uusi lohko",
  "DESCRIPTION_SOFT_TABS": "false: poista pehmeät sarkaimet -toiminto käytöstä",
  "DESCRIPTION_SORT_DIRECTORIES_FIRST": "true: järjestä hakemistot ensin projektipuussa",
  "DESCRIPTION_SPACE_UNITS": "Väleihin perustuvassa sisennyksessä käytettävien välilyöntien määrä",
  "DESCRIPTION_STATIC_SERVER_PORT": "Portin numero, jota sisäänrakennetun palvelimen pitäisi käyttää esikatselussa",
  "DESCRIPTION_STYLE_ACTIVE_LINE": "true: korosta taustavärillä rivi, jossa kohdistin on",
  "DESCRIPTION_TAB_SIZE": "Näytettävien välilyöntien määrä sarkainmerkeissä",
  "DESCRIPTION_USE_TAB_CHAR": "true: käytä sarkainmerkkejä välilyöntien sijaan",
  "DESCRIPTION_UPPERCASE_COLORS": "true: luo suuraakkosin kirjoitettuja hex-värejä sisäisessä värieditorissa",
  "DESCRIPTION_WORD_WRAP": "Katkaise rivit, jotka ylittävät näyttöalueen leveyden",
  "DESCRIPTION_SEARCH_AUTOHIDE": "Sulje haku heti, kun editori on kohdistettu",
  "DESCRIPTION_DETECTED_EXCLUSIONS": "Luettelo tiedostoista, joiden on havaittu aiheuttavan sen, että Tern ajautuu pois hallinnasta",
  "DESCRIPTION_INFERENCE_TIMEOUT": "Aika, jonka jälkeen Tern aikakatkaistaan, sen yrittäessä ymmärtää tiedostoja",
  "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR": "true: näytä virheet tilapalkissa",
  "DESCRIPTION_QUICK_VIEW_ENABLED": "true: ota pikanäkymä käyttöön",
  "DESCRIPTION_SELECTION_VIEW_ENABLED": "true ottaaksesi valintanäkymän käyttöön",
  "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW": "true: näytä kuvien esikatselut päätteettömille URL-osoitteille",
  "DESCRIPTION_NUMBER_QUICK_VIEW": "tosi näyttääksesi Quick View'n viemällä hiiren editorissa numeroiden päälle",
  "DESCRIPTION_THEME": "Valitse {APP_NAME}in teema",
  "DESCRIPTION_USE_THEME_SCROLLBARS": "true: salli mukautetut vierityspalkit",
  "DESCRIPTION_LINTING_COLLAPSED": "true: pienennä tarkistuksen paneeli",
  "DESCRIPTION_FONT_FAMILY": "Vaihda fonttiperhettä",
  "DESCRIPTION_DESKTOP_ZOOM_SCALE": "Valitse zoomauskerroin välillä 0,1 (pienemmälle näkymälle) 2:een (suuremmalle ja suurennettulle näkymälle). Saatavilla vain työpöytäsovelluksissa",
  "DESCRIPTION_FONT_SIZE": "Vaihda fonttikokoa, esim. 13px",
  "DESCRIPTION_FIND_IN_FILES_NODE": "true: ota Node-pohjainen haku käyttöön",
  "DESCRIPTION_FIND_IN_FILES_INSTANT": "true: ota pikahaku käyttöön",
  "DESCRIPTION_FONT_SMOOTHING": "Vain Mac: ota käyttöön alipikselien reunapehmennys valinnalla ”subpixel-antialiased” tai harmaansävyinen reunapehmennys valinnalla ”antialiased”",
  "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW": "false: poista asetustiedoston avaaminen käytöstä jaetussa näkymässä",
  "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE": "false: avaa käyttäjän asetustiedosto vasemmassa tai ylemmässä ruudussa",
  "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED": "true: yhdistä ruudut sen jälkeen, kun ruudun viimeinen tiedosto on suljettu ruudun yläosassa olevalla sulkupaikkeella",
  "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS": "Valitse, milloin sulku- ja flip view -painikkeet näkyvät ruudun yläosassa",
  "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT": "/*\n * Tämä on vain luku -tiedosto, jonka asetuksia tuetaan\n * tekijältä {APP_NAME}.\n * Käytä tätä tiedostoa viitteenä asetusten muokkaamiseen\n * tiedosto \"phcode.json\" avattiin toisessa ruudussa.\n * Lisätietoja asetusten käyttämisestä sisällä\n * {APP_NAME}, katso verkkosivua osoitteessa https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences\n */",
  "DEFAULT_PREFERENCES_JSON_DEFAULT": "Oletus",
  "DESCRIPTION_PURE_CODING_SURFACE": "true: ota vain koodi -näkymä käyttöön ja piilota muut {APP_NAME}in käyttöliittymäelementit",
  "DESCRIPTION_INDENT_LINE_COMMENT": "true: ota rivikommenttien sisennys käyttöön",
  "DESCRIPTION_RECENT_FILES_NAV": "Ota viimeaikaisiin tiedostoihin siirtyminen käyttöön tai poista se käytöstä",
  "DESCRIPTION_LIVEDEV_WEBSOCKET_PORT": "WebSocket-palvelimen käyttämä portti esikatselua varten",
  "DESCRIPTION_LIVE_DEV_HIGHLIGHT_SETTINGS": "Esikatselun korostuksen asetukset",
  "DESCRIPTION_LIVEDEV_ENABLE_REVERSE_INSPECT": "false reaaliaikaisen esikatselun käänteisen tarkastuksen poistamiseksi käytöstä",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW": "Ei mitään esikatseltavaa!",
  "DESCRIPTION_LIVEDEV_EXCLUDED": "Mukautettu palvelin ei voi palvella tätä tiedostoa",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW_EXCLUDED": "Live-esikatseluasetukset on määritetty näyttämään vain kansion {0} tiedostoja",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW_DETAILS": "Valitse esikatselu HTML-tiedosto",
  "DESCRIPTION_LIVEDEV_PREVIEW_RESTRICTED": "Esikatselu ei saatavilla!",
  "DESCRIPTION_LIVEDEV_PREVIEW_RESTRICTED_DETAILS": "Tämä HTML-tiedosto ei ole osa nykyistä projektia. Turvallisuussyistä vain projektitiedostoja voidaan esikatsella livenä. Voit esikatsella tätä tiedostoa avaamalla sen sisältävän kansion erillisenä projektina.",
  "DESCRIPTION_LIVEDEV_MAIN_HEADING": "Voi ei!<br> Nykyinen selaimesi ei tue live-esikatselua.",
  "DESCRIPTION_LIVEDEV_MAIN_SPAN": "Saat parhaan live-esikatselukokemuksen lataamalla alkuperäiset sovelluksemme Windowsille, Macille ja Linuxille osoitteesta <a href=\"https://phcode.io\" style=\"color: white\">phcode.io</a> .<br>",
  "DESCRIPTION_LIVEDEV_SECURITY_POPOUT_MESSAGE": "Olet avaamassa tiedoston live-esikatselua varten. Jatka vain, jos luotat tämän projektin lähteeseen. Napsauta \"Trust Project\" jatkaaksesi tai sulje tämä ikkuna, jos et luota lähteeseen.",
  "DESCRIPTION_LIVEDEV_SECURITY_TRUST_MESSAGE": "Olet avaamassa tiedoston live-esikatselua varten. Jatka napsauttamalla \"Luota projektiin\" vain, jos luotat tämän projektin lähteeseen!",
  "CONFIRM_EXTERNAL_BROWSER_TITLE": "Ponnahdusikkunat estetty",
  "CONFIRM_EXTERNAL_BROWSER_MESSAGE": "Haluatko sallia live-esikatselusivun avata tämän URL-osoitteen: {0}?",
  "TRUST_PROJECT": "Luota ja suorita esikatselu – {0}",
  "TRUST_AUTHORS": "Luotatko tämän projektin tekijöihin?",
  "DOWNLOAD_FAILED": "Lataus epäonnistui.",
  "DOWNLOAD_COMPLETE": "Lataus valmis!",
  "UPDATE_SUCCESSFUL": "Päivitys onnistui!",
  "UPDATE_FAILED": "Päivitys epäonnistui!",
  "VALIDATION_FAILED": "Vahvistus epäonnistui!",
  "INITIALISATION_FAILED": "Alustus epäonnistui!",
  "CLEANUP_FAILED": "Puhdistus epäonnistui!",
  "WARNING_TYPE": "Varoitus!",
  "CLICK_RESTART_TO_UPDATE": "Napsauta Käynnistä uudelleen päivittääksesi Brackets.",
  "UPDATE_ON_NEXT_LAUNCH": "Päivitys otetaan käyttöön uudelleenkäynnistyksen yhteydessä.",
  "GO_TO_SITE": "Siirry osoitteeseen <a href = \"http://brackets.io/\">brackets.io</a> ja yritä uudelleen.",
  "INTERNET_UNAVAILABLE": "Internet-yhteyttä ei ole saatavilla.",
  "UPDATEDIR_READ_FAILED": "Päivityshakemistoa ei voitu lukea.",
  "UPDATEDIR_CLEAN_FAILED": "Päivityshakemistoa ei voitu puhdistaa.",
  "INITIAL_DOWNLOAD": "Ladataan päivitystä...",
  "RETRY_DOWNLOAD": "Lataus epäonnistui. Yritetään uudelleen...Yritetään",
  "VALIDATING_INSTALLER": "Lataus valmis! Vahvistetaan asennusohjelmaa...",
  "CHECKSUM_DID_NOT_MATCH": "Tarkistussumma ei täsmää.",
  "INSTALLER_NOT_FOUND": "Asennusohjelmaa ei löydy.",
  "DOWNLOAD_ERROR": "Latauksessa tapahtui virhe.",
  "NETWORK_SLOW_OR_DISCONNECTED": "Verkko on katkennut tai liian hidas.",
  "RESTART_BUTTON": "Uudelleenkäynnistää",
  "LATER_BUTTON": "Myöhemmin",
  "DESCRIPTION_AUTO_UPDATE": "Ota käyttöön tai poista käytöstä {APP_NAME} automaattinen päivitys",
  "AUTOUPDATE_ERROR": "Virhe!",
  "AUTOUPDATE_IN_PROGRESS": "Päivitys on jo käynnissä.",
  "NUMBER_WITH_PERCENTAGE": "{0} %",
  "CMD_FIND_RELATED_FILES": "Etsi aiheeseen liittyviä tiedostoja",
  "PHP_VERSION_INVALID": "Virhe jäsennettäessä PHP-versiota. Tarkista “php –version” -komennon tulos.",
  "PHP_UNSUPPORTED_VERSION": "Asenna PHP7 runtime ottaaksesi käyttöön PHP:hen liittyvät työkalut, kuten koodivihjeet, parametrivinkit, Jump to Definition ja paljon muuta. Löytyi versio: {0}",
  "PHP_EXECUTABLE_NOT_FOUND": "PHP-ajoaikaa ei löydy. Asenna PHP7 ajonaika ja päivitä PHP Preferencesissa \"executablePath\" asianmukaisesti. Tämä mahdollistaa PHP:hen liittyvät työkalut, kuten koodivihjeet, parametrivinkit, hyppy määritelmään ja paljon muuta.",
  "PHP_PROCESS_SPAWN_ERROR": "Virhekoodi {0} havaittiin PHP-prosessia käynnistettäessä.",
  "PHP_SERVER_ERROR_TITLE": "Virhe",
  "PHP_SERVER_MEMORY_LIMIT_INVALID": "Antamasi muistiraja on virheellinen. Tarkista PHP-asetukset asettaaksesi oikean arvon.",
  "DESCRIPTION_PHP_TOOLING_CONFIGURATION": "PHP Toolingin oletuskokoonpanoasetukset",
  "OPEN_PREFERENNCES": "Avaa Asetukset",
  "LANGUAGE_TOOLS_PREFERENCES": "Kielityökalujen asetukset",
  "FIND_ALL_REFERENCES": "Etsi kaikki referenssit",
  "REFERENCES_IN_FILES": "viittauksia",
  "REFERENCE_IN_FILES": "viite",
  "REFERENCES_NO_RESULTS": "Kohdistimen nykyiselle sijainnille ei ole saatavilla viitteitä",
  "CMD_FIND_DOCUMENT_SYMBOLS": "Etsi asiakirjasymbolit",
  "CMD_FIND_PROJECT_SYMBOLS": "Etsi projektin symbolit",
  "REMOTE_DEBUGGING_ENABLED": "Etävirheenkorjaus käytössä localhostissa:",
  "REMOTE_DEBUGGING_PORT_INVALID": "Etävirheenkorjausta ei voi ottaa käyttöön portissa {0}. Porttinumeroiden tulee olla välillä {1} - {2}.",
  "DESCRIPTION_EXTERNAL_APPLICATION_ASSOCIATE": "Ulkoisten sovellusten tiedostotunnisteiden yhdistäminen. Syntaksi: \"<tiedoston_tyyppi>\": \"<oletus|sovelluksennimi|ApplicationPath>\", Käytä \"oletus\" avataksesi tiedostot järjestelmän oletussovelluksessa kyseiselle tiedostotyypille.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_TITLE": "Avaa grafiikkatiedostot ulkoisissa muokkausohjelmissa.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_MSG": "Nykyisessä kansiossasi on grafiikkatiedostotyyppejä, joita {APP_NAME} ei tue.<br/> Voit nyt liittää tiettyjä tiedostotyyppejä ulkoisiin muokkausohjelmiin. Kun olet liitetty, voit avata graafisia tiedostoja, kuten .xd, .psd, .jpg, .png, .ai, .svg, oletussovelluksissa kaksoisnapsauttamalla tiedostoja tiedostopuussa.<br/><br/> Napsauta &#39;Ok&#39;-painiketta liittääksesi grafiikkatiedostotyypit vastaaviin oletussovelluksiin.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_CNF_MSG": "Seuraavat tiedostotyypit on yhdistetty onnistuneesti oletussovelluksiin.<br/> {0} Voit valita, haluatko poistaa/lisätäkö uusia tiedostotyyppiyhdistelmiä phcode.json-tiedostossa valitsemalla &quot;Debug-&gt;Open Preferences File&quot; -valikosta.",
  "UNSUPPORTED_BROWSER_TITLE": "Selainta ei tueta",
  "UNSUPPORTED_BROWSER_MESSAGE": "Käytä nykyaikaista selainta (julkaistu viimeisen 3 vuoden aikana).",
  "UNSUPPORTED_BROWSER_MOBILE_TITLE": "Mobiiliselaimia ei tueta",
  "UNSUPPORTED_BROWSER_MOBILE": "Mobiili- ja tablet-selaimia ei tällä hetkellä tueta täysin. Voit sulkea tämän valintaikkunan, mutta jotkin Phoenixin ominaisuudet eivät toimi tässä selaimessa.<br/><br/> Kehitämme natiivisovelluksia iOS:lle ja Androidille. <a href=\"https://github.com/phcode-dev/phoenix/discussions/1046\" target=\"_blank\">Liity keskusteluun tästä!</a>",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER_TITLE": "Selain ei tue paikallisen kansion käyttöä",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER": "Valitettavasti näyttää siltä, että nykyinen selaimesi ei tue paikallisten kansioiden avaamista. Tätä ominaisuutta varten suosittelemme Chromen, Edgen tai Operan käyttöä.<br/><br/> Vaihtoehtoisesti kehitämme natiivisovelluksia Windowsille, Macille, Linuxille, iOS:lle ja Androidille täyden tuen tarjoamiseksi. <a href=\"https://github.com/phcode-dev/phoenix/discussions/1047\" target=\"_blank\">Pysy kuulolla päivityksistä!</a>",
  "ATTENTION_SAFARI_USERS": "Huomio Safarin käyttäjät",
  "ATTENTION_SAFARI_USERS_MESSAGE": "<span>Safari poistaa verkkosivuston tiedot automaattisesti, jos sivustoa ei käytetä uudelleen 7 päivän kuluessa. {APP_NAME} käyttää selaimen tallennustilaa projektisi tallentamiseen, mikä saatetaan poistaa tämän käytännön vuoksi.<br/><br/> On suositeltavaa <strong>ladata macOS-työpöytäsovellus</strong> osoitteesta <a href='https://phcode.io' target='_blank' style='color: white'>https://phcode.io</a></span>",
  "CANNOT_PUBLISH_LARGE_PROJECT": "Suurta projektia ei voi julkaista",
  "CANNOT_PUBLISH_LARGE_PROJECT_MESSAGE": "Phoenix on edelleen kokeellisessa alfassa. Emme ole vielä ottaneet käyttöön yli 500 tiedostoa sisältävien projektien synkronointia.",
  "SHARE_WEBSITE": "Julkaise ja jaa verkkosivusto?",
  "PUBLISH": "Julkaista",
  "PUBLISH_CONSENT_MESSAGE": "Esikatsele muutoksia nopeasti ja jaa verkkosivustosi muiden kanssa. Phoenix voi julkaista tämän verkkosivuston puolestasi osoitteessa {0}. Julkaistut linkit ovat voimassa 30 päivää. </br>Haluatko julkaista ja jakaa verkkosivustosi?",
  "PUBLISH_SYNC_IN_PROGRESS": "Synkronointi käynnissä esikatselua varten...",
  "PUBLISH_PAGE": "Napsauta julkaistaksesi ja jakaaksesi tämän sivuston",
  "PUBLISH_VIEW_PAGE": "Napsauta nähdäksesi julkaistun sivun",
  "MISSING_FIELDS": "Puuttuvat kentät",
  "PLEASE_FILL_ALL_REQUIRED": "Täytä kaikki vaaditut punaisella korostetut kentät",
  "CODE_EDITOR": "Koodieditori",
  "BUILD_THE_WEB": "Rakenna verkko",
  "IMPORT_PROJECT": "Tuo projekti",
  "GITHUB_PROJECT": "GitHub-projekti",
  "NEW_PROJECT_FROM_GITHUB": "Uusi projekti GitHubilta",
  "GITHUB_REPO_URL": "GitHub Repon URL-osoite:",
  "START_PROJECT": "Aloita projekti…",
  "DOWNLOAD_DESKTOP_APP": "Lataa työpöytäsovellus",
  "GET_DESKTOP_APP": "Hanki työpöytäsovellus",
  "CREATE_PROJECT": "Luo projekti",
  "SETTING_UP_PROJECT": "Projektin perustaminen",
  "LOCATION": "Sijainti:",
  "DOWNLOADING": "Ladataan...",
  "DOWNLOADING_FILE": "Ladataan {0}...",
  "EXTRACTING_FILES_PROGRESS": "Puretaan {0}/{1} tiedostoa.",
  "COMPRESS_FILES_PROGRESS": "Pakkaaminen {0}/{1} tiedostoa.",
  "DOWNLOAD_FAILED_MESSAGE": "Varmista, että lataus-URL-osoite on kelvollinen. </br>Huom. Koska Phoenix on alfa-tilassa, yli 25 Mt:n yksityiset repot ja GitHub-URL-osoitteet eivät ole sallittuja.",
  "PLEASE_SELECT_A_FOLDER": "Valitse kansio...",
  "UNZIP_IN_PROGRESS": "Puretaan tiedostoja...",
  "UNZIP_FAILED": "Virhe: Purkaminen epäonnistui.",
  "CONFIRM_REPLACE_TITLE": "Vahvista Vaihda",
  "KEEP_BOTH": "Pidä molemmat",
  "EXPLORE": "HTML pelit",
  "BLOG": "Blogi",
  "PHOENIX_DEFAULT_PROJECT": "Oletusprojekti",
  "PROJECT_NAME": "Projektin nimi:",
  "NEW_HTML": "Uusi HTML-projekti",
  "LICENSE": "Lisenssi ja luottotiedot:",
  "PREVIEW": "Esikatselu",
  "BUILD_WEBSITE": "Rakenna verkkosivusto",
  "VIEW_MORE": "Katso lisää...",
  "NEW_PROJECT_NOTIFICATION": "Napsauta tätä kuvaketta avataksesi &quot;Uusi projekti&quot; -ikkunan uudelleen.</br> Katso Viimeaikaiset projektit, Avaa kansio tai aloita projekteja malleista.</br><img src=\"styles/images/new_project.png\"><br/> <a href='#' style='float:right;'>okei</a>",
  "BEAUTIFY_CODE_NOTIFICATION": "Napsauta tätä tai paina <b>`{0}`</b> kaunistaaksesi koodia.</br><img src=\"styles/images/beautify.gif\"><br/> <a href='#' style='float:right;'>okei</a>",
  "DEFAULT_PROJECT_NOTIFICATION": "Napsauta tästä avataksesi<br/> <b>oletusprojekti</b> phoenixissa.</br> <a href='#' style='float:right;'>okei</a>",
  "DIRECTORY_REPLACE_MESSAGE": "Valittu kansio <span class='dialog-filename'>{0}</span> ei ole tyhjä. Haluatko varmasti korvata kansion sisällön projektilla?",
  "DEFAULT_PROJECT_HTML_CLICK_HERE": "Napsauta tätä löytääksesi tämän &lt;span&gt; HTML-tiedostossa",
  "BUILD_WEBSITE_SECTION": "Rakenna verkkosivusto",
  "LEARN_SECTION": "Opi esimerkkien avulla",
  "CREATE_EXTENSION_SECTION": "Luo sovelluksen {APP_NAME} laajennuksia ja teemoja",
  "CREATE_EXTENSION": "Luo laajennus",
  "CREATE_THEME": "Luo teema",
  "WEBPAGE_HOME_PAGE": "Kotisivu",
  "WEBPAGE_BLOG": "Blogisivu",
  "WEBPAGE_DASHBOARD": "HTML-hallintapaneeli",
  "WEBPAGE_BOOTSTRAP_EXAMPLES": "Bootstrap esimerkkejä",
  "PROJECTS_AT_A_GLANCE": "Projektisi yhdellä silmäyksellä",
  "PROJECT_AT_GLANCE_DESCRIPTION": "Aloita katsomalla video.",
  "PROJECT_FROM_BROWSER": "Tallennettu selaimeesi",
  "PROJECT_FROM_BROWSER_TERSE": "Selaimen tallennustila",
  "PROJECT_SHOW_ON_STARTUP": "Näytä tämä dialogi käynnistyksen yhteydessä",
  "GUIDED_LIVE_PREVIEW": "Tee joitain koodimuutoksia HTML-tiedostoon nähdäksesi live-esikatselun.</br> <a href='#' style='float:right;'>okei</a>",
  "GUIDED_LIVE_PREVIEW_POPOUT": "Napsauta tätä painiketta avataksesi esikatselun uudelle välilehdelle.</br> <a href='#' style='float:right;'>okei</a>",
  "ENJOYING_APP": "Pidätkö sovelluksesta {APP_NAME}?",
  "GITHUB_STARS_POPUP": "<div>Tukesi auttaa pientä tiimiämme, joka on motivoitunut tekemään <b style='color: darkblue'>phcode.devistä</b> entistä paremman.<br/> Merkitse meidät tähdellä tai harkitse meidän sponsorointia GitHubissa:",
  "GITHUB_STARS_POPUP_TWITTER": "Anna palautetta tai levitä sanaa Twitterissä:",
  "TEST_TRANSLATE": "käytä tätä käännösten testaamiseen",
  "BEAUTIFY_ERROR": "Koodia ei voitu kaunistaa. Tarkista syntaksi.",
  "BEAUTIFY_ERROR_ORIGINAL_CHANGED": "Ei voinut kaunistaa. Editorin tekstiä on muutettu kaunistamisen jälkeen.",
  "BEAUTIFY_PROJECT_BUSY_MESSAGE": "Kaunistava tiedosto {0}",
  "BEAUTIFY_ERROR_SELECTION": "Ei voitu kaunistaa.</br>Epätäydellinen koodilohko valittu tai virheellinen syntaksi.",
  "BEAUTIFY_OPTIONS": "Vaihtoehdot, jotka ohjaavat Beautify Coden toimintaa",
  "BEAUTIFY_OPTION_PRINT_WIDTH": "Määritä viivan pituus, johon kaunistaja käärii",
  "BEAUTIFY_OPTION_SEMICOLON": "Lisää puolipiste jokaisen lauseen loppuun",
  "BEAUTIFY_OPTION_SINGLE_QUOTE": "Käytä lainausmerkkejä kaksoislainausmerkkien sijaan",
  "BEAUTIFY_OPTION_QUOTE_PROPS": "Muuta, kun objektien ominaisuudet lainataan",
  "BEAUTIFY_OPTION_BRACKET_SAME_LINE": "Lisää monirivisen HTML-elementin (HTML, JSX, Vue, Angular) > viimeisen rivin loppuun sen sijaan, että olisit yksin seuraavalla rivillä (ei koske itsestään sulkeutuvia elementtejä)",
  "BEAUTIFY_OPTION_SINGLE_ATTRIBUTE_PER_LINE": "Pakota yksi attribuutti riviä kohden HTML-, Vue- ja JSX-kielissä",
  "BEAUTIFY_OPTION_PROSE_WRAP": "Kääri proosa, jos se ylittää painoleveyden merkintätiedostoissa",
  "BEAUTIFY_OPTION_PRINT_TRAILING_COMMAS": "Tulosta loppupilkut aina kun mahdollista monirivisissä pilkuilla erotetuissa syntaktisissa rakenteissa"
});