/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "システムのデフォルト",
  "PROJECT_BUSY": "進行中のプロジェクト オペレーション",
  "DUPLICATING": "{0} を複製しています",
  "MOVING": "{0}を移動中",
  "COPYING": "{0}をコピーしています",
  "DELETING": "{0}を削除しています",
  "DELETE_TO_TRASH": "{0} をゴミ箱に移動しています",
  "DELETE_TO_RECYCLE_BIN": "{0} をごみ箱に移動しています",
  "RENAMING": "名前の変更",
  "STORED_IN_YOUR_BROWSER": "ブラウザに保存",
  "SUPPORT_US_OPEN_COLLECTIVE": "GitHubスポンサーでサポートしてください",
  "GENERIC_ERROR": "(エラー {0})",
  "NOT_FOUND_ERR": "ファイルまたはディレクトリが見つかりません。",
  "NOT_READABLE_ERR": "ファイルまたはディレクトリを読み込めませんでした。",
  "EXCEEDS_MAX_FILE_SIZE": "{0} MB を超えるサイズのファイルは {APP_NAME} で開くことはできません。",
  "NO_MODIFICATION_ALLOWED_ERR": "対象ディレクトリは変更できません。",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "ファイルを変更する権限がありません。",
  "CONTENTS_MODIFIED_ERR": "このファイルは {APP_NAME} 以外で変更されています。",
  "UNSUPPORTED_ENCODING_ERR": "不明なエンコード形式",
  "ENCODE_FILE_FAILED_ERR": "{APP_NAME} でファイルの内容をエンコードすることができませんでした。",
  "DECODE_FILE_FAILED_ERR": "{APP_NAME} でファイルの内容をデコードすることができませんでした。",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "{APP_NAME} は現在 UTF-16 でエンコードされたテキストファイルに対応していません。",
  "FILE_EXISTS_ERR": "ファイルまたはディレクトリは既に存在しています。",
  "FILE": "ファイル",
  "FILE_TITLE": "ファイル",
  "DIRECTORY": "ディレクトリ",
  "DIRECTORY_TITLE": "ディレクトリ",
  "DIRECTORY_NAMES_LEDE": "ディレクトリ名",
  "FILENAMES_LEDE": "ファイル名",
  "FILENAME": "ファイル名",
  "DIRECTORY_NAME": "ディレクトリ名",
  "ERROR_LOADING_PROJECT": "プロジェクトを読み込む際にエラーが発生しました。",
  "OPEN_DIALOG_ERROR": "「ファイルを開く」ダイアログを表示する際にエラーが発生しました。(エラー {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "ディレクトリ <span class='dialog-filename'>{0}</span> を読み込む際にエラーが発生しました。(エラー {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "ディレクトリ <span class='dialog-filename'>{0}</span> の内容を読み込む際にエラーが発生しました。(エラー {1})",
  "ZOOM_WITH_SHORTCUTS": "キーボード ショートカットを使用してズームする",
  "ZOOM_WITH_SHORTCUTS_DETAILS": "ズームインするにはキーボード ショートカット<code><i>{0}</i></code> 、ズームアウトするには<code><i>{1}</i></code>を使用してください。",
  "ERROR_OPENING_FILE_TITLE": "ファイルを開く際にエラーが発生しました。",
  "ERROR_OPENING_FILE": "ファイル <span class='dialog-filename'>{0}</span> を開く際にエラーが発生しました。{1}",
  "ERROR_OPENING_FILES": "次のファイルを開くときにエラーが発生しました :",
  "ERROR_RELOADING_FILE_TITLE": "ディスクから変更を再読み込みする際にエラーが発生しました。",
  "ERROR_RELOADING_FILE": "ファイル <span class='dialog-filename'>{0}</span> を再読込する際にエラーが発生しました。{1}",
  "ERROR_SAVING_FILE_TITLE": "ファイルを保存する際にエラーが発生しました。",
  "ERROR_SAVING_FILE": "ファイル <span class='dialog-filename'>{0}</span> を保存する際にエラーが発生しました。{1}",
  "ERROR_RENAMING_FILE_TITLE": "{0} の名前を変更する際にエラーが発生しました。",
  "ERROR_RENAMING_FILE": "{2} <span class='dialog-filename'>{0}</span> の名前を変更する際にエラーが発生しました。{1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "ファイルまたはディレクトリが、現在開いているプロジェクトの一部ではありません。現時点で、プロジェクトファイルの名前のみを変更できます。",
  "ERROR_MOVING_FILE_TITLE": "{0}の移動エラー",
  "ERROR_MOVING_FILE": "{2} <span class='dialog-filename'>{0}</span> を移動する際にエラーが発生しました。{1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "現在のプロジェクトに含まれないため、ファイル/フォルダーを移動することはできません。",
  "ERROR_DELETING_FILE_TITLE": "{0} を削除する際にエラーが発生しました。",
  "ERROR_DELETING_FILE": "{2} <span class='dialog-filename'>{0}</span> を削除する際にエラーが発生しました。{1}",
  "INVALID_FILENAME_TITLE": "無効な{0}",
  "CANNOT_PASTE_TITLE": "{0} を貼り付けできません",
  "CANNOT_DOWNLOAD_TITLE": "{0} をダウンロードできません",
  "ERR_TYPE_DOWNLOAD_FAILED": "<span class='dialog-filename'>{0}</span>のダウンロード中にエラーが発生しました",
  "ERR_TYPE_PASTE_FAILED": "<span class='dialog-filename'>{0}</span>を<span class='dialog-filename'>{1}</span>に貼り付け中にエラーが発生しました",
  "CANNOT_DUPLICATE_TITLE": "複製できません",
  "ERR_TYPE_DUPLICATE_FAILED": "<span class='dialog-filename'>{0}</span>の複製中にエラーが発生しました",
  "ERR_TYPE_DUPLICATE_FAILED_NO_FILE": "複製するファイルを選択してください。",
  "INVALID_FILENAME_MESSAGE": "{0}にはシステムのすべての予約語、末尾のピリオド (.)、および次の文字を含めることはできません : <code class='emphasized'>{1}</code>",
  "ENTRY_WITH_SAME_NAME_EXISTS": "<span class='dialog-filename'>{0}</span> という名前のファイルまたはディレクトリは既に存在します。",
  "ERROR_CREATING_FILE_TITLE": "{0} を作成する際にエラーが発生しました。",
  "ERROR_CREATING_FILE": "{0} <span class='dialog-filename'>{1}</span> を作成する際にエラーが発生しました。{2}",
  "ERROR_MIXED_DRAGDROP": "他のファイルを開いている間はフォルダーを開くことはできません。",
  "ERROR_KEYMAP_TITLE": "ユーザーキーマップを読み込む際にエラーが発生しました",
  "ERROR_KEYMAP_CORRUPT": "キーマップファイルが有効な JSON ではありません。ファイルが開かれます。フォーマットを修正してください。",
  "ERROR_LOADING_KEYMAP": "キーマップファイルが UTF-8 でエンコードされた有効なテキストファイルではないため、読み込めません",
  "ERROR_RESTRICTED_COMMANDS": "次のコマンドにショートカットを割り当て直すことはできません : {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "次のショートカットを割り当て直すことはできません : {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "次のコマンドに複数のショートカットを割り当て直しています : {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "次のショートカットの複数のバインディングがあります : {0}",
  "ERROR_INVALID_SHORTCUTS": "次のショートカットは無効です : {0}",
  "ERROR_NONEXISTENT_COMMANDS": "存在しないコマンドにショートカットを割り当てています : {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "環境設定を読み込む際にエラーが発生しました。",
  "ERROR_PREFS_PROJECT_LINT": "プロジェクトの設定",
  "ERROR_PREFS_PROJECT_LINT_MESSAGE": "エラー: プロジェクトには `.brackets.json` と `.phcode.json` ファイルの両方が含まれているため、競合が発生します。 `.brackets.json` または `.phcode.json` を削除して、プロジェクトを再読み込みしてください。",
  "ERROR_PREFS_CORRUPT": "環境設定ファイルが有効な JSON ではありません。ファイルが開かれます。フォーマットを修正してください。変更を反映するには、{APP_NAME} を再起動する必要があります。",
  "ERROR_PROJ_PREFS_CORRUPT": "プロジェクトの環境設定ファイルが有効な JSON ではありません。ファイルが開かれます。フォーマットを修正してください。変更を反映するには、プロジェクトを再読み込みする必要があります。",
  "ERROR_IN_BROWSER_TITLE": "{APP_NAME} は、まだブラウザー上で実行されていません。",
  "ERROR_IN_BROWSER": "{APP_NAME} は HTML で構築されていますが、デスクトップアプリとして実行することで、ローカルファイルを編集することができます。{APP_NAME} を実行するために、<b>github.com/adobe/brackets-shell</b> リポジトリのアプリケーションシェルを使用してください。",
  "ERROR_MAX_FILES_TITLE": "ファイルのインデックス時にエラーが発生しました。",
  "ERROR_MAX_FILES": "このプロジェクトには 30,000 個以上のファイルが含まれています。複数のファイルを操作する機能が無効になるか、プロジェクトが空であるかのように動作します。<a href='https://github.com/adobe/brackets/wiki/Large-Projects'>大きいプロジェクトの操作方法の詳細を表示</a>。",
  "ERROR_LAUNCHING_BROWSER_TITLE": "ブラウザーの起動時にエラーが発生しました。",
  "ERROR_CANT_FIND_CHROME": "Google Chrome ブラウザーが見つかりません。インストールされていることを確認してください。",
  "ERROR_LAUNCHING_BROWSER": "ブラウザーの起動時にエラーが発生しました。(エラー {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "ライブプレビューのエラーが発生しました。",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "ブラウザーに接続しています",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "ライブプレビューに接続するには、リモートデバッグを有効にして Chrome を再起動する必要があります。<br /><br />Chrome を再起動してリモートデバッグを有効にしますか？<br /><br />",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "ライブプレビューページを読み込めません。",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "サーバー側ファイルでライブプレビューを起動するには、このプロジェクトのベース URL を指定する必要があります。",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "ファイルのライブプレビューで使用する HTTP サーバーの起動時にエラーが発生しました。もう一度実行してください。",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "詳しくは、<a href='{0}' title='{0}'>ライブプレビューの接続エラーに関するトラブルシューティング</a>を参照してください。",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "ライブプレビュー",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "ライブプレビュー : 接続中…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "ライブプレビュー : 初期化中…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "ライブ プレビュー サーバーがアクティブです",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "ライブプレビュー",
  "LIVE_DEV_TOOLTIP_SHOW_IN_EDITOR": "{0} - エディターで表示…",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "プレビューするファイルを選択",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "ページのリロード",
  "LIVE_DEV_TOGGLE_LIVE_HIGHLIGHT": "ライブ プレビュー ハイライトの切り替え",
  "LIVE_DEV_CLICK_POPOUT": "ライブプレビューを新しいウィンドウにポップアウト",
  "LIVE_DEV_OPEN_CHROME": "Chrome で開く…",
  "LIVE_DEV_OPEN_SAFARI": "Safariで開く…",
  "LIVE_DEV_OPEN_EDGE": "エッジで開く…",
  "LIVE_DEV_OPEN_FIREFOX": "Firefox で開く…",
  "LIVE_DEV_OPEN_ERROR_TITLE": "{0} でライブ プレビューを開くときにエラーが発生しました",
  "LIVE_DEV_OPEN_ERROR_MESSAGE": "{0} ブラウザがインストールされていることを確認して、もう一度お試しください。",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "プレビューページをピン留めまたはピン留め解除する",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "ライブプレビュー (シンタックスエラーのため更新されません)",
  "LIVE_DEV_SETTINGS": "ライブプレビュー設定…",
  "LIVE_DEV_SETTINGS_BANNER": "PHP、JSP、その他のサーバーレンダリングファイルをライブプレビューするためのカスタムサーバーをセットアップする",
  "LIVE_DEV_SETTINGS_TITLE": "ライブプレビュー設定",
  "LIVE_DEV_SETTINGS_STARTUP": "起動時にライブプレビューパネルを表示する",
  "LIVE_DEV_SETTINGS_SERVER_PREFERENCE": "カスタム開発サーバーを有効にするにはtrue",
  "LIVE_DEV_SETTINGS_STARTUP_PREFERENCE": "起動時にライブプレビューパネルを表示するにはtrue",
  "LIVE_DEV_SETTINGS_HOT_RELOAD_PREFERENCE": "サーバーがホットリロードをサポートし、保存時にライブプレビューのリロードを無効にする場合は true",
  "LIVE_DEV_SETTINGS_USE_SERVER": "このプロジェクトにはカスタム開発サーバーを使用する",
  "LIVE_DEV_SETTINGS_SERVE_PREFERENCE": "プロジェクトの開発サーバー URL (例: http://localhost:8000/php)",
  "LIVE_DEV_SETTINGS_SERVER_INBUILT": "例: http://localhost:8000/php - 現在、組み込みサーバーを使用しています。",
  "LIVE_DEV_SETTINGS_SERVER_ROOT": "プロジェクト内のフォルダの提供",
  "LIVE_DEV_SETTINGS_SERVER_ROOT_HELP": "例: www/ (デフォルトは /)",
  "LIVE_DEV_SETTINGS_SERVER_ROOT_PREF": "開発サーバーによって提供されるプロジェクト内のパス (例: www/ (デフォルトは /))",
  "LIVE_DEV_SETTINGS_RELOAD": "サーバーはホットリロードをサポート",
  "LIVE_DEV_SETTINGS_RELOAD_HELP": "一部のサーバーでは、ページ全体をリロードせずにコードの変更をページにプッシュするホット リロードがサポートされています。\n{APP_NAME} が保存するたびにページをリロードしないようにするには、この機能を有効にします。",
  "LIVE_DEV_SETTINGS_FRAMEWORK": "サーバーフレームワーク",
  "LIVE_DEV_SETTINGS_FRAMEWORK_CUSTOM": "カスタム",
  "LIVE_DEV_SETTINGS_FRAMEWORK_PREFERENCES": "サーバーフレームワーク、現在はdocusaurusのみをサポート",
  "LIVE_PREVIEW_CUSTOM_SERVER_BANNER": "カスタム サーバー {0} からプレビューを取得しています",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "ブラウザーの開発ツールが開いているため、ライブプレビューはキャンセルされました",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "ブラウザーでページが閉じられたため、ライブプレビューはキャンセルされました",
  "LIVE_DEV_NAVIGATED_AWAY": "ブラウザーで現在のプロジェクトに含まれないページに移動したため、ライブプレビューはキャンセルされました",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "不明な原因 ({0}) によってライブプレビューはキャンセルされました",
  "SAVE_CLOSE_TITLE": "変更を保存",
  "SAVE_CLOSE_MESSAGE": "文書 <span class='dialog-filename'>{0}</span> に加えた変更を保存しますか？",
  "SAVE_CLOSE_MULTI_MESSAGE": "以下のファイルに対する変更を保存しますか？",
  "EXT_MODIFIED_TITLE": "外部で変更されました。",
  "CONFIRM_DELETE_TITLE": "削除を確認",
  "CONFIRM_FILE_DELETE": "ファイル <span class='dialog-filename'>{0}</span> を削除してもよろしいですか？",
  "CONFIRM_FOLDER_DELETE": "<span class='dialog-filename'>{0}</span> フォルダーを削除してもよろしいですか？",
  "CONFIRM_FILE_DELETE_TRASH": "ファイル<span class='dialog-filename'>{0}</span>を削除してもよろしいですか?<br>このファイルはゴミ箱から復元できます。",
  "CONFIRM_FOLDER_DELETE_TRASH": "フォルダー<span class='dialog-filename'>{0}</span>を削除してもよろしいですか?<br>このフォルダはゴミ箱から復元できます。",
  "CONFIRM_FILE_DELETE_RECYCLE_BIN": "ファイル<span class='dialog-filename'>{0}</span>を削除してもよろしいですか?<br>このファイルはごみ箱から復元できます。",
  "CONFIRM_FOLDER_DELETE_RECYCLE_BIN": "フォルダー<span class='dialog-filename'>{0}</span>を削除してもよろしいですか?<br>このフォルダはごみ箱から復元できます。",
  "MOVE_TO_TRASH": "ゴミ箱に移動",
  "MOVE_TO_RECYCLE_BIN": "ごみ箱に移動",
  "FILE_DELETED_TITLE": "ファイルは削除されました",
  "EXT_MODIFIED_WARNING": "<span class='dialog-filename'>{0}</span> は {APP_NAME} 外のディスク上で変更されています。<br /><br />ファイルを保存し、これらの変更を上書きしますか？",
  "EXT_MODIFIED_MESSAGE": "<span class='dialog-filename'>{0}</span> は {APP_NAME} 外のディスク上で変更されていますが、{APP_NAME} 内にも保存されていない変更があります。<br /><br />どちらのバージョンを保持しますか？",
  "EXT_DELETED_MESSAGE": "<span class='dialog-filename'>{0}</span> は {APP_NAME} 外のディスク上で削除されていますが、{APP_NAME} 内に保存されていない変更があります。<br /><br />変更を保持しますか？",
  "EXT_ALWAYS_MODIFIED_BUTTON_TOOLTIP": "プロジェクトが切り替わるか再起動されるまで、常にファイルを上書きします",
  "WINDOW_UNLOAD_WARNING": "別の URL に移動して {APP_NAME} を離れてもよろしいですか?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "未保存の変更があります。別の URL に移動して {APP_NAME} を離れてもよろしいですか?",
  "DONE": "完了",
  "OK": "OK",
  "CANCEL": "キャンセル",
  "DONT_SAVE": "保存しない",
  "SAVE": "保存",
  "SAVE_AS": "名前を付けて保存…",
  "SAVE_AND_OVERWRITE": "上書き",
  "ALWAYS_OVERWRITE": "常に上書き",
  "DELETE": "削除",
  "BUTTON_YES": "はい",
  "BUTTON_NO": "いいえ",
  "FIND_MATCH_INDEX": "{0} / {1}",
  "FIND_NO_RESULTS": "該当なし",
  "FIND_QUERY_PLACEHOLDER": "検索…",
  "FIND_HISTORY_MAX_COUNT": "検索履歴内の検索項目の最大数",
  "REPLACE_PLACEHOLDER": " に置換…",
  "BUTTON_REPLACE_ALL": "すべて置換",
  "BUTTON_REPLACE_BATCH": "バッチ…",
  "BUTTON_REPLACE_ALL_IN_FILES": "置換…",
  "BUTTON_REPLACE": "置換",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "次の候補に移動",
  "BUTTON_PREV_HINT": "前の候補に移動",
  "BUTTON_CASESENSITIVE_HINT": "大文字と小文字を区別",
  "BUTTON_REGEXP_HINT": "正規表現",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "取り消し情報を保存せずに置換",
  "REPLACE_WITHOUT_UNDO_WARNING": "{0} 個を超えるファイルを変更する必要があるため、{APP_NAME} によってディスク上の開かれていないファイルが変更されます。<br />これらのファイルで行った置換は取り消しできません。",
  "BUTTON_REPLACE_WITHOUT_UNDO": "取り消し情報を保存せずに置換",
  "OPEN_FILE": "ファイルを開く",
  "SAVE_FILE_AS": "ファイルを保存",
  "CHOOSE_FOLDER": "フォルダーを選択",
  "RELEASE_NOTES": "リリースノート",
  "NO_UPDATE_TITLE": "最新バージョンです。",
  "NO_UPDATE_MESSAGE": "{APP_NAME} の最新バージョンを実行中です。",
  "FIND_REPLACE_TITLE_LABEL": "置換",
  "FIND_REPLACE_TITLE_WITH": "置換後の文字列",
  "FIND_TITLE_LABEL": "検索結果",
  "FIND_TITLE_SUMMARY": "&mdash; {0} {1} {2} ({3})",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "<span class='dialog-filename'>{0}</span> 内",
  "FIND_IN_FILES_NO_SCOPE": "プロジェクト内",
  "FIND_IN_FILES_PROJECT_SCOPE": "プロジェクト内で検索",
  "FIND_IN_FILES_PROJECT_SCOPE_FILTER": "{0} で検索",
  "FIND_IN_FILES_PROJECT_SCOPE_REPLACE": "プロジェクト内で置換",
  "FIND_IN_FILES_PROJECT_SCOPE_REPLACE_FILTER": "{0} で置換",
  "FIND_IN_FILES_ZERO_FILES": "フィルターは {0}の全ファイルを除外します",
  "FIND_IN_FILES_FILE": "ファイル",
  "FIND_IN_FILES_FILES": "ファイル",
  "FIND_IN_FILES_MATCH": "が見つかりました",
  "FIND_IN_FILES_MATCHES": "件見つかりました",
  "FIND_IN_FILES_MORE_THAN": "以上",
  "FIND_IN_FILES_PAGING": "{0}&mdash;{1}",
  "FIND_IN_FILES_FILE_PATH": "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "Ctrl / Command キーをクリックしてすべて展開 / 折りたたみ",
  "FIND_IN_FILES_INDEXING": "クイック検索のインデックスを作成中…",
  "FIND_IN_FILES_SEARCHING": "ファイルを検索中…",
  "FIND_IN_FILES_SEARCHING_IN": "{0} に",
  "FIND_IN_FILES_INDEXING_PROGRESS": "クイック検索用に {1} ファイル中 {0} のインデックスを作成しています…",
  "REPLACE_IN_FILES_ERRORS_TITLE": "置換エラー",
  "REPLACE_IN_FILES_ERRORS": "次のファイルは検索の後で変更されているか、書き込むことができないため、変更されていません。",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "更新情報を取得する際にエラーが発生しました。",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "サーバーから最新の更新情報を取得する際にエラーが発生しました。インターネット接続を確認してリトライしてください。",
  "NEW_FILE_FILTER": "新規除外セット…",
  "CLEAR_FILE_FILTER": "ファイルを除外しない",
  "NO_FILE_FILTER": "除外されたファイルはありません",
  "EXCLUDE_FILE_FILTER": "ファイルを除外する",
  "INCLUDE_FILE_FILTER": "ファイル内を検索する",
  "FILTER_PLACEHOLDER": "例えばインデックス、.css、*.js、src/**/*.css",
  "FILTER_HISTORY_TOOLTIP": "`Ctrl-Space`を押して履歴を表示します。",
  "FILTER_HISTORY_TOOLTIP_MAC": "`Cmd-Space`を押して履歴を表示します。",
  "FIND_HISTORY_TOOLTIP": "`Ctrl-Space`を押して履歴を表示します。",
  "FIND_HISTORY_TOOLTIP_MAC": "`Cmd-Space`を押して履歴を表示します。",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "現在のカーソル位置で行えるクイック編集はありません",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "CSS クイック編集 : カーソルを単一のクラス名に置いてください",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "CSS クイック編集 : 不完全なクラス属性",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "CSS クイック編集 : 不完全な ID 属性",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "CSS クイック編集 : カーソルをタグ、クラスまたは ID に置いてください",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "CSS タイミング機能のクイック編集 : 無効なシンタックス",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "JS クイック編集 : カーソルを関数名に置いてください",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "現在のカーソル位置で使用できるクイックドキュメントはありません",
  "PROJECT_LOADING": "読み込んでいます…",
  "UNTITLED": "名称未設定",
  "WORKING_FILES": "作業中ファイル",
  "TOP": "上",
  "BOTTOM": "下",
  "LEFT": "左",
  "RIGHT": "右",
  "CMD_SPLITVIEW_NONE": "分割なし",
  "CMD_SPLITVIEW_VERTICAL": "左右分割",
  "CMD_SPLITVIEW_HORIZONTAL": "上下分割",
  "SPLITVIEW_MENU_TOOLTIP": "エディターを垂直方向 / 水平方向に分割",
  "GEAR_MENU_TOOLTIP": "ワーキングセットを構成",
  "SPLITVIEW_INFO_TITLE": "既に開かれています",
  "SPLITVIEW_MULTIPANE_WARNING": "ファイルは他のペインで既に開かれています。{APP_NAME} ではまもなく複数のペインで同じファイルを開くことが可能になる予定です。それまでは、ファイルは既に開かれているペインで表示されます。<br /><br />(このメッセージは一度しか表示されません。)",
  "KEYBOARD_OVERLAY_TEXT": "矢印を使用して移動するか、入力して UI 要素を選択します。",
  "KEYBOARD_SHORTCUT_CHANGE_TITLE": "キーボード ショートカットを変更…",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_TITLE": "キーボードショートカットの変更",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_TEXT": "<b>「{0}」</b>の新しいキーの組み合わせを押してください (現在: <b>{1}</b> )",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_DUPLICATE": "警告: キーの組み合わせ<b>{0}</b>はすでに<b>&#39;{1}&#39;</b>に割り当てられています。 <b>&#39;{2}&#39;</b>に再割り当てしますか?",
  "KEYBOARD_SHORTCUT_ASSIGN": "割当",
  "KEYBOARD_SHORTCUT_NONE": "なし",
  "KEYBOARD_SHORTCUT_MENU_SHOW_SHORTCUTS": "キーボードショートカット…",
  "KEYBOARD_SHORTCUT_MENU_SHOW_SHORTCUTS_BUTTON": "すべてのショートカットを表示…",
  "KEYBOARD_SHORTCUT_TABLE_BASE_KEY": "ベースキー",
  "KEYBOARD_SHORTCUT_TABLE_KEY_BINDING": "ショートカット",
  "KEYBOARD_SHORTCUT_TABLE_COMMAND_ID": "コマンドID",
  "KEYBOARD_SHORTCUT_TABLE_COMMAND_NAME": "指示",
  "KEYBOARD_SHORTCUT_TABLE_DOUBLE_CLICK": "ダブルクリックしてショートカットを変更します",
  "KEYBOARD_SHORTCUT_TABLE_ORIGIN": "起源",
  "KEYBOARD_SHORTCUT_ORIG_EXTENSION": "拡大",
  "KEYBOARD_SHORTCUT_PANEL_TITLE": "キーボードショートカット",
  "KEYBOARD_SHORTCUT_PANEL_FILTER": "フィルター&hellip;",
  "KEYBOARD_SHORTCUT_PANEL_RESET": "リセット…",
  "KEYBOARD_SHORTCUT_PANEL_RESET_DEFAULT": "デフォルトのショートカットにリセット…",
  "KEYBOARD_SHORTCUT_RESET_DIALOG_TITLE": "キーボード ショートカットをリセットする",
  "KEYBOARD_SHORTCUT_RESET_DIALOG_MESSAGE": "すべてのカスタム ショートカットをデフォルトにリセットしますか?これは、元に戻すことはできません。",
  "STATUSBAR_CURSOR_POSITION": "行 {0}, 列 {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": " — {0} 列を選択",
  "STATUSBAR_SELECTION_CH_PLURAL": " — {0} 列を選択",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " — {0} 行を選択",
  "STATUSBAR_SELECTION_LINE_PLURAL": " — {0} 行を選択",
  "STATUSBAR_SELECTION_MULTIPLE": " — 選択範囲 {0}",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "インデントをスペースに変換する",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "インデントをタブに変換する",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "インデントに用いるスペースの数を変更",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "タブ幅を変更",
  "STATUSBAR_SPACES": "スペース :",
  "STATUSBAR_TAB_SIZE": "タブ幅 :",
  "STATUSBAR_LINE_COUNT_SINGULAR": "— {0} 行",
  "STATUSBAR_LINE_COUNT_PLURAL": "— {0} 行",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "拡張機能無効",
  "STATUSBAR_INSERT": "INS",
  "STATUSBAR_OVERWRITE": "OVR",
  "STATUSBAR_INSOVR_TOOLTIP": "クリックして挿入 (INS) モードと上書き (OVR) モード間のカーソルを切り替え",
  "STATUSBAR_LANG_TOOLTIP": "クリックしてファイルタイプを変更",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}。クリックしてレポートパネルを切り替えます。",
  "STATUSBAR_DEFAULT_LANG": "(指定なし)",
  "STATUSBAR_SET_DEFAULT_LANG": ".{0} ファイルのデフォルトとして設定",
  "STATUSBAR_ENCODING_TOOLTIP": "エンコードを選択",
  "STATUSBAR_TASKS": "タスク",
  "STATUSBAR_TASKS_TOOLTIP": "アクティブなタスクの管理",
  "STATUSBAR_TASKS_HIDE_SPINNER": "スピナーアイコンを非表示にする",
  "STATUSBAR_TASKS_UNKNOWN_EXTENSION_TASK": "不明な拡張タスク…",
  "STATUSBAR_TASKS_PLAY": "開始または再開",
  "STATUSBAR_TASKS_PAUSE": "一時停止",
  "STATUSBAR_TASKS_STOP": "停止",
  "STATUSBAR_TASKS_RESTART": "再起動",
  "ERRORS_NO_FILE": "ファイルが開いていません",
  "ERRORS_PANEL_TITLE_MULTIPLE": "{0} の問題 - {1}",
  "ERRORS_PANEL_TITLE_MULTIPLE_FIXABLE": "{0} の問題、{1} は修正可能 - {2}",
  "SINGLE_ERROR": "1 {0} 問題 - {1}",
  "SINGLE_ERROR_FIXABLE": "1 件の {0} 問題、{1} 修正可能 - {2}",
  "MULTIPLE_ERRORS": "{0} {1} 問題 - {2}",
  "MULTIPLE_ERRORS_FIXABLE": "{0} {1} の問題、{2} 修正可能 - {3}",
  "NO_ERRORS": "{0} の問題は検出されませんでした - Good job!",
  "NO_ERRORS_MULTIPLE_PROVIDER": "問題は検出されませんでした - Good job!",
  "LINT_DISABLED": "Lint チェックは使用できません",
  "NO_LINT_AVAILABLE": "{0} に使用できる Lint チェッカーがありません",
  "NOTHING_TO_LINT": "Lint チェックするファイルがありません",
  "COPY_ERROR": "エラーメッセージをコピー",
  "FIX_ERROR": "問題を解決する",
  "FIX": "修理",
  "CANNOT_FIX_TITLE": "修正を適用できませんでした",
  "CANNOT_FIX_SOME_TITLE": "いくつかの修正を適用できませんでした",
  "CANNOT_FIX_MESSAGE": "修正の準備以降にドキュメントが変更されています。もう一度お試しください。",
  "LINTER_TIMED_OUT": "{0} は {1} ミリ秒待機した後でタイムアウトしました",
  "LINTER_FAILED": "{0} は次のエラーにより終了しました : {1}",
  "FILE_MENU": "ファイル",
  "CMD_FILE_NEW_UNTITLED": "新規作成",
  "CMD_FILE_NEW": "新しいファイル",
  "CMD_FILE_DUPLICATE": "行を複製",
  "CMD_FILE_DUPLICATE_FILE": "重複ファイル",
  "CMD_FILE_DOWNLOAD_PROJECT": "プロジェクトをダウンロード",
  "CMD_FILE_DOWNLOAD": "ダウンロード",
  "CMD_FILE_CUT": "カット",
  "CMD_FILE_COPY": "コピー",
  "CMD_FILE_COPY_PATH": "パスをコピー",
  "CMD_FILE_PASTE": "ペースト",
  "CMD_PROJECT_NEW": "新しいプロジェクト…",
  "CMD_FILE_NEW_FOLDER": "新しいフォルダー",
  "CMD_FILE_OPEN": "ファイルを開いています…",
  "CMD_RECENT_FILES_OPEN": "最近使用したファイル…",
  "CMD_ADD_TO_WORKING_SET": "ワーキングセットに開く",
  "CMD_OPEN_DROPPED_FILES": "ドロップしたファイルを開く",
  "CMD_OPEN_FOLDER": "フォルダーを開く…",
  "CMD_FILE_CLOSE": "閉じる",
  "CMD_FILE_CLOSE_ALL": "すべて閉じる",
  "CMD_FILE_CLOSE_LIST": "リストを閉じる",
  "CMD_FILE_CLOSE_OTHERS": "他をすべて閉じる",
  "CMD_FILE_CLOSE_ABOVE": "上をすべて閉じる",
  "CMD_FILE_CLOSE_BELOW": "下をすべて閉じる",
  "CMD_FILE_SAVE": "ファイルを保存",
  "CMD_FILE_SAVE_ALL": "すべて保存",
  "CMD_FILE_SAVE_AS": "名前を付けて保存…",
  "CMD_LIVE_FILE_PREVIEW": "ライブプレビュー",
  "CMD_LIVE_FILE_PREVIEW_SETTINGS": "ライブプレビュー設定",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "試験ライブプレビューを有効にする",
  "CMD_RELOAD_LIVE_PREVIEW": "ライブプレビューを強制的に再読込み",
  "CMD_PROJECT_SETTINGS": "プロジェクト設定…",
  "CMD_FILE_RENAME": "ファイル名変更",
  "CMD_FILE_DELETE": "削除",
  "CMD_INSTALL_EXTENSION": "拡張機能をインストール…",
  "CMD_EXTENSION_MANAGER": "拡張機能マネージャー…",
  "CMD_FILE_REFRESH": "ファイルツリーを更新",
  "CMD_FILE_SHOW_FOLDERS_FIRST": "フォルダーを最初に並べ替える",
  "CMD_QUIT": "終了する",
  "CMD_EXIT": "終了",
  "EDIT_MENU": "編集",
  "CMD_UNDO": "取り消し",
  "CMD_REDO": "やり直し",
  "CMD_CUT": "カット",
  "CMD_COPY": "コピー",
  "CMD_PASTE": "ペースト",
  "CMD_SELECT_ALL": "すべて選択",
  "CMD_SELECT_LINE": "行の選択",
  "CMD_SPLIT_SEL_INTO_LINES": "選択範囲を行に分ける",
  "CMD_ADD_CUR_TO_NEXT_LINE": "次の行にカーソルを追加",
  "CMD_ADD_CUR_TO_PREV_LINE": "前の行にカーソルを追加",
  "CMD_INDENT": "インデント",
  "CMD_UNINDENT": "インデント解除",
  "CMD_DUPLICATE": "行を複製",
  "CMD_DELETE_LINES": "行を削除",
  "CMD_COMMENT": "行コメントの切り替え",
  "CMD_BLOCK_COMMENT": "ブロックコメントの切り替え",
  "CMD_LINE_UP": "行を上に移動",
  "CMD_LINE_DOWN": "行を下に移動",
  "CMD_OPEN_LINE_ABOVE": "上の行を開く",
  "CMD_OPEN_LINE_BELOW": "下の行を開く",
  "CMD_TOGGLE_CLOSE_BRACKETS": "自動閉じカッコ",
  "CMD_SHOW_CODE_HINTS": "コードヒントを表示",
  "CMD_BEAUTIFY_CODE": "コードの美化",
  "CMD_BEAUTIFY_CODE_ON_SAVE": "保存後にコードを美しくする",
  "FIND_MENU": "検索",
  "CMD_FIND": "検索",
  "CMD_FIND_NEXT": "次を検索",
  "CMD_FIND_PREVIOUS": "前を検索",
  "CMD_FIND_ALL_AND_SELECT": "すべての出現箇所を選択",
  "CMD_ADD_NEXT_MATCH": "次の出現箇所を追加",
  "CMD_SKIP_CURRENT_MATCH": "スキップして次の出現箇所を追加",
  "CMD_FIND_IN_FILES": "ファイルを横断して検索",
  "CMD_FIND_IN_SUBTREE": "検索先…",
  "CMD_REPLACE": "置換",
  "CMD_REPLACE_IN_FILES": "ファイルを横断して置換",
  "CMD_REPLACE_IN_SUBTREE": "置換対象…",
  "VIEW_MENU": "表示",
  "CMD_HIDE_SIDEBAR": "サイドバーを隠す",
  "CMD_SHOW_SIDEBAR": "サイドバーを表示する",
  "CMD_TOGGLE_SIDEBAR": "サイドバーの切り替え",
  "CMD_TOGGLE_PANELS": "パネルの表示切り替え",
  "CMD_TOGGLE_PURE_CODE": "簡易表示",
  "CMD_TOGGLE_FULLSCREEN": "全画面表示",
  "CMD_ZOOM_UI": "ZoomのUIとフォント",
  "CMD_ZOOM_IN": "ズームイン",
  "CMD_ZOOM_IN_SCALE": "ズームイン (現在: {0}%)",
  "CMD_ZOOM_OUT": "ズームアウトする",
  "CMD_INCREASE_FONT_SIZE": "フォントサイズを大きく",
  "CMD_DECREASE_FONT_SIZE": "フォントサイズを小さく",
  "CMD_RESTORE_FONT_SIZE": "フォントサイズを元に戻す",
  "CMD_SCROLL_LINE_UP": "1 行上にスクロール",
  "CMD_SCROLL_LINE_DOWN": "1 行下にスクロール",
  "CMD_TOGGLE_LINE_NUMBERS": "行番号",
  "CMD_TOGGLE_ACTIVE_LINE": "アクティブな行をハイライト",
  "CMD_TOGGLE_WORD_WRAP": "折り返し",
  "CMD_LIVE_HIGHLIGHT": "ライブプレビューハイライト",
  "CMD_VIEW_TOGGLE_INSPECTION": "保存時にファイルを Lint チェック",
  "CMD_WORKINGSET_SORT_BY_ADDED": "追加日時順",
  "CMD_WORKINGSET_SORT_BY_NAME": "名前順",
  "CMD_WORKINGSET_SORT_BY_TYPE": "種類順",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "自動ソート",
  "CMD_THEMES": "テーマ…",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "検索を自動的に閉じる",
  "CMD_TOGGLE_RULERS": "支配者",
  "CMD_KEYBOARD_NAV_OVERLAY": "ビジュアルコマンドパレット",
  "NAVIGATE_MENU": "ナビゲート",
  "CMD_QUICK_OPEN": "クイックオープン",
  "CMD_GOTO_LINE": "行に移動",
  "CMD_GOTO_DEFINITION": "定義をクイック検索",
  "CMD_GOTO_DEFINITION_PROJECT": "プロジェクトで定義をクイック検索",
  "CMD_GOTO_FIRST_PROBLEM": "最初の問題に移動",
  "CMD_TOGGLE_QUICK_EDIT": "クイック編集",
  "CMD_TOGGLE_QUICK_DOCS": "クイックドキュメント",
  "CMD_QUICK_EDIT_PREV_MATCH": "前のクイック編集項目",
  "CMD_QUICK_EDIT_NEXT_MATCH": "次のクイック編集項目",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "新規ルール",
  "CMD_NEXT_DOC": "次の文書",
  "CMD_PREV_DOC": "前の文書",
  "CMD_NAVIGATE_BACKWARD": "前に戻る",
  "CMD_NAVIGATE_FORWARD": "次に進む",
  "CMD_NEXT_DOC_LIST_ORDER": "リストの次の文書",
  "CMD_PREV_DOC_LIST_ORDER": "リストの前の文書",
  "CMD_SHOW_IN_TREE": "ファイルツリー内で表示",
  "CMD_SHOW_IN_EXPLORER": "エクスプローラーで表示",
  "CMD_SHOW_IN_FINDER": "Finder で表示",
  "CMD_SHOW_IN_OS": "OS ファイルに表示",
  "CMD_SWITCH_PANE_FOCUS": "ペインフォーカスの切り替え",
  "CMD_OPEN_VFS": "仮想ファイル システムを開く",
  "CMD_DIAGNOSTIC_TOOLS": "{APP_NAME} 診断ツール",
  "CMD_OPEN_EXTENSIONS_FOLDER": "拡張機能フォルダーを開く…",
  "CMD_OPEN_VIRTUAL_SERVER": "仮想サーバーを開く",
  "HELP_MENU": "ヘルプ",
  "CMD_CHECK_FOR_UPDATE": "アップデートを確認…",
  "CMD_AUTO_UPDATE": "自動更新",
  "CMD_HOW_TO_USE_BRACKETS": "{APP_NAME} の使用方法",
  "CMD_SUPPORT": "{APP_NAME} サポート",
  "CMD_DOCS": "ヘルプ、はじめに",
  "CMD_SUGGEST": "機能改善の提案",
  "CMD_RELEASE_NOTES": "リリースノート",
  "CMD_GET_INVOLVED": "コミュニティに参加",
  "CMD_SHOW_EXTENSIONS_FOLDER": "拡張機能のフォルダーを開く",
  "CMD_HEALTH_DATA_STATISTICS": "健康レポート…",
  "CMD_HOMEPAGE": "アプリをダウンロード - ホームページ",
  "CMD_TWITTER": "Twitter で {TWITTER_NAME} をフォロー",
  "CMD_YOUTUBE": "Youtubeチャンネル",
  "CMD_ABOUT": "{APP_TITLE} について",
  "CMD_OPEN_PREFERENCES": "環境設定ファイルを開く",
  "CMD_OPEN_KEYMAP": "ユーザーキーマップファイルを開く",
  "EXPERIMENTAL_BUILD": "試験ビルド",
  "RELEASE_BUILD": "ビルド",
  "DEVELOPMENT_BUILD": "開発ビルド",
  "PRERELEASE_BUILD": "プレリリースビルド",
  "RELOAD_FROM_DISK": "ディスクから再読み込み",
  "KEEP_CHANGES_IN_EDITOR": "エディター内の変更を保持する",
  "CLOSE_DONT_SAVE": "保存せずに閉じる",
  "RELAUNCH_CHROME": "Chrome を再起動",
  "ABOUT": "このソフトウェアについて",
  "CLOSE": "閉じる",
  "ABOUT_TEXT_LINE1": "{VERSION_MAJOR} をリリースします。{VERSION_MINOR} {BUILD_TYPE} {VERSION}",
  "ABOUT_TEXT_BUILD_TIMESTAMP": "ビルド タイムスタンプ:",
  "ABOUT_RELEASE_CREDITS": "リリースクレジット:",
  "ABOUT_TEXT_LINE3": "当社が使用するサードパーティ ライブラリ -<a href='https://github.com/phcode-dev/phoenix/tree/main/src/thirdparty/licences'>ライセンスと帰属</a>。",
  "ABOUT_TEXT_LINE4": "<a href='https://github.com/phcode-dev/phoenix/'>https://github.com/phcode-dev/phoenix/</a>のドキュメントとソース",
  "ABOUT_TEXT_LINE5": "❤ と JavaScript で作成:",
  "ABOUT_TEXT_LINE6": "多くの人がいます (しかし、現在そのデータの読み込みに問題があります)。",
  "ABOUT_TEXT_MDN_DOCS": "MDN Docs および MDN グラフィックロゴは Creative Commons の帰属ライセンス、<a href='{MDN_DOCS_LICENSE}'>CC-BY-SA 2.5 Unported</a> によってライセンス付与されています。",
  "UPDATE_NOTIFICATION_TOOLTIP": "{APP_NAME} の新しいビルドを利用できます。詳細はここをクリックしてください。",
  "UPDATE_NOT_AVAILABLE_TITLE": "{APP_NAME} は最新です",
  "UPDATE_UP_TO_DATE": "{APP_NAME} のバージョンは最新です。",
  "UPDATE_AVAILABLE_TITLE": "利用可能なアップデートがあります",
  "UPDATE_WHATS_NEW": "{APP_NAME} の新機能",
  "UPDATE_READY_RESTART_TITLE": "更新するにはアプリを再起動してください",
  "UPDATE_READY_RESTART_INSTALL_MESSAGE": "開いているウィンドウをすべて閉じると、{APP_NAME} は自動的に更新されます。",
  "UPDATE_FAILED_TITLE": "アップデートに失敗しました",
  "UPDATE_INSTALLING": "インストールするアップデート…",
  "UPDATE_INSTALLING_MESSAGE": "アップデートのインストールが進行中: {APP_NAME} は現在、最新のアップデートをインストール中です。インストールが完了すると、アプリケーションは自動的に終了します。",
  "UPDATE_FAILED_MESSAGE": "すべての {APP_NAME} アプリ ウィンドウを閉じて、アプリケーションを再度開き、再度更新を試行してください。<br/> <a href='https://phcode.io'>phcode.io</a>からインストーラーをダウンロードしてアップデートをインストールすることもできます。",
  "UPDATE_FAILED_VISIT_SITE_MESSAGE": "再試行するには、{APP_NAME} のすべてのインスタンスを終了し、アプリケーションを再起動してください。<br>すぐにダウンロード ページに移動します。そこで、最新バージョンを手動でダウンロードできます。",
  "UPDATE_MESSAGE": "{APP_NAME} の新しいビルドが利用できます。新機能の一部を以下にご紹介します :",
  "GET_IT_NOW": "すぐに入手する",
  "UPDATE_ON_EXIT": "終了時に更新",
  "UPDATE_LATER": "後でリマインドする",
  "UPDATE_DONE": "再起動して {APP_NAME} をアップデートしてください",
  "UPDATE_RESTART_INSTALL": "再起動してアップデートをインストールする",
  "UPDATE_DOWNLOADING": "インストーラーをダウンロード中",
  "INSTALL_WEBAPP": "デバイスに {APP_NAME} をインストールします",
  "UPDATE_DOWNLOAD_PROGRESS": "ダウンロード中 - {0}/{1} MB",
  "UPDATING_APP": "{APP_NAME} を更新しています",
  "UPDATING_APP_MESSAGE": "これは時間がかかる場合があります",
  "UPDATING_APP_DIALOG_MESSAGE": "更新中です。アップグレード中は、引き続き {APP_NAME} を使用できます。",
  "PROJECT_SETTINGS_TITLE": "プロジェクト設定 : {0}",
  "PROJECT_SETTING_BASE_URL": "ライブプレビューのベース URL",
  "PROJECT_SETTING_BASE_URL_HINT": "ローカルサーバーを使用するには、http://localhost:8000/ などの URL を入力してください",
  "BASEURL_ERROR_INVALID_PROTOCOL": "{0} プロトコルはライブプレビューではサポートされていません。http: または https: を使用してください。",
  "BASEURL_ERROR_SEARCH_DISALLOWED": "ベース URL には、「{0}」のような検索パラメーターは使用できません。",
  "BASEURL_ERROR_HASH_DISALLOWED": "ベース URL には、「{0}」のようなハッシュ記号は使用できません。",
  "BASEURL_ERROR_INVALID_CHAR": "「{0}」のような特殊文字は、パーセントエンコーディングする必要があります。",
  "BASEURL_ERROR_UNKNOWN_ERROR": "ベース URL の解析中に不明なエラーが発生しました",
  "EMPTY_VIEW_HEADER": "<em>このペインにフォーカスがあるときにファイルを開く</em>",
  "FLIPVIEW_BTN_TOOLTIP": "このビューを {0} ペインにめくる",
  "CURRENT_THEME": "現在のテーマ ",
  "USE_THEME_SCROLLBARS": "テーマスクロールバーを使用 ",
  "FONT_SIZE": "フォントサイズ ",
  "FONT_FAMILY": "フォントファミリー ",
  "THEMES_SETTINGS": "テーマ設定",
  "THEMES_ERROR": "テーマ エラー",
  "THEMES_ERROR_CANNOT_APPLY": "エラーのため、テーマを適用できませんでした。",
  "BUTTON_NEW_RULE": "新規ルール",
  "INSTALL": "インストール",
  "APPLY": "申し込み",
  "UPDATE": "更新",
  "REMOVE": "削除",
  "DISABLE": "無効",
  "ENABLE": "有効",
  "OVERWRITE": "上書き",
  "CANT_DROP_ZIP": "zip ファイルのドロップは、まもなくサポートされる予定です...",
  "CANT_REMOVE_DEV": "dev フォルダーの拡張機能は手動で削除する必要があります。",
  "CANT_UPDATE": "アップデートはこのバージョンの {APP_NAME} と互換性がありません。",
  "CANT_UPDATE_DEV": "dev フォルダーの拡張機能は自動的に更新されません。",
  "INSTALL_EXTENSION_TITLE": "拡張機能をインストール",
  "UPDATE_EXTENSION_TITLE": "拡張機能を更新",
  "INSTALL_EXTENSION_LABEL": "拡張機能の URL",
  "INSTALL_EXTENSION_HINT": "拡張機能 zip ファイルまたは GitHub レポジトリの URL",
  "INSTALLING_FROM": "{0} から拡張機能をインストールしています…",
  "INSTALL_SUCCEEDED": "インストールは成功しました。",
  "INSTALL_FAILED": "インストールは失敗しました。",
  "CANCELING_INSTALL": "キャンセルしています…",
  "CANCELING_HUNG": "インストールのキャンセルに時間がかかっています。内部エラーが発生した可能性があります。",
  "INSTALL_CANCELED": "インストールはキャンセルされました。",
  "VIEW_COMPLETE_DESCRIPTION": "詳細な説明を表示",
  "VIEW_TRUNCATED_DESCRIPTION": "省略された説明を表示",
  "SORT_EXTENSION_METHOD": "downloadCount または publishedDate を使用してエクステンションをソート",
  "INVALID_ZIP_FILE": "ダウンロードされたコンテンツは有効な zip ファイルではありません。",
  "MISSING_PACKAGE_JSON": "パッケージに package.json ファイルがありません。",
  "INVALID_PACKAGE_JSON": "package.json ファイルは有効ではありません (エラーは {0} です)。",
  "MISSING_PACKAGE_NAME": "package.json ファイルはパッケージ名を指定していません。",
  "BAD_PACKAGE_NAME": "{0} は無効なパッケージ名です。",
  "MISSING_PACKAGE_VERSION": "package.json ファイルはパッケージバージョンを指定していません。",
  "INVALID_VERSION_NUMBER": "パッケージバージョン番号 ({0}) は無効です。",
  "INVALID_BRACKETS_VERSION": "{APP_NAME} 互換文字列 {0} は無効です。",
  "DISALLOWED_WORDS": "{1} は {0} フィールドでは使用できません。",
  "NPM_INSTALL_FAILED": "npm install コマンドに失敗しました : {0}",
  "API_NOT_COMPATIBLE": "拡張機能はこのバージョンの {APP_NAME} と互換性がありません。無効な拡張機能フォルダーにインストールされます。",
  "MISSING_MAIN": "パッケージに main.js ファイルが含まれていません。",
  "EXTENSION_ALREADY_INSTALLED": "このパッケージをインストールすると以前にインストールした拡張機能が上書きされます。古い拡張機能を上書きしますか？",
  "EXTENSION_SAME_VERSION": "このパッケージのバージョンは現在インストールされているバージョンと同じです。既存のインストールを上書きしますか？",
  "EXTENSION_OLDER_VERSION": "このパッケージのバージョン ({0}) は、現在インストールされているバージョン ({1}) よりも古いバージョンです。既存のインストールを上書きしますか？",
  "DOWNLOAD_ID_IN_USE": "内部エラー : ダウンロード ID は既に使用されています。",
  "NO_SERVER_RESPONSE": "サーバーに接続できません。",
  "BAD_HTTP_STATUS": "ファイルがサーバー (HTTP {0}) に見つかりません。",
  "CANNOT_WRITE_TEMP": "一時ダウンロードファイルを保存できません。",
  "ERROR_LOADING": "拡張機能の起動時にエラーが発生しました。",
  "MALFORMED_URL": "URL が無効です。正しく入力されているか確認してください。",
  "UNSUPPORTED_PROTOCOL": "URL は http または https URL である必要があります。",
  "UNKNOWN_ERROR": "不明な内部エラー。",
  "EXTENSION_VERIFIED_PUBLISHER": "この発行者は {0} の所有権を確認しました",
  "EXTENSION_VERIFIED_SORT": "検証済み",
  "EXTENSION_STAR": "星",
  "EXTENSION_STAR_SORT": "星評価",
  "EXTENSION_MANAGER_TITLE": "拡張機能マネージャー",
  "EXTENSION_MANAGER_ERROR_LOAD": "拡張機能レジストリにアクセスできません。後でもう一度試してください。",
  "EXTENSION_UPDATE_RESTART_TITLE": "再起動してアップデートする",
  "EXTENSION_UPDATE_RESTART_MESSAGE": "更新された拡張機能を読み込むには、実行中の {APP_NAME} のインスタンスをすべて閉じて、アプリケーションを再起動してください。",
  "INSTALL_EXTENSION_DRAG": ".zip をここにドラッグするか、",
  "INSTALL_EXTENSION_DROP": ".zip をドロップしてインストール",
  "INSTALL_EXTENSION_DROP_ERROR": "次のエラーのため、インストール / アンインストールが中止されました :",
  "INSTALL_FROM_URL": "URL からインストール…",
  "INSTALL_EXTENSION_VALIDATING": "検証中…",
  "EXTENSION_AUTHOR": "作成者",
  "EXTENSION_DATE": "日付",
  "EXTENSION_INCOMPATIBLE_NEWER": "この拡張機能には新しいバージョンの {APP_NAME} が必要です。",
  "EXTENSION_INCOMPATIBLE_OLDER": "この拡張機能は現在、古いバージョンの {APP_NAME} でしか動作しません。",
  "EXTENSION_DEFAULT_FEATURE_PRESENT": "この拡張機能は必要ない場合があります。 {APP_NAME} にはすでにこの機能があります。",
  "EXTENSION_LATEST_INCOMPATIBLE_NEWER": "この拡張機能のバージョン {0} には {APP_NAME} の新しいバージョンが必要です。ただし、以前のバージョン {1} をインストールすることができます。",
  "EXTENSION_LATEST_INCOMPATIBLE_OLDER": "この拡張機能のバージョン {0} は {APP_NAME} の古いバージョンでのみ動作します。ただし、以前のバージョン {1} をインストールすることができます。",
  "EXTENSION_NO_DESCRIPTION": "説明なし",
  "EXTENSION_MORE_INFO": "詳細情報…",
  "EXTENSION_ERROR": "拡張機能のエラー",
  "EXTENSION_KEYWORDS": "キーワード",
  "EXTENSION_TRANSLATED_USER_LANG": "ご使用の言語を含む {0} 言語に翻訳されました",
  "EXTENSION_TRANSLATED_GENERAL": "{0} 言語に翻訳されました",
  "EXTENSION_TRANSLATED_LANGS": "この拡張機能はこれらの言語に翻訳されています : {0}",
  "EXTENSION_INSTALLED": "インストール済み",
  "EXTENSION_UPDATE_INSTALLED": "この拡張機能のアップデートがダウンロードされました。{APP_NAME} のリロード後にインストールされます。",
  "EXTENSION_SEARCH_PLACEHOLDER": "検索",
  "EXTENSION_MORE_INFO_LINK": "詳細",
  "EXTENSION_MANAGER_CREATE_EXTENSION": "+ 拡張機能を作成",
  "EXTENSION_MANAGER_CREATE_THEME": "+ テーマを作成",
  "BROWSE_EXTENSIONS": "拡張機能を探す",
  "EXTENSION_MANAGER_REMOVE": "拡張機能を削除",
  "EXTENSION_MANAGER_REMOVE_ERROR": "1 つ以上の拡張機能 ({0}) を削除できません。{APP_NAME} がリロード中です。",
  "EXTENSION_MANAGER_UPDATE": "拡張機能を更新",
  "EXTENSION_MANAGER_UPDATE_ERROR": "1 つ以上の拡張機能 ({0}) を更新できません。{APP_NAME} がリロード中です。",
  "EXTENSION_MANAGER_DISABLE": "拡張機能を無効化",
  "EXTENSION_MANAGER_DISABLE_ERROR": "1 つ以上の拡張機能 ({0}) を無効化できません。{APP_NAME} がリロード中です。",
  "EXTENSION_MANAGER_THEMES_INFO": "<a class=\"theme_settings\">デフォルトのテーマを選択する</a>か、他のテーマ設定を変更するには、<a class=\"theme_settings\">ここをクリックしてください</a>。",
  "EXTENSION_MANAGER_THEMES_UNDO": "前のテーマに戻す",
  "MARKED_FOR_REMOVAL": "削除予定",
  "UNDO_REMOVE": "取り消し",
  "MARKED_FOR_UPDATE": "更新予定",
  "UNDO_UPDATE": "取り消し",
  "MARKED_FOR_DISABLING": "無効化予定",
  "UNDO_DISABLE": "取り消し",
  "CHANGE_AND_RELOAD_TITLE": "拡張機能を変更",
  "CHANGE_AND_RELOAD_MESSAGE": "予定された拡張機能を更新、削除、無効にするには、{APP_NAME} をリロードする必要があります。未保存の変更を保存するかどうか確認されます。",
  "REMOVE_AND_RELOAD": "拡張機能を削除してリロード",
  "CHANGE_AND_RELOAD": "拡張機能を変更してリロード",
  "UPDATE_AND_RELOAD": "拡張機能を更新してリロード",
  "DISABLE_AND_RELOAD": "拡張機能を無効化してリロード",
  "PROCESSING_EXTENSIONS": "拡張機能の変更を処理中…",
  "EXTENSION_NOT_INSTALLED": "インストールされていなかったため、拡張機能 {0} を削除できませんでした。",
  "NO_EXTENSIONS": "インストールされている拡張機能はまだありません。<br>上の「入手可能」タブをクリックしてインストールしてください。",
  "NO_EXTENSION_MATCHES": "検索条件に一致する拡張機能がありません。",
  "REGISTRY_SANITY_CHECK_WARNING": "注意 : これらの拡張機能の作成元が {APP_NAME} 以外である可能性があります。拡張機能はレビューされず、ローカルアクセス権が一杯です。不明なソースから拡張機能をインストールするときは十分に注意してください。",
  "EXTENSIONS_INSTALLED_TITLE": "インストール済み",
  "EXTENSIONS_DEFAULT_TITLE": "デフォルト",
  "EXTENSIONS_AVAILABLE_TITLE": "入手可能",
  "EXTENSIONS_THEMES_TITLE": "テーマ",
  "EXTENSIONS_UPDATES_TITLE": "アップデート",
  "EXTENSIONS_LAST_UPDATED": "最終更新日",
  "EXTENSIONS_DOWNLOADS": "ダウンロード",
  "INLINE_EDITOR_NO_MATCHES": "一致するものがありません。",
  "INLINE_EDITOR_HIDDEN_MATCHES": "一致項目はすべて縮小されています。一致項目を表示するには、右側にリストされているファイルを展開してください。",
  "CSS_QUICK_EDIT_NO_MATCHES": "選択に一致する既存の CSS ルールがありません。<br>「新規ルール」をクリックしてルールを作成してください。",
  "CSS_QUICK_EDIT_NO_STYLESHEETS": "プロジェクトにはスタイルシートがありません。<br>スタイルシートを作成して CSS ルールに追加してください。",
  "IMAGE_VIEWER_LARGEST_ICON": "最大",
  "UNIT_PIXELS": "ピクセル",
  "DEBUG_MENU": "デバッグ",
  "ERRORS": "エラー ",
  "CMD_SHOW_DEV_TOOLS": "{APP_NAME} 開発者ツール",
  "CMD_REFRESH_WINDOW": "拡張機能付きでリロード",
  "CMD_LOAD_CURRENT_EXTENSION": "プロジェクトを拡張子としてロード",
  "CMD_RELOAD_CURRENT_EXTENSION": "プロジェクトを拡張子としてリロード",
  "CMD_UNLOAD_CURRENT_EXTENSION": "プロジェクトを拡張子としてアンロード",
  "CMD_RELOAD_WITHOUT_USER_EXTS": "拡張機能なしでリロード",
  "CMD_NEW_BRACKETS_WINDOW": "新しい窓",
  "CMD_LAUNCH_SCRIPT_MAC": "コマンドラインショートカットをインストール",
  "CMD_SWITCH_LANGUAGE": "言語を切り替え…",
  "CMD_RUN_UNIT_TESTS": "{APP_NAME} テストを実行する",
  "CMD_SHOW_PERF_DATA": "パフォーマンスデータを表示",
  "CMD_ENABLE_LOGGING": "詳細ログを有効にする",
  "CMD_ENABLE_PHNODE_INSPECTOR": "PhNode インスペクターを有効にする",
  "CMD_GET_PHNODE_INSPECTOR_URL": "PhNode を検査する方法",
  "CMD_ENABLE_LIVE_PREVIEW_LOGS": "ライブ プレビュー ログ",
  "CMD_OPEN_BRACKETS_SOURCE": "{APP_NAME} ソースを開く",
  "CREATING_LAUNCH_SCRIPT_TITLE": "{APP_NAME} コマンドラインショートカット",
  "ERROR_CREATING_LAUNCH_SCRIPT": "コマンドラインショートカットのインストール中にエラーが発生しました。<a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting'>これらのトラブルシューティングの提案</a>をお試しください。<br/><br/>理由 : {0}",
  "ERROR_CLTOOLS_RMFAILED": "既存の <code>/usr/local/bin/brackets</code> シンボリックリンクを削除できません。",
  "ERROR_CLTOOLS_MKDIRFAILED": "<code>/usr/local/bin</code> ディレクトリを作成できません。",
  "ERROR_CLTOOLS_LNFAILED": "<code>/usr/local/bin/brackets</code> シンボリックリンクを作成できません。",
  "ERROR_CLTOOLS_SERVFAILED": "内部エラーです。",
  "ERROR_CLTOOLS_NOTSUPPORTED": "この OS ではコマンドラインショートカットがサポートされていません。",
  "LAUNCH_SCRIPT_CREATE_SUCCESS": "成功しました。{APP_NAME} をコマンドラインから簡単に起動できるようになりました (<code>brackets myFile.txt</code> でファイルを開く、<code>brackets myFolder</code> でプロジェクトを切り替えるなど)。<br/><br/>コマンドラインから {APP_NAME} を使用する方法について<a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments'>詳細</a>をご確認ください。",
  "ERROR_LOADING_EXTENSION": "拡張機能の読み込みエラー",
  "ERROR_NO_EXTENSION_PACKAGE": "<code>package.json</code>ファイルが現在のプロジェクトで検出されませんでした。現在のプロジェクトは有効な {APP_NAME} 拡張機能ですか?</br>詳細については<a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>、このリンクを</a>参照してください。",
  "ERROR_INVALID_EXTENSION_PACKAGE": "<code>package.json</code>ファイルが無効な JSON です。</br>詳細については<a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>、このリンクを</a>参照してください。",
  "ERROR_INVALID_EXTENSION_PACKAGE_FIELDS": "<code>package.json</code>に必須フィールドがありません: [{0}]</br>詳細については<a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>、このリンクを</a>参照してください。",
  "ERROR_NODE_JS_CRASH_TITLE": "おっとっと！何か問題が発生しました。",
  "ERROR_NODE_JS_CRASH_MESSAGE": "問題が発生したため、{APP_NAME} を再起動する必要があります。心配しないでください。再起動する前にすべての作業内容を保存しようとしています。 </br>(エラー: ERROR_NODE_JS_CRASH)",
  "LANGUAGE_TITLE": "言語を切り替える",
  "LANGUAGE_MESSAGE": "言語 :",
  "LANGUAGE_SUBMIT": "{APP_NAME} をリロード",
  "LANGUAGE_CANCEL": "キャンセル",
  "LANGUAGE_SYSTEM_DEFAULT": "システムのデフォルト",
  "HEALTH_DATA_NOTIFICATION": "Health Report Preferences",
  "HEALTH_FIRST_POPUP_TITLE": "プライバシー通知",
  "HEALTH_DATA_DO_TRACK": "{APP_NAME} の使用方法に関する匿名の情報を共有する",
  "HEALTH_DATA_NOTIFICATION_MESSAGE": "{APP_NAME}<strong>は個人を特定できる情報を収集または処理しません</strong>が、プライバシーを保護するために<strong>匿名の使用統計を収集します</strong>。匿名データは GDPR/CCPA の通知要件の対象外ですが、匿名データの収集をオプトアウトする選択肢も必要であると考えています。<br><br> <strong>[ヘルプ] &gt; [ヘルスレポート]</strong>を選択すると、データを確認する<strong>か、匿名データを共有しないことを選択</strong>できます。これらの<strong>匿名の</strong>アプリ使用状況統計とエラー レポートは、機能の優先順位付け、バグの検出、ユーザビリティの問題の特定に役立ち、{APP_NAME} のエクスペリエンスを向上できます。このデータがなければ、どのような機能を構築する価値があるかわかりません。<br><br>",
  "HEALTH_DATA_PREVIEW": "{APP_NAME} の正常性レポート",
  "HEALTH_DATA_PREVIEW_INTRO": "<p>{APP_NAME} は<strong>個人を特定できる情報を収集または処理しません</strong>が、プライバシーを保護するために<strong>匿名の使用統計を収集します</strong>。これらの<strong>匿名の</strong>アプリ使用統計とエラー レポートは、機能の優先順位付け、バグの検出、ユーザビリティの問題の特定に役立ち、{APP_NAME} のエクスペリエンスを向上させます。</p><p>以下は、有効になっている<em>場合に</em>次回のヘルスレポートで送信されるデータのプレビューです。(「重大なエラーが発生しました」とマークされたエラー ログについては、開発者コンソールも参照してください。)</p>",
  "INLINE_TIMING_EDITOR_TIME": "時間",
  "INLINE_TIMING_EDITOR_PROGRESSION": "進行",
  "BEZIER_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd><kbd>←</kbd><kbd>→</kbd> 選択したポイントを移動<br><kbd class='text'>Shift</kbd> 10 単位ずつ移動<br><kbd class='text'>Tab</kbd> ポイントを切り替え",
  "STEPS_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd> 手順を増減<br><kbd>←</kbd><kbd>→</kbd> 「開始」または「終了」",
  "INLINE_TIMING_EDITOR_INVALID": "古い値 <code>{0}</code> が無効なため、表示されている関数は <code>{1}</code> に変更されました。ドキュメントは最初の編集内容で更新されます。",
  "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP": "現在の色",
  "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP": "元の色",
  "COLOR_EDITOR_RGBA_BUTTON_TIP": "RGBa 形式",
  "COLOR_EDITOR_HEX_BUTTON_TIP": "16 進形式",
  "COLOR_EDITOR_HSLA_BUTTON_TIP": "HSLa 形式",
  "COLOR_EDITOR_0X_BUTTON_TIP": "16 進数 (0x) 形式",
  "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR": "{0} ({1} 回使用)",
  "COLOR_EDITOR_USED_COLOR_TIP_PLURAL": "{0} ({1} 回使用)",
  "EDIT": "編集",
  "CMD_JUMPTO_DEFINITION": "定義にジャンプ",
  "CMD_SHOW_PARAMETER_HINT": "パラメーターヒントを表示",
  "NO_ARGUMENTS": "<パラメーターがありません>",
  "DETECTED_EXCLUSION_TITLE": "JavaScript ファイルの推論問題",
  "DETECTED_EXCLUSION_INFO": "{APP_NAME} で<span class='dialog-filename'>{0} の</span>処理中に問題が発生しました。<br><br>このファイルは、コード ヒント、定義へのジャンプ、またはクイック編集のために処理されなくなります。このファイルを再度有効にするには、プロジェクトで<code>.phcode.json</code>を開き、 <code>jscodehints.detectedExclusions</code>を編集します。<br><br>これはおそらく {APP_NAME} のバグです。このファイルのコピーを提供できる場合は、ここに指定されたファイルへのリンクを使用して<a href='https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue'>バグを報告して</a>ください。",
  "CMD_REFACTOR": "リファクタリング",
  "CMD_EXTRACTTO_VARIABLE": "変数に抽出",
  "CMD_EXTRACTTO_FUNCTION": "関数に抽出",
  "ERROR_TERN_FAILED": "Tern からデータを取得できません",
  "ERROR_EXTRACTTO_VARIABLE_NOT_VALID": "選択内容は式になっていません",
  "ERROR_EXTRACTTO_FUNCTION_NOT_VALID": "選択したブロックは、ステートメントセットまたは式を表す必要があります",
  "ERROR_EXTRACTTO_VARIABLE_MULTICURSORS": "変数に抽出は複数カーソルでは機能しません",
  "ERROR_EXTRACTTO_FUNCTION_MULTICURSORS": "関数に抽出は複数カーソルでは機能しません",
  "EXTRACTTO_FUNCTION_SELECT_SCOPE": "対象範囲を選択",
  "EXTRACTTO_VARIABLE_SELECT_EXPRESSION": "式を選択",
  "CMD_REFACTORING_RENAME": "ファイル名変更",
  "CMD_REFACTORING_TRY_CATCH": "Try Catch で囲む",
  "CMD_REFACTORING_CONDITION": "Condition で囲む",
  "CMD_REFACTORING_GETTERS_SETTERS": "Getters Setters を作成",
  "CMD_REFACTORING_ARROW_FUNCTION": "Arrow Function へ変換",
  "DESCRIPTION_CODE_REFACTORING": "JavaScript のコードリファクタリングを有効化または無効化します",
  "ERROR_TRY_CATCH": "有効なコードを選択して、Try-catch ブロックで囲みます",
  "ERROR_WRAP_IN_CONDITION": "有効なコードを選択して、Condition ブロックで囲みます",
  "ERROR_ARROW_FUNCTION": "関数式の中にカーソルを置きます",
  "ERROR_GETTERS_SETTERS": "オブジェクト式のメンバーにカーソルを置きます",
  "ERROR_RENAME_MULTICURSOR": "複数のカーソルを使用して名前を変更することはできません",
  "ERROR_RENAME_QUICKEDIT": "この識別子は、この関数以外の場所で参照されているため名前変更できません",
  "ERROR_RENAME_GENERAL": "選択したテキストの名前を変更できません",
  "JSHINT_NAME": "JSHint",
  "ESLINT_NAME": "ESLint",
  "CSS_LINT_NAME": "{0} 糸くず",
  "CMD_ENABLE_QUICK_VIEW": "ホバー・クイックビュー",
  "CMD_ENABLE_SELECTION_VIEW": "選択ビュー",
  "TOOLTIP_CLICK_TO_EDIT_COLOR": "ここをクリックして色を編集します",
  "CMD_TOGGLE_RECENT_PROJECTS": "最近使用したプロジェクト",
  "REMOVE_FROM_RECENT_PROJECTS": "最近のプロジェクトから削除",
  "DOCS_MORE_LINK": "詳細",
  "DOCS_MORE_LINK_MDN_TITLE": "クリックしてドキュメントを読む",
  "COLLAPSE_ALL": "すべて折りたたむ",
  "EXPAND_ALL": "すべて展開",
  "COLLAPSE_CURRENT": "現在のコードをたたむ",
  "EXPAND_CURRENT": "現在のコードを展開",
  "RECENT_FILES_DLG_HEADER": "最近使用したファイル",
  "RECENT_FILES_DLG_CLEAR_BUTTON_LABEL": "消去",
  "RECENT_FILES_DLG_CLEAR_BUTTON_TITLE": "ワーキングセットにないファイルをクリア",
  "RECOVER_UNSAVED_FILES_TITLE": "保存されていないファイルを回復しますか?",
  "RECOVER_UNSAVED_FILES_MESSAGE": "前回のセッションから保存されていないファイルを復元しますか?",
  "RECOVER_UNSAVED_FILES_RESTORE": "戻す",
  "DISCARD_UNSAVED_FILES_RESTORE": "破棄",
  "DESCRIPTION_CLOSE_BRACKETS": "中括弧、角括弧、丸括弧を自動的に閉じるには true",
  "DESCRIPTION_CLOSE_OTHERS_ABOVE": "「作業中ファイル」コンテキストメニューから「上をすべて閉じる」を削除するには false",
  "DESCRIPTION_CLOSE_OTHERS_BELOW": "「作業中ファイル」コンテキストメニューから「下をすべて閉じる」を削除するには false",
  "DESCRIPTION_CLOSE_OTHERS": "「作業中ファイル」コンテキストメニューから「他をすべて閉じる」を削除するには false",
  "DESCRIPTION_CLOSE_TAGS": "タグ終了オプションを設定します",
  "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS": "自動終了させないタグの配列",
  "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING": "開始タグの > の入力時に閉じる",
  "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING": "終了タグの / の入力時に閉じる",
  "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS": "表示時に空白行があるタグの配列",
  "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD": "インデントレベルの変更時に、折りたたみ可能なセクションマーカーを常に生成するには true",
  "DESCRIPTION_CODE_FOLDING_ENABLED": "コード折りたたみを有効にするには true",
  "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER": "余白の上にマウスのポインターを置いたときにのみセクション折りたたみマーカーを表示させるには true",
  "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL": "「すべて折りたたむ」を適用するレベル数を制限します",
  "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE": "次の行数に達したら折りたたみ可能なセクションのアイコンを表示する",
  "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES": "ファイルまたはプロジェクトを閉じて再度開く場合に折りたたまれたセクションを記憶するには true",
  "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE": "エディター内の選択したテキストでコード折りたたみを有効にするには true",
  "DESCRIPTION_DISABLED_DEFAULT_EXTENSIONS": "無効化された初期設定のエクステンション",
  "DESCRIPTION_ATTR_HINTS": "HTML 属性ヒントを有効化/無効化",
  "DESCRIPTION_CSS_PROP_HINTS": "CSS/LESS/SCSS プロパティヒントを有効化/無効化",
  "DESCRIPTION_JS_HINTS": "JavaScript のコードヒントを有効化/無効化",
  "DESCRIPTION_JS_HINTS_TYPE_DETAILS": "JavaScript コードヒントのデータタイプの詳細を有効化/無効化",
  "DESCRIPTION_PREF_HINTS": "環境設定のコードヒントを有効化/無効化",
  "DESCRIPTION_SPECIAL_CHAR_HINTS": "HTML エンティティヒントを有効化/無効化",
  "DESCRIPTION_SVG_HINTS": "SVG のコードヒントを有効化/無効化",
  "DESCRIPTION_HTML_TAG_HINTS": "HTML タグヒントを有効化/無効化",
  "DESCRIPTION_URL_CODE_HINTS": "HTML や CSS/LESS/SCSS の URL ヒントを有効化/無効化",
  "DESCRIPTION_DRAG_DROP_TEXT": "ドラッグ＆ドロップ機能を有効化/無効化",
  "DESCRIPTION_HEALTH_DATA_TRACKING": "正常性データのトラッキングを有効にする",
  "DESCRIPTION_HIGHLIGHT_MATCHES": "ドキュメント全体の一致する文字列の自動ハイライト表示を有効にします",
  "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN": "現在カーソルがあるトークンと一致するすべての文字列をハイライト表示 (選択不要)",
  "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY": "選択内容が完全なトークンの場合のみハイライト表示",
  "DESCRIPTION_INSERT_HINT_ON_TAB": "タブで現在選択しているコードヒントを挿入するには true",
  "DESCRIPTION_NO_HINTS_ON_DOT": ". の入力時に JS コードヒントを自動表示しない場合は true",
  "DESCRIPTION_JSHINT_DISABLE": "問題パネルで JSHints リンターを無効にするには true にします",
  "DESCRIPTION_ESLINT_DISABLE": "問題パネルで ESLint リンターを無効にするには true にします",
  "DESCRIPTION_ESLINT_FAILED": "ESLint が失敗しました ({0})。プロジェクトに有効な<a href='https://eslint.org/docs/latest/use/configure/configuration-files'>構成ファイルが</a>含まれていることを確認してください",
  "DESCRIPTION_ESLINT_USE_NATIVE_APP": "ESLintはデスクトップアプリでのみ利用可能です。phcode.ioからダウンロードしてください<a href='https://phcode.io'>。</a>",
  "DESCRIPTION_ESLINT_LOAD_FAILED": "このプロジェクトの ESLint の読み込みに失敗しました。{APP_NAME} は ESLint バージョン 7 以上のみをサポートしています。",
  "DESCRIPTION_ESLINT_DO_NPM_INSTALL": "ESLintを有効にするには、プロジェクトで「npm install」を実行してください。",
  "DESCRIPTION_LANGUAGE": "言語固有の設定",
  "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS": "ファイル拡張子から言語名への追加のマッピング",
  "DESCRIPTION_LANGUAGE_FILE_NAMES": "ファイル名から言語名への追加のマッピング",
  "DESCRIPTION_LINEWISE_COPY_CUT": "何も選択せずにコピーやカットを行うと、カーソルのあるすべての行がコピーまたはカットされます。",
  "DESCRIPTION_INPUT_STYLE": "CodeMirror による入力とフォーカスの処理方法を選択します。Textarea (初期設定) や counterditable (スクリーンリーダー向け)(不安定) などを選択できます",
  "DESCRIPTION_LINTING_ENABLED": "コード検証を有効にするには true",
  "DESCRIPTION_ASYNC_TIMEOUT": "非同期の構文チェックがタイムアウトするまでの時間 (ミリ秒)",
  "DESCRIPTION_LINTING_PREFER": "最初に実行する構文チェックの配列",
  "DESCRIPTION_LIVE_DEV_MULTIBROWSER": "試験ライブプレビューを有効にするには true",
  "DESCRIPTION_USE_PREFERED_ONLY": "linting.prefer のみで指定されたプロバイダーを実行するには true",
  "DESCRIPTION_MAX_CODE_HINTS": "一度に表示される最大コードヒント",
  "DESCRIPTION_PATH": "パス固有の設定",
  "DESCRIPTION_PROXY": "拡張機能のインストールに使用するプロキシサーバーの URL",
  "DESCRIPTION_SCROLL_PAST_END": "ドキュメントの終端を超えたスクロールを有効にするには true",
  "DESCRIPTION_SHOW_CODE_HINTS": "すべてのコードヒントを無効にするには false",
  "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING": "文字が選択されているときに点滅カーソルを表示したままにします",
  "DESCRIPTION_SHOW_LINE_NUMBERS": "コードの左の「余白」に行番号を表示するには true",
  "DESCRIPTION_RULERS_COLUMNS": "エディターで垂直ルーラーを描画するための列番号の配列。例: [80, 100]",
  "DESCRIPTION_RULERS_COLORS": "エディターのルーラー オプションに対応するルーラーの色の配列。例: [\"#3d3d3d\", \"赤\"]",
  "DESCRIPTION_RULERS_ENABLED": "エディターのルーラーを有効にする場合は true、そうでない場合は false",
  "DESCRIPTION_SMART_INDENT": "新規ブロックの作成時に自動的にインデントを設定",
  "DESCRIPTION_SOFT_TABS": "ソフトタブの動作を無効にするには false",
  "DESCRIPTION_SORT_DIRECTORIES_FIRST": "プロジェクトツリーでディレクトリが先に来るように並べ替えるには true",
  "DESCRIPTION_SPACE_UNITS": "スペースベースのインデントに用いるスペースの数",
  "DESCRIPTION_STATIC_SERVER_PORT": "組み込みのサーバーがライブプレビューで使用するポートの番号",
  "DESCRIPTION_STYLE_ACTIVE_LINE": "カーソルが置かれた線の背景色をハイライト表示するには true",
  "DESCRIPTION_TAB_SIZE": "タブに表示するスペースの数",
  "DESCRIPTION_USE_TAB_CHAR": "スペースの代わりにタブを使用するには true",
  "DESCRIPTION_UPPERCASE_COLORS": "Inline Color Editor で大文字の 16 進カラーを生成するには true",
  "DESCRIPTION_WORD_WRAP": "ビューポートの幅を超える行を折り返す",
  "DESCRIPTION_SEARCH_AUTOHIDE": "エディターがフォーカスされるとすぐに検索を閉じる",
  "DESCRIPTION_DETECTED_EXCLUSIONS": "Tern が制御不能になる原因として検出されたファイルの一覧",
  "DESCRIPTION_INFERENCE_TIMEOUT": "ファイルの認識時に Tern がタイムアウトするまでの時間",
  "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR": "ステータスバーにエラーを表示するには true",
  "DESCRIPTION_QUICK_VIEW_ENABLED": "クイックビューを有効にするには true",
  "DESCRIPTION_SELECTION_VIEW_ENABLED": "選択ビューを有効にする場合は true",
  "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW": "URL のない拡張機能の画像プレビューを表示するには true",
  "DESCRIPTION_NUMBER_QUICK_VIEW": "エディターで数値の上にマウスを移動するとクイック ビューを表示する場合は true",
  "DESCRIPTION_THEME": "{APP_NAME} のテーマを選択",
  "DESCRIPTION_USE_THEME_SCROLLBARS": "カスタムスクロールバーを許可するには true",
  "DESCRIPTION_LINTING_COLLAPSED": "構文チェックパネルを閉じるには true",
  "DESCRIPTION_FONT_FAMILY": "フォントファミリーを変更",
  "DESCRIPTION_DESKTOP_ZOOM_SCALE": "0.1 (よりコンパクトなビューの場合) から 2 (より大きく拡大されたビューの場合) の範囲のズーム倍率を選択します。デスクトップ アプリでのみ利用可能",
  "DESCRIPTION_FONT_SIZE": "フォントサイズを変更 (例 : 13 px)",
  "DESCRIPTION_FIND_IN_FILES_NODE": "ノードベースの検索を有効にするには true",
  "DESCRIPTION_FIND_IN_FILES_INSTANT": "クイック検索を有効にするには true",
  "DESCRIPTION_FONT_SMOOTHING": "Mac のみ : サブピクセルアンチエイリアスを有効にするには subpixel-antialiased、グレースケールアンチエイリアスの場合は antialiased",
  "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW": "分割ビューで環境設定ファイルを開けないようにするには false",
  "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE": "左側/上部のペインでユーザーの環境設定ファイルを開くには false",
  "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED": "ペインからの最後のファイルがペインのヘッダーの閉じるボタンにより閉じられた後、ペインを折りたたむには true",
  "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS": "ヘッダーの閉じるボタンと反転表示ボタンを表示するタイミングを切り替えます。",
  "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT": "/*\n * これは、環境設定がサポートされている読み取り専用ファイルです。\n * {APP_NAME} による。\n * このファイルを参照として使用して環境設定を変更してください\n * ファイル「phcode.json」が別のペインで開きます。\n * 内部の環境設定の使用方法の詳細については、\n * {APP_NAME}、https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences の Web ページを参照してください。\n */",
  "DEFAULT_PREFERENCES_JSON_DEFAULT": "デフォルト",
  "DESCRIPTION_PURE_CODING_SURFACE": "{APP_NAME} でコードのみモードを有効にし、その他すべての UI エレメントを非表示にするには true",
  "DESCRIPTION_INDENT_LINE_COMMENT": "行コメントのインデントを有効にするには true",
  "DESCRIPTION_RECENT_FILES_NAV": "最近使用したファイルのナビゲーションを有効化/無効化",
  "DESCRIPTION_LIVEDEV_WEBSOCKET_PORT": "ライブプレビューで WebSocket サーバーが実行されるポート",
  "DESCRIPTION_LIVE_DEV_HIGHLIGHT_SETTINGS": "ライブプレビューハイライト設定",
  "DESCRIPTION_LIVEDEV_ENABLE_REVERSE_INSPECT": "false にすると、ライブプレビューでのリバースインスペクトが無効になります",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW": "プレビューするものがありません!",
  "DESCRIPTION_LIVEDEV_EXCLUDED": "カスタムサーバーはこのファイルを提供できません",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW_EXCLUDED": "ライブ プレビュー設定は、フォルダー '{0}' からのファイルのみを提供するように構成されています",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW_DETAILS": "プレビューする HTML ファイルを選択してください",
  "DESCRIPTION_LIVEDEV_PREVIEW_RESTRICTED": "プレビューは利用できません!",
  "DESCRIPTION_LIVEDEV_PREVIEW_RESTRICTED_DETAILS": "この HTML ファイルは現在のプロジェクトの一部ではありません。セキュリティ上の理由から、ライブ プレビューできるのはプロジェクト ファイルのみです。このファイルをプレビューするには、そのファイルを含むフォルダーを別のプロジェクトとして開きます。",
  "DESCRIPTION_LIVEDEV_MAIN_HEADING": "ええとああ！<br>現在のブラウザはライブ プレビューをサポートしていません。",
  "DESCRIPTION_LIVEDEV_MAIN_SPAN": "<a href=\"https://phcode.io\" style=\"color: white\">phcode.io</a>から Windows、Mac、Linux 用のネイティブ アプリをダウンロードして、最高のライブ プレビュー エクスペリエンスを実現してください。<br>",
  "DESCRIPTION_LIVEDEV_SECURITY_POPOUT_MESSAGE": "ライブ プレビュー用にファイルを開こうとしています。このプロジェクトのソースを信頼できる場合にのみ続行してください。 [プロジェクトを信頼する] をクリックして続行するか、ソースを信頼しない場合はこのウィンドウを閉じます。",
  "DESCRIPTION_LIVEDEV_SECURITY_TRUST_MESSAGE": "ライブ プレビュー用にファイルを開こうとしています。このプロジェクトのソースを信頼できる場合にのみ、「プロジェクトを信頼する」をクリックして続行してください。",
  "CONFIRM_EXTERNAL_BROWSER_TITLE": "ポップアップがブロックされました",
  "CONFIRM_EXTERNAL_BROWSER_MESSAGE": "ライブ プレビュー ページでこの URL: {0} を開くことを許可しますか?",
  "TRUST_PROJECT": "信頼してプレビューを実行 - {0}",
  "TRUST_AUTHORS": "このプロジェクトの作者を信頼しますか?",
  "DOWNLOAD_FAILED": "ダウンロードに失敗しました。",
  "DOWNLOAD_COMPLETE": "ダウンロードが完了しました。",
  "UPDATE_SUCCESSFUL": "アップデートが正常に完了しました。",
  "UPDATE_FAILED": "アップデートに失敗しました。",
  "VALIDATION_FAILED": "検証に失敗しました。",
  "INITIALISATION_FAILED": "初期化に失敗しました。",
  "CLEANUP_FAILED": "クリーンアップに失敗しました。",
  "WARNING_TYPE": "警告",
  "CLICK_RESTART_TO_UPDATE": "Brackets をアップデートするには、「再起動」をクリックしてください。",
  "UPDATE_ON_NEXT_LAUNCH": "アップデートは再起動時に適用されます。",
  "GO_TO_SITE": "<a href=\"http://brackets.io/\">brackets.io</a> に移動して、再試行します。",
  "INTERNET_UNAVAILABLE": "インターネットに接続されていません.",
  "UPDATEDIR_READ_FAILED": "アップデートディレクトリを読み込めませんでした。",
  "UPDATEDIR_CLEAN_FAILED": "アップデートディレクトリを空にできませんでした。",
  "INITIAL_DOWNLOAD": "アップデートをダウンロード中...",
  "RETRY_DOWNLOAD": "ダウンロードに失敗しました。再試行...試行",
  "VALIDATING_INSTALLER": "ダウンロードが完了しました。インストーラーを検証中...",
  "CHECKSUM_DID_NOT_MATCH": "チェックサムが一致しませんでした。",
  "INSTALLER_NOT_FOUND": "インストーラーが見つかりません。",
  "DOWNLOAD_ERROR": "ダウンロード中にエラーが発生しました。",
  "NETWORK_SLOW_OR_DISCONNECTED": "ネットワーク接続がないか速度が遅すぎます。",
  "RESTART_BUTTON": "再起動",
  "LATER_BUTTON": "後で再起動",
  "DESCRIPTION_AUTO_UPDATE": "{APP_NAME} の自動更新を有効または無効にする",
  "AUTOUPDATE_ERROR": "エラー!",
  "AUTOUPDATE_IN_PROGRESS": "更新は既に進行中です。",
  "NUMBER_WITH_PERCENTAGE": "{0}%",
  "CMD_FIND_RELATED_FILES": "関連するファイルを検索",
  "PHP_VERSION_INVALID": "PHP バージョンを解析する際のエラーです。“php –version” コマンドの出力を確認してください。",
  "PHP_UNSUPPORTED_VERSION": "コードヒント、パラメーターヒント、定義にジャンプなどの PHP 関連のツールを有効化するために、PHP7 ランタイムをインストールしてください。検出されたバージョン: {0}",
  "PHP_EXECUTABLE_NOT_FOUND": "PHP ランタイムが見つかりません。PHP7 ランタイムをインストールして、PHP の環境設定で適切に “executablePath” を更新してください。これにより、コードヒント、パラメーターヒント、定義にジャンプなどの PHP 関連のツールが有効になります。",
  "PHP_PROCESS_SPAWN_ERROR": "PHP プロセスを起動中に、エラーコード {0} が発生しました。",
  "PHP_SERVER_ERROR_TITLE": "エラー",
  "PHP_SERVER_MEMORY_LIMIT_INVALID": "指定したメモリ制限は無効です。正しい値を設定するために、PHP の環境設定を確認してください。",
  "DESCRIPTION_PHP_TOOLING_CONFIGURATION": "PHP ツールのデフォルト設定",
  "OPEN_PREFERENNCES": "環境設定を開く",
  "LANGUAGE_TOOLS_PREFERENCES": "言語ツールの設定",
  "FIND_ALL_REFERENCES": "すべての参照を検索",
  "REFERENCES_IN_FILES": "参照",
  "REFERENCE_IN_FILES": "参照",
  "REFERENCES_NO_RESULTS": "現在のカーソル位置で利用可能な参照はありません",
  "CMD_FIND_DOCUMENT_SYMBOLS": "ドキュメント記号を検索",
  "CMD_FIND_PROJECT_SYMBOLS": "プロジェクト記号を検索",
  "REMOTE_DEBUGGING_ENABLED": "次のローカルホストでリモートデバッグが有効になりました。localhost:",
  "REMOTE_DEBUGGING_PORT_INVALID": "ポート {0} でリモートデバッグを有効にできません。ポート番号は、{1} から {2} の間で指定してください。",
  "DESCRIPTION_EXTERNAL_APPLICATION_ASSOCIATE": "ファイル拡張子の外部アプリケーションへのマッピング。構文: \"<file_type>\": \"<default|applicationName|ApplicationPath>\"。「default」を指定すると、そのファイルタイプに対してシステムでデフォルトに設定されているアプリケーションを使用してファイルが開きます。",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_TITLE": "外部エディターでグラフィックファイルを開きます。",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_MSG": "現在のフォルダーには、{APP_NAME}でサポートされていないタイプのグラフィックファイルがあります。<br/>ここで、特定のファイルタイプを外部エディターに関連付けることができます。関連付けが完了すると、xd、.psd、.jpg、.png、.ai、.svgなどのグラフィックファイルをファイルツリーでダブルクリックすることで、デフォルトのアプリケーションで開くことができます。<br/><br/>「OK」ボタンをクリックして、グラフィックファイルタイプをそれぞれのデフォルトアプリケーションに関連付けてください。",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_CNF_MSG": "次のファイル タイプはデフォルトのアプリケーションに正常に関連付けられています。<br/> {0}「デバッグ -&gt; 環境設定ファイルを開く」メニューに移動すると、phcode.json 内の新しいファイルタイプの関連付けを削除または追加するかどうかの環境設定を変更するオプションがあります。",
  "UNSUPPORTED_BROWSER_TITLE": "ブラウザはサポートされていません",
  "UNSUPPORTED_BROWSER_MESSAGE": "最新のブラウザー (過去 3 年以内にリリースされたもの) を使用してください。",
  "UNSUPPORTED_BROWSER_MOBILE_TITLE": "モバイル ブラウザはサポートされていません",
  "UNSUPPORTED_BROWSER_MOBILE": "モバイルおよびタブレット ブラウザは、現在完全にはサポートされていません。このダイアログを閉じることはできますが、このブラウザでは Phoenix の一部の機能が動作しません。<br/><br/> iOS および Android 向けのネイティブ アプリの開発に取り組んでいます。<a href=\"https://github.com/phcode-dev/phoenix/discussions/1046\" target=\"_blank\">ここで議論に参加してください！</a>",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER_TITLE": "ブラウザでサポートされていないローカル フォルダ アクセス",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER": "申し訳ありませんが、現在お使いのブラウザはローカル フォルダを開くことをサポートしていないようです。この機能については、Chrome、Edge、または Opera を使用することをお勧めします。<br/><br/>または、完全なサポートを提供するために、Windows、Mac、Linux、iOS、および Android 用のネイティブ アプリの開発に取り組んでいます。<a href=\"https://github.com/phcode-dev/phoenix/discussions/1047\" target=\"_blank\">最新情報をお楽しみに！</a>",
  "ATTENTION_SAFARI_USERS": "Safariユーザーへの注意",
  "ATTENTION_SAFARI_USERS_MESSAGE": "<span>7 日以内にサイトに再アクセスしないと、Safari は Web サイトのデータを自動的に削除します。 {APP_NAME} はブラウザのストレージに依存してプロジェクトを保存しているため、このポリシーにより削除される可能性があります。<br/><br/> <a href='https://phcode.io' target='_blank' style='color: white'>https://phcode.io</a>から<strong>macOS デスクトップ アプリをダウンロードする</strong>ことをお勧めします。</span>",
  "CANNOT_PUBLISH_LARGE_PROJECT": "大規模なプロジェクトを発行できません",
  "CANNOT_PUBLISH_LARGE_PROJECT_MESSAGE": "Phoenix はまだ実験的なアルファ版です。 500 を超えるファイルを含むプロジェクトの同期はまだ有効になっていません。",
  "SHARE_WEBSITE": "ウェブサイトを公開して共有しますか?",
  "PUBLISH": "公開",
  "PUBLISH_CONSENT_MESSAGE": "変更をすばやくプレビューし、Web サイトを他のユーザーと共有します。 Phoenix は、この Web サイトを {0} で公開できます。公開されたリンクは 30 日間有効です。 </br>ウェブサイトを公開して共有しますか?",
  "PUBLISH_SYNC_IN_PROGRESS": "プレビューのために同期中...",
  "PUBLISH_PAGE": "クリックしてこのサイトを公開して共有する",
  "PUBLISH_VIEW_PAGE": "クリックして公開ページを表示",
  "MISSING_FIELDS": "欠落しているフィールド",
  "PLEASE_FILL_ALL_REQUIRED": "赤で強調表示されているすべての必須フィールドに入力してください",
  "CODE_EDITOR": "コード エディタ",
  "BUILD_THE_WEB": "ウェブを構築する",
  "IMPORT_PROJECT": "プロジェクトのインポート",
  "GITHUB_PROJECT": "GitHub プロジェクト",
  "NEW_PROJECT_FROM_GITHUB": "GitHub からの新しいプロジェクト",
  "GITHUB_REPO_URL": "GitHub リポジトリの URL :",
  "START_PROJECT": "プロジェクトを開始…",
  "DOWNLOAD_DESKTOP_APP": "デスクトップアプリをダウンロード",
  "GET_DESKTOP_APP": "デスクトップアプリを入手",
  "CREATE_PROJECT": "プロジェクトを作成",
  "SETTING_UP_PROJECT": "プロジェクトの設定",
  "LOCATION": "位置 ：",
  "DOWNLOADING": "ダウンロード中...",
  "DOWNLOADING_FILE": "{0} をダウンロードしています...",
  "EXTRACTING_FILES_PROGRESS": "{1} 個のファイルのうち {0} 個を抽出しています。",
  "COMPRESS_FILES_PROGRESS": "{1} 個のファイルの {0} 個を圧縮しています。",
  "DOWNLOAD_FAILED_MESSAGE": "ダウンロード URL が有効であることを確認してください。 </br>注: Phoenix はアルファ版であるため、25 MB を超えるプライベート リポジトリと GitHub URL は許可されていません。",
  "PLEASE_SELECT_A_FOLDER": "フォルダを選択してください...",
  "UNZIP_IN_PROGRESS": "ファイルを解凍しています...",
  "UNZIP_FAILED": "エラー: 解凍に失敗しました。",
  "CONFIRM_REPLACE_TITLE": "交換の確認",
  "KEEP_BOTH": "両方保持",
  "EXPLORE": "HTML ゲーム",
  "BLOG": "ブログ",
  "PHOENIX_DEFAULT_PROJECT": "デフォルト プロジェクト",
  "PROJECT_NAME": "プロジェクト名:",
  "NEW_HTML": "新しい HTML プロジェクト",
  "LICENSE": "ライセンスとクレジット:",
  "PREVIEW": "プレビュー",
  "BUILD_WEBSITE": "ウェブサイトの構築",
  "VIEW_MORE": "もっと見る...",
  "NEW_PROJECT_NOTIFICATION": "このアイコンをクリックすると、「新しいプロジェクト」ウィンドウが再度開きます。</br>最近のプロジェクトを表示したり、フォルダーを開いたり、テンプレートからプロジェクトを開始したりできます。</br><img src=\"styles/images/new_project.png\"><br/><a href='#' style='float:right;'>わかりました</a>",
  "BEAUTIFY_CODE_NOTIFICATION": "コードを美しくするには、ここをクリックするか、 <b>「{0}」</b>を押してください。</br><img src=\"styles/images/beautify.gif\"><br/><a href='#' style='float:right;'>わかりました</a>",
  "DEFAULT_PROJECT_NOTIFICATION": "ここをクリックして開きます<br/>phoenix の<b>デフォルト プロジェクト</b>。</br><a href='#' style='float:right;'>わかった</a>",
  "DIRECTORY_REPLACE_MESSAGE": "選択したフォルダー<span class='dialog-filename'>{0}</span>は空ではありません。フォルダーの内容をプロジェクトに置き換えてよろしいですか?",
  "DEFAULT_PROJECT_HTML_CLICK_HERE": "HTML ファイル内でこの &ltspan&gt を見つけるには、ここをクリックしてください",
  "BUILD_WEBSITE_SECTION": "ウェブサイトの構築",
  "LEARN_SECTION": "例で学ぶ",
  "CREATE_EXTENSION_SECTION": "{APP_NAME} の拡張機能とテーマを作成する",
  "CREATE_EXTENSION": "拡張機能を作成",
  "CREATE_THEME": "テーマを作成",
  "WEBPAGE_HOME_PAGE": "ホームページ",
  "WEBPAGE_BLOG": "ブログページ",
  "WEBPAGE_DASHBOARD": "HTML ダッシュボード",
  "WEBPAGE_BOOTSTRAP_EXAMPLES": "ブートストラップの例",
  "PROJECTS_AT_A_GLANCE": "プロジェクトの概要",
  "PROJECT_AT_GLANCE_DESCRIPTION": "開始するにはビデオをご覧ください。",
  "PROJECT_FROM_BROWSER": "ブラウザに保存",
  "PROJECT_FROM_BROWSER_TERSE": "ブラウザストレージ",
  "PROJECT_SHOW_ON_STARTUP": "起動時にこのダイアログを表示する",
  "GUIDED_LIVE_PREVIEW": "HTML ファイルのコードを変更して、ライブ プレビューを表示します。</br><a href='#' style='float:right;'>わかった</a>",
  "GUIDED_LIVE_PREVIEW_POPOUT": "このボタンをクリックして、ライブ プレビューを新しいタブにポップアウトします。</br><a href='#' style='float:right;'>わかった</a>",
  "ENJOYING_APP": "{APP_NAME} を楽しんでいますか？",
  "GITHUB_STARS_POPUP": "<div>あなたのサポートは、 <b style='color: darkblue'>phcode.dev を</b>さらに改善するための私たちの小さなチームのモチベーションになります。<br/>ぜひ私たちにスターを付けるか、GitHub でスポンサーになってください:",
  "GITHUB_STARS_POPUP_TWITTER": "フィードバックを送信するか、Twitter でその言葉を広めてください。",
  "TEST_TRANSLATE": "これを使用して翻訳をテストします",
  "BEAUTIFY_ERROR": "コードを美化できませんでした。構文を確認してください。",
  "BEAUTIFY_ERROR_ORIGINAL_CHANGED": "美化できませんでした。美化後にエディターのテキストが変更されました。",
  "BEAUTIFY_PROJECT_BUSY_MESSAGE": "美化ファイル {0}",
  "BEAUTIFY_ERROR_SELECTION": "美化できませんでした。</br>不完全なコード ブロックが選択されているか、構文が無効です。",
  "BEAUTIFY_OPTIONS": "Beautify Code の動作を制御するオプション",
  "BEAUTIFY_OPTION_PRINT_WIDTH": "beautifier が折り返す行の長さを指定します",
  "BEAUTIFY_OPTION_SEMICOLON": "すべてのステートメントの最後にセミコロンを追加します",
  "BEAUTIFY_OPTION_SINGLE_QUOTE": "二重引用符の代わりに一重引用符を使用する",
  "BEAUTIFY_OPTION_QUOTE_PROPS": "オブジェクトのプロパティが引用符で囲まれている場合の変更",
  "BEAUTIFY_OPTION_BRACKET_SAME_LINE": "複数行の HTML (HTML、JSX、Vue、Angular) 要素の > を次の行に単独で配置するのではなく、最後の行の最後に配置します (自己終了要素には適用されません)。",
  "BEAUTIFY_OPTION_SINGLE_ATTRIBUTE_PER_LINE": "HTML、Vue、JSX で 1 行に 1 つの属性を適用する",
  "BEAUTIFY_OPTION_PROSE_WRAP": "マークダウンファイルの印刷幅を超える場合は文章を折り返す",
  "BEAUTIFY_OPTION_PRINT_TRAILING_COMMAS": "複数行のコンマ区切りの構文構造では、可能な限り末尾のコンマを出力します"
});