/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 * Original work Copyright (c) 2012 - 2021 Adobe Systems Incorporated. All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "GENERIC_ERROR": "(fout {0})",
  "NOT_FOUND_ERR": "Het bestand kan niet worden gevonden.",
  "NOT_READABLE_ERR": "Het bestand kan niet worden ingelezen.",
  "EXCEEDS_MAX_FILE_SIZE": "Bestanden groter dan {0} MB kunnen niet worden geopend in {APP_NAME}.",
  "NO_MODIFICATION_ALLOWED_ERR": "De doelmap kan niet gewijzigd worden.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "De bevoegdheden laten u niet toe enige wijzigingen aan te brengen.",
  "CONTENTS_MODIFIED_ERR": "Het bestand is bijgewerkt buiten {APP_NAME} om.",
  "UNSUPPORTED_ENCODING_ERR": "{APP_NAME} ondersteunt momenteel alleen bestanden in UTF-8 tekstcodering.",
  "ENCODE_FILE_FAILED_ERR": "{APP_NAME} kon de inhoud van het bestand niet coderen.",
  "DECODE_FILE_FAILED_ERR": "{APP_NAME} kon de inhoud van het bestand niet decoderen.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "{APP_NAME} ondersteunt momenteel geen UTF-16 gecodeerde tekstbestanden.",
  "FILE_EXISTS_ERR": "Het bestand of map bestaat al.",
  "FILE": "bestand",
  "FILE_TITLE": "Bestand",
  "DIRECTORY": "map",
  "DIRECTORY_TITLE": "Map",
  "DIRECTORY_NAMES_LEDE": "Mapnamen",
  "FILENAMES_LEDE": "Bestandsnamen",
  "FILENAME": "Bestandsnaam",
  "DIRECTORY_NAME": "Mapnaam",
  "ERROR_LOADING_PROJECT": "Probleem tijdens het laden van het project",
  "OPEN_DIALOG_ERROR": "Er is een fout opgetreden bij het tonen van het dialoogvenster om een bestand te openen. (error {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "Er is een fout opgetreden bij het laden van map <span class='dialog-filename'>{0}</span>. (error {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "Er is een fout opgetreden bij het lezen van de inhoud van map <span class='dialog-filename'>{0}</span>. (error {1})",
  "ERROR_OPENING_FILE_TITLE": "Probleem bij het openen van een bestand",
  "ERROR_OPENING_FILE": "Er is een fout opgetreden bij het openen van het bestand <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_OPENING_FILES": "Er is een fout opgetreden bij het openen van de volgende bestanden:",
  "ERROR_RELOADING_FILE_TITLE": "Probleem bij het herladen van wijzigingen op de schijf",
  "ERROR_RELOADING_FILE": "Er is een fout opgetreden bij het herladen van het bestand <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_SAVING_FILE_TITLE": "Probleem bij het opslaan van een bestand",
  "ERROR_SAVING_FILE": "Er is een fout opgetreden bij het opslaan van het bestand <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_FILE_TITLE": "Probleem bij het hernoemen van een bestand",
  "ERROR_RENAMING_FILE": "Er is een fout opgetreden bij het hernoemen van het bestand <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "Het bestand of de map maakt geen deel uit van het momenteel geopende project. Helaas kunnen op dit moment alleen projectbestanden worden hernoemd.",
  "ERROR_MOVING_FILE_TITLE": "Fout bij verplaatsen van {0}",
  "ERROR_MOVING_FILE": "Er is een fout opgetreden bij het verplaatsen van de {2} <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "Kan het bestand/de map niet verplaatsen, omdat deze geen deel uitmaken van het huidige project.",
  "ERROR_DELETING_FILE_TITLE": "Probleem bij het verwijderen van een bestand",
  "ERROR_DELETING_FILE": "Er is een fout opgetreden bij het verwijderen van het bestand <span class='dialog-filename'>{0}</span>. {1}",
  "INVALID_FILENAME_TITLE": "Ongeldige {0} naam",
  "INVALID_FILENAME_MESSAGE": "Bestandsnamen kunnen de volgende karakters niet bevatten: {0} of gebruik maken van woorden die door het systeem zijn gereserveerd.",
  "ENTRY_WITH_SAME_NAME_EXISTS": "Een bestand of map met de naam <span class='dialog-filename'>{0}</span> bestaat al.",
  "ERROR_CREATING_FILE_TITLE": "Probleem bij het aanmaken van een {0}",
  "ERROR_CREATING_FILE": "Er is een fout opgetreden bij het aanmaken van het {0} <span class='dialog-filename'>{1}</span>. {2}",
  "ERROR_MIXED_DRAGDROP": "Het is niet mogelijk een map te openen en tegelijkertijd andere bestanden.",
  "ERROR_KEYMAP_TITLE": "Fout tijdens lezen van het configuratiebestand (keymap.json).",
  "ERROR_KEYMAP_CORRUPT": "De JSON-code in het configuratiebestand (keymap.json) is niet correct. Het bestand wordt geopend zodat je het kan corrigeren.",
  "ERROR_LOADING_KEYMAP": "Het configuratiebestand (keymap.json) is niet opgeslagen in UTF-8 tekstcodering en kan zodoende niet worden geopend.",
  "ERROR_RESTRICTED_COMMANDS": "Je kan deze sneltoetsen niet toewijzen aan deze commando's: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "Je kan deze sneltoetsen niet opnieuw toewijzen: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "Je wijst meerdere sneltoetsen toe aan deze commando's: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "Je hebt meerdere acties aan dezelfde sneltoetsen toegewezen: {0}",
  "ERROR_INVALID_SHORTCUTS": "Deze sneltoetsen zijn niet toegestaan: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "Je wijst sneltoetsen toe aan niet-bestaande commando's: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "Fout tijdens lezen instellingen",
  "ERROR_PREFS_CORRUPT": "De JSON-code van het configuratiebestand is niet correct. Het bestand wordt geopend zodat je het kan corrigeren. {APP_NAME} moet hierna herstart worden om de wijzigingen toe te passen.",
  "ERROR_PROJ_PREFS_CORRUPT": "De JSON-code van het project-configuratiebestand is niet correct. Het bestand wordt geopend zodat je het kan corrigeren. Je moet het project opnieuw laden om de wijzigingen toe te passen.",
  "ERROR_IN_BROWSER_TITLE": "Oeps! {APP_NAME} werkt nog niet in browsers.",
  "ERROR_IN_BROWSER": "{APP_NAME} is gebouwd in HTML, maar op dit moment werkt het als desktop applicatie zodat je het kan gebruiken om lokale bestanden te bewerken. Gebruik graag de applicatie-omgeving op <b>github.com/adobe/brackets-shell</b> om {APP_NAME} te starten.",
  "ERROR_MAX_FILES_TITLE": "Probleem bij het indexeren van bestanden",
  "ERROR_MAX_FILES": "Het maximum aantal bestanden is geïndexeerd. Het kan zijn dat acties om bestanden op te zoeken in de index niet correct verlopen.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "Probleem bij het starten in de browser",
  "ERROR_CANT_FIND_CHROME": "De Google Chrome browser kon niet gevonden worden. Zorg ervoor dat deze geïnstalleerd is.",
  "ERROR_LAUNCHING_BROWSER": "Er is een fout opgetreden bij het starten van de browser. (error {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "Probleem met Live Voorbeeld",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "Bezig met verbinden met de browser",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "Om met Live Voorbeeld te verbinden, moet Chrome opnieuw gestart worden met debugging op afstand ingeschakeld.<br /><br />Wil je Chrome herstarten en debugging op afstand inschakelen?",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "Onmogelijk om de Live Ontwikkeling pagina te laden",
  "LIVE_DEV_NEED_HTML_MESSAGE": "Open een HTML bestand om Live Voorbeeld te starten.",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "Om live voorbeeld te starten met een server-side bestand, moet je een Start URL voor dit project definiëren.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "Er is een fout opgetreden bij het opstarten van de HTTP server voor live ontwikkeling bestanden. Probeer alsjeblieft opnieuw.",
  "LIVE_DEVELOPMENT_INFO_TITLE": "Welkom bij Live Voorbeeld!",
  "LIVE_DEVELOPMENT_INFO_MESSAGE": "Live Voorbeeld verbindt {APP_NAME} met je browser. Het toont een voorbeeld van je HTML bestand in de browser, vervolgens updatet het voorbeeld onmiddelijk bij het wijzigen van je code.<br /><br />In deze vroege versie van {APP_NAME}, werkt Live Voorbeeld enkel met <strong>Google Chrome</strong> en updatet live bij het wijzigen van <strong>CSS of HTML bestanden</strong>. Wijzigingen aan JavaScript bestanden worden automatisch herladen wanneer je bewaart.<br /><br />(Je zal dit bericht slechts eenmaal zien.)",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "Voor meer informatie, zie <a href='{0}' title='{0}'>oplossen van Live Voorbeeld verbindingsproblemen</a>.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "Live Voorbeeld",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "Live Voorbeeld: Bezig met verbinden…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "Live Voorbeeld: Initialiseren…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "Verbreek verbinding met Live Voorbeeld",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "Live Voorbeeld (sla bestand op om te verversen)",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "Selecteer bestand om live voorbeeld te bekijken",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "Pagina opnieuw laden",
  "LIVE_DEV_CLICK_POPOUT": "Popout Live Preview naar nieuw venster",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "Pin op Voorbeeldpagina losmaken",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "Live Voorbeeld (niet bezig met updaten door een verkeerde syntax)",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "Live Voorbeeld is geannuleerd omdat de developer tools in de browser zijn geopend",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "Live Voorbeeld is geannuleerd omdat de pagina gesloten werd in de browser",
  "LIVE_DEV_NAVIGATED_AWAY": "Live Voorbeeld is geannuleerd omdat de browser navigeerde naar een pagina die geen deel uit maakt van het huidige project",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "Live Voorbeeld is geannuleerd om een onbekende reden ({0})",
  "SAVE_CLOSE_TITLE": "Opslaan van wijzigingen",
  "SAVE_CLOSE_MESSAGE": "Wil je de wijzigingen opslaan die je maakte in het document <span class='dialog-filename'>{0}</span>?",
  "SAVE_CLOSE_MULTI_MESSAGE": "Wil je je wijzigingen van de volgende bestanden opslaan?",
  "EXT_MODIFIED_TITLE": "Externe wijzigingen",
  "CONFIRM_DELETE_TITLE": "Bevestig verwijderen",
  "CONFIRM_FILE_DELETE": "Weet je zeker dat je het bestand <span class='dialog-filename'>{0}</span> wilt verwijderen?",
  "CONFIRM_FOLDER_DELETE": "Ben je zeker dat je de map <span class='dialog-filename'>{0}</span> wil verwijderen?",
  "FILE_DELETED_TITLE": "Bestand verwijderd",
  "EXT_MODIFIED_WARNING": "<span class='dialog-filename'>{0}</span> is gewijzigd op de schijf buiten {APP_NAME}.<br /><br />Wil je het bestand overschrijven evenals de wijzigingen buiten {APP_NAME} om?",
  "EXT_MODIFIED_MESSAGE": "<span class='dialog-filename'>{0}</span> is gewijzigd op de schijf, maar heeft ook onbewaarde wijzigingen in {APP_NAME}.<br /><br />Welke versie wil je behouden?",
  "EXT_DELETED_MESSAGE": "<span class='dialog-filename'>{0}</span> is verwijderd op de schijf, maar heeft onbewaarde wijzigingen in {APP_NAME}.<br /><br />Wil je je wijzigingen behouden?",
  "WINDOW_UNLOAD_WARNING": "Weet je zeker dat je naar een andere URL wilt navigeren en haakjes wilt verlaten?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "Je hebt nog niet opgeslagen wijzigingen! Weet je zeker dat je naar een andere URL wilt navigeren en haakjes wilt verlaten?",
  "DONE": "Gedaan",
  "OK": "OK",
  "CANCEL": "Annuleren",
  "DONT_SAVE": "Niet opslaan",
  "SAVE": "Opslaan",
  "SAVE_AS": "Opslaan als…",
  "SAVE_AND_OVERWRITE": "Overschrijf",
  "DELETE": "Verwijder",
  "BUTTON_YES": "Ja",
  "BUTTON_NO": "Nee",
  "FIND_MATCH_INDEX": "{0} van {1}",
  "FIND_NO_RESULTS": "Geen resultaten",
  "FIND_QUERY_PLACEHOLDER": "Zoek…",
  "FIND_HISTORY_MAX_COUNT": "Maximaal aantal zoekitems in de zoekgeschiedenis",
  "REPLACE_PLACEHOLDER": "Vervang met…",
  "BUTTON_REPLACE_ALL": "Alle…",
  "BUTTON_REPLACE_BATCH": "Batch...",
  "BUTTON_REPLACE_ALL_IN_FILES": "Vervang…",
  "BUTTON_REPLACE": "Vervang",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "Volgende overeenkomst",
  "BUTTON_PREV_HINT": "Vorige overeenkomst",
  "BUTTON_CASESENSITIVE_HINT": "Hoofdlettergevoelig",
  "BUTTON_REGEXP_HINT": "Reguliere expressie",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "Vervang zonder herstellen",
  "REPLACE_WITHOUT_UNDO_WARNING": "Omdat meer dan {0} bestanden moeten worden veranderd, {APP_NAME} zal ongeopende bestanden op de schijf aanpassen.<br /> Wijzigingen kunnen niet meer ongedaan worden gemaakt in die bestanden.",
  "BUTTON_REPLACE_WITHOUT_UNDO": "Vervang zonder herstellen",
  "OPEN_FILE": "Bestand openen",
  "SAVE_FILE_AS": "Bestand opslaan",
  "CHOOSE_FOLDER": "Kies een map",
  "RELEASE_NOTES": "Nieuw in deze versie",
  "NO_UPDATE_TITLE": "Je bent up to date!",
  "NO_UPDATE_MESSAGE": "Je werkt met de laatste versie van {APP_NAME}.",
  "FIND_REPLACE_TITLE_LABEL": "Vervang",
  "FIND_REPLACE_TITLE_WITH": "met",
  "FIND_TITLE_LABEL": "Gevonden",
  "FIND_TITLE_SUMMARY": "&mdash; {0} {1} {2} in {3}",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "in <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_NO_SCOPE": "in project",
  "FIND_IN_FILES_ZERO_FILES": "Filter sluit alle bestanden uit {0}",
  "FIND_IN_FILES_FILE": "bestand",
  "FIND_IN_FILES_FILES": "bestanden",
  "FIND_IN_FILES_MATCH": "overeenkomst",
  "FIND_IN_FILES_MATCHES": "overeenkomsten",
  "FIND_IN_FILES_MORE_THAN": "Meer dan ",
  "FIND_IN_FILES_PAGING": "{0}&mdash;{1}",
  "FIND_IN_FILES_FILE_PATH": "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "Klik Ctrl/Cmd om alles in/uit te vouwen",
  "FIND_IN_FILES_INDEXING": "Indexering voor Direct zoeken...",
  "REPLACE_IN_FILES_ERRORS_TITLE": "Vervang fouten",
  "REPLACE_IN_FILES_ERRORS": "De volgende bestanden zijn niet aangepast omdat deze na het zoeken zijn aangepast of niet bewerkt kunnen worden.",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "Probleem bij het ophalen van update-informatie",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "Er is een fout opgetreden bij het ophalen van de laatste update-informatie van de server. Zorg ervoor dat je verbonden bent met het internet en probeer opnieuw.",
  "NEW_FILE_FILTER": "Nieuwe set uitgesloten bestanden…",
  "CLEAR_FILE_FILTER": "Sluit geen bestanden uit",
  "NO_FILE_FILTER": "Geen uitgesloten bestanden",
  "EXCLUDE_FILE_FILTER": "Sluit {0} uit",
  "EDIT_FILE_FILTER": "Bewerk…",
  "FILE_FILTER_DIALOG": "Bewerk set uitgesloten bestanden",
  "FILE_FILTER_INSTRUCTIONS": "Sluit bestanden en mappen uit met de volgende teksten/deelteksten of <a href='{0}' title='{0}'>wildcards</a>. Plaats elke tekst op een nieuwe regel.",
  "FILTER_NAME_PLACEHOLDER": "Geef deze set een naam (optioneel)",
  "FILTER_NAME_REMAINING": "{0} resterende tekens",
  "FILE_FILTER_CLIPPED_SUFFIX": "en {0} meer",
  "FILTER_COUNTING_FILES": "Bestanden tellen…",
  "FILTER_FILE_COUNT": "Sta {0} toe van {1} bestanden {2}",
  "FILTER_FILE_COUNT_ALL": "Sta alle {0} bestanden toe {1}",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "Quick Edit is niet beschikbaar voor huidige cursorpositie.",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "CSS Quick Edit: plaats cursor op een enkele class naam.",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "CSS Quick Edit: class attribuut is incompleet.",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "CSS Quick Edit: id attribuut is incompleet.",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "CSS Quick Edit: plaats cursor in tag, class of id.",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "CSS Timing Function Quick Edit: syntax onjuist",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "JS Quick Edit: plaats cursor in functienaam.",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "Geen snelle documentatie beschikbaar voor huidige cursorpositie.",
  "PROJECT_LOADING": "Laden…",
  "UNTITLED": "Naamloos",
  "WORKING_FILES": "Geopend",
  "TOP": "Boven",
  "BOTTOM": "Beneden",
  "LEFT": "Links",
  "RIGHT": "Rechts",
  "CMD_SPLITVIEW_NONE": "Niet splitsen",
  "CMD_SPLITVIEW_VERTICAL": "Verticaal splitsen",
  "CMD_SPLITVIEW_HORIZONTAL": "Horizontaal splitsen",
  "SPLITVIEW_MENU_TOOLTIP": "Splits de editor verticaal of horizontaal",
  "GEAR_MENU_TOOLTIP": "Configureer bestanden",
  "SPLITVIEW_INFO_TITLE": "Al geopend",
  "SPLITVIEW_MULTIPANE_WARNING": "Dit bestand is al geopend in een ander paneel. {APP_NAME} zal spoedig ondersteuning bieden aan het openen van hetzelfde bestand in meerdere panelen. Voor nu wordt het bestand weergegeven in het paneel waarin het al geopend is.<br /><br />(Dit is een eenmalige melding.)",
  "KEYBOARD_CTRL": "Ctrl",
  "KEYBOARD_SHIFT": "Shift",
  "KEYBOARD_SPACE": "Space",
  "KEYBOARD_PAGE_UP": "Pagina omhoog",
  "KEYBOARD_PAGE_DOWN": "Pagina omlaag",
  "KEYBOARD_HOME": "Home",
  "KEYBOARD_END": "Einde",
  "KEYBOARD_INSERT": "Invoegen",
  "KEYBOARD_DELETE": "Verwijder",
  "STATUSBAR_CURSOR_POSITION": "Regel {0}, Kolom {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": " — {0} kolom geselecteerd",
  "STATUSBAR_SELECTION_CH_PLURAL": " — {0} kolommen geselecteerd",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " — {0} regel geselecteerd",
  "STATUSBAR_SELECTION_LINE_PLURAL": " — {0} regels geselecteerd",
  "STATUSBAR_SELECTION_MULTIPLE": " — {0} selecties",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "Klik om de indentatie te veranderen naar spaties",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "Klik om de indentatie te veranderen naar tabs",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "Klik om het aantal spaties bij indentatie te veranderen",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "Klik om de breedte van het tab karakter te veranderen",
  "STATUSBAR_SPACES": "Spaties:",
  "STATUSBAR_TAB_SIZE": "Tab Grootte:",
  "STATUSBAR_LINE_COUNT_SINGULAR": "— {0} Regel",
  "STATUSBAR_LINE_COUNT_PLURAL": "— {0} Regels",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "Extensies uitgeschakeld",
  "STATUSBAR_INSERT": "INS",
  "STATUSBAR_OVERWRITE": "OVR",
  "STATUSBAR_INSOVR_TOOLTIP": "Klik om de cursor te wisselen tussen Insert (INS) en Overwrite (OVR) mode.",
  "STATUSBAR_LANG_TOOLTIP": "Klik om bestandstype te veranderen.",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. Klik om foutenpaneel te openen.",
  "STATUSBAR_DEFAULT_LANG": "(default)",
  "STATUSBAR_SET_DEFAULT_LANG": "Standaard voor .{0} bestanden",
  "STATUSBAR_ENCODING_TOOLTIP": "Selecteer de codering",
  "ERRORS_PANEL_TITLE_MULTIPLE": "{0} Fouten",
  "SINGLE_ERROR": "1 {0} Fout",
  "MULTIPLE_ERRORS": "{1} {0} Fouten",
  "NO_ERRORS": "Geen {0} fouten - goed zo!",
  "NO_ERRORS_MULTIPLE_PROVIDER": "Geen fouten gevonden - goed zo!",
  "LINT_DISABLED": "Linting is uitgeschakeld",
  "NO_LINT_AVAILABLE": "Er is geen linter beschikbaar voor {0}",
  "NOTHING_TO_LINT": "Niets om te linten",
  "LINTER_TIMED_OUT": "{0} is gestopt na wachten voor {1} ms",
  "LINTER_FAILED": "{0} is gestopt met fout: {1}",
  "FILE_MENU": "Bestand",
  "CMD_FILE_NEW_UNTITLED": "Nieuw",
  "CMD_FILE_NEW": "Nieuw bestand",
  "CMD_PROJECT_NEW": "Nieuw project",
  "CMD_FILE_NEW_FOLDER": "Nieuwe map",
  "CMD_FILE_OPEN": "Bestand openen…",
  "CMD_RECENT_FILES_OPEN": "Recent openen...",
  "CMD_ADD_TO_WORKING_SET": "Voeg toe aan werkset",
  "CMD_OPEN_DROPPED_FILES": "Open gesloten bestanden",
  "CMD_OPEN_FOLDER": "Open map…",
  "CMD_FILE_CLOSE": "Sluiten",
  "CMD_FILE_CLOSE_ALL": "Alles sluiten",
  "CMD_FILE_CLOSE_LIST": "Sluit lijsten",
  "CMD_FILE_CLOSE_OTHERS": "Sluit anderen",
  "CMD_FILE_CLOSE_ABOVE": "Sluit bestanden boven",
  "CMD_FILE_CLOSE_BELOW": "Sluit bestanden onder",
  "CMD_FILE_SAVE": "Opslaan",
  "CMD_FILE_SAVE_ALL": "Alles opslaan",
  "CMD_FILE_SAVE_AS": "Opslaan als…",
  "CMD_LIVE_FILE_PREVIEW": "Live Voorbeeld",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "Experimentele versie Live Voorbeeld",
  "CMD_RELOAD_LIVE_PREVIEW": "Forceer herladen Live Voorbeeld",
  "CMD_PROJECT_SETTINGS": "Projectinstellingen…",
  "CMD_FILE_RENAME": "Bestand hernoemen",
  "CMD_FILE_DELETE": "Verwijder",
  "CMD_INSTALL_EXTENSION": "Installeer extensie…",
  "CMD_EXTENSION_MANAGER": "Extensiebeheer…",
  "CMD_FILE_REFRESH": "Ververs bestandsboom",
  "CMD_QUIT": "Stoppen",
  "CMD_EXIT": "Afsluiten",
  "EDIT_MENU": "Bewerken",
  "CMD_UNDO": "Herstel",
  "CMD_REDO": "Opnieuw",
  "CMD_CUT": "Knippen",
  "CMD_COPY": "Kopierën",
  "CMD_PASTE": "Plakken",
  "CMD_SELECT_ALL": "Alles selecteren",
  "CMD_SELECT_LINE": "Regel selecteren",
  "CMD_SPLIT_SEL_INTO_LINES": "Splits selectie in regels",
  "CMD_ADD_CUR_TO_NEXT_LINE": "Voeg cursor toe aan volgende regel",
  "CMD_ADD_CUR_TO_PREV_LINE": "Voeg cursor toe aan vorige regel",
  "CMD_INDENT": "Inspringen",
  "CMD_UNINDENT": "Inspringen verwijderen",
  "CMD_DUPLICATE": "Dupliceer",
  "CMD_DELETE_LINES": "Verwijder regel",
  "CMD_COMMENT": "Zet regel commentaar aan/uit",
  "CMD_BLOCK_COMMENT": "Zet blok commentaar aan/uit",
  "CMD_LINE_UP": "Verplaats regel naar boven",
  "CMD_LINE_DOWN": "Verplaats regel naar beneden",
  "CMD_OPEN_LINE_ABOVE": "Open regel boven",
  "CMD_OPEN_LINE_BELOW": "Open regel beneden",
  "CMD_TOGGLE_CLOSE_BRACKETS": "Automatisch accolades sluiten",
  "CMD_SHOW_CODE_HINTS": "Toon code hints",
  "FIND_MENU": "Zoek",
  "CMD_FIND": "Zoek",
  "CMD_FIND_NEXT": "Zoek volgende",
  "CMD_FIND_PREVIOUS": "Zoek vorige",
  "CMD_FIND_ALL_AND_SELECT": "Zoek alles en selecteer",
  "CMD_ADD_NEXT_MATCH": "Voeg eerstvolgende overeenkomst toe aan selectie",
  "CMD_SKIP_CURRENT_MATCH": "Sla-over en selecteer volgende overeenkomst",
  "CMD_FIND_IN_FILES": "Zoek in bestanden",
  "CMD_FIND_IN_SUBTREE": "Zoek in…",
  "CMD_REPLACE": "Vervang",
  "CMD_REPLACE_IN_FILES": "Vervang in bestanden",
  "CMD_REPLACE_IN_SUBTREE": "Vervang in…",
  "VIEW_MENU": "Beeld",
  "CMD_HIDE_SIDEBAR": "Verberg zijbalk",
  "CMD_SHOW_SIDEBAR": "Toon zijbalk",
  "CMD_TOGGLE_SIDEBAR": "Toggle Sidebar",
  "CMD_TOGGLE_PANELS": "Panelen schakelen",
  "CMD_TOGGLE_PURE_CODE": "Geen afleiding",
  "CMD_INCREASE_FONT_SIZE": "Vergroot lettertype",
  "CMD_DECREASE_FONT_SIZE": "Verklein lettertype",
  "CMD_RESTORE_FONT_SIZE": "Herstel lettertype",
  "CMD_SCROLL_LINE_UP": "Scroll regel naar Boven",
  "CMD_SCROLL_LINE_DOWN": "Scroll regel naar Beneden",
  "CMD_TOGGLE_LINE_NUMBERS": "Regelnummers",
  "CMD_TOGGLE_ACTIVE_LINE": "Markeer actieve regel",
  "CMD_TOGGLE_WORD_WRAP": "Word wrap",
  "CMD_LIVE_HIGHLIGHT": "Live voorbeeld markeren",
  "CMD_VIEW_TOGGLE_INSPECTION": "Lint bestanden bij opslaan",
  "CMD_WORKINGSET_SORT_BY_ADDED": "Sorteren op toegevoegd",
  "CMD_WORKINGSET_SORT_BY_NAME": "Sorteren op naam",
  "CMD_WORKINGSET_SORT_BY_TYPE": "Sorteren op type",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "Automatisch sorteren",
  "CMD_THEMES": "Thema's…",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "Zoekopdracht automatisch sluiten",
  "NAVIGATE_MENU": "Navigeer",
  "CMD_QUICK_OPEN": "Snel openen",
  "CMD_GOTO_LINE": "Ga naar regel…",
  "CMD_GOTO_DEFINITION": "Definitie snel zoeken",
  "CMD_GOTO_DEFINITION_PROJECT": "Snelle zoekdefinitie in project",
  "CMD_GOTO_FIRST_PROBLEM": "Ga naar de eerstvolgende fout/waarschuwing",
  "CMD_TOGGLE_QUICK_EDIT": "Snel wijzigen",
  "CMD_TOGGLE_QUICK_DOCS": "Snel naar documentatie",
  "CMD_QUICK_EDIT_PREV_MATCH": "Vorige overeenkomst",
  "CMD_QUICK_EDIT_NEXT_MATCH": "Volgende overeenkomst",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "Nieuwe regel",
  "CMD_NEXT_DOC": "Volgend document",
  "CMD_PREV_DOC": "Vorig document",
  "CMD_NAVIGATE_BACKWARD": "Achterwaarts navigeren",
  "CMD_NAVIGATE_FORWARD": "Voorwaarts navigeren",
  "CMD_NEXT_DOC_LIST_ORDER": "Volgende document in lijst",
  "CMD_PREV_DOC_LIST_ORDER": "Vorig document in lijst",
  "CMD_SHOW_IN_TREE": "Toon in bestandsboom",
  "CMD_SHOW_IN_EXPLORER": "Toon in Verkenner",
  "CMD_SHOW_IN_FINDER": "Toon in Finder",
  "CMD_SHOW_IN_OS": "Toon in besturingssysteem",
  "CMD_SWITCH_PANE_FOCUS": "Focus op schakelpaneel",
  "CMD_OPEN_VFS": "Virtueel bestandssysteem openen",
  "CMD_OPEN_VIRTUAL_SERVER": "Virtuele server openen",
  "HELP_MENU": "Help",
  "CMD_CHECK_FOR_UPDATE": "Controleer op updates",
  "CMD_HOW_TO_USE_BRACKETS": "Hoe gebruik je {APP_NAME}",
  "CMD_SUPPORT": "{APP_NAME} ondersteuning",
  "CMD_SUGGEST": "Stel een nieuwe functie voor",
  "CMD_RELEASE_NOTES": "Nieuw in deze versie",
  "CMD_GET_INVOLVED": "Doe mee",
  "CMD_SHOW_EXTENSIONS_FOLDER": "Toon de map met extensies",
  "CMD_HEALTH_DATA_STATISTICS": "Statusrapport",
  "CMD_HOMEPAGE": "{APP_TITLE} homepage",
  "CMD_TWITTER": "{TWITTER_NAME} op Twitter",
  "CMD_ABOUT": "Over {APP_TITLE}",
  "CMD_OPEN_PREFERENCES": "Open configuratiebestand",
  "CMD_OPEN_KEYMAP": "Open gebruiker toetsenbordinstellingen",
  "EXPERIMENTAL_BUILD": "experimentele build",
  "RELEASE_BUILD": "build",
  "DEVELOPMENT_BUILD": "development build",
  "PRERELEASE_BUILD": "prerelease-build",
  "RELOAD_FROM_DISK": "Opnieuw laden van schijf",
  "KEEP_CHANGES_IN_EDITOR": "Behoud veranderingen in editor",
  "CLOSE_DONT_SAVE": "Sluit (niet bewaren)",
  "RELAUNCH_CHROME": "Herstart Chrome",
  "ABOUT": "Over",
  "CLOSE": "Sluiten",
  "ABOUT_TEXT_LINE1": "Release {VERSION_MAJOR}. {VERSION_MINOR} {BUILD_TYPE} {VERSION}",
  "ABOUT_TEXT_BUILD_TIMESTAMP": "tijdstempel bouwen: ",
  "ABOUT_TEXT_LINE3": "Bibliotheken van derden die we gebruiken - <a href='https://github.com/phcode-dev/phoenix/tree/main/src/thirdparty/licences'>Licenties en Attributies</a>. ",
  "ABOUT_TEXT_LINE4": "Documentatie en bron op <a href='https://github.com/phcode-dev/phoenix/'>https://github.com/phcode-dev/phoenix/</a>",
  "ABOUT_TEXT_LINE5": "Gemaakt met ❤ en JavaScript door:",
  "ABOUT_TEXT_LINE6": "Veel mensen (maar we hebben momenteel problemen met het laden van die gegevens).",
  "ABOUT_TEXT_MDN_DOCS": "MDN Docs en het MDN logo zijn gelicentieerd onder een Creative Commons Attribution licentie, <a href='{MDN_DOCS_LICENSE}'>CC-BY-SA 2.5 Unported</a>.",
  "UPDATE_NOTIFICATION_TOOLTIP": "Er is een nieuwe versie van {APP_NAME} beschikbaar! Klik hier voor details.",
  "UPDATE_AVAILABLE_TITLE": "Update beschikbaar",
  "UPDATE_MESSAGE": "Hey, er is een nieuwe versie van {APP_NAME} beschikbaar. Hier zijn een aantal van de nieuwe functies:",
  "GET_IT_NOW": "Download het nu!",
  "PROJECT_SETTINGS_TITLE": "Projectinstellingen voor: {0}",
  "PROJECT_SETTING_BASE_URL": "Live voorbeeld begin URL",
  "PROJECT_SETTING_BASE_URL_HINT": "Gebruik url als http://localhost:8000/ om als lokale server te gebruiken.",
  "BASEURL_ERROR_INVALID_PROTOCOL": "Het {0} protocol wordt niet ondersteund door Live Voorbeeld&mdash;gebruik http: of https: .",
  "BASEURL_ERROR_SEARCH_DISALLOWED": "De start URL kan geen zoekparameters bevatten zoals \"{0}\".",
  "BASEURL_ERROR_HASH_DISALLOWED": "De start URL kan geen hashes bevatten zoals \"{0}\".",
  "BASEURL_ERROR_INVALID_CHAR": "Speciale karakters zoals '{0}' moeten %-geëncodeerd zijn.",
  "BASEURL_ERROR_UNKNOWN_ERROR": "Onbekende fout bij het parsen van de begin URL",
  "EMPTY_VIEW_HEADER": "<em>Open een bestand wanneer dit paneel actief is</em>",
  "FLIPVIEW_BTN_TOOLTIP": "Draai deze weergave om naar het {0} -venster",
  "CURRENT_THEME": "Huidig thema",
  "USE_THEME_SCROLLBARS": "Scrollbalken van thema",
  "FONT_SIZE": "Lettergrootte",
  "FONT_FAMILY": "Lettertype(s)",
  "THEMES_SETTINGS": "Thema-instellingen",
  "BUTTON_NEW_RULE": "Nieuwe regel",
  "INSTALL": "Installeren",
  "UPDATE": "Update",
  "REMOVE": "Verwijder",
  "DISABLE": "Uitschakelen",
  "ENABLE": "Inschakelen",
  "OVERWRITE": "Overschrijf",
  "CANT_REMOVE_DEV": "Extensies in de \"dev\" map moeten met de hand verwijderd worden.",
  "CANT_UPDATE": "De update is niet compatibel met deze versie van {APP_NAME}.",
  "CANT_UPDATE_DEV": "Extensies in de \"dev\" map kunnen niet automatisch geupdate worden.",
  "INSTALL_EXTENSION_TITLE": "Installeer extensie",
  "UPDATE_EXTENSION_TITLE": "Update extensie",
  "INSTALL_EXTENSION_LABEL": "Extensie URL",
  "INSTALL_EXTENSION_HINT": "URL van het zip bestand of de GitHub repo van de extensie",
  "INSTALLING_FROM": "Bezig met installeren van {0}…",
  "INSTALL_SUCCEEDED": "Installatie succesvol!",
  "INSTALL_FAILED": "Installatie mislukt.",
  "CANCELING_INSTALL": "Bezig met annuleren…",
  "CANCELING_HUNG": "Het annuleren van de installatie duurt lang. Een intern probleem kan zijn opgetreden.",
  "INSTALL_CANCELED": "Installatie geannuleerd.",
  "VIEW_COMPLETE_DESCRIPTION": "Laat volledige beschrijving zien",
  "VIEW_TRUNCATED_DESCRIPTION": "Laat afgekorte beschrijving zien",
  "SORT_EXTENSION_METHOD": "Extensies sorteren met DownloadCount of PublishedDate",
  "INVALID_ZIP_FILE": "De gedownloade inhoud is geen geldig zip bestand.",
  "MISSING_PACKAGE_JSON": "Het pakket bevat geen pakket.json-bestand.",
  "INVALID_PACKAGE_JSON": "Het package.json bestand is niet geldig (Fout: {0}).",
  "MISSING_PACKAGE_NAME": "Het package.json specifieert geen pakket naam.",
  "BAD_PACKAGE_NAME": "{0} is een ongeldige pakket naam.",
  "MISSING_PACKAGE_VERSION": "Het package.json bestand specifieert geen geldige pakket versie.",
  "INVALID_VERSION_NUMBER": "Het pakket versienummer ({0}) is ongeldig.",
  "INVALID_BRACKETS_VERSION": "De {APP_NAME} compatibiliteit string ({0}) is ongeldig.",
  "DISALLOWED_WORDS": "De woorden ({1}) zijn niet toegelaten in het {0} veld.",
  "NPM_INSTALL_FAILED": "npm install commando mislukt: {0}",
  "API_NOT_COMPATIBLE": "De extensie is niet compatibel met deze versie van {APP_NAME}. Het werd geïnstalleerd in de map met uitgeschakelde extensies.",
  "MISSING_MAIN": "Het pakket heeft geen main.js bestand.",
  "EXTENSION_ALREADY_INSTALLED": "Het installeren van dit pakket zal een vroeger geïnstalleerde extensie overschrijven. Overschrijf de oudere extensie?",
  "EXTENSION_SAME_VERSION": "Dit pakket is dezelfde versie als degene die op dit moment is geïnstalleerd. Overschrijf de bestaande installatie?",
  "EXTENSION_OLDER_VERSION": "Dit pakket is versie {0} welke ouder is dan de op dit moment geïnstalleerde ({1}). Overschrijf de bestaande installatie?",
  "DOWNLOAD_ID_IN_USE": "Interne fout: download ID is reeds in gebruik.",
  "NO_SERVER_RESPONSE": "Kan niet verbinden met de server.",
  "BAD_HTTP_STATUS": "Bestand niet worden gevonden op server (HTTP {0}).",
  "CANNOT_WRITE_TEMP": "Onmogelijk om het gedownloade bestand op te slaan naar een tijdelijk bestand.",
  "ERROR_LOADING": "De extensie ondervond een probleem bij het opstarten.",
  "MALFORMED_URL": "De URL is ongeldig. Controleer of deze correct is ingevoerd.",
  "UNSUPPORTED_PROTOCOL": "De URL moet een http of https URL zijn.",
  "UNKNOWN_ERROR": "Onbekende interne fout.",
  "EXTENSION_MANAGER_TITLE": "Extensiebeheer",
  "EXTENSION_MANAGER_ERROR_LOAD": "Er is momenteel geen toegang mogelijk tot het extensieregister. Probeer later opnieuw.",
  "INSTALL_EXTENSION_DRAG": "Sleep .zip hier of",
  "INSTALL_EXTENSION_DROP": "Sleep .zip hier voor installatie",
  "INSTALL_EXTENSION_DROP_ERROR": "Installatie/update afgebroken vanwege de volgende fouten:",
  "INSTALL_FROM_URL": "installeer van URL…",
  "INSTALL_EXTENSION_VALIDATING": "Validating…",
  "EXTENSION_AUTHOR": "Auteur",
  "EXTENSION_DATE": "Datum",
  "EXTENSION_INCOMPATIBLE_NEWER": "Deze extensie vereist een nieuwere versie van {APP_NAME}.",
  "EXTENSION_INCOMPATIBLE_OLDER": "Deze extensie werkt momenteel enkel met oudere versies van {APP_NAME}.",
  "EXTENSION_LATEST_INCOMPATIBLE_NEWER": "Versie {0} van deze extensie vereist een nieuwere versie van {APP_NAME}. Je kan wel de oudere versie {1} installeren.",
  "EXTENSION_LATEST_INCOMPATIBLE_OLDER": "Versie {0} van deze extensie werkt alleen met oudere versies van {APP_NAME}. Je kan wel de oudere versie {1} installeren.",
  "EXTENSION_NO_DESCRIPTION": "Geen beschrijving",
  "EXTENSION_MORE_INFO": "Meer info...",
  "EXTENSION_ERROR": "Extensie fout",
  "EXTENSION_KEYWORDS": "Sleutelwoorden",
  "EXTENSION_TRANSLATED_USER_LANG": "Vertaalt in {0} talen, inclusief de jouwe",
  "EXTENSION_TRANSLATED_GENERAL": "Vertaalt in {0} talen",
  "EXTENSION_TRANSLATED_LANGS": "Deze extensie is vertaald in de volgende talen: {0}",
  "EXTENSION_INSTALLED": "Geïnstalleerd",
  "EXTENSION_UPDATE_INSTALLED": "Deze extensie is gedownload en zal geïnstalleerd worden wanneer je {APP_NAME} stopt.",
  "EXTENSION_SEARCH_PLACEHOLDER": "Zoek",
  "EXTENSION_MORE_INFO_LINK": "Meer",
  "BROWSE_EXTENSIONS": "Blader door extensies",
  "EXTENSION_MANAGER_REMOVE": "Verwijder extensie",
  "EXTENSION_MANAGER_REMOVE_ERROR": "Onmogelijk om een of meerdere extensies te verwijderen: {0}. {APP_NAME} zal nog steeds stoppen.",
  "EXTENSION_MANAGER_UPDATE": "Update extensie",
  "EXTENSION_MANAGER_UPDATE_ERROR": "Onmogelijk om een of meerdere extensies te updaten: {0}. {APP_NAME} zal nog steeds stoppen.",
  "EXTENSION_MANAGER_DISABLE": "Uitbreiding uitschakelen",
  "EXTENSION_MANAGER_DISABLE_ERROR": "Kan een of meer extensies niet uitschakelen: {0}. {APP_NAME} wordt nog steeds opnieuw geladen.",
  "MARKED_FOR_REMOVAL": "Aangeduid voor verwijder",
  "UNDO_REMOVE": "Herstel",
  "MARKED_FOR_UPDATE": "Aangeduid voor update",
  "UNDO_UPDATE": "Herstel",
  "MARKED_FOR_DISABLING": "Gemarkeerd om uit te schakelen",
  "UNDO_DISABLE": "Herstel",
  "CHANGE_AND_RELOAD_TITLE": "Wijzig extensies",
  "CHANGE_AND_RELOAD_MESSAGE": "Om de aangeduidde extensie te updaten of te verwijderen, moet je {APP_NAME} stoppen en herstarten. Er zal gevraagd worden alle onbewaarde wijzigingen op te slaan.",
  "REMOVE_AND_RELOAD": "Verwijder extensies en herladen",
  "CHANGE_AND_RELOAD": "Wijzig extensies en herladen",
  "UPDATE_AND_RELOAD": "Update extensies en herladen",
  "DISABLE_AND_RELOAD": "Uitbreidingen uitschakelen en opnieuw laden",
  "PROCESSING_EXTENSIONS": "Verwerken van wijzigingen aan extensie…",
  "EXTENSION_NOT_INSTALLED": "Kon de extensie {0} niet verwijderen omdat deze niet is geïnstalleerd",
  "NO_EXTENSIONS": "Geen extensies geïnstalleerd.<br>Klik op de Beschikbaar tab hierboven om te starten.",
  "NO_EXTENSION_MATCHES": "Geen extensies komen overeen met je zoekopdracht.",
  "REGISTRY_SANITY_CHECK_WARNING": "Wees voorzichtig bij het installeren van extensies van een onbekende bron.",
  "EXTENSIONS_INSTALLED_TITLE": "Geïnstalleerd",
  "EXTENSIONS_DEFAULT_TITLE": "Standaard",
  "EXTENSIONS_AVAILABLE_TITLE": "Beschikbaar",
  "EXTENSIONS_THEMES_TITLE": "Thema's",
  "EXTENSIONS_UPDATES_TITLE": "Updates",
  "EXTENSIONS_LAST_UPDATED": "Laatst bijgewerkt",
  "EXTENSIONS_DOWNLOADS": "Downloads",
  "INLINE_EDITOR_NO_MATCHES": "Geen overeenkomsten beschikbaar.",
  "INLINE_EDITOR_HIDDEN_MATCHES": "Alle overeenkomsten zijn samengevouwen. Vouw alle bestanden uit in het overzicht rechts om overeenkomsten te zien.",
  "CSS_QUICK_EDIT_NO_MATCHES": "Er zijn geen bestaande CSS regels die overeenkomsten met jouw selectie.<br> Klik \"Nieuwe regel\" om te maken.",
  "CSS_QUICK_EDIT_NO_STYLESHEETS": "Er zijn geen stylesheets in je project.<br>Maak er een om CSS regels toe te voegen.",
  "IMAGE_VIEWER_LARGEST_ICON": "meest grote",
  "UNIT_PIXELS": "pixels",
  "DEBUG_MENU": "Debug",
  "ERRORS": "fouten",
  "CMD_SHOW_DEV_TOOLS": "Tools voor ontwikkelaars weergeven",
  "CMD_REFRESH_WINDOW": "Laad {APP_NAME} opnieuw",
  "CMD_RELOAD_WITHOUT_USER_EXTS": "Laad opnieuw zonder extensies",
  "CMD_NEW_BRACKETS_WINDOW": "Nieuw {APP_NAME} venster",
  "CMD_LAUNCH_SCRIPT_MAC": "Installeer {APP_NAME} in de opdrachtprompt",
  "CMD_SWITCH_LANGUAGE": "Wijzig taal",
  "CMD_RUN_UNIT_TESTS": "Start testen",
  "CMD_SHOW_PERF_DATA": "Toon prestatiedata",
  "CMD_ENABLE_LOGGING": "Gedetailleerde logboeken inschakelen",
  "CMD_OPEN_BRACKETS_SOURCE": "Open broncode van {APP_NAME}",
  "CREATING_LAUNCH_SCRIPT_TITLE": "{APP_NAME} Command Line Shortcut",
  "ERROR_CREATING_LAUNCH_SCRIPT": "Er is een fout opgetreden bij het installeren van de opdrachtprompt snelkoppeling. Kijk op <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting'>deze pagina</a> voor mogelijke foutoplossing.<br/><br/>Reden: {0}",
  "ERROR_CLTOOLS_RMFAILED": "Niet mogelijk om bestaande symlink <code>/usr/local/bin/brackets</code> te verwijderen.",
  "ERROR_CLTOOLS_MKDIRFAILED": "Niet mogelijk om map <code>/usr/local/bin</code> te maken.",
  "ERROR_CLTOOLS_LNFAILED": "Niet mogelijk om symlink <code>/usr/local/bin/brackets</code> te maken.",
  "ERROR_CLTOOLS_SERVFAILED": "Interne fout.",
  "ERROR_CLTOOLS_NOTSUPPORTED": "Koppeling met opdrachtprompt is niet beschikbaar op dit OS.",
  "LAUNCH_SCRIPT_CREATE_SUCCESS": "Gelukt! Je kunt {APP_NAME} nu makkelijk starten vanaf de opdrachtprompt. Type <code>brackets myFile.txt</code> om een bestand te openen of <code>brackets myFolder</code> om van project te wisselen. <br/><br/><a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments'>Klik hier</a> voor meer informatie over het gebruik van {APP_NAME} via de opdrachtprompt (in het Engels).",
  "LANGUAGE_TITLE": "Wijzig taal",
  "LANGUAGE_MESSAGE": "Taal:",
  "LANGUAGE_SUBMIT": "{APP_NAME} opnieuw laden",
  "LANGUAGE_CANCEL": "Annuleren",
  "LANGUAGE_SYSTEM_DEFAULT": "Systeemvoorkeuren",
  "HEALTH_DATA_NOTIFICATION": "Statusrapport instellingen",
  "HEALTH_FIRST_POPUP_TITLE": "{APP_NAME} statusrapport",
  "HEALTH_DATA_DO_TRACK": "Deel anoniem informatie over hoe je {APP_NAME} gebruikt.",
  "HEALTH_DATA_NOTIFICATION_MESSAGE": "Om {APP_NAME} te verbeteren, wordt er periodiek <strong>(anoniem)</strong> beperkt aantal statistieken verzonden naar Adobe over hoe je {APP_NAME} gebruikt. Deze informatie helpt ons prioriteit te geven aan bepaalde functies, het vinden van fouten in de software en problemen in het gebruik zichtbaar te maken.<br><br>Je kan de data bekijken of ervoor kiezen om geen data te delen via <strong>Help > Statusrapport</strong>. <br><br><a href='https://github.com/adobe/brackets/wiki/Health-Data'>Lees meer over het {APP_NAME} statusrapport (Engels)</a>",
  "HEALTH_DATA_PREVIEW": "{APP_NAME} statusrapport",
  "HEALTH_DATA_PREVIEW_INTRO": "<p>Om {APP_NAME} te verbeteren, wordt er periodiek <strong>(anoniem)</strong> beperkt aantal statistieken verzonden naar Adobe over hoe je {APP_NAME} gebruikt. Deze informatie helpt ons prioriteit te geven aan bepaalde functies, het vinden van fouten in de software en problemen in het gebruik zichtbaar te maken. <a href='https://github.com/adobe/brackets/wiki/Health-Data'>Lees meer over het {APP_NAME} statusrapport (Engels)</a> en hoe het bijdraagt aan de {APP_NAME} gemeenschap terwijl je privacy beschermd blijft.</p><p>Onder zie je een voorbeeld van de data die wordt verzonden bij het volgende statusrapport, <em>als</em> het is ingeschakeld.</p>",
  "INLINE_TIMING_EDITOR_TIME": "Tijd",
  "INLINE_TIMING_EDITOR_PROGRESSION": "Voortgang",
  "BEZIER_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd><kbd>←</kbd><kbd>→</kbd> Verplaats geselecteerde punt<br><kbd class='text'>Shift</kbd> Verplaats met 10 units<br><kbd class='text'>Tab</kbd> Verwissel punten",
  "STEPS_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd> Vergroot of verklein stappen<br><kbd>←</kbd><kbd>→</kbd> 'Start' of 'Einde'",
  "INLINE_TIMING_EDITOR_INVALID": "De oude waarde <code>{0}</code> is niet geldig, de weergegeven functie is veranderd naar <code>{1}</code>. Het bestand wordt bijgewerkt met de eerste aanpassing.",
  "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP": "Huidige kleur",
  "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP": "Originele kleur",
  "COLOR_EDITOR_RGBA_BUTTON_TIP": "RGBa formaat",
  "COLOR_EDITOR_HEX_BUTTON_TIP": "Hex formaat",
  "COLOR_EDITOR_HSLA_BUTTON_TIP": "HSLa formaat",
  "COLOR_EDITOR_0X_BUTTON_TIP": "Hex (0x) formaat",
  "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR": "{0} ({1} keer gebruikt)",
  "COLOR_EDITOR_USED_COLOR_TIP_PLURAL": "{0} ({1} keer gebruikt)",
  "CMD_JUMPTO_DEFINITION": "Ga naar definitie",
  "CMD_SHOW_PARAMETER_HINT": "Toon parameter hint",
  "NO_ARGUMENTS": "<geen parameters>",
  "DETECTED_EXCLUSION_TITLE": "JavaScript File Inference Problem",
  "DETECTED_EXCLUSION_INFO": "{APP_NAME} kwam in de problemen met het verwerken van <span class='dialog-filename'>{0}</span>.<br><br>Dit bestand wordt niet verder verwerkt voor \"code hints\", \"Jump to Definition\" of \"Quick Edit\". Om het bestand weer te activeren, open <code>brackets.json</code> in je project en bewerkt <code>jscodehints.detectedExclusions</code>.<br><br>Dit is vermoedelijk een bug in {APP_NAME}. Indien mogelijk kun je een kopie van het bestand sturen naar <a href='https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue'>\"rapporteer een bug\"</a> met een link naar het bestand.",
  "CMD_REFACTOR": "Refactor",
  "CMD_EXTRACTTO_VARIABLE": "Uitpakken naar variabele",
  "CMD_EXTRACTTO_FUNCTION": "Uitpakken naar functie",
  "ERROR_TERN_FAILED": "Kan geen gegevens van Tern krijgen",
  "ERROR_EXTRACTTO_VARIABLE_NOT_VALID": "Selectie vormt geen expressie",
  "ERROR_EXTRACTTO_FUNCTION_NOT_VALID": "Geselecteerd blok moet een reeks instructies of een expressie vertegenwoordigen",
  "ERROR_EXTRACTTO_VARIABLE_MULTICURSORS": "Uitpakken naar variabele werkt niet in multicursors",
  "ERROR_EXTRACTTO_FUNCTION_MULTICURSORS": "Extract to Function werkt niet in multicursors",
  "EXTRACTTO_FUNCTION_SELECT_SCOPE": "Kies het bereik van bestemming",
  "EXTRACTTO_VARIABLE_SELECT_EXPRESSION": "Selecteer een expressie",
  "CMD_REFACTORING_RENAME": "Bestand hernoemen",
  "CMD_REFACTORING_TRY_CATCH": "Wrap in Try Catch",
  "CMD_REFACTORING_CONDITION": "Wrap in conditie",
  "CMD_REFACTORING_GETTERS_SETTERS": "Getters/setters maken",
  "CMD_REFACTORING_ARROW_FUNCTION": "Converteren naar pijlfunctie",
  "DESCRIPTION_CODE_REFACTORING": "JavaScript-code-refactoring inschakelen/uitschakelen",
  "ERROR_TRY_CATCH": "Selecteer geldige code om in een Try-catch-blok te wikkelen",
  "ERROR_WRAP_IN_CONDITION": "Selecteer geldige code om in een Conditieblok te eindigen",
  "ERROR_ARROW_FUNCTION": "Plaats de cursor in een functie-expressie",
  "ERROR_GETTERS_SETTERS": "Plaats de cursor op een lid van een objectuitdrukking",
  "ERROR_RENAME_MULTICURSOR": "Kan de naam niet wijzigen bij gebruik van meerdere cursors",
  "ERROR_RENAME_QUICKEDIT": "Kan deze identifier niet hernoemen, omdat er elders buiten deze functie naar wordt verwezen",
  "ERROR_RENAME_GENERAL": "Kan geselecteerde tekst niet hernoemen",
  "JSLINT_NAME": "JSLint",
  "CMD_ENABLE_QUICK_VIEW": "Snel bekijken bij muis over",
  "CMD_TOGGLE_RECENT_PROJECTS": "Recente projecten",
  "DOCS_MORE_LINK": "Lees meer",
  "COLLAPSE_ALL": "Alles inklappen",
  "EXPAND_ALL": "Alles uitklappen",
  "COLLAPSE_CURRENT": "Huidige inklappen",
  "EXPAND_CURRENT": "Huidige uitklappen",
  "RECENT_FILES_DLG_HEADER": "Recente bestanden",
  "RECENT_FILES_DLG_CLEAR_BUTTON_LABEL": "Helder",
  "RECENT_FILES_DLG_CLEAR_BUTTON_TITLE": "Bestanden wissen die niet in de werkset staan",
  "DESCRIPTION_CLOSE_BRACKETS": "true om accolades, haakjes en haakjes automatisch te sluiten",
  "DESCRIPTION_CLOSE_OTHERS_ABOVE": "false om de „Close Others Above” uit het contextmenu Werkbestanden te verwijderen",
  "DESCRIPTION_CLOSE_OTHERS_BELOW": "false om de „Anderen hieronder sluiten” te verwijderen uit het contextmenu Werkbestanden",
  "DESCRIPTION_CLOSE_OTHERS": "false om de „Close Others” uit het contextmenu Werkbestanden te verwijderen",
  "DESCRIPTION_CLOSE_TAGS": "De opties voor het sluiten van tags instellen",
  "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS": "Een reeks tags die niet automatisch gesloten mogen worden",
  "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING": "Sluiten wanneer > van de openingstag is getypt",
  "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING": "Sluiten wanneer/van afsluitende tag wordt getypt",
  "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS": "Een array van tags die, wanneer geopend, een lege regel heeft",
  "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD": "true om altijd inklapbare sectiemarkeringen te genereren wanneer het inspringniveau verandert",
  "DESCRIPTION_CODE_FOLDING_ENABLED": "true om code vouwen mogelijk te maken",
  "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER": "true om markeringen voor het samenvouwen van secties alleen zichtbaar te maken wanneer u de muis over de goot beweegt",
  "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL": "Beperkt hoeveel niveaus diep Inklappen Alles van toepassing is",
  "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE": "Minimumregels voordat een inklapbaar sectiepictogram verschijnt",
  "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES": "true om samengevouwen secties te onthouden als u een bestand of project sluit en opnieuw opent",
  "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE": "true om het vouwen van code op geselecteerde tekst in de editor mogelijk te maken",
  "DESCRIPTION_DISABLED_DEFAULT_EXTENSIONS": "Standaardextensies die zijn uitgeschakeld",
  "DESCRIPTION_ATTR_HINTS": "Tips voor HTML-kenmerken inschakelen/uitschakelen",
  "DESCRIPTION_CSS_PROP_HINTS": "Tips voor eigenschappen van CSS/LESS/SCSS inschakelen/uitschakelen",
  "DESCRIPTION_JS_HINTS": "Tips voor JavaScript-code in-/uitschakelen",
  "DESCRIPTION_JS_HINTS_TYPE_DETAILS": "Gegevens over gegevenstypen inschakelen/uitschakelen in JavaScript-codehints",
  "DESCRIPTION_PREF_HINTS": "Code-hints voor voorkeuren inschakelen/uitschakelen",
  "DESCRIPTION_SPECIAL_CHAR_HINTS": "Tips voor HTML-entiteiten inschakelen/uitschakelen",
  "DESCRIPTION_SVG_HINTS": "Tips voor SVG-code inschakelen/uitschakelen",
  "DESCRIPTION_HTML_TAG_HINTS": "Tips voor HTML-tags inschakelen/uitschakelen",
  "DESCRIPTION_URL_CODE_HINTS": "URL-hints inschakelen/uitschakelen in HTML & CSS/MINDER/SCSS",
  "DESCRIPTION_DRAG_DROP_TEXT": "Drag & Drop-functionaliteit inschakelen/uitschakelen",
  "DESCRIPTION_HEALTH_DATA_TRACKING": "Het bijhouden van gezondheidsgegevens inschakelen",
  "DESCRIPTION_HIGHLIGHT_MATCHES": "Maakt het automatisch markeren van overeenkomende tekenreeksen in het hele document mogelijk",
  "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN": "Markeer alle tekenreeksen die overeenkomen met het token waarin de cursor zich momenteel bevindt (geen selectie nodig)",
  "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY": "Markeer alleen als selectie een volledig token is",
  "DESCRIPTION_INSERT_HINT_ON_TAB": "true om de momenteel geselecteerde codehint op het tabblad in te voegen",
  "DESCRIPTION_NO_HINTS_ON_DOT": "true om niet automatisch JS-codehints weer te geven wanneer. wordt getypt",
  "DESCRIPTION_JSLINT_OPTIONS": "Een object met de standaardopties voor JSLint",
  "DESCRIPTION_JSLINT_OPTIONS_ASS": "true om toewijzingsuitdrukkingen toe",
  "DESCRIPTION_JSLINT_OPTIONS_BITWISE": "true om bitsgewijze operators toe te staan",
  "DESCRIPTION_JSLINT_OPTIONS_BROWSER": "true als standaard browserglobals vooraf gedefinieerd moeten zijn",
  "DESCRIPTION_JSLINT_OPTIONS_CLOSURE": "true om Google Closure idiomen toe te staan",
  "DESCRIPTION_JSLINT_OPTIONS_CONTINUE": "true om de „continue” -verklaring toe te staan",
  "DESCRIPTION_JSLINT_OPTIONS_COUCH": "true als couchDB globals vooraf gedefinieerd moeten zijn",
  "DESCRIPTION_JSLINT_OPTIONS_DEBUG": "true om debugger-instructies toe te staan",
  "DESCRIPTION_JSLINT_OPTIONS_DEVEL": "true als browserglobals die nuttig zijn bij ontwikkeling vooraf gedefinieerd moeten zijn",
  "DESCRIPTION_JSLINT_OPTIONS_EQEQ": "true to allow == en! =",
  "DESCRIPTION_JSLINT_OPTIONS_ES6": "true als ES6-globalen vooraf moeten worden gedefinieerd",
  "DESCRIPTION_JSLINT_OPTIONS_EVIL": "true om eval mogelijk te maken",
  "DESCRIPTION_JSLINT_OPTIONS_FORIN": "true om ongefilterd „voor... in” toe te staan",
  "DESCRIPTION_JSLINT_OPTIONS_INDENT": "Een specifieke tabbreedte instellen",
  "DESCRIPTION_JSLINT_OPTIONS_MAXERR": "Het maximale aantal gerapporteerde waarschuwingen",
  "DESCRIPTION_JSLINT_OPTIONS_MAXLEN": "Het maximale aantal tekens in een regel",
  "DESCRIPTION_JSLINT_OPTIONS_NEWCAP": "true om constructeurs zonder hoofdletter toe te staan",
  "DESCRIPTION_JSLINT_OPTIONS_NODE": "true als Node.js globals vooraf gedefinieerd moeten zijn",
  "DESCRIPTION_JSLINT_OPTIONS_NOMEN": "true om bungelende onderstrepingstekens in identifiers toe te staan",
  "DESCRIPTION_JSLINT_OPTIONS_PASSFAIL": "true om te stoppen bij de eerste fout",
  "DESCRIPTION_JSLINT_OPTIONS_PLUSPLUS": "true om ++ en — toe te staan",
  "DESCRIPTION_JSLINT_OPTIONS_REGEXP": "true om toe te staan. en [^...]. in RegExp",
  "DESCRIPTION_JSLINT_OPTIONS_RHINO": "true als Rhino globals vooraf gedefinieerd moeten worden",
  "DESCRIPTION_JSLINT_OPTIONS_SLOPPY": "true om ontbrekende `use strict` pragma toe te staan",
  "DESCRIPTION_JSLINT_OPTIONS_STUPID": "true als blokkerende ('... Sync') methoden kunnen worden gebruikt.",
  "DESCRIPTION_JSLINT_OPTIONS_SUB": "true om inefficiënte abonnementen mogelijk te maken",
  "DESCRIPTION_JSLINT_OPTIONS_TODO": "true om TODO-opmerkingen toe te staan",
  "DESCRIPTION_JSLINT_OPTIONS_UNPARAM": "true om ongebruikte parameters toe te staan",
  "DESCRIPTION_JSLINT_OPTIONS_VARS": "true om meer dan 1 vars in een functie toe te staan",
  "DESCRIPTION_JSLINT_OPTIONS_WHITE": "true om witruimte-regels te negeren",
  "DESCRIPTION_LANGUAGE": "Taalspecifieke instellingen",
  "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS": "Extra toewijzingen van bestandsextensie naar taalnaam",
  "DESCRIPTION_LANGUAGE_FILE_NAMES": "Aanvullende toewijzingen van bestandsnaam naar taalnaam",
  "DESCRIPTION_LINEWISE_COPY_CUT": "Als u kopieert en knipt wanneer er geen selectie is, worden de hele regels met cursors gekopieerd of geknipt.",
  "DESCRIPTION_INPUT_STYLE": "Hiermee selecteert u de manier waarop CodeMirror omgaat met invoer en focus. Het kan tekstgebied zijn, wat de standaard is, of inhoudbewerkbaar, wat beter is voor schermlezers (onstabiel)",
  "DESCRIPTION_LINTING_ENABLED": "true om Code Inspection in te schakelen",
  "DESCRIPTION_ASYNC_TIMEOUT": "De tijd in milliseconden waarna asynchrone linters een time-out krijgen",
  "DESCRIPTION_LINTING_PREFER": "Array van linters die als eerste moeten worden uitgevoerd",
  "DESCRIPTION_LIVE_DEV_MULTIBROWSER": "true om experimentele Live Preview in te schakelen",
  "DESCRIPTION_USE_PREFERED_ONLY": "true to run providers gespecificeerd in linting.prefer only",
  "DESCRIPTION_MAX_CODE_HINTS": "Maximale codehints die in één keer worden weergegeven",
  "DESCRIPTION_PATH": "Pad-specifieke instellingen",
  "DESCRIPTION_PROXY": "De URL van de proxyserver die wordt gebruikt voor de installatie van extensies",
  "DESCRIPTION_SCROLL_PAST_END": "true om scrollen na het einde van het document mogelijk te maken",
  "DESCRIPTION_SHOW_CODE_HINTS": "false om alle codehints uit te schakelen",
  "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING": "Houdt de knipperende cursor zichtbaar wanneer u een tekstselectie hebt",
  "DESCRIPTION_SHOW_LINE_NUMBERS": "true om regelnummers weer te geven in een „goot” links van de code",
  "DESCRIPTION_SMART_INDENT": "Automatisch inspringen bij het maken van een nieuw blok",
  "DESCRIPTION_SOFT_TABS": "false om het gedrag van zachte tabbladen uit te schakelen",
  "DESCRIPTION_SORT_DIRECTORIES_FIRST": "true om de mappen eerst in de projectboom te sorteren",
  "DESCRIPTION_SPACE_UNITS": "Aantal spaties dat moet worden gebruikt voor inkepingen op basis van ruimte",
  "DESCRIPTION_STATIC_SERVER_PORT": "Poortnummer dat de ingebouwde server moet gebruiken voor Live Preview",
  "DESCRIPTION_STYLE_ACTIVE_LINE": "true om de achtergrondkleur van de lijn waarop de cursor staat te markeren",
  "DESCRIPTION_TAB_SIZE": "Aantal spaties dat moet worden weergegeven voor tabbladen",
  "DESCRIPTION_USE_TAB_CHAR": "true om tabbladen te gebruiken in plaats van spaties",
  "DESCRIPTION_UPPERCASE_COLORS": "true om hex-kleuren in hoofdletters te genereren in de Inline Color Editor",
  "DESCRIPTION_WORD_WRAP": "Omlooplijnen die de vensterbreedte overschrijden",
  "DESCRIPTION_SEARCH_AUTOHIDE": "Sluit de zoekopdracht zodra de editor is gefocust",
  "DESCRIPTION_DETECTED_EXCLUSIONS": "Een lijst met bestanden die zijn gedetecteerd om ervoor te zorgen dat Tern uit de hand loopt",
  "DESCRIPTION_INFERENCE_TIMEOUT": "De hoeveelheid tijd waarna Tern een time-out krijgt bij het proberen bestanden te begrijpen",
  "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR": "true om fouten in de statusbalk weer te geven",
  "DESCRIPTION_QUICK_VIEW_ENABLED": "true om Quick View in te schakelen",
  "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW": "true om voorbeelden van afbeeldingen weer te geven voor URL's die extensies missen",
  "DESCRIPTION_THEME": "Selecteer een {APP_NAME} -thema",
  "DESCRIPTION_USE_THEME_SCROLLBARS": "true om aangepaste schuifbalken toe te staan",
  "DESCRIPTION_LINTING_COLLAPSED": "true om pluispaneel in te klappen",
  "DESCRIPTION_FONT_FAMILY": "Lettertype-familie wijzigen",
  "DESCRIPTION_FONT_SIZE": "Lettergrootte wijzigen; bijv. 13px",
  "DESCRIPTION_FIND_IN_FILES_NODE": "true om op knooppunten gebaseerd zoeken mogelijk te maken",
  "DESCRIPTION_FIND_IN_FILES_INSTANT": "true om direct zoeken mogelijk te maken",
  "DESCRIPTION_FONT_SMOOTHING": "Alleen voor Mac: „subpixel-antialiased” om antialiasing van subpixels of „antialiasing” voor antialiasing op grijswaarden mogelijk te maken",
  "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW": "false om openingsvoorkeurenbestand in gesplitste weergave uit te schakelen",
  "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE": "false om het gebruikersvoorkeurenbestand te openen in het linker/bovenste deelvenster",
  "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED": "true om deelvensters samen te vouwen nadat het laatste bestand uit het deelvenster is gesloten via de knop voor het sluiten van de vensterkop",
  "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS": "Schakel in wanneer de knoppen voor sluiten en flip-view op de koptekst moeten worden weergegeven.",
  "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT": "/*\n * Dit is een alleen-lezen bestand met de ondersteunde voorkeuren\n * door {APP_NAME}.\n * Gebruik dit bestand als referentie om uw voorkeuren aan te passen\n * bestand „brackets.json” geopend in het andere paneel.\n * Voor meer informatie over het gebruik van voorkeuren binnen\n * {APP_NAME}, raadpleeg de webpagina op https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences\n */",
  "DEFAULT_PREFERENCES_JSON_DEFAULT": "Standaard",
  "DESCRIPTION_PURE_CODING_SURFACE": "true om de modus alleen code in te schakelen en alle andere UI-elementen in {APP_NAME} te verbergen",
  "DESCRIPTION_INDENT_LINE_COMMENT": "true om inspringen van regelopmerkingen mogelijk te maken",
  "DESCRIPTION_RECENT_FILES_NAV": "Navigatie in recente bestanden inschakelen/uitschakelen",
  "DESCRIPTION_LIVEDEV_WEBSOCKET_PORT": "Poort waarop WebSocket Server draait voor Live Preview",
  "DESCRIPTION_LIVE_DEV_HIGHLIGHT_SETTINGS": "Instellingen voor Live Preview Highlight",
  "DESCRIPTION_LIVEDEV_ENABLE_REVERSE_INSPECT": "false om live preview reverse inspection uit te schakelen",
  "DOWNLOAD_FAILED": "Het downloaden is mislukt.",
  "DOWNLOAD_COMPLETE": "Download compleet!",
  "UPDATE_SUCCESSFUL": "Update succesvol!",
  "UPDATE_FAILED": "Update is mislukt!",
  "VALIDATION_FAILED": "Validatie mislukt!",
  "INITIALISATION_FAILED": "Initialisatie is mislukt!",
  "CLEANUP_FAILED": "Opschonen is mislukt!",
  "WARNING_TYPE": "Waarschuwing!",
  "CLICK_RESTART_TO_UPDATE": "Klik op Opnieuw opstarten om beugels bij te werken",
  "UPDATE_ON_NEXT_LAUNCH": "De update wordt toegepast bij het opnieuw starten.",
  "GO_TO_SITE": "Ga naar <a href = \"http://brackets.io/ „> brackets.io</a> om het opnieuw te proberen.",
  "INTERNET_UNAVAILABLE": "Geen internetverbinding beschikbaar.",
  "UPDATEDIR_READ_FAILED": "De update-map kon niet worden gelezen.",
  "UPDATEDIR_CLEAN_FAILED": "De update-map kon niet worden opgeschoond.",
  "INITIAL_DOWNLOAD": "Update downloaden...",
  "RETRY_DOWNLOAD": "Het downloaden is mislukt. Opnieuw proberen... Poging ",
  "VALIDATING_INSTALLER": "Download compleet! Installatieprogramma valideren...",
  "CHECKSUM_DID_NOT_MATCH": "Checksum kwam niet overeen.",
  "INSTALLER_NOT_FOUND": "Installatieprogramma niet gevonden.",
  "DOWNLOAD_ERROR": "Er is fout opgetreden tijdens het downloaden.",
  "NETWORK_SLOW_OR_DISCONNECTED": "Het netwerk is losgekoppeld of te traag.",
  "RESTART_BUTTON": "Opnieuw opstarten",
  "LATER_BUTTON": "Later",
  "DESCRIPTION_AUTO_UPDATE": "Haakjes inschakelen/uitschakelen Automatisch bijwerken",
  "AUTOUPDATE_ERROR": "Fout!",
  "AUTOUPDATE_IN_PROGRESS": "Er is al een update aan de gang.",
  "NUMBER_WITH_PERCENTAGE": "{0}%",
  "CMD_FIND_RELATED_FILES": "Zoek gerelateerde bestanden",
  "PHP_VERSION_INVALID": "Fout bij parseren van PHP-versie. Controleer de uitvoer van het „php —version” commando.",
  "PHP_UNSUPPORTED_VERSION": "Installeer PHP7-runtime voor het inschakelen van PHP-gerelateerde tooling zoals codehints, parameterhints, Jump To Definition en meer. Versie gevonden: {0}",
  "PHP_EXECUTABLE_NOT_FOUND": "PHP-runtime niet gevonden. Installeer de PHP7-runtime en werk „ExecutablePath” op de juiste manier bij in PHP-voorkeuren. Dit maakt PHP-gerelateerde tooling mogelijk, zoals codehints, parameterhints, Jump To Definition en meer.",
  "PHP_PROCESS_SPAWN_ERROR": "Foutcode {0} is opgetreden tijdens het starten van het PHP-proces.",
  "PHP_SERVER_ERROR_TITLE": "Fout",
  "PHP_SERVER_MEMORY_LIMIT_INVALID": "De geheugenlimiet die u hebt opgegeven, is ongeldig. Bekijk de PHP-voorkeuren om de juiste waarde in te stellen.",
  "DESCRIPTION_PHP_TOOLING_CONFIGURATION": "Standaardconfiguratie-instellingen voor PHP Tooling",
  "OPEN_PREFERENNCES": "Voorkeuren openen",
  "LANGUAGE_TOOLS_PREFERENCES": "Voorkeuren voor taalhulpmiddelen",
  "FIND_ALL_REFERENCES": "Zoek alle referenties",
  "REFERENCES_IN_FILES": "referenties",
  "REFERENCE_IN_FILES": "verwijzing",
  "REFERENCES_NO_RESULTS": "Geen referenties beschikbaar voor de huidige cursorpositie",
  "CMD_FIND_DOCUMENT_SYMBOLS": "Document symbolen zoeken",
  "CMD_FIND_PROJECT_SYMBOLS": "Projectsymbolen zoeken",
  "REMOTE_DEBUGGING_ENABLED": "Foutopsporing op afstand ingeschakeld op localhost:",
  "REMOTE_DEBUGGING_PORT_INVALID": "Kan foutopsporing op afstand niet inschakelen op poort {0}. Poortnummers moeten tussen {1} en {2} liggen.",
  "DESCRIPTION_EXTERNAL_APPLICATION_ASSOCIATE": "Toewijzingen voor bestandsextensies aan externe toepassingen. Syntax: \"<file_type>„: „<default|ApplicationName|ApplicationPath>”, Gebruik „default” om bestanden te openen in de standaardtoepassing van het systeem voor het bestandstype.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_TITLE": "Open grafische bestanden in externe editors.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_MSG": "Je huidige map bevat grafische bestandstypen die niet worden ondersteund door {APP_NAME}. <br/>U kunt nu specifieke bestandstypen koppelen aan externe editors. Eenmaal gekoppeld, kunt u grafische bestanden zoals .xd, .psd, .jpg, .png, .ai, .svg openen in hun standaardtoepassingen door te dubbelklikken op de bestanden in Bestandsstructuur. <br/><br/>Klik op de knop 'Ok' om de grafische bestandstypen te koppelen aan hun respectieve standaardtoepassingen.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_CNF_MSG": "De volgende bestandstypen zijn met succes gekoppeld aan standaardtoepassingen. <br/>{0} Je hebt de mogelijkheid om je voorkeur te wijzigen voor het al dan niet verwijderen/toevoegen van nieuwe bestandstypekassociaties in brackets.json door naar het menu „Debug->Bestand Voorkeuren openen” te gaan.",
  "UNSUPPORTED_BROWSER": "Browser wordt niet ondersteund",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER": "Browser ondersteunt geen Open map",
  "UNSUPPORTED_BROWSER_MESSAGE_LINE1": "Gebruik een van de onderstaande ondersteunde browsers.",
  "UNSUPPORTED_BROWSER_MESSAGE_LINE2": " We werken er hard aan om Phoenix beschikbaar te maken in meer browsers. U kunt deze dialoog sluiten, maar sommige functies in Phoenix werken niet in deze browser.",
  "MISSING_FIELDS": "Ontbrekende velden",
  "PLEASE_FILL_ALL_REQUIRED": "Vul alle verplichte velden in die rood zijn gemarkeerd",
  "CODE_EDITOR": "Code-editor",
  "BUILD_THE_WEB": "Bouw het web",
  "IMPORT_PROJECT": "Project importeren",
  "GITHUB_PROJECT": "Github-project",
  "NEW_PROJECT_FROM_GITHUB": "Nieuw project van Github",
  "GITHUB_REPO_URL": "Github Repo-URL:",
  "CREATE_PROJECT": "Project maken",
  "SETTING_UP_PROJECT": "Project opzetten",
  "LOCATION": "Locatie:",
  "DOWNLOADING": "Downloaden...",
  "DOWNLOAD_FAILED_MESSAGE": "Zorg ervoor dat de download-URL geldig is. </br>NB: Aangezien Phoenix in alpha is, zijn Private Repo's en Github-URL's groter dan 25 MB niet toegestaan.",
  "PLEASE_SELECT_A_FOLDER": "Selecteer een map...",
  "UNZIP_IN_PROGRESS": "Bestanden uitpakken...",
  "UNZIP_FAILED": "Fout: Uitpakken is mislukt.",
  "CONFIRM_REPLACE_TITLE": "Vervangen bevestigen",
  "KEEP_BOTH": "Beide bewaren",
  "EXPLORE": "HTML-spellen",
  "BLOG": "Blog",
  "PROJECT_NAME": "Naam van het project:",
  "NEW_BOOTSTRAP_BLOG": "Nieuwe Bootstrap-blog",
  "NEW_HTML": "Nieuw HTML-project",
  "LICENSE": "Licentie:",
  "CREDITS": "Credits:",
  "NEW_PROJECT_NOTIFICATION": "Klik op dit pictogram om een nieuw project te<br/> maken. </br><a href='#' style='float:right;'>ok</a>",
  "DIRECTORY_REPLACE_MESSAGE": "De geselecteerde map <span class='dialog-filename'>{0}</span> is niet leeg. Weet u zeker dat u de inhoud van de map wilt vervangen door het project?",
  "GUIDED_FILES_SIDEBAR": "Selecteer een HTML-bestand</br> <a href='#' style='float:right;'>ok</a>",
  "GUIDED_LIVE_PREVIEW": "Breng enkele codewijzigingen aan en sla het bestand op om een voorbeeld te zien. </br><a href='#' style='float:right;'>ok</a>"
});