/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "Systemstandard",
  "PROJECT_BUSY": "Projektverksamhet pågår",
  "DUPLICATING": "Duplicerar {0}",
  "MOVING": "Flyttar {0}",
  "COPYING": "Kopierar {0}",
  "DELETING": "Raderar {0}",
  "RENAMING": "Byter namn",
  "GENERIC_ERROR": "(fel {0})",
  "NOT_FOUND_ERR": "Filen/mappen kunde inte hittas.",
  "NOT_READABLE_ERR": "Filen/mappen kunde inte läsas.",
  "EXCEEDS_MAX_FILE_SIZE": "Filer större än {0} MB kan inte öppnas i {APP_NAME}.",
  "NO_MODIFICATION_ALLOWED_ERR": "Målmappen kunde inte ändras.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "Du har inte behörighet att modifiera filen.",
  "CONTENTS_MODIFIED_ERR": "Filen har ändrats utanför {APP_NAME}.",
  "UNSUPPORTED_ENCODING_ERR": "{APP_NAME} stöder just nu bara textfiler kodade i UTF-8.",
  "ENCODE_FILE_FAILED_ERR": "{APP_NAME} kunde inte koda innehållet i filen.",
  "DECODE_FILE_FAILED_ERR": "{APP_NAME} kunde inte avkoda innehållet i filen.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "{APP_NAME} stöder för närvarande inte UTF-16-kodade textfiler.",
  "FILE_EXISTS_ERR": "Filen eller mappen existerar redan.",
  "FILE": "fil",
  "FILE_TITLE": "Arkiv",
  "DIRECTORY": "mapp",
  "DIRECTORY_TITLE": "Mapp",
  "DIRECTORY_NAMES_LEDE": "Mappnamn",
  "FILENAMES_LEDE": "Filnamn",
  "FILENAME": "filnamn",
  "DIRECTORY_NAME": "mappnamn",
  "ERROR_LOADING_PROJECT": "Projektet kunde inte öppnas",
  "OPEN_DIALOG_ERROR": "Ett fel inträffade när öppningsdialogen skulle visas. (fel {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "Ett fel inträffade när mappen skulle öppnas <span class='dialog-filename'>{0}</span>. (fel {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "Ett fel inträffade när mappens innehåll skulle läsas <span class='dialog-filename'>{0}</span>. (fel {1})",
  "ERROR_OPENING_FILE_TITLE": "Filen kunde inte öppnas",
  "ERROR_OPENING_FILE": "Ett fel inträffade när filen <span class='dialog-filename'>{0}</span> skulle öppnas. {1}",
  "ERROR_OPENING_FILES": "Ett fel inträffade när följande filer skulle öppnas:",
  "ERROR_RELOADING_FILE_TITLE": "Filen kunde inte laddas om",
  "ERROR_RELOADING_FILE": "Ett fel inträffade när filen <span class='dialog-filename'>{0}</span> skulle läsas om. {1}",
  "ERROR_SAVING_FILE_TITLE": "Filen kunde inte sparas",
  "ERROR_SAVING_FILE": "Ett fel inträffade när filen <span class='dialog-filename'>{0}</span> skulle sparas. {1}",
  "ERROR_RENAMING_FILE_TITLE": "Filen kunde inte döpas om",
  "ERROR_RENAMING_FILE": "Ett fel uppstod när {2}-filen <span class='dialog-filename'>{0}</span> skulle döpas om. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "Filen eller mappen är inte del av det öppna projektet. Tyvärr kan bara projektfiler döpas om för närvarande.",
  "ERROR_MOVING_FILE_TITLE": "Det gick inte att flytta {0}",
  "ERROR_MOVING_FILE": "Ett fel uppstod när du försökte flytta {2} <span class='dialog-filename'>{0}</span> . {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "Kan inte flytta filen/mappen, eftersom de inte är en del av det aktuella projektet.",
  "ERROR_DELETING_FILE_TITLE": "Filen kunde inte raderas",
  "ERROR_DELETING_FILE": "Ett fel uppstod när {2}-filen <span class='dialog-filename'>{0}</span> skulle tas bort. {1}",
  "INVALID_FILENAME_TITLE": "Ogiltigt {0}",
  "CANNOT_PASTE_TITLE": "Kan inte klistra in {0}",
  "CANNOT_DOWNLOAD_TITLE": "Kan inte ladda ned {0}",
  "ERR_TYPE_DOWNLOAD_FAILED": "Ett fel uppstod vid nedladdning av <span class='dialog-filename'>{0}</span>",
  "ERR_TYPE_PASTE_FAILED": "Ett fel uppstod när <span class='dialog-filename'>{0}</span> skulle klistras in i <span class='dialog-filename'>{1}</span>",
  "CANNOT_DUPLICATE_TITLE": "Kan inte duplicera",
  "ERR_TYPE_DUPLICATE_FAILED": "Ett fel uppstod vid duplicering av <span class='dialog-filename'>{0}</span>",
  "INVALID_FILENAME_MESSAGE": "{0} får inte innehålla ord som reserverats av systemet, sluta med punkt (.) eller använda något av följande tecken: <code class='emphasized'>{1}</code>.",
  "ENTRY_WITH_SAME_NAME_EXISTS": "En fil eller mapp med namnet <span class='dialog-filename'>{0}</span> existerar redan.",
  "ERROR_CREATING_FILE_TITLE": "Kunde inte skapa {0}",
  "ERROR_CREATING_FILE": "Ett fel uppstod när en {0} med namnet <span class='dialog-filename'>{1}</span> skulle skapas. {2}",
  "ERROR_MIXED_DRAGDROP": "Kan inte öppna en mapp samtidigt som andra filer öppnas.",
  "ERROR_KEYMAP_TITLE": "Fel uppstod när användarens tangentuppsättning lästes in",
  "ERROR_KEYMAP_CORRUPT": "Din tangentuppsättningsfil är inte korrekt formaterad JSON. Filen kommer att öppnas så att du kan åtgärda formateringsfelet.",
  "ERROR_LOADING_KEYMAP": "Din tangentuppsättningsfil är inte en UTF-8-kodad textfil och kan inte läsas",
  "ERROR_RESTRICTED_COMMANDS": "Du kan inte ändra kortkommandot för följande kommandon: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "Du kan inte ändra följande kortkommandon: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "Du håller på att koppla flera kortkommandon till följande kommandon: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "Du har flera kopplingar till följande kommandon: {0}",
  "ERROR_INVALID_SHORTCUTS": "Följande kortkommandon är felaktiga: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "Du håller på att skapa kortkommandon till följande icke-existerande kommandon: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "Kunde inte läsa inställningar",
  "ERROR_PREFS_CORRUPT": "Din inställningsfil är inte korrekt formaterad JSON. Filen kommer att öppnas så att du kan korrigera felet. Du kommer att behöva starta om {APP_NAME} för att ändringarna ska träda i kraft.",
  "ERROR_PROJ_PREFS_CORRUPT": "Dina projektinställningar är inte giltig JSON. Filen kommer att öppnas så att du kan rätta till formatet. Du behöver ladda om projektet för att ändringarna ska träda i kraft.",
  "ERROR_IN_BROWSER_TITLE": "Ajdå! {APP_NAME} körs inte i webbläsaren ännu.",
  "ERROR_IN_BROWSER": "{APP_NAME} är byggd i HTML, men körs just nu som en skrivbordsapplikation så att du kan använda den för att redigera lokala filer. Vänligen använd skalapplikationen <b>github.com/adobe/brackets-shell</b> för att köra {APP_NAME}.",
  "ERROR_MAX_FILES_TITLE": "Fel vid indexering av filer",
  "ERROR_MAX_FILES": "Det maximala antalet filer har indexerats. Funktioner som använder sig av indexet kanske inte kommer att fungera som förväntat.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "Webbläsaren kunde inte öppnas.",
  "ERROR_CANT_FIND_CHROME": "Google Chrome kunde inte hittas. Kontrollera att den är installerad.",
  "ERROR_LAUNCHING_BROWSER": "Ett fel inträffade då webbläsaren skulle startas. (fel {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "Förhandsvisning misslyckades",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "Ansluter till webbläsaren",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "För att förhandsvisningen ska lyckas måste Chrome startas om med fjärrfelsökning aktiverad.<br /><br />Vill du starta om Chrome och aktivera fjärrfelsökning?",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "Lyckades inte ladda förhandsvisningssidan.",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "För att starta förhandsvisningen med en fil innehållande serverkod måste du ange en bas-URL för detta projekt.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "Ett fel uppstod när webbsevern för förhandsvisningen skulle startas. Vänligen försök igen.",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "För mer information se <a href='{0}' title='{0}'>Troubleshooting Live Development connection errors</a>.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "Förhandsvisning",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "Förhandsvisning: Ansluter…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "Förhandsvisning: Initierar…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "Koppla från förhandsvisningen",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "Förhandsvisning",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "Välj File To Live Preview",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "Ladda om sidan",
  "LIVE_DEV_TOGGLE_LIVE_HIGHLIGHT": "Växla Live Preview Highlights",
  "LIVE_DEV_CLICK_POPOUT": "Popout Live Preview till nytt fönster",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "Fäst på Unpin Preview Page",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "Förhandsvisning (uppdateras inte på grund av syntaxfel)",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "Förhandsvisningen avbröts eftersom webbläsarens utvecklarverktyg öppnades.",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "Förhandsvisningen avbröts eftersom sidan stängdes i webbläsaren.",
  "LIVE_DEV_NAVIGATED_AWAY": "Förhandsvisningen avbröts eftersom webbläsaren navigerades till en sida som inte är del av det nuvarande projektet.",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "Förhandsvisningen avbröts på grund av ett okänt fel. ({0})",
  "SAVE_CLOSE_TITLE": "Spara ändringar?",
  "SAVE_CLOSE_MESSAGE": "Vill du spara de ändringar i dokumentet <span class='dialog-filename'>{0}</span>?",
  "SAVE_CLOSE_MULTI_MESSAGE": "Vill du spara ändringarna du gjort följande filer?",
  "EXT_MODIFIED_TITLE": "Externa ändringar",
  "CONFIRM_DELETE_TITLE": "Bekräfta borttagning",
  "CONFIRM_FILE_DELETE": "Är du säker att du vill radera filen <span class='dialog-filename'>{0}</span>?",
  "CONFIRM_FOLDER_DELETE": "Är du säker att du vill radera mappen <span class='dialog-filename'>{0}</span>?",
  "FILE_DELETED_TITLE": "Filen raderades",
  "EXT_MODIFIED_WARNING": "<span class='dialog-filename'>{0}</span> har ändrats.<br /><br />Vill du spara filen och skriva över dessa ändringar?",
  "EXT_MODIFIED_MESSAGE": "<span class='dialog-filename'>{0}</span> har ändrats men har också osparade ändringar i {APP_NAME}.<br /><br />Vilken version vill du behålla?",
  "EXT_DELETED_MESSAGE": "<span class='dialog-filename'>{0}</span> har raderats man har också osparade ändringar i {APP_NAME}.<br /><br />Vill du behålla dina ändringar?",
  "WINDOW_UNLOAD_WARNING": "Är du säker på att du vill navigera till en annan URL och lämna parenteser?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "Du har osparade ändringar! Är du säker på att du vill navigera till en annan URL och lämna parenteser?",
  "DONE": "Klar",
  "OK": "OK",
  "CANCEL": "Avbryt",
  "DONT_SAVE": "Spara inte",
  "SAVE": "Spara",
  "SAVE_AS": "Spara som…",
  "SAVE_AND_OVERWRITE": "Skriv över",
  "DELETE": "Radera",
  "BUTTON_YES": "Ja",
  "BUTTON_NO": "Nej",
  "FIND_MATCH_INDEX": "{0} av {1}",
  "FIND_NO_RESULTS": "Inga träffar",
  "FIND_QUERY_PLACEHOLDER": "Sök…",
  "FIND_HISTORY_MAX_COUNT": "Maximalt antal poster i sökhistoriken",
  "REPLACE_PLACEHOLDER": "Ersätt med…",
  "BUTTON_REPLACE_ALL": "Alla…",
  "BUTTON_REPLACE_BATCH": "Omgång…",
  "BUTTON_REPLACE_ALL_IN_FILES": "Ersätt…",
  "BUTTON_REPLACE": "Ersätt",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "Nästa träff",
  "BUTTON_PREV_HINT": "Föregående träff",
  "BUTTON_CASESENSITIVE_HINT": "Skiftlägeskänslig",
  "BUTTON_REGEXP_HINT": "Regular Expression",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "Ersätt utan att ångra",
  "REPLACE_WITHOUT_UNDO_WARNING": "Eftersom mer än {0} filer ändras kommer {APP_NAME} ändra dessa utan att de öppnas.<br />Du kommer inte att kunna ånga ändringarna i dessa filer.",
  "BUTTON_REPLACE_WITHOUT_UNDO": "Ersätt utan att ångra",
  "OPEN_FILE": "Öppna fil",
  "SAVE_FILE_AS": "Spara fil som",
  "CHOOSE_FOLDER": "Välj mapp",
  "RELEASE_NOTES": "Versionsinformation",
  "NO_UPDATE_TITLE": "Du är uppdaterad!",
  "NO_UPDATE_MESSAGE": "Du använder den senaste versionen av {APP_NAME}.",
  "FIND_REPLACE_TITLE_LABEL": "Ersätt",
  "FIND_REPLACE_TITLE_WITH": "med",
  "FIND_TITLE_LABEL": "Hittades",
  "FIND_TITLE_SUMMARY": "&mdash; {0} {1} {2} i {3}",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "i <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_NO_SCOPE": "i projekt",
  "FIND_IN_FILES_ZERO_FILES": "Filter exkluderar alla filer {0}",
  "FIND_IN_FILES_FILE": "fil",
  "FIND_IN_FILES_FILES": "filer",
  "FIND_IN_FILES_MATCH": "träff",
  "FIND_IN_FILES_MATCHES": "träffar",
  "FIND_IN_FILES_MORE_THAN": "Mer än ",
  "FIND_IN_FILES_PAGING": "{0}&mdash;{1}",
  "FIND_IN_FILES_FILE_PATH": "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "Ctrl/Cmd-klicka för att expandera/minimera alla",
  "FIND_IN_FILES_INDEXING": "Indexerar för Instant Search...",
  "FIND_IN_FILES_INDEXING_PROGRESS": "Indexerar {0} av {1} filer för Instant Search...",
  "REPLACE_IN_FILES_ERRORS_TITLE": "Ersättningsfel",
  "REPLACE_IN_FILES_ERRORS": "Följande filer ändrades inte eftersom de förändrats efter sökningen eller inte kunde skrivas till.",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "Fel vid hämtning av versioninformation",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "Det gick inte att hämta versionsinformation från servern. Kontrollera din internetuppkoppling och försök igen.",
  "NEW_FILE_FILTER": "Nytt exkluderingsset…",
  "CLEAR_FILE_FILTER": "Exkludera inte filer",
  "NO_FILE_FILTER": "Exkludera filer…",
  "EXCLUDE_FILE_FILTER": "Exkludera {0}",
  "EDIT_FILE_FILTER": "Redigera…",
  "FILE_FILTER_DIALOG": "Redigera filter",
  "FILE_FILTER_INSTRUCTIONS": "Exkludera filer och mappar som matchar någon av följande strängar, substrängar eller <a href='{0}' title='{0}'>wildcards</a>. Ange varje sträng på en ny rad.",
  "FILTER_NAME_PLACEHOLDER": "Namnge detta exkluderingsset (frivilligt)",
  "FILTER_NAME_REMAINING": "{0} tecken kvar",
  "FILE_FILTER_CLIPPED_SUFFIX": "och {0} till",
  "FILTER_COUNTING_FILES": "Räknar filer…",
  "FILTER_FILE_COUNT": "Tillåter {0} av {1} filer {2}",
  "FILTER_FILE_COUNT_ALL": "Tillåter alla {0} filer {1}",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "Ingen Quick Edit är tillgänglig vid markörens nuvarande position",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "CSS Quick Edit: placera markören på ett klassnamn",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "CSS Quick Edit: ofullständigt klassattribut",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "CSS Quick Edit: ofullständigt ID-attribut",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "CSS Quick Edit: placera markören inom en tagg, klass eller ID",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "CSS tidsfunktion Quick Edit: felaktigt syntax",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "JS Quick Edit: placera markören på ett funktionsnamn",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "Inga Quick Docs är tillgängliga vid markörens nuvarande position",
  "PROJECT_LOADING": "Öppnar…",
  "UNTITLED": "Namnlös",
  "WORKING_FILES": "Öppna filer",
  "TOP": "Övre",
  "BOTTOM": "Undre",
  "LEFT": "Vänster",
  "RIGHT": "Höger",
  "CMD_SPLITVIEW_NONE": "Ingen delning",
  "CMD_SPLITVIEW_VERTICAL": "Vertikal delning",
  "CMD_SPLITVIEW_HORIZONTAL": "Horisontell delning",
  "SPLITVIEW_MENU_TOOLTIP": "Dela editorn vertikalt eller horisontellt",
  "GEAR_MENU_TOOLTIP": "Konfigurera arbetsyta",
  "SPLITVIEW_INFO_TITLE": "Redan öppen",
  "SPLITVIEW_MULTIPANE_WARNING": "Filen är redan öppen i en annan panel. {APP_NAME} kommer inom kort att stödja möjligheten att öppna samma fil i flera paneler. Filen kommer att visas i nuvarande panel tills dess.<br /><br />(Detta meddelande kommer bara att visas en gång.)",
  "STATUSBAR_CURSOR_POSITION": "Rad {0}, kolumn {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": " — Markerade {0} kolumn",
  "STATUSBAR_SELECTION_CH_PLURAL": " — Markerade {0} kolumner",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " — Markerade {0} rad",
  "STATUSBAR_SELECTION_LINE_PLURAL": " — Markerade {0} rader",
  "STATUSBAR_SELECTION_MULTIPLE": " — {0} markeringar",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "Klicka för att använda mellanslag för indrag",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "Klicka för att använda tabbar för indrag",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "Klicka för att ändra antalet mellanslag som används för indrag",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "Klicka för att ändra bredden på tabbtecken",
  "STATUSBAR_SPACES": "Mellanslag:",
  "STATUSBAR_TAB_SIZE": "Tabbstorlek:",
  "STATUSBAR_LINE_COUNT_SINGULAR": "— {0} rad",
  "STATUSBAR_LINE_COUNT_PLURAL": "— {0} rader",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "Tillägg har avaktiverats",
  "STATUSBAR_INSERT": "INS",
  "STATUSBAR_OVERWRITE": "ÖVR",
  "STATUSBAR_INSOVR_TOOLTIP": "Klicka för att växla mellan Insert (INS)- och Overwrite (ÖVR)-läge.",
  "STATUSBAR_LANG_TOOLTIP": "Klicka för att byta filtyp",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. Klicka för att visa rapportpanel.",
  "STATUSBAR_DEFAULT_LANG": "(standard)",
  "STATUSBAR_SET_DEFAULT_LANG": "Ställ in som standard för .{0}-filer",
  "STATUSBAR_ENCODING_TOOLTIP": "Välj kodning",
  "ERRORS_PANEL_TITLE_MULTIPLE": "{0} fel",
  "SINGLE_ERROR": "1 {0} fel",
  "MULTIPLE_ERRORS": "{1} {0} fel",
  "NO_ERRORS": "Inga {0} fel funna - bra jobbat!",
  "NO_ERRORS_MULTIPLE_PROVIDER": "Inga fel funna - bra jobbat!",
  "LINT_DISABLED": "Linting är avaktiverat.",
  "NO_LINT_AVAILABLE": "Ingen linter är tillgänglig för {0}",
  "NOTHING_TO_LINT": "Ingenting att linta",
  "LINTER_TIMED_OUT": "{0} har avbrutits efter att ha väntat {1} ms",
  "LINTER_FAILED": "{0} avbröts efter ett fel: {1}",
  "FILE_MENU": "Arkiv",
  "CMD_FILE_NEW_UNTITLED": "Ny",
  "CMD_FILE_NEW": "Ny fil",
  "CMD_FILE_DUPLICATE": "Duplicera",
  "CMD_FILE_DOWNLOAD_PROJECT": "Ladda ner projekt",
  "CMD_FILE_DOWNLOAD": "Ladda ner",
  "CMD_FILE_CUT": "Klipp ut",
  "CMD_FILE_COPY": "Kopiera",
  "CMD_FILE_COPY_PATH": "Kopiera sökväg",
  "CMD_FILE_PASTE": "Klistra in",
  "CMD_PROJECT_NEW": "Nytt projekt",
  "CMD_FILE_NEW_FOLDER": "Ny mapp",
  "CMD_FILE_OPEN": "Öppna…",
  "CMD_RECENT_FILES_OPEN": "Senaste filer…",
  "CMD_ADD_TO_WORKING_SET": "Lägg till i arbetsyta",
  "CMD_OPEN_DROPPED_FILES": "Öppna släppta filer",
  "CMD_OPEN_FOLDER": "Öppna mapp…",
  "CMD_FILE_CLOSE": "Stäng",
  "CMD_FILE_CLOSE_ALL": "Stäng alla",
  "CMD_FILE_CLOSE_LIST": "Stäng lista",
  "CMD_FILE_CLOSE_OTHERS": "Stäng andra",
  "CMD_FILE_CLOSE_ABOVE": "Stäng andra ovanför",
  "CMD_FILE_CLOSE_BELOW": "Stäng andra nedanför",
  "CMD_FILE_SAVE": "Spara fil som",
  "CMD_FILE_SAVE_ALL": "Spara alla",
  "CMD_FILE_SAVE_AS": "Spara som…",
  "CMD_LIVE_FILE_PREVIEW": "Förhandsvisning",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "Aktivera Experimentell Live Preview",
  "CMD_RELOAD_LIVE_PREVIEW": "Tvinga uppdatering av förhandsvisningen",
  "CMD_PROJECT_SETTINGS": "Projektinställningar…",
  "CMD_FILE_RENAME": "Byt namn",
  "CMD_FILE_DELETE": "Radera",
  "CMD_INSTALL_EXTENSION": "Installera tillägg…",
  "CMD_EXTENSION_MANAGER": "Tilläggshanteraren…",
  "CMD_FILE_REFRESH": "Uppdatera filträd",
  "CMD_FILE_SHOW_FOLDERS_FIRST": "Sortera mappar först",
  "CMD_QUIT": "Avsluta",
  "CMD_EXIT": "Avsluta",
  "EDIT_MENU": "Redigera",
  "CMD_UNDO": "Ångra",
  "CMD_REDO": "Gör om",
  "CMD_CUT": "Klipp ut",
  "CMD_COPY": "Kopiera",
  "CMD_PASTE": "Klistra in",
  "CMD_SELECT_ALL": "Markera alla",
  "CMD_SELECT_LINE": "Markera rad",
  "CMD_SPLIT_SEL_INTO_LINES": "Dela markering i rader",
  "CMD_ADD_CUR_TO_NEXT_LINE": "Lägg till markör på nästa rad",
  "CMD_ADD_CUR_TO_PREV_LINE": "Lägg till markör på föregående rad",
  "CMD_INDENT": "Öka indrag",
  "CMD_UNINDENT": "Minska indrag",
  "CMD_DUPLICATE": "Duplicera",
  "CMD_DELETE_LINES": "Radera rad",
  "CMD_COMMENT": "Växla kommentarsrad",
  "CMD_BLOCK_COMMENT": "Växla blockkommentar",
  "CMD_LINE_UP": "Flytta rad uppåt",
  "CMD_LINE_DOWN": "Flytta rad nedåt",
  "CMD_OPEN_LINE_ABOVE": "Öppna rad ovanför",
  "CMD_OPEN_LINE_BELOW": "Öppna rad nedanför",
  "CMD_TOGGLE_CLOSE_BRACKETS": "Stäng parenteser automatiskt",
  "CMD_SHOW_CODE_HINTS": "Visa kodförslag",
  "CMD_BEAUTIFY_CODE": "Försköna kod",
  "CMD_BEAUTIFY_CODE_ON_SAVE": "Försköna koden efter spara",
  "FIND_MENU": "Sök",
  "CMD_FIND": "Sök",
  "CMD_FIND_NEXT": "Sök nästa",
  "CMD_FIND_PREVIOUS": "Sök föregående",
  "CMD_FIND_ALL_AND_SELECT": "Sök och markera alla",
  "CMD_ADD_NEXT_MATCH": "Lägg nästa träff till markering",
  "CMD_SKIP_CURRENT_MATCH": "Hoppa över och lägg till nästa träff",
  "CMD_FIND_IN_FILES": "Sök i filer",
  "CMD_FIND_IN_SUBTREE": "Sök i…",
  "CMD_REPLACE": "Ersätt",
  "CMD_REPLACE_IN_FILES": "Ersätt i filer",
  "CMD_REPLACE_IN_SUBTREE": "Ersätt i…",
  "VIEW_MENU": "Visa",
  "CMD_HIDE_SIDEBAR": "Dölj sidomeny",
  "CMD_SHOW_SIDEBAR": "Visa sidomeny",
  "CMD_TOGGLE_SIDEBAR": "Växla på/av sidomeny",
  "CMD_TOGGLE_PANELS": "Växla på/av paneler",
  "CMD_TOGGLE_PURE_CODE": "Inga distraktioner",
  "CMD_INCREASE_FONT_SIZE": "Öka textstorlek",
  "CMD_DECREASE_FONT_SIZE": "Minska teckenstorlek",
  "CMD_RESTORE_FONT_SIZE": "Återställ teckenstorlek",
  "CMD_SCROLL_LINE_UP": "Rulla rad uppåt",
  "CMD_SCROLL_LINE_DOWN": "Rulla rad nedåt",
  "CMD_TOGGLE_LINE_NUMBERS": "Radnummer",
  "CMD_TOGGLE_ACTIVE_LINE": "Markera aktiv rad",
  "CMD_TOGGLE_WORD_WRAP": "Automatisk radbrytning",
  "CMD_LIVE_HIGHLIGHT": "Markera förhandsvisning",
  "CMD_VIEW_TOGGLE_INSPECTION": "Linta filer vid spara",
  "CMD_WORKINGSET_SORT_BY_ADDED": "Sortera efter senast tillagd",
  "CMD_WORKINGSET_SORT_BY_NAME": "Sortera efter namn",
  "CMD_WORKINGSET_SORT_BY_TYPE": "Sortera efter typ",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "Automatisk sortering",
  "CMD_THEMES": "Teman…",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "Stäng sökning automatiskt",
  "NAVIGATE_MENU": "Navigera",
  "CMD_QUICK_OPEN": "Snabböppna",
  "CMD_GOTO_LINE": "Gå till rad",
  "CMD_GOTO_DEFINITION": "Gå till definition",
  "CMD_GOTO_DEFINITION_PROJECT": "Snabbsökningsdefinition i Project",
  "CMD_GOTO_FIRST_PROBLEM": "Gå till första fel/varning",
  "CMD_TOGGLE_QUICK_EDIT": "Snabbredigering",
  "CMD_TOGGLE_QUICK_DOCS": "Quick Docs",
  "CMD_QUICK_EDIT_PREV_MATCH": "Föregående träff",
  "CMD_QUICK_EDIT_NEXT_MATCH": "Nästa träff",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "Ny regel",
  "CMD_NEXT_DOC": "Nästa dokument",
  "CMD_PREV_DOC": "Föregående dokument",
  "CMD_NAVIGATE_BACKWARD": "Navigera bakåt",
  "CMD_NAVIGATE_FORWARD": "Navigera framåt",
  "CMD_NEXT_DOC_LIST_ORDER": "Nästa dokument i lista",
  "CMD_PREV_DOC_LIST_ORDER": "Föregående dokument i lista",
  "CMD_SHOW_IN_TREE": "Visa i filträdet",
  "CMD_SHOW_IN_EXPLORER": "Visa i Utforskaren",
  "CMD_SHOW_IN_FINDER": "Visa i Finder",
  "CMD_SHOW_IN_OS": "Visa i operativsystemet",
  "CMD_SWITCH_PANE_FOCUS": "Växla panelfokus",
  "CMD_OPEN_VFS": "Öppna Virtual File System",
  "CMD_OPEN_VIRTUAL_SERVER": "Öppna Virtual Server",
  "HELP_MENU": "Hjälp",
  "CMD_CHECK_FOR_UPDATE": "Sök efter uppdateringar",
  "CMD_HOW_TO_USE_BRACKETS": "Hur du använder {APP_NAME}",
  "CMD_SUPPORT": "{APP_NAME}-forum",
  "CMD_SUGGEST": "Föreslå en funktion",
  "CMD_RELEASE_NOTES": "Versionsinformation",
  "CMD_GET_INVOLVED": "Engagera dig",
  "CMD_SHOW_EXTENSIONS_FOLDER": "Visa tilläggsmapp",
  "CMD_HEALTH_DATA_STATISTICS": "Hälsorapport",
  "CMD_HOMEPAGE": "Startsida för {APP_NAME}",
  "CMD_TWITTER": "{TWITTER_NAME} på Twitter",
  "CMD_ABOUT": "Om {APP_TITLE}",
  "CMD_OPEN_PREFERENCES": "Öppna inställningsfil",
  "CMD_OPEN_KEYMAP": "Öppna användarens tangentuppsättning",
  "EXPERIMENTAL_BUILD": "experimental build",
  "RELEASE_BUILD": "build",
  "DEVELOPMENT_BUILD": "development build",
  "PRERELEASE_BUILD": "prerelease build",
  "RELOAD_FROM_DISK": "Ladda om",
  "KEEP_CHANGES_IN_EDITOR": "Behåll ändringar i editorn",
  "CLOSE_DONT_SAVE": "Stäng (spara inte)",
  "RELAUNCH_CHROME": "Starta om Chrome",
  "ABOUT": "Om",
  "CLOSE": "Stäng",
  "ABOUT_TEXT_LINE1": "Släpp {VERSION_MAJOR}.{VERSION_MINOR} {BUILD_TYPE} {VERSION}",
  "ABOUT_TEXT_BUILD_TIMESTAMP": "bygg tidsstämpel:",
  "ABOUT_TEXT_LINE3": "Tredjepartsbibliotek som vi använder - <a href='https://github.com/phcode-dev/phoenix/tree/main/src/thirdparty/licences'>Licenser och attribut</a> .",
  "ABOUT_TEXT_LINE4": "Dokumentation och källa på <a href='https://github.com/phcode-dev/phoenix/'>https://github.com/phcode-dev/phoenix/</a>",
  "ABOUT_TEXT_LINE5": "Tillverkad med ❤ och JavaScript av:",
  "ABOUT_TEXT_LINE6": "Många människor (men vi har problem med att ladda den datan just nu).",
  "ABOUT_TEXT_MDN_DOCS": "MDN Docs och dess logotyp är licenserad under en Creative Commons Attribution-licens, <a href='{MDN_DOCS_LICENSE}'>CC-BY-SA 2.5 Unported</a>.",
  "UPDATE_NOTIFICATION_TOOLTIP": "En ny version av {APP_NAME} är tillgänglig! Klicka här för fler detaljer.",
  "UPDATE_AVAILABLE_TITLE": "Uppdatering tillgänglig!",
  "UPDATE_RELOAD_APP": "Stäng alla fönster/flikar i {APP_NAME} och öppna {APP_NAME} igen för att få den senaste versionen.",
  "UPDATE_MESSAGE": "Hallå! En ny version av {APP_NAME} är tillgänglig. Här är några av de nya funktionerna:",
  "GET_IT_NOW": "Installera nu!",
  "PROJECT_SETTINGS_TITLE": "Projektinställningar för: {0}",
  "PROJECT_SETTING_BASE_URL": "URL till förhandsvisning",
  "PROJECT_SETTING_BASE_URL_HINT": "För att använda en lokal server anger du en adress liknande: http://localhost:8000/",
  "BASEURL_ERROR_INVALID_PROTOCOL": "{0}-protokollet stöder inte förhandsvisning &mdash; vänligen använd http: eller https: .",
  "BASEURL_ERROR_SEARCH_DISALLOWED": "Adressen kan inte innehålla sökparametrar som \"{0}\".",
  "BASEURL_ERROR_HASH_DISALLOWED": "Adressen kan inte innehålla hashar som \"{0}\".",
  "BASEURL_ERROR_INVALID_CHAR": "Specialtecken som '{0}' måste vara %-kodade.",
  "BASEURL_ERROR_UNKNOWN_ERROR": "Okänt fel när adressen skulle läsas!",
  "EMPTY_VIEW_HEADER": "<em>Öppna en fil medan denna panel är i fokus</em>",
  "FLIPVIEW_BTN_TOOLTIP": "Flippa denna vy till panel {0}",
  "CURRENT_THEME": "Nuvarande tema",
  "USE_THEME_SCROLLBARS": "Använd temats rullningslister",
  "FONT_SIZE": "Teckenstorlek",
  "FONT_FAMILY": "Typsnitt",
  "THEMES_SETTINGS": "Temainställningar",
  "THEMES_ERROR": "Temafel",
  "THEMES_ERROR_CANNOT_APPLY": "Det gick inte att använda temat på grund av ett fel.",
  "BUTTON_NEW_RULE": "Ny regel",
  "INSTALL": "Installera",
  "APPLY": "Tillämpa",
  "UPDATE": "Uppdatera",
  "REMOVE": "Radera",
  "DISABLE": "Avaktivera",
  "ENABLE": "Aktivera",
  "OVERWRITE": "Skriv över",
  "CANT_DROP_ZIP": "Att släppa zip-filer kommer att stödjas snart...",
  "CANT_REMOVE_DEV": "Tillägg i mappen \"dev\" måste raderas manuellt.",
  "CANT_UPDATE": "Uppdateringen är inte kompatibel med denna version av {APP_NAME}.",
  "CANT_UPDATE_DEV": "Tilläggen i mappen \"dev\" kan inte uppdateras automatiskt.",
  "INSTALL_EXTENSION_TITLE": "Installera tillägg",
  "UPDATE_EXTENSION_TITLE": "Uppdatera tillägg",
  "INSTALL_EXTENSION_LABEL": "Tilläggets URL",
  "INSTALL_EXTENSION_HINT": "URL till tilläggets zip-fil eller GitHub-repository",
  "INSTALLING_FROM": "Installerar tillägg från {0}…",
  "INSTALL_SUCCEEDED": "Installationen lyckades!",
  "INSTALL_FAILED": "Installationen misslyckades.",
  "CANCELING_INSTALL": "Avbryter…",
  "CANCELING_HUNG": "Installationen avbröts då den tog för lång tid. Ett internt fel kan ha inträffat.",
  "INSTALL_CANCELED": "Installationen avbröts.",
  "VIEW_COMPLETE_DESCRIPTION": "Visa hela beskrivningen",
  "VIEW_TRUNCATED_DESCRIPTION": "Visa förkortad beskrivning",
  "SORT_EXTENSION_METHOD": "Sortera tillägg på downloadCount eller publishedDate",
  "INVALID_ZIP_FILE": "Det nedladdade innehållet är inte en fungerande zip-fil.",
  "MISSING_PACKAGE_JSON": "Paketet saknar filen package.json.",
  "INVALID_PACKAGE_JSON": "Filen package.json är inte korrekt (felet var: {0}).",
  "MISSING_PACKAGE_NAME": "Filen package.json innehåller inte tilläggets namn.",
  "BAD_PACKAGE_NAME": "{0} är inte ett godkänt namn.",
  "MISSING_PACKAGE_VERSION": "Filen package.json innehåller inte tilläggets versionsnummer.",
  "INVALID_VERSION_NUMBER": "Tilläggets versionsnummer ({0}) är felaktigt.",
  "INVALID_BRACKETS_VERSION": "Kompatibilitetssträngen ({0}) för {APP_NAME} är felaktig.",
  "DISALLOWED_WORDS": "Orden ({1}) är inte tillåtna i {0}-fältet.",
  "NPM_INSTALL_FAILED": "npm installationskommandot misslyckades: {0}",
  "API_NOT_COMPATIBLE": "Tillägget är inte kompatibelt med denna version av {APP_NAME}. Det har installerats i din mapp med inaktiverade tillägg.",
  "MISSING_MAIN": "Tillägget har ingen fil med namnet main.js.",
  "EXTENSION_ALREADY_INSTALLED": "Installationen av detta tillägg kommer att skriva över ett tidigare installerat tillägg. Vill du skriva över det befintliga tillägget?",
  "EXTENSION_SAME_VERSION": "Tillägget har samma versionsnummer som ett redan installerat tillägg. Vill du skriva över den befintliga installationen?",
  "EXTENSION_OLDER_VERSION": "Detta tillägg har versionsnummer {0} och är äldre än den nuvarade versionen ({1}). Vill du skriva över den befintliga installationen?",
  "DOWNLOAD_ID_IN_USE": "Internt fel: nedladdnings-ID används redan.",
  "NO_SERVER_RESPONSE": "Kunde inte ansluta till servern.",
  "BAD_HTTP_STATUS": "Filen kunde inte hittas på servern (HTTP {0}).",
  "CANNOT_WRITE_TEMP": "Kunde inte spara filen temporärt.",
  "ERROR_LOADING": "Tillägget stötte på ett fel under uppstart.",
  "MALFORMED_URL": "Adressen är felaktig. Vänligen kontrollera att du angett den korrekt.",
  "UNSUPPORTED_PROTOCOL": "Adressen måste använda http eller https.",
  "UNKNOWN_ERROR": "Okänt internt fel.",
  "EXTENSION_MANAGER_TITLE": "Tilläggshanteraren",
  "EXTENSION_MANAGER_ERROR_LOAD": "Kunde inte nå tilläggsregistret. Vänligen försök igen senare.",
  "INSTALL_EXTENSION_DRAG": "Dra .zip hit eller",
  "INSTALL_EXTENSION_DROP": "Släpp .zip här för att installera",
  "INSTALL_EXTENSION_DROP_ERROR": "Installation/Uppdatering avbröts på grund av följande fel:",
  "INSTALL_FROM_URL": "Installera från URL…",
  "INSTALL_EXTENSION_VALIDATING": "Validerar…",
  "EXTENSION_AUTHOR": "Författare",
  "EXTENSION_DATE": "Datum",
  "EXTENSION_INCOMPATIBLE_NEWER": "Detta tillägg kräver en nyare version av {APP_NAME}.",
  "EXTENSION_INCOMPATIBLE_OLDER": "Detta tillägg fungerar för närvarande bara med äldre versioner av {APP_NAME}.",
  "EXTENSION_LATEST_INCOMPATIBLE_NEWER": "Version {0} av detta tillägg kräver en nyare version av {APP_NAME} men du kan installera den äldre versionen {1}.",
  "EXTENSION_LATEST_INCOMPATIBLE_OLDER": "Version {0} av detta tillägg fungerar endast med äldre versioner av {APP_NAME} men du kan installera den äldre versionen {1}.",
  "EXTENSION_NO_DESCRIPTION": "Ingen beskrivning",
  "EXTENSION_MORE_INFO": "Mer information...",
  "EXTENSION_ERROR": "Tilläggsfel",
  "EXTENSION_KEYWORDS": "Nyckelord",
  "EXTENSION_TRANSLATED_USER_LANG": "Översatt till {0} språk, inklusive ditt",
  "EXTENSION_TRANSLATED_GENERAL": "Översatt till {0} språk",
  "EXTENSION_TRANSLATED_LANGS": "Detta tillägg har översatts till dessa språk: {0}",
  "EXTENSION_INSTALLED": "Installerade",
  "EXTENSION_UPDATE_INSTALLED": "Uppdateringen av detta tillägg har laddats ner och kommer att installeras när {APP_NAME} startas om.",
  "EXTENSION_SEARCH_PLACEHOLDER": "Sök",
  "EXTENSION_MORE_INFO_LINK": "Mer",
  "BROWSE_EXTENSIONS": "Bläddra bland tillägg",
  "EXTENSION_MANAGER_REMOVE": "Ta bort tillägg",
  "EXTENSION_MANAGER_REMOVE_ERROR": "Kunde inte ta bort ett eller flera tillägg: {0}. {APP_NAME} kommer fortfarande att startas om.",
  "EXTENSION_MANAGER_UPDATE": "Uppdatera tillägg",
  "EXTENSION_MANAGER_UPDATE_ERROR": "Kunde inte uppdatera ett eller flera tillägg: {0}. {APP_NAME} kommer fortfarande att startas om.",
  "EXTENSION_MANAGER_DISABLE": "Avaktivera tillägg",
  "EXTENSION_MANAGER_DISABLE_ERROR": "Kan inte avaktivera ett eller flera tillägg: {0}. {APP_NAME} kommer fortfarande att startas om.",
  "EXTENSION_MANAGER_THEMES_INFO": "<a class=\"theme_settings\">Klicka här</a> för att <a class=\"theme_settings\">välja standardteman</a> eller ändra andra temainställningar.",
  "MARKED_FOR_REMOVAL": "Markerad för borttagning",
  "UNDO_REMOVE": "Ångra",
  "MARKED_FOR_UPDATE": "Markerad för uppdatering",
  "UNDO_UPDATE": "Ångra",
  "MARKED_FOR_DISABLING": "Markerad för avaktivering",
  "UNDO_DISABLE": "Ångra",
  "CHANGE_AND_RELOAD_TITLE": "Ändra tillägg",
  "CHANGE_AND_RELOAD_MESSAGE": "{APP_NAME} måste startas om för att uppdatera eller ta bort markerade tillägg. Du kommer att få en fråga om att spara eventuella osparade ändringar.",
  "REMOVE_AND_RELOAD": "Ta bort tillägg och starta om",
  "CHANGE_AND_RELOAD": "Ta bort tillägg och starta om",
  "UPDATE_AND_RELOAD": "Ändra tillägg och starta om",
  "DISABLE_AND_RELOAD": "Inaktivera tillägg och ladda om",
  "PROCESSING_EXTENSIONS": "Genomför förändringar av tillägg…",
  "EXTENSION_NOT_INSTALLED": "Kunde inte radera tillägget {0} då det inte är installerat.",
  "NO_EXTENSIONS": "Inga tillägg har installerats ännu.<br>Klicka på fliken Tillgängliga för att komma igång.",
  "NO_EXTENSION_MATCHES": "Inga tillägg matchade din sökning.",
  "REGISTRY_SANITY_CHECK_WARNING": "Var försiktig när du installerar tillägg från okända källor.",
  "EXTENSIONS_INSTALLED_TITLE": "Installerade",
  "EXTENSIONS_DEFAULT_TITLE": "Standard",
  "EXTENSIONS_AVAILABLE_TITLE": "Tillgängliga",
  "EXTENSIONS_THEMES_TITLE": "Teman",
  "EXTENSIONS_UPDATES_TITLE": "Uppdateringar",
  "EXTENSIONS_LAST_UPDATED": "Senast uppdaterad",
  "EXTENSIONS_DOWNLOADS": "Nedladdningar",
  "INLINE_EDITOR_NO_MATCHES": "Inga träffar tillgängliga.",
  "INLINE_EDITOR_HIDDEN_MATCHES": "Alla träffar är minimerade. Expandera filerna listade till höger för att visa träffar.",
  "CSS_QUICK_EDIT_NO_MATCHES": "Det finns inga CSS-regler som matchar din markering.<br> Klicka på \"Ny regel\" för att skapa en.",
  "CSS_QUICK_EDIT_NO_STYLESHEETS": "Det finns inga stilmallar i ditt projekt.<br>Skapa en flr att lägga till CSS-regler.",
  "IMAGE_VIEWER_LARGEST_ICON": "största",
  "UNIT_PIXELS": "pixlar",
  "DEBUG_MENU": "Debug",
  "ERRORS": "Fel",
  "CMD_SHOW_DEV_TOOLS": "Visa utvecklarverktyg",
  "CMD_REFRESH_WINDOW": "Starta om med tillägg",
  "CMD_RELOAD_WITHOUT_USER_EXTS": "Starta om utan tillägg",
  "CMD_NEW_BRACKETS_WINDOW": "Nytt {APP_NAME}-fönster",
  "CMD_LAUNCH_SCRIPT_MAC": "Installera genväg i kommandotolk",
  "CMD_SWITCH_LANGUAGE": "Byt språk",
  "CMD_RUN_UNIT_TESTS": "Kör tester",
  "CMD_SHOW_PERF_DATA": "Visa prestandadata",
  "CMD_ENABLE_LOGGING": "Aktivera detaljerade loggar",
  "CMD_ENABLE_LIVE_PREVIEW_LOGS": "Live Preview-loggar",
  "CMD_OPEN_BRACKETS_SOURCE": "Öppna Brackets källkod",
  "CREATING_LAUNCH_SCRIPT_TITLE": "{APP_NAME} kommandotolk-genväg",
  "ERROR_CREATING_LAUNCH_SCRIPT": "Ett fel inträffade under installationen av kommandotolk-genvägen. Vänligen prova <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting'>dessa felsökningsförslag</a>.<br/><br/>Anledning: {0}",
  "ERROR_CLTOOLS_RMFAILED": "Kunde inte ta bort existerande symlink <code>/usr/local/bin/brackets</code>.",
  "ERROR_CLTOOLS_MKDIRFAILED": "Kunde inte skapa mappen <code>/usr/local/bin</code>.",
  "ERROR_CLTOOLS_LNFAILED": "Kunde inte skapa symlink <code>/usr/local/bin/brackets</code>.",
  "ERROR_CLTOOLS_SERVFAILED": "Internt fel.",
  "ERROR_CLTOOLS_NOTSUPPORTED": "Kommandotolk-genväg stöds inte för det här operativsystemet.",
  "LAUNCH_SCRIPT_CREATE_SUCCESS": "Lyckades! Nu kan du lätt starta {APP_NAME} från kommandotolken: <code>brackets myFile.txt</code> för att öppna en fil eller <code>brackets myFolder</code> för att växla projekt. <br/><br/><a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments'>Läs mer</a> om att använda {APP_NAME} från kommandotolken.",
  "LANGUAGE_TITLE": "Byt språk",
  "LANGUAGE_MESSAGE": "Språk:",
  "LANGUAGE_SUBMIT": "Uppdatera {APP_NAME}",
  "LANGUAGE_CANCEL": "Avbryt",
  "LANGUAGE_SYSTEM_DEFAULT": "Systemstandard",
  "HEALTH_DATA_NOTIFICATION": "Hälsorapport inställningar",
  "HEALTH_FIRST_POPUP_TITLE": "{APP_NAME} Hälsorapport",
  "HEALTH_DATA_DO_TRACK": "Dela anonym information om hur jag använder {APP_NAME}",
  "HEALTH_DATA_NOTIFICATION_MESSAGE": "För att förbättra {APP_NAME} skickar vi med jämna mellanrum begränsad, <strong>pseudonym</strong> statistik och felrapporter till phcode.dev om hur du använder {APP_NAME}. Den här informationen hjälper till att prioritera funktioner, hitta buggar och upptäcka användbarhetsproblem samtidigt som du skyddar din integritet.<br><br> Du kan se dina data eller välja att inte dela data genom att välja <strong>Hjälp &gt; Hälsorapport</strong> .<br><br>",
  "HEALTH_DATA_PREVIEW": "{APP_NAME} Hälsorapport",
  "HEALTH_DATA_PREVIEW_INTRO": "<p>För att förbättra {APP_NAME} skickar vi med jämna mellanrum begränsad, <strong>pseudonym</strong> statistik och felrapporter till phcode.dev om hur du använder {APP_NAME}. Den här informationen hjälper till att prioritera funktioner, hitta buggar och upptäcka användbarhetsproblem.</p><p> Nedan finns en förhandsgranskning av data som kommer att skickas i din nästa hälsorapport <em>om</em> den är aktiverad. (Se även utvecklarkonsolen för felloggar märkta &quot;Fångat kritiskt fel&quot;.)</p>",
  "INLINE_TIMING_EDITOR_TIME": "Tid",
  "INLINE_TIMING_EDITOR_PROGRESSION": "Progression",
  "BEZIER_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd><kbd>←</kbd><kbd>→</kbd> Flytta markerad punkt<br><kbd class='text'>Shift</kbd> Flytta tio enheter",
  "STEPS_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd> Öka eller minska antal steg<br><kbd>←</kbd><kbd>→</kbd> 'Start' eller 'Slut'",
  "INLINE_TIMING_EDITOR_INVALID": "Det tidigare värdet <code>{0}</code> är inte korrekt så den visade funktionen har ändrats till <code>{1}</code>. Dokumentet kommer att uppdateras med det första värdet.",
  "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP": "Nuvarande färg",
  "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP": "Originalfärg",
  "COLOR_EDITOR_RGBA_BUTTON_TIP": "RGBa-format",
  "COLOR_EDITOR_HEX_BUTTON_TIP": "Hex-format",
  "COLOR_EDITOR_HSLA_BUTTON_TIP": "HSLa-format",
  "COLOR_EDITOR_0X_BUTTON_TIP": "Hex (0x)-format",
  "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR": "{0} (använd {1} gång)",
  "COLOR_EDITOR_USED_COLOR_TIP_PLURAL": "{0} (använd {1} gånger)",
  "CMD_JUMPTO_DEFINITION": "Gå till definition",
  "CMD_SHOW_PARAMETER_HINT": "Visa parameterförslag",
  "NO_ARGUMENTS": "<inga parametrar>",
  "DETECTED_EXCLUSION_TITLE": "Problem att slutleda JavaScript-fil",
  "DETECTED_EXCLUSION_INFO": "Brackets stötte på processeringsfel:<br><br>{0}<br><br>Denna fil kommer inte längre genomsökas efter kodförslag eller definitioner. Öppna <code>.brackets.json</code> och ta bort filen från jscodehints.detectedExclusions för att återställa detta.",
  "CMD_REFACTOR": "Refaktor",
  "CMD_EXTRACTTO_VARIABLE": "Extrahera till Variabel",
  "CMD_EXTRACTTO_FUNCTION": "Extrahera för att fungera",
  "ERROR_TERN_FAILED": "Det går inte att få data från Tern",
  "ERROR_EXTRACTTO_VARIABLE_NOT_VALID": "Urval bildar inget uttryck",
  "ERROR_EXTRACTTO_FUNCTION_NOT_VALID": "Det valda blocket ska representera en uppsättning satser eller ett uttryck",
  "ERROR_EXTRACTTO_VARIABLE_MULTICURSORS": "Extrahera till variabel fungerar inte i flera markörer",
  "ERROR_EXTRACTTO_FUNCTION_MULTICURSORS": "Extrahera till funktion fungerar inte i flera markörer",
  "EXTRACTTO_FUNCTION_SELECT_SCOPE": "Välj destinationsomfång",
  "EXTRACTTO_VARIABLE_SELECT_EXPRESSION": "Välj ett uttryck",
  "CMD_REFACTORING_RENAME": "Byt namn",
  "CMD_REFACTORING_TRY_CATCH": "Slå in Try Catch",
  "CMD_REFACTORING_CONDITION": "Omslag i skick",
  "CMD_REFACTORING_GETTERS_SETTERS": "Skapa Getters/Setters",
  "CMD_REFACTORING_ARROW_FUNCTION": "Konvertera till pilfunktion",
  "DESCRIPTION_CODE_REFACTORING": "Aktivera/inaktivera JavaScript Code Refactoring",
  "ERROR_TRY_CATCH": "Välj en giltig kod att slå in i ett Try-catch-block",
  "ERROR_WRAP_IN_CONDITION": "Välj en giltig kod att slå in i ett villkorsblock",
  "ERROR_ARROW_FUNCTION": "Placera markören inuti ett funktionsuttryck",
  "ERROR_GETTERS_SETTERS": "Placera markören på en medlem av ett objektuttryck",
  "ERROR_RENAME_MULTICURSOR": "Kan inte byta namn när du använder flera markörer",
  "ERROR_RENAME_QUICKEDIT": "Det går inte att byta namn på denna identifierare, eftersom den hänvisas till någon annanstans utanför denna funktion",
  "ERROR_RENAME_GENERAL": "Kan inte byta namn på markerad text",
  "JSHINT_NAME": "JSHint",
  "CMD_ENABLE_QUICK_VIEW": "Quick View vid hover",
  "CMD_ENABLE_SELECTION_VIEW": "Urvalsvy",
  "TOOLTIP_CLICK_TO_EDIT_COLOR": "Klicka här för att redigera färg",
  "CMD_TOGGLE_RECENT_PROJECTS": "Senaste projekt",
  "DOCS_MORE_LINK": "Läs mer",
  "COLLAPSE_ALL": "Kollapsa alla",
  "EXPAND_ALL": "Expandera alla",
  "COLLAPSE_CURRENT": "Kollapsa nuvarande",
  "EXPAND_CURRENT": "Expandera nuvarande",
  "RECENT_FILES_DLG_HEADER": "Senaste filer",
  "RECENT_FILES_DLG_CLEAR_BUTTON_LABEL": "Rensa",
  "RECENT_FILES_DLG_CLEAR_BUTTON_TITLE": "Rensa filer ej i arbetsyta",
  "DESCRIPTION_CLOSE_BRACKETS": "sant att automatiskt stänga hängslen, parenteser och parenteser",
  "DESCRIPTION_CLOSE_OTHERS_ABOVE": "false för att ta bort \"Stäng andra ovan\" från snabbmenyn för arbetsfiler",
  "DESCRIPTION_CLOSE_OTHERS_BELOW": "false för att ta bort \"Stäng andra nedan\" från snabbmenyn för arbetsfiler",
  "DESCRIPTION_CLOSE_OTHERS": "false för att ta bort \"Stäng andra\" från snabbmenyn för arbetsfiler",
  "DESCRIPTION_CLOSE_TAGS": "Ställer in alternativen för taggstängning",
  "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS": "En uppsättning taggar som inte bör stängas automatiskt",
  "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING": "Stäng när > av öppningstaggen har skrivits",
  "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING": "Stäng när / av avslutande tagg skrivs",
  "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS": "En rad taggar som när de öppnas har en tom rad",
  "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD": "sant för att alltid generera hopfällbara avsnittsmarkörer när indragsnivån ändras",
  "DESCRIPTION_CODE_FOLDING_ENABLED": "sant för att möjliggöra kodvikning",
  "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER": "sant för att göra sektionskollapsande markörer synliga endast när du flyttar musen över rännstenen",
  "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL": "Begränsar hur många nivåer djupt Collapse All gäller",
  "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE": "Minsta rader innan en hopfällbar sektionsikon visas",
  "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES": "sant att komma ihåg komprimerade avsnitt om du stänger och öppnar en fil eller ett projekt igen",
  "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE": "sant för att aktivera kodvikning på vald text i editorn",
  "DESCRIPTION_DISABLED_DEFAULT_EXTENSIONS": "Standardtillägg som är inaktiverade",
  "DESCRIPTION_ATTR_HINTS": "Aktivera/inaktivera HTML-attributtips",
  "DESCRIPTION_CSS_PROP_HINTS": "Aktivera/inaktivera CSS/LESS/SCSS-egenskapstips",
  "DESCRIPTION_JS_HINTS": "Aktivera/inaktivera JavaScript-kodtips",
  "DESCRIPTION_JS_HINTS_TYPE_DETAILS": "Aktivera/inaktivera datatypdetaljer i JavaScript-kodtips",
  "DESCRIPTION_PREF_HINTS": "Aktivera/inaktivera Preferences-kodtips",
  "DESCRIPTION_SPECIAL_CHAR_HINTS": "Aktivera/inaktivera HTML-entitetstips",
  "DESCRIPTION_SVG_HINTS": "Aktivera/inaktivera SVG-kodtips",
  "DESCRIPTION_HTML_TAG_HINTS": "Aktivera/inaktivera HTML-taggtips",
  "DESCRIPTION_URL_CODE_HINTS": "Aktivera/inaktivera URL-tips i HTML & CSS/LESS/SCSS",
  "DESCRIPTION_DRAG_DROP_TEXT": "Aktivera/inaktivera Dra & Drop-funktionalitet",
  "DESCRIPTION_HEALTH_DATA_TRACKING": "Aktivera hälsodataspårning",
  "DESCRIPTION_HIGHLIGHT_MATCHES": "Möjliggör automatisk markering av matchande strängar i hela dokumentet",
  "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN": "Markera alla strängar som matchar token markören befinner sig i (inget val behövs)",
  "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY": "Markera endast när valet är en fullständig token",
  "DESCRIPTION_INSERT_HINT_ON_TAB": "sant för att infoga det för närvarande valda kodtipset på fliken",
  "DESCRIPTION_NO_HINTS_ON_DOT": "sant för att inte automatiskt visa JS-kodtips när . är maskinskrivet",
  "DESCRIPTION_JSHINT_OPTIONS": "Ett objekt med standardalternativen för JSHint. Se följande URL för alla tillgängliga JSHint-alternativ: https://jshint.com/docs/options/",
  "DESCRIPTION_LANGUAGE": "Språkspecifika inställningar",
  "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS": "Ytterligare mappningar från filtillägg till språknamn",
  "DESCRIPTION_LANGUAGE_FILE_NAMES": "Ytterligare mappningar från filnamn till språknamn",
  "DESCRIPTION_LINEWISE_COPY_CUT": "Om du kopierar och klipper ut när det inte finns något val kommer du att kopiera eller klippa hela raderna som har markörer i dem",
  "DESCRIPTION_INPUT_STYLE": "Väljer hur CodeMirror hanterar inmatning och fokus. Det kan vara textarea, som är standard, eller contenteditable vilket är bättre för skärmläsare (instabil)",
  "DESCRIPTION_LINTING_ENABLED": "sant för att aktivera kodinspektion",
  "DESCRIPTION_ASYNC_TIMEOUT": "Tiden i millisekunder efter vilken asynkrona linters timeout",
  "DESCRIPTION_LINTING_PREFER": "Array av linters att köra först",
  "DESCRIPTION_LIVE_DEV_MULTIBROWSER": "sant för att aktivera experimentell Live Preview",
  "DESCRIPTION_USE_PREFERED_ONLY": "leverantörer som anges i linting.prefer endast",
  "DESCRIPTION_MAX_CODE_HINTS": "Maximalt antal kodtips visas på en gång",
  "DESCRIPTION_PATH": "Sökvägsspecifika inställningar",
  "DESCRIPTION_PROXY": "URL:en till proxyservern som används för installation av tillägg",
  "DESCRIPTION_SCROLL_PAST_END": "sant för att möjliggöra rullning bortom slutet av dokumentet",
  "DESCRIPTION_SHOW_CODE_HINTS": "false för att inaktivera alla kodtips",
  "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING": "Håller den blinkande markören synlig när du har ett textval",
  "DESCRIPTION_SHOW_LINE_NUMBERS": "sant för att visa radnummer i en \"ränna\" till vänster om koden",
  "DESCRIPTION_SMART_INDENT": "Indrag automatiskt när du skapar ett nytt block",
  "DESCRIPTION_SOFT_TABS": "false för att stänga av beteendet med mjuka flikar",
  "DESCRIPTION_SORT_DIRECTORIES_FIRST": "sant att sortera katalogerna först i projektträdet",
  "DESCRIPTION_SPACE_UNITS": "Antal utrymmen som ska användas för utrymmesbaserad indragning",
  "DESCRIPTION_STATIC_SERVER_PORT": "Portnummer som den inbyggda servern ska använda för Live Preview",
  "DESCRIPTION_STYLE_ACTIVE_LINE": "sant för att markera bakgrundsfärgen på linjen som markören är på",
  "DESCRIPTION_TAB_SIZE": "Antal utrymmen att visa för flikar",
  "DESCRIPTION_USE_TAB_CHAR": "sant att använda tabbar istället för blanksteg",
  "DESCRIPTION_UPPERCASE_COLORS": "sant för att generera hex-färger med stora bokstäver i Inline Color Editor",
  "DESCRIPTION_WORD_WRAP": "Wrap linjer som överskrider visningsportens bredd",
  "DESCRIPTION_SEARCH_AUTOHIDE": "Stäng sökningen så snart redigeraren är fokuserad",
  "DESCRIPTION_DETECTED_EXCLUSIONS": "En lista över filer som har upptäckts för att få Tern att köra utom kontroll",
  "DESCRIPTION_INFERENCE_TIMEOUT": "Tiden efter vilken Tern kommer att ta en timeout när han försöker förstå filer",
  "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR": "sant för att visa fel i statusfältet",
  "DESCRIPTION_QUICK_VIEW_ENABLED": "sant för att aktivera Quick View",
  "DESCRIPTION_SELECTION_VIEW_ENABLED": "sant för att aktivera urvalsvy",
  "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW": "sant för att visa bildförhandsvisningar för webbadresser som saknar tillägg",
  "DESCRIPTION_NUMBER_QUICK_VIEW": "sant för att visa snabbvy när du håller muspekaren över siffror i editorn",
  "DESCRIPTION_THEME": "Välj ett {APP_NAME}-tema",
  "DESCRIPTION_USE_THEME_SCROLLBARS": "sant för att tillåta anpassade rullningslister",
  "DESCRIPTION_LINTING_COLLAPSED": "sann att kollapsa luddpanel",
  "DESCRIPTION_FONT_FAMILY": "Ändra teckensnittsfamilj",
  "DESCRIPTION_FONT_SIZE": "Ändra typsnittsstorlek; t.ex. 13 px",
  "DESCRIPTION_FIND_IN_FILES_NODE": "sant för att aktivera nodbaserad sökning",
  "DESCRIPTION_FIND_IN_FILES_INSTANT": "sant för att möjliggöra omedelbar sökning",
  "DESCRIPTION_FONT_SMOOTHING": "Endast för Mac: \"utjämnade underpixlar\" för att aktivera kantutjämning av underpixlar eller \"utjämnade\" för kantutjämning i gråskala",
  "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW": "false för att inaktivera öppningspreferensfilen i delad vy",
  "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE": "false för att öppna användarpreferensfilen i vänstra/översta rutan",
  "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED": "sant att komprimera fönster efter att den sista filen från rutan stängts via stängningsknappen för rutans rubrik",
  "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS": "Växla när du vill visa stängnings- och flip-view-knapparna i sidhuvudet.",
  "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT": "/*\n * Det här är en skrivskyddad fil med de inställningar som stöds\n * av {APP_NAME}.\n * Använd den här filen som referens för att ändra dina inställningar\n * filen \"brackets.json\" öppnas i den andra rutan.\n * För mer information om hur du använder inställningar inuti\n * {APP_NAME}, se webbsidan på https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences\n */",
  "DEFAULT_PREFERENCES_JSON_DEFAULT": "Standard",
  "DESCRIPTION_PURE_CODING_SURFACE": "sant för att aktivera endast kodläge och dölja alla andra UI-element i {APP_NAME}",
  "DESCRIPTION_INDENT_LINE_COMMENT": "sant för att möjliggöra indrag av radkommentarer",
  "DESCRIPTION_RECENT_FILES_NAV": "Aktivera/inaktivera navigering i de senaste filerna",
  "DESCRIPTION_LIVEDEV_WEBSOCKET_PORT": "Port på vilken WebSocket Server körs för Live Preview",
  "DESCRIPTION_LIVE_DEV_HIGHLIGHT_SETTINGS": "Inställningar för Live Preview Highlight",
  "DESCRIPTION_LIVEDEV_ENABLE_REVERSE_INSPECT": "false för att inaktivera liveförhandsgranskning omvänd inspektera",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW": "Inget att förhandsgranska!",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW_DETAILS": "Välj en HTML-fil att förhandsgranska",
  "DOWNLOAD_FAILED": "Nedladdning misslyckad.",
  "DOWNLOAD_COMPLETE": "Nedladdning klar!",
  "UPDATE_SUCCESSFUL": "Uppdatering lyckades!",
  "UPDATE_FAILED": "Uppdateringen misslyckades!",
  "VALIDATION_FAILED": "Validering misslyckades!",
  "INITIALISATION_FAILED": "Initiering misslyckades!",
  "CLEANUP_FAILED": "Rengöring misslyckades!",
  "WARNING_TYPE": "Varning!",
  "CLICK_RESTART_TO_UPDATE": "Klicka på Starta om för att uppdatera parenteser.",
  "UPDATE_ON_NEXT_LAUNCH": "Uppdateringen kommer att tillämpas vid omstart.",
  "GO_TO_SITE": "Gå till <a href = \"http://brackets.io/\">brackets.io</a> för att försöka igen.",
  "INTERNET_UNAVAILABLE": "Ingen internetanslutning tillgänglig.",
  "UPDATEDIR_READ_FAILED": "Uppdateringskatalogen kunde inte läsas.",
  "UPDATEDIR_CLEAN_FAILED": "Uppdateringskatalogen kunde inte rengöras.",
  "INITIAL_DOWNLOAD": "Laddar ned uppdatering...",
  "RETRY_DOWNLOAD": "Nedladdning misslyckad. Försöker igen...Försök",
  "VALIDATING_INSTALLER": "Nedladdning klar! Validerar installationsprogrammet...",
  "CHECKSUM_DID_NOT_MATCH": "Kontrollsumman stämde inte.",
  "INSTALLER_NOT_FOUND": "Installationsprogrammet hittades inte.",
  "DOWNLOAD_ERROR": "Ett fel uppstod vid nedladdning.",
  "NETWORK_SLOW_OR_DISCONNECTED": "Nätverket är frånkopplat eller för långsamt.",
  "RESTART_BUTTON": "Omstart",
  "LATER_BUTTON": "Senare",
  "DESCRIPTION_AUTO_UPDATE": "Aktivera/inaktivera automatisk uppdatering av parenteser",
  "AUTOUPDATE_ERROR": "Fel!",
  "AUTOUPDATE_IN_PROGRESS": "En uppdatering pågår redan.",
  "NUMBER_WITH_PERCENTAGE": "{0}%",
  "CMD_FIND_RELATED_FILES": "Hitta relaterade filer",
  "PHP_VERSION_INVALID": "Fel vid analys av PHP-version. Kontrollera utdata från kommandot \"php –version\".",
  "PHP_UNSUPPORTED_VERSION": "Installera PHP7 runtime för att aktivera PHP-relaterade verktyg som kodtips, parametertips, hoppa till definition och mer. Version hittades: {0}",
  "PHP_EXECUTABLE_NOT_FOUND": "PHP-körtid hittades inte. Installera PHP7 runtime och uppdatera \"executablePath\" i PHP-inställningarna på lämpligt sätt. Detta möjliggör PHP-relaterade verktyg som kodtips, parametertips, hoppa till definition och mer.",
  "PHP_PROCESS_SPAWN_ERROR": "Felkod {0} påträffades när PHP-processen startas.",
  "PHP_SERVER_ERROR_TITLE": "Fel",
  "PHP_SERVER_MEMORY_LIMIT_INVALID": "Minnesgränsen du angav är ogiltig. Granska PHP-inställningarna för att ställa in rätt värde.",
  "DESCRIPTION_PHP_TOOLING_CONFIGURATION": "PHP Tooling standardkonfigurationsinställningar",
  "OPEN_PREFERENNCES": "Öppna Inställningar",
  "LANGUAGE_TOOLS_PREFERENCES": "Inställningar för språkverktyg",
  "FIND_ALL_REFERENCES": "Hitta alla referenser",
  "REFERENCES_IN_FILES": "referenser",
  "REFERENCE_IN_FILES": "referens",
  "REFERENCES_NO_RESULTS": "Inga referenser tillgängliga för aktuell markörposition",
  "CMD_FIND_DOCUMENT_SYMBOLS": "Hitta dokumentsymboler",
  "CMD_FIND_PROJECT_SYMBOLS": "Hitta projektsymboler",
  "REMOTE_DEBUGGING_ENABLED": "Fjärrfelsökning aktiverad på localhost:",
  "REMOTE_DEBUGGING_PORT_INVALID": "Det går inte att aktivera fjärrfelsökning på port {0}. Portnummer bör vara mellan {1} och {2}.",
  "DESCRIPTION_EXTERNAL_APPLICATION_ASSOCIATE": "Mappningar för filtillägg till externa applikationer. Syntax: \"<filtyp>\": \"<standard|programnamn|ApplicationPath>\", Använd \"default\" för att öppna filer i systemets standardprogram för filtypen.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_TITLE": "Öppna grafikfiler i externa redigerare.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_MSG": "Din nuvarande mapp har grafiska filtyper som inte stöds av {APP_NAME}.<br/> Du kan nu associera specifika filtyper med externa redigerare. När de är associerade kan du öppna grafikfiler som .xd, .psd, .jpg, .png, .ai, .svg i deras standardapplikationer genom att dubbelklicka på filerna i filträdet.<br/><br/> Klicka på &quot;Ok&quot;-knappen för att associera grafikfiltyperna med deras respektive standardapplikationer.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_CNF_MSG": "Följande filtyper har framgångsrikt associerats med standardapplikationer.<br/> {0} Du har möjlighet att ändra dina inställningar om du tar bort/lägger till nya filtypsassociationer inom brackets.json genom att gå till menyn &quot;Felsökning-&gt;Öppna inställningsfil&quot;.",
  "UNSUPPORTED_BROWSER": "Webbläsaren stöds inte",
  "UNSUPPORTED_BROWSER_MOBILE": "Mobila enheter och surfplattor stöds för närvarande inte fullt ut. Du kan stänga den här dialogrutan, men vissa funktioner i Phoenix fungerar inte i den här webbläsaren.",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER": "Webbläsaren stöder inte Öppna mapp. Använd Chrome, Edge eller Opera för att öppna lokala mappar.",
  "UNSUPPORTED_BROWSER_MESSAGE_LINE1": "Använd en av de webbläsare som stöds nedan.",
  "UNSUPPORTED_BROWSER_MESSAGE_LINE2": " Vi arbetar hårt för att göra Phoenix tillgängligt i fler webbläsare. Du kan stänga den här dialogrutan, men vissa funktioner i Phoenix fungerar inte i den här webbläsaren.",
  "CANNOT_PUBLISH_LARGE_PROJECT": "Kan inte publicera stort projekt",
  "CANNOT_PUBLISH_LARGE_PROJECT_MESSAGE": "Phoenix är fortfarande i experimentell alfa. Vi har ännu inte aktiverat synkronisering av projekt med fler än 500 filer.",
  "SHARE_WEBSITE": "Publicera och dela webbplats?",
  "PUBLISH": "Publicera",
  "PUBLISH_CONSENT_MESSAGE": "Förhandsgranska snabbt ändringar och dela din webbplats med andra. Phoenix kan publicera den här webbplatsen åt dig på {0}. De publicerade länkarna kommer att vara giltiga i en period av 7 dagar. </br>Vill du publicera och dela din webbplats?",
  "PUBLISH_SYNC_IN_PROGRESS": "Synkronisering pågår för förhandsgranskning...",
  "PUBLISH_PAGE": "Klicka för att publicera och dela denna webbplats",
  "PUBLISH_VIEW_PAGE": "Klicka för att se publicerad sida",
  "MISSING_FIELDS": "Saknade fält",
  "PLEASE_FILL_ALL_REQUIRED": "Fyll i alla obligatoriska fält markerade i rött",
  "CODE_EDITOR": "Kodredigerare",
  "BUILD_THE_WEB": "Bygg webben",
  "IMPORT_PROJECT": "Importera projekt",
  "GITHUB_PROJECT": "GitHub-projekt",
  "NEW_PROJECT_FROM_GITHUB": "Nytt projekt från GitHub",
  "GITHUB_REPO_URL": "GitHub Repo URL:",
  "CREATE_PROJECT": "Skapa projekt",
  "SETTING_UP_PROJECT": "Konfigurera projekt",
  "LOCATION": "Plats:",
  "DOWNLOADING": "Laddar ner...",
  "DOWNLOADING_FILE": "Laddar ned {0}...",
  "EXTRACTING_FILES_PROGRESS": "Extraherar {0} av {1} filer.",
  "COMPRESS_FILES_PROGRESS": "Komprimerar {0} av {1} filer.",
  "DOWNLOAD_FAILED_MESSAGE": "Se till att nedladdningsadressen är giltig. </br>OBS: Eftersom Phoenix är i alfa, är privata repos och GitHub-webbadresser större än 25 MB inte tillåtna.",
  "PLEASE_SELECT_A_FOLDER": "Välj en mapp...",
  "UNZIP_IN_PROGRESS": "Packar upp filer...",
  "UNZIP_FAILED": "Fel: Uppackning misslyckades.",
  "CONFIRM_REPLACE_TITLE": "Bekräfta Ersätt",
  "KEEP_BOTH": "Behåll båda",
  "EXPLORE": "HTML-spel",
  "BLOG": "Blogg",
  "PHOENIX_DEFAULT_PROJECT": "Standardprojekt",
  "PROJECT_NAME": "Projektnamn:",
  "NEW_HTML": "Nytt HTML-projekt",
  "LICENSE": "Licens:",
  "CREDITS": "Krediter:",
  "PREVIEW": "Förhandsvisning",
  "BUILD_WEBSITE": "Bygg webbplats",
  "VIEW_MORE": "Visa mer...",
  "NEW_PROJECT_NOTIFICATION": "Klicka på den här ikonen för att<br/> skapa ett nytt projekt.</br> <a href='#' style='float:right;'>ok</a>",
  "BEAUTIFY_CODE_NOTIFICATION": "Klicka här eller tryck på <b>`{0}`</b> för att försköna koden.</br><img src=\"extensions/default/Phoenix/images/beautify.gif\"><br/> <a href='#' style='float:right;'>ok</a>",
  "DEFAULT_PROJECT_NOTIFICATION": "Klicka här för att öppna<br/> <b>standardprojekt</b> i phoenix.</br> <a href='#' style='float:right;'>ok</a>",
  "DIRECTORY_REPLACE_MESSAGE": "Den valda mappen <span class='dialog-filename'>{0}</span> är inte tom. Är du säker på att du vill ersätta mappinnehållet med projektet?",
  "BUILD_WEBSITE_SECTION": "Bygg webbplats",
  "LEARN_SECTION": "Lär dig med exempel",
  "WEBPAGE_HOME_PAGE": "Hemsida",
  "WEBPAGE_BLOG": "Bloggsida",
  "WEBPAGE_DASHBOARD": "HTML Dashboard",
  "WEBPAGE_BOOTSTRAP_EXAMPLES": "Exempel på bootstrap",
  "PROJECTS_AT_A_GLANCE": "Dina projekt i en överblick",
  "PROJECT_AT_GLANCE_DESCRIPTION": "Titta på video för att komma igång.",
  "GUIDED_LIVE_PREVIEW": "Gör några kodändringar i HTML-filen för att se liveförhandsgranskning.</br> <a href='#' style='float:right;'>ok</a>",
  "GUIDED_LIVE_PREVIEW_POPOUT": "Klicka på den här knappen för att öppna liveförhandsvisningen till en ny flik.</br> <a href='#' style='float:right;'>ok</a>",
  "ENJOYING_APP": "Gillar du {APP_NAME}?",
  "GITHUB_STARS_POPUP": "<div>Dina recensioner håller vårt lilla team motiverat att göra <b>phcode.dev</b> ännu bättre.<br/> Vänligen stjärna oss på GitHub:",
  "GITHUB_STARS_POPUP_TWITTER": "Ge feedback eller sprid ordet på Twitter:",
  "TEST_TRANSLATE": "använd detta för att testa översättningar",
  "POWER_USER_POPUP_TITLE": "Hur kan vi göra {APP_NAME} bättre för dig?",
  "POWER_USER_POPUP_TEXT": "<div>Vi vill gärna ha din feedback. Din feedback hjälper oss att bestämma vilka funktioner som ska byggas och vilka förbättringar som bör göras på vår plattform.<br/> <a>Fyll i denna korta enkät.</a></div>",
  "BEAUTIFY_ERROR": "Det gick inte att försköna koden. Kontrollera syntax.",
  "BEAUTIFY_ERROR_ORIGINAL_CHANGED": "Kunde inte försköna. Redaktörstext ändrad efter försköning.",
  "BEAUTIFY_PROJECT_BUSY_MESSAGE": "Försköna fil {0}",
  "BEAUTIFY_ERROR_SELECTION": "Kunde inte försköna.</br>Ofullständigt kodblock valt eller ogiltig syntax.",
  "BEAUTIFY_OPTIONS": "Alternativ som styr hur Beautify Code fungerar",
  "BEAUTIFY_OPTION_PRINT_WIDTH": "Ange radlängden som beautifier ska lindas på",
  "BEAUTIFY_OPTION_SEMICOLON": "Lägg till ett semikolon i slutet av varje påstående",
  "BEAUTIFY_OPTION_SINGLE_QUOTE": "Använd enkla citattecken istället för dubbla citattecken",
  "BEAUTIFY_OPTION_QUOTE_PROPS": "Ändra när egenskaper i objekt citeras",
  "BEAUTIFY_OPTION_BRACKET_SAME_LINE": "Sätt > för ett HTML-element med flera rader (HTML, JSX, Vue, Angular) i slutet av den sista raden istället för att vara ensam på nästa rad (gäller inte självstängande element)",
  "BEAUTIFY_OPTION_SINGLE_ATTRIBUTE_PER_LINE": "Genomför ett enda attribut per rad i HTML, Vue och JSX",
  "BEAUTIFY_OPTION_PROSE_WRAP": "Slå in prosa om den överskrider utskriftsbredden i markdown-filer",
  "BEAUTIFY_OPTION_PRINT_TRAILING_COMMAS": "Skriv ut avslutande kommatecken där det är möjligt i flerrads kommaseparerade syntaktiska strukturer"
});