/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "افتراضي النظام",
  "PROJECT_BUSY": "عمليات المشروع قيد التقدم",
  "DUPLICATING": "تكرار {0}",
  "MOVING": "الانتقال {0}",
  "COPYING": "نسخ {0}",
  "DELETING": "حذف {0}",
  "RENAMING": "إعادة تسمية",
  "GENERIC_ERROR": "(خطأ {0})",
  "NOT_FOUND_ERR": "تعذر العثور على الملف/الدليل.",
  "NOT_READABLE_ERR": "تعذّر قراءة الملف/الدليل.",
  "EXCEEDS_MAX_FILE_SIZE": "لا يمكن فتح الملفات الأكبر من {0} ميغابايت في {APP_NAME}.",
  "NO_MODIFICATION_ALLOWED_ERR": "لا يمكن تعديل الدليل الهدف.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "لا تسمح لك الأذونات بإجراء تعديلات.",
  "CONTENTS_MODIFIED_ERR": "تم تعديل الملف خارج {APP_NAME}.",
  "UNSUPPORTED_ENCODING_ERR": "تنسيق ترميز غير معروف",
  "ENCODE_FILE_FAILED_ERR": "لم يتمكن {APP_NAME} من ترميز محتويات الملف.",
  "DECODE_FILE_FAILED_ERR": "لم يتمكن {APP_NAME} من فك تشفير محتويات الملف.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "{APP_NAME} لا يدعم حاليًا الملفات النصية المشفرة UTF-16.",
  "FILE_EXISTS_ERR": "الملف أو الدليل موجود بالفعل.",
  "FILE": "ملف",
  "FILE_TITLE": "ملف",
  "DIRECTORY": "دليل",
  "DIRECTORY_TITLE": "دليل",
  "DIRECTORY_NAMES_LEDE": "أسماء الدليل",
  "FILENAMES_LEDE": "أسماء الملفات",
  "FILENAME": "اسم الملف",
  "DIRECTORY_NAME": "اسم الدليل",
  "ERROR_LOADING_PROJECT": "خطأ في تحميل المشروع",
  "OPEN_DIALOG_ERROR": "حدث خطأ عند عرض مربع حوار الملف المفتوح. (خطأ {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "حدث خطأ عند محاولة تحميل الدليل <span class='dialog-filename'>{0}</span>. (خطأ {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "حدث خطأ عند قراءة محتويات الدليل <span class='dialog-filename'>{0}</span>. (خطأ {1})",
  "ERROR_OPENING_FILE_TITLE": "حدث خطأ أثناء فتح الملف",
  "ERROR_OPENING_FILE": "حدث خطأ عند محاولة فتح الملف <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_OPENING_FILES": "حدث خطأ عند محاولة فتح الملفات التالية:",
  "ERROR_RELOADING_FILE_TITLE": "خطأ في إعادة تحميل التغييرات من القرص",
  "ERROR_RELOADING_FILE": "حدث خطأ عند محاولة إعادة تحميل الملف <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_SAVING_FILE_TITLE": "حدث خطأ أثناء حفظ الملف",
  "ERROR_SAVING_FILE": "حدث خطأ عند محاولة حفظ الملف <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_FILE_TITLE": "خطأ في إعادة تسمية {0}",
  "ERROR_RENAMING_FILE": "حدث خطأ عند محاولة إعادة تسمية {2} <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "الملف أو الدليل ليس جزءًا من المشروع المفتوح حاليًا. لسوء الحظ، يمكن إعادة تسمية ملفات المشروع فقط في هذه المرحلة.",
  "ERROR_MOVING_FILE_TITLE": "حدث خطأ أثناء النقل {0}",
  "ERROR_MOVING_FILE": "حدث خطأ عند محاولة نقل {2} <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "لا يمكن نقل الملف/المجلد، لأنها ليست جزءا من المشروع الحالي.",
  "ERROR_DELETING_FILE_TITLE": "حدث خطأ أثناء الحذف {0}",
  "ERROR_DELETING_FILE": "حدث خطأ عند محاولة حذف {2} <span class='dialog-filename'>{0}</span>. {1}",
  "INVALID_FILENAME_TITLE": "غير صالح {0}",
  "CANNOT_PASTE_TITLE": "لا يمكن لصق {0}",
  "ERR_TYPE_PASTE_FAILED": "حدث خطأ أثناء لصق <span class='dialog-filename'>{0}</span> إلى <span class='dialog-filename'>{1}</span>",
  "CANNOT_DUPLICATE_TITLE": "لا يمكن التكرار",
  "ERR_TYPE_DUPLICATE_FAILED": "حدث خطأ أثناء تكرار <span class='dialog-filename'>{0}</span>",
  "INVALID_FILENAME_MESSAGE": "{0} لا يمكن استخدام أي كلمات محجوزة للنظام، تنتهي بالنقاط (.) أو استخدام أي من الأحرف التالية: <code class='emphasized'>{1}</code>",
  "ENTRY_WITH_SAME_NAME_EXISTS": "يوجد بالفعل ملف أو دليل باسم <span class='dialog-filename'>{0}</span>.",
  "ERROR_CREATING_FILE_TITLE": "حدث خطأ أثناء إنشاء {0}",
  "ERROR_CREATING_FILE": "حدث خطأ عند محاولة إنشاء {0} <span class='dialog-filename'>{1}</span>. {2}",
  "ERROR_MIXED_DRAGDROP": "لا يمكن فتح مجلد في نفس وقت فتح الملفات الأخرى.",
  "ERROR_KEYMAP_TITLE": "خطأ في قراءة خريطة مفتاح المستخدم",
  "ERROR_KEYMAP_CORRUPT": "ملف الخريطة الرئيسي الخاص بك غير صالح JSON. سيتم فتح الملف بحيث يمكنك تصحيح التنسيق.",
  "ERROR_LOADING_KEYMAP": "ملف الخريطة الرئيسي الخاص بك ليس ملف نصي مشفر UTF-8 صالح ولا يمكن تحميله",
  "ERROR_RESTRICTED_COMMANDS": "لا يمكنك إعادة تعيين الاختصارات لهذه الأوامر: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "لا يمكنك إعادة تعيين هذه الاختصارات: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "أنت تعيد تعيين اختصارات متعددة لهذه الأوامر: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "لديك روابط متعددة لهذه الاختصارات: {0}",
  "ERROR_INVALID_SHORTCUTS": "هذه الاختصارات غير صالحة: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "أنت تقوم بتعيين اختصارات لأوامر غير موجودة: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "تفضيلات قراءة الخطأ",
  "ERROR_PREFS_CORRUPT": "ملف التفضيلات الخاص بك غير صالح JSON. سيتم فتح الملف بحيث يمكنك تصحيح التنسيق. ستحتاج إلى إعادة تشغيل {APP_NAME} حتى تصبح التغييرات نافذة المفعول.",
  "ERROR_PROJ_PREFS_CORRUPT": "ملف تفضيلات المشروع الخاص بك غير صالح JSON. سيتم فتح الملف بحيث يمكنك تصحيح التنسيق. ستحتاج إلى إعادة تحميل المشروع حتى تصبح التغييرات سارية المفعول.",
  "ERROR_IN_BROWSER_TITLE": "عفوا! {APP_NAME} لا يتم تشغيله في المتصفحات حتى الآن.",
  "ERROR_IN_BROWSER": "تم إنشاء {APP_NAME} في HTML، ولكنه يعمل الآن كتطبيق سطح مكتب حتى تتمكن من استخدامه لتحرير الملفات المحلية. الرجاء استخدام غلاف التطبيق في الريبو <b>github.com/adobe/brackets-shell</b> لتشغيل {APP_NAME}.",
  "ERROR_MAX_FILES_TITLE": "خطأ في فهرسة الملفات",
  "ERROR_MAX_FILES": "يحتوي هذا المشروع على أكثر من 30،000 ملف. قد يتم تعطيل الميزات التي تعمل عبر ملفات متعددة أو تتصرف كما لو كان المشروع فارغًا. <a href='https://github.com/adobe/brackets/wiki/Large-Projects'>اقرأ المزيد عن العمل مع المشاريع الكبيرة</a>.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "حدث خطأ أثناء تشغيل المتصفح",
  "ERROR_CANT_FIND_CHROME": "تعذر العثور على متصفح Google Chrome. يرجى التأكد من تثبيته.",
  "ERROR_LAUNCHING_BROWSER": "حدث خطأ عند تشغيل المتصفح. (خطأ {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "خطأ المعاينة المباشرة",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "الاتصال بالمتصفح",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "لكي تتمكن المعاينة المباشرة من الاتصال، يجب إعادة تشغيل Chrome مع تمكين تصحيح الأخطاء عن بُعد. <br /><br />هل ترغب في إعادة تشغيل Chrome وتمكين تصحيح الأخطاء عن بُعد؟ <br /><br />",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "غير قادر على تحميل صفحة المعاينة المباشرة.",
  "LIVE_DEV_NEED_HTML_MESSAGE": "افتح ملف HTML أو تأكد من وجود ملف index.html في مشروعك لبدء المعاينة المباشرة.",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "لبدء المعاينة المباشرة مع ملف من جانب الخادم، تحتاج إلى تحديد عنوان URL الأساسي لهذا المشروع.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "حدث خطأ أثناء بدء تشغيل خادم HTTP لملفات المعاينة المباشرة. يرجى المحاولة مرة أخرى.",
  "LIVE_DEVELOPMENT_INFO_TITLE": "مرحبًا بك في المعاينة المباشرة!",
  "LIVE_DEVELOPMENT_INFO_MESSAGE": "تربط المعاينة المباشرة {APP_NAME} بمتصفحك. يقوم بتشغيل معاينة لملف HTML الخاص بك في المتصفح، ثم يقوم بتحديث المعاينة على الفور أثناء تحرير التعليمات البرمجية الخاصة بك. <br /><br />في هذا الإصدار المبكر من {APP_NAME}، تعمل المعاينة المباشرة فقط مع <strong>Google Chrome</strong> والتحديثات مباشرة أثناء تحرير <strong>ملفات CSS أو HTML</strong>. تتم إعادة تحميل التغييرات على ملفات JavaScript تلقائيًا عند الحفظ. <br /><br />(سترى هذه الرسالة مرة واحدة فقط.)",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "لمزيد من المعلومات، راجع <a href='{0}' title='{0}'>استكشاف أخطاء اتصال المعاينة المباشرة وإصلاحها</a>.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "معاينة مباشرة",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "المعاينة المباشرة: الاتصال...",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "معاينة مباشرة: تهيئة...",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "قطع الاتصال بالمعاينة المباشرة",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "المعاينة المباشرة (حفظ الملف للتحديث)",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "حدد ملف للمعاينة الحية",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "إعادة تحميل الصفحة",
  "LIVE_DEV_CLICK_POPOUT": "معاينة Popout الحية إلى نافذة جديدة",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "تثبيت على صفحة معاينة إلغاء تثبيت",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "معاينة مباشرة (لا يتم تحديثها بسبب خطأ في بناء الجملة)",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "تم إلغاء Live Preview لأنه تم فتح أدوات مطور المتصفح",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "تم إلغاء المعاينة المباشرة بسبب إغلاق الصفحة في المتصفح",
  "LIVE_DEV_NAVIGATED_AWAY": "تم إلغاء المعاينة المباشرة لأن المتصفح انتقل إلى صفحة ليست جزءًا من المشروع الحالي.",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "تم إلغاء المعاينة المباشرة لسبب غير معروف ({0})",
  "SAVE_CLOSE_TITLE": "حفظ التغييرات",
  "SAVE_CLOSE_MESSAGE": "هل تريد حفظ التغييرات التي أجريتها في المستند <span class='dialog-filename'>{0}</span>؟",
  "SAVE_CLOSE_MULTI_MESSAGE": "هل تريد حفظ تغييراتك على الملفات التالية؟",
  "EXT_MODIFIED_TITLE": "التغييرات الخارجية",
  "CONFIRM_DELETE_TITLE": "تأكيد الحذف",
  "CONFIRM_FILE_DELETE": "هل تريد بالتأكيد حذف الملف <span class='dialog-filename'>{0}</span>؟",
  "CONFIRM_FOLDER_DELETE": "هل تريد بالتأكيد حذف المجلد <span class='dialog-filename'>{0}</span>؟",
  "FILE_DELETED_TITLE": "تم حذف الملف",
  "EXT_MODIFIED_WARNING": "تم تعديل <span class='dialog-filename'>{0}</span> على القرص خارج {APP_NAME}. <br /><br />هل تريد حفظ الملف والكتابة فوق هذه التغييرات؟",
  "EXT_MODIFIED_MESSAGE": "<span class='dialog-filename'>{0}</span> تم تعديل {0} على قرص خارج {APP_NAME}، ولكن يحتوي أيضًا على تغييرات غير محفوظة في {APP_NAME}. <br /><br />ما الإصدار الذي تريد الاحتفاظ به؟",
  "EXT_DELETED_MESSAGE": "تم حذف <span class='dialog-filename'>{0}</span> على القرص خارج {APP_NAME}، ولكن لديه تغييرات غير محفوظة في {APP_NAME}. <br /><br />هل تريد الاحتفاظ بتغييراتك؟",
  "WINDOW_UNLOAD_WARNING": "هل تريد بالتأكيد الانتقال إلى عنوان URL مختلف وترك Brackets؟",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "لديك تغييرات غير محفوظة! هل تريد بالتأكيد الانتقال إلى عنوان URL مختلف وترك Brackets؟",
  "DONE": "تم",
  "OK": "حسنا",
  "CANCEL": "إلغاء",
  "DONT_SAVE": "لا تحفظ",
  "SAVE": "حفظ",
  "SAVE_AS": "حفظ باسم...",
  "SAVE_AND_OVERWRITE": "الكتابة فوق",
  "DELETE": "حذف",
  "BUTTON_YES": "نعم",
  "BUTTON_NO": "لا",
  "FIND_MATCH_INDEX": "{0} من {1}",
  "FIND_NO_RESULTS": "لا توجد نتائج",
  "FIND_QUERY_PLACEHOLDER": "ابحث عن...",
  "FIND_HISTORY_MAX_COUNT": "الحد الأقصى لعدد عناصر البحث في سجل البحث",
  "REPLACE_PLACEHOLDER": "استبدل بـ...",
  "BUTTON_REPLACE_ALL": "استبدال الكل",
  "BUTTON_REPLACE_BATCH": "دفعة...",
  "BUTTON_REPLACE_ALL_IN_FILES": "استبدال...",
  "BUTTON_REPLACE": "استبدال",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "المباراة التالية",
  "BUTTON_PREV_HINT": "المباراة السابقة",
  "BUTTON_CASESENSITIVE_HINT": "حالة مطابقة",
  "BUTTON_REGEXP_HINT": "التعبير العادي",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "استبدال بدون تراجع",
  "REPLACE_WITHOUT_UNDO_WARNING": "نظرًا لأن هناك حاجة لتغيير أكثر من {0} ملفات، سيقوم {APP_NAME} بتعديل الملفات غير المفتوحة على القرص. <br />لن تتمكن من التراجع عن البدائل في هذه الملفات.",
  "BUTTON_REPLACE_WITHOUT_UNDO": "استبدال بدون تراجع",
  "OPEN_FILE": "افتح ملف",
  "SAVE_FILE_AS": "حفظ ملف",
  "CHOOSE_FOLDER": "اختر مجلدًا",
  "RELEASE_NOTES": "ملاحظات الإصدار",
  "NO_UPDATE_TITLE": "أنت حتى الآن!",
  "NO_UPDATE_MESSAGE": "أنت تقوم بتشغيل أحدث إصدار من {APP_NAME}.",
  "FIND_REPLACE_TITLE_LABEL": "استبدال",
  "FIND_REPLACE_TITLE_WITH": "مع",
  "FIND_TITLE_LABEL": "العثور على",
  "FIND_TITLE_SUMMARY": "— {0} {1} {2} في {3}",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "في <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_NO_SCOPE": "في المشروع",
  "FIND_IN_FILES_ZERO_FILES": "عامل التصفية يستبعد جميع الملفات {0}",
  "FIND_IN_FILES_FILE": "ملف",
  "FIND_IN_FILES_FILES": "ملفات",
  "FIND_IN_FILES_MATCH": "مباراة",
  "FIND_IN_FILES_MATCHES": "مباريات",
  "FIND_IN_FILES_MORE_THAN": "أكثر ",
  "FIND_IN_FILES_PAGING": "{0} - {1}",
  "FIND_IN_FILES_FILE_PATH": "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "كترل/كمد انقر لتوسيع/طي الكل",
  "FIND_IN_FILES_INDEXING": "يتم الآن فهرسة البحث الفوري...",
  "FIND_IN_FILES_INDEXING_PROGRESS": "يتم الآن فهرسة {0} لملفات {1} للبحث الفوري...",
  "REPLACE_IN_FILES_ERRORS_TITLE": "استبدال الأخطاء",
  "REPLACE_IN_FILES_ERRORS": "لم يتم تعديل الملفات التالية لأنها تغيرت بعد البحث أو تعذر كتابتها.",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "خطأ في الحصول على معلومات التحديث",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "حدثت مشكلة في الحصول على أحدث معلومات التحديث من الخادم. يرجى التأكد من أنك متصل بالإنترنت وحاول مرة أخرى.",
  "NEW_FILE_FILTER": "مجموعة استبعاد جديدة...",
  "CLEAR_FILE_FILTER": "لا تستبعد الملفات",
  "NO_FILE_FILTER": "لا توجد ملفات مستبعدة",
  "EXCLUDE_FILE_FILTER": "استبعاد {0}",
  "EDIT_FILE_FILTER": "تحرير...",
  "FILE_FILTER_DIALOG": "تحرير مجموعة الاستبعاد",
  "FILE_FILTER_INSTRUCTIONS": "استبعاد الملفات والمجلدات المطابقة لأي من السلاسل أو السلاسل الفرعية أو <a href='{0}' title='{0}'>أحرف البدل</a> التالية. أدخل كل سلسلة على سطر جديد.",
  "FILTER_NAME_PLACEHOLDER": "قم بتسمية مجموعة الاستبعاد هذه (اختياري)",
  "FILTER_NAME_REMAINING": "{0} الأحرف المتبقية",
  "FILE_FILTER_CLIPPED_SUFFIX": "و {0} المزيد",
  "FILTER_COUNTING_FILES": "يتم الآن عد الملفات...",
  "FILTER_FILE_COUNT": "يسمح {0} من {1} ملفات {2}",
  "FILTER_FILE_COUNT_ALL": "يسمح لجميع ملفات {0} {1}",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "لا يتوفر تحرير سريع لموضع المؤشر الحالي",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "تحرير CSS السريع: ضع المؤشر على اسم فئة واحدة",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "تحرير CSS السريع: سمة فئة غير مكتملة",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "تحرير CSS السريع: سمة معرف غير مكتملة",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "تحرير CSS السريع: ضع المؤشر في العلامة أو الفئة أو المعرف",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "تعديل سريع لوظيفة توقيت CSS: بناء جملة غير صالح",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "JS Quick Edit: ضع المؤشر في اسم الوظيفة",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "لا يتوفر مستندات سريعة لموضع المؤشر الحالي",
  "PROJECT_LOADING": "جاري التحميل...",
  "UNTITLED": "بدون عنوان",
  "WORKING_FILES": "ملفات العمل",
  "TOP": "توب",
  "BOTTOM": "بوتوم",
  "LEFT": "يسار",
  "RIGHT": "صحيح",
  "CMD_SPLITVIEW_NONE": "لا يوجد انقسام",
  "CMD_SPLITVIEW_VERTICAL": "انقسام عمودي",
  "CMD_SPLITVIEW_HORIZONTAL": "انقسام أفقي",
  "SPLITVIEW_MENU_TOOLTIP": "تقسيم المحرر رأسيًا أو أفقيًا",
  "GEAR_MENU_TOOLTIP": "تكوين مجموعة العمل",
  "SPLITVIEW_INFO_TITLE": "مفتوح بالفعل",
  "SPLITVIEW_MULTIPANE_WARNING": "الملف مفتوح بالفعل في جزء آخر. {APP_NAME} ستدعم قريبًا فتح نفس الملف في أكثر من جزء. حتى ذلك الحين، سيتم عرض الملف في الجزء المفتوح بالفعل فيه. <br /><br />(سترى هذه الرسالة مرة واحدة فقط.)",
  "STATUSBAR_CURSOR_POSITION": "السطر {0}، العمود {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": " - عمود محدد {0}",
  "STATUSBAR_SELECTION_CH_PLURAL": " - الأعمدة المحددة {0}",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " - خط محدد {0}",
  "STATUSBAR_SELECTION_LINE_PLURAL": " - خطوط محددة {0}",
  "STATUSBAR_SELECTION_MULTIPLE": " — {0} التحديدات",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "انقر لتبديل المسافة البادئة إلى مسافات",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "انقر لتبديل المسافة البادئة إلى علامات التبويب",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "انقر لتغيير عدد المسافات المستخدمة عند وضع مسافة بادئة",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "انقر لتغيير عرض حرف علامة التبويب",
  "STATUSBAR_SPACES": "المساحات:",
  "STATUSBAR_TAB_SIZE": "حجم علامة التبويب:",
  "STATUSBAR_LINE_COUNT_SINGULAR": "— {0} خط",
  "STATUSBAR_LINE_COUNT_PLURAL": "— {0} خطوط",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "تم تعطيل الإضافات",
  "STATUSBAR_INSERT": "الإضافية",
  "STATUSBAR_OVERWRITE": "على",
  "STATUSBAR_INSOVR_TOOLTIP": "انقر لتبديل المؤشر بين وضعي إدراج (INS) والكتابة فوق (OVR)",
  "STATUSBAR_LANG_TOOLTIP": "انقر لتغيير نوع الملف",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. انقر لتبديل لوحة التقرير.",
  "STATUSBAR_DEFAULT_LANG": "(افتراضي)",
  "STATUSBAR_SET_DEFAULT_LANG": "تعيين كافتراضي لملفات. {0}",
  "STATUSBAR_ENCODING_TOOLTIP": "حدد الترميز",
  "ERRORS_PANEL_TITLE_MULTIPLE": "{0} مشاكل",
  "SINGLE_ERROR": "1 {0} مشكلة",
  "MULTIPLE_ERRORS": "{1} {0} المشاكل",
  "NO_ERRORS": "لم يتم العثور على مشاكل {0} - عمل جيد!",
  "NO_ERRORS_MULTIPLE_PROVIDER": "لم يتم العثور على مشاكل - عمل جيد!",
  "LINT_DISABLED": "تم تعطيل Linting",
  "NO_LINT_AVAILABLE": "لا يوجد لينتر متاح لـ {0}",
  "NOTHING_TO_LINT": "لا شيء للوبر",
  "LINTER_TIMED_OUT": "انتهت مهلة {0} بعد انتظار {1} مللي ثانية",
  "LINTER_FAILED": "{0} تم إنهاؤها بالخطأ: {1}",
  "FILE_MENU": "ملف",
  "CMD_FILE_NEW_UNTITLED": "جديد",
  "CMD_FILE_NEW": "ملف جديد",
  "CMD_FILE_DUPLICATE": "نسخة مكررة",
  "CMD_FILE_CUT": "قص",
  "CMD_FILE_COPY": "نسخ",
  "CMD_FILE_COPY_PATH": "مسار النسخ",
  "CMD_FILE_PASTE": "لصق",
  "CMD_PROJECT_NEW": "مشروع جديد",
  "CMD_FILE_NEW_FOLDER": "مجلد جديد",
  "CMD_FILE_OPEN": "افتح...",
  "CMD_RECENT_FILES_OPEN": "الملفات الأخيرة...",
  "CMD_ADD_TO_WORKING_SET": "فتح لمجموعة العمل",
  "CMD_OPEN_DROPPED_FILES": "افتح الملفات المسقطة",
  "CMD_OPEN_FOLDER": "افتح المجلد...",
  "CMD_FILE_CLOSE": "إغلاق",
  "CMD_FILE_CLOSE_ALL": "إغلاق الكل",
  "CMD_FILE_CLOSE_LIST": "إغلاق القائمة",
  "CMD_FILE_CLOSE_OTHERS": "أغلق الآخرين",
  "CMD_FILE_CLOSE_ABOVE": "أغلق الآخرين أعلاه",
  "CMD_FILE_CLOSE_BELOW": "أغلق الآخرين أدناه",
  "CMD_FILE_SAVE": "حفظ",
  "CMD_FILE_SAVE_ALL": "حفظ الكل",
  "CMD_FILE_SAVE_AS": "حفظ باسم...",
  "CMD_LIVE_FILE_PREVIEW": "معاينة مباشرة",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "تمكين المعاينة المباشرة التجريبية",
  "CMD_RELOAD_LIVE_PREVIEW": "فرض إعادة تحميل المعاينة المباشرة",
  "CMD_PROJECT_SETTINGS": "إعدادات المشروع...",
  "CMD_FILE_RENAME": "إعادة تسمية",
  "CMD_FILE_DELETE": "حذف",
  "CMD_INSTALL_EXTENSION": "تثبيت ملحق...",
  "CMD_EXTENSION_MANAGER": "إدارة الإضافات...",
  "CMD_FILE_REFRESH": "تحديث شجرة الملفات",
  "CMD_FILE_SHOW_FOLDERS_FIRST": "فرز المجلدات أولاً",
  "CMD_QUIT": "قم بإنهاء",
  "CMD_EXIT": "إكسيت",
  "EDIT_MENU": "تحرير",
  "CMD_UNDO": "تراجع",
  "CMD_REDO": "ريدو",
  "CMD_CUT": "قص",
  "CMD_COPY": "نسخ",
  "CMD_PASTE": "لصق",
  "CMD_SELECT_ALL": "حدد الكل",
  "CMD_SELECT_LINE": "حدد الخط",
  "CMD_SPLIT_SEL_INTO_LINES": "تقسيم التحديد إلى خطوط",
  "CMD_ADD_CUR_TO_NEXT_LINE": "إضافة المؤشر إلى السطر التالي",
  "CMD_ADD_CUR_TO_PREV_LINE": "إضافة المؤشر إلى السطر السابق",
  "CMD_INDENT": "مسافة بادئة",
  "CMD_UNINDENT": "مسافة بادئة",
  "CMD_DUPLICATE": "نسخة مكررة",
  "CMD_DELETE_LINES": "حذف السطر",
  "CMD_COMMENT": "تعليق تبديل الخط",
  "CMD_BLOCK_COMMENT": "تبديل تعليق بلوك",
  "CMD_LINE_UP": "موف لاين اب",
  "CMD_LINE_DOWN": "نقل الخط لأسفل",
  "CMD_OPEN_LINE_ABOVE": "افتح الخط أعلاه",
  "CMD_OPEN_LINE_BELOW": "افتح الخط أدناه",
  "CMD_TOGGLE_CLOSE_BRACKETS": "أقواس الإغلاق التلقائي",
  "CMD_SHOW_CODE_HINTS": "إظهار تلميحات التعليمات البرمجية",
  "CMD_BEAUTIFY_CODE": "كود تجميل",
  "CMD_BEAUTIFY_CODE_ON_SAVE": "تجميل الكود بعد الحفظ",
  "FIND_MENU": "البحث",
  "CMD_FIND": "البحث",
  "CMD_FIND_NEXT": "البحث عن التالي",
  "CMD_FIND_PREVIOUS": "البحث عن السابق",
  "CMD_FIND_ALL_AND_SELECT": "ابحث عن الكل وحدد",
  "CMD_ADD_NEXT_MATCH": "إضافة المطابقة التالية إلى التحديد",
  "CMD_SKIP_CURRENT_MATCH": "تخطي وإضافة المطابقة التالية",
  "CMD_FIND_IN_FILES": "البحث في الملفات",
  "CMD_FIND_IN_SUBTREE": "ابحث في...",
  "CMD_REPLACE": "استبدال",
  "CMD_REPLACE_IN_FILES": "استبدال في الملفات",
  "CMD_REPLACE_IN_SUBTREE": "استبدال في...",
  "VIEW_MENU": "عرض",
  "CMD_HIDE_SIDEBAR": "إخفاء الشريط الجانبي",
  "CMD_SHOW_SIDEBAR": "إظهار الشريط الجانبي",
  "CMD_TOGGLE_SIDEBAR": "تبديل الشريط الجانبي",
  "CMD_TOGGLE_PANELS": "لوحات تبديل",
  "CMD_TOGGLE_PURE_CODE": "لا تشتيت",
  "CMD_INCREASE_FONT_SIZE": "زيادة حجم الخط",
  "CMD_DECREASE_FONT_SIZE": "تقليل حجم الخط",
  "CMD_RESTORE_FONT_SIZE": "استعادة حجم الخط",
  "CMD_SCROLL_LINE_UP": "انتقل إلى الخط لأعلى",
  "CMD_SCROLL_LINE_DOWN": "انتقل إلى الخط لأسفل",
  "CMD_TOGGLE_LINE_NUMBERS": "أرقام الأسطر",
  "CMD_TOGGLE_ACTIVE_LINE": "تسليط الضوء على الخط النشط",
  "CMD_TOGGLE_WORD_WRAP": "ورد راب",
  "CMD_LIVE_HIGHLIGHT": "تسليط الضوء على المعاينة المباشرة",
  "CMD_VIEW_TOGGLE_INSPECTION": "ملفات Lint على حفظ",
  "CMD_WORKINGSET_SORT_BY_ADDED": "فرز حسب المضافة",
  "CMD_WORKINGSET_SORT_BY_NAME": "فرز حسب الاسم",
  "CMD_WORKINGSET_SORT_BY_TYPE": "فرز حسب النوع",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "فرز تلقائي",
  "CMD_THEMES": "ثيمات...",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "إغلاق البحث تلقائيًا",
  "NAVIGATE_MENU": "التنقل",
  "CMD_QUICK_OPEN": "فتح سريع",
  "CMD_GOTO_LINE": "انتقل إلى الخط",
  "CMD_GOTO_DEFINITION": "تعريف البحث السريع",
  "CMD_GOTO_DEFINITION_PROJECT": "تعريف البحث السريع في المشروع",
  "CMD_GOTO_FIRST_PROBLEM": "انتقل إلى المشكلة الأولى",
  "CMD_TOGGLE_QUICK_EDIT": "تحرير سريع",
  "CMD_TOGGLE_QUICK_DOCS": "مستندات سريعة",
  "CMD_QUICK_EDIT_PREV_MATCH": "المباراة السابقة",
  "CMD_QUICK_EDIT_NEXT_MATCH": "المباراة التالية",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "قاعدة جديدة",
  "CMD_NEXT_DOC": "المستند التالي",
  "CMD_PREV_DOC": "المستند السابق",
  "CMD_NAVIGATE_BACKWARD": "التنقل للخلف",
  "CMD_NAVIGATE_FORWARD": "انتقل إلى الأمام",
  "CMD_NEXT_DOC_LIST_ORDER": "المستند التالي في القائمة",
  "CMD_PREV_DOC_LIST_ORDER": "المستند السابق في القائمة",
  "CMD_SHOW_IN_TREE": "إظهار في شجرة الملفات",
  "CMD_SHOW_IN_EXPLORER": "عرض في إكسبلورر",
  "CMD_SHOW_IN_FINDER": "عرض في Finder",
  "CMD_SHOW_IN_OS": "عرض في نظام التشغيل",
  "CMD_SWITCH_PANE_FOCUS": "تركيز جزء المحول",
  "CMD_OPEN_VFS": "افتح نظام الملفات الافتراضية",
  "CMD_OPEN_VIRTUAL_SERVER": "افتح الخادم الافتراضي",
  "HELP_MENU": "مساعدة",
  "CMD_CHECK_FOR_UPDATE": "تحقق من وجود تحديثات",
  "CMD_HOW_TO_USE_BRACKETS": "كيفية استخدام {APP_NAME}",
  "CMD_SUPPORT": "الدعم {APP_NAME}",
  "CMD_SUGGEST": "اقتراح ميزة",
  "CMD_RELEASE_NOTES": "ملاحظات الإصدار",
  "CMD_GET_INVOLVED": "احصل على المشاركة",
  "CMD_SHOW_EXTENSIONS_FOLDER": "عرض مجلد الإضافات",
  "CMD_HEALTH_DATA_STATISTICS": "تقرير الصحة",
  "CMD_HOMEPAGE": "الصفحة الرئيسية {APP_NAME}",
  "CMD_TWITTER": "{TWITTER_NAME} على تويتر",
  "CMD_ABOUT": "حول {APP_TITLE}",
  "CMD_OPEN_PREFERENCES": "افتح ملف التفضيلات",
  "CMD_OPEN_KEYMAP": "افتح خريطة مفتاح المستخدم",
  "EXPERIMENTAL_BUILD": "بناء تجريبي",
  "RELEASE_BUILD": "يبني",
  "DEVELOPMENT_BUILD": "بناء التطوير",
  "PRERELEASE_BUILD": "بناء ما قبل الإصدار",
  "RELOAD_FROM_DISK": "إعادة التحميل من القرص",
  "KEEP_CHANGES_IN_EDITOR": "الاحتفاظ بالتغييرات في المحرر",
  "CLOSE_DONT_SAVE": "إغلاق (لا تحفظ)",
  "RELAUNCH_CHROME": "إعادة تشغيل كروم",
  "ABOUT": "حول",
  "CLOSE": "إغلاق",
  "ABOUT_TEXT_LINE1": "الإصدار {فيرسيون_ماجور}. {VERSION_MINOR} {BUILD_TYPE} {الإصدار}",
  "ABOUT_TEXT_BUILD_TIMESTAMP": "طابع زمني للبناء: ",
  "ABOUT_TEXT_LINE3": "مكتبات الطرف الثالث التي نستخدمها - <a href='https://github.com/phcode-dev/phoenix/tree/main/src/thirdparty/licences'>التراخيص والسمات</a>. ",
  "ABOUT_TEXT_LINE4": "التوثيق والمصدر في <a href='https://github.com/phcode-dev/phoenix/'>https://github.com/phcode-dev/phoenix/</a>",
  "ABOUT_TEXT_LINE5": "مصنوع باستخدام ❤ وجافا سكريبت من خلال:",
  "ABOUT_TEXT_LINE6": "الكثير من الأشخاص (لكننا نواجه مشكلة في تحميل هذه البيانات الآن).",
  "ABOUT_TEXT_MDN_DOCS": "يتم ترخيص مستندات MDN والشعار الرسومي MDN بموجب ترخيص إسناد المشاع الإبداعي، <a href='{MDN_DOCS_LICENSE}'>CC-BY-SA 2.5 Unported</a>.",
  "UPDATE_NOTIFICATION_TOOLTIP": "تتوفر بنية جديدة من {APP_NAME}! انقر هنا للحصول على التفاصيل.",
  "UPDATE_AVAILABLE_TITLE": "التحديث متاح",
  "UPDATE_MESSAGE": "مهلا، هناك بناء جديد من {APP_NAME} متاح. فيما يلي بعض الميزات الجديدة:",
  "GET_IT_NOW": "احصل عليه الآن!",
  "PROJECT_SETTINGS_TITLE": "إعدادات المشروع لـ: {0}",
  "PROJECT_SETTING_BASE_URL": "عنوان URL لقاعدة المعاينة المباشرة",
  "PROJECT_SETTING_BASE_URL_HINT": "لاستخدام خادم محلي، أدخل عنوان URL مثل http://localhost:8000/",
  "BASEURL_ERROR_INVALID_PROTOCOL": "البروتوكول {0} غير مدعوم من قبل المعاينة المباشرة - يرجى استخدام http: أو https:.",
  "BASEURL_ERROR_SEARCH_DISALLOWED": "لا يمكن أن يحتوي عنوان URL الأساسي على معلمات بحث مثل «{0}».",
  "BASEURL_ERROR_HASH_DISALLOWED": "لا يمكن أن يحتوي عنوان URL الأساسي على تجزئات مثل «{0}».",
  "BASEURL_ERROR_INVALID_CHAR": "يجب أن تكون الأحرف الخاصة مثل '{0}' مشفرة بنسبة٪.",
  "BASEURL_ERROR_UNKNOWN_ERROR": "خطأ غير معروف في تحليل عنوان URL الأساسي",
  "EMPTY_VIEW_HEADER": "<em>افتح ملفًا أثناء تركيز هذا الجزء</em>",
  "FLIPVIEW_BTN_TOOLTIP": "اقلب طريقة العرض هذه إلى {0} جزء",
  "CURRENT_THEME": "الموضوع الحالي",
  "USE_THEME_SCROLLBARS": "استخدم أشرطة تمرير السمة",
  "FONT_SIZE": "حجم الخط",
  "FONT_FAMILY": "عائلة الخط",
  "THEMES_SETTINGS": "إعدادات السمات",
  "BUTTON_NEW_RULE": "قاعدة جديدة",
  "INSTALL": "تثبيت",
  "UPDATE": "تحديث",
  "REMOVE": "إزالة",
  "DISABLE": "تعطيل",
  "ENABLE": "تمكين",
  "OVERWRITE": "الكتابة فوق",
  "CANT_REMOVE_DEV": "يجب حذف الإضافات الموجودة في مجلد «dev» يدويًا.",
  "CANT_UPDATE": "التحديث غير متوافق مع هذا الإصدار من {APP_NAME}.",
  "CANT_UPDATE_DEV": "لا يمكن تحديث الإضافات الموجودة في مجلد «dev» تلقائيًا.",
  "INSTALL_EXTENSION_TITLE": "تثبيت ملحق",
  "UPDATE_EXTENSION_TITLE": "ملحق التحديث",
  "INSTALL_EXTENSION_LABEL": "عنوان URL الملحق",
  "INSTALL_EXTENSION_HINT": "عنوان URL للملف المضغوط للملحق أو الريبو GitHub",
  "INSTALLING_FROM": "يتم الآن تثبيت الإضافة من {0}...",
  "INSTALL_SUCCEEDED": "تم التثبيت بنجاح!",
  "INSTALL_FAILED": "فشل التثبيت.",
  "CANCELING_INSTALL": "جاري الإلغاء...",
  "CANCELING_HUNG": "يستغرق إلغاء التثبيت وقتًا طويلاً. ربما حدث خطأ داخلي.",
  "INSTALL_CANCELED": "تم إلغاء التثبيت.",
  "VIEW_COMPLETE_DESCRIPTION": "عرض الوصف الكامل",
  "VIEW_TRUNCATED_DESCRIPTION": "عرض الوصف المقتطع",
  "SORT_EXTENSION_METHOD": "فرز الإضافات باستخدام DownloadCount أو تاريخ النشر",
  "INVALID_ZIP_FILE": "المحتوى الذي تم تنزيله ليس ملف zip صالح.",
  "MISSING_PACKAGE_JSON": "لا تحتوي الحزمة على ملف package.json.",
  "INVALID_PACKAGE_JSON": "ملف package.json غير صالح (كان الخطأ: {0}).",
  "MISSING_PACKAGE_NAME": "لا يحدد ملف package.json اسم الحزمة.",
  "BAD_PACKAGE_NAME": "{0} اسم حزمة غير صالح.",
  "MISSING_PACKAGE_VERSION": "لا يحدد ملف package.json إصدار حزمة.",
  "INVALID_VERSION_NUMBER": "رقم إصدار الحزمة ({0}) غير صالح.",
  "INVALID_BRACKETS_VERSION": "سلسلة التوافق {APP_NAME} ({0}) غير صالحة.",
  "DISALLOWED_WORDS": "الكلمات ({1}) غير مسموح بها في الحقل {0}.",
  "NPM_INSTALL_FAILED": "فشل أمر تثبيت npm: {0}",
  "API_NOT_COMPATIBLE": "الإضافة غير متوافقة مع هذا الإصدار من {APP_NAME}. تم تثبيته في مجلد الإضافات المعطلة.",
  "MISSING_MAIN": "لا تحتوي الحزمة على ملف main.js.",
  "EXTENSION_ALREADY_INSTALLED": "سيؤدي تثبيت هذه الحزمة إلى استبدال ملحق مثبت مسبقًا. هل تريد الكتابة فوق الامتداد القديم؟",
  "EXTENSION_SAME_VERSION": "هذه الحزمة هي نفس الإصدار المثبت حاليًا. هل تريد الكتابة فوق التثبيت الحالي؟",
  "EXTENSION_OLDER_VERSION": "هذه الحزمة هي الإصدار {0} وهو أقدم من الإصدار المثبت حاليًا ({1}). هل تريد الكتابة فوق التثبيت الحالي؟",
  "DOWNLOAD_ID_IN_USE": "خطأ داخلي: معرف التنزيل قيد الاستخدام بالفعل.",
  "NO_SERVER_RESPONSE": "لا يمكن الاتصال بالخادم.",
  "BAD_HTTP_STATUS": "لم يتم العثور على الملف على الخادم (HTTP {0}).",
  "CANNOT_WRITE_TEMP": "غير قادر على حفظ التنزيل إلى ملف temp.",
  "ERROR_LOADING": "واجهت الإضافة خطأ أثناء بدء التشغيل.",
  "MALFORMED_URL": "عنوان URL غير صالح. يرجى التحقق من أنك أدخلته بشكل صحيح.",
  "UNSUPPORTED_PROTOCOL": "يجب أن يكون عنوان URL عنوان URL http أو https.",
  "UNKNOWN_ERROR": "خطأ داخلي غير معروف.",
  "EXTENSION_MANAGER_TITLE": "إدارة الإضافات",
  "EXTENSION_MANAGER_ERROR_LOAD": "غير قادر على الوصول إلى سجل الملحق. يرجى المحاولة مرة أخرى لاحقًا.",
  "INSTALL_EXTENSION_DRAG": "اسحب .zip هنا أو",
  "INSTALL_EXTENSION_DROP": "قم بإسقاط .zip للتثبيت",
  "INSTALL_EXTENSION_DROP_ERROR": "تم إحباط التثبيت/التحديث بسبب الأخطاء التالية:",
  "INSTALL_FROM_URL": "التثبيت من عنوان URL...",
  "INSTALL_EXTENSION_VALIDATING": "جاري التحقق...",
  "EXTENSION_AUTHOR": "المؤلف",
  "EXTENSION_DATE": "التاريخ",
  "EXTENSION_INCOMPATIBLE_NEWER": "يتطلب هذا الملحق إصدارًا أحدث من {APP_NAME}.",
  "EXTENSION_INCOMPATIBLE_OLDER": "تعمل هذه الإضافة حاليًا فقط مع الإصدارات القديمة من {APP_NAME}.",
  "EXTENSION_LATEST_INCOMPATIBLE_NEWER": "يتطلب الإصدار {0} من هذا الملحق إصدارًا أحدث من {APP_NAME}. ولكن يمكنك تثبيت الإصدار السابق {1}.",
  "EXTENSION_LATEST_INCOMPATIBLE_OLDER": "يعمل الإصدار {0} من هذا الملحق فقط مع الإصدارات القديمة من {APP_NAME}. ولكن يمكنك تثبيت الإصدار السابق {1}.",
  "EXTENSION_NO_DESCRIPTION": "لا يوجد وصف",
  "EXTENSION_MORE_INFO": "مزيد من المعلومات...",
  "EXTENSION_ERROR": "خطأ ملحق",
  "EXTENSION_KEYWORDS": "الكلمات الدالة",
  "EXTENSION_TRANSLATED_USER_LANG": "تمت ترجمته إلى {0} اللغات، بما في ذلك لغتك",
  "EXTENSION_TRANSLATED_GENERAL": "تمت ترجمته إلى {0} لغات",
  "EXTENSION_TRANSLATED_LANGS": "تمت ترجمة هذا الامتداد إلى هذه اللغات: {0}",
  "EXTENSION_INSTALLED": "تم تثبيت",
  "EXTENSION_UPDATE_INSTALLED": "تم تنزيل تحديث الملحق هذا وسيتم تثبيته بعد إعادة تحميل {APP_NAME}.",
  "EXTENSION_SEARCH_PLACEHOLDER": "بحث",
  "EXTENSION_MORE_INFO_LINK": "المزيد",
  "BROWSE_EXTENSIONS": "تصفح الإضافات",
  "EXTENSION_MANAGER_REMOVE": "إزالة الامتداد",
  "EXTENSION_MANAGER_REMOVE_ERROR": "غير قادر على إزالة ملحق واحد أو أكثر: {0}. {APP_NAME} ستظل إعادة التحميل.",
  "EXTENSION_MANAGER_UPDATE": "ملحق التحديث",
  "EXTENSION_MANAGER_UPDATE_ERROR": "غير قادر على تحديث ملحق واحد أو أكثر: {0}. {APP_NAME} ستظل إعادة التحميل.",
  "EXTENSION_MANAGER_DISABLE": "تعطيل الملحق",
  "EXTENSION_MANAGER_DISABLE_ERROR": "غير قادر على تعطيل ملحق واحد أو أكثر: {0}. {APP_NAME} ستظل إعادة التحميل.",
  "MARKED_FOR_REMOVAL": "تم وضع علامة للإزالة",
  "UNDO_REMOVE": "تراجع",
  "MARKED_FOR_UPDATE": "تم وضع علامة للتحديث",
  "UNDO_UPDATE": "تراجع",
  "MARKED_FOR_DISABLING": "تم وضع علامة لتعطيل",
  "UNDO_DISABLE": "تراجع",
  "CHANGE_AND_RELOAD_TITLE": "تغيير الإضافات",
  "CHANGE_AND_RELOAD_MESSAGE": "لتحديث الإضافات المميزة أو إزالتها أو تعطيلها، ستحتاج {APP_NAME} إلى إعادة التحميل. ستتم مطالبتك بحفظ التغييرات غير المحفوظة.",
  "REMOVE_AND_RELOAD": "إزالة الإضافات وإعادة التحميل",
  "CHANGE_AND_RELOAD": "تغيير الإضافات وإعادة التحميل",
  "UPDATE_AND_RELOAD": "تحديث الإضافات وإعادة التحميل",
  "DISABLE_AND_RELOAD": "تعطيل الإضافات وإعادة التحميل",
  "PROCESSING_EXTENSIONS": "يتم الآن معالجة تغييرات الملحق...",
  "EXTENSION_NOT_INSTALLED": "تعذر إزالة الامتداد {0} لأنه لم يتم تثبيته.",
  "NO_EXTENSIONS": "لا توجد ملحقات مثبتة حتى الآن. <br>انقر فوق علامة التبويب المتاحة أعلاه للبدء.",
  "NO_EXTENSION_MATCHES": "لا توجد إضافات تطابق بحثك.",
  "REGISTRY_SANITY_CHECK_WARNING": "ملاحظة: قد تأتي هذه الامتدادات من مؤلفين مختلفين عن {APP_NAME} نفسها. لا تتم مراجعة الإضافات ولديها امتيازات محلية كاملة. كن حذرًا عند تثبيت الإضافات من مصدر غير معروف.",
  "EXTENSIONS_INSTALLED_TITLE": "تم تثبيت",
  "EXTENSIONS_DEFAULT_TITLE": "افتراضي",
  "EXTENSIONS_AVAILABLE_TITLE": "متاح",
  "EXTENSIONS_THEMES_TITLE": "ثيمات",
  "EXTENSIONS_UPDATES_TITLE": "التحديثات",
  "EXTENSIONS_LAST_UPDATED": "آخر تحديث",
  "EXTENSIONS_DOWNLOADS": "التنزيلات",
  "INLINE_EDITOR_NO_MATCHES": "لا توجد مباريات متاحة.",
  "INLINE_EDITOR_HIDDEN_MATCHES": "يتم طي جميع المباريات. قم بتوسيع الملفات المدرجة على اليمين لعرض التطابقات.",
  "CSS_QUICK_EDIT_NO_MATCHES": "لا توجد قواعد CSS موجودة تطابق اختيارك. <br>انقر فوق «قاعدة جديدة» لإنشاء واحدة.",
  "CSS_QUICK_EDIT_NO_STYLESHEETS": "لا توجد أوراق أنماط في مشروعك. <br>قم بإنشاء واحدة لإضافة قواعد CSS.",
  "IMAGE_VIEWER_LARGEST_ICON": "أكبر",
  "UNIT_PIXELS": "بكسل",
  "DEBUG_MENU": "تصحيح",
  "ERRORS": "الأخطاء",
  "CMD_SHOW_DEV_TOOLS": "إظهار أدوات المطور",
  "CMD_REFRESH_WINDOW": "إعادة التحميل باستخدام الامتدادات",
  "CMD_RELOAD_WITHOUT_USER_EXTS": "إعادة التحميل بدون ملحقات",
  "CMD_NEW_BRACKETS_WINDOW": "نافذة جديدة {APP_NAME}",
  "CMD_LAUNCH_SCRIPT_MAC": "تثبيت اختصار سطر الأوامر",
  "CMD_SWITCH_LANGUAGE": "لغة التبديل",
  "CMD_RUN_UNIT_TESTS": "تشغيل الاختبارات",
  "CMD_SHOW_PERF_DATA": "عرض بيانات الأداء",
  "CMD_ENABLE_LOGGING": "تمكين السجلات التفصيلية",
  "CMD_OPEN_BRACKETS_SOURCE": "افتح مصدر {APP_NAME}",
  "CREATING_LAUNCH_SCRIPT_TITLE": "اختصار سطر الأوامر {APP_NAME}",
  "ERROR_CREATING_LAUNCH_SCRIPT": "حدث خطأ أثناء تثبيت اختصار سطر الأوامر. الرجاء تجربة <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting'>اقتراحات استكشاف الأخطاء وإصلاحها هذه</a>. <br/><br/>السبب: {0}",
  "ERROR_CLTOOLS_RMFAILED": "غير قادر على إزالة الارتباط <code>الرمزي الموجود /usr/local/bin/الأقواس</code>.",
  "ERROR_CLTOOLS_MKDIRFAILED": "غير قادر على إنشاء دليل <code>/usr/local/bin</code>.",
  "ERROR_CLTOOLS_LNFAILED": "غير قادر على إنشاء رابط <code>رمزي /usr/local/bin/بين قوسين</code>.",
  "ERROR_CLTOOLS_SERVFAILED": "خطأ داخلي.",
  "ERROR_CLTOOLS_NOTSUPPORTED": "اختصار سطر الأوامر غير معتمد على نظام التشغيل هذا.",
  "LAUNCH_SCRIPT_CREATE_SUCCESS": "النجاح! الآن يمكنك بسهولة تشغيل {APP_NAME} من سطر الأوامر: <code>الأقواس myFile.txt</code> لفتح ملف أو <code>أقواس MyFolder</code> لتبديل المشاريع. <br/><br/><a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments'>تعرف على المزيد</a> حول استخدام {APP_NAME} من سطر الأوامر.",
  "LANGUAGE_TITLE": "لغة التبديل",
  "LANGUAGE_MESSAGE": "اللغة:",
  "LANGUAGE_SUBMIT": "إعادة تحميل {APP_NAME}",
  "LANGUAGE_CANCEL": "إلغاء",
  "LANGUAGE_SYSTEM_DEFAULT": "افتراضي النظام",
  "HEALTH_DATA_NOTIFICATION": "تفضيلات التقرير الصحي",
  "HEALTH_FIRST_POPUP_TITLE": "تقرير الصحة {APP_NAME}",
  "HEALTH_DATA_DO_TRACK": "مشاركة معلومات باسم مستعار حول كيفية استخدام {APP_NAME}",
  "HEALTH_DATA_NOTIFICATION_MESSAGE": "من أجل تحسين {APP_NAME}، نرسل بشكل دوري إحصائيات محدودة <strong>بأسماء مستعارة</strong> إلى core.ai حول كيفية استخدامك {APP_NAME}. تساعد هذه المعلومات في تحديد أولويات الميزات والعثور على الأخطاء وتحديد مشكلات قابلية الاستخدام أثناء حماية خصوصيتك. <br><br>يمكنك الاطلاع على بياناتك أو اختيار عدم مشاركة البيانات عن طريق تحديد <strong>تعليمات > تقرير الصحة</strong>. <br><br>",
  "HEALTH_DATA_PREVIEW": "تقرير الصحة {APP_NAME}",
  "HEALTH_DATA_PREVIEW_INTRO": "<p>من أجل تحسين {APP_NAME}، نرسل بشكل دوري إحصائيات محدودة <strong>بأسماء مستعارة</strong> إلى core.ai حول كيفية استخدامك {APP_NAME}. تساعد هذه المعلومات في تحديد أولويات الميزات والعثور على الأخطاء وتحديد مشكلات قابلية الاستخدام. </p><p>فيما يلي معاينة للبيانات التي سيتم إرسالها في تقرير الصحة التالي <em>إذا</em> تم تمكينها. </p>",
  "INLINE_TIMING_EDITOR_TIME": "الوقت",
  "INLINE_TIMING_EDITOR_PROGRESSION": "التقدم",
  "BEZIER_EDITOR_INFO": "<kbd>↑</kbd> <kbd>↓</kbd> <kbd>← <kbd>←</kbd></kbd> نقل النقطة المحددة <br><kbd class='text'>Shift</kbd> نقل بمقدار عشر وحدات <br>نقاط تبديل <kbd class='text'>علامات التبويب</kbd>",
  "STEPS_EDITOR_INFO": "<kbd>↑</kbd> <kbd>↓</kbd> زيادة أو تقليل الخطوات <br><kbd>← <kbd>←</kbd></kbd> «ابدأ» أو «إنهاء»",
  "INLINE_TIMING_EDITOR_INVALID": "القيمة القديمة <code>{0}</code> غير صالحة، لذلك تم تغيير الدالة المعروضة إلى <code>{1}</code>. سيتم تحديث المستند مع التعديل الأول.",
  "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP": "اللون الحالي",
  "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP": "اللون الأصلي",
  "COLOR_EDITOR_RGBA_BUTTON_TIP": "تنسيق RGB",
  "COLOR_EDITOR_HEX_BUTTON_TIP": "تنسيق سداسي",
  "COLOR_EDITOR_HSLA_BUTTON_TIP": "تنسيق شلا",
  "COLOR_EDITOR_0X_BUTTON_TIP": "تنسيق سداسي (0x)",
  "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR": "{0} (تستخدم {1} مرة)",
  "COLOR_EDITOR_USED_COLOR_TIP_PLURAL": "{0} (تستخدم {1} مرات)",
  "CMD_JUMPTO_DEFINITION": "الانتقال إلى التعريف",
  "CMD_SHOW_PARAMETER_HINT": "إظهار تلميح المعلمة",
  "NO_ARGUMENTS": "<no parameters>",
  "DETECTED_EXCLUSION_TITLE": "مشكلة استدلال ملف جافا سكريبت",
  "DETECTED_EXCLUSION_INFO": "واجهت {APP_NAME} مشكلة في معالجة <span class='dialog-filename'>{0}</span>. <br><br>لن تتم معالجة هذا الملف بعد الآن لتلميحات التعليمات البرمجية أو الانتقال إلى التعريف أو التحرير السريع. لإعادة تمكين هذا الملف، <code>افتح.brackets.json</code> في مشروعك وقم بتحرير <code>JSCODEHints.detectedExclusions</code>. <br><br>من المحتمل أن يكون هذا خطأ {APP_NAME}. إذا كان بإمكانك تقديم نسخة من هذا الملف، فيرجى <a href='https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue'>تقديم خطأ</a> برابط إلى الملف المسمى هنا.",
  "CMD_REFACTOR": "ريفاكتور",
  "CMD_EXTRACTTO_VARIABLE": "استخراج إلى متغير",
  "CMD_EXTRACTTO_FUNCTION": "استخراج إلى وظيفة",
  "ERROR_TERN_FAILED": "غير قادر على الحصول على البيانات من Tern",
  "ERROR_EXTRACTTO_VARIABLE_NOT_VALID": "لا يشكل التحديد تعبيرًا",
  "ERROR_EXTRACTTO_FUNCTION_NOT_VALID": "يجب أن تمثل الكتلة المحددة مجموعة من العبارات أو التعبير",
  "ERROR_EXTRACTTO_VARIABLE_MULTICURSORS": "استخراج إلى متغير لا يعمل في multicursors",
  "ERROR_EXTRACTTO_FUNCTION_MULTICURSORS": "استخراج إلى وظيفة لا يعمل في multicursors",
  "EXTRACTTO_FUNCTION_SELECT_SCOPE": "اختر نطاق الوجهة",
  "EXTRACTTO_VARIABLE_SELECT_EXPRESSION": "حدد تعبيرًا",
  "CMD_REFACTORING_RENAME": "إعادة تسمية",
  "CMD_REFACTORING_TRY_CATCH": "التفاف في محاولة الصيد",
  "CMD_REFACTORING_CONDITION": "التفاف في حالة",
  "CMD_REFACTORING_GETTERS_SETTERS": "إنشاء جيترز/سيترز",
  "CMD_REFACTORING_ARROW_FUNCTION": "تحويل إلى وظيفة السهم",
  "DESCRIPTION_CODE_REFACTORING": "تمكين/تعطيل إعادة بيع كود جافا سكريبت",
  "ERROR_TRY_CATCH": "حدد رمزًا صالحًا للالتفاف في كتلة Try-catch",
  "ERROR_WRAP_IN_CONDITION": "حدد رمزًا صالحًا للالتفاف في كتلة الشرط",
  "ERROR_ARROW_FUNCTION": "ضع المؤشر داخل تعبير دالة",
  "ERROR_GETTERS_SETTERS": "ضع المؤشر على عضو تعبير كائن",
  "ERROR_RENAME_MULTICURSOR": "لا يمكن إعادة التسمية عند استخدام مؤشرات متعددة",
  "ERROR_RENAME_QUICKEDIT": "لا يمكن إعادة تسمية هذا المعرف، كما هو مشار إليه في مكان آخر خارج هذه الوظيفة",
  "ERROR_RENAME_GENERAL": "لا يمكن إعادة تسمية النص المحدد",
  "JSHINT_NAME": "جيه شينت",
  "CMD_ENABLE_QUICK_VIEW": "عرض سريع على التحويم",
  "CMD_ENABLE_SELECTION_VIEW": "طريقة عرض التحديد",
  "CMD_TOGGLE_RECENT_PROJECTS": "المشاريع الأخيرة",
  "DOCS_MORE_LINK": "اقرأ المزيد",
  "COLLAPSE_ALL": "طي الكل",
  "EXPAND_ALL": "توسيع الكل",
  "COLLAPSE_CURRENT": "طي التيار",
  "EXPAND_CURRENT": "قم بتوسيع التيار",
  "RECENT_FILES_DLG_HEADER": "الملفات الأخيرة",
  "RECENT_FILES_DLG_CLEAR_BUTTON_LABEL": "مسح",
  "RECENT_FILES_DLG_CLEAR_BUTTON_TITLE": "مسح الملفات غير الموجودة في مجموعة العمل",
  "DESCRIPTION_CLOSE_BRACKETS": "true لإغلاق الأقواس والأقواس والأقواس تلقائيًا",
  "DESCRIPTION_CLOSE_OTHERS_ABOVE": "false لإزالة «إغلاق الآخرين أعلاه» من قائمة سياق ملفات العمل",
  "DESCRIPTION_CLOSE_OTHERS_BELOW": "false لإزالة «إغلاق الآخرين أدناه» من قائمة سياق ملفات العمل",
  "DESCRIPTION_CLOSE_OTHERS": "false لإزالة «إغلاق الآخرين» من قائمة سياق ملفات العمل",
  "DESCRIPTION_CLOSE_TAGS": "تعيين خيارات إغلاق العلامة",
  "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS": "مجموعة من العلامات التي لا يجب إغلاقها تلقائيًا",
  "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING": "إغلاق عند كتابة > علامة الفتح",
  "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING": "إغلاق عند كتابة علامة الإغلاق",
  "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS": "مجموعة من العلامات التي عند فتحها تحتوي على سطر فارغ",
  "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD": "true لإنشاء علامات قسم قابلة للطي دائمًا عندما يتغير مستوى المسافة البادئة",
  "DESCRIPTION_CODE_FOLDING_ENABLED": "true لتمكين طي التعليمات البرمجية",
  "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER": "true لجعل علامات انهيار القسم مرئية فقط عند تحريك الماوس فوق الحضيض",
  "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL": "يحد من عدد المستويات العميقة ينطبق انهيار الكل",
  "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE": "الحد الأدنى من الخطوط قبل ظهور رمز قسم قابل للطي",
  "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES": "true لتذكر المقاطع المنهارة إذا قمت بإغلاق وإعادة فتح ملف أو مشروع",
  "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE": "true لتمكين طي التعليمات البرمجية على النص المحدد في المحرر",
  "DESCRIPTION_DISABLED_DEFAULT_EXTENSIONS": "الإضافات الافتراضية التي تم تعطيلها",
  "DESCRIPTION_ATTR_HINTS": "تمكين/تعطيل تلميحات سمة HTML",
  "DESCRIPTION_CSS_PROP_HINTS": "تمكين/تعطيل تلميحات خاصية CSS/LESS/SCSS",
  "DESCRIPTION_JS_HINTS": "تمكين/تعطيل تلميحات شفرة جافا سكريبت",
  "DESCRIPTION_JS_HINTS_TYPE_DETAILS": "تمكين/تعطيل تفاصيل نوع البيانات في تلميحات شفرة جافا سكريبت",
  "DESCRIPTION_PREF_HINTS": "تمكين/تعطيل تلميحات رمز التفضيلات",
  "DESCRIPTION_SPECIAL_CHAR_HINTS": "تمكين/تعطيل تلميحات كيان HTML",
  "DESCRIPTION_SVG_HINTS": "تمكين/تعطيل تلميحات رمز SVG",
  "DESCRIPTION_HTML_TAG_HINTS": "تمكين/تعطيل تلميحات علامات HTML",
  "DESCRIPTION_URL_CODE_HINTS": "تمكين/تعطيل تلميحات URL في HTML & CSS/LESS/SCSS",
  "DESCRIPTION_DRAG_DROP_TEXT": "تمكين/تعطيل وظيفة السحب والإفلات",
  "DESCRIPTION_HEALTH_DATA_TRACKING": "تمكين تتبع البيانات الصحية",
  "DESCRIPTION_HIGHLIGHT_MATCHES": "تمكين التمييز التلقائي للسلاسل المطابقة في جميع أنحاء المستند",
  "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN": "قم بتمييز جميع السلاسل التي تطابق الرمز المميز الذي يوجد به المؤشر حاليًا (لا حاجة إلى تحديد)",
  "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY": "قم بتمييز فقط عندما يكون التحديد رمزًا مميزًا كاملاً",
  "DESCRIPTION_INSERT_HINT_ON_TAB": "true لإدراج تلميح التعليمات البرمجية المحدد حاليًا في علامة التبويب",
  "DESCRIPTION_NO_HINTS_ON_DOT": "true لعدم إظهار تلميحات رمز JS تلقائيًا عندما.",
  "DESCRIPTION_JSHINT_OPTIONS": "كائن يحتوي على الخيارات الافتراضية لـ JSHint. يرجى الاطلاع على عنوان URL التالي لجميع خيارات JSHint المتاحة: https://jshint.com/docs/options/",
  "DESCRIPTION_LANGUAGE": "إعدادات اللغة الخاصة",
  "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS": "تعيينات إضافية من امتداد الملف إلى اسم اللغة",
  "DESCRIPTION_LANGUAGE_FILE_NAMES": "تعيينات إضافية من اسم الملف إلى اسم اللغة",
  "DESCRIPTION_LINEWISE_COPY_CUT": "القيام بالنسخ والقطع عندما لا يكون هناك تحديد سيؤدي إلى نسخ أو قطع الخطوط الكاملة التي تحتوي على مؤشرات فيها.",
  "DESCRIPTION_INPUT_STYLE": "يحدد الطريقة التي يتعامل بها CodeMirror مع الإدخال والتركيز. يمكن أن يكون textarea، وهو الافتراضي، أو contenteditable وهو أفضل لقارئات الشاشة (غير مستقر)",
  "DESCRIPTION_LINTING_ENABLED": "true لتمكين فحص الكود",
  "DESCRIPTION_ASYNC_TIMEOUT": "الوقت بالمللي ثانية بعد انتهاء مهلة linters غير المتزامنة",
  "DESCRIPTION_LINTING_PREFER": "صفيف من linters لتشغيل أولاً",
  "DESCRIPTION_LIVE_DEV_MULTIBROWSER": "true لتمكين المعاينة المباشرة التجريبية",
  "DESCRIPTION_USE_PREFERED_ONLY": "true لتشغيل الموفرين المحددين في linting.prefer فقط",
  "DESCRIPTION_MAX_CODE_HINTS": "يتم عرض تلميحات التعليمات البرمجية القصوى مرة واحدة",
  "DESCRIPTION_PATH": "إعدادات المسار المحددة",
  "DESCRIPTION_PROXY": "عنوان URL للخادم الوكيل المستخدم لتثبيت الملحق",
  "DESCRIPTION_SCROLL_PAST_END": "true لتمكين التمرير بعد نهاية المستند",
  "DESCRIPTION_SHOW_CODE_HINTS": "false لتعطيل جميع تلميحات التعليمات البرمجية",
  "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING": "يحافظ على المؤشر الوامض مرئيًا عندما يكون لديك تحديد نص",
  "DESCRIPTION_SHOW_LINE_NUMBERS": "true لإظهار أرقام الأسطر في «مزراب» على يسار التعليمات البرمجية",
  "DESCRIPTION_SMART_INDENT": "وضع مسافة بادئة تلقائيًا عند إنشاء كتلة جديدة",
  "DESCRIPTION_SOFT_TABS": "false لإيقاف سلوك علامات التبويب الناعمة",
  "DESCRIPTION_SORT_DIRECTORIES_FIRST": "true لفرز الدلائل أولاً في شجرة المشروع",
  "DESCRIPTION_SPACE_UNITS": "عدد المساحات التي يجب استخدامها للمسافات البادئة الفضائية",
  "DESCRIPTION_STATIC_SERVER_PORT": "رقم المنفذ الذي يجب أن يستخدمه الخادم المدمج للمعاينة المباشرة",
  "DESCRIPTION_STYLE_ACTIVE_LINE": "true لتسليط الضوء على لون خلفية الخط الذي يوجد عليه المؤشر",
  "DESCRIPTION_TAB_SIZE": "عدد المسافات التي سيتم عرضها لعلامات التبويب",
  "DESCRIPTION_USE_TAB_CHAR": "true لاستخدام علامات التبويب بدلاً من المسافات",
  "DESCRIPTION_UPPERCASE_COLORS": "true لتوليد ألوان سداسية كبيرة في محرر الألوان المضمنة",
  "DESCRIPTION_WORD_WRAP": "التفاف الأسطر التي تتجاوز عرض إطار العرض",
  "DESCRIPTION_SEARCH_AUTOHIDE": "أغلق البحث بمجرد تركيز المحرر",
  "DESCRIPTION_DETECTED_EXCLUSIONS": "قائمة بالملفات التي تم اكتشافها لتتسبب في نفاد Tern عن السيطرة",
  "DESCRIPTION_INFERENCE_TIMEOUT": "مقدار الوقت الذي ستستغرقه Tern عند محاولة فهم الملفات",
  "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR": "true لإظهار الأخطاء في شريط الحالة",
  "DESCRIPTION_QUICK_VIEW_ENABLED": "true لتمكين العرض السريع",
  "DESCRIPTION_SELECTION_VIEW_ENABLED": "true لتمكين طريقة عرض التحديد",
  "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW": "true لإظهار معاينات الصور لعناوين URL المفقودة",
  "DESCRIPTION_THEME": "حدد سمة {APP_NAME}",
  "DESCRIPTION_USE_THEME_SCROLLBARS": "true للسماح بأشرطة التمرير المخصصة",
  "DESCRIPTION_LINTING_COLLAPSED": "صحيح أن تنهار لوحة linting",
  "DESCRIPTION_FONT_FAMILY": "تغيير عائلة الخط",
  "DESCRIPTION_FONT_SIZE": "تغيير حجم الخط؛ على سبيل المثال 13px",
  "DESCRIPTION_FIND_IN_FILES_NODE": "true لتمكين البحث المستند إلى العقدة",
  "DESCRIPTION_FIND_IN_FILES_INSTANT": "true لتمكين البحث الفوري",
  "DESCRIPTION_FONT_SMOOTHING": "ماك فقط: «subpixel-antialiased» لتمكين antialiasing بكسل الفرعية أو «antialiased» من أجل antialiasing المقياس الرمادي",
  "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW": "false لتعطيل فتح ملف التفضيلات في طريقة العرض المنقسمة",
  "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE": "false لفتح ملف تفضيلات المستخدم في الجزء الأيسر/العلوي",
  "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED": "true لطي الأجزاء بعد إغلاق الملف الأخير من الجزء عبر زر إغلاق رأس الجزء",
  "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS": "قم بالتبديل عند إظهار زري الإغلاق والعرض المقلوب على الرأس.",
  "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT": "/*\n * هذا ملف للقراءة فقط مع التفضيلات المدعومة\n * بواسطة {APP_NAME}.\n * استخدم هذا الملف كمرجع لتعديل تفضيلاتك\n * فتح ملف «brackets.json» في الجزء الآخر.\n * لمزيد من المعلومات حول كيفية استخدام التفضيلات في الداخل\n * {APP_NAME}، ارجع إلى صفحة الويب على https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences\n */",
  "DEFAULT_PREFERENCES_JSON_DEFAULT": "افتراضي",
  "DESCRIPTION_PURE_CODING_SURFACE": "true لتمكين وضع التعليمات البرمجية فقط وإخفاء جميع عناصر واجهة المستخدم الأخرى في {APP_NAME}",
  "DESCRIPTION_INDENT_LINE_COMMENT": "true لتمكين المسافة البادئة للتعليقات الخطية",
  "DESCRIPTION_RECENT_FILES_NAV": "تمكين/تعطيل التنقل في الملفات الحديثة",
  "DESCRIPTION_LIVEDEV_WEBSOCKET_PORT": "المنفذ الذي يعمل عليه خادم WebSocket للمعاينة المباشرة",
  "DESCRIPTION_LIVE_DEV_HIGHLIGHT_SETTINGS": "إعدادات تمييز المعاينة المباشرة",
  "DESCRIPTION_LIVEDEV_ENABLE_REVERSE_INSPECT": "false لتعطيل المعاينة المباشرة الفحص العكسي",
  "DOWNLOAD_FAILED": "فشل التنزيل.",
  "DOWNLOAD_COMPLETE": "اكتمل التنزيل!",
  "UPDATE_SUCCESSFUL": "تم التحديث بنجاح!",
  "UPDATE_FAILED": "فشل التحديث!",
  "VALIDATION_FAILED": "فشل التحقق من الصحة!",
  "INITIALISATION_FAILED": "فشلت التهيئة!",
  "CLEANUP_FAILED": "فشلت عملية التنظيف!",
  "WARNING_TYPE": "تحذير!",
  "CLICK_RESTART_TO_UPDATE": "انقر فوق إعادة تشغيل لتحديث الأقواس.",
  "UPDATE_ON_NEXT_LAUNCH": "سيتم تطبيق التحديث عند إعادة التشغيل.",
  "GO_TO_SITE": "انتقل إلى <a href = \"http://brackets.io/ «> brackets.io</a> لإعادة المحاولة.",
  "INTERNET_UNAVAILABLE": "لا يوجد اتصال بالإنترنت متاح.",
  "UPDATEDIR_READ_FAILED": "تعذر قراءة دليل التحديث.",
  "UPDATEDIR_CLEAN_FAILED": "تعذر تنظيف دليل التحديث.",
  "INITIAL_DOWNLOAD": "يتم الآن تنزيل التحديث...",
  "RETRY_DOWNLOAD": "فشل التنزيل. إعادة المحاولة... محاولة ",
  "VALIDATING_INSTALLER": "اكتمل التنزيل! جاري التحقق من المثبت...",
  "CHECKSUM_DID_NOT_MATCH": "المجموع الاختباري لم يتطابق.",
  "INSTALLER_NOT_FOUND": "لم يتم العثور على المثبت.",
  "DOWNLOAD_ERROR": "حدث خطأ أثناء التنزيل.",
  "NETWORK_SLOW_OR_DISCONNECTED": "الشبكة غير متصلة أو بطيئة للغاية.",
  "RESTART_BUTTON": "إعادة التشغيل",
  "LATER_BUTTON": "لاحقًا",
  "DESCRIPTION_AUTO_UPDATE": "تمكين/تعطيل التحديث التلقائي بين قوسين",
  "AUTOUPDATE_ERROR": "خطأ!",
  "AUTOUPDATE_IN_PROGRESS": "تحديث قيد التقدم بالفعل.",
  "NUMBER_WITH_PERCENTAGE": "{0}%",
  "CMD_FIND_RELATED_FILES": "البحث عن الملفات ذات الصلة",
  "PHP_VERSION_INVALID": "خطأ في تحليل إصدار PHP. يرجى التحقق من إخراج الأمر «php —version».",
  "PHP_UNSUPPORTED_VERSION": "قم بتثبيت وقت تشغيل PHP7 لتمكين الأدوات المتعلقة بـ PHP مثل تلميحات التعليمات البرمجية وتلميحات المعلمات والانتقال إلى التعريف والمزيد. تم العثور على الإصدار: {0}",
  "PHP_EXECUTABLE_NOT_FOUND": "وقت تشغيل PHP غير موجود. قم بتثبيت وقت تشغيل PHP7 وتحديث «ExecutablePath» في تفضيلات PHP بشكل مناسب. يتيح ذلك الأدوات المتعلقة بـ PHP مثل تلميحات التعليمات البرمجية وتلميحات المعلمات والانتقال إلى التعريف والمزيد.",
  "PHP_PROCESS_SPAWN_ERROR": "تمت مصادفة رمز الخطأ {0} أثناء بدء عملية PHP.",
  "PHP_SERVER_ERROR_TITLE": "خطأ",
  "PHP_SERVER_MEMORY_LIMIT_INVALID": "حد الذاكرة الذي قدمته غير صالح. راجع تفضيلات PHP لتعيين القيمة الصحيحة.",
  "DESCRIPTION_PHP_TOOLING_CONFIGURATION": "إعدادات التكوين الافتراضية لأدوات PHP",
  "OPEN_PREFERENNCES": "افتح التفضيلات",
  "LANGUAGE_TOOLS_PREFERENCES": "تفضيلات أدوات اللغة",
  "FIND_ALL_REFERENCES": "البحث عن جميع المراجع",
  "REFERENCES_IN_FILES": "المراجع",
  "REFERENCE_IN_FILES": "مرجع",
  "REFERENCES_NO_RESULTS": "لا توجد مراجع متاحة لموضع المؤشر الحالي",
  "CMD_FIND_DOCUMENT_SYMBOLS": "البحث عن رموز المستندات",
  "CMD_FIND_PROJECT_SYMBOLS": "ابحث عن رموز المشروع",
  "REMOTE_DEBUGGING_ENABLED": "تم تمكين التصحيح عن بعد على localhost:",
  "REMOTE_DEBUGGING_PORT_INVALID": "لا يمكن تمكين تصحيح الأخطاء عن بُعد على المنفذ {0}. يجب أن تكون أرقام المنافذ بين {1} و {2}.",
  "DESCRIPTION_EXTERNAL_APPLICATION_ASSOCIATE": "تعيينات ملحق الملف إلى التطبيقات الخارجية. بناء الجملة: \"<file_type>«: «<Default|ApplicationName|ApplicationPath>», استخدم «default» لفتح الملفات في تطبيق النظام الافتراضي لنوع الملف.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_TITLE": "افتح ملفات الرسومات في المحررين الخارجيين.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_MSG": "يحتوي المجلد الحالي على أنواع ملفات رسومية غير معتمدة من قبل {APP_NAME}. <br/>يمكنك الآن ربط أنواع ملفات معينة بالمحررين الخارجيين. بمجرد اقترانها، يمكنك فتح ملفات الرسومات مثل .xd، .psd، .jpg، .png، .ai، .svg في تطبيقاتها الافتراضية عن طريق النقر المزدوج على الملفات في شجرة الملفات. <br/><br/>الرجاء النقر فوق الزر «موافق» لربط أنواع ملفات الرسومات بالتطبيقات الافتراضية الخاصة بها.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_CNF_MSG": "تم إقران أنواع الملفات التالية بنجاح مع التطبيقات الافتراضية. <br/>{0} لديك خيار تغيير تفضيلاتك حول ما إذا كنت تقوم بحذف/إضافة ارتباطات نوع ملف جديد في brackets.json بالانتقال إلى قائمة «تصحيح-> فتح ملف التفضيلات».",
  "UNSUPPORTED_BROWSER": "المستعرض غير مدعوم",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER": "المتصفح لا يدعم المجلد المفتوح",
  "UNSUPPORTED_BROWSER_MESSAGE_LINE1": "الرجاء استخدام أحد المتصفحات المدعومة أدناه.",
  "UNSUPPORTED_BROWSER_MESSAGE_LINE2": " نحن نعمل بجد لجعل Phoenix متاحًا في المزيد من المتصفحات. يمكنك إغلاق هذا الحوار، ولكن بعض الميزات في Phoenix لن تعمل في هذا المتصفح.",
  "CANNOT_PUBLISH_LARGE_PROJECT": "لا يمكن نشر مشروع كبير",
  "CANNOT_PUBLISH_LARGE_PROJECT_MESSAGE": "فينيكس لا يزال في ألفا التجريبية. لم نقم بعد بتمكين مزامنة المشاريع التي تحتوي على أكثر من 500 ملف.",
  "SHARE_WEBSITE": "نشر ومشاركة موقع الويب؟",
  "PUBLISH": "نشر",
  "PUBLISH_CONSENT_MESSAGE": "معاينة التغييرات بسرعة ومشاركة موقع الويب الخاص بك مع الآخرين. يمكن لـ Phoenix نشر هذا الموقع لك على {0}. ستكون الروابط المنشورة صالحة لمدة 7 أيام. </br>هل ترغب في نشر ومشاركة موقع الويب الخاص بك؟",
  "PUBLISH_SYNC_IN_PROGRESS": "المزامنة قيد التقدم للمعاينة...",
  "PUBLISH_PAGE": "انقر لنشر ومشاركة هذا الموقع",
  "PUBLISH_VIEW_PAGE": "انقر لعرض الصفحة المنشورة",
  "MISSING_FIELDS": "حقول مفقودة",
  "PLEASE_FILL_ALL_REQUIRED": "يرجى ملء جميع الحقول المطلوبة المميزة باللون الأحمر",
  "CODE_EDITOR": "محرر التعليمات البرمجية",
  "BUILD_THE_WEB": "إنشاء الويب",
  "IMPORT_PROJECT": "مشروع استيراد",
  "GITHUB_PROJECT": "جيثب",
  "NEW_PROJECT_FROM_GITHUB": "مشروع جديد من Github",
  "GITHUB_REPO_URL": "رابط جيثب ريبو:",
  "CREATE_PROJECT": "إنشاء مشروع",
  "SETTING_UP_PROJECT": "إعداد المشروع",
  "LOCATION": "الموقع:",
  "DOWNLOADING": "جاري التنزيل...",
  "EXTRACTING_FILES_PROGRESS": "استخراج {0} من ملفات {1}.",
  "DOWNLOAD_FAILED_MESSAGE": "تأكد من أن عنوان URL للتنزيل صالح. </br>ملحوظة: نظرًا لأن Phoenix في alpha، لا يُسمح بعناوين URL الخاصة لـ Repos و Github التي يزيد حجمها عن 25 ميغابايت.",
  "PLEASE_SELECT_A_FOLDER": "الرجاء تحديد مجلد...",
  "UNZIP_IN_PROGRESS": "فك ضغط الملفات...",
  "UNZIP_FAILED": "خطأ: فشل فك الضغط.",
  "CONFIRM_REPLACE_TITLE": "تأكيد الاستبدال",
  "KEEP_BOTH": "حافظ على كليهما",
  "EXPLORE": "ألعاب HTML",
  "BLOG": "مدونة",
  "PHOENIX_DEFAULT_PROJECT": "المشروع الافتراضي",
  "PROJECT_NAME": "اسم المشروع:",
  "NEW_HTML": "مشروع HTML جديد",
  "LICENSE": "الترخيص:",
  "CREDITS": "قروض:",
  "PREVIEW": "استطلاع",
  "BUILD_WEBSITE": "إنشاء موقع",
  "VIEW_MORE": "عرض المزيد...",
  "NEW_PROJECT_NOTIFICATION": "انقر فوق هذا الرمز<br/> لإنشاء مشروع جديد. </br><a href='#' style='float:right;'>موافق</a>",
  "DEFAULT_PROJECT_NOTIFICATION": "انقر هنا لفتح <b>المشروع<br/> الافتراضي</b> في طائر الفينيق. </br><a href='#' style='float:right;'>موافق</a>",
  "DIRECTORY_REPLACE_MESSAGE": "المجلد المحدد <span class='dialog-filename'>{0}</span> ليس فارغًا. هل تريد بالتأكيد استبدال محتويات المجلد بالمشروع؟",
  "BUILD_WEBSITE_SECTION": "إنشاء موقع",
  "LEARN_SECTION": "تعلم مع أمثلة",
  "WEBPAGE_HOME_PAGE": "تخطيطات الصفحة الرئيسية",
  "WEBPAGE_BLOG": "صفحة المدونة",
  "WEBPAGE_DASHBOARD": "لوحة تحكم HTML",
  "WEBPAGE_BOOTSTRAP_EXAMPLES": "أمثلة على التمهيد",
  "GUIDED_FILES_SIDEBAR": "حدد ملف HTML</br> <a href='#' style='float:right;'>موافق</a>",
  "GUIDED_LIVE_PREVIEW": "قم بإجراء بعض التغييرات في التعليمات البرمجية وحفظ الملف لمشاهدة المعاينة. </br><a href='#' style='float:right;'>موافق</a>",
  "GUIDED_LIVE_PREVIEW_POPOUT": "انقر فوق هذا الزر لبدء المعاينة المباشرة لعلامة تبويب جديدة. </br><a href='#' style='float:right;'>موافق</a>",
  "TEST_TRANSLATE": "استخدم هذا لاختبار الترجمات",
  "BEAUTIFY_ERROR": "لا يمكن تجميل الكود. تحقق من بناء الجملة.",
  "BEAUTIFY_ERROR_ORIGINAL_CHANGED": "لا يمكن تجميلها. تم تغيير نص المحرر بعد التجميل.",
  "BEAUTIFY_PROJECT_BUSY_MESSAGE": "ملف تجميل {0}",
  "BEAUTIFY_ERROR_SELECTION": "لا يمكن تجميلها. </br>كتلة تعليمات برمجية غير كاملة محددة أو بناء جملة غير صالح",
  "BEAUTIFY_OPTIONS": "الخيارات التي تتحكم في كيفية عمل كود تجميل",
  "BEAUTIFY_OPTION_PRINT_WIDTH": "حدد طول الخط الذي سوف يلتف عليه جهاز التجميل",
  "BEAUTIFY_OPTION_SEMICOLON": "إضافة فاصلة منقوطة في نهاية كل عبارة",
  "BEAUTIFY_OPTION_SINGLE_QUOTE": "استخدم علامات اقتباس مفردة بدلاً من علامات الاقتباس المزدوجة",
  "BEAUTIFY_OPTION_QUOTE_PROPS": "التغيير عندما يتم اقتباس الخصائص في الكائنات",
  "BEAUTIFY_OPTION_BRACKET_SAME_LINE": "ضع عنصر HTML متعدد الأسطر (HTML، JSX، Vue، Angular) في نهاية السطر الأخير بدلاً من أن تكون وحيدًا في السطر التالي (لا ينطبق على عناصر الإغلاق الذاتي)",
  "BEAUTIFY_OPTION_SINGLE_ATTRIBUTE_PER_LINE": "فرض سمة واحدة لكل سطر في HTML و Vue و JSX",
  "BEAUTIFY_OPTION_PROSE_WRAP": "التفاف النثر إذا تجاوز عرض الطباعة في ملفات تخفيض السعر",
  "BEAUTIFY_OPTION_PRINT_TRAILING_COMMAS": "اطبع الفواصل اللاحقة حيثما أمكن ذلك في الهياكل النحوية متعددة الأسطر المفصولة بفواصل"
});