/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "Domyślny systemu",
  "PROJECT_BUSY": "Operacje projektowe w toku",
  "DUPLICATING": "Duplikowanie {0}",
  "MOVING": "Przenoszenie {0}",
  "COPYING": "Kopiowanie {0}",
  "DELETING": "Usuwanie {0}",
  "RENAMING": "Zmiana nazwy",
  "STORED_IN_YOUR_BROWSER": "Przechowywane w Twojej przeglądarce",
  "SUPPORT_US_OPEN_COLLECTIVE": "Wesprzyj nas w Open Collective",
  "GENERIC_ERROR": "(błąd {0})",
  "NOT_FOUND_ERR": "Nie znaleziono pliku/folderu.",
  "NOT_READABLE_ERR": "Nie można odczytać pliku/folderu.",
  "EXCEEDS_MAX_FILE_SIZE": "Pliki większe niż {0} MB nie mogą być otwarte w {APP_NAME}.",
  "NO_MODIFICATION_ALLOWED_ERR": "Nie można zmodyfikować folderu docelowego.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "Nie masz uprawnień by modyfikować ten plik.",
  "CONTENTS_MODIFIED_ERR": "Plik został zmodyfikowany poza {APP_NAME}.",
  "UNSUPPORTED_ENCODING_ERR": "{APP_NAME} aktualnie wspiera tylko pliki tekstowe z kodowaniem UTF-8.",
  "ENCODE_FILE_FAILED_ERR": "{APP_NAME} nie może zakodować zawartości pliku.",
  "DECODE_FILE_FAILED_ERR": "{APP_NAME} nie może odkodować zawartości pliku.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "{APP_NAME} obecnie nie obsługuje plików tekstowych zakodowanych w UTF-16.",
  "FILE_EXISTS_ERR": "Plik lub folder już istnieje.",
  "FILE": "plik",
  "FILE_TITLE": "Plik",
  "DIRECTORY": "folder",
  "DIRECTORY_TITLE": "Folder",
  "DIRECTORY_NAMES_LEDE": "Nazwy folderów",
  "FILENAMES_LEDE": "Nazwy plików",
  "FILENAME": "Nazwa pliku",
  "DIRECTORY_NAME": "Nazwa folderu",
  "ERROR_LOADING_PROJECT": "Błąd podczas ładowania projektu",
  "OPEN_DIALOG_ERROR": "Wystąpił błąd podczas wyświetlania okna otwierania pliku. (błąd {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "Wystąpił błąd przy próbie otwarcia folderu <span class='dialog-filename'>{0}</span>. (błąd {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "Wystąpił błąd podczas odczytu zawartości folderu <span class='dialog-filename'>{0}</span>. (błąd {1})",
  "ZOOM_WITH_SHORTCUTS": "Użyj skrótów klawiaturowych, aby powiększyć",
  "ZOOM_WITH_SHORTCUTS_DETAILS": "Użyj skrótów klawiaturowych <code><i>{0}</i></code> aby powiększyć i <code><i>{1}</i></code> , aby pomniejszyć.",
  "ERROR_OPENING_FILE_TITLE": "Błąd podczas otwarcia pliku",
  "ERROR_OPENING_FILE": "Wystąpił błąd podczas próby otwarcia pliku <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_OPENING_FILES": "Wystąpił błąd podczas otwierania plików:",
  "ERROR_RELOADING_FILE_TITLE": "Błąd podczas przeładowania zmian z dysku",
  "ERROR_RELOADING_FILE": "Błąd podczas przeładowania pliku <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_SAVING_FILE_TITLE": "Problem z zapisaniem pliku",
  "ERROR_SAVING_FILE": "Błąd podczas próby zapisu pliku <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_FILE_TITLE": "Błąd podczas zmiany nazwy pliku {0}",
  "ERROR_RENAMING_FILE": "Błąd podczas próby zmiany nazwy pliku {2} <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "Plik lub folder nie jest częścią aktualnie otwartego projektu. Niestety, w tym momencie możesz zmienić nazwę tylko dla plików projektu.",
  "ERROR_MOVING_FILE_TITLE": "Błąd podczas przenoszenia {0}",
  "ERROR_MOVING_FILE": "Wystąpił błąd podczas próby przeniesienia {2} <span class='dialog-filename'>{0}</span> . {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "Nie można przenieść pliku/folderu, ponieważ nie są one częścią bieżącego projektu.",
  "ERROR_DELETING_FILE_TITLE": "Błąd podczas usuwania pliku {0}",
  "ERROR_DELETING_FILE": "Błąd podczas próby usunięcia {2} <span class='dialog-filename'>{0}</span>. {1}",
  "INVALID_FILENAME_TITLE": "Nieprawidłowa nazwa pliku {0}",
  "CANNOT_PASTE_TITLE": "Nie można wkleić {0}",
  "CANNOT_DOWNLOAD_TITLE": "Nie można pobrać {0}",
  "ERR_TYPE_DOWNLOAD_FAILED": "Wystąpił błąd podczas pobierania <span class='dialog-filename'>{0}</span>",
  "ERR_TYPE_PASTE_FAILED": "Wystąpił błąd podczas wklejania <span class='dialog-filename'>{0}</span> do <span class='dialog-filename'>{1}</span>",
  "CANNOT_DUPLICATE_TITLE": "Nie można powielić",
  "ERR_TYPE_DUPLICATE_FAILED": "Wystąpił błąd podczas duplikowania <span class='dialog-filename'>{0}</span>",
  "ERR_TYPE_DUPLICATE_FAILED_NO_FILE": "Wybierz plik do zduplikowania.",
  "INVALID_FILENAME_MESSAGE": "{0} nie może kończyć się kropką (.), zawierać żadnych zarezerwowanych słów ani żadnych z tych znaków: <code class='emphasized'>{1}</code>",
  "ENTRY_WITH_SAME_NAME_EXISTS": "Plik lub folder o nazwie <span class='dialog-filename'>{0}</span> już istnieje.",
  "ERROR_CREATING_FILE_TITLE": "Nie można utworzyć pliku {0}",
  "ERROR_CREATING_FILE": "Błąd podczas próby stworzenia pliku {0} <span class='dialog-filename'>{1}</span>. {2}",
  "ERROR_MIXED_DRAGDROP": "Nie można otworzyć folderu podczas otwierana innych plików.",
  "ERROR_KEYMAP_TITLE": "Błąd podczas odczytywania konfiguracji klawiszy",
  "ERROR_KEYMAP_CORRUPT": "Twój plik z konfiguracją klawiszy nie jest poprawnie zakodowanym plikiem JSON. Zostanie on otwarty abyś mógł go poprawić.",
  "ERROR_LOADING_KEYMAP": "Twój plik z konfiguracją klawiszy nie jest poprawnie zakodowanym plikiem UTF-8 i nie może zostać załadowany.",
  "ERROR_RESTRICTED_COMMANDS": "Nie możesz nadpisać skrótów do tych komend: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "Nie możesz nadpisać tych skrótów: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "Próbujesz przypisać kilka skrótów do następujących komend: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "Upewnij się, że następujące skróty są unikalne (nie nadpisują się): {0}",
  "ERROR_INVALID_SHORTCUTS": "Podane skróty są nieprawidłowe: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "Próbujesz przypisać skróty do niestniejących komend: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "Błąd podczas wczytywania ustawień",
  "ERROR_PREFS_PROJECT_LINT": "Preferencje projektu",
  "ERROR_PREFS_PROJECT_LINT_MESSAGE": "Błąd: projekt zawiera pliki `.brackets.json` i `.phcode.json`, co powoduje konflikt. Usuń plik `.brackets.json` lub `.phcode.json`, a następnie załaduj projekt ponownie.",
  "ERROR_PREFS_CORRUPT": "Twój plik ustawień nie jest poprawnie zakodowanym plikiem JSON. Zostanie on otwarty abyś mógł go poprawić. Aby zastosować zmiany, uruchom ponownie {APP_NAME}.",
  "ERROR_PROJ_PREFS_CORRUPT": "Twój plik ustawień projektu nie jest poprawnie zakodowanym plikiem JSON. Zostanie on otwarty abyś mógł go poprawić. Aby zastosować zmiany, musisz przeładować projekt.",
  "ERROR_IN_BROWSER_TITLE": "Oops! {APP_NAME} nie działa jeszcze w przeglądarkach.",
  "ERROR_IN_BROWSER": "{APP_NAME} został zbudowany w HTML, jednak na razie działa jako samodzielna aplikacja. Możesz użyć jej do edycji plików na dysku. Aby uruchomić {APP_NAME} użyj aplikacji dostępnej pod adresem <b>github.com/adobe/brackets-shell</b>.",
  "ERROR_MAX_FILES_TITLE": "Błąd podczas indeksowania plików",
  "ERROR_MAX_FILES": "Ten projekt zawiera więcej niż 30.000 plików. Funkcje, które pracują na wielu plikach mogą być wyłączone lub zachowywać się tak, jakby projekt był pusty. <a href='https://github.com/adobe/brackets/wiki/Large-Projects'>Przeczytaj więcej nt. pracy z dużymi projektami</a>.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "Błąd podczas uruchamiania przeglądarki",
  "ERROR_CANT_FIND_CHROME": "Nie znaleziono przeglądarki Google Chrome. Upewnij się, że jest zainstalowana.",
  "ERROR_LAUNCHING_BROWSER": "Błąd podczas uruchamiania przeglądarki. (błąd {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "Błąd podglądu na żywo",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "Łączenie z przeglądarką",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "Aby podgląd na żywo mógł się połączyć, Chrome musi zostać zrestartowany z włączonym zdalnym debugowaniem.<br /><br />Czy chcesz zrestartować Chrome i uaktywnić zdalne debugowanie?<br /><br />",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "Nie można wczytać strony podglądu na żywo.",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "Aby uruchomić podgląd na żywo na plikach serwerowych, musisz podać główny adres dla tego projektu (Base URL).",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "Błąd przy próbie uruchomienia serwera HTTP dla podglądu na żywo. Spróbuj ponownie.",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "Więcej informacji znajdziesz na stronie <a href='{0}' title='{0}'>Troubleshooting Live Preview connection errors</a>.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "Podgląd na żywo",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "Podgląd na żywo: łączenie…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "Podgląd na żywo: inicjalizacja…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "Aktywny serwer podglądu na żywo",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "Podgląd na żywo",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "Wybierz plik do podglądu na żywo",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "Odśwież stronę",
  "LIVE_DEV_TOGGLE_LIVE_HIGHLIGHT": "Przełącz najciekawsze podglądy na żywo",
  "LIVE_DEV_CLICK_POPOUT": "Wyskakujący podgląd na żywo w nowym oknie",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "Przypnij na Odepnij stronę podglądu",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "Podgląd na żywo (bez odświeżania - wystąpiły błędy składniowe)",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "Podgląd na żywo został wyłączony, ponieważ uruchomiono narzędzia dla programistów w przeglądarce",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "Podgląd na żywo został wyłączony, ponieważ strona została zamknięta w przeglądarce",
  "LIVE_DEV_NAVIGATED_AWAY": "Podgląd na żywo został wyłączony, ponieważ została załadowana strona nie należąca do aktualnego projektu",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "Podgląd na żywo został wyłączony z nieznanego powodu ({0})",
  "SAVE_CLOSE_TITLE": "Zapisz zmiany",
  "SAVE_CLOSE_MESSAGE": "Czy chcesz zapisać zmiany w dokumencie <span class='dialog-filename'>{0}</span>?",
  "SAVE_CLOSE_MULTI_MESSAGE": "Czy chcesz zapisać zmiany w następujących plikach?",
  "EXT_MODIFIED_TITLE": "Zmiany zewnętrzne",
  "CONFIRM_DELETE_TITLE": "Potwierdź usunięcie",
  "CONFIRM_FILE_DELETE": "Czy na pewno chcesz usunąć plik <span class='dialog-filename'>{0}</span>?",
  "CONFIRM_FOLDER_DELETE": "Czy na pewno chcesz usunąć folder <span class='dialog-filename'>{0}</span>?",
  "FILE_DELETED_TITLE": "Plik został usunięty",
  "EXT_MODIFIED_WARNING": "<span class='dialog-filename'>{0}</span> został zmodyfikowany na dysku, poza {APP_NAME}.<br /><br />Czy chcesz zapisać plik i nadpisać te zmiany?",
  "EXT_MODIFIED_MESSAGE": "<span class='dialog-filename'>{0}</span> został zmodyfikowany na dysku, poza {APP_NAME}, ale zawiera też niezapisane zmiany w {APP_NAME}.<br /><br />Którą wersję chcesz zachować?",
  "EXT_DELETED_MESSAGE": "<span class='dialog-filename'>{0}</span> został usunięty z dysku, ale zawiera niezapisane zmiany w {APP_NAME}.<br /><br />Czy chcesz zachować te zmiany?",
  "EXT_ALWAYS_MODIFIED_BUTTON_TOOLTIP": "Zawsze nadpisuj pliki do czasu zmiany projektu lub ponownego uruchomienia",
  "WINDOW_UNLOAD_WARNING": "Czy na pewno chcesz przejść pod inny adres URL i opuścić aplikację {APP_NAME}?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "Masz niezapisane zmiany! Czy na pewno chcesz przejść pod inny adres URL i opuścić aplikację {APP_NAME}?",
  "DONE": "Gotowe",
  "OK": "OK",
  "CANCEL": "Anuluj",
  "DONT_SAVE": "Nie zapisuj",
  "SAVE": "Zapisz",
  "SAVE_AS": "Zapisz jako…",
  "SAVE_AND_OVERWRITE": "Nadpisz",
  "ALWAYS_OVERWRITE": "Zawsze nadpisz",
  "DELETE": "Usuń",
  "BUTTON_YES": "Tak",
  "BUTTON_NO": "Nie",
  "FIND_MATCH_INDEX": "{0} z {1}",
  "FIND_NO_RESULTS": "Brak wyników",
  "FIND_QUERY_PLACEHOLDER": "Szukaj…",
  "FIND_HISTORY_MAX_COUNT": "Maksymalna liczba pozycji w historii wyszukiwania",
  "REPLACE_PLACEHOLDER": "Zamień na…",
  "BUTTON_REPLACE_ALL": "Zamień wiele…",
  "BUTTON_REPLACE_BATCH": "Przetwarzaj…",
  "BUTTON_REPLACE_ALL_IN_FILES": "Zamień w wielu plikach…",
  "BUTTON_REPLACE": "Zamień",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "Następny wynik",
  "BUTTON_PREV_HINT": "Poprzedni wynik",
  "BUTTON_CASESENSITIVE_HINT": "Weź pod uwagę wielkie i małe litery",
  "BUTTON_REGEXP_HINT": "Wyrażenie regularne",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "Zamień bez cofania",
  "REPLACE_WITHOUT_UNDO_WARNING": "Ponieważ więcej niż {0} plików wymaga zmiany, {APP_NAME} zmodyfikuje pliki na dysku, które nie są otwarte.<br />Nie będziesz możlwiości cofnięcia nadpisanych zmian w tych plikach.",
  "BUTTON_REPLACE_WITHOUT_UNDO": "Zamień bez cofania",
  "OPEN_FILE": "Otwórz plik",
  "SAVE_FILE_AS": "Zapisz plik",
  "CHOOSE_FOLDER": "Wybierz folder",
  "RELEASE_NOTES": "Informacje o wydaniu",
  "NO_UPDATE_TITLE": "{APP_NAME} jest aktualny!",
  "NO_UPDATE_MESSAGE": "Aktualnie używasz najnowszej wersji {APP_NAME}.",
  "FIND_REPLACE_TITLE_LABEL": "Zamień",
  "FIND_REPLACE_TITLE_WITH": "z",
  "FIND_TITLE_LABEL": "Znaleziono",
  "FIND_TITLE_SUMMARY": "&mdash; {0} {1} {2} w {3}",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "w <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_NO_SCOPE": "w projekcie",
  "FIND_IN_FILES_ZERO_FILES": "Filtr wyklucza wszystkie pliki {0}",
  "FIND_IN_FILES_FILE": "plik",
  "FIND_IN_FILES_FILES": "pliki",
  "FIND_IN_FILES_MATCH": "dopasowanie",
  "FIND_IN_FILES_MATCHES": "dopasowania",
  "FIND_IN_FILES_MORE_THAN": "Więcej niż ",
  "FIND_IN_FILES_PAGING": "{0}&mdash;{1}",
  "FIND_IN_FILES_FILE_PATH": "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "Naciśnij Ctrl/Cmd by rozwinąć/zwinąć wszystkie",
  "FIND_IN_FILES_INDEXING": "Indeksowanie do natychmiastowego wyszukiwania…",
  "FIND_IN_FILES_SEARCHING": "Wyszukiwanie plików…",
  "FIND_IN_FILES_SEARCHING_IN": "w {0}",
  "FIND_IN_FILES_INDEXING_PROGRESS": "Indeksowanie {0} z {1} plików do wyszukiwania błyskawicznego…",
  "REPLACE_IN_FILES_ERRORS_TITLE": "Zamień błędy",
  "REPLACE_IN_FILES_ERRORS": "Poniższe pliki nie zostały zmienione, ponieważ ich treść zmieniła się po zakończeniu wyszukiwania lub nie mogły być zapisane.",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "Błąd podczas pobierania informacji o aktualizacjach",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "Wystąpił problem podczas pobierania informacji o najnowszej wersji aplikacji. Upewnij się, że masz połączenie z internetem i spróbuj ponownie",
  "NEW_FILE_FILTER": "Nowy filtr…",
  "CLEAR_FILE_FILTER": "Nie wykluczaj plików",
  "NO_FILE_FILTER": "Brak wykluczonych plików",
  "EXCLUDE_FILE_FILTER": "Wyklucz pliki",
  "INCLUDE_FILE_FILTER": "Szukaj w plikach",
  "FILTER_PLACEHOLDER": "np. indeks,.css,*.js,src/**/*.css",
  "FILTER_HISTORY_TOOLTIP": "Naciśnij `Ctrl-Spacja`, aby wyświetlić historię.",
  "FILTER_HISTORY_TOOLTIP_MAC": "Naciśnij `Cmd-Spacja`, aby wyświetlić historię.",
  "FIND_HISTORY_TOOLTIP": "Naciśnij `Ctrl-Spacja`, aby wyświetlić historię.",
  "FIND_HISTORY_TOOLTIP_MAC": "Naciśnij `Cmd-Spacja`, aby wyświetlić historię.",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "Nie można użyć szybkiej edycji w tym miejscu",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "Szybka edycja CSS: zaznacz kursorem pojedynczą nazwę klasy",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "Szybka edycja CSS: niekompletny atrybut class",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "Szybka edycja CSS: niekompletny atrybut id",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "Szybka edycja CSS: zaznacz kursorem tag, klasę lub id",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "Szybka edycja funkcji czasowych CSS: nieprawidłowa składnia",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "Szybka edycja JS: zaznacz kursorem nazwę funkcji",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "Nie znaleziono dokumentacji dla tego elementu.",
  "PROJECT_LOADING": "Ładowanie…",
  "UNTITLED": "Bez tytułu",
  "WORKING_FILES": "Otwarte pliki",
  "TOP": "Panel górny",
  "BOTTOM": "Panel dolny",
  "LEFT": "Panel lewy",
  "RIGHT": "Panel prawy",
  "CMD_SPLITVIEW_NONE": "Bez podziału",
  "CMD_SPLITVIEW_VERTICAL": "Podziel pionowo",
  "CMD_SPLITVIEW_HORIZONTAL": "Podziel poziomo",
  "SPLITVIEW_MENU_TOOLTIP": "Podziel edytor pionowo lub poziomo",
  "GEAR_MENU_TOOLTIP": "Uporządkuj pliki",
  "SPLITVIEW_INFO_TITLE": "Plik jest już otwarty",
  "SPLITVIEW_MULTIPANE_WARNING": "Plik jest już otwarty w innym panelu. {APP_NAME} niedługo będzie pozwalał otwierać ten sam plik w wielu panelach. Do tego czasu plik będzie widoczny w panelu, w którym już jest otwarty.<br /><br />(Tę wiadomość zobaczysz tylko raz)",
  "KEYBOARD_OVERLAY_TEXT": "Użyj strzałek do nawigacji lub pisania, aby wybrać elementy interfejsu użytkownika.",
  "KEYBOARD_SHORTCUT_CHANGE_TITLE": "Zmień skrót klawiaturowy…",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_TITLE": "Zmień skrót klawiaturowy",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_TEXT": "Naciśnij nową kombinację klawiszy dla <b>„{0}”</b> (obecnie: <b>{1}</b> )",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_DUPLICATE": "Ostrzeżenie: Kombinacja klawiszy <b>{0}</b> jest już przypisana do <b>&#39;{1}&#39;</b> . Przypisać ponownie do <b>„{2}”</b> ?",
  "KEYBOARD_SHORTCUT_ASSIGN": "Przydzielać",
  "KEYBOARD_SHORTCUT_NONE": "Nic",
  "KEYBOARD_SHORTCUT_MENU_SHOW_SHORTCUTS": "Skróty klawiszowe…",
  "KEYBOARD_SHORTCUT_MENU_SHOW_SHORTCUTS_BUTTON": "Pokaż wszystkie skróty…",
  "KEYBOARD_SHORTCUT_TABLE_BASE_KEY": "Klucz podstawowy",
  "KEYBOARD_SHORTCUT_TABLE_KEY_BINDING": "Skrót",
  "KEYBOARD_SHORTCUT_TABLE_COMMAND_ID": "Identyfikator polecenia",
  "KEYBOARD_SHORTCUT_TABLE_COMMAND_NAME": "Komenda",
  "KEYBOARD_SHORTCUT_TABLE_DOUBLE_CLICK": "Kliknij dwukrotnie, aby zmienić skrót",
  "KEYBOARD_SHORTCUT_TABLE_ORIGIN": "Pochodzenie",
  "KEYBOARD_SHORTCUT_ORIG_EXTENSION": "Rozszerzenie",
  "KEYBOARD_SHORTCUT_PANEL_TITLE": "Skróty klawiszowe",
  "KEYBOARD_SHORTCUT_PANEL_FILTER": "Filtruj&hellip;",
  "KEYBOARD_SHORTCUT_PANEL_RESET": "Resetowanie…",
  "KEYBOARD_SHORTCUT_PANEL_RESET_DEFAULT": "Przywróć domyślne skróty…",
  "KEYBOARD_SHORTCUT_RESET_DIALOG_TITLE": "Zresetuj skróty klawiaturowe",
  "KEYBOARD_SHORTCUT_RESET_DIALOG_MESSAGE": "Zresetować wszystkie niestandardowe skróty do ustawień domyślnych? Tego nie da się cofnąć.",
  "STATUSBAR_CURSOR_POSITION": "linia {0}, kolumna {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": " — Zaznaczono {0} kolumnę",
  "STATUSBAR_SELECTION_CH_PLURAL": " — Zaznaczono {0} kolumn",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " — Zaznaczono {0} linię",
  "STATUSBAR_SELECTION_LINE_PLURAL": " — Zaznaczono {0} linii",
  "STATUSBAR_SELECTION_MULTIPLE": " — {0} zaznaczeń",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "Kliknij, by zamienić wcięcia na spacje",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "Kliknij, by zamienić wcięcia na tabulacje",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "Kliknij, by zmienić ilość spacji we wcięciu",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "Kliknij, by zmienić wielkość tabulacji",
  "STATUSBAR_SPACES": "Spacje:",
  "STATUSBAR_TAB_SIZE": "Tabulacje:",
  "STATUSBAR_LINE_COUNT_SINGULAR": "— {0} linia",
  "STATUSBAR_LINE_COUNT_PLURAL": "— {0} linii",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "Rozszerzenia wyłączone",
  "STATUSBAR_INSERT": "INS",
  "STATUSBAR_OVERWRITE": "OVR",
  "STATUSBAR_INSOVR_TOOLTIP": "Kliknij aby zmienić tryb wprowadzania: wstaw (INS) lub zastąp (OVR)",
  "STATUSBAR_LANG_TOOLTIP": "Kliknij aby zmienić rodzaj pliku (podświetlanie składni)",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. Naciśnij aby włączyć/wyłączyć panel raportów.",
  "STATUSBAR_DEFAULT_LANG": "(domyślny)",
  "STATUSBAR_SET_DEFAULT_LANG": "Ustaw domyślny dla plików .{0}",
  "STATUSBAR_ENCODING_TOOLTIP": "Wybierz kodowanie",
  "STATUSBAR_TASKS": "Zadania",
  "STATUSBAR_TASKS_TOOLTIP": "Zarządzaj aktywnymi zadaniami",
  "STATUSBAR_TASKS_HIDE_SPINNER": "Ukryj ikonę pokrętła",
  "STATUSBAR_TASKS_UNKNOWN_EXTENSION_TASK": "Nieznane zadanie rozszerzenia…",
  "STATUSBAR_TASKS_PLAY": "Rozpocznij lub Wznów",
  "STATUSBAR_TASKS_PAUSE": "Pauza",
  "STATUSBAR_TASKS_STOP": "Zatrzymywać się",
  "STATUSBAR_TASKS_RESTART": "Uruchom ponownie",
  "ERRORS_PANEL_TITLE_MULTIPLE": "{0} problemów",
  "SINGLE_ERROR": "1 błąd {0}",
  "MULTIPLE_ERRORS": "{1} błędów {0} ",
  "NO_ERRORS": "Brak błędów {0} – dobra robota!",
  "NO_ERRORS_MULTIPLE_PROVIDER": "Brak błędów - dobra robota!",
  "LINT_DISABLED": "Linting jest wyłączony.",
  "NO_LINT_AVAILABLE": "Żaden linter nie jest dostępny dla {0}",
  "NOTHING_TO_LINT": "Brak plików do sprawdzenia.",
  "LINTER_TIMED_OUT": "{0} przekroczył limit czasu, czekał {1} ms",
  "LINTER_FAILED": "{0} zakończył z błędem: {1}",
  "FILE_MENU": "Plik",
  "CMD_FILE_NEW_UNTITLED": "Nowy",
  "CMD_FILE_NEW": "Nowy plik",
  "CMD_FILE_DUPLICATE": "Duplikuj",
  "CMD_FILE_DUPLICATE_FILE": "Duplikat pliku",
  "CMD_FILE_DOWNLOAD_PROJECT": "Pobierz projekt",
  "CMD_FILE_DOWNLOAD": "Pobierać",
  "CMD_FILE_CUT": "Wytnij",
  "CMD_FILE_COPY": "Kopiuj",
  "CMD_FILE_COPY_PATH": "Kopiuj ścieżkę",
  "CMD_FILE_PASTE": "Wklej",
  "CMD_PROJECT_NEW": "Nowy projekt…",
  "CMD_FILE_NEW_FOLDER": "Nowy folder",
  "CMD_FILE_OPEN": "Otwórz pliki…",
  "CMD_RECENT_FILES_OPEN": "Ostatnie pliki…",
  "CMD_ADD_TO_WORKING_SET": "Dodaj do folderu roboczego",
  "CMD_OPEN_DROPPED_FILES": "Otwórz przeciągnięte pliki",
  "CMD_OPEN_FOLDER": "Otwórz folder…",
  "CMD_FILE_CLOSE": "Zamknij",
  "CMD_FILE_CLOSE_ALL": "Zamknij wszystko",
  "CMD_FILE_CLOSE_LIST": "Zamknij listę",
  "CMD_FILE_CLOSE_OTHERS": "Zamknij inne",
  "CMD_FILE_CLOSE_ABOVE": "Zamknij pliki powyżej",
  "CMD_FILE_CLOSE_BELOW": "Zamknij pliki poniżej",
  "CMD_FILE_SAVE": "Zapisz plik",
  "CMD_FILE_SAVE_ALL": "Zapisz wszystko",
  "CMD_FILE_SAVE_AS": "Zapisz jako…",
  "CMD_LIVE_FILE_PREVIEW": "Podgląd na żywo",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "Podgląd na żywo (eksperymentalny)",
  "CMD_RELOAD_LIVE_PREVIEW": "Wymuś przeładowanie podglądu na żywo",
  "CMD_PROJECT_SETTINGS": "Ustawienia projektu…",
  "CMD_FILE_RENAME": "Zmień nazwę",
  "CMD_FILE_DELETE": "Usuń",
  "CMD_INSTALL_EXTENSION": "Zainstaluj rozszerzenie…",
  "CMD_EXTENSION_MANAGER": "Menedżer rozszerzeń…",
  "CMD_FILE_REFRESH": "Odśwież",
  "CMD_FILE_SHOW_FOLDERS_FIRST": "Najpierw sortuj foldery",
  "CMD_QUIT": "Wyjdź",
  "CMD_EXIT": "Wyjdź",
  "EDIT_MENU": "Edytuj",
  "CMD_UNDO": "Cofnij",
  "CMD_REDO": "Ponów",
  "CMD_CUT": "Wytnij",
  "CMD_COPY": "Kopiuj",
  "CMD_PASTE": "Wklej",
  "CMD_SELECT_ALL": "Zaznacz wszystko",
  "CMD_SELECT_LINE": "Zaznacz linię",
  "CMD_SPLIT_SEL_INTO_LINES": "Podziel zaznaczenie na linie",
  "CMD_ADD_CUR_TO_NEXT_LINE": "Dodaj kursor do następnej linii",
  "CMD_ADD_CUR_TO_PREV_LINE": "Dodaj kursor do poprzedniej linii",
  "CMD_INDENT": "Dodaj wcięcie",
  "CMD_UNINDENT": "Cofnij wcięcie",
  "CMD_DUPLICATE": "Duplikuj",
  "CMD_DELETE_LINES": "Usuń linię",
  "CMD_COMMENT": "Komentarz liniowy",
  "CMD_BLOCK_COMMENT": "Komentarz blokowy",
  "CMD_LINE_UP": "Przenieś linię wyżej",
  "CMD_LINE_DOWN": "Przenieś linię niżej",
  "CMD_OPEN_LINE_ABOVE": "Otwórz linię wyżej",
  "CMD_OPEN_LINE_BELOW": "Otwórz linię niżej",
  "CMD_TOGGLE_CLOSE_BRACKETS": "Automatycznie zamykaj nawiasy",
  "CMD_SHOW_CODE_HINTS": "Pokaż podpowiedź",
  "CMD_BEAUTIFY_CODE": "Upiększ kod",
  "CMD_BEAUTIFY_CODE_ON_SAVE": "Upiększ kod po zapisaniu",
  "FIND_MENU": "Znajdź",
  "CMD_FIND": "Znajdź",
  "CMD_FIND_NEXT": "Znajdź następny",
  "CMD_FIND_PREVIOUS": "Znajdź poprzedni",
  "CMD_FIND_ALL_AND_SELECT": "Wybierz opcję Wszystkie wystąpienia",
  "CMD_ADD_NEXT_MATCH": "Dodaj następne wystąpienie",
  "CMD_SKIP_CURRENT_MATCH": "Pomiń i dodaj następne wystąpienie",
  "CMD_FIND_IN_FILES": "Szukaj w plikach",
  "CMD_FIND_IN_SUBTREE": "Szukaj w…",
  "CMD_REPLACE": "Zamień",
  "CMD_REPLACE_IN_FILES": "Zamień w plikach",
  "CMD_REPLACE_IN_SUBTREE": "Zamień w…",
  "VIEW_MENU": "Widok",
  "CMD_HIDE_SIDEBAR": "Ukryj pasek boczny",
  "CMD_SHOW_SIDEBAR": "Pokaż pasek boczny",
  "CMD_TOGGLE_SIDEBAR": "Przełącz pasek boczny",
  "CMD_TOGGLE_PANELS": "Przełącz panele",
  "CMD_TOGGLE_PURE_CODE": "Tryb bez przeszkadzania",
  "CMD_TOGGLE_FULLSCREEN": "Pełny ekran",
  "CMD_ZOOM_UI": "Zoom UI i czcionki",
  "CMD_ZOOM_IN": "Zbliżenie",
  "CMD_ZOOM_IN_SCALE": "Powiększ (bieżące: {0}%)",
  "CMD_ZOOM_OUT": "Pomniejsz",
  "CMD_INCREASE_FONT_SIZE": "Zwiększ czcionkę",
  "CMD_DECREASE_FONT_SIZE": "Zmniejsz czcionkę",
  "CMD_RESTORE_FONT_SIZE": "Przywróć domyślny rozmiar czcionki",
  "CMD_SCROLL_LINE_UP": "Przewiń linię wyżej",
  "CMD_SCROLL_LINE_DOWN": "Przewiń linię niżej",
  "CMD_TOGGLE_LINE_NUMBERS": "Numery linii",
  "CMD_TOGGLE_ACTIVE_LINE": "Podświetl aktualną linię",
  "CMD_TOGGLE_WORD_WRAP": "Zawijaj wiersze",
  "CMD_LIVE_HIGHLIGHT": "Podświetlaj w podglądzie na żywo",
  "CMD_VIEW_TOGGLE_INSPECTION": "Sprawdzaj poprawność plików przy zapisie",
  "CMD_WORKINGSET_SORT_BY_ADDED": "Sortuj według dodanych",
  "CMD_WORKINGSET_SORT_BY_NAME": "Sortuj według nazwy",
  "CMD_WORKINGSET_SORT_BY_TYPE": "Sortuj według typu",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "Automatyczne sortowanie",
  "CMD_THEMES": "Motywy…",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "Automatycznie zamknij wyszukiwanie",
  "CMD_KEYBOARD_NAV_OVERLAY": "Tryb nawigacji interfejsu użytkownika",
  "NAVIGATE_MENU": "Nawigacja",
  "CMD_QUICK_OPEN": "Otwórz szybko",
  "CMD_GOTO_LINE": "Przejdź do linii",
  "CMD_GOTO_DEFINITION": "Znajdź szybko definicję",
  "CMD_GOTO_DEFINITION_PROJECT": "Szybkie wyszukiwanie definicji w projekcie",
  "CMD_GOTO_FIRST_PROBLEM": "Przejdź do pierwszego błędu",
  "CMD_TOGGLE_QUICK_EDIT": "Szybka edycja",
  "CMD_TOGGLE_QUICK_DOCS": "Szybka dokumentacja",
  "CMD_QUICK_EDIT_PREV_MATCH": "Poprzedni element szybkiej edycji",
  "CMD_QUICK_EDIT_NEXT_MATCH": "Następny element szybkiej edycji",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "Nowa reguła",
  "CMD_NEXT_DOC": "Następny dokument",
  "CMD_PREV_DOC": "Poprzedni dokument",
  "CMD_NAVIGATE_BACKWARD": "Przejdź wstecz",
  "CMD_NAVIGATE_FORWARD": "Przejdź do przodu",
  "CMD_NEXT_DOC_LIST_ORDER": "Następny dokument z listy",
  "CMD_PREV_DOC_LIST_ORDER": "Poprzedni dokument z listy",
  "CMD_SHOW_IN_TREE": "Pokaż w drzewie katalogów",
  "CMD_SHOW_IN_EXPLORER": "Pokaż w eksploratorze",
  "CMD_SHOW_IN_FINDER": "Pokaż w Finder",
  "CMD_SHOW_IN_OS": "Pokaż w plikach systemu operacyjnego",
  "CMD_SWITCH_PANE_FOCUS": "Zmień aktywny panel",
  "CMD_OPEN_VFS": "Otwórz wirtualny system plików",
  "CMD_DIAGNOSTIC_TOOLS": "Narzędzia diagnostyczne {APP_NAME}",
  "CMD_OPEN_EXTENSIONS_FOLDER": "Otwórz folder rozszerzeń…",
  "CMD_OPEN_VIRTUAL_SERVER": "Otwórz serwer wirtualny",
  "HELP_MENU": "Pomoc",
  "CMD_CHECK_FOR_UPDATE": "Sprawdź aktualizacje",
  "CMD_HOW_TO_USE_BRACKETS": "Jak używać {APP_NAME}",
  "CMD_SUPPORT": "Wsparcie {APP_NAME}",
  "CMD_SUGGEST": "Zaproponuj swój pomysł",
  "CMD_RELEASE_NOTES": "Informacje o wydaniu",
  "CMD_GET_INVOLVED": "Daj coś od siebie",
  "CMD_SHOW_EXTENSIONS_FOLDER": "Otwórz folder z rozszerzeniami",
  "CMD_HEALTH_DATA_STATISTICS": "Raport dotyczący zdrowia…",
  "CMD_HOMEPAGE": "Strona główna - Pobierz aplikacje",
  "CMD_TWITTER": "{TWITTER_NAME} na Twitterze",
  "CMD_ABOUT": "O programie",
  "CMD_OPEN_PREFERENCES": "Otwórz plik z ustawieniami",
  "CMD_OPEN_KEYMAP": "Otwórz plik mapy kluczy użytkownika",
  "EXPERIMENTAL_BUILD": "kompilacja eksperymentalna",
  "RELEASE_BUILD": "kompilacja",
  "DEVELOPMENT_BUILD": "kompilacja rozwojowa",
  "PRERELEASE_BUILD": "kompilacja przedpremierowa",
  "RELOAD_FROM_DISK": "Załaduj z dysku",
  "KEEP_CHANGES_IN_EDITOR": "Zachowaj zmiany w edytorze",
  "CLOSE_DONT_SAVE": "Zamknij (nie zapisuj)",
  "RELAUNCH_CHROME": "Zrestartuj Chrome",
  "ABOUT": "O programie",
  "CLOSE": "Zamknij",
  "ABOUT_TEXT_LINE1": "Wydaj {VERSION_MAJOR}.{VERSION_MINOR} {BUILD_TYPE} {VERSION}",
  "ABOUT_TEXT_BUILD_TIMESTAMP": "sygnatura czasowa kompilacji:",
  "ABOUT_TEXT_LINE3": "Biblioteki stron trzecich, z których korzystamy — <a href='https://github.com/phcode-dev/phoenix/tree/main/src/thirdparty/licences'>licencje i atrybucje</a> .",
  "ABOUT_TEXT_LINE4": "Dokumentacja i źródło na <a href='https://github.com/phcode-dev/phoenix/'>https://github.com/phcode-dev/phoenix/</a>",
  "ABOUT_TEXT_LINE5": "Wykonane za pomocą ❤ i JavaScript przez:",
  "ABOUT_TEXT_LINE6": "Mnóstwo osób (ale w tej chwili mamy problem z załadowaniem tych danych).",
  "ABOUT_TEXT_MDN_DOCS": "Dokumentacja MDN oraz logo MDN są objęte licencją Creative Commons Attribution, <a href='{MDN_DOCS_LICENSE}'>CC-BY-SA 2.5 Unported</a>.",
  "UPDATE_NOTIFICATION_TOOLTIP": "Dostępna jest nowa wersja {APP_NAME}! Kliknij tutaj i dowiedz się więcej.",
  "UPDATE_NOT_AVAILABLE_TITLE": "Aplikacja {APP_NAME} jest aktualna",
  "UPDATE_UP_TO_DATE": "Twoja wersja aplikacji {APP_NAME} jest najnowsza i najlepsza!",
  "UPDATE_AVAILABLE_TITLE": "Dostępna nowa aktualizacja",
  "UPDATE_READY_RESTART_TITLE": "Aktualizacja gotowa: wymagane ponowne uruchomienie",
  "UPDATE_READY_RESTART_MESSAGE": "Zamknij wszystkie okna aplikacji {APP_NAME} i uruchom ją ponownie, aby uruchomić zaktualizowaną wersję.",
  "UPDATE_READY_RESTART_INSTALL_MESSAGE": "Aktualizacja została pobrana: zamknij wszystkie okna aplikacji {APP_NAME}, aby zastosować najnowsze aktualizacje.",
  "UPDATE_FAILED_TITLE": "Aktualizacja nie powiodła się",
  "UPDATE_INSTALLING": "Instalacja aktualizacji…",
  "UPDATE_INSTALLING_MESSAGE": "Trwa instalacja aktualizacji: aplikacja {APP_NAME} instaluje obecnie najnowsze aktualizacje. Aplikacja zostanie automatycznie zamknięta po zakończeniu instalacji.",
  "UPDATE_FAILED_MESSAGE": "Zamknij wszystkie okna aplikacji {APP_NAME} i otwórz aplikację ponownie, aby ponowić próbę aktualizacji.",
  "UPDATE_FAILED_VISIT_SITE_MESSAGE": "Aby spróbować ponownie, zamknij wszystkie wystąpienia aplikacji {APP_NAME} i uruchom ją ponownie.<br> Wkrótce zostaniesz przekierowany na naszą stronę pobierania, gdzie możesz ręcznie pobrać najnowszą wersję.",
  "UPDATE_MESSAGE": "Hej, dostępna jest już nowa wersja {APP_NAME}. Oto kilka nowych funkcjonalności:",
  "GET_IT_NOW": "Pobierz teraz!",
  "UPDATE_LATER": "Przypomnij mi później",
  "UPDATE_DONE": "Uruchom ponownie, aby zaktualizować aplikację {APP_NAME}",
  "UPDATE_RESTART": "Uruchom ponownie, aby zastosować aktualizacje",
  "UPDATE_RESTART_INSTALL": "Uruchom ponownie, aby zainstalować aktualizacje",
  "UPDATE_DOWNLOADING": "Pobieranie instalatora",
  "INSTALL_WEBAPP": "Zainstaluj aplikację {APP_NAME} na swoim urządzeniu",
  "UPDATE_DOWNLOAD_PROGRESS": "Pobieranie — {0} z {1} MB",
  "UPDATING_APP": "Aktualizuję aplikację {APP_NAME}",
  "UPDATING_APP_MESSAGE": "To może zająć chwilę",
  "UPDATING_APP_DIALOG_MESSAGE": "Aktualizacja w toku. Podczas aktualizacji możesz nadal korzystać z aplikacji {APP_NAME}.",
  "PROJECT_SETTINGS_TITLE": "Ustawienia projektu dla: {0}",
  "PROJECT_SETTING_BASE_URL": "Adres podglądu na żywo",
  "PROJECT_SETTING_BASE_URL_HINT": "Aby użyć lokalnego serwera, wpisz odpowiedni adres, np. http://localhost:8000/",
  "BASEURL_ERROR_INVALID_PROTOCOL": "Protokół {0} nie jest wspierany przez podgląd na żywo&mdash;Użyj http lub https.",
  "BASEURL_ERROR_SEARCH_DISALLOWED": "Adres URL nie może zawierać parametrów wyszukiwania takich, jak \"{0}\".",
  "BASEURL_ERROR_HASH_DISALLOWED": "Adres URL nie może zawierać znaku hash: \"{0}\".",
  "BASEURL_ERROR_INVALID_CHAR": "Znaki specjalne takie, jak '{0}' muszą być zakodowane.",
  "BASEURL_ERROR_UNKNOWN_ERROR": "Nieznany błąd podczas parsowania adresu URL",
  "EMPTY_VIEW_HEADER": "<em>Kliknij w to okno, a następnie otwórz plik</em>",
  "FLIPVIEW_BTN_TOOLTIP": "Przenieś ten widok do: {0}",
  "CURRENT_THEME": "Aktualny motyw",
  "USE_THEME_SCROLLBARS": "Użyj pasków przewijania z motywu",
  "FONT_SIZE": "Rozmiar czcionki",
  "FONT_FAMILY": "Rodzina czcionek",
  "THEMES_SETTINGS": "Ustawienia motywów",
  "THEMES_ERROR": "Błąd motywów",
  "THEMES_ERROR_CANNOT_APPLY": "Nie można zastosować motywu z powodu błędu.",
  "BUTTON_NEW_RULE": "Nowa reguła",
  "INSTALL": "Zainstaluj",
  "APPLY": "Zastosować",
  "UPDATE": "Aktualizuj",
  "REMOVE": "Usuń",
  "DISABLE": "Wyłącz",
  "ENABLE": "Włącz",
  "OVERWRITE": "Nadpisz",
  "CANT_DROP_ZIP": "Upuszczanie plików ZIP będzie obsługiwane wkrótce...",
  "CANT_REMOVE_DEV": "Rozszerzenia w folderze \"dev\" muszą być usunięte ręcznie.",
  "CANT_UPDATE": "Aktualizacja nie jest kompatybilna z tą wersją {APP_NAME}.",
  "CANT_UPDATE_DEV": "Rozszerzenia w folderze \"dev\" nie mogą być automatycznie zaktualizowane.",
  "INSTALL_EXTENSION_TITLE": "Zainstaluj rozszerzenie",
  "UPDATE_EXTENSION_TITLE": "Zaktualizuj rozszerzenie",
  "INSTALL_EXTENSION_LABEL": "Adres URL rozszerzenia",
  "INSTALL_EXTENSION_HINT": "Adres URL pliku zip z rozszerzeniem lub adres repozytorium na GitHub",
  "INSTALLING_FROM": "Instaluję rozszerzenie z {0}…",
  "INSTALL_SUCCEEDED": "Instalacja zakończona!",
  "INSTALL_FAILED": "Instalacja nie powiodła się.",
  "CANCELING_INSTALL": "Anulowanie…",
  "CANCELING_HUNG": "Anulowanie instalacji trwa zbyt długo. Możliwe, że wystąpił błąd wewnętrzny.",
  "INSTALL_CANCELED": "Instalacja anulowana.",
  "VIEW_COMPLETE_DESCRIPTION": "Pokaż cały opis",
  "VIEW_TRUNCATED_DESCRIPTION": "Pokaż skrócony opis",
  "SORT_EXTENSION_METHOD": "Sortuj rozszerzenia według liczby pobrań lub daty publikacji",
  "INVALID_ZIP_FILE": "Pobrany plik nie jest poprawnym plikiem zip.",
  "MISSING_PACKAGE_JSON": "Pakiet nie zawiera pliku package.json.",
  "INVALID_PACKAGE_JSON": "Plik package.json nie jest poprawny (wystąpił błąd: {0}).",
  "MISSING_PACKAGE_NAME": "Plik package.json nie zawiera nazwy pakietu.",
  "BAD_PACKAGE_NAME": "{0} jest niepoprawną nazwą pakietu.",
  "MISSING_PACKAGE_VERSION": "Plik package.json nie zawiera wersji pakietu.",
  "INVALID_VERSION_NUMBER": "Numer wersji pakietu ({0}) jest niepoprawny.",
  "INVALID_BRACKETS_VERSION": "Ciąg kompatybilności z {APP_NAME} ({0}) jest nieprawidłowy.",
  "DISALLOWED_WORDS": "Słowa ({1}) są niedozwolone w polu {0}.",
  "NPM_INSTALL_FAILED": "Nie udało się wykonać polecenia npm install: {0}",
  "API_NOT_COMPATIBLE": "Rozszerzenie nie jest kompatybilne z tą wersją {APP_NAME}. Jest zainstalowane w folderze z nieaktywnymi rozszerzeniami.",
  "MISSING_MAIN": "Pakiet nie zawiera pliku main.js.",
  "EXTENSION_ALREADY_INSTALLED": "Zainstalowanie tego rozszerzenia nadpisze to, które zainstalowano poprzednio. Czy nadpisać starsze rozszerzenie?",
  "EXTENSION_SAME_VERSION": "To rozszerzenie jest w tej samej wersji, co obecnie zainstalowane. Czy nadpisać zainstalowane rozszerzenie?",
  "EXTENSION_OLDER_VERSION": "To rozszerzenie jest w wersji {0}, czyli jest starsze niż obecnie zainstalowane ({1}). Czy nadpisać zainstalowane rozszerzenie?",
  "DOWNLOAD_ID_IN_USE": "Błąd wewnętrzny: taki plik już istnieje.",
  "NO_SERVER_RESPONSE": "Nie można połączyć z serwerem.",
  "BAD_HTTP_STATUS": "Nie znaleziono pliku na serwerze (HTTP {0}).",
  "CANNOT_WRITE_TEMP": "Nie można zapisać pobranego pliku w folderze tymczasowym.",
  "ERROR_LOADING": "Rozszerzenie napotkało błąd podczas uruchamiania.",
  "MALFORMED_URL": "Niepoprawny adres URL. Sprawdź czy został wpisany prawidłowo.",
  "UNSUPPORTED_PROTOCOL": "Adres URL musi zaczynać się od http lub https.",
  "UNKNOWN_ERROR": "Nieznany błąd wewnętrzny.",
  "EXTENSION_VERIFIED_PUBLISHER": "Ten wydawca zweryfikował własność {0}",
  "EXTENSION_VERIFIED_SORT": "Zweryfikowano",
  "EXTENSION_STAR": "Gwiazda",
  "EXTENSION_STAR_SORT": "Ocena w skali gwiazdkowej",
  "EXTENSION_MANAGER_TITLE": "Menedżer rozszerzeń",
  "EXTENSION_MANAGER_ERROR_LOAD": "Nie udało się dostać do rejestru rozszerzeń. Spróbuj ponownie później.",
  "EXTENSION_UPDATE_RESTART_TITLE": "Uruchom ponownie, aby zaktualizować",
  "EXTENSION_UPDATE_RESTART_MESSAGE": "Aby załadować zaktualizowane rozszerzenia, zamknij wszystkie działające wystąpienia aplikacji {APP_NAME} i uruchom ją ponownie.",
  "INSTALL_EXTENSION_DRAG": "Przenieś plik .zip lub",
  "INSTALL_EXTENSION_DROP": "Przenieś plik .zip aby zainstalować",
  "INSTALL_EXTENSION_DROP_ERROR": "Instalacja/aktualizacja przerwana z powodu błędów:",
  "INSTALL_FROM_URL": "zainstaluj z adresu URL…",
  "INSTALL_EXTENSION_VALIDATING": "Sprawdzanie…",
  "EXTENSION_AUTHOR": "Autor",
  "EXTENSION_DATE": "Data",
  "EXTENSION_INCOMPATIBLE_NEWER": "To rozszerzenie wymaga nowszej wersji {APP_NAME}.",
  "EXTENSION_INCOMPATIBLE_OLDER": "To rozszerzenie działa tylko ze starszymi wersjami {APP_NAME}.",
  "EXTENSION_DEFAULT_FEATURE_PRESENT": "Możesz nie potrzebować tego rozszerzenia. {APP_NAME} ma już tę funkcję.",
  "EXTENSION_LATEST_INCOMPATIBLE_NEWER": "Wersja {0} tego rozszerzenia wymaga nowszej wersji {APP_NAME}, ale możesz zainstalować starszą wersję {1}.",
  "EXTENSION_LATEST_INCOMPATIBLE_OLDER": "Wersja {0} tego rozszerzenia wymaga starszej wersji {APP_NAME}, ale możesz zainstalować starszą wersję {1}.",
  "EXTENSION_NO_DESCRIPTION": "Brak opisu",
  "EXTENSION_MORE_INFO": "Więcej informacji…",
  "EXTENSION_ERROR": "Błąd rozszerzenia",
  "EXTENSION_KEYWORDS": "Słowa kluczowe",
  "EXTENSION_TRANSLATED_USER_LANG": "Przetłumaczono na {0} języków, w tym twój",
  "EXTENSION_TRANSLATED_GENERAL": "Przetłumaczono na {0} języków",
  "EXTENSION_TRANSLATED_LANGS": "To rozszerzenie zostało przetłumaczone na języki: {0}",
  "EXTENSION_INSTALLED": "Zainstalowane",
  "EXTENSION_UPDATE_INSTALLED": "Aktualizacja rozszerzenia została pobrana i będzie zainstalowana po przeładowaniu {APP_NAME}.",
  "EXTENSION_SEARCH_PLACEHOLDER": "Szukaj",
  "EXTENSION_MORE_INFO_LINK": "Więcej",
  "EXTENSION_MANAGER_CREATE_EXTENSION": "+ Utwórz rozszerzenie",
  "EXTENSION_MANAGER_CREATE_THEME": "+ Utwórz motyw",
  "BROWSE_EXTENSIONS": "Przeglądaj rozszerzenia",
  "EXTENSION_MANAGER_REMOVE": "Usuń rozszerzenie",
  "EXTENSION_MANAGER_REMOVE_ERROR": "Nie udało się usunąć rozszerzeń: {0}. {APP_NAME} zostanie zrestartowany.",
  "EXTENSION_MANAGER_UPDATE": "Zaktualizuj rozszerzenie",
  "EXTENSION_MANAGER_UPDATE_ERROR": "Nie udało się zaktualizować rozszerzeń: {0}. {APP_NAME} zostanie zrestartowany.",
  "EXTENSION_MANAGER_DISABLE": "Wyłącz rozszerzenie",
  "EXTENSION_MANAGER_DISABLE_ERROR": "Nie udało się wyłączyć rozszerzeń: {0}. {APP_NAME} zostanie zrestartowany.",
  "EXTENSION_MANAGER_THEMES_INFO": "Aby <a class=\"theme_settings\">wybrać motywy domyślne</a> lub zmodyfikować inne ustawienia motywu, <a class=\"theme_settings\">kliknij tutaj</a> .",
  "EXTENSION_MANAGER_THEMES_UNDO": "Wróć do poprzedniego motywu",
  "MARKED_FOR_REMOVAL": "Zaznaczono do usunięcia",
  "UNDO_REMOVE": "Cofnij",
  "MARKED_FOR_UPDATE": "Zaznaczono do aktualizacji",
  "UNDO_UPDATE": "Cofnij",
  "MARKED_FOR_DISABLING": "Zaznaczono do wyłączenia",
  "UNDO_DISABLE": "Cofnij",
  "CHANGE_AND_RELOAD_TITLE": "Zmień rozszerzenia",
  "CHANGE_AND_RELOAD_MESSAGE": "Aby zaktualizować, usunąć lub wyłączyć zaznaczone rozszerzenia, {APP_NAME} musi zostać zrestartowany. Zostaniesz poproszony o zapisanie zmian.",
  "REMOVE_AND_RELOAD": "Usuń rozszerzenia i zrestartuj",
  "CHANGE_AND_RELOAD": "Zmień rozszerzenia i zrestartuj",
  "UPDATE_AND_RELOAD": "Zaktualizuj rozszerzenia i zrestartuj",
  "DISABLE_AND_RELOAD": "Wyłącz rozszerzenia i zrestartuj",
  "PROCESSING_EXTENSIONS": "Przetwarzanie…",
  "EXTENSION_NOT_INSTALLED": "Nie można usunąć rozszerzenia {0}, ponieważ nie zostało zainstalowane.",
  "NO_EXTENSIONS": "Nie masz jeszcze żadnych rozszerzeń.<br>Użyj zakładki Dostępne (powyżej), aby zobaczyć listę.",
  "NO_EXTENSION_MATCHES": "Nie znaleziono pasujących rozszerzeń.",
  "REGISTRY_SANITY_CHECK_WARNING": "Uwaga: te rozszerzenia mogą pochodzić od innych autorów i mają pełne uprawnienia. Uważaj gdy instalujesz rozszerzenia z nieznanych źródeł.",
  "EXTENSIONS_INSTALLED_TITLE": "Zainstalowane",
  "EXTENSIONS_DEFAULT_TITLE": "Domyślnie",
  "EXTENSIONS_AVAILABLE_TITLE": "Dostępne",
  "EXTENSIONS_THEMES_TITLE": "Motywy",
  "EXTENSIONS_UPDATES_TITLE": "Aktualizacje",
  "EXTENSIONS_LAST_UPDATED": "Ostatnia aktualizacja",
  "EXTENSIONS_DOWNLOADS": "Ilość pobrań",
  "INLINE_EDITOR_NO_MATCHES": "Brak wyników.",
  "INLINE_EDITOR_HIDDEN_MATCHES": "Wszystkie wyniki zostały zwinięte. Rozwiń listę plików po prawej, by pokazać wyniki.",
  "CSS_QUICK_EDIT_NO_MATCHES": "Brak reguł.<br> Kliknij \"Nowa reguła\", aby ją utworzyć.",
  "CSS_QUICK_EDIT_NO_STYLESHEETS": "W twoim projekcie brakuje stylów CSS.<br>Stwórz je, by móc dodawać reguły CSS.",
  "IMAGE_VIEWER_LARGEST_ICON": "największy",
  "UNIT_PIXELS": "pikseli",
  "DEBUG_MENU": "Debuguj",
  "ERRORS": "Błędy",
  "CMD_SHOW_DEV_TOOLS": "Narzędzia programistyczne {APP_NAME}",
  "CMD_REFRESH_WINDOW": "Uruchom ponownie z rozszerzeniami",
  "CMD_LOAD_CURRENT_EXTENSION": "Załaduj projekt jako rozszerzenie",
  "CMD_RELOAD_CURRENT_EXTENSION": "Załaduj ponownie projekt jako rozszerzenie",
  "CMD_UNLOAD_CURRENT_EXTENSION": "Wyładuj projekt jako rozszerzenie",
  "CMD_RELOAD_WITHOUT_USER_EXTS": "Uruchom ponownie bez rozszerzeń",
  "CMD_NEW_BRACKETS_WINDOW": "Nowe okno",
  "CMD_LAUNCH_SCRIPT_MAC": "Zainstaluj skrót do wiersza poleceń",
  "CMD_SWITCH_LANGUAGE": "Zmień język…",
  "CMD_RUN_UNIT_TESTS": "Uruchom testy aplikacji {APP_NAME}",
  "CMD_SHOW_PERF_DATA": "Pokaż informacje o wydajności",
  "CMD_ENABLE_LOGGING": "Włącz szczegółowe dzienniki",
  "CMD_ENABLE_PHNODE_INSPECTOR": "Włącz inspektora PhNode",
  "CMD_GET_PHNODE_INSPECTOR_URL": "Jak sprawdzić PhNode",
  "CMD_ENABLE_LIVE_PREVIEW_LOGS": "Dzienniki podglądu na żywo",
  "CMD_OPEN_BRACKETS_SOURCE": "Otwórz kod źródłowy {APP_NAME}",
  "CREATING_LAUNCH_SCRIPT_TITLE": "Skrót do wiersza poleceń {APP_NAME}",
  "ERROR_CREATING_LAUNCH_SCRIPT": "Błąd podczas instalacji skrótu wiersza poleceń. Przeczytaj artykuł <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting'>z propozycjami rozwiązania tego problemu.</a>.<br/><br/>Powód: {0}",
  "ERROR_CLTOOLS_RMFAILED": "Nie można usunąć istniejącego dowiązania <code>/usr/local/bin/brackets</code>.",
  "ERROR_CLTOOLS_MKDIRFAILED": "Nie można utworzyć katalogu <code>/usr/local/bin</code>.",
  "ERROR_CLTOOLS_LNFAILED": "Nie można utworzyć dowiązania <code>/usr/local/bin/brackets</code>.",
  "ERROR_CLTOOLS_SERVFAILED": "Błąd wewnętrzny.",
  "ERROR_CLTOOLS_NOTSUPPORTED": "Skrót do wiersza poleceń nie jest dostępny w tym systemie.",
  "LAUNCH_SCRIPT_CREATE_SUCCESS": "Udało się! Teraz możesz uruchamiać {APP_NAME} z wiersza poleceń: <code>brackets plik.txt</code> aby otworzyć plik lub <code>brackets folder</code> aby zmienić projekt. <br/><br/><a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments'>Przeczytaj więcej</a> na temat używania {APP_NAME} w wierszu poleceń.",
  "ERROR_LOADING_EXTENSION": "Błąd ładowania rozszerzenia",
  "ERROR_NO_EXTENSION_PACKAGE": "Nie wykryto pliku <code>package.json</code> w bieżącym projekcie. Czy bieżący projekt jest prawidłowym rozszerzeniem aplikacji {APP_NAME}?</br> Zobacz <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>ten link</a> , aby uzyskać więcej informacji.",
  "ERROR_INVALID_EXTENSION_PACKAGE": "plik <code>package.json</code> ma nieprawidłowy format JSON.</br> Zobacz <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>ten link</a> , aby uzyskać więcej informacji.",
  "ERROR_INVALID_EXTENSION_PACKAGE_FIELDS": "Brak wymaganych pól w <code>package.json</code> : [{0}]</br> Zobacz <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>ten link</a> , aby uzyskać więcej informacji.",
  "ERROR_NODE_JS_CRASH_TITLE": "Ups! Coś poszło nie tak.",
  "ERROR_NODE_JS_CRASH_MESSAGE": "Wystąpił problem i musimy ponownie uruchomić aplikację {APP_NAME}. Nie martw się, staramy się zapisać całą Twoją pracę przed ponownym uruchomieniem. </br>(Błąd: ERROR_NODE_JS_CRASH)",
  "LANGUAGE_TITLE": "Zmień język",
  "LANGUAGE_MESSAGE": "Język:",
  "LANGUAGE_SUBMIT": "Zrestartuj {APP_NAME}",
  "LANGUAGE_CANCEL": "Anuluj",
  "LANGUAGE_SYSTEM_DEFAULT": "Domyślny systemu",
  "HEALTH_DATA_NOTIFICATION": "Ustawienia raportowania",
  "HEALTH_FIRST_POPUP_TITLE": "Raporty {APP_NAME}",
  "HEALTH_DATA_DO_TRACK": "Wysyłaj anonimowe informacje o tym, jak używam {APP_NAME}",
  "HEALTH_DATA_NOTIFICATION_MESSAGE": "Aby udoskonalić aplikację {APP_NAME}, okresowo wysyłamy do <strong>phcode.dev</strong> ograniczone, anonimowe statystyki i raporty o błędach dotyczące sposobu korzystania z aplikacji {APP_NAME}. Te informacje pomagają ustalać priorytety funkcji, znajdować błędy i wykrywać problemy z użytecznością, jednocześnie chroniąc Twoją prywatność.<br><br> Możesz zobaczyć swoje dane lub zrezygnować z ich udostępniania, wybierając opcję <strong>Pomoc &gt; Raport o</strong> stanie.<br><br>",
  "HEALTH_DATA_PREVIEW": "Raporty {APP_NAME}",
  "HEALTH_DATA_PREVIEW_INTRO": "<p>Aby udoskonalić aplikację {APP_NAME}, okresowo wysyłamy do <strong>phcode.dev</strong> ograniczone, anonimowe statystyki i raporty o błędach dotyczące sposobu korzystania z aplikacji {APP_NAME}. Te informacje pomagają ustalać priorytety funkcji, znajdować błędy i wykrywać problemy z użytecznością.</p><p> Poniżej znajduje się podgląd danych, które zostaną przesłane w następnym raporcie o stanie <em>, jeśli</em> jest włączony. (Zobacz także konsolę programisty, aby zapoznać się z dziennikami błędów oznaczonymi jako „Przechwycony błąd krytyczny”.)</p>",
  "INLINE_TIMING_EDITOR_TIME": "Czas",
  "INLINE_TIMING_EDITOR_PROGRESSION": "Postęp",
  "BEZIER_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd><kbd>←</kbd><kbd>→</kbd> Przenieś zaznaczony punkt<br><kbd class='text'>Shift</kbd> Przenieś o 10 jednostek<br><kbd class='text'>Tab</kbd> Zmień punkt",
  "STEPS_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd> Zwiększ lub zmniejsz kroki<br><kbd>←</kbd><kbd>→</kbd> 'Start' lub 'End'",
  "INLINE_TIMING_EDITOR_INVALID": "Poprzednia wartość <code>{0}</code> jest niepoprawna, więc została zamieniona na <code>{1}</code>. Dokument zostanie uaktualniony podczas pierwszej edycji.",
  "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP": "Aktualny kolor",
  "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP": "Orginalny kolor",
  "COLOR_EDITOR_RGBA_BUTTON_TIP": "Format RGBa",
  "COLOR_EDITOR_HEX_BUTTON_TIP": "Format Hex",
  "COLOR_EDITOR_HSLA_BUTTON_TIP": "Format HSLa",
  "COLOR_EDITOR_0X_BUTTON_TIP": "Format Hex (0x)",
  "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR": "{0} (użyto {1} raz)",
  "COLOR_EDITOR_USED_COLOR_TIP_PLURAL": "{0} (użyto {1} razy)",
  "CMD_JUMPTO_DEFINITION": "Przejdź do definicji",
  "CMD_SHOW_PARAMETER_HINT": "Pokaż podpowiedź (parametr)",
  "NO_ARGUMENTS": "<brak parametrów>",
  "DETECTED_EXCLUSION_TITLE": "Błąd podczas sprawdzania poprawności kodu JavaScript",
  "DETECTED_EXCLUSION_INFO": "Aplikacja {APP_NAME} napotkała problemy podczas przetwarzania <span class='dialog-filename'>{0}</span> .<br><br> Ten plik nie będzie już przetwarzany w celu uzyskania wskazówek do kodu, skoku do definicji lub szybkiej edycji. Aby ponownie włączyć ten plik, otwórz <code>.phcode.json</code> w swoim projekcie i edytuj <code>jscodehints.detectedExclusions</code> .<br><br> Prawdopodobnie jest to błąd aplikacji {APP_NAME}. Jeśli możesz dostarczyć kopię tego pliku, <a href='https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue'>zgłoś błąd</a> za pomocą łącza do pliku wymienionego tutaj.",
  "CMD_REFACTOR": "Refaktoryzacja",
  "CMD_EXTRACTTO_VARIABLE": "Wyodrębnij do zmiennej",
  "CMD_EXTRACTTO_FUNCTION": "Wyodrębnij do funkcji",
  "ERROR_TERN_FAILED": "Nie można uzyskać danych z Tern",
  "ERROR_EXTRACTTO_VARIABLE_NOT_VALID": "Wybór nie tworzy wyrażenia",
  "ERROR_EXTRACTTO_FUNCTION_NOT_VALID": "Wybrany blok powinien reprezentować zbiór instrukcji lub wyrażenie",
  "ERROR_EXTRACTTO_VARIABLE_MULTICURSORS": "Wyodrębnij do zmiennej nie działa w multikursorach",
  "ERROR_EXTRACTTO_FUNCTION_MULTICURSORS": "Wyodrębnij do funkcji nie działa w multikursorach",
  "EXTRACTTO_FUNCTION_SELECT_SCOPE": "Wybierz zakres docelowy",
  "EXTRACTTO_VARIABLE_SELECT_EXPRESSION": "Wybierz wyrażenie",
  "CMD_REFACTORING_RENAME": "Zmień nazwę",
  "CMD_REFACTORING_TRY_CATCH": "Zapakuj w Try Catch",
  "CMD_REFACTORING_CONDITION": "Owiń w stanie!",
  "CMD_REFACTORING_GETTERS_SETTERS": "Twórz Gettery/Settery",
  "CMD_REFACTORING_ARROW_FUNCTION": "Konwertuj na funkcję strzałki",
  "DESCRIPTION_CODE_REFACTORING": "Włącz/wyłącz refaktoryzację kodu JavaScript",
  "ERROR_TRY_CATCH": "Wybierz prawidłowy kod, aby umieścić go w bloku Try-catch",
  "ERROR_WRAP_IN_CONDITION": "Wybierz poprawny kod, aby umieścić go w bloku Warunku",
  "ERROR_ARROW_FUNCTION": "Umieść kursor wewnątrz wyrażenia funkcji",
  "ERROR_GETTERS_SETTERS": "Umieść kursor na elemencie wyrażenia obiektowego",
  "ERROR_RENAME_MULTICURSOR": "Nie można zmienić nazwy podczas korzystania z wielu kursorów",
  "ERROR_RENAME_QUICKEDIT": "Nie można zmienić nazwy tego identyfikatora, ponieważ odwołuje się do niego w innym miejscu poza tą funkcją",
  "ERROR_RENAME_GENERAL": "Nie można zmienić nazwy zaznaczonego tekstu",
  "JSHINT_NAME": "JSHint",
  "CMD_ENABLE_QUICK_VIEW": "Szybki Podgląd po najechaniu na element",
  "CMD_ENABLE_SELECTION_VIEW": "Widok wyboru",
  "TOOLTIP_CLICK_TO_EDIT_COLOR": "Kliknij tutaj, aby edytować kolor",
  "CMD_TOGGLE_RECENT_PROJECTS": "Ostatnie projekty",
  "REMOVE_FROM_RECENT_PROJECTS": "Usuń z ostatnich projektów",
  "DOCS_MORE_LINK": "Czytaj więcej",
  "COLLAPSE_ALL": "Zwiń wszystko",
  "EXPAND_ALL": "Rozwiń wszystko",
  "COLLAPSE_CURRENT": "Zwiń element",
  "EXPAND_CURRENT": "Rozwiń element",
  "RECENT_FILES_DLG_HEADER": "Ostatnio otwierane pliki",
  "RECENT_FILES_DLG_CLEAR_BUTTON_LABEL": "Wyczyść",
  "RECENT_FILES_DLG_CLEAR_BUTTON_TITLE": "Wyczyść pliki (oprócz aktualnie otwartych)",
  "RECOVER_UNSAVED_FILES_TITLE": "Odzyskać niezapisane pliki?",
  "RECOVER_UNSAVED_FILES_MESSAGE": "Przywrócić niezapisane pliki z poprzedniej sesji?",
  "RECOVER_UNSAVED_FILES_RESTORE": "Przywrócić",
  "DISCARD_UNSAVED_FILES_RESTORE": "Wyrzucać",
  "DESCRIPTION_CLOSE_BRACKETS": "true, by automatycznie zamykać nawiasy okrągłe, kwadratowe i klamrowe",
  "DESCRIPTION_CLOSE_OTHERS_ABOVE": "false, by usunąć pozycję \"Zamknij pliki powyżej\" z menu kontekstowego plików w obszarze roboczym",
  "DESCRIPTION_CLOSE_OTHERS_BELOW": "false, by usunąć pozycję \"Zamknij pliki poniżej\" z menu kontekstowego plików w obszarze roboczym",
  "DESCRIPTION_CLOSE_OTHERS": "false, by usunąć pozycję \"Zamknij inne\" z menu kontekstowego plików w obszarze roboczym",
  "DESCRIPTION_CLOSE_TAGS": "Opcje automatycznego zamykania tagów",
  "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS": "lista tagów, które nie powinny być automatycznie zamykane",
  "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING": "zamykaj znaczniki po wpisaniu \">\" otwierającego tagu",
  "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING": "zamykaj znaczniki po wpisaniu \"/\" zamykającego tagu",
  "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS": "lista tagów, które wstawiają pustą linie (po wpisaniu otwierającego znacznika)",
  "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD": "true, by generować znaczniki zwijania kodu na podstawie poziomów wcięć",
  "DESCRIPTION_CODE_FOLDING_ENABLED": "true, by włączyć zwijanie kodu",
  "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER": "true, by wyświetlać znaczniki zwijania kodu po najechaniu kursora myszy na boczny panel",
  "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL": "Określa do ilu poziomów głębokości zostanie zastosowana funkcja \"Zwiń wszystko\"",
  "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE": "Minimalna liczba linii wymagana do pojawienia się znacznika zwijania kodu",
  "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES": "true, by zapamiętać zwinięte fragmenty kodu, gdy plik lub projekt zostanie zamknięty bądź ponownie otwarty",
  "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE": "true, by zezwolić na zwijanie zaznaczonego fragmentu kodu",
  "DESCRIPTION_DISABLED_DEFAULT_EXTENSIONS": "Lista rozszerzeń, które są domyślnie wyłączone",
  "DESCRIPTION_ATTR_HINTS": "Włącz/wyłącz podpowiedzi do atrybutów HTML",
  "DESCRIPTION_CSS_PROP_HINTS": "Włącz/wyłącz podpowiedzi do właściwości CSS/LESS/SCSS",
  "DESCRIPTION_JS_HINTS": "Włącz/wyłącz podpowiedzi do kodu JavaScript",
  "DESCRIPTION_JS_HINTS_TYPE_DETAILS": "Włącz/wyłącz wyświetlanie typów danych w podpowiedziach do kodu JavaScript",
  "DESCRIPTION_PREF_HINTS": "Włącz/wyłącz podpowiedzi w pliku z ustawieniami",
  "DESCRIPTION_SPECIAL_CHAR_HINTS": "Włącz/wyłącz podpowiedzi dla encji HTML",
  "DESCRIPTION_SVG_HINTS": "Włącz/wyłącz podpowiedzi do kodu SVG",
  "DESCRIPTION_HTML_TAG_HINTS": "Włącz/wyłącz podpowiedzi do tagów HTML",
  "DESCRIPTION_URL_CODE_HINTS": "Włącz/wyłącz podpowiedzi URL w kodzie HTML i CSS/LESS/SCSS",
  "DESCRIPTION_DRAG_DROP_TEXT": "Włącz/wyłącz funkcjonalność przeciągnij i upuść",
  "DESCRIPTION_HEALTH_DATA_TRACKING": "Włącz raportowanie o stanie programu",
  "DESCRIPTION_HIGHLIGHT_MATCHES": "Zezwól na automatyczne podświetlanie dopasowanych wyrazów w dokumencie",
  "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN": "Podświetl wszystkie wyrazy dopasowane według słowa z aktualnej pozycji kursora (bez zaznaczania)",
  "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY": "Podświetl, tylko gdy zaznaczony jest cały wyraz",
  "DESCRIPTION_INSERT_HINT_ON_TAB": "true, by wstawić podpowiedź do kodu po naciśnięciu klawisza tab",
  "DESCRIPTION_NO_HINTS_ON_DOT": "true, by nie pokazywać automatycznie podpowiedzi do kodu JS po wpisaniu znaku \".\"",
  "DESCRIPTION_JSHINT_OPTIONS": "Obiekt z domyślnymi opcjami dla JSHint. Proszę zobaczyć następujący adres URL dla wszystkich dostępnych opcji JSHint: https://jshint.com/docs/options/",
  "DESCRIPTION_LANGUAGE": "Ustawienia języka",
  "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS": "Dodatkowe mapowanie nazwy rozszerzenia z nazwą języka",
  "DESCRIPTION_LANGUAGE_FILE_NAMES": "Dodatkowe mapowanie nazwy pliku z nazwą języka",
  "DESCRIPTION_LINEWISE_COPY_CUT": "Kopiuj lub wytnij całą linie, gdy nie został zaznaczony żaden fragment tekstu",
  "DESCRIPTION_INPUT_STYLE": "Wybiera sposób, w jaki CodeMirror obsługuje wejście oraz aktywność. Wartością może być textarea (domyślnie) lub contenteditable, która jest lepsza dla czytników ekranu (niestabilne)",
  "DESCRIPTION_LINTING_ENABLED": "true, by włączyć inspekcje kodu (Code Inspection)",
  "DESCRIPTION_ASYNC_TIMEOUT": "Limit czasu (w milisekundach), którego nie mogą przekroczyć asynchroniczne lintery",
  "DESCRIPTION_LINTING_PREFER": "Lista linterów do uruchomienia w pierwszej kolejności",
  "DESCRIPTION_LIVE_DEV_MULTIBROWSER": "true, by włączyć eksperymentalny podgląd na żywo",
  "DESCRIPTION_USE_PREFERED_ONLY": "true, by uruchomić tylko te moduły, które zostały określone w linting.prefer",
  "DESCRIPTION_MAX_CODE_HINTS": "Maksymalna liczba pozycji w liście podpowiedzi do kodu",
  "DESCRIPTION_PATH": "Ścieżka do ustawień",
  "DESCRIPTION_PROXY": "Adres URL serwera proxy używanego do instalacji rozszerzeń",
  "DESCRIPTION_SCROLL_PAST_END": "true, by włączyć możliwość przewijania poza koniec dokumentu",
  "DESCRIPTION_SHOW_CODE_HINTS": "false, by wyłączyć wszystkie podpowiedzi do kodu",
  "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING": "Wyświetlaj migający kursor podczas zaznaczenia tekstu",
  "DESCRIPTION_SHOW_LINE_NUMBERS": "true, by wyświetlać numery linii obok kodu",
  "DESCRIPTION_SMART_INDENT": "Automatycznie dodaj wcięcie, gdy zostanie utworzona nowa linia",
  "DESCRIPTION_SOFT_TABS": "false, by wyłączyć soft tabs",
  "DESCRIPTION_SORT_DIRECTORIES_FIRST": "true, by sortować foldery w drzewie projektu",
  "DESCRIPTION_SPACE_UNITS": "Liczba spacji lub tabulatorów do sformatowania wcięcia w kodzie",
  "DESCRIPTION_STATIC_SERVER_PORT": "Numer portu, który powinien być używany przez wbudowany serwer podczas podglądu na żywo",
  "DESCRIPTION_STYLE_ACTIVE_LINE": "true, by podświetlać tło dla aktualnie edytowanej linii",
  "DESCRIPTION_TAB_SIZE": "Określ rozmiar tabulatora (według liczby spacji)",
  "DESCRIPTION_USE_TAB_CHAR": "true, by używać tabulatorów zamiast spacji",
  "DESCRIPTION_UPPERCASE_COLORS": "true, by generować kolory w formacie szesnastkowym (hex) używając wielkich liter w liniowym edytorze kolorów",
  "DESCRIPTION_WORD_WRAP": "Zawijaj wiersze",
  "DESCRIPTION_SEARCH_AUTOHIDE": "Zamknij wyszukiwanie, gdy tylko edytor się skupi",
  "DESCRIPTION_DETECTED_EXCLUSIONS": "Lista plików, które zostały wykryte jako problematyczne dla modułu Tern",
  "DESCRIPTION_INFERENCE_TIMEOUT": "Limit czasu, którego moduł Tern nie może przekroczyć podczas analizy plików",
  "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR": "true, by wyświetlać błędy aplikacji w pasku stanu",
  "DESCRIPTION_QUICK_VIEW_ENABLED": "true, by włączyć Quick View",
  "DESCRIPTION_SELECTION_VIEW_ENABLED": "true aby włączyć widok wyboru",
  "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW": "true, by wyświetlać podgląd dla grafiki, która nie posiada rozszerzenia w adresie URL",
  "DESCRIPTION_NUMBER_QUICK_VIEW": "true , aby wyświetlić Szybki podgląd po najechaniu kursorem na liczby w edytorze",
  "DESCRIPTION_THEME": "Wybierz motyw dla {APP_NAME}",
  "DESCRIPTION_USE_THEME_SCROLLBARS": "true, by zezwolić na modyfikacje pasków przewijania przez motyw",
  "DESCRIPTION_LINTING_COLLAPSED": "true, by zwijać (ukrywać) panel inspekcji kodu",
  "DESCRIPTION_FONT_FAMILY": "Rodzaj czcionki",
  "DESCRIPTION_DESKTOP_ZOOM_SCALE": "Wybierz współczynnik skali powiększenia w zakresie od 0,1 (dla bardziej kompaktowego widoku) do 2 (dla większego, bardziej powiększonego widoku). Dostępne tylko w aplikacjach komputerowych",
  "DESCRIPTION_FONT_SIZE": "Rozmiar czcionki, np. 13px",
  "DESCRIPTION_FIND_IN_FILES_NODE": "true, by włączyć wyszukiwanie oparte na NodeJS",
  "DESCRIPTION_FIND_IN_FILES_INSTANT": "true, by zezwolić na natychmiastowe wyszukiwanie",
  "DESCRIPTION_FONT_SMOOTHING": "Tylko dla MacOS: \"subpixel-antialiased\" włącz sub-pixel antialiasing lub \"antialiased\" dla antyaliasingu skali szarości",
  "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW": "false, by wyłączyć otwieranie pliku z ustawieniami w podzielonym widoku",
  "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE": "false, by wyłączyć otwieranie pliku z ustawieniami użytkownika w lewym/górnym panelu",
  "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED": "true, by automatycznie włączyć tryb \"bez podziału\", gdy ostatni plik w panelu zostanie zamknięty (za pomocą przyciku w nagłówku panelu)",
  "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS": "Określ, kiedy powinny być wyświetlane przyciski zamknięcia i odwrócenia widoku w nagłówku panelu",
  "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT": "/*\n * Jest to plik tylko do odczytu z obsługiwanymi preferencjami\n * przez aplikację {APP_NAME}.\n * Użyj tego pliku jako odniesienia do modyfikacji swoich preferencji\n * plik „phcode.json” otwarty w drugim panelu.\n * Aby uzyskać więcej informacji na temat korzystania z preferencji w środku\n * {APP_NAME}, zobacz stronę internetową https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences\n */",
  "DEFAULT_PREFERENCES_JSON_DEFAULT": "Domyślnie",
  "DESCRIPTION_PURE_CODING_SURFACE": "true, by włączyć tryb \"bez przeszkadzania\" i ukryć wszystkie inne elementy UI w {APP_NAME}",
  "DESCRIPTION_INDENT_LINE_COMMENT": "true, by włączyć wcięcia w komentarzach",
  "DESCRIPTION_RECENT_FILES_NAV": "Włącz/wyłącz nawigację w ostatnich plikach",
  "DESCRIPTION_LIVEDEV_WEBSOCKET_PORT": "Port, na którym będzie uruchomiony serwer WebSocket podczas podglądu na żywo",
  "DESCRIPTION_LIVE_DEV_HIGHLIGHT_SETTINGS": "Ustawienia podświetlenia podglądu na żywo",
  "DESCRIPTION_LIVEDEV_ENABLE_REVERSE_INSPECT": "false, aby wyłączyć odwrotną inspekcję podglądu na żywo",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW": "Nie ma nic do podglądu!",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW_DETAILS": "Wybierz plik HTML do podglądu",
  "DESCRIPTION_LIVEDEV_PREVIEW_RESTRICTED": "Podgląd niedostępny!",
  "DESCRIPTION_LIVEDEV_PREVIEW_RESTRICTED_DETAILS": "Ten plik HTML nie jest częścią bieżącego projektu. Ze względów bezpieczeństwa podgląd na żywo można oglądać wyłącznie w przypadku plików projektu. Aby wyświetlić podgląd tego pliku, otwórz folder zawierający go jako oddzielny projekt.",
  "DESCRIPTION_LIVEDEV_MAIN_HEADING": "O o!<br> Twoja bieżąca przeglądarka nie obsługuje podglądu na żywo.",
  "DESCRIPTION_LIVEDEV_MAIN_SPAN": "Uzyskaj najlepszą jakość podglądu na żywo, pobierając nasze natywne aplikacje dla systemów Windows, Mac i Linux ze strony <a href=\"https://phcode.io\" style=\"color: white\">phcode.io</a> .<br>",
  "DESCRIPTION_LIVEDEV_SECURITY_POPOUT_MESSAGE": "Za chwilę otworzysz plik do podglądu na żywo. Kontynuuj tylko wtedy, gdy ufasz źródłu tego projektu. Kliknij „Zaufaj projektowi”, aby kontynuować, lub zamknij to okno, jeśli nie ufasz źródłu.",
  "DESCRIPTION_LIVEDEV_SECURITY_TRUST_MESSAGE": "Za chwilę otworzysz plik do podglądu na żywo. Kontynuuj, klikając „Zaufaj projektowi” tylko wtedy, gdy ufasz źródłu tego projektu!",
  "CONFIRM_EXTERNAL_BROWSER_TITLE": "Wyskakujące okienka zablokowane",
  "CONFIRM_EXTERNAL_BROWSER_MESSAGE": "Czy chcesz zezwolić stronie podglądu na żywo na otwarcie tego adresu URL: {0}?",
  "TRUST_PROJECT": "Podgląd zaufania i wykonania — {0}",
  "TRUST_AUTHORS": "Czy ufasz autorom tego projektu?",
  "DOWNLOAD_FAILED": "Pobieranie nie udane.",
  "DOWNLOAD_COMPLETE": "Pobieranie zakończone!",
  "UPDATE_SUCCESSFUL": "Aktualizacja przeprowadzona pomyślnie!",
  "UPDATE_FAILED": "Aktualizacja nieudana!",
  "VALIDATION_FAILED": "Weryfikacja nie powiodła się!",
  "INITIALISATION_FAILED": "Inicjalizacja nieudana!",
  "CLEANUP_FAILED": "Czyszczenie nie powiodło się!",
  "WARNING_TYPE": "Ostrzeżenie!",
  "CLICK_RESTART_TO_UPDATE": "Kliknij Uruchom ponownie, aby zaktualizować wsporniki.",
  "UPDATE_ON_NEXT_LAUNCH": "Aktualizacja zostanie zastosowana przy ponownym uruchomieniu.",
  "GO_TO_SITE": "Przejdź do <a href = \"http://brackets.io/\">brackets.io</a> , aby spróbować ponownie.",
  "INTERNET_UNAVAILABLE": "Brak połączenia internetowego.",
  "UPDATEDIR_READ_FAILED": "Nie można odczytać katalogu aktualizacji.",
  "UPDATEDIR_CLEAN_FAILED": "Nie udało się wyczyścić katalogu aktualizacji.",
  "INITIAL_DOWNLOAD": "Pobieranie aktualizacji...",
  "RETRY_DOWNLOAD": "Pobieranie nie udane. Ponowna próba... Próba",
  "VALIDATING_INSTALLER": "Pobieranie zakończone! Sprawdzam Instalatora...",
  "CHECKSUM_DID_NOT_MATCH": "Suma kontrolna się nie zgadza.",
  "INSTALLER_NOT_FOUND": "Nie znaleziono instalatora.",
  "DOWNLOAD_ERROR": "Wystąpił błąd podczas pobierania.",
  "NETWORK_SLOW_OR_DISCONNECTED": "Sieć jest rozłączona lub zbyt wolna.",
  "RESTART_BUTTON": "Uruchom ponownie",
  "LATER_BUTTON": "Później",
  "DESCRIPTION_AUTO_UPDATE": "Włącz/wyłącz automatyczną aktualizację nawiasów",
  "AUTOUPDATE_ERROR": "Błąd!",
  "AUTOUPDATE_IN_PROGRESS": "Aktualizacja jest już w toku.",
  "NUMBER_WITH_PERCENTAGE": "{0}%",
  "CMD_FIND_RELATED_FILES": "Znajdź powiązane pliki",
  "PHP_VERSION_INVALID": "Błąd podczas analizowania wersji PHP. Sprawdź dane wyjściowe polecenia „php –version”.",
  "PHP_UNSUPPORTED_VERSION": "Zainstaluj środowisko wykonawcze PHP7, aby włączyć narzędzia związane z PHP, takie jak wskazówki do kodu, wskazówki dotyczące parametrów, skok do definicji i inne. Znaleziona wersja: {0}",
  "PHP_EXECUTABLE_NOT_FOUND": "Nie znaleziono środowiska wykonawczego PHP. Zainstaluj środowisko wykonawcze PHP7 i odpowiednio zaktualizuj „executablePath” w Preferencjach PHP. Umożliwia to narzędzia związane z PHP, takie jak wskazówki do kodu, wskazówki dotyczące parametrów, skok do definicji i inne.",
  "PHP_PROCESS_SPAWN_ERROR": "Wystąpił kod błędu {0} podczas uruchamiania procesu PHP.",
  "PHP_SERVER_ERROR_TITLE": "Błąd",
  "PHP_SERVER_MEMORY_LIMIT_INVALID": "Podany limit pamięci jest nieprawidłowy. Przejrzyj preferencje PHP, aby ustawić poprawną wartość.",
  "DESCRIPTION_PHP_TOOLING_CONFIGURATION": "Domyślne ustawienia konfiguracji narzędzi PHP",
  "OPEN_PREFERENNCES": "Otwórz preferencje",
  "LANGUAGE_TOOLS_PREFERENCES": "Preferencje narzędzi językowych",
  "FIND_ALL_REFERENCES": "Znajdź wszystkie referencje",
  "REFERENCES_IN_FILES": "Bibliografia",
  "REFERENCE_IN_FILES": "odniesienie",
  "REFERENCES_NO_RESULTS": "Brak dostępnych referencji dla bieżącej pozycji kursora",
  "CMD_FIND_DOCUMENT_SYMBOLS": "Znajdź symbole dokumentów",
  "CMD_FIND_PROJECT_SYMBOLS": "Znajdź symbole projektu",
  "REMOTE_DEBUGGING_ENABLED": "Zdalne debugowanie włączone na hoście lokalnym:",
  "REMOTE_DEBUGGING_PORT_INVALID": "Nie można włączyć zdalnego debugowania na porcie {0}. Numery portów powinny wynosić od {1} do {2}.",
  "DESCRIPTION_EXTERNAL_APPLICATION_ASSOCIATE": "Mapowania rozszerzeń plików do aplikacji zewnętrznych. Składnia: \"<file_type>\": \"<default|applicationName|ApplicationPath>\", Użyj \"default\" do otwierania plików w domyślnej aplikacji systemowej dla danego typu pliku.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_TITLE": "Otwórz pliki graficzne w zewnętrznych edytorach.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_MSG": "Twój bieżący folder zawiera typy plików graficznych, które nie są obsługiwane przez aplikację {APP_NAME}.<br/> Możesz teraz powiązać określone typy plików z zewnętrznymi edytorami. Po skojarzeniu możesz otwierać pliki graficzne, takie jak .xd, .psd, .jpg, .png, .ai, .svg w ich domyślnych aplikacjach, klikając dwukrotnie pliki w drzewie plików.<br/><br/> Kliknij przycisk „OK”, aby powiązać typy plików graficznych z ich odpowiednimi domyślnymi aplikacjami.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_CNF_MSG": "Następujące typy plików zostały pomyślnie skojarzone z aplikacjami domyślnymi.<br/> {0} Masz możliwość zmiany preferencji dotyczących usuwania/dodawania nowych skojarzeń typów plików w phcode.json, przechodząc do menu „Debuguj-&gt;Otwórz plik preferencji”.",
  "UNSUPPORTED_BROWSER_TITLE": "Przeglądarka nie jest obsługiwana",
  "UNSUPPORTED_BROWSER_MESSAGE": "Prosimy o korzystanie z nowoczesnej przeglądarki (wydanej w ciągu ostatnich 3 lat).",
  "UNSUPPORTED_BROWSER_MOBILE_TITLE": "Przeglądarki mobilne nie są obsługiwane",
  "UNSUPPORTED_BROWSER_MOBILE": "Przeglądarki mobilne i tablety nie są obecnie w pełni obsługiwane. Możesz zamknąć to okno dialogowe, ale niektóre funkcje oprogramowania Phoenix nie będą działać w tej przeglądarce.<br/><br/> Pracujemy nad tworzeniem natywnych aplikacji na iOS i Androida. <a href=\"https://github.com/phcode-dev/phoenix/discussions/1046\" target=\"_blank\">Dołącz do dyskusji tutaj!</a>",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER_TITLE": "Dostęp do folderu lokalnego nieobsługiwany przez przeglądarkę",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER": "Przepraszamy, wygląda na to, że Twoja bieżąca przeglądarka nie obsługuje otwierania folderów lokalnych. W przypadku tej funkcji zalecamy korzystanie z przeglądarki Chrome, Edge lub Opera.<br/><br/> Alternatywnie, pracujemy nad tworzeniem aplikacji natywnych dla systemów Windows, Mac, Linux, iOS i Android, aby zapewnić pełne wsparcie. <a href=\"https://github.com/phcode-dev/phoenix/discussions/1047\" target=\"_blank\">Bądź na bieżąco z aktualizacjami!</a>",
  "ATTENTION_SAFARI_USERS": "Uwaga użytkownicy Safari",
  "ATTENTION_SAFARI_USERS_MESSAGE": "<span>Safari automatycznie usuwa dane witryny, jeśli nie zostanie ona ponownie odwiedzona w ciągu 7 dni. Aplikacja {APP_NAME} korzysta z pamięci przeglądarki, aby zapisywać Twoje projekty, które mogą zostać usunięte ze względu na te zasady.<br/><br/> Zaleca się <strong>pobranie aplikacji komputerowej dla systemu macOS</strong> ze strony <a href='https://phcode.io' target='_blank' style='color: white'>https://phcode.io</a></span>",
  "CANNOT_PUBLISH_LARGE_PROJECT": "Nie można opublikować dużego projektu",
  "CANNOT_PUBLISH_LARGE_PROJECT_MESSAGE": "Phoenix jest wciąż w fazie eksperymentalnej alfa. Nie włączyliśmy jeszcze synchronizacji projektów zawierających ponad 500 plików.",
  "SHARE_WEBSITE": "Publikować i udostępniać witrynę?",
  "PUBLISH": "Publikować",
  "PUBLISH_CONSENT_MESSAGE": "Szybko przeglądaj zmiany i udostępniaj swoją witrynę innym. Firma Phoenix może opublikować dla Ciebie tę witrynę pod adresem {0}. Opublikowane linki będą ważne przez okres 30 dni. </br>Chcesz opublikować i udostępnić swoją witrynę?",
  "PUBLISH_SYNC_IN_PROGRESS": "Trwa synchronizacja podglądu...",
  "PUBLISH_PAGE": "Kliknij, aby opublikować i udostępnić tę witrynę",
  "PUBLISH_VIEW_PAGE": "Kliknij, aby wyświetlić opublikowaną stronę",
  "MISSING_FIELDS": "Brakujące pola",
  "PLEASE_FILL_ALL_REQUIRED": "Proszę wypełnić wszystkie wymagane pola zaznaczone na czerwono",
  "CODE_EDITOR": "Edytor kodu",
  "BUILD_THE_WEB": "Buduj sieć",
  "IMPORT_PROJECT": "Importuj projekt",
  "GITHUB_PROJECT": "Projekt GitHub",
  "NEW_PROJECT_FROM_GITHUB": "Nowy projekt z GitHub",
  "GITHUB_REPO_URL": "Adres URL repozytorium GitHub :",
  "CREATE_PROJECT": "Utwórz projekt",
  "SETTING_UP_PROJECT": "Konfiguracja projektu",
  "LOCATION": "Lokalizacja :",
  "DOWNLOADING": "Ściąganie...",
  "DOWNLOADING_FILE": "Pobieranie {0}...",
  "EXTRACTING_FILES_PROGRESS": "Rozpakowywanie {0} z {1} plików.",
  "COMPRESS_FILES_PROGRESS": "Kompresowanie {0} z {1} plików.",
  "DOWNLOAD_FAILED_MESSAGE": "Upewnij się, że adres URL pobierania jest prawidłowy. </br>NB: Ponieważ Phoenix jest w wersji alfa, prywatne repozytoria i adresy URL GitHub większe niż 25 MB są niedozwolone.",
  "PLEASE_SELECT_A_FOLDER": "Wybierz folder...",
  "UNZIP_IN_PROGRESS": "Rozpakowywanie plików...",
  "UNZIP_FAILED": "Błąd: rozpakowywanie nie powiodło się.",
  "CONFIRM_REPLACE_TITLE": "Potwierdź zastąpienie",
  "KEEP_BOTH": "Zatrzymaj oba",
  "EXPLORE": "Gry HTML",
  "BLOG": "Blog",
  "PHOENIX_DEFAULT_PROJECT": "Projekt domyślny",
  "PROJECT_NAME": "Nazwa Projektu:",
  "NEW_HTML": "Nowy projekt HTML",
  "LICENSE": "Licencja:",
  "CREDITS": "Kredyty:",
  "PREVIEW": "Zapowiedź",
  "BUILD_WEBSITE": "Zbuduj stronę internetową",
  "VIEW_MORE": "Zobacz więcej...",
  "NEW_PROJECT_NOTIFICATION": "Kliknij tę ikonę, aby utworzyć nowy projekt.</br><img src=\"styles/images/new_project.png\"><br/> <a href='#' style='float:right;'>OK</a>",
  "BEAUTIFY_CODE_NOTIFICATION": "Kliknij tutaj lub naciśnij <b>`{0}`</b> , aby upiększyć kod.</br><img src=\"styles/images/beautify.gif\"><br/> <a href='#' style='float:right;'>OK</a>",
  "DEFAULT_PROJECT_NOTIFICATION": "Kliknij tutaj, aby otworzyć<br/> <b>domyślny projekt</b> w feniksie.</br> <a href='#' style='float:right;'>ok</a>",
  "DIRECTORY_REPLACE_MESSAGE": "Wybrany folder <span class='dialog-filename'>{0}</span> nie jest pusty. Czy na pewno chcesz zastąpić zawartość folderu projektem?",
  "BUILD_WEBSITE_SECTION": "Zbuduj stronę internetową",
  "LEARN_SECTION": "Ucz się z przykładami",
  "CREATE_EXTENSION_SECTION": "Utwórz rozszerzenia i motywy aplikacji {APP_NAME}",
  "CREATE_EXTENSION": "Utwórz rozszerzenie",
  "CREATE_THEME": "Utwórz motyw",
  "WEBPAGE_HOME_PAGE": "Strona główna",
  "WEBPAGE_BLOG": "Strona bloga",
  "WEBPAGE_DASHBOARD": "Panel HTML",
  "WEBPAGE_BOOTSTRAP_EXAMPLES": "Przykłady Bootstrap",
  "PROJECTS_AT_A_GLANCE": "Twoje projekty w skrócie",
  "PROJECT_AT_GLANCE_DESCRIPTION": "Obejrzyj wideo, aby rozpocząć.",
  "PROJECT_FROM_BROWSER": "Przechowywane w Twojej przeglądarce",
  "PROJECT_FROM_BROWSER_TERSE": "Pamięć przeglądarki",
  "PROJECT_SHOW_ON_STARTUP": "Pokaż ten dialog przy uruchomieniu",
  "GUIDED_LIVE_PREVIEW": "Wprowadź zmiany w kodzie w pliku HTML, aby wyświetlić podgląd na żywo.</br> <a href='#' style='float:right;'>OK</a>",
  "GUIDED_LIVE_PREVIEW_POPOUT": "Kliknij ten przycisk, aby wyświetlić podgląd na żywo na nowej karcie.</br> <a href='#' style='float:right;'>ok</a>",
  "ENJOYING_APP": "Korzystasz z aplikacji {APP_NAME}?",
  "GITHUB_STARS_POPUP": "<div>Twoje recenzje motywują nasz mały zespół do <b>ulepszania phcode.dev</b> .<br/> Oznacz nas gwiazdką na GitHub:",
  "GITHUB_STARS_POPUP_TWITTER": "Przekaż opinię lub podziel się opinią na Twitterze:",
  "TEST_TRANSLATE": "użyj tego do testowania tłumaczeń",
  "POWER_USER_POPUP_TITLE": "Jak możemy ulepszyć {APP_NAME} dla Ciebie?",
  "POWER_USER_POPUP_TEXT": "<div>Chcielibyśmy poznać Twoją opinię. Twoja opinia pomoże nam zdecydować, które funkcje zbudować i jakie ulepszenia należy wprowadzić na naszej platformie.<br/> <a>Prosimy o wypełnienie tej krótkiej ankiety.</a></div>",
  "BEAUTIFY_ERROR": "Nie udało się upiększyć kodu. Sprawdź składnię.",
  "BEAUTIFY_ERROR_ORIGINAL_CHANGED": "Nie udało się upiększyć. Tekst edytora zmieniony po upiększeniu.",
  "BEAUTIFY_PROJECT_BUSY_MESSAGE": "Plik upiększający {0}",
  "BEAUTIFY_ERROR_SELECTION": "Nie można upiększyć.</br>Wybrano niekompletny blok kodu lub nieprawidłową składnię.",
  "BEAUTIFY_OPTIONS": "Opcje, które kontrolują sposób działania Beautify Code",
  "BEAUTIFY_OPTION_PRINT_WIDTH": "Określ długość linii, na której upiększacz będzie zawijał",
  "BEAUTIFY_OPTION_SEMICOLON": "Dodaj średnik na końcu każdej instrukcji",
  "BEAUTIFY_OPTION_SINGLE_QUOTE": "Używaj pojedynczych cudzysłowów zamiast podwójnych",
  "BEAUTIFY_OPTION_QUOTE_PROPS": "Zmień, gdy właściwości w obiektach są cytowane",
  "BEAUTIFY_OPTION_BRACKET_SAME_LINE": "Umieść > wielowierszowego elementu HTML (HTML, JSX, Vue, Angular) na końcu ostatniego wiersza zamiast być sam w następnym wierszu (nie dotyczy elementów samozamykających się)",
  "BEAUTIFY_OPTION_SINGLE_ATTRIBUTE_PER_LINE": "Egzekwuj pojedynczy atrybut na linię w HTML, Vue i JSX",
  "BEAUTIFY_OPTION_PROSE_WRAP": "Zawijaj prozę, jeśli przekracza szerokość wydruku w plikach przecen",
  "BEAUTIFY_OPTION_PRINT_TRAILING_COMMAS": "Drukuj końcowe przecinki tam, gdzie to możliwe, w wielowierszowych strukturach składniowych oddzielonych przecinkami"
});