/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "Výchozí",
  "PROJECT_BUSY": "Probíhající operace projektu",
  "DUPLICATING": "Duplikování {0}",
  "MOVING": "Přesouvání {0}",
  "COPYING": "Kopírování {0}",
  "DELETING": "Mazání {0}",
  "RENAMING": "Přejmenování",
  "STORED_IN_YOUR_BROWSER": "Uloženo ve vašem prohlížeči",
  "SUPPORT_US_OPEN_COLLECTIVE": "Podpořte nás na Open Collective",
  "GENERIC_ERROR": "(chyba {0})",
  "NOT_FOUND_ERR": "Soubor nenalezen.",
  "NOT_READABLE_ERR": "Soubor nelze číst.",
  "EXCEEDS_MAX_FILE_SIZE": "Soubor větší než {0} MB nemůže být otevřen v aplikaci {APP_NAME}.",
  "NO_MODIFICATION_ALLOWED_ERR": "Cílová složka nemůže být změněna.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "Oprávnění neumožní provádět změny.",
  "CONTENTS_MODIFIED_ERR": "Soubor byl změněn mimo aplikaci {APP_NAME}.",
  "UNSUPPORTED_ENCODING_ERR": "{APP_NAME} v této chvíli podporuje pouze UTF-8 textové soubory.",
  "ENCODE_FILE_FAILED_ERR": "Aplikaci {APP_NAME} se nepodařilo zakódovat obsah souboru.",
  "DECODE_FILE_FAILED_ERR": "Aplikaci {APP_NAME} se nepodařilo dekódovat obsah souboru.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "Aplikace {APP_NAME} v současné době nepodporuje textové soubory s kódováním UTF-16.",
  "FILE_EXISTS_ERR": "Soubor již existuje.",
  "FILE": "souboru",
  "FILE_TITLE": "Soubor",
  "DIRECTORY": "složky",
  "DIRECTORY_TITLE": "Složka",
  "DIRECTORY_NAMES_LEDE": "Názvy složek",
  "FILENAMES_LEDE": "Názvy souborů",
  "FILENAME": "název souboru",
  "DIRECTORY_NAME": "název složky",
  "ERROR_LOADING_PROJECT": "Chyba při otevírání projektu",
  "OPEN_DIALOG_ERROR": "Došlo k chybě při zobrazování dialogu Otevřít soubor. (chyba {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "Došlo k chybě při načítání adresáře <span class='dialog-filename'>{0}</span>. (chyba {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "Došlo k chybě při načítání obsahu složky <span class='dialog-filename'>{0}</span>. (chyba {1})",
  "ZOOM_WITH_SHORTCUTS": "K přiblížení použijte klávesové zkratky",
  "ZOOM_WITH_SHORTCUTS_DETAILS": "Pro přiblížení použijte klávesové zkratky <code><i>{0}</i></code> a pro oddálení <code><i>{1}</i></code> .",
  "ERROR_OPENING_FILE_TITLE": "Chyba při otevírání souboru",
  "ERROR_OPENING_FILE": "Došlo k chybě při otevírání souboru <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_OPENING_FILES": "Došlo k chybě při otevírání následujících souborů:",
  "ERROR_RELOADING_FILE_TITLE": "Chyba při načítání změn z disku",
  "ERROR_RELOADING_FILE": "Došlo k chybě při načítání souboru <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_SAVING_FILE_TITLE": "Chyba při ukládání souboru",
  "ERROR_SAVING_FILE": "Došlo k chybě při ukládání souboru <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_FILE_TITLE": "Chyba při přejmenování {0}",
  "ERROR_RENAMING_FILE": "Došlo k chybě při přejmenování {2} <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "Soubor nebo adresář není součástí aktuálně otevřeného projektu. Bohužel v tomto okamžiku lze přejmenovat pouze soubory projektu.",
  "ERROR_MOVING_FILE_TITLE": "Chyba při přesunu {0}",
  "ERROR_MOVING_FILE": "Při pokusu o přesunutí položky {2} <span class='dialog-filename'>{0}</span> došlo k chybě. {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "Soubor/složku nelze přesunout, protože nejsou součástí aktuálního projektu.",
  "ERROR_DELETING_FILE_TITLE": "Chyba při mazání {0}",
  "ERROR_DELETING_FILE": "Došlo k chybě při mazání {2} <span class='dialog-filename'>{0}</span>. {1}",
  "INVALID_FILENAME_TITLE": "Špatný {0}",
  "CANNOT_PASTE_TITLE": "Nelze vložit {0}",
  "CANNOT_DOWNLOAD_TITLE": "Nelze stáhnout {0}",
  "ERR_TYPE_DOWNLOAD_FAILED": "Při stahování <span class='dialog-filename'>souboru {0}</span> došlo k chybě",
  "ERR_TYPE_PASTE_FAILED": "Při vkládání <span class='dialog-filename'>{0}</span> do <span class='dialog-filename'>{1}</span> došlo k chybě",
  "CANNOT_DUPLICATE_TITLE": "Nelze duplikovat",
  "ERR_TYPE_DUPLICATE_FAILED": "Při duplikování <span class='dialog-filename'>{0}</span> došlo k chybě",
  "ERR_TYPE_DUPLICATE_FAILED_NO_FILE": "Vyberte soubor, který chcete duplikovat.",
  "INVALID_FILENAME_MESSAGE": "{0} nemohou obsahovat rezervovaná slova, končit tečkami (.) nebo obsahovat znaky: <code class='emphasized'>{1}</code>",
  "ENTRY_WITH_SAME_NAME_EXISTS": "Soubor nebo složka se jménem <span class='dialog-filename'>{0}</span> již existuje.",
  "ERROR_CREATING_FILE_TITLE": "Chyba při vytváření {0}",
  "ERROR_CREATING_FILE": "Došlo k chybě při vytváření {0} <span class='dialog-filename'>{1}</span>. {2}",
  "ERROR_MIXED_DRAGDROP": "Nelze otevřít složku ve chvíli, kdy se otevírají jiné soubory.",
  "ERROR_KEYMAP_TITLE": "Chyba při čtení uživatelských klávesových zkratek",
  "ERROR_KEYMAP_CORRUPT": "Soubor s nastavením klávesových zkratek není platný soubor typu JSON. Soubor bude otevřen, abyste mohli opravit formát.",
  "ERROR_LOADING_KEYMAP": "Váš soubor s klávesovými zkratkami není platný UTF-8 soubor a nemůže být otevřen",
  "ERROR_RESTRICTED_COMMANDS": "Nemůžete změnit klávesové zkratky následujícím příkazům: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "Nemůžete změnit tyto klávesové zkratky: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "Vytváříte více klávesových zkratek pro tyto příkazy: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "Tyto příkazy mají stejnou klávesovou zkratku: {0}",
  "ERROR_INVALID_SHORTCUTS": "Tyto klávesové zkratky jsou neplatné: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "Vytváříte klávesovou zkratku pro neexistující příkaz: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "Chyba při čtení nastavení",
  "ERROR_PREFS_PROJECT_LINT": "Předvolby projektu",
  "ERROR_PREFS_PROJECT_LINT_MESSAGE": "Chyba: Projekt obsahuje soubory `.brackets.json` i `.phcode.json`, což způsobuje konflikt. Smažte prosím buď `.brackets.json` nebo `.phcode.json` a poté znovu načtěte projekt.",
  "ERROR_PREFS_CORRUPT": "Soubor s nastavením není platný soubor typu JSON. Soubor bude otevřen, abyste mohli opravit formát. Pro uložení změn budete muset restartovat aplikaci {APP_NAME}.",
  "ERROR_PROJ_PREFS_CORRUPT": "Soubor s preferencemi vašeho projektu neodpovídá validnímu JSON formátu. Tento soubor bude otevřen, abyste mohl formát opravit. K provedení změn bude nutné znovu načíst projekt.",
  "ERROR_IN_BROWSER_TITLE": "Ouha! {APP_NAME} ještě neběží v prohlížeči.",
  "ERROR_IN_BROWSER": "{APP_NAME} je vytvořen v HTML, ale nyní pracuje jako desktopová aplikace, takže ji můžete použít pro úpravu lokálních souborů. Prosím, použijte shell aplikace v repozitáři <b>github.com/adobe/brackets-shell</b> pro spuštění {APP_NAME}.",
  "ERROR_MAX_FILES_TITLE": "Chyba při indexování souborů",
  "ERROR_MAX_FILES": "Tento projekt obsahuje více než 30.000 souborů. Funkce zpracovávající více souborů mohou být zablokované nebo se mohou chovat jako kdyby byl projekt prázdný. <a href='https://github.com/adobe/brackets/wiki/Large-Projects'>Čtěte více o práci s obřími projekty</a>.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "Chyba při spouštění prohlížeče",
  "ERROR_CANT_FIND_CHROME": "Prohlížeč Google Chrome nebyl nalezen. Přesvědčte se, že je nainstalován",
  "ERROR_LAUNCHING_BROWSER": "Došlo k chybě při spouštění prohlížeče. (chyba {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "Živý náhled - chyba",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "Připojování k prohlížeči",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "Aby se mohl živý náhled připojit, je třeba restartovat Chrome s povolenou možností vzdálené ladění.<br /><br />Chcete restartovat Chrome a povolit vzdálené ladění?<br /><br />",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "Nelze načíst stránku s živým náhledem",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "Pro spuštění živého náhledu se vzdáleným souborem, musíte specifikovat URL pro tento projekt.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "Chyba při spouštění HTTP serveru pro soubory živého náhledu. Prosím, zkuste to znovu.",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "Pro více informací navštivte stránku <a href='{0}' title='{0}'>řešení problémů s připojením v Živém náhledu</a>.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "Živý náhled",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "Živý náhled: Připojování…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "Živý náhled: Spouštění…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "Server živého náhledu je aktivní",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "Živý náhled",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "Vyberte Soubor do živého náhledu",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "Znovu načíst stránku",
  "LIVE_DEV_TOGGLE_LIVE_HIGHLIGHT": "Přepnout zvýraznění živého náhledu",
  "LIVE_DEV_CLICK_POPOUT": "Vyskakovat živý náhled do nového okna",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "Připnout na stránku náhledu Odepnout",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "Živý náhled (neaktualizováno kvůli chybě v syntaxi)",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "Živý náhled byl zrušen, protože byly otevřeny vývojářské nástroje prohlížeče",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "Živý náhled byl zrušen, protože dokument byl zavřen v prohlížeči",
  "LIVE_DEV_NAVIGATED_AWAY": "Živý náhled byl zrušen, protože prohlížeč přešel na stránku, která není součástí projektu",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "Živý náhled byl zrušen z neznámého důvodu ({0})",
  "SAVE_CLOSE_TITLE": "Uložit změny",
  "SAVE_CLOSE_MESSAGE": "Chcete uložit změny v souboru <span class='dialog-filename'>{0}</span>?",
  "SAVE_CLOSE_MULTI_MESSAGE": "Chcete uložit změny v následujících souborech?",
  "EXT_MODIFIED_TITLE": "Externí změny",
  "CONFIRM_DELETE_TITLE": "Potvrdit smazání",
  "CONFIRM_FILE_DELETE": "Opravdu chcete smazat soubor <span class='dialog-filename'>{0}</span> ?",
  "CONFIRM_FOLDER_DELETE": "Opravdu chcete smazat složku <span class='dialog-filename'>{0}</span>?",
  "FILE_DELETED_TITLE": "Soubor smazán",
  "EXT_MODIFIED_WARNING": "<span class='dialog-filename'>{0}</span> byl změněn mimo {APP_NAME}.<br /><br />Chcete uložit soubor a přepsat tyto změny?",
  "EXT_MODIFIED_MESSAGE": "<span class='dialog-filename'>{0}</span> byl změněn mimo {APP_NAME}, ale existují také neuložené změny v {APP_NAME}.<br /><br />Kterou verzi chcete zachovat?",
  "EXT_DELETED_MESSAGE": "<span class='dialog-filename'>{0}</span> byl smazán mimo {APP_NAME}, ale existují neuložené změny v {APP_NAME}.<br /><br />Chcete vaše změny zachovat?",
  "EXT_ALWAYS_MODIFIED_BUTTON_TOOLTIP": "Vždy přepisujte soubory, dokud se projekt nepřepne nebo nerestartuje",
  "WINDOW_UNLOAD_WARNING": "Opravdu chcete přejít na jinou adresu URL a opustit aplikaci {APP_NAME}?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "Máte neuložené změny! Opravdu chcete přejít na jinou adresu URL a opustit aplikaci {APP_NAME}?",
  "DONE": "Hotovo",
  "OK": "OK",
  "CANCEL": "Zrušit",
  "DONT_SAVE": "Neukládat",
  "SAVE": "Uložit",
  "SAVE_AS": "Uložit jako…",
  "SAVE_AND_OVERWRITE": "Přepsat",
  "ALWAYS_OVERWRITE": "Vždy přepsat",
  "DELETE": "Smazat",
  "BUTTON_YES": "Ano",
  "BUTTON_NO": "Ne",
  "FIND_MATCH_INDEX": "{0} z {1}",
  "FIND_NO_RESULTS": "Žádné výsledky",
  "FIND_QUERY_PLACEHOLDER": "Najít…",
  "FIND_HISTORY_MAX_COUNT": "Maximální počet hledaných položek v historii vyhledávání",
  "REPLACE_PLACEHOLDER": "Nahradit s…",
  "BUTTON_REPLACE_ALL": "Vše…",
  "BUTTON_REPLACE_BATCH": "Dávka…",
  "BUTTON_REPLACE_ALL_IN_FILES": "Nahradit…",
  "BUTTON_REPLACE": "Nahradit",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "Další shoda",
  "BUTTON_PREV_HINT": "Předchozí shoda",
  "BUTTON_CASESENSITIVE_HINT": "Rozlišovat velká a malá písmena",
  "BUTTON_REGEXP_HINT": "Regulární výraz",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "Nahradit bez možnosti vrátit změny",
  "REPLACE_WITHOUT_UNDO_WARNING": "Protože musí být změněno více než {0} souborů, {APP_NAME} změní neotevřené soubory na disku.<br />Nebude možné vrátit změny v těchto souborech.",
  "BUTTON_REPLACE_WITHOUT_UNDO": "Nahradit bez možnosti vrátit změny",
  "OPEN_FILE": "Otevřít soubor",
  "SAVE_FILE_AS": "Uložit soubor",
  "CHOOSE_FOLDER": "Vybrat složku",
  "RELEASE_NOTES": "Poznámky k verzi",
  "NO_UPDATE_TITLE": "Vše je aktuální!",
  "NO_UPDATE_MESSAGE": "Verze {APP_NAME} je aktuální.",
  "FIND_REPLACE_TITLE_LABEL": "Nahradit",
  "FIND_REPLACE_TITLE_WITH": "s",
  "FIND_TITLE_LABEL": "Nalezeno",
  "FIND_TITLE_SUMMARY": "&mdash; {0} {1} {2} v {3}",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "v <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_NO_SCOPE": "v projektu",
  "FIND_IN_FILES_ZERO_FILES": "Filtr vyloučil všechny soubory {0}",
  "FIND_IN_FILES_FILE": "souboru",
  "FIND_IN_FILES_FILES": "souborech",
  "FIND_IN_FILES_MATCH": "výsledek",
  "FIND_IN_FILES_MATCHES": "výsledků",
  "FIND_IN_FILES_MORE_THAN": "více než ",
  "FIND_IN_FILES_PAGING": "{0}&mdash;{1}",
  "FIND_IN_FILES_FILE_PATH": "Soubor <span class='dialog-filename'>{0}</span> ve složce <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "Ctrl/Cmd klik pro rozbalení/sbalení všeho",
  "FIND_IN_FILES_INDEXING": "Indexování pro okamžité vyhledávání…",
  "FIND_IN_FILES_SEARCHING": "Vyhledávání souborů…",
  "FIND_IN_FILES_SEARCHING_IN": "V {0}",
  "FIND_IN_FILES_INDEXING_PROGRESS": "Indexování {0} z {1} souborů pro Okamžité vyhledávání…",
  "REPLACE_IN_FILES_ERRORS_TITLE": "Nahradit chyby",
  "REPLACE_IN_FILES_ERRORS": "Následující soubory nebyly změněny, protože se změnily po hledání nebo do nich nelze zapisovat.",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "Chyba při získávání informací o aktualizaci",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "Nelze získat aktualizace. Ujistěte se, že máte připojení k internetu a zkuste to znovu.",
  "NEW_FILE_FILTER": "Nová řada vyloučených souborů…",
  "CLEAR_FILE_FILTER": "Nevylučovat soubory",
  "NO_FILE_FILTER": "Vyloučit soubory…",
  "EXCLUDE_FILE_FILTER": "Vyloučit soubory",
  "INCLUDE_FILE_FILTER": "Hledat v souborech",
  "FILTER_PLACEHOLDER": "např. index,.css,*.js,src/**/*.css",
  "FILTER_HISTORY_TOOLTIP": "Historii zobrazíte stisknutím `Ctrl-Mezerník`.",
  "FILTER_HISTORY_TOOLTIP_MAC": "Historii zobrazíte stisknutím `Cmd-Space`.",
  "FIND_HISTORY_TOOLTIP": "Historii zobrazíte stisknutím `Ctrl-Mezerník`.",
  "FIND_HISTORY_TOOLTIP_MAC": "Historii zobrazíte stisknutím `Cmd-Space`.",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "Rychlá úprava není dostupná pro aktuální pozici kurzoru",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "Rychlá úprava CSS: umístěte kurzor do jména třídy",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "Rychlá úprava CSS: nekompletní class atribut",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "Rychlá úprava CSS: nekompletní id atribut",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "Rychlá úprava CSS: umístěte kurzor do elementu, třídy nebo id",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "Rychlá úprava CSS časování: neplatná syntaxe",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "Rychlá úprava JS: umístěte kurzor do jména funkce",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "Rychlá dokumentace není dostupná pro aktuální pozici kurzoru",
  "PROJECT_LOADING": "Načítání…",
  "UNTITLED": "Nový",
  "WORKING_FILES": "Pracovní soubory",
  "TOP": "Nahoře",
  "BOTTOM": "Dole",
  "LEFT": "Vlevo",
  "RIGHT": "Vpravo",
  "CMD_SPLITVIEW_NONE": "Bez rozdělení",
  "CMD_SPLITVIEW_VERTICAL": "Vertikální rozdělení",
  "CMD_SPLITVIEW_HORIZONTAL": "Horizontální rozdělení",
  "SPLITVIEW_MENU_TOOLTIP": "Rozdělit editor horizontálně nebo vertikálně",
  "GEAR_MENU_TOOLTIP": "Nastavit pracovní plochu",
  "SPLITVIEW_INFO_TITLE": "Již otevřen",
  "SPLITVIEW_MULTIPANE_WARNING": "Soubor je již otevřen v jiném okně. {APP_NAME} bude brzy podporovat otevírání stejného souboru ve více oknech. Do té doby bude soubor zobrazen v již otevřeném okně.<br /><br />(Tuto zprávu uvidíte pouze jednou.)",
  "KEYBOARD_OVERLAY_TEXT": "K navigaci použijte šipky nebo zadejte prvky uživatelského rozhraní.",
  "KEYBOARD_SHORTCUT_CHANGE_TITLE": "Změnit klávesovou zkratku…",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_TITLE": "Změnit klávesovou zkratku",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_TEXT": "Stiskněte novou kombinaci kláves pro <b>„{0}“</b> (aktuální: <b>{1}</b> )",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_DUPLICATE": "Upozornění: Kombinace kláves <b>{0}</b> je již přiřazena k <b>&#39;{1}&#39;</b> . Změnit přiřazení k <b>&#39;{2}&#39;</b> ?",
  "KEYBOARD_SHORTCUT_ASSIGN": "Přiřadit",
  "KEYBOARD_SHORTCUT_NONE": "Žádný",
  "KEYBOARD_SHORTCUT_MENU_SHOW_SHORTCUTS": "Klávesové zkratky…",
  "KEYBOARD_SHORTCUT_MENU_SHOW_SHORTCUTS_BUTTON": "Zobrazit všechny zkratky…",
  "KEYBOARD_SHORTCUT_TABLE_BASE_KEY": "Základní klíč",
  "KEYBOARD_SHORTCUT_TABLE_KEY_BINDING": "Zkratka",
  "KEYBOARD_SHORTCUT_TABLE_COMMAND_ID": "ID příkazu",
  "KEYBOARD_SHORTCUT_TABLE_COMMAND_NAME": "Příkaz",
  "KEYBOARD_SHORTCUT_TABLE_DOUBLE_CLICK": "Dvojitým kliknutím změníte zástupce",
  "KEYBOARD_SHORTCUT_TABLE_ORIGIN": "Původ",
  "KEYBOARD_SHORTCUT_ORIG_EXTENSION": "Rozšíření",
  "KEYBOARD_SHORTCUT_PANEL_TITLE": "Klávesové zkratky",
  "KEYBOARD_SHORTCUT_PANEL_FILTER": "Filtr&hellip;",
  "KEYBOARD_SHORTCUT_PANEL_RESET": "Resetovat…",
  "KEYBOARD_SHORTCUT_PANEL_RESET_DEFAULT": "Obnovit výchozí zástupce…",
  "KEYBOARD_SHORTCUT_RESET_DIALOG_TITLE": "Resetovat klávesové zkratky",
  "KEYBOARD_SHORTCUT_RESET_DIALOG_MESSAGE": "Obnovit všechny vlastní zástupce na výchozí? To nelze vrátit zpět.",
  "STATUSBAR_CURSOR_POSITION": "Řádek {0}, Sloupec {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": " — Vybrán {0} sloupec",
  "STATUSBAR_SELECTION_CH_PLURAL": " — Vybrány {0} sloupce",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " — Vybrán {0} řádek",
  "STATUSBAR_SELECTION_LINE_PLURAL": " — Vybrány {0} řádky",
  "STATUSBAR_SELECTION_MULTIPLE": " — {0} Vybráno",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "Přepnout odsazení na mezery",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "Přepnout odsazení na tabulátory",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "Změnit počet mezer použitých pro odsazení",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "Změnit šířku tabulátoru",
  "STATUSBAR_SPACES": "Mezery:",
  "STATUSBAR_TAB_SIZE": "Velikost tabulátoru:",
  "STATUSBAR_LINE_COUNT_SINGULAR": "Řádek: {0}",
  "STATUSBAR_LINE_COUNT_PLURAL": "Řádky: {0}",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "Doplňky zakázány",
  "STATUSBAR_INSERT": "INS",
  "STATUSBAR_OVERWRITE": "OVR",
  "STATUSBAR_INSOVR_TOOLTIP": "Klikněte pro přepnutí kurzoru mezi módem Insert (INS) a Overwrite (OVR)",
  "STATUSBAR_LANG_TOOLTIP": "Klikněte pro změnu typu souboru",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. Klikněte pro zapnutí panelu zpráv.",
  "STATUSBAR_DEFAULT_LANG": "(výchozí)",
  "STATUSBAR_SET_DEFAULT_LANG": "Nastavit jako výchozí pro .{0} soubory",
  "STATUSBAR_ENCODING_TOOLTIP": "Vyberte kódování",
  "STATUSBAR_TASKS": "Úkoly",
  "STATUSBAR_TASKS_TOOLTIP": "Správa aktivních úloh",
  "STATUSBAR_TASKS_HIDE_SPINNER": "Skrýt ikonu Spinner",
  "STATUSBAR_TASKS_UNKNOWN_EXTENSION_TASK": "Neznámý úkol rozšíření…",
  "STATUSBAR_TASKS_PLAY": "Spustit nebo Pokračovat",
  "STATUSBAR_TASKS_PAUSE": "Pauza",
  "STATUSBAR_TASKS_STOP": "Stop",
  "STATUSBAR_TASKS_RESTART": "Restartujte",
  "ERRORS_PANEL_TITLE_MULTIPLE": "{0} chyb",
  "SINGLE_ERROR": "1 {0} chyba",
  "MULTIPLE_ERRORS": "{1} {0} chyby",
  "NO_ERRORS": "Žádné {0} chyby - dobrá práce!",
  "NO_ERRORS_MULTIPLE_PROVIDER": "Žádné chyby nenalezeny - dobrá práce!",
  "LINT_DISABLED": "Lintování je vypnuto",
  "NO_LINT_AVAILABLE": "Žádný linter není dostupný pro {0}",
  "NOTHING_TO_LINT": "Nic k lintování",
  "LINTER_TIMED_OUT": "{0} - vypršel časový limit po uplynutí {1} ms",
  "LINTER_FAILED": "{0} byl(a) ukončen(a) s chybou: {1}",
  "FILE_MENU": "Soubor",
  "CMD_FILE_NEW_UNTITLED": "Nový",
  "CMD_FILE_NEW": "Nový soubor",
  "CMD_FILE_DUPLICATE": "Duplikovat",
  "CMD_FILE_DUPLICATE_FILE": "Duplicitní soubor",
  "CMD_FILE_DOWNLOAD_PROJECT": "Stáhnout projekt",
  "CMD_FILE_DOWNLOAD": "Stažení",
  "CMD_FILE_CUT": "Vyjmout",
  "CMD_FILE_COPY": "Kopírovat",
  "CMD_FILE_COPY_PATH": "Kopírovat cestu",
  "CMD_FILE_PASTE": "Vložit",
  "CMD_PROJECT_NEW": "Nový projekt…",
  "CMD_FILE_NEW_FOLDER": "Nová složka",
  "CMD_FILE_OPEN": "Otevřít soubory…",
  "CMD_RECENT_FILES_OPEN": "Poslední soubory…",
  "CMD_ADD_TO_WORKING_SET": "Přidat k pracovní sadě",
  "CMD_OPEN_DROPPED_FILES": "Otevřít opuštěné soubory",
  "CMD_OPEN_FOLDER": "Otevřít složku…",
  "CMD_FILE_CLOSE": "Zavřít",
  "CMD_FILE_CLOSE_ALL": "Zavřít vše",
  "CMD_FILE_CLOSE_LIST": "Zavřít seznam",
  "CMD_FILE_CLOSE_OTHERS": "Zavřít ostatní",
  "CMD_FILE_CLOSE_ABOVE": "Zavřít ostatní výše",
  "CMD_FILE_CLOSE_BELOW": "Zavřít ostatní níže",
  "CMD_FILE_SAVE": "Uložit soubor",
  "CMD_FILE_SAVE_ALL": "Uložit vše",
  "CMD_FILE_SAVE_AS": "Uložit jako…",
  "CMD_LIVE_FILE_PREVIEW": "Živý náhled",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "Experimentální živý náhled",
  "CMD_RELOAD_LIVE_PREVIEW": "Vynutit obnovení živého náhledu",
  "CMD_PROJECT_SETTINGS": "Nastavení projektu…",
  "CMD_FILE_RENAME": "Přejmenovat",
  "CMD_FILE_DELETE": "Smazat",
  "CMD_INSTALL_EXTENSION": "Instalovat doplňky…",
  "CMD_EXTENSION_MANAGER": "Správce doplňků…",
  "CMD_FILE_REFRESH": "Obnovit",
  "CMD_FILE_SHOW_FOLDERS_FIRST": "Nejprve seřadit složky",
  "CMD_QUIT": "Konec",
  "CMD_EXIT": "Konec",
  "EDIT_MENU": "Úpravy",
  "CMD_UNDO": "Zpět",
  "CMD_REDO": "Znovu",
  "CMD_CUT": "Vyjmout",
  "CMD_COPY": "Kopírovat",
  "CMD_PASTE": "Vložit",
  "CMD_SELECT_ALL": "Vybrat vše",
  "CMD_SELECT_LINE": "Vybrat řádek",
  "CMD_SPLIT_SEL_INTO_LINES": "Rozdělit výběr na řádky",
  "CMD_ADD_CUR_TO_NEXT_LINE": "Přidat kurzor na další řádek",
  "CMD_ADD_CUR_TO_PREV_LINE": "Přidat kurzor na předcházející řádek",
  "CMD_INDENT": "Odsadit",
  "CMD_UNINDENT": "Vrátit odsazení",
  "CMD_DUPLICATE": "Duplikovat",
  "CMD_DELETE_LINES": "Smazat řádek",
  "CMD_COMMENT": "Řádkový komentář",
  "CMD_BLOCK_COMMENT": "Blokový komentář",
  "CMD_LINE_UP": "Posunout řádek nahoru",
  "CMD_LINE_DOWN": "Posunout řádek dolů",
  "CMD_OPEN_LINE_ABOVE": "O řádek výše",
  "CMD_OPEN_LINE_BELOW": "O řádek níže",
  "CMD_TOGGLE_CLOSE_BRACKETS": "Uzavírat závorky",
  "CMD_SHOW_CODE_HINTS": "Zobrazit nápovědy kódu",
  "CMD_BEAUTIFY_CODE": "Zkrášlit kód",
  "CMD_BEAUTIFY_CODE_ON_SAVE": "Zkrášlit kód po uložení",
  "FIND_MENU": "Najít",
  "CMD_FIND": "Najít",
  "CMD_FIND_NEXT": "Najít další",
  "CMD_FIND_PREVIOUS": "Najít předchozí",
  "CMD_FIND_ALL_AND_SELECT": "Vyberte Všechny výskyty",
  "CMD_ADD_NEXT_MATCH": "Přidat další výskyt",
  "CMD_SKIP_CURRENT_MATCH": "Přeskočit a přidat další výskyt",
  "CMD_FIND_IN_FILES": "Najít v souborech",
  "CMD_FIND_IN_SUBTREE": "Najít v…",
  "CMD_REPLACE": "Nahradit",
  "CMD_REPLACE_IN_FILES": "Nahradit v souborech",
  "CMD_REPLACE_IN_SUBTREE": "Nahradit v…",
  "VIEW_MENU": "Zobrazit",
  "CMD_HIDE_SIDEBAR": "Skrýt boční menu",
  "CMD_SHOW_SIDEBAR": "Zobrazit boční menu",
  "CMD_TOGGLE_SIDEBAR": "Zobrazit/skrýt boční menu",
  "CMD_TOGGLE_PANELS": "Zobrazit/skrýt panely",
  "CMD_TOGGLE_PURE_CODE": "Žádné rozptylování",
  "CMD_TOGGLE_FULLSCREEN": "Celá obrazovka",
  "CMD_ZOOM_UI": "Zoom UI a písma",
  "CMD_ZOOM_IN": "Přiblížit",
  "CMD_ZOOM_IN_SCALE": "Přiblížit (aktuální: {0} %)",
  "CMD_ZOOM_OUT": "Oddálit",
  "CMD_INCREASE_FONT_SIZE": "Zvětšit velikost písma",
  "CMD_DECREASE_FONT_SIZE": "Zmenšit velikost písma",
  "CMD_RESTORE_FONT_SIZE": "Obnovit velikost písma",
  "CMD_SCROLL_LINE_UP": "Posunout o řádek nahoru",
  "CMD_SCROLL_LINE_DOWN": "Posunout o řádek dolů",
  "CMD_TOGGLE_LINE_NUMBERS": "Čísla řádků",
  "CMD_TOGGLE_ACTIVE_LINE": "Zvýraznit aktivní řádek",
  "CMD_TOGGLE_WORD_WRAP": "Zalomit řádky",
  "CMD_LIVE_HIGHLIGHT": "Živé zvýraznění",
  "CMD_VIEW_TOGGLE_INSPECTION": "Lintovat soubory při uložení",
  "CMD_WORKINGSET_SORT_BY_ADDED": "Řadit podle data přidání",
  "CMD_WORKINGSET_SORT_BY_NAME": "Řadit podle jména",
  "CMD_WORKINGSET_SORT_BY_TYPE": "Řadit podle typu",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "Automatické řazení",
  "CMD_THEMES": "Motivy…",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "Automaticky zavřít vyhledávání",
  "CMD_KEYBOARD_NAV_OVERLAY": "Režim navigace uživatelského rozhraní",
  "NAVIGATE_MENU": "Navigace",
  "CMD_QUICK_OPEN": "Rychle otevřít",
  "CMD_GOTO_LINE": "Přejít na řádek",
  "CMD_GOTO_DEFINITION": "Přejít na definici",
  "CMD_GOTO_DEFINITION_PROJECT": "Definice rychlého hledání v projektu",
  "CMD_GOTO_FIRST_PROBLEM": "Přejít na první chybu/varování",
  "CMD_TOGGLE_QUICK_EDIT": "Rychlá úprava",
  "CMD_TOGGLE_QUICK_DOCS": "Rychlá dokumentace",
  "CMD_QUICK_EDIT_PREV_MATCH": "Předchozí položka rychlé úpravy",
  "CMD_QUICK_EDIT_NEXT_MATCH": "Další položka Rychlá úprava",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "Nový předpis",
  "CMD_NEXT_DOC": "Další dokument",
  "CMD_PREV_DOC": "Předchozí dokument",
  "CMD_NAVIGATE_BACKWARD": "Přejít zpět",
  "CMD_NAVIGATE_FORWARD": "Přejít vpřed",
  "CMD_NEXT_DOC_LIST_ORDER": "Další dokument v seznamu",
  "CMD_PREV_DOC_LIST_ORDER": "Předchozí dokument v seznamu",
  "CMD_SHOW_IN_TREE": "Zobrazit stromovou strukturu",
  "CMD_SHOW_IN_EXPLORER": "Zobrazit v průzkumníkovi",
  "CMD_SHOW_IN_FINDER": "Zobrazit ve vyhledávači",
  "CMD_SHOW_IN_OS": "Zobrazit v souborech OS",
  "CMD_SWITCH_PANE_FOCUS": "Přepnout zaměření podokna",
  "CMD_OPEN_VFS": "Otevřete virtuální souborový systém",
  "CMD_DIAGNOSTIC_TOOLS": "Diagnostické nástroje {APP_NAME}",
  "CMD_OPEN_EXTENSIONS_FOLDER": "Otevřít složku Rozšíření…",
  "CMD_OPEN_VIRTUAL_SERVER": "Otevřete virtuální server",
  "HELP_MENU": "Nápověda",
  "CMD_CHECK_FOR_UPDATE": "Zkontrolovat aktualizace",
  "CMD_HOW_TO_USE_BRACKETS": "Jak používat {APP_NAME}",
  "CMD_SUPPORT": "{APP_NAME} Podpora",
  "CMD_SUGGEST": "Navrhněte funkci",
  "CMD_RELEASE_NOTES": "Poznámky k verzi",
  "CMD_GET_INVOLVED": "Zapojte se",
  "CMD_SHOW_EXTENSIONS_FOLDER": "Zobrazit složku s doplňky",
  "CMD_HEALTH_DATA_STATISTICS": "Zdravotní zpráva…",
  "CMD_HOMEPAGE": "Domovská stránka – stahování aplikací",
  "CMD_TWITTER": "{TWITTER_NAME} na Twitteru",
  "CMD_ABOUT": "O aplikaci {APP_TITLE}",
  "CMD_OPEN_PREFERENCES": "Otevřít soubor s preferencemi",
  "CMD_OPEN_KEYMAP": "Otevřete soubor mapy uživatelských klíčů",
  "EXPERIMENTAL_BUILD": "experimentální sestavení",
  "RELEASE_BUILD": "sestavení",
  "DEVELOPMENT_BUILD": "vývojové sestavení",
  "PRERELEASE_BUILD": "předběžná verze",
  "RELOAD_FROM_DISK": "Načíst z disku",
  "KEEP_CHANGES_IN_EDITOR": "Ponechat změny v editoru",
  "CLOSE_DONT_SAVE": "Zavřít (neukládat)",
  "RELAUNCH_CHROME": "Restartovat Chrome",
  "ABOUT": "O aplikaci",
  "CLOSE": "Zavřít",
  "ABOUT_TEXT_LINE1": "Vydání {VERSION_MAJOR}.{VERSION_MINOR} {BUILD_TYPE} {VERSION}",
  "ABOUT_TEXT_BUILD_TIMESTAMP": "časové razítko sestavení:",
  "ABOUT_TEXT_LINE3": "Knihovny třetích stran, které používáme – <a href='https://github.com/phcode-dev/phoenix/tree/main/src/thirdparty/licences'>Licence a Attributions</a> .",
  "ABOUT_TEXT_LINE4": "Dokumentace a zdroj na <a href='https://github.com/phcode-dev/phoenix/'>https://github.com/phcode-dev/phoenix/</a>",
  "ABOUT_TEXT_LINE5": "Vytvořeno pomocí ❤ a JavaScript od:",
  "ABOUT_TEXT_LINE6": "Spousta lidí (ale právě teď máme potíže s načítáním těchto dat).",
  "ABOUT_TEXT_MDN_DOCS": "MDN Docs a MDN logo využívají licenci Creative Commons Attribution, <a href='{MDN_DOCS_LICENSE}'>CC-BY-SA 2.5 Unported</a>.",
  "UPDATE_NOTIFICATION_TOOLTIP": "Je dostupná nová verze {APP_NAME}! Klikněte zde pro více informací.",
  "UPDATE_NOT_AVAILABLE_TITLE": "Aplikace {APP_NAME} je aktuální",
  "UPDATE_UP_TO_DATE": "Vaše verze aplikace {APP_NAME} je nejnovější!",
  "UPDATE_AVAILABLE_TITLE": "Dostupná aktualizace",
  "UPDATE_READY_RESTART_TITLE": "Aktualizace připravena: Je vyžadován restart",
  "UPDATE_READY_RESTART_MESSAGE": "Zavřete všechna okna aplikace {APP_NAME} a restartujte aplikaci, aby se spustila aktualizovaná verze.",
  "UPDATE_READY_RESTART_INSTALL_MESSAGE": "Aktualizace byla úspěšně stažena: Chcete-li použít nejnovější aktualizace, zavřete všechna okna aplikace {APP_NAME}.",
  "UPDATE_FAILED_TITLE": "Aktualizace selhala",
  "UPDATE_INSTALLING": "Instalování aktualizace…",
  "UPDATE_INSTALLING_MESSAGE": "Probíhá instalace aktualizace: Aplikace {APP_NAME} aktuálně instaluje nejnovější aktualizace. Po dokončení instalace se aplikace automaticky zavře.",
  "UPDATE_FAILED_MESSAGE": "Zavřete všechna okna aplikace {APP_NAME} a znovu aplikaci otevřete, abyste se mohli pokusit o aktualizaci znovu.",
  "UPDATE_FAILED_VISIT_SITE_MESSAGE": "Chcete-li to zkusit znovu, ukončete všechny instance aplikace {APP_NAME} a restartujte aplikaci.<br> Brzy budete přesměrováni na naši stránku pro stahování, kde si můžete ručně stáhnout nejnovější verzi.",
  "UPDATE_MESSAGE": "Nová verze {APP_NAME} je dostupná. Seznam některých vylepšení:",
  "GET_IT_NOW": "Stáhnout!",
  "UPDATE_LATER": "Připomeň mi později",
  "UPDATE_DONE": "Restartujte a aktualizujte aplikaci {APP_NAME}",
  "UPDATE_RESTART": "Chcete-li použít aktualizace, restartujte",
  "UPDATE_RESTART_INSTALL": "Restartujte pro instalaci aktualizací",
  "UPDATE_DOWNLOADING": "Stahování instalačního programu",
  "INSTALL_WEBAPP": "Nainstalujte si do zařízení aplikaci {APP_NAME}",
  "UPDATE_DOWNLOAD_PROGRESS": "Stahování – {0} z {1} MB",
  "UPDATING_APP": "Aktualizace aplikace {APP_NAME}",
  "UPDATING_APP_MESSAGE": "Může to chvíli trvat",
  "UPDATING_APP_DIALOG_MESSAGE": "Aktualizace probíhá. Během upgradu můžete aplikaci {APP_NAME} nadále používat.",
  "PROJECT_SETTINGS_TITLE": "Nastavení projektu: {0}",
  "PROJECT_SETTING_BASE_URL": "URL Živého náhledu",
  "PROJECT_SETTING_BASE_URL_HINT": "(nechte prázdné pro URL souboru)",
  "BASEURL_ERROR_INVALID_PROTOCOL": "{0} protokol není podporován živým náhledem &mdash; prosím, použijte http: nebo https: .",
  "BASEURL_ERROR_SEARCH_DISALLOWED": "URL nemůže obsahovat výrazy pro hledání jako \"{0}\".",
  "BASEURL_ERROR_HASH_DISALLOWED": "URL nemůže obsahovat znaky jako \"{0}\".",
  "BASEURL_ERROR_INVALID_CHAR": "Zvláštní znaky jako '{0}' musí být zakódovány %.",
  "BASEURL_ERROR_UNKNOWN_ERROR": "Neznámá chyba při zpracování URL",
  "EMPTY_VIEW_HEADER": "<em>Otevřete soubor, zatímco tento panel je aktivní</em>",
  "FLIPVIEW_BTN_TOOLTIP": "Přepnout toto zobrazení na panel {0}",
  "CURRENT_THEME": "Aktuální motiv",
  "USE_THEME_SCROLLBARS": "Použít posuvníky motivu",
  "FONT_SIZE": "Velikost písma",
  "FONT_FAMILY": "Rodina písma",
  "THEMES_SETTINGS": "Nastavení motivů",
  "THEMES_ERROR": "Chyba motivů",
  "THEMES_ERROR_CANNOT_APPLY": "Motiv nelze použít kvůli chybě.",
  "BUTTON_NEW_RULE": "Nový předpis",
  "INSTALL": "Instalovat",
  "APPLY": "Aplikovat",
  "UPDATE": "Aktualizovat",
  "REMOVE": "Odstranit",
  "DISABLE": "Deaktivovat",
  "ENABLE": "Aktivovat",
  "OVERWRITE": "Přepsat",
  "CANT_DROP_ZIP": "Brzy bude podporováno vyhazování souborů zip...",
  "CANT_REMOVE_DEV": "Doplněk ve složce \"dev\" musí být smazán manuálně.",
  "CANT_UPDATE": "Aktualizace není kompatibilní s touto verzí {APP_NAME}.",
  "CANT_UPDATE_DEV": "Doplňky ve složce \"dev\" nemohou být aktualizovány automaticky.",
  "INSTALL_EXTENSION_TITLE": "Instalovat doplněk",
  "UPDATE_EXTENSION_TITLE": "Aktualizovat doplněk",
  "INSTALL_EXTENSION_LABEL": "URL adresa doplňku",
  "INSTALL_EXTENSION_HINT": "URL adresa zip archivu nebo GitHub repozitáře",
  "INSTALLING_FROM": "Instalace doplňku z {0}…",
  "INSTALL_SUCCEEDED": "Instalace byla úspěšná!",
  "INSTALL_FAILED": "Instalace se nezdařila.",
  "CANCELING_INSTALL": "Rušení instalace…",
  "CANCELING_HUNG": "Rušení instalace trvá dlouho. Mohlo dojít k interní chybě.",
  "INSTALL_CANCELED": "Instalace zrušena.",
  "VIEW_COMPLETE_DESCRIPTION": "Zobrazit úplný popis",
  "VIEW_TRUNCATED_DESCRIPTION": "Zobrazit zkrácený popis",
  "SORT_EXTENSION_METHOD": "Seřaďte rozšíření pomocí downloadCount nebo publishingDate",
  "INVALID_ZIP_FILE": "Stažený soubor není platný zip soubor.",
  "MISSING_PACKAGE_JSON": "Balíček neobsahuje žádný soubor package.json.",
  "INVALID_PACKAGE_JSON": "Package.json balíček není platný (chyba byla: {0}).",
  "MISSING_PACKAGE_NAME": "Package.json balíček nespecifikuje jméno souboru.",
  "BAD_PACKAGE_NAME": "{0} je neplatné jméno balíčku.",
  "MISSING_PACKAGE_VERSION": "Package.json balíček nespecifikuje verzi souboru.",
  "INVALID_VERSION_NUMBER": "Balíček verze ({0}) je neplatný.",
  "INVALID_BRACKETS_VERSION": "Řetězec kompatibility {0} pro {APP_NAME} je neplatný.",
  "DISALLOWED_WORDS": "Slova {1} nejsou povolena v {0} poli.",
  "NPM_INSTALL_FAILED": "Instalační příkaz npm se nezdařil: {0}",
  "API_NOT_COMPATIBLE": "Doplněk není kompatibilní s touto verzí {APP_NAME}. Naleznete jej ve složce disabled extensions.",
  "MISSING_MAIN": "Balíček neobsahuje soubor main.js.",
  "EXTENSION_ALREADY_INSTALLED": "Instalace tohoto balíčku přepíše již nainstalovaný doplněk. Chcete přepsat starý doplněk?",
  "EXTENSION_SAME_VERSION": "Tento balíček je stejná verze jako ta, kterou již máte nainstalovanou. Chcete přepsat existující doplněk?",
  "EXTENSION_OLDER_VERSION": "Tento balíček je verze {0}, která je starší než současně nainstalovaná verze ({1}). Chcete přepsat existující doplněk?",
  "DOWNLOAD_ID_IN_USE": "Interní chyba: ID stahování se již používá.",
  "NO_SERVER_RESPONSE": "Nelze se připojit na server.",
  "BAD_HTTP_STATUS": "Soubor nebyl nalezen (HTTP {0}).",
  "CANNOT_WRITE_TEMP": "Nelze uložit do dočasných souborů.",
  "ERROR_LOADING": "Při spuštění doplňku došlo k chybě.",
  "MALFORMED_URL": "URL adresa je neplatná. Ujistěte se, že jste adresu zadali správně.",
  "UNSUPPORTED_PROTOCOL": "URL adresa musí být http nebo https.",
  "UNKNOWN_ERROR": "Neznámá chyba.",
  "EXTENSION_VERIFIED_PUBLISHER": "Tento vydavatel ověřil vlastnictví webu {0}",
  "EXTENSION_VERIFIED_SORT": "Ověřeno",
  "EXTENSION_STAR": "Hvězda",
  "EXTENSION_STAR_SORT": "Hodnocení hvězdičkami",
  "EXTENSION_MANAGER_TITLE": "Správce doplňků",
  "EXTENSION_MANAGER_ERROR_LOAD": "Nelze získat přístup k registru doplňků. Prosím, zkuste to znovu později.",
  "EXTENSION_UPDATE_RESTART_TITLE": "Restartovat a aktualizovat",
  "EXTENSION_UPDATE_RESTART_MESSAGE": "Chcete-li načíst aktualizovaná rozšíření, zavřete všechny spuštěné instance aplikace {APP_NAME} a restartujte aplikaci.",
  "INSTALL_EXTENSION_DRAG": "Přetáhněte .zip zde nebo",
  "INSTALL_EXTENSION_DROP": "Pusťte .zip pro instalaci",
  "INSTALL_EXTENSION_DROP_ERROR": "Instalace/aktualizace byla zrušena kvůli následujících chyb:",
  "INSTALL_FROM_URL": "Instalovat z URL…",
  "INSTALL_EXTENSION_VALIDATING": "Ověření…",
  "EXTENSION_AUTHOR": "Autor",
  "EXTENSION_DATE": "Datum",
  "EXTENSION_INCOMPATIBLE_NEWER": "Tento doplněk požaduje novější verzi {APP_NAME}.",
  "EXTENSION_INCOMPATIBLE_OLDER": "Tento doplněk funguje pouze ve starší verzi {APP_NAME}.",
  "EXTENSION_DEFAULT_FEATURE_PRESENT": "Toto rozšíření možná nebudete potřebovat. Aplikace {APP_NAME} již tuto funkci má.",
  "EXTENSION_LATEST_INCOMPATIBLE_NEWER": "Verze {0} tohoto doplňku vyžaduje novější verzi {APP_NAME}. Můžete si ale nainstalovat dřívější verzi {1}.",
  "EXTENSION_LATEST_INCOMPATIBLE_OLDER": "Verze {0} tohoto doplňku funguje pouze se starší verzí {APP_NAME}. Můžete si ale nainstalovat dřívější verzi {1}.",
  "EXTENSION_NO_DESCRIPTION": "Bez popisu",
  "EXTENSION_MORE_INFO": "Více informací…",
  "EXTENSION_ERROR": "Chyba doplňku",
  "EXTENSION_KEYWORDS": "Klíčová slova",
  "EXTENSION_TRANSLATED_USER_LANG": "Přeloženo do {0} jazyků, včetně vašeho",
  "EXTENSION_TRANSLATED_GENERAL": "Přeloženo do {0} jazyků",
  "EXTENSION_TRANSLATED_LANGS": "Tento doplněk byl přeložen do těchto jazyků: {0}",
  "EXTENSION_INSTALLED": "Nainstalované",
  "EXTENSION_UPDATE_INSTALLED": "Aktualizace doplňku byla stažena a bude nainstalována při ukončení aplikace {APP_NAME}.",
  "EXTENSION_SEARCH_PLACEHOLDER": "Hledat",
  "EXTENSION_MORE_INFO_LINK": "Více",
  "EXTENSION_MANAGER_CREATE_EXTENSION": "+ Vytvořit rozšíření",
  "EXTENSION_MANAGER_CREATE_THEME": "+ Vytvořit téma",
  "BROWSE_EXTENSIONS": "Procházet doplňky",
  "EXTENSION_MANAGER_REMOVE": "Odstranit doplněk",
  "EXTENSION_MANAGER_REMOVE_ERROR": "Nelze odstranit jeden nebo více doplňků: {0}. Aplikace {APP_NAME} se i přesto restartuje.",
  "EXTENSION_MANAGER_UPDATE": "Aktualizovat doplněk",
  "EXTENSION_MANAGER_UPDATE_ERROR": "Nelze aktualizovat jeden nebo více doplňků: {0}. Aplikace {APP_NAME} se i přesto restartuje.",
  "EXTENSION_MANAGER_DISABLE": "Deaktivovat doplněk",
  "EXTENSION_MANAGER_DISABLE_ERROR": "Nelze deaktivovat jeden nebo více doplňků: {0}. Aplikace {APP_NAME} se i přesto restartuje.",
  "EXTENSION_MANAGER_THEMES_INFO": "Chcete-li <a class=\"theme_settings\">vybrat výchozí motivy</a> nebo upravit jiná nastavení motivu, <a class=\"theme_settings\">klikněte sem</a> .",
  "EXTENSION_MANAGER_THEMES_UNDO": "Vrátit se k předchozímu tématu",
  "MARKED_FOR_REMOVAL": "Označeno k odstranění",
  "UNDO_REMOVE": "Zpět",
  "MARKED_FOR_UPDATE": "Označeno k aktualizaci",
  "UNDO_UPDATE": "Zpět",
  "MARKED_FOR_DISABLING": "Označeno k deaktivaci",
  "UNDO_DISABLE": "Zpět",
  "CHANGE_AND_RELOAD_TITLE": "Změnit doplňky",
  "CHANGE_AND_RELOAD_MESSAGE": "K aktualizaci, odstranění nebo deaktivaci označených doplňků je třeba restartovat aplikaci {APP_NAME}. Budete vyzváni k uložení změn.",
  "REMOVE_AND_RELOAD": "Odstranit doplňky a restartovat",
  "CHANGE_AND_RELOAD": "Změnit doplňky a restartovat",
  "UPDATE_AND_RELOAD": "Aktualizovat doplňky a restartovat",
  "DISABLE_AND_RELOAD": "Deaktivovat doplňky a restartovat",
  "PROCESSING_EXTENSIONS": "Zpracování změn doplňku…",
  "EXTENSION_NOT_INSTALLED": "Doplněk {0} nemohl být odstraněn, protože nebyl nainstalován.",
  "NO_EXTENSIONS": "Žádný doplněk ještě nebyl nainstalován.<br>Klikněte na tlačítko Instalovat z URL pro zahájení instalace.",
  "NO_EXTENSION_MATCHES": "Žádný doplněk neodpovídá hledání.",
  "REGISTRY_SANITY_CHECK_WARNING": "POZNÁMKA: Tyto doplňky mohou pocházet od jiných autorů než {APP_NAME}. Buďte opatrní při instalaci doplňků z neznámých zdrojů.",
  "EXTENSIONS_INSTALLED_TITLE": "Nainstalované",
  "EXTENSIONS_DEFAULT_TITLE": "Výchozí",
  "EXTENSIONS_AVAILABLE_TITLE": "Dostupné",
  "EXTENSIONS_THEMES_TITLE": "Motivy",
  "EXTENSIONS_UPDATES_TITLE": "Aktualizace",
  "EXTENSIONS_LAST_UPDATED": "Naposledy aktualizováno",
  "EXTENSIONS_DOWNLOADS": "Stahování",
  "INLINE_EDITOR_NO_MATCHES": "Žádné dostupné shody.",
  "INLINE_EDITOR_HIDDEN_MATCHES": "Všechny shody jsou sbalené. Pro prohlédnutí shod rozbalte soubory zobrazené vpravo.",
  "CSS_QUICK_EDIT_NO_MATCHES": "Neexistují žádné CSS předpisy odpovídající vašemu výběru.<br>Pro vytvoření předpisu klikněte na \"Nový předpis\".",
  "CSS_QUICK_EDIT_NO_STYLESHEETS": "Neexistují žádné soubory s kaskádovými styly ve vašem projektu.<br>Vytvořte nový soubor pro přidání CSS předpisů.",
  "IMAGE_VIEWER_LARGEST_ICON": "největší",
  "UNIT_PIXELS": "pixely",
  "DEBUG_MENU": "Nástroje",
  "ERRORS": "Chyby",
  "CMD_SHOW_DEV_TOOLS": "Nástroje pro vývojáře {APP_NAME}",
  "CMD_REFRESH_WINDOW": "Restartovat {APP_NAME}",
  "CMD_LOAD_CURRENT_EXTENSION": "Načíst projekt jako rozšíření",
  "CMD_RELOAD_CURRENT_EXTENSION": "Znovu načíst projekt jako rozšíření",
  "CMD_UNLOAD_CURRENT_EXTENSION": "Uvolnit projekt jako rozšíření",
  "CMD_RELOAD_WITHOUT_USER_EXTS": "Restartovat bez doplňků",
  "CMD_NEW_BRACKETS_WINDOW": "Nové okno",
  "CMD_LAUNCH_SCRIPT_MAC": "Nainstalovat zástupce do příkazové řádky",
  "CMD_SWITCH_LANGUAGE": "Přepnout jazyk…",
  "CMD_RUN_UNIT_TESTS": "Spusťte testy aplikace {APP_NAME}",
  "CMD_SHOW_PERF_DATA": "Zobrazit údaje o výkonnosti",
  "CMD_ENABLE_LOGGING": "Povolit podrobné protokoly",
  "CMD_ENABLE_PHNODE_INSPECTOR": "Povolit PhNode Inspector",
  "CMD_GET_PHNODE_INSPECTOR_URL": "Jak zkontrolovat PhNode",
  "CMD_ENABLE_LIVE_PREVIEW_LOGS": "Záznamy živého náhledu",
  "CMD_OPEN_BRACKETS_SOURCE": "Otevřít zdroj {APP_NAME}",
  "CREATING_LAUNCH_SCRIPT_TITLE": "Zástupce {APP_NAME} v příkazové řádce",
  "ERROR_CREATING_LAUNCH_SCRIPT": "Při instalaci zástupce do příkazové řádky se vyskytla chyba. Prosím vyzkoušejte řešení <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting'>na této stránce</a>.<br/><br/>Důvod: {0}",
  "ERROR_CLTOOLS_RMFAILED": "Nelze odstranit existující symbolický odkaz na <code>/usr/local/bin/brackets</code>.",
  "ERROR_CLTOOLS_MKDIRFAILED": "Nelze vytvořit složku <code>/usr/local/bin</code>.",
  "ERROR_CLTOOLS_LNFAILED": "Nelze vytvořit symbolický odkaz na <code>/usr/local/bin/brackets</code>.",
  "ERROR_CLTOOLS_SERVFAILED": "Vnitřní chyba.",
  "ERROR_CLTOOLS_NOTSUPPORTED": "V tomto operačním systému nelze vytvořit zástupce do příkazové řádky.",
  "LAUNCH_SCRIPT_CREATE_SUCCESS": "Hotovo! Nyní můžete jednoduše spustit {APP_NAME} z příkazové řádky: příkazem <code>brackets myFile.txt</code> otevřete soubor a příkazem <code>brackets myFolder</code> změníte projekt. <br/><br/><a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments'>Na této stránce zjistíte více</a> o používání {APP_NAME} z příkazové řádky.",
  "ERROR_LOADING_EXTENSION": "Chyba při načítání rozšíření",
  "ERROR_NO_EXTENSION_PACKAGE": "V aktuálním projektu nebyl zjištěn soubor <code>package.json</code> . Je aktuální projekt platným rozšířením {APP_NAME}?</br> Další podrobnosti naleznete <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>na tomto odkazu</a> .",
  "ERROR_INVALID_EXTENSION_PACKAGE": "soubor <code>package.json</code> je neplatný JSON.</br> Další podrobnosti naleznete <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>na tomto odkazu</a> .",
  "ERROR_INVALID_EXTENSION_PACKAGE_FIELDS": "V <code>package.json</code> chybí povinná pole: [{0}]</br> Další podrobnosti naleznete <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>na tomto odkazu</a> .",
  "ERROR_NODE_JS_CRASH_TITLE": "Jejda! Něco se pokazilo.",
  "ERROR_NODE_JS_CRASH_MESSAGE": "Narazili jsme na problém a potřebujeme restartovat {APP_NAME}. Nebojte se, před restartem se snažíme uložit veškerou vaši práci. </br>(Chyba: ERROR_NODE_JS_CRASH)",
  "LANGUAGE_TITLE": "Změnit jazyk",
  "LANGUAGE_MESSAGE": "Prosím, vyberte jazyk ze seznamu:",
  "LANGUAGE_SUBMIT": "Restartovat {APP_NAME}",
  "LANGUAGE_CANCEL": "Zrušit",
  "LANGUAGE_SYSTEM_DEFAULT": "Výchozí",
  "HEALTH_DATA_NOTIFICATION": "Nastavení hlášení o zdraví",
  "HEALTH_FIRST_POPUP_TITLE": "Hlášení o zdraví {APP_NAME}",
  "HEALTH_DATA_DO_TRACK": "Sdílejte anonymní informace o používání {APP_NAME}",
  "HEALTH_DATA_NOTIFICATION_MESSAGE": "Abychom vylepšili {APP_NAME}, pravidelně zasíláme omezené <strong>pseudonymní</strong> statistiky a chybová hlášení na phcode.dev o tom, jak {APP_NAME} používáte. Tyto informace pomáhají upřednostňovat funkce, nacházet chyby a odhalovat problémy s použitelností a zároveň chránit vaše soukromí.<br><br> Svá data můžete zobrazit nebo se rozhodnout data nesdílet výběrem položky <strong>Nápověda &gt; Zpráva o stavu</strong> .<br><br>",
  "HEALTH_DATA_PREVIEW": "Hlášení o zdraví {APP_NAME}",
  "HEALTH_DATA_PREVIEW_INTRO": "<p>Abychom vylepšili {APP_NAME}, pravidelně zasíláme omezené <strong>pseudonymní</strong> statistiky a chybová hlášení na phcode.dev o tom, jak {APP_NAME} používáte. Tyto informace pomáhají určit priority funkcí, najít chyby a zjistit problémy s použitelností.</p><p> Níže je uveden náhled dat, která budou odeslána ve vaší další zdravotní zprávě <em>, pokud</em> je povolena. (Prohlédněte si také vývojářskou konzoli, kde najdete protokoly chyb označené jako „Zachycena kritická chyba“.)</p>",
  "INLINE_TIMING_EDITOR_TIME": "Doba",
  "INLINE_TIMING_EDITOR_PROGRESSION": "Postup",
  "BEZIER_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd><kbd>←</kbd><kbd>→</kbd> Posunout vybraný bod<br><kbd class='text'>Shift</kbd> Posunout o deset jednotek<br><kbd class='text'>Tab</kbd> Vyměnit body",
  "STEPS_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd> Zvýšení nebo snížení kroků<br><kbd>←</kbd><kbd>→</kbd> 'Start' nebo 'End'",
  "INLINE_TIMING_EDITOR_INVALID": "Stará hodnota <code>{0}</code> není platná, proto zobrazená funkce byla změněna na <code>{1}</code>. Dokument bude aktualizován při první úpravě.",
  "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP": "Současná barva",
  "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP": "Původní barva",
  "COLOR_EDITOR_RGBA_BUTTON_TIP": "RGBa formát",
  "COLOR_EDITOR_HEX_BUTTON_TIP": "Hex formát",
  "COLOR_EDITOR_HSLA_BUTTON_TIP": "HSLa formát",
  "COLOR_EDITOR_0X_BUTTON_TIP": "Hexadecimální (0x) formát",
  "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR": "{0} (použito {1} krát)",
  "COLOR_EDITOR_USED_COLOR_TIP_PLURAL": "{0} (použito {1} krát)",
  "CMD_JUMPTO_DEFINITION": "Přejít na definici",
  "CMD_SHOW_PARAMETER_HINT": "Zobrazit nápovědu parametru",
  "NO_ARGUMENTS": "<žádné parametry>",
  "DETECTED_EXCLUSION_TITLE": "Inferenční problém JavaScript souboru",
  "DETECTED_EXCLUSION_INFO": "V aplikaci {APP_NAME} došlo k potížím se zpracováním <span class='dialog-filename'>{0}</span> .<br><br> Tento soubor již nebude zpracován pro rady ke kódu, skok na definici nebo rychlé úpravy. Chcete-li tento soubor znovu povolit, otevřete ve svém projektu <code>.phcode.json</code> a upravte soubor <code>jscodehints.detectedExclusions</code> .<br><br> Pravděpodobně se jedná o chybu aplikace {APP_NAME}. Pokud můžete poskytnout kopii tohoto souboru, <a href='https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue'>nahlaste prosím chybu</a> s odkazem na zde uvedený soubor.",
  "CMD_REFACTOR": "Refaktor",
  "CMD_EXTRACTTO_VARIABLE": "Extrahujte do proměnné",
  "CMD_EXTRACTTO_FUNCTION": "Extrahujte do funkce",
  "ERROR_TERN_FAILED": "Nelze získat data z Tern",
  "ERROR_EXTRACTTO_VARIABLE_NOT_VALID": "Výběr netvoří výraz",
  "ERROR_EXTRACTTO_FUNCTION_NOT_VALID": "Vybraný blok by měl představovat sadu příkazů nebo výraz",
  "ERROR_EXTRACTTO_VARIABLE_MULTICURSORS": "Extrakce do proměnné nefunguje v multikurzorech",
  "ERROR_EXTRACTTO_FUNCTION_MULTICURSORS": "Extract to Function nefunguje v multikurzorech",
  "EXTRACTTO_FUNCTION_SELECT_SCOPE": "Vyberte cílový rozsah",
  "EXTRACTTO_VARIABLE_SELECT_EXPRESSION": "Vyberte výraz",
  "CMD_REFACTORING_RENAME": "Přejmenovat",
  "CMD_REFACTORING_TRY_CATCH": "Zabalte do Try Catch",
  "CMD_REFACTORING_CONDITION": "Zabalit do stavu",
  "CMD_REFACTORING_GETTERS_SETTERS": "Vytvořte Gettry/Settery",
  "CMD_REFACTORING_ARROW_FUNCTION": "Převést na funkci šipky",
  "DESCRIPTION_CODE_REFACTORING": "Povolit/zakázat Refaktorování kódu JavaScript",
  "ERROR_TRY_CATCH": "Vyberte platný kód, který chcete zabalit do bloku Try-catch",
  "ERROR_WRAP_IN_CONDITION": "Vyberte platný kód, který chcete zabalit do bloku podmínky",
  "ERROR_ARROW_FUNCTION": "Umístěte kurzor do výrazu funkce",
  "ERROR_GETTERS_SETTERS": "Umístěte kurzor na člen výrazu objektu",
  "ERROR_RENAME_MULTICURSOR": "Nelze přejmenovat při použití více kurzorů",
  "ERROR_RENAME_QUICKEDIT": "Tento identifikátor nelze přejmenovat, protože se na něj odkazuje jinde mimo tuto funkci",
  "ERROR_RENAME_GENERAL": "Vybraný text nelze přejmenovat",
  "JSHINT_NAME": "JSHint",
  "CMD_ENABLE_QUICK_VIEW": "Rychlý náhled",
  "CMD_ENABLE_SELECTION_VIEW": "Zobrazení výběru",
  "TOOLTIP_CLICK_TO_EDIT_COLOR": "Klikněte zde pro úpravu barvy",
  "CMD_TOGGLE_RECENT_PROJECTS": "Nedávné projekty",
  "REMOVE_FROM_RECENT_PROJECTS": "Odebrat z nedávných projektů",
  "DOCS_MORE_LINK": "Více",
  "COLLAPSE_ALL": "Skrýt vše",
  "EXPAND_ALL": "Zobrazit vše",
  "COLLAPSE_CURRENT": "Skrýt aktuální",
  "EXPAND_CURRENT": "Zobrazit aktuální",
  "RECENT_FILES_DLG_HEADER": "Nedávné soubory",
  "RECENT_FILES_DLG_CLEAR_BUTTON_LABEL": "Průhledná",
  "RECENT_FILES_DLG_CLEAR_BUTTON_TITLE": "Vymažte soubory, které nejsou v pracovní sadě",
  "RECOVER_UNSAVED_FILES_TITLE": "Obnovit neuložené soubory?",
  "RECOVER_UNSAVED_FILES_MESSAGE": "Obnovit neuložené soubory z předchozí relace?",
  "RECOVER_UNSAVED_FILES_RESTORE": "Obnovit",
  "DISCARD_UNSAVED_FILES_RESTORE": "Vyřadit",
  "DESCRIPTION_CLOSE_BRACKETS": "true k automatickému uzavírání závorek",
  "DESCRIPTION_CLOSE_OTHERS_ABOVE": "false k odebrání \"Zavřít ostatní výše\" z kontextového menu pracovních souborů",
  "DESCRIPTION_CLOSE_OTHERS_BELOW": "false k odebrání \"Zavřít ostatní níže\" z kontextového menu pracovních souborů",
  "DESCRIPTION_CLOSE_OTHERS": "false k odebrání \"Zavřít ostatní\" z kontextového menu pracovních souborů",
  "DESCRIPTION_CLOSE_TAGS": "Nastavit možnosti uzavírání značek",
  "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS": "Pole značek, které by neměly být automaticky uzavírány",
  "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING": "Zavřít, pokud je napsán > otevírací značky",
  "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING": "Zavřít, pokud je napsán / uzavírací značky",
  "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS": "Pole značek, do kterých je po jejich otevření vložen prázdný řádek",
  "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD": "true k vygenerování záložek skrývajících kód vždy, když se změní úroveň odsazení",
  "DESCRIPTION_CODE_FOLDING_ENABLED": "true k povolení skrývání kódu",
  "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER": "true k zobrazení záložek skrývajících kód pouze pokud přejedete myší nad okrajem",
  "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL": "Limity, kolik úrovní do hloubky platí Skrýt vše",
  "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE": "Nejmenší počet řádků, pro které se objeví ikona pro skrytí kódu",
  "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES": "true k zapamatování skrytých částí pokud zavřete a znovu otevřete soubor nebo projekt",
  "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE": "true k povolení skrývání kódu při výběru textu v editoru",
  "DESCRIPTION_DISABLED_DEFAULT_EXTENSIONS": "Výchozí rozšíření, která jsou zakázána",
  "DESCRIPTION_ATTR_HINTS": "Povolit/zakázat nápovědy HTML vlastností",
  "DESCRIPTION_CSS_PROP_HINTS": "Povolit/zakázat nápovědy CSS/LESS/SCSS hodnot",
  "DESCRIPTION_JS_HINTS": "Povolit/zakázat nápovědy v JavaScriptu",
  "DESCRIPTION_JS_HINTS_TYPE_DETAILS": "Povolit/zakázat detaily o datových typech v nápovědách kódu u JavaScriptu",
  "DESCRIPTION_PREF_HINTS": "Povolit/zakázat nápovědy v preferencích",
  "DESCRIPTION_SPECIAL_CHAR_HINTS": "Povolit/zakázat nápovědy HTML entit",
  "DESCRIPTION_SVG_HINTS": "Povolit/zakázat nápovědy v SVG",
  "DESCRIPTION_HTML_TAG_HINTS": "Povolit/zakázat nápovědy HTML značek",
  "DESCRIPTION_URL_CODE_HINTS": "Povolit/zakázat nápovědy adres URL v HTML & CSS/LESS/SCSS",
  "DESCRIPTION_DRAG_DROP_TEXT": "Povolit/zakázat funkci Drag & Drop",
  "DESCRIPTION_HEALTH_DATA_TRACKING": "Povolit sledování hlášení o zdraví",
  "DESCRIPTION_HIGHLIGHT_MATCHES": "Povolit automatické zvýrazňování shodujících se výrazů v celém dokumentu",
  "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN": "Zvýraznit všechny výrazy shodující se s výrazem, na kterém je aktuálně kurzor (není nutný výběr výrazu)",
  "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY": "Zvýraznit pouze pokud je výběr kompletním výrazem",
  "DESCRIPTION_INSERT_HINT_ON_TAB": "true k vložení aktuálně vybrané nápovědy při tabulátoru",
  "DESCRIPTION_NO_HINTS_ON_DOT": "true k zamezení automatického zobrazení nápověd JS kódu, jestliže je napsaná .",
  "DESCRIPTION_JSHINT_OPTIONS": "Objekt s výchozími možnostmi pro JSHint. Všechny dostupné možnosti JSHint naleznete na následující adrese URL: https://jshint.com/docs/options/",
  "DESCRIPTION_LANGUAGE": "Vlastní nastavení jazyků",
  "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS": "Dodatečná mapování z přípony souboru na jméno jazyka",
  "DESCRIPTION_LANGUAGE_FILE_NAMES": "Dodatečná mapování z názvu souboru na jméno jazyka",
  "DESCRIPTION_LINEWISE_COPY_CUT": "Provádění kopírování a vyjímání, když není žádný výběr, zkopíruje nebo vyjme celé řádky, které obsahují kurzory",
  "DESCRIPTION_INPUT_STYLE": "Vybírá způsob, jakým CodeMirror zpracovává vstup a zaměření. Může to být textarea, což je výchozí, nebo contenteditable, což je lepší pro čtečky obrazovky (nestabilní)",
  "DESCRIPTION_LINTING_ENABLED": "true k povolení panelu zpráv",
  "DESCRIPTION_ASYNC_TIMEOUT": "Čas v milisekundách, po kterém vyprší asynchronní lintery",
  "DESCRIPTION_LINTING_PREFER": "Pole linterů spouštěných nejdříve",
  "DESCRIPTION_LIVE_DEV_MULTIBROWSER": "true k povolení experimentálního živého náhledu",
  "DESCRIPTION_USE_PREFERED_ONLY": "true ke spuštění poskytovatelů určených pouze v linting.prefer",
  "DESCRIPTION_MAX_CODE_HINTS": "Maximální počet současně zobrazených nápověd kódu",
  "DESCRIPTION_PATH": "Vlastní nastavení cest",
  "DESCRIPTION_PROXY": "URL proxy serveru použitého k instalaci doplňků",
  "DESCRIPTION_SCROLL_PAST_END": "true k povolení rolování za konec dokumentu",
  "DESCRIPTION_SHOW_CODE_HINTS": "false k zakázání všech nápověd kódu",
  "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING": "Při výběru textu nechat zobrazený blikající kurzor",
  "DESCRIPTION_SHOW_LINE_NUMBERS": "true ke zobrazení čísel řádků na okraji vlevo od kódu",
  "DESCRIPTION_SMART_INDENT": "Automaticky odsadit při vytvoření nového bloku",
  "DESCRIPTION_SOFT_TABS": "false k zamezení nahrazování tabulátorů mezerami",
  "DESCRIPTION_SORT_DIRECTORIES_FIRST": "true k řazení složek nahoru ve stromu souborů projektu",
  "DESCRIPTION_SPACE_UNITS": "Počet mezer použitých v odsazení mezerami",
  "DESCRIPTION_STATIC_SERVER_PORT": "Síťový port, který by zabudovaný server měl použít pro živý náhled",
  "DESCRIPTION_STYLE_ACTIVE_LINE": "true ke zvýraznění řádku, na kterém se nachází kurzor, barvou na pozadí",
  "DESCRIPTION_TAB_SIZE": "Počet zobrazených mezer místo tabulátoru",
  "DESCRIPTION_USE_TAB_CHAR": "true k používání tabulátorů místo mezer",
  "DESCRIPTION_UPPERCASE_COLORS": "true k vygenerování hex barev velkými písmeny v Inline Color Editor",
  "DESCRIPTION_WORD_WRAP": "Zalomit řádky přesahující šířku viewportu",
  "DESCRIPTION_SEARCH_AUTOHIDE": "Zavřete vyhledávání, jakmile je editor zaměřen",
  "DESCRIPTION_DETECTED_EXCLUSIONS": "Seznam souborů, u kterých bylo zjištěno, že způsobují, že se Tern vymkne kontrole",
  "DESCRIPTION_INFERENCE_TIMEOUT": "Doba, po jejímž uplynutí Tern při snaze porozumět souborům vyprší",
  "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR": "true ke zobrazení chyb ve stavovém řádku",
  "DESCRIPTION_QUICK_VIEW_ENABLED": "true k povolení rychlého náhledu",
  "DESCRIPTION_SELECTION_VIEW_ENABLED": "true pro povolení zobrazení výběru",
  "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW": "true ke zobrazení náhledů obrázků pro chybějící přípony URL",
  "DESCRIPTION_NUMBER_QUICK_VIEW": "true pro zobrazení rychlého náhledu po najetí myší na čísla v editoru",
  "DESCRIPTION_THEME": "Vybrat motiv {APP_NAME}",
  "DESCRIPTION_USE_THEME_SCROLLBARS": "true k povolení vlastních posuvníků",
  "DESCRIPTION_LINTING_COLLAPSED": "true ke skrytí panelu linteru",
  "DESCRIPTION_FONT_FAMILY": "Změnit písmo",
  "DESCRIPTION_DESKTOP_ZOOM_SCALE": "Zvolte faktor měřítka přiblížení v rozsahu od 0,1 (pro kompaktnější zobrazení) do 2 (pro větší, více zvětšený pohled). Dostupné pouze v aplikacích pro stolní počítače",
  "DESCRIPTION_FONT_SIZE": "Změnit velikost písma, např. 13px",
  "DESCRIPTION_FIND_IN_FILES_NODE": "true k povolení vyhledávání založeného na Node",
  "DESCRIPTION_FIND_IN_FILES_INSTANT": "true k povolení okamžitého vyhledávání",
  "DESCRIPTION_FONT_SMOOTHING": "Pouze pro Mac: \"subpixel-antialiased\" k povolení sub-pixel vyhlazování nebo \"antialiased\" k vyhlazování v odstínech šedi",
  "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW": "false k zamezení otevírání souboru s preferencemi v rozděleném editoru",
  "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE": "false k otevření souboru s preferencemi v levém/horním panelu",
  "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED": "true ke skrytí panelů po zavření posledního souboru z panelu pomocí tlačítka na hlavičce panelu",
  "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS": "Změňte ke zobrazení tlačítek zavřít a rozdělit ve hlavičce.",
  "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT": "/*\n * Toto je soubor pouze pro čtení s podporovanými preferencemi\n * od aplikace {APP_NAME}.\n * Použijte tento soubor jako referenci pro úpravu vašich preferencí\n * soubor \"phcode.json\" otevřený v druhém panelu.\n * Další informace o tom, jak používat předvolby uvnitř\n * {APP_NAME}, viz webovou stránku https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences\n */",
  "DEFAULT_PREFERENCES_JSON_DEFAULT": "Výchozí",
  "DESCRIPTION_PURE_CODING_SURFACE": "true k povolení módu pouze s kódem a ke skrytí Všech dalších UI prvků v {APP_NAME}",
  "DESCRIPTION_INDENT_LINE_COMMENT": "true pro povolení odsazení řádků komentářů",
  "DESCRIPTION_RECENT_FILES_NAV": "Povolit/zakázat navigaci v posledních souborech",
  "DESCRIPTION_LIVEDEV_WEBSOCKET_PORT": "Port, na kterém běží WebSocket Server pro živý náhled",
  "DESCRIPTION_LIVE_DEV_HIGHLIGHT_SETTINGS": "Živý náhled Nastavení zvýraznění",
  "DESCRIPTION_LIVEDEV_ENABLE_REVERSE_INSPECT": "false pro zakázání zpětné kontroly živého náhledu",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW": "Nic k náhledu!",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW_DETAILS": "Vyberte soubor HTML pro náhled",
  "DESCRIPTION_LIVEDEV_PREVIEW_RESTRICTED": "Náhled není k dispozici!",
  "DESCRIPTION_LIVEDEV_PREVIEW_RESTRICTED_DETAILS": "Tento soubor HTML není součástí aktuálního projektu. Z bezpečnostních důvodů lze živý náhled zobrazit pouze u souborů projektu. Chcete-li zobrazit náhled tohoto souboru, otevřete složku obsahující jeho složku jako samostatný projekt.",
  "DESCRIPTION_LIVEDEV_MAIN_HEADING": "A jé!<br> Váš aktuální prohlížeč nepodporuje živý náhled.",
  "DESCRIPTION_LIVEDEV_MAIN_SPAN": "Získejte nejlepší zážitek z živého náhledu stažením našich nativních aplikací pro Windows, Mac a Linux z <a href=\"https://phcode.io\" style=\"color: white\">phcode.io</a> .<br>",
  "DESCRIPTION_LIVEDEV_SECURITY_POPOUT_MESSAGE": "Chystáte se otevřít soubor pro živý náhled. Pokračujte prosím, pouze pokud důvěřujete zdroji tohoto projektu. Pokračujte kliknutím na „Důvěřovat projektu“, nebo pokud nedůvěřujete zdroji, toto okno zavřete.",
  "DESCRIPTION_LIVEDEV_SECURITY_TRUST_MESSAGE": "Chystáte se otevřít soubor pro živý náhled. Pokračujte kliknutím na „Důvěřovat projektu“ pouze v případě, že důvěřujete zdroji tohoto projektu!",
  "CONFIRM_EXTERNAL_BROWSER_TITLE": "Vyskakovací okna blokována",
  "CONFIRM_EXTERNAL_BROWSER_MESSAGE": "Chcete povolit, aby stránka živého náhledu otevřela tuto adresu URL: {0}?",
  "TRUST_PROJECT": "Trust & Execute Preview – {0}",
  "TRUST_AUTHORS": "Důvěřujete autorům tohoto projektu?",
  "DOWNLOAD_FAILED": "Stažení se nezdařilo.",
  "DOWNLOAD_COMPLETE": "Stahování dokončeno!",
  "UPDATE_SUCCESSFUL": "Aktualizace proběhla úspěšně!",
  "UPDATE_FAILED": "Aktualizace selhala!",
  "VALIDATION_FAILED": "Ověření se nezdařilo!",
  "INITIALISATION_FAILED": "Inicializace se nezdařila!",
  "CLEANUP_FAILED": "Čištění se nezdařilo!",
  "WARNING_TYPE": "Varování!",
  "CLICK_RESTART_TO_UPDATE": "Klepnutím na Restartovat aktualizujte závorky.",
  "UPDATE_ON_NEXT_LAUNCH": "Aktualizace bude použita při opětovném spuštění.",
  "GO_TO_SITE": "Přejděte na <a href = \"http://brackets.io/\">brackets.io</a> a zkuste to znovu.",
  "INTERNET_UNAVAILABLE": "Není k dispozici připojení k internetu.",
  "UPDATEDIR_READ_FAILED": "Aktualizovat adresář nelze přečíst.",
  "UPDATEDIR_CLEAN_FAILED": "Aktualizační adresář nelze vyčistit.",
  "INITIAL_DOWNLOAD": "Stahování aktualizace...",
  "RETRY_DOWNLOAD": "Stažení se nezdařilo. Opakuji...Pokus",
  "VALIDATING_INSTALLER": "Stahování dokončeno! Ověřování instalačního programu...",
  "CHECKSUM_DID_NOT_MATCH": "Kontrolní součet se neshodoval.",
  "INSTALLER_NOT_FOUND": "Instalační program nebyl nalezen.",
  "DOWNLOAD_ERROR": "Při stahování došlo k chybě.",
  "NETWORK_SLOW_OR_DISCONNECTED": "Síť je odpojená nebo příliš pomalá.",
  "RESTART_BUTTON": "Restartujte",
  "LATER_BUTTON": "Později",
  "DESCRIPTION_AUTO_UPDATE": "Povolit/zakázat automatickou aktualizaci závorek",
  "AUTOUPDATE_ERROR": "Chyba!",
  "AUTOUPDATE_IN_PROGRESS": "Aktualizace již probíhá.",
  "NUMBER_WITH_PERCENTAGE": "{0} %",
  "CMD_FIND_RELATED_FILES": "Najít související soubory",
  "PHP_VERSION_INVALID": "Chyba při analýze verze PHP. Zkontrolujte prosím výstup příkazu „php –version“.",
  "PHP_UNSUPPORTED_VERSION": "Nainstalujte si běhové prostředí PHP7 pro umožnění nástrojů souvisejících s PHP, jako jsou rady pro kód, rady parametrů, skok na definici a další. Nalezená verze: {0}",
  "PHP_EXECUTABLE_NOT_FOUND": "Runtime PHP nebyl nalezen. Nainstalujte běhové prostředí PHP7 a odpovídajícím způsobem aktualizujte „executablePath“ v předvolbách PHP. To umožňuje nástroje související s PHP, jako jsou rady pro kód, rady parametrů, skok na definici a další.",
  "PHP_PROCESS_SPAWN_ERROR": "Při spouštění procesu PHP byl zjištěn kód chyby {0}.",
  "PHP_SERVER_ERROR_TITLE": "Chyba",
  "PHP_SERVER_MEMORY_LIMIT_INVALID": "Zadaný limit paměti je neplatný. Zkontrolujte předvolby PHP a nastavte správnou hodnotu.",
  "DESCRIPTION_PHP_TOOLING_CONFIGURATION": "Výchozí nastavení konfigurace PHP Tooling",
  "OPEN_PREFERENNCES": "Otevřete Předvolby",
  "LANGUAGE_TOOLS_PREFERENCES": "Předvolby pro jazykové nástroje",
  "FIND_ALL_REFERENCES": "Najít všechny reference",
  "REFERENCES_IN_FILES": "Reference",
  "REFERENCE_IN_FILES": "odkaz",
  "REFERENCES_NO_RESULTS": "Pro aktuální pozici kurzoru nejsou k dispozici žádné odkazy",
  "CMD_FIND_DOCUMENT_SYMBOLS": "Najít symboly dokumentů",
  "CMD_FIND_PROJECT_SYMBOLS": "Najděte symboly projektu",
  "REMOTE_DEBUGGING_ENABLED": "Vzdálené ladění povoleno na localhost:",
  "REMOTE_DEBUGGING_PORT_INVALID": "Nelze povolit vzdálené ladění na portu {0}. Čísla portů by měla být mezi {1} a {2}.",
  "DESCRIPTION_EXTERNAL_APPLICATION_ASSOCIATE": "Mapování přípon souborů na externí aplikace. Syntaxe: \"<typ_souboru>\": \"<výchozí|název_aplikace|Cesta aplikace>\", \"výchozí\" použijte k otevření souborů v systémové výchozí aplikaci pro daný typ souboru.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_TITLE": "Otevřete grafické soubory v externích editorech.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_MSG": "Vaše aktuální složka obsahuje typy grafických souborů, které aplikace {APP_NAME} nepodporuje.<br/> Nyní můžete přidružit konkrétní typy souborů k externím editorům. Po přiřazení můžete otevřít grafické soubory jako .xd, .psd, .jpg, .png, .ai, .svg v jejich výchozích aplikacích dvojitým kliknutím na soubory ve Stromu souborů.<br/><br/> Kliknutím na tlačítko „OK“ přiřadíte typy grafických souborů k jejich příslušným výchozím aplikacím.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_CNF_MSG": "Následující typy souborů byly úspěšně spojeny s výchozími aplikacemi.<br/> (",
  "UNSUPPORTED_BROWSER_TITLE": "Prohlížeč není podporován",
  "UNSUPPORTED_BROWSER_MESSAGE": "Použijte prosím moderní prohlížeč (vydaný během posledních 3 let).",
  "UNSUPPORTED_BROWSER_MOBILE_TITLE": "Mobilní prohlížeče nejsou podporovány",
  "UNSUPPORTED_BROWSER_MOBILE": "Prohlížeče pro mobily a tablety nejsou v současné době plně podporovány. Tento dialog můžete zavřít, ale některé funkce ve Phoenixu nebudou v tomto prohlížeči fungovat.<br/><br/> Pracujeme na vývoji nativních aplikací pro iOS a Android. <a href=\"https://github.com/phcode-dev/phoenix/discussions/1046\" target=\"_blank\">Zapojte se do diskuze zde!</a>",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER_TITLE": "Přístup k místní složce Prohlížeč nepodporuje",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER": "Je nám líto, zdá se, že váš aktuální prohlížeč nepodporuje otevírání místních složek. Pro tuto funkci doporučujeme používat Chrome, Edge nebo Opera.<br/><br/> Případně pracujeme na vývoji nativních aplikací pro Windows, Mac, Linux, iOS a Android, abychom poskytovali plnou podporu. <a href=\"https://github.com/phcode-dev/phoenix/discussions/1047\" target=\"_blank\">Zůstaňte naladěni na aktualizace!</a>",
  "ATTENTION_SAFARI_USERS": "Pozor uživatelé Safari",
  "ATTENTION_SAFARI_USERS_MESSAGE": "<span>Safari automaticky odstraní data webových stránek, pokud web znovu nenavštívíte do 7 dnů. Aplikace {APP_NAME} při ukládání vašich projektů spoléhá na úložiště prohlížeče, které může být kvůli této zásadě odstraněno.<br/><br/> Doporučujeme <strong>stáhnout si desktopovou aplikaci pro macOS</strong> z <a href='https://phcode.io' target='_blank' style='color: white'>https://phcode.io</a></span>",
  "CANNOT_PUBLISH_LARGE_PROJECT": "Nelze publikovat velký projekt",
  "CANNOT_PUBLISH_LARGE_PROJECT_MESSAGE": "Phoenix je stále v experimentální verzi alfa. Zatím jsme nepovolili synchronizaci projektů s více než 500 soubory.",
  "SHARE_WEBSITE": "Publikovat a sdílet web?",
  "PUBLISH": "Publikovat",
  "PUBLISH_CONSENT_MESSAGE": "Rychlý náhled změn a sdílení vašeho webu s ostatními. Phoenix pro vás může publikovat tyto webové stránky na adrese {0}. Zveřejněné odkazy budou platné po dobu 30 dnů. </br>Přejete si zveřejnit a sdílet svůj web?",
  "PUBLISH_SYNC_IN_PROGRESS": "Probíhá synchronizace pro náhled...",
  "PUBLISH_PAGE": "Klikněte pro publikování a sdílení tohoto webu",
  "PUBLISH_VIEW_PAGE": "Kliknutím zobrazíte publikovanou stránku",
  "MISSING_FIELDS": "Chybějící pole",
  "PLEASE_FILL_ALL_REQUIRED": "Vyplňte prosím všechna povinná pole zvýrazněná červeně",
  "CODE_EDITOR": "Editor kódu",
  "BUILD_THE_WEB": "Vytvořte web",
  "IMPORT_PROJECT": "Importovat projekt",
  "GITHUB_PROJECT": "Projekt GitHub",
  "NEW_PROJECT_FROM_GITHUB": "Nový projekt od GitHubu",
  "GITHUB_REPO_URL": "Adresa URL úložiště GitHub:",
  "CREATE_PROJECT": "Vytvořit projekt",
  "SETTING_UP_PROJECT": "Nastavení projektu",
  "LOCATION": "umístění:",
  "DOWNLOADING": "Stahování...",
  "DOWNLOADING_FILE": "Stahování souboru {0}...",
  "EXTRACTING_FILES_PROGRESS": "Rozbalování {0} z {1} souborů.",
  "COMPRESS_FILES_PROGRESS": "Komprese {0} z {1} souborů.",
  "DOWNLOAD_FAILED_MESSAGE": "Ujistěte se, že adresa URL ke stažení je platná. </br>Poznámka: Vzhledem k tomu, že Phoenix je ve verzi alfa, soukromé repozitáře a adresy URL GitHub větší než 25 MB nejsou povoleny.",
  "PLEASE_SELECT_A_FOLDER": "Vyberte prosím složku...",
  "UNZIP_IN_PROGRESS": "Rozbalování souborů...",
  "UNZIP_FAILED": "Chyba: Rozbalení se nezdařilo.",
  "CONFIRM_REPLACE_TITLE": "Potvrďte Nahradit",
  "KEEP_BOTH": "Nechat si oba",
  "EXPLORE": "HTML hry",
  "BLOG": "Blog",
  "PHOENIX_DEFAULT_PROJECT": "Výchozí projekt",
  "PROJECT_NAME": "Název projektu:",
  "NEW_HTML": "Nový HTML projekt",
  "LICENSE": "Licence a kredity:",
  "PREVIEW": "Náhled",
  "BUILD_WEBSITE": "Vytvořit web",
  "VIEW_MORE": "Zobrazit více...",
  "NEW_PROJECT_NOTIFICATION": "Kliknutím na tuto ikonu vytvoříte nový projekt.</br><img src=\"styles/images/new_project.png\"><br/> <a href='#' style='float:right;'>OK</a>",
  "BEAUTIFY_CODE_NOTIFICATION": "Chcete-li kód zkrášlit, klikněte sem nebo stiskněte <b>`{0}`</b> .</br><img src=\"styles/images/beautify.gif\"><br/> <a href='#' style='float:right;'>OK</a>",
  "DEFAULT_PROJECT_NOTIFICATION": "Kliknutím sem otevřete<br/> <b>výchozí projekt</b> ve Phoenixu.</br> <a href='#' style='float:right;'>OK</a>",
  "DIRECTORY_REPLACE_MESSAGE": "Vybraná složka <span class='dialog-filename'>{0}</span> není prázdná. Opravdu chcete nahradit obsah složky projektem?",
  "BUILD_WEBSITE_SECTION": "Vytvořit web",
  "LEARN_SECTION": "Učte se s příklady",
  "CREATE_EXTENSION_SECTION": "Vytvářejte rozšíření a motivy aplikace {APP_NAME}",
  "CREATE_EXTENSION": "Vytvořit rozšíření",
  "CREATE_THEME": "Vytvořit motiv",
  "WEBPAGE_HOME_PAGE": "Domovská stránka",
  "WEBPAGE_BLOG": "Blogová stránka",
  "WEBPAGE_DASHBOARD": "HTML Dashboard",
  "WEBPAGE_BOOTSTRAP_EXAMPLES": "Příklady bootstrapu",
  "PROJECTS_AT_A_GLANCE": "Přehled vašich projektů",
  "PROJECT_AT_GLANCE_DESCRIPTION": "Začněte sledováním videa.",
  "PROJECT_FROM_BROWSER": "Uloženo ve vašem prohlížeči",
  "PROJECT_FROM_BROWSER_TERSE": "Úložiště prohlížeče",
  "PROJECT_SHOW_ON_STARTUP": "Zobrazit tento dialog při spuštění",
  "GUIDED_LIVE_PREVIEW": "Chcete-li zobrazit živý náhled, proveďte v souboru HTML nějaké změny kódu.</br> <a href='#' style='float:right;'>OK</a>",
  "GUIDED_LIVE_PREVIEW_POPOUT": "Klepnutím na toto tlačítko zobrazíte živý náhled na novou kartu.</br> <a href='#' style='float:right;'>OK</a>",
  "ENJOYING_APP": "Líbí se vám aplikace {APP_NAME}?",
  "GITHUB_STARS_POPUP": "<div>Vaše recenze udržují náš malý tým motivovaný k tomu, aby byl <b>phcode.dev</b> ještě lepší.<br/> Označte nás hvězdičkou na GitHubu:",
  "GITHUB_STARS_POPUP_TWITTER": "Poskytněte zpětnou vazbu nebo ji rozšiřte na Twitteru:",
  "TEST_TRANSLATE": "použijte k testování překladů",
  "POWER_USER_POPUP_TITLE": "Jak pro vás můžeme vylepšit aplikaci {APP_NAME}?",
  "POWER_USER_POPUP_TEXT": "<div>Rádi bychom od vás dostali zpětnou vazbu. Vaše zpětná vazba nám pomáhá rozhodnout se, které funkce vytvořit a jaká vylepšení by měla být na naší platformě provedena.<br/> <a>Vyplňte prosím tento krátký dotazník.</a></div>",
  "BEAUTIFY_ERROR": "Kód se nepodařilo zkrášlit. Zkontrolujte syntaxi.",
  "BEAUTIFY_ERROR_ORIGINAL_CHANGED": "Nešlo zkrášlit. Text editoru změněn po zkrášlení.",
  "BEAUTIFY_PROJECT_BUSY_MESSAGE": "Zkrášlující soubor {0}",
  "BEAUTIFY_ERROR_SELECTION": "Nelze zkrášlit.</br>Vybrali jste neúplný blok kódu nebo neplatnou syntaxi.",
  "BEAUTIFY_OPTIONS": "Možnosti, které řídí, jak Beautify Code funguje",
  "BEAUTIFY_OPTION_PRINT_WIDTH": "Zadejte délku čáry, na kterou se zkrášlovač zalomí",
  "BEAUTIFY_OPTION_SEMICOLON": "Na konec každého příkazu přidejte středník",
  "BEAUTIFY_OPTION_SINGLE_QUOTE": "Místo dvojitých uvozovek používejte jednoduché uvozovky",
  "BEAUTIFY_OPTION_QUOTE_PROPS": "Změna, když jsou vlastnosti v objektech citovány",
  "BEAUTIFY_OPTION_BRACKET_SAME_LINE": "Umístěte > víceřádkového prvku HTML (HTML, JSX, Vue, Angular) na konec posledního řádku namísto toho, abyste byli sami na dalším řádku (neplatí pro samozavírací prvky)",
  "BEAUTIFY_OPTION_SINGLE_ATTRIBUTE_PER_LINE": "Vynutit jeden atribut na řádek v HTML, Vue a JSX",
  "BEAUTIFY_OPTION_PROSE_WRAP": "Zabalte prózu, pokud přesahuje šířku tisku do souborů značek",
  "BEAUTIFY_OPTION_PRINT_TRAILING_COMMAS": "Pokud je to možné, vytiskněte koncové čárky ve víceřádkových syntaktických strukturách oddělených čárkami"
});