/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "Idioma predeterminado",
  "PROJECT_BUSY": "Proyecto Operaciones En Progreso",
  "DUPLICATING": "Duplicando {0}",
  "MOVING": "Moviendo {0}",
  "COPYING": "Copiando {0}",
  "DELETING": "Eliminando {0}",
  "RENAMING": "Renombrar",
  "GENERIC_ERROR": "(error {0})",
  "NOT_FOUND_ERR": "No se pudo encontrar el archivo/directorio.",
  "NOT_READABLE_ERR": "No se pudo leer el archivo/directorio.",
  "EXCEEDS_MAX_FILE_SIZE": "Los archivos de más de {0} MB no se pueden abrir en {APP_NAME}.",
  "NO_MODIFICATION_ALLOWED_ERR": "El directorio de destino no se puede modificar.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "Los permisos no permiten hacer modificaciones.",
  "CONTENTS_MODIFIED_ERR": "El archivo fue modificado fuera de {APP_NAME}.",
  "UNSUPPORTED_ENCODING_ERR": "{APP_NAME} actualmente solo soporta archivos codificados como UTF-8.",
  "ENCODE_FILE_FAILED_ERR": "{APP_NAME} no pudo codificar el contenido del archivo.",
  "DECODE_FILE_FAILED_ERR": "{APP_NAME} no pudo descodificar el contenido del archivo.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "{APP_NAME} actualmente no admite archivos de texto codificados en UTF-16.",
  "FILE_EXISTS_ERR": "El archivo ya existe.",
  "FILE": "archivo",
  "FILE_TITLE": "Archivo",
  "DIRECTORY": "directorio",
  "DIRECTORY_TITLE": "directorio",
  "DIRECTORY_NAMES_LEDE": "nombres de directorios",
  "FILENAMES_LEDE": "nombres de archivos",
  "FILENAME": "nombre de archivo",
  "DIRECTORY_NAME": "nombre de directorio",
  "ERROR_LOADING_PROJECT": "Error abriendo el proyecto",
  "OPEN_DIALOG_ERROR": "Ha ocurrido un error al mostrar el aviso de apertura de archivo. (error {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "Ha ocurrido un error al intentar abrir el directorio <span class='dialog-filename'>{0}</span>. (error {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "Ha ocurrido un error al leer los contenidos del directorio <span class='dialog-filename'>{0}</span>. (error {1})",
  "ERROR_OPENING_FILE_TITLE": "Error abriendo el archivo",
  "ERROR_OPENING_FILE": "Ha ocurrido un error al intentar abrir el archivo <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_OPENING_FILES": "Ha ocurrido un error al intentar abrir los siguientes archivos:",
  "ERROR_RELOADING_FILE_TITLE": "Error recargando cambios desde disco",
  "ERROR_RELOADING_FILE": "Ha ocurrido un error al intentar recargar el archivo <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_SAVING_FILE_TITLE": "Error guardando el archivo",
  "ERROR_SAVING_FILE": "Ha ocurrido un error al intentar guardar el archivo <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_FILE_TITLE": "Error renombrando el {0}",
  "ERROR_RENAMING_FILE": "Ha ocurrido un error al intentar renombrar el {2} <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "El archivo o directorio no forma parte del proyecto abierto actualmente. Desafortunadamente, solo los archivos de proyecto se pueden renombrar en este punto.",
  "ERROR_MOVING_FILE_TITLE": "Error al mover {0}",
  "ERROR_MOVING_FILE": "Ocurrió un error al intentar mover el {2} <span class='dialog-filename'>{0}</span> . {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "No se puede mover el archivo o la carpeta, ya que no forman parte del proyecto actual.",
  "ERROR_DELETING_FILE_TITLE": "Error eliminando el {0}",
  "ERROR_DELETING_FILE": "Ha ocurrido un error al intentar eliminar el {2} <span class='dialog-filename'>{0}</span>. {1}",
  "INVALID_FILENAME_TITLE": "{0} inválido",
  "CANNOT_PASTE_TITLE": "No se puede pegar {0}",
  "ERR_TYPE_PASTE_FAILED": "Ocurrió un error al pegar <span class='dialog-filename'>{0}</span> a <span class='dialog-filename'>{1}</span>",
  "CANNOT_DUPLICATE_TITLE": "no se puede duplicar",
  "ERR_TYPE_DUPLICATE_FAILED": "Ocurrió un error al duplicar <span class='dialog-filename'>{0}</span>",
  "INVALID_FILENAME_MESSAGE": "Los {0} no pueden utilizar ninguna palabra reservada por el sistema, terminar con puntos (.) o utilizar cualquiera de los siguientes caracteres: <code class='emphasized'>{1}</code>",
  "ENTRY_WITH_SAME_NAME_EXISTS": "Ya existe un archivo o directorio con el nombre <span class='dialog-filename'>{0}</span>.",
  "ERROR_CREATING_FILE_TITLE": "Error creando {0}",
  "ERROR_CREATING_FILE": "Ha ocurrido un error al intentar crear el {0} <span class='dialog-filename'>{1}</span>. {2}",
  "ERROR_MIXED_DRAGDROP": "No es posible abrir una carpeta y otros archivos al mismo tiempo.",
  "ERROR_KEYMAP_TITLE": "Ocurrió un error leyendo los atajos de teclado",
  "ERROR_KEYMAP_CORRUPT": "El archivo de atajos de teclado no tiene un formato JSON válido. El archivo se abrirá para que puedas corregir el formato.",
  "ERROR_LOADING_KEYMAP": "El archivo de atajos de teclado no está codificado como UTF-8 y no puede ser cargado.",
  "ERROR_RESTRICTED_COMMANDS": "No puedes reasignar atajos de teclado a los siguientes comandos: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "No puedes reasignar los siguientes atajos de teclado: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "Estas reasignando múltiples atajos de teclado a los siguientes comandos: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "Hay múltiples apariciones de los siguientes atajos de teclado: {0}",
  "ERROR_INVALID_SHORTCUTS": "Los siguientes atajos de teclado son inválidos: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "Estas asignando atajos de teclado a commandos inexistentes: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "Error leyendo las preferencias",
  "ERROR_PREFS_CORRUPT": "El archivo de preferencias no tiene un formato JSON válido. El archivo se abrirá para que puedas corregir el formato. Luego deberás reiniciar {APP_NAME} para que los cambios surtan efecto.",
  "ERROR_PROJ_PREFS_CORRUPT": "El archivo de preferencias para el proyecto no tiene un formato JSON válido. El archivo se abrirá para que puedas corregir el formato. Luego deberás recargar el proyecto para que los cambios surtan efecto.",
  "ERROR_IN_BROWSER_TITLE": "Vaya... parece que {APP_NAME} todavía no funciona en navegadores.",
  "ERROR_IN_BROWSER": "{APP_NAME} está desarrollado en HTML, pero por ahora funciona como una aplicación de escritorio para que puedas editar archivos localmente. Por favor, utiliza la aplicación del repositorio <b>github.com/adobe/brackets-shell</b> para ejecutar {APP_NAME}.",
  "ERROR_MAX_FILES_TITLE": "Error indexando archivos",
  "ERROR_MAX_FILES": "Este proyecto contiene más de 30.000 archivos. Funciones que operan sobre múltiples archivos pueden estar deshabilitadas o funcionar igual que si el proyecto estuviese vacío. <a href='https://github.com/adobe/brackets/wiki/Large-Projects'>Leer más acerca de cómo trabajar con proyectos grandes</a>.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "Error iniciando el navegador",
  "ERROR_CANT_FIND_CHROME": "No se pudo encontrar el navegador Google Chrome. Por favor, asegúrate que esté instalado correctamente.",
  "ERROR_LAUNCHING_BROWSER": "Ha ocurrido un error al iniciar el navegador. (error {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "Error en la Vista previa dinámica",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "Conectando con el navegador",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "Para poder iniciar el modo de Vista previa dinámica, Chrome debe ser iniciado habilitando la depuración remota.<br><br>¿Quieres reiniciar Chrome y habilitar la depuración remota?<br><br>",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "No se pudo cargar la página para la Vista previa dinámica.",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "Necesitas especificar una URL base en este proyecto para poder iniciar la Vista previa dinámica con archivos de servidor.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "Error iniciando el servidor HTTP para la Vista previa dinámica. Vuelve a intentarlo, por favor.",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "Para más información, consulta <a href='{0}' title='{0}'>Resolución de Problemas de conexión en Vista previa dinámica</a>.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "Vista previa dinámica",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "Vista previa dinámica: Conectando…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "Vista previa dinámica: Inicializando…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "Terminar la Vista previa dinámica",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "Vista previa dinámica",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "Seleccionar archivo para vista previa en vivo",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "Recargar página",
  "LIVE_DEV_CLICK_POPOUT": "Vista previa emergente en vivo a una nueva ventana",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "Pin en Unpin Preview Page",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "Vista previa dinámica (no se está actualizando debido a un error de sintaxis)",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "Vista previa dinámica se ha detenido porque se han abierto las herramientas de desarrollo",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "Vista previa dinámica se ha detenido porque se ha cerrado la página en el navegador",
  "LIVE_DEV_NAVIGATED_AWAY": "Vista previa dinámica se ha detenido porque se ha accedido a una página que no es parte del proyecto actual",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "Vista previa dinámica se ha detenido por motivos desconocidos ({0})",
  "SAVE_CLOSE_TITLE": "Guardar cambios",
  "SAVE_CLOSE_MESSAGE": "¿Quieres guardar los cambios existentes en el documento <span class='dialog-filename'>{0}</span>?",
  "SAVE_CLOSE_MULTI_MESSAGE": "¿Quieres guardar tus cambios en los siguientes documentos?",
  "EXT_MODIFIED_TITLE": "Cambios externos",
  "CONFIRM_DELETE_TITLE": "Confirmar eliminación",
  "CONFIRM_FILE_DELETE": "¿Está seguro de que desea eliminar el archivo <span class='dialog-filename'>{0}</span> ?",
  "CONFIRM_FOLDER_DELETE": "¿Estás seguro que deseas eliminar el directorio <span class='dialog-filename'>{0}</span>?",
  "FILE_DELETED_TITLE": "Archivo eliminado",
  "EXT_MODIFIED_WARNING": "<span class='dialog-filename'>{0}</span> ha sido modificado en el disco fuera de {APP_NAME}.<br><br>¿Deseas guardar el archivo y sobrescribir esos cambios?",
  "EXT_MODIFIED_MESSAGE": "<span class='dialog-filename'>{0}</span> ha sido modificado en el disco fuera de {APP_NAME}, pero también tiene cambios en {APP_NAME}.<br><br>¿Qué versión quieres conservar?",
  "EXT_DELETED_MESSAGE": "<span class='dialog-filename'>{0}</span> ha sido eliminado en el disco fuera de {APP_NAME}, pero tiene cambios sin guardar en {APP_NAME}.<br><br>¿Quieres conservar tus cambios?",
  "WINDOW_UNLOAD_WARNING": "¿Está seguro de que desea navegar a una URL diferente y salir de Brackets?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "¡Usted tiene cambios no guardados! ¿Está seguro de que desea navegar a una URL diferente y salir de Brackets?",
  "DONE": "Aceptar",
  "OK": "Aceptar",
  "CANCEL": "Cancelar",
  "DONT_SAVE": "No guardar",
  "SAVE": "Guardar",
  "SAVE_AS": "Guardar como…",
  "SAVE_AND_OVERWRITE": "Sobrescribir",
  "DELETE": "Eliminar",
  "BUTTON_YES": "Sí",
  "BUTTON_NO": "No",
  "FIND_MATCH_INDEX": "{0} de {1}",
  "FIND_NO_RESULTS": "No hay resultados",
  "FIND_QUERY_PLACEHOLDER": "Buscar…",
  "FIND_HISTORY_MAX_COUNT": "Número máximo de elementos de búsqueda en el historial de búsqueda",
  "REPLACE_PLACEHOLDER": "Reemplazar con…",
  "BUTTON_REPLACE_ALL": "Todo…",
  "BUTTON_REPLACE_BATCH": "Lote…",
  "BUTTON_REPLACE_ALL_IN_FILES": "Reemplazar…",
  "BUTTON_REPLACE": "Reemplazar",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "Coincidencia siguiente",
  "BUTTON_PREV_HINT": "Coincidencia anterior",
  "BUTTON_CASESENSITIVE_HINT": "Sensible a mayúsculas",
  "BUTTON_REGEXP_HINT": "Expresión regular",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "Reemplazar sin deshacer",
  "REPLACE_WITHOUT_UNDO_WARNING": "Dado que hay más de {0} archivos que necesitan ser modificados, {APP_NAME} modificará los archivos no abiertos en el disco.<br>Por lo tanto, no será posible deshacer los reemplazos en esos archivos.",
  "BUTTON_REPLACE_WITHOUT_UNDO": "Reemplazar sin deshacer",
  "OPEN_FILE": "Abrir archivo",
  "SAVE_FILE_AS": "Guardar archivo",
  "CHOOSE_FOLDER": "Elige una carpeta",
  "RELEASE_NOTES": "Notas de la versión",
  "NO_UPDATE_TITLE": "¡Estás actualizado!",
  "NO_UPDATE_MESSAGE": "Estás utilizando la última versión de {APP_NAME}.",
  "FIND_REPLACE_TITLE_LABEL": "Reemplazar",
  "FIND_REPLACE_TITLE_WITH": "con",
  "FIND_TITLE_LABEL": "Se encontró",
  "FIND_TITLE_SUMMARY": "&mdash; {0} {1} {2} en {3}",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "en <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_NO_SCOPE": "en el proyecto",
  "FIND_IN_FILES_ZERO_FILES": "El filtro excluye todos los archivos {0}",
  "FIND_IN_FILES_FILE": "archivo",
  "FIND_IN_FILES_FILES": "archivos",
  "FIND_IN_FILES_MATCH": "coincidencia",
  "FIND_IN_FILES_MATCHES": "coincidencias",
  "FIND_IN_FILES_MORE_THAN": "Más de ",
  "FIND_IN_FILES_PAGING": "{0}&mdash;{1}",
  "FIND_IN_FILES_FILE_PATH": "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "Ctrl/Cmd clic para expandir/colapsar todo",
  "FIND_IN_FILES_INDEXING": "Indexando archivos para la Búsqueda instantánea…",
  "FIND_IN_FILES_INDEXING_PROGRESS": "Indexando {0} de {1} archivos para búsqueda instantánea...",
  "REPLACE_IN_FILES_ERRORS_TITLE": "Errores al reemplazar",
  "REPLACE_IN_FILES_ERRORS": "Los siguientes archivos no fueron modificados porque cambiaron después de realizar la búsqueda o no pueden ser escritos.",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "Error obteniendo información sobre actualizaciones",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "Ocurrió un problema al obtener la información sobre las últimas actualizaciones desde el servidor. Por favor, asegúrate de estar conectado a Internet y vuelve a intentarlo.",
  "NEW_FILE_FILTER": "Nuevo conjunto de filtros…",
  "CLEAR_FILE_FILTER": "No excluir archivos",
  "NO_FILE_FILTER": "No hay archivos excluidos",
  "EXCLUDE_FILE_FILTER": "Excluir {0}",
  "EDIT_FILE_FILTER": "Editar…",
  "FILE_FILTER_DIALOG": "Editar conjunto de filtros",
  "FILE_FILTER_INSTRUCTIONS": "Excluir archivos y carpetas que coincidan con alguna de las siguientes cadenas / subcadenas o <a href='{0}' title='{0}'>comodines</a>. Ingrese una cadena por línea.",
  "FILTER_NAME_PLACEHOLDER": "Nombrar este conjunto de filtros (opcional)",
  "FILTER_NAME_REMAINING": "{0} caracteres restantes",
  "FILE_FILTER_CLIPPED_SUFFIX": "y {0} más",
  "FILTER_COUNTING_FILES": "Contando archivos…",
  "FILTER_FILE_COUNT": "Permite {0} de {1} archivos {2}",
  "FILTER_FILE_COUNT_ALL": "Permite todos los {0} archivos {1}",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "La Edición Rápida no está disponible para la posición actual del cursor",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "Edición Rápida para CSS: ubique el cursor sobre el nombre de una clase",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "Edición Rápida para CSS: atributo de clase incompleto",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "Edición Rápida para CSS: atributo de identificación incompleto",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "Edición Rápida para CSS: ubique el cursor sobre una etiqueta, clase o id",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "Edición Rápida para Funciones de Temporización de CSS: sintaxis inválida",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "Edición Rápida para JS: ubique el cursor sobre el nombre de una función",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "La Documentación Rápida no está disponible para la posición actual del cursor",
  "PROJECT_LOADING": "Cargando…",
  "UNTITLED": "Sin título",
  "WORKING_FILES": "Área de trabajo",
  "TOP": "Arriba",
  "BOTTOM": "Abajo",
  "LEFT": "Izquierda",
  "RIGHT": "Derecha",
  "CMD_SPLITVIEW_NONE": "No dividido",
  "CMD_SPLITVIEW_VERTICAL": "División vertical",
  "CMD_SPLITVIEW_HORIZONTAL": "División horizontal",
  "SPLITVIEW_MENU_TOOLTIP": "Dividir el editor vertical u horizontalmente",
  "GEAR_MENU_TOOLTIP": "Configurar el área de trabajo",
  "SPLITVIEW_INFO_TITLE": "Ya está abierto",
  "SPLITVIEW_MULTIPANE_WARNING": "El archivo ya está abierto en otro panel. Próximamente {APP_NAME} soportará abrir el mismo archivo en más de un panel. Hasta entonces, el archivo se mostrará en el panel en el cual ya está abierto.<br><br>(Sólo verá este mensaje una vez.)",
  "STATUSBAR_CURSOR_POSITION": "Línea {0}, Columna {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": " — {0} columna seleccionada",
  "STATUSBAR_SELECTION_CH_PLURAL": " — {0} columnas seleccionadas",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " — {0} línea seleccionada",
  "STATUSBAR_SELECTION_LINE_PLURAL": " — {0} líneas seleccionadas",
  "STATUSBAR_SELECTION_MULTIPLE": " — {0} selecciones",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "Haz clic para usar espacios en la sangría",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "Haz clic para usar tabulaciones en la sangría",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "Haz clic para cambiar el número de espacios usados en la sangría",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "Haz clic para cambiar el ancho de las tabulaciones",
  "STATUSBAR_SPACES": "Espacios:",
  "STATUSBAR_TAB_SIZE": "Tamaño del tabulador:",
  "STATUSBAR_LINE_COUNT_SINGULAR": "— {0} línea",
  "STATUSBAR_LINE_COUNT_PLURAL": "— {0} líneas",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "Extensiones deshabilitadas",
  "STATUSBAR_INSERT": "INS",
  "STATUSBAR_OVERWRITE": "SOB",
  "STATUSBAR_INSOVR_TOOLTIP": "Haz clic para intercambiar entre el modo insertar (INS) y el modo sobrescribir (SOB)",
  "STATUSBAR_LANG_TOOLTIP": "Haz clic para cambiar el tipo de archivo",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. Haz clic para mostrar/ocultar el panel de reportes.",
  "STATUSBAR_DEFAULT_LANG": "(por defecto)",
  "STATUSBAR_SET_DEFAULT_LANG": "Marcar como predeterminado para los archivos .{0}",
  "STATUSBAR_ENCODING_TOOLTIP": "Seleccione la codificación",
  "ERRORS_PANEL_TITLE_MULTIPLE": "Problemas de {0}",
  "SINGLE_ERROR": "1 problema de {0}",
  "MULTIPLE_ERRORS": "{1} problemas de {0}",
  "NO_ERRORS": "No se encontraron problemas de {0} - ¡Buen trabajo!",
  "NO_ERRORS_MULTIPLE_PROVIDER": "No se encontraron problemas - ¡Buen trabajo!",
  "LINT_DISABLED": "La inspección de código está deshabilitada",
  "NO_LINT_AVAILABLE": "No hay inspección de código disponible para {0}",
  "NOTHING_TO_LINT": "No hay nada para inspeccionar",
  "LINTER_TIMED_OUT": "{0} ha agotado el tiempo después de esperar {1} ms",
  "LINTER_FAILED": "{0} terminó con error: {1}",
  "FILE_MENU": "Archivo",
  "CMD_FILE_NEW_UNTITLED": "Nuevo",
  "CMD_FILE_NEW": "Nuevo archivo",
  "CMD_FILE_DUPLICATE": "Duplicar",
  "CMD_FILE_CUT": "Cortar",
  "CMD_FILE_COPY": "Copiar",
  "CMD_FILE_COPY_PATH": "Copiar ruta",
  "CMD_FILE_PASTE": "Pegar",
  "CMD_PROJECT_NEW": "Nuevo proyecto",
  "CMD_FILE_NEW_FOLDER": "Nueva carpeta",
  "CMD_FILE_OPEN": "Abrir…",
  "CMD_RECENT_FILES_OPEN": "Archivos recientes…",
  "CMD_ADD_TO_WORKING_SET": "Abrir en el área de trabajo",
  "CMD_OPEN_DROPPED_FILES": "Abrir archivos soltados",
  "CMD_OPEN_FOLDER": "Abrir carpeta…",
  "CMD_FILE_CLOSE": "Cerrar",
  "CMD_FILE_CLOSE_ALL": "Cerrar todo",
  "CMD_FILE_CLOSE_LIST": "Cerrar lista",
  "CMD_FILE_CLOSE_OTHERS": "Cerrar otros",
  "CMD_FILE_CLOSE_ABOVE": "Cerrar otros por encima",
  "CMD_FILE_CLOSE_BELOW": "Cerrar otros por debajo",
  "CMD_FILE_SAVE": "Guardar archivo",
  "CMD_FILE_SAVE_ALL": "Guardar todo",
  "CMD_FILE_SAVE_AS": "Guardar como…",
  "CMD_LIVE_FILE_PREVIEW": "Vista previa dinámica",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "Habilitar la Vista previa dinámica experimental",
  "CMD_RELOAD_LIVE_PREVIEW": "Recargar la Vista previa dinámica",
  "CMD_PROJECT_SETTINGS": "Configuración del proyecto…",
  "CMD_FILE_RENAME": "Renombrar",
  "CMD_FILE_DELETE": "Eliminar",
  "CMD_INSTALL_EXTENSION": "Instalar extensión…",
  "CMD_EXTENSION_MANAGER": "Gestionar extensiones…",
  "CMD_FILE_REFRESH": "Actualizar árbol de archivos",
  "CMD_FILE_SHOW_FOLDERS_FIRST": "Ordenar carpetas primero",
  "CMD_QUIT": "Salir",
  "CMD_EXIT": "Salir",
  "EDIT_MENU": "Edición",
  "CMD_UNDO": "Deshacer",
  "CMD_REDO": "Rehacer",
  "CMD_CUT": "Cortar",
  "CMD_COPY": "Copiar",
  "CMD_PASTE": "Pegar",
  "CMD_SELECT_ALL": "Seleccionar todo",
  "CMD_SELECT_LINE": "Seleccionar línea",
  "CMD_SPLIT_SEL_INTO_LINES": "Dividir selección en líneas",
  "CMD_ADD_CUR_TO_NEXT_LINE": "Agregar cursor a la siguiente línea",
  "CMD_ADD_CUR_TO_PREV_LINE": "Agregar cursor a la línea anterior",
  "CMD_INDENT": "Aumentar sangría",
  "CMD_UNINDENT": "Disminuir sangría",
  "CMD_DUPLICATE": "Duplicar",
  "CMD_DELETE_LINES": "Eliminar línea",
  "CMD_COMMENT": "Comentar/Descomentar línea",
  "CMD_BLOCK_COMMENT": "Comentar/Descomentar bloque",
  "CMD_LINE_UP": "Subir línea",
  "CMD_LINE_DOWN": "Bajar línea",
  "CMD_OPEN_LINE_ABOVE": "Crear línea arriba",
  "CMD_OPEN_LINE_BELOW": "Crear línea abajo",
  "CMD_TOGGLE_CLOSE_BRACKETS": "Completar paréntesis automáticamente",
  "CMD_SHOW_CODE_HINTS": "Mostrar sugerencias de código",
  "CMD_BEAUTIFY_CODE": "embellecer código",
  "CMD_BEAUTIFY_CODE_ON_SAVE": "Embellecer código después de guardar",
  "FIND_MENU": "Buscar",
  "CMD_FIND": "Buscar",
  "CMD_FIND_NEXT": "Buscar siguiente",
  "CMD_FIND_PREVIOUS": "Buscar anterior",
  "CMD_FIND_ALL_AND_SELECT": "Buscar todo y seleccionar",
  "CMD_ADD_NEXT_MATCH": "Agregar la siguiente coincidencia a la selección",
  "CMD_SKIP_CURRENT_MATCH": "Omitir y agregar la siguiente coincidencia",
  "CMD_FIND_IN_FILES": "Buscar en archivos",
  "CMD_FIND_IN_SUBTREE": "Buscar en…",
  "CMD_REPLACE": "Reemplazar",
  "CMD_REPLACE_IN_FILES": "Reemplazar en archivos",
  "CMD_REPLACE_IN_SUBTREE": "Reemplazar en…",
  "VIEW_MENU": "Ver",
  "CMD_HIDE_SIDEBAR": "Ocultar menú lateral",
  "CMD_SHOW_SIDEBAR": "Mostrar menú lateral",
  "CMD_TOGGLE_SIDEBAR": "Alternar barra lateral",
  "CMD_TOGGLE_PANELS": "Alternar paneles",
  "CMD_TOGGLE_PURE_CODE": "Sin distracciones",
  "CMD_INCREASE_FONT_SIZE": "Aumentar tamaño de fuente",
  "CMD_DECREASE_FONT_SIZE": "Disminuir tamaño de fuente",
  "CMD_RESTORE_FONT_SIZE": "Restablecer tamaño de fuente",
  "CMD_SCROLL_LINE_UP": "Desplazar hacia arriba",
  "CMD_SCROLL_LINE_DOWN": "Desplazar hacia abajo",
  "CMD_TOGGLE_LINE_NUMBERS": "Mostrar números de línea",
  "CMD_TOGGLE_ACTIVE_LINE": "Resaltar línea actual",
  "CMD_TOGGLE_WORD_WRAP": "Habilitar ajuste de línea",
  "CMD_LIVE_HIGHLIGHT": "Resaltado en Vista previa dinámica",
  "CMD_VIEW_TOGGLE_INSPECTION": "Inspeccionar el código al guardar",
  "CMD_WORKINGSET_SORT_BY_ADDED": "Ordenar por Añadido",
  "CMD_WORKINGSET_SORT_BY_NAME": "Ordenar por Nombre",
  "CMD_WORKINGSET_SORT_BY_TYPE": "Ordenar por Tipo",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "Ordenación automática",
  "CMD_THEMES": "Temas…",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "Cerrar búsqueda automáticamente",
  "NAVIGATE_MENU": "Navegación",
  "CMD_QUICK_OPEN": "Apertura rápida",
  "CMD_GOTO_LINE": "Ir a la línea",
  "CMD_GOTO_DEFINITION": "Búsqueda rápida de definición",
  "CMD_GOTO_DEFINITION_PROJECT": "Definición de búsqueda rápida en el proyecto",
  "CMD_GOTO_FIRST_PROBLEM": "Ir al primer problema",
  "CMD_TOGGLE_QUICK_EDIT": "Edición rápida",
  "CMD_TOGGLE_QUICK_DOCS": "Documentación rápida",
  "CMD_QUICK_EDIT_PREV_MATCH": "Coincidencia anterior",
  "CMD_QUICK_EDIT_NEXT_MATCH": "Coincidencia siguiente",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "Nueva regla",
  "CMD_NEXT_DOC": "Documento siguiente",
  "CMD_PREV_DOC": "Documento anterior",
  "CMD_NAVIGATE_BACKWARD": "Navegar hacia atrás",
  "CMD_NAVIGATE_FORWARD": "Navegar hacia adelante",
  "CMD_NEXT_DOC_LIST_ORDER": "Documento siguiente en la lista",
  "CMD_PREV_DOC_LIST_ORDER": "Documento anterior en la lista",
  "CMD_SHOW_IN_TREE": "Mostrar en el árbol de directorios",
  "CMD_SHOW_IN_EXPLORER": "Mostrar en el Explorador",
  "CMD_SHOW_IN_FINDER": "Mostrar en Finder",
  "CMD_SHOW_IN_OS": "Mostrar en el Sistema Operativo",
  "CMD_SWITCH_PANE_FOCUS": "Cambiar el enfoque del panel",
  "CMD_OPEN_VFS": "Sistema de archivos virtual abierto",
  "CMD_OPEN_VIRTUAL_SERVER": "Abrir servidor virtual",
  "HELP_MENU": "Ayuda",
  "CMD_CHECK_FOR_UPDATE": "Buscar actualizaciones",
  "CMD_HOW_TO_USE_BRACKETS": "Cómo utilizar {APP_NAME}",
  "CMD_SUPPORT": "Soporte de {APP_NAME}",
  "CMD_SUGGEST": "Sugerir una mejora",
  "CMD_RELEASE_NOTES": "Notas de la versión",
  "CMD_GET_INVOLVED": "Involúcrese",
  "CMD_SHOW_EXTENSIONS_FOLDER": "Abrir carpeta de extensiones",
  "CMD_HEALTH_DATA_STATISTICS": "Reporte de estadísticas",
  "CMD_HOMEPAGE": "Página de inicio de {APP_NAME}",
  "CMD_TWITTER": "{TWITTER_NAME} en Twitter",
  "CMD_ABOUT": "Acerca de {APP_TITLE}",
  "CMD_OPEN_PREFERENCES": "Abrir archivo de preferencias",
  "CMD_OPEN_KEYMAP": "Abrir archivo de atajos de teclado",
  "EXPERIMENTAL_BUILD": "versión experimental",
  "RELEASE_BUILD": "versión",
  "DEVELOPMENT_BUILD": "versión de desarrollo",
  "PRERELEASE_BUILD": "versión preliminar",
  "RELOAD_FROM_DISK": "Volver a cargar desde disco",
  "KEEP_CHANGES_IN_EDITOR": "Conservar los cambios del editor",
  "CLOSE_DONT_SAVE": "Cerrar (No guardar)",
  "RELAUNCH_CHROME": "Reiniciar Chrome",
  "ABOUT": "Acerca de…",
  "CLOSE": "Cerrar",
  "ABOUT_TEXT_LINE1": "Publicar {VERSION_MAJOR}.{VERSION_MINOR} {BUILD_TYPE} {VERSION}",
  "ABOUT_TEXT_BUILD_TIMESTAMP": "marca de tiempo de compilación:",
  "ABOUT_TEXT_LINE3": "Bibliotecas de terceros que utilizamos: <a href='https://github.com/phcode-dev/phoenix/tree/main/src/thirdparty/licences'>licencias y atribuciones</a> .",
  "ABOUT_TEXT_LINE4": "Documentación y fuente en <a href='https://github.com/phcode-dev/phoenix/'>https://github.com/phcode-dev/phoenix/</a>",
  "ABOUT_TEXT_LINE5": "Hecho con ❤ y JavaScript por:",
  "ABOUT_TEXT_LINE6": "Mucha gente (pero estamos teniendo problemas para cargar esos datos en este momento).",
  "ABOUT_TEXT_MDN_DOCS": "El contenido de MDN Docs y el logo de MDN están disponibles bajo Licencia de Reconocimiento de Creative Commons, <a href='{MDN_DOCS_LICENSE}'>CC-BY-SA 2.5 Unported</a>.",
  "UPDATE_NOTIFICATION_TOOLTIP": "¡Hay una nueva versión de {APP_NAME} disponible! Haz clic aquí para ver más detalles.",
  "UPDATE_AVAILABLE_TITLE": "Actualización disponible",
  "UPDATE_RELOAD_APP": "Cierra todas las ventanas/pestañas de {APP_NAME} y vuelve a abrir {APP_NAME} para obtener la versión más reciente.",
  "UPDATE_MESSAGE": "¡Hay una nueva versión de {APP_NAME} disponible! Éstas son algunas de las nuevas características:",
  "GET_IT_NOW": "¡Consíguelo ahora!",
  "PROJECT_SETTINGS_TITLE": "Configuración del proyecto para: {0}",
  "PROJECT_SETTING_BASE_URL": "URL base para Vista previa dinámica",
  "PROJECT_SETTING_BASE_URL_HINT": "Para usar un servidor local, ingresa una URL como http://localhost:8000/",
  "BASEURL_ERROR_INVALID_PROTOCOL": "El protocolo {0} no está soportado por la Vista previa dinámica. Por favor, utiliza http: o https: .",
  "BASEURL_ERROR_SEARCH_DISALLOWED": "La URL base no puede contener parámetros de búsqueda como \"{0}\".",
  "BASEURL_ERROR_HASH_DISALLOWED": "La URL base no puede contener hashes como \"{0}\".",
  "BASEURL_ERROR_INVALID_CHAR": "Los caracteres especiales como '{0}' deben codificarse en formato %.",
  "BASEURL_ERROR_UNKNOWN_ERROR": "Error desconocido analizando la URL base",
  "EMPTY_VIEW_HEADER": "<em>Abra un archivo mientras este panel está enfocado</em>",
  "FLIPVIEW_BTN_TOOLTIP": "Voltear esta vista al panel {0}",
  "CURRENT_THEME": "Tema actual",
  "USE_THEME_SCROLLBARS": "Usar las barras de desplazamiento del tema",
  "FONT_SIZE": "Tamaño de letra",
  "FONT_FAMILY": "Tipo de letra",
  "THEMES_SETTINGS": "Preferencias de temas",
  "BUTTON_NEW_RULE": "Nueva regla",
  "INSTALL": "Instalar",
  "UPDATE": "Actualizar",
  "REMOVE": "Eliminar",
  "DISABLE": "Deshabilitar",
  "ENABLE": "Habilitar",
  "OVERWRITE": "Sobrescribir",
  "CANT_REMOVE_DEV": "Las extensiones en la carpeta \"dev\" se deben eliminar manualmente.",
  "CANT_UPDATE": "La actualización no es compatible con esta versión de {APP_NAME}.",
  "CANT_UPDATE_DEV": "Las extensiones en la carpeta \"dev\" no se pueden actualizar automáticamente.",
  "INSTALL_EXTENSION_TITLE": "Instalar extensión",
  "UPDATE_EXTENSION_TITLE": "Actualizar extensión",
  "INSTALL_EXTENSION_LABEL": "URL de la extensión",
  "INSTALL_EXTENSION_HINT": "URL del archivo zip de la extensión o del repositorio de Github",
  "INSTALLING_FROM": "Instalando extensión desde {0}…",
  "INSTALL_SUCCEEDED": "¡Instalación completada!",
  "INSTALL_FAILED": "Error en la instalación.",
  "CANCELING_INSTALL": "Cancelando…",
  "CANCELING_HUNG": "Cancelando la instalación porque está tardando demasiado tiempo. Puede que se haya producido un error interno.",
  "INSTALL_CANCELED": "Instalación cancelada.",
  "VIEW_COMPLETE_DESCRIPTION": "Ver descripción completa",
  "VIEW_TRUNCATED_DESCRIPTION": "Ver descripción corta",
  "SORT_EXTENSION_METHOD": "Ordenar extensiones usando downloadCount o PublishedDate",
  "INVALID_ZIP_FILE": "El contenido descargado no es un archivo zip válido.",
  "MISSING_PACKAGE_JSON": "El paquete no tiene ningún archivo package.json.",
  "INVALID_PACKAGE_JSON": "El archivo package.json no es válido (error: {0}).",
  "MISSING_PACKAGE_NAME": "El archivo package.json no especifica un nombre de paquete.",
  "BAD_PACKAGE_NAME": "{0} no es un nombre de paquete válido.",
  "MISSING_PACKAGE_VERSION": "El archivo package.json no especifica la versión del paquete.",
  "INVALID_VERSION_NUMBER": "El número de paquete de la versión ({0}) no es válido.",
  "INVALID_BRACKETS_VERSION": "El código de compatibilidad de {APP_NAME} ({0}) no es válido.",
  "DISALLOWED_WORDS": "Las palabras ({1}) no están permitidas en el campo {0}.",
  "NPM_INSTALL_FAILED": "El comando de instalación de npm falló: {0}",
  "API_NOT_COMPATIBLE": "La extensión no es compatible con esta versión de {APP_NAME}. Está en la carpeta de extensiones deshabilitadas.",
  "MISSING_MAIN": "El paquete no contiene el archivo main.js.",
  "EXTENSION_ALREADY_INSTALLED": "Instalar este paquete sobrescribirá una extensión instalada previamente. ¿Deseas sobrescribir la antigua extensión?",
  "EXTENSION_SAME_VERSION": "La versión de este paquete es la misma que la instalada actualmente. ¿Deseas sobrescribir la instalación actual?",
  "EXTENSION_OLDER_VERSION": "La versión {0} de este paquete es más antigua que la instalada actualmente ({1}). ¿Deseas sobrescribir la instalación actual?",
  "DOWNLOAD_ID_IN_USE": "Error interno: el ID de descarga ya está siendo utilizado.",
  "NO_SERVER_RESPONSE": "No se puede conectar con el servidor.",
  "BAD_HTTP_STATUS": "Archivo no encontrado en el servidor (HTTP {0}).",
  "CANNOT_WRITE_TEMP": "No se pudo guardar la descarga en un archivo temporal.",
  "ERROR_LOADING": "La extensión ha encontrado un error al arrancar.",
  "MALFORMED_URL": "La URL no es válida. Por favor, comprueba que esté escrita correctamente.",
  "UNSUPPORTED_PROTOCOL": "La URL debe ser una dirección http o https.",
  "UNKNOWN_ERROR": "Error interno desconocido.",
  "EXTENSION_MANAGER_TITLE": "Gestor de extensiones",
  "EXTENSION_MANAGER_ERROR_LOAD": "No se pudo acceder al registro de extensiones. Vuelve a intentarlo más tarde, por favor.",
  "INSTALL_EXTENSION_DRAG": "Arrastrar el .zip aquí ó",
  "INSTALL_EXTENSION_DROP": "Soltar el .zip para instalarlo",
  "INSTALL_EXTENSION_DROP_ERROR": "La instalación/actualización fue abortada por los siguientes errores:",
  "INSTALL_FROM_URL": "Instalar desde URL…",
  "INSTALL_EXTENSION_VALIDATING": "Validando…",
  "EXTENSION_AUTHOR": "Autor",
  "EXTENSION_DATE": "Fecha",
  "EXTENSION_INCOMPATIBLE_NEWER": "Esta extensión necesita una versión más actualizada de {APP_NAME}.",
  "EXTENSION_INCOMPATIBLE_OLDER": "En estos momentos esta extensión sólo funciona con versiones anteriores de {APP_NAME}.",
  "EXTENSION_LATEST_INCOMPATIBLE_NEWER": "La versión {0} de esta extensión necesita una versión superior de {APP_NAME}. Puedes instalar la versión anterior {1}.",
  "EXTENSION_LATEST_INCOMPATIBLE_OLDER": "La versión {0} de esta extensión sólo funciona con versiones anteriores de {APP_NAME}. Puedes instalar la versión anterior {1}.",
  "EXTENSION_NO_DESCRIPTION": "Sin descripción",
  "EXTENSION_MORE_INFO": "Más información…",
  "EXTENSION_ERROR": "Error en la extensión",
  "EXTENSION_KEYWORDS": "Palabras clave",
  "EXTENSION_TRANSLATED_USER_LANG": "Traducida a {0} idiomas, incluyendo el tuyo",
  "EXTENSION_TRANSLATED_GENERAL": "Traducida a {0} idiomas",
  "EXTENSION_TRANSLATED_LANGS": "Esta extension fue traducida a los siguientes idiomas: {0}",
  "EXTENSION_INSTALLED": "Instaladas",
  "EXTENSION_UPDATE_INSTALLED": "La actualización de esta extensión se ha descargado y se instalará luego de recargar {APP_NAME}.",
  "EXTENSION_SEARCH_PLACEHOLDER": "Buscar",
  "EXTENSION_MORE_INFO_LINK": "Más",
  "BROWSE_EXTENSIONS": "Explorar extensiones",
  "EXTENSION_MANAGER_REMOVE": "Eliminar extensión",
  "EXTENSION_MANAGER_REMOVE_ERROR": "No se pudo eliminar una o más extensiones: {0}. {APP_NAME} se recargará igualmente.",
  "EXTENSION_MANAGER_UPDATE": "Actualizar extensión",
  "EXTENSION_MANAGER_UPDATE_ERROR": "No se pudo actualizar una o más extensiones: {0}. {APP_NAME} se recargará igualmente.",
  "EXTENSION_MANAGER_DISABLE": "Deshabilitar extensiones",
  "EXTENSION_MANAGER_DISABLE_ERROR": "No se pudo deshabilitar una o más extensiones: {0}. {APP_NAME} se recargará igualmente.",
  "MARKED_FOR_REMOVAL": "Marcada para eliminar",
  "UNDO_REMOVE": "Deshacer",
  "MARKED_FOR_UPDATE": "Marcada para actualizar",
  "UNDO_UPDATE": "Deshacer",
  "MARKED_FOR_DISABLING": "Marcada para deshabilitar",
  "UNDO_DISABLE": "Deshacer",
  "CHANGE_AND_RELOAD_TITLE": "Cambiar extensiones",
  "CHANGE_AND_RELOAD_MESSAGE": "Para actualizar o eliminar las extensiones marcadas, necesitas recargar {APP_NAME}. Se solicitará confirmación para guardar los cambios pendientes.",
  "REMOVE_AND_RELOAD": "Eliminar extensiones y recargar",
  "CHANGE_AND_RELOAD": "Cambiar extensiones y recargar",
  "UPDATE_AND_RELOAD": "Actualizar extensiones y recargar",
  "DISABLE_AND_RELOAD": "Deshabilitar extensiones y recargar",
  "PROCESSING_EXTENSIONS": "Procesando los cambios en las extensiones…",
  "EXTENSION_NOT_INSTALLED": "No se pudo eliminar la extensión {0} porque no se encuentra instalada.",
  "NO_EXTENSIONS": "Todavía no hay ninguna extensión instalada.<br>Haz clic en la pestaña Disponibles para empezar.",
  "NO_EXTENSION_MATCHES": "No hay extensiones que coincidan con tu búsqueda.",
  "REGISTRY_SANITY_CHECK_WARNING": "NOTA: estas extensiones pueden provenir de autores diferentes a {APP_NAME}. Las extensiones no son revisadas y tiene todos los privilegios locales. Tenga cuidado cuando instala extensiones de una fuente desconocida.",
  "EXTENSIONS_INSTALLED_TITLE": "Instaladas",
  "EXTENSIONS_DEFAULT_TITLE": "Por defecto",
  "EXTENSIONS_AVAILABLE_TITLE": "Disponibles",
  "EXTENSIONS_THEMES_TITLE": "Temas",
  "EXTENSIONS_UPDATES_TITLE": "Actualizaciones",
  "EXTENSIONS_LAST_UPDATED": "Última actualización",
  "EXTENSIONS_DOWNLOADS": "Descargas",
  "INLINE_EDITOR_NO_MATCHES": "No hay coincidencias disponibles.",
  "INLINE_EDITOR_HIDDEN_MATCHES": "Todas las coincidencias están colapsadas. Expanda los archivos listados a la derecha para ver coincidencias.",
  "CSS_QUICK_EDIT_NO_MATCHES": "No hay reglas de CSS existentes que coincidan con tu selección.<br> Haz clic en \"Nueva regla\" para crear una.",
  "CSS_QUICK_EDIT_NO_STYLESHEETS": "No hay hojas de estilos en tu proyecto.<br>Crea una para añadir reglas de CSS.",
  "IMAGE_VIEWER_LARGEST_ICON": "más grande",
  "UNIT_PIXELS": "píxeles",
  "DEBUG_MENU": "Desarrollo",
  "ERRORS": "Errores",
  "CMD_SHOW_DEV_TOOLS": "Mostrar herramientas para desarrolladores",
  "CMD_REFRESH_WINDOW": "Recargar con extensiones",
  "CMD_RELOAD_WITHOUT_USER_EXTS": "Recargar sin extensiones",
  "CMD_NEW_BRACKETS_WINDOW": "Nueva ventana de {APP_NAME}",
  "CMD_LAUNCH_SCRIPT_MAC": "Instalar acceso directo por línea de comandos",
  "CMD_SWITCH_LANGUAGE": "Cambiar idioma",
  "CMD_RUN_UNIT_TESTS": "Ejecutar tests",
  "CMD_SHOW_PERF_DATA": "Mostrar información de rendimiento",
  "CMD_ENABLE_LOGGING": "Habilitar registros detallados",
  "CMD_ENABLE_LIVE_PREVIEW_LOGS": "Registros de vista previa en vivo",
  "CMD_OPEN_BRACKETS_SOURCE": "Abrir el código fuente de {APP_NAME}",
  "CREATING_LAUNCH_SCRIPT_TITLE": "Acceso directo a {APP_NAME} por línea de comandos",
  "ERROR_CREATING_LAUNCH_SCRIPT": "Ocurrió un error al instalar el acceso directo por línea de comandos. Por favor probá <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting'>estas sugerencias de solución de problemas</a>.<br><br>Razón: {0}",
  "ERROR_CLTOOLS_RMFAILED": "No se pudó eliminar el enlace simbólico existente <code>/usr/local/bin/brackets</code>.",
  "ERROR_CLTOOLS_MKDIRFAILED": "No se pudó crear el directorio <code>/usr/local/bin</code>.",
  "ERROR_CLTOOLS_LNFAILED": "No se pudó crear elenlace simbólico <code>/usr/local/bin/brackets</code>.",
  "ERROR_CLTOOLS_SERVFAILED": "Error interno.",
  "ERROR_CLTOOLS_NOTSUPPORTED": "El acceso directo por línea de comandos no es compatible con este sistema operativo.",
  "LAUNCH_SCRIPT_CREATE_SUCCESS": "¡Éxito! Ahora puedes abrir fácilmente {APP_NAME} desde la línea de comandos: <code>brackets myFile.txt</code> para abrir un archivo o <code>brackets myFolder</code> para cambiar de proyecto.<br><br><a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments'>Aprende más</a> acerca de como usar {APP_NAME} desde la línea de comandos.",
  "LANGUAGE_TITLE": "Cambiar idioma",
  "LANGUAGE_MESSAGE": "Idioma:",
  "LANGUAGE_SUBMIT": "Reiniciar {APP_NAME}",
  "LANGUAGE_CANCEL": "Cancelar",
  "LANGUAGE_SYSTEM_DEFAULT": "Idioma predeterminado",
  "HEALTH_DATA_NOTIFICATION": "Preferencias del reporte de estadísticas",
  "HEALTH_FIRST_POPUP_TITLE": "Reporte de estadísticas de {APP_NAME}",
  "HEALTH_DATA_DO_TRACK": "Compartir información anónima sobre cómo utilizo {APP_NAME}",
  "HEALTH_DATA_NOTIFICATION_MESSAGE": "Para poder mejorar {APP_NAME}, enviamos periódicamente limitadas estadísticas <strong>anónimas</strong> a Adobe acerca de cómo se utiliza {APP_NAME}. Esta información ayuda a priorizar características a desarrollar, encontrar errores y problemas de usabilidad.<br><br>Puedes ver tus datos o elegir no compartir datos seleccionando <strong>Ayuda > Reporte de estadísticas</strong>.<br><br><a href='https://github.com/adobe/brackets/wiki/Health-Data'>Aprende más sobre el reporte de estadísticas de {APP_NAME}</a>",
  "HEALTH_DATA_PREVIEW": "Reporte de estadísticas de {APP_NAME}",
  "HEALTH_DATA_PREVIEW_INTRO": "<p>Para poder mejorar {APP_NAME}, enviamos periódicamente limitadas estadísticas <strong>anónimas</strong> a Adobe acerca de cómo se utiliza {APP_NAME}. Esta información ayuda a priorizar características a desarrollar, encontrar errores y problemas de usabilidad. <a href='https://github.com/adobe/brackets/wiki/Health-Data'>Aprende más sobre el Reporte de estadísticas de {APP_NAME}</a> y cómo beneficia a la comunidad de {APP_NAME} mientras protege tu privacidad.</p><p>A continuación hay una vista previa de la información que será enviada en el siguiente Reporte de estadísticas <em>si</em> está habilitado.</p>",
  "INLINE_TIMING_EDITOR_TIME": "Tiempo",
  "INLINE_TIMING_EDITOR_PROGRESSION": "Progresión",
  "BEZIER_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd><kbd>←</kbd><kbd>→</kbd> Mueven el punto seleccionado<br><kbd class='text'>Shift</kbd> Mueve de a diez unidades<br><kbd class='text'>Tab</kbd> Cambia el punto seleccionado",
  "STEPS_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd> Incrementa o disminuya los pasos<br><kbd>←</kbd><kbd>→</kbd> 'Start' o 'End'",
  "INLINE_TIMING_EDITOR_INVALID": "El valor viejo <code>{0}</code> no es válido, por lo tanto, fue modificado a <code>{1}</code>. El documento será actualizado luego de la primer edición.",
  "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP": "Color actual",
  "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP": "Color original",
  "COLOR_EDITOR_RGBA_BUTTON_TIP": "Formato RGBa",
  "COLOR_EDITOR_HEX_BUTTON_TIP": "Formato Hex",
  "COLOR_EDITOR_HSLA_BUTTON_TIP": "Formato HSLa",
  "COLOR_EDITOR_0X_BUTTON_TIP": "Formato hexadecimal (0x)",
  "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR": "{0} (Utilizado {1} vez)",
  "COLOR_EDITOR_USED_COLOR_TIP_PLURAL": "{0} (Utilizado {1} veces)",
  "CMD_JUMPTO_DEFINITION": "Saltar a la definición",
  "CMD_SHOW_PARAMETER_HINT": "Mostrar sugerencias de parámetros",
  "NO_ARGUMENTS": "<no hay parámetros>",
  "DETECTED_EXCLUSION_TITLE": "Problema de inferencia con un archivo JavaScript",
  "DETECTED_EXCLUSION_INFO": "{APP_NAME} se encontró con problemas procesando: <span class='dialog-filename'>{0}</span>.<br><br>Este archivo no volverá a ser procesado para las sugerencias de código, saltar a la definición o para la edición rápida. Para reactivar este archivo, abra el archivo <code>.brackets.json</code> en su proyecto y edite <code>jscodehints.detectedExclusions</code><br><br>Esto es probablemente un error en {APP_NAME}. Si puede proporcionar una copia de este archivo, por favor <a href='https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue'>envíe un informe</a> con un vínculo a dicho archivo.",
  "CMD_REFACTOR": "refactorizar",
  "CMD_EXTRACTTO_VARIABLE": "Extraer a variable",
  "CMD_EXTRACTTO_FUNCTION": "Extraer a función",
  "ERROR_TERN_FAILED": "No se pueden obtener datos de Tern",
  "ERROR_EXTRACTTO_VARIABLE_NOT_VALID": "La selección no forma una expresión.",
  "ERROR_EXTRACTTO_FUNCTION_NOT_VALID": "El bloque seleccionado debe representar un conjunto de declaraciones o una expresión",
  "ERROR_EXTRACTTO_VARIABLE_MULTICURSORS": "Extraer a variable no funciona en multicursores",
  "ERROR_EXTRACTTO_FUNCTION_MULTICURSORS": "Extraer a función no funciona en multicursores",
  "EXTRACTTO_FUNCTION_SELECT_SCOPE": "Elija el ámbito de destino",
  "EXTRACTTO_VARIABLE_SELECT_EXPRESSION": "Seleccione una expresión",
  "CMD_REFACTORING_RENAME": "Renombrar",
  "CMD_REFACTORING_TRY_CATCH": "Envolver en Try Catch",
  "CMD_REFACTORING_CONDITION": "Envolver en condición",
  "CMD_REFACTORING_GETTERS_SETTERS": "Crear captadores/establecedores",
  "CMD_REFACTORING_ARROW_FUNCTION": "Convertir a función de flecha",
  "DESCRIPTION_CODE_REFACTORING": "Habilitar/deshabilitar la refactorización de código JavaScript",
  "ERROR_TRY_CATCH": "Seleccione un código válido para envolver en un bloque Try-catch",
  "ERROR_WRAP_IN_CONDITION": "Seleccione un código válido para envolver en un bloque de condición",
  "ERROR_ARROW_FUNCTION": "Coloque el cursor dentro de una expresión de función",
  "ERROR_GETTERS_SETTERS": "Coloque el cursor en un miembro de una expresión de objeto",
  "ERROR_RENAME_MULTICURSOR": "No se puede cambiar el nombre cuando se usan cursores múltiples",
  "ERROR_RENAME_QUICKEDIT": "No se puede cambiar el nombre de este identificador, ya que se hace referencia en otro lugar fuera de esta función",
  "ERROR_RENAME_GENERAL": "No se puede cambiar el nombre del texto seleccionado",
  "JSHINT_NAME": "JSHint",
  "CMD_ENABLE_QUICK_VIEW": "Vista rápida con cursor",
  "CMD_ENABLE_SELECTION_VIEW": "Vista de selección",
  "CMD_TOGGLE_RECENT_PROJECTS": "Proyectos recientes",
  "DOCS_MORE_LINK": "Más",
  "COLLAPSE_ALL": "Colapsar todo",
  "EXPAND_ALL": "Expandir todo",
  "COLLAPSE_CURRENT": "Colapsar actual",
  "EXPAND_CURRENT": "Expandir actual",
  "RECENT_FILES_DLG_HEADER": "Archivos recientes",
  "RECENT_FILES_DLG_CLEAR_BUTTON_LABEL": "Claro",
  "RECENT_FILES_DLG_CLEAR_BUTTON_TITLE": "Borrar archivos que no están en el conjunto de trabajo",
  "DESCRIPTION_CLOSE_BRACKETS": "true para cerrar automáticamente las llaves, los corchetes y los paréntesis",
  "DESCRIPTION_CLOSE_OTHERS_ABOVE": "false para eliminar \"Cerrar otros por encima\" del menú contextual del Área de trabajo",
  "DESCRIPTION_CLOSE_OTHERS_BELOW": "false para eliminar \"Cerrar otros por debajo\" del menú contextual del Área de trabajo",
  "DESCRIPTION_CLOSE_OTHERS": "false para eliminar \"Cerrar otros\" del menú contextual del Área de trabajo",
  "DESCRIPTION_CLOSE_TAGS": "Configura las opciones de cierre de etiquetas automático",
  "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS": "Un vector de etiquetas que no deben cerrarse automáticamente",
  "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING": "Cerrar cuando \">\" de la etiqueta de apertura es tipeado",
  "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING": "Cerrar cuando \"/\" de la etiqueta de clausura es tipeado",
  "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS": "Un vector de etiquetas que cuando se cierran generan una linea en blanco entre las etiquetas",
  "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD": "true para siempre generar marcadores plegables cuando cambia el nivel de indentación",
  "DESCRIPTION_CODE_FOLDING_ENABLED": "true para habilitar el colapsado del código",
  "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER": "true para hacer marcadores de sección plegables visible sólo cuando se mueve el cursor sobre el espacio a la izquierda del código",
  "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL": "Limita a cuántos niveles de profundidad Colapsar todo aplica",
  "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE": "Mínima cantidad de líneas antes de que aparezca un icono de sección plegable",
  "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES": "true para recordar la secciones colapsadas luego de cerrar y abrir un archivo o proyecto",
  "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE": "true para habilitar el plegado de código en el texto seleccionado en el editor",
  "DESCRIPTION_DISABLED_DEFAULT_EXTENSIONS": "Extensiones predeterminadas que están deshabilitadas",
  "DESCRIPTION_ATTR_HINTS": "Activar/desactivar las sugerencias de código para los atributos en HTML",
  "DESCRIPTION_CSS_PROP_HINTS": "Activar/desactivar las sugerencias de código para las propiedades en CSS/LESS/SCSS",
  "DESCRIPTION_JS_HINTS": "Activar/desactivar las sugerencias de código en JavaScript",
  "DESCRIPTION_JS_HINTS_TYPE_DETAILS": "Habilitar/deshabilitar detalles de tipo de datos en sugerencias de código JavaScript",
  "DESCRIPTION_PREF_HINTS": "Activar/desactivar las sugerencias de código para las Preferences",
  "DESCRIPTION_SPECIAL_CHAR_HINTS": "Activar/desactivar las sugerencias de código para las entidades en HTML",
  "DESCRIPTION_SVG_HINTS": "Activar/desactivar las sugerencias de código en SVG",
  "DESCRIPTION_HTML_TAG_HINTS": "Activar/desactivar las sugerencias de código para las etiquetas en HTML",
  "DESCRIPTION_URL_CODE_HINTS": "Activar/desactivar las sugerencias de código para las URLs en HTML & CSS/LESS/SCSS",
  "DESCRIPTION_DRAG_DROP_TEXT": "Activar/desactivar la funcionalidad de arrastrar y soltar",
  "DESCRIPTION_HEALTH_DATA_TRACKING": "Habilitar el seguimiento de los Reportes de estadísticas",
  "DESCRIPTION_HIGHLIGHT_MATCHES": "Habilita el resaltado automático de cadenas que coinciden en el documento",
  "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN": "Resaltar todas las cadenas que coincidan con la cadena donde el cursor se encuentra (ninguna selección es necesaria)",
  "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY": "Resaltar sólo cuando la selección es una cadena completa",
  "DESCRIPTION_INSERT_HINT_ON_TAB": "true para insertar la sugerencia de código al presionar tab",
  "DESCRIPTION_NO_HINTS_ON_DOT": "true para no mostrar sugerencias de código automáticamente en JS cuando \".\" es tipeado",
  "DESCRIPTION_JSHINT_OPTIONS": "Un objeto con las opciones predeterminadas para JSHint. Consulte la siguiente URL para ver todas las opciones de JSHint disponibles: https://jshint.com/docs/options/",
  "DESCRIPTION_LANGUAGE": "Preferencias específicas de un lenguaje",
  "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS": "Asignaciones adicionales de extensión de archivo a nombre del lenguaje",
  "DESCRIPTION_LANGUAGE_FILE_NAMES": "Asignaciones adicionales de nombre de archivo a nombre del lenguaje",
  "DESCRIPTION_LINEWISE_COPY_CUT": "Hacer copiar y cortar cuando no hay selección copiará o cortará todas las líneas que tienen cursores en ellas",
  "DESCRIPTION_INPUT_STYLE": "Selecciona la forma en que CodeMirror maneja la entrada y el enfoque. Puede ser textarea, que es el predeterminado, o contenteditable, que es mejor para los lectores de pantalla (inestable)",
  "DESCRIPTION_LINTING_ENABLED": "true para habilitar la inspección del código",
  "DESCRIPTION_ASYNC_TIMEOUT": "El tiempo en milisegundos para esperar a los inspectores de código asincrónicos",
  "DESCRIPTION_LINTING_PREFER": "Vector de inspectores de código para ejecutar primero",
  "DESCRIPTION_LIVE_DEV_MULTIBROWSER": "true para habilitar la Vista previa dinámica experimental",
  "DESCRIPTION_USE_PREFERED_ONLY": "true para ejecutar solo los proveedores especificados en linting.prefer",
  "DESCRIPTION_MAX_CODE_HINTS": "Máxima cantidad de sugerencias de código mostradas",
  "DESCRIPTION_PATH": "Preferencias especificas para una ruta de archivo",
  "DESCRIPTION_PROXY": "La URL del servidor proxy utilizada para la instalación de extensiones",
  "DESCRIPTION_SCROLL_PAST_END": "true permitir el desplazamiento más allá del final del documento",
  "DESCRIPTION_SHOW_CODE_HINTS": "false para deshabilitar todas las sugerencias de código",
  "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING": "Mantiene el cursor intermitente visible cuando se tiene una selección de texto",
  "DESCRIPTION_SHOW_LINE_NUMBERS": "true para mostrar los números de líne a la izquierda del código",
  "DESCRIPTION_SMART_INDENT": "Indentar automáticamente cuando se crea un nuevo bloque",
  "DESCRIPTION_SOFT_TABS": "false para deshabilitar el comportamiento de \"soft tabs\"",
  "DESCRIPTION_SORT_DIRECTORIES_FIRST": "true para ordenar los directorios primero en el árbol del proyecto",
  "DESCRIPTION_SPACE_UNITS": "Cantidad de espacios para utilizar en la indentación basada en espacios",
  "DESCRIPTION_STATIC_SERVER_PORT": "Número de puerto que el servidor utilizará para la Vista previa dinámica",
  "DESCRIPTION_STYLE_ACTIVE_LINE": "true para resaltar la línea en la que se encuentra el cursor",
  "DESCRIPTION_TAB_SIZE": "Cantidad de espacios utilizados para el tab",
  "DESCRIPTION_USE_TAB_CHAR": "true para usar tabs en vez de espacios",
  "DESCRIPTION_UPPERCASE_COLORS": "true para generar color en mayúsculas en el editor de colores",
  "DESCRIPTION_WORD_WRAP": "Ajustar líneas que sobrepasen el ancho de la ventana",
  "DESCRIPTION_SEARCH_AUTOHIDE": "Cierra la búsqueda tan pronto como el editor esté enfocado",
  "DESCRIPTION_DETECTED_EXCLUSIONS": "Una lista de los archivos que se ha detectado que causan que Tern no funcione correctamente",
  "DESCRIPTION_INFERENCE_TIMEOUT": "La cantidad de veces después de la cual Tern dejara de intentar entender los archivos",
  "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR": "true para mostrar errores en la barra de estado",
  "DESCRIPTION_QUICK_VIEW_ENABLED": "true para habilitar la Vista rápida",
  "DESCRIPTION_SELECTION_VIEW_ENABLED": "true para habilitar la vista de selección",
  "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW": "true para mostrar vistas previas de imágenes para URLs sin extensión",
  "DESCRIPTION_THEME": "Seleccionar un tema para {APP_NAME}",
  "DESCRIPTION_USE_THEME_SCROLLBARS": "true para habilitar la barra de desplazamiento customizada",
  "DESCRIPTION_LINTING_COLLAPSED": "true para colapsar el panel de inspección de código",
  "DESCRIPTION_FONT_FAMILY": "Cambiar la fuente",
  "DESCRIPTION_FONT_SIZE": "Cambiar el tamaño de la fuente; ej., 13px",
  "DESCRIPTION_FIND_IN_FILES_NODE": "True to para habilitar búsquedas basadas en node",
  "DESCRIPTION_FIND_IN_FILES_INSTANT": "True to para habilitar la búsqueda instantánea",
  "DESCRIPTION_FONT_SMOOTHING": "Sólo para Mac: \"subpixel-antialiased\" para habilitar sub-pixel antialiasing o \"antialiased\" para antialiasing en escala de grises",
  "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW": "false para deshabilitar la apertura del archivo de preferencias en la vista dividida",
  "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE": "false para abrir el archivo de preferencias en el panel de la izquierda/arriba",
  "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED": "verdadero para colapsar los paneles después de cerrar el último archivo del panel mediante el botón de cierre del encabezado del panel",
  "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS": "Alterne cuándo mostrar los botones cerrar y voltear vista en el encabezado.",
  "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT": "/*\n * Éste es un archivo únicamente de lectura con las preferencias soportadas\n * por {APP_NAME}.\n * Podes usar este archivo como referencia para modificar tu archivo de\n * preferencias \"brackets.json\" abierto en el otro panel.\n * Para más información sobre como usar las preferencias dentro de\n * {APP_NAME}, podes consultar la página web https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences\n */",
  "DEFAULT_PREFERENCES_JSON_DEFAULT": "Por defecto",
  "DESCRIPTION_PURE_CODING_SURFACE": "true para habilitar el modo de solo código y ocultar todos los demás elementos de la interfaz de usuario en {APP_NAME}",
  "DESCRIPTION_INDENT_LINE_COMMENT": "true para habilitar la sangría de los comentarios de línea",
  "DESCRIPTION_RECENT_FILES_NAV": "Habilitar/deshabilitar la navegación en archivos recientes",
  "DESCRIPTION_LIVEDEV_WEBSOCKET_PORT": "Puerto en el que se ejecuta WebSocket Server para Live Preview",
  "DESCRIPTION_LIVE_DEV_HIGHLIGHT_SETTINGS": "Configuración de resaltado de vista previa en vivo",
  "DESCRIPTION_LIVEDEV_ENABLE_REVERSE_INSPECT": "false para deshabilitar la vista previa en vivo, la inspección inversa",
  "DOWNLOAD_FAILED": "Descarga fracasó.",
  "DOWNLOAD_COMPLETE": "¡Descarga completa!",
  "UPDATE_SUCCESSFUL": "¡Actualización exitosa!",
  "UPDATE_FAILED": "¡La actualización falló!",
  "VALIDATION_FAILED": "¡Validación fallida!",
  "INITIALISATION_FAILED": "¡Inicialización falló!",
  "CLEANUP_FAILED": "¡La limpieza falló!",
  "WARNING_TYPE": "¡Advertencia!",
  "CLICK_RESTART_TO_UPDATE": "Haga clic en Reiniciar para actualizar Brackets.",
  "UPDATE_ON_NEXT_LAUNCH": "La actualización se aplicará en el reinicio.",
  "GO_TO_SITE": "Vaya a <a href = \"http://brackets.io/\">brackets.io</a> para volver a intentarlo.",
  "INTERNET_UNAVAILABLE": "No hay conexión a Internet disponible.",
  "UPDATEDIR_READ_FAILED": "No se pudo leer el directorio de actualización.",
  "UPDATEDIR_CLEAN_FAILED": "No se pudo limpiar el directorio de actualización.",
  "INITIAL_DOWNLOAD": "Descargando actualización...",
  "RETRY_DOWNLOAD": "Descarga fracasó. Reintentando... Intento",
  "VALIDATING_INSTALLER": "¡Descarga completa! Validando instalador...",
  "CHECKSUM_DID_NOT_MATCH": "La suma de comprobación no coincide.",
  "INSTALLER_NOT_FOUND": "Instalador no encontrado.",
  "DOWNLOAD_ERROR": "Ocurrió un error durante la descarga.",
  "NETWORK_SLOW_OR_DISCONNECTED": "La red está desconectada o es demasiado lenta.",
  "RESTART_BUTTON": "Reiniciar",
  "LATER_BUTTON": "Luego",
  "DESCRIPTION_AUTO_UPDATE": "Habilitar/deshabilitar la actualización automática de corchetes",
  "AUTOUPDATE_ERROR": "¡Error!",
  "AUTOUPDATE_IN_PROGRESS": "Ya hay una actualización en curso.",
  "NUMBER_WITH_PERCENTAGE": "{0}%",
  "CMD_FIND_RELATED_FILES": "Buscar archivos relacionados",
  "PHP_VERSION_INVALID": "Error al analizar la versión de PHP. Verifique la salida del comando \"php –version\".",
  "PHP_UNSUPPORTED_VERSION": "Instale el tiempo de ejecución de PHP7 para habilitar las herramientas relacionadas con PHP, como Sugerencias de código, Sugerencias de parámetros, Saltar a la definición y más. Versión encontrada: {0}",
  "PHP_EXECUTABLE_NOT_FOUND": "Tiempo de ejecución de PHP no encontrado. Instale el tiempo de ejecución de PHP7 y actualice \"ejecutablePath\" en las Preferencias de PHP de manera adecuada. Esto habilita las herramientas relacionadas con PHP, como Sugerencias de código, Sugerencias de parámetros, Saltar a definición y más.",
  "PHP_PROCESS_SPAWN_ERROR": "Se encontró el código de error {0} al iniciar el proceso de PHP.",
  "PHP_SERVER_ERROR_TITLE": "Error",
  "PHP_SERVER_MEMORY_LIMIT_INVALID": "El límite de memoria que proporcionó no es válido. Revise las preferencias de PHP para establecer el valor correcto.",
  "DESCRIPTION_PHP_TOOLING_CONFIGURATION": "Ajustes de configuración predeterminados de PHP Tooling",
  "OPEN_PREFERENNCES": "Preferencias abiertas",
  "LANGUAGE_TOOLS_PREFERENCES": "Preferencias para herramientas de idioma",
  "FIND_ALL_REFERENCES": "Buscar todas las referencias",
  "REFERENCES_IN_FILES": "referencias",
  "REFERENCE_IN_FILES": "referencia",
  "REFERENCES_NO_RESULTS": "No hay referencias disponibles para la posición actual del cursor",
  "CMD_FIND_DOCUMENT_SYMBOLS": "Buscar símbolos de documento",
  "CMD_FIND_PROJECT_SYMBOLS": "Buscar símbolos de proyecto",
  "REMOTE_DEBUGGING_ENABLED": "Depuración remota habilitada en localhost:",
  "REMOTE_DEBUGGING_PORT_INVALID": "No se puede habilitar la depuración remota en el puerto {0}. Los números de puerto deben estar entre {1} y {2}.",
  "DESCRIPTION_EXTERNAL_APPLICATION_ASSOCIATE": "Asignaciones para la extensión de archivos a aplicaciones externas. Sintaxis: \"<tipo_de_archivo>\": \"<predeterminado|nombre de la aplicación|Ruta de la aplicación>\", use \"predeterminado\" para abrir archivos en la aplicación predeterminada del sistema para el tipo de archivo.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_TITLE": "Abrir archivos gráficos en editores externos.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_MSG": "Tu carpeta actual tiene tipos de archivos gráficos que {APP_NAME} no admite.<br/> Ahora puede asociar tipos de archivos específicos con editores externos. Una vez asociados, puede abrir archivos gráficos como .xd, .psd, .jpg, .png, .ai, .svg en sus aplicaciones predeterminadas haciendo doble clic en los archivos en el Árbol de archivos.<br/><br/> Haga clic en el botón &#39;Aceptar&#39; para asociar los tipos de archivos gráficos con sus respectivas aplicaciones predeterminadas.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_CNF_MSG": "Los siguientes tipos de archivos se han asociado correctamente con las aplicaciones predeterminadas.<br/> {0} Tiene la opción de cambiar su preferencia sobre si elimina o agrega nuevas asociaciones de tipo de archivo en brackets.json yendo al menú &quot;Depurar-&gt;Abrir archivo de preferencias&quot;.",
  "UNSUPPORTED_BROWSER": "El navegador no es compatible",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER": "El navegador no es compatible con Abrir carpeta",
  "UNSUPPORTED_BROWSER_MESSAGE_LINE1": "Utilice uno de los navegadores compatibles a continuación.",
  "UNSUPPORTED_BROWSER_MESSAGE_LINE2": " Estamos trabajando arduamente para que Phoenix esté disponible en más navegadores. Puede cerrar este cuadro de diálogo, pero algunas funciones de Phoenix no funcionarán en este navegador.",
  "CANNOT_PUBLISH_LARGE_PROJECT": "No se puede publicar un proyecto grande",
  "CANNOT_PUBLISH_LARGE_PROJECT_MESSAGE": "Phoenix todavía está en alfa experimental. Todavía no hemos habilitado la sincronización de proyectos con más de 500 archivos.",
  "SHARE_WEBSITE": "¿Publicar y compartir sitio web?",
  "PUBLISH": "Publicar",
  "PUBLISH_CONSENT_MESSAGE": "Previsualice rápidamente los cambios y comparta su sitio web con otros. Phoenix puede publicar este sitio web para usted en {0}. Los enlaces publicados tendrán una vigencia de 7 días. </br>¿Desea publicar y compartir su sitio web?",
  "PUBLISH_SYNC_IN_PROGRESS": "Sincronización en progreso para vista previa...",
  "PUBLISH_PAGE": "Haga clic para publicar y compartir este sitio",
  "PUBLISH_VIEW_PAGE": "Haga clic para ver la página publicada",
  "MISSING_FIELDS": "Campos faltantes",
  "PLEASE_FILL_ALL_REQUIRED": "Por favor complete todos los campos requeridos resaltados en rojo",
  "CODE_EDITOR": "Editor de código",
  "BUILD_THE_WEB": "construir la web",
  "IMPORT_PROJECT": "Proyecto de importación",
  "GITHUB_PROJECT": "Proyecto GitHub",
  "NEW_PROJECT_FROM_GITHUB": "Nuevo proyecto de GitHub",
  "GITHUB_REPO_URL": "URL del repositorio de GitHub:",
  "CREATE_PROJECT": "Crear proyecto",
  "SETTING_UP_PROJECT": "Configuración del proyecto",
  "LOCATION": "Ubicación :",
  "DOWNLOADING": "Descargando...",
  "EXTRACTING_FILES_PROGRESS": "Extrayendo {0} de {1} archivos.",
  "DOWNLOAD_FAILED_MESSAGE": "Asegúrese de que la URL de descarga sea válida. </br>NB: Como Phoenix está en versión alfa, no se permiten repositorios privados ni direcciones URL de GitHub de más de 25 MB.",
  "PLEASE_SELECT_A_FOLDER": "Seleccione una carpeta...",
  "UNZIP_IN_PROGRESS": "Descomprimiendo archivos...",
  "UNZIP_FAILED": "Error: Error al descomprimir.",
  "CONFIRM_REPLACE_TITLE": "Confirmar Reemplazar",
  "KEEP_BOTH": "Mantén ambos",
  "EXPLORE": "Juegos HTML",
  "BLOG": "Blog",
  "PHOENIX_DEFAULT_PROJECT": "Proyecto predeterminado",
  "PROJECT_NAME": "Nombre del proyecto:",
  "NEW_HTML": "Nuevo proyecto HTML",
  "LICENSE": "Licencia:",
  "CREDITS": "Créditos:",
  "PREVIEW": "Avance",
  "BUILD_WEBSITE": "Crear sitio web",
  "VIEW_MORE": "Ver más...",
  "NEW_PROJECT_NOTIFICATION": "Haga clic en este icono para<br/> crear un nuevo proyecto.</br> <a href='#' style='float:right;'>OK</a>",
  "DEFAULT_PROJECT_NOTIFICATION": "Haga clic aquí para abrir el<br/> <b>proyecto por defecto</b> en phoenix.</br> <a href='#' style='float:right;'>OK</a>",
  "DIRECTORY_REPLACE_MESSAGE": "La carpeta seleccionada <span class='dialog-filename'>{0}</span> no está vacía. ¿Está seguro de que desea reemplazar el contenido de la carpeta con el proyecto?",
  "BUILD_WEBSITE_SECTION": "Crear sitio web",
  "LEARN_SECTION": "Aprende con ejemplos",
  "WEBPAGE_HOME_PAGE": "Diseños de página de inicio",
  "WEBPAGE_BLOG": "Página de blog",
  "WEBPAGE_DASHBOARD": "Tablero HTML",
  "WEBPAGE_BOOTSTRAP_EXAMPLES": "Ejemplos de arranque",
  "GUIDED_FILES_SIDEBAR": "Seleccione un archivo HTML</br> <a href='#' style='float:right;'>OK</a>",
  "GUIDED_LIVE_PREVIEW": "Realice algunos cambios en el código y guarde el archivo para ver una vista previa.</br> <a href='#' style='float:right;'>OK</a>",
  "GUIDED_LIVE_PREVIEW_POPOUT": "Haga clic en este botón para abrir una vista previa en vivo en una nueva pestaña.</br> <a href='#' style='float:right;'>OK</a>",
  "TEST_TRANSLATE": "usa esto para probar las traducciones",
  "BEAUTIFY_ERROR": "No se pudo embellecer el código. Compruebe la sintaxis.",
  "BEAUTIFY_ERROR_ORIGINAL_CHANGED": "No se pudo embellecer. El texto del editor cambió después del embellecimiento.",
  "BEAUTIFY_PROJECT_BUSY_MESSAGE": "Archivo embellecedor {0}",
  "BEAUTIFY_ERROR_SELECTION": "No se pudo embellecer.</br>Bloque de código incompleto seleccionado o sintaxis no válida.",
  "BEAUTIFY_OPTIONS": "Opciones que controlan cómo funciona Beautify Code",
  "BEAUTIFY_OPTION_PRINT_WIDTH": "Especifique la longitud de la línea en la que se envolverá el embellecedor",
  "BEAUTIFY_OPTION_SEMICOLON": "Agregue un punto y coma al final de cada declaración",
  "BEAUTIFY_OPTION_SINGLE_QUOTE": "Use comillas simples en lugar de comillas dobles",
  "BEAUTIFY_OPTION_QUOTE_PROPS": "Cambiar cuando se citan las propiedades de los objetos",
  "BEAUTIFY_OPTION_BRACKET_SAME_LINE": "Coloque el > de un elemento HTML de varias líneas (HTML, JSX, Vue, Angular) al final de la última línea en lugar de estar solo en la línea siguiente (no se aplica a los elementos de cierre automático)",
  "BEAUTIFY_OPTION_SINGLE_ATTRIBUTE_PER_LINE": "Aplique un solo atributo por línea en HTML, Vue y JSX",
  "BEAUTIFY_OPTION_PROSE_WRAP": "Envuelva la prosa si excede el ancho de impresión en los archivos de rebajas",
  "BEAUTIFY_OPTION_PRINT_TRAILING_COMMAS": "Imprima comas finales siempre que sea posible en estructuras sintácticas separadas por comas de varias líneas"
});