/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "സ്ഥിരസ്ഥിതി സിസ്റ്റം",
  "PROJECT_BUSY": "പദ്ധതി പ്രവർത്തനങ്ങൾ പുരോഗമിക്കുന്നു",
  "DUPLICATING": "ഡ്യൂപ്ലിക്കേറ്റിംഗ് {0}",
  "MOVING": "നീക്കുന്നു {0}",
  "COPYING": "പകർത്തുന്നു {0}",
  "DELETING": "{0} ഇല്ലാതാക്കുന്നു",
  "RENAMING": "പുനർനാമകരണം",
  "GENERIC_ERROR": "(പിശക് {0})",
  "NOT_FOUND_ERR": "ഫയൽ/ഡയറക്ടറി കണ്ടെത്താൻ കഴിഞ്ഞില്ല.",
  "NOT_READABLE_ERR": "ഫയൽ/ഡയറക്ടറി വായിക്കാൻ കഴിഞ്ഞില്ല.",
  "EXCEEDS_MAX_FILE_SIZE": "{0} MB യിൽ കൂടുതലുള്ള ഫയലുകൾ {APP_NAME} ൽ തുറക്കാൻ കഴിയില്ല.",
  "NO_MODIFICATION_ALLOWED_ERR": "ടാർഗെറ്റ് ഡയറക്ടറി പരിഷ്ക്കരിക്കാൻ കഴിയില്ല.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "പരിഷ്കാരങ്ങൾ വരുത്താൻ അനുമതികൾ നിങ്ങളെ അനുവദിക്കുന്നില്ല.",
  "CONTENTS_MODIFIED_ERR": "ഫയൽ {APP_NAME} ന് പുറത്ത് പരിഷ്ക്കരിച്ചു.",
  "UNSUPPORTED_ENCODING_ERR": "അജ്ഞാത എൻകോഡിംഗ് ഫോർമാറ്റ്",
  "ENCODE_FILE_FAILED_ERR": "{APP_NAME} ഫയലിന്റെ ഉള്ളടക്കങ്ങൾ എൻകോഡ് ചെയ്യാൻ കഴിഞ്ഞില്ല.",
  "DECODE_FILE_FAILED_ERR": "{APP_NAME} ഫയലിന്റെ ഉള്ളടക്കങ്ങൾ ഡീകോഡ് ചെയ്യാൻ കഴിഞ്ഞില്ല.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "{APP_NAME} നിലവിൽ UTF-16 എൻകോഡ് ചെയ്ത ടെക്സ്റ്റ് ഫയലുകളെ പിന്തുണയ്ക്കുന്നില്ല.",
  "FILE_EXISTS_ERR": "ഫയൽ അല്ലെങ്കിൽ ഡയറക്ടറി ഇതിനകം നിലവിലുണ്ട്.",
  "FILE": "ഫയൽ",
  "FILE_TITLE": "ഫയൽ",
  "DIRECTORY": "ഡയറക്ടറി",
  "DIRECTORY_TITLE": "ഡയറക്ടറി",
  "DIRECTORY_NAMES_LEDE": "ഡയറക്ടറി പേരുകൾ",
  "FILENAMES_LEDE": "ഫയൽനാമങ്ങൾ",
  "FILENAME": "ഫയലിന്റെ",
  "DIRECTORY_NAME": "ഡയറക്ടറി പേര്",
  "ERROR_LOADING_PROJECT": "പ്രോജക്റ്റ് ലോഡുചെയ്യുന്നു",
  "OPEN_DIALOG_ERROR": "തുറന്ന ഫയൽ ഡയലോഗ് കാണിക്കുമ്പോൾ ഒരു പിശക് സംഭവിച്ചു. (പിശക് {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "<span class='dialog-filename'>{ 0}</span>ഡയറക്ടറി ലോഡ് ചെയ്യാൻ ശ്രമിക്കുമ്പോൾ ഒരു പിശക് സംഭവിച്ചു. (പിശക് {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "<span class='dialog-filename'>{ 0}</span>ഡയറക്ടറിയിലെ ഉള്ളടക്കങ്ങൾ വായിക്കുമ്പോൾ ഒരു പിശക് സംഭവിച്ചു. (പിശക് {1})",
  "ERROR_OPENING_FILE_TITLE": "ഫയൽ തുറക്കുന്നതിൽ പിശക്",
  "ERROR_OPENING_FILE": "<span class='dialog-filename'>{ 0}</span>ഫയൽ തുറക്കാൻ ശ്രമിക്കുമ്പോൾ ഒരു പിശക് സംഭവിച്ചു. {1}",
  "ERROR_OPENING_FILES": "ഇനിപ്പറയുന്ന ഫയലുകൾ തുറക്കാൻ ശ്രമിക്കുമ്പോൾ ഒരു പിശക് സംഭവിച്ചു:",
  "ERROR_RELOADING_FILE_TITLE": "ഡിസ്കിൽ നിന്നും മാറ്റങ്ങൾ വീണ്ടും ലോഡുചെയ്യുന്നു പിശക്",
  "ERROR_RELOADING_FILE": "<span class='dialog-filename'>{ 0}</span>ഫയൽ റീലോഡ് ചെയ്യാൻ ശ്രമിക്കുമ്പോൾ ഒരു പിശക് സംഭവിച്ചു. {1}",
  "ERROR_SAVING_FILE_TITLE": "ഫയൽ സംരക്ഷിക്കുന്നതിൽ പിശക്",
  "ERROR_SAVING_FILE": "<span class='dialog-filename'>{ 0}</span>ഫയൽ സംരക്ഷിക്കാൻ ശ്രമിക്കുമ്പോൾ ഒരു പിശക് സംഭവിച്ചു. {1}",
  "ERROR_RENAMING_FILE_TITLE": "പേരുമാറ്റുന്നതിൽ പിശക് {0}",
  "ERROR_RENAMING_FILE": "{2} { <span class='dialog-filename'>0</span>} എന്ന് പുനർനാമകരണം ചെയ്യാൻ ശ്രമിക്കുമ്പോൾ ഒരു പിശക് സംഭവിച്ചു. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "ഫയൽ അല്ലെങ്കിൽ ഡയറക്ടറി നിലവിൽ തുറന്ന പ്രോജക്റ്റിന്റെ ഭാഗമല്ല. നിർഭാഗ്യവശാൽ, പ്രോജക്റ്റ് ഫയലുകൾ മാത്രമേ ഈ സമയത്ത് പുനർനാമകരണം ചെയ്യാൻ കഴിയൂ.",
  "ERROR_MOVING_FILE_TITLE": "നീക്കുന്നതിൽ പിശക് {0}",
  "ERROR_MOVING_FILE": "{2} { <span class='dialog-filename'>0</span>} നീക്കാൻ ശ്രമിക്കുമ്പോൾ ഒരു പിശക് സംഭവിച്ചു. {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "നിലവിലെ പ്രോജക്റ്റിന്റെ ഭാഗമല്ലാത്തതിനാൽ ഫയൽ/ഫോൾഡർ നീക്കാൻ കഴിയില്ല.",
  "ERROR_DELETING_FILE_TITLE": "{0} ഇല്ലാതാക്കുന്നതിൽ പിശക്",
  "ERROR_DELETING_FILE": "{2} { <span class='dialog-filename'>0</span>} ഇല്ലാതാക്കാൻ ശ്രമിക്കുമ്പോൾ ഒരു പിശക് സംഭവിച്ചു. {1}",
  "INVALID_FILENAME_TITLE": "അസാധുവായ {0}",
  "CANNOT_PASTE_TITLE": "{0} ഒട്ടിക്കാൻ കഴിയില്ല",
  "ERR_TYPE_PASTE_FAILED": "<span class='dialog-filename'>{ 0} <span class='dialog-filename'>{1}</span> </span> ലേക്ക് ഒട്ടിക്കുമ്പോൾ ഒരു പിശക് സംഭവിച്ചു",
  "CANNOT_DUPLICATE_TITLE": "ഡ്യൂപ്ലിക്കേറ്റ് ചെയ്യാൻ കഴിയില്ല",
  "ERR_TYPE_DUPLICATE_FAILED": "<span class='dialog-filename'>{ 0}</span>തനിപ്പകർപ്പ് ചെയ്യുമ്പോൾ ഒരു പിശക് സംഭവിച്ചു",
  "INVALID_FILENAME_MESSAGE": "{0} സിസ്റ്റം റിസർവ് ചെയ്ത വാക്കുകളൊന്നും ഉപയോഗിക്കാൻ കഴിയില്ല, ഡോട്ടുകൾ ഉപയോഗിച്ച് അവസാനിപ്പിക്കുക (.) അല്ലെങ്കിൽ ഇനിപ്പറയുന്ന ഏതെങ്കിലും പ്രതീകങ്ങൾ ഉപയോഗിക്കുക: <code class='emphasized'>{1}</code>",
  "ENTRY_WITH_SAME_NAME_EXISTS": "<span class='dialog-filename'>{ 0}</span> എന്ന പേരിലുള്ള ഒരു ഫയൽ അല്ലെങ്കിൽ ഡയറക്ടറി ഇതിനകം നിലവിലുണ്ട്.",
  "ERROR_CREATING_FILE_TITLE": "{0} സൃഷ്ടിക്കുന്നതിൽ പിശക്",
  "ERROR_CREATING_FILE": "{0} { <span class='dialog-filename'>1</span>} സൃഷ്ടിക്കാൻ ശ്രമിക്കുമ്പോൾ ഒരു പിശക് സംഭവിച്ചു. {2}",
  "ERROR_MIXED_DRAGDROP": "മറ്റ് ഫയലുകൾ തുറക്കുന്ന അതേ സമയം ഒരു ഫോൾഡർ തുറക്കാൻ കഴിയില്ല.",
  "ERROR_KEYMAP_TITLE": "ഉപയോക്തൃ കീ മാപ്പ് വായിക്കുന്നതിൽ പിശക്",
  "ERROR_KEYMAP_CORRUPT": "നിങ്ങളുടെ കീ മാപ്പ് ഫയൽ സാധുവായ JSONE അല്ല. ഫയൽ തുറക്കും, അങ്ങനെ നിങ്ങൾക്ക് ഫോർമാറ്റ് ശരിയാക്കാൻ കഴിയും.",
  "ERROR_LOADING_KEYMAP": "നിങ്ങളുടെ കീ മാപ്പ് ഫയൽ സാധുവായ UTF-8 എൻകോഡ് ചെയ്ത ടെക്സ്റ്റ് ഫയലല്ല, മാത്രമല്ല ലോഡുചെയ്യാൻ കഴിയില്ല",
  "ERROR_RESTRICTED_COMMANDS": "ഈ കമാൻഡുകളിലേക്ക് നിങ്ങൾക്ക് കുറുക്കുവഴികൾ പുനർനിയമിക്കാൻ കഴിയില്ല: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "നിങ്ങൾക്ക് ഈ കുറുക്കുവഴികൾ പുനർനിയമിക്കാൻ കഴിയില്ല: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "ഈ കമാൻഡുകളിലേക്ക് നിങ്ങൾ ഒന്നിലധികം കുറുക്കുവഴികൾ പുനർനിയമിക്കുന്നു: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "ഈ കുറുക്കുവഴികളുടെ ഒന്നിലധികം ബൈൻഡിംഗുകൾ നിങ്ങൾക്ക് ഉണ്ട്: {0}",
  "ERROR_INVALID_SHORTCUTS": "ഈ കുറുക്കുവഴികൾ അസാധുവാണ്: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "നിലവിലില്ലാത്ത കമാൻഡുകളിലേക്ക് നിങ്ങൾ കുറുക്കുവഴികൾ നൽകുകയാണ്: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "മുൻഗണനകൾ വായിക്കുന്നതിൽ പിശക്",
  "ERROR_PREFS_CORRUPT": "നിങ്ങളുടെ മുൻഗണനകൾ ഫയൽ സാധുവായ JSONE അല്ല. ഫയൽ തുറക്കും, അങ്ങനെ നിങ്ങൾക്ക് ഫോർമാറ്റ് ശരിയാക്കാൻ കഴിയും. മാറ്റങ്ങൾ പ്രാബല്യത്തിൽ വരുന്നതിന് നിങ്ങൾ {APP_NAME} പുനരാരംഭിക്കേണ്ടതുണ്ട്.",
  "ERROR_PROJ_PREFS_CORRUPT": "നിങ്ങളുടെ പദ്ധതി മുൻഗണനകൾ ഫയൽ സാധുവായ JSONE അല്ല. ഫയൽ തുറക്കും, അങ്ങനെ നിങ്ങൾക്ക് ഫോർമാറ്റ് ശരിയാക്കാൻ കഴിയും. മാറ്റങ്ങൾ പ്രാബല്യത്തിൽ വരുന്നതിന് നിങ്ങൾ പ്രോജക്റ്റ് വീണ്ടും ലോഡുചെയ്യേണ്ടതുണ്ട്.",
  "ERROR_IN_BROWSER_TITLE": "ശ്ശോ! {APP_NAME} ഇതുവരെ ബ്രൗസറുകളിൽ പ്രവർത്തിക്കുന്നില്ല.",
  "ERROR_IN_BROWSER": "{APP_NAME} എച്ച്ടിഎംഎല്ലിലാണ് നിർമ്മിച്ചിരിക്കുന്നത്, പക്ഷേ ഇപ്പോൾ ഇത് ഒരു ഡെസ്ക്ടോപ്പ് അപ്ലിക്കേഷനായി പ്രവർത്തിക്കുന്നതിനാൽ പ്രാദേശിക ഫയലുകൾ എഡിറ്റുചെയ്യാൻ നിങ്ങൾക്ക് ഇത് ഉപയോഗിക്കാൻ കഴിയും. {APP_NAME} പ്രവർത്തിപ്പിക്കാൻ <b>github.com/adobe/brackets-shell</b> repo ലെ ആപ്ലിക്കേഷൻ ഷെൽ ഉപയോഗിക്കുക.",
  "ERROR_MAX_FILES_TITLE": "ഫയലുകൾ ഇൻഡെക്സിംഗ് പിശക്",
  "ERROR_MAX_FILES": "ഈ പ്രോജക്റ്റിൽ 30,000 ലധികം ഫയലുകൾ അടങ്ങിയിരിക്കുന്നു. ഒന്നിലധികം ഫയലുകളിലുടനീളം പ്രവർത്തിക്കുന്ന സവിശേഷതകൾ അപ്രാപ്തമാക്കിയേക്കാം അല്ലെങ്കിൽ പ്രോജക്റ്റ് ശൂന്യമാണ് പോലെ പെരുമാറാം. <a href='https://github.com/adobe/brackets/wiki/Large-Projects'>വലിയ പ്രോജക്റ്റുകളിൽ പ്രവർത്തിക്കുന്നതിനെക്കുറിച്ച് കൂടുതൽ വായിക്കുക</a>.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "ബ്രൗസർ സമാരംഭിക്കുന്നതിൽ",
  "ERROR_CANT_FIND_CHROME": "Google Chrome ബ്രൗസർ കണ്ടെത്താനായില്ല. ഇത് ഇൻസ്റ്റാൾ ചെയ്തിട്ടുണ്ടെന്ന് ഉറപ്പാക്കുക.",
  "ERROR_LAUNCHING_BROWSER": "ബ്രൗസർ സമാരംഭിക്കുമ്പോൾ ഒരു പിശക് സംഭവിച്ചു. (പിശക് {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "തൽസമയ പ്രിവ്യൂ പിശക്",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "ബ്രൗസറിലേക്ക് ബന്ധിപ്പിക്കുന്നു",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "തത്സമയ പ്രിവ്യൂ കണക്റ്റുചെയ്യുന്നതിന്, വിദൂര ഡീബഗ്ഗിംഗ് പ്രവർത്തനക്ഷമമാക്കി Chrome വീണ്ടും സമാരംഭിക്കേണ്ടതുണ്ട്. <br /><br />Chrome വീണ്ടും സമാരംഭിക്കാനും വിദൂര ഡീബഗ്ഗിംഗ് പ്രവർത്തനക്ഷമമാക്കാനും നിങ്ങൾ ആഗ്രഹിക്കുന്നുണ്ടോ? <br /><br />",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "ലൈവ് പ്രിവ്യൂ പേജ് ലോഡ് ചെയ്യാൻ കഴിയുന്നില്ല.",
  "LIVE_DEV_NEED_HTML_MESSAGE": "ഒരു HTML ഫയൽ തുറക്കുക അല്ലെങ്കിൽ തത്സമയ പ്രിവ്യൂ സമാരംഭിക്കുന്നതിന് നിങ്ങളുടെ പ്രോജക്റ്റിൽ ഒരു index.html ഫയൽ ഉണ്ടെന്ന് ഉറപ്പാക്കുക.",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "ഒരു സെർവർ സൈഡ് ഫയൽ ഉപയോഗിച്ച് തത്സമയ പ്രിവ്യൂ സമാരംഭിക്കുന്നതിന്, ഈ പ്രോജക്റ്റിനായി നിങ്ങൾ ഒരു അടിസ്ഥാന URL വ്യക്തമാക്കേണ്ടതുണ്ട്.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "തൽസമയ പ്രിവ്യൂ ഫയലുകൾക്കായി HTTP സെർവർ ആരംഭിക്കുന്നതിൽ പിശക്. ദയവായി വീണ്ടും ശ്രമിക്കുക.",
  "LIVE_DEVELOPMENT_INFO_TITLE": "ലൈവ് പ്രിവ്യൂ സ്വാഗതം!",
  "LIVE_DEVELOPMENT_INFO_MESSAGE": "ലൈവ് പ്രിവ്യൂ നിങ്ങളുടെ ബ്രൗസറിലേക്ക് {APP_NAME} ബന്ധിപ്പിക്കുന്നു. ഇത് ബ്രൗസറിൽ നിങ്ങളുടെ HTML ഫയൽ ഒരു പ്രിവ്യൂ സമാരംഭിക്കുന്നു, തുടർന്ന് നിങ്ങളുടെ കോഡ് എഡിറ്റ് പോലെ തൽക്ഷണം പ്രിവ്യൂ അപ്ഡേറ്റുകൾ. <br /><br />{ APP_NAME} ന്റെ ഈ ആദ്യകാല പതിപ്പിൽ, തത്സമയ പ്രിവ്യൂ <strong>Google Chrome-</strong> ൽ മാത്രമേ പ്രവർത്തിക്കൂ, നിങ്ങൾ <strong>CSS അല്ലെങ്കിൽ HTML ഫയലുകൾ</strong> എഡിറ്റുചെയ്യുന്നതുപോലെ അപ്ഡേറ്റുകൾ തത്സമയം പ്രവർത്തിക്കുന്നു. നിങ്ങൾ സംരക്ഷിക്കുമ്പോൾ JavaScript ഫയലുകളിലെ മാറ്റങ്ങൾ യാന്ത്രികമായി റീലോഡുചെയ്യപ്പെടും. <br /><br />( നിങ്ങൾ ഒരിക്കൽ മാത്രമേ ഈ സന്ദേശം കാണും.)",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "കൂടുതൽ വിവരങ്ങൾക്ക്, കാണുക <a href='{0}' title='{0}'>ട്രബിൾഷൂട്ടിംഗ് ലൈവ് പ്രിവ്യൂ കണക്ഷൻ പിശകുകൾ</a>.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "തത്സമയ പ്രിവ്യൂ",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "തത്സമയ പ്രിവ്യൂ: കണക്റ്റുചെയ്യുന്നു...",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "തത്സമയ പ്രിവ്യൂ: സമാരംഭിക്കുന്നു...",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "തത്സമയ പ്രിവ്യൂ വിച്ഛേദിക്കുക",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "തത്സമയ പ്രിവ്യൂ (പുതുക്കാൻ ഫയൽ സംരക്ഷിക്കുക)",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "തൽസമയ പ്രിവ്യൂ ഫയൽ തിരഞ്ഞെടുക്കുക",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "പേജ് വീണ്ടും ലോഡുചെയ്യുക",
  "LIVE_DEV_CLICK_POPOUT": "പുതിയ വിൻഡോയിലേക്ക് പോപ്പ് out ട്ട് ലൈവ് പ്രിവ്യൂ",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "അൺപിൻ പ്രിവ്യൂ പേജിൽ പിൻ ചെയ്യുക",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "തത്സമയ പ്രിവ്യൂ (വാക്യഘടന പിശക് കാരണം അപ്ഡേറ്റ് ചെയ്യുന്നില്ല)",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "ബ്രൗസറിന്റെ ഡവലപ്പർ ടൂളുകൾ തുറന്നതിനാൽ ലൈവ് പ്രിവ്യൂ റദ്ദാക്കി",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "ബ്രൗസറിൽ പേജ് അടച്ചതിനാൽ തത്സമയ പ്രിവ്യൂ റദ്ദാക്കി",
  "LIVE_DEV_NAVIGATED_AWAY": "നിലവിലെ പ്രോജക്റ്റിന്റെ ഭാഗമല്ലാത്ത ഒരു പേജിലേക്ക് ബ്രൗസർ നാവിഗേറ്റുചെയ്തതിനാൽ തത്സമയ പ്രിവ്യൂ റദ്ദാക്കി",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "അജ്ഞാതമായ കാരണത്താൽ തത്സമയ പ്രിവ്യൂ റദ്ദാക്കി ({0})",
  "SAVE_CLOSE_TITLE": "മാറ്റങ്ങൾ സംരക്ഷിക്കുക",
  "SAVE_CLOSE_MESSAGE": "<span class='dialog-filename'>{ 0}</span>പ്രമാണത്തിൽ നിങ്ങൾ വരുത്തിയ മാറ്റങ്ങൾ സംരക്ഷിക്കാൻ നിങ്ങൾ ആഗ്രഹിക്കുന്നുണ്ടോ?",
  "SAVE_CLOSE_MULTI_MESSAGE": "ഇനിപ്പറയുന്ന ഫയലുകളിലേക്ക് നിങ്ങളുടെ മാറ്റങ്ങൾ സംരക്ഷിക്കാൻ നിങ്ങൾ ആഗ്രഹിക്കുന്നുണ്ടോ?",
  "EXT_MODIFIED_TITLE": "ബാഹ്യ മാറ്റങ്ങൾ",
  "CONFIRM_DELETE_TITLE": "ഇല്ലാതാക്കുക സ്ഥിരീകരിക്കുക",
  "CONFIRM_FILE_DELETE": "<span class='dialog-filename'>{ 0}</span>ഫയൽ നീക്കം ചെയ്യണമെന്ന് നിങ്ങൾക്ക് ഉറപ്പാണോ?",
  "CONFIRM_FOLDER_DELETE": "ഫോൾഡർ <span class='dialog-filename'>{0}</span>ഇല്ലാതാക്കണമെന്ന് നിങ്ങൾക്ക് ഉറപ്പാണോ?",
  "FILE_DELETED_TITLE": "ഫയൽ ഇല്ലാതാക്കി",
  "EXT_MODIFIED_WARNING": "<span class='dialog-filename'>{ 0}</span> {APP_NAME} ന് പുറത്തുള്ള ഡിസ്കിൽ മാറ്റം വരുത്തിയിരിക്കുന്നു. <br /><br />ഫയൽ സംരക്ഷിച്ച് ആ മാറ്റങ്ങൾ തിരുത്തിയെഴുതാൻ നിങ്ങൾ ആഗ്രഹിക്കുന്നുണ്ടോ?",
  "EXT_MODIFIED_MESSAGE": "<span class='dialog-filename'>{ 0}</span> {APP_NAME} ന് പുറത്തുള്ള ഡിസ്കിൽ പരിഷ്ക്കരിച്ചു, മാത്രമല്ല {APP_NAME} ൽ സംരക്ഷിക്കാത്ത മാറ്റങ്ങളും ഉണ്ട്. <br /><br />ഏത് പതിപ്പാണ് നിങ്ങൾ സൂക്ഷിക്കാൻ ആഗ്രഹിക്കുന്നത്?",
  "EXT_DELETED_MESSAGE": "<span class='dialog-filename'>{ 0}</span> {APP_NAME} ന് പുറത്തുള്ള ഡിസ്കിൽ ഇല്ലാതാക്കി, പക്ഷേ {APP_NAME} ൽ സംരക്ഷിക്കാത്ത മാറ്റങ്ങൾ ഉണ്ട്. <br /><br />നിങ്ങളുടെ മാറ്റങ്ങൾ നിലനിർത്താൻ നിങ്ങൾ ആഗ്രഹിക്കുന്നുണ്ടോ?",
  "WINDOW_UNLOAD_WARNING": "മറ്റൊരു URL- ലേക്ക് നാവിഗേറ്റുചെയ്യാനും ബ്രാക്കറ്റുകൾ ഉപേക്ഷിക്കാനും നിങ്ങൾ ആഗ്രഹിക്കുന്നുണ്ടോ?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "നിങ്ങൾക്ക് സംരക്ഷിക്കാത്ത മാറ്റങ്ങൾ ഉണ്ട്! മറ്റൊരു URL- ലേക്ക് നാവിഗേറ്റുചെയ്യാനും ബ്രാക്കറ്റുകൾ ഉപേക്ഷിക്കാനും നിങ്ങൾ ആഗ്രഹിക്കുന്നുണ്ടോ?",
  "DONE": "പൂർത്തിയായി",
  "OK": "ശരി",
  "CANCEL": "റദ്ദാക്കുക",
  "DONT_SAVE": "സംരക്ഷിക്കരുത്",
  "SAVE": "സംരക്ഷിക്കുക",
  "SAVE_AS": "ഇതായി സംരക്ഷിക്കുക...",
  "SAVE_AND_OVERWRITE": "തിരുത്തിയെഴുതുക",
  "DELETE": "ഇല്ലാതാക്കുക",
  "BUTTON_YES": "അതെ",
  "BUTTON_NO": "ഇല്ല",
  "FIND_MATCH_INDEX": "{0} ഓഫ് {1}",
  "FIND_NO_RESULTS": "ഫലങ്ങളൊന്നുമില്ല",
  "FIND_QUERY_PLACEHOLDER": "കണ്ടെത്തുക...",
  "FIND_HISTORY_MAX_COUNT": "തിരയൽ ചരിത്രത്തിലെ തിരയൽ ഇനങ്ങളുടെ പരമാവധി എണ്ണം",
  "REPLACE_PLACEHOLDER": "മാറ്റിസ്ഥാപിക്കുക...",
  "BUTTON_REPLACE_ALL": "എല്ലാം മാറ്റിസ്ഥാപിക്കുക",
  "BUTTON_REPLACE_BATCH": "ബാച്ച്...",
  "BUTTON_REPLACE_ALL_IN_FILES": "മാറ്റിസ്ഥാപിക്കുക...",
  "BUTTON_REPLACE": "മാറ്റിസ്ഥാപിക്കുക",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "അടുത്ത മാച്ച്",
  "BUTTON_PREV_HINT": "മുമ്പത്തെ മാച്ച്",
  "BUTTON_CASESENSITIVE_HINT": "മാച്ച് കേസ്",
  "BUTTON_REGEXP_HINT": "പതിവ് എക്സ്പ്രഷൻ",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "പഴയ ഇല്ലാതെ മാറ്റിസ്ഥാപിക്കുക",
  "REPLACE_WITHOUT_UNDO_WARNING": "{0} ഫയലുകളിൽ കൂടുതൽ മാറ്റേണ്ടതിനാൽ, {APP_NAME} ഡിസ്കിൽ തുറക്കാത്ത ഫയലുകൾ പരിഷ്ക്കരിക്കും. <br />നിങ്ങൾക്ക് ആ ഫയലുകളിൽ മാറ്റിസ്ഥാപിക്കലുകൾ പുന: സ്ഥാപിക്കാൻ കഴിയില്ല.",
  "BUTTON_REPLACE_WITHOUT_UNDO": "പഴയ ഇല്ലാതെ മാറ്റിസ്ഥാപിക്കുക",
  "OPEN_FILE": "തുറക്കുക ഫയൽ",
  "SAVE_FILE_AS": "ഫയൽ സംരക്ഷിക്കുക",
  "CHOOSE_FOLDER": "ഒരു ഫോൾഡർ തിരഞ്ഞെടുക്കുക",
  "RELEASE_NOTES": "റിലീസ് കുറിപ്പുകൾ",
  "NO_UPDATE_TITLE": "നിങ്ങൾ കാലികമാണ്!",
  "NO_UPDATE_MESSAGE": "നിങ്ങൾ {APP_NAME} ന്റെ ഏറ്റവും പുതിയ പതിപ്പ് പ്രവർത്തിപ്പിക്കുന്നു.",
  "FIND_REPLACE_TITLE_LABEL": "മാറ്റിസ്ഥാപിക്കുക",
  "FIND_REPLACE_TITLE_WITH": "കൂടെ",
  "FIND_TITLE_LABEL": "കണ്ടെത്തി",
  "FIND_TITLE_SUMMARY": "— {0} {1} {2} {3}",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "<span class='dialog-filename'>{ 0}</span>",
  "FIND_IN_FILES_NO_SCOPE": "പ്രോജക്റ്റിൽ",
  "FIND_IN_FILES_ZERO_FILES": "ഫിൽറ്റർ എല്ലാ ഫയലുകളും ഒഴിവാക്കുന്നു {0}",
  "FIND_IN_FILES_FILE": "ഫയൽ",
  "FIND_IN_FILES_FILES": "ഫയലുകൾ",
  "FIND_IN_FILES_MATCH": "മത്സരം",
  "FIND_IN_FILES_MATCHES": "മത്സരങ്ങൾ",
  "FIND_IN_FILES_MORE_THAN": "ഓവര് ",
  "FIND_IN_FILES_PAGING": "{0} - {1}",
  "FIND_IN_FILES_FILE_PATH": "<span class='dialog-filename'>{ 0}</span> {2} <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "എല്ലാം വിപുലീകരിക്കാനും ചുരുക്കാനും Ctrl/Cmd ക്ലിക്കുചെയ്യുക",
  "FIND_IN_FILES_INDEXING": "തൽക്ഷണ തിരയലിനായി ഇൻഡെക്സിംഗ്...",
  "FIND_IN_FILES_INDEXING_PROGRESS": "തൽക്ഷണ തിരയലിനായി {0} {1} ഫയലുകളുടെ സൂചികയിലാക്കുന്നു...",
  "REPLACE_IN_FILES_ERRORS_TITLE": "പിശകുകൾ മാറ്റിസ്ഥാപിക്കുക",
  "REPLACE_IN_FILES_ERRORS": "താഴെ ഫയലുകൾ അവർ തിരയൽ ശേഷം മാറ്റി അല്ലെങ്കിൽ എഴുതാൻ കഴിഞ്ഞില്ല കാരണം പരിഷ്ക്കരിച്ചില്ല.",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "അപ്ഡേറ്റ് വിവരം നേടുന്നതിൽ പിശക്",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "സെർവറിൽ നിന്ന് ഏറ്റവും പുതിയ അപ്ഡേറ്റ് വിവരങ്ങൾ ലഭിക്കുന്നതിൽ ഒരു പ്രശ്നമുണ്ടായിരുന്നു. നിങ്ങൾ ഇന്റർനെറ്റിലേക്ക് കണക്റ്റുചെയ്തിട്ടുണ്ടെന്ന് ഉറപ്പുവരുത്തി വീണ്ടും ശ്രമിക്കുക.",
  "NEW_FILE_FILTER": "പുതിയ ഒഴിവാക്കൽ സജ്ജമാക്കുക...",
  "CLEAR_FILE_FILTER": "ഫയലുകൾ ഒഴിവാക്കരുത്",
  "NO_FILE_FILTER": "ഒഴിവാക്കിയ ഫയലുകൾ ഇല്ല",
  "EXCLUDE_FILE_FILTER": "ഒഴിവാക്കുക {0}",
  "EDIT_FILE_FILTER": "എഡിറ്റുചെയ്യുക...",
  "FILE_FILTER_DIALOG": "ഒഴിവാക്കൽ സെറ്റ് എഡിറ്റുചെയ്യുക",
  "FILE_FILTER_INSTRUCTIONS": "ഇനിപ്പറയുന്ന ഏതെങ്കിലും സ്ട്രിംഗുകൾ/സബ്സ്ട്രിംഗുകൾ അല്ലെങ്കിൽ <a href='{0}' title='{0}'>വൈൽഡ്കാർഡുകളുമായി</a>പൊരുത്തപ്പെടുന്ന ഫയലുകളും ഫോൾഡറുകളും ഒഴിവാക്കുക. ഒരു പുതിയ വരിയിൽ ഓരോ സ്ട്രിംഗും നൽകുക.",
  "FILTER_NAME_PLACEHOLDER": "ഈ ഒഴിവാക്കൽ സെറ്റിന് പേര് (ഓപ്ഷണൽ)",
  "FILTER_NAME_REMAINING": "{0} പ്രതീകങ്ങൾ ശേഷിക്കുന്നു",
  "FILE_FILTER_CLIPPED_SUFFIX": "ഒപ്പം {0} കൂടുതൽ",
  "FILTER_COUNTING_FILES": "ഫയലുകൾ എണ്ണുന്നു...",
  "FILTER_FILE_COUNT": "{0} {1} ഫയലുകളുടെ {2} അനുവദിക്കുന്നു",
  "FILTER_FILE_COUNT_ALL": "എല്ലാ {0} ഫയലുകളും {1} അനുവദിക്കുന്നു",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "നിലവിലെ കഴ്സർ സ്ഥാനത്തിനായി ദ്രുത എഡിറ്റ് ലഭ്യമല്ല",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "CSS ദ്രുത എഡിറ്റ്: ഒരൊറ്റ ക്ലാസ് നാമത്തിൽ കഴ്സർ സ്ഥാപിക്കുക",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "CSS ദ്രുത എഡിറ്റ്: അപൂർണ്ണമായ ക്ലാസ് ആട്രിബ്യൂട്ട്",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "CSS ദ്രുത എഡിറ്റ്: അപൂർണ്ണമായ ഐഡി ആട്രിബ്യൂട്ട്",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "CSS ദ്രുത എഡിറ്റ്: ടാഗ്, ക്ലാസ് അല്ലെങ്കിൽ ഐഡിയിൽ കഴ്സർ സ്ഥാപിക്കുക",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "സിഎസ്എസ് ടൈമിംഗ് ഫംഗ്ഷൻ ദ്രുത എഡിറ്റ്: അസാധുവായ വാക്യഘടന",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "JS ദ്രുത എഡിറ്റ്: ഫംഗ്ഷൻ നാമത്തിൽ കഴ്സർ സ്ഥാപിക്കുക",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "നിലവിലെ കഴ്സർ സ്ഥാനത്തിനായി ദ്രുത ഡോക്സുകൾ ലഭ്യമല്ല",
  "PROJECT_LOADING": "ലോഡുചെയ്യുന്നു...",
  "UNTITLED": "ശീർഷകമില്ലാത്ത",
  "WORKING_FILES": "പ്രവർത്തിക്കുന്ന ഫയലുകൾ",
  "TOP": "ടോപ്പ്",
  "BOTTOM": "താഴെ",
  "LEFT": "ഇടത്",
  "RIGHT": "വലത്",
  "CMD_SPLITVIEW_NONE": "സ്പ്ലിറ്റ് ഇല്ല",
  "CMD_SPLITVIEW_VERTICAL": "ലംബ സ്പ്ലിറ്റ്",
  "CMD_SPLITVIEW_HORIZONTAL": "തിരശ്ചീന സ്പ്ലിട്",
  "SPLITVIEW_MENU_TOOLTIP": "എഡിറ്റർ ലംബമായി അല്ലെങ്കിൽ തിരശ്ചീനമായി വിഭജിക്കുക",
  "GEAR_MENU_TOOLTIP": "വർക്കിംഗ് സെറ്റ് കോൺഫിഗർ ചെയ്യുക",
  "SPLITVIEW_INFO_TITLE": "ഇതിനകം തുറക്കുക",
  "SPLITVIEW_MULTIPANE_WARNING": "ഫയൽ ഇതിനകം മറ്റൊരു പാളിയിൽ തുറന്നിരിക്കുന്നു. {APP_NAME} ഉടൻ തന്നെ ഒരേ ഫയൽ ഒന്നിൽ കൂടുതൽ പാളികളിൽ തുറക്കുന്നതിനെ പിന്തുണയ്ക്കും. അതുവരെ, ഫയൽ പാളിയിൽ കാണിക്കും അത് ഇതിനകം തുറന്നിരിക്കുന്നു. <br /><br />( നിങ്ങൾ ഒരിക്കൽ മാത്രമേ ഈ സന്ദേശം കാണും.)",
  "STATUSBAR_CURSOR_POSITION": "വര {0}, നിര {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": " — തിരഞ്ഞെടുത്ത {0} നിര",
  "STATUSBAR_SELECTION_CH_PLURAL": " — തിരഞ്ഞെടുത്ത {0} നിരകൾ",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " — തിരഞ്ഞെടുത്ത {0} വരി",
  "STATUSBAR_SELECTION_LINE_PLURAL": " — തിരഞ്ഞെടുത്ത {0} ലൈനുകൾ",
  "STATUSBAR_SELECTION_MULTIPLE": " — {0} തിരഞ്ഞെടുക്കലുകൾ",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "സ്പെയ്സുകളിലേക്ക് ഇൻഡന്റേഷൻ സ്വിച്ചുചെയ്യുന്നതിന് ക്ലിക്കുചെയ്യുക",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "ടാബുകളിലേക്ക് ഇൻഡന്റേഷൻ മാറാൻ ക്ലിക്കുചെയ്യുക",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "ഇൻഡെന്റ് ചെയ്യുമ്പോൾ ഉപയോഗിക്കുന്ന ഇടങ്ങളുടെ എണ്ണം മാറ്റാൻ ക്ലിക്കുചെയ്യുക",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "ടാബ് പ്രതീക വീതി മാറ്റാൻ ക്ലിക്കുചെയ്യുക",
  "STATUSBAR_SPACES": "ഇടങ്ങൾ:",
  "STATUSBAR_TAB_SIZE": "ടാബ് വലുപ്പം:",
  "STATUSBAR_LINE_COUNT_SINGULAR": "— {0} ലൈൻ",
  "STATUSBAR_LINE_COUNT_PLURAL": "— {0} ലൈനുകൾ",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "വിപുലീകരണങ്ങൾ പ്രവർത്തനരഹിത",
  "STATUSBAR_INSERT": "INS",
  "STATUSBAR_OVERWRITE": "ഒവ്ര്",
  "STATUSBAR_INSOVR_TOOLTIP": "തിരുകുക (ഐഎൻഎസ്), ഓവർറൈറ്റ് (ഒവിആർ) മോഡുകൾക്കിടയിൽ കഴ്സർ ടോഗിൾ ചെയ്യാൻ ക്ലിക്കുചെയ്യുക",
  "STATUSBAR_LANG_TOOLTIP": "ഫയൽ തരം മാറ്റാൻ ക്ലിക്കുചെയ്യുക",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. റിപ്പോർട്ട് പാനൽ ടോഗിൾ ക്ലിക്ക്.",
  "STATUSBAR_DEFAULT_LANG": "(സ്ഥിരസ്ഥിതി)",
  "STATUSBAR_SET_DEFAULT_LANG": "സ്ഥിരസ്ഥിതിയായി സജ്ജമാക്കുക. {0} ഫയലുകൾ",
  "STATUSBAR_ENCODING_TOOLTIP": "എൻകോഡിംഗ് തിരഞ്ഞെടുക്കുക",
  "ERRORS_PANEL_TITLE_MULTIPLE": "{0} പ്രശ്നങ്ങൾ",
  "SINGLE_ERROR": "1 {0} പ്രശ്നം",
  "MULTIPLE_ERRORS": "{1} {0} പ്രശ്നങ്ങൾ",
  "NO_ERRORS": "ഇല്ല {0} പ്രശ്നങ്ങൾ കണ്ടെത്തി - നല്ല ജോലി!",
  "NO_ERRORS_MULTIPLE_PROVIDER": "പ്രശ്നങ്ങളൊന്നും കണ്ടെത്തിയില്ല - നല്ല ജോലി!",
  "LINT_DISABLED": "ലിന്റിംഗ് പ്രവർത്തനരഹിതമാക്കി",
  "NO_LINT_AVAILABLE": "{0} ന് ലിന്റർ ലഭ്യമല്ല",
  "NOTHING_TO_LINT": "ലിന്റ് ചെയ്യാൻ ഒന്നുമില്ല",
  "LINTER_TIMED_OUT": "{0} {1} എംഎസിനായി കാത്തിരുന്ന ശേഷം കാലപ്പഴക്കം തീർന്നിരിക്കുന്നു",
  "LINTER_FAILED": "{0} പിശക് അവസാനിപ്പിച്ചു: {1}",
  "FILE_MENU": "ഫയൽ",
  "CMD_FILE_NEW_UNTITLED": "പുതിയത്",
  "CMD_FILE_NEW": "പുതിയ ഫയൽ",
  "CMD_FILE_DUPLICATE": "ഡ്യൂപ്ലിക്കേറ്റ്",
  "CMD_FILE_CUT": "മുറിക്കുക",
  "CMD_FILE_COPY": "പകർത്തുക",
  "CMD_FILE_COPY_PATH": "പാത പകർത്തുക",
  "CMD_FILE_PASTE": "ഒട്ടിക്കുക",
  "CMD_PROJECT_NEW": "പുതിയ പദ്ധതി",
  "CMD_FILE_NEW_FOLDER": "പുതിയ ഫോൾഡർ",
  "CMD_FILE_OPEN": "തുറക്കുക...",
  "CMD_RECENT_FILES_OPEN": "സമീപകാല തുറക്കുക...",
  "CMD_ADD_TO_WORKING_SET": "ജോലി സജ്ജമാക്കുക തുറക്കുക",
  "CMD_OPEN_DROPPED_FILES": "തുറക്കുക ഉപേക്ഷിച്ച ഫയലുകൾ",
  "CMD_OPEN_FOLDER": "ഫോൾഡർ തുറക്കുക...",
  "CMD_FILE_CLOSE": "അടയ്ക്കുക",
  "CMD_FILE_CLOSE_ALL": "എല്ലാം അടയ്ക്കുക",
  "CMD_FILE_CLOSE_LIST": "പട്ടിക അടയ്ക്കുക",
  "CMD_FILE_CLOSE_OTHERS": "മറ്റുള്ളവ അടയ്ക്കുക",
  "CMD_FILE_CLOSE_ABOVE": "മുകളിൽ മറ്റുള്ളവ അടയ്ക്കുക",
  "CMD_FILE_CLOSE_BELOW": "താഴെ മറ്റുള്ളവ അടയ്ക്കുക",
  "CMD_FILE_SAVE": "സംരക്ഷിക്കുക",
  "CMD_FILE_SAVE_ALL": "എല്ലാം സംരക്ഷിക്കുക",
  "CMD_FILE_SAVE_AS": "ഇതായി സംരക്ഷിക്കുക...",
  "CMD_LIVE_FILE_PREVIEW": "തത്സമയ പ്രിവ്യൂ",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "പരീക്ഷണാത്മക തത്സമയ പ്രിവ്യൂ പ്രാപ്തമാക്കുക",
  "CMD_RELOAD_LIVE_PREVIEW": "ഫോഴ്സ് റീലോഡ് ലൈവ് പ്രിവ്യൂ",
  "CMD_PROJECT_SETTINGS": "പ്രോജക്റ്റ് ക്രമീകരണങ്ങൾ...",
  "CMD_FILE_RENAME": "പുനർനാമകരണം",
  "CMD_FILE_DELETE": "ഇല്ലാതാക്കുക",
  "CMD_INSTALL_EXTENSION": "വിപുലീകരണം ഇൻസ്റ്റാൾ ചെയ്യുക...",
  "CMD_EXTENSION_MANAGER": "എക്സ്റ്റൻഷൻ മാനേജർ...",
  "CMD_FILE_REFRESH": "ഫയൽ ട്രീ പുതുക്കുക",
  "CMD_FILE_SHOW_FOLDERS_FIRST": "ആദ്യം ഫോൾഡറുകൾ അടുക്കുക",
  "CMD_QUIT": "ക്വിറ്റ്",
  "CMD_EXIT": "എക്സിറ്റ്",
  "EDIT_MENU": "എഡിറ്റ്",
  "CMD_UNDO": "ഉന്മുനതെ",
  "CMD_REDO": "വീണ്ടും ചെയ്യുക",
  "CMD_CUT": "മുറിക്കുക",
  "CMD_COPY": "പകർത്തുക",
  "CMD_PASTE": "ഒട്ടിക്കുക",
  "CMD_SELECT_ALL": "എല്ലാം തിരഞ്ഞെടുക്കുക",
  "CMD_SELECT_LINE": "ലൈൻ തിരഞ്ഞെടുക്കുക",
  "CMD_SPLIT_SEL_INTO_LINES": "ലൈനുകളായി തിരഞ്ഞെടുക്കൽ വിഭജിക്കുക",
  "CMD_ADD_CUR_TO_NEXT_LINE": "അടുത്ത വരിയിലേക്ക് കഴ്സർ ചേർക്കുക",
  "CMD_ADD_CUR_TO_PREV_LINE": "മുമ്പത്തെ വരിയിലേക്ക് കഴ്സർ ചേർക്കുക",
  "CMD_INDENT": "ഇൻഡന്റ്",
  "CMD_UNINDENT": "ഉനിംദെംത്",
  "CMD_DUPLICATE": "ഡ്യൂപ്ലിക്കേറ്റ്",
  "CMD_DELETE_LINES": "ലൈൻ ഇല്ലാതാക്കുക",
  "CMD_COMMENT": "ടോഗിൾ ലൈൻ അഭിപ്രായം",
  "CMD_BLOCK_COMMENT": "തടയുക അഭിപ്രായം ടോഗിൾ",
  "CMD_LINE_UP": "ലൈൻ അപ്പ് നീക്കുക",
  "CMD_LINE_DOWN": "ലൈൻ താഴേക്ക് നീക്കുക",
  "CMD_OPEN_LINE_ABOVE": "മുകളിൽ ലൈൻ തുറക്കുക",
  "CMD_OPEN_LINE_BELOW": "താഴെ ലൈൻ തുറക്കുക",
  "CMD_TOGGLE_CLOSE_BRACKETS": "ഓട്ടോ അടയ്ക്കുക വലയം",
  "CMD_SHOW_CODE_HINTS": "കോഡ് സൂചനകൾ കാണിക്കുക",
  "CMD_BEAUTIFY_CODE": "ബ്യൂട്ടിഫൈ കോഡ്",
  "FIND_MENU": "കണ്ടെത്തുക",
  "CMD_FIND": "കണ്ടെത്തുക",
  "CMD_FIND_NEXT": "അടുത്തത് കണ്ടെത്തുക",
  "CMD_FIND_PREVIOUS": "മുമ്പത്തെ കണ്ടെത്തുക",
  "CMD_FIND_ALL_AND_SELECT": "എല്ലാം കണ്ടെത്തി തിരഞ്ഞെടുക്കുക",
  "CMD_ADD_NEXT_MATCH": "തിരഞ്ഞെടുക്കുന്നതിന് അടുത്ത പൊരുത്തം ചേർക്കുക",
  "CMD_SKIP_CURRENT_MATCH": "അടുത്ത മത്സരം ഒഴിവാക്കി ചേർക്കുക",
  "CMD_FIND_IN_FILES": "ഫയലുകൾ കണ്ടെത്തുക",
  "CMD_FIND_IN_SUBTREE": "കണ്ടെത്തുക...",
  "CMD_REPLACE": "മാറ്റിസ്ഥാപിക്കുക",
  "CMD_REPLACE_IN_FILES": "ഫയലുകൾ മാറ്റിസ്ഥാപിക്കുക",
  "CMD_REPLACE_IN_SUBTREE": "മാറ്റിസ്ഥാപിക്കുക...",
  "VIEW_MENU": "കാഴ്ച",
  "CMD_HIDE_SIDEBAR": "സൈഡ്ബാർ മറയ്ക്കുക",
  "CMD_SHOW_SIDEBAR": "സൈഡ്ബാർ കാണിക്കുക",
  "CMD_TOGGLE_SIDEBAR": "സൈഡ്ബാർ ടോഗിൾ ചെയ്യുക",
  "CMD_TOGGLE_PANELS": "ടോഗിൾ പാനലുകൾ",
  "CMD_TOGGLE_PURE_CODE": "ഇല്ല ശ്രദ്ധ",
  "CMD_INCREASE_FONT_SIZE": "ഫോണ്ട് വലുപ്പം വർദ്ധിപ്പിക്കുക",
  "CMD_DECREASE_FONT_SIZE": "ഫോണ്ട് വലുപ്പം കുറയ്ക്കുക",
  "CMD_RESTORE_FONT_SIZE": "ഫോണ്ട് വലുപ്പം പുനഃസ്ഥാപിക്കുക",
  "CMD_SCROLL_LINE_UP": "സ്ക്രോൾ ലൈൻ അപ്പ്",
  "CMD_SCROLL_LINE_DOWN": "സ്ക്രോൾ ലൈൻ താഴേക്ക്",
  "CMD_TOGGLE_LINE_NUMBERS": "ലൈൻ നമ്പറുകൾ",
  "CMD_TOGGLE_ACTIVE_LINE": "സജീവ ലൈൻ ഹൈലൈറ്റ്",
  "CMD_TOGGLE_WORD_WRAP": "വാക്ക് റാപ്",
  "CMD_LIVE_HIGHLIGHT": "തത്സമയ പ്രിവ്യൂ ഹൈലൈറ്റ്",
  "CMD_VIEW_TOGGLE_INSPECTION": "സംരക്ഷിക്കുക ഫയലുകൾ ലിന്റ്",
  "CMD_WORKINGSET_SORT_BY_ADDED": "ചേർത്തത് അടുക്കുക",
  "CMD_WORKINGSET_SORT_BY_NAME": "പേര് പ്രകാരം അടുക്കുക",
  "CMD_WORKINGSET_SORT_BY_TYPE": "തരം പ്രകാരം അടുക്കുക",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "ഓട്ടോമാറ്റിക് ബ്ലാക്ക്",
  "CMD_THEMES": "തീമുകൾ...",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "യാന്ത്രികമായി തിരയൽ അടയ്ക്കുക",
  "NAVIGATE_MENU": "നാവിഗേറ്റുചെയ്യുക",
  "CMD_QUICK_OPEN": "ദ്രുത തുറക്കുക",
  "CMD_GOTO_LINE": "ലൈൻ പോകുക",
  "CMD_GOTO_DEFINITION": "ദ്രുത കണ്ടെത്തൽ നിർവചനം",
  "CMD_GOTO_DEFINITION_PROJECT": "പ്രോജക്റ്റിൽ ദ്രുത കണ്ടെത്തൽ നിർവചനം",
  "CMD_GOTO_FIRST_PROBLEM": "പോകുക ആദ്യ പ്രശ്നം",
  "CMD_TOGGLE_QUICK_EDIT": "ദ്രുത എഡിറ്റ്",
  "CMD_TOGGLE_QUICK_DOCS": "ദ്രുത ഡോക്സ്",
  "CMD_QUICK_EDIT_PREV_MATCH": "മുമ്പത്തെ മാച്ച്",
  "CMD_QUICK_EDIT_NEXT_MATCH": "അടുത്ത മാച്ച്",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "പുതിയ നിയമം",
  "CMD_NEXT_DOC": "അടുത്ത പ്രമാണം",
  "CMD_PREV_DOC": "മുമ്പത്തെ പ്രമാണം",
  "CMD_NAVIGATE_BACKWARD": "പിന്നിലേക്ക് നാവിഗേറ്റുചെയ്യുക",
  "CMD_NAVIGATE_FORWARD": "ഫോർവേഡ് നാവിഗേറ്റുചെയ്യുക",
  "CMD_NEXT_DOC_LIST_ORDER": "ലിസ്റ്റിലെ അടുത്ത പ്രമാണം",
  "CMD_PREV_DOC_LIST_ORDER": "മുമ്പത്തെ ലിസ്റ്റിലെ പ്രമാണം",
  "CMD_SHOW_IN_TREE": "ഫയൽ ട്രീ കാണിക്കുക",
  "CMD_SHOW_IN_EXPLORER": "എക്സ്പ്ലോററിൽ കാണിക്കുക",
  "CMD_SHOW_IN_FINDER": "ഫൈൻഡർ കാണിക്കുക",
  "CMD_SHOW_IN_OS": "OS- ൽ കാണിക്കുക",
  "CMD_SWITCH_PANE_FOCUS": "ഫോക്കസ് സ്വിച്ച്",
  "CMD_OPEN_VFS": "തുറക്കുക വെർച്വൽ ഫയൽ സിസ്റ്റം",
  "CMD_OPEN_VIRTUAL_SERVER": "ഓപ്പൺ വെർച്വൽ സെർവർ",
  "HELP_MENU": "സഹായിക്കുക",
  "CMD_CHECK_FOR_UPDATE": "അപ്ഡേറ്റുകൾക്കായി പരിശോധിക്കുക",
  "CMD_HOW_TO_USE_BRACKETS": "{APP_NAME} എങ്ങനെ ഉപയോഗിക്കാം",
  "CMD_SUPPORT": "{APP_NAME} പിന്തുണ",
  "CMD_SUGGEST": "ഒരു സവിശേഷത നിർദ്ദേശിക്കുക",
  "CMD_RELEASE_NOTES": "റിലീസ് കുറിപ്പുകൾ",
  "CMD_GET_INVOLVED": "പങ്കെടുക്കുക",
  "CMD_SHOW_EXTENSIONS_FOLDER": "വിപുലീകരണങ്ങൾ ഫോൾഡർ കാണിക്കുക",
  "CMD_HEALTH_DATA_STATISTICS": "ആരോഗ്യ റിപ്പോർട്ട്",
  "CMD_HOMEPAGE": "{APP_NAME} ഹോംപേജ്",
  "CMD_TWITTER": "{Twitter_NAME} ട്വിറ്ററിൽ",
  "CMD_ABOUT": "{APP_TITLE} കുറിച്ച്",
  "CMD_OPEN_PREFERENCES": "തുറക്കുക മുൻഗണനകൾ ഫയൽ",
  "CMD_OPEN_KEYMAP": "ഉപയോക്തൃ കീ മാപ്പ് തുറക്കുക",
  "EXPERIMENTAL_BUILD": "പരീക്ഷണാത്മക ബിൽഡ്",
  "RELEASE_BUILD": "പണിയുക",
  "DEVELOPMENT_BUILD": "വികസന ബിൽഡ്",
  "PRERELEASE_BUILD": "പ്രീറിലീസ് ബിൽഡ്",
  "RELOAD_FROM_DISK": "ഡിസ്കിൽ നിന്ന് വീണ്ടും ലോഡുചെയ്യുക",
  "KEEP_CHANGES_IN_EDITOR": "എഡിറ്റർ മാറ്റങ്ങൾ നിലനിർത്തുക",
  "CLOSE_DONT_SAVE": "അടയ്ക്കുക (സംരക്ഷിക്കരുത്)",
  "RELAUNCH_CHROME": "Chrome വീണ്ടും സമാരംഭിക്കുക",
  "ABOUT": "കുറിച്ച്",
  "CLOSE": "അടയ്ക്കുക",
  "ABOUT_TEXT_LINE1": "റിലീസ് {വെര്സിഒന്_മഗര്}. {VERSION_MINOR} {BUILD_TYPE} {പതിപ്പ്}",
  "ABOUT_TEXT_BUILD_TIMESTAMP": "ടൈംസ്റ്റാമ്പ് നിർമ്മിക്കുക: ",
  "ABOUT_TEXT_LINE3": "ഞങ്ങൾ ഉപയോഗിക്കുന്ന മൂന്നാം കക്ഷി ലൈബ്രറികൾ - <a href='https://github.com/phcode-dev/phoenix/tree/main/src/thirdparty/licences'> ലൈസൻസുകളും ആട്രിബ്യൂഷനുകളും</a> . ",
  "ABOUT_TEXT_LINE4": "ഡോക്യുമെന്റേഷനും ഉറവിടവും <a href='https://github.com/phcode-dev/phoenix/'>https://github.com/phcode-dev/phoenix/</a>",
  "ABOUT_TEXT_LINE5": "❤, JavaScript എന്നിവ ഉപയോഗിച്ച് നിർമ്മിച്ചത്:",
  "ABOUT_TEXT_LINE6": "ധാരാളം ആളുകൾ (പക്ഷേ ഇപ്പോൾ ആ ഡാറ്റ ലോഡ് ചെയ്യുന്നതിൽ ഞങ്ങൾക്ക് പ്രശ്നമുണ്ട്).",
  "ABOUT_TEXT_MDN_DOCS": "MDN ഡോക്സും MDN ഗ്രാഫിക്കൽ ലോഗോയും ക്രിയേറ്റീവ് കോമൺസ് ആട്രിബ്യൂഷൻ ലൈസൻസിന് കീഴിൽ ലൈസൻസ് ചെയ്തിട്ടുണ്ട്, <a href='{MDN_DOCS_LICENSE}'>CC-BY-SA 2.5 അൺപോർട്ടഡ്</a>.",
  "UPDATE_NOTIFICATION_TOOLTIP": "{APP_NAME} ന്റെ ഒരു പുതിയ ബിൽഡ് ലഭ്യമാണ്! വിശദാംശങ്ങൾക്ക് ഇവിടെ ക്ലിക്കുചെയ്യുക.",
  "UPDATE_AVAILABLE_TITLE": "ലഭ്യമായ അപ്ഡേറ്റ്",
  "UPDATE_MESSAGE": "ഹേയ്, {APP_NAME} ഒരു പുതിയ ബിൽഡ് ലഭ്യമാണ്. ഇവിടെ പുതിയ സവിശേഷതകൾ ചില:",
  "GET_IT_NOW": "ഇപ്പോൾ അത് നേടുക!",
  "PROJECT_SETTINGS_TITLE": "ഇതിനായി പ്രോജക്റ്റ് ക്രമീകരണങ്ങൾ: {0}",
  "PROJECT_SETTING_BASE_URL": "ലൈവ് പ്രിവ്യൂ ബേസ് URL",
  "PROJECT_SETTING_BASE_URL_HINT": "ഒരു പ്രാദേശിക സെർവർ ഉപയോഗിക്കുന്നതിന്, http://localhost:8000/ പോലുള്ള ഒരു URL നൽകുക",
  "BASEURL_ERROR_INVALID_PROTOCOL": "തൽസമയ പ്രിവ്യൂ {0} പ്രോട്ടോക്കോൾ പിന്തുണയ്ക്കുന്നില്ല - ദയവായി http: അല്ലെങ്കിൽ https: ഉപയോഗിക്കുക.",
  "BASEURL_ERROR_SEARCH_DISALLOWED": "അടിസ്ഥാന URL- ൽ “{0}” പോലുള്ള തിരയൽ പാരാമീറ്ററുകൾ ഉൾക്കൊള്ളാൻ കഴിയില്ല.",
  "BASEURL_ERROR_HASH_DISALLOWED": "അടിസ്ഥാന URL- ൽ “{0}” പോലുള്ള ഹാഷുകൾ അടങ്ങിയിരിക്കാൻ കഴിയില്ല.",
  "BASEURL_ERROR_INVALID_CHAR": "'{ 0} 'പോലുള്ള പ്രത്യേക പ്രതീകങ്ങൾ %-എൻകോഡ് ചെയ്തിരിക്കണം.",
  "BASEURL_ERROR_UNKNOWN_ERROR": "അടിസ്ഥാന URL പാഴ്സിംഗ് അജ്ഞാത പിശക്",
  "EMPTY_VIEW_HEADER": "<em>ഈപാളിക്ക് ഫോക്കസ് ഉള്ളപ്പോൾ ഒരു ഫയൽ തുറക്കുക</em>",
  "FLIPVIEW_BTN_TOOLTIP": "ഈ കാഴ്ച {0} പാനിലേക്ക് ഫ്ലിപ്പുചെയ്യുക",
  "CURRENT_THEME": "നിലവിലെ തീം",
  "USE_THEME_SCROLLBARS": "തീം സ്ക്രോൾബാറുകൾ ഉപയോഗിക്കുക",
  "FONT_SIZE": "ഫോണ്ട് വലുപ്പം",
  "FONT_FAMILY": "ഫോണ്ട് കുടുംബ",
  "THEMES_SETTINGS": "തീമുകൾ ക്രമീകരണങ്ങൾ",
  "BUTTON_NEW_RULE": "പുതിയ നിയമം",
  "INSTALL": "ഇൻസ്റ്റാൾ ചെയ്യുക",
  "UPDATE": "അപ്ഡേറ്റ്",
  "REMOVE": "നീക്കംചെയ്യുക",
  "DISABLE": "അപ്രാപ്തമാക്കുക",
  "ENABLE": "പ്രാപ്തമാക്കുക",
  "OVERWRITE": "തിരുത്തിയെഴുതുക",
  "CANT_REMOVE_DEV": "“dev” ഫോൾഡറിലെ വിപുലീകരണങ്ങൾ സ്വമേധയാ ഇല്ലാതാക്കണം.",
  "CANT_UPDATE": "അപ്ഡേറ്റ് {APP_NAME} ന്റെ ഈ പതിപ്പുമായി പൊരുത്തപ്പെടുന്നില്ല.",
  "CANT_UPDATE_DEV": "“dev” ഫോൾഡറിലെ വിപുലീകരണങ്ങൾ യാന്ത്രികമായി അപ്ഡേറ്റ് ചെയ്യാൻ കഴിയില്ല.",
  "INSTALL_EXTENSION_TITLE": "വിപുലീകരണം ഇൻസ്റ്റാൾ ചെയ്യുക",
  "UPDATE_EXTENSION_TITLE": "അപ്ഡേറ്റ് വിപുലീകരണം",
  "INSTALL_EXTENSION_LABEL": "വിപുലീകരണ URL",
  "INSTALL_EXTENSION_HINT": "വിപുലീകരണത്തിന്റെ സിപ്പ് ഫയലിന്റെ URL അല്ലെങ്കിൽ GitHub repo",
  "INSTALLING_FROM": "{0} ൽ നിന്ന് വിപുലീകരണം ഇൻസ്റ്റാൾ ചെയ്യുന്നു...",
  "INSTALL_SUCCEEDED": "ഇൻസ്റ്റാളേഷൻ വിജയകരം!",
  "INSTALL_FAILED": "ഇൻസ്റ്റാളേഷൻ പരാജയപ്പെട്ടു.",
  "CANCELING_INSTALL": "റദ്ദാക്കുന്നു...",
  "CANCELING_HUNG": "ഇൻസ്റ്റാൾ റദ്ദാക്കുന്നത് വളരെക്കാലം എടുക്കുന്നു. ഒരു ആന്തരിക പിശക് സംഭവിച്ചിരിക്കാം.",
  "INSTALL_CANCELED": "ഇൻസ്റ്റലേഷൻ റദ്ദാക്കി.",
  "VIEW_COMPLETE_DESCRIPTION": "പൂർണ്ണമായ വിവരണം കാണുക",
  "VIEW_TRUNCATED_DESCRIPTION": "വെട്ടിച്ചുരുക്കിയ വിവരണം കാണുക",
  "SORT_EXTENSION_METHOD": "DownloadCount അല്ലെങ്കിൽ പബ്ലിഷ്ഡേറ്റ് ഉപയോഗിച്ച് വിപുലീകരണങ്ങൾ അടുക്കുക",
  "INVALID_ZIP_FILE": "ഡൌൺലോഡ് ചെയ്ത ഉള്ളടക്കം സാധുവായ ഒരു zip ഫയലല്ല.",
  "MISSING_PACKAGE_JSON": "പാക്കേജ് പാക്കേജ് ഇല്ല.json ഫയൽ.",
  "INVALID_PACKAGE_JSON": "പാക്കേജ്.json ഫയൽ സാധുവല്ല (പിശക്: {0} ആയിരുന്നു).",
  "MISSING_PACKAGE_NAME": "പാക്കേജ്. json ഫയൽ ഒരു പാക്കേജിന്റെ പേര് വ്യക്തമാക്കുന്നില്ല.",
  "BAD_PACKAGE_NAME": "{0} എന്നത് അസാധുവായ ഒരു പാക്കേജ് നാമമാണ്.",
  "MISSING_PACKAGE_VERSION": "പാക്കേജ്. json ഫയൽ ഒരു പാക്കേജ് പതിപ്പ് വ്യക്തമാക്കുന്നില്ല.",
  "INVALID_VERSION_NUMBER": "പാക്കേജ് പതിപ്പ് നമ്പർ ({0}) അസാധുവാണ്.",
  "INVALID_BRACKETS_VERSION": "{APP_NAME} അനുയോജ്യത സ്ട്രിംഗ് ({0}) അസാധുവാണ്.",
  "DISALLOWED_WORDS": "{0} ഫീൽഡിൽ വാക്കുകൾ ({1}) അനുവദനീയമല്ല.",
  "NPM_INSTALL_FAILED": "npm ഇൻസ്റ്റാൾ കമാൻഡ് പരാജയപ്പെട്ടു: {0}",
  "API_NOT_COMPATIBLE": "വിപുലീകരണം {APP_NAME} ന്റെ ഈ പതിപ്പുമായി പൊരുത്തപ്പെടുന്നില്ല. ഇത് നിങ്ങളുടെ അപ്രാപ്തമാക്കിയ വിപുലീകരണങ്ങളുടെ ഫോൾഡറിൽ ഇൻസ്റ്റാൾ ചെയ്തു.",
  "MISSING_MAIN": "പാക്കേജിന് main.js ഫയൽ ഇല്ല.",
  "EXTENSION_ALREADY_INSTALLED": "ഈ പാക്കേജ് ഇൻസ്റ്റാൾ ചെയ്യുന്നത് മുമ്പ് ഇൻസ്റ്റാൾ ചെയ്ത വിപുലീകരണത്തെ തിരുത്തിയെഴുതും. പഴയ വിപുലീകരണം തിരുത്തിയെഴുതുക?",
  "EXTENSION_SAME_VERSION": "നിലവിൽ ഇൻസ്റ്റാൾ ചെയ്ത അതേ പതിപ്പാണ് ഈ പാക്കേജ്. നിലവിലുള്ള ഇൻസ്റ്റാളേഷൻ തിരുത്തിയെഴുതുക?",
  "EXTENSION_OLDER_VERSION": "ഈ പാക്കേജ് പതിപ്പ് {0} ആണ്, ഇത് നിലവിൽ ഇൻസ്റ്റാൾ ചെയ്തതിനേക്കാൾ പഴയതാണ് ({1}). നിലവിലുള്ള ഇൻസ്റ്റാളേഷൻ തിരുത്തിയെഴുതുക?",
  "DOWNLOAD_ID_IN_USE": "ആന്തരിക പിശക്: ഇതിനകം ഉപയോഗത്തിലുള്ള ഐഡി ഡ download ൺലോഡ് ചെയ്യുക.",
  "NO_SERVER_RESPONSE": "സെർവറിലേക്ക് കണക്റ്റുചെയ്യാൻ കഴിയില്ല.",
  "BAD_HTTP_STATUS": "ഫയൽ സെർവറിൽ കണ്ടെത്തിയില്ല (HTTP {0}).",
  "CANNOT_WRITE_TEMP": "ഫയൽ താൽക്കാലിക ഡൗൺലോഡ് സംരക്ഷിക്കാൻ കഴിയുന്നില്ല.",
  "ERROR_LOADING": "ആരംഭിക്കുമ്പോൾ വിപുലീകരണം ഒരു പിശക് നേരിട്ടു.",
  "MALFORMED_URL": "URL അസാധുവാണ്. നിങ്ങൾ ഇത് ശരിയായി നൽകിയിട്ടുണ്ടോ എന്ന് പരിശോധിക്കുക.",
  "UNSUPPORTED_PROTOCOL": "URL ഒരു http അല്ലെങ്കിൽ https URL ആയിരിക്കണം.",
  "UNKNOWN_ERROR": "അജ്ഞാത ആന്തരിക പിശക്.",
  "EXTENSION_MANAGER_TITLE": "എക്സ്റ്റൻഷൻ മാനേജർ",
  "EXTENSION_MANAGER_ERROR_LOAD": "വിപുലീകരണ രജിസ്ട്രി ആക്സസ് ചെയ്യാൻ കഴിയുന്നില്ല. പിന്നീട് വീണ്ടും ശ്രമിക്കുക.",
  "INSTALL_EXTENSION_DRAG": "ഇവിടെ. zip വലിച്ചിടുക അല്ലെങ്കിൽ",
  "INSTALL_EXTENSION_DROP": "ഇൻസ്റ്റാൾ ചെയ്യാൻ.zip ഡ്രോപ്പ് ചെയ്യുക",
  "INSTALL_EXTENSION_DROP_ERROR": "ഇനിപ്പറയുന്ന പിശകുകൾ കാരണം ഇൻസ്റ്റാൾ ചെയ്യുക/അപ്ഡേറ്റ് ചെയ്യുക:",
  "INSTALL_FROM_URL": "URL- ൽ നിന്ന് ഇൻസ്റ്റാൾ ചെയ്യുക...",
  "INSTALL_EXTENSION_VALIDATING": "സാധൂകരിക്കുന്നു...",
  "EXTENSION_AUTHOR": "രചയിതാവ്",
  "EXTENSION_DATE": "തീയതി",
  "EXTENSION_INCOMPATIBLE_NEWER": "ഈ വിപുലീകരണത്തിന് {APP_NAME} ന്റെ ഒരു പുതിയ പതിപ്പ് ആവശ്യമാണ്.",
  "EXTENSION_INCOMPATIBLE_OLDER": "ഈ വിപുലീകരണം നിലവിൽ {APP_NAME} ന്റെ പഴയ പതിപ്പുകളിൽ മാത്രമേ പ്രവർത്തിക്കൂ.",
  "EXTENSION_LATEST_INCOMPATIBLE_NEWER": "ഈ വിപുലീകരണത്തിന്റെ {0} പതിപ്പ് {APP_NAME} ന്റെ പുതിയ പതിപ്പ് ആവശ്യമാണ്. എന്നാൽ നിങ്ങൾക്ക് മുമ്പത്തെ പതിപ്പ് {1} ഇൻസ്റ്റാൾ ചെയ്യാൻ കഴിയും.",
  "EXTENSION_LATEST_INCOMPATIBLE_OLDER": "ഈ വിപുലീകരണത്തിന്റെ പതിപ്പ് {0} {APP_NAME} ന്റെ പഴയ പതിപ്പുകളിൽ മാത്രമേ പ്രവർത്തിക്കൂ. എന്നാൽ നിങ്ങൾക്ക് മുമ്പത്തെ പതിപ്പ് {1} ഇൻസ്റ്റാൾ ചെയ്യാൻ കഴിയും.",
  "EXTENSION_NO_DESCRIPTION": "വിവരണമൊന്നുമില്ല",
  "EXTENSION_MORE_INFO": "കൂടുതൽ വിവരങ്ങൾ...",
  "EXTENSION_ERROR": "വിപുലീകരണ പിശക്",
  "EXTENSION_KEYWORDS": "കീവേഡുകൾ",
  "EXTENSION_TRANSLATED_USER_LANG": "നിങ്ങളുടേത് ഉൾപ്പെടെ {0} ഭാഷകളിലേക്ക് വിവർത്തനം ചെയ്തു",
  "EXTENSION_TRANSLATED_GENERAL": "{0} ഭാഷകളിലേക്ക് വിവർത്തനം ചെയ്തു",
  "EXTENSION_TRANSLATED_LANGS": "ഈ വിപുലീകരണം ഈ ഭാഷകളിലേക്ക് വിവർത്തനം ചെയ്തു: {0}",
  "EXTENSION_INSTALLED": "ഇൻസ്റ്റാൾ ചെയ്തു",
  "EXTENSION_UPDATE_INSTALLED": "ഈ വിപുലീകരണ അപ്ഡേറ്റ് ഡ download ൺലോഡ് ചെയ്തു, {APP_NAME} റീലോഡുകൾക്ക് ശേഷം ഇൻസ്റ്റാൾ ചെയ്യപ്പെടും.",
  "EXTENSION_SEARCH_PLACEHOLDER": "തിരയുക",
  "EXTENSION_MORE_INFO_LINK": "കൂടുതൽ",
  "BROWSE_EXTENSIONS": "വിപുലീകരണങ്ങൾ ബ്രൗസുചെയ്യുക",
  "EXTENSION_MANAGER_REMOVE": "വിപുലീകരണം നീക്കംചെയ്യുക",
  "EXTENSION_MANAGER_REMOVE_ERROR": "ഒന്നോ അതിലധികമോ വിപുലീകരണങ്ങൾ നീക്കംചെയ്യാൻ കഴിയില്ല: {0}. {APP_NAME} ഇപ്പോഴും വീണ്ടും ലോഡുചെയ്യും.",
  "EXTENSION_MANAGER_UPDATE": "അപ്ഡേറ്റ് വിപുലീകരണം",
  "EXTENSION_MANAGER_UPDATE_ERROR": "ഒന്നോ അതിലധികമോ വിപുലീകരണങ്ങൾ അപ്ഡേറ്റ് ചെയ്യാൻ കഴിയില്ല: {0}. {APP_NAME} ഇപ്പോഴും വീണ്ടും ലോഡുചെയ്യും.",
  "EXTENSION_MANAGER_DISABLE": "വിപുലീകരണം അപ്രാപ്തമാക്കുക",
  "EXTENSION_MANAGER_DISABLE_ERROR": "ഒന്നോ അതിലധികമോ വിപുലീകരണങ്ങൾ അപ്രാപ്തമാക്കാൻ കഴിയില്ല: {0}. {APP_NAME} ഇപ്പോഴും വീണ്ടും ലോഡുചെയ്യും.",
  "MARKED_FOR_REMOVAL": "നീക്കംചെയ്യുന്നതിന് അടയാളപ്പെടുത്തി",
  "UNDO_REMOVE": "ഉന്മുനതെ",
  "MARKED_FOR_UPDATE": "അപ്ഡേറ്റിനായി അടയാളപ്പെടുത്തി",
  "UNDO_UPDATE": "ഉന്മുനതെ",
  "MARKED_FOR_DISABLING": "പ്രവർത്തനരഹിതമാക്കുന്നതിനായി അടയാളപ്പെടുത്തി",
  "UNDO_DISABLE": "ഉന്മുനതെ",
  "CHANGE_AND_RELOAD_TITLE": "വിപുലീകരണങ്ങൾ മാറ്റുക",
  "CHANGE_AND_RELOAD_MESSAGE": "അടയാളപ്പെടുത്തിയ വിപുലീകരണങ്ങൾ അപ്ഡേറ്റ് ചെയ്യാനോ നീക്കംചെയ്യാനോ അപ്രാപ്തമാക്കാനോ, {APP_NAME} വീണ്ടും ലോഡ് ചെയ്യേണ്ടതുണ്ട്. സംരക്ഷിക്കാത്ത മാറ്റങ്ങൾ സംരക്ഷിക്കാൻ നിങ്ങളോട് ആവശ്യപ്പെടും.",
  "REMOVE_AND_RELOAD": "വിപുലീകരണങ്ങൾ നീക്കംചെയ്ത് വീണ്ടും ലോഡുചെയ്യുക",
  "CHANGE_AND_RELOAD": "വിപുലീകരണങ്ങൾ മാറ്റി വീണ്ടും ലോഡുചെയ്യുക",
  "UPDATE_AND_RELOAD": "വിപുലീകരണങ്ങൾ അപ്ഡേറ്റ് ചെയ്ത് വീണ്ടും ലോഡുചെയ്യുക",
  "DISABLE_AND_RELOAD": "വിപുലീകരണങ്ങൾ അപ്രാപ്തമാക്കി വീണ്ടും ലോഡുചെയ്യുക",
  "PROCESSING_EXTENSIONS": "വിപുലീകരണ മാറ്റങ്ങൾ പ്രോസസ്സ് ചെയ്യുന്നു...",
  "EXTENSION_NOT_INSTALLED": "ഇത് ഇൻസ്റ്റാൾ ചെയ്യാത്തതിനാൽ വിപുലീകരണം {0} നീക്കംചെയ്യാൻ കഴിഞ്ഞില്ല.",
  "NO_EXTENSIONS": "വിപുലീകരണങ്ങളൊന്നും ഇതുവരെ ഇൻസ്റ്റാളുചെയ്തിട്ടില്ല. <br>ആരംഭിക്കുന്നതിന്മുകളിലുള്ള ലഭ്യമായ ടാബിൽ ക്ലിക്കുചെയ്യുക.",
  "NO_EXTENSION_MATCHES": "വിപുലീകരണങ്ങളൊന്നും നിങ്ങളുടെ തിരയലിനോട് പൊരുത്തപ്പെടുന്നില്ല.",
  "REGISTRY_SANITY_CHECK_WARNING": "ശ്രദ്ധിക്കുക: ഈ വിപുലീകരണങ്ങൾ {APP_NAME} എന്നതിനേക്കാൾ വ്യത്യസ്ത രചയിതാക്കളിൽ നിന്ന് വന്നേക്കാം. വിപുലീകരണങ്ങൾ അവലോകനം ചെയ്യപ്പെടുന്നില്ല, കൂടാതെ പൂർണ്ണ പ്രാദേശിക അധികാരങ്ങളും ഉണ്ട്. അജ്ഞാതമായ ഉറവിടത്തിൽ നിന്ന് വിപുലീകരണങ്ങൾ ഇൻസ്റ്റാൾ ചെയ്യുമ്പോൾ ജാഗ്രത പാലിക്കുക.",
  "EXTENSIONS_INSTALLED_TITLE": "ഇൻസ്റ്റാൾ ചെയ്തു",
  "EXTENSIONS_DEFAULT_TITLE": "സ്ഥിരസ്ഥിതി",
  "EXTENSIONS_AVAILABLE_TITLE": "ലഭ്യമാണ്",
  "EXTENSIONS_THEMES_TITLE": "തീമുകൾ",
  "EXTENSIONS_UPDATES_TITLE": "അപ്ഡേറ്റുകൾ",
  "EXTENSIONS_LAST_UPDATED": "അവസാനം അപ്ഡേറ്റുചെയ്തത്",
  "EXTENSIONS_DOWNLOADS": "ഡൗൺലോഡുകൾ",
  "INLINE_EDITOR_NO_MATCHES": "ഇല്ല മത്സരങ്ങൾ ലഭ്യമാണ്.",
  "INLINE_EDITOR_HIDDEN_MATCHES": "എല്ലാ മത്സരങ്ങളും തകർന്നു ചെയ്യുന്നു. മത്സരങ്ങൾ കാണുന്നതിന് വലതുവശത്ത് ലിസ്റ്റുചെയ്തിരിക്കുന്ന ഫയലുകൾ വിപുലീകരിക്കുക.",
  "CSS_QUICK_EDIT_NO_MATCHES": "നിങ്ങളുടെ തിരഞ്ഞെടുപ്പുമായി പൊരുത്തപ്പെടുന്ന നിലവിലുള്ള CSS നിയമങ്ങളൊന്നുമില്ല. <br> ഒരെണ്ണംസൃഷ്ടിക്കാൻ “പുതിയ നിയമം” ക്ലിക്കുചെയ്യുക.",
  "CSS_QUICK_EDIT_NO_STYLESHEETS": "നിങ്ങളുടെ പ്രോജക്റ്റിൽ സ്റ്റൈൽഷീറ്റുകൾ ഒന്നുമില്ല. എസ് .<br>എസ് നിയമങ്ങൾ ചേർക്കാൻ ഒന്ന് സൃഷ്ടിക്കുക.",
  "IMAGE_VIEWER_LARGEST_ICON": "ഏറ്റവും വലിയ",
  "UNIT_PIXELS": "പിക്സലുകൾ",
  "DEBUG_MENU": "ഡീബഗ്",
  "ERRORS": "പിശകുകൾ",
  "CMD_SHOW_DEV_TOOLS": "ഡെവലപ്പർ ഉപകരണങ്ങൾ കാണിക്കുക",
  "CMD_REFRESH_WINDOW": "വിപുലീകരണങ്ങൾ ഉപയോഗിച്ച് വീണ്ടും ലോഡുചെയ്യുക",
  "CMD_RELOAD_WITHOUT_USER_EXTS": "വിപുലീകരണങ്ങൾ ഇല്ലാതെ വീണ്ടും ലോഡുചെയ്യുക",
  "CMD_NEW_BRACKETS_WINDOW": "പുതിയ {APP_NAME} വിൻഡോ",
  "CMD_LAUNCH_SCRIPT_MAC": "കമാൻഡ് ലൈൻ കുറുക്കുവഴി ഇൻസ്റ്റാൾ ചെയ്യുക",
  "CMD_SWITCH_LANGUAGE": "ഭാഷ മാറുക",
  "CMD_RUN_UNIT_TESTS": "ടെസ്റ്റുകൾ പ്രവർത്തിപ്പിക്കുക",
  "CMD_SHOW_PERF_DATA": "പ്രകടന ഡാറ്റ കാണിക്കുക",
  "CMD_ENABLE_LOGGING": "വിശദമായ ലോഗുകൾ പ്രവർത്തനക്ഷമമാക്കുക",
  "CMD_OPEN_BRACKETS_SOURCE": "തുറക്കുക {APP_NAME} ഉറവിടം",
  "CREATING_LAUNCH_SCRIPT_TITLE": "{APP_NAME} കമാൻഡ് ലൈൻ കുറുക്കുവഴി",
  "ERROR_CREATING_LAUNCH_SCRIPT": "കമാൻഡ് ലൈൻ കുറുക്കുവഴി ഇൻസ്റ്റോൾ ചെയ്യുമ്പോൾ ഒരു പിശക് സംഭവിച്ചു. ദയവായി <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting'>ഈ ട്രബിൾഷൂട്ടിംഗ് നിർദ്ദേശങ്ങൾ</a>പരീക്ഷിക്കുക. <br/><br/>കാരണം: {0}",
  "ERROR_CLTOOLS_RMFAILED": "<code>നിലവിലുള്ള/usr/പ്രാദേശിക/bin/ബ്രാക്കറ്റുകൾ</code> സ്യ്മ്ലിന്ക് നീക്കം ചെയ്യാൻ കഴിയുന്നില്ല.",
  "ERROR_CLTOOLS_MKDIRFAILED": "<code>/usr/local/bin</code> ഡയറക്ടറി സൃഷ്ടിക്കാൻ കഴിയുന്നില്ല.",
  "ERROR_CLTOOLS_LNFAILED": "<code>/usr/പ്രാദേശിക/bin/ബ്രാക്കറ്റുകൾ</code> സ്യ്മ്ലിന്ക് സൃഷ്ടിക്കാൻ കഴിയുന്നില്ല.",
  "ERROR_CLTOOLS_SERVFAILED": "ആന്തരിക പിശക്.",
  "ERROR_CLTOOLS_NOTSUPPORTED": "കമാൻഡ് ലൈൻ കുറുക്കുവഴി ഈ OS- ൽ പിന്തുണയ്ക്കുന്നില്ല.",
  "LAUNCH_SCRIPT_CREATE_SUCCESS": "വിജയം! ഇപ്പോൾ നിങ്ങൾക്ക് കമാൻഡ് ലൈനിൽ നിന്ന് {APP_NAME} എളുപ്പത്തിൽ സമാരംഭിക്കാം: ഒരു ഫയൽ തുറക്കാൻ <code>ബ്രാക്കറ്റുകൾ myFile.txt</code> അല്ലെങ്കിൽ <code>ബ്രാക്കറ്റുകൾ പ്രോജക്റ്റുകൾ സ്വിച്ചുചെയ്യുന്നതിന് MyFoldor</code> . <br/><br/>കമാൻഡ്ലൈനിൽ നിന്ന് {APP_NAME} ഉപയോഗിക്കുന്നതിനെക്കുറിച്ച്<a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments'>കൂടുതലറിയുക</a> .",
  "LANGUAGE_TITLE": "ഭാഷ മാറുക",
  "LANGUAGE_MESSAGE": "ഭാഷ:",
  "LANGUAGE_SUBMIT": "വീണ്ടും ലോഡ് {APP_NAME}",
  "LANGUAGE_CANCEL": "റദ്ദാക്കുക",
  "LANGUAGE_SYSTEM_DEFAULT": "സ്ഥിരസ്ഥിതി സിസ്റ്റം",
  "HEALTH_DATA_NOTIFICATION": "ആരോഗ്യ റിപ്പോർട്ട് മുൻഗണനകൾ",
  "HEALTH_FIRST_POPUP_TITLE": "{APP_NAME} ആരോഗ്യ റിപ്പോർട്ട്",
  "HEALTH_DATA_DO_TRACK": "ഞാൻ {APP_NAME} എങ്ങനെ ഉപയോഗിക്കുന്നു എന്നതിനെക്കുറിച്ചുള്ള കപടനാമയ വിവരങ്ങൾ പങ്കിടുക",
  "HEALTH_DATA_NOTIFICATION_MESSAGE": "{APP_NAME} മെച്ചപ്പെടുത്തുന്നതിന്, നിങ്ങൾ { <strong>APP_NAME} എങ്ങനെ ഉപയോഗിക്കുന്നു എന്നതിനെക്കുറിച്ച് ഞങ്ങൾ ഇടയ്ക്കിടെ പരിമിതമായ, കപടശാസ്ത്ര സ്ഥിതിവിവരക്കണക്കുകൾ core.ai ലേക്ക് അയയ്ക്കുന്നു</strong> . നിങ്ങളുടെ സ്വകാര്യത കാത്തുസൂക്ഷിക്കുമ്പോൾ സവിശേഷതകൾക്ക് മുൻഗണന നൽകാനും ബഗുകൾ കണ്ടെത്താനും ഉപയോഗക്ഷമത പ്രശ്നങ്ങൾ കണ്ടെത്താനും ഈ വിവരങ്ങൾ സഹായിക്കുന്നു. <br><br>നിങ്ങൾക്ക്നിങ്ങളുടെ ഡാറ്റ കാണാം അല്ലെങ്കിൽ <strong>സഹായം> ആരോഗ്യ റിപ്പോർട്ട്</strong>തിരഞ്ഞെടുത്ത് ഡാറ്റ പങ്കിടരുതെന്ന് തിരഞ്ഞെടുക്കാം. <br><br>",
  "HEALTH_DATA_PREVIEW": "{APP_NAME} ആരോഗ്യ റിപ്പോർട്ട്",
  "HEALTH_DATA_PREVIEW_INTRO": "<p>{APP_NAME} മെച്ചപ്പെടുത്തുന്നതിന്, നിങ്ങൾ { <strong>APP_NAME} എങ്ങനെ ഉപയോഗിക്കുന്നു എന്നതിനെക്കുറിച്ച് ഞങ്ങൾ ഇടയ്ക്കിടെ പരിമിതമായ, കപടശാസ്ത്ര സ്ഥിതിവിവരക്കണക്കുകൾ core.ai ലേക്ക് അയയ്ക്കുന്നു</strong> . ഈ വിവരങ്ങൾ സവിശേഷതകൾ മുൻഗണന സഹായിക്കുന്നു, ബഗുകൾ കണ്ടെത്താൻ, സ്പോട്ട് ഉപയോഗക്ഷമത പ്രശ്നങ്ങൾ. </p><p>നിങ്ങളുടെഅടുത്ത ആരോഗ്യ റിപ്പോർട്ടിൽ ഇത് <em>പ്രാപ്തമാക്കിയിട്ടുണ്ടെങ്കിൽ</em> അയയ്ക്കുന്ന ഡാറ്റയുടെ പ്രിവ്യൂ ചുവടെയുണ്ട്. </p>",
  "INLINE_TIMING_EDITOR_TIME": "സമയം",
  "INLINE_TIMING_EDITOR_PROGRESSION": "പുരോഗതിയെ",
  "BEZIER_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd><kbd>←</kbd><kbd>→</kbd>തിരഞ്ഞെടുത്ത പോയിന്റ് നീക്കുക<br><kbd class='text'>ഷിഫ്റ്റ്</kbd>പത്ത് യൂണിറ്റുകൾ ഉപയോഗിച്ച് നീക്കുക<br><kbd class='text'>ടാബ്</kbd>സ്വിച്ച് പോയിന്റുകൾ",
  "STEPS_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd>ഘട്ടങ്ങൾ കൂട്ടുക അല്ലെങ്കിൽ കുറയ്ക്കുക<br><kbd>←</kbd><kbd>→</kbd>'ആരംഭിക്കുക' അല്ലെങ്കിൽ 'അവസാനിപ്പിക്കുക'",
  "INLINE_TIMING_EDITOR_INVALID": "പഴയ മൂല്യം <code>{0}</code> സാധുവല്ല, അതിനാൽ പ്രദർശിപ്പിച്ച പ്രവർത്തനം <code>{1}</code> എന്നാക്കി മാറ്റി. ആദ്യ എഡിറ്റ് ഉപയോഗിച്ച് പ്രമാണം അപ്ഡേറ്റ് ചെയ്യും.",
  "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP": "ഇപ്പോഴത്തെ കളർ",
  "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP": "യഥാർത്ഥ നിറം",
  "COLOR_EDITOR_RGBA_BUTTON_TIP": "ര്ഗ്ബ ഫോർമാറ്റ്",
  "COLOR_EDITOR_HEX_BUTTON_TIP": "Hex ഫോർമാറ്റ്",
  "COLOR_EDITOR_HSLA_BUTTON_TIP": "HSLA ഫോർമാറ്റ്",
  "COLOR_EDITOR_0X_BUTTON_TIP": "Hex (0x) ഫോർമാറ്റ്",
  "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR": "{0} (ഉപയോഗിച്ച {1} സമയം)",
  "COLOR_EDITOR_USED_COLOR_TIP_PLURAL": "{0} (ഉപയോഗിച്ച {1} തവണ)",
  "CMD_JUMPTO_DEFINITION": "നിർവചനം പോവുക",
  "CMD_SHOW_PARAMETER_HINT": "പാരാമീറ്റർ സൂചന കാണിക്കുക",
  "NO_ARGUMENTS": "<no parameters>",
  "DETECTED_EXCLUSION_TITLE": "JavaScript ഫയൽ അനുമാനത്തിന്റെ പ്രശ്നം",
  "DETECTED_EXCLUSION_INFO": "{APP_NAME} <span class='dialog-filename'>{0}</span>പ്രോസസ്സിംഗ് പ്രശ്നത്തിലേക്ക് ഓടി. <br><br>കോഡ്സൂചനകൾ, നിർവചനത്തിലേക്ക് പോകുക അല്ലെങ്കിൽ ദ്രുത എഡിറ്റ് എന്നിവയ്ക്കായി ഈ ഫയൽ മേലിൽ പ്രോസസ്സ് ചെയ്യില്ല. ഈ ഫയൽ വീണ്ടും പ്രവർത്തനക്ഷമമാക്കാൻ, നിങ്ങളുടെ <code>പ്രോജക്റ്റിൽ .brackets.json</code> തുറന്ന് <code>jscodeHints.detectedexclusions</code> എഡിറ്റുചെയ്യുക. <br><br>ഇത്ഒരു {APP_NAME} ബഗ് ആണ്. നിങ്ങൾക്ക് ഈ ഫയലിന്റെ ഒരു പകർപ്പ് നൽകാൻ കഴിയുമെങ്കിൽ, ഇവിടെ പേരുള്ള <a href='https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue'>ഫയലിലേക്കുള്ള ഒരു ലിങ്ക് ഉപയോഗിച്ച് ഒരു ബഗ്</a> ഫയൽ ചെയ്യുക.",
  "CMD_REFACTOR": "റീഫാക്ടർ",
  "CMD_EXTRACTTO_VARIABLE": "വേരിയബിൾ എക്സ്ട്രാക്റ്റ്",
  "CMD_EXTRACTTO_FUNCTION": "പ്രവർത്തനം എക്സ്ട്രാക്റ്റ്",
  "ERROR_TERN_FAILED": "ടെറനിൽ നിന്ന് ഡാറ്റ നേടാൻ കഴിയുന്നില്ല",
  "ERROR_EXTRACTTO_VARIABLE_NOT_VALID": "തിരഞ്ഞെടുക്കൽ ഒരു പദപ്രയോഗമല്ല",
  "ERROR_EXTRACTTO_FUNCTION_NOT_VALID": "തിരഞ്ഞെടുത്ത ബ്ലോക്ക് പ്രസ്താവനകളെയോ ഒരു പദപ്രയോഗത്തെയോ പ്രതിനിധീകരിക്കണം",
  "ERROR_EXTRACTTO_VARIABLE_MULTICURSORS": "വേരിയബിളിലേക്ക് എക്സ്ട്രാക്റ്റുചെയ്യുക മൾട്ടികോർസറുകളിൽ പ്രവർത്തിക്കില്ല",
  "ERROR_EXTRACTTO_FUNCTION_MULTICURSORS": "ഫംഗ്ഷനിലേക്ക് എക്സ്ട്രാക്റ്റുചെയ്യുക മൾട്ടി സർസറുകളിൽ പ്രവർത്തിക്കുന്നില്ല",
  "EXTRACTTO_FUNCTION_SELECT_SCOPE": "ലക്ഷ്യസ്ഥാന സാധ്യത തിരഞ്ഞെടുക്കുക",
  "EXTRACTTO_VARIABLE_SELECT_EXPRESSION": "ഒരു പദപ്രയോഗം തിരഞ്ഞെടുക്കുക",
  "CMD_REFACTORING_RENAME": "പുനർനാമകരണം",
  "CMD_REFACTORING_TRY_CATCH": "ശ്രമിക്കുക ക്യാച്ച് പൊതിയുക",
  "CMD_REFACTORING_CONDITION": "അവസ്ഥയിൽ പൊതിയുക",
  "CMD_REFACTORING_GETTERS_SETTERS": "ഗെറ്ററുകൾ/സെറ്ററുകൾ സൃഷ്ടിക്കുക",
  "CMD_REFACTORING_ARROW_FUNCTION": "ആരോ ഫംഗ്ഷനിലേക്ക് പരിവർത്തനം ചെയ്യുക",
  "DESCRIPTION_CODE_REFACTORING": "JavaScript കോഡ് Refactoring പ്രാപ്തമാക്കുക/അപ്രാപ്തമാക്കുക",
  "ERROR_TRY_CATCH": "ഒരു ശ്രമിക്കുക-ക്യാച്ച് തടയൽ പൊതിയാൻ സാധുവായ കോഡ് തിരഞ്ഞെടുക്കുക",
  "ERROR_WRAP_IN_CONDITION": "ഒരു കണ്ടീഷൻ ബ്ലോക്കിൽ പൊതിയാൻ സാധുവായ കോഡ് തിരഞ്ഞെടുക്കുക",
  "ERROR_ARROW_FUNCTION": "ഒരു ഫംഗ്ഷൻ എക്സ്പ്രഷനുള്ളിൽ കഴ്സർ സ്ഥാപിക്കുക",
  "ERROR_GETTERS_SETTERS": "ഒരു ഒബ്ജക്റ്റ് എക്സ്പ്രഷനിലെ അംഗത്തിൽ കഴ്സർ സ്ഥാപിക്കുക",
  "ERROR_RENAME_MULTICURSOR": "മൾട്ടി-കഴ്സറുകൾ ഉപയോഗിക്കുമ്പോൾ പുനർനാമകരണം ചെയ്യാൻ കഴിയില്ല",
  "ERROR_RENAME_QUICKEDIT": "ഈ ഫംഗ്ഷന് പുറത്ത് മറ്റെവിടെയെങ്കിലും പരാമർശിച്ചിരിക്കുന്നതിനാൽ ഈ ഐഡന്റിഫയർ പുനർനാമകരണം ചെയ്യാൻ കഴിയില്ല",
  "ERROR_RENAME_GENERAL": "തിരഞ്ഞെടുത്ത വാചകം പുനർനാമകരണം ചെയ്യാൻ കഴിയില്ല",
  "JSHINT_NAME": "JShint",
  "CMD_ENABLE_QUICK_VIEW": "ഹോവറിൽ ദ്രുത കാഴ്ച",
  "CMD_ENABLE_SELECTION_VIEW": "തിരഞ്ഞെടുക്കൽ കാഴ്ച",
  "CMD_TOGGLE_RECENT_PROJECTS": "സമീപകാല പദ്ധതികൾ",
  "DOCS_MORE_LINK": "കൂടുതല് വായിക്കുക",
  "COLLAPSE_ALL": "എല്ലാം ചുരുക്കുക",
  "EXPAND_ALL": "എല്ലാം വിപുലീകരിക്കുക",
  "COLLAPSE_CURRENT": "നിലവിലെ ചുരുക്കുക",
  "EXPAND_CURRENT": "നിലവിലുള്ളത് വിപുലീകരിക്കുക",
  "RECENT_FILES_DLG_HEADER": "സമീപകാല ഫയലുകൾ",
  "RECENT_FILES_DLG_CLEAR_BUTTON_LABEL": "തെളിഞ്ഞ",
  "RECENT_FILES_DLG_CLEAR_BUTTON_TITLE": "വർക്കിംഗ് സെറ്റിൽ ഇല്ലാത്ത ഫയലുകൾ മായ്ക്കുക",
  "DESCRIPTION_CLOSE_BRACKETS": "ബ്രേസുകൾ, ബ്രാക്കറ്റുകൾ, പരാന്തിസിസ് എന്നിവ സ്വപ്രേരിതമായി അടയ്ക്കുന്നതിന് ശരിയാണ്",
  "DESCRIPTION_CLOSE_OTHERS_ABOVE": "ജോലി ഫയലുകൾ സന്ദർഭ മെനുവിൽ നിന്നും “മുകളിൽ മറ്റുള്ളവ അടയ്ക്കുക” നീക്കം തെറ്റായ",
  "DESCRIPTION_CLOSE_OTHERS_BELOW": "ജോലി ഫയലുകൾ സന്ദർഭ മെനുവിൽ നിന്നും “താഴെ മറ്റുള്ളവ അടയ്ക്കുക” നീക്കം തെറ്റായ",
  "DESCRIPTION_CLOSE_OTHERS": "വർക്കിംഗ് ഫയലുകളുടെ സന്ദർഭ മെനുവിൽ നിന്ന് “മറ്റുള്ളവ അടയ്ക്കുക” നീക്കംചെയ്യുന്നതിന് തെറ്റായ",
  "DESCRIPTION_CLOSE_TAGS": "ടാഗ് ക്ലോസിംഗ് ഓപ്ഷനുകൾ സജ്ജമാക്കുന്നു",
  "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS": "യാന്ത്രികമായി അടയ്ക്കാൻ പാടില്ലാത്ത ടാഗുകളുടെ ഒരു നിര",
  "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING": "> തുറക്കുന്ന ടാഗ് ടൈപ്പ് ചെയ്യുമ്പോൾ അടയ്ക്കുക",
  "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING": "ക്ലോസിംഗ് ടാഗ് ടൈപ്പ് ചെയ്യുമ്പോൾ /അടയ്ക്കുക",
  "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS": "തുറക്കുമ്പോൾ ഒരു കൂട്ടം ടാഗുകൾ ഒരു ശൂന്യമായ വരിയുണ്ട്",
  "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD": "ഇൻഡന്റ് ലെവൽ മാറുമ്പോൾ എല്ലായ്പ്പോഴും തകർക്കാവുന്ന സെക്ഷൻ മാർക്കറുകൾ സൃഷ്ടിക്കുന്നതിന് ശരിയാണ്",
  "DESCRIPTION_CODE_FOLDING_ENABLED": "കോഡ് മടക്കൽ പ്രവർത്തനക്ഷമമാക്കാൻ true",
  "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER": "നിങ്ങൾ അഴുക്കുചാലിൽ മൗസ് നീക്കുമ്പോൾ മാത്രം വിഭാഗം-തകർക്കുന്ന മാർക്കറുകൾ ദൃശ്യമാക്കാൻ true",
  "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL": "എത്ര ലെവലുകൾ ആഴമുള്ള ചുരുക്കുക പരിമിതപ്പെടുത്തുന്നു എല്ലാം ബാധകമാണ്",
  "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE": "തകർക്കാവുന്ന വിഭാഗ ഐക്കൺ ദൃശ്യമാകുന്നതിന് മുമ്പുള്ള ഏറ്റവും കുറഞ്ഞ",
  "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES": "നിങ്ങൾ ഒരു ഫയൽ അല്ലെങ്കിൽ പ്രോജക്റ്റ് അടച്ച് വീണ്ടും തുറക്കുകയാണെങ്കിൽ തകർന്ന വിഭാഗങ്ങൾ ഓർമ്മിക്കാൻ true",
  "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE": "എഡിറ്ററിൽ തിരഞ്ഞെടുത്ത വാചകത്തിൽ കോഡ് മടക്കിക്കളയുന്നത് പ്രാപ്തമാക്കുന്നതിന് true",
  "DESCRIPTION_DISABLED_DEFAULT_EXTENSIONS": "അപ്രാപ്തമാക്കിയ സ്ഥിരസ്ഥിതി വിപുലീകരണങ്ങൾ",
  "DESCRIPTION_ATTR_HINTS": "എച്ച്ടിഎംഎൽ ആട്രിബ്യൂട്ട് സൂചനകൾ പ്രവർത്തനക്ഷമമാക്കുക/",
  "DESCRIPTION_CSS_PROP_HINTS": "CSS/LS/SCSS പ്രോപ്പർട്ടി സൂചനകൾ പ്രവർത്തനക്ഷമമാക്കുക",
  "DESCRIPTION_JS_HINTS": "ജാവാസ്ക്രിപ്റ്റ് കോഡ് സൂചനകൾ പ്രവർത്തനക്ഷമമാക്കുക/അപ്രാപ്തമാക്കുക",
  "DESCRIPTION_JS_HINTS_TYPE_DETAILS": "JavaScript കോഡ് സൂചനകളിൽ ഡാറ്റാടൈപ്പ് വിശദാംശങ്ങൾ പ്രാപ്തമാക്കുക/അപ്രാപ്തമാക്കുക",
  "DESCRIPTION_PREF_HINTS": "മുൻഗണനകൾ കോഡ് സൂചനകൾ പ്രാപ്തമാക്കുക/അപ്രാപ്ത",
  "DESCRIPTION_SPECIAL_CHAR_HINTS": "HTML എന്റിറ്റി സൂചനകൾ പ്രാപ്തമാക്കുക/അപ്രാപ്ത",
  "DESCRIPTION_SVG_HINTS": "എസ്വിജി കോഡ് സൂചനകൾ പ്രാപ്തമാക്കുക/അപ്രാപ്തമാക്കുക",
  "DESCRIPTION_HTML_TAG_HINTS": "HTML ടാഗ് സൂചനകൾ പ്രാപ്തമാക്കുക/അപ്രാപ്തമാക്കുക",
  "DESCRIPTION_URL_CODE_HINTS": "HTML & CSS/Les/SCSS ൽ URL സൂചനകൾ പ്രാപ്തമാക്കുക/അപ്രാപ്തമാക്കുക",
  "DESCRIPTION_DRAG_DROP_TEXT": "ഡ്രാഗ് & ഡ്രോപ്പ് പ്രവർത്തനം പ്രവർത്തനക്ഷമമാക്കുക/അപ്രാപ്തമാക്കുക",
  "DESCRIPTION_HEALTH_DATA_TRACKING": "ആരോഗ്യ ഡാറ്റ ട്രാക്കിംഗ് പ്രവർത്തനക്ഷമമാക്കുക",
  "DESCRIPTION_HIGHLIGHT_MATCHES": "പ്രമാണത്തിലുടനീളം പൊരുത്തപ്പെടുന്ന സ്ട്രിംഗുകളുടെ യാന്ത്രിക ഹൈലൈറ്റ് പ്രാപ്തമാക്കുന്നു",
  "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN": "കഴ്സർ നിലവിൽ ഉള്ള ടോക്കണുമായി പൊരുത്തപ്പെടുന്ന എല്ലാ സ്ട്രിംഗുകളും ഹൈലൈറ്റ് ചെയ്യുക (തിരഞ്ഞെടുക്കൽ ആവശ്യമില്ല)",
  "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY": "തിരഞ്ഞെടുക്കൽ പൂർണ്ണമായ ടോക്കൺ ആയിരിക്കുമ്പോൾ മാത്രം ഹൈലൈറ്റ് ചെയ്യുക",
  "DESCRIPTION_INSERT_HINT_ON_TAB": "ടാബിൽ നിലവിൽ തിരഞ്ഞെടുത്ത കോഡ് സൂചന ചേർക്കുന്നതിന് true",
  "DESCRIPTION_NO_HINTS_ON_DOT": "സ്വയം ജെ. എസ് കോഡ് സൂചനകൾ കാണിക്കാൻ സത്യമാണ്.",
  "DESCRIPTION_JSHINT_OPTIONS": "JShint- നായുള്ള സ്ഥിരസ്ഥിതി ഓപ്ഷനുകളുള്ള ഒരു ഒബ്ജക്റ്റ്. ലഭ്യമായ എല്ലാ JShint ഓപ്ഷനുകൾക്കുമായി ഇനിപ്പറയുന്ന URL കാണുക: https://jshint.com/docs/options/",
  "DESCRIPTION_LANGUAGE": "ഭാഷ നിർദ്ദിഷ്ട ക്രമീകരണങ്ങൾ",
  "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS": "ഫയൽ വിപുലീകരണത്തിൽ നിന്ന് ഭാഷാ നാമത്തിലേക്ക് അധിക മാപ്പിംഗുകൾ",
  "DESCRIPTION_LANGUAGE_FILE_NAMES": "ഫയലിന്റെ പേര് മുതൽ ഭാഷാ നാമം വരെയുള്ള അധിക മാപ്പിംഗുകൾ",
  "DESCRIPTION_LINEWISE_COPY_CUT": "തിരഞ്ഞെടുക്കൽ ഇല്ലാത്തപ്പോൾ പകർപ്പും മുറിക്കലും ചെയ്യുന്നത് അവയിൽ കഴ്സറുകളുള്ള മുഴുവൻ വരികളും പകർത്തുകയോ മുറിക്കുകയോ ചെയ്യും",
  "DESCRIPTION_INPUT_STYLE": "വഴി ചൊദെമിര്രൊര് ഇൻപുട്ട് ഫോക്കസ് കൈകാര്യം തിരഞ്ഞെടുക്കുന്നു. ഇത് ടെക്സ്റ്റാരിയ ആകാം, ഇത് സ്ഥിരസ്ഥിതിയോ അല്ലെങ്കിൽ സ്ക്രീൻ റീഡറുകൾക്ക് (അസ്ഥിരമോ) മികച്ചതോ ആയ ഉള്ളടക്കമാണ്",
  "DESCRIPTION_LINTING_ENABLED": "കോഡ് പരിശോധന പ്രവർത്തനക്ഷമമാക്കുന്നതിന് true",
  "DESCRIPTION_ASYNC_TIMEOUT": "അസിൻക്രണസ് ലിന്റേഴ്സ് സമയം കഴിഞ്ഞ് മില്ലിസെക്കൻഡിൽ സമയം",
  "DESCRIPTION_LINTING_PREFER": "ആദ്യം പ്രവർത്തിപ്പിക്കാൻ ലിംതെര്സ് അറേ",
  "DESCRIPTION_LIVE_DEV_MULTIBROWSER": "പരീക്ഷണാത്മക ലൈവ് പ്രിവ്യൂ പ്രാപ്തമാക്കാൻ true",
  "DESCRIPTION_USE_PREFERED_ONLY": "ലിൻടിംഗിൽ വ്യക്തമാക്കിയ ദാതാക്കളെ പ്രവർത്തിപ്പിക്കുന്നതിന് ശരിയാണ്.",
  "DESCRIPTION_MAX_CODE_HINTS": "പരമാവധി കോഡ് സൂചനകൾ ഒറ്റയടിക്ക് പ്രദർശിപ്പിക്കും",
  "DESCRIPTION_PATH": "പാത നിർദ്ദിഷ്ട ക്രമീകരണങ്ങൾ",
  "DESCRIPTION_PROXY": "വിപുലീകരണ ഇൻസ്റ്റാളേഷനായി ഉപയോഗിക്കുന്ന പ്രോക്സി സെർവറിന്റെ URL",
  "DESCRIPTION_SCROLL_PAST_END": "പ്രമാണത്തിന്റെ അവസാനത്തിനപ്പുറം സ്ക്രോളിംഗ് പ്രാപ്തമാക്കുന്നതിന് true",
  "DESCRIPTION_SHOW_CODE_HINTS": "എല്ലാ കോഡ് സൂചനകളും അപ്രാപ്തമാക്കാൻ തെറ്റായ",
  "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING": "നിങ്ങൾക്ക് ഒരു ടെക്സ്റ്റ് സെലക്ഷൻ ഉള്ളപ്പോൾ മിന്നുന്ന കഴ്സർ ദൃശ്യമാകും",
  "DESCRIPTION_SHOW_LINE_NUMBERS": "കോഡിന്റെ ഇടതുവശത്തുള്ള ഒരു “ഗട്ടറിൽ” ലൈൻ നമ്പറുകൾ കാണിക്കാൻ true",
  "DESCRIPTION_SMART_INDENT": "ഒരു പുതിയ ബ്ലോക്ക് സൃഷ്ടിക്കുമ്പോൾ യാന്ത്രികമായി ഇൻഡന്റ് ചെയ്യുക",
  "DESCRIPTION_SOFT_TABS": "സോഫ്റ്റ് ടാബുകൾ സ്വഭാവം ഓഫ് തെറ്റായ",
  "DESCRIPTION_SORT_DIRECTORIES_FIRST": "പ്രോജക്റ്റ് ട്രീയിൽ ആദ്യം ഡയറക്ടറികൾ അടുക്കുന്നതിന് ശരിയാണ്",
  "DESCRIPTION_SPACE_UNITS": "സ്പെയ്സ് അധിഷ്ഠിത ഇൻഡന്റേഷനായി ഉപയോഗിക്കേണ്ട ഇടങ്ങളുടെ എണ്ണം",
  "DESCRIPTION_STATIC_SERVER_PORT": "തത്സമയ പ്രിവ്യൂവിന് അന്തർനിർമ്മിത സെർവർ ഉപയോഗിക്കേണ്ട പോർട്ട് നമ്പർ",
  "DESCRIPTION_STYLE_ACTIVE_LINE": "കഴ്സർ ഓൺ ചെയ്ത വരിയുടെ പശ്ചാത്തല നിറം ഹൈലൈറ്റ് ചെയ്യുന്നതിന് ശരിയാണ്",
  "DESCRIPTION_TAB_SIZE": "ടാബുകൾക്കായി പ്രദർശിപ്പിക്കാനുള്ള ഇടങ്ങളുടെ എണ്ണം",
  "DESCRIPTION_USE_TAB_CHAR": "സ്പെയ്സുകൾക്ക് പകരം ടാബുകൾ ഉപയോഗിക്കുന്നത് ശരിയാണ്",
  "DESCRIPTION_UPPERCASE_COLORS": "ഇൻലൈൻ കളർ എഡിറ്ററിൽ വലിയക്ഷര ഹെക്സ് നിറങ്ങൾ സൃഷ്ടിക്കുന്നത് ശരിയാണ്",
  "DESCRIPTION_WORD_WRAP": "വ്യൂപോർട്ട് വീതി കവിയുന്ന റാപ് ലൈനുകൾ",
  "DESCRIPTION_SEARCH_AUTOHIDE": "എഡിറ്റർ ശ്രദ്ധ കേന്ദ്രീകരിച്ചാലുടൻ തിരയൽ അടയ്ക്കുക",
  "DESCRIPTION_DETECTED_EXCLUSIONS": "ടെർൺ നിയന്ത്രണം തീർന്നുപോകുന്നതിന് കാരണമാകുമെന്ന് കണ്ടെത്തിയ ഫയലുകളുടെ ഒരു ലിസ്റ്റ്",
  "DESCRIPTION_INFERENCE_TIMEOUT": "ഫയലുകൾ മനസിലാക്കാൻ ശ്രമിക്കുമ്പോൾ ടെർൺ സമയം ചെലവഴിക്കും",
  "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR": "സ്റ്റാറ്റസ് ബാറിൽ പിശകുകൾ കാണിക്കാൻ true",
  "DESCRIPTION_QUICK_VIEW_ENABLED": "ദ്രുത കാഴ്ച പ്രവർത്തനക്ഷമമാക്കാൻ true",
  "DESCRIPTION_SELECTION_VIEW_ENABLED": "തിരഞ്ഞെടുക്കൽ കാഴ്ച പ്രാപ്തമാക്കുന്നതിന് true",
  "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW": "വിപുലീകരണങ്ങൾ കാണാതായ URL- കൾക്കായി ഇമേജ് പ്രിവ്യൂകൾ കാണിക്കുന്നതിന് true",
  "DESCRIPTION_THEME": "ഒരു {APP_NAME} തീം തിരഞ്ഞെടുക്കുക",
  "DESCRIPTION_USE_THEME_SCROLLBARS": "ഇഷ്ടാനുസൃത സ്ക്രോൾ ബാറുകൾ അനുവദിക്കുന്നതിന് ശരിയാണ്",
  "DESCRIPTION_LINTING_COLLAPSED": "ലിൻറ്റിംഗ് പാനൽ ചുരുങ്ങുന്നത് ശരിയാണ്",
  "DESCRIPTION_FONT_FAMILY": "ഫോണ്ട് കുടുംബം മാറ്റുക",
  "DESCRIPTION_FONT_SIZE": "ഫോണ്ട് വലുപ്പം മാറ്റുക; ഉദാ. 13px",
  "DESCRIPTION_FIND_IN_FILES_NODE": "നോഡ് അടിസ്ഥാനമാക്കിയുള്ള തിരയൽ പ്രാപ്തമാക്കുന്നതിന് true",
  "DESCRIPTION_FIND_IN_FILES_INSTANT": "തൽക്ഷണ തിരയൽ പ്രവർത്തനക്ഷമമാക്കാൻ true",
  "DESCRIPTION_FONT_SMOOTHING": "മാക്-മാത്രം: “സബ്പിക്സൽ-അംതിഅലിഅസെദ്” സബ്-പിക്സൽ അംതിഅലിഅസിന്ഗ് പ്രാപ്തമാക്കാൻ അല്ലെങ്കിൽ ഗ്രേ സ്കെയിൽ അംതിഅലിഅസിന്ഗ് വേണ്ടി “അംതിഅലിഅസെദ്”",
  "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW": "പിളർപ്പ് കാഴ്ചയിൽ തുറക്കുന്ന മുൻഗണനകൾ ഫയൽ അപ്രാപ്തമാക്കാൻ തെറ്റായ",
  "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE": "ഇടത്/മുകളിൽ പാളിയിൽ ഉപയോക്തൃ മുൻഗണനകൾ ഫയൽ തുറക്കാൻ തെറ്റായ",
  "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED": "പാളിയിൽ നിന്നുള്ള അവസാന ഫയൽ പെയ്ൻ ഹെഡർ ക്ലോസ് ബട്ടൺ വഴി അടച്ചതിനുശേഷം പാളികൾ ചുരുക്കാൻ ശരിയാണ്",
  "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS": "ഹെഡ്ഡറിൽ അടുത്തതും ഫ്ലിപ്പ്-വ്യൂ ബട്ടണുകളും കാണിക്കുമ്പോൾ ടോഗിൾ ചെയ്യുക.",
  "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT": "/*\n * ഇത് പിന്തുണയ്ക്കുന്ന മുൻഗണനകളുള്ള ഒരു റീഡ്-ഒണ്ലി-ഫയലാണ്\n * {APP_NAME} ചെയ്തത്.\n * നിങ്ങളുടെ മുൻഗണനകൾ പരിഷ്ക്കരിക്കുന്നതിന് ഒരു റഫറൻസായി ഈ ഫയൽ ഉപയോഗിക്കുക\n * ഫയൽ “ബ്രാക്കറ്റുകൾ. ജ്സൊന്” മറ്റ് പാളിയിൽ തുറന്നു.\n * ഉള്ളിൽ മുൻഗണനകൾ എങ്ങനെ ഉപയോഗിക്കാം എന്നതിനെക്കുറിച്ചുള്ള കൂടുതൽ വിവരങ്ങൾക്ക്\n * {APP_NAME}, https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences എന്നതിലെ വെബ് പേജ് കാണുക\n */",
  "DEFAULT_PREFERENCES_JSON_DEFAULT": "സ്ഥിരസ്ഥിതി",
  "DESCRIPTION_PURE_CODING_SURFACE": "കോഡ് മാത്രം മോഡ് പ്രവർത്തനക്ഷമമാക്കുന്നതിനും മറ്റെല്ലാ യുഐ ഘടകങ്ങളും മറയ്ക്കുന്നതിനും true {APP_NAME}",
  "DESCRIPTION_INDENT_LINE_COMMENT": "ലൈൻ അഭിപ്രായങ്ങൾ ഇംദെംതിന്ഗ് പ്രാപ്തമാക്കാൻ true",
  "DESCRIPTION_RECENT_FILES_NAV": "സമീപകാല ഫയലുകളിൽ നാവിഗേഷൻ പ്രാപ്തമാക്കുക/അപ്രാപ്തമാക്കുക",
  "DESCRIPTION_LIVEDEV_WEBSOCKET_PORT": "തത്സമയ പ്രിവ്യൂവിന് വെബ്സോക്കറ്റ് സെർവർ പ്രവർത്തിക്കുന്ന പോർട്ട്",
  "DESCRIPTION_LIVE_DEV_HIGHLIGHT_SETTINGS": "തത്സമയ പ്രിവ്യൂ ഹൈലൈറ്റ് ക്രമീകരണങ്ങൾ",
  "DESCRIPTION_LIVEDEV_ENABLE_REVERSE_INSPECT": "തൽസമയ പ്രിവ്യൂ റിവേഴ്സ് പരിശോധന അപ്രാപ്തമാക്കാൻ തെറ്റായ",
  "DOWNLOAD_FAILED": "ഡൗൺലോഡ് പരാജയപ്പെട്ടു.",
  "DOWNLOAD_COMPLETE": "പൂർണ്ണമായ ഡൗൺലോഡ്!",
  "UPDATE_SUCCESSFUL": "വിജയകരമായ അപ്ഡേറ്റ്!",
  "UPDATE_FAILED": "അപ്ഡേറ്റ് പരാജയപ്പെട്ടു!",
  "VALIDATION_FAILED": "മൂല്യനിർണ്ണയം പരാജയപ്പെട്ടു!",
  "INITIALISATION_FAILED": "സമാരംഭിക്കൽ പരാജയപ്പെട്ടു!",
  "CLEANUP_FAILED": "വൃത്തിയാക്കൽ പരാജയപ്പെട്ടു!",
  "WARNING_TYPE": "മുന്നറിയിപ്പ്!",
  "CLICK_RESTART_TO_UPDATE": "ബ്രാക്കറ്റുകൾ അപ്ഡേറ്റ് ചെയ്യുന്നതിന് പുനരാരംഭിക്കുക ക്ലിക്കുചെയ്യുക.",
  "UPDATE_ON_NEXT_LAUNCH": "അപ്ഡേറ്റ് വീണ്ടും സമാരംഭിക്കുമ്പോൾ പ്രയോഗിക്കും.",
  "GO_TO_SITE": "വീണ്ടും ശ്രമിക്കുന്നതിന് <a href = \"http://brackets.io/ “> brackets.io എന്നതിലേക്ക് പോകുക </a> .",
  "INTERNET_UNAVAILABLE": "ഇന്റർനെറ്റ് കണക്ഷൻ ലഭ്യമല്ല.",
  "UPDATEDIR_READ_FAILED": "അപ്ഡേറ്റ് ഡയറക്ടറി വായിക്കാൻ കഴിഞ്ഞില്ല.",
  "UPDATEDIR_CLEAN_FAILED": "അപ്ഡേറ്റ് ഡയറക്ടറി വൃത്തിയാക്കാൻ കഴിഞ്ഞില്ല.",
  "INITIAL_DOWNLOAD": "അപ്ഡേറ്റ് ഡൗൺലോഡുചെയ്യുന്നു...",
  "RETRY_DOWNLOAD": "ഡൗൺലോഡ് പരാജയപ്പെട്ടു. വീണ്ടും ശ്രമിക്കുന്നു... ശ്രമം ",
  "VALIDATING_INSTALLER": "പൂർണ്ണമായ ഡൗൺലോഡ്! ഇൻസ്റ്റാളർ സാധൂകരിക്കുന്നു...",
  "CHECKSUM_DID_NOT_MATCH": "ചെക്ക്സം പൊരുത്തപ്പെടുന്നില്ല.",
  "INSTALLER_NOT_FOUND": "ഇൻസ്റ്റാളർ കണ്ടെത്തിയില്ല.",
  "DOWNLOAD_ERROR": "ഡൌൺലോഡ് ചെയ്യുമ്പോൾ പിശക് സംഭവിച്ചു.",
  "NETWORK_SLOW_OR_DISCONNECTED": "നെറ്റ്വർക്ക് വിച്ഛേദിച്ചു അല്ലെങ്കിൽ വളരെ മന്ദഗതിയിലാണ്.",
  "RESTART_BUTTON": "പുനരാരംഭിക്കുക",
  "LATER_BUTTON": "പിന്നീട്",
  "DESCRIPTION_AUTO_UPDATE": "ബ്രാക്കറ്റുകൾ യാന്ത്രിക-അപ്ഡേറ്റ് പ്രാപ്തമാക്കുക/അപ്രാപ്തമാക്കുക",
  "AUTOUPDATE_ERROR": "പിശക്!",
  "AUTOUPDATE_IN_PROGRESS": "ഒരു അപ്ഡേറ്റ് ഇതിനകം പുരോഗതിയിലാണ്.",
  "NUMBER_WITH_PERCENTAGE": "{0}%",
  "CMD_FIND_RELATED_FILES": "ബന്ധപ്പെട്ട ഫയലുകൾ കണ്ടെത്തുക",
  "PHP_VERSION_INVALID": "എച്ച്. പി പതിപ്പ് പാഴ്സിംഗ് പിശക്. “php —version” കമാൻഡിന്റെ ഔട്ട്പുട്ട് പരിശോധിക്കുക.",
  "PHP_UNSUPPORTED_VERSION": "കോഡ് സൂചനകൾ, പാരാമീറ്റർ സൂചനകൾ, നിർവചനത്തിലേക്ക് പോകുക എന്നിവയും അതിലേറെയും പോലുള്ള പിഎച്ച്പിയുമായി ബന്ധപ്പെട്ട ടൂളിംഗ് പ്രാപ്തമാക്കുന്നതിനായി PHP7 റൺടൈം ഇൻസ്റ്റാൾ ചെയ്യുക. പതിപ്പ് കണ്ടെത്തി: {0}",
  "PHP_EXECUTABLE_NOT_FOUND": "എച്ച്. പി പ്രവർത്തനസമയം കണ്ടെത്തിയില്ല. പിഎച്ച്പി മുൻഗണനകളിൽ PHP7 പ്രവർത്തനസമയം ഇൻസ്റ്റാൾ ചെയ്ത് “എക്സിക്യൂട്ടബിൾപാത്ത്” അപ്ഡേറ്റ് ചെയ്യുക. കോഡ് സൂചനകൾ, പാരാമീറ്റർ സൂചനകൾ, നിർവചനത്തിലേക്ക് പോകുക എന്നിവയും അതിലേറെയും പോലുള്ള പിഎച്ച്പിയുമായി ബന്ധപ്പെട്ട ടൂളിംഗ് ഇത് പ്രാപ്തമാക്കുന്നു.",
  "PHP_PROCESS_SPAWN_ERROR": "പിഎച്ച്പി പ്രക്രിയ ആരംഭിക്കുമ്പോൾ പിശക് കോഡ് {0} നേരിട്ടു.",
  "PHP_SERVER_ERROR_TITLE": "പിശക്",
  "PHP_SERVER_MEMORY_LIMIT_INVALID": "നിങ്ങൾ നൽകിയ മെമ്മറി പരിധി അസാധുവാണ്. ശരിയായ മൂല്യം സജ്ജമാക്കാൻ PHP മുൻഗണനകൾ അവലോകനം ചെയ്യുക.",
  "DESCRIPTION_PHP_TOOLING_CONFIGURATION": "പിഎച്ച്പി ടൂളിംഗ് സ്ഥിരസ്ഥിതി കോൺഫിഗറേഷൻ ക്രമീകരണങ്ങൾ",
  "OPEN_PREFERENNCES": "മുൻഗണനകൾ തുറക്കുക",
  "LANGUAGE_TOOLS_PREFERENCES": "ഭാഷാ ഉപകരണങ്ങൾക്കുള്ള മുൻഗണനകൾ",
  "FIND_ALL_REFERENCES": "എല്ലാ അവലംബങ്ങളും കണ്ടെത്തുക",
  "REFERENCES_IN_FILES": "പരാമർശങ്ങൾ",
  "REFERENCE_IN_FILES": "റഫറൻസ്",
  "REFERENCES_NO_RESULTS": "നിലവിലെ കഴ്സർ സ്ഥാനത്തിനായി റഫറൻസുകൾ ലഭ്യമല്ല",
  "CMD_FIND_DOCUMENT_SYMBOLS": "പ്രമാണ ചിഹ്നങ്ങൾ കണ്ടെത്തുക",
  "CMD_FIND_PROJECT_SYMBOLS": "പ്രോജക്റ്റ് ചിഹ്നങ്ങൾ കണ്ടെത്തുക",
  "REMOTE_DEBUGGING_ENABLED": "ലോക്കൽഹോസ്റ്റിൽ വിദൂര ഡീബഗ്ഗിംഗ് പ്രവർത്തനക്ഷമമാക്കി:",
  "REMOTE_DEBUGGING_PORT_INVALID": "പോർട്ട് {0} ൽ വിദൂര ഡീബഗ്ഗിംഗ് പ്രാപ്തമാക്കാൻ കഴിയില്ല. പോർട്ട് നമ്പറുകൾ {1} നും {2} നും ഇടയിലായിരിക്കണം.",
  "DESCRIPTION_EXTERNAL_APPLICATION_ASSOCIATE": "ബാഹ്യ അപ്ലിക്കേഷനുകളിലേക്ക് ഫയൽ വിപുലീകരണത്തിനുള്ള മാപ്പിംഗുകൾ. വാക്യഘടന: \"<file_type>“: “<default|applicationname|Applicationpath>”, ഫയല് ടൈപ്പിനായി സിസ്റ്റം ഡിഫോള്ട്ട് ആപ്ലിക്കേഷനില് ഫയലുകള് തുറക്കുന്നതിന് “default” ഉപയോഗിക്കുക.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_TITLE": "ബാഹ്യ എഡിറ്റർമാരിൽ ഗ്രാഫിക് ഫയലുകൾ തുറക്കുക.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_MSG": "നിങ്ങളുടെ നിലവിലെ ഫോൾഡറിൽ {APP_NAME} പിന്തുണയ്ക്കാത്ത ഗ്രാഫിക് ഫയൽ തരങ്ങളുണ്ട്. <br/>നിങ്ങൾക്ക്ഇപ്പോൾ പ്രത്യേക ഫയൽ തരങ്ങൾ ബാഹ്യ എഡിറ്റർമാരുമായി ബന്ധപ്പെടുത്താം. ബന്ധപ്പെട്ടുകഴിഞ്ഞാൽ, ഫയൽ ട്രീയിലെ ഫയലുകളിൽ ഇരട്ട ക്ലിക്കുചെയ്ത് നിങ്ങൾക്ക്.xd, .psd, .jpg, .png, .ai, .svg പോലുള്ള ഗ്രാഫിക് ഫയലുകൾ അവരുടെ സ്ഥിരസ്ഥിതി ആപ്ലിക്കേഷനുകളിൽ തുറക്കാൻ കഴിയും. <br/><br/>ഗ്രാഫിക്ഫയൽ തരങ്ങൾ അതത് സ്ഥിരസ്ഥിതി അപ്ലിക്കേഷനുകളുമായി ബന്ധപ്പെടുത്തുന്നതിന് 'ശരി' ബട്ടണിൽ ക്ലിക്കുചെയ്യുക.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_CNF_MSG": "ഫയൽ തരങ്ങൾ പിന്തുടർന്ന് വിജയകരമായി സ്ഥിര അപ്ലിക്കേഷനുകൾ ബന്ധപ്പെട്ടിരിക്കുന്നു. <br/>{0} “ഡീബഗ്->മുൻഗണനകൾ തുറക്കുക ഫയൽ” മെനുവിലേക്ക് പോയി നിങ്ങൾ ബ്രാക്കറ്റുകളിൽ പുതിയ ഫയൽ ടൈപ്പ് അസോസിയേഷനുകൾ നീക്കം ചെയ്യുക/ചേർക്കുക എന്നതിൽ നിങ്ങളുടെ മുൻഗണന മാറ്റാനുള്ള ഓപ്ഷൻ നിങ്ങൾക്കുണ്ട്.",
  "UNSUPPORTED_BROWSER": "ബ്രൗസർ പിന്തുണയ്ക്കുന്നില്ല",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER": "ബ്രൗസർ പിന്തുണയ്ക്കുന്നില്ല ഫോൾഡർ തുറക്കുക",
  "UNSUPPORTED_BROWSER_MESSAGE_LINE1": "താഴെ പിന്തുണയ്ക്കുന്ന ബ്രൗസറുകളിൽ ഒന്ന് ഉപയോഗിക്കുക.",
  "UNSUPPORTED_BROWSER_MESSAGE_LINE2": " ഫീനിക്സ് കൂടുതൽ ബ്രൗസറുകളിൽ ലഭ്യമാക്കാൻ ഞങ്ങൾ കഠിനമായി പരിശ്രമിക്കുന്നു. നിങ്ങൾ ഈ ഡയലോഗ് ക്ലോസ് ചെയ്യാം, എന്നാൽ ഫീനിക്സ് ചില സവിശേഷതകൾ ഈ ബ്രൗസറിൽ പ്രവർത്തിക്കില്ല.",
  "CANNOT_PUBLISH_LARGE_PROJECT": "വലിയ പ്രോജക്റ്റ് പ്രസിദ്ധീകരിക്കാൻ കഴിയില്ല",
  "CANNOT_PUBLISH_LARGE_PROJECT_MESSAGE": "ഫീനിക്സ് പരീക്ഷണാത്മക ആൽഫ ഇപ്പോഴും. 500 ഫയലുകളിൽ കൂടുതലുള്ള പ്രോജക്റ്റുകളുടെ സമന്വയം ഞങ്ങൾ ഇതുവരെ പ്രാപ്തമാക്കിയിട്ടില്ല.",
  "SHARE_WEBSITE": "വെബ്സൈറ്റ് പ്രസിദ്ധീകരിക്കുക, പങ്കിടുക?",
  "PUBLISH": "പ്രസിദ്ധീകരിക്കുക",
  "PUBLISH_CONSENT_MESSAGE": "മാറ്റങ്ങൾ വേഗത്തിൽ പ്രിവ്യൂ ചെയ്യുകയും നിങ്ങളുടെ വെബ്സൈറ്റ് മറ്റുള്ളവരുമായി പങ്കിടുകയും ചെയ്യുക. ഫീനിക്സ് {0} നിങ്ങൾക്കായി ഈ വെബ്സൈറ്റ് പ്രസിദ്ധീകരിക്കാൻ കഴിയും. പ്രസിദ്ധീകരിച്ച ലിങ്കുകൾ 7 ദിവസത്തേക്ക് സാധുതയുള്ളതായിരിക്കും. </br>നിങ്ങളുടെവെബ്സൈറ്റ് പ്രസിദ്ധീകരിക്കാനും പങ്കിടാനും നിങ്ങൾ ആഗ്രഹിക്കുന്നുണ്ടോ?",
  "PUBLISH_SYNC_IN_PROGRESS": "പ്രിവ്യൂ പുരോഗതിയിലാണ് സമന്വയിപ്പിക്കുക...",
  "PUBLISH_PAGE": "ഈ സൈറ്റ് പ്രസിദ്ധീകരിക്കാനും പങ്കിടാനും ക്ലിക്കുചെയ്യുക",
  "PUBLISH_VIEW_PAGE": "പ്രസിദ്ധീകരിച്ച പേജ് കാണുന്നതിന് ക്ലിക്കുചെയ്യുക",
  "MISSING_FIELDS": "കാണാതായ ഫീൽഡുകൾ",
  "PLEASE_FILL_ALL_REQUIRED": "ചുവപ്പ് നിറത്തിൽ ഹൈലൈറ്റ് ചെയ്ത ആവശ്യമായ എല്ലാ ഫീൽഡുകളും പൂരിപ്പിക്കുക",
  "CODE_EDITOR": "കോഡ് എഡിറ്റർ",
  "BUILD_THE_WEB": "വെബ് നിർമ്മിക്കുക",
  "IMPORT_PROJECT": "പ്രോജക്റ്റ് ഇറക്കുമതി ചെയ്യുക",
  "GITHUB_PROJECT": "ഗിറ്റ്ഹബ് പ്രോജക്റ്റ്",
  "NEW_PROJECT_FROM_GITHUB": "ഗിറ്റ്ഹബിൽ നിന്നുള്ള പുതിയ പ്രോജക്റ്റ്",
  "GITHUB_REPO_URL": "ഗിറ്റ്ഹബ് റിപ്പോ URL:",
  "CREATE_PROJECT": "പ്രോജക്റ്റ് സൃഷ്ടിക്കുക",
  "SETTING_UP_PROJECT": "പ്രോജക്റ്റ് സജ്ജമാക്കുന്നു",
  "LOCATION": "സ്ഥലം:",
  "DOWNLOADING": "ഡൗൺലോഡുചെയ്യുന്നു...",
  "EXTRACTING_FILES_PROGRESS": "{1} ഫയലുകളുടെ {0} എക്സ്ട്രാക്റ്റുചെയ്യുന്നു.",
  "DOWNLOAD_FAILED_MESSAGE": "ഡ download ൺലോഡ് URL സാധുവാണെന്ന് ഉറപ്പാക്കുക. </br>NB: ഫീനിക്സ് ആൽഫയിൽ ഉള്ളതിനാൽ, 25 MB- യിൽ കൂടുതൽ വലുപ്പമുള്ള സ്വകാര്യ റിപോകളും Github URL കളും അനുവദനീയമല്ല.",
  "PLEASE_SELECT_A_FOLDER": "ദയവായി ഒരു ഫോൾഡർ തിരഞ്ഞെടുക്കുക...",
  "UNZIP_IN_PROGRESS": "ഫയലുകൾ അൺസിപ്പ് ചെയ്യുന്നു...",
  "UNZIP_FAILED": "പിശക്: അൺസിപ്പിംഗ് പരാജയപ്പെട്ടു.",
  "CONFIRM_REPLACE_TITLE": "മാറ്റിസ്ഥാപിക്കുക സ്ഥിരീകരിക്കുക",
  "KEEP_BOTH": "രണ്ടും സൂക്ഷിക്കുക",
  "EXPLORE": "HTML ഗെയിമുകൾ",
  "BLOG": "ബ്ലോഗ്",
  "PHOENIX_DEFAULT_PROJECT": "സ്ഥിരസ്ഥിതി പ്രോജക്റ്റ്",
  "PROJECT_NAME": "പ്രോജക്റ്റിന്റെ പേര്:",
  "NEW_HTML": "പുതിയ HTML പ്രോജക്റ്റ്",
  "LICENSE": "ലൈസൻസ്:",
  "CREDITS": "ക്രെഡിറ്റുകൾ:",
  "PREVIEW": "പ്രിവ്യൂ",
  "BUILD_WEBSITE": "വെബ്സൈറ്റ് നിർമ്മിക്കുക",
  "VIEW_MORE": "കൂടുതൽ കാണുക...",
  "NEW_PROJECT_NOTIFICATION": "ഒരു പുതിയ പ്രോജക്റ്റ്<br/>സൃഷ്ടിക്കുന്നതിന് ഈ ഐക്കണിൽ ക്ലിക്കുചെയ്യുക. </br> <a href='#' style='float:right;'>ശരി</a>",
  "DEFAULT_PROJECT_NOTIFICATION": "ഫീനിക്സിൽ <br/><b>സ്ഥിരസ്ഥിതി പ്രോജക്റ്റ്</b> തുറക്കാൻ ഇവിടെ ക്ലിക്കുചെയ്യുക. </br> <a href='#' style='float:right;'>ശരി</a>",
  "DIRECTORY_REPLACE_MESSAGE": "തിരഞ്ഞെടുത്ത ഫോൾഡർ <span class='dialog-filename'>{0}</span> ശൂന്യമല്ല. പ്രോജക്റ്റിനൊപ്പം ഫോൾഡർ ഉള്ളടക്കങ്ങൾ മാറ്റിസ്ഥാപിക്കണമെന്ന് നിങ്ങൾക്ക് ഉറപ്പാണോ?",
  "BUILD_WEBSITE_SECTION": "വെബ്സൈറ്റ് നിർമ്മിക്കുക",
  "LEARN_SECTION": "ഉദാഹരണങ്ങൾ ഉപയോഗിച്ച് പഠിക്കുക",
  "WEBPAGE_HOME_PAGE": "വീട് പേജ് ലേഔട്ടുകൾ",
  "WEBPAGE_BLOG": "ബ്ലോഗ് പേജ്",
  "WEBPAGE_DASHBOARD": "HTML ഡാഷ്ബോർഡ്",
  "WEBPAGE_BOOTSTRAP_EXAMPLES": "ബൂട്ട്സ്ട്രാപ്പ് ഉദാഹരണങ്ങൾ",
  "GUIDED_FILES_SIDEBAR": "<a href='#' style='float:right;'>ശരി</a>ഒരു HTML ഫയൽ തിരഞ്ഞെടുക്കുക </br>",
  "GUIDED_LIVE_PREVIEW": "പ്രിവ്യൂ കാണുന്നതിന് ചില കോഡ് മാറ്റങ്ങൾ വരുത്തി ഫയൽ സംരക്ഷിക്കുക. </br> <a href='#' style='float:right;'>ശരി</a>",
  "GUIDED_LIVE_PREVIEW_POPOUT": "ഒരു പുതിയ ടാബിലേക്ക് തത്സമയ പ്രിവ്യൂ പോപ്പ് out ട്ട് ചെയ്യുന്നതിന് ഈ ബട്ടൺ ക്ലിക്കുചെയ്യുക. </br> <a href='#' style='float:right;'>ശരി</a>",
  "TEST_TRANSLATE": "വിവർത്തനങ്ങൾ പരീക്ഷിക്കാൻ ഇത് ഉപയോഗിക്കുക",
  "BEAUTIFY_OPTIONS": "എങ്ങനെ നിയന്ത്രിക്കുന്ന ഓപ്ഷനുകൾ Beautify കോഡ് പ്രവർത്തിക്കുന്നു",
  "BEAUTIFY_OPTION_PRINT_WIDTH": "ബ്യൂട്ടിഫയർ പൊതിയുന്ന ലൈൻ ദൈർഘ്യം വ്യക്തമാക്കുക",
  "BEAUTIFY_OPTION_SEMICOLON": "ഓരോ പ്രസ്താവനയുടെയും അവസാനം ഒരു അർദ്ധവിരാമം ചേർക്കുക",
  "BEAUTIFY_OPTION_SINGLE_QUOTE": "ഇരട്ട ഉദ്ധരണികൾക്കു പകരം ഒറ്റ ഉദ്ധരണികൾ ഉപയോഗിക്കുക",
  "BEAUTIFY_OPTION_QUOTE_PROPS": "ഒബ്ജക്റ്റുകളിലെ പ്രോപ്പർട്ടികൾ ഉദ്ധരിക്കുമ്പോൾ മാറ്റുക",
  "BEAUTIFY_OPTION_BRACKET_SAME_LINE": "അടുത്ത വരിയിൽ തനിച്ചായിരിക്കുന്നതിനുപകരം അവസാന വരിയുടെ അവസാനം ഒരു മൾട്ടി-ലൈൻ എച്ച്ടിഎംഎൽ (HTML, JSX, Vue, ആംഗുലർ) മൂലകത്തിന്റെ > ഇടുക (സ്വയം അടയ്ക്കുന്ന ഘടകങ്ങൾക്ക് ബാധകമല്ല)",
  "BEAUTIFY_OPTION_SINGLE_ATTRIBUTE_PER_LINE": "എച്ച്ടിഎംഎൽ, ഗ്രിൻസിങ്ങിനടുത്ത് ആൻഡ് ജ്സ്ക്സ ഓരോ വരിയിലും ഒറ്റ ആട്രിബ്യൂട്ട് നടപ്പിലാക്കുക",
  "BEAUTIFY_OPTION_PROSE_WRAP": "അത് മര്ക്ദൊവ്ന് ഫയലുകൾ പ്രിന്റ് വീതി കവിയുന്നു എങ്കിൽ ഗദ്യ പൊതിയുക",
  "BEAUTIFY_OPTION_PRINT_TRAILING_COMMAS": "മൾട്ടി-ലൈൻ കോമ-വേർതിരിച്ച സിന്റാക്റ്റിക് ഘടനകളിൽ സാധ്യമാകുന്നിടത്തെല്ലാം ട്രെയിലിംഗ് കോമകൾ അച്ചടിക്കുക"
});