/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "Типова в системі",
  "PROJECT_BUSY": "Проект виконується",
  "DUPLICATING": "Копіювання {0}",
  "MOVING": "Переміщення {0}",
  "COPYING": "Копіювання {0}",
  "DELETING": "Видалення {0}",
  "DELETE_TO_TRASH": "Переміщення {0} у кошик",
  "DELETE_TO_RECYCLE_BIN": "Переміщення {0} до кошика",
  "RENAMING": "Перейменування",
  "STORED_IN_YOUR_BROWSER": "Зберігається у вашому браузері",
  "SUPPORT_US_OPEN_COLLECTIVE": "Підтримайте нас на спонсорах GitHub",
  "GENERIC_ERROR": "(помилка {0})",
  "NOT_FOUND_ERR": "Файл не знайдено.",
  "NOT_READABLE_ERR": "Не вдається прочитати файл.",
  "EXCEEDS_MAX_FILE_SIZE": "{APP_NAME} не працює з файлами, що перевищують {0} Мб.",
  "NO_MODIFICATION_ALLOWED_ERR": "Не вдається внести зміни до цільової теки.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "Ваших повноважень недостатньо, аби вносити змінити.",
  "CONTENTS_MODIFIED_ERR": "Файл змінено за межами {APP_NAME}.",
  "UNSUPPORTED_ENCODING_ERR": "{APP_NAME} наразі підтримує тільки текстові файли у кодуванні UTF-8.",
  "ENCODE_FILE_FAILED_ERR": "{APP_NAME} не вдалося закодувати вміст файлу.",
  "DECODE_FILE_FAILED_ERR": "{APP_NAME} не вдалося розшифрувати вміст файлу.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "{APP_NAME} наразі не підтримує текстові файли в кодуванні UTF-16.",
  "FILE_EXISTS_ERR": "Файл або така уже існує.",
  "FILE": "файл",
  "FILE_TITLE": "Файл",
  "DIRECTORY": "тека",
  "DIRECTORY_TITLE": "Тека",
  "DIRECTORY_NAMES_LEDE": "Назви тек",
  "FILENAMES_LEDE": "Назви файлів",
  "FILENAME": "Назва файлу",
  "DIRECTORY_NAME": "Назва теки",
  "ERROR_LOADING_PROJECT": "Помилка завантаження проекту",
  "OPEN_DIALOG_ERROR": "Під час показу діалогу відкриття файлу виникла помилка. (помилка {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "Виникла помилка під час спроби відкрити теку <span class='dialog-filename'>{0}</span>. (помилка {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "Виникла помилка під час спроби прочитати вміст теки <span class='dialog-filename'>{0}</span>. (помилка {1})",
  "ZOOM_WITH_SHORTCUTS": "Використовуйте комбінації клавіш для масштабування",
  "ZOOM_WITH_SHORTCUTS_DETAILS": "Будь ласка, використовуйте комбінації клавіш <code><i>{0}</i></code> для збільшення та <code><i>{1}</i></code> для зменшення.",
  "ERROR_OPENING_FILE_TITLE": "Помилка відкриття файлу",
  "ERROR_OPENING_FILE": "Виникла помилка під час спроби відкрити файл <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_OPENING_FILES": "Під час відкриття наступних файлів виникли помилки:",
  "ERROR_RELOADING_FILE_TITLE": "Помилка перевантаження змін з диску",
  "ERROR_RELOADING_FILE": "Сталась помилка під час спроби перевантаження файлу <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_SAVING_FILE_TITLE": "Помилка збереження файлу",
  "ERROR_SAVING_FILE": "Сталась помилка під час спроби збереження файлу <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_FILE_TITLE": "Помилка під час перейменування {0}",
  "ERROR_RENAMING_FILE": "Сталась помилка під час спроби перейменувати файл {2} <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "Файл або каталог не є частиною поточного відкритого проекту. На жаль, на даний момент можна перейменувати лише файли проекту.",
  "ERROR_MOVING_FILE_TITLE": "Помилка переміщення {0}",
  "ERROR_MOVING_FILE": "Під час спроби перемістити {2} <span class='dialog-filename'>{0}</span> сталася помилка. {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "Неможливо перемістити файл/папку, оскільки вони не є частиною поточного проекту.",
  "ERROR_DELETING_FILE_TITLE": "Помилка видалення {0}",
  "ERROR_DELETING_FILE": "Сталась помилка під час проби видалити {2} <span class='dialog-filename'>{0}</span>. {1}",
  "INVALID_FILENAME_TITLE": "Невірна {0}",
  "CANNOT_PASTE_TITLE": "Не вдається вставити {0}",
  "CANNOT_DOWNLOAD_TITLE": "Не вдається завантажити {0}",
  "ERR_TYPE_DOWNLOAD_FAILED": "Сталася помилка під час завантаження <span class='dialog-filename'>{0}</span>",
  "ERR_TYPE_PASTE_FAILED": "Під час вставлення <span class='dialog-filename'>{0}</span> до <span class='dialog-filename'>{1}</span> сталася помилка",
  "CANNOT_DUPLICATE_TITLE": "Неможливо дублювати",
  "ERR_TYPE_DUPLICATE_FAILED": "Під час копіювання <span class='dialog-filename'>{0}</span> сталася помилка",
  "ERR_TYPE_DUPLICATE_FAILED_NO_FILE": "Виберіть файл для копіювання.",
  "INVALID_FILENAME_MESSAGE": "{0} не може містити зарезервованих слів, закінчуватись крапками (.) та використовувати наступні симовли: <code class='emphasized'>{1}</code>",
  "ENTRY_WITH_SAME_NAME_EXISTS": "Файл або тека з назвою <span class='dialog-filename'>{0}</span> уже існує.",
  "ERROR_CREATING_FILE_TITLE": "Помилка створення {0}",
  "ERROR_CREATING_FILE": "Сталась помилка під час спроби створити файл {0} <span class='dialog-filename'>{1}</span>. {2}",
  "ERROR_MIXED_DRAGDROP": "Не можна відкривати теку одночасно відкриваючи інші файли",
  "ERROR_KEYMAP_TITLE": "Не вдалось прочитати карту прив’язок клавіш",
  "ERROR_KEYMAP_CORRUPT": "У вашому файлі помилкова структура JSON. Файли буде відкрито, аби ви могли її виправити.",
  "ERROR_LOADING_KEYMAP": "Ваш файл не у кодуванні UTF-8 і не може бути завантаженим",
  "ERROR_RESTRICTED_COMMANDS": "Ви не можете переприв’язати клавіатурні скорочення для команд: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "Ви не можете переприв’язати ці клавіатурні скорочення: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "Ви переприв’язуєте кілька клавіатурних скорочень для команд: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "У вас кілька прив’язок до цих комбінацій: {0}",
  "ERROR_INVALID_SHORTCUTS": "Це клавіатурне скорочення помилкове: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "Ви назначили клавіатурне скорочення для неіснуючій команді: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "Помилка читання налаштувань",
  "ERROR_PREFS_PROJECT_LINT": "Налаштування проекту",
  "ERROR_PREFS_PROJECT_LINT_MESSAGE": "Помилка: проект містить файли `.brackets.json` і `.phcode.json`, що спричиняє конфлікт. Будь ласка, видаліть `.brackets.json` або `.phcode.json`, а потім перезавантажте проект.",
  "ERROR_PREFS_CORRUPT": "Ваш файл налаштувань не відповідає правилам формату JSON. Файл буде відкрито для виправлення. Після цього потрібно буде перезапустити {APP_NAME}, аби зміни набули чинності.",
  "ERROR_PROJ_PREFS_CORRUPT": "Ваш файл налаштувань проекту недійсний JSON. Файл буде відкрито, щоб ви могли виправити формат. Вам потрібно буде перезавантажити проект, щоб зміни набули чинності.",
  "ERROR_IN_BROWSER_TITLE": "Ой! {APP_NAME} ще не працює у браузерах.",
  "ERROR_IN_BROWSER": "{APP_NAME} створено на базі веб-технологій, але наразі працює як звичайна програма аби мати змогу редагувати локальні файли. Будь ласка, скористайтесь спеціальною оболонкою на <b>github.com/adobe/brackets-shell</b> для запуску {APP_NAME}.",
  "ERROR_MAX_FILES_TITLE": "Помилка індексації файлів",
  "ERROR_MAX_FILES": "Цей проект містить більше 30 000 файлів. Функції, що оперують кількома файлам можуть не працювати правильно або вимкнутись. <a href='https://github.com/adobe/brackets/wiki/Large-Projects'>Дізнайтесь більше про роботу програми під час відкриття великих проектів</a>.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "Помилка запуску браузера",
  "ERROR_CANT_FIND_CHROME": "Не знайдено браузер Google Chrome. Переконайтесь, будь ласка, що він встановлений.",
  "ERROR_LAUNCHING_BROWSER": "Під час запуску браузера сталася помилка. (помилка {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "Помилка Live Preview",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "Підключення до броузера",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "Live Preview потребує перезапустити Chrome з увімкненням віддаленого відлагодження.<br /><br />Бажаєте виконати це?<br /><br />",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "Помилка завантаження сторінки Live Preview.",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "Аби запустити live preview з серверним файлом, вам варто вказати базову адресу для цього проекту.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "Помилка запуску HTTP-сервера для live preview. Будь ласка, спробуйте пізніше.",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "Для докладнішої інформації погляньте на <a href='{0}' title='{0}'>пошук та усунення помилок підключення Live Preview</a>.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "Live Preview",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "Live Preview: Підключення…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "Live Preview: Ініціалізація…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "Активний сервер попереднього перегляду",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "Live Preview",
  "LIVE_DEV_TOOLTIP_SHOW_IN_EDITOR": "{0} - Показати в редакторі…",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "Виберіть «Файл для попереднього перегляду».",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "Перезавантажити сторінку",
  "LIVE_DEV_TOGGLE_LIVE_HIGHLIGHT": "Увімкнути/перемкнути попередній перегляд основних моментів",
  "LIVE_DEV_CLICK_POPOUT": "Попередній перегляд у спливаючому режимі в новому вікні",
  "LIVE_DEV_OPEN_CHROME": "Відкрити в Chrome…",
  "LIVE_DEV_OPEN_SAFARI": "Відкрити в Safari…",
  "LIVE_DEV_OPEN_EDGE": "Відкрити в Edge…",
  "LIVE_DEV_OPEN_FIREFOX": "Відкрити у Firefox…",
  "LIVE_DEV_OPEN_ERROR_TITLE": "Помилка під час відкриття попереднього перегляду в {0}",
  "LIVE_DEV_OPEN_ERROR_MESSAGE": "Переконайтеся, що браузер {0} встановлено, і повторіть спробу.",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "Закріпити або відкріпити сторінку попереднього перегляду",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "Live Preview (не оновлюється, якщо є помилки)",
  "LIVE_DEV_SETTINGS": "Налаштування попереднього перегляду в реальному часі…",
  "LIVE_DEV_SETTINGS_BANNER": "Налаштуйте спеціальний сервер для попереднього перегляду PHP, JSP та інших серверних файлів",
  "LIVE_DEV_SETTINGS_TITLE": "Налаштування попереднього перегляду",
  "LIVE_DEV_SETTINGS_STARTUP": "Показувати панель попереднього перегляду під час запуску",
  "LIVE_DEV_SETTINGS_SERVER_PREFERENCE": "true, щоб увімкнути спеціальний сервер розробки",
  "LIVE_DEV_SETTINGS_STARTUP_PREFERENCE": "true, щоб показувати панель попереднього перегляду в реальному часі під час запуску",
  "LIVE_DEV_SETTINGS_HOT_RELOAD_PREFERENCE": "true, якщо сервер підтримує гаряче перезавантаження та вимикає перезавантаження Live Preview під час збереження",
  "LIVE_DEV_SETTINGS_USE_SERVER": "Використовуйте спеціальний сервер розробки для цього проекту",
  "LIVE_DEV_SETTINGS_SERVE_PREFERENCE": "URL-адреса вашого сервера розробки для проекту, наприклад. http://localhost:8000/php",
  "LIVE_DEV_SETTINGS_SERVER_INBUILT": "напр. http://localhost:8000/php – зараз використовується вбудований сервер.",
  "LIVE_DEV_SETTINGS_SERVER_ROOT": "Обслуговуюча папка в проекті",
  "LIVE_DEV_SETTINGS_SERVER_ROOT_HELP": "напр. www/ (за замовчуванням /)",
  "LIVE_DEV_SETTINGS_SERVER_ROOT_PREF": "Шлях у проекті, який обслуговується сервером розробки, наприклад. www/ (за замовчуванням /)",
  "LIVE_DEV_SETTINGS_RELOAD": "Сервер підтримує гаряче перезавантаження",
  "LIVE_DEV_SETTINGS_RELOAD_HELP": "Деякі сервери підтримують гаряче перезавантаження, коли зміни коду надсилаються на сторінку без повного перезавантаження сторінки.\nУвімкніть цю функцію, якщо не хочете, щоб {APP_NAME} перезавантажувала сторінку під час кожного збереження.",
  "LIVE_DEV_SETTINGS_FRAMEWORK": "Серверна структура",
  "LIVE_DEV_SETTINGS_FRAMEWORK_CUSTOM": "Custom",
  "LIVE_DEV_SETTINGS_FRAMEWORK_PREFERENCES": "Server Framework, наразі підтримує лише docusaurus",
  "LIVE_PREVIEW_CUSTOM_SERVER_BANNER": "Отримання попереднього перегляду з вашого спеціального сервера {0}",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "Live Preview зупинено, оскільки в браузері відкрито панель інструментів розробника",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "Live Preview зупинено, оскільки сторінку закрито в браузері",
  "LIVE_DEV_NAVIGATED_AWAY": "Live Preview зупинено, оскільки браузер перенаправлено на сторінку, що не є частиною поточного проекту",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "Live Preview скасовано з невідомих причин ({0})",
  "SAVE_CLOSE_TITLE": "Зберегти зміни",
  "SAVE_CLOSE_MESSAGE": "Чи бажаєте ви зберегти зміни внесені у файл <span class='dialog-filename'>{0}</span>?",
  "SAVE_CLOSE_MULTI_MESSAGE": "Чи бажаєте ви зберегти зміни до наступних файлів?",
  "EXT_MODIFIED_TITLE": "Зовнішні зміни",
  "CONFIRM_DELETE_TITLE": "Підтвердження видалення",
  "CONFIRM_FILE_DELETE": "Ви впевнені, що бажаєте видалити файл <span class='dialog-filename'>{0}</span> ?",
  "CONFIRM_FOLDER_DELETE": "Ви дійсно хочете видалити теку <span class='dialog-filename'>{0}</span>?",
  "CONFIRM_FILE_DELETE_TRASH": "Ви впевнені, що бажаєте видалити файл <span class='dialog-filename'>{0}</span> ?<br> Ви можете відновити цей файл із кошика.",
  "CONFIRM_FOLDER_DELETE_TRASH": "Ви впевнені, що бажаєте видалити папку <span class='dialog-filename'>{0}</span> ?<br> Ви можете відновити цю папку з кошика.",
  "CONFIRM_FILE_DELETE_RECYCLE_BIN": "Ви впевнені, що бажаєте видалити файл <span class='dialog-filename'>{0}</span> ?<br> Ви можете відновити цей файл із кошика.",
  "CONFIRM_FOLDER_DELETE_RECYCLE_BIN": "Ви впевнені, що бажаєте видалити папку <span class='dialog-filename'>{0}</span> ?<br> Ви можете відновити цю папку з кошика.",
  "MOVE_TO_TRASH": "Перемістити в кошик",
  "MOVE_TO_RECYCLE_BIN": "Перемістити до кошика",
  "FILE_DELETED_TITLE": "Файл видалено",
  "EXT_MODIFIED_WARNING": "<span class='dialog-filename'>{0}</span> змінено на диску.<br /><br />Чи ви хочете зберегти файл і перезаписати ці зміни?",
  "EXT_MODIFIED_MESSAGE": "<span class='dialog-filename'>{0}</span> змінено на диску, проте існують також не збережені зміни у {APP_NAME}.<br /><br />Яку версію ви бажаєте лишити?",
  "EXT_DELETED_MESSAGE": "<span class='dialog-filename'>{0}</span> видалено з диску, але {APP_NAME} містить не збережені в нього зміни.<br /><br />Чи бажаєте ви залишити їх?",
  "EXT_ALWAYS_MODIFIED_BUTTON_TOOLTIP": "Завжди перезаписуйте файли до перемикання проекту або перезапуску",
  "WINDOW_UNLOAD_WARNING": "Ви впевнені, що бажаєте перейти до іншої URL-адреси та залишити {APP_NAME}?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "У вас є незбережені зміни! Ви впевнені, що бажаєте перейти до іншої URL-адреси та залишити {APP_NAME}?",
  "DONE": "Готово",
  "OK": "OK",
  "CANCEL": "Скасувати",
  "DONT_SAVE": "Не зберігати зміни",
  "SAVE": "Зберегти",
  "SAVE_AS": "Зберегти як…",
  "SAVE_AND_OVERWRITE": "Перезаписати",
  "ALWAYS_OVERWRITE": "Завжди перезаписувати",
  "DELETE": "Видалити",
  "BUTTON_YES": "Так",
  "BUTTON_NO": "Ні",
  "FIND_MATCH_INDEX": "{0} з {1}",
  "FIND_NO_RESULTS": "Жодних результатів",
  "FIND_QUERY_PLACEHOLDER": "Хочу знайти…",
  "FIND_HISTORY_MAX_COUNT": "Максимальна кількість елементів пошуку в історії пошуку",
  "REPLACE_PLACEHOLDER": "Замінити на…",
  "BUTTON_REPLACE_ALL": "Усе…",
  "BUTTON_REPLACE_BATCH": "Пакет…",
  "BUTTON_REPLACE_ALL_IN_FILES": "Замінити…",
  "BUTTON_REPLACE": "Замінити",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "Наступний збіг",
  "BUTTON_PREV_HINT": "Попередній збіг",
  "BUTTON_CASESENSITIVE_HINT": "Враховувати регістр",
  "BUTTON_REGEXP_HINT": "Регулярний вираз",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "Замінити без можливості скасування",
  "REPLACE_WITHOUT_UNDO_WARNING": "Оскільки більше {0} файлів потрібно змінити, {APP_NAME} виконає заміну невідкритих файлів безпосередньо на диску.<br />Ви не зможете скасувати цю дію.",
  "BUTTON_REPLACE_WITHOUT_UNDO": "Замінити без можливості скасування",
  "OPEN_FILE": "Відкрити файл",
  "SAVE_FILE_AS": "Зберегти файл",
  "CHOOSE_FOLDER": "Оберіть теку",
  "RELEASE_NOTES": "Примітки до випуску",
  "NO_UPDATE_TITLE": "У вас найновіша версія!",
  "NO_UPDATE_MESSAGE": "Ви користуєтесь останньою версією {APP_NAME}.",
  "FIND_REPLACE_TITLE_LABEL": "Замінити",
  "FIND_REPLACE_TITLE_WITH": "на",
  "FIND_TITLE_LABEL": "Знайдене",
  "FIND_TITLE_SUMMARY": "&mdash; {0} {1} {2} у {3}",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "у <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_NO_SCOPE": "у проекті",
  "FIND_IN_FILES_PROJECT_SCOPE": "Знайти в проекті",
  "FIND_IN_FILES_PROJECT_SCOPE_FILTER": "Знайти в {0}",
  "FIND_IN_FILES_PROJECT_SCOPE_REPLACE": "Замінити в проекті",
  "FIND_IN_FILES_PROJECT_SCOPE_REPLACE_FILTER": "Замінити в {0}",
  "FIND_IN_FILES_ZERO_FILES": "Фільтр не включає всі файли {0}",
  "FIND_IN_FILES_FILE": "файл",
  "FIND_IN_FILES_FILES": "файлів",
  "FIND_IN_FILES_MATCH": "збіг",
  "FIND_IN_FILES_MATCHES": "збігів",
  "FIND_IN_FILES_MORE_THAN": "Більше ",
  "FIND_IN_FILES_PAGING": "{0}&mdash;{1}",
  "FIND_IN_FILES_FILE_PATH": "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "Ctrl/Cmd+клік згорнути/розгорнути все",
  "FIND_IN_FILES_INDEXING": "Індексування для миттєвого пошуку…",
  "FIND_IN_FILES_SEARCHING": "Пошук файлів…",
  "FIND_IN_FILES_SEARCHING_IN": "У {0}",
  "FIND_IN_FILES_INDEXING_PROGRESS": "Індексація {0} із {1} файлів для миттєвого пошуку…",
  "REPLACE_IN_FILES_ERRORS_TITLE": "Помилки під час заміни",
  "REPLACE_IN_FILES_ERRORS": "Наступні файли не змінено, оскільки вони змінились після пошуку аби недоступні для запису.",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "Сталась помилка під час отримання даних про оновлення",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "Помилка отримання з сервера інформації про оновлення. Переконайтесь, що маєте доступ до інтернету та спробуйте знову.",
  "NEW_FILE_FILTER": "Новий набір виключень…",
  "CLEAR_FILE_FILTER": "Не виключати файли",
  "NO_FILE_FILTER": "Жодного файлу не виключено",
  "EXCLUDE_FILE_FILTER": "Виключити файли",
  "INCLUDE_FILE_FILTER": "Пошук у файлах",
  "FILTER_PLACEHOLDER": "напр. index,.css,*.js,src/**/*.css",
  "FILTER_HISTORY_TOOLTIP": "Натисніть `Ctrl-Пробіл`, щоб переглянути історію.",
  "FILTER_HISTORY_TOOLTIP_MAC": "Натисніть `Cmd-Пробіл`, щоб переглянути історію.",
  "FIND_HISTORY_TOOLTIP": "Натисніть `Ctrl-Пробіл`, щоб переглянути історію.",
  "FIND_HISTORY_TOOLTIP_MAC": "Натисніть `Cmd-Пробіл`, щоб переглянути історію.",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "Швидке редагування не доступне для поточного розміщення курсора",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "Швидке редагування CSS: помістіть курсор на один клас",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "Швидке редагування CSS: атрибут класу незавершено",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "Швидке редагування CSS: атрибут ID незавершено",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "Швидке редагування CSS: помістіть курсор на мітку, клас або ID",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "Швидке редагування часової функції CSS: невірний синтаксис",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "Швидке редагування JS: помістіть курсор на назву функції",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "Для поточного розміщення курсора швидка документація відсутня",
  "PROJECT_LOADING": "Завантаження…",
  "UNTITLED": "Без-назви",
  "WORKING_FILES": "Робочі файли",
  "TOP": "Верхня",
  "BOTTOM": "Нижня",
  "LEFT": "Ліва",
  "RIGHT": "Права",
  "CMD_SPLITVIEW_NONE": "Не розділяти",
  "CMD_SPLITVIEW_VERTICAL": "Вертикальне розділення",
  "CMD_SPLITVIEW_HORIZONTAL": "Горизонтальне розділення",
  "SPLITVIEW_MENU_TOOLTIP": "Розділити редактор горизонтально або вертикально",
  "GEAR_MENU_TOOLTIP": "Налаштувати робочий набір",
  "SPLITVIEW_INFO_TITLE": "Уже відкрито",
  "SPLITVIEW_MULTIPANE_WARNING": "Цей файл відкрито в іншій панелі. {APP_NAME} незабаром підтримуватиме відкриття файлу в кількох панелях одночасно. А до того часу, файл буде показуватись у тій панелі, у якій уже відкритий.<br /><br />(Ви більше не бачитимете цього повідомлення.)",
  "KEYBOARD_OVERLAY_TEXT": "Використовуйте стрілки для навігації або вводьте для вибору елементів інтерфейсу.",
  "KEYBOARD_SHORTCUT_CHANGE_TITLE": "Змінити комбінацію клавіш…",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_TITLE": "Змінити комбінацію клавіш",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_TEXT": "Натисніть нову комбінацію клавіш для <b>&quot;{0}&quot;</b> (Поточний: <b>{1}</b> )",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_DUPLICATE": "Попередження: комбінацію клавіш <b>{0}</b> уже призначено для <b>«{1}»</b> . Перепризначити <b>&#39;{2}&#39;</b> ?",
  "KEYBOARD_SHORTCUT_ASSIGN": "Призначити",
  "KEYBOARD_SHORTCUT_NONE": "Жодного",
  "KEYBOARD_SHORTCUT_MENU_SHOW_SHORTCUTS": "Гарячі клавіши…",
  "KEYBOARD_SHORTCUT_MENU_SHOW_SHORTCUTS_BUTTON": "Показати всі ярлики…",
  "KEYBOARD_SHORTCUT_TABLE_BASE_KEY": "Базовий ключ",
  "KEYBOARD_SHORTCUT_TABLE_KEY_BINDING": "Ярлик",
  "KEYBOARD_SHORTCUT_TABLE_COMMAND_ID": "ID команди",
  "KEYBOARD_SHORTCUT_TABLE_COMMAND_NAME": "Команда",
  "KEYBOARD_SHORTCUT_TABLE_DOUBLE_CLICK": "Двічі клацніть, щоб змінити ярлик",
  "KEYBOARD_SHORTCUT_TABLE_ORIGIN": "Походження",
  "KEYBOARD_SHORTCUT_ORIG_EXTENSION": "Розширення",
  "KEYBOARD_SHORTCUT_PANEL_TITLE": "Гарячі клавіши",
  "KEYBOARD_SHORTCUT_PANEL_FILTER": "Фільтр&hellip;",
  "KEYBOARD_SHORTCUT_PANEL_RESET": "Скинути…",
  "KEYBOARD_SHORTCUT_PANEL_RESET_DEFAULT": "Відновити ярлики за замовчуванням…",
  "KEYBOARD_SHORTCUT_RESET_DIALOG_TITLE": "Скинути комбінації клавіш",
  "KEYBOARD_SHORTCUT_RESET_DIALOG_MESSAGE": "Відновити всі спеціальні ярлики до стандартних? Це не може бути скасоване.",
  "STATUSBAR_CURSOR_POSITION": "Рядок {0}, Стовпець {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": "— Обрано {0} стовпець",
  "STATUSBAR_SELECTION_CH_PLURAL": "— Обрано {0} стовпців",
  "STATUSBAR_SELECTION_LINE_SINGULAR": "— Обрано {0} рядок",
  "STATUSBAR_SELECTION_LINE_PLURAL": "— Обрано {0} рядків",
  "STATUSBAR_SELECTION_MULTIPLE": "— обрано {0}",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "Натисніть, аби перемкнути відступи а пробіли",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "Натисніть, аби перемкнути відступи а ьаби",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "Натисніть, аби змінити кількість пробілів для відступів",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "Натисніть, аби змінити ширину символа вкладки",
  "STATUSBAR_SPACES": "Пробіли:",
  "STATUSBAR_TAB_SIZE": "Розмір вкладки:",
  "STATUSBAR_LINE_COUNT_SINGULAR": "— {0} Рядок",
  "STATUSBAR_LINE_COUNT_PLURAL": "— {0} Рядків",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "Розширення вимкнено",
  "STATUSBAR_INSERT": "ВСТ",
  "STATUSBAR_OVERWRITE": "ПРЗ",
  "STATUSBAR_INSOVR_TOOLTIP": "Натисніть, аби перемкнути режим курсору між вставкою (ВСТ) та перезаписом (ПРЗ)",
  "STATUSBAR_LANG_TOOLTIP": "Натисніть, аби змінити тип файлу",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. Натисніть, аби перемкнути панель повідомлень.",
  "STATUSBAR_DEFAULT_LANG": "(типово)",
  "STATUSBAR_SET_DEFAULT_LANG": "Встановити типовим для файлів .{0}",
  "STATUSBAR_ENCODING_TOOLTIP": "Виберіть кодування",
  "STATUSBAR_TASKS": "завдання",
  "STATUSBAR_TASKS_TOOLTIP": "Керуйте активними завданнями",
  "STATUSBAR_TASKS_HIDE_SPINNER": "Приховати піктограму Spinner",
  "STATUSBAR_TASKS_UNKNOWN_EXTENSION_TASK": "Невідоме завдання розширення…",
  "STATUSBAR_TASKS_PLAY": "Почати або Відновити",
  "STATUSBAR_TASKS_PAUSE": "Пауза",
  "STATUSBAR_TASKS_STOP": "СТІЙ",
  "STATUSBAR_TASKS_RESTART": "Перезапустіть",
  "ERRORS_NO_FILE": "Файл не відкрито",
  "ERRORS_PANEL_TITLE_MULTIPLE": "{0} Проблеми - {1}",
  "ERRORS_PANEL_TITLE_MULTIPLE_FIXABLE": "{0} Проблеми, {1} Виправні - {2}",
  "SINGLE_ERROR": "1 {0} Проблема - {1}",
  "SINGLE_ERROR_FIXABLE": "1 {0} Проблема, {1} Виправна - {2}",
  "MULTIPLE_ERRORS": "{0} {1} Проблеми - {2}",
  "MULTIPLE_ERRORS_FIXABLE": "{0} {1} Проблеми, {2} Виправні - {3}",
  "NO_ERRORS": "Не знайдено жодної помилки {0} – гарна робота!",
  "NO_ERRORS_MULTIPLE_PROVIDER": "Не знайдено жодної помилки – гарна робота!",
  "LINT_DISABLED": "Аналіз вимкнено",
  "NO_LINT_AVAILABLE": "Для {0} відсутній аналізатор",
  "NOTHING_TO_LINT": "Нічого аналізувати",
  "COPY_ERROR": "Проблема копіювання",
  "FIX": "Виправити",
  "CANNOT_FIX_TITLE": "Не вдалося застосувати виправлення",
  "CANNOT_FIX_SOME_TITLE": "Не вдалося застосувати деякі виправлення",
  "CANNOT_FIX_MESSAGE": "Документ було змінено після підготовки виправлення. Будь ласка спробуйте ще раз.",
  "LINTER_TIMED_OUT": "Аналізатором {0} перевищено час очікування у {1} мс",
  "LINTER_FAILED": "Аналізатор {0} завершився з помилкою: {1}",
  "CLICK_VIEW_PROBLEM": "Натисніть, щоб переглянути проблему на панелі",
  "FILE_MENU": "Файл",
  "CMD_FILE_NEW_UNTITLED": "Новий",
  "CMD_FILE_NEW": "Новий файл",
  "CMD_FILE_DUPLICATE": "Дублювати",
  "CMD_FILE_DUPLICATE_FILE": "Дублікат файлу",
  "CMD_FILE_DOWNLOAD_PROJECT": "Завантажити проект",
  "CMD_FILE_DOWNLOAD": "Завантажити",
  "CMD_FILE_CUT": "Вирізати",
  "CMD_FILE_COPY": "Копіювати",
  "CMD_FILE_COPY_PATH": "Копіювати шлях",
  "CMD_FILE_PASTE": "Вставити",
  "CMD_PROJECT_NEW": "Новий проект…",
  "CMD_FILE_NEW_FOLDER": "Нова тека",
  "CMD_FILE_OPEN": "Відкрити файли…",
  "CMD_RECENT_FILES_OPEN": "Останні файли…",
  "CMD_ADD_TO_WORKING_SET": "Відкрити у робочому наборі",
  "CMD_OPEN_DROPPED_FILES": "Відкрити вкинуті файли",
  "CMD_OPEN_FOLDER": "Відкрити теку…",
  "CMD_FILE_CLOSE": "Закрити",
  "CMD_FILE_CLOSE_ALL": "Закрити все",
  "CMD_FILE_CLOSE_LIST": "Закрити список",
  "CMD_FILE_CLOSE_OTHERS": "Закрити інші",
  "CMD_FILE_CLOSE_ABOVE": "Закрити інші ті що вище",
  "CMD_FILE_CLOSE_BELOW": "Закрити інші ті що нижче",
  "CMD_FILE_SAVE": "Зберегти файл",
  "CMD_FILE_SAVE_ALL": "Зберегти все",
  "CMD_FILE_SAVE_AS": "Зберегти як…",
  "CMD_LIVE_FILE_PREVIEW": "Live Preview",
  "CMD_LIVE_FILE_PREVIEW_SETTINGS": "Налаштування попереднього перегляду",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "Увімкнути експериментальний попередній перегляд",
  "CMD_RELOAD_LIVE_PREVIEW": "Примусово перезапустити Live Preview",
  "CMD_PROJECT_SETTINGS": "Налаштування проекту…",
  "CMD_FILE_RENAME": "Перейменувати",
  "CMD_FILE_DELETE": "Видалити",
  "CMD_INSTALL_EXTENSION": "Встановити розширення…",
  "CMD_EXTENSION_MANAGER": "Менеджер розширень…",
  "CMD_FILE_REFRESH": "Оновити дерево файлів",
  "CMD_FILE_SHOW_FOLDERS_FIRST": "Спочатку відсортуйте папки",
  "CMD_QUIT": "Покинути програму",
  "CMD_EXIT": "Вийти",
  "EDIT_MENU": "Змінити",
  "CMD_UNDO": "Відмінити",
  "CMD_REDO": "Повторити",
  "CMD_CUT": "Вирізати",
  "CMD_COPY": "Копіювати",
  "CMD_PASTE": "Вставити",
  "CMD_SELECT_ALL": "Обрати все",
  "CMD_SELECT_LINE": "Обрати рядок",
  "CMD_SPLIT_SEL_INTO_LINES": "Розбити виділене на рядки",
  "CMD_ADD_CUR_TO_NEXT_LINE": "Додати курсор на наступний рядок",
  "CMD_ADD_CUR_TO_PREV_LINE": "Додати курсор на попередній рядок рядок",
  "CMD_INDENT": "Зробити відступ",
  "CMD_UNINDENT": "Забрати відступ",
  "CMD_DUPLICATE": "Дублювати",
  "CMD_DELETE_LINES": "Вилучити рядок",
  "CMD_COMMENT": "Перемкнути рядковий коментар",
  "CMD_BLOCK_COMMENT": "Перемкнути блочний коментар",
  "CMD_LINE_UP": "Перемістити рядок угору",
  "CMD_LINE_DOWN": "Перемісти рядок униз",
  "CMD_OPEN_LINE_ABOVE": "Відкрити рядок вище",
  "CMD_OPEN_LINE_BELOW": "Відкрити рядок нижче",
  "CMD_TOGGLE_CLOSE_BRACKETS": "Автозакривання дужок",
  "CMD_SHOW_CODE_HINTS": "Показувати поради до коду",
  "CMD_BEAUTIFY_CODE": "Прикрасити код",
  "CMD_BEAUTIFY_CODE_ON_SAVE": "Прикрасьте код після збереження",
  "FIND_MENU": "Знайти",
  "CMD_FIND": "Знайти",
  "CMD_FIND_NEXT": "Знайти наступний",
  "CMD_FIND_PREVIOUS": "Знайти попередній",
  "CMD_FIND_ALL_AND_SELECT": "Виберіть Усі випадки",
  "CMD_ADD_NEXT_MATCH": "Додати наступне повторення",
  "CMD_SKIP_CURRENT_MATCH": "Пропустити та додати наступне повторення",
  "CMD_FIND_IN_FILES": "Знайти у файлах",
  "CMD_FIND_IN_SUBTREE": "Знайти у…",
  "CMD_REPLACE": "Замінити",
  "CMD_REPLACE_IN_FILES": "Замінити у файлах",
  "CMD_REPLACE_IN_SUBTREE": "Замінити…",
  "VIEW_MENU": "Вигляд",
  "CMD_HIDE_SIDEBAR": "Приховати бокову панель",
  "CMD_SHOW_SIDEBAR": "Показати бокову панель",
  "CMD_TOGGLE_SIDEBAR": "Перемкнути бічну панель",
  "CMD_TOGGLE_PANELS": "Перемикати панелі",
  "CMD_TOGGLE_PURE_CODE": "Ніяких відволікань",
  "CMD_TOGGLE_FULLSCREEN": "Повноекранний",
  "CMD_ZOOM_UI": "Zoom UI та шрифти",
  "CMD_ZOOM_IN": "Збільшувати",
  "CMD_ZOOM_IN_SCALE": "Збільшення (поточне: {0}%)",
  "CMD_ZOOM_OUT": "Зменшення",
  "CMD_INCREASE_FONT_SIZE": "Збільшити розмір шрифту",
  "CMD_DECREASE_FONT_SIZE": "Зменшити розмір шрифту",
  "CMD_RESTORE_FONT_SIZE": "Відновити типовий шрифт",
  "CMD_SCROLL_LINE_UP": "Прокрутити на рядок вгору",
  "CMD_SCROLL_LINE_DOWN": "Прокрутити на рядок вниз",
  "CMD_TOGGLE_LINE_NUMBERS": "Номери рядків",
  "CMD_TOGGLE_ACTIVE_LINE": "Підсвічувати активний рядок",
  "CMD_TOGGLE_WORD_WRAP": "Перенесення слів",
  "CMD_LIVE_HIGHLIGHT": "Виділяти у Live Preview",
  "CMD_VIEW_TOGGLE_INSPECTION": "Аналізувати файли під час збереження",
  "CMD_WORKINGSET_SORT_BY_ADDED": "Впорядкувати за додаванням",
  "CMD_WORKINGSET_SORT_BY_NAME": "Впорядкувати за назвою",
  "CMD_WORKINGSET_SORT_BY_TYPE": "Впорядкувати за типом",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "Автоматичне впорядкування",
  "CMD_THEMES": "Теми…",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "Автоматично закрити пошук",
  "CMD_TOGGLE_RULERS": "Лінійки",
  "CMD_KEYBOARD_NAV_OVERLAY": "Візуальна палітра команд",
  "NAVIGATE_MENU": "Навігація",
  "CMD_QUICK_OPEN": "Швидке відкриття",
  "CMD_GOTO_LINE": "Перейти до рядка",
  "CMD_GOTO_DEFINITION": "Швидкий пошук оголошення",
  "CMD_GOTO_DEFINITION_PROJECT": "Визначення швидкого пошуку в проекті",
  "CMD_GOTO_FIRST_PROBLEM": "Перейти до найближчої помилки",
  "CMD_TOGGLE_QUICK_EDIT": "Швидке редагування",
  "CMD_TOGGLE_QUICK_DOCS": "Швидка документація",
  "CMD_QUICK_EDIT_PREV_MATCH": "Попередній елемент швидкого редагування",
  "CMD_QUICK_EDIT_NEXT_MATCH": "Наступний елемент швидкого редагування",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "Нове правило",
  "CMD_NEXT_DOC": "Наступний документ",
  "CMD_PREV_DOC": "Попередній документ",
  "CMD_NAVIGATE_BACKWARD": "Перейти назад",
  "CMD_NAVIGATE_FORWARD": "Перейти вперед",
  "CMD_NEXT_DOC_LIST_ORDER": "Наступний документ у списку",
  "CMD_PREV_DOC_LIST_ORDER": "Попередній документ у списку",
  "CMD_SHOW_IN_TREE": "Показати у дереві файлів",
  "CMD_SHOW_IN_EXPLORER": "Показати у провіднику",
  "CMD_SHOW_IN_FINDER": "Показати у Finder",
  "CMD_SHOW_IN_OS": "Показати у файлах ОС",
  "CMD_SWITCH_PANE_FOCUS": "Переключити фокус панелі",
  "CMD_OPEN_VFS": "Відкрийте віртуальну файлову систему",
  "CMD_DIAGNOSTIC_TOOLS": "Інструменти діагностики {APP_NAME}",
  "CMD_OPEN_EXTENSIONS_FOLDER": "Відкрити папку розширень…",
  "CMD_OPEN_VIRTUAL_SERVER": "Відкрийте віртуальний сервер",
  "HELP_MENU": "Допомога",
  "CMD_CHECK_FOR_UPDATE": "Перевірити наявність оновлень…",
  "CMD_AUTO_UPDATE": "Автоматичне оновлення",
  "CMD_HOW_TO_USE_BRACKETS": "Як використовувати {APP_NAME}",
  "CMD_SUPPORT": "Підтримка {APP_NAME}",
  "CMD_DOCS": "Допомога, початок роботи",
  "CMD_SUGGEST": "Запропонувати ідею",
  "CMD_RELEASE_NOTES": "Примітки до випуску",
  "CMD_GET_INVOLVED": "Прийняти участь в розробці",
  "CMD_SHOW_EXTENSIONS_FOLDER": "Показати теку розширень",
  "CMD_HEALTH_DATA_STATISTICS": "Звіт про стан здоров’я…",
  "CMD_HOMEPAGE": "Завантажити програми – домашня сторінка",
  "CMD_TWITTER": "{TWITTER_NAME} у Twitter",
  "CMD_YOUTUBE": "Канал Youtube",
  "CMD_ABOUT": "Про {APP_TITLE}",
  "CMD_OPEN_PREFERENCES": "Відкрити файл налаштувань",
  "CMD_OPEN_KEYMAP": "Відкрийте файл картки ключів користувача",
  "EXPERIMENTAL_BUILD": "експериментальна збірка",
  "RELEASE_BUILD": "збірка",
  "DEVELOPMENT_BUILD": "тестова збірка",
  "PRERELEASE_BUILD": "попередня збірка",
  "RELOAD_FROM_DISK": "Завантажити з диска",
  "KEEP_CHANGES_IN_EDITOR": "Залишити зміни в редакторі",
  "CLOSE_DONT_SAVE": "Закрити (без збереження)",
  "RELAUNCH_CHROME": "Перезапустити Chrome",
  "ABOUT": "Про програму",
  "CLOSE": "Закрити",
  "ABOUT_TEXT_LINE1": "Випуск {VERSION_MAJOR}.{VERSION_MINOR} {BUILD_TYPE} {VERSION}",
  "ABOUT_TEXT_BUILD_TIMESTAMP": "час створення:",
  "ABOUT_RELEASE_CREDITS": "Кредити випуску:",
  "ABOUT_TEXT_LINE3": "Бібліотеки сторонніх розробників, якими ми користуємося – <a href='https://github.com/phcode-dev/phoenix/tree/main/src/thirdparty/licences'>Ліцензії та посилання</a> .",
  "ABOUT_TEXT_LINE4": "Документація та джерело на <a href='https://github.com/phcode-dev/phoenix/'>https://github.com/phcode-dev/phoenix/</a>",
  "ABOUT_TEXT_LINE5": "Створено за допомогою ❤ і JavaScript:",
  "ABOUT_TEXT_LINE6": "Багато людей (але ми зараз маємо проблеми із завантаженням цих даних).",
  "ABOUT_TEXT_MDN_DOCS": "Документація та логотип MDN Docs поширюється на умовах ліцензії Creative Commons Attribution, <a href='{MDN_DOCS_LICENSE}'>CC-BY-SA 2.5 Unported</a>.",
  "UPDATE_NOTIFICATION_TOOLTIP": "Доступна нова збірка {APP_NAME}! Натисніть тут аби дізнатись деталі.",
  "UPDATE_NOT_AVAILABLE_TITLE": "{APP_NAME} оновлено",
  "UPDATE_UP_TO_DATE": "Ваша версія {APP_NAME} остання!",
  "UPDATE_AVAILABLE_TITLE": "Доступне оновлення",
  "UPDATE_WHATS_NEW": "Що нового в {APP_NAME}",
  "UPDATE_READY_RESTART_TITLE": "Перезапустіть додаток, щоб оновити",
  "UPDATE_READY_RESTART_INSTALL_MESSAGE": "{APP_NAME} буде оновлено автоматично, коли ви закриєте всі відкриті вікна.",
  "UPDATE_FAILED_TITLE": "Не вдалося оновити",
  "UPDATE_INSTALLING": "Встановлення оновлення…",
  "UPDATE_INSTALLING_MESSAGE": "Триває встановлення оновлення: {APP_NAME} зараз встановлює останні оновлення. Програма автоматично закриється після завершення встановлення.",
  "UPDATE_FAILED_MESSAGE": "Закрийте всі вікна програми {APP_NAME} і знову відкрийте програму, щоб повторити спробу оновлення.<br/> Ви також можете встановити оновлення, завантаживши програму встановлення з <a href='https://phcode.io'>phcode.io</a>",
  "UPDATE_FAILED_VISIT_SITE_MESSAGE": "Щоб повторити спробу, закрийте всі екземпляри {APP_NAME} і перезапустіть програму.<br> Невдовзі ви перейдете на нашу сторінку завантаження, де ви зможете вручну завантажити останню версію.",
  "UPDATE_MESSAGE": "Агов! Доступна нова збірка {APP_NAME}. Ось кілька функцій, що з’явилися:",
  "GET_IT_NOW": "Забрати негайно!",
  "UPDATE_ON_EXIT": "Оновлення при виході",
  "UPDATE_LATER": "Нагадай мені пізніше",
  "UPDATE_DONE": "Перезапустіть, щоб оновити {APP_NAME}",
  "UPDATE_RESTART_INSTALL": "Перезапустіть, щоб інсталювати оновлення",
  "UPDATE_DOWNLOADING": "Завантаження інсталятора",
  "INSTALL_WEBAPP": "Установіть {APP_NAME} на свій пристрій",
  "UPDATE_DOWNLOAD_PROGRESS": "Завантаження – {0} із {1} Мб",
  "UPDATING_APP": "Оновлення {APP_NAME}",
  "UPDATING_APP_MESSAGE": "Це може зайняти деякий час",
  "UPDATING_APP_DIALOG_MESSAGE": "Виконується оновлення. Ви можете продовжувати використовувати {APP_NAME}, поки ми оновимо його.",
  "PROJECT_SETTINGS_TITLE": "Налаштування проекту для: {0}",
  "PROJECT_SETTING_BASE_URL": "Базова адреса Live Preview",
  "PROJECT_SETTING_BASE_URL_HINT": "Уведіть URL кшталту http://localhost:8000/, аби користуватись локальним сервером",
  "BASEURL_ERROR_INVALID_PROTOCOL": "Протокол {0} не підтримується Preview&mdash;будь ласка, використовуйте http: або https: .",
  "BASEURL_ERROR_SEARCH_DISALLOWED": "Базова адреса не може містити параметри пошуку, кшталту \"{0}\".",
  "BASEURL_ERROR_HASH_DISALLOWED": "Базова адреса не може містити хеші кшталту \"{0}\".",
  "BASEURL_ERROR_INVALID_CHAR": "Спеціальні символи, кшталту '{0}', мають бути з обох боків заключені у %.",
  "BASEURL_ERROR_UNKNOWN_ERROR": "Неочікувана помилка розбору базової адреси",
  "EMPTY_VIEW_HEADER": "<em>Відкрийте файл, поки ця панель у фокусі</em>",
  "FLIPVIEW_BTN_TOOLTIP": "Переверніть цей вигляд на панель {0}",
  "CURRENT_THEME": "Поточна тема",
  "USE_THEME_SCROLLBARS": "Брати панель прокрутки з теми",
  "FONT_SIZE": "Розмір шрифту",
  "FONT_FAMILY": "Сімейство шрифтів",
  "THEMES_SETTINGS": "Налаштування тем",
  "THEMES_ERROR": "Помилка теми",
  "THEMES_ERROR_CANNOT_APPLY": "Не вдалося застосувати тему через помилку.",
  "BUTTON_NEW_RULE": "Нове правило",
  "INSTALL": "Встановити",
  "APPLY": "Застосувати",
  "UPDATE": "Оновити",
  "REMOVE": "Вилучити",
  "DISABLE": "Вимкнути",
  "ENABLE": "Увімкнути",
  "OVERWRITE": "Перезаписати",
  "CANT_DROP_ZIP": "Незабаром буде підтримуватися видалення файлів zip...",
  "CANT_REMOVE_DEV": "Розширення у теці \"dev\" потрібно видалити власноруч.",
  "CANT_UPDATE": "Оновлення не сумісне з цією версією {APP_NAME}.",
  "CANT_UPDATE_DEV": "Розширення у теці \"dev\" не можуть автоматично оновлюватись.",
  "INSTALL_EXTENSION_TITLE": "Встановлення розширень",
  "UPDATE_EXTENSION_TITLE": "Оновити розширення",
  "INSTALL_EXTENSION_LABEL": "URL розширення",
  "INSTALL_EXTENSION_HINT": "Посилання на zip-файл розширення або репозитарій GitHub",
  "INSTALLING_FROM": "Встановлення розширення з {0}…",
  "INSTALL_SUCCEEDED": "Встановлення вдалося!",
  "INSTALL_FAILED": "Встановлення не вдалося.",
  "CANCELING_INSTALL": "Скасування…",
  "CANCELING_HUNG": "Скасування встановлення займає багато часу. Схоже, на виникнення внутрішньої помилки.",
  "INSTALL_CANCELED": "Встановлення скасовано.",
  "VIEW_COMPLETE_DESCRIPTION": "Переглянути весь опис",
  "VIEW_TRUNCATED_DESCRIPTION": "Переглянути короткий опис",
  "SORT_EXTENSION_METHOD": "Сортуйте розширення за допомогою downloadCount або publishedDate",
  "INVALID_ZIP_FILE": "Завантажені дані не є zip-архівом.",
  "MISSING_PACKAGE_JSON": "У пакеті немає файлу package.json.",
  "INVALID_PACKAGE_JSON": "Файл package.json – помилковий (помилка: {0}).",
  "MISSING_PACKAGE_NAME": "Файл package.json не містить назви пакунку.",
  "BAD_PACKAGE_NAME": "{0} – помилкова назва пакунку.",
  "MISSING_PACKAGE_VERSION": "Файл package.json не містить версії пакунку.",
  "INVALID_VERSION_NUMBER": "Номер версії пакунку ({0}) – помилковий.",
  "INVALID_BRACKETS_VERSION": "У {APP_NAME} рядок сумісності ({0}) – помилковий.",
  "DISALLOWED_WORDS": "Слова ({1}) недозволені у полі {0}.",
  "NPM_INSTALL_FAILED": "Помилка встановлення команди npm: {0}",
  "API_NOT_COMPATIBLE": "Розширення не сумісне з цією версією {APP_NAME}. Його встановлено до теки disabled.",
  "MISSING_MAIN": "Пакунок не містить файлу main.js.",
  "EXTENSION_ALREADY_INSTALLED": "Встановлення цього пакунка перезапише попередньо встановлене розширення. Ви впевнені?",
  "EXTENSION_SAME_VERSION": "Пакунок має ту ж версію що й наразі встановлена. Перезаписати?",
  "EXTENSION_OLDER_VERSION": "Версія пакунка {0} старіша ніж наразі встановлена ({1}). Перезаписати?",
  "DOWNLOAD_ID_IN_USE": "Внутрішня помилка: ID завантаження уже використовується.",
  "NO_SERVER_RESPONSE": "Не вдалось приєднатися до сервера.",
  "BAD_HTTP_STATUS": "Файл відсутній на сервері (HTTP {0}).",
  "CANNOT_WRITE_TEMP": "Помилка запису тимчасового файлу.",
  "ERROR_LOADING": "Розширення несподівано викликало помилку під час запуску.",
  "MALFORMED_URL": "Адреса недійсна. Перевірте, будь ласка, чи ви все вказали вірно.",
  "UNSUPPORTED_PROTOCOL": "Адреса має бути на протоколі http або https.",
  "UNKNOWN_ERROR": "Невідома внутрішня помилка.",
  "EXTENSION_VERIFIED_PUBLISHER": "Цей видавець підтвердив право власності на {0}",
  "EXTENSION_VERIFIED_SORT": "Перевірено",
  "EXTENSION_STAR": "зірка",
  "EXTENSION_STAR_SORT": "Зірковий рейтинг",
  "EXTENSION_MANAGER_TITLE": "Менеджер розширень",
  "EXTENSION_MANAGER_ERROR_LOAD": "Помилка отримання доступу до реєстру розширення. Будь ласка, спробуйте пізніше.",
  "EXTENSION_UPDATE_RESTART_TITLE": "Перезапустіть для оновлення",
  "EXTENSION_UPDATE_RESTART_MESSAGE": "Щоб завантажити оновлені розширення, закрийте всі запущені екземпляри {APP_NAME} і перезапустіть програму.",
  "INSTALL_EXTENSION_DRAG": "Перетягніть сюди .zip або",
  "INSTALL_EXTENSION_DROP": "Перетягніть .zip для встановлення",
  "INSTALL_EXTENSION_DROP_ERROR": "Встановлення/оновлення скасовано через наступні помилки:",
  "INSTALL_FROM_URL": "встановіть з URL…",
  "INSTALL_EXTENSION_VALIDATING": "Перевірка…",
  "EXTENSION_AUTHOR": "Автор",
  "EXTENSION_DATE": "Дата",
  "EXTENSION_INCOMPATIBLE_NEWER": "Це розширення потребує новішої версії {APP_NAME}.",
  "EXTENSION_INCOMPATIBLE_OLDER": "Наразі це розширення працює зі старішими версіями {APP_NAME}.",
  "EXTENSION_DEFAULT_FEATURE_PRESENT": "Можливо, це розширення вам не знадобиться. {APP_NAME} уже має цю функцію.",
  "EXTENSION_LATEST_INCOMPATIBLE_NEWER": "Версія {0} цього розширення потребує новішої версії {APP_NAME}. Як варіант, ви можете встановити новішу версію {1}.",
  "EXTENSION_LATEST_INCOMPATIBLE_OLDER": "Версія {0} цього розширення працює тільки зі старішими версіями {APP_NAME}. Як варіант, ви можете встановити новішу версію {1}.",
  "EXTENSION_NO_DESCRIPTION": "Опис відсутній",
  "EXTENSION_MORE_INFO": "Докладніше...",
  "EXTENSION_ERROR": "Помилка розширення",
  "EXTENSION_KEYWORDS": "Ключові слова",
  "EXTENSION_TRANSLATED_USER_LANG": "Перекладено {0} мовами, включаючи вашу",
  "EXTENSION_TRANSLATED_GENERAL": "Перекладено {0} мовами",
  "EXTENSION_TRANSLATED_LANGS": "Це розширення перекладено наступними мовами: {0}",
  "EXTENSION_INSTALLED": "Встановлені",
  "EXTENSION_UPDATE_INSTALLED": "Оновлення розширення завантажено і буде встановлено після перевантаження {APP_NAME}.",
  "EXTENSION_SEARCH_PLACEHOLDER": "Пошук",
  "EXTENSION_MORE_INFO_LINK": "Більше",
  "EXTENSION_MANAGER_CREATE_EXTENSION": "+ Створити розширення",
  "EXTENSION_MANAGER_CREATE_THEME": "+ Створити тему",
  "BROWSE_EXTENSIONS": "Переглянути розширення",
  "EXTENSION_MANAGER_REMOVE": "Вилучити розшмрення",
  "EXTENSION_MANAGER_REMOVE_ERROR": "Не вдалось вилучити одне або кілька розширень: {0}. {APP_NAME} продовжить перезапуск.",
  "EXTENSION_MANAGER_UPDATE": "Оновити розширення",
  "EXTENSION_MANAGER_UPDATE_ERROR": "Не вдалось оновити одне або кілька розширень: {0}. {APP_NAME} продовжить перезапуск.",
  "EXTENSION_MANAGER_DISABLE": "Вимкнути розширення",
  "EXTENSION_MANAGER_DISABLE_ERROR": "Неможливо вимкнути одне або кілька розширень: {0}. {APP_NAME} усе одно перезавантажиться.",
  "EXTENSION_MANAGER_THEMES_INFO": "Щоб <a class=\"theme_settings\">вибрати теми за замовчуванням</a> або змінити інші налаштування теми, <a class=\"theme_settings\">натисніть тут</a> .",
  "EXTENSION_MANAGER_THEMES_UNDO": "Повернутися до попередньої теми",
  "MARKED_FOR_REMOVAL": "Помічено для вилучення",
  "UNDO_REMOVE": "Відмінити",
  "MARKED_FOR_UPDATE": "Помічено для оновлення",
  "UNDO_UPDATE": "Відмінити",
  "MARKED_FOR_DISABLING": "Позначено для вимкнення",
  "UNDO_DISABLE": "Відмінити",
  "CHANGE_AND_RELOAD_TITLE": "Змінити розширення",
  "CHANGE_AND_RELOAD_MESSAGE": "Аби оновити або вилучити помічені розширення, потрібно перезапустити {APP_NAME}. Вам буде запропоновано зберегти незбережені зміни.",
  "REMOVE_AND_RELOAD": "Вилучити розширення і перезапустити",
  "CHANGE_AND_RELOAD": "Змінити розширення і перезапустити",
  "UPDATE_AND_RELOAD": "Оновити розширення і перезапустити",
  "DISABLE_AND_RELOAD": "Вимкніть розширення та перезавантажте",
  "PROCESSING_EXTENSIONS": "Обробка змін розширення…",
  "EXTENSION_NOT_INSTALLED": "Не вдалось вилучити розширення {0} оскільки воно не встановлене.",
  "NO_EXTENSIONS": "Ви ще не маєте жодного розширення.<br>Натисніть на вкладку Доступні вище, аби щось встановити.",
  "NO_EXTENSION_MATCHES": "Жодне розширення не відповідає вашому запиту.",
  "REGISTRY_SANITY_CHECK_WARNING": "ЗАУВАЖТЕ: Ці розширення поширюються різними авторами і не тільки від {APP_NAME}. Вони не перевіряються і мають повні локальні права. Будьте обережні під час встановлення розширень з невідомих джерел",
  "EXTENSIONS_INSTALLED_TITLE": "Встановлені",
  "EXTENSIONS_DEFAULT_TITLE": "За замовчуванням",
  "EXTENSIONS_AVAILABLE_TITLE": "Доступні",
  "EXTENSIONS_THEMES_TITLE": "Теми",
  "EXTENSIONS_UPDATES_TITLE": "Оновлення",
  "EXTENSIONS_LAST_UPDATED": "Останнє оновлення",
  "EXTENSIONS_DOWNLOADS": "Завантаження",
  "INLINE_EDITOR_NO_MATCHES": "Нічого не знайдено.",
  "INLINE_EDITOR_HIDDEN_MATCHES": "Всі збіги згорнуто. Розгортайте файли наведені справа, аби переглянути збіги.",
  "CSS_QUICK_EDIT_NO_MATCHES": "Жодне правило CSS, що відповідає виділенню.<br> Натисніть 'Нове правило' для створення. ",
  "CSS_QUICK_EDIT_NO_STYLESHEETS": "У вашому проекті відсутні таблиці стилів.<br>Створіть хоча б одну аби мати можливість додавати CSS-правила.",
  "IMAGE_VIEWER_LARGEST_ICON": "найбільша",
  "UNIT_PIXELS": "пікселі",
  "DEBUG_MENU": "Відлагодження",
  "ERRORS": "Помилки",
  "CMD_SHOW_DEV_TOOLS": "Інструменти розробника {APP_NAME}",
  "CMD_REFRESH_WINDOW": "Перезапустити з розширеннями",
  "CMD_LOAD_CURRENT_EXTENSION": "Завантажити проект як розширення",
  "CMD_RELOAD_CURRENT_EXTENSION": "Перезавантажте проект як розширення",
  "CMD_UNLOAD_CURRENT_EXTENSION": "Вивантажити проект як розширення",
  "CMD_RELOAD_WITHOUT_USER_EXTS": "Перезапустити без розширень",
  "CMD_NEW_BRACKETS_WINDOW": "Нове вікно",
  "CMD_LAUNCH_SCRIPT_MAC": "Встановити ярлик командного рядка",
  "CMD_SWITCH_LANGUAGE": "Змінити мову…",
  "CMD_RUN_UNIT_TESTS": "Виконайте тести {APP_NAME}",
  "CMD_SHOW_PERF_DATA": "Показати дані продуктивності",
  "CMD_ENABLE_LOGGING": "Увімкнути докладні журнали",
  "CMD_ENABLE_PHNODE_INSPECTOR": "Увімкнути PhNode Inspector",
  "CMD_GET_PHNODE_INSPECTOR_URL": "Як перевірити PhNode",
  "CMD_ENABLE_LIVE_PREVIEW_LOGS": "Журнали попереднього перегляду",
  "CMD_OPEN_BRACKETS_SOURCE": "Відкрити код Brackets",
  "CREATING_LAUNCH_SCRIPT_TITLE": "Ярлик командного рядка {APP_NAME}",
  "ERROR_CREATING_LAUNCH_SCRIPT": "Під час встановлення ярлика командного рядка сталася помилка. Будь ласка, спробуйте <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting'>ці пропозиції щодо усунення несправностей</a> .<br/><br/> Причина: {0}",
  "ERROR_CLTOOLS_RMFAILED": "Неможливо видалити існуюче символічне посилання <code>/usr/local/bin/brackets</code> brackets.",
  "ERROR_CLTOOLS_MKDIRFAILED": "Не вдалося створити каталог <code>/usr/local/bin</code> .",
  "ERROR_CLTOOLS_LNFAILED": "Не вдалося створити символічне посилання <code>/usr/local/bin/brackets</code> brackets.",
  "ERROR_CLTOOLS_SERVFAILED": "Внутрішня помилка.",
  "ERROR_CLTOOLS_NOTSUPPORTED": "Ярлик командного рядка не підтримується цією ОС.",
  "LAUNCH_SCRIPT_CREATE_SUCCESS": "Успіх! Тепер ви можете легко запускати {APP_NAME} з командного рядка: візьміть у <code>brackets myFile.txt</code> , щоб відкрити файл, або в <code>brackets myFolder</code> , щоб переключити проекти.<br/><br/> <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments'>Дізнайтеся більше</a> про використання {APP_NAME} з командного рядка.",
  "ERROR_LOADING_EXTENSION": "Помилка завантаження розширення",
  "ERROR_NO_EXTENSION_PACKAGE": "файл <code>package.json</code> не виявлено в поточному проекті. Чи є поточний проект дійсним розширенням {APP_NAME}?</br> Перегляньте <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>це посилання</a> для отримання додаткової інформації.",
  "ERROR_INVALID_EXTENSION_PACKAGE": "файл <code>package.json</code> недійсний JSON.</br> Перегляньте <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>це посилання</a> для отримання додаткової інформації.",
  "ERROR_INVALID_EXTENSION_PACKAGE_FIELDS": "У <code>package.json</code> відсутні обов’язкові поля: [{0}]</br> Перегляньте <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>це посилання</a> для отримання додаткової інформації.",
  "ERROR_NODE_JS_CRASH_TITLE": "Ой! Щось пішло не так.",
  "ERROR_NODE_JS_CRASH_MESSAGE": "У нас виникла проблема, тому потрібно перезапустити {APP_NAME}. Не хвилюйтеся, ми намагаємося зберегти всю вашу роботу перед перезапуском. </br>(Помилка: ERROR_NODE_JS_CRASH)",
  "LANGUAGE_TITLE": "Змінити мову",
  "LANGUAGE_MESSAGE": "Мова:",
  "LANGUAGE_SUBMIT": "Перезапустити {APP_NAME}",
  "LANGUAGE_CANCEL": "Скасувати",
  "LANGUAGE_SYSTEM_DEFAULT": "Типова в системі",
  "HEALTH_DATA_NOTIFICATION": "Параметри звіту про стан здоров’я",
  "HEALTH_FIRST_POPUP_TITLE": "Повідомлення про конфіденційність",
  "HEALTH_DATA_DO_TRACK": "Поділіться анонімною інформацією про те, як я використовую {APP_NAME}",
  "HEALTH_DATA_NOTIFICATION_MESSAGE": "{APP_NAME} <strong>не збирає та не обробляє будь-яку особисту інформацію</strong> , але <strong>збирає анонімну статистику використання</strong> , щоб захистити вашу конфіденційність. На анонімні дані не поширюються вимоги щодо сповіщень GDPR/CCPA, але ми вважаємо, що ви також повинні мати можливість відмовитися від збору анонімних даних.<br><br> Ви можете переглянути свої дані або <strong>відмовитися від анонімних даних</strong> , вибравши <strong>Довідка &gt; Звіт про стан здоров’я</strong> . Ці <strong>анонімні</strong> статистичні дані про використання програми та звіти про помилки допомагають визначити пріоритетність функцій, знайти помилки та проблеми з зручністю використання, щоб покращити роботу з {APP_NAME}. Без цих даних ми б не знали, які функції варто створити для вас!<br><br>",
  "HEALTH_DATA_PREVIEW": "Звіт про стан {APP_NAME}",
  "HEALTH_DATA_PREVIEW_INTRO": "<p>{APP_NAME} <strong>не збирає та не обробляє будь-яку особисту інформацію</strong> , але <strong>збирає анонімну статистику використання,</strong> щоб захистити вашу конфіденційність. Ці <strong>анонімні</strong> статистичні дані про використання програми та звіти про помилки допомагають визначити пріоритетність функцій, знайти помилки та проблеми з зручністю використання, щоб покращити роботу з {APP_NAME}.</p><p> Нижче наведено попередній перегляд даних, які буде надіслано у вашому наступному звіті про стан здоров’я <em>, якщо</em> його ввімкнено. (Також перегляньте журнали помилок із позначкою «Caught Critical error» у консолі розробника.)</p>",
  "INLINE_TIMING_EDITOR_TIME": "Час",
  "INLINE_TIMING_EDITOR_PROGRESSION": "Просування",
  "BEZIER_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd><kbd>←</kbd><kbd>→</kbd> Переміщення обраної точки<br><kbd class='text'>Shift</kbd> Переміщення на 10 одиниць<br><kbd class='text'>Tab</kbd> Навігація точками",
  "STEPS_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd> Збільшення та зменшення кроку<br><kbd>←</kbd><kbd>→</kbd> 'Початок' та 'кінець'",
  "INLINE_TIMING_EDITOR_INVALID": "Старе значення <code>{0}</code> – невірне, тому функцію змінено на <code>{1}</code>. Документ буде оновлено після першого редагування.",
  "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP": "Поточний колір",
  "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP": "Початковий колір",
  "COLOR_EDITOR_RGBA_BUTTON_TIP": "Формат RGBa",
  "COLOR_EDITOR_HEX_BUTTON_TIP": "Формат Hex",
  "COLOR_EDITOR_HSLA_BUTTON_TIP": "Формат HSLa",
  "COLOR_EDITOR_0X_BUTTON_TIP": "Шістнадцятковий (0x) формат",
  "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR": "{0} (використано {1} раз)",
  "COLOR_EDITOR_USED_COLOR_TIP_PLURAL": "{0} (використано {1} разів)",
  "EDIT": "Змінити",
  "CMD_JUMPTO_DEFINITION": "Перейти до оголошення",
  "CMD_SHOW_PARAMETER_HINT": "Показувати підсвічування параметрів функції",
  "NO_ARGUMENTS": "<параметри відсутні>",
  "DETECTED_EXCLUSION_TITLE": "Помилка виведення файлу JavaScript",
  "DETECTED_EXCLUSION_INFO": "{APP_NAME} зіткнувся з проблемою обробки <span class='dialog-filename'>{0}</span> .<br><br> Цей файл більше не оброблятиметься для підказок коду, переходу до визначення чи швидкого редагування. Щоб знову ввімкнути цей файл, відкрийте <code>.phcode.json</code> у своєму проекті та відредагуйте <code>jscodehints.detectedExclusions</code> .<br><br> Ймовірно, це помилка {APP_NAME}. Якщо ви можете надати копію цього файлу, <a href='https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue'>надішліть повідомлення про помилку</a> з посиланням на вказаний тут файл.",
  "CMD_REFACTOR": "Рефактор",
  "CMD_EXTRACTTO_VARIABLE": "Видобути до змінної",
  "CMD_EXTRACTTO_FUNCTION": "Витяг до функції",
  "ERROR_TERN_FAILED": "Не вдалося отримати дані від Tern",
  "ERROR_EXTRACTTO_VARIABLE_NOT_VALID": "Виділення не формує вираження",
  "ERROR_EXTRACTTO_FUNCTION_NOT_VALID": "Вибраний блок має представляти набір операторів або вираз",
  "ERROR_EXTRACTTO_VARIABLE_MULTICURSORS": "Екстракт до змінної не працює в мультикурсорах",
  "ERROR_EXTRACTTO_FUNCTION_MULTICURSORS": "Екстракт до функції не працює в мультикурсорах",
  "EXTRACTTO_FUNCTION_SELECT_SCOPE": "Виберіть область призначення",
  "EXTRACTTO_VARIABLE_SELECT_EXPRESSION": "Виберіть вираз",
  "CMD_REFACTORING_RENAME": "Перейменувати",
  "CMD_REFACTORING_TRY_CATCH": "Загорнути в Try Catch",
  "CMD_REFACTORING_CONDITION": "Упаковка в стані",
  "CMD_REFACTORING_GETTERS_SETTERS": "Створити Getters/Setters",
  "CMD_REFACTORING_ARROW_FUNCTION": "Перетворити на функцію стрілки",
  "DESCRIPTION_CODE_REFACTORING": "Увімкнути/вимкнути рефакторинг коду JavaScript",
  "ERROR_TRY_CATCH": "Виберіть дійсний код, щоб обернути його в блок Try-catch",
  "ERROR_WRAP_IN_CONDITION": "Виберіть дійсний код для обгортання в блок умови",
  "ERROR_ARROW_FUNCTION": "Помістіть курсор у вираз функції",
  "ERROR_GETTERS_SETTERS": "Помістіть курсор на елемент виразу об’єкта",
  "ERROR_RENAME_MULTICURSOR": "Неможливо перейменувати під час використання мультикурсорів",
  "ERROR_RENAME_QUICKEDIT": "Неможливо перейменувати цей ідентифікатор, оскільки на нього посилаються деінде за межами цієї функції",
  "ERROR_RENAME_GENERAL": "Неможливо перейменувати виділений текст",
  "JSHINT_NAME": "JSHint",
  "JSHINT_CONFIG_ERROR": "Помилка читання конфігураційного файлу JSHint: {0}",
  "JSHINT_CONFIG_JSON_ERROR": "Помилка: файл конфігурації JSHint `{0}` недійсний JSON",
  "ESLINT_NAME": "ESLint",
  "CSS_LINT_NAME": "{0}",
  "HTML_LINT_NAME": "HTML",
  "HTML_LINT_CONFIG_JSON_ERROR": "Помилка: файл конфігурації HTML Validator `{0}` не є дійсним JSON",
  "HTML_LINT_CONFIG_UNSUPPORTED": "Помилка: непідтримуваний формат конфігурації `{0}`. Використовуйте конфігурацію JSON `.htmlvalidate.json`",
  "CMD_ENABLE_QUICK_VIEW": "Швидкий перегляд під час наведення",
  "CMD_ENABLE_SELECTION_VIEW": "Вид вибору",
  "TOOLTIP_CLICK_TO_EDIT_COLOR": "Натисніть тут, щоб змінити колір",
  "CMD_TOGGLE_RECENT_PROJECTS": "Останні проекти",
  "REMOVE_FROM_RECENT_PROJECTS": "Видалити з останніх проектів",
  "DOCS_MORE_LINK": "Докладніше",
  "DOCS_MORE_LINK_MDN_TITLE": "Натисніть, щоб прочитати документацію",
  "COLLAPSE_ALL": "Закрити всі",
  "EXPAND_ALL": "Розгорнути все",
  "COLLAPSE_CURRENT": "Згорнути струм",
  "EXPAND_CURRENT": "Розгорніть Current",
  "RECENT_FILES_DLG_HEADER": "Останні файли",
  "RECENT_FILES_DLG_CLEAR_BUTTON_LABEL": "ясно",
  "RECENT_FILES_DLG_CLEAR_BUTTON_TITLE": "Очистити файли, яких немає в робочому наборі",
  "RECOVER_UNSAVED_FILES_TITLE": "Відновити незбережені файли?",
  "RECOVER_UNSAVED_FILES_MESSAGE": "Відновити незбережені файли з попереднього сеансу?",
  "RECOVER_UNSAVED_FILES_RESTORE": "Відновлення",
  "DISCARD_UNSAVED_FILES_RESTORE": "Відкинути",
  "DESCRIPTION_CLOSE_BRACKETS": "true для автоматичного закриття дужок, дужок і круглих дужок",
  "DESCRIPTION_CLOSE_OTHERS_ABOVE": "false, щоб видалити «Закрити інші вище» з контекстного меню робочих файлів",
  "DESCRIPTION_CLOSE_OTHERS_BELOW": "false, щоб видалити «Закрити інші нижче» з контекстного меню робочих файлів",
  "DESCRIPTION_CLOSE_OTHERS": "false, щоб видалити «Закрити інші» з контекстного меню робочих файлів",
  "DESCRIPTION_CLOSE_TAGS": "Встановлює параметри закриття тегів",
  "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS": "Масив тегів, які не повинні автоматично закриватися",
  "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING": "Закривати після введення > початкового тегу",
  "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING": "Закрити, коли введено закриваючий тег /",
  "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS": "Масив тегів, який після відкриття має порожній рядок",
  "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD": "true, щоб завжди створювати маркери розділів, що згортаються, коли змінюється рівень відступу",
  "DESCRIPTION_CODE_FOLDING_ENABLED": "true, щоб увімкнути згортання коду",
  "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER": "true, щоб зробити маркери згортання розділу видимими лише тоді, коли ви наводите мишу на жолоб",
  "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL": "Обмежує глибину рівня Згорнути все",
  "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE": "Мінімальна кількість рядків перед появою значка розділу, що згортається",
  "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES": "правда, щоб запам'ятати згорнуті розділи, якщо ви закриваєте та знову відкриваєте файл або проект",
  "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE": "true, щоб увімкнути згортання коду виділеного тексту в редакторі",
  "DESCRIPTION_DISABLED_DEFAULT_EXTENSIONS": "Розширення за замовчуванням, які вимкнено",
  "DESCRIPTION_ATTR_HINTS": "Увімкнути/вимкнути підказки атрибутів HTML",
  "DESCRIPTION_CSS_PROP_HINTS": "Увімкнути/вимкнути підказки властивостей CSS/LESS/SCSS",
  "DESCRIPTION_JS_HINTS": "Увімкнути/вимкнути підказки коду JavaScript",
  "DESCRIPTION_JS_HINTS_TYPE_DETAILS": "Увімкнути/вимкнути деталі типу даних у підказках коду JavaScript",
  "DESCRIPTION_PREF_HINTS": "Увімкнути/вимкнути підказки коду налаштувань",
  "DESCRIPTION_SPECIAL_CHAR_HINTS": "Увімкнути/вимкнути підказки для сутностей HTML",
  "DESCRIPTION_SVG_HINTS": "Увімкнути/вимкнути підказки коду SVG",
  "DESCRIPTION_HTML_TAG_HINTS": "Увімкнути/вимкнути підказки тегів HTML",
  "DESCRIPTION_URL_CODE_HINTS": "Увімкнути/вимкнути URL-підказки в HTML і CSS/LESS/SCSS",
  "DESCRIPTION_DRAG_DROP_TEXT": "Увімкнути/вимкнути функцію перетягування",
  "DESCRIPTION_HEALTH_DATA_TRACKING": "Увімкніть відстеження даних про здоров’я",
  "DESCRIPTION_HIGHLIGHT_MATCHES": "Вмикає автоматичне виділення відповідних рядків у всьому документі",
  "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN": "Виділіть усі рядки, які відповідають токену, у якому зараз знаходиться курсор (вибір не потрібен)",
  "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY": "Виділіть лише тоді, коли виділено повний маркер",
  "DESCRIPTION_INSERT_HINT_ON_TAB": "true, щоб вставити вибрану підказку коду на вкладці",
  "DESCRIPTION_NO_HINTS_ON_DOT": "true, щоб автоматично не показувати підказки коду JS, коли . набирається",
  "DESCRIPTION_JSHINT_DISABLE": "true, щоб вимкнути JSHints linter на панелі проблем",
  "DESCRIPTION_ESLINT_DISABLE": "true, щоб вимкнути ESLint linter на панелі проблем",
  "DESCRIPTION_HTML_LINT_DISABLE": "true, щоб вимкнути HTML-лінтер на панелі проблем",
  "DESCRIPTION_ESLINT_FAILED": "Помилка ESLint ({0}). Переконайтеся, що проект містить дійсні <a href='https://eslint.org/docs/latest/use/configure/configuration-files'>файли конфігурації</a>",
  "DESCRIPTION_ESLINT_USE_NATIVE_APP": "ESLint доступний лише в програмі Desktop. Завантажте його з <a href='https://phcode.io'>phcode.io</a>",
  "DESCRIPTION_ESLINT_LOAD_FAILED": "Не вдалося завантажити ESLint для цього проекту. {APP_NAME} підтримує лише версії ESLint вище 7.",
  "DESCRIPTION_ESLINT_DO_NPM_INSTALL": "Будь ласка, запустіть `npm install` у своєму проекті, щоб увімкнути ESLint",
  "DESCRIPTION_LANGUAGE": "Спеціальні налаштування мови",
  "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS": "Додаткові зіставлення розширення файлу з назвою мови",
  "DESCRIPTION_LANGUAGE_FILE_NAMES": "Додаткові зіставлення імені файлу з назвою мови",
  "DESCRIPTION_LINEWISE_COPY_CUT": "Виконання копіювання та вирізання, коли немає виділення, призведе до копіювання або вирізання всіх рядків, у яких є курсори",
  "DESCRIPTION_INPUT_STYLE": "Вибирає спосіб обробки введення та фокусування CodeMirror. Це може бути текстове поле, яке є типовим, або contenteditable, що краще для програм зчитування з екрана (нестабільне)",
  "DESCRIPTION_LINTING_ENABLED": "true, щоб увімкнути перевірку коду",
  "DESCRIPTION_ASYNC_TIMEOUT": "Час у мілісекундах, після якого асинхронні лінтери закінчуються",
  "DESCRIPTION_LINTING_PREFER": "Масив лінтерів для запуску в першу чергу",
  "DESCRIPTION_LIVE_DEV_MULTIBROWSER": "true, щоб увімкнути експериментальний попередній перегляд у реальному часі",
  "DESCRIPTION_USE_PREFERED_ONLY": "true лише для запуску постачальників, указаних у linting.prefer",
  "DESCRIPTION_MAX_CODE_HINTS": "Максимальна кількість підказок коду відображається одночасно",
  "DESCRIPTION_PATH": "Спеціальні налаштування шляху",
  "DESCRIPTION_PROXY": "URL-адреса проксі-сервера, який використовується для встановлення розширення",
  "DESCRIPTION_SCROLL_PAST_END": "true, щоб увімкнути прокручування за кінець документа",
  "DESCRIPTION_SHOW_CODE_HINTS": "false, щоб вимкнути всі підказки коду",
  "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING": "Зберігає миготливий курсор видимим, коли ви вибрали текст",
  "DESCRIPTION_SHOW_LINE_NUMBERS": "true, щоб показувати номери рядків у «жолобі» ліворуч від коду",
  "DESCRIPTION_RULERS_COLUMNS": "Масив номерів стовпців для малювання вертикальних лінійок у редакторі. Наприклад: [80, 100]",
  "DESCRIPTION_RULERS_COLORS": "Масив кольорів лінійки, що відповідає параметру лінійки в редакторі. Наприклад: [\"#3d3d3d\", \"red\"]",
  "DESCRIPTION_RULERS_ENABLED": "true, щоб увімкнути лінійки редактора, інакше false",
  "DESCRIPTION_SMART_INDENT": "Автоматичний відступ при створенні нового блоку",
  "DESCRIPTION_SOFT_TABS": "false, щоб вимкнути поведінку програмних вкладок",
  "DESCRIPTION_SORT_DIRECTORIES_FIRST": "true, щоб спочатку сортувати каталоги в дереві проекту",
  "DESCRIPTION_SPACE_UNITS": "Кількість пробілів для відступу на основі пробілу",
  "DESCRIPTION_STATIC_SERVER_PORT": "Номер порту, який має використовувати вбудований сервер для Live Preview",
  "DESCRIPTION_STYLE_ACTIVE_LINE": "true для виділення кольору тла лінії, на якій знаходиться курсор",
  "DESCRIPTION_TAB_SIZE": "Кількість пробілів для відображення вкладок",
  "DESCRIPTION_USE_TAB_CHAR": "вірно використовувати символи табуляції замість пробілів",
  "DESCRIPTION_UPPERCASE_COLORS": "true, щоб генерувати шістнадцяткові кольори у верхньому регістрі у вбудованому редакторі кольорів",
  "DESCRIPTION_WORD_WRAP": "Обтікання лініями, які перевищують ширину вікна перегляду",
  "DESCRIPTION_SEARCH_AUTOHIDE": "Закрийте пошук, як тільки редактор буде сфокусований",
  "DESCRIPTION_DETECTED_EXCLUSIONS": "Список файлів, які, як було виявлено, викликають вихід Tern з-під контролю",
  "DESCRIPTION_INFERENCE_TIMEOUT": "Проміжок часу, після якого Tern завершує роботу під час спроби зрозуміти файли",
  "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR": "true, щоб відображати помилки в рядку стану",
  "DESCRIPTION_QUICK_VIEW_ENABLED": "true, щоб увімкнути швидкий перегляд",
  "DESCRIPTION_SELECTION_VIEW_ENABLED": "true, щоб увімкнути перегляд виділення",
  "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW": "true, щоб показати попередній перегляд зображень для URL-адрес без розширень",
  "DESCRIPTION_NUMBER_QUICK_VIEW": "true, щоб показувати швидкий перегляд при наведенні курсора на числа в редакторі",
  "DESCRIPTION_THEME": "Виберіть тему {APP_NAME}",
  "DESCRIPTION_USE_THEME_SCROLLBARS": "true, щоб дозволити спеціальні смуги прокрутки",
  "DESCRIPTION_LINTING_COLLAPSED": "правда, щоб згорнути панель лінінгу",
  "DESCRIPTION_FONT_FAMILY": "Змінити сімейство шрифтів",
  "DESCRIPTION_DESKTOP_ZOOM_SCALE": "Виберіть коефіцієнт масштабування в діапазоні від 0,1 (для більш компактного перегляду) до 2 (для більшого та збільшеного перегляду). Доступно лише в настільних програмах",
  "DESCRIPTION_FONT_SIZE": "Змінити розмір шрифту; напр. 13 пікселів",
  "DESCRIPTION_FIND_IN_FILES_NODE": "true, щоб увімкнути пошук на основі вузлів",
  "DESCRIPTION_FIND_IN_FILES_INSTANT": "true, щоб увімкнути миттєвий пошук",
  "DESCRIPTION_FONT_SMOOTHING": "Лише для Mac: «subpixel-antialiased» для ввімкнення субпіксельного згладжування або «antialiased» для згладжування відтінків сірого",
  "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW": "false, щоб вимкнути відкриття файлу параметрів у розділеному перегляді",
  "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE": "false, щоб відкрити файл налаштувань користувача на лівій/верхній панелі",
  "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED": "true для згортання панелей після закриття останнього файлу на панелі за допомогою кнопки закриття заголовка панелі",
  "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS": "Увімкніть, коли показувати кнопки закриття та перегортання в заголовку.",
  "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT": "/*\n * Це файл лише для читання з підтримуваними налаштуваннями\n * від {APP_NAME}.\n * Використовуйте цей файл як посилання, щоб змінити свої налаштування\n * файл \"phcode.json\", відкритий на іншій панелі.\n * Для отримання додаткової інформації про те, як використовувати налаштування всередині\n * {APP_NAME}, зверніться до веб-сторінки https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences\n */",
  "DEFAULT_PREFERENCES_JSON_DEFAULT": "За замовчуванням",
  "DESCRIPTION_PURE_CODING_SURFACE": "true, щоб увімкнути режим лише коду та приховати всі інші елементи інтерфейсу користувача в {APP_NAME}",
  "DESCRIPTION_INDENT_LINE_COMMENT": "true, щоб увімкнути відступи для рядкових коментарів",
  "DESCRIPTION_RECENT_FILES_NAV": "Увімкнути/вимкнути навігацію в останніх файлах",
  "DESCRIPTION_LIVEDEV_WEBSOCKET_PORT": "Порт, на якому працює WebSocket Server для Live Preview",
  "DESCRIPTION_LIVE_DEV_HIGHLIGHT_SETTINGS": "Налаштування підсвічування попереднього перегляду",
  "DESCRIPTION_LIVEDEV_ENABLE_REVERSE_INSPECT": "false, щоб вимкнути попередній перегляд у реальному часі",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW": "Немає нічого для попереднього перегляду!",
  "DESCRIPTION_LIVEDEV_EXCLUDED": "Спеціальний сервер не може обслуговувати цей файл",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW_EXCLUDED": "Налаштування попереднього перегляду в режимі реального часу налаштовано для обслуговування файлів лише з папки \"{0}\"",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW_DETAILS": "Виберіть файл HTML для попереднього перегляду",
  "DESCRIPTION_LIVEDEV_PREVIEW_RESTRICTED": "Попередній перегляд недоступний!",
  "DESCRIPTION_LIVEDEV_PREVIEW_RESTRICTED_DETAILS": "Цей файл HTML не є частиною поточного проекту. З міркувань безпеки лише файли проекту можна переглядати в реальному часі. Щоб переглянути цей файл, відкрийте його папку як окремий проект.",
  "DESCRIPTION_LIVEDEV_MAIN_HEADING": "Ой-ой!<br> Ваш поточний браузер не підтримує попередній перегляд.",
  "DESCRIPTION_LIVEDEV_MAIN_SPAN": "Отримайте найкращий попередній перегляд, завантаживши наші рідні програми для Windows, Mac і Linux із <a href=\"https://phcode.io\" style=\"color: white\">phcode.io</a> .<br>",
  "DESCRIPTION_LIVEDEV_SECURITY_POPOUT_MESSAGE": "Ви збираєтеся відкрити файл для попереднього перегляду. Продовжуйте, лише якщо ви довіряєте джерелу цього проекту. Натисніть «Довіряти проекту», щоб продовжити, або закрийте це вікно, якщо ви не довіряєте джерелу.",
  "DESCRIPTION_LIVEDEV_SECURITY_TRUST_MESSAGE": "Ви збираєтеся відкрити файл для попереднього перегляду. Продовжуйте, натискаючи «Довіряти проекту», лише якщо ви довіряєте джерелу цього проекту!",
  "CONFIRM_EXTERNAL_BROWSER_TITLE": "Спливаючі вікна заблоковано",
  "CONFIRM_EXTERNAL_BROWSER_MESSAGE": "Ви бажаєте дозволити сторінці попереднього перегляду відкривати цю URL-адресу: {0}?",
  "TRUST_PROJECT": "Довіряти та виконувати попередній перегляд – {0}",
  "TRUST_AUTHORS": "Чи довіряєте ви авторам цього проекту?",
  "DOWNLOAD_FAILED": "Помилка завантаження.",
  "DOWNLOAD_COMPLETE": "Завантаження завершено!",
  "UPDATE_SUCCESSFUL": "Оновлення успішне!",
  "UPDATE_FAILED": "Помилка оновлення!",
  "VALIDATION_FAILED": "Помилка перевірки!",
  "INITIALISATION_FAILED": "Помилка ініціалізації!",
  "CLEANUP_FAILED": "Очищення не вдалося!",
  "WARNING_TYPE": "УВАГА!",
  "CLICK_RESTART_TO_UPDATE": "Натисніть Перезапустити, щоб оновити дужки.",
  "UPDATE_ON_NEXT_LAUNCH": "Оновлення буде застосовано після повторного запуску.",
  "GO_TO_SITE": "Перейдіть на <a href = \"http://brackets.io/\">brackets.io</a> , щоб повторити спробу.",
  "INTERNET_UNAVAILABLE": "Немає підключення до Інтернету.",
  "UPDATEDIR_READ_FAILED": "Не вдалося прочитати каталог оновлень.",
  "UPDATEDIR_CLEAN_FAILED": "Не вдалося очистити каталог оновлень.",
  "INITIAL_DOWNLOAD": "Завантаження оновлення...",
  "RETRY_DOWNLOAD": "Помилка завантаження. Повторна спроба...Спроба",
  "VALIDATING_INSTALLER": "Завантаження завершено! Перевірка інсталятора...",
  "CHECKSUM_DID_NOT_MATCH": "Контрольна сума не співпала.",
  "INSTALLER_NOT_FOUND": "Інсталятор не знайдено.",
  "DOWNLOAD_ERROR": "Під час завантаження сталася помилка.",
  "NETWORK_SLOW_OR_DISCONNECTED": "Мережа відключена або занадто повільна.",
  "RESTART_BUTTON": "Перезапустіть",
  "LATER_BUTTON": "Пізніше",
  "DESCRIPTION_AUTO_UPDATE": "Увімкнути/вимкнути автоматичне оновлення {APP_NAME}",
  "AUTOUPDATE_ERROR": "Помилка!",
  "AUTOUPDATE_IN_PROGRESS": "Оновлення вже триває.",
  "NUMBER_WITH_PERCENTAGE": "{0}%",
  "CMD_FIND_RELATED_FILES": "Знайти пов’язані файли",
  "PHP_VERSION_INVALID": "Помилка аналізу версії PHP. Будь ласка, перевірте результат команди «php –version».",
  "PHP_UNSUPPORTED_VERSION": "Встановіть середовище виконання PHP7, щоб увімкнути пов’язані з PHP інструменти, такі як підказки коду, підказки параметрів, перехід до визначення тощо. Знайдено версію: {0}",
  "PHP_EXECUTABLE_NOT_FOUND": "Середовище виконання PHP не знайдено. Встановіть середовище виконання PHP7 і належним чином оновіть «executablePath» у параметрах PHP. Це дозволяє використовувати пов’язані з PHP інструменти, такі як підказки коду, підказки параметрів, перехід до визначення тощо.",
  "PHP_PROCESS_SPAWN_ERROR": "Під час запуску процесу PHP виявлено код помилки {0}.",
  "PHP_SERVER_ERROR_TITLE": "Помилка",
  "PHP_SERVER_MEMORY_LIMIT_INVALID": "Наданий вами ліміт пам’яті недійсний. Перегляньте параметри PHP, щоб встановити правильне значення.",
  "DESCRIPTION_PHP_TOOLING_CONFIGURATION": "Параметри конфігурації PHP Tooling за замовчуванням",
  "OPEN_PREFERENNCES": "Відкрийте налаштування",
  "LANGUAGE_TOOLS_PREFERENCES": "Налаштування мовних інструментів",
  "FIND_ALL_REFERENCES": "Знайти всі посилання",
  "REFERENCES_IN_FILES": "посилання",
  "REFERENCE_IN_FILES": "посилання",
  "REFERENCES_NO_RESULTS": "Немає доступних посилань для поточної позиції курсору",
  "CMD_FIND_DOCUMENT_SYMBOLS": "Знайдіть символи документа",
  "CMD_FIND_PROJECT_SYMBOLS": "Знайдіть символи проекту",
  "REMOTE_DEBUGGING_ENABLED": "Віддалене налагодження ввімкнено на локальному хості:",
  "REMOTE_DEBUGGING_PORT_INVALID": "Неможливо ввімкнути віддалене налагодження на порту {0}. Номери портів мають бути між {1} і {2}.",
  "DESCRIPTION_EXTERNAL_APPLICATION_ASSOCIATE": "Зіставлення розширення файлу із зовнішніми програмами. Синтаксис: \"<тип_файлу>\": \"<default|applicationName|ApplicationPath>\", використовуйте \"default\", щоб відкривати файли в системній програмі за замовчуванням для цього типу файлів.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_TITLE": "Відкрийте графічні файли у зовнішніх редакторах.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_MSG": "Ваша поточна папка містить типи графічних файлів, які не підтримуються {APP_NAME}.<br/> Тепер ви можете пов’язувати певні типи файлів із зовнішніми редакторами. Після пов’язання ви можете відкривати графічні файли, такі як .xd, .psd, .jpg, .png, .ai, .svg, у програмах за замовчуванням, двічі клацнувши файли в дереві файлів.<br/><br/> Будь ласка, натисніть кнопку «OK», щоб пов’язати типи графічних файлів із відповідними програмами за замовчуванням.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_CNF_MSG": "Наступні типи файлів успішно пов’язані з програмами за замовчуванням.<br/> {0} У вас є можливість змінити параметри видалення чи додавання нових зв’язків типів файлів у phcode.json, перейшовши в меню «Debug-&gt;Open Preferences File».",
  "UNSUPPORTED_BROWSER_TITLE": "Браузер не підтримується",
  "UNSUPPORTED_BROWSER_MESSAGE": "Будь ласка, використовуйте сучасний браузер (випущений протягом останніх 3 років).",
  "UNSUPPORTED_BROWSER_MOBILE_TITLE": "Мобільні браузери не підтримуються",
  "UNSUPPORTED_BROWSER_MOBILE": "Мобільні та планшетні браузери наразі підтримуються не повністю. Ви можете закрити це діалогове вікно, але деякі функції Phoenix не працюватимуть у цьому браузері.<br/><br/> Ми працюємо над розробкою нативних програм для iOS та Android. <a href=\"https://github.com/phcode-dev/phoenix/discussions/1046\" target=\"_blank\">Приєднуйтесь до обговорення тут!</a>",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER_TITLE": "Доступ до локальної папки не підтримується браузером",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER": "Вибачте, схоже, ваш поточний браузер не підтримує відкриття локальних папок. Для цієї функції ми рекомендуємо використовувати Chrome, Edge або Opera.<br/><br/> Крім того, ми працюємо над розробкою нативних програм для Windows, Mac, Linux, iOS і Android, щоб забезпечити повну підтримку. <a href=\"https://github.com/phcode-dev/phoenix/discussions/1047\" target=\"_blank\">Слідкуйте за оновленнями!</a>",
  "ATTENTION_SAFARI_USERS": "До уваги користувачів Safari",
  "ATTENTION_SAFARI_USERS_MESSAGE": "<span>Safari автоматично видаляє дані веб-сайту, якщо сайт не відвідується повторно протягом 7 днів. {APP_NAME} використовує пам’ять веб-переглядача для збереження ваших проектів, які можуть бути видалені через цю політику.<br/><br/> Рекомендовано <strong>завантажити програму для комп’ютера macOS</strong> із <a href='https://phcode.io' target='_blank' style='color: white'>https://phcode.io</a></span>",
  "CANNOT_PUBLISH_LARGE_PROJECT": "Неможливо опублікувати великий проект",
  "CANNOT_PUBLISH_LARGE_PROJECT_MESSAGE": "Phoenix все ще знаходиться в експериментальній альфа-версії. Ми ще не ввімкнули синхронізацію проектів із понад 500 файлами.",
  "SHARE_WEBSITE": "Опублікувати та поділитися веб-сайтом?",
  "PUBLISH": "Опублікувати",
  "PUBLISH_CONSENT_MESSAGE": "Швидко переглядайте зміни та діліться своїм веб-сайтом з іншими. Phoenix може опублікувати цей веб-сайт для вас за адресою {0}. Опубліковані посилання будуть дійсні протягом 30 днів. </br>Ви бажаєте опублікувати свій веб-сайт і поділитися ним?",
  "PUBLISH_SYNC_IN_PROGRESS": "Виконується синхронізація для попереднього перегляду...",
  "PUBLISH_PAGE": "Натисніть, щоб опублікувати та поділитися цим сайтом",
  "PUBLISH_VIEW_PAGE": "Натисніть, щоб переглянути опубліковану сторінку",
  "MISSING_FIELDS": "Відсутні поля",
  "PLEASE_FILL_ALL_REQUIRED": "Будь ласка, заповніть усі необхідні поля, виділені червоним",
  "CODE_EDITOR": "Редактор коду",
  "BUILD_THE_WEB": "Створіть мережу",
  "IMPORT_PROJECT": "Імпорт проекту",
  "GITHUB_PROJECT": "Проект GitHub",
  "NEW_PROJECT_FROM_GITHUB": "Новий проект від GitHub",
  "GITHUB_REPO_URL": "URL-адреса сховища GitHub:",
  "START_PROJECT": "Розпочати проект…",
  "DOWNLOAD_DESKTOP_APP": "Завантажте додаток для робочого столу",
  "GET_DESKTOP_APP": "Отримати програму для комп’ютера",
  "CREATE_PROJECT": "Створити проект",
  "SETTING_UP_PROJECT": "Налаштування проекту",
  "LOCATION": "Місцезнаходження :",
  "DOWNLOADING": "Завантаження...",
  "DOWNLOADING_FILE": "Завантаження {0}...",
  "EXTRACTING_FILES_PROGRESS": "Видобування {0} із {1} файлів.",
  "COMPRESS_FILES_PROGRESS": "Стискається {0} із {1} файлів.",
  "DOWNLOAD_FAILED_MESSAGE": "Переконайтеся, що URL-адреса завантаження дійсна. </br>Примітка: оскільки Phoenix перебуває в альфа-версії, URL-адреси приватних сховищ і GitHub не допускаються, розмір яких перевищує 25 МБ.",
  "PLEASE_SELECT_A_FOLDER": "Виберіть папку...",
  "UNZIP_IN_PROGRESS": "Розпакування файлів...",
  "UNZIP_FAILED": "Помилка: не вдалося розархівувати.",
  "CONFIRM_REPLACE_TITLE": "Підтвердити заміну",
  "KEEP_BOTH": "Тримайте обидва",
  "EXPLORE": "Ігри HTML",
  "BLOG": "Блог",
  "PHOENIX_DEFAULT_PROJECT": "Проект за замовчуванням",
  "PROJECT_NAME": "Назва проекту:",
  "NEW_HTML": "Новий проект HTML",
  "LICENSE": "Ліцензія та подяки:",
  "PREVIEW": "Попередній перегляд",
  "BUILD_WEBSITE": "Створення веб-сайту",
  "VIEW_MORE": "Дивитись більше...",
  "NEW_PROJECT_NOTIFICATION": "Натисніть цю піктограму, щоб знову відкрити вікно `Новий проект`.</br> Перегляньте «Останні проекти», «Відкрити папку» або почніть проекти з шаблонів.</br><img src=\"styles/images/new_project.png\"><br/> <a href='#' style='float:right;'>в порядку</a>",
  "BEAUTIFY_CODE_NOTIFICATION": "Натисніть тут або натисніть <b>`{0}`</b> , щоб прикрасити код.</br><img src=\"styles/images/beautify.gif\"><br/> <a href='#' style='float:right;'>в порядку</a>",
  "DEFAULT_PROJECT_NOTIFICATION": "Натисніть тут, щоб відкрити<br/> <b>проект за замовчуванням</b> у Phoenix.</br> <a href='#' style='float:right;'>в порядку</a>",
  "DIRECTORY_REPLACE_MESSAGE": "Вибрана папка <span class='dialog-filename'>{0}</span> не порожня. Ви впевнені, що бажаєте замінити вміст папки проектом?",
  "DEFAULT_PROJECT_HTML_CLICK_HERE": "Натисніть тут, щоб знайти цей &lt;span&gt; у файлі HTML",
  "BUILD_WEBSITE_SECTION": "Створення веб-сайту",
  "LEARN_SECTION": "Навчайтеся на прикладах",
  "CREATE_EXTENSION_SECTION": "Створюйте розширення та теми {APP_NAME}",
  "CREATE_EXTENSION": "Створити розширення",
  "CREATE_THEME": "Створити тему",
  "WEBPAGE_HOME_PAGE": "Домашня сторінка",
  "WEBPAGE_BLOG": "Сторінка блогу",
  "WEBPAGE_DASHBOARD": "Інформаційна панель HTML",
  "WEBPAGE_BOOTSTRAP_EXAMPLES": "Приклади Bootstrap",
  "PROJECTS_AT_A_GLANCE": "Короткий огляд ваших проектів",
  "PROJECT_AT_GLANCE_DESCRIPTION": "Перегляньте відео, щоб почати.",
  "PROJECT_FROM_BROWSER": "Зберігається у вашому браузері",
  "PROJECT_FROM_BROWSER_TERSE": "Зберігання браузера",
  "PROJECT_SHOW_ON_STARTUP": "Показати цей діалог під час запуску",
  "GUIDED_LIVE_PREVIEW": "Внесіть деякі зміни у код HTML-файлу, щоб переглянути попередній перегляд.</br> <a href='#' style='float:right;'>добре</a>",
  "GUIDED_LIVE_PREVIEW_POPOUT": "Натисніть цю кнопку, щоб вивести попередній перегляд на нову вкладку.</br> <a href='#' style='float:right;'>в порядку</a>",
  "ENJOYING_APP": "Подобається {APP_NAME}?",
  "GITHUB_STARS_POPUP": "<div>Ваша підтримка допомагає нашій невеликій команді мотивувати робити <b style='color: darkblue'>phcode.dev</b> ще кращим.<br/> Будь ласка, позначте нас зірочкою або подумайте про спонсорство на GitHub:",
  "GITHUB_STARS_POPUP_TWITTER": "Надішліть відгук або поширте інформацію у Twitter:",
  "TEST_TRANSLATE": "використовуйте це для перевірки перекладів",
  "BEAUTIFY_ERROR": "Не вдалося прикрасити код. Перевірте синтаксис.",
  "BEAUTIFY_ERROR_ORIGINAL_CHANGED": "Не міг прикрасити. Текст редактора змінено після доопрацювання.",
  "BEAUTIFY_PROJECT_BUSY_MESSAGE": "Файл для покращення {0}",
  "BEAUTIFY_ERROR_SELECTION": "Не вдалося прикрасити.</br>Вибрано неповний блок коду або недійсний синтаксис.",
  "BEAUTIFY_OPTIONS": "Параметри, які контролюють роботу Beautify Code",
  "BEAUTIFY_OPTION_PRINT_WIDTH": "Укажіть довжину лінії, на яку буде накладатися косметик",
  "BEAUTIFY_OPTION_SEMICOLON": "Додайте крапку з комою в кінці кожного твердження",
  "BEAUTIFY_OPTION_SINGLE_QUOTE": "Використовуйте одинарні лапки замість подвійних",
  "BEAUTIFY_OPTION_QUOTE_PROPS": "Змінити, коли властивості об’єктів беруться в лапки",
  "BEAUTIFY_OPTION_BRACKET_SAME_LINE": "Розмістіть > багаторядкового HTML-елемента (HTML, JSX, Vue, Angular) у кінці останнього рядка замість того, щоб бути одним у наступному рядку (не стосується самозакриваючих елементів)",
  "BEAUTIFY_OPTION_SINGLE_ATTRIBUTE_PER_LINE": "Використовуйте один атрибут на рядок у HTML, Vue та JSX",
  "BEAUTIFY_OPTION_PROSE_WRAP": "Оберніть прозу, якщо вона перевищує ширину друку у файлах розмітки",
  "BEAUTIFY_OPTION_PRINT_TRAILING_COMMAS": "Друк завершальних ком, де це можливо, у багаторядкових синтаксичних структурах, розділених комами"
});