/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "Rendszer Alapértelmezett",
  "PROJECT_BUSY": "Projektműveletek folyamatban",
  "DUPLICATING": "{0} másolása",
  "MOVING": "{0} áthelyezése",
  "COPYING": "{0} másolása",
  "DELETING": "{0} törlése",
  "DELETE_TO_TRASH": "{0} áthelyezése a kukába",
  "DELETE_TO_RECYCLE_BIN": "{0} áthelyezése a Lomtárba",
  "RENAMING": "Átnevezés",
  "STORED_IN_YOUR_BROWSER": "A böngészőben tárolva",
  "SUPPORT_US_OPEN_COLLECTIVE": "Támogass minket a GitHub-szponzorokban",
  "GENERIC_ERROR": "(hiba {0})",
  "NOT_FOUND_ERR": "A fájl nem található.",
  "NOT_READABLE_ERR": "A fájl nem olvasható.",
  "EXCEEDS_MAX_FILE_SIZE": "A {0} MB-nál nagyobb fájlok nem nyithatók meg a(z) {APP_NAME} alkalmazásban.",
  "NO_MODIFICATION_ALLOWED_ERR": "A célkönyvtárat nem lehet módosítani.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "Nincs engedélyed a módosításhoz.",
  "CONTENTS_MODIFIED_ERR": "A fájlt a {APP_NAME} alkalmazáson kívül módosították.",
  "UNSUPPORTED_ENCODING_ERR": "Ismeretlen kódolási formátum",
  "ENCODE_FILE_FAILED_ERR": "A {APP_NAME} nem tudta kódolni a fájl tartalmát.",
  "DECODE_FILE_FAILED_ERR": "A {APP_NAME} nem tudta dekódolni a fájl tartalmát.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "A {APP_NAME} jelenleg nem támogatja az UTF-16 kódolású szöveges fájlokat.",
  "FILE_EXISTS_ERR": "A fájl vagy a könyvtár már létezik.",
  "FILE": "fájl",
  "FILE_TITLE": "Fájl",
  "DIRECTORY": "Könyvtár",
  "DIRECTORY_TITLE": "Könyvtár",
  "DIRECTORY_NAMES_LEDE": "Könyvtárnevek",
  "FILENAMES_LEDE": "Fájlnevek",
  "FILENAME": "Fájl név",
  "DIRECTORY_NAME": "Könyvtár neve",
  "ERROR_LOADING_PROJECT": "Hiba a projekt betöltése közben",
  "OPEN_DIALOG_ERROR": "Hiba történt a \"fájl megnyitása\" ablak megjelenítésekor. (hiba {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "Hiba történt a <span class='dialog-filename'>{0}</span> könyvtár megnyitása közben. (hiba {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "Hiba történt a könyvtár tartalmának beolvasása közben. <span class='dialog-filename'>{0}</span>. (hiba {1})",
  "ZOOM_WITH_SHORTCUTS": "Használja a billentyűparancsokat a nagyításhoz",
  "ZOOM_WITH_SHORTCUTS_DETAILS": "A nagyításhoz használja <code><i>{0}</i></code> , a kicsinyítéshez pedig <code><i>{1}</i></code> billentyűkódot.",
  "ERROR_OPENING_FILE_TITLE": "Hiba történt a fájl megnyitása közben.",
  "ERROR_OPENING_FILE": "Hiba történt a fájl megnyitása közben: <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_OPENING_FILES": "Hiba történt a következő fájlok megnyitásakor:",
  "ERROR_RELOADING_FILE_TITLE": "Hiba történt a változások merevlemezről való újratöltése közben.",
  "ERROR_RELOADING_FILE": "Hiba történt a fájl újratöltése közben: <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_SAVING_FILE_TITLE": "Hiba történt a fájl mentése közben",
  "ERROR_SAVING_FILE": "Hiba történt a fájl mentése közben: <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_FILE_TITLE": "Hiba történt a fájl átnevezése közben",
  "ERROR_RENAMING_FILE": "Hiba történt a fájl átnevezése közben: <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "A fájl vagy könyvtár nem része az éppen megnyitott projektnek. Sajnos ezen a ponton csak a projektfájlokat lehet átnevezni.",
  "ERROR_MOVING_FILE_TITLE": "Hiba a következő mozgatásakor: {0}",
  "ERROR_MOVING_FILE": "Hiba történt a(z) {2} <span class='dialog-filename'>{0}</span> áthelyezésekor. {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "A fájl/mappa nem helyezhető át, mivel nem részei az aktuális projektnek.",
  "ERROR_DELETING_FILE_TITLE": "Hiba történt a fájl törlése közben",
  "ERROR_DELETING_FILE": "Hiba történt a fájl törlése közben: <span class='dialog-filename'>{0}</span>. {1}",
  "INVALID_FILENAME_TITLE": "Helytelen fájlnév",
  "CANNOT_PASTE_TITLE": "Nem lehet beilleszteni a következőt: {0}",
  "CANNOT_DOWNLOAD_TITLE": "Nem lehet letölteni a következőt: {0}",
  "ERR_TYPE_DOWNLOAD_FAILED": "Hiba történt a(z <span class='dialog-filename'>) {0}</span> letöltése közben",
  "ERR_TYPE_PASTE_FAILED": "Hiba történt a(z <span class='dialog-filename'>) {0}</span> beillesztése közben ide: <span class='dialog-filename'>{1}</span>",
  "CANNOT_DUPLICATE_TITLE": "Nem lehet másolni",
  "ERR_TYPE_DUPLICATE_FAILED": "Hiba történt a(z <span class='dialog-filename'>) {0}</span> másolása közben",
  "ERR_TYPE_DUPLICATE_FAILED_NO_FILE": "Kérjük, válasszon egy fájlt a sokszorosításhoz.",
  "INVALID_FILENAME_MESSAGE": "A fájl neve nem tartalmazhatja a következő karaktereket: {0} és foglalt rendszer neveket.",
  "ENTRY_WITH_SAME_NAME_EXISTS": "Már létezik <span class='dialog-filename'>{0}</span> nevű fájl vagy könyvtár.",
  "ERROR_CREATING_FILE_TITLE": "Hiba történt a fájl létrehozása közben.",
  "ERROR_CREATING_FILE": "Hiba történt a fájl létrehozása közben: <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_MIXED_DRAGDROP": "Egy mappa nem nyitható meg más fájlok megnyitásával egyidejűleg.",
  "DROP_TO_OPEN_FILES": "Húzza le a fájlok megnyitásához",
  "DROP_TO_OPEN_FILE": "Emelje le a fájl megnyitásához",
  "DROP_TO_OPEN_PROJECT": "Húzza le a `{0}` mappát projektként",
  "ERROR_KEYMAP_TITLE": "Hiba a felhasználói kulcstérkép olvasásakor",
  "ERROR_KEYMAP_CORRUPT": "A kulcsleképezési fájl nem érvényes JSON. A fájl megnyílik a formátum javításához.",
  "ERROR_LOADING_KEYMAP": "A kulcsleképezési fájl nem érvényes UTF-8 kódolású szövegfájl, és nem tölthető be",
  "ERROR_RESTRICTED_COMMANDS": "Nem rendelhet újra parancsikonokat ezekhez a parancsokhoz: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "Nem rendelheti újra ezeket a parancsikonokat: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "Több parancsikont is hozzárendel ezekhez a parancsokhoz: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "Több kötése is van ezeknek a parancsikonoknak: {0}",
  "ERROR_INVALID_SHORTCUTS": "Ezek a parancsikonok érvénytelenek: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "Parancsikonokat rendel nem létező parancsokhoz: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "Hiba a beállítások olvasása közben",
  "ERROR_PREFS_RESET_TITLE": "Beállítások visszaállítása – Újraindítás szükséges",
  "ERROR_PREFS_PROJECT_LINT": "Projektbeállítások",
  "ERROR_PREFS_PROJECT_LINT_MESSAGE": "Hiba: A projekt .brackets.json és .phcode.json fájlokat is tartalmaz, ami ütközést okoz. Kérjük, törölje a \".brackets.json\" vagy a \".phcode.json\" fájlt, majd töltse be újra a projektet.",
  "ERROR_PREFS_CORRUPT": "A beállításfájl nem érvényes JSON. A fájl megnyílik a formátum javításához. A módosítások életbe léptetéséhez újra kell indítania a(z) {APP_NAME} alkalmazást.",
  "ERROR_PREFS_CORRUPT_RESET": "A(z) {APP_NAME} beállításai sérültek, és visszaállításra kerültek. Kérjük, indítsa újra a(z) {APP_NAME} alkalmazást, hogy a módosítások életbe lépjenek.",
  "ERROR_PROJ_PREFS_CORRUPT": "A projektbeállítások fájlja nem érvényes JSON. A fájl megnyílik a formátum javításához. A változtatások életbe lépéséhez újra be kell töltenie a projektet.",
  "ERROR_IN_BROWSER_TITLE": "Oops! A {APP_NAME} még nem fut böngészőben.",
  "ERROR_IN_BROWSER": "A {APP_NAME} HTML-ben épült, de jelenleg asztali alkalmazásként fut, ezért helyi fájlokat is tudsz vele szerkeszteni. Kérlek használd az alkalmazás \"burkot\" a {APP_NAME} futtatásához: <b>github.com/adobe/brackets-shell</b>.",
  "ERROR_MAX_FILES_TITLE": "Hiba a fájlok Indexszelése közben",
  "ERROR_MAX_FILES": "A maximális fájlszám indexelésre került. Folyamatok amelyek a fájlokat az indexben keresik esélyes hogy nem fognak rendesen működni.",
  "UNSUPPORTED_DOM_APIS_CONFIRM": "A \"window.confirm\" és a \"window.prompt\" API nem érhető el a(z) {APP_NAME} beágyazott élő előnézetében. Az API-k böngészőben való használatához nyissa ki az Élő előnézetet.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "Hiba a böngésző megnyitása közben",
  "ERROR_CANT_FIND_CHROME": "A Google Chrome böngésző nem található. Bizonyosodj meg hogy telepítve van.",
  "ERROR_LAUNCHING_BROWSER": "Hiba a böngésző megnyitása közben: (hiba {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "Élő Előnézet hiba",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "Csatlakozás a Böngészőhöz",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "Az Élő Előnézet használatához muszály újraindítani a Chrome-ot a megfelelő beállításokkal.<br /><br />Szeretnéd most újraindítani a Chrome-ot ezekkel a beállításokkal?",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "Nem lehet betölteni az Élő Fejlesztő oldalt",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "Az Élő Előnézet használatához szerver-oldali fájlokkal meg kell adni az alap URL-t a projekthez.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "Hiba a HTTP szerver indításakor az Élő Fejlesztéshez. Kérlek próbáld újra később.",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "További információért lásd: <a href='{0}' title='{0}'>Élő Előnézet csatlakozási hibák kiküszöbölése</a>.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "Élő Előnézet",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "Élő Előnézet: Csatlakozás…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "Élő Előnézet: Inicializálás…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "Élő előnézeti kiszolgáló aktív",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "Élő Előnézet",
  "LIVE_DEV_TOOLTIP_SHOW_IN_EDITOR": "{0} – Megjelenítés a Szerkesztőben…",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "Válassza a File To Live Preview lehetőséget",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "Oldal újratöltése",
  "LIVE_DEV_TOGGLE_LIVE_HIGHLIGHT": "Kapcsolja be az Élő előnézeti kiemeléseket",
  "LIVE_DEV_CLICK_POPOUT": "Élő előnézet megnyitása új ablakba",
  "LIVE_DEV_OPEN_CHROME": "Megnyitás Chrome-ban…",
  "LIVE_DEV_OPEN_SAFARI": "Megnyitás Safariban…",
  "LIVE_DEV_OPEN_EDGE": "Megnyitás az Edge-ben…",
  "LIVE_DEV_OPEN_FIREFOX": "Megnyitás Firefoxban…",
  "LIVE_DEV_OPEN_ERROR_TITLE": "Hiba az élő előnézet megnyitásakor itt: {0}",
  "LIVE_DEV_OPEN_ERROR_MESSAGE": "Győződjön meg arról, hogy a(z) {0} böngésző telepítve van, és próbálja újra.",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "Előnézeti oldal rögzítése vagy rögzítésének feloldása",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "Élő előnézet (szintaktikai hiba miatt nem frissül)",
  "LIVE_DEV_SETTINGS": "Élő előnézet beállításai…",
  "LIVE_DEV_SETTINGS_BANNER": "Állítson be egyéni szervert a ` <b>{0}</b> ` és más szerver által renderelt fájlok (PHP, JSP stb.) élő előnézetéhez.",
  "LIVE_DEV_SETTINGS_TITLE": "Élő előnézet beállításai",
  "LIVE_DEV_SETTINGS_STARTUP": "Az Élő előnézeti panel megjelenítése indításkor",
  "LIVE_DEV_SETTINGS_SERVER_PREFERENCE": "igaz az egyéni fejlesztői szerver engedélyezéséhez",
  "LIVE_DEV_SETTINGS_STARTUP_PREFERENCE": "igaz az Élő előnézeti panel megjelenítéséhez indításkor",
  "LIVE_DEV_SETTINGS_HOT_RELOAD_PREFERENCE": "igaz, ha a kiszolgáló támogatja a gyors újratöltést, és mentéskor letiltja a Live Preview újratöltést",
  "LIVE_DEV_SETTINGS_USE_SERVER": "Használjon egyéni fejlesztési kiszolgálót ehhez a projekthez",
  "LIVE_DEV_SETTINGS_SERVE_PREFERENCE": "A projekt fejlesztői szerverének URL-címe, pl. http://localhost:8000/php",
  "LIVE_DEV_SETTINGS_SERVER_INBUILT": "Például. http://localhost:8000/php – Jelenleg beépített szervert használ.",
  "LIVE_DEV_SETTINGS_SERVER_ROOT": "Mappa kiszolgálása a projektben",
  "LIVE_DEV_SETTINGS_SERVER_ROOT_HELP": "Például. www/ (alapértelmezett a /)",
  "LIVE_DEV_SETTINGS_SERVER_ROOT_PREF": "Útvonal a projekten belül, amelyet a Development Server szolgál ki, pl. www/ (alapértelmezett a /)",
  "LIVE_DEV_SETTINGS_RELOAD": "A szerver támogatja a forró újratöltést",
  "LIVE_DEV_SETTINGS_RELOAD_HELP": "Egyes szerverek támogatják a gyors újratöltést, ahol a kódmódosítások teljes oldal újratöltés nélkül kerülnek át az oldalra.\nEngedélyezze ezt a funkciót, ha nem szeretné, hogy a {APP_NAME} minden mentéskor újratöltse az oldalt.",
  "LIVE_DEV_SETTINGS_FRAMEWORK": "Szerver keretrendszer",
  "LIVE_DEV_SETTINGS_FRAMEWORK_CUSTOM": "Egyedi",
  "LIVE_DEV_SETTINGS_FRAMEWORK_PREFERENCES": "Server Framework, jelenleg csak a docusaurust támogatja",
  "LIVE_PREVIEW_CUSTOM_SERVER_BANNER": "Előnézet letöltése egyéni szerveréről {0}",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "Az Élő Előnézet lecsatlakozott mert a bongésző fejlesztő eszközei meg lettek nyitva",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "Az Élő Előnézet lecsatlakozott mert az oldal be lett zárva a böngészőben",
  "LIVE_DEV_NAVIGATED_AWAY": "Az Élő Előnézet lecsatlakozott mert a böngésző olyan oldalra lépett amely nem része a jelenlegi projektnek",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "Az Élő Előnézet lecsatlakozott ismeretlen ok miatt ({0})",
  "SAVE_CLOSE_TITLE": "Változtatások mentése",
  "SAVE_CLOSE_MESSAGE": "El szeretnéd menteni a változtatásokat itt: <span class='dialog-filename'>{0}</span>?",
  "SAVE_CLOSE_MULTI_MESSAGE": "El szeretnéd menteni a változtatásokat a következő fájlokban?",
  "EXT_MODIFIED_TITLE": "Külső Változtatások",
  "CONFIRM_DELETE_TITLE": "Törlés jóváhagyása",
  "CONFIRM_FILE_DELETE": "Biztosan törli a(z) <span class='dialog-filename'>{0}</span> fájlt?",
  "CONFIRM_FOLDER_DELETE": "Biztosan törli a(z <span class='dialog-filename'>) {0}</span> mappát?",
  "CONFIRM_FILE_DELETE_TRASH": "Biztosan törli a(z) <span class='dialog-filename'>{0}</span> fájlt?<br> Ezt a fájlt visszaállíthatja a kukából.",
  "CONFIRM_FOLDER_DELETE_TRASH": "Biztosan törli a(z) <span class='dialog-filename'>{0}</span> mappát?<br> Ezt a mappát visszaállíthatja a kukából.",
  "CONFIRM_FILE_DELETE_RECYCLE_BIN": "Biztosan törli a(z) <span class='dialog-filename'>{0}</span> fájlt?<br> Ezt a fájlt visszaállíthatja a Lomtárból.",
  "CONFIRM_FOLDER_DELETE_RECYCLE_BIN": "Biztosan törli a(z) <span class='dialog-filename'>{0}</span> mappát?<br> Ezt a mappát visszaállíthatja a Lomtárból.",
  "MOVE_TO_TRASH": "Kidobni a kukába",
  "MOVE_TO_RECYCLE_BIN": "Menjen a Lomtárba",
  "FILE_DELETED_TITLE": "Fájl törölve",
  "EXT_MODIFIED_WARNING": "A(z) <span class='dialog-filename'>{0}</span> a(z) {APP_NAME} alkalmazáson kívüli lemezen módosult.<br /><br /> Menti a fájlt, és felülírja a változtatásokat?",
  "EXT_MODIFIED_MESSAGE": "A/az <span class='dialog-filename'>{0}</span> meg lett változtatva a lemezen, de tartalmaz nem mentet változtatásokat is a {APP_NAME}-ben.<br /><br />Melyik verziót szeretnéd megtartani?",
  "EXT_DELETED_MESSAGE": "A/az <span class='dialog-filename'>{0}</span> törölve lett a lemezen, de tartalmaz nem mentet változtatásokat is a {APP_NAME}-ben.<br /><br />Meg szeretnéd tartani a változtatásokat?",
  "EXT_ALWAYS_MODIFIED_BUTTON_TOOLTIP": "Mindig írja felül a fájlokat a projektváltásig vagy újraindításig",
  "WINDOW_UNLOAD_WARNING": "Biztosan egy másik URL-re szeretne navigálni, és kilép a(z) {APP_NAME} alkalmazásból?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "Nem mentett módosításai vannak! Biztosan egy másik URL-re szeretne navigálni, és kilép a(z) {APP_NAME} alkalmazásból?",
  "DONE": "Kész",
  "OK": "OK",
  "CANCEL": "Mégsem",
  "DONT_SAVE": "Ne Mentse",
  "SAVE": "Mentés",
  "SAVE_AS": "Mentés másként…",
  "SAVE_AND_OVERWRITE": "Felülírás",
  "ALWAYS_OVERWRITE": "Mindig felülírja",
  "DELETE": "Töröl",
  "BUTTON_YES": "Igen",
  "BUTTON_NO": "Nem",
  "FIND_MATCH_INDEX": "{0}/{1}",
  "FIND_NO_RESULTS": "Nincs eredmény",
  "FIND_QUERY_PLACEHOLDER": "Megtalálja…",
  "FIND_HISTORY_MAX_COUNT": "Keresési elemek maximális száma a keresési előzményekben",
  "REPLACE_PLACEHOLDER": "Cseréld ki…",
  "BUTTON_REPLACE_ALL": "Cserélje ki az összeset",
  "BUTTON_REPLACE_BATCH": "Batch…",
  "BUTTON_REPLACE_ALL_IN_FILES": "Csere…",
  "BUTTON_REPLACE": "Csere",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "Következő Találat",
  "BUTTON_PREV_HINT": "Előző Találat",
  "BUTTON_CASESENSITIVE_HINT": "Mérkőzés esetén",
  "BUTTON_REGEXP_HINT": "Reguláris kifejezés",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "Csere visszavonás nélkül",
  "REPLACE_WITHOUT_UNDO_WARNING": "Mivel több mint {0} fájlt kell módosítani, a(z) {APP_NAME} módosítja a meg nem nyitott fájlokat a lemezen.<br /> Nem tudja visszavonni a cseréket ezekben a fájlokban.",
  "BUTTON_REPLACE_WITHOUT_UNDO": "Csere visszavonás nélkül",
  "OPEN_FILE": "Fájl megnyitása",
  "SAVE_FILE_AS": "Fájl mentése",
  "CHOOSE_FOLDER": "Válassz mappát",
  "RELEASE_NOTES": "Kiadási megjegyzések",
  "NO_UPDATE_TITLE": "A legfrissebb verziót használod!",
  "NO_UPDATE_MESSAGE": "A legfrissebb {APP_NAME} fut.",
  "FIND_REPLACE_TITLE_LABEL": "Csere",
  "FIND_REPLACE_TITLE_WITH": "val vel",
  "FIND_TITLE_LABEL": "Megtalált",
  "FIND_TITLE_SUMMARY": "&mdash; {0} {1} {2} itt: {3}",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "a <span class='dialog-filename'>{0}</span>-ban",
  "FIND_IN_FILES_NO_SCOPE": "a projektben",
  "FIND_IN_FILES_PROJECT_SCOPE": "Keresse meg a projektben",
  "FIND_IN_FILES_PROJECT_SCOPE_FILTER": "Keresés itt: {0}",
  "FIND_IN_FILES_PROJECT_SCOPE_REPLACE": "Cserélje ki a projektben",
  "FIND_IN_FILES_PROJECT_SCOPE_REPLACE_FILTER": "Csere itt: {0}",
  "FIND_IN_FILES_ZERO_FILES": "A szűrő kizárja az összes fájlt {0}",
  "FIND_IN_FILES_FILE": "fájl",
  "FIND_IN_FILES_FILES": "fájlok",
  "FIND_IN_FILES_MATCH": "találat",
  "FIND_IN_FILES_MATCHES": "találatok",
  "FIND_IN_FILES_MORE_THAN": "Több mint ",
  "FIND_IN_FILES_PAGING": "{0}&mdash;{1}",
  "FIND_IN_FILES_FILE_PATH": "Fájl: <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "Ctrl/Cmd kattintson az összes kibontásához/összecsukásához",
  "FIND_IN_FILES_INDEXING": "Indexelés az azonnali kereséshez…",
  "FIND_IN_FILES_SEARCHING": "Fájlok keresése…",
  "FIND_IN_FILES_SEARCHING_IN": "Itt: {0}",
  "FIND_IN_FILES_INDEXING_PROGRESS": "{0}/{1} fájl indexelése az Azonnali kereséshez…",
  "REPLACE_IN_FILES_ERRORS_TITLE": "Cserélje ki a hibákat",
  "REPLACE_IN_FILES_ERRORS": "A következő fájlok nem módosultak, mert megváltoztak a keresés után, vagy nem lehetett őket írni.",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "Hiba a frissítési infó lekérdezése közben",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "Hiba történt a legfrissebb frissítési infó lekérdezése közben. Győződj meg arról hogy van internet kapcsolatod, majd próbáld meg újra.",
  "NEW_FILE_FILTER": "Új kizárási készlet…",
  "CLEAR_FILE_FILTER": "Ne zárjon ki fájlokat",
  "NO_FILE_FILTER": "Nincsenek kizárt fájlok",
  "EXCLUDE_FILE_FILTER": "Fájlok kizárása",
  "INCLUDE_FILE_FILTER": "Keresés a fájlokban",
  "FILTER_PLACEHOLDER": "például. index,.css,*.js,src/**/*.css",
  "FILTER_HISTORY_TOOLTIP": "Nyomja meg a Ctrl-Szóköz billentyűket az előzmények megtekintéséhez.",
  "FILTER_HISTORY_TOOLTIP_MAC": "Nyomja meg a „Cmd-Space” billentyűt az előzmények megtekintéséhez.",
  "FIND_HISTORY_TOOLTIP": "Nyomja meg a Ctrl-Szóköz billentyűket az előzmények megtekintéséhez.",
  "FIND_HISTORY_TOOLTIP_MAC": "Nyomja meg a „Cmd-Space” billentyűt az előzmények megtekintéséhez.",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "A kurzor aktuális pozíciójához nem érhető el gyorsszerkesztés",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "CSS gyorsszerkesztés: helyezze a kurzort egyetlen osztálynévre",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "CSS gyorsszerkesztés: hiányos osztályattribútum",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "CSS gyorsszerkesztés: hiányos azonosító attribútum",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "CSS gyorsszerkesztés: helyezze a kurzort a címkébe, osztályba vagy azonosítóba",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "CSS időzítési funkció Gyors szerkesztés: érvénytelen szintaxis",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "JS Gyorsszerkesztés: helyezze a kurzort a függvény nevébe",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "A kurzor aktuális pozíciójához nem érhető el Gyorsdokumentum",
  "PROJECT_LOADING": "Betöltés…",
  "UNTITLED": "Névtelen",
  "WORKING_FILES": "Munka fájlok",
  "TOP": "Top",
  "BOTTOM": "Alsó",
  "LEFT": "Bal",
  "RIGHT": "Jobb",
  "CMD_SPLITVIEW_NONE": "Nem Split",
  "CMD_SPLITVIEW_VERTICAL": "Függőleges felosztás",
  "CMD_SPLITVIEW_HORIZONTAL": "Vízszintes felosztás",
  "SPLITVIEW_MENU_TOOLTIP": "A szerkesztő felosztása függőlegesen vagy vízszintesen",
  "GEAR_MENU_TOOLTIP": "Munkakészlet konfigurálása",
  "SPLITVIEW_INFO_TITLE": "Már nyitva",
  "SPLITVIEW_MULTIPANE_WARNING": "A fájl már meg van nyitva egy másik ablaktáblában. A {APP_NAME} hamarosan támogatja ugyanannak a fájlnak egynél több panelen való megnyitását. Addig a fájl abban az ablaktáblában jelenik meg, amelyben már meg van nyitva.<br /><br /> (Ez az üzenet csak egyszer jelenik meg.)",
  "KEYBOARD_OVERLAY_TEXT": "Használja a nyilakat a navigáláshoz, vagy írja be a kezelőfelület elemeit.",
  "KEYBOARD_SHORTCUT_CHANGE_TITLE": "Billentyűparancs módosítása…",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_TITLE": "Billentyűparancs módosítása",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_TEXT": "Nyomja meg a <b>(z) &#39;{0}&#39;</b> új billentyűkombinációját (jelenleg: <b>{1}</b> )",
  "KEYBOARD_SHORTCUT_CHANGE_DIALOG_DUPLICATE": "Figyelmeztetés: A <b>(z) {0}</b> billentyűkombináció már hozzá van rendelve a <b>(z) &#39;{1}&#39;</b> -hez. Újra hozzárendeli a következőhöz <b>: &#39;{2}&#39;</b> ?",
  "KEYBOARD_SHORTCUT_ASSIGN": "Hozzárendelni",
  "KEYBOARD_SHORTCUT_NONE": "Egyik sem",
  "KEYBOARD_SHORTCUT_MENU_SHOW_SHORTCUTS": "Gyorsbillentyűket…",
  "KEYBOARD_SHORTCUT_MENU_SHOW_SHORTCUTS_BUTTON": "Az összes billentyűparancs megjelenítése…",
  "KEYBOARD_SHORTCUT_TABLE_BASE_KEY": "Alapkulcs",
  "KEYBOARD_SHORTCUT_TABLE_KEY_BINDING": "Parancsikon",
  "KEYBOARD_SHORTCUT_TABLE_COMMAND_ID": "Parancsazonosító",
  "KEYBOARD_SHORTCUT_TABLE_COMMAND_NAME": "Parancs",
  "KEYBOARD_SHORTCUT_TABLE_DOUBLE_CLICK": "Kattintson duplán a parancsikon módosításához",
  "KEYBOARD_SHORTCUT_TABLE_ORIGIN": "Eredet",
  "KEYBOARD_SHORTCUT_ORIG_EXTENSION": "Kiterjesztés",
  "KEYBOARD_SHORTCUT_PANEL_TITLE": "Gyorsbillentyűket",
  "KEYBOARD_SHORTCUT_PRESET_TOOLTIP": "Használja az olyan szerkesztők billentyűparancsait, mint a VSCode, WebStorm vagy a Sublime Text",
  "KEYBOARD_SHORTCUT_PRESET_SELECT": "Válassza a Parancsikon-előbeállítások lehetőséget",
  "KEYBOARD_SHORTCUT_PRESET_USING": "{0} használata",
  "DEFAULT": "Alapértelmezett",
  "KEYBOARD_SHORTCUT_PANEL_FILTER": "Szűrés&hellip;",
  "KEYBOARD_SHORTCUT_PANEL_RESET": "Visszaállítás…",
  "KEYBOARD_SHORTCUT_PANEL_RESET_DEFAULT": "Visszaállítás az alapértelmezett gyorsbillentyűkre…",
  "KEYBOARD_SHORTCUT_RESET_DIALOG_TITLE": "Billentyűparancsok visszaállítása",
  "KEYBOARD_SHORTCUT_RESET_DIALOG_MESSAGE": "Visszaállítja az összes egyéni parancsikont az alapértelmezettre? Ezt nem lehet visszacsinálni.",
  "KEYBOARD_SHORTCUT_SRC_USER": "Felhasználó által meghatározott",
  "KEYBOARD_SHORTCUT_SRC_PRESET": "{0} Előre beállított",
  "STATUSBAR_CURSOR_POSITION": "Sor {0}, Oszlop {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": " – Kijelölt {0} oszlop",
  "STATUSBAR_SELECTION_CH_PLURAL": " – Kijelölt {0} oszlop",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " – Kijelölt {0} sor",
  "STATUSBAR_SELECTION_LINE_PLURAL": " – Kijelölt {0} sor",
  "STATUSBAR_SELECTION_MULTIPLE": " – {0} kijelölés",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "Kattints hogy átváltsd a behúzást space-re",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "Kattints hogy átváltsd a behúzást tabokra",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "Kattints hogy átváltsd a behúzás space-ek számát",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "Kattints hogy átváltsd a tab szélességét",
  "STATUSBAR_SPACES": "Szóközök",
  "STATUSBAR_TAB_SIZE": "Tab Mérete",
  "STATUSBAR_AUTO_INDENT": "<span title=\"Kattintson a rögzített behúzásokra váltáshoz. Jelenleg úgy van beállítva, hogy az aktuális fájl alapján automatikusan észlelje és alkalmazza a behúzásokat.\">Auto</span>",
  "STATUSBAR_FIXED_INDENT": "<span title=\"Kattintson az Automatikus behúzás észlelésére való váltáshoz. Jelenleg Fix behúzásra van állítva.\">Rögzített</span>",
  "STATUSBAR_LINE_COUNT_SINGULAR": "— {0} Sor",
  "STATUSBAR_LINE_COUNT_PLURAL": "— {0} Sor",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "A bővítmények letiltva",
  "STATUSBAR_INSERT": "INS",
  "STATUSBAR_OVERWRITE": "OVR",
  "STATUSBAR_INSOVR_TOOLTIP": "Kattintson a kurzor váltásához a Beszúrás (INS) és a Felülírás (OVR) módok között",
  "STATUSBAR_LANG_TOOLTIP": "Kattintson a fájltípus módosításához",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. Kattintson a jelentéspanel váltásához.",
  "STATUSBAR_DEFAULT_LANG": "(alapértelmezett)",
  "STATUSBAR_SET_DEFAULT_LANG": "Beállítás alapértelmezettként a .{0} Fájlokhoz",
  "STATUSBAR_ENCODING_TOOLTIP": "Válassza ki a kódolást",
  "STATUSBAR_TASKS": "Feladatok",
  "STATUSBAR_TASKS_TOOLTIP": "Aktív feladatok kezelése",
  "STATUSBAR_TASKS_HIDE_SPINNER": "Spinner ikon elrejtése",
  "STATUSBAR_TASKS_UNKNOWN_EXTENSION_TASK": "Ismeretlen bővítési feladat…",
  "STATUSBAR_TASKS_PLAY": "Indítás vagy Folytatás",
  "STATUSBAR_TASKS_PAUSE": "Szünet",
  "STATUSBAR_TASKS_STOP": "Állj meg",
  "STATUSBAR_TASKS_RESTART": "Újrakezd",
  "ERRORS_NO_FILE": "Nincs fájl megnyitva",
  "ERRORS_PANEL_TITLE_MULTIPLE": "{0} Problémák - {1}",
  "ERRORS_PANEL_TITLE_MULTIPLE_FIXABLE": "{0} Problémák, {1} Javítható - {2}",
  "SINGLE_ERROR": "1 {0} Probléma - {1}",
  "SINGLE_ERROR_FIXABLE": "1 {0} probléma, {1} javítható - {2}",
  "MULTIPLE_ERRORS": "{0} {1} Problémák - {2}",
  "MULTIPLE_ERRORS_FIXABLE": "{0} {1} Problémák, {2} Javítható - {3}",
  "NO_ERRORS": "Nem található {0} probléma – jó munkát!",
  "NO_ERRORS_MULTIPLE_PROVIDER": "Nem találtunk problémát – jó munkát!",
  "LINT_DISABLED": "A szöszölés le van tiltva",
  "NO_LINT_AVAILABLE": "Nem áll rendelkezésre linter a következőhöz: {0}",
  "NOTHING_TO_LINT": "Nincs mit szöszölni",
  "COPY_ERROR": "Másolási probléma",
  "FIX": "Fix",
  "CANNOT_FIX_TITLE": "Nem sikerült a javítás alkalmazása",
  "CANNOT_FIX_SOME_TITLE": "Egyes javítások alkalmazása nem sikerült",
  "CANNOT_FIX_MESSAGE": "A dokumentumot a javítás elkészítése óta módosították. Kérlek próbáld újra.",
  "LINTER_TIMED_OUT": "A(z) {0} {1} ms várakozás után időtúllépést ért el",
  "LINTER_FAILED": "A(z) {0} hibával leállt: {1}",
  "CLICK_VIEW_PROBLEM": "Kattintson a probléma megtekintéséhez a panelen",
  "FILE_MENU": "Fájl",
  "CMD_FILE_NEW_UNTITLED": "Új",
  "CMD_FILE_NEW": "Új Fájl",
  "CMD_FILE_DUPLICATE": "Duplikálás",
  "CMD_FILE_DUPLICATE_FILE": "Fájl megkettőzése",
  "CMD_FILE_DOWNLOAD_PROJECT": "Projekt letöltése",
  "CMD_FILE_DOWNLOAD": "Letöltés",
  "CMD_FILE_CUT": "Kivágás",
  "CMD_FILE_COPY": "Másolás",
  "CMD_FILE_COPY_PATH": "Útvonal másolása",
  "CMD_FILE_PASTE": "Beillesztés",
  "CMD_PROJECT_NEW": "Projekt indítása…",
  "CMD_FILE_NEW_FOLDER": "Új Mappa",
  "CMD_FILE_OPEN": "Fájlok megnyitása…",
  "CMD_RECENT_FILES_OPEN": "Legutóbbi fájlok…",
  "CMD_ADD_TO_WORKING_SET": "Hozzáadás a Munkakészlethez",
  "CMD_OPEN_DROPPED_FILES": "Nyissa meg az Eldobott fájlok elemet",
  "CMD_OPEN_FOLDER": "Mappa Megnyitása…",
  "CMD_FILE_CLOSE": "Bezárás",
  "CMD_FILE_CLOSE_ALL": "Összes Bezárása",
  "CMD_REOPEN_CLOSED": "Nyissa meg újra a zárt fájlt",
  "CMD_FILE_CLOSE_LIST": "Lista bezárása",
  "CMD_FILE_CLOSE_OTHERS": "Mások bezárása",
  "CMD_FILE_CLOSE_ABOVE": "Zárja be a többieket fent",
  "CMD_FILE_CLOSE_BELOW": "Zárja be az Egyebeket lent",
  "CMD_FILE_SAVE": "Fájl mentése",
  "CMD_FILE_SAVE_ALL": "Összes Mentése",
  "CMD_FILE_SAVE_AS": "Mentés másként…",
  "CMD_LIVE_FILE_PREVIEW": "Élő Előnézet",
  "CMD_LIVE_FILE_PREVIEW_SETTINGS": "Élő előnézet beállításai",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "Engedélyezze a kísérleti élő előnézetet",
  "CMD_RELOAD_LIVE_PREVIEW": "Újratöltés kényszerítése élő előnézet",
  "CMD_PROJECT_SETTINGS": "Projekt Beállítások…",
  "CMD_FILE_RENAME": "Átnevez",
  "CMD_FILE_DELETE": "Töröl",
  "CMD_INSTALL_EXTENSION": "Bővítmény Telepítése…",
  "CMD_EXTENSION_MANAGER": "Bővítménykezelő…",
  "CMD_FILE_REFRESH": "Újratöltés",
  "CMD_FILE_SHOW_FOLDERS_FIRST": "Először rendezze a mappákat",
  "CMD_QUIT": "Bezár",
  "CMD_EXIT": "Kilépés",
  "EDIT_MENU": "Szerkesztés",
  "CMD_UNDO": "Mégsem",
  "CMD_REDO": "Újra",
  "CMD_CUT": "Kivágás",
  "CMD_COPY": "Másolás",
  "CMD_PASTE": "Beillesztés",
  "CMD_SELECT_ALL": "Összes kijelölése",
  "CMD_SELECT_LINE": "Sor kijelölése",
  "CMD_SPLIT_SEL_INTO_LINES": "A kijelölés felosztása sorokra",
  "CMD_ADD_CUR_TO_NEXT_LINE": "Adja hozzá a kurzort a következő sorhoz",
  "CMD_ADD_CUR_TO_PREV_LINE": "Adja hozzá a kurzort az előző sorhoz",
  "CMD_INDENT": "Behúzás",
  "CMD_UNINDENT": "Behúzás visszavonása",
  "CMD_DUPLICATE": "Duplikálás",
  "CMD_DELETE_LINES": "Sor törlése",
  "CMD_COMMENT": "Sor komment bekapcsolása",
  "CMD_BLOCK_COMMENT": "Blokk komment bekapcsolása",
  "CMD_LINE_UP": "Sor Mozgatása Fel",
  "CMD_LINE_DOWN": "Sor Mozgatása le",
  "CMD_OPEN_LINE_ABOVE": "Sor Nyitása Felül",
  "CMD_OPEN_LINE_BELOW": "Sor Nyitása Alul",
  "CMD_TOGGLE_CLOSE_BRACKETS": "Zárójelek Automatikus Bezárása",
  "CMD_SHOW_CODE_HINTS": "Kód Súgó megjelenítése",
  "CMD_BEAUTIFY_CODE": "Szépít Code",
  "CMD_BEAUTIFY_CODE_ON_SAVE": "Szépítsd a kódot a mentés után",
  "CMD_AUTO_RENAME_TAGS": "HTML-címkék automatikus átnevezése",
  "FIND_MENU": "Keres",
  "CMD_FIND": "Keres",
  "CMD_FIND_NEXT": "Következő találat",
  "CMD_FIND_PREVIOUS": "Előző találat",
  "CMD_FIND_ALL_AND_SELECT": "Válassza az Összes előfordulás lehetőséget",
  "CMD_ADD_NEXT_MATCH": "Következő előfordulás hozzáadása",
  "CMD_SKIP_CURRENT_MATCH": "Kihagyás és következő előfordulás hozzáadása",
  "CMD_FIND_IN_FILES": "Keresés a Fájlokban",
  "CMD_FIND_IN_SUBTREE": "Keresés a…",
  "CMD_REPLACE": "Csere",
  "CMD_REPLACE_IN_FILES": "Csere a Fájlokban",
  "CMD_REPLACE_IN_SUBTREE": "Cserélje ki…",
  "VIEW_MENU": "Nézet",
  "CMD_HIDE_SIDEBAR": "Oldalsáv Elrejtése",
  "CMD_SHOW_SIDEBAR": "Oldalsáv Mutatása",
  "CMD_TOGGLE_SIDEBAR": "Kapcsolja be az oldalsávot",
  "CMD_TOGGLE_PANELS": "Panelek váltása",
  "CMD_TOGGLE_PURE_CODE": "Nincsenek zavaró tényezők",
  "CMD_TOGGLE_FULLSCREEN": "Teljes képernyő",
  "CMD_ZOOM_UI": "Zoom felhasználói felület és betűtípusok",
  "CMD_ZOOM_IN": "Nagyítás",
  "CMD_ZOOM_IN_SCALE": "Nagyítás (jelenleg: {0}%)",
  "CMD_ZOOM_OUT": "Kicsinyítés",
  "CMD_INCREASE_FONT_SIZE": "Font Méretének Nagyítása",
  "CMD_DECREASE_FONT_SIZE": "Font Méretének Kicsinyítése",
  "CMD_RESTORE_FONT_SIZE": "Font Méretének Visszaállítása",
  "CMD_SCROLL_LINE_UP": "Sor Lapozása Felfele",
  "CMD_SCROLL_LINE_DOWN": "Sor Lapozása Lefele",
  "CMD_TOGGLE_LINE_NUMBERS": "Sorok száma",
  "CMD_TOGGLE_ACTIVE_LINE": "Aktív sor megjelölése",
  "CMD_TOGGLE_WORD_WRAP": "Sortörés",
  "CMD_LIVE_HIGHLIGHT": "Élő Kijelölés",
  "CMD_VIEW_TOGGLE_INSPECTION": "Lint Files a Mentésben",
  "CMD_VIEW_TOGGLE_PROBLEMS": "Problémák",
  "CMD_WORKINGSET_SORT_BY_ADDED": "Rendezés Hozzáadás Szerint",
  "CMD_WORKINGSET_SORT_BY_NAME": "Rendezés Név Szerint",
  "CMD_WORKINGSET_SORT_BY_TYPE": "Rendezés Típus Szerint",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "Automatikus Rendezés",
  "CMD_THEMES": "Témák…",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "Keresés automatikus bezárása",
  "CMD_TOGGLE_RULERS": "Uralkodók",
  "CMD_KEYBOARD_NAV_OVERLAY": "Vizuális parancspaletta",
  "NAVIGATE_MENU": "Navigálás",
  "CMD_QUICK_OPEN": "Gyors megnyitás",
  "CMD_GOTO_LINE": "Ugrás Sorhoz",
  "CMD_GOTO_DEFINITION": "Gyors Definíció keresés",
  "CMD_GOTO_DEFINITION_PROJECT": "Gyorskeresés definíció a Projectben",
  "CMD_GOTO_FIRST_PROBLEM": "Lépjen az Első probléma elemre",
  "CMD_GOTO_NEXT_PROBLEM": "Lépjen a Következő probléma elemre",
  "CMD_GOTO_PREV_PROBLEM": "Lépjen az Előző probléma elemre",
  "CMD_TOGGLE_QUICK_EDIT": "Gyors Szerkesztés",
  "CMD_TOGGLE_QUICK_DOCS": "Gyors Dokumentáció",
  "CMD_QUICK_EDIT_PREV_MATCH": "Előző gyorsszerkesztési elem",
  "CMD_QUICK_EDIT_NEXT_MATCH": "Következő gyorsszerkesztési elem",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "Új szabály",
  "CMD_NEXT_DOC": "Következő Dokumentum",
  "CMD_PREV_DOC": "Előző Dokumentum",
  "CMD_NAVIGATE_BACKWARD": "Navigáljon vissza",
  "CMD_NAVIGATE_FORWARD": "Navigáljon előre",
  "CMD_NEXT_DOC_LIST_ORDER": "Következő dokumentum a listában",
  "CMD_PREV_DOC_LIST_ORDER": "Előző dokumentum a listában",
  "CMD_SHOW_IN_TREE": "Megjelenítés a Fastruktúrában",
  "CMD_SHOW_IN_EXPLORER": "Megjelenítés az Intézőben",
  "CMD_SHOW_IN_FINDER": "Megjelenítés a Finderben",
  "CMD_SHOW_IN_OS": "Megjelenítés az OS-fájlokban",
  "CMD_SWITCH_PANE_FOCUS": "Switch Pane Focus",
  "CMD_OPEN_VFS": "Nyissa meg a Virtuális fájlrendszert",
  "CMD_DIAGNOSTIC_TOOLS": "{APP_NAME} Diagnosztikai eszközök",
  "CMD_EXPERIMENTAL_FEATURES": "Kísérleti jellemzők",
  "CMD_ENABLE_DRAG_AND_DROP": "Drag and Drop Fájlok",
  "CMD_OPEN_EXTENSIONS_FOLDER": "Nyissa meg a Bővítmények mappát…",
  "CMD_OPEN_VIRTUAL_SERVER": "Nyissa meg a Virtuális szervert",
  "HELP_MENU": "Súgó",
  "CMD_CHECK_FOR_UPDATE": "Frissítések keresése…",
  "CMD_AUTO_UPDATE": "Automatikus frissítés",
  "CMD_HOW_TO_USE_BRACKETS": "{APP_NAME} használata",
  "CMD_SUPPORT": "{APP_NAME} támogatás",
  "CMD_DOCS": "Segítség, első lépések",
  "CMD_SUGGEST": "Javasolj egy funkciót",
  "CMD_RELEASE_NOTES": "Kiadási megjegyzések",
  "CMD_GET_INVOLVED": "Részt venni",
  "CMD_SHOW_EXTENSIONS_FOLDER": "Bővítmények mappa megjelenítése",
  "CMD_HEALTH_DATA_STATISTICS": "Egészségügyi jelentés…",
  "CMD_HOMEPAGE": "Alkalmazások letöltése - Kezdőlap",
  "CMD_TWITTER": "{TWITTER_NAME} a Twitter-en",
  "CMD_YOUTUBE": "Youtube csatorna",
  "CMD_ABOUT": "A {APP_TITLE}-ről",
  "CMD_OPEN_PREFERENCES": "Nyissa meg a Beállítások fájlt",
  "CMD_OPEN_KEYMAP": "Nyissa meg a felhasználói kulcstérkép fájlt",
  "EXPERIMENTAL_BUILD": "kísérleti verzió",
  "RELEASE_BUILD": "épít",
  "DEVELOPMENT_BUILD": "fejlesztési verzió",
  "PRERELEASE_BUILD": "kiadás előtti build",
  "RELOAD_FROM_DISK": "Újratöltés a lemezről",
  "KEEP_CHANGES_IN_EDITOR": "Változtatások megtartása a szerkesztőben",
  "CLOSE_DONT_SAVE": "Bezárás (Ne Mentse)",
  "RELAUNCH_CHROME": "Chrome Újraindítása",
  "ABOUT": "Rólunk",
  "CLOSE": "Bezárás",
  "ABOUT_TEXT_LINE1": "Kiadás: {VERSION_MAJOR}.{VERSION_MINOR} {BUILD_TYPE} {VERSION}",
  "ABOUT_TEXT_BUILD_TIMESTAMP": "építési időbélyeg:",
  "ABOUT_RELEASE_CREDITS": "Kiadási kreditek:",
  "ABOUT_TEXT_LINE3": "Harmadik fél általunk használt könyvtárak – <a href='https://github.com/phcode-dev/phoenix/tree/main/src/thirdparty/licences'>Licencek és forrásmegjelölések</a> .",
  "ABOUT_TEXT_LINE4": "Dokumentáció és forrás: <a href='https://github.com/phcode-dev/phoenix/'>https://github.com/phcode-dev/phoenix/</a>",
  "ABOUT_TEXT_LINE5": "Készítette ❤ és JavaScript segítségével:",
  "ABOUT_TEXT_LINE6": "Sok ember (de jelenleg problémáink vannak az adatok betöltésével).",
  "ABOUT_TEXT_MDN_DOCS": "A MDN Dokumentáció és a  MDN grafikai logó a Creative Commons Attribution license alatt vannak licencelve, <a href='{MDN_DOCS_LICENSE}'>CC-BY-SA 2.5 Unported</a>.",
  "UPDATE_NOTIFICATION_TOOLTIP": "Új {APP_NAME} verzió elérhető! Kattints ide a részletekért.",
  "UPDATE_NOT_AVAILABLE_TITLE": "A {APP_NAME} naprakész",
  "UPDATE_UP_TO_DATE": "Az Ön {APP_NAME} verziója a legújabb!",
  "UPDATE_AVAILABLE_TITLE": "Új verzió elérhető",
  "UPDATE_WHATS_NEW": "A(z) {APP_NAME} újdonságai",
  "UPDATE_READY_RESTART_TITLE": "Indítsa újra az alkalmazást a frissítéshez",
  "UPDATE_READY_RESTART_INSTALL_MESSAGE": "A(z) {APP_NAME} automatikusan frissül, ha bezár minden nyitott ablakot.",
  "UPDATE_FAILED_TITLE": "Frissítés sikertelen",
  "UPDATE_INSTALLING": "Frissítés telepítése…",
  "UPDATE_INSTALLING_MESSAGE": "Frissítés telepítése folyamatban: a(z) {APP_NAME} jelenleg a legújabb frissítéseket telepíti. Az alkalmazás automatikusan bezárul, amint a telepítés befejeződött.",
  "UPDATE_FAILED_MESSAGE": "Kérjük, zárja be az összes {APP_NAME} alkalmazásablakát, és nyissa meg újra az alkalmazást a frissítés újbóli próbálkozásához.<br/> A frissítést úgy is telepítheti, hogy letölti a telepítőt <a href='https://phcode.io'>a phcode.io</a> webhelyről",
  "UPDATE_FAILED_VISIT_SITE_MESSAGE": "Az újrapróbálkozáshoz lépjen ki a(z) {APP_NAME} összes példányából, és indítsa újra az alkalmazást.<br> Hamarosan a letöltési oldalunkra irányítjuk, ahonnan manuálisan letöltheti a legújabb verziót.",
  "UPDATE_MESSAGE": "Hé, új {APP_NAME} verzió elérhető. Íme néhány kulcsfontosságú frissítés:",
  "GET_IT_NOW": "Szerezd meg most!",
  "UPDATE_ON_EXIT": "Frissítés kilépéskor",
  "UPDATE_LATER": "Emlékeztess később",
  "UPDATE_DONE": "Indítsa újra a(z) {APP_NAME} frissítéséhez",
  "UPDATE_RESTART_INSTALL": "A frissítések telepítéséhez indítsa újra",
  "UPDATE_DOWNLOADING": "Telepítő letöltése",
  "INSTALL_WEBAPP": "Telepítse a(z) {APP_NAME} alkalmazást eszközére",
  "UPDATE_DOWNLOAD_PROGRESS": "Letöltés – {0}/{1} MB",
  "UPDATING_APP": "{APP_NAME} frissítése",
  "UPDATING_APP_MESSAGE": "Ez eltarthat egy ideig",
  "UPDATING_APP_DIALOG_MESSAGE": "Frissítés folyamatban. Továbbra is használhatja a(z) {APP_NAME} alkalmazást, amíg frissítünk.",
  "PROJECT_SETTINGS_TITLE": "Projekt Beállítások a következőhöz: {0}",
  "PROJECT_SETTING_BASE_URL": "Élő Előnézet alap URL",
  "PROJECT_SETTING_BASE_URL_HINT": "Helyi szerver használatához, írd be a címet pl.: http://localhost:8000/",
  "BASEURL_ERROR_INVALID_PROTOCOL": "A {0} protokol nem támogatott az Élő Előnézetben&mdash;kérlek használj http:-t vagy https:-t.",
  "BASEURL_ERROR_SEARCH_DISALLOWED": "Az alap URL nem tartalmazhat paramétereket mint: \"{0}\".",
  "BASEURL_ERROR_HASH_DISALLOWED": "Az alap URL nem tartalmazhat hash-okat mint: \"{0}\".",
  "BASEURL_ERROR_INVALID_CHAR": "Speciális karakterek mint: '{0}' muszáj enkódolni %-be.",
  "BASEURL_ERROR_UNKNOWN_ERROR": "Ismeretlen hiba az alap URL beolvasásakor",
  "EMPTY_VIEW_HEADER": "<em>Nyisson meg egy fájlt, miközben ez a panel fókuszban van</em>",
  "FLIPVIEW_BTN_TOOLTIP": "Fordítsa ezt a nézetet a következőre: {0}",
  "CURRENT_THEME": "Aktuális téma",
  "USE_THEME_SCROLLBARS": "Használja a téma görgetősávjait",
  "FONT_SIZE": "Betűméret",
  "FONT_FAMILY": "Betűtípus család",
  "THEMES_SETTINGS": "Témák beállításai",
  "THEMES_ERROR": "Témák hiba",
  "THEMES_ERROR_CANNOT_APPLY": "Hiba miatt nem sikerült alkalmazni a témát.",
  "BUTTON_NEW_RULE": "Új szabály",
  "INSTALL": "Telepítés",
  "APPLY": "Alkalmaz",
  "UPDATE": "Frissítés",
  "REMOVE": "Eltávolítás",
  "DISABLE": "Letiltás",
  "ENABLE": "Engedélyezze",
  "OVERWRITE": "Felülírás",
  "CANT_DROP_ZIP": "A zip fájlok eldobása hamarosan támogatott lesz...",
  "CANT_REMOVE_DEV": "Bővítmények a \"dev\" mappában csak manuálisan távolíthatóak el.",
  "CANT_UPDATE": "A frissítés nem kompatibilis a(z) {APP_NAME} ezen verziójával.",
  "CANT_UPDATE_DEV": "A „dev” mappában lévő bővítmények nem frissíthetők automatikusan.",
  "INSTALL_EXTENSION_TITLE": "Bővítmény telepítése",
  "UPDATE_EXTENSION_TITLE": "Bővítmény frissítése",
  "INSTALL_EXTENSION_LABEL": "Bővítmény URL",
  "INSTALL_EXTENSION_HINT": "A Bővítmény GitHub repo-jának ZIP URL-je",
  "INSTALLING_FROM": "Bővítmény telepítése: {0}…",
  "INSTALL_SUCCEEDED": "Sikeres telepítés!",
  "INSTALL_FAILED": "Sikertelen telepítés.",
  "CANCELING_INSTALL": "Telepítés lemondása…",
  "CANCELING_HUNG": "A Telepítés lemondása sokáig tart. Lehetséges hogy belső hiba történt.",
  "INSTALL_CANCELED": "Telepítés lemondva.",
  "VIEW_COMPLETE_DESCRIPTION": "Teljes leírás megtekintése",
  "VIEW_TRUNCATED_DESCRIPTION": "A csonka leírás megtekintése",
  "SORT_EXTENSION_METHOD": "A bővítmények rendezése a downloadCount vagy a publishedDate segítségével",
  "INVALID_ZIP_FILE": "A letöltött tartalom nem érvényes ZIP fájl.",
  "MISSING_PACKAGE_JSON": "A csomagban nincs package.json fájl.",
  "INVALID_PACKAGE_JSON": "A package.json fájl nem érvényes (hiba: {0}).",
  "MISSING_PACKAGE_NAME": "A package.json fájl nem határoz meg csomagnevet.",
  "BAD_PACKAGE_NAME": "A {0} nem érvényes csomagnév.",
  "MISSING_PACKAGE_VERSION": "A package.json fájl nem határoz meg csomagverziót.",
  "INVALID_VERSION_NUMBER": "A csomagverzió ({0}) nem érvényes.",
  "INVALID_BRACKETS_VERSION": "A {APP_NAME} kompatibilitási sor ({0}) nem érvényes.",
  "DISALLOWED_WORDS": "A ({1}) szavak nem engedélyezettek a {0} mezőben.",
  "NPM_INSTALL_FAILED": "npm telepítési parancs nem sikerült: {0}",
  "API_NOT_COMPATIBLE": "A Bővítmény nem kompatibilis a jelenlegi {APP_NAME} verzióval. A letiltott bővítmények közé lett telepítve.",
  "MISSING_MAIN": "A csomag nem tartalmaz main.js fájlt.",
  "EXTENSION_ALREADY_INSTALLED": "A csomag telepítésével felülíródik egy előzőleg telepített bővítmény. Folytatod?",
  "EXTENSION_SAME_VERSION": "A csomag verziója megegyezik a jelenleg telepítettével. Felülírod?",
  "EXTENSION_OLDER_VERSION": "A csomag verziója {0} ami régebbi mint a jelenlegi ({1}). Felülírod a jelenlegit?",
  "DOWNLOAD_ID_IN_USE": "Belső hiba: letöltő ID már használatban van.",
  "NO_SERVER_RESPONSE": "Nem lehet csatlakozni a szerverhez.",
  "BAD_HTTP_STATUS": "A fájl nem található a szerveren (HTTP {0}).",
  "CANNOT_WRITE_TEMP": "Nem lehet ideiglenes fájlba menteni a letöltést.",
  "ERROR_LOADING": "A bővítmény hibába ütközött indításkor.",
  "MALFORMED_URL": "Az URL helytelen. Nézd meg hogy jól írtad be.",
  "UNSUPPORTED_PROTOCOL": "Az URL muszáj http vagy https URL legyen.",
  "UNKNOWN_ERROR": "Ismeretlen belső hiba.",
  "EXTENSION_VERIFIED_PUBLISHER": "Ez a kiadó igazolta a(z) {0} tulajdonjogát",
  "EXTENSION_VERIFIED_SORT": "Ellenőrzött",
  "EXTENSION_STAR": "Csillag",
  "EXTENSION_STAR_SORT": "Csillagok értékelése",
  "EXTENSION_MANAGER_TITLE": "Bővítménykezelő",
  "EXTENSION_MANAGER_ERROR_LOAD": "Nem lehet elérni a bővítmény adatbázist. Kérlek próbáld meg később.",
  "EXTENSION_UPDATE_RESTART_TITLE": "Újraindítás a frissítéshez",
  "EXTENSION_UPDATE_RESTART_MESSAGE": "A frissített bővítmények betöltéséhez zárja be a(z) {APP_NAME} összes futó példányát, és indítsa újra az alkalmazást.",
  "INSTALL_EXTENSION_DRAG": "Húzza ide a .zip fájlt vagy",
  "INSTALL_EXTENSION_DROP": "A telepítéshez dobja a .zip fájlt",
  "INSTALL_EXTENSION_DROP_ERROR": "A telepítés/frissítés megszakadt a következő hibák miatt:",
  "INSTALL_FROM_URL": "Telepítés URL-ről…",
  "INSTALL_EXTENSION_VALIDATING": "Érvényesítés folyamatban...",
  "EXTENSION_AUTHOR": "Szerző",
  "EXTENSION_DATE": "Dátum",
  "EXTENSION_INCOMPATIBLE_NEWER": "Ez a bővítmény csak a {APP_NAME} újabb verziójához jó.",
  "EXTENSION_INCOMPATIBLE_OLDER": "Ez a bővítmény csak a {APP_NAME} régebbi verziójához jó",
  "EXTENSION_DEFAULT_FEATURE_PRESENT": "Lehet, hogy nincs szüksége erre a bővítményre. A(z) {APP_NAME} már rendelkezik ezzel a funkcióval.",
  "EXTENSION_LATEST_INCOMPATIBLE_NEWER": "A bővítmény {0}. verziójához a(z) {APP_NAME} újabb verziója szükséges. De telepítheti a korábbi verziót ({1}).",
  "EXTENSION_LATEST_INCOMPATIBLE_OLDER": "A bővítmény {0} verziója csak a {APP_NAME} régebbi verzióival működik. De telepítheti a korábbi verziót ({1}).",
  "EXTENSION_NO_DESCRIPTION": "Nincs leírás",
  "EXTENSION_MORE_INFO": "További infó...",
  "EXTENSION_ERROR": "Bővítmény hiba",
  "EXTENSION_KEYWORDS": "Kulcsszavak",
  "EXTENSION_TRANSLATED_USER_LANG": "Lefordítva {0} nyelvre, beleértve az Önét is",
  "EXTENSION_TRANSLATED_GENERAL": "Lefordítva {0} nyelvre",
  "EXTENSION_TRANSLATED_LANGS": "Ezt a bővítményt a következő nyelvekre fordították le: {0}",
  "EXTENSION_INSTALLED": "Telepítve",
  "EXTENSION_UPDATE_INSTALLED": "A bővítményfrissítés letöltve és telepítve lessz amikor kilépsz a {APP_NAME}-ből.",
  "EXTENSION_SEARCH_PLACEHOLDER": "Keresés",
  "EXTENSION_MORE_INFO_LINK": "Több",
  "EXTENSION_MANAGER_CREATE_EXTENSION": "+ Hozzon létre bővítményt",
  "EXTENSION_MANAGER_CREATE_THEME": "+ Téma létrehozása",
  "BROWSE_EXTENSIONS": "Bővítmények tallózása",
  "EXTENSION_MANAGER_REMOVE": "Bővítmény Eltávolítása",
  "EXTENSION_MANAGER_REMOVE_ERROR": "Nem lehet eltávolítani egy vagy több bővítményt: {0}. A {APP_NAME} ki fog lépni.",
  "EXTENSION_MANAGER_UPDATE": "Bővítmény frissítése",
  "EXTENSION_MANAGER_UPDATE_ERROR": "Nem lehet frissíteni egy vagy több bővítményt: {0}. A {APP_NAME} ki fog lépni.",
  "EXTENSION_MANAGER_DISABLE": "Kiterjesztés letiltása",
  "EXTENSION_MANAGER_DISABLE_ERROR": "Nem lehet letiltani egy vagy több bővítményt: {0}. A {APP_NAME} továbbra is újratöltődik.",
  "EXTENSION_MANAGER_THEMES_INFO": "Az <a class=\"theme_settings\">alapértelmezett témák kiválasztásához</a> vagy más témabeállítások módosításához <a class=\"theme_settings\">kattintson ide</a> .",
  "EXTENSION_MANAGER_THEMES_UNDO": "Visszatérés az előző témához",
  "MARKED_FOR_REMOVAL": "Eltávolításhoz megjelölve",
  "UNDO_REMOVE": "Mégsem",
  "MARKED_FOR_UPDATE": "Frissítéshez megjelölve",
  "UNDO_UPDATE": "Mégsem",
  "MARKED_FOR_DISABLING": "Letiltásra megjelölve",
  "UNDO_DISABLE": "Mégsem",
  "CHANGE_AND_RELOAD_TITLE": "Bővítmények módosítása",
  "CHANGE_AND_RELOAD_MESSAGE": "A megjelölt bővítmények frissítéséhez, eltávolításához vagy letiltásához a(z) {APP_NAME} alkalmazást újra be kell tölteni. A rendszer felkéri a nem mentett módosítások mentésére.",
  "REMOVE_AND_RELOAD": "Távolítsa el a bővítményeket és töltse be újra",
  "CHANGE_AND_RELOAD": "Bővítmények módosítása és újratöltés",
  "UPDATE_AND_RELOAD": "Frissítse a bővítményeket és töltse be újra",
  "DISABLE_AND_RELOAD": "A bővítmények letiltása és az újratöltés",
  "PROCESSING_EXTENSIONS": "Bővítmény módosításainak feldolgozása…",
  "EXTENSION_NOT_INSTALLED": "A {0} bővítményt nem lehet eltávolítani, mert nincs telepítve.",
  "NO_EXTENSIONS": "Nincs még telepített bővítmény.<br>Kattints a Telepítés URL-ről gombra a kezdéshez.",
  "NO_EXTENSION_MATCHES": "Nincs bővítmény a keresett szavakra.",
  "REGISTRY_SANITY_CHECK_WARNING": "MEGJEGYZÉS: Ezek a bővítmények más szerzőktől származhatnak, mint maga a {APP_NAME}. A bővítményeket nem vizsgáljuk felül, és teljes helyi jogosultsággal rendelkeznek. Legyen óvatos, amikor ismeretlen forrásból telepít bővítményeket.",
  "EXTENSIONS_INSTALLED_TITLE": "Telepítve",
  "EXTENSIONS_DEFAULT_TITLE": "Alapértelmezett",
  "EXTENSIONS_AVAILABLE_TITLE": "Elérhető",
  "EXTENSIONS_THEMES_TITLE": "Témák",
  "EXTENSIONS_UPDATES_TITLE": "Frissítések",
  "EXTENSIONS_LAST_UPDATED": "Utolsó frissítés",
  "EXTENSIONS_DOWNLOADS": "Letöltések",
  "INLINE_EDITOR_NO_MATCHES": "Nincs találat.",
  "INLINE_EDITOR_HIDDEN_MATCHES": "Minden meccs összeomlott. Bontsa ki a jobb oldalon felsorolt fájlokat az egyezések megtekintéséhez.",
  "CSS_QUICK_EDIT_NO_MATCHES": "Nincsenek a kiválasztottnak megfelelő CSS-szabályok.<br> Kattintson az &quot;Új szabály&quot; gombra, hogy létrehozzon egyet.",
  "CSS_QUICK_EDIT_NO_STYLESHEETS": "A projektben nincsenek stíluslapok.<br> Hozzon létre egyet a CSS-szabályok hozzáadásához.",
  "IMAGE_VIEWER_LARGEST_ICON": "legnagyobb",
  "UNIT_PIXELS": "pixelek",
  "DEBUG_MENU": "Hibakeresés",
  "ERRORS": "Hibák",
  "CMD_SHOW_DEV_TOOLS": "{APP_NAME} Fejlesztői eszközök",
  "CMD_REFRESH_WINDOW": "A {APP_NAME} újratöltése",
  "CMD_LOAD_CURRENT_EXTENSION": "Projekt betöltése bővítményként",
  "CMD_RELOAD_CURRENT_EXTENSION": "Projekt újratöltése bővítményként",
  "CMD_UNLOAD_CURRENT_EXTENSION": "Töltse ki a projektet bővítményként",
  "CMD_RELOAD_WITHOUT_USER_EXTS": "Újratöltés bővítmények nélkül",
  "CMD_NEW_BRACKETS_WINDOW": "Új ablak",
  "CMD_LAUNCH_SCRIPT_MAC": "Telepítse a parancssori parancsikont",
  "CMD_SWITCH_LANGUAGE": "Nyelv váltása…",
  "CMD_RUN_UNIT_TESTS": "Futtassa a {APP_NAME} teszteket",
  "CMD_BUILD_TESTS": "Build Editor tesztek",
  "CMD_SHOW_PERF_DATA": "Teljesítmény adatok megjelenítése",
  "CMD_ENABLE_LOGGING": "Részletes naplók engedélyezése",
  "CMD_ENABLE_PHNODE_INSPECTOR": "A PhNode Inspector engedélyezése",
  "CMD_GET_PHNODE_INSPECTOR_URL": "A PhNode vizsgálata",
  "CMD_ENABLE_LIVE_PREVIEW_LOGS": "Élő előnézeti naplók",
  "CMD_OPEN_BRACKETS_SOURCE": "Nyissa meg a(z) {APP_NAME} forrását",
  "CREATING_LAUNCH_SCRIPT_TITLE": "A {APP_NAME} parancssori parancsikonja",
  "ERROR_CREATING_LAUNCH_SCRIPT": "Hiba történt a parancssori parancsikon telepítésekor. Kérjük, próbálja meg <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting'>ezeket a hibaelhárítási javaslatokat</a> .<br/><br/> Ok: {0}",
  "ERROR_CLTOOLS_RMFAILED": "Nem lehet eltávolítani a meglévő <code>/usr/local/bin/brackets</code> szimbolikus hivatkozást.",
  "ERROR_CLTOOLS_MKDIRFAILED": "Nem lehet létrehozni a <code>/usr/local/bin</code> könyvtárat.",
  "ERROR_CLTOOLS_LNFAILED": "Nem sikerült létrehozni a <code>/usr/local/bin/brackets</code> szimbolikus hivatkozást.",
  "ERROR_CLTOOLS_SERVFAILED": "Belső hiba.",
  "ERROR_CLTOOLS_NOTSUPPORTED": "A parancssori parancsikon nem támogatott ezen az operációs rendszeren.",
  "LAUNCH_SCRIPT_CREATE_SUCCESS": "Siker! Mostantól egyszerűen elindíthatja a(z) {APP_NAME} alkalmazást a parancssorból: <code>brackets myFile.txt</code> fájl megnyitásához, vagy <code>brackets myFolder</code> alkalmazáshoz a projektváltáshoz.<br/><br/> <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments'>További információ</a> a(z) {APP_NAME} parancssorból történő használatáról.",
  "ERROR_LOADING_EXTENSION": "Hiba a bővítmény betöltésekor",
  "ERROR_NO_EXTENSION_PACKAGE": "<code>package.json</code> fájl nem található az aktuális projektben. A jelenlegi projekt érvényes {APP_NAME} bővítmény?</br> További részletekért lásd <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>ezt a linket</a> .",
  "ERROR_INVALID_EXTENSION_PACKAGE": "<code>package.json</code> fájl érvénytelen JSON.</br> További részletekért lásd <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>ezt a linket</a> .",
  "ERROR_INVALID_EXTENSION_PACKAGE_FIELDS": "Hiányoznak a kötelező mezők <code>package.json</code> fájlból: [{0}]</br> További részletekért lásd <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>ezt a linket</a> .",
  "ERROR_NODE_JS_CRASH_TITLE": "Hoppá! Valami elromlott.",
  "ERROR_NODE_JS_CRASH_MESSAGE": "Hibába ütköztünk, és újra kell indítanunk a(z) {APP_NAME} alkalmazást. Ne aggódjon, megpróbáljuk menteni az összes munkáját az újraindítás előtt. </br>(Hiba: ERROR_NODE_JS_CRASH)",
  "LANGUAGE_TITLE": "Nyelv változtatása",
  "LANGUAGE_MESSAGE": "Nyelv:",
  "LANGUAGE_SUBMIT": "{APP_NAME} újratöltése",
  "LANGUAGE_CANCEL": "Mégsem",
  "LANGUAGE_SYSTEM_DEFAULT": "Rendszer Alapértelmezett",
  "HEALTH_DATA_NOTIFICATION": "Az állapotjelentés beállításai",
  "HEALTH_FIRST_POPUP_TITLE": "Adatvédelmi nyilatkozat",
  "HEALTH_DATA_DO_TRACK": "Névtelen információk megosztása arról, hogyan használom a(z) {APP_NAME} alkalmazást",
  "HEALTH_DATA_NOTIFICATION_MESSAGE": "A {APP_NAME} <strong>nem gyűjt és nem dolgoz fel semmilyen személyazonosításra alkalmas információt</strong> , de <strong>névtelen használati statisztikákat gyűjt</strong> az Ön adatainak védelme érdekében. Az anonim adatok mentesülnek a GDPR/CCPA értesítési követelményei alól, de úgy gondoljuk, hogy Önnek lehetősége van arra, hogy leiratkozzon az anonim adatgyűjtésről is.<br><br> Megtekintheti adatait, vagy <strong>dönthet úgy, hogy nem oszt meg névtelen adatokat</strong> , ha kiválasztja <strong>a Súgó &gt; Állapotjelentés lehetőséget</strong> . Ezek az <strong>anonim</strong> alkalmazáshasználati statisztikák és hibajelentések segítenek a funkciók prioritásainak meghatározásában, a hibák megtalálásában és a használhatósági problémák észlelésében, hogy javítsa a(z) {APP_NAME} alkalmazással kapcsolatos élményt. Ezen adatok nélkül nem tudnánk, milyen funkciókat érdemes építeni neked!<br><br>",
  "HEALTH_DATA_PREVIEW": "{APP_NAME} állapotjelentés",
  "HEALTH_DATA_PREVIEW_INTRO": "<p>A {APP_NAME} <strong>nem gyűjt és nem dolgoz fel semmilyen személyazonosításra alkalmas információt</strong> , de <strong>névtelen használati statisztikákat gyűjt</strong> az Ön adatainak védelme érdekében. Ezek az <strong>anonim</strong> alkalmazáshasználati statisztikák és hibajelentések segítenek a funkciók prioritásainak meghatározásában, a hibák megtalálásában és a használhatósági problémák észlelésében, hogy javítsa a(z) {APP_NAME} alkalmazással kapcsolatos élményt.</p><p> Az alábbiakban a következő állapotjelentésben elküldendő adatok előnézete látható <em>, ha</em> engedélyezve van. (Tekintse meg a fejlesztői konzolt is a „Caught Critical error” jelzésű hibanaplókért.)</p>",
  "INLINE_TIMING_EDITOR_TIME": "Idő",
  "INLINE_TIMING_EDITOR_PROGRESSION": "Haladás",
  "BEZIER_EDITOR_INFO": "<kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd> A kiválasztott pont mozgatása<br> <kbd class='text'>Shift</kbd> Mozgás tíz egységgel<br> <kbd class='text'>Tab</kbd> Kapcsolópontok",
  "STEPS_EDITOR_INFO": "<kbd>↑</kbd> <kbd>↓</kbd> Lépések növelése vagy csökkentése<br> <kbd>←</kbd> <kbd>→</kbd> &#39;Kezdés&#39; vagy &#39;Vége&#39;",
  "INLINE_TIMING_EDITOR_INVALID": "A régi <code>{0}</code> érték nem érvényes, ezért a megjelenített függvény a következőre módosult: <code>{1}</code> . A dokumentum az első szerkesztéssel frissül.",
  "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP": "Jelenlegi szín",
  "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP": "Eredeti szín",
  "COLOR_EDITOR_RGBA_BUTTON_TIP": "RGBa Formátum",
  "COLOR_EDITOR_HEX_BUTTON_TIP": "Hex Formátum",
  "COLOR_EDITOR_HSLA_BUTTON_TIP": "HSLa Formátum",
  "COLOR_EDITOR_0X_BUTTON_TIP": "Hex (0x) formátum",
  "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR": "{0} ({1}-szer használva)",
  "COLOR_EDITOR_USED_COLOR_TIP_PLURAL": "{0} ({1}-szer használva)",
  "EDIT": "Szerkesztés",
  "CMD_JUMPTO_DEFINITION": "Ugrás a Definícióhoz",
  "CMD_SHOW_PARAMETER_HINT": "Paraméter tipp megjelenítése",
  "NO_ARGUMENTS": "<nincs paraméter>",
  "DETECTED_EXCLUSION_TITLE": "JavaScript fájl következtetési probléma",
  "DETECTED_EXCLUSION_INFO": "A(z) {APP_NAME} problémába ütközött a(z <span class='dialog-filename'>) {0}</span> feldolgozása során.<br><br> Ez a fájl a továbbiakban nem kerül feldolgozásra kódtippek, Ugrás a definícióra vagy Gyorsszerkesztés céljából. A fájl újbóli engedélyezéséhez nyissa meg <code>.phcode.json</code> a projektben, és szerkessze <code>jscodehints.detectedExclusions</code> .<br><br> Ez valószínűleg a(z) {APP_NAME} programhibája. Ha tud másolatot adni erről a fájlról, kérjük <a href='https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue'>, küldjön be egy hibát</a> az itt megnevezett fájlra mutató hivatkozással.",
  "CMD_REFACTOR": "Refaktor",
  "CMD_EXTRACTTO_VARIABLE": "Kivonat változóba",
  "CMD_EXTRACTTO_FUNCTION": "Kivonat a funkcióhoz",
  "ERROR_TERN_FAILED": "Nem lehet adatokat lekérni Terntől",
  "ERROR_EXTRACTTO_VARIABLE_NOT_VALID": "A kijelölés nem alkot kifejezést",
  "ERROR_EXTRACTTO_FUNCTION_NOT_VALID": "A kiválasztott blokknak utasításkészletet vagy kifejezést kell képviselnie",
  "ERROR_EXTRACTTO_VARIABLE_MULTICURSORS": "Az Extract to Variable nem működik több kurzorban",
  "ERROR_EXTRACTTO_FUNCTION_MULTICURSORS": "A Funkció kibontása nem működik több kurzorban",
  "EXTRACTTO_FUNCTION_SELECT_SCOPE": "Válassza ki a cél hatókörét",
  "EXTRACTTO_VARIABLE_SELECT_EXPRESSION": "Válasszon ki egy kifejezést",
  "CMD_REFACTORING_RENAME": "Átnevez",
  "CMD_REFACTORING_TRY_CATCH": "Csomagolja be a Try Catch-et",
  "CMD_REFACTORING_CONDITION": "Állapotú csomagolás",
  "CMD_REFACTORING_GETTERS_SETTERS": "Getterek/Setterek létrehozása",
  "CMD_REFACTORING_ARROW_FUNCTION": "Konvertálás Arrow Funkcióvá",
  "DESCRIPTION_CODE_REFACTORING": "JavaScript kód újrafaktorálás engedélyezése/letiltása",
  "ERROR_TRY_CATCH": "Válassza ki az érvényes kódot a Try-catch blokkba csomagolni",
  "ERROR_WRAP_IN_CONDITION": "Válassza ki az érvényes kódot a feltétel blokkba burkoláshoz",
  "ERROR_ARROW_FUNCTION": "Helyezze a kurzort egy függvénykifejezés belsejébe",
  "ERROR_GETTERS_SETTERS": "Helyezze a kurzort egy objektumkifejezés egy tagjára",
  "ERROR_RENAME_MULTICURSOR": "Több kurzor használata esetén nem lehet átnevezni",
  "ERROR_RENAME_QUICKEDIT": "Ez az azonosító nem nevezhető át, mivel a függvényen kívül máshol hivatkoznak rá",
  "ERROR_RENAME_GENERAL": "A kiválasztott szöveget nem lehet átnevezni",
  "JSHINT_NAME": "JSHint",
  "JSHINT_CONFIG_ERROR": "Hiba a JSHint konfigurációs fájl olvasásakor: {0}",
  "JSHINT_CONFIG_JSON_ERROR": "Hiba: A `{0}` JSHint konfigurációs fájl nem érvényes JSON",
  "ESLINT_NAME": "ESLint",
  "CSS_LINT_NAME": "{0}",
  "HTML_LINT_NAME": "HTML",
  "HTML_LINT_CONFIG_JSON_ERROR": "Hiba: A HTML-ellenőrző `{0}` konfigurációs fájlja nem érvényes JSON",
  "HTML_LINT_CONFIG_UNSUPPORTED": "Hiba: Nem támogatott konfigurációs formátum: `{0}`. Használja a `.htmlvalidate.json` JSON-konfigurációt",
  "CMD_ENABLE_QUICK_VIEW": "Gyors Nézet rámutatáskor",
  "CMD_ENABLE_SELECTION_VIEW": "Kijelölés nézet",
  "TOOLTIP_CLICK_TO_EDIT_COLOR": "Kattintson ide a szín szerkesztéséhez",
  "CMD_TOGGLE_RECENT_PROJECTS": "Legutóbbi projektek",
  "REMOVE_FROM_RECENT_PROJECTS": "Eltávolítás a legutóbbi projektekből",
  "DOCS_MORE_LINK": "Olvasd tovább",
  "DOCS_MORE_LINK_MDN_TITLE": "Kattintson a Dokumentáció elolvasásához",
  "COLLAPSE_ALL": "Összes bezárása",
  "EXPAND_ALL": "Bontsa ki az összeset",
  "COLLAPSE_CURRENT": "Az aktuális összecsukása",
  "EXPAND_CURRENT": "Bontsa ki az Aktuális elemet",
  "RECENT_FILES_DLG_HEADER": "Legutóbbi fájlok",
  "RECENT_FILES_DLG_CLEAR_BUTTON_LABEL": "Egyértelmű",
  "RECENT_FILES_DLG_CLEAR_BUTTON_TITLE": "Törölje a munkakészletben nem szereplő fájlokat",
  "RECOVER_UNSAVED_FILES_TITLE": "Visszaállítja a nem mentett fájlokat?",
  "RECOVER_UNSAVED_FILES_MESSAGE": "Visszaállítja az előző munkamenet nem mentett fájljait?",
  "RECOVER_UNSAVED_FILES_RESTORE": "visszaállítás",
  "DISCARD_UNSAVED_FILES_RESTORE": "Eldobni",
  "DESCRIPTION_CLOSE_BRACKETS": "igaz a kapcsos zárójelek, zárójelek és zárójelek automatikus bezárásához",
  "DESCRIPTION_CLOSE_OTHERS_ABOVE": "false, hogy eltávolítsa a \"Fent többiek bezárása\" elemet a Working Files helyi menüből",
  "DESCRIPTION_CLOSE_OTHERS_BELOW": "false, hogy eltávolítsa a \"Mások bezárása lent\" elemet a Working Files helyi menüből",
  "DESCRIPTION_CLOSE_OTHERS": "false, hogy eltávolítsa a \"Mások bezárása\" elemet a Working Files helyi menüből",
  "DESCRIPTION_CLOSE_TAGS": "Beállítja a címkezárási beállításokat",
  "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS": "Címkék tömbje, amelyet nem szabad automatikusan bezárni",
  "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING": "Bezárás, ha > a nyitó címke be van írva",
  "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING": "Bezárás, amikor a / of záró címkét beírja",
  "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS": "Címkék tömbje, amelynek megnyitásakor üres sor van",
  "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD": "igaz, hogy mindig összecsukható szakaszjelölőket generáljon, amikor a behúzási szint megváltozik",
  "DESCRIPTION_CODE_FOLDING_ENABLED": "igaz a kódhajtogatás engedélyezéséhez",
  "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER": "igaz, hogy a szakasz-összecsukható jelölők csak akkor legyenek láthatók, ha az egeret az ereszcsatorna fölé viszi",
  "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL": "Korlátozza a mélységi szintek számát Az Összes összecsukása érvényes",
  "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE": "Minimális sor az összecsukható szakasz ikon megjelenése előtt",
  "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES": "igaz, hogy emlékezzen az összecsukott szakaszokra, ha bezár és újra megnyit egy fájlt vagy projektet",
  "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE": "igaz, hogy engedélyezze a kód hajtogatását a szerkesztőben kiválasztott szövegen",
  "DESCRIPTION_DISABLED_DEFAULT_EXTENSIONS": "Letiltott alapértelmezett bővítmények",
  "DESCRIPTION_ATTR_HINTS": "Engedélyezze/letiltja a HTML attribútum tippeket",
  "DESCRIPTION_CSS_PROP_HINTS": "A CSS/LESS/SCSS tulajdonságra vonatkozó tippek engedélyezése/letiltása",
  "DESCRIPTION_JS_HINTS": "JavaScript kód tippek engedélyezése/letiltása",
  "DESCRIPTION_JS_HINTS_TYPE_DETAILS": "Az adattípus részleteinek engedélyezése/letiltása a JavaScript kód tippjeiben",
  "DESCRIPTION_PREF_HINTS": "A Beállítások kód tippjeinek engedélyezése/letiltása",
  "DESCRIPTION_SPECIAL_CHAR_HINTS": "HTML entitási tippek engedélyezése/letiltása",
  "DESCRIPTION_SVG_HINTS": "SVG-kód tippek engedélyezése/letiltása",
  "DESCRIPTION_HTML_TAG_HINTS": "HTML címke tippek engedélyezése/letiltása",
  "DESCRIPTION_URL_CODE_HINTS": "Engedélyezze/letiltja az URL-tippeket HTML-ben és CSS/LESS/SCSS-ben",
  "DESCRIPTION_DRAG_DROP_TEXT": "A Drag & Drop funkció engedélyezése/letiltása",
  "DESCRIPTION_HEALTH_DATA_TRACKING": "Engedélyezze az állapotadatok követését",
  "DESCRIPTION_HIGHLIGHT_MATCHES": "Lehetővé teszi az egyező karakterláncok automatikus kiemelését a dokumentumban",
  "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN": "Jelölje ki az összes karakterláncot, amely megfelel annak a tokennek, amelyben a kurzor jelenleg van (nincs szükség kiválasztásra)",
  "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY": "Csak akkor emelje ki, ha a kijelölés teljes token",
  "DESCRIPTION_INSERT_HINT_ON_TAB": "true (igaz) az aktuálisan kiválasztott kód tipp beszúrásához a lapon",
  "DESCRIPTION_NO_HINTS_ON_DOT": "igaz, hogy ne jelenítse meg automatikusan a JS-kód tippeket, ha . be van gépelve",
  "DESCRIPTION_JSHINT_DISABLE": "igaz a JSHints linter letiltásához a problémapanelen",
  "DESCRIPTION_ESLINT_DISABLE": "igaz az ESLint linter letiltásához a problémapanelen",
  "DESCRIPTION_HTML_LINT_DISABLE": "igaz a HTML linter letiltásához a problémapanelen",
  "DESCRIPTION_ESLINT_FAILED": "Az ESLint sikertelen ({0}). Győződjön meg arról, hogy a projekt tartalmaz érvényes <a href='https://eslint.org/docs/latest/use/configure/configuration-files'>konfigurációs fájlokat</a>",
  "DESCRIPTION_ESLINT_USE_NATIVE_APP": "Az ESLint csak az asztali alkalmazásban érhető el. Töltsd le <a href='https://phcode.io'>a phcode.io</a> oldalról",
  "DESCRIPTION_ESLINT_LOAD_FAILED": "Nem sikerült betölteni az ESLint-et ehhez a projekthez. A {APP_NAME} csak a 7-nél magasabb ESLint-verziókat támogatja.",
  "DESCRIPTION_ESLINT_DO_NPM_INSTALL": "Az ESLint engedélyezéséhez futtassa az \"npm install\" parancsot a projekten",
  "DESCRIPTION_LANGUAGE": "Nyelvspecifikus beállítások",
  "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS": "További leképezések a fájlkiterjesztéstől a nyelvnévhez",
  "DESCRIPTION_LANGUAGE_FILE_NAMES": "További leképezések a fájlnévtől a nyelvnévhez",
  "DESCRIPTION_LINEWISE_COPY_CUT": "Ha másolást és kivágást végez, amikor nincs kijelölés, akkor a teljes sorokat másolja vagy vágja, amelyekben kurzorok vannak",
  "DESCRIPTION_INPUT_STYLE": "Kiválasztja a CodeMirror beviteli és fókuszkezelési módját. Lehet textarea, ami az alapértelmezett, vagy contenteditable, ami jobb a képernyőolvasók számára (instabil)",
  "DESCRIPTION_LINTING_ENABLED": "igaz, hogy engedélyezze a kódellenőrzést",
  "DESCRIPTION_ASYNC_TIMEOUT": "Az az idő ezredmásodpercben, amely után az aszinkron linterek lejárnak",
  "DESCRIPTION_LINTING_PREFER": "Linterek tömbje az első futtatáshoz",
  "DESCRIPTION_LIVE_DEV_MULTIBROWSER": "igaz a kísérleti élő előnézet engedélyezéséhez",
  "DESCRIPTION_USE_PREFERED_ONLY": "igaz a linting.prefer csak a megadott szolgáltatókra",
  "DESCRIPTION_MAX_CODE_HINTS": "Egyszerre megjelenített maximális kódútmutató",
  "DESCRIPTION_PATH": "Útvonal-specifikus beállítások",
  "DESCRIPTION_PROXY": "A bővítmény telepítéséhez használt proxyszerver URL-je",
  "DESCRIPTION_SCROLL_PAST_END": "igaz, hogy lehetővé tegye a görgetést a dokumentum végén túlra",
  "DESCRIPTION_SHOW_CODE_HINTS": "false az összes kódtipp letiltásához",
  "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING": "A villogó kurzor látható marad, ha szöveget választ",
  "DESCRIPTION_SHOW_LINE_NUMBERS": "igaz, hogy a kódtól balra található „ereszcsatornában” sorszámok jelenjenek meg",
  "DESCRIPTION_RULERS_COLUMNS": "Oszlopszámok tömbje függőleges vonalzók rajzolásához a szerkesztőben. Pl.: [80, 100]",
  "DESCRIPTION_RULERS_COLORS": "Vonalzószínek tömbje, amely megfelel a szerkesztő vonalzói beállításának. Pl.: [\"#3d3d3d\", \"piros\"]",
  "DESCRIPTION_RULERS_ENABLED": "igaz a szerkesztői vonalzók engedélyezéséhez, egyébként false",
  "DESCRIPTION_AUTO_RENAME_TAGS": "igaz a párosított HTML/XML címke automatikus átnevezéséhez, egyébként false",
  "DESCRIPTION_DRAG_AND_DROP_ENABLED": "igaz, hogy engedélyezze a drag and drop funkciót a fájlok és mappák számára a fájlkezelőből vagy a Finderből",
  "DESCRIPTION_TRIPLE_CTRL_PALETTE": "igaz, hogy engedélyezze a vizuális parancsfedő megjelenítését a Ctrl/Cmd billentyű három egymást követő lenyomására",
  "DESCRIPTION_SMART_INDENT": "Automatikus behúzás új blokk létrehozásakor",
  "DESCRIPTION_SOFT_TABS": "false a lágy lapok viselkedésének kikapcsolásához",
  "DESCRIPTION_SORT_DIRECTORIES_FIRST": "igaz, ha először rendezi a könyvtárakat a projektfában",
  "DESCRIPTION_SPACE_UNITS": "A szóköz alapú behúzáshoz használt szóközök száma",
  "DESCRIPTION_STATIC_SERVER_PORT": "Portszám, amelyet a beépített kiszolgálónak használnia kell az élő előnézethez",
  "DESCRIPTION_STYLE_ACTIVE_LINE": "igaz, hogy kiemelje annak a vonalnak a háttérszínét, amelyen a kurzor áll",
  "DESCRIPTION_TAB_SIZE": "A tabulátoroknál megjelenítendő szóközök száma",
  "DESCRIPTION_USE_TAB_CHAR": "igaz, hogy szóköz helyett tabulátorokat használjon",
  "DESCRIPTION_AUTO_TAB_SPACE": "igaz az aktuális fájlban használt tabulátorok és szóközök automatikus észlelésére",
  "DESCRIPTION_UPPERCASE_COLORS": "igaz, hogy nagybetűs hexadecimális színeket generáljon az Inline Color Editorban",
  "DESCRIPTION_WORD_WRAP": "A nézetablak szélességét meghaladó vonalak tördelése",
  "DESCRIPTION_SEARCH_AUTOHIDE": "Zárja be a keresést, amint a szerkesztő fókuszba áll",
  "DESCRIPTION_DETECTED_EXCLUSIONS": "Azon fájlok listája, amelyekről azt észlelték, hogy a Tern kifutott az ellenőrzés alól",
  "DESCRIPTION_INFERENCE_TIMEOUT": "Az az idő, ameddig Tern lejár, amikor megpróbálja megérteni a fájlokat",
  "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR": "igaz, hogy a hibákat az állapotsorban jelenítse meg",
  "DESCRIPTION_QUICK_VIEW_ENABLED": "igaz a Gyorsnézet engedélyezéséhez",
  "DESCRIPTION_SELECTION_VIEW_ENABLED": "igaz a Kijelölés nézet engedélyezéséhez",
  "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW": "igaz, hogy a bővítményt nem tartalmazó URL-ek kép-előnézeteit jelenítse meg",
  "DESCRIPTION_NUMBER_QUICK_VIEW": "igaz, hogy a szerkesztőben a számok fölé vigye az egérmutatót a Gyorsnézet megjelenítéséhez",
  "DESCRIPTION_THEME": "Válasszon egy {APP_NAME} témát",
  "DESCRIPTION_USE_THEME_SCROLLBARS": "igaz az egyéni görgetősávok engedélyezéséhez",
  "DESCRIPTION_LINTING_COLLAPSED": "összecsukható szöszmötölő panel",
  "DESCRIPTION_FONT_FAMILY": "Betűcsalád módosítása",
  "DESCRIPTION_DESKTOP_ZOOM_SCALE": "Válasszon egy nagyítási léptéktényezőt 0,1-től (kompaktabb nézethez) 2-ig (nagyobb, nagyobb nézethez). Csak asztali alkalmazásokban érhető el",
  "DESCRIPTION_FONT_SIZE": "Betűméret megváltoztatása; például. 13 képpont",
  "DESCRIPTION_FIND_IN_FILES_NODE": "igaz a csomópont alapú keresés engedélyezéséhez",
  "DESCRIPTION_FIND_IN_FILES_INSTANT": "igaz az azonnali keresés engedélyezéséhez",
  "DESCRIPTION_FONT_SMOOTHING": "Csak Mac: \"alpixel élsimítás\" az alpixel élsimítás engedélyezéséhez vagy \"élsimított\" a szürkeárnyalatos élsimításhoz",
  "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW": "false a beállításfájl megnyitásának letiltásához osztott nézetben",
  "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE": "false a felhasználói beállítások fájl megnyitásához a bal/felső panelen",
  "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED": "igaz az ablaktáblák összecsukására, miután a panel utolsó fájlját bezárták az ablaktábla fejlécének bezárása gombbal",
  "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS": "Váltás, hogy mikor jelenjenek meg a bezárás és a megfordítás gombok a fejlécen.",
  "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT": "/*\n * Ez egy csak olvasható fájl, támogatott beállításokkal\n * készítette: {APP_NAME}.\n * Használja ezt a fájlt referenciaként a beállítások módosításához\n * a \"phcode.json\" fájl megnyílik a másik ablaktáblában.\n * További információ a beállítások belső használatáról\n * {APP_NAME}, tekintse meg a https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences weboldalt\n */",
  "DEFAULT_PREFERENCES_JSON_DEFAULT": "Alapértelmezett",
  "DESCRIPTION_PURE_CODING_SURFACE": "igaz a csak kód mód engedélyezése és az összes többi felhasználói felület elrejtése a(z) {APP_NAME} alkalmazásban",
  "DESCRIPTION_INDENT_LINE_COMMENT": "igaz, hogy engedélyezze a soros megjegyzések behúzását",
  "DESCRIPTION_RECENT_FILES_NAV": "Navigáció engedélyezése/letiltása a legutóbbi fájlokban",
  "DESCRIPTION_LIVEDEV_WEBSOCKET_PORT": "Port, amelyen a WebSocket Server fut az élő előnézethez",
  "DESCRIPTION_LIVE_DEV_HIGHLIGHT_SETTINGS": "Élő előnézeti kiemelés beállításai",
  "DESCRIPTION_LIVEDEV_ENABLE_REVERSE_INSPECT": "false az élő előnézeti fordított ellenőrzés letiltásához",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW": "Nincs mit megnézni!",
  "DESCRIPTION_LIVEDEV_EXCLUDED": "Az egyéni kiszolgáló nem tudja kiszolgálni ezt a fájlt",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW_EXCLUDED": "Az élő előnézet beállításai úgy vannak beállítva, hogy csak a(z) „{0}” mappából származó fájlokat szolgáltassák ki",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW_DETAILS": "Kérjük, válasszon egy HTML-fájlt az előnézethez",
  "DESCRIPTION_LIVEDEV_PREVIEW_RESTRICTED": "Az előnézet nem érhető el!",
  "DESCRIPTION_LIVEDEV_PREVIEW_RESTRICTED_DETAILS": "Ez a HTML-fájl nem része az aktuális projektnek. Biztonsági okokból csak a projektfájlokat lehet élőben megtekinteni. A fájl előnézetének megtekintéséhez nyissa meg a fájlt tartalmazó mappát külön projektként.",
  "DESCRIPTION_LIVEDEV_MAIN_HEADING": "UH Oh!<br> Jelenlegi böngészője nem támogatja az élő előnézetet.",
  "DESCRIPTION_LIVEDEV_MAIN_SPAN": "Szerezze meg a legjobb élő előnézeti élményt, ha letölti natív alkalmazásainkat Windowsra, Macre és Linuxra <a href=\"https://phcode.io\" style=\"color: white\">a phcode.io</a> webhelyről.<br>",
  "DESCRIPTION_LIVEDEV_SECURITY_POPOUT_MESSAGE": "Egy fájl megnyitására készül az élő előnézethez. Kérjük, csak akkor folytassa, ha megbízik a projekt forrásában. Kattintson a \"Trust Project\" gombra a folytatáshoz, vagy zárja be ezt az ablakot, ha nem bízik a forrásban.",
  "DESCRIPTION_LIVEDEV_SECURITY_TRUST_MESSAGE": "Egy fájl megnyitására készül az élő előnézethez. Kérjük, csak akkor folytassa a \"Trust Project\" gombra kattintva, ha megbízik a projekt forrásában!",
  "CONFIRM_EXTERNAL_BROWSER_TITLE": "Előugró ablakok blokkolva",
  "CONFIRM_EXTERNAL_BROWSER_MESSAGE": "Engedélyezi az élő előnézeti oldal számára a következő URL megnyitását: {0}?",
  "TRUST_PROJECT": "Trust & Execute előnézet – {0}",
  "TRUST_AUTHORS": "Bízol a projekt szerzőiben?",
  "DOWNLOAD_FAILED": "Sikertelen letöltés.",
  "DOWNLOAD_COMPLETE": "Letöltés kész!",
  "UPDATE_SUCCESSFUL": "Frissítés sikeres!",
  "UPDATE_FAILED": "Frissítés sikertelen!",
  "VALIDATION_FAILED": "Az érvényesítés sikertelen!",
  "INITIALISATION_FAILED": "Az inicializálás nem sikerült!",
  "CLEANUP_FAILED": "A tisztítás nem sikerült!",
  "WARNING_TYPE": "Figyelem!",
  "CLICK_RESTART_TO_UPDATE": "Kattintson az Újraindítás gombra a zárójelek frissítéséhez.",
  "UPDATE_ON_NEXT_LAUNCH": "A frissítés az újraindításkor kerül alkalmazásra.",
  "GO_TO_SITE": "Nyissa meg a <a href = \"http://brackets.io/\">brackets.io oldalt</a> az újrapróbálkozáshoz.",
  "INTERNET_UNAVAILABLE": "Nincs internet kapcsolat.",
  "UPDATEDIR_READ_FAILED": "A frissítési könyvtár nem olvasható.",
  "UPDATEDIR_CLEAN_FAILED": "A frissítési könyvtár nem tisztítható.",
  "INITIAL_DOWNLOAD": "Frissítés letöltése...",
  "RETRY_DOWNLOAD": "Sikertelen letöltés. Újrapróbálkozás...Kísérlet",
  "VALIDATING_INSTALLER": "Letöltés kész! Telepítő érvényesítése...",
  "CHECKSUM_DID_NOT_MATCH": "Az ellenőrző összeg nem egyezik.",
  "INSTALLER_NOT_FOUND": "A telepítő nem található.",
  "DOWNLOAD_ERROR": "Hiba történt a letöltés során.",
  "NETWORK_SLOW_OR_DISCONNECTED": "A hálózat megszakadt vagy túl lassú.",
  "RESTART_BUTTON": "Újrakezd",
  "LATER_BUTTON": "A későbbiekben",
  "DESCRIPTION_AUTO_UPDATE": "A(z) {APP_NAME} automatikus frissítésének engedélyezése/letiltása",
  "AUTOUPDATE_ERROR": "Hiba!",
  "AUTOUPDATE_IN_PROGRESS": "A frissítés már folyamatban van.",
  "NUMBER_WITH_PERCENTAGE": "{0}%",
  "CMD_FIND_RELATED_FILES": "Kapcsolódó fájlok keresése",
  "PHP_VERSION_INVALID": "Hiba a PHP verzió elemzésekor. Kérjük, ellenőrizze a „php –version” parancs kimenetét.",
  "PHP_UNSUPPORTED_VERSION": "Telepítse a PHP7 futtatókörnyezetét, hogy engedélyezze a PHP-vel kapcsolatos eszközöket, mint például a kódtippek, paraméteri tippek, ugrás a definícióhoz és még sok más. Talált verzió: {0}",
  "PHP_EXECUTABLE_NOT_FOUND": "PHP futási környezet nem található. Telepítse a PHP7 futtatókörnyezetét, és megfelelően frissítse az „executablePath”-t a PHP Preferencesben. Ez lehetővé teszi a PHP-vel kapcsolatos eszközök használatát, mint például kódtippek, paraméteri tippek, ugrás a definícióhoz és még sok más.",
  "PHP_PROCESS_SPAWN_ERROR": "A(z) {0} hibakód a PHP-folyamat indításakor.",
  "PHP_SERVER_ERROR_TITLE": "Hiba",
  "PHP_SERVER_MEMORY_LIMIT_INVALID": "A megadott memóriakorlát érvénytelen. Tekintse át a PHP beállításokat a helyes érték beállításához.",
  "DESCRIPTION_PHP_TOOLING_CONFIGURATION": "A PHP Tooling alapértelmezett konfigurációs beállításai",
  "OPEN_PREFERENNCES": "Nyissa meg a Beállításokat",
  "LANGUAGE_TOOLS_PREFERENCES": "Nyelvi eszközök beállításai",
  "FIND_ALL_REFERENCES": "Találja meg az összes hivatkozást",
  "REFERENCES_IN_FILES": "hivatkozások",
  "REFERENCE_IN_FILES": "referencia",
  "REFERENCES_NO_RESULTS": "Nincs elérhető hivatkozás a kurzor aktuális pozíciójához",
  "CMD_FIND_DOCUMENT_SYMBOLS": "Keresse meg a dokumentumszimbólumokat",
  "CMD_FIND_PROJECT_SYMBOLS": "Keresse meg a projekt szimbólumait",
  "REMOTE_DEBUGGING_ENABLED": "Távoli hibakeresés engedélyezve a localhost-on:",
  "REMOTE_DEBUGGING_PORT_INVALID": "A távoli hibakeresés nem engedélyezhető a(z) {0} porton. A portszámoknak {1} és {2} között kell lenniük.",
  "DESCRIPTION_EXTERNAL_APPLICATION_ASSOCIATE": "Leképezések a fájlkiterjesztéshez külső alkalmazásokhoz. Szintaxis: \"<fájltípus>\": \"<alapértelmezett|alkalmazásnév|Alkalmazásútvonal>\", A \"default\" használatával nyissa meg a fájltípushoz tartozó fájlokat a rendszer alapértelmezett alkalmazásában.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_TITLE": "Nyissa meg a grafikus fájlokat a külső szerkesztőkben.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_MSG": "Jelenlegi mappájában olyan grafikus fájltípusok találhatók, amelyeket a(z) {APP_NAME} nem támogat.<br/> Mostantól bizonyos fájltípusokat társíthat külső szerkesztőkkel. A társítás után megnyithat olyan grafikus fájlokat, mint az .xd, .psd, .jpg, .png, .ai, .svg az alapértelmezett alkalmazásokban, ha duplán kattint a fájlokra a Fájlfában.<br/><br/> Kattintson az &#39;Ok&#39; gombra, hogy a grafikus fájltípusokat a megfelelő alapértelmezett alkalmazásokhoz társítsa.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_CNF_MSG": "A következő fájltípusok sikeresen társításra kerültek az alapértelmezett alkalmazásokhoz.<br/> {0} A „Debug-&gt;Open Preferences File” menüben módosíthatja a phcode.json fájltípus-társítások törlésére/adására vonatkozó beállításait.",
  "UNSUPPORTED_BROWSER_TITLE": "A böngésző nem támogatott",
  "UNSUPPORTED_BROWSER_MESSAGE": "Kérjük, használjon modern böngészőt (amely az elmúlt 3 évben jelent meg).",
  "UNSUPPORTED_BROWSER_MOBILE_TITLE": "A mobil böngészők nem támogatottak",
  "UNSUPPORTED_BROWSER_MOBILE": "A mobil- és táblagépes böngészők jelenleg nem támogatottak teljes mértékben. Bezárhatja ezt a párbeszédpanelt, de a Phoenix egyes funkciói nem működnek ebben a böngészőben.<br/><br/> Dolgozunk az iOS és Android natív alkalmazások fejlesztésén. <a href=\"https://github.com/phcode-dev/phoenix/discussions/1046\" target=\"_blank\">Csatlakozz a vitához itt!</a>",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER_TITLE": "A helyi mappa elérését a böngésző nem támogatja",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER": "Sajnáljuk, úgy tűnik, hogy jelenlegi böngészője nem támogatja a helyi mappák megnyitását. Ehhez a funkcióhoz a Chrome, az Edge vagy az Opera használatát javasoljuk.<br/><br/> Alternatív megoldásként natív alkalmazások fejlesztésén dolgozunk Windows, Mac, Linux, iOS és Android rendszerekhez, hogy teljes körű támogatást nyújtsunk. <a href=\"https://github.com/phcode-dev/phoenix/discussions/1047\" target=\"_blank\">Maradjon velünk a frissítésekért!</a>",
  "ATTENTION_SAFARI_USERS": "Safari felhasználók figyelmébe",
  "ATTENTION_SAFARI_USERS_MESSAGE": "<span>A Safari automatikusan törli a webhely adatait, ha egy webhelyet 7 napon belül nem keresnek fel újra. A(z) {APP_NAME} a böngésző tárhelyére támaszkodik a projektek mentéséhez, amelyek a házirend miatt eltávolíthatók.<br/><br/> Javasoljuk, hogy <strong>töltse le a macOS asztali alkalmazást</strong> <a href='https://phcode.io' target='_blank' style='color: white'>a https://phcode.io</a> címről</span>",
  "CANNOT_PUBLISH_LARGE_PROJECT": "A nagy projektet nem lehet közzétenni",
  "CANNOT_PUBLISH_LARGE_PROJECT_MESSAGE": "A Phoenix még mindig kísérleti alfában van. Még nem engedélyeztük az 500 fájlnál nagyobb projektek szinkronizálását.",
  "SHARE_WEBSITE": "Webhely közzététele és megosztása?",
  "PUBLISH": "Közzététel",
  "PUBLISH_CONSENT_MESSAGE": "Gyorsan megtekintheti a változások előnézetét, és megoszthatja webhelyét másokkal. A {APP_NAME} közzéteheti ezt a webhelyet a következő címen: {0}. A közzétett linkek 3 napig érvényesek. </br>Szeretné közzétenni és megosztani webhelyét?",
  "PUBLISH_SYNC_IN_PROGRESS": "Szinkronizálás az előnézethez...",
  "PUBLISH_PAGE": "Kattintson ide az oldal közzétételéhez és megosztásához",
  "PUBLISH_VIEW_PAGE": "Kattintson a közzétett oldal megtekintéséhez",
  "MISSING_FIELDS": "Hiányzó mezők",
  "PLEASE_FILL_ALL_REQUIRED": "Kérjük, töltse ki az összes pirossal kiemelt mezőt",
  "CODE_EDITOR": "Kódszerkesztő",
  "BUILD_THE_WEB": "Építsd meg a webet",
  "IMPORT_PROJECT": "Projekt importálása",
  "GITHUB_PROJECT": "GitHub projekt",
  "NEW_PROJECT_FROM_GITHUB": "Új projekt a GitHubtól",
  "GITHUB_REPO_URL": "GitHub Repo URL-je:",
  "START_PROJECT": "Projekt indítása…",
  "DOWNLOAD_DESKTOP_APP": "Töltse le az asztali alkalmazást",
  "GET_DESKTOP_APP": "Töltse le az asztali alkalmazást",
  "CREATE_PROJECT": "Projekt létrehozása",
  "SETTING_UP_PROJECT": "Projekt beállítása",
  "LOCATION": "Helyszín:",
  "DOWNLOADING": "Letöltés...",
  "DOWNLOADING_FILE": "{0} letöltése...",
  "EXTRACTING_FILES_PROGRESS": "{1}/{0} fájl kibontása.",
  "COMPRESS_FILES_PROGRESS": "{1}/{0} fájl tömörítése.",
  "DOWNLOAD_FAILED_MESSAGE": "Győződjön meg arról, hogy a letöltési URL érvényes. </br>Megjegyzés: Mivel a Phoenix alfa állapotban van, a 25 MB-nál nagyobb privát repo- és GitHub-URL-ek nem engedélyezettek.",
  "PLEASE_SELECT_A_FOLDER": "Kérjük, válasszon mappát...",
  "UNZIP_IN_PROGRESS": "Fájlok kicsomagolása...",
  "UNZIP_FAILED": "Hiba: A kicsomagolás nem sikerült.",
  "CONFIRM_REPLACE_TITLE": "Erősítse meg a Csere lehetőséget",
  "KEEP_BOTH": "Megtartani mindkettőt",
  "EXPLORE": "HTML játékok",
  "BLOG": "Blog",
  "PHOENIX_DEFAULT_PROJECT": "Alapértelmezett projekt",
  "PROJECT_NAME": "Projekt neve:",
  "NEW_HTML": "Új HTML projekt",
  "LICENSE": "Licenc és kreditek:",
  "PREVIEW": "Előnézet",
  "BUILD_WEBSITE": "Webhely készítése",
  "VIEW_MORE": "Mutass többet...",
  "NEW_PROJECT_NOTIFICATION": "Kattintson erre az ikonra az „Új projekt” ablak újbóli megnyitásához.</br> Lásd: Legutóbbi projektek, Nyissa meg a mappát, vagy indítson projekteket sablonokból.</br><img src=\"styles/images/new_project.png\"><br/> <a href='#' style='float:right;'>rendben</a>",
  "BEAUTIFY_CODE_NOTIFICATION": "Kattintson ide, vagy nyomja meg <b>a `{0}`</b> gombot a kód szépítéséhez.</br><img src=\"styles/images/beautify.gif\"><br/> <a href='#' style='float:right;'>rendben</a>",
  "DEFAULT_PROJECT_NOTIFICATION": "Kattintson ide a megnyitásához<br/> <b>alapértelmezett projekt</b> a phoenixben.</br> <a href='#' style='float:right;'>rendben</a>",
  "DIRECTORY_REPLACE_MESSAGE": "A kiválasztott mappa <span class='dialog-filename'>({0}</span> ) nem üres. Biztosan le szeretné cserélni a mappa tartalmát a projekttel?",
  "DEFAULT_PROJECT_HTML_CLICK_HERE": "Kattintson ide a &lt;span&gt; a HTML fájlban",
  "BUILD_WEBSITE_SECTION": "Webhely készítése",
  "LEARN_SECTION": "Tanuljon példákkal",
  "CREATE_EXTENSION_SECTION": "Hozzon létre {APP_NAME} bővítményeket és témákat",
  "CREATE_EXTENSION": "Bővítmény létrehozása",
  "CREATE_THEME": "Téma létrehozása",
  "WEBPAGE_HOME_PAGE": "Kezdőlap",
  "WEBPAGE_BLOG": "Blog oldal",
  "WEBPAGE_DASHBOARD": "HTML irányítópult",
  "WEBPAGE_BOOTSTRAP_EXAMPLES": "Bootstrap példák",
  "PROJECTS_AT_A_GLANCE": "Projektjei egy pillantással",
  "PROJECT_AT_GLANCE_DESCRIPTION": "Nézze meg a videót a kezdéshez.",
  "PROJECT_FROM_BROWSER": "A böngészőben tárolva",
  "PROJECT_FROM_BROWSER_TERSE": "Böngésző tárolása",
  "PROJECT_SHOW_ON_STARTUP": "A párbeszéd megjelenítése indításkor",
  "GUIDED_LIVE_PREVIEW": "Az élő előnézet megtekintéséhez hajtson végre néhány kódmódosítást a HTML-fájlban.</br> <a href='#' style='float:right;'>rendben</a>",
  "GUIDED_LIVE_PREVIEW_POPOUT": "Kattintson erre a gombra, hogy az élő előnézetet egy új lapra hozza.</br> <a href='#' style='float:right;'>rendben</a>",
  "ENJOYING_APP": "Tetszik a(z) {APP_NAME}?",
  "GITHUB_STARS_POPUP": "<div>Az Ön támogatása segít a mi kis csapatunknak abban, hogy még jobbá tegyük <b style='color: darkblue'>a phcode.dev webhelyet</b> .<br/> Kérjük, csillagozzon meg minket, vagy fontolja meg szponzorálásunkat a GitHubon:",
  "GITHUB_STARS_POPUP_TWITTER": "Adjon visszajelzést, vagy terjessze az igét a Twitteren:",
  "TEST_TRANSLATE": "használja ezt a fordítások tesztelésére",
  "BEAUTIFY_ERROR": "Nem sikerült szépíteni a kódot. Ellenőrizze a szintaxist.",
  "BEAUTIFY_ERROR_ORIGINAL_CHANGED": "Nem lehetett szépíteni. A szerkesztő szövege a szépítés után megváltozott.",
  "BEAUTIFY_PROJECT_BUSY_MESSAGE": "Szépítő fájl {0}",
  "BEAUTIFY_ERROR_SELECTION": "Nem sikerült szépíteni.</br>Hiányos kódblokk van kiválasztva, vagy érvénytelen a szintaxis.",
  "BEAUTIFY_OPTIONS": "A Beautify Code működését szabályozó beállítások",
  "BEAUTIFY_OPTION_PRINT_WIDTH": "Határozza meg a sor hosszát, amelyre a szépítő fog burkolni",
  "BEAUTIFY_OPTION_SEMICOLON": "Adjon pontosvesszőt minden utasítás végére",
  "BEAUTIFY_OPTION_SINGLE_QUOTE": "Használjon szimpla idézőjeleket dupla idézőjelek helyett",
  "BEAUTIFY_OPTION_QUOTE_PROPS": "Az objektumok tulajdonságainak idézőjelének módosítása",
  "BEAUTIFY_OPTION_BRACKET_SAME_LINE": "Tegye egy többsoros HTML (HTML, JSX, Vue, Angular) elem > jelét az utolsó sor végére ahelyett, hogy egyedül lenne a következő sorban (nem vonatkozik az önzáró elemekre)",
  "BEAUTIFY_OPTION_SINGLE_ATTRIBUTE_PER_LINE": "Egyetlen attribútum kényszerítése soronként HTML, Vue és JSX nyelven",
  "BEAUTIFY_OPTION_PROSE_WRAP": "Csomagolja be a prózát, ha meghaladja a nyomtatási szélességet a leíró fájlokban",
  "BEAUTIFY_OPTION_PRINT_TRAILING_COMMAS": "A többsoros, vesszővel elválasztott szintaktikai struktúrákban lehetőség szerint nyomtasson záró vesszőt"
});