exports.ESLINT_ERROR_MODULE_LOAD_FAILED = "ESLINT_MODULE_LOAD_FAILED";
exports.ESLINT_ERROR_MODULE_NOT_FOUND = "ESLINT_MODULE_NOT_FOUND";
exports.ESLINT_ERROR_LINT_FAILED = "ESLINT_LINT_FAILED";

exports.OPERATION_LINT_TEXT = "LINT_TEXT";
exports.OPERATION_GET_LOADED_VERSION = "GET_LOADED_VERSION";
exports.OPERATION_QUIT = "QUIT";
exports.OPERATION_RESPONSE = "ESLINT_RESPONSE";

// https://eslint.org/docs/latest/integrate/nodejs-api#-lintmessage-type
exports.SEVERITY_WARNING = 1;
exports.SEVERITY_ERROR = 2;
