/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "Predvolený v systéme",
  "PROJECT_BUSY": "Prebiehajúce operácie projektu",
  "DUPLICATING": "Duplikovanie {0}",
  "MOVING": "Pohybujúce sa {0}",
  "COPYING": "Kopírovanie {0}",
  "DELETING": "Odstránenie {0}",
  "RENAMING": "Premenovanie",
  "GENERIC_ERROR": "(chyba {0})",
  "NOT_FOUND_ERR": "Súbor nenájdený.",
  "NOT_READABLE_ERR": "Súbor sa nedá čítať.",
  "EXCEEDS_MAX_FILE_SIZE": "Súbory väčšie ako {0} MB nie je možné otvoriť v {APP_NAME}.",
  "NO_MODIFICATION_ALLOWED_ERR": "Cieľový adresár nemôže byť zmenený.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "Práva vám neumožňujú robiť zmeny.",
  "CONTENTS_MODIFIED_ERR": "Súbor bol upravený mimo {APP_NAME}.",
  "UNSUPPORTED_ENCODING_ERR": "Neznámy formát kódovania",
  "ENCODE_FILE_FAILED_ERR": "{APP_NAME} nebol schopný zakódovať obsah súboru.",
  "DECODE_FILE_FAILED_ERR": "{APP_NAME} nebol schopný dekódovať obsah súboru.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "{APP_NAME} momentálne nepodporuje kódované textové súbory UTF-16.",
  "FILE_EXISTS_ERR": "Súbor alebo adresár už existuje.",
  "FILE": "súbor",
  "FILE_TITLE": "Súbor",
  "DIRECTORY": "adresár",
  "DIRECTORY_TITLE": "adresár",
  "DIRECTORY_NAMES_LEDE": "Názvy adresárov",
  "FILENAMES_LEDE": "Názvy súborov",
  "FILENAME": "Názov súboru",
  "DIRECTORY_NAME": "Názov adresára",
  "ERROR_LOADING_PROJECT": "Chyba pri otváraní projektu",
  "OPEN_DIALOG_ERROR": "Nastala chyba pri zobrazení dialógu otvorenia súboru. (chyba {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "Nastala chyba pri načítaní adresára <span class='dialog-filename'>{0}</span>. (chyba {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "Nastala chyba pri načítaní obsahu adresára <span class='dialog-filename'>{0}</span>. (chyba {1})",
  "ERROR_OPENING_FILE_TITLE": "Chyba pri otváraní súboru",
  "ERROR_OPENING_FILE": "Nastala chyba pri otváraní súboru <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_OPENING_FILES": "Nastala chyba pri otváraní nasledujúcich súborov:",
  "ERROR_RELOADING_FILE_TITLE": "Chyba pri načítaní zmien z disku",
  "ERROR_RELOADING_FILE": "Nastala chyba pri načítaní súboru <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_SAVING_FILE_TITLE": "Chyba pri ukladaní súboru",
  "ERROR_SAVING_FILE": "Nastala chyba pri ukladaní súboru <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_FILE_TITLE": "Chyba pri premenovaní súboru",
  "ERROR_RENAMING_FILE": "Nastala chyba pri premenovaní súboru <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "Súbor alebo adresár nie je súčasťou aktuálne otvoreného projektu. Bohužiaľ, v tomto bode je možné premenovať iba súbory projektu.",
  "ERROR_MOVING_FILE_TITLE": "Chyba pri pohybe {0}",
  "ERROR_MOVING_FILE": "Pri pokuse o presunutie {2} <span class='dialog-filename'>{0}</span>sa vyskytla chyba. {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "Súbor/priečinok nie je možné presunúť, pretože nie sú súčasťou aktuálneho projektu.",
  "ERROR_DELETING_FILE_TITLE": "Chyba pri zmazaní súboru",
  "ERROR_DELETING_FILE": "Nastala chyba pri zmazaní súboru <span class='dialog-filename'>{0}</span>. {1}",
  "INVALID_FILENAME_TITLE": "Neplatný {0} názov",
  "CANNOT_PASTE_TITLE": "Nie je možné vložiť {0}",
  "ERR_TYPE_PASTE_FAILED": "Pri vkladaní <span class='dialog-filename'>{0} do <span class='dialog-filename'>{1}</span> </span> došlo k chybe",
  "CANNOT_DUPLICATE_TITLE": "Nie je možné duplikovať",
  "ERR_TYPE_DUPLICATE_FAILED": "Pri duplikovaní <span class='dialog-filename'>{0}</span>sa vyskytla chyba",
  "INVALID_FILENAME_MESSAGE": "Názvy súboru nesmú obsahovať nasledujúce znaky: {0} alebo používať rezervované systémové slová.",
  "ENTRY_WITH_SAME_NAME_EXISTS": "Súbor alebo adresár s názvom <span class='dialog-filename'>{0}</span> už existuje.",
  "ERROR_CREATING_FILE_TITLE": "Chyba pri vytváraní súboru {0}",
  "ERROR_CREATING_FILE": "Nastala chyba pri vytváraní súboru {0} <span class='dialog-filename'>{1}</span>. {2}",
  "ERROR_MIXED_DRAGDROP": "Nie je možné otvoriť priečinok súčasne s otvorením iných súborov.",
  "ERROR_KEYMAP_TITLE": "Chyba pri čítaní mapy kľúčov používateľa",
  "ERROR_KEYMAP_CORRUPT": "Váš súbor mapy kľúčov nie je platný JSON. Súbor sa otvorí, aby ste mohli opraviť formát.",
  "ERROR_LOADING_KEYMAP": "Váš súbor mapy kľúčov nie je platný textový súbor kódovaný UTF-8 a nie je možné ho načítať",
  "ERROR_RESTRICTED_COMMANDS": "Nie je možné priradiť skratky k týmto príkazom: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "Tieto skratky nie je možné priradiť: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "K týmto príkazom priraďujete viacero skratiek: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "Máte viacero väzieb týchto skratiek: {0}",
  "ERROR_INVALID_SHORTCUTS": "Tieto skratky sú neplatné: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "Priraďujete skratky k neexistujúcim príkazom: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "Chyba pri čítaní nastavení",
  "ERROR_PREFS_CORRUPT": "Váš súbor preferencií nie je platný JSON. Súbor sa otvorí, aby ste mohli opraviť formát. Aby sa zmeny prejavili, budete musieť reštartovať {APP_NAME}.",
  "ERROR_PROJ_PREFS_CORRUPT": "Súbor predvolieb projektu nie je platný JSON. Súbor sa otvorí, aby ste mohli opraviť formát. Aby sa zmeny prejavili, budete musieť znovu načítať projekt.",
  "ERROR_IN_BROWSER_TITLE": "Hopa! {APP_NAME} zatiaľ nejde spustiť v prehliadači.",
  "ERROR_IN_BROWSER": "{APP_NAME} je vytvorený HTML, ale teraz pracuje ako desktopová aplikácia, takže ho môžete využiť na úpravu lokálnych súborov. Prosím, používajte shell aplikácie v <b>github.com/adobe/brackets-shell</b> repozitári pre spustenie {APP_NAME}.",
  "ERROR_MAX_FILES_TITLE": "Chyba pri indexovaní súborov",
  "ERROR_MAX_FILES": "Bol indexovaný maximálny počet súborov. Akcie pre vyhľadávanie súborov podľa indexu nemusia fungovať správne.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "Chyba pri spúšťaní prehliadača",
  "ERROR_CANT_FIND_CHROME": "Prehliadač Google Chrome nebol nájdený. Prosím uistite sa, že je nainštalovaný.",
  "ERROR_LAUNCHING_BROWSER": "Nastala chyba pri spúšťaní prehliadača. (chyba {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "Chyba pri živom náhľade",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "Pripojovanie k prehliadaču",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "V prípade využitia živého náhľadu je treba reštarovať Chrome zo zapnutým vzdialeným ladením.<br /><br />Chceli by ste reštartovať Chrome a zapnúť vzdialené ladenie?",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "Nie je možné načítať stránku zo živým náhľadom",
  "LIVE_DEV_NEED_HTML_MESSAGE": "Otvorte HTML súbor pre spustenie živého náhľadu.",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "Pre spustenie živého náhľadu zo súborom na serveri, musíte špecifikovať URL pre tento projekt.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "Chyba pri spúšťaní HTTP severa pre súbory živého náhľadu. Prosím, skúste to znovu.",
  "LIVE_DEVELOPMENT_INFO_TITLE": "Vitajte v živom náhľade!",
  "LIVE_DEVELOPMENT_INFO_MESSAGE": "Živý náhľad pripája {APP_NAME} k vášmu prehliadaču. Spustí náhľad vášho HTML súboru v prehliadači, potom aktualizuje náhľad okamžite, vždy keď upravíte svoj kód.<br /><br />V tejto verzii {APP_NAME}, živý náhľad funguje iba s <strong>Google Chrome</strong> a aktualizuje keď upravíte <strong>CSS súbory</strong>. Zmeny pre HTML alebo JavaScript súbory sú automaticky načítané, keď súbor uložíte.<br /><br />(Túto správu uvidíte iba jeden krát.)",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "Pre viac informácií pozrite <a class=\"clickable-link\" data-href=\"{0}\">Riešenie chýb pri pripojení do živého náhľadu</a>.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "Živý náhľad",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "Živý náhľad: Pripájanie…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "Živý náhľad: Inicializácia…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "Odpojenie živého náhľadu",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "Živý náhľad: Kliknite pre odpojenie (Uložte súbor)",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "Vyberte súbor na živý náhľad",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "Znovu načítať stránku",
  "LIVE_DEV_CLICK_POPOUT": "Popout Live Náhľad do nového okna",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "Pripnúť na stránku Uvoľnite ukážku",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "Live Preview (neaktualizuje sa kvôli chybe syntaxe)",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "Živý náhľad bol zrušený kvôli tomu, že boli otvorené vývojárske nástroje v prehliadači",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "Živý náhľad bol zrušený kvôli tomu, že stránka bola zatvorená v prehliadači",
  "LIVE_DEV_NAVIGATED_AWAY": "Živý náhľad bol zrušený kvôli tomu, že prehliadač odkazoval na stránku, ktorá nie je súčasťou aktuálneho projektu",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "Živý náhľad bol zrušený pre neznámy dôvod ({0})",
  "SAVE_CLOSE_TITLE": "Uložiť zmeny",
  "SAVE_CLOSE_MESSAGE": "Chcete uložiť zmeny, ktoré ste spravili v dokumente <span class='dialog-filename'>{0}</span>?",
  "SAVE_CLOSE_MULTI_MESSAGE": "Chcete uložiť zmeny v následujúcich súboroch?",
  "EXT_MODIFIED_TITLE": "Externé zmeny",
  "CONFIRM_DELETE_TITLE": "Potvrdte odstránenie",
  "CONFIRM_FILE_DELETE": "Naozaj chcete odstrániť súbor <span class='dialog-filename'>{0}</span>?",
  "CONFIRM_FOLDER_DELETE": "Ste si istý zmazaním priečinku <span class='dialog-filename'>{0}</span>?",
  "FILE_DELETED_TITLE": "Súbor odstránený",
  "EXT_MODIFIED_WARNING": "<span class='dialog-filename'>{ 0}</span> bol upravený na disku mimo {APP_NAME}. <br /><br />Chcete súbor uložiť a prepísať tieto zmeny?",
  "EXT_MODIFIED_MESSAGE": "<span class='dialog-filename'>{0}</span> bol upravený na disku, ale tiež ma neuložené zmeny in {APP_NAME}.<br /><br />Ktorú verziu chcete ponechať?",
  "EXT_DELETED_MESSAGE": "<span class='dialog-filename'>{0}</span> bol zmazaný z disku, ale zmeny sa neuložili v {APP_NAME}.<br /><br />Chcete uložiť zmeny?",
  "WINDOW_UNLOAD_WARNING": "Naozaj chcete prejsť na inú adresu URL a nechať zátvorky?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "Máte neuložené zmeny! Naozaj chcete prejsť na inú adresu URL a nechať zátvorky?",
  "DONE": "Hotovo",
  "OK": "OK",
  "CANCEL": "Zrušiť",
  "DONT_SAVE": "Neukladať",
  "SAVE": "Uložiť",
  "SAVE_AS": "Uložiť ako…",
  "SAVE_AND_OVERWRITE": "Prepísať",
  "DELETE": "Zmazať",
  "BUTTON_YES": "Áno",
  "BUTTON_NO": "Nie",
  "FIND_MATCH_INDEX": "{0} z {1}",
  "FIND_NO_RESULTS": "Žiadne výsledky",
  "FIND_QUERY_PLACEHOLDER": "Nájsť...",
  "FIND_HISTORY_MAX_COUNT": "Maximálny počet položiek vyhľadávania v histórii vyhľadávania",
  "REPLACE_PLACEHOLDER": "Nahradiť s...",
  "BUTTON_REPLACE_ALL": "Nahradiť všetko",
  "BUTTON_REPLACE_BATCH": "Šarže...",
  "BUTTON_REPLACE_ALL_IN_FILES": "Nahradiť...",
  "BUTTON_REPLACE": "Nahradiť",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "Ďalšia zhoda",
  "BUTTON_PREV_HINT": "Predchádzajúca zhoda",
  "BUTTON_CASESENSITIVE_HINT": "Prípad zápasu",
  "BUTTON_REGEXP_HINT": "Regulárny výraz",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "Nahradiť bez zrušenia",
  "REPLACE_WITHOUT_UNDO_WARNING": "Pretože je potrebné zmeniť viac ako {0} súborov, {APP_NAME} upraví neotvorené súbory na disku. <br />Nebudete môcť vrátiť späť náhrady v týchto súboroch.",
  "BUTTON_REPLACE_WITHOUT_UNDO": "Nahradiť bez zrušenia",
  "OPEN_FILE": "Otvoriť súbor",
  "SAVE_FILE_AS": "Uložiť súbor",
  "CHOOSE_FOLDER": "Vybrať adresár",
  "RELEASE_NOTES": "Poznámky o verzii",
  "NO_UPDATE_TITLE": "Všetko je aktuálne!",
  "NO_UPDATE_MESSAGE": "Máte najnovšiu verziu {APP_NAME}.",
  "FIND_REPLACE_TITLE_LABEL": "Nahradiť",
  "FIND_REPLACE_TITLE_WITH": "so",
  "FIND_TITLE_LABEL": "Nájdené",
  "FIND_TITLE_SUMMARY": "— {0} {1} {2} v {3}",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "v <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_NO_SCOPE": "v projekte",
  "FIND_IN_FILES_ZERO_FILES": "Filter vylučuje všetky súbory {0}",
  "FIND_IN_FILES_FILE": "súbor",
  "FIND_IN_FILES_FILES": "súbory",
  "FIND_IN_FILES_MATCH": "zhoda",
  "FIND_IN_FILES_MATCHES": "zhody",
  "FIND_IN_FILES_MORE_THAN": "Cez ",
  "FIND_IN_FILES_PAGING": "{0}&mdash;{1}",
  "FIND_IN_FILES_FILE_PATH": "Súbor: <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "Ctrl/Cmd kliknutím rozbaliť/zbaliť všetky",
  "FIND_IN_FILES_INDEXING": "Indexovanie pre okamžité vyhľadávanie...",
  "FIND_IN_FILES_INDEXING_PROGRESS": "Indexovanie {0} {1} súborov pre okamžité vyhľadávanie...",
  "REPLACE_IN_FILES_ERRORS_TITLE": "Nahradiť chyby",
  "REPLACE_IN_FILES_ERRORS": "Nasledujúce súbory neboli upravené, pretože sa po vyhľadávaní zmenili alebo sa nedali zapísať.",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "Problém pri získavaní informácií o aktualizácii",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "Nastal problém pri získavaní aktuálnych informácií zo servera. Prosím uistite sa, že ste pripojený do internetu a skúste znovu.",
  "NEW_FILE_FILTER": "Nová sada vylúčení...",
  "CLEAR_FILE_FILTER": "Nevylučujte súbory",
  "NO_FILE_FILTER": "Žiadne súbory vylúčené",
  "EXCLUDE_FILE_FILTER": "Vylúčiť {0}",
  "EDIT_FILE_FILTER": "Upraviť...",
  "FILE_FILTER_DIALOG": "Upraviť sadu vylúčení",
  "FILE_FILTER_INSTRUCTIONS": "Vylúčte súbory a priečinky zodpovedajúce niektorému z nasledujúcich reťazcov alebo podreťazcov alebo <a href='{0}' title='{0}'>zástupných znakov</a>. Zadajte každý reťazec na nový riadok.",
  "FILTER_NAME_PLACEHOLDER": "Názov tejto sady vylúčení (voliteľné)",
  "FILTER_NAME_REMAINING": "{0} zostávajúcich znakov",
  "FILE_FILTER_CLIPPED_SUFFIX": "a {0} viac",
  "FILTER_COUNTING_FILES": "Počítanie súborov...",
  "FILTER_FILE_COUNT": "Umožňuje {0} {1} súborov {2}",
  "FILTER_FILE_COUNT_ALL": "Umožňuje všetky {0} súbory {1}",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "Pre aktuálnu pozíciu kurzora nie je k dispozícii žiadna rýchla úprava",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "CSS Quick Edit: umiestnite kurzor na jeden názov triedy",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "CSS Quick Edit: neúplný atribút triedy",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "CSS Quick Edit: neúplný atribút id",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "CSS Quick Edit: umiestnite kurzor do značky, triedy alebo id",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "Funkcia časovania CSS Rýchla úprava: neplatná syntax",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "JS Quick Edit: umiestnite kurzor do názvu funkcie",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "Pre aktuálnu pozíciu kurzora nie sú k dispozícii žiadne rýchle dokumenty",
  "PROJECT_LOADING": "Načítavanie…",
  "UNTITLED": "bez názvu",
  "WORKING_FILES": "Otvorené súbory",
  "TOP": "Top",
  "BOTTOM": "Spodná",
  "LEFT": "Vľavo",
  "RIGHT": "Pravá",
  "CMD_SPLITVIEW_NONE": "Žiadne Rozdelenie",
  "CMD_SPLITVIEW_VERTICAL": "Vertikálne Rozdelenie",
  "CMD_SPLITVIEW_HORIZONTAL": "Horizontálne rozdelenie",
  "SPLITVIEW_MENU_TOOLTIP": "Rozdeliť editor vertikálne alebo horizontálne",
  "GEAR_MENU_TOOLTIP": "Konfigurácia pracovnej sady",
  "SPLITVIEW_INFO_TITLE": "Už otvorené",
  "SPLITVIEW_MULTIPANE_WARNING": "Súbor je už otvorený v inej table. {APP_NAME} čoskoro podporí otvorenie rovnakého súboru vo viac ako jednej table. Dovtedy sa súbor zobrazí na paneli, v nej je už otvorený. <br /><br />( Táto správa sa zobrazí iba raz.)",
  "STATUSBAR_CURSOR_POSITION": "Riadok {0}, Stĺpec {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": " — Vybraný {0} stĺpec",
  "STATUSBAR_SELECTION_CH_PLURAL": " — Vybraných {0} stĺpcov",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " — Vybraný {0} riadok",
  "STATUSBAR_SELECTION_LINE_PLURAL": " — Vybraných {0} riadkov",
  "STATUSBAR_SELECTION_MULTIPLE": " — {0} výbery",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "Kliknite pre zmenu osadenia na medzery",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "Kliknite pre zmenu odsadenia na tabulátory",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "Kliknite pre zmenu počet medzier použitých pre odsadenie",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "Kliknite pre zmenu šírky tabulátora",
  "STATUSBAR_SPACES": "Medzery",
  "STATUSBAR_TAB_SIZE": "Velkosť tabulátora",
  "STATUSBAR_LINE_COUNT_SINGULAR": "Riadok: — {0}",
  "STATUSBAR_LINE_COUNT_PLURAL": "Riadky: — {0}",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "Rozšírenia zakázané",
  "STATUSBAR_INSERT": "INS",
  "STATUSBAR_OVERWRITE": "OVR",
  "STATUSBAR_INSOVR_TOOLTIP": "Kliknite pre prepínanie kurzora medzi režimami Insert (INS) a Overwrite (OVR)",
  "STATUSBAR_LANG_TOOLTIP": "Kliknite pre zmenu typu súboru",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. Kliknite na tlačidlo pre prepnutie panela správy.",
  "STATUSBAR_DEFAULT_LANG": "(predvolené)",
  "STATUSBAR_SET_DEFAULT_LANG": "Nastaviť ako predvolené pre súbory {0}",
  "STATUSBAR_ENCODING_TOOLTIP": "Vyberte kódovanie",
  "ERRORS_PANEL_TITLE_MULTIPLE": "{0} Problémy",
  "SINGLE_ERROR": "1 {0} Problém",
  "MULTIPLE_ERRORS": "{1} {0} Problémy",
  "NO_ERRORS": "Neboli nájdené žiadne {0} problémy - dobrá práca!",
  "NO_ERRORS_MULTIPLE_PROVIDER": "Nenašli sa žiadne problémy - dobrá práca!",
  "LINT_DISABLED": "Linting je zakázaný",
  "NO_LINT_AVAILABLE": "Pre {0} nie je k dispozícii žiadny linter",
  "NOTHING_TO_LINT": "Nič, čo by nepúšťalo",
  "LINTER_TIMED_OUT": "{0} vypršal časový limit po čakaní na {1} ms",
  "LINTER_FAILED": "{0} ukončené chybou: {1}",
  "FILE_MENU": "Súbor",
  "CMD_FILE_NEW_UNTITLED": "Nový",
  "CMD_FILE_NEW": "Nový súbor",
  "CMD_FILE_DUPLICATE": "Duplikovať",
  "CMD_FILE_CUT": "Vystrihnúť",
  "CMD_FILE_COPY": "Kopírovať",
  "CMD_FILE_COPY_PATH": "Kopírovať cestu",
  "CMD_FILE_PASTE": "Vložiť",
  "CMD_PROJECT_NEW": "Nový projekt",
  "CMD_FILE_NEW_FOLDER": "Nový adresár",
  "CMD_FILE_OPEN": "Otvoriť…",
  "CMD_RECENT_FILES_OPEN": "Otvoriť Nedávne...",
  "CMD_ADD_TO_WORKING_SET": "Pridať do pracovnej sady",
  "CMD_OPEN_DROPPED_FILES": "Otvorte spadnuté súbory",
  "CMD_OPEN_FOLDER": "Otvoriť adresár…",
  "CMD_FILE_CLOSE": "Zatvoriť",
  "CMD_FILE_CLOSE_ALL": "Zatvoriť všetko",
  "CMD_FILE_CLOSE_LIST": "Zavrieť zoznam",
  "CMD_FILE_CLOSE_OTHERS": "Zatvoriť ostatné",
  "CMD_FILE_CLOSE_ABOVE": "Zatvorte ostatné vyššie",
  "CMD_FILE_CLOSE_BELOW": "Zatvorte ostatné nižšie",
  "CMD_FILE_SAVE": "Uložiť",
  "CMD_FILE_SAVE_ALL": "Uložiť všetko",
  "CMD_FILE_SAVE_AS": "Uložiť ako…",
  "CMD_LIVE_FILE_PREVIEW": "Živý náhľad",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "Povoliť experimentálny živý náhľad",
  "CMD_RELOAD_LIVE_PREVIEW": "Vynútiť obnovenie živého náhľadu",
  "CMD_PROJECT_SETTINGS": "Nastavenia projektu…",
  "CMD_FILE_RENAME": "Premenovať",
  "CMD_FILE_DELETE": "Zmazať",
  "CMD_INSTALL_EXTENSION": "Inštalovať rozšírenia…",
  "CMD_EXTENSION_MANAGER": "Správca rozšírení…",
  "CMD_FILE_REFRESH": "Obnoviť strom súborov",
  "CMD_FILE_SHOW_FOLDERS_FIRST": "Najskôr zoradiť priečinky",
  "CMD_QUIT": "Koniec",
  "CMD_EXIT": "Koniec",
  "EDIT_MENU": "Upraviť",
  "CMD_UNDO": "Späť",
  "CMD_REDO": "Znovu",
  "CMD_CUT": "Vystrihnúť",
  "CMD_COPY": "Kopírovať",
  "CMD_PASTE": "Vložiť",
  "CMD_SELECT_ALL": "Vybrať všetko",
  "CMD_SELECT_LINE": "Vybrať riadok",
  "CMD_SPLIT_SEL_INTO_LINES": "Rozdeliť výber na riadky",
  "CMD_ADD_CUR_TO_NEXT_LINE": "Pridať kurzor na nasledujúci riadok",
  "CMD_ADD_CUR_TO_PREV_LINE": "Pridať kurzor na predchádzajúci riadok",
  "CMD_INDENT": "Odsadiť",
  "CMD_UNINDENT": "Vrátiť odsadenie",
  "CMD_DUPLICATE": "Duplikovať",
  "CMD_DELETE_LINES": "Zmazať riadok",
  "CMD_COMMENT": "Riadkový komentár",
  "CMD_BLOCK_COMMENT": "Blokový komentár",
  "CMD_LINE_UP": "Posunúť riadok hore",
  "CMD_LINE_DOWN": "Posunúť riadok dole",
  "CMD_OPEN_LINE_ABOVE": "O riadok vyššie",
  "CMD_OPEN_LINE_BELOW": "O riadok nižšie",
  "CMD_TOGGLE_CLOSE_BRACKETS": "Uzatvárať zátvorky",
  "CMD_SHOW_CODE_HINTS": "Zobraziť tipy",
  "CMD_BEAUTIFY_CODE": "Skrášliť kód",
  "FIND_MENU": "Vyhľadať",
  "CMD_FIND": "Vyhľadať",
  "CMD_FIND_NEXT": "Vyhľadať nasledujúci",
  "CMD_FIND_PREVIOUS": "Vyhľadať predchádzajúci",
  "CMD_FIND_ALL_AND_SELECT": "Nájsť všetko a vybrať",
  "CMD_ADD_NEXT_MATCH": "Pridať ďalšiu zhodu do výberu",
  "CMD_SKIP_CURRENT_MATCH": "Preskočiť a pridať ďalší zápas",
  "CMD_FIND_IN_FILES": "Vyhľadať v súboroch",
  "CMD_FIND_IN_SUBTREE": "Vyhľadať v…",
  "CMD_REPLACE": "Nahradiť",
  "CMD_REPLACE_IN_FILES": "Nahradiť v súboroch",
  "CMD_REPLACE_IN_SUBTREE": "Nahradiť v...",
  "VIEW_MENU": "Zobraziť",
  "CMD_HIDE_SIDEBAR": "Skryť bočný panel",
  "CMD_SHOW_SIDEBAR": "Zobraziť bočný panel",
  "CMD_TOGGLE_SIDEBAR": "Prepnúť bočný panel",
  "CMD_TOGGLE_PANELS": "Prepínanie panelov",
  "CMD_TOGGLE_PURE_CODE": "Žiadne rozptýlenie",
  "CMD_INCREASE_FONT_SIZE": "Zväčšiť veľkosť písma",
  "CMD_DECREASE_FONT_SIZE": "Zmenšiť veľkosť písma",
  "CMD_RESTORE_FONT_SIZE": "Obnoviť veľkosť písma",
  "CMD_SCROLL_LINE_UP": "Posunúť o riadok hore",
  "CMD_SCROLL_LINE_DOWN": "Posunúť o riadok dole",
  "CMD_TOGGLE_LINE_NUMBERS": "Čísla riadkov",
  "CMD_TOGGLE_ACTIVE_LINE": "Zvýrazniť aktívny riadok",
  "CMD_TOGGLE_WORD_WRAP": "Zalomenie riadkov",
  "CMD_LIVE_HIGHLIGHT": "Zvýraznenie živého náhľadu",
  "CMD_VIEW_TOGGLE_INSPECTION": "Súbory na vlákna pri ukladaní",
  "CMD_WORKINGSET_SORT_BY_ADDED": "Usporiadať podľa dátumu",
  "CMD_WORKINGSET_SORT_BY_NAME": "Usporiadať podľa mena",
  "CMD_WORKINGSET_SORT_BY_TYPE": "Usporiadať podľa typu",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "Automatické usporiadanie",
  "CMD_THEMES": "Témy...",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "Automaticky zatvorte vyhľadávanie",
  "NAVIGATE_MENU": "Navigácia",
  "CMD_QUICK_OPEN": "Rýchle otvorenie",
  "CMD_GOTO_LINE": "Prejsť na riadok",
  "CMD_GOTO_DEFINITION": "Prejsť na definíciu",
  "CMD_GOTO_DEFINITION_PROJECT": "Rýchle nájdenie definície v projekte",
  "CMD_GOTO_FIRST_PROBLEM": "Prejsť na prvý problém",
  "CMD_TOGGLE_QUICK_EDIT": "Rýchla úprava",
  "CMD_TOGGLE_QUICK_DOCS": "Rýchla dokumentácia",
  "CMD_QUICK_EDIT_PREV_MATCH": "Predchádzajúca zhoda",
  "CMD_QUICK_EDIT_NEXT_MATCH": "Ďalšia zhoda",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "Nové pravidlo",
  "CMD_NEXT_DOC": "Následujúci dokument",
  "CMD_PREV_DOC": "Predchádzajúci dokument",
  "CMD_NAVIGATE_BACKWARD": "Navigovať dozadu",
  "CMD_NAVIGATE_FORWARD": "Navigovať vpred",
  "CMD_NEXT_DOC_LIST_ORDER": "Ďalší dokument v zozname",
  "CMD_PREV_DOC_LIST_ORDER": "Predchádzajúci dokument v zozname",
  "CMD_SHOW_IN_TREE": "Zobraziť stromovú štruktúru",
  "CMD_SHOW_IN_EXPLORER": "Zobraziť v programe Explorer",
  "CMD_SHOW_IN_FINDER": "Zobraziť vo Finderi",
  "CMD_SHOW_IN_OS": "Zobraziť v OS",
  "CMD_SWITCH_PANE_FOCUS": "Zameranie panela prepí",
  "CMD_OPEN_VFS": "Otvorte virtuálny súborový systém",
  "CMD_OPEN_VIRTUAL_SERVER": "Otvorte virtuálny server",
  "HELP_MENU": "Nápoveda",
  "CMD_CHECK_FOR_UPDATE": "Skontrolovať aktualizácie",
  "CMD_HOW_TO_USE_BRACKETS": "Ako používať {APP_NAME}",
  "CMD_SUPPORT": "{APP_NAME} Podpora",
  "CMD_SUGGEST": "Navrhnúť funkciu",
  "CMD_RELEASE_NOTES": "Poznámky o verzii",
  "CMD_GET_INVOLVED": "Zapojte sa",
  "CMD_SHOW_EXTENSIONS_FOLDER": "Zobraziť priečinok s doplnkami",
  "CMD_HEALTH_DATA_STATISTICS": "Zdravotná správa",
  "CMD_HOMEPAGE": "{APP_NAME} Domovská stránka",
  "CMD_TWITTER": "{TWITTER_NAME} na Twitteri",
  "CMD_ABOUT": "O {APP_TITLE}",
  "CMD_OPEN_PREFERENCES": "Otvoriť súbor predvolieb",
  "CMD_OPEN_KEYMAP": "Otvoriť mapu používateľských kľúčov",
  "EXPERIMENTAL_BUILD": "experimentálna verzia",
  "RELEASE_BUILD": "vybudovať",
  "DEVELOPMENT_BUILD": "vývojová verzia",
  "PRERELEASE_BUILD": "predbežné zostavenie",
  "RELOAD_FROM_DISK": "Načítať z disku",
  "KEEP_CHANGES_IN_EDITOR": "Ponechať zmeny v editore",
  "CLOSE_DONT_SAVE": "Zatvoriť (neukladať)",
  "RELAUNCH_CHROME": "Reštartovať Chrome",
  "ABOUT": "O aplikácii",
  "CLOSE": "Zatvoriť",
  "ABOUT_TEXT_LINE1": "Uvoľnite {VERSION_MAJOR}. {VERSION_MINOR} {BUILD_TYPE} {VERZIA}",
  "ABOUT_TEXT_BUILD_TIMESTAMP": "zostaviť časovú pečiatku: ",
  "ABOUT_TEXT_LINE3": "Knižnice tretích strán, ktoré používame - <a href='https://github.com/phcode-dev/phoenix/tree/main/src/thirdparty/licences'> Licencie a atribúty</a> . ",
  "ABOUT_TEXT_LINE4": "Dokumentácia a zdroj na adrese <a href='https://github.com/phcode-dev/phoenix/'>https://github.com/phcode-dev/phoenix/</a>",
  "ABOUT_TEXT_LINE5": "Vyrobené pomocou ❤ a JavaScriptu:",
  "ABOUT_TEXT_LINE6": "Veľa ľudí (ale máme problémy s načítaním týchto údajov práve teraz).",
  "ABOUT_TEXT_MDN_DOCS": "MDN Docs a the MDN grafické logo sú licencované pod Creative Commons Attribution license, <a class=\"clickable-link\" data-href=\"{MDN_DOCS_LICENSE}\">CC-BY-SA 2.5 Unported</a>.",
  "UPDATE_NOTIFICATION_TOOLTIP": "Je dostupná nová verzia {APP_NAME}! Kliknite sem pre viac detailov.",
  "UPDATE_AVAILABLE_TITLE": "Dostupná aktualizácia",
  "UPDATE_MESSAGE": "Hey, je dostupná nová verzia {APP_NAME}. Zoznam niektorých nových vylepšení:",
  "GET_IT_NOW": "Stiahnuť!",
  "PROJECT_SETTINGS_TITLE": "Nastavenia projketu pre: {0}",
  "PROJECT_SETTING_BASE_URL": "Živý náhľad URL",
  "PROJECT_SETTING_BASE_URL_HINT": "Pre použitie lokálneho servera, vložte URL v tvare http://localhost:8000/",
  "BASEURL_ERROR_INVALID_PROTOCOL": "Protokol {0} nie je podporovaný Živým náhľadom&mdash;prosím použite http: alebo https: .",
  "BASEURL_ERROR_SEARCH_DISALLOWED": "URL adresa nemôže obsahovať výrazy pre hľadanie ako \"{0}\".",
  "BASEURL_ERROR_HASH_DISALLOWED": "URL adresa nemôže obsahovať znaky ako \"{0}\".",
  "BASEURL_ERROR_INVALID_CHAR": "Zvláštné znaky ako '{0}' musia byť %-enkódované.",
  "BASEURL_ERROR_UNKNOWN_ERROR": "Neznáma chyba pri spracovávaní URL",
  "EMPTY_VIEW_HEADER": "<em>Otvortesúbor, keď je táto tabla zameraná</em>",
  "FLIPVIEW_BTN_TOOLTIP": "Preklopenie tohto zobrazenia na panel {0}",
  "CURRENT_THEME": "Aktuálna téma",
  "USE_THEME_SCROLLBARS": "Používanie posúvačov motívov",
  "FONT_SIZE": "Veľkosť písma",
  "FONT_FAMILY": "Rodina písiem",
  "THEMES_SETTINGS": "Nastavenia motívov",
  "BUTTON_NEW_RULE": "Nové pravidlo",
  "INSTALL": "Inštalovať",
  "UPDATE": "Aktualizovať",
  "REMOVE": "Odstrániť",
  "DISABLE": "Zakázať",
  "ENABLE": "Povoliť",
  "OVERWRITE": "Prepísať",
  "CANT_REMOVE_DEV": "Doplnky v \"dev\" priečinku musia byť manuálne odstránené.",
  "CANT_UPDATE": "Aktualizácia nie je kompatibilná s touto verziou {APP_NAME}.",
  "CANT_UPDATE_DEV": "Rozšírenia v priečinku „dev“ sa nedajú automaticky aktualizovať.",
  "INSTALL_EXTENSION_TITLE": "Inštalovať doplnok",
  "UPDATE_EXTENSION_TITLE": "Aktualizovať doplnok",
  "INSTALL_EXTENSION_LABEL": "URL adresa doplnku",
  "INSTALL_EXTENSION_HINT": "URL adresa zip súboru doplnku alebo Git repozitár",
  "INSTALLING_FROM": "Inštalovanie doplnku z {0}…",
  "INSTALL_SUCCEEDED": "Inštalácia bola úspešná!",
  "INSTALL_FAILED": "Inštalácia sa nepodarila.",
  "CANCELING_INSTALL": "Rušenie…",
  "CANCELING_HUNG": "Zrušenie inštalácie trvá dlho. Mohlo prísť k internej chybe.",
  "INSTALL_CANCELED": "Inštalácia zrušená.",
  "VIEW_COMPLETE_DESCRIPTION": "Zobraziť úplný popis",
  "VIEW_TRUNCATED_DESCRIPTION": "Zobraziť skrátený popis",
  "SORT_EXTENSION_METHOD": "Zoradenie rozšírení pomocou aplikácie DownloadCount alebo PublishedDate",
  "INVALID_ZIP_FILE": "Stiahnutý obsah nie je platný zip súbor.",
  "MISSING_PACKAGE_JSON": "Balík nemá súbor package.json.",
  "INVALID_PACKAGE_JSON": "Súbor package.json nie je platný (chyba bola: {0}).",
  "MISSING_PACKAGE_NAME": "Súbor package.json nešpecifikuje názov balíku.",
  "BAD_PACKAGE_NAME": "{0} je neplatný názov balíka.",
  "MISSING_PACKAGE_VERSION": "Súbor package.json nešpecifikuje verziu súboru.",
  "INVALID_VERSION_NUMBER": "Balík verzie ({0}) je neplatný.",
  "INVALID_BRACKETS_VERSION": "Reťazec kompatibility ({0}) pre {APP_NAME} je neplatný.",
  "DISALLOWED_WORDS": "Slová ({1}) nie sú povolené v {0} poli.",
  "NPM_INSTALL_FAILED": "npm install príkaz zlyhal: {0}",
  "API_NOT_COMPATIBLE": "Balík nie je kompatibilný s verziou {APP_NAME}. Nájdete ho v zložke vypnuté doplnky.",
  "MISSING_MAIN": "Balík nemá žiadny súbor main.js.",
  "EXTENSION_ALREADY_INSTALLED": "Inštalácia tohto balíku prepíše nainštalovaný doplnok. Prepísať starý doplnok?",
  "EXTENSION_SAME_VERSION": "Tento balík je rovnakej verzie ako aktuálne nainštalovaný. Prepísať existujúci doplnok?",
  "EXTENSION_OLDER_VERSION": "Tento balík je verzie {0}, ktorá je staršia ako aktuálne nainštalovaná ({1}). Prepísať existujúci doplnok?",
  "DOWNLOAD_ID_IN_USE": "Interná chyba: ID sťahovania sa už používa.",
  "NO_SERVER_RESPONSE": "Nie je možné pripojiť sa k serveru.",
  "BAD_HTTP_STATUS": "Súbor nebol nájdený na serveri (HTTP {0}).",
  "CANNOT_WRITE_TEMP": "Nie je možné uložiť do dočasného súboru.",
  "ERROR_LOADING": "Pri spúšťaní doplnku prišlo k chybe.",
  "MALFORMED_URL": "URL adresa je chybná. Prosím skontrolujte ju, či je zadaná správne.",
  "UNSUPPORTED_PROTOCOL": "URL adresa musí byť http alebo https.",
  "UNKNOWN_ERROR": "Neznáma chyba",
  "EXTENSION_MANAGER_TITLE": "Správca doplnkov",
  "EXTENSION_MANAGER_ERROR_LOAD": "Nie je možné získať prístup k registrom doplnkov. Prosím, skúste to znovu neskôr.",
  "INSTALL_EXTENSION_DRAG": "Presuňte .zip sem alebo",
  "INSTALL_EXTENSION_DROP": "Drop .zip na inštaláciu",
  "INSTALL_EXTENSION_DROP_ERROR": "Inštalácia/aktualizácia prerušená z dôvodu nasledujúcich chýb:",
  "INSTALL_FROM_URL": "Inštalovať z URL…",
  "INSTALL_EXTENSION_VALIDATING": "Overenie...",
  "EXTENSION_AUTHOR": "Autor",
  "EXTENSION_DATE": "Dátum",
  "EXTENSION_INCOMPATIBLE_NEWER": "Tento doplnok vyžaduje novšiu verziu {APP_NAME}.",
  "EXTENSION_INCOMPATIBLE_OLDER": "Tento doplnok momentálne funguje iba zo staršími verziami {APP_NAME}.",
  "EXTENSION_LATEST_INCOMPATIBLE_NEWER": "Verzia {0} tohto rozšírenia vyžaduje novšiu verziu {APP_NAME}. Ale môžete nainštalovať staršiu verziu {1}.",
  "EXTENSION_LATEST_INCOMPATIBLE_OLDER": "Verzia {0} tohto rozšírenia funguje len so staršími verziami {APP_NAME}. Ale môžete nainštalovať staršiu verziu {1}.",
  "EXTENSION_NO_DESCRIPTION": "Bez popisu",
  "EXTENSION_MORE_INFO": "Viac informácií...",
  "EXTENSION_ERROR": "Chyba doplnku",
  "EXTENSION_KEYWORDS": "Kľúčové slová",
  "EXTENSION_TRANSLATED_USER_LANG": "Preložené do {0} jazykov vrátane vašich",
  "EXTENSION_TRANSLATED_GENERAL": "Preložené do {0} jazykov",
  "EXTENSION_TRANSLATED_LANGS": "Toto rozšírenie bolo preložené do týchto jazykov: {0}",
  "EXTENSION_INSTALLED": "Nainštalované",
  "EXTENSION_UPDATE_INSTALLED": "Aktualizácia tohto doplnku bola stiahnutá a bude nainštalovaná keď ukončíte {APP_NAME}.",
  "EXTENSION_SEARCH_PLACEHOLDER": "Hľadať",
  "EXTENSION_MORE_INFO_LINK": "Viac",
  "BROWSE_EXTENSIONS": "Prechádzať doplnky",
  "EXTENSION_MANAGER_REMOVE": "Odstrániť doplnok",
  "EXTENSION_MANAGER_REMOVE_ERROR": "Nie je možné odstrániť jeden alebo viac doplnkov: {0}. {APP_NAME} bude ukončená.",
  "EXTENSION_MANAGER_UPDATE": "Aktualizovať doplnok",
  "EXTENSION_MANAGER_UPDATE_ERROR": "Nie je možné aktualizovať jeden alebo viac doplnkov: {0}. {APP_NAME} bude ukončená.",
  "EXTENSION_MANAGER_DISABLE": "Zakázať rozšírenie",
  "EXTENSION_MANAGER_DISABLE_ERROR": "Nie je možné zakázať jedno alebo viac rozšírení: {0}. {APP_NAME} sa bude naďalej znovu načítať.",
  "MARKED_FOR_REMOVAL": "Označené pre odstránenie",
  "UNDO_REMOVE": "Späť",
  "MARKED_FOR_UPDATE": "Označené pre aktualizáciu",
  "UNDO_UPDATE": "Späť",
  "MARKED_FOR_DISABLING": "Označené pre deaktiváciu",
  "UNDO_DISABLE": "Späť",
  "CHANGE_AND_RELOAD_TITLE": "Zmeniť rozšírenia",
  "CHANGE_AND_RELOAD_MESSAGE": "Ak chcete aktualizovať, odstrániť alebo zakázať označené rozšírenia, {APP_NAME} bude potrebné znova načítať. Zobrazí sa výzva na uloženie neuložených zmien.",
  "REMOVE_AND_RELOAD": "Odstrániť rozšírenia a znovu načítať",
  "CHANGE_AND_RELOAD": "Zmena rozšírení a znovu načítať",
  "UPDATE_AND_RELOAD": "Aktualizovať rozšírenia a znovu načítať",
  "DISABLE_AND_RELOAD": "Zakázať rozšírenia a znovu načítať",
  "PROCESSING_EXTENSIONS": "Zmeny rozšírenia spracovania...",
  "EXTENSION_NOT_INSTALLED": "Nie je možné odstrániť doplnok {0}, pretože nebol nainštalovaný",
  "NO_EXTENSIONS": "Nie sú nainštalované žiadne doplnky.<br>Click on the Available tab above to get started.",
  "NO_EXTENSION_MATCHES": "Nenašiel sa žiadny doplnok.",
  "REGISTRY_SANITY_CHECK_WARNING": "Buďte opatrní pri inštalácií doplnkov z neznámeho zdroja.",
  "EXTENSIONS_INSTALLED_TITLE": "Nainštalované",
  "EXTENSIONS_DEFAULT_TITLE": "Predvolené",
  "EXTENSIONS_AVAILABLE_TITLE": "Dostupné",
  "EXTENSIONS_THEMES_TITLE": "Témy",
  "EXTENSIONS_UPDATES_TITLE": "Aktualizácie",
  "EXTENSIONS_LAST_UPDATED": "Naposledy aktualizované",
  "EXTENSIONS_DOWNLOADS": "Súbory na stiahnutie",
  "INLINE_EDITOR_NO_MATCHES": "Nie sú k dispozícii žiadne zhody.",
  "INLINE_EDITOR_HIDDEN_MATCHES": "Všetky zápasy sú zrútené. Ak chcete zobraziť zhody, rozbaľte súbory uvedené vpravo.",
  "CSS_QUICK_EDIT_NO_MATCHES": "Neexistujú žiadne pravidlá CSS, ktoré by zodpovedali vášmu výberu. <br> Kliknitena „Nové pravidlo“ pre vytvorenie jedného.",
  "CSS_QUICK_EDIT_NO_STYLESHEETS": "Vo vašom projekte nie sú žiadne štýly. <br>Vytvortejeden pre pridanie pravidiel CSS.",
  "IMAGE_VIEWER_LARGEST_ICON": "najväčší",
  "UNIT_PIXELS": "pixely",
  "DEBUG_MENU": "Ladenie",
  "ERRORS": "Chyby",
  "CMD_SHOW_DEV_TOOLS": "Zobraziť vývojárske nástroje",
  "CMD_REFRESH_WINDOW": "Reštartovať {APP_NAME}",
  "CMD_RELOAD_WITHOUT_USER_EXTS": "Znovu načítať bez rozšírení",
  "CMD_NEW_BRACKETS_WINDOW": "Nové {APP_NAME} okno",
  "CMD_LAUNCH_SCRIPT_MAC": "Inštalácia skratky príkazového riadka",
  "CMD_SWITCH_LANGUAGE": "Zmeniť jazyk",
  "CMD_RUN_UNIT_TESTS": "Spustiť testy",
  "CMD_SHOW_PERF_DATA": "Zobraziť údaje o výkone",
  "CMD_ENABLE_LOGGING": "Povoliť podrobné protokoly",
  "CMD_OPEN_BRACKETS_SOURCE": "Otvoriť {APP_NAME} Zdroj",
  "CREATING_LAUNCH_SCRIPT_TITLE": "{APP_NAME} Skratka príkazového riadka",
  "ERROR_CREATING_LAUNCH_SCRIPT": "Pri inštalácii skratky príkazového riadka sa vyskytla chyba. Vyskúšajte <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting'>tieto návrhy na riešenie problémov</a>. <br/><br/>Dôvod: {0}",
  "ERROR_CLTOOLS_RMFAILED": "Nepodarilo sa odstrániť existujúci symbolický odkaz <code>/usr/local/bin/brackets</code> .",
  "ERROR_CLTOOLS_MKDIRFAILED": "Nepodarilo sa vytvoriť adresár <code>/usr/local/bin</code> .",
  "ERROR_CLTOOLS_LNFAILED": "Nepodarilo sa vytvoriť symbolický odkaz <code>/usr/local/bin/brackets</code> .",
  "ERROR_CLTOOLS_SERVFAILED": "Vnútorná chyba.",
  "ERROR_CLTOOLS_NOTSUPPORTED": "Skratka príkazového riadka nie je v tomto operačnom systéme podporovaná.",
  "LAUNCH_SCRIPT_CREATE_SUCCESS": "Úspech! Teraz môžete ľahko spustiť {APP_NAME} z príkazového riadku: <code>zátvorky myFile.txt</code> otvoriť súbor alebo <code>zátvorky MyFolder</code> prepínať projekty. <br/><br/><a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments'>Ďalšie informácie</a> o používaní {APP_NAME} nájdete v príkazovom riadku.",
  "LANGUAGE_TITLE": "Zmeniť jazyk",
  "LANGUAGE_MESSAGE": "Jazyk:",
  "LANGUAGE_SUBMIT": "Reštartovať {APP_NAME}",
  "LANGUAGE_CANCEL": "Zrušiť",
  "LANGUAGE_SYSTEM_DEFAULT": "Predvolený v systéme",
  "HEALTH_DATA_NOTIFICATION": "Predvoľby zdravotnej správy",
  "HEALTH_FIRST_POPUP_TITLE": "{APP_NAME} Zdravotná správa",
  "HEALTH_DATA_DO_TRACK": "Zdieľanie pseudonymných informácií o tom, ako používam {APP_NAME}",
  "HEALTH_DATA_NOTIFICATION_MESSAGE": "Aby sme zlepšili {APP_NAME}, pravidelne odosielame do core.ai obmedzené <strong>pseudonymné</strong> štatistiky o tom, ako používate {APP_NAME}. Tieto informácie pomáhajú uprednostňovať funkcie, nájsť chyby a odhaliť problémy s použiteľnosťou a zároveň chrániť vaše súkromie. <br><br>Môžetezobraziť svoje údaje alebo sa rozhodnúť nezdieľať údaje výberom položky <strong>Pomocník > Správa o stave</strong>. <br><br>",
  "HEALTH_DATA_PREVIEW": "{APP_NAME} Zdravotná správa",
  "HEALTH_DATA_PREVIEW_INTRO": "<p>Abysme zlepšili {APP_NAME}, pravidelne odosielame do core.ai obmedzené <strong>pseudonymné</strong> štatistiky o tom, ako používate {APP_NAME}. Tieto informácie pomáhajú uprednostňovať funkcie, nájsť chyby a odhaliť problémy s použiteľnosťou. </p><p>Nižšieje ukážka údajov, ktoré budú odoslané v nasledujúcej zdravotnej správe, <em>ak</em> je povolená. </p>",
  "INLINE_TIMING_EDITOR_TIME": "Čas",
  "INLINE_TIMING_EDITOR_PROGRESSION": "Progresie",
  "BEZIER_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd><kbd>←<kbd>→</kbd>Presunúť</kbd>vybraný bod<br><kbd class='text'>Shift Presun</kbd>o desať jednotiek<br><kbd class='text'>Tab</kbd>Prepínacie body",
  "STEPS_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd>Zvýšenie alebo zníženie krokov<br><kbd>←</kbd><kbd>→</kbd>'Štart' alebo 'Koniec'",
  "INLINE_TIMING_EDITOR_INVALID": "Stará hodnota <code>{0}</code> nie je platná, takže zobrazená funkcia bola zmenená na <code>{1}</code> . Dokument sa aktualizuje prvou úpravou.",
  "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP": "Aktuálna farba",
  "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP": "Pôvodná farba",
  "COLOR_EDITOR_RGBA_BUTTON_TIP": "RGBa formát",
  "COLOR_EDITOR_HEX_BUTTON_TIP": "Hex formát",
  "COLOR_EDITOR_HSLA_BUTTON_TIP": "HSLa formát",
  "COLOR_EDITOR_0X_BUTTON_TIP": "Hex (0x) Formát",
  "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR": "{0} (Použité {1} krát)",
  "COLOR_EDITOR_USED_COLOR_TIP_PLURAL": "{0} (Použité {1} krát)",
  "CMD_JUMPTO_DEFINITION": "Prejsť na definíciu",
  "CMD_SHOW_PARAMETER_HINT": "Ukázať pomôcku parametra",
  "NO_ARGUMENTS": "<žiadne parametre>",
  "DETECTED_EXCLUSION_TITLE": "JavaScript súbor inferencie problém",
  "DETECTED_EXCLUSION_INFO": "{APP_NAME} narazil na problémy so spracovaním <span class='dialog-filename'>{0}</span>. <br><br>Tentosúbor sa už nebude spracovávať pre rady s kódom, Prejsť na definíciu alebo Rýchle úpravy. Ak chcete tento súbor znova povoliť, otvorte vo svojom projekte <code>.brackets.json</code> a upravte <code>JScodeHints.DetecteDExclusions</code> . <br><br>Totoje pravdepodobne chyba {APP_NAME}. Ak môžete poskytnúť kópiu tohto súboru, zadajte <a href='https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue'>chybu s</a> odkazom na súbor, ktorý je tu uvedený.",
  "CMD_REFACTOR": "refaktor",
  "CMD_EXTRACTTO_VARIABLE": "Výpis do premennej",
  "CMD_EXTRACTTO_FUNCTION": "Extrahovať do funkcie",
  "ERROR_TERN_FAILED": "Nie je možné získať údaje od spoločnosti Tern",
  "ERROR_EXTRACTTO_VARIABLE_NOT_VALID": "Výber netvorí výraz",
  "ERROR_EXTRACTTO_FUNCTION_NOT_VALID": "Vybraný blok by mal predstavovať množinu príkazov alebo výrazov",
  "ERROR_EXTRACTTO_VARIABLE_MULTICURSORS": "Extrakt do premennej nefunguje v multicurzoroch",
  "ERROR_EXTRACTTO_FUNCTION_MULTICURSORS": "Extrakt do funkcie nefunguje v multicurzoroch",
  "EXTRACTTO_FUNCTION_SELECT_SCOPE": "Vyberte rozsah cieľa",
  "EXTRACTTO_VARIABLE_SELECT_EXPRESSION": "Vyberte výraz",
  "CMD_REFACTORING_RENAME": "Premenovať",
  "CMD_REFACTORING_TRY_CATCH": "Zabaliť v Try Catch",
  "CMD_REFACTORING_CONDITION": "Zabaliť v stave",
  "CMD_REFACTORING_GETTERS_SETTERS": "Vytvoriť Getters/Setters",
  "CMD_REFACTORING_ARROW_FUNCTION": "Prevod na funkciu šípky",
  "DESCRIPTION_CODE_REFACTORING": "Povolenie/vypnutie refaktoringu kódu JavaScriptu",
  "ERROR_TRY_CATCH": "Vyberte platný kód, ktorý chcete zabaliť do bloku TRY-catch",
  "ERROR_WRAP_IN_CONDITION": "Vyberte platný kód, ktorý chcete zabaliť do bloku Podmienka",
  "ERROR_ARROW_FUNCTION": "Umiestnite kurzor do funkčného výrazu",
  "ERROR_GETTERS_SETTERS": "Umiestnenie kurzora na člen výrazu objektu",
  "ERROR_RENAME_MULTICURSOR": "Nie je možné premenovať pri použití viacerých kurzorov",
  "ERROR_RENAME_QUICKEDIT": "Tento identifikátor nie je možné premenovať, pretože sa odkazuje inde mimo tejto funkcie",
  "ERROR_RENAME_GENERAL": "Nie je možné premenovať vybraný text",
  "JSHINT_NAME": "JSHint",
  "CMD_ENABLE_QUICK_VIEW": "Rýchly náhľad",
  "CMD_ENABLE_SELECTION_VIEW": "Zobrazenie výberu",
  "CMD_TOGGLE_RECENT_PROJECTS": "Nedávne projekty",
  "DOCS_MORE_LINK": "Viac",
  "COLLAPSE_ALL": "Zbaliť všetko",
  "EXPAND_ALL": "Rozbaliť všetko",
  "COLLAPSE_CURRENT": "Zbaliť prúd",
  "EXPAND_CURRENT": "Rozbaliť prúd",
  "RECENT_FILES_DLG_HEADER": "Posledné súbory",
  "RECENT_FILES_DLG_CLEAR_BUTTON_LABEL": "Vymazať",
  "RECENT_FILES_DLG_CLEAR_BUTTON_TITLE": "Vymazať súbory nie sú v pracovnej sade",
  "DESCRIPTION_CLOSE_BRACKETS": "true pre automatické zatvorenie zátvoriek, zátvoriek a zátvoriek",
  "DESCRIPTION_CLOSE_OTHERS_ABOVE": "false odstrániť „Zavrieť ostatné vyššie“ z kontextového menu Pracovné súbory",
  "DESCRIPTION_CLOSE_OTHERS_BELOW": "false, aby ste odstránili položku „Zatvoriť ostatné nižšie“ z kontextového menu Pracovné súbory",
  "DESCRIPTION_CLOSE_OTHERS": "false odstrániť „Zatvoriť ostatné“ z kontextového menu Pracovné súbory",
  "DESCRIPTION_CLOSE_TAGS": "Nastavuje možnosti zatvárania tagov",
  "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS": "Pole značiek, ktoré by sa nemali automaticky zatvárať",
  "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING": "Zatvorte, keď je zadaná> otváracej značky",
  "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING": "Zatvorte, keď je zadaný/zatváracej značky",
  "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS": "Pole značiek, ktoré po otvorení majú prázdny riadok",
  "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD": "true vždy generovať skladacie značky sekcií pri zmene úrovne odsadenia",
  "DESCRIPTION_CODE_FOLDING_ENABLED": "true na povolenie skladania kódu",
  "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER": "true, aby sa značky zrútenia sekcie viditeľné len vtedy, keď presuniete myšou nad žľab",
  "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL": "Obmedzuje, koľko úrovní hlboko Zbaliť všetko platí",
  "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE": "Minimálne riadky pred zobrazením ikony skladacieho oddielu",
  "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES": "true na zapamätanie zbalených sekcií, ak zatvoríte a znovu otvoríte súbor alebo projekt",
  "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE": "true pre povolenie skladania kódu na vybraný text v editore",
  "DESCRIPTION_DISABLED_DEFAULT_EXTENSIONS": "Predvolené rozšírenia, ktoré sú zakázané",
  "DESCRIPTION_ATTR_HINTS": "Zapnúť/zakázať rady atribútov HTML",
  "DESCRIPTION_CSS_PROP_HINTS": "Zapnúť/zakázať rady vlastností CSS/LESS/SCSS",
  "DESCRIPTION_JS_HINTS": "Povolenie/vypnutie náznakov kódu JavaScriptu",
  "DESCRIPTION_JS_HINTS_TYPE_DETAILS": "Zapnúť/vypnúť podrobnosti o typoch údajov v tipoch kódu JavaScriptu",
  "DESCRIPTION_PREF_HINTS": "Zapnúť/zakázať predvoľby tipy na kód",
  "DESCRIPTION_SPECIAL_CHAR_HINTS": "Povolenie/vypnutie náznakov entity HTML",
  "DESCRIPTION_SVG_HINTS": "Zapnúť/zakázať rady s kódom SVG",
  "DESCRIPTION_HTML_TAG_HINTS": "Povolenie/vypnutie náznakov HTML",
  "DESCRIPTION_URL_CODE_HINTS": "Zapnúť/zakázať URL rady v HTML & CSS/LESS/SCSS",
  "DESCRIPTION_DRAG_DROP_TEXT": "Zapnúť/zakázať funkciu Drag & Drop",
  "DESCRIPTION_HEALTH_DATA_TRACKING": "Povoliť sledovanie zdravotných údajov",
  "DESCRIPTION_HIGHLIGHT_MATCHES": "Umožňuje automatické zvýraznenie zodpovedajúcich reťazcov v celom dokumente",
  "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN": "Zvýraznite všetky reťazce, ktoré zodpovedajú tokenu, v akom sa momentálne nachádza kurzor (nie je potrebný žiadny výber)",
  "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY": "Zvýraznite iba vtedy, keď je výber kompletným tokenom",
  "DESCRIPTION_INSERT_HINT_ON_TAB": "true pre vloženie aktuálne vybraného náznaku kódu na kartu",
  "DESCRIPTION_NO_HINTS_ON_DOT": "true, aby automaticky nezobrazovať tipy kódu JS, keď je napísaný",
  "DESCRIPTION_JSHINT_OPTIONS": "Objekt s predvolenými možnosťami pre JSHint. Pozrite si nasledujúcu adresu URL pre všetky dostupné možnosti JSHint: https://jshint.com/docs/options/",
  "DESCRIPTION_LANGUAGE": "Nastavenia špecifické pre jazyk",
  "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS": "Ďalšie mapovania z prípony súboru na názov jazyka",
  "DESCRIPTION_LANGUAGE_FILE_NAMES": "Ďalšie mapovania od názvu súboru k názvu jazyka",
  "DESCRIPTION_LINEWISE_COPY_CUT": "Ak chcete kopírovať a strihať, keď nie je výber, skopíruje alebo vystrihne celé riadky, ktoré majú v nich kurzory",
  "DESCRIPTION_INPUT_STYLE": "Vyberá spôsob, akým CodeMirror spracováva vstup a zaostrenie. Môže to byť textarea, ktorá je predvolená alebo contenteditable, čo je lepšie pre čítačky obrazovky (nestabilné)",
  "DESCRIPTION_LINTING_ENABLED": "true, aby sa povolila kontrola kódu",
  "DESCRIPTION_ASYNC_TIMEOUT": "Čas v milisekundách, po ktorom asynchrónne linters oddychrónne",
  "DESCRIPTION_LINTING_PREFER": "Pole linterov, ktoré sa majú spustiť ako prvé",
  "DESCRIPTION_LIVE_DEV_MULTIBROWSER": "true pre povolenie experimentálnej Live Preview",
  "DESCRIPTION_USE_PREFERED_ONLY": "true spustiť poskytovateľov uvedených v linting.prefer iba",
  "DESCRIPTION_MAX_CODE_HINTS": "Maximálny počet naraz zobrazených tipov kódu",
  "DESCRIPTION_PATH": "Nastavenia špecifické pre cestu",
  "DESCRIPTION_PROXY": "URL servera proxy používaného na inštaláciu rozšírenia",
  "DESCRIPTION_SCROLL_PAST_END": "true, aby sa umožnilo posúvanie za koniec dokumentu",
  "DESCRIPTION_SHOW_CODE_HINTS": "false vypnúť všetky rady s kódom",
  "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING": "Udržuje blikajúci kurzor viditeľný, keď máte výber textu",
  "DESCRIPTION_SHOW_LINE_NUMBERS": "true pre zobrazenie čísel riadkov v „žľabe“ naľavo od kódu",
  "DESCRIPTION_SMART_INDENT": "Automatické odsadenie pri vytváraní nového bloku",
  "DESCRIPTION_SOFT_TABS": "false vypnúť správanie mäkkých kariet",
  "DESCRIPTION_SORT_DIRECTORIES_FIRST": "true zoradiť adresáre ako prvé v strome projektu",
  "DESCRIPTION_SPACE_UNITS": "Počet medzier, ktoré sa majú použiť na odsadenie podľa priestoru",
  "DESCRIPTION_STATIC_SERVER_PORT": "Číslo portu, ktoré by mal vstavaný server použiť pre Live Preview",
  "DESCRIPTION_STYLE_ACTIVE_LINE": "true pre zvýraznenie farby pozadia riadku, na ktorý je kurzor",
  "DESCRIPTION_TAB_SIZE": "Počet medzier, ktoré sa majú zobraziť pre karty",
  "DESCRIPTION_USE_TAB_CHAR": "true používať karty namiesto medzier",
  "DESCRIPTION_UPPERCASE_COLORS": "true pre generovanie veľké hexadecimné farby v Inline Color Editor",
  "DESCRIPTION_WORD_WRAP": "Omotanie čiar, ktoré presahujú šírku výrezu",
  "DESCRIPTION_SEARCH_AUTOHIDE": "Zatvorte vyhľadávanie hneď, ako je editor zameraný",
  "DESCRIPTION_DETECTED_EXCLUSIONS": "Zoznam súborov, ktoré boli zistené, aby spôsobili, že sa Tern vymkol kontrole",
  "DESCRIPTION_INFERENCE_TIMEOUT": "Množstvo času, po ktorom bude Tern časový čas pri pokuse porozumieť súborom",
  "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR": "true pre zobrazenie chýb v stavovom riadku",
  "DESCRIPTION_QUICK_VIEW_ENABLED": "true na zapnutie Rýchleho zobrazenia",
  "DESCRIPTION_SELECTION_VIEW_ENABLED": "true, aby sa povolilo zobrazenie výberu",
  "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW": "true na zobrazenie náhľadov obrázkov pre chýbajúce rozšírenia URL",
  "DESCRIPTION_THEME": "Vyberte tému {APP_NAME}",
  "DESCRIPTION_USE_THEME_SCROLLBARS": "true, aby sa umožnili vlastné posuvné lišty",
  "DESCRIPTION_LINTING_COLLAPSED": "true zbaliť linting panel",
  "DESCRIPTION_FONT_FAMILY": "Zmena rodiny písiem",
  "DESCRIPTION_FONT_SIZE": "Zmena veľkosti písma; napr. 13px",
  "DESCRIPTION_FIND_IN_FILES_NODE": "true na povolenie vyhľadávania založeného na uzloch",
  "DESCRIPTION_FIND_IN_FILES_INSTANT": "true, aby sa umožnilo okamžité vyhľadávanie",
  "DESCRIPTION_FONT_SMOOTHING": "Iba Mac: „subpixel-antialiased“ na povolenie vyhladzovania subpixelov alebo „antialiased“ pre antialiasing stupnice šedej stupnice",
  "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW": "false zakázať otvorenie súboru predvolieb v rozdelenom zobrazení",
  "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE": "false otvoriť súbor preferencií používateľa v ľavej/hornom paneli",
  "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED": "true pre zbalenie tabúľ po zatvorení posledného súboru z tabla pomocou tlačidla zatvorenia hlavičky tabule",
  "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS": "Prepnite, kedy sa na hlavičke zobrazia tlačidlá zatvárania a preklopenia.",
  "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT": "/*\n * Toto je súbor len na čítanie s podporovanými preferenciami\n * podľa {APP_NAME}.\n * Použite tento súbor ako referenciu na úpravu vašich preferencií\n * súbor „brackets.json“ otvorený v druhej table.\n * Ďalšie informácie o tom, ako používať predvoľby vo vnútri\n * {APP_NAME}, pozrite si webovú stránku na adrese https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences\n */",
  "DEFAULT_PREFERENCES_JSON_DEFAULT": "Predvolené",
  "DESCRIPTION_PURE_CODING_SURFACE": "true pre povolenie režimu iba kódu a skrytie všetkých ostatných prvkov používateľského rozhrania v {APP_NAME}",
  "DESCRIPTION_INDENT_LINE_COMMENT": "true, aby sa umožnilo odsadenie riadkových komentárov",
  "DESCRIPTION_RECENT_FILES_NAV": "Zapnúť/zakázať navigáciu v posledných súboroch",
  "DESCRIPTION_LIVEDEV_WEBSOCKET_PORT": "Port, na ktorom WebSocket Server beží pre Live Preview",
  "DESCRIPTION_LIVE_DEV_HIGHLIGHT_SETTINGS": "Nastavenia zvýraznenia Live Preview",
  "DESCRIPTION_LIVEDEV_ENABLE_REVERSE_INSPECT": "false zakázať živý náhľad spätnej kontroly",
  "DOWNLOAD_FAILED": "Preberanie zlyhalo.",
  "DOWNLOAD_COMPLETE": "Stiahnite si kompletné!",
  "UPDATE_SUCCESSFUL": "Aktualizácia bola úspešná!",
  "UPDATE_FAILED": "Aktualizácia zlyhala!",
  "VALIDATION_FAILED": "Validácia zlyhala!",
  "INITIALISATION_FAILED": "Inicializácia zlyhala!",
  "CLEANUP_FAILED": "Vyčistenie zlyhalo!",
  "WARNING_TYPE": "Varovanie!",
  "CLICK_RESTART_TO_UPDATE": "Kliknite na tlačidlo Reštartovať aktualizujte zátvorky.",
  "UPDATE_ON_NEXT_LAUNCH": "Aktualizácia sa použije pri opätovnom spustení.",
  "GO_TO_SITE": "Prejdite na <a href = \"http://brackets.io/ „> brackets.io </a> opakovať.",
  "INTERNET_UNAVAILABLE": "Nie je k dispozícii internetové pripojenie.",
  "UPDATEDIR_READ_FAILED": "Adresár aktualizácie sa nepodarilo prečítať.",
  "UPDATEDIR_CLEAN_FAILED": "Aktualizačný adresár sa nepodarilo vyčistiť.",
  "INITIAL_DOWNLOAD": "Sťahovanie aktualizácie...",
  "RETRY_DOWNLOAD": "Preberanie zlyhalo. Opakovanie... Pokus ",
  "VALIDATING_INSTALLER": "Stiahnite si kompletné! Overenie inštalátora...",
  "CHECKSUM_DID_NOT_MATCH": "Kontrolný súčet sa nezhodoval.",
  "INSTALLER_NOT_FOUND": "Inštalátor nebol nájdený.",
  "DOWNLOAD_ERROR": "Počas sťahovania sa vyskytla chyba.",
  "NETWORK_SLOW_OR_DISCONNECTED": "Sieť je odpojená alebo príliš pomalá.",
  "RESTART_BUTTON": "Reštartovať",
  "LATER_BUTTON": "Neskôr",
  "DESCRIPTION_AUTO_UPDATE": "Zapnúť/vypnúť zátvorky Automatická aktualizácia",
  "AUTOUPDATE_ERROR": "Chyba!",
  "AUTOUPDATE_IN_PROGRESS": "Aktualizácia už prebieha.",
  "NUMBER_WITH_PERCENTAGE": "{0}%",
  "CMD_FIND_RELATED_FILES": "Nájsť súvisiace súbory",
  "PHP_VERSION_INVALID": "Chyba pri analýze PHP verzie. Skontrolujte výstup príkazu „php —version“.",
  "PHP_UNSUPPORTED_VERSION": "Nainštalujte PHP7 runtime na povolenie nástrojov súvisiacich s PHP, ako sú tipy na kód, rady parametrov, Prejsť na definíciu a ďalšie. Nájdená verzia: {0}",
  "PHP_EXECUTABLE_NOT_FOUND": "PHP runtime nebol nájdený. Nainštalujte PHP7 runtime a aktualizujte „ExecutablePath“ v predvoľbách PHP vhodne. To umožňuje nástroje súvisiace s PHP, ako sú tipy na kód, rady parametrov, Prejsť na definíciu a ďalšie.",
  "PHP_PROCESS_SPAWN_ERROR": "Pri spustení procesu PHP sa vyskytla chyba {0}.",
  "PHP_SERVER_ERROR_TITLE": "Chyba",
  "PHP_SERVER_MEMORY_LIMIT_INVALID": "Limit pamäte, ktorý ste zadali, je neplatný. Ak chcete nastaviť správnu hodnotu, skontrolujte predvoľby PHP.",
  "DESCRIPTION_PHP_TOOLING_CONFIGURATION": "Predvolené nastavenia konfigurácie PHP Tooling",
  "OPEN_PREFERENNCES": "Otvorte predvoľby",
  "LANGUAGE_TOOLS_PREFERENCES": "Predvoľby pre jazykové nástroje",
  "FIND_ALL_REFERENCES": "Nájsť všetky referencie",
  "REFERENCES_IN_FILES": "referencie",
  "REFERENCE_IN_FILES": "referencie",
  "REFERENCES_NO_RESULTS": "Pre aktuálnu pozíciu kurzora nie sú k dispozícii žiadne referencie",
  "CMD_FIND_DOCUMENT_SYMBOLS": "Nájsť symboly dokumentu",
  "CMD_FIND_PROJECT_SYMBOLS": "Nájsť symboly projektu",
  "REMOTE_DEBUGGING_ENABLED": "Vzdialené ladenie povolené na localhost:",
  "REMOTE_DEBUGGING_PORT_INVALID": "Nie je možné povoliť vzdialené ladenie na porte {0}. Čísla portov by mali byť medzi {1} a {2}.",
  "DESCRIPTION_EXTERNAL_APPLICATION_ASSOCIATE": "Mapovanie rozšírenia súboru na externé aplikácie. Syntax: \"<file_type>„: „<default|ApplicationName|ApplicationPath>“, Použite „default“ na otvorenie súborov v systémovej predvolenej aplikácii pre daný typ súboru.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_TITLE": "Otvorte grafické súbory v externých editoroch.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_MSG": "Váš aktuálny priečinok obsahuje grafické typy súborov, ktoré nie sú podporované {APP_NAME}. <br/>Terazmôžete priradiť konkrétne typy súborov s externými editormi. Po priradení môžete otvoriť grafické súbory ako .xd, .psd, .jpg, .png, .ai, .svg v ich predvolených aplikáciách dvojitým kliknutím na súbory v Strome súborov. <br/><br/>Kliknutímna tlačidlo „Ok“ priraďte typy grafických súborov k príslušným predvoleným aplikáciám.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_CNF_MSG": "Nasledujúce typy súborov boli úspešne priradené k predvoleným aplikáciám. <br/>{0} Máte možnosť zmeniť svoje preferencie, či odstránite alebo pridáte nové združenia typov súborov v brackets.json tak, že prejdete do ponuky „Debug->Otvoriť súbor predvolieb“.",
  "UNSUPPORTED_BROWSER": "Prehliadač nie je podporovaný",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER": "Prehliadač nepodporuje Otvoriť priečinok",
  "UNSUPPORTED_BROWSER_MESSAGE_LINE1": "Použite jeden z podporovaných prehliadačov nižšie.",
  "UNSUPPORTED_BROWSER_MESSAGE_LINE2": " Usilovne pracujeme na tom, aby bol Phoenix dostupný vo viacerých prehliadačoch. Tento dialóg môžete zatvoriť, ale niektoré funkcie vo Phoenixe v tomto prehliadači nebudú fungovať.",
  "CANNOT_PUBLISH_LARGE_PROJECT": "Nie je možné publikovať veľký projekt",
  "CANNOT_PUBLISH_LARGE_PROJECT_MESSAGE": "Phoenix je stále v experimentálnej alfa. Zatiaľ sme nepovolili synchronizáciu projektov s viac ako 500 súbormi.",
  "SHARE_WEBSITE": "Publikovať a zdieľať webové stránky?",
  "PUBLISH": "Publikovať",
  "PUBLISH_CONSENT_MESSAGE": "Rýchlo ukážte zmeny a zdieľajte svoje webové stránky s ostatnými. Phoenix môže zverejniť túto webovú stránku pre vás na {0}. Uverejnené odkazy budú platné po dobu 7 dní. </br>Chcetepublikovať a zdieľať svoje webové stránky?",
  "PUBLISH_SYNC_IN_PROGRESS": "Prebieha synchronizácia pre ukážku...",
  "PUBLISH_PAGE": "Kliknite pre publikovanie a zdieľanie tejto stránky",
  "PUBLISH_VIEW_PAGE": "Kliknite pre zobrazenie publikovanej stránky",
  "MISSING_FIELDS": "Chýbajúce polia",
  "PLEASE_FILL_ALL_REQUIRED": "Vyplňte všetky povinné polia zvýraznené červenou farbou",
  "CODE_EDITOR": "Editor kódu",
  "BUILD_THE_WEB": "Zostavte web",
  "IMPORT_PROJECT": "Importovať projekt",
  "GITHUB_PROJECT": "Projekt Github",
  "NEW_PROJECT_FROM_GITHUB": "Nový projekt od spoločnosti Github",
  "GITHUB_REPO_URL": "URL spoločnosti Github Repo:",
  "CREATE_PROJECT": "Vytvoriť projekt",
  "SETTING_UP_PROJECT": "Nastavenie projektu",
  "LOCATION": "Miesto:",
  "DOWNLOADING": "Sťahovanie...",
  "EXTRACTING_FILES_PROGRESS": "Extrahovanie {0} súborov {1}.",
  "DOWNLOAD_FAILED_MESSAGE": "Uistite sa, že adresa URL na prevzatie je platná. </br>Poznámka: Keďže Phoenix je v alfa, nie sú povolené adresy URL Private Repos a Github väčšie ako 25 MB.",
  "PLEASE_SELECT_A_FOLDER": "Vyberte priečinok...",
  "UNZIP_IN_PROGRESS": "Rozbaliť súbory...",
  "UNZIP_FAILED": "Chyba: Rozbalenie zlyhalo.",
  "CONFIRM_REPLACE_TITLE": "Potvrdiť Nahradiť",
  "KEEP_BOTH": "Udržujte oboje",
  "EXPLORE": "HTML Hry",
  "BLOG": "Blog",
  "PHOENIX_DEFAULT_PROJECT": "Predvolený projekt",
  "PROJECT_NAME": "Názov projektu:",
  "NEW_HTML": "Nový HTML projekt",
  "LICENSE": "Licencia:",
  "CREDITS": "Kredity:",
  "PREVIEW": "Náhľad",
  "BUILD_WEBSITE": "Vytvorte webovú stránku",
  "VIEW_MORE": "Zobraziť viac...",
  "NEW_PROJECT_NOTIFICATION": "Kliknutím na túto ikonu<br/>vytvoríte nový projekt. </br> <a href='#' style='float:right;'>ok</a>",
  "DEFAULT_PROJECT_NOTIFICATION": "Kliknite tu pre otvorenie <br/><b>predvoleného projektu</b> vo Phoenixe. </br> <a href='#' style='float:right;'>ok</a>",
  "DIRECTORY_REPLACE_MESSAGE": "Vybraný priečinok <span class='dialog-filename'>{0}</span> nie je prázdny. Naozaj chcete nahradiť obsah priečinka s projektom?",
  "BUILD_WEBSITE_SECTION": "Vytvorte webovú stránku",
  "LEARN_SECTION": "Naučte sa s príkladmi",
  "WEBPAGE_HOME_PAGE": "Usporiadanie domovskej stránky",
  "WEBPAGE_BLOG": "Stránka blogu",
  "WEBPAGE_DASHBOARD": "HTML Dashboard",
  "WEBPAGE_BOOTSTRAP_EXAMPLES": "Bootstrap Príklady",
  "GUIDED_FILES_SIDEBAR": "Vyberte súbor HTML </br> <a href='#' style='float:right;'>ok</a>",
  "GUIDED_LIVE_PREVIEW": "Vykonajte nejaké zmeny kódu a uložte súbor, aby ste videli náhľad. </br> <a href='#' style='float:right;'>ok</a>",
  "GUIDED_LIVE_PREVIEW_POPOUT": "Kliknutím na toto tlačidlo zobrazíte živý náhľad na novú kartu. </br> <a href='#' style='float:right;'>ok</a>",
  "TEST_TRANSLATE": "použiť na testovanie prekladov",
  "BEAUTIFY_OPTIONS": "Možnosti, ktoré riadia, ako funguje Beautify Code",
  "BEAUTIFY_OPTION_PRINT_WIDTH": "Zadajte dĺžku čiary, na ktorú sa skrášľovač zabalí",
  "BEAUTIFY_OPTION_SEMICOLON": "Pridajte bodkočiarku na koniec každého vyhlásenia",
  "BEAUTIFY_OPTION_SINGLE_QUOTE": "Použite jednoduché úvodzovky namiesto dvojitých úvod",
  "BEAUTIFY_OPTION_QUOTE_PROPS": "Zmena, keď sú citované vlastnosti objektov",
  "BEAUTIFY_OPTION_BRACKET_SAME_LINE": "Vložte > viacriadkového HTML (HTML, JSX, Vue, Angular) prvok na konci posledného riadku namiesto toho, aby bol sám na ďalšom riadku (nevzťahuje sa na samozatváracie prvky)",
  "BEAUTIFY_OPTION_SINGLE_ATTRIBUTE_PER_LINE": "Vynútiť jeden atribút na riadok v HTML, Vue a JSX",
  "BEAUTIFY_OPTION_PROSE_WRAP": "Zabaľte prózu, ak presahuje šírku tlače v súboroch s označením",
  "BEAUTIFY_OPTION_PRINT_TRAILING_COMMAS": "Tlač koncové čiarky všade tam, kde je to možné, vo viacriadkových syntaktických štruktúrach oddelených čiarkami"
});