/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "Predvolený v systéme",
  "PROJECT_BUSY": "Operácie projektu prebiehajú",
  "DUPLICATING": "Duplikuje sa {0}",
  "MOVING": "Presúva sa {0}",
  "COPYING": "Kopíruje sa {0}",
  "DELETING": "Odstraňuje sa {0}",
  "RENAMING": "Premenovanie",
  "GENERIC_ERROR": "(chyba {0})",
  "NOT_FOUND_ERR": "Súbor nenájdený.",
  "NOT_READABLE_ERR": "Súbor sa nedá čítať.",
  "EXCEEDS_MAX_FILE_SIZE": "Súbory väčšie ako {0} MB nie je možné otvoriť v aplikácii {APP_NAME}.",
  "NO_MODIFICATION_ALLOWED_ERR": "Cieľový adresár nemôže byť zmenený.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "Práva vám neumožňujú robiť zmeny.",
  "CONTENTS_MODIFIED_ERR": "Súbor bol upravený mimo aplikácie {APP_NAME}.",
  "UNSUPPORTED_ENCODING_ERR": "Neznámy formát kódovania",
  "ENCODE_FILE_FAILED_ERR": "Aplikácii {APP_NAME} sa nepodarilo zakódovať obsah súboru.",
  "DECODE_FILE_FAILED_ERR": "Aplikácii {APP_NAME} sa nepodarilo dekódovať obsah súboru.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "Aplikácia {APP_NAME} momentálne nepodporuje textové súbory s kódovaním UTF-16.",
  "FILE_EXISTS_ERR": "Súbor alebo adresár už existuje.",
  "FILE": "súbor",
  "FILE_TITLE": "Súbor",
  "DIRECTORY": "adresár",
  "DIRECTORY_TITLE": "Adresár",
  "DIRECTORY_NAMES_LEDE": "Názvy adresárov",
  "FILENAMES_LEDE": "Názvy súborov",
  "FILENAME": "Názov súboru",
  "DIRECTORY_NAME": "Názov adresára",
  "ERROR_LOADING_PROJECT": "Chyba pri otváraní projektu",
  "OPEN_DIALOG_ERROR": "Nastala chyba pri zobrazení dialógu otvorenia súboru. (chyba {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "Nastala chyba pri načítaní adresára <span class='dialog-filename'>{0}</span>. (chyba {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "Nastala chyba pri načítaní obsahu adresára <span class='dialog-filename'>{0}</span>. (chyba {1})",
  "ERROR_OPENING_FILE_TITLE": "Chyba pri otváraní súboru",
  "ERROR_OPENING_FILE": "Nastala chyba pri otváraní súboru <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_OPENING_FILES": "Nastala chyba pri otváraní nasledujúcich súborov:",
  "ERROR_RELOADING_FILE_TITLE": "Chyba pri načítaní zmien z disku",
  "ERROR_RELOADING_FILE": "Nastala chyba pri načítaní súboru <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_SAVING_FILE_TITLE": "Chyba pri ukladaní súboru",
  "ERROR_SAVING_FILE": "Nastala chyba pri ukladaní súboru <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_FILE_TITLE": "Chyba pri premenovaní súboru",
  "ERROR_RENAMING_FILE": "Nastala chyba pri premenovaní súboru <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "Súbor alebo adresár nie je súčasťou aktuálne otvoreného projektu. Bohužiaľ, v tomto bode je možné premenovať iba súbory projektu.",
  "ERROR_MOVING_FILE_TITLE": "Chyba pri presúvaní {0}",
  "ERROR_MOVING_FILE": "Pri pokuse o presun položky {2} <span class='dialog-filename'>{0}</span> sa vyskytla chyba. {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "Nie je možné presunúť súbor/priečinok, pretože nie sú súčasťou aktuálneho projektu.",
  "ERROR_DELETING_FILE_TITLE": "Chyba pri zmazaní súboru",
  "ERROR_DELETING_FILE": "Nastala chyba pri zmazaní súboru <span class='dialog-filename'>{0}</span>. {1}",
  "INVALID_FILENAME_TITLE": "Neplatný {0} názov",
  "CANNOT_PASTE_TITLE": "Nie je možné prilepiť {0}",
  "ERR_TYPE_PASTE_FAILED": "Pri vkladaní <span class='dialog-filename'>{0}</span> do <span class='dialog-filename'>{1}</span> sa vyskytla chyba",
  "CANNOT_DUPLICATE_TITLE": "Nie je možné duplikovať",
  "ERR_TYPE_DUPLICATE_FAILED": "Pri duplikovaní <span class='dialog-filename'>{0}</span> sa vyskytla chyba",
  "INVALID_FILENAME_MESSAGE": "Názvy súboru nesmú obsahovať nasledujúce znaky: {0} alebo používať rezervované systémové slová.",
  "ENTRY_WITH_SAME_NAME_EXISTS": "Súbor alebo adresár s názvom <span class='dialog-filename'>{0}</span> už existuje.",
  "ERROR_CREATING_FILE_TITLE": "Chyba pri vytváraní súboru {0}",
  "ERROR_CREATING_FILE": "Nastala chyba pri vytváraní súboru {0} <span class='dialog-filename'>{1}</span>. {2}",
  "ERROR_MIXED_DRAGDROP": "Nie je možné otvoriť priečinok súčasne s otváraním iných súborov.",
  "ERROR_KEYMAP_TITLE": "Chyba pri čítaní mapy používateľských kľúčov",
  "ERROR_KEYMAP_CORRUPT": "Váš súbor mapy kľúčov nie je platný JSON. Súbor sa otvorí, aby ste mohli opraviť formát.",
  "ERROR_LOADING_KEYMAP": "Váš súbor mapy kľúčov nie je platný textový súbor s kódovaním UTF-8 a nemožno ho načítať",
  "ERROR_RESTRICTED_COMMANDS": "Nemôžete zmeniť priradenie skratiek k týmto príkazom: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "Nemôžete zmeniť priradenie týchto skratiek: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "Znova priraďujete viacero skratiek k týmto príkazom: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "Máte viacero väzieb týchto skratiek: {0}",
  "ERROR_INVALID_SHORTCUTS": "Tieto skratky sú neplatné: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "Priraďujete skratky k neexistujúcim príkazom: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "Chyba čítania predvolieb",
  "ERROR_PREFS_CORRUPT": "Váš súbor predvolieb nie je platný JSON. Súbor sa otvorí, aby ste mohli opraviť formát. Zmeny sa prejavia až po reštartovaní aplikácie {APP_NAME}.",
  "ERROR_PROJ_PREFS_CORRUPT": "Váš súbor predvolieb projektu nie je platný JSON. Súbor sa otvorí, aby ste mohli opraviť formát. Aby sa zmeny prejavili, budete musieť projekt znova načítať.",
  "ERROR_IN_BROWSER_TITLE": "Hopa! {APP_NAME} zatiaľ nejde spustiť v prehliadači.",
  "ERROR_IN_BROWSER": "{APP_NAME} je vytvorený HTML, ale teraz pracuje ako desktopová aplikácia, takže ho môžete využiť na úpravu lokálnych súborov. Prosím, používajte shell aplikácie v <b>github.com/adobe/brackets-shell</b> repozitári pre spustenie {APP_NAME}.",
  "ERROR_MAX_FILES_TITLE": "Chyba pri indexovaní súborov",
  "ERROR_MAX_FILES": "Bol indexovaný maximálny počet súborov. Akcie pre vyhľadávanie súborov podľa indexu nemusia fungovať správne.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "Chyba pri spúšťaní prehliadača",
  "ERROR_CANT_FIND_CHROME": "Prehliadač Google Chrome nebol nájdený. Prosím uistite sa, že je nainštalovaný.",
  "ERROR_LAUNCHING_BROWSER": "Nastala chyba pri spúšťaní prehliadača. (chyba {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "Chyba pri živom náhľade",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "Pripojovanie k prehliadaču",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "V prípade využitia živého náhľadu je treba reštarovať Chrome zo zapnutým vzdialeným ladením.<br /><br />Chceli by ste reštartovať Chrome a zapnúť vzdialené ladenie?",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "Nie je možné načítať stránku zo živým náhľadom",
  "LIVE_DEV_NEED_HTML_MESSAGE": "Otvorte HTML súbor pre spustenie živého náhľadu.",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "Pre spustenie živého náhľadu zo súborom na serveri, musíte špecifikovať URL pre tento projekt.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "Chyba pri spúšťaní HTTP severa pre súbory živého náhľadu. Prosím, skúste to znovu.",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "Pre viac informácií pozrite <a class=\"clickable-link\" data-href=\"{0}\">Riešenie chýb pri pripojení do živého náhľadu</a>.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "Živý náhľad",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "Živý náhľad: Pripájanie…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "Živý náhľad: Inicializácia…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "Odpojenie živého náhľadu",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "Živý náhľad",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "Vyberte položku Súbor na živý náhľad",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "Znovu načítať stránku",
  "LIVE_DEV_CLICK_POPOUT": "Vyskakovať živý náhľad do nového okna",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "Pripnúť na stránke s ukážkou Odopnúť",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "Živá ukážka (neaktualizuje sa kvôli chybe syntaxe)",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "Živý náhľad bol zrušený kvôli tomu, že boli otvorené vývojárske nástroje v prehliadači",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "Živý náhľad bol zrušený kvôli tomu, že stránka bola zatvorená v prehliadači",
  "LIVE_DEV_NAVIGATED_AWAY": "Živý náhľad bol zrušený kvôli tomu, že prehliadač odkazoval na stránku, ktorá nie je súčasťou aktuálneho projektu",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "Živý náhľad bol zrušený pre neznámy dôvod ({0})",
  "SAVE_CLOSE_TITLE": "Uložiť zmeny",
  "SAVE_CLOSE_MESSAGE": "Chcete uložiť zmeny, ktoré ste spravili v dokumente <span class='dialog-filename'>{0}</span>?",
  "SAVE_CLOSE_MULTI_MESSAGE": "Chcete uložiť zmeny v následujúcich súboroch?",
  "EXT_MODIFIED_TITLE": "Externé zmeny",
  "CONFIRM_DELETE_TITLE": "Potvrdte odstránenie",
  "CONFIRM_FILE_DELETE": "Naozaj chcete odstrániť súbor <span class='dialog-filename'>{0}</span> ?",
  "CONFIRM_FOLDER_DELETE": "Ste si istý zmazaním priečinku <span class='dialog-filename'>{0}</span>?",
  "FILE_DELETED_TITLE": "Súbor odstránený",
  "EXT_MODIFIED_WARNING": "Aplikácia <span class='dialog-filename'>{0}</span> bola upravená na disku mimo aplikácie {APP_NAME}.<br /><br /> Chcete súbor uložiť a prepísať tieto zmeny?",
  "EXT_MODIFIED_MESSAGE": "<span class='dialog-filename'>{0}</span> bol upravený na disku, ale tiež ma neuložené zmeny in {APP_NAME}.<br /><br />Ktorú verziu chcete ponechať?",
  "EXT_DELETED_MESSAGE": "<span class='dialog-filename'>{0}</span> bol zmazaný z disku, ale zmeny sa neuložili v {APP_NAME}.<br /><br />Chcete uložiť zmeny?",
  "WINDOW_UNLOAD_WARNING": "Naozaj chcete prejsť na inú adresu URL a opustiť hranaté zátvorky?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "Máte neuložené zmeny! Naozaj chcete prejsť na inú adresu URL a opustiť hranaté zátvorky?",
  "DONE": "hotový",
  "OK": "OK",
  "CANCEL": "Zrušiť",
  "DONT_SAVE": "Neukladať",
  "SAVE": "Uložiť",
  "SAVE_AS": "Uložiť ako…",
  "SAVE_AND_OVERWRITE": "Prepísať",
  "DELETE": "Zmazať",
  "BUTTON_YES": "Áno",
  "BUTTON_NO": "Nie",
  "FIND_MATCH_INDEX": "{0} z {1}",
  "FIND_NO_RESULTS": "Žiadne výsledky",
  "FIND_QUERY_PLACEHOLDER": "Nájsť…",
  "FIND_HISTORY_MAX_COUNT": "Maximálny počet hľadaných položiek v histórii vyhľadávania",
  "REPLACE_PLACEHOLDER": "Nahraď s…",
  "BUTTON_REPLACE_ALL": "Nahradiť všetko",
  "BUTTON_REPLACE_BATCH": "Dávka…",
  "BUTTON_REPLACE_ALL_IN_FILES": "Nahradiť…",
  "BUTTON_REPLACE": "Nahradiť",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "Ďalšia zhoda",
  "BUTTON_PREV_HINT": "Predchádzajúca zhoda",
  "BUTTON_CASESENSITIVE_HINT": "Match Case",
  "BUTTON_REGEXP_HINT": "Regulárny výraz",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "Nahradiť bez vrátenia späť",
  "REPLACE_WITHOUT_UNDO_WARNING": "Keďže je potrebné zmeniť viac ako {0} súborov, {APP_NAME} upraví neotvorené súbory na disku.<br /> Nahradenia v týchto súboroch nebudete môcť vrátiť späť.",
  "BUTTON_REPLACE_WITHOUT_UNDO": "Nahradiť bez vrátenia späť",
  "OPEN_FILE": "Otvoriť súbor",
  "SAVE_FILE_AS": "Uložiť súbor",
  "CHOOSE_FOLDER": "Vybrať adresár",
  "RELEASE_NOTES": "Poznámky o verzii",
  "NO_UPDATE_TITLE": "Všetko je aktuálne!",
  "NO_UPDATE_MESSAGE": "Máte najnovšiu verziu {APP_NAME}.",
  "FIND_REPLACE_TITLE_LABEL": "Nahradiť",
  "FIND_REPLACE_TITLE_WITH": "s",
  "FIND_TITLE_LABEL": "Nájdené",
  "FIND_TITLE_SUMMARY": "&mdash; {0} {1} {2} v {3}",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "v <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_NO_SCOPE": "v projekte",
  "FIND_IN_FILES_ZERO_FILES": "Filter vylučuje všetky súbory {0}",
  "FIND_IN_FILES_FILE": "súbor",
  "FIND_IN_FILES_FILES": "súbory",
  "FIND_IN_FILES_MATCH": "zhoda",
  "FIND_IN_FILES_MATCHES": "zhody",
  "FIND_IN_FILES_MORE_THAN": "Cez ",
  "FIND_IN_FILES_PAGING": "{0}&mdash;{1}",
  "FIND_IN_FILES_FILE_PATH": "Súbor: <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "Kliknutím Ctrl/Cmd všetko rozbalíte/zbalíte",
  "FIND_IN_FILES_INDEXING": "Indexovanie pre Okamžité vyhľadávanie…",
  "FIND_IN_FILES_INDEXING_PROGRESS": "Indexuje sa {0} z {1} súborov pre Okamžité vyhľadávanie…",
  "REPLACE_IN_FILES_ERRORS_TITLE": "Nahradiť chyby",
  "REPLACE_IN_FILES_ERRORS": "Nasledujúce súbory neboli upravené, pretože sa zmenili po vyhľadávaní alebo sa nedali zapísať.",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "Problém pri získavaní informácií o aktualizácii",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "Nastal problém pri získavaní aktuálnych informácií zo servera. Prosím uistite sa, že ste pripojený do internetu a skúste znovu.",
  "NEW_FILE_FILTER": "Nová súprava vylúčení…",
  "CLEAR_FILE_FILTER": "Nevylučovať súbory",
  "NO_FILE_FILTER": "Nie sú vylúčené žiadne súbory",
  "EXCLUDE_FILE_FILTER": "Vylúčiť {0}",
  "EDIT_FILE_FILTER": "Upraviť…",
  "FILE_FILTER_DIALOG": "Upraviť množinu vylúčení",
  "FILE_FILTER_INSTRUCTIONS": "Vylúčte súbory a priečinky zodpovedajúce ľubovoľnému z nasledujúcich reťazcov/podreťazcov alebo <a href='{0}' title=\"{0}\">zástupných znakov</a> . Zadajte každý reťazec na nový riadok.",
  "FILTER_NAME_PLACEHOLDER": "Pomenujte túto skupinu vylúčení (voliteľné)",
  "FILTER_NAME_REMAINING": "Počet zostávajúcich znakov: {0}",
  "FILE_FILTER_CLIPPED_SUFFIX": "a ďalšie ({0}).",
  "FILTER_COUNTING_FILES": "Počítanie súborov…",
  "FILTER_FILE_COUNT": "Povoľuje {0} z {1} súborov {2}",
  "FILTER_FILE_COUNT_ALL": "Povoľuje všetky súbory ({0}) {1}",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "Pre aktuálnu polohu kurzora nie je k dispozícii žiadna rýchla úprava",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "Rýchla úprava CSS: umiestnite kurzor na názov jednej triedy",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "Rýchla úprava CSS: neúplný atribút triedy",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "Rýchla úprava CSS: neúplný atribút id",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "Rýchla úprava CSS: umiestnite kurzor do značky, triedy alebo id",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "Funkcia časovania CSS Rýchla úprava: neplatná syntax",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "JS Quick Edit: umiestnite kurzor do názvu funkcie",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "Pre aktuálnu polohu kurzora nie sú k dispozícii žiadne rýchle dokumenty",
  "PROJECT_LOADING": "Načítavanie…",
  "UNTITLED": "bez názvu",
  "WORKING_FILES": "Otvorené súbory",
  "TOP": "Hore",
  "BOTTOM": "Spodná časť",
  "LEFT": "Vľavo",
  "RIGHT": "Správny",
  "CMD_SPLITVIEW_NONE": "Nie Split",
  "CMD_SPLITVIEW_VERTICAL": "Vertikálne rozdelenie",
  "CMD_SPLITVIEW_HORIZONTAL": "Horizontálne rozdelenie",
  "SPLITVIEW_MENU_TOOLTIP": "Rozdeľte editor vertikálne alebo horizontálne",
  "GEAR_MENU_TOOLTIP": "Konfigurácia pracovnej sady",
  "SPLITVIEW_INFO_TITLE": "Už otvorené",
  "SPLITVIEW_MULTIPANE_WARNING": "Súbor je už otvorený na inom paneli. Aplikácia {APP_NAME} bude čoskoro podporovať otváranie rovnakého súboru na viac ako jednom paneli. Dovtedy sa súbor bude zobrazovať na table, v ktorej je už otvorený.<br /><br /> (Túto správu uvidíte iba raz.)",
  "STATUSBAR_CURSOR_POSITION": "Riadok {0}, Stĺpec {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": " — Vybraný {0} stĺpec",
  "STATUSBAR_SELECTION_CH_PLURAL": " — Vybraných {0} stĺpcov",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " — Vybraný {0} riadok",
  "STATUSBAR_SELECTION_LINE_PLURAL": " — Vybraných {0} riadkov",
  "STATUSBAR_SELECTION_MULTIPLE": " — {0} výberov",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "Kliknite pre zmenu osadenia na medzery",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "Kliknite pre zmenu odsadenia na tabulátory",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "Kliknite pre zmenu počet medzier použitých pre odsadenie",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "Kliknite pre zmenu šírky tabulátora",
  "STATUSBAR_SPACES": "Medzery",
  "STATUSBAR_TAB_SIZE": "Velkosť tabulátora",
  "STATUSBAR_LINE_COUNT_SINGULAR": "Riadok: — {0}",
  "STATUSBAR_LINE_COUNT_PLURAL": "Riadky: — {0}",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "Rozšírenia sú zakázané",
  "STATUSBAR_INSERT": "INS",
  "STATUSBAR_OVERWRITE": "OVR",
  "STATUSBAR_INSOVR_TOOLTIP": "Kliknutím prepínate kurzor medzi režimami Vložiť (INS) a Prepísať (OVR).",
  "STATUSBAR_LANG_TOOLTIP": "Kliknutím zmeníte typ súboru",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. Kliknutím prepnete panel prehľadu.",
  "STATUSBAR_DEFAULT_LANG": "(predvolené)",
  "STATUSBAR_SET_DEFAULT_LANG": "Nastaviť ako predvolené pre súbory .{0}",
  "STATUSBAR_ENCODING_TOOLTIP": "Vyberte kódovanie",
  "ERRORS_PANEL_TITLE_MULTIPLE": "Problémy {0}",
  "SINGLE_ERROR": "1 {0} Problém",
  "MULTIPLE_ERRORS": "Problémy {1} {0}",
  "NO_ERRORS": "Nenašli sa žiadne problémy ({0}) – dobrá práca!",
  "NO_ERRORS_MULTIPLE_PROVIDER": "Nenašli sa žiadne problémy – dobrá práca!",
  "LINT_DISABLED": "Lining je vypnutý",
  "NO_LINT_AVAILABLE": "Pre {0} nie je k dispozícii žiadny linter",
  "NOTHING_TO_LINT": "Nič, čo by sa prášilo",
  "LINTER_TIMED_OUT": "{0} vypršal po čakaní {1} ms",
  "LINTER_FAILED": "{0} ukončené s chybou: {1}",
  "FILE_MENU": "Súbor",
  "CMD_FILE_NEW_UNTITLED": "Nový",
  "CMD_FILE_NEW": "Nový súbor",
  "CMD_FILE_DUPLICATE": "Duplikovať",
  "CMD_FILE_CUT": "Vystrihnúť",
  "CMD_FILE_COPY": "Kopírovať",
  "CMD_FILE_COPY_PATH": "Kopírovať cestu",
  "CMD_FILE_PASTE": "Vložiť",
  "CMD_PROJECT_NEW": "Nový projekt",
  "CMD_FILE_NEW_FOLDER": "Nový adresár",
  "CMD_FILE_OPEN": "Otvoriť…",
  "CMD_RECENT_FILES_OPEN": "Posledné súbory…",
  "CMD_ADD_TO_WORKING_SET": "Pridať do pracovnej sady",
  "CMD_OPEN_DROPPED_FILES": "Otvorte zrušené súbory",
  "CMD_OPEN_FOLDER": "Otvoriť adresár…",
  "CMD_FILE_CLOSE": "Zatvoriť",
  "CMD_FILE_CLOSE_ALL": "Zatvoriť všetko",
  "CMD_FILE_CLOSE_LIST": "Zatvoriť zoznam",
  "CMD_FILE_CLOSE_OTHERS": "Zavrieť Ostatné",
  "CMD_FILE_CLOSE_ABOVE": "Zavrieť ostatné vyššie",
  "CMD_FILE_CLOSE_BELOW": "Zavrieť Ostatné nižšie",
  "CMD_FILE_SAVE": "Uložiť súbor",
  "CMD_FILE_SAVE_ALL": "Uložiť všetko",
  "CMD_FILE_SAVE_AS": "Uložiť ako…",
  "CMD_LIVE_FILE_PREVIEW": "Živý náhľad",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "Povoliť experimentálny živý náhľad",
  "CMD_RELOAD_LIVE_PREVIEW": "Vynútiť opätovné načítanie živého náhľadu",
  "CMD_PROJECT_SETTINGS": "Nastavenia projektu…",
  "CMD_FILE_RENAME": "Premenovať",
  "CMD_FILE_DELETE": "Zmazať",
  "CMD_INSTALL_EXTENSION": "Inštalovať rozšírenia…",
  "CMD_EXTENSION_MANAGER": "Správca rozšírení…",
  "CMD_FILE_REFRESH": "Obnoviť strom súborov",
  "CMD_FILE_SHOW_FOLDERS_FIRST": "Najprv zoraďte priečinky",
  "CMD_QUIT": "Koniec",
  "CMD_EXIT": "Koniec",
  "EDIT_MENU": "Upraviť",
  "CMD_UNDO": "Späť",
  "CMD_REDO": "Znovu",
  "CMD_CUT": "Vystrihnúť",
  "CMD_COPY": "Kopírovať",
  "CMD_PASTE": "Vložiť",
  "CMD_SELECT_ALL": "Vybrať všetko",
  "CMD_SELECT_LINE": "Vybrať riadok",
  "CMD_SPLIT_SEL_INTO_LINES": "Rozdeľte výber na riadky",
  "CMD_ADD_CUR_TO_NEXT_LINE": "Pridajte kurzor na ďalší riadok",
  "CMD_ADD_CUR_TO_PREV_LINE": "Pridať kurzor na predchádzajúci riadok",
  "CMD_INDENT": "Odsadiť",
  "CMD_UNINDENT": "Vrátiť odsadenie",
  "CMD_DUPLICATE": "Duplikovať",
  "CMD_DELETE_LINES": "Zmazať riadok",
  "CMD_COMMENT": "Riadkový komentár",
  "CMD_BLOCK_COMMENT": "Blokový komentár",
  "CMD_LINE_UP": "Posunúť riadok hore",
  "CMD_LINE_DOWN": "Posunúť riadok dole",
  "CMD_OPEN_LINE_ABOVE": "O riadok vyššie",
  "CMD_OPEN_LINE_BELOW": "O riadok nižšie",
  "CMD_TOGGLE_CLOSE_BRACKETS": "Uzatvárať zátvorky",
  "CMD_SHOW_CODE_HINTS": "Zobraziť tipy",
  "CMD_BEAUTIFY_CODE": "Skrášliť kód",
  "CMD_BEAUTIFY_CODE_ON_SAVE": "Skrášliť kód po uložení",
  "FIND_MENU": "Vyhľadať",
  "CMD_FIND": "Vyhľadať",
  "CMD_FIND_NEXT": "Vyhľadať nasledujúci",
  "CMD_FIND_PREVIOUS": "Vyhľadať predchádzajúci",
  "CMD_FIND_ALL_AND_SELECT": "Nájsť všetko a vybrať",
  "CMD_ADD_NEXT_MATCH": "Pridať ďalšiu zhodu do výberu",
  "CMD_SKIP_CURRENT_MATCH": "Preskočiť a pridať ďalšiu zhodu",
  "CMD_FIND_IN_FILES": "Vyhľadať v súboroch",
  "CMD_FIND_IN_SUBTREE": "Vyhľadať v…",
  "CMD_REPLACE": "Nahradiť",
  "CMD_REPLACE_IN_FILES": "Nahradiť v súboroch",
  "CMD_REPLACE_IN_SUBTREE": "Nahradiť v…",
  "VIEW_MENU": "Zobraziť",
  "CMD_HIDE_SIDEBAR": "Skryť bočný panel",
  "CMD_SHOW_SIDEBAR": "Zobraziť bočný panel",
  "CMD_TOGGLE_SIDEBAR": "Prepnúť bočný panel",
  "CMD_TOGGLE_PANELS": "Prepnúť panely",
  "CMD_TOGGLE_PURE_CODE": "Žiadne rozptýlenie",
  "CMD_INCREASE_FONT_SIZE": "Zväčšiť veľkosť písma",
  "CMD_DECREASE_FONT_SIZE": "Zmenšiť veľkosť písma",
  "CMD_RESTORE_FONT_SIZE": "Obnoviť veľkosť písma",
  "CMD_SCROLL_LINE_UP": "Posunúť o riadok hore",
  "CMD_SCROLL_LINE_DOWN": "Posunúť o riadok dole",
  "CMD_TOGGLE_LINE_NUMBERS": "Čísla riadkov",
  "CMD_TOGGLE_ACTIVE_LINE": "Zvýrazniť aktívny riadok",
  "CMD_TOGGLE_WORD_WRAP": "Zalomenie riadkov",
  "CMD_LIVE_HIGHLIGHT": "Zvýraznenie živého náhľadu",
  "CMD_VIEW_TOGGLE_INSPECTION": "Súbory Lint na Uložiť",
  "CMD_WORKINGSET_SORT_BY_ADDED": "Usporiadať podľa dátumu",
  "CMD_WORKINGSET_SORT_BY_NAME": "Usporiadať podľa mena",
  "CMD_WORKINGSET_SORT_BY_TYPE": "Usporiadať podľa typu",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "Automatické usporiadanie",
  "CMD_THEMES": "Témy…",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "Automaticky zavrieť vyhľadávanie",
  "NAVIGATE_MENU": "Navigácia",
  "CMD_QUICK_OPEN": "Rýchle otvorenie",
  "CMD_GOTO_LINE": "Prejsť na riadok",
  "CMD_GOTO_DEFINITION": "Prejsť na definíciu",
  "CMD_GOTO_DEFINITION_PROJECT": "Definícia rýchleho hľadania v projekte",
  "CMD_GOTO_FIRST_PROBLEM": "Prejdite na Prvý problém",
  "CMD_TOGGLE_QUICK_EDIT": "Rýchla úprava",
  "CMD_TOGGLE_QUICK_DOCS": "Rýchla dokumentácia",
  "CMD_QUICK_EDIT_PREV_MATCH": "Predchádzajúca zhoda",
  "CMD_QUICK_EDIT_NEXT_MATCH": "Ďalšia zhoda",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "Nové pravidlo",
  "CMD_NEXT_DOC": "Následujúci dokument",
  "CMD_PREV_DOC": "Predchádzajúci dokument",
  "CMD_NAVIGATE_BACKWARD": "Navigovať dozadu",
  "CMD_NAVIGATE_FORWARD": "Navigovať dopredu",
  "CMD_NEXT_DOC_LIST_ORDER": "Ďalší dokument v zozname",
  "CMD_PREV_DOC_LIST_ORDER": "Predchádzajúci dokument v zozname",
  "CMD_SHOW_IN_TREE": "Zobraziť stromovú štruktúru",
  "CMD_SHOW_IN_EXPLORER": "Ukázať v prehliadači",
  "CMD_SHOW_IN_FINDER": "Zobraziť vo Finderi",
  "CMD_SHOW_IN_OS": "Zobraziť v OS",
  "CMD_SWITCH_PANE_FOCUS": "Prepnúť zameranie tably",
  "CMD_OPEN_VFS": "Otvorte virtuálny súborový systém",
  "CMD_OPEN_VIRTUAL_SERVER": "Otvorte virtuálny server",
  "HELP_MENU": "Nápoveda",
  "CMD_CHECK_FOR_UPDATE": "Skontrolovať aktualizácie",
  "CMD_HOW_TO_USE_BRACKETS": "Ako používať {APP_NAME}",
  "CMD_SUPPORT": "Podpora aplikácie {APP_NAME}",
  "CMD_SUGGEST": "Navrhnite funkciu",
  "CMD_RELEASE_NOTES": "Poznámky o verzii",
  "CMD_GET_INVOLVED": "Zapojte sa",
  "CMD_SHOW_EXTENSIONS_FOLDER": "Zobraziť priečinok s doplnkami",
  "CMD_HEALTH_DATA_STATISTICS": "Správa o zdraví",
  "CMD_HOMEPAGE": "Domovská stránka aplikácie {APP_NAME}",
  "CMD_TWITTER": "{TWITTER_NAME} na Twitteri",
  "CMD_ABOUT": "O {APP_TITLE}",
  "CMD_OPEN_PREFERENCES": "Otvorte súbor predvolieb",
  "CMD_OPEN_KEYMAP": "Otvorte mapu používateľských kľúčov",
  "EXPERIMENTAL_BUILD": "experimentálna verzia",
  "RELEASE_BUILD": "stavať",
  "DEVELOPMENT_BUILD": "vývojová verzia",
  "PRERELEASE_BUILD": "predbežná verzia",
  "RELOAD_FROM_DISK": "Načítať z disku",
  "KEEP_CHANGES_IN_EDITOR": "Ponechať zmeny v editore",
  "CLOSE_DONT_SAVE": "Zatvoriť (neukladať)",
  "RELAUNCH_CHROME": "Reštartovať Chrome",
  "ABOUT": "O aplikácii",
  "CLOSE": "Zatvoriť",
  "ABOUT_TEXT_LINE1": "Vydanie {VERSION_MAJOR}.{VERSION_MINOR} {BUILD_TYPE} {VERSION}",
  "ABOUT_TEXT_BUILD_TIMESTAMP": "časová pečiatka zostavy:",
  "ABOUT_TEXT_LINE3": "Knižnice tretích strán, ktoré používame – <a href='https://github.com/phcode-dev/phoenix/tree/main/src/thirdparty/licences'>Licencie a Atribúcie</a> .",
  "ABOUT_TEXT_LINE4": "Dokumentácia a zdroj na <a href='https://github.com/phcode-dev/phoenix/'>https://github.com/phcode-dev/phoenix/</a>",
  "ABOUT_TEXT_LINE5": "Vyrobené pomocou ❤ a JavaScript od:",
  "ABOUT_TEXT_LINE6": "Veľa ľudí (ale práve teraz máme problémy s načítaním týchto údajov).",
  "ABOUT_TEXT_MDN_DOCS": "MDN Docs a the MDN grafické logo sú licencované pod Creative Commons Attribution license, <a class=\"clickable-link\" data-href=\"{MDN_DOCS_LICENSE}\">CC-BY-SA 2.5 Unported</a>.",
  "UPDATE_NOTIFICATION_TOOLTIP": "Je dostupná nová verzia {APP_NAME}! Kliknite sem pre viac detailov.",
  "UPDATE_AVAILABLE_TITLE": "Dostupná aktualizácia",
  "UPDATE_MESSAGE": "Hey, je dostupná nová verzia {APP_NAME}. Zoznam niektorých nových vylepšení:",
  "GET_IT_NOW": "Stiahnuť!",
  "PROJECT_SETTINGS_TITLE": "Nastavenia projketu pre: {0}",
  "PROJECT_SETTING_BASE_URL": "Živý náhľad URL",
  "PROJECT_SETTING_BASE_URL_HINT": "Pre použitie lokálneho servera, vložte URL v tvare http://localhost:8000/",
  "BASEURL_ERROR_INVALID_PROTOCOL": "Protokol {0} nie je podporovaný Živým náhľadom&mdash;prosím použite http: alebo https: .",
  "BASEURL_ERROR_SEARCH_DISALLOWED": "URL adresa nemôže obsahovať výrazy pre hľadanie ako \"{0}\".",
  "BASEURL_ERROR_HASH_DISALLOWED": "URL adresa nemôže obsahovať znaky ako \"{0}\".",
  "BASEURL_ERROR_INVALID_CHAR": "Zvláštné znaky ako '{0}' musia byť %-enkódované.",
  "BASEURL_ERROR_UNKNOWN_ERROR": "Neznáma chyba pri spracovávaní URL",
  "EMPTY_VIEW_HEADER": "<em>Otvorte súbor, kým je tento panel aktívny</em>",
  "FLIPVIEW_BTN_TOOLTIP": "Otočte toto zobrazenie na tablu {0}",
  "CURRENT_THEME": "Aktuálna téma",
  "USE_THEME_SCROLLBARS": "Použite posúvače motívov",
  "FONT_SIZE": "Veľkosť písma",
  "FONT_FAMILY": "Rodina písiem",
  "THEMES_SETTINGS": "Nastavenia motívov",
  "BUTTON_NEW_RULE": "Nové pravidlo",
  "INSTALL": "Inštalovať",
  "UPDATE": "Aktualizovať",
  "REMOVE": "Odstrániť",
  "DISABLE": "Zakázať",
  "ENABLE": "Povoliť",
  "OVERWRITE": "Prepísať",
  "CANT_REMOVE_DEV": "Doplnky v \"dev\" priečinku musia byť manuálne odstránené.",
  "CANT_UPDATE": "Aktualizácia nie je kompatibilná s touto verziou {APP_NAME}.",
  "CANT_UPDATE_DEV": "Rozšírenia v priečinku „dev“ nie je možné aktualizovať automaticky.",
  "INSTALL_EXTENSION_TITLE": "Inštalovať doplnok",
  "UPDATE_EXTENSION_TITLE": "Aktualizovať doplnok",
  "INSTALL_EXTENSION_LABEL": "URL adresa doplnku",
  "INSTALL_EXTENSION_HINT": "URL adresa zip súboru doplnku alebo Git repozitár",
  "INSTALLING_FROM": "Inštalovanie doplnku z {0}…",
  "INSTALL_SUCCEEDED": "Inštalácia bola úspešná!",
  "INSTALL_FAILED": "Inštalácia sa nepodarila.",
  "CANCELING_INSTALL": "Rušenie…",
  "CANCELING_HUNG": "Zrušenie inštalácie trvá dlho. Mohlo prísť k internej chybe.",
  "INSTALL_CANCELED": "Inštalácia zrušená.",
  "VIEW_COMPLETE_DESCRIPTION": "Zobraziť úplný popis",
  "VIEW_TRUNCATED_DESCRIPTION": "Zobraziť skrátený popis",
  "SORT_EXTENSION_METHOD": "Zoraďte rozšírenia pomocou downloadCount alebo publishingDate",
  "INVALID_ZIP_FILE": "Stiahnutý obsah nie je platný zip súbor.",
  "MISSING_PACKAGE_JSON": "Balík neobsahuje súbor package.json.",
  "INVALID_PACKAGE_JSON": "Súbor package.json nie je platný (chyba bola: {0}).",
  "MISSING_PACKAGE_NAME": "Súbor package.json nešpecifikuje názov balíku.",
  "BAD_PACKAGE_NAME": "{0} je neplatný názov balíka.",
  "MISSING_PACKAGE_VERSION": "Súbor package.json nešpecifikuje verziu súboru.",
  "INVALID_VERSION_NUMBER": "Balík verzie ({0}) je neplatný.",
  "INVALID_BRACKETS_VERSION": "Reťazec kompatibility ({0}) pre {APP_NAME} je neplatný.",
  "DISALLOWED_WORDS": "Slová ({1}) nie sú povolené v {0} poli.",
  "NPM_INSTALL_FAILED": "Inštalačný príkaz npm zlyhal: {0}",
  "API_NOT_COMPATIBLE": "Balík nie je kompatibilný s verziou {APP_NAME}. Nájdete ho v zložke vypnuté doplnky.",
  "MISSING_MAIN": "Balík nemá žiadny súbor main.js.",
  "EXTENSION_ALREADY_INSTALLED": "Inštalácia tohto balíku prepíše nainštalovaný doplnok. Prepísať starý doplnok?",
  "EXTENSION_SAME_VERSION": "Tento balík je rovnakej verzie ako aktuálne nainštalovaný. Prepísať existujúci doplnok?",
  "EXTENSION_OLDER_VERSION": "Tento balík je verzie {0}, ktorá je staršia ako aktuálne nainštalovaná ({1}). Prepísať existujúci doplnok?",
  "DOWNLOAD_ID_IN_USE": "Interná chyba: ID sťahovania sa už používa.",
  "NO_SERVER_RESPONSE": "Nie je možné pripojiť sa k serveru.",
  "BAD_HTTP_STATUS": "Súbor nebol nájdený na serveri (HTTP {0}).",
  "CANNOT_WRITE_TEMP": "Nie je možné uložiť do dočasného súboru.",
  "ERROR_LOADING": "Pri spúšťaní doplnku prišlo k chybe.",
  "MALFORMED_URL": "URL adresa je chybná. Prosím skontrolujte ju, či je zadaná správne.",
  "UNSUPPORTED_PROTOCOL": "URL adresa musí byť http alebo https.",
  "UNKNOWN_ERROR": "Neznáma chyba",
  "EXTENSION_MANAGER_TITLE": "Správca doplnkov",
  "EXTENSION_MANAGER_ERROR_LOAD": "Nie je možné získať prístup k registrom doplnkov. Prosím, skúste to znovu neskôr.",
  "INSTALL_EXTENSION_DRAG": "Potiahnite sem .zip alebo",
  "INSTALL_EXTENSION_DROP": "Ak chcete nainštalovať, presuňte súbor .zip",
  "INSTALL_EXTENSION_DROP_ERROR": "Inštalácia/aktualizácia bola prerušená z dôvodu nasledujúcich chýb:",
  "INSTALL_FROM_URL": "Inštalovať z URL…",
  "INSTALL_EXTENSION_VALIDATING": "Overuje sa…",
  "EXTENSION_AUTHOR": "Autor",
  "EXTENSION_DATE": "Dátum",
  "EXTENSION_INCOMPATIBLE_NEWER": "Tento doplnok vyžaduje novšiu verziu {APP_NAME}.",
  "EXTENSION_INCOMPATIBLE_OLDER": "Tento doplnok momentálne funguje iba zo staršími verziami {APP_NAME}.",
  "EXTENSION_LATEST_INCOMPATIBLE_NEWER": "Verzia {0} tohto rozšírenia vyžaduje novšiu verziu aplikácie {APP_NAME}. Môžete si však nainštalovať staršiu verziu {1}.",
  "EXTENSION_LATEST_INCOMPATIBLE_OLDER": "Verzia {0} tohto rozšírenia funguje iba so staršími verziami aplikácie {APP_NAME}. Môžete si však nainštalovať staršiu verziu {1}.",
  "EXTENSION_NO_DESCRIPTION": "Bez popisu",
  "EXTENSION_MORE_INFO": "Viac informácií...",
  "EXTENSION_ERROR": "Chyba doplnku",
  "EXTENSION_KEYWORDS": "Kľúčové slová",
  "EXTENSION_TRANSLATED_USER_LANG": "Preložené do {0} jazykov vrátane vášho",
  "EXTENSION_TRANSLATED_GENERAL": "Preložené do {0} jazykov",
  "EXTENSION_TRANSLATED_LANGS": "Toto rozšírenie bolo preložené do týchto jazykov: {0}",
  "EXTENSION_INSTALLED": "Nainštalované",
  "EXTENSION_UPDATE_INSTALLED": "Aktualizácia tohto doplnku bola stiahnutá a bude nainštalovaná keď ukončíte {APP_NAME}.",
  "EXTENSION_SEARCH_PLACEHOLDER": "Hľadať",
  "EXTENSION_MORE_INFO_LINK": "Viac",
  "BROWSE_EXTENSIONS": "Prechádzať doplnky",
  "EXTENSION_MANAGER_REMOVE": "Odstrániť doplnok",
  "EXTENSION_MANAGER_REMOVE_ERROR": "Nie je možné odstrániť jeden alebo viac doplnkov: {0}. {APP_NAME} bude ukončená.",
  "EXTENSION_MANAGER_UPDATE": "Aktualizovať doplnok",
  "EXTENSION_MANAGER_UPDATE_ERROR": "Nie je možné aktualizovať jeden alebo viac doplnkov: {0}. {APP_NAME} bude ukončená.",
  "EXTENSION_MANAGER_DISABLE": "Zakázať rozšírenie",
  "EXTENSION_MANAGER_DISABLE_ERROR": "Nie je možné zakázať jedno alebo viac rozšírení: {0}. Aplikácia {APP_NAME} sa stále znova načíta.",
  "MARKED_FOR_REMOVAL": "Označené pre odstránenie",
  "UNDO_REMOVE": "Späť",
  "MARKED_FOR_UPDATE": "Označené pre aktualizáciu",
  "UNDO_UPDATE": "Späť",
  "MARKED_FOR_DISABLING": "Označené na deaktiváciu",
  "UNDO_DISABLE": "Späť",
  "CHANGE_AND_RELOAD_TITLE": "Zmeniť rozšírenia",
  "CHANGE_AND_RELOAD_MESSAGE": "Ak chcete aktualizovať, odstrániť alebo zakázať označené rozšírenia, aplikáciu {APP_NAME} bude potrebné znova načítať. Zobrazí sa výzva na uloženie neuložených zmien.",
  "REMOVE_AND_RELOAD": "Odstráňte rozšírenia a znova načítajte",
  "CHANGE_AND_RELOAD": "Zmeňte rozšírenia a znova načítajte",
  "UPDATE_AND_RELOAD": "Aktualizujte rozšírenia a znova načítajte",
  "DISABLE_AND_RELOAD": "Zakázať rozšírenia a znova načítať",
  "PROCESSING_EXTENSIONS": "Spracúvajú sa zmeny rozšírenia…",
  "EXTENSION_NOT_INSTALLED": "Nie je možné odstrániť doplnok {0}, pretože nebol nainštalovaný",
  "NO_EXTENSIONS": "Nie sú nainštalované žiadne doplnky.<br>Click on the Available tab above to get started.",
  "NO_EXTENSION_MATCHES": "Nenašiel sa žiadny doplnok.",
  "REGISTRY_SANITY_CHECK_WARNING": "Buďte opatrní pri inštalácií doplnkov z neznámeho zdroja.",
  "EXTENSIONS_INSTALLED_TITLE": "Nainštalované",
  "EXTENSIONS_DEFAULT_TITLE": "Predvolené",
  "EXTENSIONS_AVAILABLE_TITLE": "Dostupné",
  "EXTENSIONS_THEMES_TITLE": "Témy",
  "EXTENSIONS_UPDATES_TITLE": "Aktualizácie",
  "EXTENSIONS_LAST_UPDATED": "Naposledy aktualizovaný",
  "EXTENSIONS_DOWNLOADS": "K stiahnutiu",
  "INLINE_EDITOR_NO_MATCHES": "Nie sú k dispozícii žiadne zhody.",
  "INLINE_EDITOR_HIDDEN_MATCHES": "Všetky zápasy sú zrútené. Ak chcete zobraziť zhody, rozbaľte súbory uvedené vpravo.",
  "CSS_QUICK_EDIT_NO_MATCHES": "Vášmu výberu nezodpovedajú žiadne existujúce pravidlá CSS.<br> Kliknutím na „Nové pravidlo“ vytvoríte pravidlo.",
  "CSS_QUICK_EDIT_NO_STYLESHEETS": "Vo vašom projekte nie sú žiadne šablóny so štýlmi.<br> Vytvorte si jedno na pridanie pravidiel CSS.",
  "IMAGE_VIEWER_LARGEST_ICON": "najväčší",
  "UNIT_PIXELS": "pixely",
  "DEBUG_MENU": "Ladenie",
  "ERRORS": "Chyby",
  "CMD_SHOW_DEV_TOOLS": "Zobraziť vývojárske nástroje",
  "CMD_REFRESH_WINDOW": "Reštartovať {APP_NAME}",
  "CMD_RELOAD_WITHOUT_USER_EXTS": "Znova načítať bez rozšírení",
  "CMD_NEW_BRACKETS_WINDOW": "Nové {APP_NAME} okno",
  "CMD_LAUNCH_SCRIPT_MAC": "Nainštalujte skratku príkazového riadka",
  "CMD_SWITCH_LANGUAGE": "Zmeniť jazyk",
  "CMD_RUN_UNIT_TESTS": "Spustiť testy",
  "CMD_SHOW_PERF_DATA": "Zobraziť údaje o výkone",
  "CMD_ENABLE_LOGGING": "Povoliť podrobné denníky",
  "CMD_ENABLE_LIVE_PREVIEW_LOGS": "Záznamy živého náhľadu",
  "CMD_OPEN_BRACKETS_SOURCE": "Otvorte zdroj aplikácie {APP_NAME}",
  "CREATING_LAUNCH_SCRIPT_TITLE": "Skratka príkazového riadka aplikácie {APP_NAME}",
  "ERROR_CREATING_LAUNCH_SCRIPT": "Pri inštalácii skratky príkazového riadka sa vyskytla chyba. Skúste <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting'>tieto návrhy na riešenie problémov</a> .<br/><br/> Dôvod: {0}",
  "ERROR_CLTOOLS_RMFAILED": "Nie je možné odstrániť existujúci symbolický odkaz <code>/usr/local/bin/brackets</code> .",
  "ERROR_CLTOOLS_MKDIRFAILED": "Nie je možné vytvoriť adresár <code>/usr/local/bin</code> .",
  "ERROR_CLTOOLS_LNFAILED": "Nie je možné vytvoriť symbolický odkaz <code>/usr/local/bin/brackets</code> .",
  "ERROR_CLTOOLS_SERVFAILED": "Vnútorná chyba.",
  "ERROR_CLTOOLS_NOTSUPPORTED": "Skratka príkazového riadka nie je v tomto OS podporovaná.",
  "LAUNCH_SCRIPT_CREATE_SUCCESS": "Úspech! Teraz môžete jednoducho spustiť aplikáciu {APP_NAME} z príkazového riadka: <code>brackets myFile.txt</code> na otvorenie súboru alebo <code>brackets myFolder</code> na prepínanie projektov.<br/><br/> <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments'>Získajte viac informácií</a> o používaní aplikácie {APP_NAME} z príkazového riadka.",
  "LANGUAGE_TITLE": "Zmeniť jazyk",
  "LANGUAGE_MESSAGE": "Jazyk:",
  "LANGUAGE_SUBMIT": "Reštartovať {APP_NAME}",
  "LANGUAGE_CANCEL": "Zrušiť",
  "LANGUAGE_SYSTEM_DEFAULT": "Predvolený v systéme",
  "HEALTH_DATA_NOTIFICATION": "Predvoľby zdravotných správ",
  "HEALTH_FIRST_POPUP_TITLE": "Správa o zdravotnom stave aplikácie {APP_NAME}",
  "HEALTH_DATA_DO_TRACK": "Zdieľať pseudonymné informácie o tom, ako používam {APP_NAME}",
  "HEALTH_DATA_NOTIFICATION_MESSAGE": "S cieľom zlepšiť aplikáciu {APP_NAME} pravidelne odosielame obmedzené <strong>pseudonymné</strong> štatistiky do core.ai o tom, ako používate {APP_NAME}. Tieto informácie pomáhajú určiť priority funkcií, nájsť chyby a odhaliť problémy s použiteľnosťou a zároveň chrániť vaše súkromie.<br><br> Svoje údaje môžete zobraziť alebo sa rozhodnúť údaje nezdieľať výberom položky <strong>Pomocník &gt; Správa o zdraví</strong> .<br><br>",
  "HEALTH_DATA_PREVIEW": "Správa o zdravotnom stave aplikácie {APP_NAME}",
  "HEALTH_DATA_PREVIEW_INTRO": "<p>S cieľom zlepšiť aplikáciu {APP_NAME} pravidelne odosielame obmedzené <strong>pseudonymné</strong> štatistiky do core.ai o tom, ako používate {APP_NAME}. Tieto informácie pomáhajú určiť priority funkcií, nájsť chyby a odhaliť problémy s použiteľnosťou.</p><p> Nižšie je uvedený náhľad údajov, ktoré sa odošlú vo vašej ďalšej správe o zdravotnom stave, <em>ak</em> je povolená.</p>",
  "INLINE_TIMING_EDITOR_TIME": "Čas",
  "INLINE_TIMING_EDITOR_PROGRESSION": "Progresia",
  "BEZIER_EDITOR_INFO": "<kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd> Presunúť vybraný bod<br> <kbd class='text'>Shift</kbd> Posun o desať jednotiek<br> <kbd class='text'>Tab</kbd> Prepínacie body",
  "STEPS_EDITOR_INFO": "<kbd>↑</kbd> <kbd>↓</kbd> Zvýšte alebo znížte kroky<br> <kbd>←</kbd> <kbd>→</kbd> &#39;Začiatok&#39; alebo &#39;Koniec&#39;",
  "INLINE_TIMING_EDITOR_INVALID": "Stará hodnota <code>{0}</code> nie je platná, takže zobrazená funkcia bola zmenená na <code>{1}</code> . Dokument bude aktualizovaný pri prvej úprave.",
  "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP": "Aktuálna farba",
  "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP": "Pôvodná farba",
  "COLOR_EDITOR_RGBA_BUTTON_TIP": "RGBa formát",
  "COLOR_EDITOR_HEX_BUTTON_TIP": "Hex formát",
  "COLOR_EDITOR_HSLA_BUTTON_TIP": "HSLa formát",
  "COLOR_EDITOR_0X_BUTTON_TIP": "Hexadecimálny (0x) formát",
  "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR": "{0} (Použité {1} krát)",
  "COLOR_EDITOR_USED_COLOR_TIP_PLURAL": "{0} (Použité {1} krát)",
  "CMD_JUMPTO_DEFINITION": "Prejsť na definíciu",
  "CMD_SHOW_PARAMETER_HINT": "Ukázať pomôcku parametra",
  "NO_ARGUMENTS": "<žiadne parametre>",
  "DETECTED_EXCLUSION_TITLE": "Problém s odvodením súboru JavaScript",
  "DETECTED_EXCLUSION_INFO": "Aplikácia {APP_NAME} mala problém so spracovaním <span class='dialog-filename'>{0}</span> .<br><br> Tento súbor sa už nebude spracovávať pre tipy na kód, skok na definíciu alebo rýchlu úpravu. Ak chcete tento súbor znova povoliť, otvorte súbor <code>.brackets.json</code> vo svojom projekte a upravte <code>jscodehints.detectedExclusions</code> .<br><br> Pravdepodobne ide o chybu aplikácie {APP_NAME}. Ak môžete poskytnúť kópiu tohto súboru, nahláste <a href='https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue'>chybu</a> s odkazom na tu uvedený súbor.",
  "CMD_REFACTOR": "Refaktor",
  "CMD_EXTRACTTO_VARIABLE": "Extrahovať do premennej",
  "CMD_EXTRACTTO_FUNCTION": "Extrahovať do funkcie",
  "ERROR_TERN_FAILED": "Nie je možné získať údaje zo služby Tern",
  "ERROR_EXTRACTTO_VARIABLE_NOT_VALID": "Výber netvorí výraz",
  "ERROR_EXTRACTTO_FUNCTION_NOT_VALID": "Vybraný blok by mal predstavovať množinu príkazov alebo výraz",
  "ERROR_EXTRACTTO_VARIABLE_MULTICURSORS": "Výpis do premennej nefunguje v multikurzoroch",
  "ERROR_EXTRACTTO_FUNCTION_MULTICURSORS": "Výpis do funkcie nefunguje v multikurzoroch",
  "EXTRACTTO_FUNCTION_SELECT_SCOPE": "Vyberte cieľový rozsah",
  "EXTRACTTO_VARIABLE_SELECT_EXPRESSION": "Vyberte výraz",
  "CMD_REFACTORING_RENAME": "Premenovať",
  "CMD_REFACTORING_TRY_CATCH": "Zabaliť do Try Catch",
  "CMD_REFACTORING_CONDITION": "Zabaliť v stave",
  "CMD_REFACTORING_GETTERS_SETTERS": "Vytvorte Getters/Setters",
  "CMD_REFACTORING_ARROW_FUNCTION": "Konvertovať na funkciu šípok",
  "DESCRIPTION_CODE_REFACTORING": "Povoliť/zakázať refaktorovanie kódu JavaScript",
  "ERROR_TRY_CATCH": "Vyberte platný kód, ktorý chcete zabaliť do bloku Try-catch",
  "ERROR_WRAP_IN_CONDITION": "Vyberte platný kód na zabalenie do bloku podmienky",
  "ERROR_ARROW_FUNCTION": "Umiestnite kurzor do funkčného výrazu",
  "ERROR_GETTERS_SETTERS": "Umiestnite kurzor na člen výrazu objektu",
  "ERROR_RENAME_MULTICURSOR": "Nie je možné premenovať pri použití viacerých kurzorov",
  "ERROR_RENAME_QUICKEDIT": "Tento identifikátor nie je možné premenovať, pretože sa naň odkazuje inde mimo tejto funkcie",
  "ERROR_RENAME_GENERAL": "Vybratý text nie je možné premenovať",
  "JSHINT_NAME": "JSHint",
  "CMD_ENABLE_QUICK_VIEW": "Rýchly náhľad",
  "CMD_ENABLE_SELECTION_VIEW": "Zobrazenie výberu",
  "CMD_TOGGLE_RECENT_PROJECTS": "Nedávne projekty",
  "DOCS_MORE_LINK": "Viac",
  "COLLAPSE_ALL": "Zbaliť všetko",
  "EXPAND_ALL": "Rozbaliť všetko",
  "COLLAPSE_CURRENT": "Zbaliť prúd",
  "EXPAND_CURRENT": "Rozbaľte Aktuálny",
  "RECENT_FILES_DLG_HEADER": "Nedávne súbory",
  "RECENT_FILES_DLG_CLEAR_BUTTON_LABEL": "jasný",
  "RECENT_FILES_DLG_CLEAR_BUTTON_TITLE": "Vymazať súbory, ktoré nie sú v pracovnej sade",
  "DESCRIPTION_CLOSE_BRACKETS": "true na automatické uzatváranie zátvoriek, zátvoriek a zátvoriek",
  "DESCRIPTION_CLOSE_OTHERS_ABOVE": "false, ak chcete odstrániť \"Zavrieť ostatné vyššie\" z kontextovej ponuky Pracovné súbory",
  "DESCRIPTION_CLOSE_OTHERS_BELOW": "false, ak chcete odstrániť \"Zavrieť ostatné nižšie\" z kontextovej ponuky Pracovné súbory",
  "DESCRIPTION_CLOSE_OTHERS": "false na odstránenie \"Zavrieť ostatné\" z kontextovej ponuky Pracovné súbory",
  "DESCRIPTION_CLOSE_TAGS": "Nastavuje možnosti zatvárania tagov",
  "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS": "Pole značiek, ktoré by sa nemali automaticky zatvárať",
  "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING": "Zatvorte, keď napíšete > otváracej značky",
  "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING": "Zatvorte, keď zadáte / uzatváracej značky",
  "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS": "Pole značiek, ktoré majú po otvorení prázdny riadok",
  "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD": "true, aby sa pri zmene úrovne odsadenia vždy vygenerovali skladacie značky sekcií",
  "DESCRIPTION_CODE_FOLDING_ENABLED": "true na povolenie skladania kódu",
  "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER": "true, aby boli značky zrútenia sekcií viditeľné iba vtedy, keď prejdete myšou nad odkvap",
  "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL": "Obmedzuje, na koľko úrovní hlboko platí Collapse All",
  "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE": "Minimálny počet riadkov pred zobrazením ikony skladateľnej sekcie",
  "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES": "pravda, aby si zapamätal zbalené sekcie, ak zatvoríte a znova otvoríte súbor alebo projekt",
  "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE": "true na povolenie skladania kódu na vybranom texte v editore",
  "DESCRIPTION_DISABLED_DEFAULT_EXTENSIONS": "Predvolené rozšírenia, ktoré sú zakázané",
  "DESCRIPTION_ATTR_HINTS": "Povoliť/zakázať rady atribútov HTML",
  "DESCRIPTION_CSS_PROP_HINTS": "Povoliť/zakázať rady vlastností CSS/LESS/SCSS",
  "DESCRIPTION_JS_HINTS": "Povoliť/zakázať rady pre kód JavaScript",
  "DESCRIPTION_JS_HINTS_TYPE_DETAILS": "Povolenie/zakázanie podrobností o údajovom type v tipoch kódu JavaScript",
  "DESCRIPTION_PREF_HINTS": "Povoliť/zakázať rady pre kódy preferencií",
  "DESCRIPTION_SPECIAL_CHAR_HINTS": "Povoliť/zakázať rady entity HTML",
  "DESCRIPTION_SVG_HINTS": "Povoliť/zakázať rady pre kód SVG",
  "DESCRIPTION_HTML_TAG_HINTS": "Povoliť/zakázať rady značiek HTML",
  "DESCRIPTION_URL_CODE_HINTS": "Povoliť/zakázať odkazy na adresy URL v HTML a CSS/LESS/SCSS",
  "DESCRIPTION_DRAG_DROP_TEXT": "Zapnutie/vypnutie funkcie Drag & Drop",
  "DESCRIPTION_HEALTH_DATA_TRACKING": "Povoľte sledovanie zdravotných údajov",
  "DESCRIPTION_HIGHLIGHT_MATCHES": "Umožňuje automatické zvýraznenie zhodných reťazcov v celom dokumente",
  "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN": "Zvýrazniť všetky reťazce, ktoré sa zhodujú s tokenom, v ktorom sa momentálne nachádza kurzor (nie je potrebný žiadny výber)",
  "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY": "Zvýraznite len vtedy, keď je výber úplný token",
  "DESCRIPTION_INSERT_HINT_ON_TAB": "true na vloženie aktuálne vybratej rady pre kód na kartu",
  "DESCRIPTION_NO_HINTS_ON_DOT": "true, aby sa automaticky nezobrazovali rady pre kód JS, keď . je napísaný",
  "DESCRIPTION_JSHINT_OPTIONS": "Objekt s predvolenými voľbami pre JSHint. Všetky dostupné možnosti JSHint nájdete na nasledujúcej adrese URL: https://jshint.com/docs/options/",
  "DESCRIPTION_LANGUAGE": "Nastavenia špecifické pre jazyk",
  "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS": "Ďalšie mapovania z prípony súboru na názov jazyka",
  "DESCRIPTION_LANGUAGE_FILE_NAMES": "Ďalšie mapovania z názvu súboru na názov jazyka",
  "DESCRIPTION_LINEWISE_COPY_CUT": "Ak vykonáte kopírovanie a vystrihnutie, keď nie je žiadny výber, skopírujú sa alebo vystrihnú celé riadky, v ktorých sú kurzory",
  "DESCRIPTION_INPUT_STYLE": "Vyberá spôsob, akým CodeMirror spracováva vstup a zaostrenie. Môže to byť textarea, ktorá je predvolená, alebo contenteditable, ktorá je lepšia pre čítačky obrazovky (nestabilná)",
  "DESCRIPTION_LINTING_ENABLED": "pravda, aby sa umožnila kontrola kódu",
  "DESCRIPTION_ASYNC_TIMEOUT": "Čas v milisekundách, po ktorom uplynie časový limit asynchrónnych línií",
  "DESCRIPTION_LINTING_PREFER": "Pole linters spustiť ako prvý",
  "DESCRIPTION_LIVE_DEV_MULTIBROWSER": "true, aby ste povolili experimentálny živý náhľad",
  "DESCRIPTION_USE_PREFERED_ONLY": "pravda, len na spúšťanie poskytovateľov špecifikovaných v linting.prefer",
  "DESCRIPTION_MAX_CODE_HINTS": "Maximálny počet tipov kódu zobrazených naraz",
  "DESCRIPTION_PATH": "Nastavenia špecifické pre cestu",
  "DESCRIPTION_PROXY": "Adresa URL servera proxy použitého na inštaláciu rozšírenia",
  "DESCRIPTION_SCROLL_PAST_END": "true, aby sa umožnilo posúvanie za koniec dokumentu",
  "DESCRIPTION_SHOW_CODE_HINTS": "false, ak chcete zakázať všetky tipy na kód",
  "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING": "Pri výbere textu ponechá blikajúci kurzor viditeľný",
  "DESCRIPTION_SHOW_LINE_NUMBERS": "true, aby sa čísla riadkov zobrazovali v „odkvape“ naľavo od kódu",
  "DESCRIPTION_SMART_INDENT": "Automaticky odsadiť pri vytváraní nového bloku",
  "DESCRIPTION_SOFT_TABS": "false na vypnutie správania mäkkých kariet",
  "DESCRIPTION_SORT_DIRECTORIES_FIRST": "true, ak chcete zoradiť adresáre ako prvé v strome projektu",
  "DESCRIPTION_SPACE_UNITS": "Počet medzier, ktoré sa majú použiť na medzerové odsadenie",
  "DESCRIPTION_STATIC_SERVER_PORT": "Číslo portu, ktoré by mal vstavaný server použiť na živý náhľad",
  "DESCRIPTION_STYLE_ACTIVE_LINE": "true na zvýraznenie farby pozadia riadku, na ktorom je kurzor",
  "DESCRIPTION_TAB_SIZE": "Počet medzier na zobrazenie pre karty",
  "DESCRIPTION_USE_TAB_CHAR": "true na použitie tabulátorov namiesto medzier",
  "DESCRIPTION_UPPERCASE_COLORS": "true na generovanie veľkých hexadecimálnych farieb v Inline Color Editor",
  "DESCRIPTION_WORD_WRAP": "Zalomenie čiar, ktoré presahujú šírku výrezu",
  "DESCRIPTION_SEARCH_AUTOHIDE": "Zatvorte vyhľadávanie hneď, ako je editor zameraný",
  "DESCRIPTION_DETECTED_EXCLUSIONS": "Zoznam súborov, pri ktorých sa zistilo, že sa Tern vymkne spod kontroly",
  "DESCRIPTION_INFERENCE_TIMEOUT": "Čas, po ktorom Tern vyprší pri pokuse o pochopenie súborov",
  "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR": "true na zobrazenie chýb v stavovom riadku",
  "DESCRIPTION_QUICK_VIEW_ENABLED": "true, aby ste povolili rýchly náhľad",
  "DESCRIPTION_SELECTION_VIEW_ENABLED": "true, ak chcete povoliť zobrazenie výberu",
  "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW": "true, ak chcete zobraziť ukážky obrázkov pre adresy URL bez rozšírení",
  "DESCRIPTION_THEME": "Vyberte motív aplikácie {APP_NAME}",
  "DESCRIPTION_USE_THEME_SCROLLBARS": "true na povolenie vlastných posúvačov",
  "DESCRIPTION_LINTING_COLLAPSED": "verný poťahový panel",
  "DESCRIPTION_FONT_FAMILY": "Zmeniť rodinu písiem",
  "DESCRIPTION_FONT_SIZE": "Zmeňte veľkosť písma; napr. 13 pixelov",
  "DESCRIPTION_FIND_IN_FILES_NODE": "true na povolenie vyhľadávania na základe uzlov",
  "DESCRIPTION_FIND_IN_FILES_INSTANT": "true, aby sa umožnilo okamžité vyhľadávanie",
  "DESCRIPTION_FONT_SMOOTHING": "Iba pre Mac: \"subpixel-antialiased\" na povolenie subpixelového antialiasingu alebo \"antialiased\" pre antialiasing v odtieňoch šedej",
  "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW": "false na zakázanie otvárania súboru preferencií v rozdelenom zobrazení",
  "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE": "false na otvorenie súboru používateľských preferencií v ľavom/hornom paneli",
  "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED": "true zbaliť panely po zatvorení posledného súboru z panela pomocou tlačidla zatvorenia hlavičky panela",
  "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS": "Prepínajte, kedy sa majú v hlavičke zobraziť tlačidlá zatvorenia a prevrátenia.",
  "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT": "/*\n * Toto je súbor len na čítanie s podporovanými preferenciami\n * od aplikácie {APP_NAME}.\n * Použite tento súbor ako referenciu na úpravu vašich preferencií\n * súbor \"brackets.json\" otvorený na druhom paneli.\n * Ďalšie informácie o tom, ako používať predvoľby vo vnútri\n * {APP_NAME}, pozrite si webovú stránku https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences\n */",
  "DEFAULT_PREFERENCES_JSON_DEFAULT": "Predvolené",
  "DESCRIPTION_PURE_CODING_SURFACE": "true, ak chcete povoliť režim iba kódu a skryť všetky ostatné prvky používateľského rozhrania v aplikácii {APP_NAME}",
  "DESCRIPTION_INDENT_LINE_COMMENT": "true, aby sa umožnilo odsadenie komentárov k riadkom",
  "DESCRIPTION_RECENT_FILES_NAV": "Povoliť/zakázať navigáciu v posledných súboroch",
  "DESCRIPTION_LIVEDEV_WEBSOCKET_PORT": "Port, na ktorom beží WebSocket Server pre živý náhľad",
  "DESCRIPTION_LIVE_DEV_HIGHLIGHT_SETTINGS": "Nastavenia zvýraznenia živého náhľadu",
  "DESCRIPTION_LIVEDEV_ENABLE_REVERSE_INSPECT": "false, ak chcete zakázať spätnú kontrolu živého náhľadu",
  "DOWNLOAD_FAILED": "Sťahovanie zlyhalo.",
  "DOWNLOAD_COMPLETE": "Sťahovanie dokončené!",
  "UPDATE_SUCCESSFUL": "Aktualizácia úspešná!",
  "UPDATE_FAILED": "Aktualizacia neuspešná!",
  "VALIDATION_FAILED": "Overenie zlyhalo!",
  "INITIALISATION_FAILED": "Inicializácia zlyhala!",
  "CLEANUP_FAILED": "Čistenie zlyhalo!",
  "WARNING_TYPE": "POZOR!",
  "CLICK_RESTART_TO_UPDATE": "Kliknutím na Reštartovať aktualizujte zátvorky.",
  "UPDATE_ON_NEXT_LAUNCH": "Aktualizácia sa použije pri opätovnom spustení.",
  "GO_TO_SITE": "Prejdite na <a href = \"http://brackets.io/\">stránku brackets.io</a> a skúste to znova.",
  "INTERNET_UNAVAILABLE": "Nie je k dispozícii internetové pripojenie.",
  "UPDATEDIR_READ_FAILED": "Aktualizovať adresár sa nepodarilo prečítať.",
  "UPDATEDIR_CLEAN_FAILED": "Aktualizačný adresár sa nepodarilo vyčistiť.",
  "INITIAL_DOWNLOAD": "Sťahuje sa aktualizácia...",
  "RETRY_DOWNLOAD": "Sťahovanie zlyhalo. Opakujem...Pokus",
  "VALIDATING_INSTALLER": "Sťahovanie dokončené! Overuje sa inštalátor...",
  "CHECKSUM_DID_NOT_MATCH": "Kontrolný súčet sa nezhodoval.",
  "INSTALLER_NOT_FOUND": "Inštalátor sa nenašiel.",
  "DOWNLOAD_ERROR": "Pri sťahovaní sa vyskytla chyba.",
  "NETWORK_SLOW_OR_DISCONNECTED": "Sieť je odpojená alebo príliš pomalá.",
  "RESTART_BUTTON": "Reštart",
  "LATER_BUTTON": "Neskôr",
  "DESCRIPTION_AUTO_UPDATE": "Povoliť/zakázať automatickú aktualizáciu zátvoriek",
  "AUTOUPDATE_ERROR": "Chyba!",
  "AUTOUPDATE_IN_PROGRESS": "Aktualizácia už prebieha.",
  "NUMBER_WITH_PERCENTAGE": "{0} %",
  "CMD_FIND_RELATED_FILES": "Nájsť súvisiace súbory",
  "PHP_VERSION_INVALID": "Chyba pri analýze verzie PHP. Skontrolujte prosím výstup príkazu „php –version“.",
  "PHP_UNSUPPORTED_VERSION": "Nainštalujte runtime PHP7, aby ste umožnili nástroje súvisiace s PHP, ako sú rady pre kód, rady pre parametre, skok na definíciu a ďalšie. Nájdená verzia: {0}",
  "PHP_EXECUTABLE_NOT_FOUND": "Runtime PHP sa nenašlo. Nainštalujte runtime PHP7 a vhodne aktualizujte „executablePath“ v predvoľbách PHP. To umožňuje nástroje súvisiace s PHP, ako sú tipy na kód, tipy na parametre, skok na definíciu a ďalšie.",
  "PHP_PROCESS_SPAWN_ERROR": "Pri spúšťaní procesu PHP sa vyskytol kód chyby {0}.",
  "PHP_SERVER_ERROR_TITLE": "Chyba",
  "PHP_SERVER_MEMORY_LIMIT_INVALID": "Zadaný limit pamäte je neplatný. Skontrolujte predvoľby PHP a nastavte správnu hodnotu.",
  "DESCRIPTION_PHP_TOOLING_CONFIGURATION": "Predvolené nastavenia konfigurácie PHP Tooling",
  "OPEN_PREFERENNCES": "Otvorte Predvoľby",
  "LANGUAGE_TOOLS_PREFERENCES": "Predvoľby pre jazykové nástroje",
  "FIND_ALL_REFERENCES": "Nájsť všetky referencie",
  "REFERENCES_IN_FILES": "referencie",
  "REFERENCE_IN_FILES": "odkaz",
  "REFERENCES_NO_RESULTS": "Pre aktuálnu polohu kurzora nie sú dostupné žiadne referencie",
  "CMD_FIND_DOCUMENT_SYMBOLS": "Nájdite symboly dokumentov",
  "CMD_FIND_PROJECT_SYMBOLS": "Nájdite symboly projektu",
  "REMOTE_DEBUGGING_ENABLED": "Vzdialené ladenie povolené na localhost:",
  "REMOTE_DEBUGGING_PORT_INVALID": "Nemožno povoliť vzdialené ladenie na porte {0}. Čísla portov by mali byť medzi {1} a {2}.",
  "DESCRIPTION_EXTERNAL_APPLICATION_ASSOCIATE": "Mapovania prípon súborov na externé aplikácie. Syntax: \"<typ_súboru>\": \"<predvolený|názov aplikácie|Cesta aplikácie>\", použite \"predvolené\" na otvorenie súborov v systémovej predvolenej aplikácii pre daný typ súboru.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_TITLE": "Otvorte grafické súbory v externých editoroch.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_MSG": "Váš aktuálny priečinok obsahuje typy grafických súborov, ktoré aplikácia {APP_NAME} nepodporuje.<br/> Teraz môžete priradiť konkrétne typy súborov k externým editorom. Po priradení môžete otvárať grafické súbory ako .xd, .psd, .jpg, .png, .ai, .svg v ich predvolených aplikáciách dvojitým kliknutím na súbory v strome súborov.<br/><br/> Kliknutím na tlačidlo „OK“ priradíte typy grafických súborov k ich príslušným predvoleným aplikáciám.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_CNF_MSG": "Nasledujúce typy súborov boli úspešne priradené k predvoleným aplikáciám.<br/> (",
  "UNSUPPORTED_BROWSER": "Prehliadač nie je podporovaný",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER": "Prehliadač nepodporuje otvorenie priečinka",
  "UNSUPPORTED_BROWSER_MESSAGE_LINE1": "Použite jeden z podporovaných prehliadačov nižšie.",
  "UNSUPPORTED_BROWSER_MESSAGE_LINE2": " Usilovne pracujeme na tom, aby bol Phoenix dostupný vo viacerých prehliadačoch. Tento dialóg môžete zavrieť, ale niektoré funkcie vo Phoenixe nebudú v tomto prehliadači fungovať.",
  "CANNOT_PUBLISH_LARGE_PROJECT": "Nie je možné publikovať veľký projekt",
  "CANNOT_PUBLISH_LARGE_PROJECT_MESSAGE": "Phoenix je stále v experimentálnej verzii alfa. Zatiaľ sme nepovolili synchronizáciu projektov s viac ako 500 súbormi.",
  "SHARE_WEBSITE": "Zverejniť a zdieľať webovú stránku?",
  "PUBLISH": "Publikovať",
  "PUBLISH_CONSENT_MESSAGE": "Rýchlo ukážte zmeny a zdieľajte svoje webové stránky s ostatnými. Spoločnosť Phoenix vám môže zverejniť túto webovú stránku na adrese {0}. Zverejnené odkazy budú platné po dobu 7 dní. </br>Chcete zverejniť a zdieľať svoje webové stránky?",
  "PUBLISH_SYNC_IN_PROGRESS": "Prebieha synchronizácia pre ukážku...",
  "PUBLISH_PAGE": "Kliknutím zverejníte a zdieľate túto stránku",
  "PUBLISH_VIEW_PAGE": "Kliknutím zobrazíte zverejnenú stránku",
  "MISSING_FIELDS": "Chýbajúce polia",
  "PLEASE_FILL_ALL_REQUIRED": "Vyplňte všetky povinné polia zvýraznené červenou farbou",
  "CODE_EDITOR": "Editor kódu",
  "BUILD_THE_WEB": "Vytvorte web",
  "IMPORT_PROJECT": "Importovať projekt",
  "GITHUB_PROJECT": "Projekt GitHub",
  "NEW_PROJECT_FROM_GITHUB": "Nový projekt od GitHubu",
  "GITHUB_REPO_URL": "Adresa URL úložiska GitHub:",
  "CREATE_PROJECT": "Vytvoriť projekt",
  "SETTING_UP_PROJECT": "Nastavenie projektu",
  "LOCATION": "miesto:",
  "DOWNLOADING": "Sťahuje sa...",
  "EXTRACTING_FILES_PROGRESS": "Extrahuje sa {0} z {1} súborov.",
  "DOWNLOAD_FAILED_MESSAGE": "Uistite sa, že adresa URL na stiahnutie je platná. </br>Poznámka: Keďže Phoenix je vo verzii alfa, súkromné repozitáre a adresy URL GitHub väčšie ako 25 MB nie sú povolené.",
  "PLEASE_SELECT_A_FOLDER": "Vyberte priečinok...",
  "UNZIP_IN_PROGRESS": "Rozbaľujú sa súbory...",
  "UNZIP_FAILED": "Chyba: Rozbalenie zlyhalo.",
  "CONFIRM_REPLACE_TITLE": "Potvrďte Nahradiť",
  "KEEP_BOTH": "Nechaj si obe",
  "EXPLORE": "HTML hry",
  "BLOG": "Blog",
  "PHOENIX_DEFAULT_PROJECT": "Predvolený projekt",
  "PROJECT_NAME": "Názov projektu:",
  "NEW_HTML": "Nový projekt HTML",
  "LICENSE": "Licencia:",
  "CREDITS": "Kredity:",
  "PREVIEW": "Náhľad",
  "BUILD_WEBSITE": "Vytvoriť webovú stránku",
  "VIEW_MORE": "Vidieť viac...",
  "NEW_PROJECT_NOTIFICATION": "Kliknite na túto ikonu<br/> vytvoriť nový projekt.</br> <a href='#' style='float:right;'>ok</a>",
  "DEFAULT_PROJECT_NOTIFICATION": "Kliknutím sem otvoríte<br/> <b>predvolený projekt</b> vo Phoenixe.</br> <a href='#' style='float:right;'>ok</a>",
  "DIRECTORY_REPLACE_MESSAGE": "Vybratý priečinok <span class='dialog-filename'>{0}</span> nie je prázdny. Naozaj chcete nahradiť obsah priečinka projektom?",
  "BUILD_WEBSITE_SECTION": "Vytvoriť webovú stránku",
  "LEARN_SECTION": "Učte sa s príkladmi",
  "WEBPAGE_HOME_PAGE": "Rozloženie domovskej stránky",
  "WEBPAGE_BLOG": "Blogová stránka",
  "WEBPAGE_DASHBOARD": "HTML Dashboard",
  "WEBPAGE_BOOTSTRAP_EXAMPLES": "Príklady bootstrapu",
  "GUIDED_FILES_SIDEBAR": "Vyberte súbor HTML</br> <a href='#' style='float:right;'>ok</a>",
  "GUIDED_LIVE_PREVIEW": "Vykonajte nejaké zmeny v kóde a uložte súbor, aby ste videli ukážku.</br> <a href='#' style='float:right;'>ok</a>",
  "GUIDED_LIVE_PREVIEW_POPOUT": "Kliknutím na toto tlačidlo zobrazíte živý náhľad na novú kartu.</br> <a href='#' style='float:right;'>ok</a>",
  "TEST_TRANSLATE": "použite na testovanie prekladov",
  "BEAUTIFY_ERROR": "Kód sa nepodarilo skrášliť. Skontrolujte syntax.",
  "BEAUTIFY_ERROR_ORIGINAL_CHANGED": "Nedalo sa skrášliť. Text editora zmenený po skrášlení.",
  "BEAUTIFY_PROJECT_BUSY_MESSAGE": "Skrášľujúci súbor {0}",
  "BEAUTIFY_ERROR_SELECTION": "Nepodarilo sa skrášliť.</br>Vybrali ste neúplný blok kódu alebo neplatnú syntax.",
  "BEAUTIFY_OPTIONS": "Možnosti, ktoré riadia fungovanie Beautify Code",
  "BEAUTIFY_OPTION_PRINT_WIDTH": "Zadajte dĺžku čiary, na ktorú sa skrášľovač zalomí",
  "BEAUTIFY_OPTION_SEMICOLON": "Na koniec každého výroku pridajte bodkočiarku",
  "BEAUTIFY_OPTION_SINGLE_QUOTE": "Namiesto dvojitých úvodzoviek používajte jednoduché úvodzovky",
  "BEAUTIFY_OPTION_QUOTE_PROPS": "Zmena, keď sú vlastnosti v objektoch citované",
  "BEAUTIFY_OPTION_BRACKET_SAME_LINE": "Umiestnite > viacriadkového prvku HTML (HTML, JSX, Vue, Angular) na koniec posledného riadku namiesto toho, aby ste boli sami na ďalšom riadku (neplatí pre samozatváracie prvky)",
  "BEAUTIFY_OPTION_SINGLE_ATTRIBUTE_PER_LINE": "Vynútiť jeden atribút na riadok v HTML, Vue a JSX",
  "BEAUTIFY_OPTION_PROSE_WRAP": "Zabaľte prózu, ak presahuje šírku tlače do súborov značiek",
  "BEAUTIFY_OPTION_PRINT_TRAILING_COMMAS": "Vždy, keď je to možné, tlačte koncové čiarky vo viacriadkových syntaktických štruktúrach oddelených čiarkami"
});