/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "Padrão do sistema",
  "PROJECT_BUSY": "Operações do projeto em andamento",
  "DUPLICATING": "Duplicando {0}",
  "MOVING": "Movendo {0}",
  "COPYING": "Copiando {0}",
  "DELETING": "Excluindo {0}",
  "RENAMING": "Renomeando",
  "GENERIC_ERROR": "(erro {0})",
  "NOT_FOUND_ERR": "O arquivo não pôde ser encontrado.",
  "NOT_READABLE_ERR": "O arquivo não pôde ser lido.",
  "EXCEEDS_MAX_FILE_SIZE": "Arquivos maiores que {0} MB não podem ser abertos no {APP_NAME}.",
  "NO_MODIFICATION_ALLOWED_ERR": "O diretório de destino não pode ser modificado.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "As permissões não permitem que você faça modificações.",
  "CONTENTS_MODIFIED_ERR": "O arquivo foi modificado fora do {APP_NAME}.",
  "UNSUPPORTED_ENCODING_ERR": "{APP_NAME} atualmente suporta apenas arquivos de texto codificados em UTF-8.",
  "ENCODE_FILE_FAILED_ERR": "{APP_NAME} não conseguiu codificar o conteúdo do arquivo.",
  "DECODE_FILE_FAILED_ERR": "{APP_NAME} não conseguiu decodificar o conteúdo do arquivo.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "{APP_NAME} atualmente não é compatível com arquivos de texto codificados em UTF-16.",
  "FILE_EXISTS_ERR": "Arquivo ou pasta já existe.",
  "FILE": "arquivo",
  "FILE_TITLE": "Arquivo",
  "DIRECTORY": "diretório",
  "DIRECTORY_TITLE": "Diretório",
  "DIRECTORY_NAMES_LEDE": "Nomes de diretórios",
  "FILENAMES_LEDE": "Nomes de arquivos",
  "FILENAME": "Nome de arquivo",
  "DIRECTORY_NAME": "Nome de diretório",
  "ERROR_LOADING_PROJECT": "Erro ao carregar o projeto",
  "OPEN_DIALOG_ERROR": "Ocorreu um erro ao mostrar o diálogo de abertura de arquivo. (erro {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "Ocorreu um erro ao tentar carregar a pasta <span class='dialog-filename'>{0}</span>. (erro {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "Ocorreu um erro ao ler o conteúdo da pasta <span class='dialog-filename'>{0}</span>. (erro {1})",
  "ZOOM_WITH_SHORTCUTS": "Use atalhos de teclado para ampliar",
  "ZOOM_WITH_SHORTCUTS_DETAILS": "Use os atalhos de teclado <code><i>{0}</i></code> para aumentar o zoom e <code><i>{1}</i></code> para diminuir o zoom.",
  "ERROR_OPENING_FILE_TITLE": "Erro ao abrir arquivo",
  "ERROR_OPENING_FILE": "Ocorreu um erro ao tentar abrir o arquivo <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_OPENING_FILES": "Ocorreu um erro ao tentar abrir os seguintes arquivos:",
  "ERROR_RELOADING_FILE_TITLE": "Erro ao recarregar as mudanças a partir do disco",
  "ERROR_RELOADING_FILE": "Ocorreu um erro ao tentar recarregar o arquivo <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_SAVING_FILE_TITLE": "Erro ao salvar arquivo",
  "ERROR_SAVING_FILE": "Ocorreu um erro ao tentar salvar o arquivo <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_FILE_TITLE": "Erro ao renomear arquivo",
  "ERROR_RENAMING_FILE": "Ocorreu um erro ao tentar renomear o arquivo <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "O arquivo ou diretório não faz parte do projeto aberto no momento. Infelizmente, apenas arquivos de projeto podem ser renomeados neste momento.",
  "ERROR_MOVING_FILE_TITLE": "Erro ao mover {0}",
  "ERROR_MOVING_FILE": "Ocorreu um erro ao tentar mover o {2} <span class='dialog-filename'>{0}</span> . {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "Não é possível mover o arquivo/pasta, pois eles não fazem parte do projeto atual.",
  "ERROR_DELETING_FILE_TITLE": "Erro ao excluir arquivo",
  "ERROR_DELETING_FILE": "Ocorreu um erro ao tentar excluir o arquivo <span class='dialog-filename'>{0}</span>. {1}",
  "INVALID_FILENAME_TITLE": "{0} inválido",
  "CANNOT_PASTE_TITLE": "Não é possível colar {0}",
  "CANNOT_DOWNLOAD_TITLE": "Não é possível baixar {0}",
  "ERR_TYPE_DOWNLOAD_FAILED": "Ocorreu um erro durante o download <span class='dialog-filename'>de {0}</span>",
  "ERR_TYPE_PASTE_FAILED": "Ocorreu um erro ao colar <span class='dialog-filename'>{0}</span> em <span class='dialog-filename'>{1}</span>",
  "CANNOT_DUPLICATE_TITLE": "Não é possível duplicar",
  "ERR_TYPE_DUPLICATE_FAILED": "Ocorreu um erro ao duplicar <span class='dialog-filename'>{0}</span>",
  "ERR_TYPE_DUPLICATE_FAILED_NO_FILE": "Selecione um arquivo para duplicar.",
  "INVALID_FILENAME_MESSAGE": "{0} não podem usar palavras reservadas do sistema, terminar com pontos (.) ou conter qualquer um dos seguintes caracteres: <code class='emphasized'>{1}</code>.",
  "ENTRY_WITH_SAME_NAME_EXISTS": "Já existe um arquivo ou diretório como o nome <span class='dialog-filename'>{0}</span>.",
  "ERROR_CREATING_FILE_TITLE": "Erro ao criar {0}",
  "ERROR_CREATING_FILE": "Ocorreu um erro ao tentar criar o {0} <span class='dialog-filename'>{1}</span>. {2}",
  "ERROR_MIXED_DRAGDROP": "Não é possível abrir uma pasta e outros arquivos ao mesmo tempo.",
  "ERROR_KEYMAP_TITLE": "Erro ao ler mapa de teclas do usuário",
  "ERROR_KEYMAP_CORRUPT": "Seu arquivo de mapa de teclas não é um JSON válido. O arquivo será aberto para que você possa corrigir o formato.",
  "ERROR_LOADING_KEYMAP": "Seu arquivo de mapa de teclas não é um arquivo de texto com codificação UTF-8 válida e não pode ser carregado",
  "ERROR_RESTRICTED_COMMANDS": "Você não pode reatribuir atalhos para estes comandos: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "Você não pode reatribuir estes atalhos: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "Você está reatribuindo múltiplos atalhos para estes comandos: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "Você tem múltiplos vínculos para estes atalhos: {0}",
  "ERROR_INVALID_SHORTCUTS": "Estes atalhos são inválidos: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "Você está atribuindo atalhos para comandos não existentes: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "Erro ao ler as preferências",
  "ERROR_PREFS_CORRUPT": "Seu arquivo de preferências não é um JSON válido. O arquivo será aberto para que você possa corrigir o formato. Você deverá reiniciar o {APP_NAME} para as alterações terem efeito.",
  "ERROR_PROJ_PREFS_CORRUPT": "O arquivo de preferências de seu projeto não é um arquivo JSON válido. O arquivo será aberto para que você corrija sua formatação. Você precisará recarregar o projeto, para que as mudanças façam efeito.",
  "ERROR_IN_BROWSER_TITLE": "Opa! O {APP_NAME} não funciona em navegadores ainda.",
  "ERROR_IN_BROWSER": "O {APP_NAME} é criado em HTML, mas no momento ele é executado como um aplicativo de desktop para que você possa usá-lo para editar arquivos locais. Por favor, use o shell da aplicação do repositório <b>github.com/adobe/brackets-shell</b> para executar {APP_NAME}.",
  "ERROR_MAX_FILES_TITLE": "Erro ao indexar arquivos",
  "ERROR_MAX_FILES": "Este projeto contém mais de 30.000 arquivos. Funcionalidades que operam em múltiplos arquivos podem ser desabilitadas ou se comportarem como se o projeto estivesse vazio. <a href='https://github.com/adobe/brackets/wiki/Large-Projects'>Leia mais sobre como trabalhar com grandes projetos</a>.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "Erro ao abrir o navegador",
  "ERROR_CANT_FIND_CHROME": "O navegador Google Chrome não pôde ser encontrado. Por favor, verifique se ele está instalado.",
  "ERROR_LAUNCHING_BROWSER": "Ocorreu um erro ao iniciar o navegador. (erro {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "Erro no Live Preview",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "Conectando-se ao navegador",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "Para que o Live Preview conecte-se, o Chrome deve ser reiniciado com a opção de depuração remota ativada.<br /><br />Gostaria de abrir o Chrome novamente e permitir a depuração remota?",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "Não foi possível carregar a página de Live Preview",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "Para iniciar um live preview com um arquivo server-side, é preciso especificar uma URL Base para este projeto.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "Erro ao iniciar o servidor HTTP para os arquivos do desenvolvimento em tempo real. Por favor, tente novamente.",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "Para mais informações, veja <a href='{0}' title='{0}'>Solucionando erros de conexão com Live Development</a>.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "Live Preview",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "Live Preview: Conectando…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "Live Preview: Inicializando…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "Desconectar Live Preview",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "Live Preview",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "Selecione o arquivo para visualização ao vivo",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "Recarregar página",
  "LIVE_DEV_TOGGLE_LIVE_HIGHLIGHT": "Alternar destaques da visualização ao vivo",
  "LIVE_DEV_CLICK_POPOUT": "Visualização ao vivo de pop-up para nova janela",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "Fixar na página de visualização de desafixação",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "Live Preview (atualização interrompida devido a erro de sintaxe)",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "O Live Preview foi cancelado pois as ferramentas de desenvolvedor do navegador foram abertas",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "O Live Preview foi cancelado pois a página foi fechada no navegador",
  "LIVE_DEV_NAVIGATED_AWAY": "O Live Preview foi cancelado pois o navegador foi para uma página que não pertence a este projeto atual",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "O Live Preview foi cancelado por uma razão desconhecida ({0})",
  "SAVE_CLOSE_TITLE": "Salvar alterações",
  "SAVE_CLOSE_MESSAGE": "Você quer salvar as alterações feitas no documento <span class='dialog-filename'>{0}</span>?",
  "SAVE_CLOSE_MULTI_MESSAGE": "Você quer salvar as alterações feitas aos seguintes arquivos?",
  "EXT_MODIFIED_TITLE": "Alterações externas",
  "CONFIRM_DELETE_TITLE": "Confirmar exclusão",
  "CONFIRM_FILE_DELETE": "Tem certeza de que deseja excluir o arquivo <span class='dialog-filename'>{0}</span> ?",
  "CONFIRM_FOLDER_DELETE": "Tem certeza que deseja excluir a pasta <span class='dialog-filename'>{0}</span>?",
  "FILE_DELETED_TITLE": "Arquivo excluído",
  "EXT_MODIFIED_WARNING": "<span class='dialog-filename'>{0}</span> foi modificado no disco.<br /><br />Deseja salvar o arquivo e sobrescrever essas alterações?",
  "EXT_MODIFIED_MESSAGE": "<span class='dialog-filename'>{0}</span> foi modificado no disco, mas também tem alterações não salvas em {APP_NAME}.<br /><br />Qual versão você quer manter?",
  "EXT_DELETED_MESSAGE": "<span class='dialog-filename'>{0}</span> foi excluído no disco, mas tem alterações não salvas em {APP_NAME}.<br /><br />Deseja manter suas alterações?",
  "WINDOW_UNLOAD_WARNING": "Tem certeza de que deseja navegar para um URL diferente e sair dos colchetes?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "Você tem alterações não salvas! Tem certeza de que deseja navegar para um URL diferente e sair dos colchetes?",
  "DONE": "Concluído",
  "OK": "OK",
  "CANCEL": "Cancelar",
  "DONT_SAVE": "Não salvar",
  "SAVE": "Salvar",
  "SAVE_AS": "Salvar como…",
  "SAVE_AND_OVERWRITE": "Sobrescrever",
  "DELETE": "Excluir",
  "BUTTON_YES": "Sim",
  "BUTTON_NO": "Não",
  "FIND_MATCH_INDEX": "{0} de {1}",
  "FIND_NO_RESULTS": "Nenhum resultado",
  "FIND_QUERY_PLACEHOLDER": "Localizar…",
  "FIND_HISTORY_MAX_COUNT": "Número máximo de itens de pesquisa no histórico de pesquisa",
  "REPLACE_PLACEHOLDER": "Substituir por…",
  "BUTTON_REPLACE_ALL": "Tudo…",
  "BUTTON_REPLACE_BATCH": "Lote…",
  "BUTTON_REPLACE_ALL_IN_FILES": "Substituir…",
  "BUTTON_REPLACE": "Substituir",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "Resultado seguinte",
  "BUTTON_PREV_HINT": "Resultado anterior",
  "BUTTON_CASESENSITIVE_HINT": "Diferenciar maiúsculas/minúsculas",
  "BUTTON_REGEXP_HINT": "Expressão regular",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "Substituir sem desfazer",
  "REPLACE_WITHOUT_UNDO_WARNING": "Porque mais de {0} arquivos precisam ser alterados, {APP_NAME} irá modificar arquivos não abertos no disco.<br />Não será possível desfazer as modificações nestes arquivos.",
  "BUTTON_REPLACE_WITHOUT_UNDO": "Substituir sem desfazer",
  "OPEN_FILE": "Abrir arquivo",
  "SAVE_FILE_AS": "Salvar arquivo",
  "CHOOSE_FOLDER": "Escolha uma pasta",
  "RELEASE_NOTES": "Notas da versão",
  "NO_UPDATE_TITLE": "Você está atualizado!",
  "NO_UPDATE_MESSAGE": "Você está executando a versão mais recente do {APP_NAME}.",
  "FIND_REPLACE_TITLE_LABEL": "Substituir",
  "FIND_REPLACE_TITLE_WITH": "por",
  "FIND_TITLE_LABEL": "Encontrados",
  "FIND_TITLE_SUMMARY": "&mdash; {0} {1} {2} em {3}",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "em <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_NO_SCOPE": "no projeto",
  "FIND_IN_FILES_ZERO_FILES": "Filtro exclui todos os arquivos {0}",
  "FIND_IN_FILES_FILE": "arquivo",
  "FIND_IN_FILES_FILES": "arquivos",
  "FIND_IN_FILES_MATCH": "resultado",
  "FIND_IN_FILES_MATCHES": "resultados",
  "FIND_IN_FILES_MORE_THAN": "Mais de ",
  "FIND_IN_FILES_PAGING": "{0}&mdash;{1}",
  "FIND_IN_FILES_FILE_PATH": "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "Ctrl/Cmd + clique para expandir/comprimir tudo",
  "FIND_IN_FILES_INDEXING": "Indexação de pesquisa instantânea…",
  "FIND_IN_FILES_INDEXING_PROGRESS": "Indexando {0} de {1} arquivos para pesquisa instantânea…",
  "REPLACE_IN_FILES_ERRORS_TITLE": "Erro na substituição",
  "REPLACE_IN_FILES_ERRORS": "Os seguintes arquivos não foram modificados porque eles foram alterados antes da busca ou não puderam ser escritos.",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "Erro ao receber informações de atualização",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "Houve um problema ao obter informações sobre a última atualização do servidor. Por favor, certifique-se de estar conectado à Internet e tente novamente.",
  "NEW_FILE_FILTER": "Adicionar filtro…",
  "CLEAR_FILE_FILTER": "Limpar filtro de arquivos",
  "NO_FILE_FILTER": "Nenhum filtro de arquivos",
  "EXCLUDE_FILE_FILTER": "Excetua {0}",
  "EDIT_FILE_FILTER": "Editar…",
  "FILE_FILTER_DIALOG": "Editar filtro",
  "FILE_FILTER_INSTRUCTIONS": "Exclui dos resultados os arquivos e pastas que correspondam a qualquer das strings, substrings ou <a href='{0}' title='{0}'>wildcards</a> abaixo. Insira cada string em uma linha separada.",
  "FILTER_NAME_PLACEHOLDER": "Nome desta configuração de filtro (opcional)",
  "FILTER_NAME_REMAINING": "{0} caracteres restantes",
  "FILE_FILTER_CLIPPED_SUFFIX": "e outros {0}",
  "FILTER_COUNTING_FILES": "Contando arquivos…",
  "FILTER_FILE_COUNT": "Permite {0} de {1} arquivos {2}",
  "FILTER_FILE_COUNT_ALL": "Permite todos os {0} arquivos {1}",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "Quick Edit não disponível para posição atual do cursor",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "Quick Edit CSS: posicione o cursor no nome de uma única classe",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "Quick Edit CSS: atributo class incompleto",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "Quick Edit CSS: atributo id incompleto",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "Quick Edit CSS: posicione cursor em tag, class ou id",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "Quick Edit Função Timing de CSS: sintaxe inválida",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "Quick Edit JS: posicione cursor no nome de uma função",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "Quick Docs não disponível para a posição atual do cursor",
  "PROJECT_LOADING": "Carregando…",
  "UNTITLED": "Sem título",
  "WORKING_FILES": "Arquivos abertos",
  "TOP": "Início",
  "BOTTOM": "Fim",
  "LEFT": "Esquerda",
  "RIGHT": "Direita",
  "CMD_SPLITVIEW_NONE": "Sem divisão",
  "CMD_SPLITVIEW_VERTICAL": "Divisão vertical",
  "CMD_SPLITVIEW_HORIZONTAL": "Divisão horizontal",
  "SPLITVIEW_MENU_TOOLTIP": "Divida o editor verticalmente ou horizontalmente",
  "GEAR_MENU_TOOLTIP": "Configurar conjunto de trabalho",
  "SPLITVIEW_INFO_TITLE": "Já está aberto",
  "SPLITVIEW_MULTIPANE_WARNING": "O arquivo já está aberto em outro painel. {APP_NAME} em breve irá suportar a abertura de um mesmo arquivo em mais de um painel. Até lá, o arquivo será mostrado no painel onde já está aberto.<br /><br />(Você irá ver esta mensagem apenas uma vez.)",
  "STATUSBAR_CURSOR_POSITION": "Linha {0}, Coluna {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": " — {0} coluna selecionada",
  "STATUSBAR_SELECTION_CH_PLURAL": " — {0} colunas selecionadas",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " — {0} linha selecionada",
  "STATUSBAR_SELECTION_LINE_PLURAL": " — {0} linhas selecionadas",
  "STATUSBAR_SELECTION_MULTIPLE": " — {0} seleções",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "Clique para alterar a indentação para espaços",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "Clique para alterar a indentação para tabulação",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "Clique para alterar o número de espaços usados ao indentar",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "Clique para alterar a largura do caractere de tabulação",
  "STATUSBAR_SPACES": "Espaços:",
  "STATUSBAR_TAB_SIZE": "Tamanho da tabulação:",
  "STATUSBAR_LINE_COUNT_SINGULAR": "— {0} linha",
  "STATUSBAR_LINE_COUNT_PLURAL": "— {0} linhas",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "Extensões desativadas",
  "STATUSBAR_INSERT": "INS",
  "STATUSBAR_OVERWRITE": "OVR",
  "STATUSBAR_INSOVR_TOOLTIP": "Clique para alternar o cursor entre os modos Insert (INS) e Overwrite (OVR)",
  "STATUSBAR_LANG_TOOLTIP": "Clique para alterar o tipo de arquivo",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. Clique para abrir/fechar o painel de relatórios.",
  "STATUSBAR_DEFAULT_LANG": "(padrão)",
  "STATUSBAR_SET_DEFAULT_LANG": "Definir como padrão para arquivos .{0}.",
  "STATUSBAR_ENCODING_TOOLTIP": "Selecione a codificação",
  "ERRORS_PANEL_TITLE_MULTIPLE": "Problemas de {0}",
  "SINGLE_ERROR": "Um problema de {0}",
  "MULTIPLE_ERRORS": "{1} problemas de {0}",
  "NO_ERRORS": "Nenhum problema de {0} encontrado - bom trabalho!",
  "NO_ERRORS_MULTIPLE_PROVIDER": "Nenhum problema encontrado - bom trabalho!",
  "LINT_DISABLED": "A análise de código está desativada",
  "NO_LINT_AVAILABLE": "Nenhum analisador de código disponível para {0}",
  "NOTHING_TO_LINT": "Nada para analisar",
  "LINTER_TIMED_OUT": "{0} expirou após esperar durante {1} ms",
  "LINTER_FAILED": "{0} terminou com o erro: {1}",
  "FILE_MENU": "Arquivo",
  "CMD_FILE_NEW_UNTITLED": "Novo",
  "CMD_FILE_NEW": "Novo arquivo",
  "CMD_FILE_DUPLICATE": "Duplicar",
  "CMD_FILE_DUPLICATE_FILE": "Arquivo Duplicado",
  "CMD_FILE_DOWNLOAD_PROJECT": "Baixar projeto",
  "CMD_FILE_DOWNLOAD": "Download",
  "CMD_FILE_CUT": "Recortar",
  "CMD_FILE_COPY": "Copiar",
  "CMD_FILE_COPY_PATH": "Copiar caminho",
  "CMD_FILE_PASTE": "Colar",
  "CMD_PROJECT_NEW": "Novo projeto",
  "CMD_FILE_NEW_FOLDER": "Nova pasta",
  "CMD_FILE_OPEN": "Abrir…",
  "CMD_RECENT_FILES_OPEN": "Arquivos recentes…",
  "CMD_ADD_TO_WORKING_SET": "Adicionar ao conjunto de trabalho",
  "CMD_OPEN_DROPPED_FILES": "Abrir arquivos largados",
  "CMD_OPEN_FOLDER": "Abrir pasta…",
  "CMD_FILE_CLOSE": "Fechar",
  "CMD_FILE_CLOSE_ALL": "Fechar todos",
  "CMD_FILE_CLOSE_LIST": "Fechar lista",
  "CMD_FILE_CLOSE_OTHERS": "Fechar outros",
  "CMD_FILE_CLOSE_ABOVE": "Fechar outros acima",
  "CMD_FILE_CLOSE_BELOW": "Fechar outros abaixo",
  "CMD_FILE_SAVE": "Salvar arquivo",
  "CMD_FILE_SAVE_ALL": "Salvar todos",
  "CMD_FILE_SAVE_AS": "Salvar como…",
  "CMD_LIVE_FILE_PREVIEW": "Live Preview",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "Habilitar Live Preview experimental",
  "CMD_RELOAD_LIVE_PREVIEW": "Forçar recarregamento do Live Preview",
  "CMD_PROJECT_SETTINGS": "Configurações do projeto…",
  "CMD_FILE_RENAME": "Renomear",
  "CMD_FILE_DELETE": "Excluir",
  "CMD_INSTALL_EXTENSION": "Instalar extensão…",
  "CMD_EXTENSION_MANAGER": "Gerenciador de extensões…",
  "CMD_FILE_REFRESH": "Atualizar árvore de arquivos",
  "CMD_FILE_SHOW_FOLDERS_FIRST": "Classifique as pastas primeiro",
  "CMD_QUIT": "Fechar",
  "CMD_EXIT": "Sair",
  "EDIT_MENU": "Editar",
  "CMD_UNDO": "Desfazer",
  "CMD_REDO": "Refazer",
  "CMD_CUT": "Recortar",
  "CMD_COPY": "Copiar",
  "CMD_PASTE": "Colar",
  "CMD_SELECT_ALL": "Selecionar tudo",
  "CMD_SELECT_LINE": "Selecionar linha",
  "CMD_SPLIT_SEL_INTO_LINES": "Dividir seleção em linhas",
  "CMD_ADD_CUR_TO_NEXT_LINE": "Adicionar cursor à linha seguinte",
  "CMD_ADD_CUR_TO_PREV_LINE": "Adicionar cursor à linha anterior",
  "CMD_INDENT": "Indentar",
  "CMD_UNINDENT": "Diminuir indentação",
  "CMD_DUPLICATE": "Duplicar",
  "CMD_DELETE_LINES": "Excluir linha",
  "CMD_COMMENT": "Alternar comentário de linha",
  "CMD_BLOCK_COMMENT": "Alternar comentário de bloco",
  "CMD_LINE_UP": "Mover linha para cima",
  "CMD_LINE_DOWN": "Mover linha para baixo",
  "CMD_OPEN_LINE_ABOVE": "Abrir linha acima",
  "CMD_OPEN_LINE_BELOW": "Abrir linha abaixo",
  "CMD_TOGGLE_CLOSE_BRACKETS": "Fechar chaves automaticamente",
  "CMD_SHOW_CODE_HINTS": "Mostrar dicas de código",
  "CMD_BEAUTIFY_CODE": "Código de Embelezamento",
  "CMD_BEAUTIFY_CODE_ON_SAVE": "Embelezar o código após salvar",
  "FIND_MENU": "Localizar",
  "CMD_FIND": "Localizar",
  "CMD_FIND_NEXT": "Localizar próximo",
  "CMD_FIND_PREVIOUS": "Localizar anterior",
  "CMD_FIND_ALL_AND_SELECT": "Localizar tudo e selecionar",
  "CMD_ADD_NEXT_MATCH": "Adicionar próximo resultado à seleção",
  "CMD_SKIP_CURRENT_MATCH": "Pular e adicionar próximo resultado",
  "CMD_FIND_IN_FILES": "Localizar em arquivos",
  "CMD_FIND_IN_SUBTREE": "Localizar em…",
  "CMD_REPLACE": "Substituir",
  "CMD_REPLACE_IN_FILES": "Substituir em arquivos",
  "CMD_REPLACE_IN_SUBTREE": "Substituir em…",
  "VIEW_MENU": "Visualizar",
  "CMD_HIDE_SIDEBAR": "Esconder barra lateral",
  "CMD_SHOW_SIDEBAR": "Mostrar barra lateral",
  "CMD_TOGGLE_SIDEBAR": "Alternar barra lateral",
  "CMD_TOGGLE_PANELS": "Alternar painéis",
  "CMD_TOGGLE_PURE_CODE": "Sem distrações",
  "CMD_ZOOM_UI": "IU de zoom e fontes",
  "CMD_ZOOM_IN": "Mais Zoom",
  "CMD_ZOOM_OUT": "Reduzir o zoom",
  "CMD_INCREASE_FONT_SIZE": "Aumentar tamanho da fonte",
  "CMD_DECREASE_FONT_SIZE": "Diminuir tamanho da fonte",
  "CMD_RESTORE_FONT_SIZE": "Restaurar tamanho da fonte",
  "CMD_SCROLL_LINE_UP": "Rolar linha para cima",
  "CMD_SCROLL_LINE_DOWN": "Rolar linha para baixo",
  "CMD_TOGGLE_LINE_NUMBERS": "Números de linha",
  "CMD_TOGGLE_ACTIVE_LINE": "Destacar linha ativa",
  "CMD_TOGGLE_WORD_WRAP": "Quebra automática de linha",
  "CMD_LIVE_HIGHLIGHT": "Destacar Live Preview",
  "CMD_VIEW_TOGGLE_INSPECTION": "Analisar arquivos ao salvar",
  "CMD_WORKINGSET_SORT_BY_ADDED": "Ordenar por Data de Adição",
  "CMD_WORKINGSET_SORT_BY_NAME": "Ordenar por Nome",
  "CMD_WORKINGSET_SORT_BY_TYPE": "Ordenar por Tipo",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "Ordenação automática",
  "CMD_THEMES": "Temas…",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "Fechar pesquisa automaticamente",
  "NAVIGATE_MENU": "Navegar",
  "CMD_QUICK_OPEN": "Abertura rápida",
  "CMD_GOTO_LINE": "Ir para linha",
  "CMD_GOTO_DEFINITION": "Encontrar definição",
  "CMD_GOTO_DEFINITION_PROJECT": "Definição de busca rápida no projeto",
  "CMD_GOTO_FIRST_PROBLEM": "Ir ao primeiro erro/aviso",
  "CMD_TOGGLE_QUICK_EDIT": "Edição rápida",
  "CMD_TOGGLE_QUICK_DOCS": "Documentação rápida",
  "CMD_QUICK_EDIT_PREV_MATCH": "Resultado anterior",
  "CMD_QUICK_EDIT_NEXT_MATCH": "Resultado seguinte",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "Nova regra",
  "CMD_NEXT_DOC": "Documento seguinte",
  "CMD_PREV_DOC": "Documento anterior",
  "CMD_NAVIGATE_BACKWARD": "Navegar para trás",
  "CMD_NAVIGATE_FORWARD": "Navegar para a frente",
  "CMD_NEXT_DOC_LIST_ORDER": "Documento seguinte na lista",
  "CMD_PREV_DOC_LIST_ORDER": "Documento anterior na lista",
  "CMD_SHOW_IN_TREE": "Mostrar na árvore de arquivos",
  "CMD_SHOW_IN_EXPLORER": "Mostrar no Explorer",
  "CMD_SHOW_IN_FINDER": "Mostrar no Finder",
  "CMD_SHOW_IN_OS": "Mostrar no sistema operacional",
  "CMD_SWITCH_PANE_FOCUS": "Mudar o foco do painel",
  "CMD_OPEN_VFS": "Abrir sistema de arquivos virtuais",
  "CMD_OPEN_VIRTUAL_SERVER": "Abrir servidor virtual",
  "HELP_MENU": "Ajuda",
  "CMD_CHECK_FOR_UPDATE": "Verificar atualizações",
  "CMD_HOW_TO_USE_BRACKETS": "Como usar o {APP_NAME}",
  "CMD_SUPPORT": "Ajuda do {APP_NAME}",
  "CMD_SUGGEST": "Sugira um recurso",
  "CMD_RELEASE_NOTES": "Notas da versão",
  "CMD_GET_INVOLVED": "Envolva-se",
  "CMD_SHOW_EXTENSIONS_FOLDER": "Mostrar pasta de extensões",
  "CMD_HEALTH_DATA_STATISTICS": "Relatório de saúde do Brackets",
  "CMD_HOMEPAGE": "Página inicial do {APP_NAME}",
  "CMD_TWITTER": "{TWITTER_NAME} no Twitter",
  "CMD_ABOUT": "Sobre o {APP_TITLE}",
  "CMD_OPEN_PREFERENCES": "Abrir arquivo de configurações",
  "CMD_OPEN_KEYMAP": "Abrir mapa de teclas do usuário",
  "EXPERIMENTAL_BUILD": "versão experimental",
  "RELEASE_BUILD": "versão",
  "DEVELOPMENT_BUILD": "versão de desenvolvimento",
  "PRERELEASE_BUILD": "compilação de pré-lançamento",
  "RELOAD_FROM_DISK": "Recarregar do disco",
  "KEEP_CHANGES_IN_EDITOR": "Manter alterações no editor",
  "CLOSE_DONT_SAVE": "Fechar (não salvar)",
  "RELAUNCH_CHROME": "Abrir Chrome novamente",
  "ABOUT": "Sobre",
  "CLOSE": "Fechar",
  "ABOUT_TEXT_LINE1": "Liberar {VERSION_MAJOR}.{VERSION_MINOR} {BUILD_TYPE} {VERSION}",
  "ABOUT_TEXT_BUILD_TIMESTAMP": "construir carimbo de data/hora:",
  "ABOUT_TEXT_LINE3": "Bibliotecas de terceiros que usamos – <a href='https://github.com/phcode-dev/phoenix/tree/main/src/thirdparty/licences'>Licenças e Atribuições</a> .",
  "ABOUT_TEXT_LINE4": "Documentação e fonte em <a href='https://github.com/phcode-dev/phoenix/'>https://github.com/phcode-dev/phoenix/</a>",
  "ABOUT_TEXT_LINE5": "Feito com ❤ e JavaScript por:",
  "ABOUT_TEXT_LINE6": "Muitas pessoas (mas estamos tendo problemas para carregar esses dados agora).",
  "ABOUT_TEXT_MDN_DOCS": "MDN Docs e logo gráfico MDN são licenciados sob a licença Creative Commons Attribution, <a href='{MDN_DOCS_LICENSE}'>CC-BY-SA 2.5 Unported</a>.",
  "UPDATE_NOTIFICATION_TOOLTIP": "Há uma nova versão do {APP_NAME} disponível! Clique aqui para mais detalhes.",
  "UPDATE_AVAILABLE_TITLE": "Atualização Disponível",
  "UPDATE_RELOAD_APP": "Feche todas as janelas/guias do {APP_NAME} e reabra o {APP_NAME} para obter a versão mais recente.",
  "UPDATE_MESSAGE": "Ei, há uma nova versão do {APP_NAME} disponível. Aqui estão alguns dos novos recursos:",
  "GET_IT_NOW": "Obtenha agora!",
  "PROJECT_SETTINGS_TITLE": "Configurações do projeto para: {0}",
  "PROJECT_SETTING_BASE_URL": "URL base do Live Preview",
  "PROJECT_SETTING_BASE_URL_HINT": "Para usar um servidor local, insira uma URL como http://localhost:8000/",
  "BASEURL_ERROR_INVALID_PROTOCOL": "O protocolo {0} não é suportado pelo Live Preview&mdash;por favor, use http: ou https: .",
  "BASEURL_ERROR_SEARCH_DISALLOWED": "A URL base não pode conter parâmetros de busca como \"{0}\".",
  "BASEURL_ERROR_HASH_DISALLOWED": "A URL base não pode conter hashes como \"{0}\".",
  "BASEURL_ERROR_INVALID_CHAR": "Caracteres especiais como '{0}' devem ser codificados para URL encoding.",
  "BASEURL_ERROR_UNKNOWN_ERROR": "Erro desconhecido ao parsear URL base",
  "EMPTY_VIEW_HEADER": "<em>Abra um arquivo enquanto este painel possui o foco</em>",
  "FLIPVIEW_BTN_TOOLTIP": "Virar esta visualização para o painel {0}",
  "CURRENT_THEME": "Tema atual",
  "USE_THEME_SCROLLBARS": "Usar barra de rolagens do tema",
  "FONT_SIZE": "Tamanho da fonte",
  "FONT_FAMILY": "Família da fonte",
  "THEMES_SETTINGS": "Configurações de temas",
  "THEMES_ERROR": "Erro de temas",
  "THEMES_ERROR_CANNOT_APPLY": "Não foi possível aplicar o tema devido a um erro.",
  "BUTTON_NEW_RULE": "Nova regra",
  "INSTALL": "Instalar",
  "APPLY": "Aplicar",
  "UPDATE": "Atualizar",
  "REMOVE": "Remover",
  "DISABLE": "Desabilitar",
  "ENABLE": "Habilitar",
  "OVERWRITE": "Sobrescrever",
  "CANT_DROP_ZIP": "A eliminação de arquivos zip será suportada em breve...",
  "CANT_REMOVE_DEV": "Extensões na pasta \"dev\" devem ser excluídas manualmente.",
  "CANT_UPDATE": "A atualização não é compatível com esta versão do {APP_NAME}.",
  "CANT_UPDATE_DEV": "Extensões na pasta \"dev\" não podem ser atualizadas automaticamente.",
  "INSTALL_EXTENSION_TITLE": "Instalar extensão",
  "UPDATE_EXTENSION_TITLE": "Atualizar extensão",
  "INSTALL_EXTENSION_LABEL": "URL da extensão",
  "INSTALL_EXTENSION_HINT": "URL do zip ou repositório GitHub da extensão",
  "INSTALLING_FROM": "Instalando extensão de {0}…",
  "INSTALL_SUCCEEDED": "Instalada com sucesso!",
  "INSTALL_FAILED": "Falha na instalação.",
  "CANCELING_INSTALL": "Cancelando…",
  "CANCELING_HUNG": "Cancelar a instalação está demorando muito. Um erro interno deve ter ocorrido.",
  "INSTALL_CANCELED": "Instalação cancelada.",
  "VIEW_COMPLETE_DESCRIPTION": "Ver descrição completa",
  "VIEW_TRUNCATED_DESCRIPTION": "Ver descrição reduzida",
  "SORT_EXTENSION_METHOD": "Classifique as extensões usando downloadCount ou publishDate",
  "INVALID_ZIP_FILE": "O conteúdo baixado não é um arquivo zip válido.",
  "MISSING_PACKAGE_JSON": "O pacote não tem arquivo package.json.",
  "INVALID_PACKAGE_JSON": "O arquivo package.json não é válido (o erro foi: {0}).",
  "MISSING_PACKAGE_NAME": "O arquivo package.json não especifica um nome de pacote.",
  "BAD_PACKAGE_NAME": "{0} é um nome de pacote inválido.",
  "MISSING_PACKAGE_VERSION": "O arquivo package.json não especifica uma versão de pacote.",
  "INVALID_VERSION_NUMBER": "O número da versão do pacote ({0}) é inválido.",
  "INVALID_BRACKETS_VERSION": "A string de compatibilidade com o {APP_NAME} ({0}) é inválida.",
  "DISALLOWED_WORDS": "As palavras ({1}) não são permitidas no campo {0}.",
  "NPM_INSTALL_FAILED": "Falha no comando de instalação do npm: {0}",
  "API_NOT_COMPATIBLE": "A extensão não é compatível com esta versão do {APP_NAME}. Está instalada na sua pasta de extensões desativadas.",
  "MISSING_MAIN": "O pacote não tem um arquivo main.js.",
  "EXTENSION_ALREADY_INSTALLED": "Instalar este pacote irá substituir uma extensão instalada anteriormente. Sobrescrever a exensão antiga?",
  "EXTENSION_SAME_VERSION": "Este pacote está na mesma versão que o instalado atualmente. Sobrescrever a instalação existente?",
  "EXTENSION_OLDER_VERSION": "Este pacote está na versão {0}, que é mais antiga que a instalada atualmente ({1}). Sobrescrever a instalação existente?",
  "DOWNLOAD_ID_IN_USE": "Erro interno: ID de download já em uso.",
  "NO_SERVER_RESPONSE": "Não foi possível conectar-se ao servidor.",
  "BAD_HTTP_STATUS": "Aquivo não encontrado no servidor (HTTP {0}).",
  "CANNOT_WRITE_TEMP": "Não foi possível salvar o download em um arquivo temporário.",
  "ERROR_LOADING": "A extensão encontrou um erro ao inicializar.",
  "MALFORMED_URL": "A URL é inválida. Por favor, verifique se você a inseriu corretamente.",
  "UNSUPPORTED_PROTOCOL": "A URL precisa ser um endereço http ou https.",
  "UNKNOWN_ERROR": "Erro interno desconhecido.",
  "EXTENSION_VERIFIED_PUBLISHER": "Este editor verificou a propriedade de {0}",
  "EXTENSION_VERIFIED_SORT": "Verificado",
  "EXTENSION_STAR": "Estrela",
  "EXTENSION_STAR_SORT": "Classificação por estrelas",
  "EXTENSION_MANAGER_TITLE": "Gerenciador de Extensões",
  "EXTENSION_MANAGER_ERROR_LOAD": "Não foi possível acessar o registro de extensões. Por favor,tente novamente mais tarde.",
  "INSTALL_EXTENSION_DRAG": "Arraste o .zip aqui ou",
  "INSTALL_EXTENSION_DROP": "Solte o .zip aqui ou",
  "INSTALL_EXTENSION_DROP_ERROR": "Instalação/atualização cancelada devido aos seguintes erros:",
  "INSTALL_FROM_URL": "Instalar a partir de URL…",
  "INSTALL_EXTENSION_VALIDATING": "Validando…",
  "EXTENSION_AUTHOR": "Autor",
  "EXTENSION_DATE": "Data",
  "EXTENSION_INCOMPATIBLE_NEWER": "Esta extensão requer uma versão mais recente do {APP_NAME}.",
  "EXTENSION_INCOMPATIBLE_OLDER": "Esta extensão atualmente só funciona com versões mais antigas do {APP_NAME}.",
  "EXTENSION_DEFAULT_FEATURE_PRESENT": "Você pode não precisar desta extensão. {APP_NAME} já tem este recurso.",
  "EXTENSION_LATEST_INCOMPATIBLE_NEWER": "A versão {0} desta extensão exige uma versão mais recente do {APP_NAME}. Mas você pode instalar a versão {1} mais antiga.",
  "EXTENSION_LATEST_INCOMPATIBLE_OLDER": "A versão {0} desta extensão funciona apenas com versões mais antigas do {APP_NAME}. Mas você pode instalar a versão {1} mais recente.",
  "EXTENSION_NO_DESCRIPTION": "Sem descrição",
  "EXTENSION_MORE_INFO": "Mais informações...",
  "EXTENSION_ERROR": "Erro na extensão",
  "EXTENSION_KEYWORDS": "Palavras-chave",
  "EXTENSION_TRANSLATED_USER_LANG": "Traduzido para {0} idiomas, incluindo o seu",
  "EXTENSION_TRANSLATED_GENERAL": "Traduzido para {0} idiomas",
  "EXTENSION_TRANSLATED_LANGS": "Essa extensão foi traduzida para os seguintes idiomas: {0}",
  "EXTENSION_INSTALLED": "Instaladas",
  "EXTENSION_UPDATE_INSTALLED": "Esta atualização foi baixada e será instalada quando você sair do {APP_NAME}.",
  "EXTENSION_SEARCH_PLACEHOLDER": "Pesquisar",
  "EXTENSION_MORE_INFO_LINK": "Mais",
  "EXTENSION_MANAGER_CREATE_EXTENSION": "+ Criar extensão",
  "EXTENSION_MANAGER_CREATE_THEME": "+ Criar tema",
  "BROWSE_EXTENSIONS": "Procurar extensões",
  "EXTENSION_MANAGER_REMOVE": "Remover extensão",
  "EXTENSION_MANAGER_REMOVE_ERROR": "Não foi possível remover uma ou mais extensões: {0}. O {APP_NAME} será encerrado mesmo assim.",
  "EXTENSION_MANAGER_UPDATE": "Atualizar extensão",
  "EXTENSION_MANAGER_UPDATE_ERROR": "Não foi possível atualizar uma ou mais extensões: {0}. O {APP_NAME} será encerrado mesmo assim.",
  "EXTENSION_MANAGER_DISABLE": "Desabilitar extensão",
  "EXTENSION_MANAGER_DISABLE_ERROR": "Não é possível desabilitar uma ou mais extensões: {0}. {APP_NAME} será encerrado mesmo assim.",
  "EXTENSION_MANAGER_THEMES_INFO": "Para <a class=\"theme_settings\">selecionar temas padrão</a> ou modificar outras configurações de tema, <a class=\"theme_settings\">clique aqui</a> .",
  "EXTENSION_MANAGER_THEMES_UNDO": "Reverter para o tema anterior",
  "MARKED_FOR_REMOVAL": "Marcada para remoção",
  "UNDO_REMOVE": "Desfazer",
  "MARKED_FOR_UPDATE": "Marcada para atualização",
  "UNDO_UPDATE": "Desfazer",
  "MARKED_FOR_DISABLING": "Marcada para desabilitação",
  "UNDO_DISABLE": "Desfazer",
  "CHANGE_AND_RELOAD_TITLE": "Alterar extensões",
  "CHANGE_AND_RELOAD_MESSAGE": "Para atualizar ou remover as extensões marcadas, o {APP_NAME} precisa ser recarregado. Você será solicitado a salvar suas alterações.",
  "REMOVE_AND_RELOAD": "Remover extensões e recarregar",
  "CHANGE_AND_RELOAD": "Alterar extensões e recarregar",
  "UPDATE_AND_RELOAD": "Atualizar extensões e recarregar",
  "DISABLE_AND_RELOAD": "Desabilitar extensões e recarregar",
  "PROCESSING_EXTENSIONS": "Processando alterações nas extensões…",
  "EXTENSION_NOT_INSTALLED": "Não foi possível remover a extensão {0} porque ela não estava instalada.",
  "NO_EXTENSIONS": "Nenhuma extensão instalada ainda.<br>Clique na aba Disponíveis acima para começar.",
  "NO_EXTENSION_MATCHES": "Nenhuma extensão corresponde à sua pesquisa.",
  "REGISTRY_SANITY_CHECK_WARNING": "NOTA: Estas extensões podem vir de diferentes autores e não do próprio {APP_NAME}. Extensões não são revisadas e tem prilégios locais totais. Tenha cuidado ao instalar extensões de fontes desconhecidas.",
  "EXTENSIONS_INSTALLED_TITLE": "Instaladas",
  "EXTENSIONS_DEFAULT_TITLE": "Padrão",
  "EXTENSIONS_AVAILABLE_TITLE": "Disponíveis",
  "EXTENSIONS_THEMES_TITLE": "Temas",
  "EXTENSIONS_UPDATES_TITLE": "Atualizações",
  "EXTENSIONS_LAST_UPDATED": "Ultima atualização",
  "EXTENSIONS_DOWNLOADS": "Transferências",
  "INLINE_EDITOR_NO_MATCHES": "Nenhum resultado.",
  "INLINE_EDITOR_HIDDEN_MATCHES": "Todas as correspondências foram ocultadas. Expanda os arquivos listados na direita para ver os resultados.",
  "CSS_QUICK_EDIT_NO_MATCHES": "Nenhuma regra CSS corresponde à sua seleção.<br> Clique em \"Nova regra\" para criar uma.",
  "CSS_QUICK_EDIT_NO_STYLESHEETS": "Seu projeto não tem uma folha de estilos.<br>Crie uma para adicionar regras CSS.",
  "IMAGE_VIEWER_LARGEST_ICON": "maior",
  "UNIT_PIXELS": "pixels",
  "DEBUG_MENU": "Depurar",
  "ERRORS": "Erros",
  "CMD_SHOW_DEV_TOOLS": "Mostrar ferramentas do desenvolvedor",
  "CMD_REFRESH_WINDOW": "Recarregar com extensões",
  "CMD_LOAD_CURRENT_EXTENSION": "Carregar projeto como extensão",
  "CMD_RELOAD_CURRENT_EXTENSION": "Recarregar projeto como extensão",
  "CMD_UNLOAD_CURRENT_EXTENSION": "Descarregar projeto como extensão",
  "CMD_RELOAD_WITHOUT_USER_EXTS": "Recarregar sem extensões",
  "CMD_NEW_BRACKETS_WINDOW": "Nova janela do {APP_NAME}",
  "CMD_LAUNCH_SCRIPT_MAC": "Instalar atalhos da linha de comando",
  "CMD_SWITCH_LANGUAGE": "Alterar idioma",
  "CMD_RUN_UNIT_TESTS": "Executar testes",
  "CMD_SHOW_PERF_DATA": "Mostrar dados de desempenho",
  "CMD_ENABLE_LOGGING": "Ativar registros detalhados",
  "CMD_ENABLE_LIVE_PREVIEW_LOGS": "Registros de visualização ao vivo",
  "CMD_OPEN_BRACKETS_SOURCE": "Abrir local do Brackets",
  "CREATING_LAUNCH_SCRIPT_TITLE": "Atalho de {APP_NAME} na linha de comando",
  "ERROR_CREATING_LAUNCH_SCRIPT": "Um erro ocorreu enquanto um atalho de linha de comando estava sendo instalado. Por favor, tente <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting'>estas sugestões de resolução</a>.<br/><br/>Razão: {0}",
  "ERROR_CLTOOLS_RMFAILED": "Não foi possível remover o link simbólico existente <code>/usr/local/bin/brackets</code> .",
  "ERROR_CLTOOLS_MKDIRFAILED": "Não foi possível criar o diretório <code>/usr/local/bin</code> .",
  "ERROR_CLTOOLS_LNFAILED": "Não foi possível criar o link simbólico <code>/usr/local/bin/brackets</code> .",
  "ERROR_CLTOOLS_SERVFAILED": "Erro interno.",
  "ERROR_CLTOOLS_NOTSUPPORTED": "Atalhos de linha de comando não são suportados por este Sistema Operacional.",
  "LAUNCH_SCRIPT_CREATE_SUCCESS": "Sucesso! Agora você poderá usar de maneira confortável a linha de comando para o {APP_NAME} !! <code>brackets myFile.txt</code> para abrir um arquivo ou <code>brackets myFolder</code> para alternar em projetos. <br/><br/><a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments'>Aprenda mais</a> como usar {APP_NAME} pela linha de comando.",
  "ERROR_LOADING_EXTENSION": "Erro ao carregar a extensão",
  "ERROR_NO_EXTENSION_PACKAGE": "Arquivo <code>package.json</code> não detectado no projeto atual. O projeto atual é uma extensão {APP_NAME} válida?</br> Veja <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>este link</a> para mais detalhes.",
  "ERROR_INVALID_EXTENSION_PACKAGE": "O arquivo <code>package.json</code> é um JSON inválido.</br> Veja <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>este link</a> para mais detalhes.",
  "ERROR_INVALID_EXTENSION_PACKAGE_FIELDS": "Campos obrigatórios ausentes em <code>package.json</code> : [{0}]</br> Veja <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>este link</a> para mais detalhes.",
  "LANGUAGE_TITLE": "Alterar idioma",
  "LANGUAGE_MESSAGE": "Idioma:",
  "LANGUAGE_SUBMIT": "Reiniciar {APP_NAME}",
  "LANGUAGE_CANCEL": "Cancelar",
  "LANGUAGE_SYSTEM_DEFAULT": "Padrão do sistema",
  "HEALTH_DATA_NOTIFICATION": "Preferências do relatório de saúde",
  "HEALTH_FIRST_POPUP_TITLE": "Relatório de saúde do {APP_NAME}",
  "HEALTH_DATA_DO_TRACK": "Compartilhe informações anônimas sobre como eu uso o {APP_NAME}",
  "HEALTH_DATA_NOTIFICATION_MESSAGE": "Para melhorar o {APP_NAME}, enviamos periodicamente estatísticas limitadas e <strong>pseudônimas</strong> e relatórios de erros para phcode.dev sobre como você usa o {APP_NAME}. Essas informações ajudam a priorizar recursos, encontrar bugs e detectar problemas de usabilidade, protegendo sua privacidade.<br><br> Você pode ver seus dados ou optar por não compartilhar dados selecionando <strong>Ajuda &gt; Relatório de integridade</strong> .<br><br>",
  "HEALTH_DATA_PREVIEW": "Relatório de saúde do {APP_NAME}",
  "HEALTH_DATA_PREVIEW_INTRO": "<p>Para melhorar o {APP_NAME}, enviamos periodicamente estatísticas limitadas e <strong>pseudônimas</strong> e relatórios de erros para phcode.dev sobre como você usa o {APP_NAME}. Essas informações ajudam a priorizar recursos, encontrar bugs e detectar problemas de usabilidade.</p><p> Abaixo está uma prévia dos dados que serão enviados em seu próximo Relatório de Saúde <em>se</em> estiver habilitado. (Consulte também o console do desenvolvedor para obter os logs de erro marcados como &#39;Erro crítico detectado&#39;.)</p>",
  "INLINE_TIMING_EDITOR_TIME": "Tempo",
  "INLINE_TIMING_EDITOR_PROGRESSION": "Progresso",
  "BEZIER_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd><kbd>←</kbd><kbd>→</kbd> Move o ponto selecionado<br><kbd class='text'>Shift</kbd> Move dez unidades<br><kbd class='text'>Tab</kbd> Troca pontos",
  "STEPS_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd> Aumenta ou diminui passos<br><kbd>←</kbd><kbd>→</kbd> 'Start' ou 'End'",
  "INLINE_TIMING_EDITOR_INVALID": "O valor antigo <code>{0}</code> não é válido, então a função exibida foi alterada para <code>{1}</code>. O documento será atualizado com a primeira edição.",
  "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP": "Cor atual",
  "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP": "Cor original",
  "COLOR_EDITOR_RGBA_BUTTON_TIP": "Formato RGBa",
  "COLOR_EDITOR_HEX_BUTTON_TIP": "Formato Hex",
  "COLOR_EDITOR_HSLA_BUTTON_TIP": "Formato HSLa",
  "COLOR_EDITOR_0X_BUTTON_TIP": "Formato Hexagonal (0x)",
  "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR": "{0} (usada {1} vez)",
  "COLOR_EDITOR_USED_COLOR_TIP_PLURAL": "{0} (usada {1} vezes)",
  "CMD_JUMPTO_DEFINITION": "Pular para definição",
  "CMD_SHOW_PARAMETER_HINT": "Mostrar dicas de parâmetro",
  "NO_ARGUMENTS": "<nenhum parâmetro>",
  "DETECTED_EXCLUSION_TITLE": "Problema de inferência de arquivo JavaScript",
  "DETECTED_EXCLUSION_INFO": "Brackets enfrentou um problema ao processar: <span class='dialog-filename'>{0}</span>.<br><br>Este arquivo não será mais processado para dicas de código, definições ou edição rápida. Para reverter, abra <code>.brackets.json</code> em seu projeto e edite <code>jscodehints.detectedExclusions</code>.<br><br>Este provavelmente é um bug do Brackets. Se você pode fornecer uma cópia deste arquivo, por favor <a href='https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue'>registre um bug</a> com um link para o arquivo mencionado aqui.",
  "CMD_REFACTOR": "Refatorar",
  "CMD_EXTRACTTO_VARIABLE": "Extrair para variável",
  "CMD_EXTRACTTO_FUNCTION": "Extrair para função",
  "ERROR_TERN_FAILED": "Não foi possível obter dados de Tern",
  "ERROR_EXTRACTTO_VARIABLE_NOT_VALID": "A seleção não forma uma expressão",
  "ERROR_EXTRACTTO_FUNCTION_NOT_VALID": "O bloco selecionado deve representar um conjunto de instruções ou uma expressão",
  "ERROR_EXTRACTTO_VARIABLE_MULTICURSORS": "Extrair para variável não funciona em multicursores",
  "ERROR_EXTRACTTO_FUNCTION_MULTICURSORS": "Extrair para função não funciona em multicursores",
  "EXTRACTTO_FUNCTION_SELECT_SCOPE": "Escolha o escopo de destino",
  "EXTRACTTO_VARIABLE_SELECT_EXPRESSION": "Selecione uma expressão",
  "CMD_REFACTORING_RENAME": "Renomear",
  "CMD_REFACTORING_TRY_CATCH": "Envolva em Try Catch",
  "CMD_REFACTORING_CONDITION": "Embrulhar em Condição",
  "CMD_REFACTORING_GETTERS_SETTERS": "Criar getters/setters",
  "CMD_REFACTORING_ARROW_FUNCTION": "Converter para função de seta",
  "DESCRIPTION_CODE_REFACTORING": "Ativar/desativar a refatoração de código JavaScript",
  "ERROR_TRY_CATCH": "Selecione um código válido para encapsular em um bloco Try-catch",
  "ERROR_WRAP_IN_CONDITION": "Selecione um código válido para envolver em um bloco de condição",
  "ERROR_ARROW_FUNCTION": "Coloque o cursor dentro de uma expressão de função",
  "ERROR_GETTERS_SETTERS": "Coloque o cursor em um membro de uma expressão de objeto",
  "ERROR_RENAME_MULTICURSOR": "Não é possível renomear ao usar vários cursores",
  "ERROR_RENAME_QUICKEDIT": "Não é possível renomear este identificador, pois ele é referenciado em outro lugar fora desta função",
  "ERROR_RENAME_GENERAL": "Não é possível renomear o texto selecionado",
  "JSHINT_NAME": "JSHintName",
  "CMD_ENABLE_QUICK_VIEW": "Quick View ao passar o mouse",
  "CMD_ENABLE_SELECTION_VIEW": "Visualização de seleção",
  "TOOLTIP_CLICK_TO_EDIT_COLOR": "Clique aqui para editar a cor",
  "CMD_TOGGLE_RECENT_PROJECTS": "Projetos Recentes",
  "DOCS_MORE_LINK": "Leia mais",
  "COLLAPSE_ALL": "Dobrar Tudo",
  "EXPAND_ALL": "Expandir Tudo",
  "COLLAPSE_CURRENT": "Dobrar Posição Atual",
  "EXPAND_CURRENT": "Expandir Posição Atual",
  "RECENT_FILES_DLG_HEADER": "Arquivos recentes",
  "RECENT_FILES_DLG_CLEAR_BUTTON_LABEL": "Claro",
  "RECENT_FILES_DLG_CLEAR_BUTTON_TITLE": "Limpar arquivos que não estão no conjunto de trabalho",
  "RECOVER_UNSAVED_FILES_TITLE": "Recuperar arquivos não salvos?",
  "RECOVER_UNSAVED_FILES_MESSAGE": "Restaurar arquivos não salvos da sessão anterior?",
  "DESCRIPTION_CLOSE_BRACKETS": "verdadeiro (true) para fechar chaves, colchetes e parênteses automaticamente",
  "DESCRIPTION_CLOSE_OTHERS_ABOVE": "falso (false) para remover  \"Fechar outros acima\" do menu de contexto Arquivos abertos",
  "DESCRIPTION_CLOSE_OTHERS_BELOW": "falso (false) para remover \"Fechar outros abaixo\" do menu de contexto Arquivos abertos",
  "DESCRIPTION_CLOSE_OTHERS": "falso (false) para remover \"Fechar outros\" do menu de contexto Arquivos abertos",
  "DESCRIPTION_CLOSE_TAGS": "Definir opções de fechamento de tags",
  "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS": "Uma matriz de tags não deve ser automaticamente fechada",
  "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING": "Fechar > quando a abertura da tag for digitada",
  "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING": "Fechar / quando o fechamento da tag for digitada",
  "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS": "Um vetor de tags terá uma linha em branco entre as tags quando for aberta",
  "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD": "verdadeiro (true) para sempre gerar marcadores de agrupamento quando o nível de identação mudar",
  "DESCRIPTION_CODE_FOLDING_ENABLED": "verdadeiro (true) para habilitar o agrupamento de código",
  "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER": "verdadeiro (true) para fazer que os marcadores de agrupamento de seção visíveis somente quando o cursor sai da área de edição pelo painel da esquerda",
  "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL": "Limite de quantos níveis de Agrupar Todos pode agrupar",
  "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE": "Mínimo de linhas antes de um ícone agrupamento de seção surgir",
  "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES": "verdadeiro (true) para lembrar o estado de uma seção agrupada caso você feche e reabra um arquivo ou projeto",
  "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE": "true para habilitar a dobra de código no texto selecionado no editor",
  "DESCRIPTION_DISABLED_DEFAULT_EXTENSIONS": "Extensões padrão que estão desativadas",
  "DESCRIPTION_ATTR_HINTS": "Habilitar/Desabilitar as sugestões de atributos HTML",
  "DESCRIPTION_CSS_PROP_HINTS": "Habilitar/Desabilitar as sugestões de atributos CSS/LESS/SCSS",
  "DESCRIPTION_JS_HINTS": "Habilitar/Desabilitar as sugestões de atributos JavaScript",
  "DESCRIPTION_JS_HINTS_TYPE_DETAILS": "Ativar/desativar detalhes do tipo de dados nas dicas de código JavaScript",
  "DESCRIPTION_PREF_HINTS": "Habilitar/Desabilitar as sugestões de preferências de código",
  "DESCRIPTION_SPECIAL_CHAR_HINTS": "Habilitar/Desabilitar as sugestões de entidades HTML",
  "DESCRIPTION_SVG_HINTS": "Habilitar/Desabilitar as sugestões de código SVG",
  "DESCRIPTION_HTML_TAG_HINTS": "Habilitar/Desabilitar as sugestões de tags HTML",
  "DESCRIPTION_URL_CODE_HINTS": "Habilitar/Desabilitar as sugestões URL dentro de HTML & CSS/LESS/SCSS",
  "DESCRIPTION_DRAG_DROP_TEXT": "Habilitar/Desabilitar funcionalidade Drag & Drop/Arrastar & Soltar",
  "DESCRIPTION_HEALTH_DATA_TRACKING": "Habilitar rastreamento de dados de saúde",
  "DESCRIPTION_HIGHLIGHT_MATCHES": "Habilitar highlighting automático de palavras ao longo do documento",
  "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN": "Destaque todas strings correspondentes ao símbolo em que o cursor se encontra (não é necessária uma seleção)",
  "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY": "Destaque somente quando um símbolo selecionado estiver completo",
  "DESCRIPTION_INSERT_HINT_ON_TAB": "verdadeiro (true) para inserir a sugestão de código ao pressionar tab",
  "DESCRIPTION_NO_HINTS_ON_DOT": "verdadeiro (true) para não mostrar automaticamente dicas para JS quando  . for digitado",
  "DESCRIPTION_JSHINT_OPTIONS": "Um objeto com as opções padrão para JSHint. Consulte o seguinte URL para todas as opções JSHint disponíveis: https://jshint.com/docs/options/",
  "DESCRIPTION_LANGUAGE": "Configurações específicas de linguagem",
  "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS": "Mapeamentos adicionais de uma extensão arquivo ao nome da linguagem",
  "DESCRIPTION_LANGUAGE_FILE_NAMES": "Mapeamentos adicionais de um nome de arquivo ao nome da linguagem",
  "DESCRIPTION_LINEWISE_COPY_CUT": "Copiar e recortar quando não houver seleção irá copiar ou recortar as linhas inteiras que possuem cursores nelas",
  "DESCRIPTION_INPUT_STYLE": "Seleciona a maneira como o CodeMirror trata a entrada e o foco. Pode ser textarea, que é o padrão, ou contenteditable, que é melhor para leitores de tela (instável)",
  "DESCRIPTION_LINTING_ENABLED": "verdadeiro (true) para habilitar a inspeção do código",
  "DESCRIPTION_ASYNC_TIMEOUT": "Tempo em milisegundos para a espera dos inspetores de código assíncronos",
  "DESCRIPTION_LINTING_PREFER": "Vetores de inspetores de código que executam primeiro",
  "DESCRIPTION_LIVE_DEV_MULTIBROWSER": "verdadeiro (true) para habilitar o Live Preview experimental",
  "DESCRIPTION_USE_PREFERED_ONLY": "verdadeiro (true) para executar somente os provedores especificados pelo linting.prefer",
  "DESCRIPTION_MAX_CODE_HINTS": "Máximo de sugestões de códigos exibidos ao mesmo tempo",
  "DESCRIPTION_PATH": "Configurações específicas para uma rota de arquivo",
  "DESCRIPTION_PROXY": "A URL do proxy utilizado para a instalação das extensões",
  "DESCRIPTION_SCROLL_PAST_END": "verdadeiro (true) para habilitar o scrolling após o fim do arquivo",
  "DESCRIPTION_SHOW_CODE_HINTS": "falso (false) para desabilitar todos as sugestões de código",
  "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING": "Mantenha o cursor visível quando houver uma seleção de texto",
  "DESCRIPTION_SHOW_LINE_NUMBERS": "verdadeiro (true) para mostrar o número das linhas na borda \"gutter\" à esquerda do editor",
  "DESCRIPTION_SMART_INDENT": "Identar automaticamente quando se criar um novo bloco",
  "DESCRIPTION_SOFT_TABS": "falso (false) para desabilitar o comportamento de \"soft tabs\"",
  "DESCRIPTION_SORT_DIRECTORIES_FIRST": "verdadeiro (true) para ordenar os diretórios no topo da árvore de projetos",
  "DESCRIPTION_SPACE_UNITS": "Quantidade de espaços utilizados na identações baseada em espaços",
  "DESCRIPTION_STATIC_SERVER_PORT": "Número da porta do servidor que será utilizada para o Live Preview",
  "DESCRIPTION_STYLE_ACTIVE_LINE": "verdadeiro (true) para ressaltar a linha atual que o cursor se encontra",
  "DESCRIPTION_TAB_SIZE": "Quantidade de espaços utilizados pelo tab",
  "DESCRIPTION_USE_TAB_CHAR": "verdadeiro (true) para usar tabs ao invés de espaços",
  "DESCRIPTION_UPPERCASE_COLORS": "verdadeiro (true) para gerar cores utilizando hexadecimais maiúsculas no editor de cores",
  "DESCRIPTION_WORD_WRAP": "Ajustar linhas que ultrapassam a largura do editor",
  "DESCRIPTION_SEARCH_AUTOHIDE": "Feche a pesquisa assim que o editor estiver focado",
  "DESCRIPTION_DETECTED_EXCLUSIONS": "Uma lista de arquivos que foram detectados problemas fazem o Tern não funcionar corretamente",
  "DESCRIPTION_INFERENCE_TIMEOUT": "Quantidade de vezes que o Tern deixará de tentar de compreender os arquivos",
  "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR": "verdadeiro (true) para mostrar os erros na barra de status",
  "DESCRIPTION_QUICK_VIEW_ENABLED": "verdadeiro (true) pra habilitar Visualização Rápida/Quick View",
  "DESCRIPTION_SELECTION_VIEW_ENABLED": "true para habilitar a exibição de seleção",
  "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW": "verdadeiro (true) para mostrar uma prévia de imagem para URLs sem extensões",
  "DESCRIPTION_NUMBER_QUICK_VIEW": "true para mostrar a visualização rápida ao passar o mouse sobre os números no editor",
  "DESCRIPTION_THEME": "Selecionar um tema para {APP_NAME}",
  "DESCRIPTION_USE_THEME_SCROLLBARS": "verdadeiro (true) para permitir barras de rolagem customizadas",
  "DESCRIPTION_LINTING_COLLAPSED": "verdadeiro (true) para agrupar painel de sugestões",
  "DESCRIPTION_FONT_FAMILY": "Alterar fonte",
  "DESCRIPTION_FONT_SIZE": "Alterar o tamanho da fonte; e.g. 13px",
  "DESCRIPTION_FIND_IN_FILES_NODE": "verdadeiro (true) para habilitar a busca baseada em nós/node",
  "DESCRIPTION_FIND_IN_FILES_INSTANT": "verdadeiro (true) para habilitar busca instantânea",
  "DESCRIPTION_FONT_SMOOTHING": "Somente para Mac: \"subpixel-antialiased\" para habilitar sub-pixel antialiasing ou \"antialiased\" para gray scale antialiasing / antialiasing com escala de cinza",
  "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW": "falso (false) para desabilitar a abertura do arquivo de preferências em tela dividida",
  "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE": "falso (false) para desabilitar a abertura do arquivo de preferências no topo do painel lateral esquerdo",
  "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED": "true para recolher painéis após o último arquivo do painel ser fechado por meio do botão fechar do cabeçalho do painel",
  "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS": "Alterne quando mostrar os botões fechar e inverter a visualização no cabeçalho.",
  "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT": "/*\n * Isso é um arquivo de somente leitura contendo as preferências suportadas\n * pelo {APP_NAME}.\n * Utilize este arquivo como referência para ajustar e modificar suas preferências no\n * arquivo \"brackets.json\" aberto em outro painel.\n * Para saber mais sobre como usar as preferências do\n * {APP_NAME}, pode consultar a página web https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences\n */",
  "DEFAULT_PREFERENCES_JSON_DEFAULT": "Padrão",
  "DESCRIPTION_PURE_CODING_SURFACE": "true para ativar o modo somente código e ocultar todos os outros elementos da interface do usuário em {APP_NAME}",
  "DESCRIPTION_INDENT_LINE_COMMENT": "true para habilitar o recuo de comentários de linha",
  "DESCRIPTION_RECENT_FILES_NAV": "Ativar/desativar a navegação em arquivos recentes",
  "DESCRIPTION_LIVEDEV_WEBSOCKET_PORT": "Porta na qual o WebSocket Server é executado para visualização ao vivo",
  "DESCRIPTION_LIVE_DEV_HIGHLIGHT_SETTINGS": "Configurações de realce de visualização ao vivo",
  "DESCRIPTION_LIVEDEV_ENABLE_REVERSE_INSPECT": "false para desabilitar a inspeção reversa da visualização ao vivo",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW": "Nada para visualizar!",
  "DESCRIPTION_LIVEDEV_NO_PREVIEW_DETAILS": "Selecione um arquivo HTML para visualizar",
  "DOWNLOAD_FAILED": "Download falhou.",
  "DOWNLOAD_COMPLETE": "Download completo!",
  "UPDATE_SUCCESSFUL": "Atualização bem sucedida!",
  "UPDATE_FAILED": "Atualização falhou!",
  "VALIDATION_FAILED": "Falha na validação!",
  "INITIALISATION_FAILED": "Inicialização falhou!",
  "CLEANUP_FAILED": "Falha na limpeza!",
  "WARNING_TYPE": "Aviso!",
  "CLICK_RESTART_TO_UPDATE": "Clique em Reiniciar para atualizar os colchetes.",
  "UPDATE_ON_NEXT_LAUNCH": "A atualização será aplicada no relançamento.",
  "GO_TO_SITE": "Acesse <a href = \"http://brackets.io/\">brackets.io</a> para tentar novamente.",
  "INTERNET_UNAVAILABLE": "Sem ligação à Internet disponível.",
  "UPDATEDIR_READ_FAILED": "O diretório de atualização não pôde ser lido.",
  "UPDATEDIR_CLEAN_FAILED": "O diretório de atualização não pôde ser limpo.",
  "INITIAL_DOWNLOAD": "Download da atualização...",
  "RETRY_DOWNLOAD": "Download falhou. Tentando novamente... Tentativa",
  "VALIDATING_INSTALLER": "Download completo! Validando o instalador...",
  "CHECKSUM_DID_NOT_MATCH": "A soma de verificação não corresponde.",
  "INSTALLER_NOT_FOUND": "Instalador não encontrado.",
  "DOWNLOAD_ERROR": "Ocorreu um erro durante o download.",
  "NETWORK_SLOW_OR_DISCONNECTED": "A rede está desconectada ou muito lenta.",
  "RESTART_BUTTON": "Reiniciar",
  "LATER_BUTTON": "Mais tarde",
  "DESCRIPTION_AUTO_UPDATE": "Ativar/desativar a atualização automática de colchetes",
  "AUTOUPDATE_ERROR": "Erro!",
  "AUTOUPDATE_IN_PROGRESS": "Uma atualização já está em andamento.",
  "NUMBER_WITH_PERCENTAGE": "{0}%",
  "CMD_FIND_RELATED_FILES": "Encontrar arquivos relacionados",
  "PHP_VERSION_INVALID": "Erro ao analisar a versão do PHP. Por favor, verifique a saída do comando “php –version”.",
  "PHP_UNSUPPORTED_VERSION": "Instale o tempo de execução do PHP7 para habilitar ferramentas relacionadas ao PHP, como dicas de código, dicas de parâmetro, salto para definição e muito mais. Versão encontrada: {0}",
  "PHP_EXECUTABLE_NOT_FOUND": "Tempo de execução do PHP não encontrado. Instale o tempo de execução do PHP7 e atualize o “executablePath” em PHP Preferences apropriadamente. Isso permite ferramentas relacionadas ao PHP, como dicas de código, dicas de parâmetro, salto para definição e muito mais.",
  "PHP_PROCESS_SPAWN_ERROR": "Código de erro {0} encontrado ao iniciar o processo PHP.",
  "PHP_SERVER_ERROR_TITLE": "Erro",
  "PHP_SERVER_MEMORY_LIMIT_INVALID": "O limite de memória fornecido é inválido. Revise as preferências do PHP para definir o valor correto.",
  "DESCRIPTION_PHP_TOOLING_CONFIGURATION": "Configurações padrão do PHP Tooling",
  "OPEN_PREFERENNCES": "Abrir preferências",
  "LANGUAGE_TOOLS_PREFERENCES": "Preferências para Ferramentas de Idioma",
  "FIND_ALL_REFERENCES": "Encontrar todas as referências",
  "REFERENCES_IN_FILES": "referências",
  "REFERENCE_IN_FILES": "referência",
  "REFERENCES_NO_RESULTS": "Nenhuma referência disponível para a posição atual do cursor",
  "CMD_FIND_DOCUMENT_SYMBOLS": "Localizar símbolos de documentos",
  "CMD_FIND_PROJECT_SYMBOLS": "Encontrar símbolos do projeto",
  "REMOTE_DEBUGGING_ENABLED": "Depuração remota habilitada no localhost:",
  "REMOTE_DEBUGGING_PORT_INVALID": "Não é possível ativar a depuração remota na porta {0}. Os números de porta devem estar entre {1} e {2}.",
  "DESCRIPTION_EXTERNAL_APPLICATION_ASSOCIATE": "Mapeamentos para extensão de arquivo para aplicativos externos. Sintaxe: \"<file_type>\": \"<default|applicationName|ApplicationPath>\", Use \"default\" para abrir arquivos no aplicativo padrão do sistema para o tipo de arquivo.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_TITLE": "Abra Arquivos Gráficos em Editores Externos.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_MSG": "Sua pasta atual tem tipos de arquivos gráficos que não são compatíveis com {APP_NAME}.<br/> Agora você pode associar tipos de arquivo específicos a editores externos. Uma vez associado, você pode abrir arquivos gráficos como .xd, .psd, .jpg, .png, .ai, .svg em seus aplicativos padrão clicando duas vezes nos arquivos na Árvore de Arquivos.<br/><br/> Por favor, clique no botão &#39;Ok&#39; para associar os tipos de arquivos gráficos com seus respectivos aplicativos padrão.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_CNF_MSG": "Os seguintes tipos de arquivo foram associados com sucesso aos aplicativos padrão.<br/> {0} Você tem a opção de alterar sua preferência sobre excluir/adicionar novas associações de tipo de arquivo em colchetes.json acessando o menu &quot;Depurar-&gt;Abrir arquivo de preferências&quot;.",
  "UNSUPPORTED_BROWSER_TITLE": "O navegador não é suportado",
  "UNSUPPORTED_BROWSER_MESSAGE": "Use um navegador moderno (lançado nos últimos 3 anos).",
  "UNSUPPORTED_BROWSER_MOBILE_TITLE": "Navegadores móveis não suportados",
  "UNSUPPORTED_BROWSER_MOBILE": "Atualmente, os navegadores para celular e tablet não são totalmente suportados. Você pode fechar esta caixa de diálogo, mas alguns recursos do Phoenix não funcionarão neste navegador.<br/><br/> Estamos trabalhando no desenvolvimento de aplicativos nativos para iOS e Android. <a href=\"https://github.com/phcode-dev/phoenix/discussions/1046\" target=\"_blank\">Junte-se à discussão aqui!</a>",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER_TITLE": "Acesso à pasta local não suportado pelo navegador",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER": "Desculpe, parece que seu navegador atual não suporta a abertura de pastas locais. Para esse recurso, recomendamos o uso do Chrome, Edge ou Opera.<br/><br/> Como alternativa, estamos trabalhando no desenvolvimento de aplicativos nativos para Windows, Mac, Linux, iOS e Android para fornecer suporte completo. <a href=\"https://github.com/phcode-dev/phoenix/discussions/1047\" target=\"_blank\">Fique atento às atualizações!</a>",
  "ATTENTION_SAFARI_USERS": "Atenção usuários do Safari",
  "ATTENTION_SAFARI_USERS_MESSAGE": "<span>O Safari exclui automaticamente os dados do site se um site não for revisitado em 7 dias. {APP_NAME} depende do armazenamento do navegador para salvar seus projetos, que podem ser removidos devido a esta política.<br/><br/> <strong>Para evitar a perda de dados</strong> , <strong>baixe</strong> seus projetos antes de fechar a guia ou fique atento aos nossos <strong>próximos aplicativos Web e nativos para Mac/iOS</strong> .</span>",
  "CANNOT_PUBLISH_LARGE_PROJECT": "Não é possível publicar um projeto grande",
  "CANNOT_PUBLISH_LARGE_PROJECT_MESSAGE": "Phoenix ainda está em alfa experimental. Ainda não ativamos a sincronização de projetos com mais de 500 arquivos.",
  "SHARE_WEBSITE": "Publicar e compartilhar site?",
  "PUBLISH": "Publicar",
  "PUBLISH_CONSENT_MESSAGE": "Visualize rapidamente as alterações e compartilhe seu site com outras pessoas. A Phoenix pode publicar este site para você em {0}. Os links publicados serão válidos por um período de 30 dias. </br>Deseja publicar e compartilhar seu site?",
  "PUBLISH_SYNC_IN_PROGRESS": "Sincronização em andamento para visualização...",
  "PUBLISH_PAGE": "Clique para publicar e compartilhar este site",
  "PUBLISH_VIEW_PAGE": "Clique para ver a página publicada",
  "MISSING_FIELDS": "Campos ausentes",
  "PLEASE_FILL_ALL_REQUIRED": "Por favor, preencha todos os campos obrigatórios destacados em vermelho",
  "CODE_EDITOR": "Editor de código",
  "BUILD_THE_WEB": "Construa a web",
  "IMPORT_PROJECT": "Importar Projeto",
  "GITHUB_PROJECT": "Projeto GitHub",
  "NEW_PROJECT_FROM_GITHUB": "Novo projeto do GitHub",
  "GITHUB_REPO_URL": "URL do repositório do GitHub:",
  "CREATE_PROJECT": "Criar projeto",
  "SETTING_UP_PROJECT": "Configurando o Projeto",
  "LOCATION": "Localização:",
  "DOWNLOADING": "Baixando...",
  "DOWNLOADING_FILE": "Baixando {0}...",
  "EXTRACTING_FILES_PROGRESS": "Extraindo {0} de {1} arquivos.",
  "COMPRESS_FILES_PROGRESS": "Compactando {0} de {1} arquivos.",
  "DOWNLOAD_FAILED_MESSAGE": "Verifique se o URL de download é válido. </br>NB: Como o Phoenix está em alfa, URLs de repositórios privados e GitHub maiores que 25 MB não são permitidos.",
  "PLEASE_SELECT_A_FOLDER": "Selecione uma pasta...",
  "UNZIP_IN_PROGRESS": "Descompactando arquivos...",
  "UNZIP_FAILED": "Erro: Falha ao descompactar.",
  "CONFIRM_REPLACE_TITLE": "Confirmar substituição",
  "KEEP_BOTH": "Mantenha ambos",
  "EXPLORE": "Jogos HTML",
  "BLOG": "Blogue",
  "PHOENIX_DEFAULT_PROJECT": "Projeto padrão",
  "PROJECT_NAME": "Nome do Projeto:",
  "NEW_HTML": "Novo projeto HTML",
  "LICENSE": "Licença:",
  "CREDITS": "Créditos:",
  "PREVIEW": "Visualizar",
  "BUILD_WEBSITE": "Criar site",
  "VIEW_MORE": "Veja mais...",
  "NEW_PROJECT_NOTIFICATION": "Clique neste ícone para<br/> criar um novo projeto.</br> <a href='#' style='float:right;'>OK</a>",
  "BEAUTIFY_CODE_NOTIFICATION": "Clique aqui ou pressione <b>`{0}`</b> para embelezar o código.</br><img src=\"extensions/default/Phoenix/images/beautify.gif\"><br/> <a href='#' style='float:right;'>OK</a>",
  "DEFAULT_PROJECT_NOTIFICATION": "Clique aqui para abrir o<br/> <b>projeto padrão</b> em phoenix.</br> <a href='#' style='float:right;'>OK</a>",
  "DIRECTORY_REPLACE_MESSAGE": "A pasta selecionada <span class='dialog-filename'>{0}</span> não está vazia. Tem certeza de que deseja substituir o conteúdo da pasta pelo projeto?",
  "BUILD_WEBSITE_SECTION": "Criar site",
  "LEARN_SECTION": "Aprenda com exemplos",
  "CREATE_EXTENSION_SECTION": "Criar extensões e temas do {APP_NAME}",
  "CREATE_EXTENSION": "Criar extensão",
  "CREATE_THEME": "Criar Tema",
  "WEBPAGE_HOME_PAGE": "Pagina inicial",
  "WEBPAGE_BLOG": "Página do blog",
  "WEBPAGE_DASHBOARD": "Painel HTML",
  "WEBPAGE_BOOTSTRAP_EXAMPLES": "Exemplos de Bootstrap",
  "PROJECTS_AT_A_GLANCE": "Seus projetos em resumo",
  "PROJECT_AT_GLANCE_DESCRIPTION": "Assista ao vídeo para começar.",
  "GUIDED_LIVE_PREVIEW": "Faça algumas alterações de código no arquivo HTML para ver a visualização ao vivo.</br> <a href='#' style='float:right;'>OK</a>",
  "GUIDED_LIVE_PREVIEW_POPOUT": "Clique neste botão para exibir a visualização ao vivo em uma nova guia.</br> <a href='#' style='float:right;'>OK</a>",
  "ENJOYING_APP": "Está gostando do {APP_NAME}?",
  "GITHUB_STARS_POPUP": "<div>Suas avaliações mantêm nossa pequena equipe motivada a tornar o <b>phcode.dev</b> ainda melhor.<br/> Por favor, marque-nos no GitHub:",
  "GITHUB_STARS_POPUP_TWITTER": "Dê feedback ou divulgue no Twitter:",
  "TEST_TRANSLATE": "use isso para testar traduções",
  "POWER_USER_POPUP_TITLE": "Como podemos tornar o {APP_NAME} melhor para você?",
  "POWER_USER_POPUP_TEXT": "<div>Nós adoraríamos ter sua opinião. Seu feedback nos ajuda a decidir quais recursos desenvolver e quais melhorias devem ser feitas em nossa plataforma.<br/> <a>Por favor, preencha esta breve pesquisa.</a></div>",
  "BEAUTIFY_ERROR": "Não foi possível embelezar o código. Verifique a sintaxe.",
  "BEAUTIFY_ERROR_ORIGINAL_CHANGED": "Não foi possível embelezar. O texto do editor foi alterado após o embelezamento.",
  "BEAUTIFY_PROJECT_BUSY_MESSAGE": "Arquivo de Embelezamento {0}",
  "BEAUTIFY_ERROR_SELECTION": "Não foi possível embelezar.</br>Bloco de código incompleto selecionado ou sintaxe inválida.",
  "BEAUTIFY_OPTIONS": "Opções que controlam como o Beautify Code funciona",
  "BEAUTIFY_OPTION_PRINT_WIDTH": "Especifique o comprimento da linha em que o embelezador irá envolver",
  "BEAUTIFY_OPTION_SEMICOLON": "Adicione um ponto e vírgula no final de cada instrução",
  "BEAUTIFY_OPTION_SINGLE_QUOTE": "Use aspas simples em vez de aspas duplas",
  "BEAUTIFY_OPTION_QUOTE_PROPS": "Alterar quando as propriedades em objetos são citadas",
  "BEAUTIFY_OPTION_BRACKET_SAME_LINE": "Coloque o > de um elemento HTML de várias linhas (HTML, JSX, Vue, Angular) no final da última linha em vez de ficar sozinho na próxima linha (não se aplica a elementos de fechamento automático)",
  "BEAUTIFY_OPTION_SINGLE_ATTRIBUTE_PER_LINE": "Aplicar atributo único por linha em HTML, Vue e JSX",
  "BEAUTIFY_OPTION_PROSE_WRAP": "Enrole prosa se exceder a largura de impressão em arquivos de remarcação",
  "BEAUTIFY_OPTION_PRINT_TRAILING_COMMAS": "Imprima vírgulas à direita sempre que possível em estruturas sintáticas de várias linhas separadas por vírgulas"
});