/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 * Original work Copyright (c) 2012 - 2021 Adobe Systems Incorporated. All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "GENERIC_ERROR": "(грешка {0})",
  "NOT_FOUND_ERR": "Непостојећа датотека.",
  "NOT_READABLE_ERR": "Датотека не може бити учитана.",
  "EXCEEDS_MAX_FILE_SIZE": "Датотеке веће од {0} MB се не могу отворити у {APP_NAME}-у.",
  "NO_MODIFICATION_ALLOWED_ERR": "Циљани директоријум не може бити измењен.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "Тренутна овлашћења Вам не дозвољавају да правите измене.",
  "CONTENTS_MODIFIED_ERR": "Ова датотека је била измењена ван {APP_NAME}-а.",
  "UNSUPPORTED_ENCODING_ERR": "{APP_NAME} тренутно подржава искључиво текстуалне датотеке које су енкодиране у UTF-8 формату.",
  "ENCODE_FILE_FAILED_ERR": "{APP_NAME} nije bio u stanju da kodiraju sadržaj datoteke.",
  "DECODE_FILE_FAILED_ERR": "{APP_NAME} nije bio u stanju da dekodira sadržaj datoteke.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "{APP_NAME} trenutno ne podržava UTF-16 kodirane tekstualne datoteke.",
  "FILE_EXISTS_ERR": "Датотека или директоријум већ постоји.",
  "FILE": "датотеци",
  "FILE_TITLE": "Датотека",
  "DIRECTORY": "директоријум",
  "DIRECTORY_TITLE": "Директоријум",
  "DIRECTORY_NAMES_LEDE": "Имена директоријума",
  "FILENAMES_LEDE": "Имена датотека",
  "FILENAME": "Име датотеке",
  "DIRECTORY_NAME": "Име директоријума",
  "ERROR_LOADING_PROJECT": "Грешка приликом учитавања пројекта",
  "OPEN_DIALOG_ERROR": "Дошло је до грешке приликом приказивања дијалога за отварање датотеке. (грешка {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "Дошло је до грешке приликом покушаја да се учита директоријум <span class='dialog-filename'>{0}</span>. (грешка {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "Дошло је до грешке приликом ишчитавања садржаја директоријума <span class='dialog-filename'>{0}</span>. (грешка {1})",
  "ERROR_OPENING_FILE_TITLE": "Грешка при отварању датотеке",
  "ERROR_OPENING_FILE": "Дошло је до грешке приликом покушаја да се отвори датотека <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_OPENING_FILES": "Дошло је до грешке приликом покушаја да се отворе следеће датотеке:",
  "ERROR_RELOADING_FILE_TITLE": "Грешка при поновном учитавању измена са диска",
  "ERROR_RELOADING_FILE": "Дошло је до грешке приликом покушаја да се поново учита датотека <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_SAVING_FILE_TITLE": "Грешка при чувању датотеке",
  "ERROR_SAVING_FILE": "Дошло је до грешке приликом покушаја да се сачува датотека <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_FILE_TITLE": "Грешка приликом преименовања датотеке {0}",
  "ERROR_RENAMING_FILE": "Дошло је до грешке приликом покушаја да се преименује датотека {2} <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "Datoteka ili direktorijum nije deo trenutno otvorenog projekta. Nažalost, u ovom trenutku mogu se preimenovati samo datoteke projekta.",
  "ERROR_MOVING_FILE_TITLE": "Greška u pomeranju {0}",
  "ERROR_MOVING_FILE": "Došlo je do greške prilikom pokušaja pomeranja {2} <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "Ne mogu premestiti datoteku/fasciklu, jer oni nisu deo trenutnog projekta.",
  "ERROR_DELETING_FILE_TITLE": "Грешка при брисању датотеке {0}",
  "ERROR_DELETING_FILE": "Дошло је до грешке приликом покушаја да се обрише датотека {2} <span class='dialog-filename'>{0}</span>. {1}",
  "INVALID_FILENAME_TITLE": "Име {0} није валидно",
  "INVALID_FILENAME_MESSAGE": "Име {0} не сме садржати системски резервисане речи, не сме се завршити тачком (.) или користити неки од следећих карактера: <code class='emphasized'>{1}</code>",
  "ENTRY_WITH_SAME_NAME_EXISTS": "Датотека или директоријум са именом <span class='dialog-filename'>{0}</span> већ постоји.",
  "ERROR_CREATING_FILE_TITLE": "Грешка при креирању {0}",
  "ERROR_CREATING_FILE": "Дошло је до грешке приликом покушаја да се креира {0} <span class='dialog-filename'>{1}</span>. {2}",
  "ERROR_MIXED_DRAGDROP": "Директоријум се не може учитавати у исто време када и остале датотеке.",
  "ERROR_KEYMAP_TITLE": "Грешка приликом ишчитавања корисничке мапе пречица на тастатури",
  "ERROR_KEYMAP_CORRUPT": "Ваша мапа пречица на тастатури није валидан JSON. Датотека ће бити отворена како бисте исправили формат.",
  "ERROR_LOADING_KEYMAP": "Ваша мапа пречица на тастатури није валидна UTF-8 енкодирана текстуална датотека и не може се учитати",
  "ERROR_RESTRICTED_COMMANDS": "Не можете поново доделити пречице овим командама: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "Не можете доделити ове пречице: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "Додајете више пречица на тастатури за ове команде: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "Имате више комбинација за ове пречице: {0}",
  "ERROR_INVALID_SHORTCUTS": "Ове пречице нису валидне: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "Додајете пречице на тастатури непостојећим командама: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "Грешка приликом ишчитавања подешавања",
  "ERROR_PREFS_CORRUPT": "Ваша датотека са подешавањима није валидан JSON. Датотека ће бити отворена како бисте исправили формат. Биће неопходно да поново покренете {APP_NAME} како би измене биле примењене.",
  "ERROR_PROJ_PREFS_CORRUPT": "Datoteka sa podešavanjima projekta nije važeća JSON. Datoteka će biti otvorena tako da možete ispraviti format. Moraćete da ponovo učitate projekat da bi promene stupile na snagu.",
  "ERROR_IN_BROWSER_TITLE": "Упс! {APP_NAME} још увек не ради у веб претраживачу.",
  "ERROR_IN_BROWSER": "Апликација {APP_NAME} је направљена помоћу HTML-а, али тренутно ради као \"desktop\" апликација па је можете користити за измену локалних датотека. Молимо Вас користите \"application shell\" на <b>github.com/adobe/brackets-shell</b> репозиторијуму за покретање {APP_NAME}-а.",
  "ERROR_MAX_FILES_TITLE": "Грешка приликом индексирања датотека",
  "ERROR_MAX_FILES": "Пројекат садржи више од 30.000 датотека. Делови апликације који врше обраду над више датотека могу постати неактивни или се понашати као да је пројекат празан. <a href='https://github.com/adobe/brackets/wiki/Large-Projects'>Прочитајте више о раду са великим пројектима</a>.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "Грешка при покретању претраживача",
  "ERROR_CANT_FIND_CHROME": "Google Chrome претраживач није пронађен. Молимо потврдите да је инсталиран.",
  "ERROR_LAUNCHING_BROWSER": "Грешка приликом покретања претраживача. (error {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "Грешка у живом приказу",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "Повезивање са веб претраживачем",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "Да би се живи приказ повезао, потребно је да поново покренете Chrome са укљученим подешавањима за \"remote debugging\".<br /><br />Да ли желите поново да покренете Chrome са укљученим подешавањима за \"remote debugging\"?<br /><br />",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "Није могуће учитати страницу са живим приказом.",
  "LIVE_DEV_NEED_HTML_MESSAGE": "Отворите HTML датотеку како бисте били сигурни да постоји index.html датотека у Вашем пројекту како бисте покренули живи приказ.",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "За покретање живог приказа са датотеком која је \"server-side\", морате навести основну URL адресу за овај пројекат.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "Грешка приликом покретања HTTP сервера за \"живе\" развојне датотеке. Молимо покушајте поново.",
  "LIVE_DEVELOPMENT_INFO_TITLE": "Добро дошли у живи приказ!",
  "LIVE_DEVELOPMENT_INFO_MESSAGE": "Живи приказ повезује {APP_NAME} са Вашим веб претраживачем. Он покреће Вашу HTML датотеку у претраживачу, а потом ажурира приказ тренутно док Ви мењате Ваш кôд.<br /><br />У овој раној верзији {APP_NAME}-a, живи приказ ради једино у <strong>Google Chrome</strong> претраживачу и ажурира приказ док мењате <strong>CSS или HTML датотеке</strong>. За освежавање приказа приликом измена у JavaScript датотекама потребно је да сачувате Ваше измене.<br /><br />(Ова порука ће се приказати само једном.)",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "За више информација, погледајте <a href='{0}' title='{0}'>Отклањање грешака у конекцији приликом развоја уживо</a>.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "Живи приказ",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "Живи приказ: Успостављање конекције…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "Живи приказ: Иницијализација…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "Прекини конекцију са живим приказом",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "Живи приказ (сачувај датотеку за освежавање)",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "Izaberite datoteku za pregled uživo",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "Reload Page",
  "LIVE_DEV_CLICK_POPOUT": "Popout Live Previev na novi prozor",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "Pin na Unpin Previev Page",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "Живи приказ (не освежава се због грешке у синтакси)",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "Живи приказ је отказан јер су развојни алати били отворени у претраживачу",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "Живи приказ је отказан јер је страница затворена у претраживачу",
  "LIVE_DEV_NAVIGATED_AWAY": "Живи приказ је отказан јер је претраживач отишао на страницу која није део тренутног пројекта",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "Живи приказ је отказан из непознатог разлога ({0})",
  "SAVE_CLOSE_TITLE": "Сачувај измене",
  "SAVE_CLOSE_MESSAGE": "Да ли желите да сачувате измене које сте направили у документу <span class='dialog-filename'>{0}</span>?",
  "SAVE_CLOSE_MULTI_MESSAGE": "Да ли желите да сачувате Ваше измене над следећим датотекама?",
  "EXT_MODIFIED_TITLE": "Екстерне измене",
  "CONFIRM_DELETE_TITLE": "Потврди брисање",
  "CONFIRM_FILE_DELETE": "Da li ste sigurni da želite da izbrišete datoteku <span class='dialog-filename'>{0}</span>?",
  "CONFIRM_FOLDER_DELETE": "Да ли сте сигурни да желите обрисати директоријум <span class='dialog-filename'>{0}</span>?",
  "FILE_DELETED_TITLE": "Датотека обрисана",
  "EXT_MODIFIED_WARNING": "Датотека <span class='dialog-filename'>{0}</span> је измењена на диску.<br /><br />Да ли желите да сачувате датотеку и преснимите те измене?",
  "EXT_MODIFIED_MESSAGE": "Датотека <span class='dialog-filename'>{0}</span> је измењена на диску, али садржи и измене начињене у {APP_NAME}-у.<br /><br />Коју верзију желите да сачувате?",
  "EXT_DELETED_MESSAGE": "Датотека <span class='dialog-filename'>{0}</span> је обрисана са диска, али садржи несачуване измене начињене у {APP_NAME}-у.<br /><br />Да ли желите да сачувате Ваше измене?",
  "WINDOW_UNLOAD_WARNING": "Da li ste sigurni da želite da se krećete do drugog URL-a i ostavite zagrade?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "Imate nesačuvane promene! Da li ste sigurni da želite da se krećete do drugog URL-a i ostavite zagrade?",
  "DONE": "Завршено",
  "OK": "OK",
  "CANCEL": "Откажи",
  "DONT_SAVE": "Немој сачувати",
  "SAVE": "Сачувај",
  "SAVE_AS": "Сачувај као…",
  "SAVE_AND_OVERWRITE": "Пресними",
  "DELETE": "Обриши",
  "BUTTON_YES": "Да",
  "BUTTON_NO": "Не",
  "FIND_MATCH_INDEX": "{0} од {1}",
  "FIND_NO_RESULTS": "Нема резултата",
  "FIND_QUERY_PLACEHOLDER": "Пронађи…",
  "FIND_HISTORY_MAX_COUNT": "Maksimalan broj stavki pretrage u istoriji pretrage",
  "REPLACE_PLACEHOLDER": "Замени са…",
  "BUTTON_REPLACE_ALL": "Комплет…",
  "BUTTON_REPLACE_BATCH": "Batch...",
  "BUTTON_REPLACE_ALL_IN_FILES": "Замени…",
  "BUTTON_REPLACE": "Замени",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "Следеће поклапање",
  "BUTTON_PREV_HINT": "Претходно поклапање",
  "BUTTON_CASESENSITIVE_HINT": "Иста величина",
  "BUTTON_REGEXP_HINT": "Регуларни израз",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "Замени без опозива",
  "REPLACE_WITHOUT_UNDO_WARNING": "Зато што је потребно променити више од {0} датотека, {APP_NAME} ће изменити неотворене датотеке на диску.<br />Нећете бити у могућности да опозовете измене у овим датотекама.",
  "BUTTON_REPLACE_WITHOUT_UNDO": "Замени без опозива",
  "OPEN_FILE": "Отвори датотеку",
  "SAVE_FILE_AS": "Сачувај датотеку",
  "CHOOSE_FOLDER": "Изабери директоријум",
  "RELEASE_NOTES": "Белешке о тренутној верзији",
  "NO_UPDATE_TITLE": "Имате актуелну верзију!",
  "NO_UPDATE_MESSAGE": "Тренутно поседујете актуелну верзију апликације {APP_NAME}.",
  "FIND_REPLACE_TITLE_LABEL": "Замени",
  "FIND_REPLACE_TITLE_WITH": "са",
  "FIND_TITLE_LABEL": "Пронађено",
  "FIND_TITLE_SUMMARY": "&mdash; {0} {1} {2} у {3}",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "у <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_NO_SCOPE": "у пројекту",
  "FIND_IN_FILES_ZERO_FILES": "Филтер искључује све датотеке {0}",
  "FIND_IN_FILES_FILE": "датотеци",
  "FIND_IN_FILES_FILES": "датотека",
  "FIND_IN_FILES_MATCH": "поклапање",
  "FIND_IN_FILES_MATCHES": "поклапања",
  "FIND_IN_FILES_MORE_THAN": "Преко ",
  "FIND_IN_FILES_PAGING": "{0}&mdash;{1}",
  "FIND_IN_FILES_FILE_PATH": "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "Притисните Ctrl/Cmd и кликните како бисте раширили/скупили све",
  "FIND_IN_FILES_INDEXING": "Indeksiranje za Instant Search...",
  "REPLACE_IN_FILES_ERRORS_TITLE": "Замени грешке",
  "REPLACE_IN_FILES_ERRORS": "Следеће датотеке нису модификоване зато што су измењене након претраге или у њих није било могуће уписивати.",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "Грешка приликом учитавања информација о новој верзији",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "Дошло је до проблема приликом преузимања последњих информација о новој верзији са сервера. Молимо проверите да ли сте повезани на интернет и покушајте поново.",
  "NEW_FILE_FILTER": "Нови сет искључења…",
  "CLEAR_FILE_FILTER": "Немој исључити датотеке",
  "NO_FILE_FILTER": "Ниједна датотека није искључена",
  "EXCLUDE_FILE_FILTER": "Искључи {0}",
  "EDIT_FILE_FILTER": "Измени…",
  "FILE_FILTER_DIALOG": "Измени сет искључења",
  "FILE_FILTER_INSTRUCTIONS": "Искључи све датотеке и директоријуме који се поклапају са било којим од следећих низова / поднизова или <a href='{0}' title='{0}'>џокер знакова</a>. Enter each string on a new line.",
  "FILTER_NAME_PLACEHOLDER": "Дај име овом сету искључења (опционо)",
  "FILTER_NAME_REMAINING": "{0} znakova preostalih",
  "FILE_FILTER_CLIPPED_SUFFIX": "и још {0}",
  "FILTER_COUNTING_FILES": "Пребројавам датотеке…",
  "FILTER_FILE_COUNT": "Дозвољава {0} од {1} датотека {2}",
  "FILTER_FILE_COUNT_ALL": "Дозвољава свих {0} датотека {1}",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "Брза измена није доступна на тренутној позицији курсора",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "CSS Брза измена: позиционирајте курсор на једно име класе",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "CSS Брза измена: непотпун атрибут класе",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "CSS Брза измена: непотпун атрибут идентификатора",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "CSS Брза измена: позиционирајте курсор на таг, класу, или идентификатор",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "CSS Времендска функција Брза измена: синтакса није валидна",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "JS Брза измена: позиционирајте курсор на име функције",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "Брзи документи нису доступни за тренутну позицију курсора",
  "PROJECT_LOADING": "Учитавам…",
  "UNTITLED": "Неименовано",
  "WORKING_FILES": "Радне датотеке",
  "TOP": "Горе",
  "BOTTOM": "Доле",
  "LEFT": "Лево",
  "RIGHT": "Десно",
  "CMD_SPLITVIEW_NONE": "Без поделе",
  "CMD_SPLITVIEW_VERTICAL": "Вертикална подела",
  "CMD_SPLITVIEW_HORIZONTAL": "Хоризонтална подела",
  "SPLITVIEW_MENU_TOOLTIP": "Подели едитор вертикално или хоризонтално",
  "GEAR_MENU_TOOLTIP": "Конфигуриши радни сет",
  "SPLITVIEW_INFO_TITLE": "Већ отворена",
  "SPLITVIEW_MULTIPANE_WARNING": "Датотека је већ отворена у другом панелу. {APP_NAME} ће ускоро подржавати отварање исте датотеке у више панела. До тада, датотека ће бити приказана у панелу у коме је већ отворена.<br /><br />(Ова порука ће се приказати само једном.)",
  "STATUSBAR_CURSOR_POSITION": "Линија {0}, колона {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": " — Изабрана {0} колона",
  "STATUSBAR_SELECTION_CH_PLURAL": " — Изабрано {0} колона",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " — Изабрана {0} линија",
  "STATUSBAR_SELECTION_LINE_PLURAL": " — Изабрано {0} линија",
  "STATUSBAR_SELECTION_MULTIPLE": " — {0} селекција",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "Кликни за коришћење размака приликом увлачења кôда",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "Кликни за коришћење таб-ова приликом увлачења кôда",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "Кликни за промену броја размака приликом увлачења кôда",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "Кликни за промену величине таб-а приликом увлачења кôда",
  "STATUSBAR_SPACES": "Размаци:",
  "STATUSBAR_TAB_SIZE": "Величина таб-а:",
  "STATUSBAR_LINE_COUNT_SINGULAR": "— {0} линија",
  "STATUSBAR_LINE_COUNT_PLURAL": "— {0} линија",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "Екстензије деактивиране",
  "STATUSBAR_INSERT": "УБ",
  "STATUSBAR_OVERWRITE": "ПРЕ",
  "STATUSBAR_INSOVR_TOOLTIP": "Кликни да промениш мôд курсора из Убаци (УБ) у Препиши (ПРЕ) и обрнуто",
  "STATUSBAR_LANG_TOOLTIP": "Кликни за измену типа датотеке",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. Кликни за приказ/скривање панела са извештајима.",
  "STATUSBAR_DEFAULT_LANG": "(подразумевано)",
  "STATUSBAR_SET_DEFAULT_LANG": "Подеси као \"подразумевано\" за .{0} датотеке",
  "STATUSBAR_ENCODING_TOOLTIP": "Izaberite kodiranje",
  "ERRORS_PANEL_TITLE_MULTIPLE": "{0} грешака",
  "SINGLE_ERROR": "1 {0} грешка",
  "MULTIPLE_ERRORS": "{1} {0} грешака",
  "NO_ERRORS": "Нема {0} грешака - свака част!",
  "NO_ERRORS_MULTIPLE_PROVIDER": "Нема пронађених грешака - свака част!",
  "LINT_DISABLED": "Детектовање сумњивог кôда искључено",
  "NO_LINT_AVAILABLE": "Ниједан детектор сумњивог кôда није доступан за {0}",
  "NOTHING_TO_LINT": "Није пронађен сумњив кôд",
  "LINTER_TIMED_OUT": "Прекинуто је извршавање {0} након чекања од {1} ms",
  "LINTER_FAILED": "Прекинуто је извршавање {0} уз грешку: {1}",
  "FILE_MENU": "Датотека",
  "CMD_FILE_NEW_UNTITLED": "Нова",
  "CMD_FILE_NEW": "Нова датотека",
  "CMD_PROJECT_NEW": "Novi projekat",
  "CMD_FILE_NEW_FOLDER": "Нови директоријум",
  "CMD_FILE_OPEN": "Отвори…",
  "CMD_RECENT_FILES_OPEN": "Otvorite Nedavna...",
  "CMD_ADD_TO_WORKING_SET": "Додај у радни сет",
  "CMD_OPEN_DROPPED_FILES": "Open Dropped Files",
  "CMD_OPEN_FOLDER": "Отвори директоријум…",
  "CMD_FILE_CLOSE": "Затвори",
  "CMD_FILE_CLOSE_ALL": "Затвори све",
  "CMD_FILE_CLOSE_LIST": "Затвори листу",
  "CMD_FILE_CLOSE_OTHERS": "Затвори остале",
  "CMD_FILE_CLOSE_ABOVE": "Затвори остале изнад",
  "CMD_FILE_CLOSE_BELOW": "Затвори остале испод",
  "CMD_FILE_SAVE": "Сачувај",
  "CMD_FILE_SAVE_ALL": "Сачувај све",
  "CMD_FILE_SAVE_AS": "Сачувај као…",
  "CMD_LIVE_FILE_PREVIEW": "Живи приказ",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "Omogući eksperimentalni pregled uživo",
  "CMD_RELOAD_LIVE_PREVIEW": "На силу обнови Живи приказ",
  "CMD_PROJECT_SETTINGS": "Подешавање пројекта…",
  "CMD_FILE_RENAME": "Преименуј",
  "CMD_FILE_DELETE": "Обриши",
  "CMD_INSTALL_EXTENSION": "Инсталирај екстензију…",
  "CMD_EXTENSION_MANAGER": "Менаџер екстензија…",
  "CMD_FILE_REFRESH": "Освежи стабло датотека",
  "CMD_QUIT": "Прекини",
  "CMD_EXIT": "Излаз",
  "EDIT_MENU": "Уреди",
  "CMD_UNDO": "Опозови",
  "CMD_REDO": "Понови",
  "CMD_CUT": "Исеци",
  "CMD_COPY": "Копирај",
  "CMD_PASTE": "Налепи",
  "CMD_SELECT_ALL": "Изабери све",
  "CMD_SELECT_LINE": "Изабери линију",
  "CMD_SPLIT_SEL_INTO_LINES": "Подели селекцију на линије",
  "CMD_ADD_CUR_TO_NEXT_LINE": "Додај курсор следећој линији",
  "CMD_ADD_CUR_TO_PREV_LINE": "Додај курсор претходној линији",
  "CMD_INDENT": "Помери удесно",
  "CMD_UNINDENT": "Помери улево",
  "CMD_DUPLICATE": "Удвостручи",
  "CMD_DELETE_LINES": "Обриши линију",
  "CMD_COMMENT": "Додај/уклони линијски коментар",
  "CMD_BLOCK_COMMENT": "Додај/уклони блок коментар",
  "CMD_LINE_UP": "Помери линију горе",
  "CMD_LINE_DOWN": "Помери линију доле",
  "CMD_OPEN_LINE_ABOVE": "Отвори линију изнад",
  "CMD_OPEN_LINE_BELOW": "Отвори линију испод",
  "CMD_TOGGLE_CLOSE_BRACKETS": "Аутоматски затвори заграде",
  "CMD_SHOW_CODE_HINTS": "Пружи малу помоћ око кôда",
  "FIND_MENU": "Пронађи",
  "CMD_FIND": "Пронађи",
  "CMD_FIND_NEXT": "Пронађи следеће",
  "CMD_FIND_PREVIOUS": "Пронађи претходно",
  "CMD_FIND_ALL_AND_SELECT": "Пронађи све и изабери",
  "CMD_ADD_NEXT_MATCH": "Додај следеће поклапање у селекцију",
  "CMD_SKIP_CURRENT_MATCH": "Прескочи и додај следеће поклапање",
  "CMD_FIND_IN_FILES": "Пронађи међу датотекама",
  "CMD_FIND_IN_SUBTREE": "Пронађи у…",
  "CMD_REPLACE": "Замени",
  "CMD_REPLACE_IN_FILES": "Замени у датотекама",
  "CMD_REPLACE_IN_SUBTREE": "Замени у…",
  "VIEW_MENU": "Приказ",
  "CMD_HIDE_SIDEBAR": "Сакриј споредну траку",
  "CMD_SHOW_SIDEBAR": "Прикажи споредну траку",
  "CMD_TOGGLE_SIDEBAR": "Toggle bočna traka",
  "CMD_TOGGLE_PANELS": "Toggle paneli",
  "CMD_TOGGLE_PURE_CODE": "Nema ometanja",
  "CMD_INCREASE_FONT_SIZE": "Повећај величину фонта",
  "CMD_DECREASE_FONT_SIZE": "Смањи величину фонта",
  "CMD_RESTORE_FONT_SIZE": "Поврати величину фонта",
  "CMD_SCROLL_LINE_UP": "Помакни једну линију горе",
  "CMD_SCROLL_LINE_DOWN": "Помакни једну линију доле",
  "CMD_TOGGLE_LINE_NUMBERS": "Бројеви редова",
  "CMD_TOGGLE_ACTIVE_LINE": "Означи активну линију",
  "CMD_TOGGLE_WORD_WRAP": "Прелом текста",
  "CMD_LIVE_HIGHLIGHT": "Обележи живи приказ",
  "CMD_VIEW_TOGGLE_INSPECTION": "Преконтролиши датотеке приликом чувања",
  "CMD_WORKINGSET_SORT_BY_ADDED": "Сортирај по датуму додавања",
  "CMD_WORKINGSET_SORT_BY_NAME": "Сортирај по имену",
  "CMD_WORKINGSET_SORT_BY_TYPE": "Сортирај по типу",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "Аутоматско сортирање",
  "CMD_THEMES": "Теме…",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "Automatski zatvori pretragu",
  "NAVIGATE_MENU": "Навигација",
  "CMD_QUICK_OPEN": "Отвори на брзину",
  "CMD_GOTO_LINE": "Иди на линију",
  "CMD_GOTO_DEFINITION": "Брзо пронађи дефиницију",
  "CMD_GOTO_DEFINITION_PROJECT": "Brzo pronalaženje definicije u projektu",
  "CMD_GOTO_FIRST_PROBLEM": "Иди на први проблем",
  "CMD_TOGGLE_QUICK_EDIT": "Измени на брзину",
  "CMD_TOGGLE_QUICK_DOCS": "Брзи документи",
  "CMD_QUICK_EDIT_PREV_MATCH": "Претходно поклапање",
  "CMD_QUICK_EDIT_NEXT_MATCH": "Следеће поклапање",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "Ново правило",
  "CMD_NEXT_DOC": "Следећи документ",
  "CMD_PREV_DOC": "Претходни документ",
  "CMD_NAVIGATE_BACKWARD": "Kretanje unazad",
  "CMD_NAVIGATE_FORWARD": "Kretanje napred",
  "CMD_NEXT_DOC_LIST_ORDER": "Sledeći dokument na listi",
  "CMD_PREV_DOC_LIST_ORDER": "Prethodni dokument na listi",
  "CMD_SHOW_IN_TREE": "Прикажи у стаблу датотека",
  "CMD_SHOW_IN_EXPLORER": "Прикажи у Explorer-у",
  "CMD_SHOW_IN_FINDER": "Прикажи у Проналазачу",
  "CMD_SHOW_IN_OS": "Прикажи у оперативном систему",
  "CMD_SWITCH_PANE_FOCUS": "Prebaci Fokus okna",
  "CMD_OPEN_VFS": "Otvorite virtuelni sistem datoteka",
  "CMD_OPEN_VIRTUAL_SERVER": "Otvorite virtuelni server",
  "HELP_MENU": "Помоћ",
  "CMD_CHECK_FOR_UPDATE": "Провери да ли постоји новијa верзија",
  "CMD_HOW_TO_USE_BRACKETS": "Корисничко упутство за {APP_NAME}",
  "CMD_SUPPORT": "{APP_NAME} подршка",
  "CMD_SUGGEST": "Предложи нову функционалност",
  "CMD_RELEASE_NOTES": "Белешке о тренутној верзији",
  "CMD_GET_INVOLVED": "Прикључи се развоју апликације",
  "CMD_SHOW_EXTENSIONS_FOLDER": "Прикажи директоријум са екстензијама",
  "CMD_HEALTH_DATA_STATISTICS": "Zdravstveni izveštaj",
  "CMD_HOMEPAGE": "{APP_NAME} Početna stranica",
  "CMD_TWITTER": "{TWITTER_NAME} на Твитеру",
  "CMD_ABOUT": "О апликацији {APP_TITLE}",
  "CMD_OPEN_PREFERENCES": "Отвори датотеку са подешавањима",
  "CMD_OPEN_KEYMAP": "Отвори мапу корисничких пречица на тастатури",
  "EXPERIMENTAL_BUILD": "експериментална верзија",
  "RELEASE_BUILD": "билд",
  "DEVELOPMENT_BUILD": "развојна верзија",
  "PRERELEASE_BUILD": "prerelease build",
  "RELOAD_FROM_DISK": "Поново учитај са диска",
  "KEEP_CHANGES_IN_EDITOR": "Сачувај измене у едитору",
  "CLOSE_DONT_SAVE": "Затвори (без чувања измена)",
  "RELAUNCH_CHROME": "Поново покрени Chrome",
  "ABOUT": "О апликацији",
  "CLOSE": "Затвори",
  "ABOUT_TEXT_LINE1": "Izdanje {VERSION_MAOR}. {VERSION_MINOR} {BUILD_TIPE} {VERZIJA}",
  "ABOUT_TEXT_BUILD_TIMESTAMP": "build timestamp: ",
  "ABOUT_TEXT_LINE3": "Biblioteke trećih strana koje koristimo - <a href='https://github.com/phcode-dev/phoenix/tree/main/src/thirdparty/licences'> Licence i atribucije</a> . ",
  "ABOUT_TEXT_LINE4": "Dokumentacija i izvor na <a href='https://github.com/phcode-dev/phoenix/'>https://github.com/phcode-dev/phoenix/</a>",
  "ABOUT_TEXT_LINE5": "Napravljeno sa ❤ i JavaScript od strane:",
  "ABOUT_TEXT_LINE6": "Mnogo ljudi (ali trenutno imamo problema sa učitavanjem tih podataka).",
  "ABOUT_TEXT_MDN_DOCS": "\"MDN Docs\" и \"MDN\" логотип су заштићени \"Creative Commons Attribution\" лиценцом, <a href='{MDN_DOCS_LICENSE}'>CC-BY-SA 2.5 Unported</a>.",
  "UPDATE_NOTIFICATION_TOOLTIP": "Објављена је нова верзија {APP_NAME}-а! Кликните овде за више информација.",
  "UPDATE_AVAILABLE_TITLE": "Нова верзија доступна",
  "UPDATE_MESSAGE": "Хеј, нова верзија {APP_NAME}-а је доступна. Ово су нека од најновијих унапређења:",
  "GET_IT_NOW": "Преузми сада!",
  "PROJECT_SETTINGS_TITLE": "Подешавања пројекта за: {0}",
  "PROJECT_SETTING_BASE_URL": "Основна URL адреса за живи приказ",
  "PROJECT_SETTING_BASE_URL_HINT": "Да бисте користили локални сервер, унесите адресу (url) попут http://localhost:8000/",
  "BASEURL_ERROR_INVALID_PROTOCOL": "Живи приказ не подржава протокол {0}&mdash;Молимо Вас користите http: или https: .",
  "BASEURL_ERROR_SEARCH_DISALLOWED": "Основна URL адреса не сме садржати параметре попут \"{0}\".",
  "BASEURL_ERROR_HASH_DISALLOWED": "Основна URL адреса не сме садржати хешеве (hashes) попут \"{0}\".",
  "BASEURL_ERROR_INVALID_CHAR": "Специјални карактери попут '{0}' морају бити %-енкодирани.",
  "BASEURL_ERROR_UNKNOWN_ERROR": "Непозната грешка приликом парсирања основне URL адресе",
  "EMPTY_VIEW_HEADER": "<em>Отвори датотеку док је овај панел у фокусу</em>",
  "FLIPVIEW_BTN_TOOLTIP": "Okrenite ovaj prikaz u okno {0}",
  "CURRENT_THEME": "Тренутна тема",
  "USE_THEME_SCROLLBARS": "Користи клизаче из теме",
  "FONT_SIZE": "Величина фонта",
  "FONT_FAMILY": "Породица фонта",
  "THEMES_SETTINGS": "Подешавања теме",
  "BUTTON_NEW_RULE": "Ново правило",
  "INSTALL": "Инсталирај",
  "UPDATE": "Ажурирај",
  "REMOVE": "Уклони",
  "DISABLE": "Onemogući",
  "ENABLE": "Omogući",
  "OVERWRITE": "Пресними",
  "CANT_REMOVE_DEV": "Екстензије у \"dev\" директоријуму морају бити ручно обрисане.",
  "CANT_UPDATE": "Нова верзија није компатибилна са тренутном верзијом {APP_NAME}-а.",
  "CANT_UPDATE_DEV": "Extensions in the \"dev\" folder can't be updated automatically.",
  "INSTALL_EXTENSION_TITLE": "Инсталирај екстензију",
  "UPDATE_EXTENSION_TITLE": "Ажурирај екстензију",
  "INSTALL_EXTENSION_LABEL": "URL екстензије",
  "INSTALL_EXTENSION_HINT": "Интернет адреса (URL) zip архиве екстензије или GitHub репозиторијума",
  "INSTALLING_FROM": "Инсталирам екстензију са {0}…",
  "INSTALL_SUCCEEDED": "Инсталација успешна!",
  "INSTALL_FAILED": "Инсталација неуспешна.",
  "CANCELING_INSTALL": "Отказујем…",
  "CANCELING_HUNG": "Отказивање инсталације траје предуго. Могуће да је дошло до интерне грешке.",
  "INSTALL_CANCELED": "Инсталација отказана.",
  "VIEW_COMPLETE_DESCRIPTION": "Прикажи комплетан опис",
  "VIEW_TRUNCATED_DESCRIPTION": "Прикажи сажет опис",
  "SORT_EXTENSION_METHOD": "Sortiranje proširenja pomoću DovnloadCount ili PublishedDate",
  "INVALID_ZIP_FILE": "Преузети садржај није валидна zip архива.",
  "MISSING_PACKAGE_JSON": "Paket nema package.json datoteku.",
  "INVALID_PACKAGE_JSON": "Датотека \"package.json\" није валидна (грешка: {0}).",
  "MISSING_PACKAGE_NAME": "У датотеци \"package.json\" није наведено име пакета.",
  "BAD_PACKAGE_NAME": "{0} није валидно име за пакет.",
  "MISSING_PACKAGE_VERSION": "У датотеци \"package.json\" није наведена верзија пакета.",
  "INVALID_VERSION_NUMBER": "Верзија пакета број ({0}) није валидна.",
  "INVALID_BRACKETS_VERSION": "{APP_NAME}-ов низ о компатибилности ({0}) није валидан.",
  "DISALLOWED_WORDS": "Речи ({1}) нису дозвољене у пољу {0}.",
  "NPM_INSTALL_FAILED": "npm install komanda nije uspela: {0}",
  "API_NOT_COMPATIBLE": "Ова екстензија није компатибилна са тренутном верзијом апликације \"{APP_NAME}\". Инсталирана је у Ваш директоријум са неактивним екстензијама.",
  "MISSING_MAIN": "Овај пакет нема \"main.js\" датотеку.",
  "EXTENSION_ALREADY_INSTALLED": "Инсталирањем овог пакета ћете преснимити претходно инсталирану екстензију. Да ли желите да преснимите стару инсталацију?",
  "EXTENSION_SAME_VERSION": "Верзија овог пакета је иста као верзија која је тренутно инсталирана. Да ли желите да преснимите постојећу инсталацију?",
  "EXTENSION_OLDER_VERSION": "Овај пакет је у верзији {0} што је старије од тренутно инсталиране верзије ({1}). Да ли желите да преснимите постојећу инсталацију?",
  "DOWNLOAD_ID_IN_USE": "Интерна грешка: ID преузимања је већ у употреби.",
  "NO_SERVER_RESPONSE": "Повезивање са сервером није могуће.",
  "BAD_HTTP_STATUS": "Датотека није пронађена на серверу (HTTP {0}).",
  "CANNOT_WRITE_TEMP": "Није могуће сачувати преузете податке у привремену датотеку.",
  "ERROR_LOADING": "Дошло је до грешке у екстензији приликом њеног покретања.",
  "MALFORMED_URL": "URL није валидан. Молимо проверите да ли је Ваш унос тачан.",
  "UNSUPPORTED_PROTOCOL": "URL мора бити http или https.",
  "UNKNOWN_ERROR": "Непозната интерна грешка.",
  "EXTENSION_MANAGER_TITLE": "Менаџер екстензија",
  "EXTENSION_MANAGER_ERROR_LOAD": "Приступање регистру екстензије није могуће. Молимо покушајте касније.",
  "INSTALL_EXTENSION_DRAG": "Превуци .zip овде или",
  "INSTALL_EXTENSION_DROP": "Пусти .zip за инсталирање",
  "INSTALL_EXTENSION_DROP_ERROR": "Инсталирање/Ажурирање прекинуто услед следећих грешака:",
  "INSTALL_FROM_URL": "Инсталирај са URL адресе…",
  "INSTALL_EXTENSION_VALIDATING": "Валидирам…",
  "EXTENSION_AUTHOR": "Аутор",
  "EXTENSION_DATE": "Датум",
  "EXTENSION_INCOMPATIBLE_NEWER": "Ова екстензија захтева новиу верзију {APP_NAME}-а.",
  "EXTENSION_INCOMPATIBLE_OLDER": "Ова екстензија тренутно ради само у старијим верзијама {APP_NAME}-а.",
  "EXTENSION_LATEST_INCOMPATIBLE_NEWER": "Верзија {0} ове екстензије захтева новију верзију апликације {APP_NAME}. Али можете инсталирати ранију верзију {1}.",
  "EXTENSION_LATEST_INCOMPATIBLE_OLDER": "Верзија {0} ове екстензије ради искључиво са старијим верзијама апликације {APP_NAME}. Али можете инсталирати ранију верзију {1}.",
  "EXTENSION_NO_DESCRIPTION": "Не постоји опис",
  "EXTENSION_MORE_INFO": "Више информација...",
  "EXTENSION_ERROR": "Грешка у екстензији",
  "EXTENSION_KEYWORDS": "Кључне речи",
  "EXTENSION_TRANSLATED_USER_LANG": "Преведено на {0} језика, укључујући Ваш",
  "EXTENSION_TRANSLATED_GENERAL": "Преведено на {0} језика",
  "EXTENSION_TRANSLATED_LANGS": "Ова екстензија је преведена на ове језике: {0}",
  "EXTENSION_INSTALLED": "Инсталирано",
  "EXTENSION_UPDATE_INSTALLED": "Ова верзија екстензије је већ преузета и биће инсталирана приликом поновног покретања {APP_NAME}-а.",
  "EXTENSION_SEARCH_PLACEHOLDER": "Пронађи",
  "EXTENSION_MORE_INFO_LINK": "Још",
  "BROWSE_EXTENSIONS": "Претражи екстензије",
  "EXTENSION_MANAGER_REMOVE": "Уклони екстензију",
  "EXTENSION_MANAGER_REMOVE_ERROR": "Није могуће уклонити једну или више екстензија: {0}. {APP_NAME} ће се ипак поново покренути.",
  "EXTENSION_MANAGER_UPDATE": "Ажурирај екстензију",
  "EXTENSION_MANAGER_UPDATE_ERROR": "Није могуће ажурирати једну или више екстензија: {0}. {APP_NAME} ће се ипак поново покренути.",
  "EXTENSION_MANAGER_DISABLE": "Onemogući proširenje",
  "EXTENSION_MANAGER_DISABLE_ERROR": "Nije moguće onemogućiti jedan ili više ekstenzija: {0}. {APP_NAME} će se i dalje ponovo učitati.",
  "MARKED_FOR_REMOVAL": "Означено за уклањање",
  "UNDO_REMOVE": "Опозови",
  "MARKED_FOR_UPDATE": "Означено за ажурирање",
  "UNDO_UPDATE": "Опозови",
  "MARKED_FOR_DISABLING": "Označeno za onemogućavanje",
  "UNDO_DISABLE": "Опозови",
  "CHANGE_AND_RELOAD_TITLE": "Промени екстензије",
  "CHANGE_AND_RELOAD_MESSAGE": "Да би се означене екстензије ажурирале или уклониле \"{APP_NAME}\" ће морати поново да се покрене. Од Вас ће бити затражено да сачувате измене.",
  "REMOVE_AND_RELOAD": "Уклони екстензије и изађи",
  "CHANGE_AND_RELOAD": "Промени екстензије и изађи",
  "UPDATE_AND_RELOAD": "Ажурирај екстензије и изађи",
  "DISABLE_AND_RELOAD": "Onemogućite proširenja i ponovo učitajte",
  "PROCESSING_EXTENSIONS": "Процесуирам измене у екстензијама…",
  "EXTENSION_NOT_INSTALLED": "Екстензија {0} није могла бити уклоњена јер није била инсталирана.",
  "NO_EXTENSIONS": "Тренутно нема инсталираних екстензија.<br>Кликните изнад на картицу Доступно да додате екстензију.",
  "NO_EXTENSION_MATCHES": "Ниједна екстензија се не поклапа са унетим параметрима претраге.",
  "REGISTRY_SANITY_CHECK_WARNING": "ОПРЕЗ: Ове екстензије можда потичу од непознатих извора. Екстензије нису проверене и поседују пуне локалне привилегије. Будите обазриви приликом инсталације екстензија које потичу од непознатих извора.",
  "EXTENSIONS_INSTALLED_TITLE": "Инсталирано",
  "EXTENSIONS_DEFAULT_TITLE": "Podrazumevano",
  "EXTENSIONS_AVAILABLE_TITLE": "Доступно",
  "EXTENSIONS_THEMES_TITLE": "Теме",
  "EXTENSIONS_UPDATES_TITLE": "Ажурирања",
  "EXTENSIONS_LAST_UPDATED": "Poslednje ažuriranje",
  "EXTENSIONS_DOWNLOADS": "Preuzimanja",
  "INLINE_EDITOR_NO_MATCHES": "Нема поклапања.",
  "INLINE_EDITOR_HIDDEN_MATCHES": "Сва поклапања су скривена. Раширите датотеке излистане на десној страни како бисте видели поклапања.",
  "CSS_QUICK_EDIT_NO_MATCHES": "Не постоје CSS правила која се поклапају са Вашом селекцијом.<br> Кликните \"Ново правило\" како бисте креирали ново.",
  "CSS_QUICK_EDIT_NO_STYLESHEETS": "Не постоје стилови у вашем пројекту.<br>Креирајте један или додајте CSS правила.",
  "IMAGE_VIEWER_LARGEST_ICON": "највећа",
  "UNIT_PIXELS": "пиксели",
  "DEBUG_MENU": "Отклањање грешака",
  "ERRORS": "Грешке",
  "CMD_SHOW_DEV_TOOLS": "Прикажи развојне алате",
  "CMD_REFRESH_WINDOW": "Поново учитај са екстензијама",
  "CMD_RELOAD_WITHOUT_USER_EXTS": "Поново учитај без екстензија",
  "CMD_NEW_BRACKETS_WINDOW": "Нови {APP_NAME} прозор",
  "CMD_LAUNCH_SCRIPT_MAC": "Instalirajte prečicu komandne linije",
  "CMD_SWITCH_LANGUAGE": "Промени језик",
  "CMD_RUN_UNIT_TESTS": "Изврши тестове",
  "CMD_SHOW_PERF_DATA": "Прикажи податке о перформансама",
  "CMD_ENABLE_LOGGING": "Omogući detaljne dnevnike",
  "CMD_OPEN_BRACKETS_SOURCE": "Отвори изворни кôд Brackets-а",
  "CREATING_LAUNCH_SCRIPT_TITLE": "{APP_NAME} Prečica komandne linije",
  "ERROR_CREATING_LAUNCH_SCRIPT": "Došlo je do greške prilikom instaliranja prečice komandne linije. Pokušajte sa <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting'>ovim predlozima za rešavanje problema</a>. <br/><br/>Razlog: {0}",
  "ERROR_CLTOOLS_RMFAILED": "Nije moguće ukloniti postojeću <code>/usr/local/bin/zagrade</code> simboličnu vezu.",
  "ERROR_CLTOOLS_MKDIRFAILED": "Nije moguće kreirati <code>/usr/local/bin</code> direktorijum.",
  "ERROR_CLTOOLS_LNFAILED": "Nije moguće kreirati simvezu <code>/usr/local/bin/zagrade</code> .",
  "ERROR_CLTOOLS_SERVFAILED": "Interna greška.",
  "ERROR_CLTOOLS_NOTSUPPORTED": "Prečica komandne linije nije podržana na ovom operativnom sistemu.",
  "LAUNCH_SCRIPT_CREATE_SUCCESS": "Uspeh! Sada možete lako pokrenuti {APP_NAME} iz komandne linije: <code>zagrade myFile.txt</code> da biste otvorili datoteku ili <code>zagrade MiFolder</code> za prebacivanje projekata. <br/><br/><a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments'>Saznajte više</a> o korišćenju {APP_NAME} iz komandne linije.",
  "LANGUAGE_TITLE": "Промени језик",
  "LANGUAGE_MESSAGE": "Језик:",
  "LANGUAGE_SUBMIT": "Поново учитај {APP_NAME}",
  "LANGUAGE_CANCEL": "Откажи",
  "LANGUAGE_SYSTEM_DEFAULT": "језик система",
  "HEALTH_DATA_NOTIFICATION": "Postavke zdravstvenog izveštaja",
  "HEALTH_FIRST_POPUP_TITLE": "{APP_NAME} Zdravstveni izveštaj",
  "HEALTH_DATA_DO_TRACK": "Delite pseudonimne informacije o tome kako koristim {APP_NAME}",
  "HEALTH_DATA_NOTIFICATION_MESSAGE": "Da bismo poboljšali {APP_NAME}, periodično šaljemo ograničene, <strong>pseudonimne</strong> statistike core.ai o tome kako koristite {APP_NAME}. Ove informacije pomažu u određivanju prioriteta funkcijama, pronalaženju grešaka i uočavanju problema sa upotrebljivošću dok čuvaju vašu privatnost. <br><br>Možeteda vidite svoje podatke ili izaberete da ne delite podatke tako što ćete izabrati <strong>Pomoć > Zdravstveni izveštaj</strong>. <br><br>",
  "HEALTH_DATA_PREVIEW": "{APP_NAME} Zdravstveni izveštaj",
  "HEALTH_DATA_PREVIEW_INTRO": "<p>Dabismo poboljšali {APP_NAME}, periodično šaljemo ograničene, <strong>pseudonimne</strong> statistike core.ai o tome kako koristite {APP_NAME}. Ove informacije pomažu u određivanju prioriteta funkcijama, pronalaženju grešaka i uočavanju problema sa upotrebljivošću. </p><p>Ispodje pregled podataka koji će biti poslati u vašem sledećem zdravstvenom izveštaju <em>ako</em> je omogućen. </p>",
  "INLINE_TIMING_EDITOR_TIME": "Време",
  "INLINE_TIMING_EDITOR_PROGRESSION": "Напредак",
  "BEZIER_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd><kbd>←</kbd><kbd>→</kbd> Помери изабрану тачку<br><kbd class='text'>Shift</kbd> Помери за десет јединица<br><kbd class='text'>Tab</kbd> Замени тачке",
  "STEPS_EDITOR_INFO": "<kbd>↑</kbd><kbd>↓</kbd> Повећај или смањи кораке<br><kbd>←</kbd><kbd>→</kbd> 'Почни' или 'Заврши'",
  "INLINE_TIMING_EDITOR_INVALID": "Стара вредност <code>{0}</code> није валидна, па је приказана функција промењена у <code>{1}</code>. Овај документ ће се ажурирати приликом прве измене.",
  "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP": "Тренутна боја",
  "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP": "Оригинална боја",
  "COLOR_EDITOR_RGBA_BUTTON_TIP": "RGBa формат",
  "COLOR_EDITOR_HEX_BUTTON_TIP": "Hex формат",
  "COLOR_EDITOR_HSLA_BUTTON_TIP": "HSLa формат",
  "COLOR_EDITOR_0X_BUTTON_TIP": "Hek (0k) Format",
  "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR": "{0} (Коришћена {1} пут)",
  "COLOR_EDITOR_USED_COLOR_TIP_PLURAL": "{0} (Коришћена {1} пута)",
  "CMD_JUMPTO_DEFINITION": "Скочи на дефиницију",
  "CMD_SHOW_PARAMETER_HINT": "Пружи малу помоћ око параметра",
  "NO_ARGUMENTS": "<без параметара>",
  "DETECTED_EXCLUSION_TITLE": "Проблем у обради JavaScript датотеке",
  "DETECTED_EXCLUSION_INFO": "Brackets није успео да процесуира <span class='dialog-filename'>{0}</span>.<br><br>Ова датотека више неће бити процесуирана за приказивање малих помоћи у кôду, Скочи на дефиницију или Брза измена. Како бисте активирали ову датотеку, отворите <code>.brackets.json</code> у Вашем пројекту и измените <code>jscodehints.detectedExclusions</code>.<br><br>Ово је вероватно баг у апликацији Brackets. Ако можете приложити копију ове датотеке, молимо Вас <a href='https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue'>пријавите баг</a> који садржи линк до овде наведене датотеке.",
  "CMD_REFACTOR": "Refaktor",
  "CMD_EXTRACTTO_VARIABLE": "Ekstrakt do promenljive",
  "CMD_EXTRACTTO_FUNCTION": "Ekstrakt u funkciju",
  "ERROR_TERN_FAILED": "Nije moguće dobiti podatke od Tern",
  "ERROR_EXTRACTTO_VARIABLE_NOT_VALID": "Izbor ne formira izraz",
  "ERROR_EXTRACTTO_FUNCTION_NOT_VALID": "Izabrani blok treba da predstavlja skup izjava ili izraz",
  "ERROR_EXTRACTTO_VARIABLE_MULTICURSORS": "Ekstrakt u promenljivu ne radi u multicursorima",
  "ERROR_EXTRACTTO_FUNCTION_MULTICURSORS": "Ekstrakt u funkciju ne radi u multicursorima",
  "EXTRACTTO_FUNCTION_SELECT_SCOPE": "Izaberite opseg destinacije",
  "EXTRACTTO_VARIABLE_SELECT_EXPRESSION": "Izaberite izraz",
  "CMD_REFACTORING_RENAME": "Преименуј",
  "CMD_REFACTORING_TRY_CATCH": "Zamotajte u pokušaj Catch",
  "CMD_REFACTORING_CONDITION": "Zamotajte u stanju",
  "CMD_REFACTORING_GETTERS_SETTERS": "Kreirajte Getters/setere",
  "CMD_REFACTORING_ARROW_FUNCTION": "Pretvori u funkciju strelice",
  "DESCRIPTION_CODE_REFACTORING": "Omogući/onemogućite refaktorisanje JavaScript koda",
  "ERROR_TRY_CATCH": "Izaberite važeći kod za umotavanje u blok TRI-Catch",
  "ERROR_WRAP_IN_CONDITION": "Izaberite važeći kod za umotavanje u blok uslova",
  "ERROR_ARROW_FUNCTION": "Postavite kursor unutar funkcijskog izraza",
  "ERROR_GETTERS_SETTERS": "Postavite kursor na člana izraza objekta",
  "ERROR_RENAME_MULTICURSOR": "Ne može se preimenovati kada koristite više kursora",
  "ERROR_RENAME_QUICKEDIT": "Ne mogu preimenovati ovaj identifikator, jer se na njega spominje negde drugde izvan ove funkcije",
  "ERROR_RENAME_GENERAL": "Ne mogu preimenovati izabrani tekst",
  "JSLINT_NAME": "JSLint",
  "CMD_ENABLE_QUICK_VIEW": "Брзи приказ приликом задржавања миша",
  "CMD_TOGGLE_RECENT_PROJECTS": "Недавни пројекти",
  "DOCS_MORE_LINK": "Прочитај више",
  "COLLAPSE_ALL": "Srušite sve",
  "EXPAND_ALL": "Proširi sve",
  "COLLAPSE_CURRENT": "Struja kolapsa",
  "EXPAND_CURRENT": "Proširi Trenutni",
  "RECENT_FILES_DLG_HEADER": "Nedavne datoteke",
  "RECENT_FILES_DLG_CLEAR_BUTTON_LABEL": "Jasno",
  "RECENT_FILES_DLG_CLEAR_BUTTON_TITLE": "Obrišite datoteke koje nisu u radnom setu",
  "DESCRIPTION_CLOSE_BRACKETS": "tačno da automatski zatvori zagrade, zagrade i zagrade",
  "DESCRIPTION_CLOSE_OTHERS_ABOVE": "false da uklonite „Zatvori druge iznad“ iz kontekstnog menija Radne datoteke",
  "DESCRIPTION_CLOSE_OTHERS_BELOW": "false da uklonite „Zatvori druge ispod“ iz kontekstnog menija Radne datoteke",
  "DESCRIPTION_CLOSE_OTHERS": "false da uklonite „Zatvori druge“ iz kontekstnog menija Radne datoteke",
  "DESCRIPTION_CLOSE_TAGS": "Postavlja opcije zatvaranja oznake",
  "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS": "Niz oznaka koje se ne bi trebalo automatski zatvoriti",
  "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING": "Zatvorite kada se ukuca > otvaranja oznake",
  "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING": "Zatvorite kada se otkucava/oznake zatvaranja",
  "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS": "Niz oznaka koji kada se otvore ima praznu liniju",
  "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD": "tačno da uvek generiše sklopive markere preseka kada se nivo uvlake promeni",
  "DESCRIPTION_CODE_FOLDING_ENABLED": "tačno da omogući savijanje koda",
  "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER": "istina da bi sekcija-kolaps markeri vidljivi samo kada pomerite miša preko oluka",
  "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL": "Ograničava koliko nivoa duboko Kolaps Sve važi",
  "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE": "Minimalne linije pre nego što se pojavi ikona sklopivog odeljka",
  "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES": "tačno da zapamtite srušene sekcije ako zatvorite i ponovo otvorite datoteku ili projekat",
  "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE": "tačno da omogući savijanje koda na izabranom tekstu u editoru",
  "DESCRIPTION_DISABLED_DEFAULT_EXTENSIONS": "Podrazumevani dodaci koji su onemogućeni",
  "DESCRIPTION_ATTR_HINTS": "Omogućite/onemogućite HTML atribute",
  "DESCRIPTION_CSS_PROP_HINTS": "Omogući/onemogućiti CSS/LES/SCSS svojstva savete",
  "DESCRIPTION_JS_HINTS": "Omogući/onemogućite savete JavaScript koda",
  "DESCRIPTION_JS_HINTS_TYPE_DETAILS": "Omogućite/onemogućite detalje tipa podataka u savetima JavaScript koda",
  "DESCRIPTION_PREF_HINTS": "Omogući/onemogući savete koda Preferences",
  "DESCRIPTION_SPECIAL_CHAR_HINTS": "Omogućite/onemogućite HTML savete entiteta",
  "DESCRIPTION_SVG_HINTS": "Omogućite/onemogućite savete SVG koda",
  "DESCRIPTION_HTML_TAG_HINTS": "Omogućite/onemogućite HTML tag savete",
  "DESCRIPTION_URL_CODE_HINTS": "Omogućite/onemogućite URL savete u HTML & CSS/LES/SCSS",
  "DESCRIPTION_DRAG_DROP_TEXT": "Omogući/onemogućite Drag & Drop funkcionalnost",
  "DESCRIPTION_HEALTH_DATA_TRACKING": "Omogućite praćenje zdravstvenih podataka",
  "DESCRIPTION_HIGHLIGHT_MATCHES": "Omogućava automatsko isticanje odgovarajućih nizova u celom dokumentu",
  "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN": "Označite sve nizove koji se podudaraju sa tokenom u kojem je kursor trenutno (nije potreban izbor)",
  "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY": "Označite samo kada je izbor kompletan token",
  "DESCRIPTION_INSERT_HINT_ON_TAB": "tačno da ubacite trenutno izabrani kod nagoveštaj na kartici",
  "DESCRIPTION_NO_HINTS_ON_DOT": "tačno da automatski ne prikazuje nagoveštaje JS koda kada je otkucano",
  "DESCRIPTION_JSLINT_OPTIONS": "Objekat sa podrazumevanim opcijama za JSlint",
  "DESCRIPTION_JSLINT_OPTIONS_ASS": "tačno da dozvoli izraze dodeljivanja",
  "DESCRIPTION_JSLINT_OPTIONS_BITWISE": "istina da dozvoli bitne operatore",
  "DESCRIPTION_JSLINT_OPTIONS_BROWSER": "tačno ako standardni globusi pregledača treba da budu unapred definisani",
  "DESCRIPTION_JSLINT_OPTIONS_CLOSURE": "istina da dozvoli Google Zatvaranje idioma",
  "DESCRIPTION_JSLINT_OPTIONS_CONTINUE": "istina da dozvoli „nastavi“ izjavu",
  "DESCRIPTION_JSLINT_OPTIONS_COUCH": "tačno ako CouchDB globali treba da budu unapred definisani",
  "DESCRIPTION_JSLINT_OPTIONS_DEBUG": "istina da dozvoli debugger izjave",
  "DESCRIPTION_JSLINT_OPTIONS_DEVEL": "tačno ako globusi pregledača korisni u razvoju treba unapred definisati",
  "DESCRIPTION_JSLINT_OPTIONS_EQEQ": "istina da dozvoli == i! =",
  "DESCRIPTION_JSLINT_OPTIONS_ES6": "tačno ako ES6 globusi treba da budu unapred definisani",
  "DESCRIPTION_JSLINT_OPTIONS_EVIL": "istina da dozvoli eval",
  "DESCRIPTION_JSLINT_OPTIONS_FORIN": "tačno da dozvoli nefiltrirano „za... u“",
  "DESCRIPTION_JSLINT_OPTIONS_INDENT": "Podesite određenu širinu jezička",
  "DESCRIPTION_JSLINT_OPTIONS_MAXERR": "Maksimalan broj prijavljenih upozorenja",
  "DESCRIPTION_JSLINT_OPTIONS_MAXLEN": "Maksimalan broj znakova u liniji",
  "DESCRIPTION_JSLINT_OPTIONS_NEWCAP": "tačno da dozvoli nekapitalizovanim konstruktorima",
  "DESCRIPTION_JSLINT_OPTIONS_NODE": "tačno ako Node.js globals treba da bude unapred definisan",
  "DESCRIPTION_JSLINT_OPTIONS_NOMEN": "istina da dozvoli viseće podvlačenje u identifikatorima",
  "DESCRIPTION_JSLINT_OPTIONS_PASSFAIL": "istina da se zaustavi na prvoj grešci",
  "DESCRIPTION_JSLINT_OPTIONS_PLUSPLUS": "istina da dozvoli ++ i -",
  "DESCRIPTION_JSLINT_OPTIONS_REGEXP": "istina da dozvoli. i [^...]. u RegEkp",
  "DESCRIPTION_JSLINT_OPTIONS_RHINO": "tačno ako Globals Rhino treba da budu unapred definisani",
  "DESCRIPTION_JSLINT_OPTIONS_SLOPPY": "istina da dozvoli nedostaje `koristite strikt` pragmu",
  "DESCRIPTION_JSLINT_OPTIONS_STUPID": "tačno ako se mogu koristiti metode blokiranja ('... Sinc').",
  "DESCRIPTION_JSLINT_OPTIONS_SUB": "istina da omogući neefikasnu pretplatu",
  "DESCRIPTION_JSLINT_OPTIONS_TODO": "istina da dozvoli TODO komentare",
  "DESCRIPTION_JSLINT_OPTIONS_UNPARAM": "tačno da dozvoli neiskorišćene parametre",
  "DESCRIPTION_JSLINT_OPTIONS_VARS": "tačno da dozvoli više od 1 vars u funkciji",
  "DESCRIPTION_JSLINT_OPTIONS_WHITE": "istina ignorisati pravila belog prostora",
  "DESCRIPTION_LANGUAGE": "Podešavanja specifična za jezik",
  "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS": "Dodatna mapiranja iz ekstenzije datoteke u ime jezika",
  "DESCRIPTION_LANGUAGE_FILE_NAMES": "Dodatna mapiranja od imena datoteke do imena jezika",
  "DESCRIPTION_LINEWISE_COPY_CUT": "Ako kopirate i isečete kada nema izbora, kopirat ćete ili iseći čitave linije koje imaju kursore u njima",
  "DESCRIPTION_INPUT_STYLE": "Bira način na koji CodeMirror rukuje ulazom i fokusom. To može biti tekstualno područje, što je podrazumevano, ili contenteditable što je bolje za čitače ekrana (nestabilno)",
  "DESCRIPTION_LINTING_ENABLED": "tačno da omogući inspekciju koda",
  "DESCRIPTION_ASYNC_TIMEOUT": "Vreme u milisekundama nakon čega asinhroni linteri isteknu",
  "DESCRIPTION_LINTING_PREFER": "Niz lintera da prvo pokrenete",
  "DESCRIPTION_LIVE_DEV_MULTIBROWSER": "tačno da omogući eksperimentalni pregled uživo",
  "DESCRIPTION_USE_PREFERED_ONLY": "istina da pokrene provajdere navedene u linting.preferiraju samo",
  "DESCRIPTION_MAX_CODE_HINTS": "Maksimalni saveti koda prikazani odjednom",
  "DESCRIPTION_PATH": "Podešavanja specifične putanje",
  "DESCRIPTION_PROXY": "URL proki servera koji se koristi za instalaciju proširenja",
  "DESCRIPTION_SCROLL_PAST_END": "istina da omogući pomeranje iza kraja dokumenta",
  "DESCRIPTION_SHOW_CODE_HINTS": "false da biste onemogućili sve savete koda",
  "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING": "Održava treptajući kursor vidljivim kada imate izbor teksta",
  "DESCRIPTION_SHOW_LINE_NUMBERS": "istina da pokaže brojeve linija u „oluka“ sa leve strane koda",
  "DESCRIPTION_SMART_INDENT": "Automatski uvlači prilikom kreiranja novog bloka",
  "DESCRIPTION_SOFT_TABS": "lažno da isključite ponašanje mekih kartica",
  "DESCRIPTION_SORT_DIRECTORIES_FIRST": "tačno da prvo sortirate direktorijume u stablu projekta",
  "DESCRIPTION_SPACE_UNITS": "Broj prostora koji se koriste za uvlačenje zasnovano na prostoru",
  "DESCRIPTION_STATIC_SERVER_PORT": "Broj porta koji ugrađeni server treba da koristi za Live Previev",
  "DESCRIPTION_STYLE_ACTIVE_LINE": "tačno da istakne boju pozadine linije na kojoj je kursor uključen",
  "DESCRIPTION_TAB_SIZE": "Broj prostora za prikaz za kartice",
  "DESCRIPTION_USE_TAB_CHAR": "tačno da koristite kartice umesto razmaka",
  "DESCRIPTION_UPPERCASE_COLORS": "istina za generisanje velikih hek boja u Inline Color Editoru",
  "DESCRIPTION_WORD_WRAP": "Vrap linije koje prelaze širinu prikaza",
  "DESCRIPTION_SEARCH_AUTOHIDE": "Zatvorite pretragu čim je urednik fokusiran",
  "DESCRIPTION_DETECTED_EXCLUSIONS": "Spisak datoteka za koje je otkriveno da uzrokuje da Tigra ponestane kontrole",
  "DESCRIPTION_INFERENCE_TIMEOUT": "Količina vremena nakon kojeg će Tern isteći vreme kada pokušavate da razumete datoteke",
  "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR": "istina da pokaže greške u statusnoj traci",
  "DESCRIPTION_QUICK_VIEW_ENABLED": "istina da omogući Kuick Viev",
  "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW": "istina za prikaz pregleda slika za URL-ove koji nedostaju ekstenzije",
  "DESCRIPTION_THEME": "Izaberite temu {APP_NAME}",
  "DESCRIPTION_USE_THEME_SCROLLBARS": "istina da dozvoli prilagođene trake za pomeranje",
  "DESCRIPTION_LINTING_COLLAPSED": "istina da se sruši oblaganje panel",
  "DESCRIPTION_FONT_FAMILY": "Promena porodice fontova",
  "DESCRIPTION_FONT_SIZE": "Promenite veličinu fonta; npr. 13pk",
  "DESCRIPTION_FIND_IN_FILES_NODE": "tačno da omogući pretragu zasnovanu",
  "DESCRIPTION_FIND_IN_FILES_INSTANT": "istina da omogući trenutnu pretragu",
  "DESCRIPTION_FONT_SMOOTHING": "Samo za Mac: „subpiksel-antialiased“ kako bi se omogućilo antialiasing pod-piksela ili „antialiased“ za antialiasing sive skale",
  "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW": "false da biste onemogućili datoteku postavki otvaranja u podeljenom prikazu",
  "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE": "false da biste otvorili datoteku korisničkih postavki u levo/gornjem oknu",
  "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED": "istina za kolaps panela nakon što se poslednja datoteka iz okna zatvori preko dugmeta za zatvaranje zaglavlja okna",
  "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS": "Uključite kada da prikažete dugmad za zatvaranje i flip-viev na zaglavlju.",
  "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT": "/*\n * Ovo je datoteka samo za čitanje sa podržanim podešavanjima\n * od {APP_NAME}.\n * Koristite ovu datoteku kao referencu da biste izmenili svoje postavke\n * fajl „brackets.json“ otvoren u drugom oknu.\n * Za više informacija o tome kako da koristite postavke unutar\n * {APP_NAME}, pogledajte veb stranicu na https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences\n */",
  "DEFAULT_PREFERENCES_JSON_DEFAULT": "Podrazumevano",
  "DESCRIPTION_PURE_CODING_SURFACE": "tačno da omogućite režim samo kod i sakrijete sve ostale elemente korisničkog interfejsa u {APP_NAME}",
  "DESCRIPTION_INDENT_LINE_COMMENT": "tačno da omogući uvlačenje linijskih komentara",
  "DESCRIPTION_RECENT_FILES_NAV": "Omogućite/onemogućite navigaciju u nedavnim datotekama",
  "DESCRIPTION_LIVEDEV_WEBSOCKET_PORT": "Port na kojem VebSocket Server radi za Live Previev",
  "DESCRIPTION_LIVE_DEV_HIGHLIGHT_SETTINGS": "Podešavanja isticanja uživo Previev",
  "DESCRIPTION_LIVEDEV_ENABLE_REVERSE_INSPECT": "false da biste onemogućili pregled uživo obrnuti pregled",
  "DOWNLOAD_FAILED": "Preuzimanje nije uspelo.",
  "DOWNLOAD_COMPLETE": "Dovnload kompletan!",
  "UPDATE_SUCCESSFUL": "Update uspešno!",
  "UPDATE_FAILED": "Update nije uspelo!",
  "VALIDATION_FAILED": "Validacija nije uspela!",
  "INITIALISATION_FAILED": "Inicijalizacija nije uspela!",
  "CLEANUP_FAILED": "Čišćenje nije uspelo!",
  "WARNING_TYPE": "Upozorenje!",
  "CLICK_RESTART_TO_UPDATE": "Kliknite na Restart da biste ažurirali zagrade.",
  "UPDATE_ON_NEXT_LAUNCH": "Ažuriranje će se primeniti prilikom ponovnog pokretanja.",
  "GO_TO_SITE": "Idite na <a href = \"http://brackets.io/ „> brackets.io </a> da pokušate ponovo.",
  "INTERNET_UNAVAILABLE": "Nije dostupna internetska veza.",
  "UPDATEDIR_READ_FAILED": "Direktorijum ažuriranja nije mogao da se pročita.",
  "UPDATEDIR_CLEAN_FAILED": "Update direktorijum nije mogao da se očisti.",
  "INITIAL_DOWNLOAD": "Preuzimanje ažuriranja...",
  "RETRY_DOWNLOAD": "Preuzimanje nije uspelo. Pokušaj pokušaja... ",
  "VALIDATING_INSTALLER": "Dovnload kompletan! Validacija instalatera...",
  "CHECKSUM_DID_NOT_MATCH": "Checksum se nije podudarao.",
  "INSTALLER_NOT_FOUND": "Instalater nije pronađen.",
  "DOWNLOAD_ERROR": "Došlo je do greške prilikom preuzimanja.",
  "NETWORK_SLOW_OR_DISCONNECTED": "Mreža je isključena ili prespora.",
  "RESTART_BUTTON": "Restart",
  "LATER_BUTTON": "Kasnije",
  "DESCRIPTION_AUTO_UPDATE": "Omogući/onemogućite zagrade Automatsko ažuriranje",
  "AUTOUPDATE_ERROR": "Greška!",
  "AUTOUPDATE_IN_PROGRESS": "Ažuriranje je već u toku.",
  "NUMBER_WITH_PERCENTAGE": "{0}%",
  "CMD_FIND_RELATED_FILES": "Find Related Files",
  "PHP_VERSION_INVALID": "Greška raščlanjivanja PHP verzije Molimo proverite izlaz komande „php —version“.",
  "PHP_UNSUPPORTED_VERSION": "Instalirajte PHP7 runtime za omogućavanje alata vezanih za PHP, kao što su saveti kod, saveti parametara, skok na definiciju i još mnogo toga. Pronađena verzija: {0}",
  "PHP_EXECUTABLE_NOT_FOUND": "PHP runtime nije pronađen. Instalirajte PHP7 runtime i ažurirajte „EkecuitablePath“ u PHP Preferences na odgovarajući način. Ovo omogućava alate povezane sa PHP-om, kao što su saveti koda, saveti parametara, skok na definiciju i još mnogo toga.",
  "PHP_PROCESS_SPAWN_ERROR": "Kod greške {0} naišao prilikom pokretanja PHP procesa.",
  "PHP_SERVER_ERROR_TITLE": "Greška",
  "PHP_SERVER_MEMORY_LIMIT_INVALID": "Ograničenje memorije koje ste naveli je nevažeći. Pregledajte PHP postavke da biste postavili tačnu vrednost.",
  "DESCRIPTION_PHP_TOOLING_CONFIGURATION": "PHP Tooling podrazumevana podešavanja konfiguracije",
  "OPEN_PREFERENNCES": "Otvori Preferences",
  "LANGUAGE_TOOLS_PREFERENCES": "Postavke za jezičke alate",
  "FIND_ALL_REFERENCES": "Pronađi sve reference",
  "REFERENCES_IN_FILES": "reference",
  "REFERENCE_IN_FILES": "referenca",
  "REFERENCES_NO_RESULTS": "Nema dostupnih referenci za trenutnu poziciju kursora",
  "CMD_FIND_DOCUMENT_SYMBOLS": "Pronađite simbole dokumenta",
  "CMD_FIND_PROJECT_SYMBOLS": "Pronađite simbole projekta",
  "REMOTE_DEBUGGING_ENABLED": "Daljinsko otklanjanje grešaka omogućeno na localhost-u:",
  "REMOTE_DEBUGGING_PORT_INVALID": "Ne mogu omogućiti daljinsko otklanjanje grešaka na portu {0}. Brojevi portova treba da budu između {1} i {2}.",
  "DESCRIPTION_EXTERNAL_APPLICATION_ASSOCIATE": "Mapiranje za ekstenziju datoteke na spoljne aplikacije. Sintaksa: \"<file_type>„: „<Default|ApplicationName|ApplicationPath>“, Koristite „podrazumevano“ da biste otvorili datoteke u sistemskoj podrazumevanoj aplikaciji za tip datoteke.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_TITLE": "Otvorite grafičke datoteke u spoljnim urednicima.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_MSG": "Vaša trenutna fascikla ima tipove grafičkih datoteka koje {APP_NAME} ne podržava. <br/>Sadamožete povezati određene tipove datoteka sa spoljnim uređivačima. Jednom povezani, možete otvoriti grafičke datoteke poput .kd, .psd, .jpg, .png, .ai, .svg u njihovim podrazumevanim aplikacijama dvostrukim klikom na datoteke u File Tree. <br/><br/>Kliknitena dugme „Ok“ da biste povezali tipove grafičkih datoteka sa njihovim podrazumevanim aplikacijama.",
  "ASSOCIATE_GRAPHICS_FILE_TO_DEFAULT_APP_CNF_MSG": "Sledeći tipovi datoteka uspešno su povezani sa podrazumevanim aplikacijama. <br/>{0} Imate mogućnost da promenite svoje preferencije o tome da li brište/dodate nove asocijacije tipa datoteka u zagradama.json tako što ćete otići u meni „Debug-> Otvori datoteku postavki“.",
  "UNSUPPORTED_BROWSER": "Brovser nije podržan",
  "UNSUPPORTED_BROWSER_OPEN_FOLDER": "Brovser ne podržava Otvori fasciklu",
  "UNSUPPORTED_BROWSER_MESSAGE_LINE1": "Molimo Vas da koristite jedan od podržanih pretraživača ispod.",
  "UNSUPPORTED_BROWSER_MESSAGE_LINE2": " Naporno radimo na tome da Phoenik bude dostupan u više pregledača. Možete zatvoriti ovaj dijalog, ali neke funkcije u Phoeniksu neće raditi u ovom pregledaču.",
  "CANNOT_PUBLISH_LARGE_PROJECT": "Ne mogu objaviti veliki projekat",
  "CANNOT_PUBLISH_LARGE_PROJECT_MESSAGE": "Feniks je i dalje u eksperimentalnoj alfa. Još nismo omogućili sinhronizaciju projekata sa većim od 500 datoteka.",
  "SHARE_WEBSITE": "Objavite i delite sajt?",
  "PUBLISH": "Objavi",
  "PUBLISH_CONSENT_MESSAGE": "Brzo pregledajte izmene i delite svoju veb lokaciju sa drugima. Feniks može da objavi ovaj sajt za vas na {0}. Objavljeni linkovi važe u trajanju od 7 dana. </br>Dali želite da objavite i delite svoju veb stranicu?",
  "PUBLISH_SYNC_IN_PROGRESS": "Sinhronizacija u toku za pregled...",
  "PUBLISH_PAGE": "Kliknite da objavite i delite ovaj sajt",
  "PUBLISH_VIEW_PAGE": "Kliknite da biste videli objavljenu stranicu",
  "MISSING_FIELDS": "Nedostaju polja",
  "PLEASE_FILL_ALL_REQUIRED": "Molimo popunite sva obavezna polja označena crvenom bojom",
  "CODE_EDITOR": "Code Editor",
  "BUILD_THE_WEB": "Izgradite veb",
  "IMPORT_PROJECT": "Uvoz Projekat",
  "GITHUB_PROJECT": "Github Projekat",
  "NEW_PROJECT_FROM_GITHUB": "Novi projekat iz Githuba",
  "GITHUB_REPO_URL": "Github Repo URL adresa:",
  "CREATE_PROJECT": "Kreirajte projekat",
  "SETTING_UP_PROJECT": "Podešavanje projekta",
  "LOCATION": "Lokacija:",
  "DOWNLOADING": "Preuzimanje...",
  "DOWNLOAD_FAILED_MESSAGE": "Uverite se da je URL za preuzimanje validan. </br>Napomena: Kako je Phoenik u alfa, privatni Repos i Github URL-ovi veći od 25 MB nisu dozvoljeni.",
  "PLEASE_SELECT_A_FOLDER": "Izaberite fasciklu...",
  "UNZIP_IN_PROGRESS": "Unzipping fajlova...",
  "UNZIP_FAILED": "Greška: Unzipping nije uspeo.",
  "CONFIRM_REPLACE_TITLE": "Potvrdi zameni",
  "KEEP_BOTH": "Zadrži oboje",
  "EXPLORE": "HTML igre",
  "BLOG": "Blog",
  "PHOENIX_DEFAULT_PROJECT": "Podrazumevani projekat",
  "PROJECT_NAME": "Naziv projekta:",
  "NEW_HTML": "Novi HTML projekat",
  "LICENSE": "Licenca:",
  "CREDITS": "Krediti:",
  "PREVIEW": "Pregled",
  "BUILD_WEBSITE": "Build Sajt",
  "VIEW_MORE": "Pogledaj više...",
  "NEW_PROJECT_NOTIFICATION": "Kliknite na ovu ikonu da<br/>biste kreirali novi projekat. </br> <a href='#' style='float:right;'>ok</a>",
  "DEFAULT_PROJECT_NOTIFICATION": "Kliknite ovde da biste otvorili <br/><b>podrazumevani projekat</b> u feniksu. </br> <a href='#' style='float:right;'>ok</a>",
  "DIRECTORY_REPLACE_MESSAGE": "Izabrana fascikla <span class='dialog-filename'>{0}</span> nije prazna. Da li ste sigurni da želite da zamenite sadržaj fascikle sa projektom?",
  "BUILD_WEBSITE_SECTION": "Build Sajt",
  "LEARN_SECTION": "Učite sa primerima",
  "WEBPAGE_HOME_PAGE": "Rasporedi početne stranice",
  "WEBPAGE_BLOG": "Blog stranica",
  "WEBPAGE_DASHBOARD": "HTML kontrolna tabla",
  "WEBPAGE_BOOTSTRAP_EXAMPLES": "Bootstrap Primeri",
  "GUIDED_FILES_SIDEBAR": "Izaberite HTML datoteku </br> <a href='#' style='float:right;'>ok</a>",
  "GUIDED_LIVE_PREVIEW": "Napravite neke promene koda i sačuvajte datoteku da biste videli pregled. </br> <a href='#' style='float:right;'>ok</a>",
  "TEST_TRANSLATE": "test"
});